IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_TOTPCJ_EG' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_TOTPCJ_EG
END

GO
CREATE PROCEDURE DBO.SPK_TOTPCJ_EG
@CODCAJA VARCHAR(4), 
@CNSFACJ VARCHAR(20) 
WITH ENCRYPTION
AS
DECLARE @TOTAL      DECIMAL(14,2)
DECLARE @TIPOEGRESO VARCHAR(10)
BEGIN
   SELECT @TIPOEGRESO= TIPOEGRESO FROM FCJ WHERE CODCAJA=@CODCAJA AND CNSFACJ = @CNSFACJ
   IF COALESCE(@TIPOEGRESO,'')=DBO.FNK_VALORVARIABLE('IDCJTECXP')
   BEGIN 
      EXEC SPK_TOTCAJA @CODCAJA, @CNSFACJ
      RETURN
   END
   ELSE
   BEGIN
      IF DBO.FNK_VALORVARIABLE('COP_VALPCJ')='SI'
      BEGIN
          SELECT @TOTAL = SUM(VALOR) FROM PCJ WHERE CODCAJA = @CODCAJA
                                              AND   CNSFACJ = @CNSFACJ
      
          UPDATE FCJD SET VALORTOTAL = @TOTAL, VALORUNITARIO = @TOTAL,
                          CANTIDAD = 1
          WHERE CODCAJA = @CODCAJA AND   CNSFACJ = @CNSFACJ
      END

      EXEC SPK_TOTCAJA @CODCAJA, @CNSFACJ
    END
END

