CREATE OR ALTER PROCEDURE DBO.SPK_GENITEMS_NOTACR 
@CNSFNOT    VARCHAR(20), 
@CLASE      VARCHAR(1), 
@USUARIO    VARCHAR(12),
@ITEM_UNICO BIT = 0
WITH ENCRYPTION 
AS
DECLARE @AUX     INT
DECLARE @REB_IND DECIMAL(14,2)
DECLARE @TOT     DECIMAL(14,2)
DECLARE @CONCEPTO      TINYINT
DECLARE @IDCONCEPTO    VARCHAR(20)
DECLARE @TIPOCONCEPTO  VARCHAR(1)
DECLARE @VALORCONCEPTO DECIMAL(19,2)
DECLARE @N_FACTURA     VARCHAR(20)
DECLARE @LIBERAHADM    SMALLINT
DECLARE @VR_TOTAL      DECIMAL(19,2)
DECLARE @VLRAREBAJAR_P DECIMAL(19,10)
DECLARE @VALORTOTAL    DECIMAL(19,2)
DECLARE @VLRDIST       DECIMAL(19,2) 
DECLARE @A             SMALLINT 
DECLARE @ITEM          SMALLINT 
DECLARE @NUMITEM       INT
DECLARE @DETGENERADOS  SMALLINT
DECLARE @TIPODTO       VARCHAR(1)
DECLARE @VLRAREBAJAR   DECIMAL(19,2)
DECLARE @PAQUETE       BIT=0
DECLARE @IDSERPAQ     VARCHAR(20)
DECLARE @DESCPAQ      VARCHAR(512)
DECLARE @NOADMISION   VARCHAR(20)
DECLARE @TIPOFAC      VARCHAR(2)
DECLARE @SALDOVK      DECIMAL(14,2) -- SALDO REAL EN CARTERA
DECLARE @CNSCXC       VARCHAR(20)
DECLARE @VR_FNOT      DECIMAL(14,2)
DECLARE @VR_DIF       DECIMAL(14,2)
DECLARE @PROCEDENCIA  VARCHAR(20)
DECLARE @MEC_FACT     VARCHAR(10)
DECLARE @COPAPROPIO  BIT=0
DECLARE @VLR_COPAGOF DECIMAL(14,2)
DECLARE @VR_NOTA_OBJ DECIMAL(19,2)
DECLARE @ITEM_UNICO_OK BIT = 0
DECLARE @NET_FTRD DECIMAL(19,2)
BEGIN
   PRINT 'CAPTURO DATOS'
   SELECT @N_FACTURA     = N_FACTURA, @CONCEPTO = CONCEPTO, @IDCONCEPTO = IDCONCEPTO, @TIPOCONCEPTO = TIPOCONCEPTO,
          @VALORCONCEPTO = VALORCONCEPTO, @LIBERAHADM = LIBERAHADM, @DETGENERADOS = DETGENERADOS,@CNSCXC=COALESCE(CNSCXC,'')
   FROM   FNOT
   WHERE  CNSFNOT = @CNSFNOT
   AND    CLASE   = @CLASE 
   
   SELECT @PROCEDENCIA=PROCEDENCIA,@COPAPROPIO=COPAPROPIO,@VLR_COPAGOF=CP_VLR_COPAGOS,@MEC_FACT=MEC_FACT
   FROM FTR WHERE  N_FACTURA=@N_FACTURA
   
   PRINT 'COMIENZO' 

   IF COALESCE(@CONCEPTO,0) = 0
   BEGIN
      RETURN
   END
   ELSE
   BEGIN
      IF @DETGENERADOS = 1
      BEGIN
         RETURN
      END
   END
   DELETE FNOTD WHERE CNSFNOT = @CNSFNOT

   --SELECT @VR_TOTAL = CASE WHEN DBO.FNK_VALORVARIABLE('FACTURAPOS_ACTIVA')='SI' THEN  VR_TOTAL ELSE VALORSERVICIOS END ,@PAQUETE=COALESCE(PAQUETE,0),@NOADMISION=NOREFERENCIA,@TIPOFAC=FTR.TIPOFAC 
   --FROM FTR WHERE N_FACTURA   = @N_FACTURA

   SELECT @VR_TOTAL =  VR_TOTAL  ,@PAQUETE=COALESCE(PAQUETE,0),@NOADMISION=NOREFERENCIA,@TIPOFAC=FTR.TIPOFAC 
   FROM FTR WHERE N_FACTURA   = @N_FACTURA

   SELECT  @TIPODTO = @TIPOCONCEPTO, @VLRAREBAJAR = @VALORCONCEPTO
   
   SELECT @AUX = COALESCE(COUNT(*),0), @TOT = SUM(FTRD.VR_TOTAL)
   FROM   FTRD 
   WHERE  N_FACTURA   = @N_FACTURA  
   
   SELECT @SALDOVK=SALDO FROM  VWK_FTRNDCR WHERE N_FACTURA=@N_FACTURA AND COALESCE(CNSCXC,'')=@CNSCXC

   IF @VR_TOTAL>@SALDOVK
   BEGIN
      IF @TIPODTO='V'
      BEGIN
	  print 'entre aqui vr_total'
         --SELECT @VR_TOTAL=@SALDOVK
      END
      ELSE
      BEGIN
         SELECT @VLRAREBAJAR_P=(((@SALDOVK*(@VLRAREBAJAR/100))*100)/@VR_TOTAL)

      END
   END
   
   IF @TIPODTO  = 'V'
   BEGIN
      PRINT 'INGRESO POR VALOR'
      PRINT  '@VLRAREBAJAR ='+STR(@VLRAREBAJAR)
      PRINT  '@VR_TOTAL ='+STR(@VR_TOTAL)
      SELECT @VLRAREBAJAR_P =CONVERT(DECIMAL(19,10),((@VLRAREBAJAR * 100.00)/@VR_TOTAL)/100)
      SELECT @VR_FNOT=VALORCONCEPTO FROM FNOT WHERE CNSFNOT=@CNSFNOT
   END
   ELSE
   BEGIN
      SELECT @VLRAREBAJAR_P = @VLRAREBAJAR/100
   END 
   PRINT '@VLRAREBAJAR_P='+CAST(@VLRAREBAJAR_P AS VARCHAR(20))

   IF @TIPODTO = 'V'
      SET @VR_NOTA_OBJ = @VLRAREBAJAR
   ELSE
      SET @VR_NOTA_OBJ = ROUND(@VR_TOTAL * @VLRAREBAJAR_P, 2)

   IF DBO.FNK_VALORVARIABLE('IXCOUNTRY') <> 'PERU' AND @ITEM_UNICO = 1 AND COALESCE(@VR_NOTA_OBJ, 0) > 0
   BEGIN
      SELECT @NET_FTRD = MAX(
         COALESCE(VLR_SERVICI, 0) - CASE WHEN COALESCE(VLR_COPAGOS, 0) > 0 AND COALESCE(@COPAPROPIO, 0) = 0 THEN VLR_COPAGOS ELSE 0 END)
      FROM FTRD
      WHERE N_FACTURA = @N_FACTURA
         AND (COALESCE(VLR_SERVICI, 0) - CASE WHEN COALESCE(VLR_COPAGOS, 0) > 0 AND COALESCE(@COPAPROPIO, 0) = 0 THEN VLR_COPAGOS ELSE 0 END) >= @VR_NOTA_OBJ

      IF COALESCE(@NET_FTRD, 0) >= @VR_NOTA_OBJ
         SET @ITEM_UNICO_OK = 1
   END

   IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND (@PAQUETE=1 OR @TIPOFAC='M')
   BEGIN
      PRINT 'Ingreso por paquete de peru'
      IF @PAQUETE=1
      BEGIN
         SELECT @IDSERPAQ=HADM.IDSERVICIOPAQUETE,@DESCPAQ=SER.DESCSERVICIO 
         FROM HADM INNER JOIN SER ON HADM.IDSERVICIOPAQUETE=SER.IDSERVICIO
         WHERE NOADMISION=@NOADMISION
      END
      ELSE
      BEGIN
         SELECT @DESCPAQ=dbo.FNK_LIMPIATEXTO(CASE WHEN COALESCE(OBSERVACION,'')<>'' 
               THEN  OBSERVACION ELSE PLN.DESCPLAN END,'0-9 A-Z '),
               @IDSERPAQ=dbo.FNK_LIMPIATEXTO(COALESCE(@IDSERPAQ,FTR.IDPLAN),'0-9 A-Z ')
         FROM FTR INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN   
         WHERE N_FACTURA=@N_FACTURA
      END
      PRINT 'INGRESO POR PAQUETES DETALLES'
      IF COALESCE(@IDSERPAQ,'')<>''
      BEGIN
         INSERT INTO FNOTD( CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
                            VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA,CCOSTO,IDAREA,PREFIJO,CUENTA)
         SELECT @CNSFNOT, 'C', 1, 'S', @IDSERPAQ, @DESCPAQ, 1, VR_TOTAL,VR_TOTAL, '01', @USUARIO, NULL, 1, PIVA, VIVA, @N_FACTURA,NULL,NULL,NULL,NULL
         FROM   FTR 
         WHERE  N_FACTURA   = @N_FACTURA  
      END
      IF @PROCEDENCIA IN ('MAD','CMV') AND @MEC_FACT IN ('PPS','MER')
      BEGIN
         PRINT 'NC MAD/CMV PPS/MER: total neto desde FTR.VR_TOTAL (copagos en PAQUETE=1)'
         INSERT INTO FNOTD( CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
                            VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA,CCOSTO,IDAREA,PREFIJO,CUENTA)
         SELECT TOP 1 @CNSFNOT, 'C', D.N_CUOTA, 'S',
            LEFT(COALESCE(D.REFERENCIA,D.PREFIJO,SUBSTRING(D.ANEXO,1,20)),20), LEFT(D.ANEXO,512), 1,
            ROUND(F.VR_TOTAL * @VLRAREBAJAR_P, 2),
            ROUND(F.VR_TOTAL * @VLRAREBAJAR_P, 2),
            '01', @USUARIO, NULL, D.N_CUOTA, D.PIVA,
            ROUND(COALESCE(F.VIVA,0) * @VLRAREBAJAR_P, 2),
            @N_FACTURA, D.CCOSTO, D.AREAPRESTACION, D.PREFIJO, D.CUENTACR
         FROM FTR F
         INNER JOIN FTRD D ON D.N_FACTURA = F.N_FACTURA
         WHERE F.N_FACTURA = @N_FACTURA
            AND COALESCE(D.PAQUETE,0) = 0
         ORDER BY CASE WHEN D.PROCEDENCIA = 'CI' THEN 0 ELSE 1 END, D.N_CUOTA
      END
      ELSE
      BEGIN
         PRINT 'Busco en los Detalles'
		   INSERT INTO FNOTD( CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
	 						 VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA,CCOSTO,IDAREA,PREFIJO,CUENTA)
	 	   SELECT @CNSFNOT, 'C', N_CUOTA, 'S', LEFT(COALESCE(REFERENCIA,PREFIJO,SUBSTRING(ANEXO,1,20)),20),left (ANEXO,512), 1,
     --    ((COALESCE(VLR_SERVICI,0)-(CASE WHEN  (DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' OR DBO.FNK_VALORVARIABLE('FACTURAPOS_ACTIVA')='SI' )  AND COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) * (@VLRAREBAJAR_P)), 
	 		 --ROUND((COALESCE(VLR_SERVICI,0)-(CASE WHEN  (DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' OR DBO.FNK_VALORVARIABLE('FACTURAPOS_ACTIVA')='SI' ) AND COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) *(@VLRAREBAJAR_P),2),
          ((COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) * (@VLRAREBAJAR_P)), 
	 		 ROUND((COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) *(@VLRAREBAJAR_P),2),
          '01', @USUARIO, NULL, N_CUOTA, PIVA, CASE WHEN DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP' THEN FTRD.VALOR_IGV_UNITARIO ELSE VIVA END, @N_FACTURA,
          CCOSTO,AREAPRESTACION,PREFIJO,CUENTACR
	  	   FROM   FTRD 
		   WHERE  N_FACTURA   = @N_FACTURA
		   AND ROUND((COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END))*(@VLRAREBAJAR_P),2)<>0
         AND COALESCE(PAQUETE,0) IN(0,3)
		   AND (COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END))>0
      END
   END
   ELSE
   BEGIN
      IF @ITEM_UNICO_OK = 1
      BEGIN
         PRINT 'FNOTD item unico: nota=' + CAST(@VR_NOTA_OBJ AS VARCHAR(20)) + ' en un servicio FTRD'
         INSERT INTO FNOTD( CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
                            VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA, CCOSTO, IDAREA, PREFIJO, CUENTA)
         SELECT TOP 1
            @CNSFNOT, 'C', 1, 'S',
            LEFT(COALESCE(REFERENCIA, PREFIJO, SUBSTRING(ANEXO, 1, 20)), 20),
            LEFT(ANEXO, 512), 1,
            @VR_NOTA_OBJ, @VR_NOTA_OBJ,
            '01', @USUARIO, NULL, N_CUOTA, PIVA,
            CASE
               WHEN @TIPODTO = 'V' THEN ROUND(COALESCE(VIVA, 0) * (@VR_NOTA_OBJ / NULLIF(
                  COALESCE(VLR_SERVICI, 0) - CASE WHEN COALESCE(VLR_COPAGOS, 0) > 0 AND COALESCE(@COPAPROPIO, 0) = 0 THEN VLR_COPAGOS ELSE 0 END, 0)), 2)
               ELSE ROUND(COALESCE(VIVA, 0) * @VLRAREBAJAR_P, 2)
            END,
            @N_FACTURA, CCOSTO, AREAPRESTACION, PREFIJO, CUENTACR
         FROM FTRD
         WHERE N_FACTURA = @N_FACTURA
            AND (COALESCE(VLR_SERVICI, 0) - CASE WHEN COALESCE(VLR_COPAGOS, 0) > 0 AND COALESCE(@COPAPROPIO, 0) = 0 THEN VLR_COPAGOS ELSE 0 END) >= @VR_NOTA_OBJ
         ORDER BY (COALESCE(VLR_SERVICI, 0) - CASE WHEN COALESCE(VLR_COPAGOS, 0) > 0 AND COALESCE(@COPAPROPIO, 0) = 0 THEN VLR_COPAGOS ELSE 0 END) DESC,
            N_CUOTA
      END
      ELSE IF @PAQUETE=1
      BEGIN
         PRINT 'INGRESO A PAQUETES'
         SELECT @IDSERPAQ=HADM.IDSERVICIOPAQUETE,@DESCPAQ=SER.DESCSERVICIO 
         FROM HADM INNER JOIN SER ON HADM.IDSERVICIOPAQUETE=SER.IDSERVICIO
         WHERE NOADMISION=@NOADMISION

         PRINT 'INGRESO LOS ITEMS  DEL PAQUETE Y LOS QUE ESTAN POR FUERA'

		   INSERT INTO FNOTD( CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
	 						 VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA,CCOSTO,IDAREA,PREFIJO,CUENTA)
	 	   SELECT @CNSFNOT, 'C', N_CUOTA, 'S', LEFT(COALESCE(REFERENCIA,PREFIJO,SUBSTRING(ANEXO,1,20)),20),left (ANEXO,512), 1,
          -- ROUND(((COALESCE(VLR_SERVICI,0)-(CASE WHEN (DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' OR DBO.FNK_VALORVARIABLE('FACTURAPOS_ACTIVA')='SI' ) AND COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) * (@VLRAREBAJAR_P)),2), 
	 		 --ROUND((COALESCE(VLR_SERVICI,0)-(CASE WHEN (DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' OR DBO.FNK_VALORVARIABLE('FACTURAPOS_ACTIVA')='SI' )  AND COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) *(@VLRAREBAJAR_P),2),
            ROUND(((COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) * (@VLRAREBAJAR_P)),2), 
	 		   ROUND((COALESCE(VLR_SERVICI,0)-(CASE WHEN  COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) *(@VLRAREBAJAR_P),2),
          '01', @USUARIO, NULL, N_CUOTA, PIVA, VIVA, @N_FACTURA,CCOSTO,AREAPRESTACION,PREFIJO,CUENTACR
	  	   FROM   FTRD 
		   WHERE  N_FACTURA   = @N_FACTURA
         AND COALESCE(PAQUETE,0) IN(0,1,3) 
		   AND ROUND((COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END))*(@VLRAREBAJAR_P),2)<>0
		   AND (COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END))>0

      END
	   ELSE
	   BEGIN
         PRINT 'ACA LO HAGO' 
		   INSERT INTO FNOTD( CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
	 						 VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA,CCOSTO,IDAREA,PREFIJO,CUENTA)
	 	   SELECT @CNSFNOT, 'C', N_CUOTA, 'S', LEFT(COALESCE(REFERENCIA,PREFIJO,SUBSTRING(ANEXO,1,20)),20),left (ANEXO,512), 1,
     --    ROUND(((COALESCE(VLR_SERVICI,0)-(CASE WHEN (DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' OR DBO.FNK_VALORVARIABLE('FACTURAPOS_ACTIVA')='SI' ) AND COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) * (@VLRAREBAJAR_P)),2), 
	 		 --ROUND((COALESCE(VLR_SERVICI,0)-(CASE WHEN (DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' OR DBO.FNK_VALORVARIABLE('FACTURAPOS_ACTIVA')='SI' )  AND COALESCE(VLR_COPAGOS,0)>0 THEN VLR_COPAGOS ELSE 0 END)) *(@VLRAREBAJAR_P),2),
           ROUND(((COALESCE(VLR_SERVICI,0)-(CASE WHEN  COALESCE(VLR_COPAGOS,0)>0 AND COALESCE(@COPAPROPIO,0)=0 THEN VLR_COPAGOS ELSE 0 END)) * (@VLRAREBAJAR_P)),2), 
	 		  ROUND((COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 AND COALESCE(@COPAPROPIO,0)=0 THEN VLR_COPAGOS ELSE 0 END)) *(@VLRAREBAJAR_P),2),
          '01', @USUARIO, NULL, N_CUOTA, PIVA, VIVA, @N_FACTURA,
          CCOSTO,AREAPRESTACION,PREFIJO,CUENTACR
	  	   FROM   FTRD 
		   WHERE  N_FACTURA   = @N_FACTURA
		   AND ROUND((COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 AND COALESCE(@COPAPROPIO,0)=0 THEN VLR_COPAGOS ELSE 0 END))*(@VLRAREBAJAR_P),2)<>0
		   AND (COALESCE(VLR_SERVICI,0)-(CASE WHEN COALESCE(VLR_COPAGOS,0)>0 AND COALESCE(@COPAPROPIO,0)=0 THEN VLR_COPAGOS ELSE 0 END))>0
         IF @PROCEDENCIA='FINANCIERO' AND COALESCE(@COPAPROPIO,0)=1
         BEGIN
            PRINT 'INGRESO '+STR(@VLR_COPAGOF)
            IF (SELECT COUNT(*) FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND VR_UNITARIO>=@VLR_COPAGOF)=1
            BEGIN
               PRINT 'ENCONTRE UNO'
               DECLARE @NOITEM INT
               DECLARE @VR_ITEM DECIMAL(19,2)
               SELECT TOP 1 @NOITEM=ITEM, @VR_ITEM=VR_TOTAL FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND VR_UNITARIO>=@VLR_COPAGOF
               IF @VR_ITEM >= @VLR_COPAGOF
               BEGIN
                  UPDATE FNOTD SET VR_UNITARIO=VR_UNITARIO-@VLR_COPAGOF,VR_TOTAL=VR_TOTAL-@VLR_COPAGOF WHERE CNSFNOT=@CNSFNOT AND ITEM=@NOITEM
               END
               ELSE
               BEGIN
                  RAISERROR(N'No es posible descontar el copago propio: el valor del ?tem quedar?a negativo.', 16, 1)
                  RETURN
               END
            END
         END
	   END
   END

   PRINT 'DESPUES DE LOS DETALLE SIN NADA...'
   
   SELECT @VR_TOTAL = SUM(VR_TOTAL) FROM FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
   IF COALESCE(@VR_FNOT,0) >0 
   BEGIN
      IF (@VR_TOTAL-@VR_FNOT)<> 0
      BEGIN
         SELECT @VR_DIF=(@VR_TOTAL-@VR_FNOT)
         DECLARE @MAXITEM INT
         DECLARE @VR_MAXITEM DECIMAL(19,2)
         DECLARE @AJUSTE_PEND DECIMAL(19,2)
         IF @VR_DIF<0
         BEGIN
            SELECT @MAXITEM=MAX(ITEM) FROM FNOTD WHERE CNSFNOT=@CNSFNOT
            UPDATE FNOTD SET VR_TOTAL=VR_TOTAL+ABS(@VR_DIF),VR_UNITARIO=VR_UNITARIO+ABS(@VR_DIF) WHERE CNSFNOT=@CNSFNOT AND ITEM=@MAXITEM
         END
         ELSE
         BEGIN
            SELECT @AJUSTE_PEND=ABS(@VR_DIF)
            WHILE @AJUSTE_PEND > 0
            BEGIN
               SET @MAXITEM = NULL
               SET @VR_MAXITEM = NULL
               SELECT TOP 1 @MAXITEM=ITEM, @VR_MAXITEM=VR_TOTAL
               FROM FNOTD
               WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND VR_TOTAL>0
               ORDER BY ITEM DESC

               IF @MAXITEM IS NULL
               BEGIN
                  RAISERROR(N'No es posible ajustar la nota cr?dito: no hay ?tems con saldo para absorber la diferencia.', 16, 1)
                  RETURN
               END

               IF @VR_MAXITEM >= @AJUSTE_PEND
               BEGIN
                  UPDATE FNOTD SET VR_TOTAL=VR_TOTAL-@AJUSTE_PEND, VR_UNITARIO=VR_UNITARIO-@AJUSTE_PEND
                  WHERE CNSFNOT=@CNSFNOT AND ITEM=@MAXITEM
                  SET @AJUSTE_PEND = 0
               END
               ELSE
               BEGIN
                  UPDATE FNOTD SET VR_TOTAL=0, VR_UNITARIO=0
                  WHERE CNSFNOT=@CNSFNOT AND ITEM=@MAXITEM
                  SET @AJUSTE_PEND = @AJUSTE_PEND - @VR_MAXITEM
               END
            END
            DELETE FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND VR_TOTAL=0 AND VR_UNITARIO=0
         END
      END
   END
   SELECT @VR_TOTAL = SUM(VR_TOTAL) FROM FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
   UPDATE FNOT SET VR_TOTAL = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN ROUND(@VR_TOTAL,2) ELSE @VR_TOTAL END WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE

   IF @TIPODTO  = 'V'
   BEGIN
      SELECT @VALORTOTAL = SUM(FNOTD.VR_TOTAL)
      FROM   FNOTD
      WHERE  CNSFNOT = @CNSFNOT AND CLASE = @CLASE
      IF @VLRAREBAJAR <> @VALORTOTAL
      BEGIN
         PRINT 'ERROR EN VALORES @VALORTOTAL='+CAST(@VALORTOTAL AS VARCHAR(20))+'--@VLRAREBAJAR='+CAST(@VLRAREBAJAR AS VARCHAR(20))
      END       
   END  
   IF EXISTS(SELECT 1 FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND (VR_TOTAL<0 OR VR_UNITARIO<0))
   BEGIN
      RAISERROR(N'Se detectaron ?tems con valor negativo al generar la nota cr?dito.', 16, 1)
      RETURN
   END
   SELECT @VR_TOTAL = SUM(VR_TOTAL) FROM FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
   UPDATE FNOT SET VR_TOTAL = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN ROUND(@VR_TOTAL,2) ELSE @VR_TOTAL END,DETGENERADOS = 1 WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
   IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND PROCEDENCIA='FACTURA' AND COALESCE(IDCONCEPTO,'')='')
   BEGIN
      UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE') WHERE CNSFNOT=@CNSFNOT AND PROCEDENCIA='FACTURA' AND COALESCE(IDCONCEPTO,'')=''
   END
END

