CREATE OR ALTER  PROCEDURE DBO.SPQ_DISTRIHPRED_SOAT @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
SET NOCOUNT ON

DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100)
DECLARE @USUARIO VARCHAR(12), @NOADMISION VARCHAR(20), @CNSHACTRAN VARCHAR(20),@ADRESS BIT
DECLARE @IDTERCEROCA_DESTINO VARCHAR(20), @IDPLAN_DESTINO VARCHAR(6)
DECLARE @TOPE DECIMAL(14,2), @TOPE1 DECIMAL(14,2),@VLREXTERNO DECIMAL(14,2),@DIFERENCIA DECIMAL(14,2),@ACUMLA DECIMAL(14,2),@TOPE2 DECIMAL(14,2)
DECLARE @VLRGASTADO_ANT DECIMAL(14,2), @CONSUMIDO_PREVIO DECIMAL(14,2), @TOPE1_ORIG DECIMAL(14,2), @TOPE2_ORIG DECIMAL(14,2)
DECLARE @FACT_ASE DECIMAL(14,2), @FACT_ADRES DECIMAL(14,2), @AB_ADRES DECIMAL(14,2), @AB_ASE DECIMAL(14,2)
DECLARE @DISP_ASE DECIMAL(14,2), @DISP_ADRES DECIMAL(14,2)
DECLARE @ITEMS_MOVIDOS INT
DECLARE @IDTERCERO_EPS VARCHAR(20), @IDPLAN_EPS VARCHAR(6)
DECLARE @IDTERCERO_ADRES VARCHAR(20), @IDPLAN_ADRES VARCHAR(6)
DECLARE @SIN_REDISTRIBUIR BIT
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
		MODELO VARCHAR(100) '$.MODELO',
		METODO VARCHAR(100) '$.METODO',
		USUARIO VARCHAR(12) '$.USUARIO',
		PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT @MODELO = MODELO, @METODO = METODO,
		   @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON

	-- =============================================
	-- CARGAR_DATOS: Obtiene topes de HACTRAN y items de HPRED
	-- =============================================
	IF @METODO = 'CARGAR_DATOS'
	BEGIN
		BEGIN TRY
			SELECT @NOADMISION = NOADMISION, @CNSHACTRAN = CNSHACTRAN,
			       @SIN_REDISTRIBUIR = SIN_REDISTRIBUIR
			FROM OPENJSON(@PARAMETROS) WITH (
				NOADMISION VARCHAR(20) '$.NOADMISION',
				CNSHACTRAN VARCHAR(20) '$.CNSHACTRAN',
				SIN_REDISTRIBUIR BIT '$.SIN_REDISTRIBUIR'
			)

			IF COALESCE(@CNSHACTRAN, '') = ''
			BEGIN
				SELECT @CNSHACTRAN = CNSHACTRAN FROM HADM WHERE NOADMISION = @NOADMISION
			END

			-- Validar que exista la admisi?n
			IF NOT EXISTS (SELECT 1 FROM HADM WHERE NOADMISION = @NOADMISION)
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'La admisi?n no existe'
			END

			IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
         SET @ADRESS = 0
         IF EXISTS(SELECT  * FROM HACTRAN LEFT JOIN TER ON HACTRAN.IDASEGURADORA=TER.IDTERCERO
                   WHERE CNSHACTRAN=@CNSHACTRAN 
                   AND  1= CASE WHEN IDASEGURADORA IS NULL OR TER.NIT=DBO.FNK_VALORVARIABLE('IDNITFONSAT') THEN 1 WHEN TOPE1 < TOPE THEN 1 ELSE 0 END)
                  
         BEGIN
            SELECT @ADRESS=1
         END
			-- Topes disponibles del evento actual: descuentan gasto externo + monto anterior.
			-- Cascada: Aseguradora, luego ADRES, luego EPS.
         SELECT @TOPE=COALESCE(TOPE,0),@TOPE1=COALESCE(TOPE1,0),@VLREXTERNO=COALESCE(VLRGASTOEXTERNO,0)
         FROM HACTRAN WHERE CNSHACTRAN=@CNSHACTRAN
         -- HACTRAND consolida el gasto de las atenciones anteriores del accidente.
         -- EXTERNO se excluye porque el encabezado lo presenta en un campo independiente.
         SELECT @VLRGASTADO_ANT = COALESCE(SUM(COALESCE(HACTRAND.VLRGASTADO,0)), 0)
         FROM HACTRAND
         WHERE HACTRAND.CNSHACTRAN = @CNSHACTRAN
           AND UPPER(LTRIM(RTRIM(COALESCE(HACTRAND.PROCEDENCIA,'')))) <> 'EXTERNO'
           AND LTRIM(RTRIM(COALESCE(HACTRAND.NOREFERENCIA,''))) <> LTRIM(RTRIM(COALESCE(@NOADMISION,'')))
         -- Un solo barrido de cargos: gasto de esta admisión + facturado/abierto por responsable
         SELECT
            @FACT_ASE = COALESCE(SUM(CASE WHEN COALESCE(HPRED.FACTURADA,0)=1 AND HPRED.GFACSOAT=1 THEN COALESCE(HPRED.CANTIDAD,0)*COALESCE(HPRED.VALOR,0) ELSE 0 END), 0),
            @FACT_ADRES = COALESCE(SUM(CASE WHEN COALESCE(HPRED.FACTURADA,0)=1 AND HPRED.GFACSOAT=2 THEN COALESCE(HPRED.CANTIDAD,0)*COALESCE(HPRED.VALOR,0) ELSE 0 END), 0),
            @AB_ADRES = COALESCE(SUM(CASE WHEN COALESCE(HPRED.FACTURADA,0)=0 AND HPRED.GFACSOAT=2 THEN COALESCE(HPRED.CANTIDAD,0)*COALESCE(HPRED.VALOR,0) ELSE 0 END), 0),
            @AB_ASE = COALESCE(SUM(CASE WHEN COALESCE(HPRED.FACTURADA,0)=0 AND HPRED.GFACSOAT=1 THEN COALESCE(HPRED.CANTIDAD,0)*COALESCE(HPRED.VALOR,0) ELSE 0 END), 0)
         FROM HPRED
         INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
         WHERE HPRE.NOADMISION = @NOADMISION
           AND COALESCE(HPRED.NOCOBRABLE, 0) = 0
         -- El monto anterior ya excluye la admision actual y el gasto externo.
         SET @TOPE1_ORIG = @TOPE1
         SET @TOPE2 = CASE WHEN @TOPE > @TOPE1_ORIG THEN @TOPE - @TOPE1_ORIG ELSE 0 END
         SET @TOPE2_ORIG = @TOPE2
         -- Cascada: (anterior + externo) al primer pagador; el resto al segundo.
         SET @CONSUMIDO_PREVIO = COALESCE(@VLREXTERNO,0) + COALESCE(@VLRGASTADO_ANT,0)
         IF @CONSUMIDO_PREVIO > 0
         BEGIN
            IF @CONSUMIDO_PREVIO <= @TOPE1_ORIG
            BEGIN
               SET @TOPE1 = @TOPE1_ORIG - @CONSUMIDO_PREVIO
            END
            ELSE
            BEGIN
               SET @DIFERENCIA = @CONSUMIDO_PREVIO - @TOPE1_ORIG
               SET @TOPE1 = 0
               IF @TOPE2 > @DIFERENCIA
                  SET @TOPE2 = @TOPE2 - @DIFERENCIA
               ELSE
                  SET @TOPE2 = 0
            END
         END
         PRINT '@TOPE1='+STR(@TOPE1)
         PRINT '@TOPE2='+STR(@TOPE2)
         PRINT '@CONSUMIDO_PREVIO='+STR(@CONSUMIDO_PREVIO)

			-- ?tems sin responsable: Aseguradora si queda tope, si no ADRES, si no EPS
			UPDATE HPRED
			SET GFACSOAT = CASE
				WHEN @TOPE1 > 0 THEN 1
				WHEN @TOPE2 > 0 THEN 2
				ELSE 3
			END
			FROM HPRED
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE HPRE.NOADMISION = @NOADMISION
			  AND COALESCE(HPRED.FACTURADA, 0) = 0
			  AND COALESCE(HPRED.NOCOBRABLE, 0) = 0
			  AND HPRED.GFACSOAT IS NULL

			SET @ITEMS_MOVIDOS = 0
			SET @DISP_ASE = CASE WHEN @TOPE1 > @FACT_ASE THEN @TOPE1 - @FACT_ASE ELSE 0 END
			SET @DISP_ADRES = CASE WHEN @TOPE2 > (@FACT_ADRES + @AB_ADRES) THEN @TOPE2 - @FACT_ADRES - @AB_ADRES ELSE 0 END

			-- Solo redistribuye si hay abiertos de Aseguradora que ya no caben.
			-- Si el usuario acaba de trasladar a ASEGURADORA (saldo puede quedar en rojo), no deshacerlo.
			IF @AB_ASE > @DISP_ASE AND COALESCE(@SIN_REDISTRIBUIR, 0) = 0
			BEGIN
				SET @IDTERCERO_ADRES = DBO.FNK_VALORVARIABLE('IDNITFONSAT')
				SET @IDPLAN_ADRES = DBO.FNK_VALORVARIABLE('IDPLANSOAT')
				SELECT @IDTERCERO_EPS = AFI.IDADMINISTRADORA, @IDPLAN_EPS = AFI.IDPLAN
				FROM HADM
				INNER JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
				WHERE HADM.NOADMISION = @NOADMISION

				;WITH ITEMS_EXC AS (
					SELECT HPRED.NOPRESTACION, HPRED.NOITEM,
					       COALESCE(HPRED.CANTIDAD,0)*COALESCE(HPRED.VALOR,0) AS VALOR,
					       SUM(COALESCE(HPRED.CANTIDAD,0)*COALESCE(HPRED.VALOR,0))
					         OVER (ORDER BY HPRE.FECHA, HPRED.NOPRESTACION, HPRED.NOITEM
					               ROWS UNBOUNDED PRECEDING) AS ACUM
					FROM HPRED
					INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
					WHERE HPRE.NOADMISION = @NOADMISION
					  AND COALESCE(HPRED.FACTURADA,0) = 0
					  AND COALESCE(HPRED.NOCOBRABLE,0) = 0
					  AND HPRED.GFACSOAT = 1
				),
				DESTINO AS (
					SELECT NOPRESTACION, NOITEM, ACUM,
					       COALESCE((SELECT MAX(ACUM) FROM ITEMS_EXC WHERE ACUM <= @DISP_ASE), 0) AS ASE_TOMADO
					FROM ITEMS_EXC
				)
				UPDATE HPRED
				SET GFACSOAT = CASE
						WHEN D.ACUM <= @DISP_ASE THEN 1
						WHEN @DISP_ADRES > 0 AND (D.ACUM - D.ASE_TOMADO) <= @DISP_ADRES THEN 2
						ELSE 3
					END,
				    IDTERCEROCA = CASE
						WHEN D.ACUM <= @DISP_ASE THEN HPRED.IDTERCEROCA
						WHEN @DISP_ADRES > 0 AND (D.ACUM - D.ASE_TOMADO) <= @DISP_ADRES THEN @IDTERCERO_ADRES
						ELSE @IDTERCERO_EPS
					END,
				    IDPLAN = CASE
						WHEN D.ACUM <= @DISP_ASE THEN HPRED.IDPLAN
						WHEN @DISP_ADRES > 0 AND (D.ACUM - D.ASE_TOMADO) <= @DISP_ADRES THEN @IDPLAN_ADRES
						ELSE @IDPLAN_EPS
					END
				FROM HPRED
				INNER JOIN DESTINO D ON D.NOPRESTACION = HPRED.NOPRESTACION AND D.NOITEM = HPRED.NOITEM
				WHERE D.ACUM > @DISP_ASE

				SET @ITEMS_MOVIDOS = @@ROWCOUNT
			END

			-- Recordset 0: OK
			SELECT 'OK' OK, @ADRESS ADRESS, @ITEMS_MOVIDOS ITEMS_MOVIDOS

			-- Recordset 1: Topes de pantalla = tope configurado (no el saldo restante)
			SELECT 
				 @TOPE1_ORIG AS TOPE_ASEGURADORA,
				 @TOPE2_ORIG AS TOPE_ADRES,
				0 AS TOPE_ARL,
				0 AS TOPE_EPS,
				COALESCE(HACTRAN.TOPE, 0) AS TOPE_TOTAL,
				COALESCE(@VLRGASTADO_ANT, 0) AS VLRGASTADO,
				CASE WHEN  COALESCE(HACTRAN.VLRFALTA, 0)-COALESCE(HACTRAN.VLRGASTOEXTERNO,0)<=0 THEN 0 ELSE COALESCE(HACTRAN.VLRFALTA, 0)-COALESCE(HACTRAN.VLRGASTOEXTERNO,0) END  AS VLRFALTA,
        COALESCE(HACTRAN.VLRGASTOEXTERNO,0)AS GASTOEXTERNO,
				HADM.ARLRELA,
				HADM.IDTERCERO,
				TER.RAZONSOCIAL,
				HADM.IDPLAN,
				AFI.IDADMINISTRADORA,
				COALESCE(HADM.CERRADA, 0) AS CERRADA,
				CASE 
					WHEN TER1.NIT = DBO.FNK_VALORVARIABLE('IDNITFONSAT') OR COALESCE(HACTRAN.IDASEGURADORA,'')='' OR @TOPE2>0
					THEN 0  -- No mostrar ADRES
					ELSE 1  -- Mostrar ADRES
				END AS MOSTRAR_ADRES,
            HADM.FECHA,HADM.FECHAALTAMED
			FROM HADM INNER JOIN HACTRAN ON HACTRAN.CNSHACTRAN = HADM.CNSHACTRAN
         LEFT JOIN TER TER1 ON HACTRAN.IDASEGURADORA=TER1.IDTERCERO
			LEFT JOIN TER ON TER.IDTERCERO = HADM.IDTERCERO
			LEFT JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
			WHERE HADM.NOADMISION = @NOADMISION

			-- Recordset 2: consumido por responsable (agregado; no se env?an todos los ?tems)
			SELECT
				HPRED.GFACSOAT,
				SUM(COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)) AS VLRSUBTOTAL,
				COUNT(*) AS CANTIDAD
			FROM HPRED
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE HPRE.NOADMISION = @NOADMISION
			  AND COALESCE(HPRED.NOCOBRABLE, 0) = 0
			GROUP BY HPRED.GFACSOAT

			-- Recordset 3: Nombres de responsables de pago

      SELECT 1 AS GFACSOAT, TER.IDTERCERO,TER.NIT,TER.RAZONSOCIAL AS NOMBRE
			FROM HADM
			INNER JOIN HACTRAN ON HACTRAN.CNSHACTRAN = HADM.CNSHACTRAN
			INNER JOIN TER ON HACTRAN.IDASEGURADORA = TER.IDTERCERO
			WHERE HADM.NOADMISION = @NOADMISION
         UNION ALL
         SELECT CASE WHEN @ADRESS=1 AND  @TOPE1 = @TOPE THEN 1 ELSE 2 END AS GFACSOAT, TER.IDTERCERO,TER.NIT,TER.RAZONSOCIAL
         FROM TER 
         WHERE TER.IDTERCERO= DBO.FNK_VALORVARIABLE('IDNITFONSAT') 
         UNION ALL
         SELECT  3 AS GFACSOAT, TER.IDTERCERO,TER.NIT,TER.RAZONSOCIAL
			   FROM HADM INNER JOIN HACTRAN ON HACTRAN.CNSHACTRAN = HADM.CNSHACTRAN
               INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO
               INNER JOIN TER ON AFI.IDADMINISTRADORA=TER.IDTERCERO
         WHERE HADM.NOADMISION = @NOADMISION
         UNION ALL
         SELECT  4 AS GFACSOAT, TER.IDTERCERO,TER.NIT,TER.RAZONSOCIAL
			FROM HADM
			LEFT JOIN HACTRAN ON HACTRAN.CNSHACTRAN = HADM.CNSHACTRAN
         LEFT JOIN TER ON HADM.IDTERECEROARL=TER.IDTERCERO
         WHERE HADM.NOADMISION = @NOADMISION
         AND COALESCE(ARLRELA,0)=1

		 -- Devuelve terceros ya facturados.
		  -- Devuelve terceros ya facturados por responsable (GFACSOAT),
		 -- validando solo por NOADMISION y cruce FTR.N_FACTURA = HPRED.N_FACTURA.
		 ;WITH FACTURAS_ADM AS (
			SELECT
				COALESCE(HPRED.GFACSOAT, 1) AS GFACSOAT,
				HPRED.N_FACTURA,
				FTR.IDTERCERO AS IDTERCERO_FTR,
				FTR.IDPLAN AS IDPLAN_FTR
			FROM HPRED
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			INNER JOIN FTR ON FTR.N_FACTURA = HPRED.N_FACTURA
			WHERE HPRE.NOADMISION = @NOADMISION
			  AND COALESCE(HPRED.N_FACTURA, '') <> ''
		)
		SELECT GFACSOAT, IDTERCEROCA, IDPLAN
		FROM (
			-- GFACSOAT = 1 (Aseguradora): validar contra HACTRAN.IDASEGURADORA
			SELECT DISTINCT
				1 AS GFACSOAT,
				FA.IDTERCERO_FTR AS IDTERCEROCA,
				FA.IDPLAN_FTR AS IDPLAN
			FROM FACTURAS_ADM FA
			INNER JOIN HADM ON HADM.NOADMISION = @NOADMISION
			LEFT JOIN HACTRAN ON HACTRAN.CNSHACTRAN = HADM.CNSHACTRAN
			WHERE FA.GFACSOAT = 1
			  AND COALESCE(HACTRAN.IDASEGURADORA, '') <> ''
			  AND FA.IDTERCERO_FTR = HACTRAN.IDASEGURADORA

			UNION ALL

			-- GFACSOAT = 2 (ADRES): validar tercero FONSAT
			SELECT DISTINCT
				2 AS GFACSOAT,
				FA.IDTERCERO_FTR AS IDTERCEROCA,
				FA.IDPLAN_FTR AS IDPLAN
			FROM FACTURAS_ADM FA
			WHERE FA.GFACSOAT = 2
			  AND FA.IDTERCERO_FTR = DBO.FNK_VALORVARIABLE('IDNITFONSAT')

			UNION ALL

			-- GFACSOAT = 3 (EPS): validar tercero/plan de AFI de la admisi?n
			SELECT DISTINCT
				3 AS GFACSOAT,
				FA.IDTERCERO_FTR AS IDTERCEROCA,
				FA.IDPLAN_FTR AS IDPLAN
			FROM FACTURAS_ADM FA
			INNER JOIN HADM ON HADM.NOADMISION = @NOADMISION
			INNER JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
			WHERE FA.GFACSOAT = 3
			  AND COALESCE(AFI.IDADMINISTRADORA, '') <> ''
			  AND FA.IDTERCERO_FTR = AFI.IDADMINISTRADORA
			  AND FA.IDPLAN_FTR = COALESCE(AFI.IDPLAN, '')

			UNION ALL

			-- GFACSOAT = 4 (ARL): mantener validaci?n por tercero/plan ARL de admisi?n
			SELECT DISTINCT
				4 AS GFACSOAT,
				FA.IDTERCERO_FTR AS IDTERCEROCA,
				FA.IDPLAN_FTR AS IDPLAN
			FROM FACTURAS_ADM FA
			INNER JOIN HADM ON HADM.NOADMISION = @NOADMISION
			WHERE FA.GFACSOAT = 4
			  AND COALESCE(HADM.IDTERECEROARL, '') <> ''
			  AND FA.IDTERCERO_FTR = HADM.IDTERECEROARL
			  AND FA.IDPLAN_FTR = COALESCE(HADM.IDPLANARL, '')
		) X
		GROUP BY GFACSOAT, IDTERCEROCA, IDPLAN


		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END CATCH
	END

	-- =============================================
	-- GUARDAR_DISTRIBUCION: Actualiza GFACSOAT en HPRED
	-- =============================================
	IF @METODO = 'GUARDAR_DISTRIBUCION'
	BEGIN
		BEGIN TRY
			SELECT @NOADMISION = NOADMISION
			FROM OPENJSON(@PARAMETROS) WITH (
				NOADMISION VARCHAR(20) '$.NOADMISION'
			)

			-- Crear tabla temporal con los items a actualizar
			SELECT 
				NOPRESTACION,
				NOITEM,
				GFACSOAT,
				CANTIDAD
			INTO #ITEMS_UPDATE
			FROM OPENJSON(@PARAMETROS, '$.ITEMS') WITH (
				NOPRESTACION VARCHAR(20) '$.NOPRESTACION',
				NOITEM INT '$.NOITEM',
				GFACSOAT INT '$.GFACSOAT',
				CANTIDAD DECIMAL(18,2) '$.CANTIDAD'
			)

			-- Validar que existan los items
			IF NOT EXISTS (SELECT 1 FROM #ITEMS_UPDATE)
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'No se recibieron items para actualizar'
			END

			IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			-- Validaciones de reglas de negocio
			-- Validaci?n 1: ADRES no puede tener el mismo responsable que Aseguradora
			IF EXISTS (
				SELECT 1 
				FROM #ITEMS_UPDATE I
				INNER JOIN HADM ON HADM.NOADMISION = @NOADMISION
				WHERE I.GFACSOAT = 2  -- ADRES
				  AND HADM.IDTERCERO = DBO.FNK_VALORVARIABLE('IDNITFONSAT')
			)
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'ADRES no puede tener el mismo responsable que la Aseguradora. No se pueden hacer cambios hasta que se corrija esta situaci?n.'
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			-- Validaci?n 2: EPS no puede ser igual al responsable del accidente de tr?nsito
			IF EXISTS (
				SELECT 1 
				FROM #ITEMS_UPDATE I
				INNER JOIN HADM ON HADM.NOADMISION = @NOADMISION
				INNER JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
				WHERE I.GFACSOAT = 3  -- EPS
				  AND AFI.IDADMINISTRADORA = HADM.IDTERCERO
			)
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'La EPS no puede ser igual al responsable del accidente de tr?nsito. Debe corregir esta situaci?n antes de continuar.'
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			-- Actualizar GFACSOAT, IDTERCEROCA e IDPLAN en HPRED seg?n el destino
			UPDATE HPRED
			SET GFACSOAT = I.GFACSOAT,
				IDTERCEROCA = CASE I.GFACSOAT
					WHEN 2 THEN DBO.FNK_VALORVARIABLE('IDNITFONSAT')  -- ADRES
					WHEN 1 THEN HADM.IDTERCERO  -- Aseguradora
					WHEN 3 THEN AFI.IDADMINISTRADORA  -- EPS
					WHEN 4 THEN HADM.IDTERECEROARL  -- ARL
					ELSE HPRED.IDTERCEROCA
				END,
				IDPLAN = CASE I.GFACSOAT
					WHEN 2 THEN DBO.FNK_VALORVARIABLE('IDPLANSOAT')  -- ADRES
					WHEN 1 THEN HADM.IDPLAN  -- Aseguradora
					WHEN 3 THEN AFI.IDPLAN  -- EPS
					WHEN 4 THEN HADM.IDPLANARL  -- ARL
					ELSE HPRED.IDPLAN
				END
			FROM HPRED
			INNER JOIN #ITEMS_UPDATE I ON I.NOPRESTACION = HPRED.NOPRESTACION 
									  AND I.NOITEM = HPRED.NOITEM
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			INNER JOIN HADM ON HADM.NOADMISION = HPRE.NOADMISION
			LEFT JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
			WHERE HPRE.NOADMISION = @NOADMISION

			DECLARE @REGISTROS_ACTUALIZADOS INT = @@ROWCOUNT

			-- Asegurar que todos los items restantes tengan GFACSOAT v?lido (por si acaso hay items nuevos)
			UPDATE HPRED
			SET GFACSOAT = 1 -- Aseguradora por defecto
			FROM HPRED
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE HPRE.NOADMISION = @NOADMISION
			  AND COALESCE(HPRED.FACTURADA, 0) = 0 -- Solo items no facturados
			  AND COALESCE(HPRED.NOCOBRABLE, 0) = 0 -- Solo items cobrables
			  AND HPRED.GFACSOAT IS NULL -- Solo los que est?n en null

			-- Reliquidar la admisi?n por cambios en tarifas y dem?s
			DECLARE @JSON_RELIQUIDAR NVARCHAR(MAX)
			SET @JSON_RELIQUIDAR = '{"MODELO":"HPRE","METODO":"HPRE","PARAMETROS":{"METODO":"RELIQUIDAR_ADMISION","NOADMISION":"' + @NOADMISION + '","PCUBRIMIENTO":"0","CCONTRATANTE":"0","NOCIRUGIA":"0","PREFIJOS":null,"IDAREA":null,"ELIMINA":"0"},"USUARIO":"' + @USUARIO + '"}'
			EXEC SPQ_JSON @JSON_RELIQUIDAR

			SELECT 'OK' OK, @REGISTROS_ACTUALIZADOS AS REGISTROS_ACTUALIZADOS

		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END CATCH
	END

	-- =============================================
	-- MOVER_ITEM: Mueve un item parcial (divide cantidad)
	-- =============================================
	IF @METODO = 'MOVER_ITEM_PARCIAL'
	BEGIN
		BEGIN TRY
			DECLARE @NOPRESTACION VARCHAR(20), @NOITEM INT, @CANTIDAD_MOVER DECIMAL(18,2)
			DECLARE @GFACSOAT_DESTINO INT,@ITEMCIRUGIA INT
			DECLARE @NUEVO_NOITEM INT = NULL
			DECLARE @PREFIJO_MV VARCHAR(10), @GFACSOAT_ORIG_MV INT

			SELECT 
				@NOADMISION = NOADMISION,
				@NOPRESTACION = NOPRESTACION,
				@NOITEM = NOITEM,
				@CANTIDAD_MOVER = CANTIDAD_MOVER,
				@GFACSOAT_DESTINO = GFACSOAT_DESTINO,
            @ITEMCIRUGIA=COALESCE(ITEMCIRUGIA,0)
			FROM OPENJSON(@PARAMETROS) WITH (
				NOADMISION VARCHAR(20) '$.NOADMISION',
				NOPRESTACION VARCHAR(20) '$.NOPRESTACION',
				NOITEM INT '$.NOITEM',
				CANTIDAD_MOVER DECIMAL(18,2) '$.CANTIDAD_MOVER',
				GFACSOAT_DESTINO INT '$.GFACSOAT_DESTINO',
            ITEMCIRUGIA  INT  '$.ITEMCIRUGIA'
			)
         IF NOT EXISTS(SELECT 1 FROM HPRE WHERE NOPRESTACION=@NOPRESTACION AND PREFIJO=DBO.FNK_VALORVARIABLE('IDCIRPREFIJO'))
         BEGIN
            SELECT @ITEMCIRUGIA=NULL
         END
			-- Obtener datos del item original
			DECLARE @CANTIDAD_ORIGINAL DECIMAL(18,2), @VALOR DECIMAL(18,2)
			SELECT @CANTIDAD_ORIGINAL = D.CANTIDAD,
				   @VALOR = D.VALOR,
				   @PREFIJO_MV = H.PREFIJO,
				   @GFACSOAT_ORIG_MV = COALESCE(D.GFACSOAT, 0)
			FROM HPRED D
			INNER JOIN HPRE H ON H.NOPRESTACION = D.NOPRESTACION
			WHERE D.NOPRESTACION = @NOPRESTACION AND D.NOITEM = @NOITEM

			-- Validar cantidad
			IF @CANTIDAD_MOVER > @CANTIDAD_ORIGINAL
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'La cantidad a mover supera la cantidad disponible'
			END

			IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			-- Validaciones de reglas de negocio
			-- Validaci?n 1: ADRES no puede tener el mismo responsable que Aseguradora
			IF @GFACSOAT_DESTINO = 2  -- ADRES
			BEGIN
				DECLARE @IDTERCERO_HADM VARCHAR(20)
				SELECT @IDTERCERO_HADM = HADM.IDTERCERO
				FROM HADM
				INNER JOIN HPRE ON HPRE.NOADMISION = HADM.NOADMISION
				WHERE HPRE.NOADMISION = @NOADMISION
				  AND HPRE.NOPRESTACION = @NOPRESTACION

				IF @IDTERCERO_HADM = DBO.FNK_VALORVARIABLE('IDNITFONSAT')
				BEGIN
					INSERT INTO @TBLERRORES(ERROR) 
					SELECT 'ADRES no puede tener el mismo responsable que la Aseguradora. No se pueden hacer cambios hasta que se corrija esta situaci?n.'
					SELECT 'KO' OK
					SELECT ERROR FROM @TBLERRORES
					RETURN
				END
			END

			-- Validaci?n 2: EPS no puede ser igual al responsable del accidente de tr?nsito
			IF @GFACSOAT_DESTINO = 3  -- EPS
			BEGIN
				DECLARE @IDADMINISTRADORA_EPS VARCHAR(20), @IDTERCERO_ACCIDENTE VARCHAR(20)
				SELECT @IDADMINISTRADORA_EPS = AFI.IDADMINISTRADORA,
					   @IDTERCERO_ACCIDENTE = HADM.IDTERCERO
				FROM HADM
				INNER JOIN HPRE ON HPRE.NOADMISION = HADM.NOADMISION
				INNER JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
				WHERE HPRE.NOADMISION = @NOADMISION
				  AND HPRE.NOPRESTACION = @NOPRESTACION

				IF @IDADMINISTRADORA_EPS = @IDTERCERO_ACCIDENTE
				BEGIN
					INSERT INTO @TBLERRORES(ERROR) 
					SELECT 'La EPS no puede ser igual al responsable del accidente de tr?nsito. Debe corregir esta situaci?n antes de continuar.'
					SELECT 'KO' OK
					SELECT ERROR FROM @TBLERRORES
					RETURN
				END
			END
			-- Determinar IDTERCEROCA e IDPLAN seg?n GFACSOAT destino
			IF @GFACSOAT_DESTINO = 2 -- ADRES
			BEGIN
				SET @IDTERCEROCA_DESTINO = DBO.FNK_VALORVARIABLE('IDNITFONSAT')
				SET @IDPLAN_DESTINO = DBO.FNK_VALORVARIABLE('IDPLANSOAT')
			END
			ELSE IF @GFACSOAT_DESTINO = 1 -- Aseguradora
			BEGIN
				-- Obtener de HADM
				SELECT @IDTERCEROCA_DESTINO = HADM.IDTERCERO, @IDPLAN_DESTINO = HADM.IDPLAN
				FROM HADM
				INNER JOIN HPRE ON HPRE.NOADMISION = HADM.NOADMISION
				WHERE HPRE.NOPRESTACION = @NOPRESTACION
			END
			ELSE IF @GFACSOAT_DESTINO = 3 -- EPS
			BEGIN
				-- Obtener de AFI
				SELECT @IDTERCEROCA_DESTINO = AFI.IDADMINISTRADORA, @IDPLAN_DESTINO = AFI.IDPLAN
				FROM HADM
				INNER JOIN HPRE ON HPRE.NOADMISION = HADM.NOADMISION
				INNER JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
				WHERE HPRE.NOPRESTACION = @NOPRESTACION
			END
			ELSE IF @GFACSOAT_DESTINO = 4 -- ARL
			BEGIN
				-- Obtener de HADM (ARL)
				SELECT @IDTERCEROCA_DESTINO = HADM.IDTERECEROARL, @IDPLAN_DESTINO = HADM.IDPLANARL
				FROM HADM
				INNER JOIN HPRE ON HPRE.NOADMISION = HADM.NOADMISION
				WHERE HPRE.NOPRESTACION = @NOPRESTACION
			END
         IF COALESCE(@ITEMCIRUGIA,0) =0
         BEGIN
			   IF @CANTIDAD_MOVER = @CANTIDAD_ORIGINAL
			   BEGIN
				   -- Mover todo: actualizar GFACSOAT, IDTERCEROCA e IDPLAN
				   UPDATE HPRED
				   SET GFACSOAT = @GFACSOAT_DESTINO,
					   IDTERCEROCA = @IDTERCEROCA_DESTINO,
					   IDPLAN = @IDPLAN_DESTINO
				   WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @NOITEM
               EXEC SPK_COPAGOQX @NOADMISION, @NOPRESTACION, @NOITEM
			   END
			   ELSE
			   BEGIN
				   -- Mover parcial: reducir original y crear nuevo
				   UPDATE HPRED
				   SET CANTIDAD = CANTIDAD - @CANTIDAD_MOVER
				   WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @NOITEM

				   -- Crear nuevo item con la cantidad movida
				   SELECT @NUEVO_NOITEM = COALESCE(MAX(NOITEM), 0) + 1
				   FROM HPRED WHERE NOPRESTACION = @NOPRESTACION

				   INSERT INTO HPRED (
					   NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR,
					   VALORCOPAGO, VALORPCOMP, VALOREXCEDENTE, FECHA, USUARIO,
					   GFACSOAT, IDCIRUGIA, CONSECUTIVOCX, IDPLAN, IDTERCEROCA,
					   FACTURADA, COBRARA, CCOSTO
				   )
				   SELECT 
					   NOPRESTACION, @NUEVO_NOITEM, IDSERVICIO, @CANTIDAD_MOVER, VALOR,
					   VALORCOPAGO, VALORPCOMP, VALOREXCEDENTE, FECHA, @USUARIO,
					   @GFACSOAT_DESTINO, IDCIRUGIA, CONSECUTIVOCX, @IDPLAN_DESTINO, @IDTERCEROCA_DESTINO,
					   0, COBRARA, CCOSTO
				   FROM HPRED
				   WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @NOITEM
               EXEC SPK_COPAGOQX @NOADMISION, @NOPRESTACION, @NOITEM
			   END
         END
         ELSE
         BEGIN
				PRINT '--ITEM CIRUGIA Mover todo: actualizar GFACSOAT, IDTERCEROCA e IDPLAN @ITEMCIRUGIA='+CAST(COALESCE(@ITEMCIRUGIA,0) AS VARCHAR(1))+' @NOPRESTACION='+@NOPRESTACION

				UPDATE HPRED SET GFACSOAT = @GFACSOAT_DESTINO,
					IDTERCEROCA = @IDTERCEROCA_DESTINO,
					IDPLAN = @IDPLAN_DESTINO
				WHERE NOPRESTACION = @NOPRESTACION 
            AND ITEMCIRUGIA=@ITEMCIRUGIA
         END
         
			SELECT 'OK' OK

			SELECT
				CASE
					WHEN COALESCE(@ITEMCIRUGIA, 0) <> 0 THEN 'CIRUGIA'
					WHEN @CANTIDAD_MOVER = @CANTIDAD_ORIGINAL THEN 'TOTAL'
					ELSE 'PARCIAL'
				END AS TIPO_MOVIMIENTO,
				@NOPRESTACION AS NOPRESTACION,
				@NOITEM AS NOITEM_ORIGEN,
				@NUEVO_NOITEM AS NOITEM_NUEVO,
				@GFACSOAT_DESTINO AS GFACSOAT_DESTINO,
				@PREFIJO_MV AS PREFIJO,
				@GFACSOAT_ORIG_MV AS GFACSOAT_ORIG,
				(SELECT COALESCE(SUM(D2.CANTIDAD), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = @NOADMISION AND H2.PREFIJO = @PREFIJO_MV AND COALESCE(D2.GFACSOAT, 0) = COALESCE(@GFACSOAT_ORIG_MV, 0)) AS TOTAL_PREFIJO_CANTIDAD_ORIG,
				(SELECT COALESCE(SUM(COALESCE(D2.CANTIDAD, 0) * COALESCE(D2.VALOR, 0)), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = @NOADMISION AND H2.PREFIJO = @PREFIJO_MV AND COALESCE(D2.GFACSOAT, 0) = COALESCE(@GFACSOAT_ORIG_MV, 0)) AS TOTAL_PREFIJO_VALOR_ORIG,
				(SELECT COUNT(*) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = @NOADMISION AND H2.PREFIJO = @PREFIJO_MV AND COALESCE(D2.GFACSOAT, 0) = COALESCE(@GFACSOAT_ORIG_MV, 0)) AS TOTAL_PREFIJO_ITEMS_ORIG,
				(SELECT COALESCE(SUM(COALESCE(D2.CANTIDAD, 0) * COALESCE(D2.VALOR, 0)), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = @NOADMISION AND COALESCE(D2.GFACSOAT, 0) = COALESCE(@GFACSOAT_ORIG_MV, 0) AND COALESCE(D2.FACTURADA, 0) = 0 AND COALESCE(D2.NOCOBRABLE, 0) = 0) AS TOTAL_RESPONSABLE_VALOR_ORIG,
				(SELECT COALESCE(SUM(D2.CANTIDAD), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = @NOADMISION AND H2.PREFIJO = @PREFIJO_MV AND COALESCE(D2.GFACSOAT, 0) = COALESCE(@GFACSOAT_DESTINO, 0)) AS TOTAL_PREFIJO_CANTIDAD_DEST,
				(SELECT COALESCE(SUM(COALESCE(D2.CANTIDAD, 0) * COALESCE(D2.VALOR, 0)), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = @NOADMISION AND H2.PREFIJO = @PREFIJO_MV AND COALESCE(D2.GFACSOAT, 0) = COALESCE(@GFACSOAT_DESTINO, 0)) AS TOTAL_PREFIJO_VALOR_DEST,
				(SELECT COUNT(*) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = @NOADMISION AND H2.PREFIJO = @PREFIJO_MV AND COALESCE(D2.GFACSOAT, 0) = COALESCE(@GFACSOAT_DESTINO, 0)) AS TOTAL_PREFIJO_ITEMS_DEST,
				(SELECT COALESCE(SUM(COALESCE(D2.CANTIDAD, 0) * COALESCE(D2.VALOR, 0)), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = @NOADMISION AND COALESCE(D2.GFACSOAT, 0) = COALESCE(@GFACSOAT_DESTINO, 0) AND COALESCE(D2.FACTURADA, 0) = 0 AND COALESCE(D2.NOCOBRABLE, 0) = 0) AS TOTAL_RESPONSABLE_VALOR_DEST

			SELECT
				'ORIGEN' AS ROL,
				HPRED.NOPRESTACION,
				HPRED.NOITEM,
				HPRE.PREFIJO,
				HPRE.NOADMISION,
				COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT,
				HPRED.IDSERVICIO,
				SER.DESCSERVICIO,
				CONVERT(INT, HPRED.CANTIDAD) AS CANTIDAD,
				CONVERT(DECIMAL(14, 2), HPRED.VALOR) AS VALOR,
				CONVERT(DECIMAL(14, 2), COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)) AS VLRSUBTOTAL,
				CONVERT(DECIMAL(14, 2), HPRED.VALORCOPAGO) AS VALORCOPAGO,
				CONVERT(DECIMAL(14, 2), HPRED.VALOREXCEDENTE) AS VALOREXCEDENTE,
				CONVERT(DECIMAL(14, 2), HPRED.VALORPCOMP) AS VALORPCOMP,
				COALESCE(HPRED.NOCOBRABLE, 0) AS NOCOBRABLE,
				COALESCE(HPRED.PAQUETE, 0) AS PAQUETE,
				COALESCE(HPRED.FACTURADA, 0) AS FACTURADA,
				COALESCE(HPRED.ENCARGOS, 0) AS ENCARGOS,
				COALESCE(HPRED.COMENTARIOS, '') AS COMENTARIOS,
				COALESCE(HPRED.NOAUTORIZACION, '') AS NOAUTORIZACION,
				HPRED.IDCIRUGIA,
				HPRED.CONSECUTIVOCX,
				HPRED.ITEMCIRUGIA
			FROM HPRED
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			INNER JOIN SER ON SER.IDSERVICIO = HPRED.IDSERVICIO
			WHERE HPRED.NOPRESTACION = @NOPRESTACION
			  AND HPRED.NOITEM = @NOITEM

			IF @NUEVO_NOITEM IS NOT NULL
			BEGIN
				SELECT
					'NUEVO' AS ROL,
					HPRED.NOPRESTACION,
					HPRED.NOITEM,
					HPRE.PREFIJO,
					HPRE.NOADMISION,
					COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT,
					HPRED.IDSERVICIO,
					SER.DESCSERVICIO,
					CONVERT(INT, HPRED.CANTIDAD) AS CANTIDAD,
					CONVERT(DECIMAL(14, 2), HPRED.VALOR) AS VALOR,
					CONVERT(DECIMAL(14, 2), COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)) AS VLRSUBTOTAL,
					CONVERT(DECIMAL(14, 2), HPRED.VALORCOPAGO) AS VALORCOPAGO,
					CONVERT(DECIMAL(14, 2), HPRED.VALOREXCEDENTE) AS VALOREXCEDENTE,
					CONVERT(DECIMAL(14, 2), HPRED.VALORPCOMP) AS VALORPCOMP,
					COALESCE(HPRED.NOCOBRABLE, 0) AS NOCOBRABLE,
					COALESCE(HPRED.PAQUETE, 0) AS PAQUETE,
					COALESCE(HPRED.FACTURADA, 0) AS FACTURADA,
					COALESCE(HPRED.ENCARGOS, 0) AS ENCARGOS,
					COALESCE(HPRED.COMENTARIOS, '') AS COMENTARIOS,
					COALESCE(HPRED.NOAUTORIZACION, '') AS NOAUTORIZACION,
					HPRED.IDCIRUGIA,
					HPRED.CONSECUTIVOCX,
					HPRED.ITEMCIRUGIA
				FROM HPRED
				INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
				INNER JOIN SER ON SER.IDSERVICIO = HPRED.IDSERVICIO
				WHERE HPRED.NOPRESTACION = @NOPRESTACION
				  AND HPRED.NOITEM = @NUEVO_NOITEM
			END

		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END CATCH
	END
	IF @METODO = 'FECHAS_CARGOS'
	BEGIN
		BEGIN TRY
			DECLARE @GFACSOAT_FECHAS SMALLINT
			SELECT
				@NOADMISION = NOADMISION,
				@GFACSOAT_FECHAS = GFACSOAT
			FROM OPENJSON(@PARAMETROS) WITH (
				NOADMISION VARCHAR(20) '$.NOADMISION',
				GFACSOAT SMALLINT '$.GFACSOAT'
			)

			SELECT 'OK' OK
			SELECT
				CONVERT(VARCHAR(10), MIN(HPRE.FECHA), 23) AS FECHA_DESDE,
				CONVERT(VARCHAR(10), MAX(HPRE.FECHA), 23) AS FECHA_HASTA
			FROM HPRED
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE HPRE.NOADMISION = @NOADMISION
			  AND HPRED.GFACSOAT = @GFACSOAT_FECHAS
			  AND COALESCE(HPRED.NOCOBRABLE, 0) = 0

			RETURN
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END CATCH
	END

   IF @METODO='MOVER_MASIVO'     
   BEGIN         
		BEGIN TRY
			DECLARE @GFACSOAT_DESMASI INT,@PREFIJO VARCHAR(10),@USUARIO_CARGOS VARCHAR(20)
         DECLARE @FECHA_DESDE DATETIME, @FECHA_HASTA DATETIME
			DECLARE @GFACSOAT_ORIGEN INT, @REGISTROS_MOVIDOS INT
			SELECT 
				@NOADMISION = NOADMISION,
				@GFACSOAT_DESMASI = GFACSOAT_DESTINO,
				@GFACSOAT_ORIGEN = GFACSOAT_ORIGEN,
            @PREFIJO = PREFIJO,
            @USUARIO_CARGOS=USUARIO,
            @FECHA_DESDE =CAST(FECHA_DESDE AS DATE),
            @FECHA_HASTA  =CAST(FECHA_HASTA AS DATE)
			FROM OPENJSON(@PARAMETROS) WITH (
				NOADMISION VARCHAR(20) '$.NOADMISION',
				GFACSOAT_DESTINO INT '$.GFACSOAT_DESTINO',
				GFACSOAT_ORIGEN INT '$.GFACSOAT_ORIGEN',
            PREFIJO  VARCHAR(10)   '$.PREFIJO',
            USUARIO  VARCHAR(20)   '$.USUARIO',
            FECHA_DESDE  VARCHAR(20)   '$.FECHA_DESDE',
            FECHA_HASTA  VARCHAR(20)   '$.FECHA_HASTA'
			) 
         
			-- Determinar IDTERCEROCA e IDPLAN seg?n GFACSOAT destino
			IF @GFACSOAT_DESMASI = 2 -- ADRES
			BEGIN
				SET @IDTERCEROCA_DESTINO = DBO.FNK_VALORVARIABLE('IDNITFONSAT')
				SET @IDPLAN_DESTINO = DBO.FNK_VALORVARIABLE('IDPLANSOAT')
			END
			ELSE IF @GFACSOAT_DESMASI = 1 -- Aseguradora
			BEGIN
				-- Obtener de HADM
				SELECT @IDTERCEROCA_DESTINO = HADM.IDTERCERO, @IDPLAN_DESTINO = HADM.IDPLAN
				FROM HADM
            WHERE NOADMISION=@NOADMISION
			END
			ELSE IF @GFACSOAT_DESMASI = 3 -- EPS
			BEGIN
				-- Obtener de AFI
				SELECT @IDTERCEROCA_DESTINO = AFI.IDADMINISTRADORA, @IDPLAN_DESTINO = AFI.IDPLAN
				FROM HADM INNER JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
            WHERE HADM.NOADMISION=@NOADMISION
			END
			ELSE IF @GFACSOAT_DESMASI = 4 -- ARL
			BEGIN
				-- Obtener de HADM (ARL)
				SELECT @IDTERCEROCA_DESTINO = HADM.IDTERECEROARL, @IDPLAN_DESTINO = HADM.IDPLANARL
				FROM HADM
				INNER JOIN HPRE ON HPRE.NOADMISION = HADM.NOADMISION
			END

			SELECT DISTINCT HPRE.PREFIJO
			INTO #PREFIJOS_MOVIDOS
			FROM HPRED
			INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
			WHERE HPRE.NOADMISION = @NOADMISION
			  AND HPRE.FECHA >= @FECHA_DESDE
			  AND HPRE.FECHA < DATEADD(DAY, 1, @FECHA_HASTA)
			  AND HPRED.GFACSOAT = COALESCE(@GFACSOAT_ORIGEN, HPRED.GFACSOAT)
			  AND HPRE.PREFIJO = CASE WHEN COALESCE(@PREFIJO, '') <> '' THEN @PREFIJO ELSE HPRE.PREFIJO END
			  AND HPRE.USUARIO = CASE WHEN COALESCE(@USUARIO_CARGOS, '') <> '' THEN @USUARIO_CARGOS ELSE HPRE.USUARIO END

         UPDATE HPRED SET GFACSOAT=@GFACSOAT_DESMASI,IDTERCEROCA=@IDTERCEROCA_DESTINO, IDPLAN=@IDPLAN_DESTINO
         FROM HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
         WHERE HPRE.NOADMISION=@NOADMISION
         AND HPRE.FECHA>=@FECHA_DESDE
         AND HPRE.FECHA < DATEADD(DAY, 1, @FECHA_HASTA)
         AND HPRED.GFACSOAT = COALESCE(@GFACSOAT_ORIGEN, HPRED.GFACSOAT)
         AND HPRE.PREFIJO=CASE WHEN COALESCE(@PREFIJO, '') <> '' THEN @PREFIJO ELSE HPRE.PREFIJO END
         AND HPRE.USUARIO=CASE WHEN COALESCE(@USUARIO_CARGOS, '') <> '' THEN @USUARIO_CARGOS ELSE HPRE.USUARIO END

			SET @REGISTROS_MOVIDOS = @@ROWCOUNT

			EXEC SPK_RELIQUIDACOPAGOQX @NOADMISION

         SELECT 'OK' OK, @REGISTROS_MOVIDOS AS REGISTROS_MOVIDOS

			SELECT PREFIJO FROM #PREFIJOS_MOVIDOS
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END CATCH
   END  
	-- =============================================
	-- DISTRIBUCION_AUTOMATICA: Distribuye autom?ticamente seg?n topes
	-- =============================================
	IF @METODO IN ('DISTRIBUCION_AUTOMATICA', 'DISTRIBUIR_HACTRAN')
	BEGIN
		BEGIN TRY
			SELECT @NOADMISION = NOADMISION
			FROM OPENJSON(@PARAMETROS) WITH (
				NOADMISION VARCHAR(20) '$.NOADMISION'
			)

			IF COALESCE(@CNSHACTRAN, '') = ''
			BEGIN
				SELECT @CNSHACTRAN = CNSHACTRAN FROM HADM WHERE NOADMISION = @NOADMISION
			END

			-- Topes disponibles del evento actual: descuentan gasto externo + monto anterior.
			-- Cascada: Aseguradora, luego ADRES, luego EPS (residual).
			DECLARE @TOPE_ASE DECIMAL(18,2), @TOPE_ADRES DECIMAL(18,2)
			DECLARE @MOSTRAR_ADRES BIT

         SELECT @TOPE=COALESCE(TOPE,0),@TOPE1=COALESCE(TOPE1,0),@VLREXTERNO=COALESCE(VLRGASTOEXTERNO,0)
         FROM HACTRAN WHERE CNSHACTRAN=@CNSHACTRAN
         SELECT @VLRGASTADO_ANT = COALESCE(SUM(COALESCE(HACTRAND.VLRGASTADO,0)), 0)
         FROM HACTRAND
         WHERE HACTRAND.CNSHACTRAN = @CNSHACTRAN
           AND UPPER(LTRIM(RTRIM(COALESCE(HACTRAND.PROCEDENCIA,'')))) <> 'EXTERNO'
           AND LTRIM(RTRIM(COALESCE(HACTRAND.NOREFERENCIA,''))) <> LTRIM(RTRIM(COALESCE(@NOADMISION,'')))
         -- El monto anterior ya excluye la admision actual y el gasto externo.
         SET @TOPE1_ORIG = @TOPE1
         SET @TOPE2 = CASE WHEN @TOPE > @TOPE1_ORIG THEN @TOPE - @TOPE1_ORIG ELSE 0 END
         -- Cascada: (anterior + externo) al primer pagador; el resto al segundo.
         SET @CONSUMIDO_PREVIO = COALESCE(@VLREXTERNO,0) + COALESCE(@VLRGASTADO_ANT,0)
         IF @CONSUMIDO_PREVIO > 0
         BEGIN
            IF @CONSUMIDO_PREVIO <= @TOPE1_ORIG
            BEGIN
               SET @TOPE1 = @TOPE1_ORIG - @CONSUMIDO_PREVIO
            END
            ELSE
            BEGIN
               SET @DIFERENCIA = @CONSUMIDO_PREVIO - @TOPE1_ORIG
               SET @TOPE1 = 0
               IF @TOPE2 > @DIFERENCIA
                  SET @TOPE2 = @TOPE2 - @DIFERENCIA
               ELSE
                  SET @TOPE2 = 0
            END
         END

			SELECT 
				@TOPE_ASE = @TOPE1,
				@TOPE_ADRES = CASE 
					WHEN HACTRAN.IDASEGURADORA = DBO.FNK_VALORVARIABLE('IDNITFONSAT') OR COALESCE(HACTRAN.IDASEGURADORA,'')=''
					THEN @TOPE1  -- Si es FONSAT, TOPE_ADRES = TOPE_ASE
					ELSE @TOPE2
				END,
				@MOSTRAR_ADRES = CASE 
					WHEN  HACTRAN.IDASEGURADORA = DBO.FNK_VALORVARIABLE('IDNITFONSAT') OR COALESCE(HACTRAN.IDASEGURADORA,'')=''
					THEN 0  -- No mostrar/distribuir a ADRES
					ELSE 1  -- Mostrar/distribuir a ADRES
				END
			FROM HADM
			LEFT JOIN HACTRAN ON HACTRAN.CNSHACTRAN = HADM.CNSHACTRAN
			WHERE HADM.NOADMISION = @NOADMISION

			-- Calcular acumulados actuales de items ya asignados (GFACSOAT en 1,2,3,4)
			DECLARE @ACUM_ASE DECIMAL(18,2) = 0
			DECLARE @ACUM_ADRES DECIMAL(18,2) = 0

			SELECT @ACUM_ASE = COALESCE(SUM(COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)), 0)
			FROM HPRED
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE HPRE.NOADMISION = @NOADMISION
			  AND COALESCE(HPRED.FACTURADA, 0) = 0
			  AND COALESCE(HPRED.NOCOBRABLE, 0) = 0
			  AND HPRED.GFACSOAT = 1

			SELECT @ACUM_ADRES = COALESCE(SUM(COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)), 0)
			FROM HPRED
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE HPRE.NOADMISION = @NOADMISION
			  AND COALESCE(HPRED.FACTURADA, 0) = 0
			  AND COALESCE(HPRED.NOCOBRABLE, 0) = 0
			  AND HPRED.GFACSOAT = 2

			-- Cursor para distribuir solo items sin asignar (GFACSOAT null o no en 1,2,3,4)
			DECLARE @CUR_NOPRESTACION VARCHAR(20), @CUR_NOITEM INT, @CUR_VALOR DECIMAL(18,2)
			
			DECLARE cur_items CURSOR FOR
				SELECT HPRED.NOPRESTACION, HPRED.NOITEM, 
					   COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0) AS VLRSUBTOTAL
				FROM HPRED
				INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
				WHERE HPRE.NOADMISION = @NOADMISION
				  AND COALESCE(HPRED.FACTURADA, 0) = 0
				  AND COALESCE(HPRED.NOCOBRABLE, 0) = 0
				  AND (HPRED.GFACSOAT IS NULL OR HPRED.GFACSOAT NOT IN (1, 2, 3, 4))
				ORDER BY COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0) DESC

			OPEN cur_items
			FETCH NEXT FROM cur_items INTO @CUR_NOPRESTACION, @CUR_NOITEM, @CUR_VALOR

			WHILE @@FETCH_STATUS = 0
			BEGIN
				DECLARE @NUEVO_GFACSOAT INT = 3 -- Por defecto EPS (residual)

				-- Intentar Aseguradora (TOPE)
				IF @ACUM_ASE + @CUR_VALOR <= @TOPE_ASE
				BEGIN
					SET @NUEVO_GFACSOAT = 1
					SET @ACUM_ASE = @ACUM_ASE + @CUR_VALOR
				END
				-- Intentar ADRES (TOPE1) - solo si se debe mostrar ADRES
				ELSE IF @MOSTRAR_ADRES = 1 AND @ACUM_ADRES + @CUR_VALOR <= @TOPE_ADRES
				BEGIN
					SET @NUEVO_GFACSOAT = 2
					SET @ACUM_ADRES = @ACUM_ADRES + @CUR_VALOR
				END
				-- EPS (residual) - todo lo que no quepa en Aseguradora ni ADRES
				-- ARL no se usa en distribuci?n autom?tica, solo manualmente por el usuario
				ELSE
				BEGIN
					SET @NUEVO_GFACSOAT = 3
				END
			-- Determinar IDTERCEROCA e IDPLAN seg?n GFACSOAT destino
			IF @NUEVO_GFACSOAT = 2 -- ADRES
			BEGIN
				SET @IDTERCEROCA_DESTINO = DBO.FNK_VALORVARIABLE('IDNITFONSAT')
				SET @IDPLAN_DESTINO = DBO.FNK_VALORVARIABLE('IDPLANSOAT')
			END
			ELSE IF @NUEVO_GFACSOAT = 1 -- Aseguradora
			BEGIN
				-- Obtener de HADM
				SELECT @IDTERCEROCA_DESTINO = HADM.IDTERCERO, @IDPLAN_DESTINO = HADM.IDPLAN
				FROM HADM
            WHERE NOADMISION = @NOADMISION
			END
			   ELSE IF @NUEVO_GFACSOAT = 3 -- EPS
			   BEGIN
				   -- Obtener de AFI
				   SELECT @IDTERCEROCA_DESTINO = AFI.IDADMINISTRADORA, @IDPLAN_DESTINO = AFI.IDPLAN
				   FROM HADM  INNER JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
               WHERE NOADMISION = @NOADMISION
			   END
			   ELSE IF @NUEVO_GFACSOAT = 4 -- ARL
			   BEGIN
				   -- Obtener de HADM (ARL)
				   SELECT @IDTERCEROCA_DESTINO = HADM.IDTERECEROARL, @IDPLAN_DESTINO = HADM.IDPLANARL
				   FROM HADM 
               WHERE NOADMISION = @NOADMISION
			   END

				-- Actualizar solo el item sin asignar
				UPDATE HPRED
				SET GFACSOAT = @NUEVO_GFACSOAT
				WHERE NOPRESTACION = @CUR_NOPRESTACION AND NOITEM = @CUR_NOITEM

				FETCH NEXT FROM cur_items INTO @CUR_NOPRESTACION, @CUR_NOITEM, @CUR_VALOR
			END

			CLOSE cur_items
			DEALLOCATE cur_items

         EXEC SPK_RELIQUIDACOPAGOQX @NOADMISION
			SELECT 'OK' OK

		END TRY
		BEGIN CATCH
			IF CURSOR_STATUS('local', 'cur_items') >= 0
			BEGIN
				CLOSE cur_items
				DEALLOCATE cur_items
			END
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END CATCH
	END

	-- =============================================
	-- REORGANIZAR_TODO: Reorganiza todos los items desde cero seg?n topes
	-- =============================================
	IF @METODO = 'REORGANIZAR_TODO'
	BEGIN
		BEGIN TRY
			SELECT @NOADMISION = NOADMISION
			FROM OPENJSON(@PARAMETROS) WITH (
				NOADMISION VARCHAR(20) '$.NOADMISION'
			)

			-- Obtener topes (solo Aseguradora y ADRES tienen topes)
			-- Si IDASEGURADORA = IDNITFONSAT, entonces TOPE_ADRES = TOPE_ASE (no se distribuye a ADRES)
         SELECT @CNSHACTRAN=CNSHACTRAN FROM HADM WHERE NOADMISION=@NOADMISION
			DECLARE @TOPE_ASE_REORG DECIMAL(18,2), @TOPE_ADRES_REORG DECIMAL(18,2)
			DECLARE @MOSTRAR_ADRES_REORG BIT

         -- Topes disponibles del evento actual: descuentan gasto externo + monto anterior.
         -- Cascada: Aseguradora, luego ADRES, luego EPS (residual).
         SELECT @TOPE=COALESCE(TOPE,0),@TOPE1=COALESCE(TOPE1,0),@VLREXTERNO=COALESCE(VLRGASTOEXTERNO,0)
         FROM HACTRAN WHERE CNSHACTRAN=@CNSHACTRAN
         SELECT @VLRGASTADO_ANT = COALESCE(SUM(COALESCE(HACTRAND.VLRGASTADO,0)), 0)
         FROM HACTRAND
         WHERE HACTRAND.CNSHACTRAN = @CNSHACTRAN
           AND UPPER(LTRIM(RTRIM(COALESCE(HACTRAND.PROCEDENCIA,'')))) <> 'EXTERNO'
           AND LTRIM(RTRIM(COALESCE(HACTRAND.NOREFERENCIA,''))) <> LTRIM(RTRIM(COALESCE(@NOADMISION,'')))
         -- El monto anterior ya excluye la admision actual y el gasto externo.
         SET @TOPE1_ORIG = @TOPE1
         SET @TOPE2 = CASE WHEN @TOPE > @TOPE1_ORIG THEN @TOPE - @TOPE1_ORIG ELSE 0 END
         -- Cascada: (anterior + externo) al primer pagador; el resto al segundo.
         SET @CONSUMIDO_PREVIO = COALESCE(@VLREXTERNO,0) + COALESCE(@VLRGASTADO_ANT,0)
         IF @CONSUMIDO_PREVIO > 0
         BEGIN
            IF @CONSUMIDO_PREVIO <= @TOPE1_ORIG
            BEGIN
               SET @TOPE1 = @TOPE1_ORIG - @CONSUMIDO_PREVIO
            END
            ELSE
            BEGIN
               SET @DIFERENCIA = @CONSUMIDO_PREVIO - @TOPE1_ORIG
               SET @TOPE1 = 0
               IF @TOPE2 > @DIFERENCIA
                  SET @TOPE2 = @TOPE2 - @DIFERENCIA
               ELSE
                  SET @TOPE2 = 0
            END
         END
         PRINT  '@TOPE='+CAST( COALESCE(@TOPE,0) AS VARCHAR(20))+' @TOPE1='+CAST( COALESCE( @TOPE1,0) AS VARCHAR(20))+'  @TOPE2='+CAST( COALESCE( @TOPE2,0) AS VARCHAR(20))
			SELECT 
				@TOPE_ASE_REORG = @TOPE1,
				@TOPE_ADRES_REORG = CASE 
					WHEN  HACTRAN.IDASEGURADORA = DBO.FNK_VALORVARIABLE('IDNITFONSAT') OR COALESCE(HACTRAN.IDASEGURADORA,'')='' 
					THEN @TOPE1 -- Si es FONSAT, TOPE_ADRES = TOPE_ASE
					ELSE @TOPE2
				END,
				@MOSTRAR_ADRES_REORG = CASE 
					WHEN  (HACTRAN.IDASEGURADORA = DBO.FNK_VALORVARIABLE('IDNITFONSAT') OR COALESCE(HACTRAN.IDASEGURADORA,'')='' OR @TOPE2>0)
					THEN 1  -- No mostrar/distribuir a ADRES
					ELSE 0  -- Mostrar/distribuir a ADRES
				END
			FROM HADM
			LEFT JOIN HACTRAN ON HACTRAN.CNSHACTRAN = HADM.CNSHACTRAN
			WHERE HADM.NOADMISION = @NOADMISION

			-- Reiniciar todos a Aseguradora (excepto los facturados)
			UPDATE HPRED
			SET GFACSOAT = 0
			FROM HPRED
			INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE HPRE.NOADMISION = @NOADMISION
			  AND COALESCE(HPRED.FACTURADA, 0) = 0
			  AND COALESCE(HPRED.NOCOBRABLE, 0) = 0

			-- Variables para acumulados (solo Aseguradora y ADRES)
			DECLARE @ACUM_ASE_REORG DECIMAL(18,2) = 0
			DECLARE @ACUM_ADRES_REORG DECIMAL(18,2) = 0

			-- Cursor para distribuir todos los items (ordenado por valor descendente)
			DECLARE @CUR_NOPRESTACION_REORG VARCHAR(20), @CUR_NOITEM_REORG INT, @CUR_VALOR_REORG DECIMAL(18,2)
			
			DECLARE cur_items_reorg CURSOR FOR
				SELECT HPRED.NOPRESTACION, HPRED.NOITEM, 
					   COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0) AS VLRSUBTOTAL
				FROM HPRED
				INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
				WHERE HPRE.NOADMISION = @NOADMISION
				  AND COALESCE(HPRED.FACTURADA, 0) = 0
				  AND COALESCE(HPRED.NOCOBRABLE, 0) = 0
				ORDER BY HPRE.FECHA

			OPEN cur_items_reorg
			FETCH NEXT FROM cur_items_reorg INTO @CUR_NOPRESTACION_REORG, @CUR_NOITEM_REORG, @CUR_VALOR_REORG

			WHILE @@FETCH_STATUS = 0
			BEGIN
				DECLARE @NUEVO_GFACSOAT_REORG INT = 3 -- Por defecto EPS (residual)

				-- Intentar Aseguradora (TOPE)
				IF @TOPE_ASE_REORG > 0 AND  @ACUM_ASE_REORG + @CUR_VALOR_REORG <= @TOPE_ASE_REORG
				BEGIN
               PRINT  'VOY EN @CUR_NOPRESTACION_REORG '+@CUR_NOPRESTACION_REORG+' @ACUM_ASE_REORG'+CAST( COALESCE(@ACUM_ASE_REORG,0) AS VARCHAR(20))+ ' @CUR_VALOR_REORG='+CAST(COALESCE(@CUR_VALOR_REORG,0) AS VARCHAR(20))+'  @TOPE_ASE_REORG='+CAST(COALESCE(@TOPE_ASE_REORG,0) AS VARCHAR(20)) 
					SET @NUEVO_GFACSOAT_REORG = 1
					SET @ACUM_ASE_REORG = @ACUM_ASE_REORG + @CUR_VALOR_REORG
				END
				ELSE IF @MOSTRAR_ADRES_REORG = 1 AND @TOPE_ADRES_REORG>0 AND @ACUM_ADRES_REORG + @CUR_VALOR_REORG <= @TOPE_ADRES_REORG
				BEGIN
            PRINT  'VOY EN @CUR_NOPRESTACION_REORG '+@CUR_NOPRESTACION_REORG+' @ACUM_ADRES_REORG'+CAST( COALESCE(@ACUM_ADRES_REORG,0) AS VARCHAR(20))+ ' @CUR_VALOR_REORG='+CAST(COALESCE(@CUR_VALOR_REORG,0) AS VARCHAR(20))+'  @TOPE_ADRES_REORG='+CAST(COALESCE(@TOPE_ADRES_REORG,0) AS VARCHAR(20)) 
               
					SET @NUEVO_GFACSOAT_REORG = 2
					SET @ACUM_ADRES_REORG = @ACUM_ADRES_REORG + @CUR_VALOR_REORG
				END
				ELSE
				BEGIN
					SET @NUEVO_GFACSOAT_REORG = 3
				END
            PRINT '@NUEVO_GFACSOAT_REORG ='+CAST(@NUEVO_GFACSOAT_REORG AS VARCHAR(2))
			-- Determinar IDTERCEROCA e IDPLAN seg?n GFACSOAT destino
			IF @NUEVO_GFACSOAT_REORG = 2 -- ADRES
			BEGIN
				SET @IDTERCEROCA_DESTINO = DBO.FNK_VALORVARIABLE('IDNITFONSAT')
				SET @IDPLAN_DESTINO = DBO.FNK_VALORVARIABLE('IDPLANSOAT')
			END
			ELSE IF @NUEVO_GFACSOAT_REORG = 1 -- Aseguradora
			BEGIN
				-- Obtener de HADM
				SELECT @IDTERCEROCA_DESTINO = HADM.IDTERCERO, @IDPLAN_DESTINO = HADM.IDPLAN
				FROM HADM
            WHERE NOADMISION = @NOADMISION
			END
			   ELSE IF @NUEVO_GFACSOAT_REORG = 3 -- EPS
			   BEGIN
				   -- Obtener de AFI
				   SELECT @IDTERCEROCA_DESTINO = AFI.IDADMINISTRADORA, @IDPLAN_DESTINO = AFI.IDPLAN
				   FROM HADM  INNER JOIN AFI ON AFI.IDAFILIADO = HADM.IDAFILIADO
               WHERE NOADMISION = @NOADMISION
			   END
			   ELSE IF @NUEVO_GFACSOAT_REORG = 4 -- ARL
			   BEGIN
				   -- Obtener de HADM (ARL)
				   SELECT @IDTERCEROCA_DESTINO = HADM.IDTERECEROARL, @IDPLAN_DESTINO = HADM.IDPLANARL
				   FROM HADM 
               WHERE NOADMISION = @NOADMISION
			   END

				-- Actualizar item
				UPDATE HPRED
				SET GFACSOAT = @NUEVO_GFACSOAT_REORG,
                IDTERCEROCA=@IDTERCEROCA_DESTINO,
                IDPLAN=@IDPLAN_DESTINO
				WHERE NOPRESTACION = @CUR_NOPRESTACION_REORG AND NOITEM = @CUR_NOITEM_REORG

				FETCH NEXT FROM cur_items_reorg INTO @CUR_NOPRESTACION_REORG, @CUR_NOITEM_REORG, @CUR_VALOR_REORG
			END

			CLOSE cur_items_reorg
			DEALLOCATE cur_items_reorg

         EXEC SPK_RELIQUIDACOPAGOQX @NOADMISION
			SELECT 'OK' OK

		END TRY
		BEGIN CATCH
			IF CURSOR_STATUS('local', 'cur_items_reorg') >= 0
			BEGIN
				CLOSE cur_items_reorg
				DEALLOCATE cur_items_reorg
			END
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END CATCH
	END

	-- =============================================
	-- FACTURAR: Llama a SPK_FACTURA_SOAT_TODO para facturar responsables seleccionados
	-- =============================================
	IF @METODO = 'FACTURAR'
	BEGIN
		BEGIN TRY
			DECLARE @COMPANIA_FACT VARCHAR(2), @IDSEDE_FACT VARCHAR(5), @NIT_FACT VARCHAR(20)
			DECLARE @SYS_COMPUTERNAME_FACT VARCHAR(254), @TFECHA_FACT SMALLINT
			DECLARE @FECHAFAC_FACT DATETIME, @GFACSOAT_FACTURAR_FACT NVARCHAR(MAX)
			DECLARE @CONSECUTIVO_CX_FACT VARCHAR(20), @CXMAYOR_FACT VARCHAR(20), @CXMENOR_FACT VARCHAR(20)
			DECLARE @CUPSMAYOR_FACT VARCHAR(6), @CUPSMENOR_FACT VARCHAR(6), @CNSHACTRAN_FACT VARCHAR(20)

			-- Leer par?metros del JSON
			SELECT @NOADMISION = NOADMISION,
				   @COMPANIA_FACT = COMPANIA,
				   @IDSEDE_FACT = IDSEDE,
				   @NIT_FACT = NIT,
				   @SYS_COMPUTERNAME_FACT = SYS_COMPUTERNAME,
				   @TFECHA_FACT = TFECHA,
				   @FECHAFAC_FACT = FECHAFAC,
				   @GFACSOAT_FACTURAR_FACT = GFACSOAT_FACTURAR
			FROM OPENJSON(@PARAMETROS) WITH (
				NOADMISION VARCHAR(20) '$.NOADMISION',
				COMPANIA VARCHAR(2) '$.COMPANIA',
				IDSEDE VARCHAR(5) '$.IDSEDE',
				NIT VARCHAR(20) '$.NIT',
				SYS_COMPUTERNAME VARCHAR(254) '$.SYS_COMPUTERNAME',
				TFECHA SMALLINT '$.TFECHA',
				FECHAFAC DATETIME '$.FECHAFAC',
				GFACSOAT_FACTURAR NVARCHAR(MAX) '$.GFACSOAT_FACTURAR'
			)

			-- Validar que exista la admisi?n
			IF NOT EXISTS (SELECT 1 FROM HADM WHERE NOADMISION = @NOADMISION)
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'La admisi?n no existe'
			END

			IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			-- Llamar al procedimiento de facturaci?n
			EXEC DBO.SPK_FACTURA_SOAT_TODO
				@NOADMISION = @NOADMISION,
				@COMPANIA = @COMPANIA_FACT,
				@IDSEDE = @IDSEDE_FACT,
				@USUARIO = @USUARIO,
				@NIT = @NIT_FACT,
				@SYS_COMPUTERNAME = @SYS_COMPUTERNAME_FACT,
				@TFECHA = @TFECHA_FACT,
				@FECHAFAC = @FECHAFAC_FACT,
				@GFACSOAT_FACTURAR = @GFACSOAT_FACTURAR_FACT

			-- Actualiza el CUPS principal cuando existe al menos una cirugía válida;
			-- el CUPS secundario se actualiza solo cuando existe una segunda cirugía.
			SELECT @CNSHACTRAN_FACT = NULLIF(LTRIM(RTRIM(H.CNSHACTRAN)), '')
			FROM HADM H
			WHERE H.NOADMISION = @NOADMISION
			  AND H.TIPOADM = '04'

			IF @CNSHACTRAN_FACT IS NOT NULL
			   AND EXISTS (SELECT 1 FROM HACTRAN WHERE CNSHACTRAN = @CNSHACTRAN_FACT)
			BEGIN
				SELECT TOP (1) @CONSECUTIVO_CX_FACT = Q.CONSECUTIVO
				FROM QXPCX Q
				WHERE Q.NOADMISION = @NOADMISION
				  AND COALESCE(Q.LIQ_ADC, 0) <> 2
				  AND EXISTS (
					  SELECT 1
					  FROM QXPCXD D
					  WHERE D.CONSECUTIVO = Q.CONSECUTIVO
				  )
				  AND EXISTS (
					  SELECT 1
					  FROM HPRED D
					  INNER JOIN HPRE P ON P.NOPRESTACION = D.NOPRESTACION
					  WHERE P.NOADMISION = @NOADMISION
						AND D.CONSECUTIVOCX = Q.CONSECUTIVO
				  )
				ORDER BY Q.FECHA DESC, Q.CONSECUTIVO DESC

				IF NULLIF(LTRIM(RTRIM(@CONSECUTIVO_CX_FACT)), '') IS NOT NULL
				BEGIN
					;WITH DATOS_TARIFA AS
					(
						SELECT D.ITEM, D.IDSERVICIO, ST.VLRSERVICIO,
							ROW_NUMBER() OVER (
								ORDER BY ST.VLRSERVICIO DESC, D.ITEM ASC
							) AS ORDEN
						FROM QXPCXD D
						INNER JOIN QXPCX Q ON Q.CONSECUTIVO = D.CONSECUTIVO
						INNER JOIN HADM H ON H.NOADMISION = Q.NOADMISION AND H.TIPOADM = '04'
						OUTER APPLY
						(
							SELECT TOP (1) C.IDTERCEROCA, C.IDPLAN, C.COBRARA
							FROM CPPAF C
							WHERE C.IDPLAN = COALESCE(NULLIF(D.IDPLAN, ''), H.IDPLAN)
							  AND C.IDSERVICIO = D.IDSERVICIO
							  AND C.IDAREA = Q.IDAREA
						) CP
						CROSS APPLY
						(
							SELECT
								CASE
									WHEN CP.COBRARA = 'O' THEN COALESCE(NULLIF(D.IDTERCEROCA, ''), H.IDTERCERO)
									WHEN NULLIF(CP.IDTERCEROCA, '') IS NOT NULL AND CP.IDTERCEROCA <> H.IDTERCERO THEN CP.IDTERCEROCA
									ELSE H.IDTERCERO
								END AS IDTERCERO,
								CASE
									WHEN CP.COBRARA = 'O' THEN COALESCE(NULLIF(D.IDPLAN, ''), H.IDPLAN)
									WHEN NULLIF(CP.IDTERCEROCA, '') IS NOT NULL AND CP.IDTERCEROCA <> H.IDTERCERO
										THEN COALESCE(NULLIF(CP.IDPLAN, ''), NULLIF(D.IDPLAN, ''), H.IDPLAN)
									ELSE COALESCE(NULLIF(D.IDPLAN, ''), H.IDPLAN)
								END AS IDPLAN
						) PAGADOR
						OUTER APPLY
						(
							SELECT TOP (1) CAST(S.VLRSERVICIO AS DECIMAL(19,4)) AS VLRSERVICIO
							FROM SERTOT S
							WHERE S.IDTERCERO = PAGADOR.IDTERCERO
							  AND S.IDPLAN = PAGADOR.IDPLAN
							  AND S.IDSERVICIO = D.IDSERVICIO
							  AND CONVERT(DATE, S.FECHAINIFD) <= CONVERT(DATE, Q.FECHA)
							  AND CONVERT(DATE, S.FECHAFINFD) >= CONVERT(DATE, Q.FECHA)
							  AND CONVERT(DATE, S.FECHAINI) <= CONVERT(DATE, Q.FECHA)
							  AND CONVERT(DATE, S.FECHAFIN) >= CONVERT(DATE, Q.FECHA)
							ORDER BY S.FECHAINIFD DESC, S.FECHAINI DESC
						) ST
						WHERE D.CONSECUTIVO = @CONSECUTIVO_CX_FACT
						  AND COALESCE(D.PAQUETE, 0) = 0
						  AND COALESCE(ST.VLRSERVICIO, 0) > 0
					)
					SELECT
						@CXMAYOR_FACT = MAX(CASE WHEN ORDEN = 1 THEN IDSERVICIO END),
						@CXMENOR_FACT = MAX(CASE WHEN ORDEN = 2 THEN IDSERVICIO END)
					FROM DATOS_TARIFA
					WHERE ORDEN <= 2

					SELECT @CUPSMAYOR_FACT = LEFT(NULLIF(LTRIM(RTRIM(S.CODCUPS)), ''), 6)
					FROM SER S
					WHERE S.IDSERVICIO = @CXMAYOR_FACT

					SELECT @CUPSMENOR_FACT = LEFT(NULLIF(LTRIM(RTRIM(S.CODCUPS)), ''), 6)
					FROM SER S
					WHERE S.IDSERVICIO = @CXMENOR_FACT

					IF NULLIF(LTRIM(RTRIM(@CXMAYOR_FACT)), '') IS NOT NULL
					   AND NULLIF(LTRIM(RTRIM(@CUPSMAYOR_FACT)), '') IS NOT NULL
					BEGIN
						UPDATE HACTRAN
						SET CUPSPPALQX = @CUPSMAYOR_FACT
						WHERE CNSHACTRAN = @CNSHACTRAN_FACT

						IF NULLIF(LTRIM(RTRIM(@CXMENOR_FACT)), '') IS NOT NULL
						   AND NULLIF(LTRIM(RTRIM(@CUPSMENOR_FACT)), '') IS NOT NULL
						BEGIN
							UPDATE HACTRAN
							SET CUPSSECQX = @CUPSMENOR_FACT
							WHERE CNSHACTRAN = @CNSHACTRAN_FACT
						END
					END
				END
			END

			SELECT 'OK' OK

		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END CATCH
	END 
   IF @METODO='HPRED_SOAT'     
   BEGIN         
      SELECT @NOADMISION=NOADMISION        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      NOADMISION  VARCHAR(20)   '$.NOADMISION'
      )
      SELECT 'OK'OK
      SELECT COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT
      ,      HPRE.PREFIJO                
      ,      PRE.NOM_PREFIJO             
      ,      HPRED.NOPRESTACION          
      ,      HPRED.NOITEM                
      ,      HPRED.IDSERVICIO            
      ,      SER.DESCSERVICIO            
      ,      HPRED.CANTIDAD              
      ,      HPRED.VALOR                 
      ,      COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)                         AS VLRSUBTOTAL
      ,      HPRED.VALORCOPAGO           
      ,      HPRED.VALORPCOMP            
      ,      HPRED.VALOREXCEDENTE        
      ,      COALESCE(HPRED.ENCARGOS, 0)  AS ENCARGOS
      ,      HPRED.USUARIO               
      ,      COALESCE(HPRED.FACTURADA, 0) AS FACTURADA
      ,      COALESCE(HPRED.N_FACTURA, '')AS N_FACTURA
      ,      COALESCE(HPRED.NOCOBRABLE, 0)AS NOCOBRABLE
      ,      COALESCE(HPRED.PAQUETE, 0)   AS PAQUETE
      ,      HPRED.IDPLAN                
      ,      HPRED.CANTIDADORIGINAL      
      ,      HPRED.FECHA                 
      ,      HPRED.VIA                   
      ,      COALESCE(HPRED.COMENTARIOS, '')  AS COMENTARIOS
      ,      HPRED.IDCONCEPTORIPS        
      ,      HPRED.DXPPAL                
      ,      HPRED.TIPOSERCIRUGIA        
      ,      COALESCE(HPRED.COBRARA, 'C') AS COBRARA
      ,      HPRED.IDTERCEROCA           
      ,      COALESCE(HPRED.PCUBRIMIENTO, 0)  AS PCUBRIMIENTO
      ,      COALESCE(HPRED.TIPODTO, 'N') AS TIPODTO
      ,      COALESCE(HPRED.PEDIDOINV, 0) AS PEDIDOINV             
      ,      COALESCE(HPRED.AQUIENCOBRO, 'N') AS AQUIENCOBRO
      ,      COALESCE(HPRED.CODCUPS, '')  AS CODCUPS
      ,      COALESCE(HPRED.MANUAL, 0)    AS MANUAL
      ,      COALESCE(HPRED.DESCUENTO, 0) AS DESCUENTO
      ,      CAST(CASE WHEN EXISTS (SELECT 1
	      FROM TGEN
	      WHERE TABLA = 'CARGOS' AND CAMPO = 'CAMBIAVALOR' AND CODIGO = HPRED.IDSERVICIO) THEN 1
                                           ELSE 0 END AS BIT)    AS ESMANUAL
      ,      HPRED.NOAUTORIZACION        
      ,      HPRED.IDPROVEEDOR           
      ,      TER.RAZONSOCIAL              AS NOM_PROVEEDOR
      ,      SERCIRUGIA.DESCSERVICIO      AS DESCIRUGIA
      ,      HPRED.IDCIRUGIA  
      ,      HPRED.CONSECUTIVOCX   
      ,      HPRED.ITEMCIRUGIA
      ,      CASE WHEN  COALESCE(IDCIRUGIA,'')<>'' AND LEN(HPRED.COMENTARIOS)>10 THEN CONCAT('Tipo: ',LTRIM(RTRIM(PARSENAME(REPLACE(HPRED.COMENTARIOS, ',', '.'), 3))))  ELSE '' END TIPOCX
      ,      CASE WHEN  COALESCE(IDCIRUGIA,'')<>'' AND LEN(HPRED.COMENTARIOS)>10 THEN CONCAT(LEFT(SUBSTRING(HPRED.COMENTARIOS,CHARINDEX('Lq:',HPRED.COMENTARIOS) + 3,LEN(HPRED.COMENTARIOS)),CHARINDEX('.', SUBSTRING(HPRED.COMENTARIOS,CHARINDEX('Lq:', HPRED.COMENTARIOS) + 3,LEN(HPRED.COMENTARIOS))) - 1),'%') ELSE '' END FACTORCX
      ,      CASE WHEN COALESCE(IDCIRUGIA,'')<>'' THEN HPRED.GRUPOQX_UVR_CX ELSE NULL END AS GRUPOUVR
      ,      HPRE.NOADMISION             
      ,      HPRE.FECHA                    AS FECHA_PRESTACION
      ,      HPRE.IDAREA                 
      ,      HPRE.CCOSTO                  AS CCOSTO_PRESTACION
      ,      HPRE.IDMEDICO
      FROM       [dbo].[HPRED]           
      INNER JOIN HPRE                     ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
      INNER JOIN PRE                      ON PRE.PREFIJO = HPRE.PREFIJO
      INNER JOIN SER                      ON SER.IDSERVICIO = HPRED.IDSERVICIO
      LEFT JOIN  TER                      ON TER.IDTERCERO = HPRED.IDPROVEEDOR
      LEFT JOIN  SER           SERCIRUGIA ON SERCIRUGIA.IDSERVICIO = HPRED.IDCIRUGIA
      WHERE HPRE.NOADMISION=@NOADMISION
      ORDER BY COALESCE(HPRED.GFACSOAT, 0)
      ,        HPRE.PREFIJO
      ,        HPRED.FECHA DESC 
                 
   END
   IF @METODO='HPRED_SOATCIRU'     
   BEGIN    
      DECLARE @PRECIR VARCHAR(20)=DBO.FNK_VALORVARIABLE('IDCIRPREFIJO')
      DECLARE @FACTSOAT SMALLINT
      SELECT @NOADMISION=NOADMISION, 
      @FACTSOAT =GFACSOAT
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      NOADMISION  VARCHAR(20)   '$.NOADMISION',
      GFACSOAT SMALLINT   '$.GFACSOAT'
      )
      DECLARE @PRECIRU VARCHAR(20)
      SELECT @PRECIRU=DBO.FNK_VALORVARIABLE('IDCIRPREFIJO')
      SELECT 'OK'OK
      SELECT COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT
      ,      HPRE.PREFIJO                
      ,      PRE.NOM_PREFIJO             
      ,      HPRED.NOPRESTACION          
      ,      HPRED.NOITEM                
      ,      HPRED.IDSERVICIO            
      ,      SER.DESCSERVICIO            
      ,      HPRED.CANTIDAD              
      ,      HPRED.VALOR                 
      ,      COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)                         AS VLRSUBTOTAL
      ,      HPRED.VALORCOPAGO           
      ,      HPRED.VALORPCOMP            
      ,      HPRED.VALOREXCEDENTE        
      ,      COALESCE(HPRED.ENCARGOS, 0)  AS ENCARGOS
      ,      HPRED.USUARIO               
      ,      COALESCE(HPRED.FACTURADA, 0) AS FACTURADA
      ,      COALESCE(HPRED.N_FACTURA, '')AS N_FACTURA
      ,      COALESCE(HPRED.NOCOBRABLE, 0)AS NOCOBRABLE
      ,      COALESCE(HPRED.PAQUETE, 0)   AS PAQUETE
      ,      HPRED.IDPLAN                
      ,      HPRED.CANTIDADORIGINAL      
      ,      HPRED.FECHA                 
      ,      HPRED.VIA                   
      ,      COALESCE(HPRED.COMENTARIOS, '')  AS COMENTARIOS
      ,      HPRED.IDCONCEPTORIPS        
      ,      HPRED.DXPPAL                
      ,      HPRED.TIPOSERCIRUGIA        
      ,      COALESCE(HPRED.COBRARA, 'C') AS COBRARA
      ,      HPRED.IDTERCEROCA           
      ,      COALESCE(HPRED.PCUBRIMIENTO, 0)  AS PCUBRIMIENTO
      ,      COALESCE(HPRED.TIPODTO, 'N') AS TIPODTO
      ,      COALESCE(HPRED.PEDIDOINV, 0) AS PEDIDOINV          
      ,      COALESCE(HPRED.AQUIENCOBRO, 'N') AS AQUIENCOBRO
      ,      COALESCE(HPRED.CODCUPS, '')  AS CODCUPS
      ,      COALESCE(HPRED.MANUAL, 0)    AS MANUAL
      ,      COALESCE(HPRED.DESCUENTO, 0) AS DESCUENTO
      ,      COALESCE(HPRED.FACTOR, 0) AS FACTOR
      ,      CAST(CASE WHEN EXISTS (SELECT 1
	      FROM TGEN
	      WHERE TABLA = 'CARGOS' AND CAMPO = 'CAMBIAVALOR' AND CODIGO = HPRED.IDSERVICIO) THEN 1
                                           ELSE 0 END AS BIT)    AS ESMANUAL
      ,      HPRED.NOAUTORIZACION        
      ,      HPRED.IDPROVEEDOR           
      ,      TER.RAZONSOCIAL              AS NOM_PROVEEDOR
      ,      SERCIRUGIA.DESCSERVICIO      AS DESCIRUGIA
      ,      HPRED.IDCIRUGIA  
      ,      HPRED.CONSECUTIVOCX   
      ,      HPRED.ITEMCIRUGIA
      ,      CASE WHEN  COALESCE(IDCIRUGIA,'')<>'' AND LEN(HPRED.COMENTARIOS)>10 THEN CONCAT('Tipo: ',LTRIM(RTRIM(PARSENAME(REPLACE(HPRED.COMENTARIOS, ',', '.'), 3))))  ELSE '' END TIPOCX
      ,      CASE WHEN  COALESCE(IDCIRUGIA,'')<>'' AND LEN(HPRED.COMENTARIOS)>10 THEN CONCAT(LEFT(SUBSTRING(HPRED.COMENTARIOS,CHARINDEX('Lq:',HPRED.COMENTARIOS) + 3,LEN(HPRED.COMENTARIOS)),CHARINDEX('.', SUBSTRING(HPRED.COMENTARIOS,CHARINDEX('Lq:', HPRED.COMENTARIOS) + 3,LEN(HPRED.COMENTARIOS))) - 1),'%') ELSE '' END FACTORCX
      ,      CASE WHEN COALESCE(IDCIRUGIA,'')<>'' THEN HPRED.GRUPOQX_UVR_CX ELSE NULL END AS GRUPOUVR
      ,      HPRE.NOADMISION             
      ,      HPRE.FECHA                    AS FECHA_PRESTACION
      ,      HPRE.IDAREA                 
      ,      HPRE.CCOSTO                  AS CCOSTO_PRESTACION
      ,      HPRE.IDMEDICO
      FROM       [dbo].[HPRED]           
      INNER JOIN HPRE                     ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
      INNER JOIN PRE                      ON PRE.PREFIJO = HPRE.PREFIJO
      INNER JOIN SER                      ON SER.IDSERVICIO = HPRED.IDSERVICIO
      LEFT JOIN  TER                      ON TER.IDTERCERO = HPRED.IDPROVEEDOR
      LEFT JOIN  SER           SERCIRUGIA ON SERCIRUGIA.IDSERVICIO = HPRED.IDCIRUGIA
      WHERE HPRE.NOADMISION=@NOADMISION
      AND HPRE.PREFIJO=@PRECIRU
      AND HPRED.GFACSOAT=@FACTSOAT
      ORDER BY COALESCE(HPRED.GFACSOAT, 0)
      ,        HPRE.PREFIJO
      ,        HPRED.FECHA DESC 
                 
   END
   IF @METODO='HPRED_SOATSER'     
   BEGIN    
      DECLARE @PRE VARCHAR(20)
      DECLARE @FACTSOATS SMALLINT
      DECLARE @IDCIRUGIA VARCHAR(20) 
      DECLARE @ITEMCIRUGIAX SMALLINT
      DECLARE @CONSECUTIVOCX VARCHAR(20)
      DECLARE @WHERE_ADICIONAL VARCHAR(256)
      DECLARE @SQL VARCHAR(MAX)
      SELECT @NOADMISION=NOADMISION, 
      @FACTSOATS =GFACSOAT,
      @PRE=PREFIJO,@IDCIRUGIA=IDCIRUGIA,
      @ITEMCIRUGIAX=ITEMCIRUGIA,
      @CONSECUTIVOCX=CONSECUTIVOCX,
      @WHERE_ADICIONAL=WHERE_ADICIONAL
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      NOADMISION  VARCHAR(20)   '$.NOADMISION',
      PREFIJO  VARCHAR(20)   '$.PREFIJO',
      IDCIRUGIA  VARCHAR(20)   '$.IDCIRUGIA',
      ITEMCIRUGIA  SMALLINT   '$.ITEMCIRUGIA',
      CONSECUTIVOCX  VARCHAR(20)   '$.CONSECUTIVOCX',
      WHERE_ADICIONAL  VARCHAR(256)   '$.WHERE_ADICIONAL',
      GFACSOAT SMALLINT   '$.GFACSOAT'
      )
      SELECT 'OK'OK
      PRINT @IDCIRUGIA
      SET @SQL='
      SELECT ROW_NUMBER() OVER(PARTITION BY HPRE.NOPRESTACION ORDER BY HPRE.NOPRESTACION ASC) IDHPRED 
      ,COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT
      ,      HPRE.PREFIJO 
      ,      PRE.NOM_PREFIJO             
      ,      HPRED.NOPRESTACION          
      ,      HPRED.NOITEM   
      ,      CONCAT(HPRED.IDSERVICIO,''-'',SER.DESCSERVICIO) AS DESCSERVICIO1
      ,      HPRED.IDSERVICIO            
      ,      SER.DESCSERVICIO            
      ,      CONVERT(INT,HPRED.CANTIDAD)CANTIDAD
      ,      CONVERT(DECIMAL(14,2),HPRED.VALOR) VALOR
      ,      CONVERT(DECIMAL(14,2),COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0))                         AS VLRSUBTOTAL
      ,      HPRED.VALORCOPAGO           
      ,      HPRED.VALORPCOMP            
      ,      CONVERT(DECIMAL(14,2),HPRED.VALOREXCEDENTE)   VALOREXCEDENTE   
      ,      COALESCE(HPRED.ENCARGOS, 0)  AS ENCARGOS
      ,      HPRED.USUARIO               
      ,      COALESCE(HPRED.FACTURADA, 0) AS FACTURADA
      ,      COALESCE(HPRED.N_FACTURA, '''')AS N_FACTURA
      ,      COALESCE(HPRED.NOCOBRABLE, 0)AS NOCOBRABLE
      ,      COALESCE(HPRED.PAQUETE, 0)   AS PAQUETE
      ,      HPRED.IDPLAN                
      ,      HPRED.CANTIDADORIGINAL      
      ,      HPRE.FECHA                 
      ,      HPRED.VIA                   
      ,      COALESCE(HPRED.COMENTARIOS, '''')  AS COMENTARIOS
      ,      HPRED.IDCONCEPTORIPS        
      ,      HPRED.DXPPAL                
      ,      HPRED.TIPOSERCIRUGIA        
      ,      COALESCE(HPRED.COBRARA, ''C'') AS COBRARA
      ,      HPRED.IDTERCEROCA           
      ,      COALESCE(HPRED.PCUBRIMIENTO, 0)  AS PCUBRIMIENTO
      ,      COALESCE(HPRED.TIPODTO, ''N'') AS TIPODTO
      ,      COALESCE(HPRED.PEDIDOINV, 0) AS PEDIDOINV
      ,      COALESCE(HPRED.AQUIENCOBRO, ''N'') AS AQUIENCOBRO
      ,      COALESCE(HPRED.CODCUPS, '''')  AS CODCUPS
      ,      COALESCE(HPRED.MANUAL, 0)    AS MANUAL
      ,      COALESCE(HPRED.DESCUENTO, 0) AS DESCUENTO
      ,      CAST(CASE WHEN EXISTS (SELECT 1
	      FROM TGEN
	      WHERE TABLA = ''CARGOS'' AND CAMPO = ''CAMBIAVALOR'' AND CODIGO = HPRED.IDSERVICIO) THEN 1  ELSE 0 END AS BIT)    AS ESMANUAL
      ,      HPRED.NOAUTORIZACION        
      ,      HPRED.IDPROVEEDOR           
      ,      TER.RAZONSOCIAL              AS NOM_PROVEEDOR
      ,      SERCIRUGIA.DESCSERVICIO      AS DESCIRUGIA
      ,      HPRED.IDCIRUGIA  
      ,      HPRED.CONSECUTIVOCX   
      ,      HPRED.ITEMCIRUGIA
      ,      CASE WHEN  COALESCE(IDCIRUGIA,'''')<>'''' AND LEN(HPRED.COMENTARIOS)>10 THEN CONCAT(''Tipo: '',LTRIM(RTRIM(PARSENAME(REPLACE(HPRED.COMENTARIOS, '','', ''.''), 3))))  ELSE '''' END TIPOCX
      ,      CASE WHEN  COALESCE(IDCIRUGIA,'''')<>'''' AND LEN(HPRED.COMENTARIOS)>10 THEN CONCAT(LEFT(SUBSTRING(HPRED.COMENTARIOS,CHARINDEX(''Lq:'',HPRED.COMENTARIOS) + 3,LEN(HPRED.COMENTARIOS)),CHARINDEX(''.'', SUBSTRING(HPRED.COMENTARIOS,CHARINDEX(''Lq:'', HPRED.COMENTARIOS) + 3,LEN(HPRED.COMENTARIOS))) - 1),''%'') ELSE '''' END FACTORCX
      ,      CASE WHEN COALESCE(IDCIRUGIA,'''')<>'''' THEN HPRED.GRUPOQX_UVR_CX ELSE NULL END AS GRUPOUVR
      ,      HPRE.NOADMISION             
      ,      dbo.FNK_FECHA_DDMMAA(HPRE.FECHA)                    AS FECHA_PRESTACION
      ,      HPRE.IDAREA                 
      ,      HPRE.CCOSTO                  AS CCOSTO_PRESTACION
      ,      HPRE.IDMEDICO
      ,      MED.NOMBRE AS N_MEDICO
      FROM       [dbo].[HPRED]           
      INNER JOIN HPRE                     ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
      INNER JOIN PRE                      ON PRE.PREFIJO = HPRE.PREFIJO
      INNER JOIN SER                      ON SER.IDSERVICIO = HPRED.IDSERVICIO
      LEFT JOIN  TER                      ON TER.IDTERCERO = HPRED.IDPROVEEDOR
      LEFT JOIN  SER           SERCIRUGIA ON SERCIRUGIA.IDSERVICIO = HPRED.IDCIRUGIA
      LEFT JOIN  MED                      ON HPRE.IDMEDICO=MED.IDMEDICO
      WHERE HPRE.NOADMISION='''+@NOADMISION+'''
      AND HPRED.GFACSOAT='+CAST(@FACTSOATS AS VARCHAR(1))
      IF COALESCE(@PRE,'')<>''
      BEGIN 
          SET @SQL+=' AND HPRE.PREFIJO='''+@PRE+''''
      END
      IF COALESCE(@IDCIRUGIA,'')<>''
      BEGIN
         SET @SQL+=' AND HPRED.IDCIRUGIA='''+@IDCIRUGIA+''' AND  HPRED.ITEMCIRUGIA = '+CAST(@ITEMCIRUGIAX AS VARCHAR(1))+' AND  HPRED.CONSECUTIVOCX =  '''+ @CONSECUTIVOCX +''''
      END
      IF COALESCE(@WHERE_ADICIONAL,'')<>''
      BEGIN
         SET @SQL+=' AND '+@WHERE_ADICIONAL
      END
      SET @SQL+='  ORDER BY HPRE.NOPRESTACION '
      PRINT @SQL
      EXEC(@SQL)
      RETURN          
   END
   IF @METODO='HPRED_SOATPRE'     
   BEGIN    
      DECLARE @FACTSOATP SMALLINT
      SELECT @NOADMISION=NOADMISION, 
      @FACTSOATP =GFACSOAT
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      NOADMISION  VARCHAR(20)   '$.NOADMISION',
      GFACSOAT SMALLINT   '$.GFACSOAT'
      )
      SELECT 'OK'OK
      SELECT COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT
      ,      HPRE.PREFIJO                
      ,      PRE.NOM_PREFIJO             
      ,      SUM(HPRED.CANTIDAD) AS CANTIDAD
      ,      SUM(COALESCE(HPRED.CANTIDAD,0) * COALESCE(HPRED.VALOR,0)) AS VALOR_TOTAL
      , CASE WHEN HPRE.PREFIJO=DBO.FNK_VALORVARIABLE('IDCIRPREFIJO') THEN 'Si' ELSE 'No' END AS ES_CIRUGIA
      FROM       [dbo].[HPRED]           
      INNER JOIN HPRE                     ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
      INNER JOIN PRE                      ON PRE.PREFIJO = HPRE.PREFIJO
      WHERE HPRE.NOADMISION=@NOADMISION
      AND HPRED.GFACSOAT=@FACTSOATP
      AND COALESCE(HPRED.NOCOBRABLE, 0) = 0
      GROUP BY  COALESCE(HPRED.GFACSOAT, 0)
      ,      HPRE.PREFIJO                
      ,      PRE.NOM_PREFIJO   
      ,CASE WHEN HPRE.PREFIJO=DBO.FNK_VALORVARIABLE('IDCIRPREFIJO') THEN 'Si' ELSE 'No' END 
      ORDER BY COALESCE(HPRED.GFACSOAT, 0)
      ,        HPRE.PREFIJO
                 
   END
   IF @METODO='TRAER_IDAREA'     
   BEGIN
     DECLARE @CCOSTO VARCHAR(20)
      SELECT @CCOSTO=CCOSTO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         CCOSTO  VARCHAR(20)   '$.CCOSTO'
      )
      SELECT 'OK',IDAREA FROM CEN WHERE CCOSTO=@CCOSTO
      RETURN
   END  
   IF @METODO='CONSULTA_HPRE'     
   BEGIN         
      SELECT   @NOADMISION=NOADMISION,@NOPRESTACION =NOPRESTACION 
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      NOADMISION  VARCHAR(20)   '$.NOADMISION',
      NOPRESTACION  VARCHAR(20)   '$.NOPRESTACION'
      )
                 
   SELECT 
     HPRE.CCOSTO,                 
     HPRE.IDAREA,                   
     HPRE.NOPRESTACION,             
     HPRE.NOADMISION,               
     HPRE.PREFIJO,                  
     HPRE.FECHA,
     HPRE.IDTERCEROCA,
     HPRE.IDPLAN,
     HPRE.COBRARA,
     HPRE.IDMEDICO,
     HPRE.VALORTOTAL,
     HPRE.VALORCOPAGO,
     COALESCE(HPRE.VALORPCOMP, 0) AS VALORPCOMP,
     HPRE.VALOREXEDENTE,
     COALESCE(HPRE.ESDEINV, 0) AS ESDEINV,
     COALESCE(HPRE.PEDIDOINV, 0) AS PEDIDOINV,
     HPRE.USUARIO,
     HPRE.PROCEDENCIA,
     PRE.NOM_PREFIJO,
     HPRE.CCOSTOAUX,
     COALESCE(PRE.PREFIJOCOOP1, '') AS PREFIJOCOOP1,
     COALESCE(PRE.PREFIJOCOOP2, '') AS PREFIJOCOOP2,
     COALESCE(PRE.PREFIJOCOOP3, '') AS PREFIJOCOOP3,
     COALESCE(PRE.PREFIJOCOOP4, '') AS PREFIJOCOOP4
      FROM HPRE
      LEFT JOIN PRE ON PRE.PREFIJO = HPRE.PREFIJO
      WHERE HPRE.NOADMISION = @NOADMISION
        AND HPRE.NOPRESTACION = @NOPRESTACION
   END

	-- =============================================
	-- MARCAR_NOCOBRABLE_ITEM: toggle no cobrable (SOAT, sin reliquidar ?rbol)
	-- =============================================
	IF @METODO = 'MARCAR_NOCOBRABLE_ITEM'
	BEGIN
		DECLARE @NOPRESTACION_NC VARCHAR(20), @NOITEM_NC SMALLINT, @IDSEDE_NC VARCHAR(5)

		SELECT @NOADMISION = NOADMISION,
			   @NOPRESTACION_NC = NOPRESTACION,
			   @NOITEM_NC = NOITEM
		FROM OPENJSON(@PARAMETROS) WITH (
			NOADMISION VARCHAR(20) '$.NOADMISION',
			NOPRESTACION VARCHAR(20) '$.NOPRESTACION',
			NOITEM SMALLINT '$.NOITEM'
		)

		IF @NOPRESTACION_NC IS NULL OR @NOITEM_NC IS NULL
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'Debe indicar NOPRESTACION y NOITEM'
			RETURN
		END

		IF NOT EXISTS (
			SELECT 1
			FROM HPRED D
			INNER JOIN HPRE H ON H.NOPRESTACION = D.NOPRESTACION
			WHERE D.NOPRESTACION = @NOPRESTACION_NC
			  AND D.NOITEM = @NOITEM_NC
			  AND (@NOADMISION IS NULL OR H.NOADMISION = @NOADMISION)
		)
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'El ?tem no existe o no pertenece a la admisi?n indicada'
			RETURN
		END

		IF EXISTS (
			SELECT 1
			FROM HPRED
			WHERE NOPRESTACION = @NOPRESTACION_NC
			  AND NOITEM = @NOITEM_NC
			  AND COALESCE(FACTURADA, 0) = 1
		)
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'No se puede modificar un ?tem facturado'
			RETURN
		END

		BEGIN TRY
			IF dbo.FNK_VALORVARIABLE('IXCOUNTRY') <> 'PERU'
				EXEC SPK_NOCOBRABLEMANUAL @NOPRESTACION_NC, @NOITEM_NC, 1, @USUARIO
			ELSE
			BEGIN
				SELECT @IDSEDE_NC = IDSEDE FROM HPRE WHERE NOPRESTACION = @NOPRESTACION_NC
				EXEC SPK_ADD_DEL_COPAGOS_HPRED @NOPRESTACION_NC, @NOITEM_NC, 1, @IDSEDE_NC, @USUARIO
			END
		END TRY
		BEGIN CATCH
			SELECT 'KO' OK
			SELECT ERROR = 'Error al marcar como no cobrable: ' + ERROR_MESSAGE()
			RETURN
		END CATCH

		SELECT 'OK' OK

		SELECT
			HPRED.NOPRESTACION,
			HPRED.NOITEM,
			HPRE.PREFIJO,
			HPRE.NOADMISION,
			COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT,
			COALESCE(HPRED.NOCOBRABLE, 0) AS NOCOBRABLE,
			COALESCE(HPRED.PAQUETE, 0) AS PAQUETE,
			CONVERT(DECIMAL(14, 2), HPRED.VALOR) AS VALOR,
			CONVERT(DECIMAL(14, 2), HPRED.VALORCOPAGO) AS VALORCOPAGO,
			CONVERT(DECIMAL(14, 2), HPRED.VALOREXCEDENTE) AS VALOREXCEDENTE,
			CONVERT(DECIMAL(14, 2), HPRED.VALORPCOMP) AS VALORPCOMP,
			CONVERT(DECIMAL(14, 2), COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)) AS VLRSUBTOTAL,
			(SELECT COALESCE(SUM(D2.CANTIDAD), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND H2.PREFIJO = HPRE.PREFIJO AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0)) AS TOTAL_PREFIJO_CANTIDAD,
			(SELECT COALESCE(SUM(D2.VALOREXCEDENTE), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND H2.PREFIJO = HPRE.PREFIJO AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0)) AS TOTAL_PREFIJO_VALOR,
			(SELECT COUNT(*) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND H2.PREFIJO = HPRE.PREFIJO AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0)) AS TOTAL_PREFIJO_ITEMS,
			(SELECT COALESCE(SUM(COALESCE(D2.CANTIDAD, 0) * COALESCE(D2.VALOR, 0)), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0) AND COALESCE(D2.FACTURADA, 0) = 0 AND COALESCE(D2.NOCOBRABLE, 0) = 0) AS TOTAL_RESPONSABLE_VALOR
		FROM HPRED
		INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
		WHERE HPRED.NOPRESTACION = @NOPRESTACION_NC
		  AND HPRED.NOITEM = @NOITEM_NC

		RETURN
	END

	-- =============================================
	-- MARCAR_PAQUETE_ITEM: toggle paquete (SOAT, sin reliquidar ?rbol)
	-- =============================================
	IF @METODO = 'MARCAR_PAQUETE_ITEM'
	BEGIN
		DECLARE @NOPRESTACION_PQ VARCHAR(20), @NOITEM_PQ SMALLINT

		SELECT @NOADMISION = NOADMISION,
			   @NOPRESTACION_PQ = NOPRESTACION,
			   @NOITEM_PQ = NOITEM
		FROM OPENJSON(@PARAMETROS) WITH (
			NOADMISION VARCHAR(20) '$.NOADMISION',
			NOPRESTACION VARCHAR(20) '$.NOPRESTACION',
			NOITEM SMALLINT '$.NOITEM'
		)

		IF @NOPRESTACION_PQ IS NULL OR @NOITEM_PQ IS NULL
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'Debe indicar NOPRESTACION y NOITEM'
			RETURN
		END

		IF NOT EXISTS (
			SELECT 1
			FROM HPRED D
			INNER JOIN HPRE H ON H.NOPRESTACION = D.NOPRESTACION
			WHERE D.NOPRESTACION = @NOPRESTACION_PQ
			  AND D.NOITEM = @NOITEM_PQ
			  AND (@NOADMISION IS NULL OR H.NOADMISION = @NOADMISION)
		)
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'El ?tem no existe o no pertenece a la admisi?n indicada'
			RETURN
		END

		IF EXISTS (
			SELECT 1
			FROM HPRED
			WHERE NOPRESTACION = @NOPRESTACION_PQ
			  AND NOITEM = @NOITEM_PQ
			  AND COALESCE(FACTURADA, 0) = 1
		)
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'No se puede modificar un ?tem facturado'
			RETURN
		END

		BEGIN TRY
			UPDATE HPRED
			SET PAQUETE = 1 - COALESCE(PAQUETE, 0)
			WHERE NOPRESTACION = @NOPRESTACION_PQ
			  AND NOITEM = @NOITEM_PQ
		END TRY
		BEGIN CATCH
			SELECT 'KO' OK
			SELECT ERROR = 'Error al marcar paquete: ' + ERROR_MESSAGE()
			RETURN
		END CATCH

		SELECT 'OK' OK

		SELECT
			HPRED.NOPRESTACION,
			HPRED.NOITEM,
			HPRE.PREFIJO,
			HPRE.NOADMISION,
			COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT,
			COALESCE(HPRED.NOCOBRABLE, 0) AS NOCOBRABLE,
			COALESCE(HPRED.PAQUETE, 0) AS PAQUETE,
			CONVERT(DECIMAL(14, 2), HPRED.VALOR) AS VALOR,
			CONVERT(DECIMAL(14, 2), HPRED.VALORCOPAGO) AS VALORCOPAGO,
			CONVERT(DECIMAL(14, 2), HPRED.VALOREXCEDENTE) AS VALOREXCEDENTE,
			CONVERT(DECIMAL(14, 2), HPRED.VALORPCOMP) AS VALORPCOMP,
			CONVERT(DECIMAL(14, 2), COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)) AS VLRSUBTOTAL,
			(SELECT COALESCE(SUM(D2.CANTIDAD), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND H2.PREFIJO = HPRE.PREFIJO AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0)) AS TOTAL_PREFIJO_CANTIDAD,
			(SELECT COALESCE(SUM(D2.VALOREXCEDENTE), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND H2.PREFIJO = HPRE.PREFIJO AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0)) AS TOTAL_PREFIJO_VALOR,
			(SELECT COUNT(*) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND H2.PREFIJO = HPRE.PREFIJO AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0)) AS TOTAL_PREFIJO_ITEMS,
			(SELECT COALESCE(SUM(COALESCE(D2.CANTIDAD, 0) * COALESCE(D2.VALOR, 0)), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0) AND COALESCE(D2.FACTURADA, 0) = 0 AND COALESCE(D2.NOCOBRABLE, 0) = 0) AS TOTAL_RESPONSABLE_VALOR
		FROM HPRED
		INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
		WHERE HPRED.NOPRESTACION = @NOPRESTACION_PQ
		  AND HPRED.NOITEM = @NOITEM_PQ

		RETURN
	END

	-- =============================================
	-- ELIMINAR_ITEM: elimina detalle SOAT sin reliquidar ?rbol
	-- =============================================
	IF @METODO = 'ELIMINAR_ITEM'
	BEGIN
		DECLARE @NOPRESTACION_EL VARCHAR(20), @NOITEM_EL SMALLINT, @IDSERVICIO_EL VARCHAR(20)
		DECLARE @PREFIJO_EL VARCHAR(10), @GFACSOAT_EL SMALLINT, @CANT_RESTANTE_PREFIJO INT

		SELECT @NOADMISION = NOADMISION,
			   @NOPRESTACION_EL = NOPRESTACION,
			   @NOITEM_EL = NOITEM
		FROM OPENJSON(@PARAMETROS) WITH (
			NOADMISION VARCHAR(20) '$.NOADMISION',
			NOPRESTACION VARCHAR(20) '$.NOPRESTACION',
			NOITEM SMALLINT '$.NOITEM'
		)

		IF @NOPRESTACION_EL IS NULL OR @NOITEM_EL IS NULL
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'Debe indicar NOPRESTACION y NOITEM'
			RETURN
		END

		SELECT @IDSERVICIO_EL = D.IDSERVICIO,
			   @NOADMISION = COALESCE(@NOADMISION, H.NOADMISION),
			   @PREFIJO_EL = H.PREFIJO,
			   @GFACSOAT_EL = COALESCE(D.GFACSOAT, 0)
		FROM HPRED D
		INNER JOIN HPRE H ON H.NOPRESTACION = D.NOPRESTACION
		WHERE D.NOPRESTACION = @NOPRESTACION_EL
		  AND D.NOITEM = @NOITEM_EL
		  AND (@NOADMISION IS NULL OR H.NOADMISION = @NOADMISION)

		IF @IDSERVICIO_EL IS NULL
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'El ?tem no existe o no pertenece a la admisi?n indicada'
			RETURN
		END

		IF EXISTS(SELECT 1 FROM HPRED WHERE NOPRESTACION = @NOPRESTACION_EL AND NOITEM = @NOITEM_EL AND COALESCE(CXP, 0) = 1)
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'No se puede editar una Prestaci?n con Honorarios Medicos, Debe Anular El Honorario'
			RETURN
		END
		IF EXISTS(SELECT 1 FROM HPRED WHERE NOPRESTACION = @NOPRESTACION_EL AND NOITEM = @NOITEM_EL AND COALESCE(FACTURADA, 0) = 1)
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'Prestaci?n Ya Facturada'
			RETURN
		END
		IF EXISTS(SELECT 1 FROM HPRED WHERE NOPRESTACION = @NOPRESTACION_EL AND NOITEM = @NOITEM_EL AND COALESCE(ENCARGOS, 0) <> 0)
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'Prestacion en apoyodx, encargos<>0'
			RETURN
		END

		BEGIN TRY
			BEGIN TRAN
				DELETE FROM HPRED
				WHERE NOPRESTACION = @NOPRESTACION_EL
				  AND NOITEM = @NOITEM_EL
				  AND IDSERVICIO = @IDSERVICIO_EL

				IF NOT EXISTS(SELECT 1 FROM HPRED WHERE NOPRESTACION = @NOPRESTACION_EL)
				BEGIN
					DELETE FROM HPRE WHERE NOPRESTACION = @NOPRESTACION_EL
				END
			COMMIT

			IF EXISTS(SELECT 1 FROM HADM A WHERE A.NOADMISION = @NOADMISION AND COALESCE(A.COPAGONOAUTORIZACION, '') <> '' AND COALESCE(A.COPAGOVALOR, 0) > 0)
				EXEC SPK_RELIQUIDACOPAGOQX @NOADMISION
			ELSE
				EXEC SPK_COPAGOQX @NOADMISION, @NOPRESTACION_EL, @NOITEM_EL
		END TRY
		BEGIN CATCH
			IF @@TRANCOUNT > 0 ROLLBACK
			SELECT 'KO' OK
			SELECT ERROR = 'Error al eliminar prestacion: ' + ERROR_MESSAGE()
			RETURN
		END CATCH

		SELECT @CANT_RESTANTE_PREFIJO = COUNT(*)
		FROM HPRED D
		INNER JOIN HPRE H ON H.NOPRESTACION = D.NOPRESTACION
		WHERE H.NOADMISION = @NOADMISION
		  AND H.PREFIJO = @PREFIJO_EL
		  AND COALESCE(D.GFACSOAT, 0) = @GFACSOAT_EL

		SELECT 'OK' OK

		SELECT
			@NOPRESTACION_EL AS NOPRESTACION,
			@NOITEM_EL AS NOITEM,
			@PREFIJO_EL AS PREFIJO,
			@GFACSOAT_EL AS GFACSOAT,
			@CANT_RESTANTE_PREFIJO AS CANTIDAD_RESTANTE_PREFIJO,
			CASE WHEN @CANT_RESTANTE_PREFIJO = 0 THEN 0 ELSE (
				SELECT COALESCE(SUM(D2.CANTIDAD), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION
				WHERE H2.NOADMISION = @NOADMISION AND H2.PREFIJO = @PREFIJO_EL AND COALESCE(D2.GFACSOAT, 0) = @GFACSOAT_EL
			) END AS TOTAL_PREFIJO_CANTIDAD,
			CASE WHEN @CANT_RESTANTE_PREFIJO = 0 THEN 0 ELSE (
				SELECT COALESCE(SUM(D2.VALOREXCEDENTE), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION
				WHERE H2.NOADMISION = @NOADMISION AND H2.PREFIJO = @PREFIJO_EL AND COALESCE(D2.GFACSOAT, 0) = @GFACSOAT_EL
			) END AS TOTAL_PREFIJO_VALOR,
			@CANT_RESTANTE_PREFIJO AS TOTAL_PREFIJO_ITEMS,
			(SELECT COALESCE(SUM(COALESCE(D2.CANTIDAD, 0) * COALESCE(D2.VALOR, 0)), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION
			 WHERE H2.NOADMISION = @NOADMISION AND COALESCE(D2.GFACSOAT, 0) = @GFACSOAT_EL AND COALESCE(D2.FACTURADA, 0) = 0 AND COALESCE(D2.NOCOBRABLE, 0) = 0) AS TOTAL_RESPONSABLE_VALOR

		RETURN
	END

	-- =============================================
	-- GUARDAR_AUTORIZACION_ITEM: actualiza NOAUTORIZACION
	-- =============================================
	IF @METODO = 'GUARDAR_AUTORIZACION_ITEM'
	BEGIN
		DECLARE @NOPRESTACION_AU VARCHAR(20), @NOITEM_AU SMALLINT, @NOAUTORIZACION_AU VARCHAR(20)

		SELECT @NOADMISION = NOADMISION,
			   @NOPRESTACION_AU = NOPRESTACION,
			   @NOITEM_AU = NOITEM,
			   @NOAUTORIZACION_AU = NOAUTORIZACION
		FROM OPENJSON(@PARAMETROS) WITH (
			NOADMISION VARCHAR(20) '$.NOADMISION',
			NOPRESTACION VARCHAR(20) '$.NOPRESTACION',
			NOITEM SMALLINT '$.NOITEM',
			NOAUTORIZACION VARCHAR(20) '$.NOAUTORIZACION'
		)

		IF @NOPRESTACION_AU IS NULL OR @NOITEM_AU IS NULL
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'Debe indicar NOPRESTACION y NOITEM'
			RETURN
		END

		BEGIN TRY
			UPDATE HPRED
			SET NOAUTORIZACION = COALESCE(@NOAUTORIZACION_AU, '')
			WHERE NOPRESTACION = @NOPRESTACION_AU
			  AND NOITEM = @NOITEM_AU
		END TRY
		BEGIN CATCH
			SELECT 'KO' OK
			SELECT ERROR = 'Error al guardar autorizaci?n: ' + ERROR_MESSAGE()
			RETURN
		END CATCH

		SELECT 'OK' OK
		SELECT
			HPRED.NOPRESTACION,
			HPRED.NOITEM,
			HPRE.PREFIJO,
			HPRE.NOADMISION,
			COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT,
			COALESCE(HPRED.NOAUTORIZACION, '') AS NOAUTORIZACION,
			HPRED.IDSERVICIO,
			SER.DESCSERVICIO,
			CONVERT(INT, HPRED.CANTIDAD) AS CANTIDAD,
			CONVERT(DECIMAL(14, 2), HPRED.VALOR) AS VALOR,
			CONVERT(DECIMAL(14, 2), COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)) AS VLRSUBTOTAL,
			CONVERT(DECIMAL(14, 2), HPRED.VALORCOPAGO) AS VALORCOPAGO,
			CONVERT(DECIMAL(14, 2), HPRED.VALOREXCEDENTE) AS VALOREXCEDENTE,
			CONVERT(DECIMAL(14, 2), HPRED.VALORPCOMP) AS VALORPCOMP,
			COALESCE(HPRED.NOCOBRABLE, 0) AS NOCOBRABLE,
			COALESCE(HPRED.PAQUETE, 0) AS PAQUETE
		FROM HPRED
		INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
		INNER JOIN SER ON SER.IDSERVICIO = HPRED.IDSERVICIO
		WHERE HPRED.NOPRESTACION = @NOPRESTACION_AU
		  AND HPRED.NOITEM = @NOITEM_AU
		RETURN
	END

	-- =============================================
	-- EDITAR_ITEM / AGREGAR_ITEM: guarda detalle SOAT
	-- =============================================
	IF @METODO IN ('EDITAR_ITEM', 'AGREGAR_ITEM')
	BEGIN
		DECLARE @JSON_HPRED NVARCHAR(MAX)
		DECLARE @CANTIDAD_IT SMALLINT, @VALOR_IT DECIMAL(14, 2), @PAQUETE_IT SMALLINT
		DECLARE @COMENTARIOS_IT VARCHAR(2048), @TIPODTO_IT VARCHAR(1), @DESCUENTO_IT DECIMAL(14, 2)
		DECLARE @MANUAL_IT SMALLINT, @NOPRESTACION_IT VARCHAR(20), @NOITEM_IT SMALLINT, @IDSERVICIO_IT VARCHAR(20)
		DECLARE @IDPROVEEDOR_IT VARCHAR(20), @GFACSOAT_IT SMALLINT, @NOAUTORIZACION_IT VARCHAR(20)
		DECLARE @IDAREA_IT VARCHAR(20), @IDSEDE_IT VARCHAR(5)

		SELECT @NOADMISION = NOADMISION, @JSON_HPRED = HPRED
		FROM OPENJSON(@PARAMETROS) WITH (
			NOADMISION VARCHAR(20) '$.NOADMISION',
			HPRED NVARCHAR(MAX) AS JSON
		)

		SELECT @NOPRESTACION_IT = NOPRESTACION, @NOITEM_IT = NOITEM, @IDSERVICIO_IT = IDSERVICIO,
			   @CANTIDAD_IT = CANTIDAD, @VALOR_IT = VALOR, @PAQUETE_IT = PAQUETE,
			   @COMENTARIOS_IT = COMENTARIOS, @TIPODTO_IT = TIPODTO, @DESCUENTO_IT = DESCUENTO,
			   @MANUAL_IT = [MANUAL], @NOAUTORIZACION_IT = NOAUTORIZACION,
			   @IDPROVEEDOR_IT = IDPROVEEDOR, @GFACSOAT_IT = GFACSOAT, @IDAREA_IT = IDAREA
		FROM OPENJSON(@JSON_HPRED) WITH (
			NOPRESTACION VARCHAR(20) '$.NOPRESTACION',
			NOITEM SMALLINT '$.NOITEM',
			IDSERVICIO VARCHAR(20) '$.IDSERVICIO',
			CANTIDAD SMALLINT '$.CANTIDAD',
			VALOR DECIMAL(14, 2) '$.VALOR',
			PAQUETE SMALLINT '$.PAQUETE',
			COMENTARIOS VARCHAR(2048) '$.COMENTARIOS',
			TIPODTO VARCHAR(1) '$.TIPODTO',
			DESCUENTO DECIMAL(14, 2) '$.DESCUENTO',
			[MANUAL] SMALLINT '$.MANUAL',
			NOAUTORIZACION VARCHAR(20) '$.NOAUTORIZACION',
			IDPROVEEDOR VARCHAR(20) '$.IDPROVEEDOR',
			GFACSOAT SMALLINT '$.GFACSOAT',
			IDAREA VARCHAR(20) '$.IDAREA'
		)

		IF @NOPRESTACION_IT IS NULL OR @IDSERVICIO_IT IS NULL
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'Debe indicar NOPRESTACION e IDSERVICIO'
			RETURN
		END

		SELECT @IDAREA_IT = COALESCE(@IDAREA_IT, IDAREA), @IDSEDE_IT = IDSEDE
		FROM HPRE WHERE NOPRESTACION = @NOPRESTACION_IT

		IF @METODO = 'AGREGAR_ITEM'
		BEGIN
			DECLARE @PRESER_IT VARCHAR(6)
			SELECT @PRESER_IT = PREFIJO FROM SER WHERE IDSERVICIO = @IDSERVICIO_IT
			IF NOT EXISTS(SELECT 1 FROM HPRE WHERE NOPRESTACION = @NOPRESTACION_IT AND PREFIJO = @PRESER_IT)
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR = 'Inconsistencia entre el prefijo de la prestaci?n y el del servicio cargado, Verifique e intente de Nuevo.'
				RETURN
			END

			SELECT @NOITEM_IT = COALESCE(MAX(NOITEM), 0) + 1 FROM HPRED WHERE NOPRESTACION = @NOPRESTACION_IT

			BEGIN TRY
				BEGIN TRAN
					INSERT INTO HPRED (
						NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, IDPLAN, COMENTARIOS, IDCONCEPTORIPS, USUARIO,
						TIPOSERCIRUGIA, FECHA, VIA, IDAREA, COBRARA, IDTERCEROCA, PCUBRIMIENTO, TIPODTO, DESCUENTO,
						CCOSTO, AQUIENCOBRO, CODCUPS, VALOR, [MANUAL], NOAUTORIZACION, IDPROVEEDOR, GFACSOAT, NOCOBRABLE, APOYODG_AMBITO
					)
					SELECT @NOPRESTACION_IT, @NOITEM_IT, @IDSERVICIO_IT, @CANTIDAD_IT, A.IDPLAN, @COMENTARIOS_IT, B.CODIGORIPS, @USUARIO,
						'No', DBO.FNK_FECHA_SIN_MLS(GETDATE()), 'NA', @IDAREA_IT, A.COBRARA, A.IDTERCEROCA, 100, @TIPODTO_IT, @DESCUENTO_IT,
						A.CCOSTO, 'N', B.CODCUPS, @VALOR_IT, @MANUAL_IT, COALESCE(@NOAUTORIZACION_IT, ''), @IDPROVEEDOR_IT, @GFACSOAT_IT, 0, B.AMBITO
					FROM HPRE A
					INNER JOIN SER B ON B.IDSERVICIO = @IDSERVICIO_IT
					WHERE A.NOPRESTACION = @NOPRESTACION_IT
				COMMIT
			END TRY
			BEGIN CATCH
				IF @@TRANCOUNT > 0 ROLLBACK
				SELECT 'KO' OK
				SELECT ERROR = 'Error al insertar detalle: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
		END
		ELSE
		BEGIN
			IF @NOITEM_IT IS NULL
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR = 'Debe indicar NOITEM para editar'
				RETURN
			END

			IF EXISTS(SELECT 1 FROM HPRED WHERE NOPRESTACION = @NOPRESTACION_IT AND NOITEM = @NOITEM_IT AND COALESCE(CXP, 0) = 1)
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR = 'No se puede Editar una Prestaci?n con Honorarios Medicos, Debe Anular El Honorario'
				RETURN
			END
			IF EXISTS(SELECT 1 FROM HPRED WHERE NOPRESTACION = @NOPRESTACION_IT AND NOITEM = @NOITEM_IT AND COALESCE(FACTURADA, 0) = 1)
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR = 'Prestaci?n Ya Facturada'
				RETURN
			END
			IF EXISTS(SELECT 1 FROM HPRED WHERE NOPRESTACION = @NOPRESTACION_IT AND NOITEM = @NOITEM_IT AND COALESCE(ENCARGOS, 0) <> 0)
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR = 'Prestacion en apoyodx, encargos<>0'
				RETURN
			END
			--IF EXISTS(
			--	SELECT 1 FROM HPRE A
			--	INNER JOIN HADM B ON A.NOADMISION = B.NOADMISION AND B.TIPOADM = DBO.FNK_VALORVARIABLE('IDTARIFASOAT')
			--	INNER JOIN HACTRAN C ON C.CNSHACTRAN = B.CNSHACTRAN
			--	WHERE A.NOPRESTACION = @NOPRESTACION_IT AND COALESCE(C.VLRFALTA, 0) <= 0
			--)
			--BEGIN
			--	SELECT 'KO' OK
			--	SELECT ERROR = 'La admision llego o sobrepaso el tope del SOAT.'
			--	RETURN
			--END
			IF EXISTS(SELECT 1 FROM HPRED WHERE NOPRESTACION = @NOPRESTACION_IT AND NOITEM = @NOITEM_IT AND COALESCE(PEDIDOINV, 0) = 1 AND IDSERVICIO <> @IDSERVICIO_IT)
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR = 'No se puede editar un servicio solicitado a inventario'
				RETURN
			END

			BEGIN TRY
				BEGIN TRAN
					UPDATE HPRED
					SET CANTIDAD = @CANTIDAD_IT, VALOR = @VALOR_IT, PAQUETE = @PAQUETE_IT, COMENTARIOS = @COMENTARIOS_IT,
						TIPODTO = @TIPODTO_IT, DESCUENTO = @DESCUENTO_IT, [MANUAL] = @MANUAL_IT, IDSERVICIO = @IDSERVICIO_IT,
						IDCONCEPTORIPS = B.CODIGORIPS, CODCUPS = B.CODCUPS, NOAUTORIZACION = COALESCE(@NOAUTORIZACION_IT, ''),
						IDPROVEEDOR = @IDPROVEEDOR_IT, GFACSOAT = @GFACSOAT_IT, NOCOBRABLE = COALESCE(NOCOBRABLE, 0)
					FROM HPRED A
					INNER JOIN SER B ON B.IDSERVICIO = @IDSERVICIO_IT
					WHERE A.NOPRESTACION = @NOPRESTACION_IT AND A.NOITEM = @NOITEM_IT
				COMMIT
			END TRY
			BEGIN CATCH
				IF @@TRANCOUNT > 0 ROLLBACK
				SELECT 'KO' OK
				SELECT ERROR = 'Error al editar prestacion: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
		END

		IF @NOADMISION IS NULL
			SELECT @NOADMISION = NOADMISION FROM HPRE WHERE NOPRESTACION = @NOPRESTACION_IT

		IF EXISTS(SELECT 1 FROM HADM A WHERE A.NOADMISION = @NOADMISION AND COALESCE(A.COPAGONOAUTORIZACION, '') <> '' AND COALESCE(A.COPAGOVALOR, 0) > 0)
			EXEC SPK_RELIQUIDACOPAGOQX @NOADMISION
		ELSE
			EXEC SPK_COPAGOQX @NOADMISION, @NOPRESTACION_IT, @NOITEM_IT

		SELECT 'OK' OK, @NOPRESTACION_IT AS NOPRESTACION, @NOITEM_IT AS NOITEM

		SELECT
			HPRED.NOPRESTACION,
			HPRED.NOITEM,
			HPRE.PREFIJO,
			HPRE.NOADMISION,
			COALESCE(HPRED.GFACSOAT, 0) AS GFACSOAT,
			HPRED.IDSERVICIO,
			SER.DESCSERVICIO,
			CONVERT(INT, HPRED.CANTIDAD) AS CANTIDAD,
			CONVERT(DECIMAL(14, 2), HPRED.VALOR) AS VALOR,
			CONVERT(DECIMAL(14, 2), COALESCE(HPRED.CANTIDAD, 0) * COALESCE(HPRED.VALOR, 0)) AS VLRSUBTOTAL,
			CONVERT(DECIMAL(14, 2), HPRED.VALORCOPAGO) AS VALORCOPAGO,
			CONVERT(DECIMAL(14, 2), HPRED.VALOREXCEDENTE) AS VALOREXCEDENTE,
			CONVERT(DECIMAL(14, 2), HPRED.VALORPCOMP) AS VALORPCOMP,
			COALESCE(HPRED.NOCOBRABLE, 0) AS NOCOBRABLE,
			COALESCE(HPRED.PAQUETE, 0) AS PAQUETE,
			COALESCE(HPRED.NOAUTORIZACION, '') AS NOAUTORIZACION,
			COALESCE(HPRED.COMENTARIOS, '') AS COMENTARIOS,
			COALESCE(HPRED.FACTURADA, 0) AS FACTURADA,
			COALESCE(HPRED.ENCARGOS, 0) AS ENCARGOS,
			COALESCE(HPRED.COBRARA, 'C') AS COBRARA,
			HPRED.IDTERCEROCA,
			HPRED.IDPLAN,
			HPRE.FECHA,
			HPRE.IDAREA,
			HPRE.CCOSTO,
			(SELECT COALESCE(SUM(D2.CANTIDAD), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND H2.PREFIJO = HPRE.PREFIJO AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0)) AS TOTAL_PREFIJO_CANTIDAD,
			(SELECT COALESCE(SUM(D2.VALOREXCEDENTE), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND H2.PREFIJO = HPRE.PREFIJO AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0)) AS TOTAL_PREFIJO_VALOR,
			(SELECT COUNT(*) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND H2.PREFIJO = HPRE.PREFIJO AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0)) AS TOTAL_PREFIJO_ITEMS,
			(SELECT COALESCE(SUM(COALESCE(D2.CANTIDAD, 0) * COALESCE(D2.VALOR, 0)), 0) FROM HPRED D2 INNER JOIN HPRE H2 ON H2.NOPRESTACION = D2.NOPRESTACION WHERE H2.NOADMISION = HPRE.NOADMISION AND COALESCE(D2.GFACSOAT, 0) = COALESCE(HPRED.GFACSOAT, 0) AND COALESCE(D2.FACTURADA, 0) = 0 AND COALESCE(D2.NOCOBRABLE, 0) = 0) AS TOTAL_RESPONSABLE_VALOR
		FROM HPRED
		INNER JOIN HPRE ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
		INNER JOIN SER ON SER.IDSERVICIO = HPRED.IDSERVICIO
		WHERE HPRED.NOPRESTACION = @NOPRESTACION_IT
		  AND HPRED.NOITEM = @NOITEM_IT

		RETURN
	END
END

