CREATE OR ALTER PROCEDURE DBO.SPQ_HACTRAN
@JSON  NVARCHAR(MAX)
WITH ENCRYPTION
AS
DECLARE	 @PARAMETROS   NVARCHAR(MAX),@MODELO           VARCHAR(100) ,@METODO    VARCHAR(100)	,@USUARIO      VARCHAR(12)
		,@GRUPO        VARCHAR(8)	,@SYS_COMPUTERNAME VARCHAR(254) ,@SEDE      VARCHAR(5)		,@FECHA        VARCHAR(10)   
		,@CNSHACTRAN    VARCHAR(20)	,@FECHA1           DATETIME		,@SQL		VARCHAR(MAX)	,@IDMEDICO     VARCHAR(20)
		,@IDAFILIADO AS VARCHAR(20)	,@NVOCONSEC		   VARCHAR(20)	,@COMPANIA	VARCHAR(2)		,@COLUMNAS	   VARCHAR(MAX) 
		,@DXING VARCHAR(254)  		,@DXEGR			VARCHAR(254)	,@FECHAEGR DATE	
		,@TIPOADM		VARCHAR(20)
		, @error   NVARCHAR(MAX)

DECLARE @PARAMETROSTOPES TABLE(
	IDTERCERO VARCHAR(20)
	, NIT  VARCHAR(20)
	, RAZONSOCIAL  VARCHAR(1000)
	, IDTARIFA  VARCHAR(20)
	, ANOTOPE  VARCHAR(20)
	, FACTORDINERO FLOAT
	, TOPEMAX FLOAT
	, TOPE1 FLOAT
	)						 
DECLARE @TBLERRORES TABLE(ERROR VARCHAR(MAX))						 
DECLARE @IPS VARCHAR(20)=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'), @DATOSPROPIETARIO VARCHAR (20)=DBO.FNK_VALORVARIABLE('DATOSPROPIETARIO')
		,@IDSEDE VARCHAR (5), @IDTERCERO VARCHAR(20) ,@PROCEDENCIA VARCHAR(20), @NOREFERENCIA VARCHAR(20), @FECHAING DATETIME
BEGIN

 /*	SPQ_HACTRAN
	Modulo:		SOAT
	Funcion:	Metodos para agregar, y actualizar la informacion de los accidentes de transito 
	Metodos:	CONSULTAR, UPDATE, INSERT, LLENAR, CONSULTARSIRASADMISION
	Elabora:	Omar Solano
	Fecha:		06-02-2023
	Modificado: 25-08-2023 por Edgardo
*/
	SET DATEFORMAT dmy
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON

	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SEDE = IDSEDE, @COMPANIA=COMPANIA FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME

	-------------------- para pruebas verificando
	print 'parametros: ' + @PARAMETROS
	print 'usuario: ' + @USUARIO
	print 'grupo: ' + @GRUPO
	PRINT 'SEDE: ' +@SEDE
	PRINT 'COMPANIA: ' +@COMPANIA
	--------------------
	IF @METODO = 'CONSULTARSIRASADMISION'
	BEGIN
		SELECT @NOREFERENCIA = NOADMISION, @IDAFILIADO = IDAFILIADO
		FROM OPENJSON(@PARAMETROS)
		WITH(
			NOADMISION VARCHAR(20) '$.NOADMISION',
			IDAFILIADO VARCHAR(20) '$.IDAFILIADO'
		)

		SELECT 'OK' OK
		SELECT LEFT(COALESCE(MAX(HADM.SIRAS), ''), 20) NOSIRAS
		FROM HADM
		WHERE HADM.NOADMISION = @NOREFERENCIA
		  AND HADM.IDAFILIADO = @IDAFILIADO

		RETURN
	END

	IF @METODO = 'CONSULTARTOPES'  --- LOS PARAMETROS DE UVT PARA EL CALCULO DE LOS TOPES DEL SOAT
	BEGIN
		IF NOT EXISTS (
			SELECT 1 
			FROM TER INNER JOIN PPT ON TER.IDTERCERO = PPT.IDTERCERO 
				INNER JOIN TARF ON PPT.IDTARIFA = TARF.IDTARIFA 
			WHERE TER.NIT = dbo.FNK_VALORVARIABLE('IDNITFONSAT') 
			AND PPT.IDPLAN = dbo.FNK_VALORVARIABLE('IDPLANFONSAT') AND PPT.IDTARIFA=dbo.FNK_VALORVARIABLE('IDTARIFAUVT')
		)
		BEGIN
			INSERT INTO @PARAMETROSTOPES			
			SELECT DISTINCT NULL, NULL, NULL, IDTARIFA,  YEAR(TARF.FECHAINI) ANOTOPE ,  TARF.FACTORDINERO, round( coalesce( TARF.FACTORDINERO,0 ) * 701.68 ,0 ) TOPEMAX,  round(  coalesce( TARF.FACTORDINERO,0 ) * 263.13 ,0 )  TOPE1 
			FROM TARF
			WHERE  IDTARIFA=dbo.FNK_VALORVARIABLE('IDTARIFAUVT')
		END
		ELSE
		BEGIN
			INSERT INTO @PARAMETROSTOPES			
			SELECT DISTINCT TER.IDTERCERO , TER.NIT, TER.RAZONSOCIAL , PPT.IDTARIFA  , YEAR(TARF.FECHAINI) ANOTOPE ,  TARF.FACTORDINERO,  round(  coalesce( TARF.FACTORDINERO,0 ) * 701.68 ,0 )  TOPEMAX,  round(    coalesce( TARF.FACTORDINERO,0 ) * 263.13 ,0 )  TOPE1 
			FROM TER INNER JOIN PPT ON TER.IDTERCERO = PPT.IDTERCERO 
				INNER JOIN TARF ON PPT.IDTARIFA = TARF.IDTARIFA 
			WHERE TER.NIT = dbo.FNK_VALORVARIABLE('IDNITFONSAT') 
			AND PPT.IDPLAN = dbo.FNK_VALORVARIABLE('IDPLANFONSAT') AND PPT.IDTARIFA=dbo.FNK_VALORVARIABLE('IDTARIFAUVT')			
		END

		--IF ( dbo.FNK_VALORVARIABLE('IDTARIFAUVT')  <> ( SELECT IDTARIFA FROM @PARAMETROSTOPES) )
		--BEGIN 
		--		PRINT 'LA TARIFA ESTA MAL CONFIGURADA EN EL PLAN O EN LA VARIABLE IDTARIFAUVT: ' + dbo.FNK_VALORVARIABLE('IDTARIFAUVT')   
		--		INSERT INTO @TBLERRORES(ERROR) SELECT  'LA TARIFA ESTA MAL CONFIGURADA EN EL PLAN O EN LA VARIABLE IDTARIFAUVT: ' + dbo.FNK_VALORVARIABLE('IDTARIFAUVT')  
			
		--		SELECT 'KO' OK 
		--		SELECT 'LA TARIFA ESTA MAL CONFIGURADA EN EL PLAN O EN LA VARIABLE IDTARIFAUVT: ' + dbo.FNK_VALORVARIABLE('IDTARIFAUVT')   ERROR
		--		RETURN
		--END 

		IF (  ( SELECT COALESCE(FACTORDINERO,0) FROM @PARAMETROSTOPES WHERE ANOTOPE = YEAR(GETDATE() ) ) = 0 )
		BEGIN 
				PRINT 'EL FATOR DEL DINERO ES 0 O NO EXISTE PARA EL PRESENTE AÑO DE LA TARIFA: ' + dbo.FNK_VALORVARIABLE('IDTARIFAUVT')    
				INSERT INTO @TBLERRORES(ERROR) SELECT  'EL FATOR DEL DINERO ES 0 O NO EXISTE PARA EL PRESENTE AÑO DE LA TARIFA: ' + dbo.FNK_VALORVARIABLE('IDTARIFAUVT')  
			
				--SELECT 'KO' OK 
				--SELECT 'EL FATOR DEL DINERO ES 0 O NO EXISTE PARA EL PRESENTE AÑO DE LA TARIFA: ' + dbo.FNK_VALORVARIABLE('IDTARIFAUVT')    ERROR
				
		END 

		SELECT 'OK' OK 
		SELECT * FROM @PARAMETROSTOPES
		
	END

	--- CORREGIR CUANDO NO TIENE CERTIFICADORES CREADOS LE CREA ALMENOS EL NA PARA QUE NO MANDE EL ERROR
	IF (SELECT COUNT(1) FROM HACTRANCE)=0 
	BEGIN 
		INSERT INTO HACTRANCE (PAPELLIDO,	SAPELLIDO,	PNOMBRE,	SNOMBRE,	TIPODOC,	DOCUMENTO,	CARGO)
		SELECT 'NA',	'NA',	'NA',	'NA',	'CC',	'NA',	'PGN'
		WHERE NOT EXISTS (SELECT 1 FROM  HACTRANCE WHERE DOCUMENTO='NA')
	END
	IF @METODO = 'CONSULTAR'
	BEGIN
		SELECT @CNSHACTRAN = CNSHACTRAN
		FROM OPENJSON(@PARAMETROS)
		WITH(CNSHACTRAN  VARCHAR(20) '$.CNSHACTRAN')

		SELECT 'OK' OK
		SELECT 
			HACTRAN.CNSHACTRAN, HACTRAN.IDAFILIADO, HACTRAN.SITIOACC, HACTRAN.FECHAACC, HACTRAN.CIUDAD, HACTRAN.ZONA, HACTRAN.INFORME, HACTRAN.MARCA, HACTRAN.PLACA, HACTRAN.TIPO, HACTRAN.IDASEGURADORA,
			HACTRAN.SUCURSAL, HACTRAN.FECHAINIPOL, HACTRAN.FECHAFINPOL, HACTRAN.CONDUCTOR, HACTRAN.EDAD, HACTRAN.SEXO, HACTRAN.TIPODOC, HACTRAN.NODOCUMENTO, HACTRAN.DE, HACTRAN.DIRECCION, HACTRAN.CIUDADCOND,
			HACTRAN.TELEFONO, HACTRAN.CONDICIONACC, HACTRAN.REMITIDADE, HACTRAN.REMITIDADECIUDAD, HACTRAN.FECHA_RD, HACTRAN.TOPE, HACTRAN.VLRGASTADO, HACTRAN.VLRFALTA, HACTRAN.FECHA, HACTRAN.USUARIO,
			HACTRAN.GASTOEXTERNO, HACTRAN.VLRGASTOEXTERNO, HACTRAN.DECLARACIONDE, HACTRAN.NOIDENTDECLARACION, HACTRAN.EXPEDIDAENDECLA, HACTRAN.NOPOLIZA, HACTRAN.TIPOPOLIZA, HACTRAN.TOPE1, HACTRAN.REMITIDADETERCERO,
			HACTRAN.COND_PNOMBRE, HACTRAN.COND_SNOMBRE, HACTRAN.COND_PAPELLIDO, HACTRAN.COND_SAPELLIDO, HACTRAN.INTERVAUTOR, HACTRAN.COBROEXCEPOL, HACTRAN.PERSONAREMITE, HACTRAN.CARGOPERREMITE, HACTRAN.DIRIPSREMITE,
			HACTRAN.TELIPSREMITE, HACTRAN.F_ACEPTA, HACTRAN.PERREMITIDAA, HACTRAN.PERSONARECIBE, HACTRAN.CARGOPERRECIBE, HACTRAN.DIRIPSRECIBE, HACTRAN.CIUDADIPSRECIBE, HACTRAN.TELIPSRECIBE, HACTRAN.PROPNOMBRE,
			HACTRAN.PROSNOMBRE, HACTRAN.PROPAPELLIDO, HACTRAN.PROSAPELLIDO, HACTRAN.PROTIPO_ID, HACTRAN.PRODOCUMENTO, HACTRAN.PRODIRECCION, HACTRAN.PROCIUDAD, HACTRAN.PROTELEFONO, HACTRAN.NATUREVENTO, HACTRAN.NATURCUAL,
			HACTRAN.F_RADICACION, HACTRAN.NRORADICADO, HACTRAN.NRORADICADOANT, HACTRAN.NROFACTURA, HACTRAN.RESPGLOSA, HACTRAN.FORMATO, HACTRAN.PLACA_AMPARO, HACTRAN.PAPELLIDO_AMPARO, HACTRAN.SAPELLIDO_AMPARO,
			HACTRAN.PNOMBRE_AMPARO, HACTRAN.SNOMBRE_AMPARO, HACTRAN.TIPODOC_AMPARO, HACTRAN.DOC_AMPARO, HACTRAN.TRANSPORTO_VIC_DESDE, HACTRAN.TRANSPORTO_VIC_HASTA, HACTRAN.TIPOTRANSPORTE, HACTRAN.ZONA_AMPARO,
			HACTRAN.ARMQXFACTURADO, HACTRAN.ARMQXFOSYGA, HACTRAN.ARTRANSFACTURADO, HACTRAN.ARTRANSFOSYGA, HACTRAN.CIUDAD_AMPARO, HACTRAN.F_AMPARO, HACTRAN.VH2_PLANCA, HACTRAN.VH2_PROTIPODOC, HACTRAN.VH2_PRODOC,
			HACTRAN.VH2_PRONOMBRE, HACTRAN.VH3_PLANCA, HACTRAN.VH3_PROTIPODOC, HACTRAN.VH3_PRODOC, HACTRAN.VH3_PRONOMBRE, HACTRAN.CER_HACTRAN, HACTRAN.COD_IPSREMITE, HACTRAN.COD_IPSRECIBE, HACTRAN.COD_IPSRECIBE_AMPARO,
			HACTRAN.REM_TIPOREFERENCIA, HACTRAN.OTROTIPOTRANS, HACTRAN.REMITIDAATERCERO, HACTRAN.EXPORTADO, HACTRAN.IDFIRMAPTE, HACTRAN.IDFIRMARESP, HACTRAN.ASIGNATOPE, HACTRAN.PRESTOUCI, HACTRAN.MATOSTEOSINTESIS,
			AFI.DOCIDAFILIADO, AFI.NOMBREAFI, TER.NIT, TER.RAZONSOCIAL, CIU.NOMBRE CIUDADACC , TER.RAZONSOCIAL NOMBREASEGURADORA ,TER.IDALTERNA2 CODIGOASEGURADORA,
			HACTRAN.CILINDRAJE,
			AFI.IDAFILIADO , HACTRAN.TIPOPOLIZA , DBO.FNK_GETDATE() FECHAACTUAL, AFI.FECHAFALLECE
		FROM HACTRAN
			LEFT JOIN AFI ON AFI.IDAFILIADO=HACTRAN.IDAFILIADO
            LEFT JOIN CIU ON CIU.CIUDAD=HACTRAN.CIUDAD
            LEFT JOIN TER ON TER.IDTERCERO=HACTRAN.IDASEGURADORA 
		WHERE CNSHACTRAN=@CNSHACTRAN			
		RETURN
	END  --- CONSULTAR
	IF @METODO = 'LLENAR'
	BEGIN
		SELECT @CNSHACTRAN = CNSHACTRAN
		FROM OPENJSON(@PARAMETROS)
		WITH(CNSHACTRAN  VARCHAR(20) '$.CNSHACTRAN')

		SELECT 'OK' OK
		SELECT 
				coalesce( HACTRAN.CNSHACTRAN,			'' ) CNSHACTRAN, 
				coalesce( HACTRAN.IDAFILIADO, 			'' ) IDAFILIADO, 
				coalesce( HACTRAN.SITIOACC, 			'' ) SITIOACC, 
				coalesce( HACTRAN.FECHAACC, 			'' ) FECHAACC, 
				coalesce( HACTRAN.CIUDAD, 				'' ) CIUDAD, 
				coalesce( HACTRAN.ZONA, 				'' ) ZONA, 
				coalesce( HACTRAN.INFORME, 				'' ) INFORME, 
				coalesce( HACTRAN.MARCA, 				'' ) MARCA, 
				coalesce( HACTRAN.PLACA, 				'' ) PLACA, 
				coalesce( HACTRAN.TIPO, 				'' ) TIPO, 
				coalesce( HACTRAN.IDASEGURADORA, 		'' ) IDASEGURADORA, 
				coalesce( HACTRAN.SUCURSAL, 			'' ) SUCURSAL, 
				coalesce( HACTRAN.FECHAINIPOL, 			'' ) FECHAINIPOL, 
				coalesce( HACTRAN.FECHAFINPOL, 			'' ) FECHAFINPOL, 
				coalesce( HACTRAN.CONDUCTOR, 			'' ) CONDUCTOR, 
				coalesce( HACTRAN.EDAD, 				'' ) EDAD, 
				coalesce( HACTRAN.SEXO, 				'' ) SEXO, 
				coalesce( HACTRAN.TIPODOC, 				'' ) TIPODOC, 
				coalesce( HACTRAN.NODOCUMENTO, 			'' ) NODOCUMENTO, 
				coalesce( HACTRAN.DE, 					'' ) DE, 
				coalesce( HACTRAN.DIRECCION, 			'' ) DIRECCION, 
				coalesce( HACTRAN.CIUDADCOND, 			'' ) CIUDADCOND, 
				coalesce( HACTRAN.TELEFONO, 			'' ) TELEFONO, 
				coalesce( HACTRAN.CONDICIONACC, 		'' ) CONDICIONACC, 
				coalesce( HACTRAN.REMITIDADE, 			'' ) REMITIDADE, 
				coalesce( HACTRAN.REMITIDADECIUDAD, 	'' ) REMITIDADECIUDAD, 
				coalesce( HACTRAN.FECHA_RD, 			'' ) FECHA_RD, 
				coalesce( HACTRAN.TOPE, 				0  ) TOPE, 
				coalesce( HACTRAN.VLRGASTADO, 			0  ) VLRGASTADO, 
				coalesce( HACTRAN.VLRFALTA, 			0  ) VLRFALTA, 
				coalesce( HACTRAN.FECHA, 				'' ) FECHA, 
				coalesce( HACTRAN.USUARIO, 				'' ) USUARIO, 
				coalesce( HACTRAN.GASTOEXTERNO, 		'' ) GASTOEXTERNO, 
				coalesce( HACTRAN.VLRGASTOEXTERNO, 		0  ) VLRGASTOEXTERNO, 
				coalesce( HACTRAN.DECLARACIONDE, 		'' ) DECLARACIONDE, 
				coalesce( HACTRAN.NOIDENTDECLARACION, 	'' ) NOIDENTDECLARACION, 
				coalesce( HACTRAN.EXPEDIDAENDECLA, 		'' ) EXPEDIDAENDECLA, 
				coalesce( HACTRAN.NOPOLIZA, 			'' ) NOPOLIZA, 
				coalesce( HACTRAN.TIPOPOLIZA, 			'' ) TIPOPOLIZA, 
				coalesce( HACTRAN.TOPE1, 				0  ) TOPE1, 
				coalesce( HACTRAN.REMITIDADETERCERO, 	'' ) REMITIDADETERCERO, 
				coalesce( HACTRAN.COND_PNOMBRE, 		'' ) COND_PNOMBRE, 
				coalesce( HACTRAN.COND_SNOMBRE, 		'' ) COND_SNOMBRE, 
				coalesce( HACTRAN.COND_PAPELLIDO, 		'' ) COND_PAPELLIDO, 
				coalesce( HACTRAN.COND_SAPELLIDO, 		'' ) COND_SAPELLIDO, 
				coalesce( HACTRAN.INTERVAUTOR, 			'' ) INTERVAUTOR, 
				coalesce( HACTRAN.COBROEXCEPOL, 		'' ) COBROEXCEPOL, 
				coalesce( HACTRAN.PERSONAREMITE, 		'' ) PERSONAREMITE, 
				coalesce( HACTRAN.CARGOPERREMITE, 		'' ) CARGOPERREMITE, 
				coalesce( HACTRAN.DIRIPSREMITE, 		'' ) DIRIPSREMITE, 
				coalesce( HACTRAN.TELIPSREMITE, 		'' ) TELIPSREMITE, 
				coalesce( HACTRAN.F_ACEPTA, 			'' ) F_ACEPTA, 
				coalesce( HACTRAN.PERREMITIDAA, 		'' ) PERREMITIDAA, 
				coalesce( HACTRAN.PERSONARECIBE, 		'' ) PERSONARECIBE, 
				coalesce( HACTRAN.CARGOPERRECIBE, 		'' ) CARGOPERRECIBE, 
				coalesce( HACTRAN.DIRIPSRECIBE, 		'' ) DIRIPSRECIBE, 
				coalesce( HACTRAN.CIUDADIPSRECIBE, 		'' ) CIUDADIPSRECIBE, 
				coalesce( HACTRAN.TELIPSRECIBE, 		'' ) TELIPSRECIBE, 
				coalesce( HACTRAN.PROPNOMBRE, 			'' ) PROPNOMBRE, 
				coalesce( HACTRAN.PROSNOMBRE, 			'' ) PROSNOMBRE, 
				coalesce( HACTRAN.PROPAPELLIDO, 		'' ) PROPAPELLIDO, 
				coalesce( HACTRAN.PROSAPELLIDO, 		'' ) PROSAPELLIDO, 
				coalesce( HACTRAN.PROTIPO_ID, 			'' ) PROTIPO_ID, 
				coalesce( HACTRAN.PRODOCUMENTO, 		'' ) PRODOCUMENTO, 
				coalesce( HACTRAN.PRODIRECCION, 		'' ) PRODIRECCION, 
				coalesce( HACTRAN.PROCIUDAD, 			'' ) PROCIUDAD, 
				coalesce( HACTRAN.PROTELEFONO, 			'' ) PROTELEFONO, 
				coalesce( HACTRAN.NATUREVENTO, 			'' ) NATUREVENTO, 
				coalesce( HACTRAN.NATURCUAL, 			'' ) NATURCUAL, 
				coalesce( HACTRAN.F_RADICACION, 		'' ) F_RADICACION, 
				coalesce( HACTRAN.NRORADICADO, 			'' ) NRORADICADO, 
				coalesce( HACTRAN.NRORADICADOANT, 		'' ) NRORADICADOANT, 
				coalesce( HACTRAN.NROFACTURA, 			'' ) NROFACTURA, 
				coalesce( HACTRAN.RESPGLOSA, 			'' ) RESPGLOSA, 
				coalesce( HACTRAN.FORMATO, 				'' ) FORMATO, 
				coalesce( HACTRAN.PLACA_AMPARO, 		'' ) PLACA_AMPARO, 
				coalesce( HACTRAN.PAPELLIDO_AMPARO, 	'' ) PAPELLIDO_AMPARO, 
				coalesce( HACTRAN.SAPELLIDO_AMPARO, 	'' ) SAPELLIDO_AMPARO, 
				coalesce( HACTRAN.PNOMBRE_AMPARO, 		'' ) PNOMBRE_AMPARO, 
				coalesce( HACTRAN.SNOMBRE_AMPARO, 		'' ) SNOMBRE_AMPARO, 
				coalesce( HACTRAN.TIPODOC_AMPARO, 		'' ) TIPODOC_AMPARO, 
				coalesce( HACTRAN.DOC_AMPARO, 			'' ) DOC_AMPARO, 
				coalesce( HACTRAN.TRANSPORTO_VIC_DESDE, '' ) TRANSPORTO_VIC_DESDE, 
				coalesce( HACTRAN.TRANSPORTO_VIC_HASTA, '' ) TRANSPORTO_VIC_HASTA, 
				coalesce( HACTRAN.TIPOTRANSPORTE, 		'' ) TIPOTRANSPORTE, 
				coalesce( HACTRAN.ZONA_AMPARO, 			'' ) ZONA_AMPARO, 
				coalesce( HACTRAN.ARMQXFACTURADO, 		0  ) ARMQXFACTURADO, 
				coalesce( HACTRAN.ARMQXFOSYGA, 			0  ) ARMQXFOSYGA, 
				coalesce( HACTRAN.ARTRANSFACTURADO, 	0  ) ARTRANSFACTURADO, 
				coalesce( HACTRAN.ARTRANSFOSYGA, 		0  ) ARTRANSFOSYGA, 
				coalesce( HACTRAN.CIUDAD_AMPARO, 		'' ) CIUDAD_AMPARO, 
				coalesce( HACTRAN.F_AMPARO, 			'' ) F_AMPARO, 
				coalesce( HACTRAN.VH2_PLANCA, 			'' ) VH2_PLANCA, 
				coalesce( HACTRAN.VH2_PROTIPODOC, 		'' ) VH2_PROTIPODOC, 
				coalesce( HACTRAN.VH2_PRODOC, 			'' ) VH2_PRODOC, 
				coalesce( HACTRAN.VH2_PRONOMBRE, 		'' ) VH2_PRONOMBRE, 
				coalesce( HACTRAN.VH3_PLANCA, 			'' ) VH3_PLANCA, 
				coalesce( HACTRAN.VH3_PROTIPODOC, 		'' ) VH3_PROTIPODOC, 
				coalesce( HACTRAN.VH3_PRODOC, 			'' ) VH3_PRODOC, 
				coalesce( HACTRAN.VH3_PRONOMBRE, 		'' ) VH3_PRONOMBRE, 
				coalesce( HACTRAN.CER_HACTRAN, 			'' ) CER_HACTRAN, 
				coalesce( HACTRAN.COD_IPSREMITE, 		'' ) COD_IPSREMITE, 
				coalesce( HACTRAN.COD_IPSRECIBE, 		'' ) COD_IPSRECIBE, 
				coalesce( HACTRAN.COD_IPSRECIBE_AMPARO, 		'' ) COD_IPSRECIBE_AMPARO, 
				coalesce( HACTRAN.REM_TIPOREFERENCIA, 	'' ) REM_TIPOREFERENCIA, 
				coalesce( HACTRAN.OTROTIPOTRANS, 		'' ) OTROTIPOTRANS, 
				coalesce( HACTRAN.REMITIDAATERCERO, 	'' ) REMITIDAATERCERO, 
				coalesce( HACTRAN.EXPORTADO, 			'' ) EXPORTADO, 
				coalesce( HACTRAN.IDFIRMAPTE, 			'' ) IDFIRMAPTE, 
				coalesce( HACTRAN.IDFIRMARESP, 			'' ) IDFIRMARESP, 
				coalesce( HACTRAN.ASIGNATOPE,			0  ) ASIGNATOPE, 
				coalesce( HACTRAN.TIPOVEHICULO,			'' ) TIPOVEHICULO, 
				coalesce( HACTRAN.CILINDRAJE,			'' ) CILINDRAJE, 
				coalesce( HACTRAN.NOSIRAS, 				'' ) NOSIRAS, 
				coalesce( HACTRAN.CUPSPPALHOSP, 		'' ) CUPSPPALHOSP, 
				coalesce( HACTRAN.CUPSPPALQX, 			'' ) CUPSPPALQX, 
				coalesce( HACTRAN.CUPSSECQX, 			'' ) CUPSSECQX, 
				coalesce( HACTRAN.PLACATRASLINTER, 		'' ) PLACATRASLINTER, 
				coalesce( HACTRAN.PRESTOUCI, 			'' ) PRESTOUCI, 
				coalesce( HACTRAN.MATOSTEOSINTESIS, 	'' ) MATOSTEOSINTESIS, 
				coalesce( HACTRAN.ATENCIONFACTURADA, 	'' ) ATENCIONFACTURADA, 
				coalesce( HACTRAN.COMPLEJIDADQX, 		'' ) COMPLEJIDADQX, 
				coalesce( HACTRAN.FECHACERTIFICA, 		'' ) FECHACERTIFICA, 
				coalesce( HACTRAN.DIASUCI, 				'' ) DIASUCI, 
				coalesce( HACTRAN.TARIFADIFERENCIAL , 	'' ) TARIFADIFERENCIAL, 
                AFI.DOCIDAFILIADO, 
				AFI.NOMBREAFI, 
				TER.NIT, 
				TER.RAZONSOCIAL ,
				coalesce( TER.RAZONSOCIAL ,'' ) NOMBREASEGURADORA ,
				coalesce( TER.IDALTERNA2 ,'' )  CODIGOASEGURADORA  ,
				coalesce ( CIU.NOMBRE		,'') NCIUDADACC ,
				coalesce ( CIUCOND.NOMBRE	,'') NCIUDADCOND,
				coalesce ( CIUDE.NOMBRE		,'') NCIUDADDE,
				coalesce ( CIUDEDOC.NOMBRE	,'') NCIUDADDEDOC,
				coalesce ( CIURECIB.NOMBRE	,'') NCIUDADRECIBE,
				coalesce ( CIUPRO.NOMBRE	,'') NCIUDADPRO,
				coalesce ( CIUAMP.NOMBRE	,'') NCIUDADAMP,
				coalesce ( TVEHIC.NOMBRE	,'') NTIPOVEHICULO,
				coalesce ( NT.DESCRIPCION	,'') NNATUREVENTO,
				coalesce ( CHAB.NOMBREENTIDAD	,'')  NIPSREMITE,
				coalesce ( CHAB2.NOMBREENTIDAD	,'')  NIPSRECIBE,
				coalesce ( CHAB3.NOMBREENTIDAD	,'')  NIPSRECIBE_AMPARO,
				coalesce ( SERPH.DESCSERVICIO		,'') NSERVICIOPH,
				coalesce ( SERPQ.DESCSERVICIO		,'') NSERVICIOPQ,
				coalesce ( SERSQ.DESCSERVICIO		,'') NSERVICIOSQ
			,	coalesce ( AFI.FECHAFALLECE	,'') FECHAFALLECE
			,	DBO.FNK_GETDATE() FECHAACTUAL 
		FROM HACTRAN
			LEFT JOIN AFI ON AFI.IDAFILIADO=HACTRAN.IDAFILIADO
            LEFT JOIN CIU ON CIU.CIUDAD=HACTRAN.CIUDAD
            LEFT JOIN CIU CIUCOND ON CIUCOND.CIUDAD=HACTRAN.CIUDADCOND
            LEFT JOIN CIU CIUDE ON CIUDE.CIUDAD=HACTRAN.REMITIDADECIUDAD
            LEFT JOIN CIU CIUDEDOC ON CIUDEDOC.CIUDAD=HACTRAN.DE
            LEFT JOIN CIU CIURECIB ON CIURECIB.CIUDAD=HACTRAN.CIUDADIPSRECIBE
            LEFT JOIN CIU CIUPRO ON CIUPRO.CIUDAD=HACTRAN.PROCIUDAD
            LEFT JOIN CIU CIUAMP ON CIUAMP.CIUDAD=HACTRAN.CIUDAD_AMPARO
			LEFT JOIN ( SELECT 	1 T, 'AUTOMOVIL'  NOMBRE UNION ALL
				SELECT 2  , 'BUS'  UNION ALL
				SELECT 3  , 'BUSETA'  UNION ALL
				SELECT 4  , 'CAMION'  UNION ALL
				SELECT 5  , 'CAMIONETA'  UNION ALL
				SELECT 6  , 'CAMPERO'  UNION ALL
				SELECT 7  , 'MICROBUS'  UNION ALL
				SELECT 8  , 'TRACTOCAMION'  UNION ALL
				SELECT 10 , 'MOTOCICLETA'  UNION ALL
				SELECT 14 , 'MOTOCARRO'  UNION ALL
				SELECT 17 , 'MOTOTRICICLO'  UNION ALL
				SELECT 19 , 'CUATRIMOTO'  UNION ALL
				SELECT 20 , 'MOTO EXTRANJERA'  UNION ALL
				SELECT 21 , 'VEHICULO EXTRANJERO'  UNION ALL
				SELECT 22 , 'VOLQUETA' ) TVEHIC ON HACTRAN.TIPOVEHICULO=TVEHIC.T
			LEFT JOIN  (SELECT CODIGO,DESCRIPCION , DATO2 FROM TGEN WHERE CAMPO = 'NATUREVENTO' ) NT ON HACTRAN.NATUREVENTO = NT.CODIGO
			LEFT JOIN SER SERPH ON  SERPH.IDSERVICIO = HACTRAN.CUPSPPALHOSP
			LEFT JOIN SER SERPQ ON  SERPQ.IDSERVICIO = HACTRAN.CUPSPPALQX
			LEFT JOIN SER SERSQ ON  SERSQ.IDSERVICIO = HACTRAN.CUPSSECQX
			LEFT OUTER JOIN IPSHAB CHAB	ON CHAB.CODIGOHABILITACION = HACTRAN.COD_IPSREMITE
			LEFT OUTER JOIN IPSHAB CHAB2	ON CHAB2.CODIGOHABILITACION = HACTRAN.COD_IPSRECIBE
			LEFT OUTER JOIN IPSHAB CHAB3	ON CHAB3.CODIGOHABILITACION = HACTRAN.COD_IPSRECIBE_AMPARO
            LEFT JOIN TER ON TER.IDTERCERO=HACTRAN.IDASEGURADORA 
		WHERE CNSHACTRAN=@CNSHACTRAN			
		RETURN
	END  --- LLENAR
	IF @METODO = 'INSERT'
	BEGIN
		SELECT *  INTO #TMPHACTRAN
		FROM OPENJSON(@PARAMETROS)
		WITH(
			CNSHACTRAN            varchar(20)     '$.CNSHACTRAN' , 
			IDAFILIADO            varchar(20)     '$.IDAFILIADO' , 
			SITIOACC              varchar(250)    '$.SITIOACC' , 
			FECHAACC              datetime        '$.FECHAACC' , 
			CIUDAD                varchar(5)      '$.CIUDAD' , 
			ZONA                  varchar(6)      '$.ZONA' , 
			INFORME               varchar(1000)   '$.INFORME' , 
			MARCA                 varchar(19)     '$.MARCA' , 
			PLACA                 varchar(10)     '$.PLACA' , 
			TIPO                  varchar(20)     '$.TIPO' , 
			IDASEGURADORA         varchar(20)     '$.IDASEGURADORA' , 
			SUCURSAL              varchar(20)     '$.SUCURSAL' , 
			FECHAINIPOL           date	          '$.FECHAINIPOL' , 
			FECHAFINPOL           date	          '$.FECHAFINPOL' , 
			CONDUCTOR             varchar(40)     '$.CONDUCTOR' , 
			EDAD                  smallint        '$.EDAD' , 
			SEXO                  varchar(9)      '$.SEXO' , 
			TIPODOC               varchar(3)      '$.TIPODOC' , 
			NODOCUMENTO           varchar(20)     '$.NODOCUMENTO' , 
			DE                    varchar(20)     '$.DE' , 
			DIRECCION             varchar(100)    '$.DIRECCION' , 
			CIUDADCOND            varchar(5)      '$.CIUDADCOND' , 
			TELEFONO              varchar(12)     '$.TELEFONO' , 
			CONDICIONACC          varchar(8)      '$.CONDICIONACC' , 
			REMITIDADE            varchar(50)     '$.REMITIDADE' , 
			REMITIDADECIUDAD      varchar(5)      '$.REMITIDADECIUDAD' , 
			FECHA_RD              datetime	      '$.FECHA_RD' , 
			TOPE                  decimal         '$.TOPE' , 
			VLRGASTADO            decimal         '$.VLRGASTADO' , 
			VLRFALTA              decimal         '$.VLRFALTA' , 
			FECHA                 date	          '$.FECHA' , 
			USUARIO               Varchar(12)     '$.USUARIO' , 
			GASTOEXTERNO          smallint        '$.GASTOEXTERNO' , 
			VLRGASTOEXTERNO       decimal         '$.VLRGASTOEXTERNO' , 
			DECLARACIONDE         varchar(50)     '$.DECLARACIONDE' , 
			NOIDENTDECLARACION    varchar(20)     '$.NOIDENTDECLARACION' , 
			EXPEDIDAENDECLA       varchar(20)     '$.EXPEDIDAENDECLA' , 
			NOPOLIZA              varchar(20)     '$.NOPOLIZA' , 
			TIPOPOLIZA            varchar(13)     '$.TIPOPOLIZA' , 
			TOPE1                 decimal         '$.TOPE1' , 
			REMITIDADETERCERO     varchar(20)     '$.REMITIDADETERCERO' , 
			COND_PNOMBRE          varchar(30)     '$.COND_PNOMBRE' , 
			COND_SNOMBRE          varchar(30)     '$.COND_SNOMBRE' , 
			COND_PAPELLIDO        varchar(30)     '$.COND_PAPELLIDO' , 
			COND_SAPELLIDO        varchar(30)     '$.COND_SAPELLIDO' , 
			INTERVAUTOR           varchar(2)      '$.INTERVAUTOR' , 
			COBROEXCEPOL          varchar(2)      '$.COBROEXCEPOL' , 
			PERSONAREMITE         varchar(40)     '$.PERSONAREMITE' , 
			CARGOPERREMITE        varchar(30)     '$.CARGOPERREMITE' , 
			DIRIPSREMITE          varchar(100)    '$.DIRIPSREMITE' , 
			TELIPSREMITE          varchar(20)     '$.TELIPSREMITE' , 
			F_ACEPTA              datetime	      '$.F_ACEPTA' , 
			PERREMITIDAA          varchar(40)     '$.PERREMITIDAA' , 
			PERSONARECIBE         varchar(60)     '$.PERSONARECIBE' , 
			CARGOPERRECIBE        varchar(40)     '$.CARGOPERRECIBE' , 
			DIRIPSRECIBE          varchar(100)    '$.DIRIPSRECIBE' , 
			CIUDADIPSRECIBE       varchar(5)      '$.CIUDADIPSRECIBE' , 
			TELIPSRECIBE          varchar(20)     '$.TELIPSRECIBE' , 
			PROPNOMBRE            varchar(30)     '$.PROPNOMBRE' , 
			PROSNOMBRE            varchar(30)     '$.PROSNOMBRE' , 
			PROPAPELLIDO          varchar(30)     '$.PROPAPELLIDO' , 
			PROSAPELLIDO          varchar(30)     '$.PROSAPELLIDO' , 
			PROTIPO_ID            varchar(3)      '$.PROTIPO_ID' , 
			PRODOCUMENTO          varchar(20)     '$.PRODOCUMENTO' , 
			PRODIRECCION          varchar(100)    '$.PRODIRECCION' , 
			PROCIUDAD             varchar(5)      '$.PROCIUDAD' , 
			PROTELEFONO           varchar(20)     '$.PROTELEFONO' , 
			NATUREVENTO           varchar(20)     '$.NATUREVENTO' , 
			NATURCUAL             varchar(30)     '$.NATURCUAL' , 
			F_RADICACION          date	          '$.F_RADICACION' , 
			NRORADICADO           varchar(30)     '$.NRORADICADO' , 
			NRORADICADOANT        varchar(30)     '$.NRORADICADOANT' , 
			NROFACTURA            varchar(30)     '$.NROFACTURA' , 
			RESPGLOSA             varchar(2)      '$.RESPGLOSA' , 
			FORMATO               varchar(2)      '$.FORMATO' , 
			PLACA_AMPARO          varchar(6)      '$.PLACA_AMPARO' , 
			PAPELLIDO_AMPARO      varchar(30)     '$.PAPELLIDO_AMPARO' , 
			SAPELLIDO_AMPARO      varchar(30)     '$.SAPELLIDO_AMPARO' , 
			PNOMBRE_AMPARO        varchar(30)     '$.PNOMBRE_AMPARO' , 
			SNOMBRE_AMPARO        varchar(30)     '$.SNOMBRE_AMPARO' , 
			TIPODOC_AMPARO        varchar(4)      '$.TIPODOC_AMPARO' , 
			DOC_AMPARO            varchar(30)     '$.DOC_AMPARO' , 
			TRANSPORTO_VIC_DESDE  varchar(30)     '$.TRANSPORTO_VIC_DESDE' , 
			TRANSPORTO_VIC_HASTA  varchar(30)     '$.TRANSPORTO_VIC_HASTA' , 
			TIPOTRANSPORTE        varchar(10)     '$.TIPOTRANSPORTE' , 
			ZONA_AMPARO           varchar(2)      '$.ZONA_AMPARO' , 
			ARMQXFACTURADO        decimal         '$.ARMQXFACTURADO' , 
			ARMQXFOSYGA           decimal         '$.ARMQXFOSYGA' , 
			ARTRANSFACTURADO      decimal         '$.ARTRANSFACTURADO' , 
			ARTRANSFOSYGA         decimal         '$.ARTRANSFOSYGA' , 
			CIUDAD_AMPARO         varchar(5)      '$.CIUDAD_AMPARO' , 
			F_AMPARO              date	          '$.F_AMPARO' , 
			VH2_PLANCA            varchar(6)      '$.VH2_PLANCA' , 
			VH2_PROTIPODOC        varchar(4)      '$.VH2_PROTIPODOC' , 
			VH2_PRODOC            varchar(20)     '$.VH2_PRODOC' , 
			VH2_PRONOMBRE         varchar(50)     '$.VH2_PRONOMBRE' , 
			VH3_PLANCA            varchar(6)      '$.VH3_PLANCA' , 
			VH3_PROTIPODOC        varchar(4)      '$.VH3_PROTIPODOC' , 
			VH3_PRODOC            varchar(20)     '$.VH3_PRODOC' , 
			VH3_PRONOMBRE         varchar(50)     '$.VH3_PRONOMBRE' , 
			CER_HACTRAN           varchar(20)     '$.CER_HACTRAN' , 
			COD_IPSREMITE         varchar(20)     '$.COD_IPSREMITE' , 
			COD_IPSRECIBE         varchar(20)     '$.COD_IPSRECIBE' ,  
			COD_IPSRECIBE_AMPARO  varchar(20)     '$.COD_IPSRECIBE_AMPARO' , 
			REM_TIPOREFERENCIA    varchar(2)      '$.REM_TIPOREFERENCIA' , 
			OTROTIPOTRANS         varchar(30)     '$.OTROTIPOTRANS' , 
			REMITIDAATERCERO      varchar(20)     '$.REMITIDAATERCERO' , 
			EXPORTADO             smallint        '$.EXPORTADO' , 
			IDFIRMAPTE            varchar(50)     '$.IDFIRMAPTE' , 
			IDFIRMARESP           varchar(50)     '$.IDFIRMARESP' , 
			ASIGNATOPE            smallint        '$.ASIGNATOPE' , 
			TIPOVEHICULO          varchar(2)      '$.TIPOVEHICULO' , 
			CILINDRAJE            varchar(10)     '$.CILINDRAJE' ,
			NOSIRAS               varchar(20)     '$.NOSIRAS' , 
			CUPSPPALHOSP          varchar(6)      '$.CUPSPPALHOSP' , 
			CUPSPPALQX            varchar(6)      '$.CUPSPPALQX' , 
			CUPSSECQX             varchar(6)      '$.CUPSSECQX' , 
			PLACATRASLINTER       varchar(6)      '$.PLACATRASLINTER' , 
			PRESTOUCI             varchar(1)      '$.PRESTOUCI' , 
			MATOSTEOSINTESIS      varchar(1)      '$.MATOSTEOSINTESIS' , 
			ATENCIONFACTURADA     varchar(1)      '$.ATENCIONFACTURADA' , 
			COMPLEJIDADQX         varchar(1)      '$.COMPLEJIDADQX',   
			FECHACERTIFICA        DATE	          '$.FECHACERTIFICA' ,   
			DIASUCI				  INTEGER	      '$.DIASUCI'  ,   
			TARIFADIFERENCIAL	  INTEGER	      '$.TARIFADIFERENCIAL' 
			, FECHAFALLECE	date			'$.FECHAFALLECE'
		)

		IF NOT EXISTS(
			SELECT 1
			FROM HACTRAN inner join #TMPHACTRAN A
			ON HACTRAN.IDAFILIADO= A.IDAFILIADO  collate database_default
			AND HACTRAN.FECHAACC = A.FECHAACC )
		BEGIN
			IF @SEDE IS NULL OR @COMPANIA IS NULL
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'No se pudo determinar la SEDE o COMPANIA del usuario. Verificar que el equipo (' + COALESCE(@SYS_COMPUTERNAME,'NULL') + ') exista en UBEQ. @SEDE=' + COALESCE(@SEDE,'NULL') + ' @COMPANIA=' + COALESCE(@COMPANIA,'NULL')
			END
			ELSE
			BEGIN

			IF NOT EXISTS (SELECT * FROM USCXS WHERE PREFIJO = '@HACTRAN' )
				INSERT INTO USCXS SELECT @COMPANIA, @SEDE, '','', '@HACTRAN' , 1 , '', 0

			EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE, '@HACTRAN', @CNSHACTRAN OUTPUT
			SELECT @CNSHACTRAN = @SEDE + REPLACE(SPACE(8 - LEN(@CNSHACTRAN))+LTRIM(RTRIM(@CNSHACTRAN)),SPACE(1),0)

			IF @CNSHACTRAN IS NULL
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'No se genero el consecutivo CNSHACTRAN. Verificar SPK_GENCONSECUTIVO y la tabla USCXS para prefijo @HACTRAN. @SEDE=' + COALESCE(@SEDE,'NULL') + ' @COMPANIA=' + COALESCE(@COMPANIA,'NULL')
			END
			ELSE
			BEGIN --- @CNSHACTRAN tiene valor

			UPDATE #TMPHACTRAN SET CNSHACTRAN = @CNSHACTRAN WHERE 1=1
			 -- COLOCO LOS NULL DONDE NO HAY FECHA
			 UPDATE #TMPHACTRAN SET 
					   FECHAACC		      = ( CASE WHEN COALESCE(YEAR(FECHAACC) ,		'1900')		=  '1900' THEN NULL ELSE FECHAACC END ) 
				   ,FECHAINIPOL	   = ( CASE WHEN COALESCE(YEAR(FECHAINIPOL ),	'1900')		=  '1900' THEN NULL ELSE FECHAINIPOL END ) 
				   ,FECHAFINPOL	   = ( CASE WHEN COALESCE(YEAR(FECHAFINPOL ),	'1900')		=  '1900' THEN NULL ELSE FECHAFINPOL END ) 
				   ,FECHA_RD		   = ( CASE WHEN COALESCE(YEAR(FECHA_RD ),		'1900')		=  '1900' THEN NULL ELSE FECHA_RD END ) 
				   ,FECHA			   = ( CASE WHEN COALESCE(YEAR(FECHA ),			'1900')		=  '1900' THEN NULL ELSE FECHA END ) 
				   ,F_ACEPTA		   = ( CASE WHEN COALESCE(YEAR(F_ACEPTA ),		'1900')		=  '1900' THEN NULL ELSE F_ACEPTA END ) 
				   ,F_RADICACION	   = ( CASE WHEN COALESCE(YEAR(F_RADICACION) ,	'1900')		=  '1900' THEN NULL ELSE F_RADICACION END ) 
				   ,F_AMPARO		   = ( CASE WHEN COALESCE(YEAR(F_AMPARO ),		'1900')		=  '1900' THEN NULL ELSE F_AMPARO END ) 
				   ,FECHACERTIFICA	= ( CASE WHEN COALESCE(YEAR(FECHACERTIFICA ), '1900')		=  '1900' THEN NULL ELSE FECHACERTIFICA  END )
				   ,FECHAFALLECE	= ( CASE WHEN COALESCE(YEAR(FECHAFALLECE ), '1900')		=  '1900' THEN NULL ELSE FECHAFALLECE  END )
			 WHERE 1=1

			 UPDATE #TMPHACTRAN
				SET CILINDRAJE = NULLIF(LTRIM(RTRIM(CILINDRAJE)), ''),
					TOPE1 = CASE
						WHEN TIPOVEHICULO = '10' AND TRY_CONVERT(INT, CILINDRAJE) > 201 THEN TOPE
						ELSE TOPE1
					END,
					ASIGNATOPE = CASE
						WHEN TIPOVEHICULO = '10' AND TRY_CONVERT(INT, CILINDRAJE) > 201 THEN 0
						ELSE ASIGNATOPE
					END
			 WHERE 1=1

			SELECT @COLUMNAS = DBO.FNK_COLUMNAS_TABLAS('HACTRAN') 
			BEGIN TRY
				SET @SQL = ' INSERT INTO HACTRAN ( ' +  @COLUMNAS + ')
						SELECT ' +  @COLUMNAS + ' FROM #TMPHACTRAN '
		
				INSERT INTO API_LOG ( FECHA , COMMAND  , COMMANDTYPE  , USUARIO )
				SELECT  GETDATE() , @SQL ,'SQL' , @USUARIO 
				EXECUTE ( @SQL)
				
				UPDATE AFI SET FECHAFALLECE = ( SELECT TOP 1  FECHAFALLECE FROM #TMPHACTRAN ) WHERE IDAFILIADO = ( SELECT TOP 1  IDAFILIADO FROM #TMPHACTRAN )

				SELECT 'OK' OK
				SELECT * FROM HACTRAN WHERE CNSHACTRAN=@CNSHACTRAN
			END TRY
			BEGIN CATCH
				SELECT  @error = CONCAT ( 'Error Numero : ', CONVERT(VARCHAR(100), ERROR_NUMBER() ) , 
						' | Severidad : ' , CONVERT(VARCHAR(100), ERROR_SEVERITY() )  ,
						' | Estado del Error : ' ,  CONVERT(VARCHAR(100),  ERROR_STATE()  ) ,
						' | Procedimiento de Error : ' , CONVERT(VARCHAR(100), ERROR_PROCEDURE() ) ,
						' | Linea : ', CONVERT(VARCHAR(100), ERROR_LINE() ) ,
						' | Mensaje de Error : ',ERROR_MESSAGE() ) 

				INSERT INTO @TBLERRORES(ERROR) SELECT COALESCE(@error, 'ERROR AL INSERTAR: CNSHACTRAN=' + COALESCE(@CNSHACTRAN,'NULL'))
			END CATCH
			END --- cierra ELSE de @CNSHACTRAN IS NULL
			END --- cierra ELSE de @SEDE/@COMPANIA IS NULL
		END
		ELSE 
		BEGIN 
			INSERT INTO @TBLERRORES(ERROR) SELECT  'YA ESTA CREADO EL ACCIDENTE NO PUEDO INSERTARLO EL MISMO IDAFILIADO ACCIDENTADO EL MISMO DIA'   
		END
	END  ---INSERT
	IF @METODO = 'UPDATE'
	BEGIN
		SELECT @CNSHACTRAN = CNSHACTRAN
		FROM OPENJSON(@PARAMETROS)
		WITH(CNSHACTRAN  VARCHAR(20) '$.CNSHACTRAN')

		SELECT * INTO #TMPHACTRANU
		FROM OPENJSON(@PARAMETROS)
		WITH(
			CNSHACTRAN            varchar(20)     '$.CNSHACTRAN' , 
			IDAFILIADO            varchar(20)     '$.IDAFILIADO' , 
			SITIOACC              varchar(250)    '$.SITIOACC' , 
			FECHAACC              datetime        '$.FECHAACC' , 
			CIUDAD                varchar(5)      '$.CIUDAD' , 
			ZONA                  varchar(6)      '$.ZONA' , 
			INFORME               varchar(1000)   '$.INFORME' , 
			PLACA                 varchar(10)     '$.PLACA' , 
			MARCA                 varchar(19)     '$.MARCA' , 
			TIPO                  varchar(20)     '$.TIPO' , 
			IDASEGURADORA         varchar(20)     '$.IDASEGURADORA' , 
			SUCURSAL              varchar(20)     '$.SUCURSAL' , 
			FECHAINIPOL           date	          '$.FECHAINIPOL' , 
			FECHAFINPOL           date	          '$.FECHAFINPOL' , 
			CONDUCTOR             varchar(40)     '$.CONDUCTOR' , 
			EDAD                  smallint        '$.EDAD' , 
			SEXO                  varchar(9)      '$.SEXO' , 
			TIPODOC               varchar(3)      '$.TIPODOC' , 
			NODOCUMENTO           varchar(20)     '$.NODOCUMENTO' , 
			DE                    varchar(20)     '$.DE' , 
			DIRECCION             varchar(100)    '$.DIRECCION' , 
			CIUDADCOND            varchar(5)      '$.CIUDADCOND' , 
			TELEFONO              varchar(12)     '$.TELEFONO' , 
			CONDICIONACC          varchar(8)      '$.CONDICIONACC' , 
			REMITIDADE            varchar(50)     '$.REMITIDADE' , 
			REMITIDADECIUDAD      varchar(5)      '$.REMITIDADECIUDAD' , 
			FECHA_RD              datetime        '$.FECHA_RD' , 
			TOPE                  decimal         '$.TOPE' , 
			VLRGASTADO            decimal         '$.VLRGASTADO' , 
			VLRFALTA              decimal         '$.VLRFALTA' , 
			FECHA                 date	          '$.FECHA' , 
			USUARIO               Varchar(12)     '$.USUARIO' , 
			GASTOEXTERNO          smallint        '$.GASTOEXTERNO' , 
			VLRGASTOEXTERNO       decimal         '$.VLRGASTOEXTERNO' , 
			DECLARACIONDE         varchar(50)     '$.DECLARACIONDE' , 
			NOIDENTDECLARACION    varchar(20)     '$.NOIDENTDECLARACION' , 
			EXPEDIDAENDECLA       varchar(20)     '$.EXPEDIDAENDECLA' , 
			NOPOLIZA              varchar(20)     '$.NOPOLIZA' , 
			TIPOPOLIZA            varchar(13)     '$.TIPOPOLIZA' , 
			TOPE1                 decimal         '$.TOPE1' , 
			REMITIDADETERCERO     varchar(20)     '$.REMITIDADETERCERO' , 
			COND_PNOMBRE          varchar(30)     '$.COND_PNOMBRE' , 
			COND_SNOMBRE          varchar(30)     '$.COND_SNOMBRE' , 
			COND_PAPELLIDO        varchar(30)     '$.COND_PAPELLIDO' , 
			COND_SAPELLIDO        varchar(30)     '$.COND_SAPELLIDO' , 
			INTERVAUTOR           varchar(2)      '$.INTERVAUTOR' , 
			COBROEXCEPOL          varchar(2)      '$.COBROEXCEPOL' , 
			PERSONAREMITE         varchar(40)     '$.PERSONAREMITE' , 
			CARGOPERREMITE        varchar(30)     '$.CARGOPERREMITE' , 
			DIRIPSREMITE          varchar(100)    '$.DIRIPSREMITE' , 
			TELIPSREMITE          varchar(20)     '$.TELIPSREMITE' , 
			F_ACEPTA              datetime        '$.F_ACEPTA' , 
			PERREMITIDAA          varchar(40)     '$.PERREMITIDAA' , 
			PERSONARECIBE         varchar(60)     '$.PERSONARECIBE' , 
			CARGOPERRECIBE        varchar(40)     '$.CARGOPERRECIBE' , 
			DIRIPSRECIBE          varchar(100)    '$.DIRIPSRECIBE' , 
			CIUDADIPSRECIBE       varchar(5)      '$.CIUDADIPSRECIBE' , 
			TELIPSRECIBE          varchar(20)     '$.TELIPSRECIBE' , 
			PROPNOMBRE            varchar(30)     '$.PROPNOMBRE' , 
			PROSNOMBRE            varchar(30)     '$.PROSNOMBRE' , 
			PROPAPELLIDO          varchar(30)     '$.PROPAPELLIDO' , 
			PROSAPELLIDO          varchar(30)     '$.PROSAPELLIDO' , 
			PROTIPO_ID            varchar(3)      '$.PROTIPO_ID' , 
			PRODOCUMENTO          varchar(20)     '$.PRODOCUMENTO' , 
			PRODIRECCION          varchar(100)    '$.PRODIRECCION' , 
			PROCIUDAD             varchar(5)      '$.PROCIUDAD' , 
			PROTELEFONO           varchar(20)     '$.PROTELEFONO' , 
			NATUREVENTO           varchar(20)     '$.NATUREVENTO' , 
			NATURCUAL             varchar(30)     '$.NATURCUAL' , 
			F_RADICACION          date	          '$.F_RADICACION' , 
			NRORADICADO           varchar(30)     '$.NRORADICADO' , 
			NRORADICADOANT        varchar(30)     '$.NRORADICADOANT' , 
			NROFACTURA            varchar(30)     '$.NROFACTURA' , 
			RESPGLOSA             varchar(2)      '$.RESPGLOSA' , 
			FORMATO               varchar(2)      '$.FORMATO' , 
			PLACA_AMPARO          varchar(6)      '$.PLACA_AMPARO' , 
			PAPELLIDO_AMPARO      varchar(30)     '$.PAPELLIDO_AMPARO' , 
			SAPELLIDO_AMPARO      varchar(30)     '$.SAPELLIDO_AMPARO' , 
			PNOMBRE_AMPARO        varchar(30)     '$.PNOMBRE_AMPARO' , 
			SNOMBRE_AMPARO        varchar(30)     '$.SNOMBRE_AMPARO' , 
			TIPODOC_AMPARO        varchar(4)      '$.TIPODOC_AMPARO' , 
			DOC_AMPARO            varchar(30)     '$.DOC_AMPARO' , 
			TRANSPORTO_VIC_DESDE  varchar(30)     '$.TRANSPORTO_VIC_DESDE' , 
			TRANSPORTO_VIC_HASTA  varchar(30)     '$.TRANSPORTO_VIC_HASTA' , 
			TIPOTRANSPORTE        varchar(10)     '$.TIPOTRANSPORTE' , 
			ZONA_AMPARO           varchar(2)      '$.ZONA_AMPARO' , 
			ARMQXFACTURADO        decimal         '$.ARMQXFACTURADO' , 
			ARMQXFOSYGA           decimal         '$.ARMQXFOSYGA' , 
			ARTRANSFACTURADO      decimal         '$.ARTRANSFACTURADO' , 
			ARTRANSFOSYGA         decimal         '$.ARTRANSFOSYGA' , 
			CIUDAD_AMPARO         varchar(5)      '$.CIUDAD_AMPARO' , 
			F_AMPARO              date	          '$.F_AMPARO' , 
			VH2_PLANCA            varchar(6)      '$.VH2_PLANCA' , 
			VH2_PROTIPODOC        varchar(4)      '$.VH2_PROTIPODOC' , 
			VH2_PRODOC            varchar(20)     '$.VH2_PRODOC' , 
			VH2_PRONOMBRE         varchar(50)     '$.VH2_PRONOMBRE' , 
			VH3_PLANCA            varchar(6)      '$.VH3_PLANCA' , 
			VH3_PROTIPODOC        varchar(4)      '$.VH3_PROTIPODOC' , 
			VH3_PRODOC            varchar(20)     '$.VH3_PRODOC' , 
			VH3_PRONOMBRE         varchar(50)     '$.VH3_PRONOMBRE' , 
			CER_HACTRAN           varchar(20)     '$.CER_HACTRAN' , 
			COD_IPSREMITE         varchar(20)     '$.COD_IPSREMITE' , 
			COD_IPSRECIBE         varchar(20)     '$.COD_IPSRECIBE' , 
			COD_IPSRECIBE_AMPARO  varchar(20)     '$.COD_IPSRECIBE_AMPARO' , 
			REM_TIPOREFERENCIA    varchar(2)      '$.REM_TIPOREFERENCIA' , 
			OTROTIPOTRANS         varchar(30)     '$.OTROTIPOTRANS' , 
			REMITIDAATERCERO      varchar(20)     '$.REMITIDAATERCERO' , 
			EXPORTADO             smallint        '$.EXPORTADO' , 
			IDFIRMAPTE            varchar(50)     '$.IDFIRMAPTE' , 
			IDFIRMARESP           varchar(50)     '$.IDFIRMARESP' , 
			ASIGNATOPE            smallint        '$.ASIGNATOPE' , 
			TIPOVEHICULO          varchar(2)      '$.TIPOVEHICULO' , 
			CILINDRAJE            varchar(10)     '$.CILINDRAJE' ,
			NOSIRAS               varchar(20)     '$.NOSIRAS' , 
			CUPSPPALHOSP          varchar(6)      '$.CUPSPPALHOSP' , 
			CUPSPPALQX            varchar(6)      '$.CUPSPPALQX' , 
			CUPSSECQX             varchar(6)      '$.CUPSSECQX' , 
			PLACATRASLINTER       varchar(6)      '$.PLACATRASLINTER' , 
			PRESTOUCI             varchar(1)      '$.PRESTOUCI' , 
			MATOSTEOSINTESIS      varchar(1)      '$.MATOSTEOSINTESIS' , 
			ATENCIONFACTURADA     varchar(1)      '$.ATENCIONFACTURADA' , 
			COMPLEJIDADQX         varchar(1)      '$.COMPLEJIDADQX'   , 
			FECHACERTIFICA        DATE	          '$.FECHACERTIFICA' ,			  
			DIASUCI				  INTEGER	      '$.DIASUCI' ,			  
			TARIFADIFERENCIAL	  INTEGER	      '$.TARIFADIFERENCIAL' 
			, FECHAFALLECE	date			'$.FECHAFALLECE'
		)


		IF NOT EXISTS (SELECT 1 FROM HACTRAN INNER JOIN #TMPHACTRANU ON HACTRAN.CNSHACTRAN=#TMPHACTRANU.CNSHACTRAN)
		BEGIN 
			PRINT 'NO EXISTE EL HACTRAN PARA ACTUALIZARLO'
			INSERT INTO @TBLERRORES(ERROR) SELECT  'NO EXISTE EL HACTRAN PARA ACTUALIZARLO' 
		END
		ELSE
		BEGIN
			BEGIN TRY
            	UPDATE #TMPHACTRANU SET 
				         FECHAACC		      = ( CASE WHEN COALESCE(YEAR(FECHAACC) ,		'1900')		=  '1900' THEN NULL ELSE FECHAACC END ) 
                     ,FECHAINIPOL	   = ( CASE WHEN COALESCE(YEAR(FECHAINIPOL ),	'1900')		=  '1900' THEN NULL ELSE FECHAINIPOL END ) 
                     ,FECHAFINPOL	   = ( CASE WHEN COALESCE(YEAR(FECHAFINPOL ),	'1900')		=  '1900' THEN NULL ELSE FECHAFINPOL END ) 
                     ,FECHA_RD		   = ( CASE WHEN COALESCE(YEAR(FECHA_RD ),		'1900')		=  '1900' THEN NULL ELSE FECHA_RD END ) 
                     ,FECHA			   = ( CASE WHEN COALESCE(YEAR(FECHA ),			'1900')		=  '1900' THEN NULL ELSE FECHA END ) 
                     ,F_ACEPTA		   = ( CASE WHEN COALESCE(YEAR(F_ACEPTA ),		'1900')		=  '1900' THEN NULL ELSE F_ACEPTA END ) 
                     ,F_RADICACION	   = ( CASE WHEN COALESCE(YEAR(F_RADICACION) ,	'1900')		=  '1900' THEN NULL ELSE F_RADICACION END ) 
                     ,F_AMPARO		   = ( CASE WHEN COALESCE(YEAR(F_AMPARO ),		'1900')		=  '1900' THEN NULL ELSE F_AMPARO END ) 
                     ,FECHACERTIFICA	= ( CASE WHEN COALESCE(YEAR(FECHACERTIFICA ), '1900')		=  '1900' THEN NULL ELSE FECHACERTIFICA  END )
                     ,FECHAFALLECE	= ( CASE WHEN COALESCE(YEAR(FECHAFALLECE ), '1900')		=  '1900' THEN NULL ELSE FECHAFALLECE  END )
              WHERE 1=1

				UPDATE #TMPHACTRANU
				   SET CILINDRAJE = NULLIF(LTRIM(RTRIM(CILINDRAJE)), ''),
					   TOPE1 = CASE
						   WHEN TIPOVEHICULO = '10' AND TRY_CONVERT(INT, CILINDRAJE) > 201 THEN TOPE
						   ELSE TOPE1
					   END,
					   ASIGNATOPE = CASE
						   WHEN TIPOVEHICULO = '10' AND TRY_CONVERT(INT, CILINDRAJE) > 201 THEN 0
						   ELSE ASIGNATOPE
					   END
				WHERE 1=1
		         
				SET @SQL = ' 
				UPDATE HACTRAN SET
					  CNSHACTRAN          =  #TMPHACTRANU.CNSHACTRAN , 
					  IDAFILIADO          =  #TMPHACTRANU.IDAFILIADO , 
					  SITIOACC            =  #TMPHACTRANU.SITIOACC , 
					  FECHAACC            =  #TMPHACTRANU.FECHAACC , 
					  CIUDAD              =  #TMPHACTRANU.CIUDAD , 
					  ZONA                =  #TMPHACTRANU.ZONA , 
					  INFORME             =  #TMPHACTRANU.INFORME , 
					  MARCA               =  #TMPHACTRANU.MARCA , 
					  PLACA               =  #TMPHACTRANU.PLACA , 
					  TIPO                =  #TMPHACTRANU.TIPO , 
					  IDASEGURADORA       =  #TMPHACTRANU.IDASEGURADORA , 
					  SUCURSAL            =  #TMPHACTRANU.SUCURSAL , 
					  FECHAINIPOL         =  #TMPHACTRANU.FECHAINIPOL , 
					  FECHAFINPOL         =  #TMPHACTRANU.FECHAFINPOL , 
					  CONDUCTOR           =  #TMPHACTRANU.CONDUCTOR , 
					  EDAD                =  #TMPHACTRANU.EDAD , 
					  SEXO                =  #TMPHACTRANU.SEXO , 
					  TIPODOC             =  #TMPHACTRANU.TIPODOC , 
					  NODOCUMENTO         =  #TMPHACTRANU.NODOCUMENTO , 
					  DE                  =  #TMPHACTRANU.DE , 
					  DIRECCION           =  #TMPHACTRANU.DIRECCION , 
					  CIUDADCOND          =  #TMPHACTRANU.CIUDADCOND , 
					  TELEFONO            =  #TMPHACTRANU.TELEFONO , 
					  CONDICIONACC        =  #TMPHACTRANU.CONDICIONACC , 
					  REMITIDADE          =  #TMPHACTRANU.REMITIDADE , 
					  REMITIDADECIUDAD    =  #TMPHACTRANU.REMITIDADECIUDAD , 
					  FECHA_RD            =  #TMPHACTRANU.FECHA_RD , 
					  TOPE                =  #TMPHACTRANU.TOPE , 
					  VLRGASTADO          =  #TMPHACTRANU.VLRGASTADO , 
					  VLRFALTA            =  #TMPHACTRANU.VLRFALTA , 
					  FECHA               =  #TMPHACTRANU.FECHA , 
					  USUARIO             =  #TMPHACTRANU.USUARIO , 
					  GASTOEXTERNO        =  #TMPHACTRANU.GASTOEXTERNO , 
					  VLRGASTOEXTERNO     =  #TMPHACTRANU.VLRGASTOEXTERNO , 
					  DECLARACIONDE       =  #TMPHACTRANU.DECLARACIONDE , 
					  NOIDENTDECLARACION  =  #TMPHACTRANU.NOIDENTDECLARACION , 
					  EXPEDIDAENDECLA     =  #TMPHACTRANU.EXPEDIDAENDECLA , 
					  NOPOLIZA            =  #TMPHACTRANU.NOPOLIZA , 
					  TIPOPOLIZA          =  #TMPHACTRANU.TIPOPOLIZA , 
					  TOPE1               =  #TMPHACTRANU.TOPE1 , 
					  REMITIDADETERCERO   =  #TMPHACTRANU.REMITIDADETERCERO , 
					  COND_PNOMBRE        =  #TMPHACTRANU.COND_PNOMBRE , 
					  COND_SNOMBRE        =  #TMPHACTRANU.COND_SNOMBRE , 
					  COND_PAPELLIDO      =  #TMPHACTRANU.COND_PAPELLIDO , 
					  COND_SAPELLIDO      =  #TMPHACTRANU.COND_SAPELLIDO , 
					  INTERVAUTOR         =  #TMPHACTRANU.INTERVAUTOR , 
					  COBROEXCEPOL        =  #TMPHACTRANU.COBROEXCEPOL , 
					  PERSONAREMITE       =  #TMPHACTRANU.PERSONAREMITE , 
					  CARGOPERREMITE      =  #TMPHACTRANU.CARGOPERREMITE , 
					  DIRIPSREMITE        =  #TMPHACTRANU.DIRIPSREMITE , 
					  TELIPSREMITE        =  #TMPHACTRANU.TELIPSREMITE , 
					  F_ACEPTA            =  #TMPHACTRANU.F_ACEPTA , 
					  PERREMITIDAA        =  #TMPHACTRANU.PERREMITIDAA , 
					  PERSONARECIBE       =  #TMPHACTRANU.PERSONARECIBE , 
					  CARGOPERRECIBE      =  #TMPHACTRANU.CARGOPERRECIBE , 
					  DIRIPSRECIBE        =  #TMPHACTRANU.DIRIPSRECIBE , 
					  CIUDADIPSRECIBE     =  #TMPHACTRANU.CIUDADIPSRECIBE , 
					  TELIPSRECIBE        =  #TMPHACTRANU.TELIPSRECIBE , 
					  PROPNOMBRE          =  #TMPHACTRANU.PROPNOMBRE , 
					  PROSNOMBRE          =  #TMPHACTRANU.PROSNOMBRE , 
					  PROPAPELLIDO        =  #TMPHACTRANU.PROPAPELLIDO , 
					  PROSAPELLIDO        =  #TMPHACTRANU.PROSAPELLIDO , 
					  PROTIPO_ID          =  #TMPHACTRANU.PROTIPO_ID , 
					  PRODOCUMENTO        =  #TMPHACTRANU.PRODOCUMENTO , 
					  PRODIRECCION        =  #TMPHACTRANU.PRODIRECCION , 
					  PROCIUDAD           =  #TMPHACTRANU.PROCIUDAD , 
					  PROTELEFONO         =  #TMPHACTRANU.PROTELEFONO , 
					  NATUREVENTO         =  #TMPHACTRANU.NATUREVENTO , 
					  NATURCUAL           =  #TMPHACTRANU.NATURCUAL , 
					  F_RADICACION        =  #TMPHACTRANU.F_RADICACION , 
					  NRORADICADO         =  #TMPHACTRANU.NRORADICADO , 
					  NRORADICADOANT      =  #TMPHACTRANU.NRORADICADOANT , 
					  NROFACTURA          =  #TMPHACTRANU.NROFACTURA , 
					  RESPGLOSA           =  #TMPHACTRANU.RESPGLOSA , 
					  FORMATO             =  #TMPHACTRANU.FORMATO , 
					  PLACA_AMPARO        =  #TMPHACTRANU.PLACA_AMPARO , 
					  PAPELLIDO_AMPARO    =  #TMPHACTRANU.PAPELLIDO_AMPARO , 
					  SAPELLIDO_AMPARO    =  #TMPHACTRANU.SAPELLIDO_AMPARO , 
					  PNOMBRE_AMPARO      =  #TMPHACTRANU.PNOMBRE_AMPARO , 
					  SNOMBRE_AMPARO      =  #TMPHACTRANU.SNOMBRE_AMPARO , 
					  TIPODOC_AMPARO      =  #TMPHACTRANU.TIPODOC_AMPARO , 
					  DOC_AMPARO          =  #TMPHACTRANU.DOC_AMPARO , 
					  TRANSPORTO_VIC_DESDE=  #TMPHACTRANU.TRANSPORTO_VIC_DESDE , 
					  TRANSPORTO_VIC_HASTA=  #TMPHACTRANU.TRANSPORTO_VIC_HASTA , 
					  TIPOTRANSPORTE      =  #TMPHACTRANU.TIPOTRANSPORTE , 
					  ZONA_AMPARO         =  #TMPHACTRANU.ZONA_AMPARO , 
					  ARMQXFACTURADO      =  #TMPHACTRANU.ARMQXFACTURADO , 
					  ARMQXFOSYGA         =  #TMPHACTRANU.ARMQXFOSYGA , 
					  ARTRANSFACTURADO    =  #TMPHACTRANU.ARTRANSFACTURADO , 
					  ARTRANSFOSYGA       =  #TMPHACTRANU.ARTRANSFOSYGA , 
					  CIUDAD_AMPARO       =  #TMPHACTRANU.CIUDAD_AMPARO , 
					  F_AMPARO            =  #TMPHACTRANU.F_AMPARO , 
					  VH2_PLANCA          =  #TMPHACTRANU.VH2_PLANCA , 
					  VH2_PROTIPODOC      =  #TMPHACTRANU.VH2_PROTIPODOC , 
					  VH2_PRODOC          =  #TMPHACTRANU.VH2_PRODOC , 
					  VH2_PRONOMBRE       =  #TMPHACTRANU.VH2_PRONOMBRE , 
					  VH3_PLANCA          =  #TMPHACTRANU.VH3_PLANCA , 
					  VH3_PROTIPODOC      =  #TMPHACTRANU.VH3_PROTIPODOC , 
					  VH3_PRODOC          =  #TMPHACTRANU.VH3_PRODOC , 
					  VH3_PRONOMBRE       =  #TMPHACTRANU.VH3_PRONOMBRE , 
					  CER_HACTRAN         =  #TMPHACTRANU.CER_HACTRAN , 
					  COD_IPSREMITE       =  #TMPHACTRANU.COD_IPSREMITE , 
					  COD_IPSRECIBE       =  #TMPHACTRANU.COD_IPSRECIBE , 
					  COD_IPSRECIBE_AMPARO=  #TMPHACTRANU.COD_IPSRECIBE_AMPARO , 
					  REM_TIPOREFERENCIA  =  #TMPHACTRANU.REM_TIPOREFERENCIA , 
					  OTROTIPOTRANS       =  #TMPHACTRANU.OTROTIPOTRANS , 
					  REMITIDAATERCERO    =  #TMPHACTRANU.REMITIDAATERCERO , 
					  EXPORTADO           =  #TMPHACTRANU.EXPORTADO , 
					  IDFIRMAPTE          =  #TMPHACTRANU.IDFIRMAPTE , 
					  IDFIRMARESP         =  #TMPHACTRANU.IDFIRMARESP , 
					  ASIGNATOPE          =  #TMPHACTRANU.ASIGNATOPE , 
					  TIPOVEHICULO        =  #TMPHACTRANU.TIPOVEHICULO , 
					  CILINDRAJE          =  #TMPHACTRANU.CILINDRAJE , 
					  NOSIRAS             =  #TMPHACTRANU.NOSIRAS , 
					  CUPSPPALHOSP        =  #TMPHACTRANU.CUPSPPALHOSP , 
					  CUPSPPALQX          =  #TMPHACTRANU.CUPSPPALQX , 
					  CUPSSECQX           =  #TMPHACTRANU.CUPSSECQX , 
					  PLACATRASLINTER     =  #TMPHACTRANU.PLACATRASLINTER , 
					  PRESTOUCI           =  #TMPHACTRANU.PRESTOUCI , 
					  MATOSTEOSINTESIS    =  #TMPHACTRANU.MATOSTEOSINTESIS , 
					  ATENCIONFACTURADA   =  #TMPHACTRANU.ATENCIONFACTURADA , 
					  COMPLEJIDADQX       =  #TMPHACTRANU.COMPLEJIDADQX  , 
					  FECHACERTIFICA      =  #TMPHACTRANU.FECHACERTIFICA , 
					  DIASUCI			  =  #TMPHACTRANU.DIASUCI , 
					  TARIFADIFERENCIAL	  =  #TMPHACTRANU.TARIFADIFERENCIAL 
				FROM HACTRAN INNER JOIN #TMPHACTRANU ON HACTRAN.CNSHACTRAN=#TMPHACTRANU.CNSHACTRAN
				'

				INSERT INTO API_LOG ( FECHA , COMMAND  , COMMANDTYPE  , USUARIO )
				SELECT  GETDATE() , @SQL ,'SQL' , @USUARIO 
				EXECUTE ( @SQL)
				UPDATE AFI SET FECHAFALLECE = ( SELECT TOP 1  FECHAFALLECE FROM #TMPHACTRANU ) WHERE IDAFILIADO = ( SELECT TOP 1  IDAFILIADO FROM #TMPHACTRANU )
				SELECT 'OK' OK
				SELECT * FROM HACTRAN WHERE CNSHACTRAN=@CNSHACTRAN
			END TRY
			BEGIN CATCH
				SELECT  @error = CONCAT ( 'Error Numero : ', CONVERT(VARCHAR(100), ERROR_NUMBER() ) , 
						' | Severidad : ' , CONVERT(VARCHAR(100), ERROR_SEVERITY() )  ,
						' | Estado del Error : ' ,  CONVERT(VARCHAR(100),  ERROR_STATE()  ) ,
						' | Procedimiento de Error : ' , CONVERT(VARCHAR(100), ERROR_PROCEDURE() ) ,
						' | Linea : ', CONVERT(VARCHAR(100), ERROR_LINE() ) ,
						' | Mensaje de Error : ',ERROR_MESSAGE() ) 
				INSERT INTO @TBLERRORES(ERROR) SELECT  'NO PUEDO  ACTUALIZAR EL HACTRAN: ' + @CNSHACTRAN  + ' : ' + CONVERT(VARCHAR(20) , @@ERROR) 
			END CATCH
		END
	END   --- UPDATE
	IF @METODO = 'CERTIFICADORES'
	BEGIN
		SELECT 'OK' OK
		INSERT INTO HACTRANCE (PAPELLIDO,	SAPELLIDO,	PNOMBRE,	SNOMBRE,	TIPODOC,	DOCUMENTO,	CARGO)
		SELECT 'NA',	'NA',	'NA',	'NA',	'CC',	'NA',	'PGN'
		WHERE NOT EXISTS (SELECT 1 from  HACTRANCE WHERE DOCUMENTO='NA')

		SELECT DOCUMENTO value , concat(PAPELLIDO,' ' , SAPELLIDO,' ' , PNOMBRE,' ' , SNOMBRE) label 
		FROM HACTRANCE
		RETURN
	END  --- CERTIFICADORES
	IF @METODO = 'CERTIFICADO_ATENCION'
	BEGIN
		SELECT @PROCEDENCIA = JSON_VALUE(@PARAMETROS,'$.PROCEDENCIA')
		SELECT @NOREFERENCIA = JSON_VALUE(@PARAMETROS,'$.NOREFERENCIA')

		SELECT @CNSHACTRAN = HACTRAN.CNSHACTRAN, @IDAFILIADO = HACTRAN.IDAFILIADO
		FROM HACTRAND 
			INNER JOIN HACTRAN ON HACTRAN.CNSHACTRAN=HACTRAND.CNSHACTRAN
		WHERE HACTRAND.PROCEDENCIA=@PROCEDENCIA AND NOREFERENCIA=@NOREFERENCIA

		IF @PROCEDENCIA='QX'
		BEGIN
			SELECT TOP 1 @IDMEDICO = IDMEDICO FROM HCA WHERE NOADMISION = @NOREFERENCIA AND CLASEPLANTILLA IN (SELECT CLASEPLANTILLA FROM MPL WHERE COALESCE(HURG, 0) = 8)
			IF COALESCE(@IDMEDICO,'')=''
			BEGIN
				SELECT @IDMEDICO = IDMEDICOING FROM HADM WHERE NOADMISION=@NOREFERENCIA
			END
			SELECT @FECHAING = FECHA, @IDSEDE = IDSEDE FROM HADM WHERE NOADMISION=@NOREFERENCIA
		END
		
		ELSE IF @PROCEDENCIA='CE'
		BEGIN
			SELECT @IDMEDICO = IDSOLICITANTE, @FECHAING = FECHA, @IDSEDE = IDSEDE FROM AUT WHERE NOAUT=@NOREFERENCIA			
		END
		ELSE IF @PROCEDENCIA='CI'
		BEGIN
			SELECT @IDMEDICO = IDMEDICO, @FECHAING = FECHA, @IDSEDE = IDSEDE FROM CIT WHERE CONSECUTIVO=@NOREFERENCIA			
		END

		SELECT 'OK' OK
		SELECT
		HACTRAND.CNSHACTRAN
		,SUSCRITO = IIF(@PROCEDENCIA='QX','El suscrito, médico del servicio de Urgencias de','El Suscrito, médico del Servicio de Consulta Externa de') 
		,CERTIFICA = IIF(@PROCEDENCIA='QX','CERTIFICA que atendio en el Servicio de Urgencias al Señor(a)','CERTIFICA que atendio en el Servicio de Consulta Externa al Señor(a)')
		,NOMMEDICO = COALESCE(MED.NOMBRE,'')
		,NOMBREMED = COALESCE(MED.NOMBRE,'')
		,MED_NOREGISTRO = COALESCE(MED.NO_REGISTRO,'')

		,DPR_RAZONSOCIAL = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DESCRIPCION,TER.RAZONSOCIAL),'')
		,DPR_DIRECCION = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DIRECCION,TER.DIRECCION),'')
		,DPR_CIUDAD = COALESCE(DPR_CIU.NOMBRE,'')
		,DPR_DEPARTAMENTO = COALESCE(DPR_DEP.NOMBRE,'')
		,DPR_TELEFONO = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.TELEFONOS,TER.TELEFONOS),'')
		
		,EDAD = DATEDIFF(YEAR,AFI.FNACIMIENTO,COALESCE(HACTRAN.FECHAACC,GETDATE()))
		,NOMAFILIADO = COALESCE(AFI.NOMBREAFI,'')+' '+COALESCE(AFI.TIPO_DOC,'')+' '+COALESCE(AFI.DOCIDAFILIADO,'') + ' de '+DOC_CIU.NOMBRE
		,DIRECCION_AFI = COALESCE(AFI.DIRECCION,'')
		,CIUDAD_AFI = COALESCE(CIU.NOMBRE,'')
		,DEPARTAMENTO_AFI = COALESCE(DEP.NOMBRE,'')
		,TELEFONO_AFI = COALESCE(AFI.TELEFONORES,'')
		,DECLARA = 'quien según declaración de (5) '+COALESCE(HACTRAN.DECLARACIONDE,'')+' con CC No. '+COALESCE(HACTRAN.NOIDENTDECLARACION,'')+' Expedida en '+COALESCE(HACTRAN.EXPEDIDAENDECLA,'')
				+' fué victima del accidente de tránsito ocurrido el día '+CONVERT(VARCHAR,DAY(HACTRAN.FECHAACC))+' mes '+DATENAME(MONTH,HACTRAN.FECHAACC)+' año '+CONVERT(VARCHAR,YEAR(HACTRAN.FECHAACC))
				+' a las '+LEFT(CONVERT(varchar,HACTRAN.FECHAACC,108),5)+' horas (6) Ingresando al Servicio de '+IIF(@PROCEDENCIA='QX','Urgencias de esta Institución el día','Consulta Externa de esta Institución el día') 
				+' '+CONVERT(VARCHAR,DAY(@FECHAING))+' mes '+DATENAME(MONTH,@FECHAING)+' año '+CONVERT(VARCHAR,YEAR(@FECHAING))+' a las '+LEFT(CONVERT(varchar,@FECHAING,108),5)+' horas con los siguientes hallazgos: '
		,DIAGNOSTICO = COALESCE(MDX.IDDX,'')+' '+COALESCE(MDX.DESCRIPCION,'')
		,TA = COALESCE(HACTRAND.TA,'')
		,FC = COALESCE(HACTRAND.FC,'')
		,FR = COALESCE(HACTRAND.FR,'')
		,TEMP1 = COALESCE(HACTRAND.TEMP1,'')
		,ALERTA = IIF (ESTADOCONC='ALERTA','X',' ')
		,OBNUBILADO = IIF (ESTADOCONC='OBNUBILADO','X',' ')
		,ESTUPOROSO = IIF (ESTADOCONC='ESTUPOROSO','X',' ')
		,COMA = IIF (ESTADOCONC='COMA','X',' ')
		,NOMGLASGOW = COALESCE(GLASGOW.DESCRIPCION,'')
		,ESTEMBSI = IIF(HACTRAND.ESTADOEMBRIAGUEZ='SI','X',' ')
		,ESTEMBNO = IIF(HACTRAND.ESTADOEMBRIAGUEZ='NO','X',' ')
		,CABEZA1 = COALESCE(HACTRAND.CABEZA1,'')
		,CUELLO1 = COALESCE(HACTRAND.CUELLO1,'')
		,TORAX1  = COALESCE(HACTRAND.TORAX1,'')
		,ABDOMEN1 = COALESCE(HACTRAND.ABDOMEN1,'')
		,GENITOURINARIO1 = COALESCE(HACTRAND.GENITOURINARIO1,'')
		,PELVIS1	= COALESCE(HACTRAND.PELVIS1,'')
		,DORSO1		= COALESCE(HACTRAND.DORSO1,'')
		,NEUROLOGICO1 = COALESCE(HACTRAND.NEUROLOGICO1,'')
		,DIAGNOSTICO1 = COALESCE(HACTRAND.DIAGNOSTICO1,'')
		,TRATAMIENTO1 = COALESCE(HACTRAND.TRATAMIENTO1,'')
		,FIRMA = (SELECT DICOM FROM ARCHIVOS WHERE ID = MED.IDFIRMA)
		FROM HACTRAND
			INNER JOIN HACTRAN ON HACTRAN.CNSHACTRAN=HACTRAND.CNSHACTRAN
			LEFT JOIN AFI ON AFI.IDAFILIADO=HACTRAN.IDAFILIADO
			LEFT JOIN TER ON TER.IDTERCERO=@IPS
			LEFT JOIN SED ON SED.IDSEDE=@IDSEDE
			LEFT JOIN MED ON MED.IDMEDICO=@IDMEDICO
			LEFT JOIN CIU ON CIU.CIUDAD=AFI.CIUDAD
			LEFT JOIN DEP ON CIU.DPTO=DEP.DPTO
			LEFT JOIN MDX ON MDX.IDDX=HACTRAND.IDDX
			LEFT JOIN CIU DOC_CIU ON DOC_CIU.CIUDAD=AFI.CIUDADDOC
			LEFT JOIN CIU DPR_CIU ON DPR_CIU.CIUDAD=IIF(@DATOSPROPIETARIO='SEDE',SED.CIUDAD, TER.CIUDAD)
			LEFT JOIN DEP DPR_DEP ON DPR_CIU.DPTO = DPR_DEP.DPTO
			LEFT JOIN TGEN GLASGOW ON GLASGOW.TABLA = 'GENERAL' AND GLASGOW.CAMPO='TIPOGLASGOW' AND GLASGOW.CODIGO=HACTRAND.TIPOGASGLOW
		WHERE HACTRAND.CNSHACTRAN=@CNSHACTRAN AND HACTRAND.PROCEDENCIA=@PROCEDENCIA AND NOREFERENCIA=@NOREFERENCIA
		RETURN
	END
	IF @METODO = 'CERTIFICADO_CONSUMO'
	BEGIN
		SELECT @NOREFERENCIA = NOREFERENCIA , @CNSHACTRAN = CNSHACTRAN , @PROCEDENCIA =  PROCEDENCIA
		FROM OPENJSON (@PARAMETROS) WITH (
				CNSHACTRAN         varchar (20)             '$.CNSHACTRAN',
				PROCEDENCIA        varchar (10)             '$.PROCEDENCIA',
				NOREFERENCIA       varchar (20)             '$.NOREFERENCIA'
		)
		
		IF @PROCEDENCIA='QX'
		BEGIN
			SELECT @IDTERCERO = IDTERCERO, @IDSEDE = IDSEDE FROM HADM WHERE NOADMISION=@NOREFERENCIA
		END		
		ELSE IF @PROCEDENCIA='CE'
		BEGIN
			SELECT @IDTERCERO = COALESCE(IDTERCEROCA, IDCONTRATANTE), @IDSEDE = IDSEDE FROM AUT WHERE NOAUT=@NOREFERENCIA
		END
		ELSE IF @PROCEDENCIA='CI'
		BEGIN
			SELECT @IDTERCERO = COALESCE(IDTERCEROCA, IDCONTRATANTE), @IDSEDE = IDSEDE FROM CIT WHERE CONSECUTIVO=@NOREFERENCIA			
		END

		SELECT 'OK' AS OK
		SELECT  TOP 1
			 SED_NOMBRE = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DESCRIPCION,IPS.RAZONSOCIAL),'')
			,SED_NIT = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.NIT,IPS.NIT),'')
			,SED_DV = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DV,IPS.DV),'')
			,SED_DIRECCION = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DIRECCION,IPS.DIRECCION),'')
			,SED_TELEFONOS = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.TELEFONOS,IPS.TELEFONOS),'')
			,SED_CIUDAD = COALESCE(DPR_CIU.NOMBRE,'')
			,NOTA = 'NOTA: La procedencia EXTERNO es el valor consumido por el paciente fuera de ' + COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DESCRIPCION,IPS.RAZONSOCIAL),'')   
			,TEXTO_COMPROBANTE = 'La clinica '+ COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DESCRIPCION,IPS.RAZONSOCIAL),'') +', Certifica que el(la) señor(a) antes mencionado(a) consumio hasta la fecha indicada, como victima de accidente de transito el(los) siguiente(s) Valor(es):'
			,AFI.NOMBREAFI 
			,AFI.TIPO_DOC
			,AFI.DOCIDAFILIADO
			,CONTRATANTE = TER.RAZONSOCIAL
			,FECHAACTUAL = CONVERT(VARCHAR, getdate(), 103)+' '+LEFT(CONVERT(VARCHAR, getdate(), 8),5)
			,CONTRA_CONFPRESER = dbo.FNK_VALORVARIABLE('CONTRA_CONFPRESER') 
			,TER2.RAZONSOCIAL NOMBRE_ASEGURADORA 
			,HACTRAN.NATUREVENTO
			,HACTRAN.TIPOPOLIZA
			,FIRMA_USUARIO = (SELECT A.DICOM FROM USUSU INNER JOIN ARCHIVOS A ON A.ID=USUSU.IDFIRMA WHERE USUARIO=@USUARIO), @USUARIO USUARIO
			,HACTRAN.CNSHACTRAN
		FROM HACTRAN
			INNER JOIN	AFI				ON	AFI.IDAFILIADO=HACTRAN.IDAFILIADO
			LEFT JOIN	TER				ON	TER.IDTERCERO=@IDTERCERO
			LEFT JOIN	SED				ON	SED.IDSEDE=@IDSEDE
			LEFT JOIN	TER	TER2		ON	TER2.IDTERCERO=HACTRAN.IDASEGURADORA
			LEFT JOIN	CIU DPR_CIU		ON DPR_CIU.CIUDAD=IIF(@DATOSPROPIETARIO='SEDE',SED.CIUDAD, TER.CIUDAD)
			LEFT JOIN	TER	IPS			ON	IPS.IDTERCERO=@IPS
		WHERE HACTRAN.CNSHACTRAN = @CNSHACTRAN

		SELECT HACTRAND.ITEM 
		, CASE HACTRAND.PROCEDENCIA WHEN 'QX' THEN 'HOSPITALARIA' WHEN 'CI' THEN 'CONSULTA EXTERNA'  WHEN 'CE' THEN 'CONSULTA EXTERNA' ELSE  HACTRAND.PROCEDENCIA END PROCEDENCIA 
		,  HACTRAND.NOREFERENCIA  'NROINGREESO'
		, ATENCION.IDDX CIE10 
		, TER.RAZONSOCIAL NOMBREENTIDAD, HACTRAND.VLRGASTADO VRCONSUMO, IPSHAB.NOMBREENTIDAD NOMBRETEREXTERNO, TER2.RAZONSOCIAL TERASEGURADORA
		 , trim(COALESCE( HACTRAND.N_FCT_FYG, HACTRAND.N_FCT_ASEG,'*sin ftr') ) FACTURA 
		FROM 	HACTRAN 
			INNER JOIN	HACTRAND		ON	HACTRAN.CNSHACTRAN =HACTRAND.CNSHACTRAN
			INNER JOIN	( SELECT 
								  COALESCE( HADM.CNSHACTRAN, COALESCE(CIT.CNSHACTRAN , COALESCE(AUT.CNSHACTRAN,''))) CNSHACTRAN
								, COALESCE( HADM.NOADMISION, COALESCE(CIT.CONSECUTIVO , COALESCE(AUT.NOAUT,''))) NOADMISION
								, COALESCE( HADM.IDAFILIADO, COALESCE(CIT.IDAFILIADO , COALESCE(AUT.IDAFILIADO,''))) IDAFILIADO
								, COALESCE( HADM.IDTERCERO, COALESCE(CIT.IDCONTRATANTE , COALESCE(AUT.IDCONTRATANTE,''))) IDTERCERO
								, COALESCE( HADM.IDSEDE, COALESCE(CIT.IDSEDE , COALESCE(AUT.IDSEDE,''))) IDSEDE
							  , COALESCE( HADM.DXINGRESO, COALESCE(HCA.IDDX , COALESCE(AUT.DXPPAL,''))) IDDX	
							  , COALESCE( HADM.FECHA, COALESCE(CIT.FECHA , COALESCE(AUT.FECHA,''))) FECHA 
							FROM	HACTRAN	
								LEFT JOIN HADM	ON	HACTRAN.IDAFILIADO = HADM.IDAFILIADO AND HADM.NOADMISION = @NOREFERENCIA AND @PROCEDENCIA='QX' AND HADM.CNSHACTRAN = HACTRAN.CNSHACTRAN
								LEFT JOIN CIT	ON	HACTRAN.IDAFILIADO = CIT.IDAFILIADO AND CIT.CONSECUTIVO = @NOREFERENCIA	AND @PROCEDENCIA='CI' AND CIT.CNSHACTRAN = HACTRAN.CNSHACTRAN
								LEFT JOIN AUT	ON	HACTRAN.IDAFILIADO = AUT.IDAFILIADO AND AUT.NOAUT = @NOREFERENCIA	AND @PROCEDENCIA ='CE' AND AUT.CNSHACTRAN = HACTRAN.CNSHACTRAN
								LEFT JOIN HCA ON CIT.CONSECUTIVOHCA = HCA.CONSECUTIVO
							WHERE HACTRAN.CNSHACTRAN =@CNSHACTRAN
						) 	ATENCION		ON	ATENCION.CNSHACTRAN = HACTRAN.CNSHACTRAN
			INNER JOIN	AFI				ON	AFI.IDAFILIADO=ATENCION.IDAFILIADO
			LEFT JOIN	TER				ON	TER.IDTERCERO=ATENCION.IDTERCERO
			LEFT JOIN	TER	TER2		ON	TER2.IDTERCERO=HACTRAN.IDASEGURADORA
			LEFT JOIN IPSHAB			ON  IPSHAB.NIT = HACTRAND.IDTERCEROEXT
		WHERE HACTRAN.CNSHACTRAN = @CNSHACTRAN
		RETURN
	END

	IF @METODO = 'FORMATO_RECLAMACION'
	BEGIN
		PRINT 'ENTRE A FORMATO_RECLAMACION'
		SELECT @PROCEDENCIA = JSON_VALUE(@PARAMETROS,'$.PROCEDENCIA')
		SELECT @NOREFERENCIA = JSON_VALUE(@PARAMETROS,'$.NOREFERENCIA')
		
		SELECT @CNSHACTRAN = HACTRAN.CNSHACTRAN, @IDAFILIADO = HACTRAN.IDAFILIADO
		FROM HACTRAND 
			INNER JOIN HACTRAN ON HACTRAN.CNSHACTRAN=HACTRAND.CNSHACTRAN
		WHERE HACTRAND.PROCEDENCIA=@PROCEDENCIA AND NOREFERENCIA=@NOREFERENCIA

		IF @PROCEDENCIA='QX'
		BEGIN
			SELECT TOP 1 @IDMEDICO = IDMEDICO FROM HCA WHERE NOADMISION = @NOREFERENCIA AND CLASEPLANTILLA IN (SELECT CLASEPLANTILLA FROM MPL WHERE COALESCE(HURG, 0) = 8)
			IF COALESCE(@IDMEDICO,'')=''
			BEGIN
				SELECT @IDMEDICO = IDMEDICOING FROM HADM WHERE NOADMISION=@NOREFERENCIA
			END
			SELECT @FECHAING = FECHA, @IDSEDE = IDSEDE , @FECHAEGR = coalesce(FECHAALTAMED ,getdate())  
			, @DXING = MDX.DESCRIPCION+ ' (' + MDX.IDDX +')' 
			, @DXEGR = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')'
			, @TIPOADM = HTAD.TIPOATENCION
			FROM HADM LEFT JOIN MDX ON MDX.IDDX= HADM.DXINGRESO 
				LEFT JOIN MDX MDX2 ON MDX2.IDDX= HADM.DXEGRESO 
				LEFT JOIN HTAD ON HTAD.TIPOADM = HADM.TIPOADM
			WHERE NOADMISION=@NOREFERENCIA
			PRINT 'QX --' + @IDMEDICO +'= IDMEDICO, '+ CONVERT(VARCHAR(20) , @FECHAING ) +'= FECHA, '+ @IDSEDE +' = IDSEDE '
		END
--QUERY2
--QUERY2
		ELSE IF @PROCEDENCIA='CE'
		BEGIN
			SELECT @IDMEDICO = IDSOLICITANTE, @FECHAING = FECHA , @IDSEDE = IDSEDE 
			,  @FECHAEGR = FECHA 
			, @DXING = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')' 
			, @DXEGR = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')'
			, @TIPOADM = 'A'
			FROM AUT 
				LEFT JOIN MDX MDX2 ON MDX2.IDDX= AUT.DXPPAL
			WHERE NOAUT=@NOREFERENCIA	
			PRINT 'CE --' + @IDMEDICO +'= IDMEDICO, '+CONVERT(VARCHAR(20) , @FECHAING ) +'= FECHA, '+ @IDSEDE+ ' = IDSEDE '
		END
		ELSE IF @PROCEDENCIA='CI'
		BEGIN
			SELECT @IDMEDICO = CIT.IDMEDICO, @FECHAING =CIT.FECHA, @IDSEDE = IDSEDE 
			,  @FECHAEGR = CIT.FECHA 
			, @DXING = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')' 
			, @DXEGR = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')'
			, @TIPOADM = 'A'
			FROM CIT 
				LEFT JOIN HCA ON (CIT.CONSECUTIVO = HCA.CONSECUTIVOCIT OR CIT.CONSECUTIVOHCA = HCA.CONSECUTIVO )AND CIT.IDAFILIADO = HCA.IDAFILIADO
				LEFT JOIN MDX MDX2 ON MDX2.IDDX= HCA.DX1
			WHERE CIT.CONSECUTIVO=@NOREFERENCIA			
			PRINT 'CI --' + @IDMEDICO +'= IDMEDICO, '+ CONVERT(VARCHAR(20) ,@FECHAING ) +'= FECHA, '+ @IDSEDE +' = IDSEDE '
		END
		
		PRINT @FECHAEGR
		
		SELECT 'OK' OK
		BEGIN TRY
			SELECT
			HACTRAND.CNSHACTRAN
			,YODECLARO = 'Yo '+COALESCE(AFI.NOMBREAFI,'')+' identificado(a) con cedula de ciudadanía número. '+COALESCE(AFI.DOCIDAFILIADO,'')+' declaro bajo la gravedad de juramento.'+
			' Que sufrí accidente de tránsito, y que la información contenida en el presente documento es cierta y puede ser verificada por la compañía de seguros. Al contactarme. '+
			'Acepto las consecuencias morales, administrativas y legales que genere la misma.'
			,CERTIFICA = IIF(@PROCEDENCIA='QX','CERTIFICA que atendio en el Servicio de Urgencias al Señor(a)','CERTIFICA que atendio en el Servicio de Consulta Externa al Señor(a)')
			,NOMMEDICO = COALESCE(MED.NOMBRE,'')
			,NOMBREMED = COALESCE(MED.NOMBRE,'')
			,MED_NOREGISTRO = COALESCE(MED.NO_REGISTRO,'')

			,DPR_RAZONSOCIAL = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DESCRIPCION,TER.RAZONSOCIAL),'')
			,DPR_DIRECCION = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DIRECCION,TER.DIRECCION),'')
			,DPR_NIT = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.NIT,TER.NIT),'')
			,DPR_CIUDAD = COALESCE(DPR_CIU.NOMBRE,'')
			,DPR_DEPARTAMENTO = COALESCE(DPR_DEP.NOMBRE,'')
			,DPR_TELEFONO = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.TELEFONOS,TER.TELEFONOS),'')
		
			,EDAD = DATEDIFF(YEAR,AFI.FNACIMIENTO,COALESCE(HACTRAN.FECHAACC,GETDATE()))
			,NOMAFILIADO = COALESCE(AFI.NOMBREAFI,'')+' '+COALESCE(AFI.TIPO_DOC,'')+' '+COALESCE(AFI.DOCIDAFILIADO,'') + ' de '+ISNULL(DOC_CIU.NOMBRE,'')
			,DIRECCION_AFI = COALESCE(AFI.DIRECCION,'')
			,CIUDAD_AFI = COALESCE(CIU.NOMBRE,'')
			,TIPO_DOC = COALESCE(AFI.TIPO_DOC,'')
			,DOCIDAFILIADO = COALESCE(AFI.DOCIDAFILIADO,'')
			,DOC_CIUDAD = COALESCE(DOC_CIU.CIUDAD,'')
			,SEXO = COALESCE(AFI.SEXO,'')
			,DEPARTAMENTO_AFI = COALESCE(DEP.NOMBRE,'')
			,TELEFONO_AFI = COALESCE(AFI.TELEFONORES,'')
			,DECLARA = 'EN REPRESENTACION DEL CENTRO ASISTENCIAL EN MENCION DECLARO BAJO LA GRAVEDAD DE JURAMENTO QUE LA INFORMACIÓN DILIGENCIADA EN ESTE DOCUMENTO ES CIERTA Y PUEDE SER VERIFICADA POR LA COMPAÑIA DE SEGUROS Y/O FONSAT, DENTRO DE LOS TREINTA (30) DIAS SIGUIENTES A LA FECHA DE PRESENTACION DE NO SER ASI ACEPTO TODAS LAS CONSECUENCIAS LEGALES QUE PRODUZCA ESTA SITUACIÓN.'
			,DIAGNOSTICO = COALESCE(MDX.IDDX,'')+' '+COALESCE(MDX.DESCRIPCION,'')
			,TA = COALESCE(HACTRAND.TA,'')
			,FC = COALESCE(HACTRAND.FC,'')
			,FR = COALESCE(HACTRAND.FR,'')
			,TEMP1 = COALESCE(HACTRAND.TEMP1,'')
			,ALERTA = IIF (ESTADOCONC='ALERTA','X',' ')
			,OBNUBILADO = IIF (ESTADOCONC='OBNUBILADO','X',' ')
			,ESTUPOROSO = IIF (ESTADOCONC='ESTUPOROSO','X',' ')
			,COMA = IIF (ESTADOCONC='COMA','X',' ')
			,NOMGLASGOW = COALESCE(GLASGOW.DESCRIPCION,'')
			,ESTEMBSI = IIF(HACTRAND.ESTADOEMBRIAGUEZ='SI','X',' ')
			,ESTEMBNO = IIF(HACTRAND.ESTADOEMBRIAGUEZ='NO','X',' ')
			,CABEZA1 = COALESCE(HACTRAND.CABEZA1,'')
			,CUELLO1 = COALESCE(HACTRAND.CUELLO1,'')
			,TORAX1  = COALESCE(HACTRAND.TORAX1,'')
			,ABDOMEN1 = COALESCE(HACTRAND.ABDOMEN1,'')
			,GENITOURINARIO1 = COALESCE(HACTRAND.GENITOURINARIO1,'')
			,PELVIS1	= COALESCE(HACTRAND.PELVIS1,'')
			,DORSO1		= COALESCE(HACTRAND.DORSO1,'')
			,NEUROLOGICO1 = COALESCE(HACTRAND.NEUROLOGICO1,'')
			,DIAGNOSTICO1 = COALESCE(HACTRAND.DIAGNOSTICO1,'')
			,TRATAMIENTO1 = COALESCE(HACTRAND.TRATAMIENTO1,'')
			,SITIOACC = COALESCE(HACTRAN.SITIOACC,'')
			,CONDICIONACC = COALESCE(HACTRAN.CONDICIONACC,'')
			,FECHAACC = COALESCE(CONVERT( VARCHAR(20),HACTRAN.FECHAACC,103 ),'')
			,HORAACC =COALESCE( RIGHT(CONVERT(VarChar(19), HACTRAN.FECHAACC , 0), 7),'') 
			,ACC_MUNICIPIO = COALESCE(ACC_CIU.CIUDAD,'')
			,ACC_DEPARTAMENTO = COALESCE(ACC_DEP.NOMBRE,'')
			,ZONA = COALESCE(HACTRAN.ZONA,'')
			,MARCA = COALESCE(HACTRAN.MARCA,'')
			,PLACA = COALESCE(HACTRAN.PLACA,'')
			,TIPO = COALESCE(HACTRAN.TIPO,'')
			,TIPOPOLIZA = COALESCE(HACTRAN.TIPOPOLIZA,'')
			,NOPOLIZA = COALESCE(HACTRAN.NOPOLIZA,'')
			,FECHAINIPOL = COALESCE(CONVERT( VARCHAR(10),HACTRAN.FECHAINIPOL,103 ),'')
			,FECHAFINPOL = COALESCE(CONVERT( VARCHAR(10),HACTRAN.FECHAFINPOL,103 ),'')
			,NOMBRE_CON = COALESCE(TRIM(HACTRAN.COND_PAPELLIDO + ' '+ HACTRAN.COND_SAPELLIDO) + ' ' +  TRIM( HACTRAN.COND_PNOMBRE+ ' ' +HACTRAN.COND_SNOMBRE) ,'')
			,EDAD_CON = COALESCE(HACTRAN.EDAD,'')
			,SEXO_CON = COALESCE(HACTRAN.SEXO,'')
			,TIPODOC_CON = COALESCE(HACTRAN.TIPODOC,'')
			,NODOCUMENTO_CON = COALESCE(HACTRAN.NODOCUMENTO,'')
			,DE_CON = COALESCE(HACTRAN.DE,'')
			,DIRECCION_CON = COALESCE(HACTRAN.DIRECCION,'')
			,CIUDAD_CON = COALESCE(CON_CIU.NOMBRE,'')
			,TELEFONO_CON = COALESCE(HACTRAN.TELEFONO,'')
			,ASE_NOMBRE = COALESCE(ASE_TER.RAZONSOCIAL,'')
			,REMITIDADE = COALESCE(HACTRAN.REMITIDADE,'')
			,FECHA_RD = COALESCE(CONVERT( VARCHAR(20),HACTRAN.FECHA_RD,103 ),'')
			,PERREMITIDAA = COALESCE(HACTRAN.PERREMITIDAA,'')
			,F_ACEPTA = COALESCE(CONVERT( VARCHAR(20),HACTRAN.F_ACEPTA,103 ),'')
			,SUCURSAL = COALESCE(HACTRAN.SUCURSAL,'')
			,INFORME = COALESCE(HACTRAN.INFORME,'')
			,FECHAINGRESO = COALESCE(CONVERT( VARCHAR(20), @FECHAING,103 ) ,'')
			,HORAINGRESO = COALESCE( RIGHT(CONVERT(VarChar(19), @FECHAING , 0), 7),'') 
			,FECHAEGRESO = COALESCE(CONVERT( VARCHAR(20),@FECHAEGR,103 ) ,'')
			,DIASESTANCIA =  CONVERT( INT , DATEDIFF(DAY,@FECHAING,@FECHAEGR) )
			,HISTORIANO = COALESCE(@NOREFERENCIA ,'')
			,DXINGRESO = COALESCE(@DXING ,'')
			,DXEGRESO = COALESCE(@DXEGR ,'')
			,TIPOADM = COALESCE(@TIPOADM ,'')
			,FECHA_MUERTE = COALESCE(CONVERT( VARCHAR(20),AFI.FECHAFALLECE,103 ),'')
			,HORA_MUERTE =  COALESCE( RIGHT(CONVERT(VarChar(19), AFI.FECHAFALLECE , 0), 7),'')  
			,MEDICOACTADEFUNCION = IIF(DBO.FNK_VALORVARIABLE('IDMEDICOALTA_BLANCO')='SI', '', COALESCE(MED.NOMBRE,''))
			,REGISTROMEDICOACTADEFUNCION = IIF(DBO.FNK_VALORVARIABLE('IDMEDICOALTA_BLANCO')='SI', '', COALESCE(MED.NO_REGISTRO,'') )
			,CIU_REGISTROMEDICOACTADEFUNCION = '' -- NO TENEMOS EL DATO
			,ACTADEFUNCION = COALESCE( HADM.ACTADEFUNCION,'')
			,CAUSAMUERTE = CASE COALESCE(AFI.ESTADO ,'') WHEN  'Muerto' THEN @DXEGR WHEN  'Fallecido' THEN @DXEGR ELSE '' END
			,FIRMA = (SELECT DICOM FROM ARCHIVOS WHERE ID = MED.IDFIRMA)
			,FECHAIMPRESION = GETDATE()
            ,IDFIRMAPTE= COALESCE(HADM.IDFIRMAPTE, HADM.IDFIRMARESP)
			FROM HACTRAND
				INNER JOIN HACTRAN ON HACTRAN.CNSHACTRAN=HACTRAND.CNSHACTRAN
				LEFT JOIN AFI ON AFI.IDAFILIADO=HACTRAN.IDAFILIADO
				LEFT JOIN TER ON TER.IDTERCERO=@IPS
				LEFT JOIN TER ASE_TER ON ASE_TER.IDTERCERO=HACTRAN.IDASEGURADORA
				LEFT JOIN SED ON SED.IDSEDE=@IDSEDE
				LEFT JOIN MED ON MED.IDMEDICO=@IDMEDICO
				LEFT JOIN CIU ON CIU.CIUDAD=AFI.CIUDAD
				LEFT JOIN DEP ON CIU.DPTO=DEP.DPTO
				LEFT JOIN MDX ON MDX.IDDX=HACTRAND.IDDX
				LEFT JOIN CIU DOC_CIU ON DOC_CIU.CIUDAD=AFI.CIUDADDOC
				LEFT JOIN CIU ACC_CIU ON ACC_CIU.CIUDAD=HACTRAN.CIUDAD
				LEFT JOIN CIU CON_CIU ON CON_CIU.CIUDAD=HACTRAN.CIUDADCOND
				LEFT JOIN DEP ACC_DEP ON ACC_DEP.DPTO=ACC_CIU.DPTO
				LEFT JOIN CIU DPR_CIU ON DPR_CIU.CIUDAD=IIF(@DATOSPROPIETARIO='SEDE',SED.CIUDAD, TER.CIUDAD)
				LEFT JOIN DEP DPR_DEP ON DPR_CIU.DPTO = DPR_DEP.DPTO
				LEFT JOIN TGEN GLASGOW ON GLASGOW.TABLA = 'GENERAL' AND GLASGOW.CAMPO='TIPOGLASGOW' AND GLASGOW.CODIGO=HACTRAND.TIPOGASGLOW
				LEFT JOIN HADM ON HADM.CNSHACTRAN= HACTRAN.CNSHACTRAN
			WHERE HACTRAND.CNSHACTRAN=@CNSHACTRAN AND HACTRAND.PROCEDENCIA=@PROCEDENCIA AND NOREFERENCIA=@NOREFERENCIA
		END TRY
		BEGIN CATCH
			PRINT 'SALIENDO POR EL CATCH'
			PRINT 'OCURRIO UN ERROR DESCONCIDO AL MOMENTO DE CONSULTAR LOS DATOS, CONSULTE CON EL ADMINISTRADOR DEL SISTEMA' 
			SELECT  @error = CONCAT ( 'Error Numero : ', CONVERT(VARCHAR(100), ERROR_NUMBER() ) , 
							' | Severidad : ' , CONVERT(VARCHAR(100), ERROR_SEVERITY() )  ,
							' | Estado del Error : ' ,  CONVERT(VARCHAR(100),  ERROR_STATE()  ) ,
							' | Procedimiento de Error : ' , CONVERT(VARCHAR(100), ERROR_PROCEDURE() ) ,
							' | Linea : ', CONVERT(VARCHAR(100), ERROR_LINE() ) ,
							' | Mensaje de Error : ',ERROR_MESSAGE() ) 

					PRINT 'NO PUEDO  OBTENER INFORMACION DE LA ADMISION : ' + @NOREFERENCIA   + ' : ' + @@ERROR  + ' :  ' +  @error
					INSERT INTO @TBLERRORES(ERROR) SELECT  'NO PUEDO  OBTENER INFORMACION DE LA ADMISION : ' + @NOREFERENCIA  + ' : ' + @@ERROR  + ' :  ' +  @error
			RETURN
		END CATCH
		PRINT 'SE COMPETO LA CONSULTA '
		RETURN
	END
	
	
	IF @METODO = 'AVISO_AUT_POLICIAL'
	BEGIN
		PRINT 'ENTRE A FORMATO AVISO DE AUTORIDAD POLICIAL'
		SELECT @PROCEDENCIA = JSON_VALUE(@PARAMETROS,'$.PROCEDENCIA')
		SELECT @NOREFERENCIA = JSON_VALUE(@PARAMETROS,'$.NOREFERENCIA')
		
		SELECT @CNSHACTRAN = HACTRAN.CNSHACTRAN, @IDAFILIADO = HACTRAN.IDAFILIADO
		FROM HACTRAND 
			INNER JOIN HACTRAN ON HACTRAN.CNSHACTRAN=HACTRAND.CNSHACTRAN
		WHERE HACTRAND.PROCEDENCIA=@PROCEDENCIA AND NOREFERENCIA=@NOREFERENCIA

		IF @PROCEDENCIA='QX'
		BEGIN
			SELECT TOP 1 @IDMEDICO = IDMEDICO FROM HCA WHERE NOADMISION = @NOREFERENCIA AND CLASEPLANTILLA IN (SELECT CLASEPLANTILLA FROM MPL WHERE COALESCE(HURG, 0) = 8)
			IF COALESCE(@IDMEDICO,'')=''
			BEGIN
				SELECT @IDMEDICO = IDMEDICOING FROM HADM WHERE NOADMISION=@NOREFERENCIA
			END
			SELECT @FECHAING = FECHA, @IDSEDE = IDSEDE , @FECHAEGR = coalesce(FECHAALTAMED ,getdate())  
			, @DXING = MDX.DESCRIPCION+ ' (' + MDX.IDDX +')' 
			, @DXEGR = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')'
			, @TIPOADM = HTAD.TIPOATENCION
			FROM HADM LEFT JOIN MDX ON MDX.IDDX= HADM.DXINGRESO 
				LEFT JOIN MDX MDX2 ON MDX2.IDDX= HADM.DXEGRESO 
				LEFT JOIN HTAD ON HTAD.TIPOADM = HADM.TIPOADM
			WHERE NOADMISION=@NOREFERENCIA

			SELECT @IDTERCERO = IDTERCERO, @IDSEDE = IDSEDE FROM HADM WHERE NOADMISION=@NOREFERENCIA

			PRINT 'QX --' + @IDMEDICO +'= IDMEDICO, '+ CONVERT(VARCHAR(20) , @FECHAING ) +'= FECHA, '+ @IDSEDE +' = IDSEDE '
		END
		ELSE IF @PROCEDENCIA='CE'
		BEGIN
			SELECT @IDMEDICO = IDSOLICITANTE, @FECHAING = FECHA , @IDSEDE = IDSEDE 
			,  @FECHAEGR = FECHA 
			, @DXING = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')' 
			, @DXEGR = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')'
			, @TIPOADM = 'A'
			FROM AUT 
				LEFT JOIN MDX MDX2 ON MDX2.IDDX= AUT.DXPPAL
			WHERE NOAUT=@NOREFERENCIA	

			-- SELECT @IDTERCERO = COALESCE(IDTERCEROCA, IDCONTRATANTE), @IDSEDE = IDSEDE FROM AUT WHERE NOAUT=@NOREFERENCIA

			PRINT 'CE --' + @IDMEDICO +'= IDMEDICO, '+CONVERT(VARCHAR(20) , @FECHAING ) +'= FECHA, '+ @IDSEDE+ ' = IDSEDE '
		END
		ELSE IF @PROCEDENCIA='CI'
		BEGIN
			SELECT @IDMEDICO = CIT.IDMEDICO, @FECHAING =CIT.FECHA, @IDSEDE = IDSEDE 
			,  @FECHAEGR = CIT.FECHA 
			, @DXING = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')' 
			, @DXEGR = MDX2.DESCRIPCION+ ' (' + MDX2.IDDX +')'
			, @TIPOADM = 'A'
			FROM CIT 
				LEFT JOIN HCA ON (CIT.CONSECUTIVO = HCA.CONSECUTIVOCIT OR CIT.CONSECUTIVOHCA = HCA.CONSECUTIVO )AND CIT.IDAFILIADO = HCA.IDAFILIADO
				LEFT JOIN MDX MDX2 ON MDX2.IDDX= HCA.DX1
			WHERE CIT.CONSECUTIVO=@NOREFERENCIA			

		--	SELECT @IDTERCERO = COALESCE(IDTERCEROCA, IDCONTRATANTE), @IDSEDE = IDSEDE FROM CIT WHERE CONSECUTIVO=@NOREFERENCIA		

			PRINT 'CI --' + @IDMEDICO +'= IDMEDICO, '+ CONVERT(VARCHAR(20) ,@FECHAING ) +'= FECHA, '+ @IDSEDE +' = IDSEDE '
		END
		
		PRINT @FECHAEGR
		
		SELECT 'OK' OK
		BEGIN TRY
			SELECT
			HACTRAND.CNSHACTRAN
			,YODECLARO = 'Yo '+COALESCE(AFI.NOMBREAFI,'')+' identificado(a) con cedula de ciudadanía número. '+COALESCE(AFI.DOCIDAFILIADO,'')+' declaro bajo la gravedad de juramento.'+
			' Que sufrí accidente de tránsito, y que la información contenida en el presente documento es cierta y puede ser verificada por la compañía de seguros. Al contactarme. '+
			'Acepto las consecuencias morales, administrativas y legales que genere la misma.'
			,CERTIFICA = IIF(@PROCEDENCIA='QX','CERTIFICA que atendio en el Servicio de Urgencias al Señor(a)','CERTIFICA que atendio en el Servicio de Consulta Externa al Señor(a)')
			,NOMMEDICO = COALESCE(MED.NOMBRE,'')
			,NOMBREMED = COALESCE(MED.NOMBRE,'')
			,MED_NOREGISTRO = COALESCE(MED.NO_REGISTRO,'')

			,DPR_RAZONSOCIAL = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DESCRIPCION,TER.RAZONSOCIAL),'')
			,DPR_DIRECCION = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.DIRECCION,TER.DIRECCION),'')
			,DPR_NIT = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.NIT,TER.NIT),'')
			,DPR_CIUDAD = COALESCE(DPR_CIU.NOMBRE,'')
			,DPR_DEPARTAMENTO = COALESCE(DPR_DEP.NOMBRE,'')
			,DPR_TELEFONO = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.TELEFONOS,TER.TELEFONOS),'')
			,DPR_EMAIL = COALESCE(IIF(@DATOSPROPIETARIO='SEDE',SED.EMAIL,TER.EMAIL),'')
		
			,EDAD = DATEDIFF(YEAR,AFI.FNACIMIENTO,COALESCE(HACTRAN.FECHAACC,GETDATE()))
			,NOMAFILIADO = COALESCE(AFI.NOMBREAFI,'')+' '+COALESCE(AFI.TIPO_DOC,'')+' '+COALESCE(AFI.DOCIDAFILIADO,'') + ' de '+DOC_CIU.NOMBRE
			,DIRECCION_AFI = COALESCE(AFI.DIRECCION,'')
			,CIUDAD_AFI = COALESCE(CIU.NOMBRE,'')
			,TIPO_DOC = COALESCE(AFI.TIPO_DOC,'')
			,DOCIDAFILIADO = COALESCE(AFI.DOCIDAFILIADO,'')
			,DOC_CIUDAD = COALESCE(DOC_CIU.CIUDAD,'')
			,SEXO = COALESCE(AFI.SEXO,'')
			,DEPARTAMENTO_AFI = COALESCE(DEP.NOMBRE,'')
			,TELEFONO_AFI = COALESCE(AFI.TELEFONORES,'')
			,FECHANACAFI = COALESCE(CONVERT( VARCHAR(10),AFI.FNACIMIENTO,103 ),'')
			,DECLARA = 'EN REPRESENTACION DEL CENTRO ASISTENCIAL EN MENCION DECLARO BAJO LA GRAVEDAD DE JURAMENTO QUE LA INFORMACIÓN DILIGENCIADA EN ESTE DOCUMENTO ES CIERTA Y PUEDE SER VERIFICADA POR LA COMPAÑIA DE SEGUROS Y/O FONSAT, DENTRO DE LOS TREINTA (30) DIAS SIGUIENTES A LA FECHA DE PRESENTACION DE NO SER ASI ACEPTO TODAS LAS CONSECUENCIAS LEGALES QUE PRODUZCA ESTA SITUACIÓN.'
			,DIAGNOSTICO = COALESCE(MDX.IDDX,'')+' '+COALESCE(MDX.DESCRIPCION,'')
			,TA = COALESCE(HACTRAND.TA,'')
			,FC = COALESCE(HACTRAND.FC,'')
			,FR = COALESCE(HACTRAND.FR,'')
			,TEMP1 = COALESCE(HACTRAND.TEMP1,'')
			,ALERTA = IIF (ESTADOCONC='ALERTA','X',' ')
			,OBNUBILADO = IIF (ESTADOCONC='OBNUBILADO','X',' ')
			,ESTUPOROSO = IIF (ESTADOCONC='ESTUPOROSO','X',' ')
			,COMA = IIF (ESTADOCONC='COMA','X',' ')
			,NOMGLASGOW = COALESCE(GLASGOW.DESCRIPCION,'')
			,ESTEMBSI = IIF(HACTRAND.ESTADOEMBRIAGUEZ='SI','X',' ')
			,ESTEMBNO = IIF(HACTRAND.ESTADOEMBRIAGUEZ='NO','X',' ')
			,CABEZA1 = COALESCE(HACTRAND.CABEZA1,'')
			,CUELLO1 = COALESCE(HACTRAND.CUELLO1,'')
			,TORAX1  = COALESCE(HACTRAND.TORAX1,'')
			,ABDOMEN1 = COALESCE(HACTRAND.ABDOMEN1,'')
			,GENITOURINARIO1 = COALESCE(HACTRAND.GENITOURINARIO1,'')
			,PELVIS1	= COALESCE(HACTRAND.PELVIS1,'')
			,DORSO1		= COALESCE(HACTRAND.DORSO1,'')
			,NEUROLOGICO1 = COALESCE(HACTRAND.NEUROLOGICO1,'')
			,DIAGNOSTICO1 = COALESCE(HACTRAND.DIAGNOSTICO1,'')
			,TRATAMIENTO1 = COALESCE(HACTRAND.TRATAMIENTO1,'')
			,SITIOACC = COALESCE(HACTRAN.SITIOACC,'')
			,CONDICIONACC = COALESCE(HACTRAN.CONDICIONACC,'')
			,FECHAACC = COALESCE(CONVERT( VARCHAR(20),HACTRAN.FECHAACC,103 ),'')
			,HORAACC =COALESCE( RIGHT(CONVERT(VarChar(19), HACTRAN.FECHAACC , 0), 7),'') 
			,ACC_MUNICIPIO = COALESCE(ACC_CIU.NOMBRE,'')
			,ACC_DEPARTAMENTO = COALESCE(ACC_DEP.NOMBRE,'')
			,ZONA = COALESCE(HACTRAN.ZONA,'')
			,MARCA = COALESCE(HACTRAN.MARCA,'')
			,PLACA = COALESCE(HACTRAN.PLACA,'')
			,TIPO = COALESCE(HACTRAN.TIPO,'')
			,TIPOPOLIZA = COALESCE(HACTRAN.TIPOPOLIZA,'')
			,NOPOLIZA = COALESCE(HACTRAN.NOPOLIZA,'')
			,FECHAINIPOL = COALESCE(CONVERT( VARCHAR(10),HACTRAN.FECHAINIPOL,103 ),'')
			,FECHAFINPOL = COALESCE(CONVERT( VARCHAR(10),HACTRAN.FECHAFINPOL,103 ),'')
			,NOMBRE_CON = COALESCE(TRIM(HACTRAN.COND_PAPELLIDO + ' '+ HACTRAN.COND_SAPELLIDO) + ' ' +  TRIM( HACTRAN.COND_PNOMBRE+ ' ' +HACTRAN.COND_SNOMBRE) ,'')
			,EDAD_CON = COALESCE(HACTRAN.EDAD,'')
			,SEXO_CON = COALESCE(HACTRAN.SEXO,'')
			,TIPODOC_CON = COALESCE(HACTRAN.TIPODOC,'')
			,NODOCUMENTO_CON = COALESCE(HACTRAN.NODOCUMENTO,'')
			,DE_CON = COALESCE(HACTRAN.DE,'')
			,DIRECCION_CON = COALESCE(HACTRAN.DIRECCION,'')
			,CIUDAD_CON = COALESCE(CON_CIU.NOMBRE,'')
			,TELEFONO_CON = COALESCE(HACTRAN.TELEFONO,'')
			,ASE_NOMBRE = COALESCE(ASE_TER.RAZONSOCIAL,'')
			
			,FECHA_RD = COALESCE(CONVERT( VARCHAR(20),HACTRAN.FECHA_RD,103 ),'')
			,PERREMITIDAA = COALESCE(HACTRAN.PERREMITIDAA,'')
			,F_ACEPTA = COALESCE(CONVERT( VARCHAR(20),HACTRAN.F_ACEPTA,103 ),'')
			,SUCURSAL = COALESCE(HACTRAN.SUCURSAL,'')
			,INFORME = COALESCE(HACTRAN.INFORME,'')
			,FECHAINGRESO = COALESCE(CONVERT( VARCHAR(20), @FECHAING,103 ) ,'')
			,HORAINGRESO = COALESCE( RIGHT(CONVERT(VarChar(19), @FECHAING , 0), 7),'') 
			,FECHAEGRESO = COALESCE(CONVERT( VARCHAR(20),@FECHAEGR,103 ) ,'')
			,DIASESTANCIA =  CONVERT( INT , DATEDIFF(DAY,@FECHAING,@FECHAEGR) )
			,HISTORIANO = COALESCE(@NOREFERENCIA ,'')
			,DXINGRESO = COALESCE(@DXING ,'')
			,DXEGRESO = COALESCE(@DXEGR ,'')
			,TIPOADM = COALESCE(@TIPOADM ,'')
			,FECHA_MUERTE = COALESCE(CONVERT( VARCHAR(20),AFI.FECHAFALLECE,103 ),'')
			,HORA_MUERTE =  COALESCE( RIGHT(CONVERT(VarChar(19), AFI.FECHAFALLECE , 0), 7),'') 
			,MUESTRAIDMEDICO_POL = DBO.FNK_VALORVARIABLE('MUESTRAIDMEDICO_POL')
			,MEDICOACTADEFUNCION = IIF(DBO.FNK_VALORVARIABLE('MUESTRAIDMEDICO_POL')='SI', '', COALESCE(MED.NOMBRE,''))
			,REGISTROMEDICOACTADEFUNCION = IIF(DBO.FNK_VALORVARIABLE('MUESTRAIDMEDICO_POL')='SI', '', COALESCE(MED.NO_REGISTRO,'') )
			,CIU_REGISTROMEDICOACTADEFUNCION = '' -- NO TENEMOS EL DATO
			,ACTADEFUNCION = COALESCE( HADM.ACTADEFUNCION,'')
			,CAUSAMUERTE = CASE COALESCE(AFI.ESTADO ,'') WHEN  'Muerto' THEN @DXEGR WHEN  'Fallecido' THEN @DXEGR ELSE '' END
			,FIRMA = (SELECT DICOM FROM ARCHIVOS WHERE ID = MED.IDFIRMA)
			,FECHAIMPRESION = GETDATE()

			,HACTRAN.COD_IPSREMITE

			,IPS_REMITENTE_DIRECCION = COALESCE(HACTRAN.DIRIPSREMITE,'')
			,IPS_REMITENTE_TELEFONO = COALESCE(HACTRAN.TELIPSREMITE,'')
			,REMITIDADE = COALESCE(HACTRAN.REMITIDADE,'')

			 ,REMITIDODEOTRAIPS = IIF( COALESCE(COD_IPSREMITE,'')= '', 'NO','SI')

			,coalesce ( CHAB.NOMBREENTIDAD	,'')  IPS_REMITENTE
			,coalesce ( TVEHIC.NOMBRE	,'') NTIPOVEHICULO

			FROM HACTRAND
				INNER JOIN HACTRAN ON HACTRAN.CNSHACTRAN=HACTRAND.CNSHACTRAN
				LEFT JOIN AFI ON AFI.IDAFILIADO=HACTRAN.IDAFILIADO
				LEFT JOIN TER ON TER.IDTERCERO=@IPS
				LEFT JOIN TER ASE_TER ON ASE_TER.IDTERCERO=HACTRAN.IDASEGURADORA
				LEFT JOIN SED ON SED.IDSEDE=@IDSEDE
				LEFT JOIN MED ON MED.IDMEDICO=@IDMEDICO
				LEFT JOIN CIU ON CIU.CIUDAD=AFI.CIUDAD
				LEFT JOIN DEP ON CIU.DPTO=DEP.DPTO
				LEFT JOIN MDX ON MDX.IDDX=HACTRAND.IDDX
				LEFT JOIN CIU DOC_CIU ON DOC_CIU.CIUDAD=AFI.CIUDADDOC
				LEFT JOIN CIU ACC_CIU ON ACC_CIU.CIUDAD=HACTRAN.CIUDAD
				LEFT JOIN CIU CON_CIU ON CON_CIU.CIUDAD=HACTRAN.CIUDADCOND
				LEFT JOIN DEP ACC_DEP ON ACC_DEP.DPTO=ACC_CIU.DPTO
				LEFT JOIN CIU DPR_CIU ON DPR_CIU.CIUDAD=IIF(@DATOSPROPIETARIO='SEDE',SED.CIUDAD, TER.CIUDAD)
				LEFT JOIN DEP DPR_DEP ON DPR_CIU.DPTO = DPR_DEP.DPTO
				LEFT JOIN TGEN GLASGOW ON GLASGOW.TABLA = 'GENERAL' AND GLASGOW.CAMPO='TIPOGLASGOW' AND GLASGOW.CODIGO=HACTRAND.TIPOGASGLOW
				LEFT JOIN HADM ON HADM.CNSHACTRAN= HACTRAN.CNSHACTRAN
				LEFT OUTER JOIN IPSHAB CHAB	ON CHAB.CODIGOHABILITACION = HACTRAN.COD_IPSREMITE
				LEFT JOIN ( 
				SELECT 	1 T, 'AUTOMOVIL'  NOMBRE UNION ALL
				SELECT 10 , 'Moto'  UNION ALL
				SELECT 2  , 'Bus'  UNION ALL
				SELECT 3  , 'Buseta'  UNION ALL
				SELECT 4  , 'Camion'  UNION ALL
				SELECT 5  , 'Camioneta'  UNION ALL
				SELECT 6  , 'Campero'  UNION ALL
				SELECT 7  , 'Microbus'  UNION ALL
				SELECT 8  , 'Camion'  UNION ALL
				SELECT 14 , 'Otro'  UNION ALL
				SELECT 17 , 'Otro'  UNION ALL
				SELECT 19 , 'Otro'  UNION ALL
				SELECT 20 , 'Otro'  UNION ALL
				SELECT 21 , 'Otro'  UNION ALL
				SELECT 22 , 'Camion' ) TVEHIC ON HACTRAN.TIPOVEHICULO=TVEHIC.T
			
			WHERE HACTRAND.CNSHACTRAN=@CNSHACTRAN AND HACTRAND.PROCEDENCIA=@PROCEDENCIA AND NOREFERENCIA=@NOREFERENCIA
		END TRY
		BEGIN CATCH
			PRINT 'SALIENDO POR EL CATCH'
			PRINT 'OCURRIO UN ERROR DESCONCIDO AL MOMENTO DE CONSULTAR LOS DATOS, CONSULTE CON EL ADMINISTRADOR DEL SISTEMA' 
			SELECT  @error = CONCAT ( 'Error Numero : ', CONVERT(VARCHAR(100), ERROR_NUMBER() ) , 
							' | Severidad : ' , CONVERT(VARCHAR(100), ERROR_SEVERITY() )  ,
							' | Estado del Error : ' ,  CONVERT(VARCHAR(100),  ERROR_STATE()  ) ,
							' | Procedimiento de Error : ' , CONVERT(VARCHAR(100), ERROR_PROCEDURE() ) ,
							' | Linea : ', CONVERT(VARCHAR(100), ERROR_LINE() ) ,
							' | Mensaje de Error : ',ERROR_MESSAGE() ) 

					PRINT 'NO PUEDO  OBTENER INFORMACION DE LA ADMISION : ' + @NOREFERENCIA   + ' : ' + @@ERROR  + ' :  ' +  @error
					INSERT INTO @TBLERRORES(ERROR) SELECT  'NO PUEDO  OBTENER INFORMACION DE LA ADMISION : ' + @NOREFERENCIA  + ' : ' + @@ERROR  + ' :  ' +  @error
			RETURN
		END CATCH
		PRINT 'SE COMPETO LA CONSULTA '
		RETURN
	END

	IF @METODO = 'VALIDARACCIDENTEMISMODIA'
	BEGIN
		SELECT *
		INTO #TMPVALIDARACCIDENTE
		FROM OPENJSON(@PARAMETROS)
	WITH(
			CNSHACTRAN VARCHAR(20) '$.CNSHACTRAN',
			IDAFILIADO VARCHAR(20) '$.IDAFILIADO',
			FECHAACC DATETIME '$.FECHAACC'
		)

		SELECT 'OK' OK

		IF EXISTS (
			SELECT 1
			FROM HACTRAN
			INNER JOIN #TMPVALIDARACCIDENTE A
				ON HACTRAN.IDAFILIADO = A.IDAFILIADO COLLATE DATABASE_DEFAULT
			WHERE CAST(HACTRAN.FECHAACC AS DATE) = CAST(A.FECHAACC AS DATE)
				AND COALESCE(HACTRAN.CNSHACTRAN,'') <> COALESCE(A.CNSHACTRAN,'')
		)
		BEGIN
			SELECT TOP 1
				CAST(1 AS BIT) EXISTE,
				HACTRAN.CNSHACTRAN,
				HACTRAN.FECHAACC
			FROM HACTRAN
			INNER JOIN #TMPVALIDARACCIDENTE A
				ON HACTRAN.IDAFILIADO = A.IDAFILIADO COLLATE DATABASE_DEFAULT
			WHERE CAST(HACTRAN.FECHAACC AS DATE) = CAST(A.FECHAACC AS DATE)
				AND COALESCE(HACTRAN.CNSHACTRAN,'') <> COALESCE(A.CNSHACTRAN,'')
			ORDER BY HACTRAN.FECHAACC DESC
		END
		ELSE
		BEGIN
			SELECT CAST(0 AS BIT) EXISTE, NULL CNSHACTRAN, NULL FECHAACC
		END

		RETURN
	END
	IF (SELECT COUNT(*) FROM  @TBLERRORES)>0
	BEGIN 
		SELECT 'KO' OK
		SELECT  * FROM  @TBLERRORES
		PRINT 'SALIENDO DEL EN LA LINEA 1258'
		RETURN
	END
END

