CREATE OR ALTER PROCEDURE DBO.SPK_FACTURA_MASI_UNIFICAWEB
@CNSRPDX       VARCHAR(20),
@NIT           VARCHAR(20),
@COMPANIA      VARCHAR(2),
@IDSEDE        VARCHAR(5),
@USUARIO       VARCHAR(12),
@IDTERCERO     VARCHAR(20),
@IDPLAN        VARCHAR(6),
@OBSERVACION   VARCHAR(255),
@NOREFERENCIA  VARCHAR(20) = 'UNIWEB',
@TFECHA        SMALLINT = 0,
@FECHAFAC      DATETIME = NULL
WITH ENCRYPTION
AS 
DECLARE @CNSFTR            VARCHAR(20),   @PRE          VARCHAR(20),   @CONSECFTR         INT,           @CNSRESOL          VARCHAR(50)
DECLARE @NVOCONSEC         VARCHAR(20),   @DATO         VARCHAR(80),   @DATO1             VARCHAR(80),   @DV                INT
DECLARE @DATO3             VARCHAR(20),   @DATO2        VARCHAR(80),   @VRTOTAL           DECIMAL(14,2), @VRSERV            DECIMAL(14,2) 
DECLARE @VRCOPA            DECIMAL(14,2), @VRPACO       DECIMAL(14,2), @OK                INT,           @OK1               INT, @OK2               INT
DECLARE @DESCUENTO         DECIMAL(14,2), @VRDTO        DECIMAL(14,2), @VRABONO           DECIMAL(14,2), @TTEC              VARCHAR(10)
DECLARE @DATOCCOSTO        VARCHAR(80),   @IDTERCEROCA  VARCHAR(20),   @SYS_COMPUTERNAME  VARCHAR(254),  @NODESCUENTACOPAGO SMALLINT
DECLARE @MABONO            SMALLINT,      @PABONO       DECIMAL(18,6), @IDAFILIADO        VARCHAR(20),   @CLASEFACTURA      VARCHAR(3)
DECLARE @CUENTACXC         VARCHAR(16),   @CUENTACXCRAD    VARCHAR(16),    @NUMTER       INT,		   @LIBERADA		  SMALLINT,		 @CANTAFI			INT
DECLARE @BASE_IVA_SER      VARCHAR(20),   @VIVA			DECIMAL(14,2), @PIVA              DECIMAL(14,2), @MIVA				SMALLINT
DECLARE @IDFORMATOFTR      VARCHAR(20)
BEGIN
	SELECT @BASE_IVA_SER = DATO FROM USVGS WHERE IDVARIABLE='BASE_IVA_SERVICIOS'

    SET @SYS_COMPUTERNAME = HOST_NAME()
    SELECT @DATOCCOSTO = DATO FROM USVGS WHERE IDVARIABLE = 'CCOSTOENPRESTACION'

	IF EXISTS(SELECT 1 FROM FTR WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND NOREFERENCIA=@NOREFERENCIA AND ESTADO='L')
	BEGIN
		SELECT @LIBERADA=1, @NVOCONSEC=N_FACTURA, @CNSFTR=CNSFCT FROM FTR WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND NOREFERENCIA=@NOREFERENCIA AND ESTADO='L'
	END

    IF ISNULL(@IDPLAN,'') = ''
    BEGIN
        RAISERROR('NO SE ESCOGIO PLAN DE FACTURACION.',16,1)
        RETURN
    END
   
  
    SELECT @DV = DIASVTO, @TTEC= TIPOTERCONTABLE, @NODESCUENTACOPAGO = NODESCUENTACOPAGO,
            @MABONO = MABONO, @PABONO = PABONO
    FROM   PPT  
    WHERE  IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN
   
    SELECT @CUENTACXC = CUENTA,@CUENTACXCRAD=CUENTARAD FROM TTEC
    WHERE TIPO = @TTEC
   
    IF @DV IS NULL 
        SELECT @DV = 30
    IF @DV = 0
        SELECT @DV = 30
   
    SELECT @DATO3 = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'     
    SELECT @DATO2 = DATO FROM USVGS WHERE IDVARIABLE = 'IDMONEDABASE'
   
    CREATE TABLE #FTRD1(CNSFTR VARCHAR(40), N_CUOTA	INT IDENTITY, FECHA DATETIME,
                DB_CR VARCHAR(2), AREAPRESTACION VARCHAR(20), UBICACION VARCHAR(16),
                VR_TOTAL FLOAT, IMPUTACION VARCHAR(16), CCOSTO VARCHAR (20),
                PREFIJO VARCHAR(6), ANEXO VARCHAR(1024), REFERENCIA VARCHAR(40), 
                IDCIRUGIA VARCHAR(20), CANTIDAD SMALLINT, VALOR DECIMAL(14,2),
                VLR_SERVICI DECIMAL(14,2), VLR_COPAGOS DECIMAL(14,2),
                VLR_PAGCOMP DECIMAL(14,2), IDPROVEEDOR VARCHAR(20),
                NOADMISION VARCHAR(16), NOPRESTACION	VARCHAR(16), NOITEM INT,	
                AREAFUNCONT VARCHAR(20), N_FACTURA VARCHAR(16),
                SUBCCOSTO VARCHAR(4), PCOSTO	DECIMAL(14,2), FECHAPREST DATETIME, PROCEDENCIA VARCHAR(10),
				IDCLASE VARCHAR(10), ITEM SMALLINT, VLRIMPUESTO DECIMAL(14,2), 
				PIVA DECIMAL(14,2), VIVA DECIMAL(14,2), CUENTA_FIMPDV DECIMAL(14, 0),
				IDIMPUESTO VARCHAR(10),IDPLAN VARCHAR(6), IDAFILIADO VARCHAR(20),TCOPAGO VARCHAR(10))
   
    UPDATE AUT SET VALORCOPAGO = 0  
    WHERE  AUT.CNSFACT  = @CNSRPDX
    AND    AUT.MARCAFAC = 1
    AND    VALORCOPAGO IS NULL
   
    UPDATE AUT SET VALORTOTAL = 0  
    WHERE  AUT.CNSFACT    = @CNSRPDX
    AND    AUT.MARCAFAC   = 1
    AND    VALORTOTAL IS NULL

    -- CUENTO ITEMS
    SELECT @OK1 = ISNULL(COUNT(*) ,0)
    FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT       = AUT.IDAUT 
    WHERE  AUT.CNSFACT = @CNSRPDX 
    AND    (AUT.FACTURADA = 0 OR AUT.FACTURADA IS NULL OR AUT.FACTURADA=2) 
    AND    AUT.MARCAFAC = 1 
    AND    AUTD.MARCA=1
    AND    (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL) 
    AND    AUT.IDTERCEROCA=@IDTERCERO
    AND    AUT.IDPLAN=@IDPLAN
    AND    COALESCE(AUT.USUARIONOFACTURABLE,'')=@USUARIO

    SELECT @OK=COUNT(*)
    FROM CIT WHERE CIT.CNSFACT=@CNSRPDX
    AND COALESCE(CIT.MARCAFAC,0)=1
    AND COALESCE(USUARIONOFACTURABLE,'')=@USUARIO
    AND COALESCE(CIT.FACTURABLE,0)=1
    AND COALESCE(CIT.FACTURADA,0)=0
    AND COALESCE(CIT.N_FACTURA,'')=''
    AND CIT.IDTERCEROCA=@IDTERCERO
    AND CIT.IDPLAN=@IDPLAN

	PRINT'CUENTO ITEM MEDICAMENTO'
	SELECT @OK2=COUNT(*)
    FROM HCATDIMOV INNER JOIN CIT ON HCATDIMOV.CONSECUTIVOCIT=CIT.CONSECUTIVO
    WHERE 1=1
	AND COALESCE(HCATDIMOV.CNSFACT,'')=@CNSRPDX
    AND COALESCE (NULLIF(HCATDIMOV.IDTERCEROCA,''),CIT.IDTERCEROCA) = @IDTERCERO --AND CIT.IDTERCEROCA=@IDTERCERO
	AND COALESCE(NULLIF(HCATDIMOV.IDPLAN,''), CIT.IDPLAN) = @IDPLAN -- CIT.IDPLAN=@IDPLAN PRIMERO VALIDA EL IDPLAN DE HCATDIMOV
    AND COALESCE(HCATDIMOV.MARCAFAC,0)=1
    AND COALESCE(HCATDIMOV.USUMARCA,'')=@USUARIO
    AND COALESCE(HCATDIMOV.FACTURADA,0)=0
    AND COALESCE(HCATDIMOV.N_FACTURA,'')=''

    IF (COALESCE(@OK,0)+COALESCE(@OK1,0)+COALESCE(@OK2,0)) <= 0
    BEGIN
        PRINT 'No se encontraron items para facturar'
        RETURN
    END
    ELSE
    BEGIN
        IF EXISTS(SELECT 1 FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>'')
        BEGIN
            SELECT @IDFORMATOFTR=IDFORFTRCE  FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>''
        END
        ELSE
        BEGIN
            SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
        END
        IF  COALESCE(@LIBERADA,0)=0
		BEGIN        
			SET @CNSFTR = SPACE(20)

			EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
			SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0 )
			SET @NVOCONSEC = SPACE(20)
			EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT
            
            IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI'
            BEGIN
                EXEC SPK_PREFIJOFACTURA @COMPANIA, @IDSEDE, @PRE OUTPUT  
                SELECT @CONSECFTR = CONSECUTIVO FROM USCXS WHERE COMPANIA = '01' AND IDSEDE = @IDSEDE AND PREFIJO = @PRE
                SELECT @CNSRESOL  = CNSRESOL FROM FDIAN WHERE IDENTIFICADOR = @IDSEDE AND VENCIDA = 0 AND PROCEDENCIA = 'FTR' AND CNSINICIAL <= @CONSECFTR AND CNSFINAL >= @CONSECFTR
            END
         

            PRINT 'INSERT FTR...'
			INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
							VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
							IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
							TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
							INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
							IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
							MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
							CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD,IDSEDE, RDIAN, CNSRESOL, IDFORMATO)
			SELECT @CNSFTR, @COMPANIA, 'C', @IDTERCERO, @NVOCONSEC, CASE @TFECHA WHEN 1 THEN @FECHAFAC ELSE GETDATE() END, 
		    CASE @TFECHA WHEN 1 THEN @FECHAFAC + @DV ELSE GETDATE() + @DV END,0, NULL, NULL, LEFT(@DATO2,2), NULL, 'P', NULL,
            @IDAFILIADO, @USUARIO, @NOREFERENCIA,'CE', 'M', @OBSERVACION, 'Credito', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0,
            NULL, NULL, @USUARIO,GETDATE(), 0, 0, 	0, @IDPLAN, NULL, 'C', NULL, NULL, NULL, @DATO3, @TTEC, @CUENTACXC,@CUENTACXCRAD,
            @IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''), @IDFORMATOFTR

        END
		ELSE
		BEGIN
			UPDATE FTR SET ESTADO='P',CONTABILIZADA=0, NROCOMPROBANTE=NULL, IDTERCERO=@IDTERCERO, IDPLAN=@IDPLAN, CUENTACXC=@CUENTACXC, TIPOTTEC=@TTEC, IDFORMATO=@IDFORMATOFTR,
            F_FACTURA=CASE @TFECHA WHEN 1 THEN @FECHAFAC ELSE DBO.FNK_GETDATE() END, F_VENCE=CASE @TFECHA WHEN 1 THEN @FECHAFAC + @DV ELSE DBO.FNK_GETDATE() + @DV END
			WHERE N_FACTURA=@NVOCONSEC AND CNSFCT=@CNSFTR AND ESTADO='L'
		END

        IF COALESCE(@OK1,0) >0
        BEGIN 
            PRINT 'Insertando en #FTRD1 AUT'
            INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                            IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                            VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                            NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, PROCEDENCIA,
						    IDIMPUESTO, IDCLASE, ITEM, VLRIMPUESTO, PIVA, VIVA, CUENTA_FIMPDV,IDPLAN,IDAFILIADO,TCOPAGO)
            SELECT @CNSFTR, GETDATE(), 'DB', AUT.IDAREA, NULL, 
                (AUTD.CANTIDAD * AUTD.VALOR) - CASE WHEN @NODESCUENTACOPAGO = 1 
                                                    THEN 0
                                                    ELSE ROUND(((AUTD.CANTIDAD * AUTD.VALOR) * AUT.VALORCOPAGO) / CASE AUT.VALORTOTAL WHEN 0 THEN 1 ELSE AUT.VALORTOTAL END ,0)
                                                END,
                NULL, CASE WHEN @DATOCCOSTO = 'SER:CCOSTO' THEN AUTD.CCOSTO ELSE AUT.CCOSTO END, SER.PREFIJO, 
                SER.DESCSERVICIO, AUTD.IDSERVICIO, NULL, AUTD.CANTIDAD, AUTD.VALOR, (AUTD.CANTIDAD * AUTD.VALOR), 
                CASE WHEN @NODESCUENTACOPAGO = 1 
                THEN 0 
                ELSE ROUND(((AUTD.CANTIDAD * AUTD.VALOR) * AUT.VALORCOPAGO) / CASE AUT.VALORTOTAL WHEN 0 THEN 1 ELSE AUT.VALORTOTAL END,0) 
                END, 
                0, AUT.IDPROVEEDOR, AUT.NOAUT, AUTD.IDAUT, AUTD.NO_ITEM, NULL, 
                @NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO, AUT.FECHA, 'CE',
			        CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END,
                CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
                CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) ELSE NULL END,
                CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.CANTIDAD * AUTD.VALOR) ELSE NULL END ,
                CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) ELSE NULL END,
                CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  CASE WHEN AUTD.VALOR = 0 THEN NULL
														    ELSE 
															    CASE WHEN @BASE_IVA_SER='CONIVA' 
																    THEN  (SELECT (AUTD.CANTIDAD * AUTD.VALOR) -ROUND((AUTD.CANTIDAD * AUTD.VALOR)/((VALOR+100)/100),0) 
																    FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)))
															    ELSE
																        (SELECT ROUND((AUTD.CANTIDAD * AUTD.VALOR)*(VALOR/100),0) 
																        FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) 
															    END
													        END
												        ELSE NULL 
												        END,
                CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)))  
												        ELSE NULL 
			                         		        END,AUTD.IDPLAN,AUT.IDAFILIADO,DBO.FNK_TRAE_TIPOCOPAGO(AUT.NOAUT,'CE')
            FROM   AUT 
                INNER JOIN AUTD ON AUT.IDAUT        = AUTD.IDAUT 
                INNER JOIN SER  ON SER.IDSERVICIO   = AUTD.IDSERVICIO 
                INNER  JOIN TER  ON AUT.IDTERCEROCA = TER.IDTERCERO
            WHERE  AUT.CNSFACT  = @CNSRPDX 
            AND    (AUTD.FACTURADA = 0 OR AUTD.FACTURADA IS NULL) 
            AND    AUT.MARCAFAC = 1 
            AND    AUTD.MARCA=1
            AND    AUT.IDTERCEROCA=@IDTERCERO
            AND    AUT.IDPLAN=@IDPLAN
            AND    COALESCE(FACTURABLE,0)=1 
            AND    COALESCE(AUT.USUARIONOFACTURABLE,'')=@USUARIO
        END

        IF COALESCE(@OK,0)>0
        BEGIN
            PRINT 'Insertando en #FTRD1 CIT'
            INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                            IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                            VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                            NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
                            FECHAPREST, IDPLAN, PROCEDENCIA, IDAFILIADO,TCOPAGO)
            SELECT @CNSFTR, GETDATE(), 'DB', CIT.IDAREA, NULL, (COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL) - COALESCE(CIT.VALORCOPAGO,0), 
                NULL, CIT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, CIT.IDSERVICIO, NULL,
                COALESCE(CIT.CANTIDADC,1) AS CANTIDAD, CIT.VALORTOTAL, COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL , COALESCE(CIT.VALORCOPAGO,0),
                0, CIT.IDMEDICO, CIT.CONSECUTIVO, CIT.CONSECUTIVO, 1, NULL, 
                @NVOCONSEC, CIT.SUBCCOSTO, CIT.VALORTOTALCOS,CIT.FECHA, CIT.IDPLAN, 'CI', CIT.IDAFILIADO,DBO.FNK_TRAE_TIPOCOPAGO(CIT.CONSECUTIVO,'CI')
            FROM   CIT INNER JOIN SER ON SER.IDSERVICIO  = CIT.IDSERVICIO 
                        LEFT JOIN TER ON CIT.IDTERCEROCA = TER.IDTERCERO
            WHERE CIT.CNSFACT=@CNSRPDX
            AND COALESCE(CIT.MARCAFAC,0)=1
            AND COALESCE(USUARIONOFACTURABLE,'')=@USUARIO
            AND COALESCE(CIT.FACTURABLE,0)=1
            AND COALESCE(CIT.FACTURADA,0)=0
            AND COALESCE(CIT.N_FACTURA,'')=''
            AND CIT.IDTERCEROCA=@IDTERCERO
            AND CIT.IDPLAN=@IDPLAN 

            PRINT 'TERMINO INSER DE CIT'
        END
        
        IF COALESCE(@OK2,0)>0
        BEGIN
            PRINT 'Insertando en #FTRD1 ONCO' --cambie aqui idservicio de cit por HCATDIMOV medicamentos en el campo refeencia
            INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                            IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                            VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                            NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
                            FECHAPREST, IDPLAN, PROCEDENCIA, IDAFILIADO,TCOPAGO)
            SELECT @CNSFTR, GETDATE(), 'DB', CIT.IDAREA, NULL, COALESCE(X.VALORTOTAL,1) , 
                NULL, CIT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, HCATDIMOV.IDSERVICIO --CIT.IDSERVICIO
				, NULL, COALESCE(X.CANTIDAD,1) AS CANTIDAD, X.VALOR,  
                X.VALORTOTAL , 0, 0, CIT.IDMEDICO, CIT.CONSECUTIVO, HCATDIMOV.CNSMOV,HCATDIMOV.ID, NULL, 
                @NVOCONSEC, CIT.SUBCCOSTO, CIT.VALORTOTALCOS,CIT.FECHA,  COALESCE(NULLIF(HCATDIMOV.IDPLAN,''), CIT.IDPLAN)IDPLAN --CIT.IDPLAN
				,'ONCO', CIT.IDAFILIADO
                ,DBO.FNK_TRAE_TIPOCOPAGO(CIT.CONSECUTIVO,'CI')
            FROM   HCATDIMOV 
                INNER JOIN  CIT ON HCATDIMOV.CONSECUTIVOCIT=CIT.CONSECUTIVO
                INNER JOIN SER ON SER.IDSERVICIO  = HCATDIMOV.IDSERVICIO 
                INNER JOIN DBO.VWK_CARGOS_HADMAUTCIT X ON HCATDIMOV.CONSECUTIVOCIT=X.NOADMISION AND HCATDIMOV.CNSMOV=X.NOPRESTACION AND HCATDIMOV.ID=X.NOITEM
                LEFT JOIN TER ON CIT.IDTERCEROCA = TER.IDTERCERO
            WHERE HCATDIMOV.CNSFACT=@CNSRPDX
            AND COALESCE(HCATDIMOV.MARCAFAC,0)=1
            AND COALESCE(HCATDIMOV.USUMARCA,'')=@USUARIO
            AND COALESCE(CIT.FACTURABLE,0)=1
            AND COALESCE(HCATDIMOV.FACTURADA,0)=0
            AND COALESCE(HCATDIMOV.N_FACTURA,'')=''
            AND COALESCE (NULLIF(HCATDIMOV.IDTERCEROCA,''),CIT.IDTERCEROCA) = @IDTERCERO --AND CIT.IDTERCEROCA=@IDTERCERO
            AND COALESCE(NULLIF(HCATDIMOV.IDPLAN,''), CIT.IDPLAN) = @IDPLAN -- CIT.IDPLAN=@IDPLAN PRIMERO VALIDA EL IDPLAN DE HCATDIMOV  
        END
    
        PRINT 'TERMINO INSERT #FTRD'
	    UPDATE #FTRD1 SET CANTIDAD = COALESCE(CANTIDAD,0), VALOR = COALESCE(VALOR,0), VLR_SERVICI = COALESCE(VLR_SERVICI,0),
					VR_TOTAL = COALESCE(VR_TOTAL,0), VLR_COPAGOS = COALESCE(VLR_COPAGOS,0), VLR_PAGCOMP = COALESCE(VLR_PAGCOMP,0)
        WHERE 1=1
       
        PRINT  'VOY A INSERTAR FTRD'
        INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                    IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                    VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                    NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, PROCEDENCIA,
				    PIVA, VIVA, CUENTA_FIMPDV, IDIMPUESTO, IDCLASE, ITEM, VLRIMPUESTO,TCOPAGO)
        SELECT @CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                NOPRESTACION, NOITEM, AREAFUNCONT, @NVOCONSEC, SUBCCOSTO, PCOSTO, FECHAPREST, PROCEDENCIA,
				    PIVA, VIVA, CUENTA_FIMPDV, IDIMPUESTO, IDCLASE, ITEM, VLRIMPUESTO,TCOPAGO
        FROM   #FTRD1
         
	    SELECT @VRTOTAL	= SUM(COALESCE(VR_TOTAL,0)), 
		    @VRSERV = SUM(COALESCE(VLR_SERVICI,0)), 
		    @VRPACO = SUM(COALESCE(VLR_PAGCOMP,0)), 
		    @VRCOPA = SUM(COALESCE(VLR_COPAGOS,0)), 
		    @VIVA	= SUM(COALESCE(VIVA,0))
        FROM  FTRD WHERE N_FACTURA = @NVOCONSEC

        UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = @VRCOPA, VALORPCOMP = @VRPACO, VIVA = @VIVA, 
		            VR_TOTAL = @VRSERV - @VRCOPA - @VRPACO - COALESCE(@VRDTO,0) - COALESCE(@VRABONO,0)
        WHERE N_FACTURA = @NVOCONSEC

        SELECT @VIVA=SUM(COALESCE(VIVA,0)) FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  
	    IF @VIVA>0
	    BEGIN
		    SELECT TOP 1 @PIVA=PIVA ,@MIVA=1 FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  AND COALESCE(PIVA,0)<>0
		    UPDATE FTR SET MIVA=@MIVA,PIVA=@PIVA,VIVA=@VIVA WHERE N_FACTURA = @NVOCONSEC
	    END

        EXEC SPK_FAC_IMPDEDUC @NIT, @CNSFTR, @NVOCONSEC, @VRTOTAL

        IF COALESCE(@OK1,0) >0
        BEGIN 
            UPDATE AUTD SET FACTURADA=1, N_FACTURA=@NVOCONSEC,MARCA=0,USUARIOMARCA=NULL
            FROM   AUT INNER JOIN AUTD ON AUT.IDAUT        = AUTD.IDAUT 
                    INNER JOIN SER  ON SER.IDSERVICIO   = AUTD.IDSERVICIO 
                    INNER  JOIN TER  ON AUT.IDTERCEROCA = TER.IDTERCERO
            WHERE  AUT.CNSFACT  = @CNSRPDX 
            AND    (AUTD.FACTURADA = 0 OR AUTD.FACTURADA IS NULL) 
            AND    AUT.MARCAFAC = 1 
            AND    AUTD.MARCA=1
            AND    AUT.IDTERCEROCA=@IDTERCERO
            AND    AUT.IDPLAN=@IDPLAN
            AND    COALESCE(FACTURABLE,0)=1 
            AND    COALESCE(AUT.USUARIONOFACTURABLE,'')=@USUARIO

            UPDATE AUT SET FACTURADA=1, N_FACTURA=@NVOCONSEC, MARCAFAC=0,USUARIONOFACTURABLE=NULL,CNSFACT=@CNSFTR
            FROM   AUT INNER JOIN AUTD ON AUT.IDAUT        = AUTD.IDAUT 
                    INNER JOIN SER  ON SER.IDSERVICIO   = AUTD.IDSERVICIO 
                    INNER  JOIN TER  ON AUT.IDTERCEROCA = TER.IDTERCERO
            WHERE  AUT.CNSFACT  = @CNSRPDX 
            AND    (AUT.FACTURADA = 0 OR AUT.FACTURADA IS NULL) 
            AND    AUT.MARCAFAC = 1 
            AND    AUT.IDTERCEROCA=@IDTERCERO
            AND    AUT.IDPLAN=@IDPLAN
            AND    COALESCE(FACTURABLE,0)=1 
            AND    COALESCE(AUT.USUARIONOFACTURABLE,'')=@USUARIO
        END 
        IF COALESCE(@OK,0)>0
        BEGIN
            UPDATE CIT SET FACTURADA=1,N_FACTURA=@NVOCONSEC, MARCAFAC=0,USUARIONOFACTURABLE=NULL,CNSFACT=@CNSFTR
            FROM   CIT INNER JOIN SER ON SER.IDSERVICIO  = CIT.IDSERVICIO 
                        LEFT JOIN TER ON CIT.IDTERCEROCA = TER.IDTERCERO
            WHERE CIT.CNSFACT=@CNSRPDX
            AND COALESCE(CIT.MARCAFAC,0)=1
            AND COALESCE(USUARIONOFACTURABLE,'')=@USUARIO
            AND COALESCE(CIT.FACTURABLE,0)=1
            AND COALESCE(CIT.FACTURADA,0)=0
            AND COALESCE(CIT.N_FACTURA,'')=''
            AND CIT.IDTERCEROCA=@IDTERCERO
            AND CIT.IDPLAN=@IDPLAN 

        END
   
        IF COALESCE(@OK2,0)>0
        BEGIN
            UPDATE HCATDIMOV SET FACTURADA=1,N_FACTURA=@NVOCONSEC, MARCAFAC=0,USUMARCA=NULL,CNSFACT=@CNSFTR
            FROM   HCATDIMOV INNER JOIN  CIT ON HCATDIMOV.CONSECUTIVOCIT=CIT.CONSECUTIVO
                        INNER JOIN SER ON SER.IDSERVICIO  = HCATDIMOV.IDSERVICIO 
                        LEFT JOIN TER ON CIT.IDTERCEROCA = TER.IDTERCERO
            WHERE HCATDIMOV.CNSFACT=@CNSRPDX
            AND COALESCE(HCATDIMOV.MARCAFAC,0)=1
            AND COALESCE(USUMARCA,'')=@USUARIO
            AND COALESCE(CIT.FACTURABLE,0)=1
            AND COALESCE(HCATDIMOV.FACTURADA,0)=0
            AND COALESCE(HCATDIMOV.N_FACTURA,'')=''
            AND COALESCE (NULLIF(HCATDIMOV.IDTERCEROCA,''),CIT.IDTERCEROCA) = @IDTERCERO --AND CIT.IDTERCEROCA=@IDTERCERO
            AND COALESCE(NULLIF(HCATDIMOV.IDPLAN,''), CIT.IDPLAN) = @IDPLAN -- CIT.IDPLAN=@IDPLAN PRIMERO VALIDA EL IDPLAN DE HCATDIMOV

        END

        SELECT @CANTAFI =COUNT (IDAFILIADO) FROM ( SELECT DISTINCT   IDAFILIADO  FROM #FTRD1) Z 

        IF @CANTAFI=1
        BEGIN
            SELECT TOP 1 @IDAFILIADO=IDAFILIADO FROM #FTRD1
            UPDATE FTR SET IDAFILIADO=@IDAFILIADO  WHERE N_FACTURA=@NVOCONSEC
        END

        DROP TABLE #FTRD1
   

        IF (SELECT DBO.FNK_VALORVARIABLE('CONTABFACCE_AUTOM') ) = 'SI'
        BEGIN
            EXEC SPK_NC_CONTAB_FTR @NVOCONSEC, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''
        END

    END
END

