IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_ADMIN_CXC_CONTAB' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_ADMIN_CXC_CONTAB
END

GO
CREATE PROCEDURE DBO.SPK_ADMIN_CXC_CONTAB
     @CNSCXC              VARCHAR(20),
     @IDTERCERO           VARCHAR(20),
     @N_FACTURA           VARCHAR(20),
     @F_FACTURA           DATETIME,
     @F_VENCE             DATETIME,
     @USUARIO             VARCHAR(12),
     @OBSERVACION         VARCHAR(255),
     @COMPANIA            VARCHAR(20),
     @NROCOMPROBANTE      VARCHAR(20),
     @VALOR               DECIMAL(14,2),     
     @CCOSTO              VARCHAR(20),
     @IDAREA              VARCHAR(20),  
     @TAREA               VARCHAR(10),
     @ITEM                INT,
     @CUENTA              VARCHAR(16)
WITH ENCRYPTION
AS
DECLARE @IDSEDE VARCHAR(5)
DECLARE @DEDUCCIONES DECIMAL(14,2)
BEGIN
 IF @TAREA='INSERT'
 BEGIN
  IF ISNULL(@CUENTA,'')=''
  BEGIN
   SELECT @CUENTA=CUENTACXC FROM FTR WHERE N_FACTURA=@N_FACTURA
   SET @CUENTA=ISNULL(@CUENTA,'')
  END
  SELECT @IDSEDE=IDSEDE FROM FTR WHERE N_FACTURA=@N_FACTURA
  INSERT INTO FCXC (CNSCXC,FECHACXC,IDTERCERO,IDMENSAJERO,F_VENCE,INDRECIBIDO,F_RECIBIDO,QUIENRECIBIO,
                    NOREFERENCIAEXT,USUARIO,COMPANIA,VALORCXC,CERRADA,VALORDEVUELTO,TIENEGLOSAS,
                    TIENEDEVOLUCION,SALDO,DEDUCCIONES,VALORCXCNETO,SALDONETO,CNSANT,ANTIGUA,VLRPAGOS,
                    VLRNOTADB,VLRNOTACR,VLRGLOSAS,VLRGLOSAS_R,VLREXTRA,OBSERVACION,NROCOMPROBANTE,
                    PROCEDENCIA,IDSEDE,ESTADO)
  SELECT 
     CNSCXC            = @CNSCXC,
     FECHACXC          = DBO.FNK_FECHA_SIN_MLS(GETDATE()),
     IDTERCERO         = @IDTERCERO,
     IDMENSAJERO       = @USUARIO,
     F_VENCE           = @F_VENCE,
     INDRECIBIDO       = 1,
     F_RECIBIDO        = DBO.FNK_FECHA_SIN_MLS(GETDATE()),
     QUIENRECIBIO      = @USUARIO,
     NOREFERENCIAEXT   = '',
     USUARIO           = @USUARIO,
     COMPANIA          = @COMPANIA,
     VALORCXC          = @VALOR,
     CERRADA           = 1,
     VALORDEVUELTO     = 0,
     TIENEGLOSAS       = 0,
     TIENEDEVOLUCION   = 0,
     SALDO             = @VALOR,
     DEDUCCIONES       = 0,
     VALORCXCNETO      = @VALOR,
     SALDONETO         = @VALOR,
     CNSANT            = '',
     ANTIGUA           = 0,
     VLRPAGOS          = 0,
     VLRNOTADB         = 0,
     VLRNOTACR         = 0,
     VLRGLOSAS         = 0,
     VLRGLOSAS_R       = 0,
     VLREXTRA          = 0,
     OBSERVACION       = @OBSERVACION,
     NROCOMPROBANTE    = @NROCOMPROBANTE,
     PROCEDENCIA       = 'CARTERA',
     @IDSEDE,'Activa'
     
     IF DBO.FNK_VALORVARIABLE('ANTIPO_IMP_RESTA_FTR')='SI'
     BEGIN
        SELECT @DEDUCCIONES =SUM(VALOR) FROM FTRI WHERE N_FACTURA=@N_FACTURA
     END
     ELSE
     BEGIN
        SELECT @DEDUCCIONES=0
     END

  INSERT INTO FCXCD (CNSCXC,N_FACTURA,USUARIO,COMPANIA,VALORFACTURA,CERRADA,TIENEGLOSAS,TIENEDEVOLUCION,
                     DEDUCCIONES,VALORFACTURANETO,VLRPAGOS,VLRNOTADB,VLRNOTACR,SALDO,SALDONETO,DESCRIPCION,
                     MARCAPAGO,NT_MARCAP,VLRGLOSAS,VLRGLOSAS_R,VLREXTRA,NROCOMPROBANTE,CUENTA)
  SELECT @CNSCXC,@N_FACTURA,@USUARIO,@COMPANIA,@VALOR,1,0,0,@DEDUCCIONES,@VALOR,0,0,0,@VALOR,@VALOR,@OBSERVACION,1,
         1,0,0,0,@NROCOMPROBANTE,@CUENTA

  INSERT INTO FCXCDV (CNSCXC,N_FACTURA,CNSGLO,TIPO,SALDONETO,FECHA,F_VENCE,F_RECIBIDO,SALDOINICIAL,
                      MARCAPAGO)
  SELECT @CNSCXC, @N_FACTURA, NULL, 'F', @VALOR, @F_FACTURA, @F_VENCE, @F_FACTURA, @VALOR, 0
  /* BEGIN_001 CAMBIO  INDCXC = 1 EN CARTERA     JEDM
             PARA QUE NO SALGA EN EL LISTADO DE FACTURAS SIN TRAMITE DE CARTERA */
  UPDATE FTR SET INDCXC = 1 WHERE N_FACTURA = @N_FACTURA AND IDTERCERO = @IDTERCERO
  -- END_001
 END
 ELSE  
 IF @TAREA='CHANGE'
 BEGIN
  UPDATE FCXC SET
     FECHACXC          = DBO.FNK_FECHA_SIN_MLS(GETDATE()),
     IDTERCERO         = @IDTERCERO,
     IDMENSAJERO       = @USUARIO,
     F_VENCE           = @F_VENCE,
     F_RECIBIDO        = DBO.FNK_FECHA_SIN_MLS(GETDATE()),
     QUIENRECIBIO      = @USUARIO,
     USUARIO           = @USUARIO,
     COMPANIA          = @COMPANIA,
     VALORCXC          = @VALOR,
     VALORCXCNETO      = @VALOR,
     VLRPAGOS          = @VALOR,
     OBSERVACION       = @OBSERVACION,
     SALDO             = @VALOR,
     SALDONETO         = @VALOR
  WHERE CNSCXC=@CNSCXC

  UPDATE FCXCD SET
     USUARIO           = @USUARIO,
     VALORFACTURA      = @VALOR,
     VALORFACTURANETO  = @VALOR,
     DESCRIPCION       = @OBSERVACION,
     SALDO             = @VALOR,
     SALDONETO         = @VALOR
  WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA
  
  UPDATE FCXCDV SET  
     SALDONETO    = @VALOR, 
     FECHA        = @F_FACTURA, 
     F_VENCE      = @F_VENCE, 
     F_RECIBIDO   = @F_FACTURA, 
     SALDOINICIAL = @VALOR
  WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA AND ITEM=@ITEM
 END
 ELSE
 IF @TAREA='DELETE'
 BEGIN
    DELETE FCXCDV WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA AND ITEM=@ITEM
    DELETE FCXCD  WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA
    DELETE FCXC   WHERE CNSCXC=@CNSCXC 
 END
END



