IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_FACTURACI_ESCIP' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_FACTURACI_ESCIP
END
GO
CREATE PROCEDURE DBO.SPK_FACTURACI_ESCIP
@CNSRPDX  VARCHAR(20),
@NIT      VARCHAR(20),
@COMPANIA VARCHAR(2),
@IDSEDE   VARCHAR(5),
@USUARIO  VARCHAR(12),
@IDTERCEROCA1 VARCHAR(20),
@IDPLAN VARCHAR(20),
@OBSERVACION VARCHAR(20),
@F_FACTURA    DATETIME 
WITH ENCRYPTION
AS
DECLARE @IDAFILIADO VARCHAR(20)
DECLARE @NOMBREAFI VARCHAR(70)
BEGIN
   PRINT 'VERIFICO FACTURACION POR SEDES'
   IF DBO.FNK_VALORVARIABLE('FACTSEDE')='NO'
   BEGIN
      IF @IDSEDE<>DBO.FNK_VALORVARIABLE('IDSEDEPRINCIPAL')
      BEGIN
         SELECT @IDSEDE=DBO.FNK_VALORVARIABLE('IDSEDEPRINCIPAL')
      END
   END
   DECLARE AUT_CURSOR CURSOR FOR
   SELECT DISTINCT(CIT.IDAFILIADO), AFI.NOMBREAFI
   FROM CIT
   LEFT JOIN TER ON CIT.IDTERCEROCA=TER.IDTERCERO
   INNER JOIN AFI ON AFI.IDAFILIADO=CIT.IDAFILIADO
   WHERE CIT.IDTERCEROCA = @IDTERCEROCA1 AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND CIT.CNSFACT = @CNSRPDX
   AND   COALESCE(FACTURABLE,0)=1 
   AND   COALESCE(CIT.DESCUENTO,0)<CASE WHEN CIT.TIPODTO='P' THEN 100 ELSE CIT.VALORTOTAL END
   AND   (TER.IDTERCERO = (CASE WHEN @IDTERCEROCA1='' THEN TER.IDTERCERO ELSE @IDTERCEROCA1 END) OR
          (TER.IDTERCERO IS NULL AND @IDTERCEROCA1<>''))
   ORDER BY AFI.NOMBREAFI

   OPEN AUT_CURSOR  
   FETCH NEXT FROM AUT_CURSOR  
   INTO @IDAFILIADO, @NOMBREAFI
   WHILE @@FETCH_STATUS = 0  
   BEGIN     
      EXEC SPK_FACTURACI_ESCMA  @CNSRPDX, @NIT, @COMPANIA, @IDSEDE, @USUARIO, @IDTERCEROCA1, @IDPLAN, @OBSERVACION, @IDTERCEROCA1, @F_FACTURA, NULL, NULL, 'CUE', @IDAFILIADO

      FETCH NEXT FROM AUT_CURSOR  
      INTO @IDAFILIADO, @NOMBREAFI
   END
   CLOSE AUT_CURSOR
   DEALLOCATE AUT_CURSOR
END



