IF EXISTS (SELECT name FROM sysobjects 
   WHERE name = 'SPK_DESITEMS_NOTACR' AND type = 'P')
   DROP PROCEDURE SPK_DESITEMS_NOTACR

GO
CREATE PROCEDURE DBO.SPK_DESITEMS_NOTACR 
@CNSFNOT  VARCHAR(20), 
@CLASE    VARCHAR(1), 
@USUARIO  VARCHAR(12)
WITH ENCRYPTION
AS
DECLARE @CONCEPTO      TINYINT
DECLARE @DETGENERADOS  SMALLINT
DECLARE @CERRADA       INT
DECLARE @VR_TOTAL      DECIMAL(14,2)
BEGIN
   SELECT @CONCEPTO = COALESCE(CONCEPTO,0), @DETGENERADOS = DETGENERADOS, @CERRADA = CERRADA
   FROM   FNOT
   WHERE  CNSFNOT = @CNSFNOT
   AND    CLASE   = @CLASE
   IF @CERRADA = 1
   BEGIN
      RETURN
   END
   IF @CONCEPTO = 1 AND @DETGENERADOS = 1
   BEGIN
      
      DELETE FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE      
      UPDATE FNOT SET DETGENERADOS = 0, VR_TOTAL = 0 WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
   END
END


