

GO
CREATE OR ALTER   PROCEDURE DBO.SPK_REVERSAR_MCP 
@NROCOMPROBANTE      VARCHAR(20),
@REFERENCIA_PRO      VARCHAR(20),
@PROCEDENCIA         VARCHAR(20),
@CNSPRO1             VARCHAR(20), 
@CNSPRO2             VARCHAR(20),
@COMPANIA            VARCHAR(2),
@SEDE                VARCHAR(5),
@USUARIO             VARCHAR(12),
@SYS_COMPUTERNAME    VARCHAR(254),
@NROCOMPROBANTEDEST  VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @NVOCONSEC     VARCHAR(20)
DECLARE @NOREFERENCIA  VARCHAR(20)
DECLARE @PREFIJO_USCXS VARCHAR(20)
DECLARE @COM           VARCHAR(2)
DECLARE @FECHACONTABLE DATETIME
DECLARE @ANO           VARCHAR(4)
DECLARE @MES			  VARCHAR(2)
DECLARE @ANO_ANT       VARCHAR(4)
DECLARE @CODCAJA       VARCHAR(4)
DECLARE @CNSFACJ       VARCHAR(20)
DECLARE @MES_ANT		  VARCHAR(2) -- ADD: JREYES REQ:0100001773 20090921
DECLARE @PROCENOTA        VARCHAR(20)
DECLARE @N_FACTURA        VARCHAR(20)
DECLARE @CUENTACR         VARCHAR(20)
DECLARE @NOREFERENCIAFTR VARCHAR(20)
DECLARE @PROCEDECNIAFTR VARCHAR(20)
BEGIN
   
   SELECT @ANO_ANT = ANO, @MES_ANT = MES, @CODCAJA=REFERENCIA2, @CNSFACJ=REFERENCIA1 -- ADD: JREYES REQ:0100001773 20090921 MES 
   FROM   MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE
   SELECT @PROCENOTA=PROCEDENCIA,@N_FACTURA=N_FACTURA FROM FNOT WHERE CNSFNOT=@CNSPRO1
   SELECT @CUENTACR=CTAGLOSADB
   FROM FTR INNER JOIN TTEC ON FTR.TIPOTTEC=TTEC.TIPO
   WHERE FTR.N_FACTURA=@N_FACTURA
   DELETE MCH WHERE NROCOMPROBANTE=@NROCOMPROBANTEDEST AND PROCEDENCIA<>'MANUAL' 

   IF (SELECT CERRADO FROM PRI WHERE ANO=@ANO_ANT AND MES=@MES_ANT AND CERRADO=0 )=0 AND  @PROCEDENCIA IN ('REVCAJAING','REVCAJAEGR')
   BEGIN 
   UPDATE MCP SET ESTADO=0 ,  ANULADO=1 WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   RETURN
   END  
   IF @NROCOMPROBANTEDEST = ''
   BEGIN
      IF @PROCEDENCIA = 'FNOT'
      BEGIN
         SET @PROCEDENCIA = 'REVNOTDBCR'
         SELECT @FECHACONTABLE = F_NOTA FROM FNOT WHERE CNSFNOT = @CNSPRO1 AND CLASE = @CNSPRO2
      END
      ELSE
      BEGIN
         SET @FECHACONTABLE = DBO.FNK_FECHA_SIN_MLS(GETDATE())
      END
      PRINT 'PROCEDENCIA 1 = '+@PROCEDENCIA
      IF @PROCEDENCIA = 'REVNOTDBCR'
         SET @COM = RTRIM(LTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_REVFTR')))
      ELSE
      BEGIN
         IF @PROCEDENCIA = 'REVCAJAING'
         BEGIN
            SET @COM = RTRIM(LTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_REVCAJAIN')))
         END
         ELSE
         BEGIN
            IF @PROCEDENCIA = 'REVCAJAEGR'
            BEGIN
               SET @COM = RTRIM(LTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_REVCAJAEG')))
            END
         END
      END
      IF @PROCEDENCIA='NOTDBCRCXP'
      BEGIN
         SET @COM = RTRIM(LTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOMREVNOTDBCR')))  
         IF COALESCE(@COM,'')=''
         BEGIN    
            SET @COM = RTRIM(LTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_NOTDBCR')))      
         END
      END
      IF ISNULL(@COM,'')='' 
      BEGIN
         SET @COM = RTRIM(LTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT')))   
      END
      IF ISNULL(@COM,'')='' 
      BEGIN
         SET @COM='IX'
      END
      
      SET @ANO = YEAR(@FECHACONTABLE)
      SET @MES = MONTH(@FECHACONTABLE)
      
      SET @PREFIJO_USCXS='@COM'+@COM
      SET @NOREFERENCIA=SPACE(20)
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
      SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
      
      PRINT 'COM: '+@COM
      PRINT 'Nuevo Comprobante: '+@NOREFERENCIA

      SET @NVOCONSEC = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NVOCONSEC OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NVOCONSEC) > 8 THEN 8 ELSE LEN(@NVOCONSEC) END)+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      
      PRINT 'NROCOMPROBANTE: '+@NVOCONSEC
      
      INSERT INTO MCPE(COMPANIA,NROCOMPROBANTE,PROCEDENCIA,NOREFERENCIA,ANO,MES,FECHACONTABLE,TOTALDEBITO,TOTALCREDITO,
                      REFERENCIA1,REFERENCIA2,USUARIO,FECHA,LOTE,OBSERVACION,IDSEDE,ESTADO,COMPROBANTE,IDTERCERO,REFERENCIA3,
                      BANCO,NOCHEQUE,ANULADO,RPT_COMPROBANTE,VALOR_CHEQUE,FECHARADICACION)
      SELECT COMPANIA,@NVOCONSEC,@PROCEDENCIA, @NOREFERENCIA,@ANO,@MES,@FECHACONTABLE,TOTALDEBITO,TOTALCREDITO,
             @REFERENCIA_PRO,REFERENCIA2,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),LOTE, LEFT('REVERSION: '+OBSERVACION,512),
             IDSEDE,ESTADO,@COM,IDTERCERO,@NROCOMPROBANTE,BANCO,NOCHEQUE,ANULADO,RPT_COMPROBANTE,VALOR_CHEQUE,FECHARADICACION
      FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   END
   ELSE
   BEGIN
      SELECT @NVOCONSEC     = NROCOMPROBANTE,
             @NOREFERENCIA  = NOREFERENCIA, 
             @COM           = COMPROBANTE,
             @ANO           = ANO,
             @MES           = MES,
             @FECHACONTABLE = FECHACONTABLE
      FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTEDEST
   END
   DELETE  MCHE	WHERE NROCOMPROBANTE= @NVOCONSEC
   PRINT 'Insertando en MCH...'
   IF @PROCEDENCIA = 'REVNOTDBCR'
   BEGIN
      -- Reversión de una Factura de Venta de Años Anteriores  
	  -- SE REALIZA COMPROBANTE PARA ANULACION DE FACTURAS DE AÑOS ANTERIORES 

         INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA,      TIPO,      CUENTA,       IDTERCERO, CCOSTO,      DETALLE,      VALOR, 
                         REFERENCIA1,    REFERENCIA2,   ITEMREF,   USUARIO,      FECHA,     PREFIJO,     IDAREA,    
                         CLASECONT,      ESTADO,        PROCESO,   REFERENCIA3,  CNSPAGO,   GENERA,      F_FACTURAREF, 
                         F_VENCE,        VALOR_PORCIMP, BASE_IMP,  CLASE_GENERA, N_FACTURA, PROCEDENCIA,  
                         REFERENCIA_PRO, CONCILIADO,    CNSFCXCXP, CODUNG,       CODPRG,    ERROR )
         SELECT @NVOCONSEC, MCH.COMPANIA,CASE WHEN MCH.TIPO='DB'  THEN 'CR' ELSE 'DB' END,
                CASE WHEN @PROCENOTA='AUDITORIA' AND MCH.TIPO='DB' THEN @CUENTACR 			 
			 	     WHEN DBO.FNK_VALORVARIABLE ('IDCON_REVDOC_AANTING')<>'' AND @ANO>@ANO_ANT AND MCH.TIPO='CR'  THEN DBO.FNK_VALORVARIABLE ('IDCON_REVDOC_AANTING')
			    ELSE CASE COALESCE(CUE.MCUEREV,0) WHEN 0 THEN MCH.CUENTA  ELSE COALESCE(MCH.CTAREVERSION,CUE.CUENTAREV,MCH.CUENTA) END END,
                IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1,REFERENCIA2, ITEMREF,
                @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO, IDAREA, CLASECONT,1, 'REVERSION', REFERENCIA3, CNSPAGO, GENERA, F_FACTURAREF, F_VENCE,
                VALOR_PORCIMP, BASE_IMP, CLASE_GENERA, N_FACTURA, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG,
                CODPRG,ERROR
         FROM   MCH INNER JOIN CUE ON MCH.CUENTA=CUE.CUENTA
         WHERE  NROCOMPROBANTE = @NROCOMPROBANTE
      
   END
   ELSE
   BEGIN 
      INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA,      TIPO,      CUENTA,       IDTERCERO, CCOSTO,      DETALLE,      VALOR, 
                      REFERENCIA1,    REFERENCIA2,   ITEMREF,   USUARIO,      FECHA,     PREFIJO,     IDAREA,    
                      CLASECONT,      ESTADO,        PROCESO,   REFERENCIA3,  CNSPAGO,   GENERA,      F_FACTURAREF, 
                      F_VENCE,        VALOR_PORCIMP, BASE_IMP,  CLASE_GENERA, N_FACTURA, PROCEDENCIA,  
                      REFERENCIA_PRO, CONCILIADO,    CNSFCXCXP, CODUNG,       CODPRG,    ERROR )
      SELECT @NVOCONSEC, COMPANIA,CASE WHEN TIPO='DB' THEN 'CR' ELSE 'DB' END,
             CASE WHEN @PROCENOTA='AUDITORIA' AND TIPO='DB' THEN @CUENTACR ELSE   CUENTA END,
             IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1,REFERENCIA2, ITEMREF,
             @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO, IDAREA, CLASECONT,1, 'REVERSION', REFERENCIA3, CNSPAGO, GENERA, F_FACTURAREF, F_VENCE,
             VALOR_PORCIMP, BASE_IMP, CLASE_GENERA, N_FACTURA, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG,
             CODPRG,ERROR
      FROM   MCH 
      WHERE  NROCOMPROBANTE = @NROCOMPROBANTE
   END
   
   IF @NROCOMPROBANTEDEST=''
   BEGIN
      IF @PROCEDENCIA = 'REVNOTDBCR'
      BEGIN
         PRINT 'Actualizando Nota: '+@CNSPRO1+'  Clase: '+@CNSPRO2
         UPDATE FNOT SET NROCOMPROBANTE=@NVOCONSEC, MARCACONT=0, CONTABILIZADA=1 WHERE CNSFNOT = @CNSPRO1 AND CLASE = @CNSPRO2
         PRINT 'VALIDO EL COMPROBANTE UNIDO'
         --SELECT @PROCEDECNIAFTR=PROCEDENCIA,@NOREFERENCIAFTR=NOREFERENCIA FROM FTR WHERE N_FACTURA=@N_FACTURA
         --IF DBO.FNK_VALORVARIABLE('CONTAB_GASTOVEN_UNI')='SI' AND @PROCEDECNIAFTR='INVENTARIO'
         --BEGIN
         --   EXEC SPK_NC_CONTAB_INV @NOREFERENCIAFTR,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NVOCONSEC
         --END
      END
   END
  
   IF @PROCEDENCIA IN ('REVCAJAING','REVCAJAEGR')
   BEGIN
    UPDATE FCJ SET NROCOMPROBANTE=@NVOCONSEC WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ
   END 
   PRINT 'Revision del Comprobante...'
   EXEC SPK_NC_REVISAMCPE @NVOCONSEC, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME
END






