IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_NC_CONTAB_ANULA_CONCI' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_NC_CONTAB_ANULA_CONCI 
END
GO
CREATE PROCEDURE DBO.SPK_NC_CONTAB_ANULA_CONCI 
@CNSCONCI         VARCHAR(20), 
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA         VARCHAR(2), 
@SEDE             VARCHAR(5),
@NROCOMPROBANTE   VARCHAR(20),
@ITEM             INT
WITH ENCRYPTION
AS
DECLARE @COM              VARCHAR(6)
DECLARE @NOREFERENCIA     VARCHAR(20)
DECLARE @ANO              VARCHAR(4)
DECLARE @MES              INT
DECLARE @IDMODELOCONT     VARCHAR(2)
DECLARE @TIPOTERCONTABLE  VARCHAR(10) 
DECLARE @PREFIJO_USCXS    VARCHAR(10)
DECLARE @FECHATRA         DATETIME
DECLARE @SI               INT
BEGIN   ---SELECT * FROM FCONCID 
   PRINT '@ITEM==='+STR(@ITEM)
   SELECT   @ANO            = YEAR(GETDATE()),
            @MES            = MONTH(GETDATE())
   FROM FCONCI
   WHERE IDFCONCI=@CNSCONCI

   SELECT @SI=COUNT(*) FROM FCONCID WHERE IDFCONCI=@CNSCONCI AND VLRRECUPERAR>0

   IF @SI<=0
   BEGIN
      RAISERROR('No Existe valor a recuperar no hay necesidad de comprobante', 16, 1)
      RETURN      
   END
    
   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)
   BEGIN
      RAISERROR('Periodo Contable NO Existe', 16, 1)
      RETURN
   END
   
   IF (SELECT CERRADO FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES) = 1
   BEGIN
      RAISERROR('Periodo Contable Cerrado', 16, 1)
      RETURN
   END   
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
   IF ISNULL(@NROCOMPROBANTE,'') = '' 
   BEGIN
      SET @NROCOMPROBANTE = SPACE(20) 
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT 
      PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'')
      SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') 
      
      
      IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
      BEGIN
         SELECT @COM = RTRIM(LTRIM(COMMS.COMPROBANTE)) FROM COMMS WHERE IDSEDE = @SEDE AND COMMS.CLASE = 'CONCILIACIONES' 
         IF @COM IS NULL
            SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_CONCI')))
      END
      ELSE
      BEGIN
         SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_CONCI')))
      END
      
      SET @PREFIJO_USCXS='@COM'+@COM
      SET @NOREFERENCIA=SPACE(20)
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
      SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
      PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
      
      PRINT 'Comprobante Contable (MCPE)'
      INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                      TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                      COMPROBANTE, IDTERCERO)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'CONCI', @NOREFERENCIA, @ANO, @MES, 
             CAST(STR(DAY(FECHACONC))+'/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME), 0, 0, IDFCONCI, '', @USUARIO, 
             DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, OBSERVACION, @SEDE, 0, @COM, IDTERCERO
      FROM   FCONCI
      WHERE  IDFCONCI=@CNSCONCI
   END
   IF (SELECT COUNT(*) FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)>0
   BEGIN
      INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
      SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
      FROM   MCP
      WHERE NROCOMPROBANTE=@NROCOMPROBANTE
      --se borran de mcp, mch
      DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
      DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE   
   END
   ELSE
   BEGIN
      DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   END
   INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
          	        REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                   CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', D.CUENTACG,A.IDTERCERO,'' AS CCOSTO, 
          'ANULA CONCILIACION  DE GLOSA FACTURA: '+B.N_FACTURA, B.VLRRECUPERAR, A.IDFCONCI, B.CNSGLO, NULL, 
          @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
          'CONC_GLOSAS', 'Movimiento','S', B.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(A.FECHADIG),
          DBO.FNK_FECHA_SIN_HORA(A.FECHACONC),'CONCI',@CNSCONCI, '', ''
   FROM   FCONCI A INNER JOIN FCONCID B ON A.IDFCONCI=B.IDFCONCI
                   INNER JOIN FTR C ON B.N_FACTURA=C.N_FACTURA
                   INNER JOIN TTEC D ON C.TIPOTTEC=D.TIPO
   WHERE  A.IDFCONCI=@CNSCONCI 
          AND B.VLRRECUPERAR>0
          AND COALESCE(C.CASTIGADA,0)=0
          AND ITEM_FCONCID=CASE WHEN COALESCE(@ITEM,0)>0 THEN @ITEM  ELSE ITEM_FCONCID END

   INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
          	        REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                   CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', CASE WHEN B.TIPO='F' THEN D.CUENTARAD
                                                 WHEN B.TIPO='G' THEN D.CUENTALG
                                                 WHEN B.TIPO='R' THEN D.CUENTALG
                                                 ELSE 'TIPO NO DEF.'
                                                  END,
           A.IDTERCERO,'' AS CCOSTO, 
          'ANULA CONCILIACION  DE GLOSA FACTURA: '+B.N_FACTURA, B.VLRRECUPERAR, A.IDFCONCI, B.CNSGLO, NULL, 
          @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
          'CONC_GLOSAS', 'Movimiento','S', B.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(A.FECHADIG),
          DBO.FNK_FECHA_SIN_HORA(A.FECHACONC),'CONCI',@CNSCONCI, '', ''
   FROM   FCONCI A INNER JOIN FCONCID B ON A.IDFCONCI=B.IDFCONCI
                   INNER JOIN FTR C ON B.N_FACTURA=C.N_FACTURA
                   INNER JOIN TTEC D ON C.TIPOTTEC=D.TIPO
   WHERE  A.IDFCONCI=@CNSCONCI 
          AND B.VLRRECUPERAR>0
          AND ITEM_FCONCID=CASE WHEN COALESCE(@ITEM,0)>0 THEN @ITEM  ELSE ITEM_FCONCID END
          AND COALESCE(C.CASTIGADA,0)=0
   
   PRINT 'Poniendo Estado de CONTABILIZADA en La Tabla FCONCI' 
   
   UPDATE FCONCID SET NROCOMPROBANTE_A=@NROCOMPROBANTE WHERE IDFCONCI=@CNSCONCI AND ITEM_FCONCID=@ITEM

  
   EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME
   EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''
END

