CREATE OR ALTER PROCEDURE DBO.SPK_NOTASCXC
@CNSFNOT          VARCHAR(20),
@CLASE            VARCHAR(1),  
@CNSRPDX          VARCHAR(20),
@SEDE             VARCHAR(5),
@COMPANIA         VARCHAR(2),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)
WITH ENCRYPTION
AS              
DECLARE @CNSCXC             VARCHAR(20)  
DECLARE @CERRADA            SMALLINT  
DECLARE @ESTADO             VARCHAR(1)
DECLARE @VLRNOTADB          DECIMAL(14,2)
DECLARE @VLRNOTACR          DECIMAL(14,2)
DECLARE @N_FACTURA          VARCHAR(16)
DECLARE @VR_TOTALNOTA       DECIMAL(14,2)
DECLARE @PROCEDENCIA        VARCHAR(10)
DECLARE @LIBERAHADM         SMALLINT
DECLARE @VLRTOTAL           DECIMAL(14,2)
DECLARE @NOADMISION         VARCHAR(16)
DECLARE @IDTERCERO          VARCHAR(20)
DECLARE @ORIGENFTR          VARCHAR(10)
DECLARE @NROCOMPROBANTE     VARCHAR(20)
DECLARE @NROCOMPROBANTEDEST VARCHAR(20)
DECLARE @CONTABILIZADA      INT
DECLARE @TIPOFAC            VARCHAR(1) 
DECLARE @INDCARTERA         SMALLINT
DECLARE @INDCXC             SMALLINT
DECLARE @ESTADO_FTR         VARCHAR(1)
DECLARE @ANOACTU            VARCHAR(4)
DECLARE @MESACTU            VARCHAR(2)
DECLARE @ANOFTR	          VARCHAR(4)
DECLARE @MESFTR	          VARCHAR(2)
---- 
DECLARE @N_CUOTA            INT
DECLARE @IDSERVICIO         VARCHAR(20)
DECLARE @CANTIDAD           DECIMAL(14,2)
DECLARE @VR_UNITARIO        DECIMAL(14,2)
DECLARE @AUX                INT
DECLARE @VAUX               DECIMAL(14,2)
DECLARE @IDPROVEEDOR        VARCHAR(20)
DECLARE @N_PRESUP           VARCHAR(16)
DECLARE @IDTERCERO_P        VARCHAR(20)
DECLARE @ITEM               INT
DECLARE @TIPOANULACION      VARCHAR(20)
DECLARE @NOPRESTACION       VARCHAR(16)
DECLARE @NOITEM             SMALLINT
DECLARE @VALOR_FXPD         DECIMAL(14,2)
DECLARE @FCOPA              SMALLINT
DECLARE @OBSERVACION        VARCHAR(MAX)
DECLARE @SIIF BIT=0
DECLARE @MEC_FACT			VARCHAR(10)
DECLARE @PROCEDENCIAFTR    VARCHAR(10)
DECLARE @PROCEDENCIAFTRD    VARCHAR(10)
DECLARE @NOREFERENCIA   VARCHAR(20)
DECLARE @ESTADOCAL			VARCHAR(50) ,@ESTADO_ANTERIOR VARCHAR(50),@EVENTO VARCHAR(50)			,@DETALLES NVARCHAR(MAX),@IDMAD	INT,@CONSECUTIVO VARCHAR(20),@IDAUT VARCHAR(20),@NOITEMCAL INT,@IDSERVICIOCAL VARCHAR(20)
DECLARE @NOREINTEGRO BIT
BEGIN 
    PRINT 'INGRESE A SPK_NOTASCXC'
    SELECT @CERRADA = CERRADA , @ESTADO = ESTADO, @CNSCXC = CNSCXC, @N_FACTURA = N_FACTURA,
            @VR_TOTALNOTA = VR_TOTAL, @PROCEDENCIA = PROCEDENCIA, @LIBERAHADM = COALESCE(LIBERAHADM,0),
            @IDTERCERO = IDTERCERO, @NROCOMPROBANTEDEST = COALESCE(NROCOMPROBANTE,''),@NOREINTEGRO=NOREINGRESO
    FROM   FNOT     
    WHERE  CNSFNOT = @CNSFNOT AND CLASE = @CLASE

	SELECT @PROCEDENCIAFTR=PROCEDENCIA,@NOADMISION = NOREFERENCIA FROM FTR WHERE N_FACTURA = @N_FACTURA

    SELECT @SIIF=COALESCE(SIIF,0) FROM TER WHERE IDTERCERO=@IDTERCERO
	IF @SIIF=1
	BEGIN
		SELECT @OBSERVACION='
        #$'+COALESCE(SIIFCODIGOPCI,'')+';'+COALESCE(SIIFCONTRATO,'')+';'+COALESCE(SIIFCORREOSUPER,'')+'#$' 
        FROM TER 
        WHERE IDTERCERO=@IDTERCERO
        UPDATE FNOT SET OBSERVACION=CONCAT(OBSERVACION,COALESCE(@OBSERVACION,'')) WHERE CNSFNOT=@CNSFNOT
	END

    IF @NROCOMPROBANTEDEST IS NULL
        SET @NROCOMPROBANTEDEST = ''    
      
    IF @PROCEDENCIA = 'NOTAS' OR ( @PROCEDENCIA = 'AUDITORIA' AND @LIBERAHADM = 1 ) OR ( @PROCEDENCIA = 'FACTURA' AND @LIBERAHADM = 1 )
    BEGIN
      SELECT @ORIGENFTR = PROCEDENCIA, @INDCARTERA = INDCARTERA, @INDCXC = INDCXC, @ESTADO_FTR = ESTADO,
        @FCOPA = CASE WHEN TIPOFIN='N' THEN 1 ELSE 0 END, @MEC_FACT = MEC_FACT,@NOREFERENCIA = NOREFERENCIA
      FROM   FTR 
      WHERE  N_FACTURA = @N_FACTURA
      
      IF @PROCEDENCIA = 'NOTAS'
      BEGIN     
         IF @ESTADO_FTR = 'A'
         BEGIN
            RAISERROR('la Factura %s No se puede Aplicar por encontrase Anulada.',16,1,@N_FACTURA)
            RETURN
         END
      
         IF @INDCXC = 1 AND @LIBERAHADM = 1
         BEGIN
            RAISERROR('la Factura %s se encuentra asignada a una Cuenta de Cobro.',16,1,@N_FACTURA)
            RETURN
         END
      END
            
      IF  @LIBERAHADM = 1
      BEGIN
         SELECT @VLRTOTAL = COUNT(*) FROM FCXCD
         WHERE  N_FACTURA = @N_FACTURA
         
         SELECT @NOADMISION = NOREFERENCIA, @TIPOFAC = TIPOFAC FROM FTR WHERE N_FACTURA = @N_FACTURA
         
         IF @ORIGENFTR = 'SALUD'
         BEGIN
            IF @TIPOFAC = 'I'
            BEGIN
               PRINT 'AQUI'
               
               UPDATE HADM SET FACTURADA = 0, N_FACTURA = '' WHERE  NOADMISION = @NOADMISION
               
               IF COALESCE(@FCOPA,0)<>1                  
                   UPDATE HPRED SET FACTURADA=0, N_FACTURA = '' FROM HPRE
                   WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION
                   AND    HPRE.NOADMISION   = @NOADMISION              
                   AND    HPRED.N_FACTURA   = @N_FACTURA       -- JEDM:11.MAY.2011 15:37
               ELSE
                   UPDATE HPRED SET N_FACTURAH = '' FROM HPRE
                   WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION
                   AND    HPRE.NOADMISION   = @NOADMISION              
                   AND    HPRED.N_FACTURAH  = @N_FACTURA

               UPDATE HADMF SET ESTADO = 'N' WHERE NOADMISION = @NOADMISION AND N_FACTURA = @N_FACTURA -- JEDM:11.MAY.2011 15:37
               UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

               --JEDM:11.MAY.2011 15:37 
               --SE CREA EL EVENTO PARA ESTA ADMISION 
               INSERT INTO HEVEN (NOADMISION, EVENTO, USUARIO, SYS_COMPUTERNAME, CONSECUTIVOGEN, 
                                  REFERENCIA1, REFERENCIA2, FECHA)
               SELECT @NOADMISION, LEFT(' NOTA CREDITO LIBERA ORIGEN: '+@PROCEDENCIA,40), 
                      @USUARIO, LEFT(HOST_NAME(),254), @CNSFNOT, '', '', GETDATE()    
               
            END            
            ELSE
            BEGIN
               IF @TIPOFAC = 'M'
               BEGIN
                  UPDATE HADM  SET FACTURADA = 0, N_FACTURA = '' 
                  FROM   FTRD WHERE FTRD.N_FACTURA  = @N_FACTURA 
                              AND   FTRD.NOADMISION = HADM.NOADMISION
                  
                  IF COALESCE(@FCOPA,0)<>1  
                     UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA                 
                  ELSE
                     UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA                 

                  --DELETE HADMF    --12/07/2013 ASI ESTABA
                  UPDATE HADMF SET ESTADO = 'N'  --12/07/2013 ASI QUEDA
                  FROM   FTRD 
                  WHERE  FTRD.N_FACTURA  = @N_FACTURA 
                  AND    FTRD.NOADMISION = HADMF.NOADMISION 
                  AND    HADMF.N_FACTURA = FTRD.N_FACTURA
               END
            END   
         END
         IF @ORIGENFTR = 'CE'
         BEGIN
            IF @TIPOFAC = 'I'
            BEGIN
			      -- JQUIROGA 20090416 con AARROYO
		     UPDATE AUT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
		     WHERE  AUT.N_FACTURA =  @N_FACTURA AND FACTURADA = 1
			
               UPDATE AUTD SET FACTURADA = 0, N_FACTURA = NULL
               WHERE  AUTD.N_FACTURA = @N_FACTURA AND FACTURADA = 1 

            END
            ELSE
               IF @TIPOFAC = 'M'
               BEGIN
				  -- JQUIROGA 20090416 con AARROYO
 			      UPDATE AUT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
                  FROM FTRD WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.N_FACTURA=AUT.N_FACTURA AND AUT.FACTURADA=1
			
                  UPDATE AUTD SET FACTURADA = 0, N_FACTURA = NULL
                  FROM FTRD WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.N_FACTURA=AUTD.N_FACTURA AND AUTD.FACTURADA=1
               END          
         END 
         IF @ORIGENFTR = 'CI'
         BEGIN
            IF @TIPOFAC = 'I'
            BEGIN
               UPDATE CIT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
               WHERE  N_FACTURA =  @N_FACTURA AND FACTURADA = 1
            END 
            ELSE
               IF @TIPOFAC = 'M'
               BEGIN
                  UPDATE CIT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
                  FROM FTRD WHERE FTRD.N_FACTURA = @N_FACTURA  AND FTRD.N_FACTURA=CIT.N_FACTURA AND CIT.FACTURADA = 1
               END
         END 
         IF @ORIGENFTR = 'ARS'
         BEGIN
            --PRINT 'Libera la cuota del plan de pago en ARS'
            UPDATE CNTPC SET ENFACTURA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA            
         END
		 IF @ORIGENFTR IN ('MAD','CMV')
         BEGIN
			PRINT 'MAD/CMV - LIBERO PRESTACIONES'
			IF @MEC_FACT = 'CPM'
			BEGIN
				UPDATE AUT SET FACTURADA_TERCERO = 0, MARCAFAC = 0, N_FACTURA_TERCERO = NULL
				WHERE  AUT.N_FACTURA_TERCERO =  @N_FACTURA AND FACTURADA_TERCERO = 1
			
				UPDATE AUTD SET FACTURADA_TERCERO = 0, N_FACTURA_TERCERO = NULL
				WHERE  AUTD.N_FACTURA_TERCERO = @N_FACTURA AND FACTURADA_TERCERO = 1 

				UPDATE CIT SET FACTURADA_TERCERO = 0, MARCAFAC = 0, N_FACTURA_TERCERO = NULL
				WHERE  N_FACTURA_TERCERO =  @N_FACTURA AND FACTURADA_TERCERO = 1

				SET @ESTADOCAL = 'APROBADO'

				DECLARE ENCUENTROS_CURSOR CURSOR FOR
				SELECT DISTINCT NOADMISION FROM FTRD
				WHERE N_FACTURA =  @N_FACTURA AND PROCEDENCIA = 'CI' AND PAQUETE = 1
				UNION
				SELECT ID FROM MAD
				WHERE @ORIGENFTR = 'CMV' AND N_FACTURA = @N_FACTURA
			
				OPEN ENCUENTROS_CURSOR
				FETCH NEXT FROM ENCUENTROS_CURSOR    
				INTO @IDMAD
				WHILE @@FETCH_STATUS = 0    
				BEGIN
					PRINT 'INGRESE A EL CURSOR PARA [RECORRER LOS ENCUENTROS].................'
					PRINT '@IDMAD >'  + COALESCE(CAST(@IDMAD AS VARCHAR),' SIN @IDMAD')

					DECLARE MAD_CURSOR CURSOR FOR
					SELECT IDMAD, CONSECUTIVO, IDAUT, NO_ITEM, IDSERVICIO
					FROM VWK_PROGRAMA_MAD
					WHERE IDMAD = @IDMAD AND @ORIGENFTR = 'MAD'
					UNION ALL
					SELECT IDMAD, CONSECUTIVO, IDAUT, NO_ITEM, IDSERVICIO
					FROM VWK_PROGRAMA_CMV
					WHERE IDMAD = @IDMAD AND @ORIGENFTR = 'CMV'
			 
					OPEN MAD_CURSOR
					FETCH NEXT FROM MAD_CURSOR    
					INTO @IDMAD, @CONSECUTIVO, @IDAUT, @NOITEMCAL, @IDSERVICIOCAL
					WHILE @@FETCH_STATUS = 0    
					BEGIN

						SELECT @ESTADO_ANTERIOR = COALESCE(ESTADO, 'PENDIENTE') 
						FROM MADSERCAL 
						WHERE IDMAD = @IDMAD AND CONSECUTIVO = @CONSECUTIVO 
							AND IDAUT = @IDAUT AND NOITEM = @NOITEMCAL AND IDSERVICIO = @IDSERVICIOCAL

						UPDATE MADSERCAL SET ESTADO = COALESCE(@ESTADOCAL,'APROBADO'), USUARIO_CALIFICA = @USUARIO, FECHA_CALIFICA = GETDATE(), IDCAUSAL = NULL, OBSERVACIONES = NULL
						WHERE IDMAD = @IDMAD 
						AND CONSECUTIVO = @CONSECUTIVO 
						AND IDAUT = @IDAUT 
						AND NOITEM = @NOITEMCAL 
						AND IDSERVICIO = @IDSERVICIOCAL
					
						SET @EVENTO = 'RESET_A_PENDIENTE'
						SET @DETALLES = 'Calificación regresada a estado pendiente por anulacion de la factura.'

						INSERT INTO MADSERCAL_LOG (IDMAD, CONSECUTIVO, IDAUT, NOITEM, IDSERVICIO, EVENTO, ESTADO_ANTERIOR, ESTADO_NUEVO,
							IDCAUSAL, OBSERVACIONES, USUARIO, DETALLES
						) 
						SELECT @IDMAD, @CONSECUTIVO, @IDAUT, @NOITEMCAL, @IDSERVICIOCAL, @EVENTO, COALESCE(@ESTADO_ANTERIOR, 'PENDIENTE'), COALESCE(@ESTADOCAL,'APROBADO'),
							NULL, NULL, @USUARIO, @DETALLES
			 
			 			FETCH NEXT FROM MAD_CURSOR    
			 			INTO @IDMAD, @CONSECUTIVO, @IDAUT, @NOITEMCAL, @IDSERVICIOCAL
					END
					CLOSE MAD_CURSOR
					DEALLOCATE MAD_CURSOR
			 
					PRINT 'TERMINE EL CURSOR DEL MAD'
			
					FETCH NEXT FROM ENCUENTROS_CURSOR    
					INTO @IDMAD
				END
				CLOSE ENCUENTROS_CURSOR
				DEALLOCATE ENCUENTROS_CURSOR

				UPDATE MAD SET FACTURADA = 0, MARCAFAC = 0, USUARIO_MARCAFAC = NULL, N_FACTURA = NULL
				WHERE  N_FACTURA =  @N_FACTURA
			
				PRINT 'TERMINE EL CURSOR DE ENCUENTROS'
			END
			ELSE IF @MEC_FACT = 'MER'
			BEGIN -- MER: detalles tipo PPS, encuentro en MAD.N_FACTURA
				PRINT 'MER - LIBERO PRESTACIONES'
				IF EXISTS (SELECT 1 FROM FTRD WHERE N_FACTURA = @N_FACTURA AND PROCEDENCIA = 'CITCI')
					UPDATE CITCI SET FACTURADA_TERCERO = 0, N_FACTURA_TERCERO = NULL
					WHERE N_FACTURA_TERCERO = @N_FACTURA

				IF EXISTS (SELECT 1 FROM FTRD WHERE N_FACTURA = @N_FACTURA AND PROCEDENCIA = 'CI')
					UPDATE CIT SET FACTURADA_TERCERO = 0, MARCAFAC = 0, N_FACTURA_TERCERO = NULL
					WHERE N_FACTURA_TERCERO = @N_FACTURA

				IF EXISTS (SELECT 1 FROM FTRD WHERE N_FACTURA = @N_FACTURA AND PROCEDENCIA = 'CE')
					UPDATE AUTD SET FACTURADA_TERCERO = 0, N_FACTURA_TERCERO = NULL
					WHERE N_FACTURA_TERCERO = @N_FACTURA

				UPDATE AUT SET FACTURADA_TERCERO = 0, MARCAFAC = 0, N_FACTURA_TERCERO = NULL
				WHERE AUT.N_FACTURA_TERCERO = @N_FACTURA AND FACTURADA_TERCERO = 1

				SET @ESTADOCAL = 'APROBADO'

				DECLARE ENCUENTROS_MER_CURSOR CURSOR FOR
				SELECT ID FROM MAD WHERE N_FACTURA = @N_FACTURA

				OPEN ENCUENTROS_MER_CURSOR
				FETCH NEXT FROM ENCUENTROS_MER_CURSOR INTO @IDMAD
				WHILE @@FETCH_STATUS = 0
				BEGIN
					DECLARE MAD_MER_CURSOR CURSOR FOR
					SELECT IDMAD, CONSECUTIVO, IDAUT, NO_ITEM, IDSERVICIO
					FROM VWK_PROGRAMA_CMV
					WHERE IDMAD = @IDMAD

					OPEN MAD_MER_CURSOR
					FETCH NEXT FROM MAD_MER_CURSOR
					INTO @IDMAD, @CONSECUTIVO, @IDAUT, @NOITEMCAL, @IDSERVICIOCAL
					WHILE @@FETCH_STATUS = 0
					BEGIN
						SELECT @ESTADO_ANTERIOR = COALESCE(ESTADO, 'PENDIENTE')
						FROM MADSERCAL
						WHERE IDMAD = @IDMAD AND CONSECUTIVO = @CONSECUTIVO
							AND IDAUT = @IDAUT AND NOITEM = @NOITEMCAL AND IDSERVICIO = @IDSERVICIOCAL

						UPDATE MADSERCAL SET ESTADO = COALESCE(@ESTADOCAL,'APROBADO'), USUARIO_CALIFICA = @USUARIO, FECHA_CALIFICA = GETDATE(), IDCAUSAL = NULL, OBSERVACIONES = NULL
						WHERE IDMAD = @IDMAD
						AND CONSECUTIVO = @CONSECUTIVO
						AND IDAUT = @IDAUT
						AND NOITEM = @NOITEMCAL
						AND IDSERVICIO = @IDSERVICIOCAL

						SET @EVENTO = 'RESET_A_PENDIENTE'
						SET @DETALLES = 'Calificacion regresada por liberacion de factura MER.'

						INSERT INTO MADSERCAL_LOG (IDMAD, CONSECUTIVO, IDAUT, NOITEM, IDSERVICIO, EVENTO, ESTADO_ANTERIOR, ESTADO_NUEVO,
							IDCAUSAL, OBSERVACIONES, USUARIO, DETALLES)
						SELECT @IDMAD, @CONSECUTIVO, @IDAUT, @NOITEMCAL, @IDSERVICIOCAL, @EVENTO, COALESCE(@ESTADO_ANTERIOR, 'PENDIENTE'), COALESCE(@ESTADOCAL,'APROBADO'),
							NULL, NULL, @USUARIO, @DETALLES

						FETCH NEXT FROM MAD_MER_CURSOR
						INTO @IDMAD, @CONSECUTIVO, @IDAUT, @NOITEMCAL, @IDSERVICIOCAL
					END
					CLOSE MAD_MER_CURSOR
					DEALLOCATE MAD_MER_CURSOR

					FETCH NEXT FROM ENCUENTROS_MER_CURSOR INTO @IDMAD
				END
				CLOSE ENCUENTROS_MER_CURSOR
				DEALLOCATE ENCUENTROS_MER_CURSOR

				UPDATE MAD SET FACTURADA = 0, MARCAFAC = 0, USUARIO_MARCAFAC = NULL, N_FACTURA = NULL
				WHERE N_FACTURA = @N_FACTURA

				PRINT 'TERMINE LIBERACION MER'
			END
			ELSE
			BEGIN -- PPS
				-- Liberar todas las fuentes presentes en la factura (consulta + labs pueden coexistir)
				IF EXISTS (SELECT 1 FROM FTRD WHERE N_FACTURA = @N_FACTURA AND PROCEDENCIA = 'CITCI')
					UPDATE CITCI SET FACTURADA_TERCERO = 0, N_FACTURA_TERCERO = NULL
					WHERE N_FACTURA_TERCERO = @N_FACTURA

				IF EXISTS (SELECT 1 FROM FTRD WHERE N_FACTURA = @N_FACTURA AND PROCEDENCIA = 'CI')
					UPDATE CIT SET FACTURADA_TERCERO = 0, MARCAFAC = 0, N_FACTURA_TERCERO = NULL
					WHERE N_FACTURA_TERCERO = @N_FACTURA

				IF EXISTS (SELECT 1 FROM FTRD WHERE N_FACTURA = @N_FACTURA AND PROCEDENCIA = 'CE')
					UPDATE AUTD SET FACTURADA_TERCERO = 0, N_FACTURA_TERCERO = NULL
					WHERE N_FACTURA_TERCERO = @N_FACTURA

				UPDATE MAD SET FACTURADA = 0, MARCAFAC = 0, USUARIO_MARCAFAC = NULL, N_FACTURA_PPS = NULL
				WHERE  N_FACTURA_PPS =  @N_FACTURA

				DECLARE MAD_CURSOR CURSOR FOR
				SELECT IDMAD, CONSECUTIVO, IDAUT, NO_ITEM, IDSERVICIO
				FROM VWK_PROGRAMA_MAD
				WHERE IDMAD = @NOREFERENCIA AND @ORIGENFTR = 'MAD'
				UNION ALL
				SELECT IDMAD, CONSECUTIVO, IDAUT, NO_ITEM, IDSERVICIO
				FROM VWK_PROGRAMA_CMV
				WHERE IDMAD = @NOREFERENCIA AND @ORIGENFTR = 'CMV'
			 
				OPEN MAD_CURSOR
				FETCH NEXT FROM MAD_CURSOR    
				INTO @IDMAD, @CONSECUTIVO, @IDAUT, @NOITEMCAL, @IDSERVICIOCAL
				WHILE @@FETCH_STATUS = 0    
				BEGIN

					SELECT @ESTADO_ANTERIOR = COALESCE(ESTADO, 'PENDIENTE') 
					FROM MADSERCAL 
					WHERE IDMAD = @IDMAD AND CONSECUTIVO = @CONSECUTIVO 
						AND IDAUT = @IDAUT AND NOITEM = @NOITEMCAL AND IDSERVICIO = @IDSERVICIOCAL

					UPDATE MADSERCAL SET ESTADO = COALESCE(@ESTADOCAL,'APROBADO'), USUARIO_CALIFICA = @USUARIO, FECHA_CALIFICA = GETDATE(), IDCAUSAL = NULL, OBSERVACIONES = NULL
					WHERE IDMAD = @IDMAD 
					AND CONSECUTIVO = @CONSECUTIVO 
					AND IDAUT = @IDAUT 
					AND NOITEM = @NOITEMCAL 
					AND IDSERVICIO = @IDSERVICIOCAL
					
					SET @EVENTO = 'RESET_A_PENDIENTE'
					SET @DETALLES = 'Calificación regresada por liberacion de la factura.'

					INSERT INTO MADSERCAL_LOG (IDMAD, CONSECUTIVO, IDAUT, NOITEM, IDSERVICIO, EVENTO, ESTADO_ANTERIOR, ESTADO_NUEVO,
						IDCAUSAL, OBSERVACIONES, USUARIO, DETALLES
					) 
					SELECT @IDMAD, @CONSECUTIVO, @IDAUT, @NOITEMCAL, @IDSERVICIOCAL, @EVENTO, COALESCE(@ESTADO_ANTERIOR, 'PENDIENTE'), COALESCE(@ESTADOCAL,'APROBADO'),
						NULL, NULL, @USUARIO, @DETALLES
			 
			 		FETCH NEXT FROM MAD_CURSOR    
			 		INTO @IDMAD, @CONSECUTIVO, @IDAUT, @NOITEMCAL, @IDSERVICIOCAL
				END
				CLOSE MAD_CURSOR
				DEALLOCATE MAD_CURSOR
			 
				PRINT 'TERMINE EL CURSOR DEL MAD'
			END         
         END
		 IF @ORIGENFTR = 'HPREP'
         BEGIN
			PRINT 'PDH PRESUPUESTO - LIBERO PRESTACIONES'
			UPDATE HPREP SET FACTURADA = 0, NFACTURA = NULL, IDKPAGE = NULL
			WHERE  HPREP.NFACTURA =  @N_FACTURA AND FACTURADA = 1
         END
      END
      
   END
   
   -- SE LLEVAN TOTALES DE NOTAS EN CADA ITEM DE FACTURA
   IF @CLASE = 'D'
   BEGIN
      BEGIN TRAN
      UPDATE FTRD SET VLRNOTADB = VLRNOTADB + FNOTD.VR_TOTAL FROM FNOTD
      WHERE  FTRD.N_FACTURA = @N_FACTURA
      AND    FTRD.N_CUOTA   = FNOTD.N_CUOTA
      AND    FNOTD.CNSFNOT  = @CNSFNOT
      AND    FNOTD.CLASE    = @CLASE
      COMMIT TRAN
   END
   ELSE
   BEGIN
      --BEGIN TRAN
      PRINT 'VAMOS A HACER UPDATE FTRD'
      UPDATE FTRD SET VLRNOTACR = VLRNOTACR + FNOTD.VR_TOTAL FROM FNOTD
      WHERE  FTRD.N_FACTURA = @N_FACTURA
      AND    FTRD.N_CUOTA   = FNOTD.N_CUOTA
      AND    FNOTD.CNSFNOT  = @CNSFNOT
      AND    FNOTD.CLASE    = @CLASE
      
      -- COMMIT
      -- BEGIN_JEDM_001 21.SEP.2009 EN VENEZUELA SE COPIA PARA COLOMBIA
      -- HONORARIOS MEDICOS
      IF (@PROCEDENCIA = 'NOTAS' AND @ORIGENFTR = 'SALUD') OR (@PROCEDENCIA = 'AUDITORIA') OR (@PROCEDENCIA = 'FACTURA')
      BEGIN
         DECLARE D_CURSOR CURSOR FOR
         SELECT FNOTD.N_CUOTA, FNOTD.IDSERVICIO, FNOTD.CANTIDAD, FNOTD.VR_UNITARIO 
         FROM   FNOTD INNER JOIN FNOT ON FNOTD.CNSFNOT = FNOT.CNSFNOT
                                     AND FNOTD.CLASE   = FNOT.CLASE
         WHERE  FNOT.CNSFNOT = @CNSFNOT 
         AND    FNOT.CLASE    = @CLASE
         AND    TIPO = 'S' -- AND LEFT(FNOT.CNSCXC,2) <> 'SI'   
         OPEN D_CURSOR
         FETCH NEXT FROM D_CURSOR  
         INTO @N_CUOTA, @IDSERVICIO, @CANTIDAD, @VR_UNITARIO
         WHILE @@FETCH_STATUS = 0  
         BEGIN                      
            SELECT @IDPROVEEDOR = COALESCE(IDPROVEEDOR,'') , @NOPRESTACION = NOPRESTACION,
                   @NOITEM      = NOITEM
            FROM   FTRD WHERE N_FACTURA = @N_FACTURA  AND N_CUOTA = @N_CUOTA 
            
            IF @IDPROVEEDOR <> ''
            BEGIN
               PRINT 'VALOR UNITARIO DESPUES DE FNOTD= ' + CAST(@VR_UNITARIO AS VARCHAR(30)) 
               SELECT @AUX = 1
               
               SELECT @VR_UNITARIO = @VR_UNITARIO * @CANTIDAD
               PRINT 'VALOR UNITARIO DESPUES DE FNOTD2= ' + CAST(@VR_UNITARIO AS VARCHAR(30)) 
               DECLARE F_CURSOR CURSOR FOR
               SELECT N_PRESUP, IDTERCERO, ITEM, VALOR
               FROM   FXPD
               WHERE  N_FACTURA = @N_FACTURA AND IDSERVICIO = @IDSERVICIO AND IDTERCERO = @IDPROVEEDOR 
               AND    NOPRESTACION = @NOPRESTACION 
               AND    NOITEM       = @NOITEM
               
               OPEN F_CURSOR
               FETCH NEXT FROM F_CURSOR
               INTO  @N_PRESUP, @IDTERCERO_P, @ITEM, @VALOR_FXPD
               WHILE @@FETCH_STATUS = 0
               BEGIN
                  PRINT '@VALOR_FXPD= ' +CAST(@VALOR_FXPD AS VARCHAR(30)) + ' @VR_UNITARIO = ' + CAST(@VR_UNITARIO AS VARCHAR(30)) 
                  IF @VALOR_FXPD >= @VR_UNITARIO
                  BEGIN
                     PRINT ' >= '
                     UPDATE FXPD SET VALOR = VALOR - @VR_UNITARIO WHERE N_PRESUP = @N_PRESUP AND IDTERCERO = @IDTERCERO_P AND ITEM = @ITEM      
                     UPDATE FXPD SET VR_TOTAL = VALOR * CANTIDAD WHERE N_PRESUP = @N_PRESUP AND IDTERCERO = @IDTERCERO_P AND ITEM = @ITEM            
                     BREAK
                  END
                  ELSE
                  BEGIN
                     PRINT ' < '
                     UPDATE FXPD SET VALOR = VALOR - VALOR 
                     WHERE  N_PRESUP  = @N_PRESUP 
                     AND    IDTERCERO = @IDTERCERO_P 
                     AND    ITEM      = @ITEM
                     
                     SELECT @VR_UNITARIO = @VR_UNITARIO - @VALOR_FXPD
                     
                  END   
                  
                  UPDATE FXPD SET VR_TOTAL = VALOR * CANTIDAD WHERE N_PRESUP = @N_PRESUP AND IDTERCERO = @IDTERCERO_P AND ITEM = @ITEM 
                  
                  SELECT @AUX = @AUX + 1  
                   
                  --IF @AUX > @CANTIDAD
                  --BEGIN  
                  --   BREAK
                  --END         
                  
                  SELECT @VAUX = SUM(VALOR) FROM FXPD WHERE N_PRESUP = @N_PRESUP AND IDTERCERO = @IDTERCERO_P
                  UPDATE FXP SET VR_TOTAL = @VAUX WHERE N_PRESUP = @N_PRESUP AND IDTERCERO = @IDTERCERO_P
                  
                  FETCH NEXT FROM F_CURSOR
                  INTO  @N_PRESUP, @IDTERCERO_P, @ITEM, @VALOR_FXPD
               END
               CLOSE F_CURSOR
               DEALLOCATE F_CURSOR
            END   
            FETCH NEXT FROM D_CURSOR  
            INTO @N_CUOTA, @IDSERVICIO, @CANTIDAD, @VR_UNITARIO
         END   
         CLOSE D_CURSOR
         DEALLOCATE D_CURSOR         
      END
      ELSE
      BEGIN
         PRINT 'NO ES PROCEDENCIA NOTAS'
      END
      --
   END
   UPDATE FNOT SET CERRADA = 1
   WHERE  CNSFNOT   = @CNSFNOT  
   AND    CLASE     = @CLASE
  
   PRINT '@PROCEDENCIAFTR='+@PROCEDENCIAFTR
   IF @PROCEDENCIAFTR ='INVENTARIO' AND DBO.FNK_VALORVARIABLE('CONTAB_GASTOVEN_UNI')='SI' AND COALESCE(@NOREINTEGRO,0)<>1
   BEGIN
      PRINT 'Voy a reintegra el inventario...'
      EXEC SPK_REINTGRA_VENTA_INV @N_FACTURA,@CNSFNOT,@COMPANIA,@SEDE,@USUARIO,@SYS_COMPUTERNAME
   END
   PRINT 'Contabilización Automática...'
      IF @LIBERAHADM = 1
      BEGIN
         Print 'Libera HADM' 
         IF @PROCEDENCIA = 'FACTURA' -- VIENE DE UNA ANULACION DE UNA FACTURA QUE ESTA CONTABILIZADA EN UN PERIODO CERRADO
         BEGIN
            UPDATE FTR SET ESTADO='P', TIPOANULACION='NC', CONTABILIZADA=1 WHERE N_FACTURA=@N_FACTURA
            SELECT @NROCOMPROBANTE = NROCOMPROBANTE FROM FTR WHERE N_FACTURA = @N_FACTURA
            EXEC SPK_REVERSAR_MCP @NROCOMPROBANTE, @N_FACTURA, 'FNOT', @CNSFNOT, @CLASE, 
			        @COMPANIA, @SEDE, @USUARIO, @SYS_COMPUTERNAME, ''
         END
         ELSE
         BEGIN
            -- JQUIROGA 20090416 con AARROYO
            SELECT @NROCOMPROBANTE = NROCOMPROBANTE, @CONTABILIZADA = CONTABILIZADA FROM FTR WHERE N_FACTURA = @N_FACTURA
            IF @CONTABILIZADA=0 OR @CONTABILIZADA IS NULL
            BEGIN
               EXEC SPK_CONTAB_FTR @N_FACTURA, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE, ''
               SELECT @NROCOMPROBANTE = NROCOMPROBANTE, @CONTABILIZADA = CONTABILIZADA FROM FTR WHERE N_FACTURA = @N_FACTURA
            END
	           -- ***************************************************************************
		      -- JQUIROGA 20081217 con AARROYO
		      SELECT @ANOFTR = YEAR(F_FACTURA), @MESFTR = MONTH(F_FACTURA) FROM FTR WHERE N_FACTURA = @N_FACTURA
		      SET @ANOACTU = YEAR(GETDATE())
		      SET @MESACTU = MONTH(GETDATE())
         
		      IF @ANOFTR = @ANOACTU AND @MESFTR = @MESACTU 
		      BEGIN
			      UPDATE FTR SET ESTADO='A', TIPOANULACION='NC', CONTABILIZADA=1 WHERE N_FACTURA=@N_FACTURA
		      END
            ELSE
		      BEGIN
			      UPDATE FTR SET ESTADO='P', TIPOANULACION='NC', CONTABILIZADA=1 WHERE N_FACTURA=@N_FACTURA
		      END

            PRINT 'VOY A HACER REVERSION CON ESTOS PARAMETROS: @NROCOMPROBANTE = '+@NROCOMPROBANTE+ ' // @N_FACTURA = '+@N_FACTURA+ ' // @CNSFNOT = '+@CNSFNOT+
                  ' // @CLASE='+@CLASE+' // @NROCOMPROBANTEDEST = '+@NROCOMPROBANTEDEST
               
		      EXEC SPK_REVERSAR_MCP @NROCOMPROBANTE, @N_FACTURA, 'FNOT', @CNSFNOT, @CLASE, 
			        @COMPANIA, @SEDE, @USUARIO, @SYS_COMPUTERNAME, @NROCOMPROBANTEDEST

            IF @PROCEDENCIAFTR ='INVENTARIO' AND DBO.FNK_VALORVARIABLE('CONTAB_GASTOVEN_UNI')='SI' AND COALESCE(@NOREINTEGRO,0)<>1
            BEGIN
               PRINT 'Voy a reintegra el inventario...'
               DECLARE @IDTIPOMOV VARCHAR(20)
               DECLARE @NROCOMPRO VARCHAR(20)
               SELECT @NROCOMPRO=NROCOMPROBANTE FROM FNOT WHERE CNSFNOT=@CNSFNOT
               SELECT @IDTIPOMOV=DBO.FNK_VALORVARIABLE('IDTIPOMOVDEV_CLIENTE')
               UPDATE IMOV SET CONTABILIZADA=1,NROCOMPROBANTE=@NROCOMPRO WHERE NODOCUMENTO=@CNSFNOT AND IDTIPOMOV=@IDTIPOMOV AND ESTADO=1
            END

         END
      END
      ELSE
      BEGIN		
         EXEC SPK_NC_CONTAB_FNOT @CNSFNOT, @CLASE, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @SEDE, @NROCOMPROBANTEDEST
      END
   --END

   IF DBO.FNK_VALORVARIABLE('FNOT_ENVIO_DIAN_AUTO')='SI'
   BEGIN
		IF (SELECT COALESCE(CONTABILIZADA,0) FROM FNOT WHERE CNSFNOT=@CNSFNOT)<>0
		BEGIN
			IF (SELECT COALESCE(SI,0) FROM FTR WHERE N_FACTURA=@N_FACTURA)=1
			BEGIN
				UPDATE FNOT SET NOTA_SIN_FACTURA=1, FACTE=1 WHERE CNSFNOT=@CNSFNOT
			END
			ELSE 
			BEGIN
				IF	EXISTS(SELECT 1 FROM FTRE WHERE FTRN_FACTURA=@N_FACTURA) 
				BEGIN
					UPDATE FNOT SET FACTE=1 WHERE CNSFNOT=@CNSFNOT
				END
			END
		END
   END


   IF @ORIGENFTR <> 'ARS'
   BEGIN
     PRINT 'VOY A DBO.SPK_RELIQUIDA_FTR  ...................................'
     EXEC SPK_RELIQUIDA_FTR @CNSCXC, @N_FACTURA  
   END
   IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
   BEGIN
      PRINT 'ENVIO NOTA A LA SUNAT'
        IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='MIFACT'
        BEGIN 
           EXEC SPK_GENERA_JSON_PERU_NOTADBCR @CNSFNOT,@N_FACTURA
        END
        ELSE
        BEGIN
           IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP'
           BEGIN
				IF @PROCEDENCIAFTR NOT IN ('MAD', 'SALUD', 'CMV')
					EXEC SPK_JSON_FTR_PERU_INTERFAX_FNOT @CNSFNOT,@N_FACTURA
           END
           ELSE
           BEGIN
             EXEC SPK_GENERA_XML_PERU_NOTADBCR @CNSFNOT,@N_FACTURA
           END
        END
   END
END

