IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_REVISAR_COMPROBANTE' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_REVISAR_COMPROBANTE
END

GO
CREATE PROCEDURE DBO.SPK_REVISAR_COMPROBANTE 
@COMPANIA         VARCHAR(2),
@NROCOMPROBANTE   VARCHAR(20) 
WITH ENCRYPTION
AS
DECLARE @IDAFILIADO VARCHAR(20),
	     @IDCATEGORIA VARCHAR(10)
BEGIN
   IF EXISTS(SELECT * FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND COMPANIA=@COMPANIA AND COALESCE(ANULADO,0)=1)
   BEGIN 
	   UPDATE MCP SET ESTADO=0 WHERE NROCOMPROBANTE=@NROCOMPROBANTE
	   UPDATE MCH SET ESTADO=0 WHERE NROCOMPROBANTE=@NROCOMPROBANTE
	   RETURN
   END

   SET @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
   DECLARE CUR_MCH CURSOR FOR
   SELECT MCH.IDTERCERO
   FROM   MCH INNER JOIN AFI ON MCH.IDTERCERO = AFI.IDAFILIADO 
              LEFT JOIN TER ON MCH.IDTERCERO = TER.IDTERCERO
   WHERE  MCH.COMPANIA = @COMPANIA 
   AND    MCH.NROCOMPROBANTE = @NROCOMPROBANTE 
   AND    TER.IDTERCERO IS NULL

   OPEN CUR_MCH
   FETCH NEXT FROM CUR_MCH
   INTO @IDAFILIADO

   WHILE @@FETCH_STATUS = 0
   BEGIN
      PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
      EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
      FETCH NEXT FROM CUR_MCH
      INTO @IDAFILIADO
   END
   CLOSE CUR_MCH
   DEALLOCATE CUR_MCH

    
   UPDATE MCH SET 
   ESTADO = CASE WHEN CUE.CUENTA IS NULL THEN '0' 
                 ELSE
                     CASE WHEN CUE.TIPO <> 'Detalle' THEN '0' 
                          ELSE
                               CASE WHEN MCH.VALOR=0 THEN '0' 
                                    ELSE
                                        CASE WHEN MCH.VALOR<0 THEN '0' 
                                             ELSE -- AGREGADO POR R.JAY PARA VALIDAR VALORES MENORES CERO
                                                  CASE WHEN TER.IDTERCERO IS NULL AND MCH.IDTERCERO <> '' THEN '0' 
                                                       ELSE '1' 
                                                  END
                                        END
                               END
                     END
            END, 
   ERROR  = CASE WHEN CUE.CUENTA IS NULL THEN 'La Cuenta NO Existe.' ELSE
             CASE WHEN CUE.TIPO<>'Detalle' THEN 'La Cuenta NO es de Detalle.' ELSE
              CASE WHEN MCH.VALOR=0 THEN 'El valor del Registro es cero (0).' ELSE
               CASE WHEN MCH.VALOR<0 THEN 'El valor del Registro es menor que cero.' ELSE -- AGREGADO POR R.JAY PARA VALIDAR VALORES MENORES CERO
                  CASE WHEN TER.IDTERCERO IS NULL AND MCH.IDTERCERO<>'' THEN 'El Tercero NO Existe.' END
               END
              END
             END  
            END
   FROM   MCH LEFT JOIN CUE ON MCH.CUENTA    = CUE.CUENTA 
                           AND CUE.COMPANIA  = @COMPANIA 
              LEFT JOIN TER ON MCH.IDTERCERO = TER.IDTERCERO
   WHERE  MCH.COMPANIA       = @COMPANIA 
   AND    MCH.NROCOMPROBANTE = @NROCOMPROBANTE 
   IF EXISTS(SELECT * FROM MCH WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND ESTADO=0)
   BEGIN
      UPDATE MCH SET DETALLE = LEFT(
      CAST('ERROR       :' AS CHAR(14))+ISNULL(ERROR,'Errores de Parametrización')+CHAR(13)+CHAR(10)+
      CAST('PROCEDENCIA :' AS CHAR(14))+ISNULL(PROCEDENCIA,'?')+CHAR(13)+CHAR(10)+  
      CAST('PROCESO     :' AS CHAR(14))+ISNULL(PROCESO,'?')+CHAR(13)+CHAR(10)+
      CAST('CCOSTO      :' AS CHAR(14))+ISNULL(CCOSTO,'?')+CHAR(13)+CHAR(10)+
      CAST('IDAREA      :' AS CHAR(14))+ISNULL(IDAREA,'?')+CHAR(13)+CHAR(10)+
      CAST('PREFIJO     :' AS CHAR(14))+ISNULL(PREFIJO,'?')+CHAR(13)+CHAR(10)+
      CAST('REFERENCIA1 :' AS CHAR(14))+ISNULL(REFERENCIA1,'?')+CHAR(13)+CHAR(10)+
      CAST('REFERENCIA2 :' AS CHAR(14))+ISNULL(REFERENCIA2,'?')+CHAR(13)+CHAR(10)+
      CAST('REFERENCIA3 :' AS CHAR(14))+ISNULL(REFERENCIA3,'?')+CHAR(13)+CHAR(10)+
      CAST('DETALLE     :' AS CHAR(14))+ISNULL(DETALLE,'?'),512)
      FROM MCH
      WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE = @NROCOMPROBANTE AND ESTADO = '0' --AND LEFT(@NROCOMPROBANTE,2)= 'IX'
   END
   IF (SELECT COUNT(*) FROM MCH WHERE COMPANIA = @COMPANIA AND NROCOMPROBANTE = @NROCOMPROBANTE AND ESTADO='0')=0
   BEGIN
      UPDATE MCP SET ESTADO = '1' WHERE COMPANIA = @COMPANIA AND NROCOMPROBANTE = @NROCOMPROBANTE
   END
END

