CREATE OR ALTER PROCEDURE DBO.SPK_CARGA_MASIVA_FAC_CXC_02  
@CNSFPAG      VARCHAR(20),  
@CNSRPDX      VARCHAR(20),  
@USUARIO      VARCHAR(12),  
@COMPANIA     VARCHAR(2),   
@PROPIETARIO  VARCHAR(20),
@TRAEIMPUESTO SMALLINT,
@CNSFTIMP     VARCHAR(20), 
@FACTOR       DECIMAL(14,5),
@DESFIN       DECIMAL(14,5),
@DF_SERV      INT
WITH ENCRYPTION
AS  
DECLARE @ITEM        INT  
DECLARE @HOY         DATETIME  
DECLARE @N_FACTURA   VARCHAR(16)  
DECLARE @CNSCXC      VARCHAR(20)  
DECLARE @PAGO        DECIMAL(14,2)  
DECLARE @IMPUESTO    DECIMAL(14,2)  
DECLARE @PAGOTOTAL   INT  
DECLARE @FINANC      INT    
DECLARE @GRUPOETAREO VARCHAR(1)
DECLARE @MAXITEM     INT
DECLARE @OK    INT
BEGIN
     BEGIN TRAN 
     PRINT 'INGRESE'
	 
	 IF (SELECT COALESCE(CERRADO,0) FROM FPAG WHERE CNSFPAG=@CNSFPAG)=1
	 BEGIN
		ROLLBACK
        RAISERROR('EL RECAUDO SELECIONADO YA SE ENCUENTRA CERRADO',16,1)
        RETURN
	 END
	 
	 SELECT @OK=COUNT(*)
	 FROM   RPDX, FTR, FPAG 
     WHERE  RPDX.CNS        = @CNSRPDX  
     AND    FTR.N_FACTURA = RPDX.CNS1
	 AND    FPAG.CNSFPAG = @CNSFPAG
	 AND    FPAG.IDTERCERO<>FTR.IDTERCERO 
	 AND	(FTR.IDTERCERO NOT IN (SELECT IDTERCEROFU FROM TERFU WHERE IDTERCEROFU = FTR.IDTERCERO))

	 IF COALESCE(@OK,0)>0
	 BEGIN
		ROLLBACK
        RAISERROR('EXISTEN FACTURAS DE ESTE RECAUDO QUE NO COINCIDEN CON EL TERCERO SELECCIONADO',16,1)
        RETURN
	 END

     UPDATE RPDX SET RPDX.VALOR8 = CASE RPDX.CANTIDAD
                                   WHEN 0 THEN 
                                      CASE RPDX.CANTIDAD2
                                        WHEN 1 THEN (RPDX.VALOR10 + RPDX.VALOR7 + RPDX.VALOR9 - RPDX.VALOR2) - ISNULL(FTR.VIVA,0)
                                        ELSE        (RPDX.VALOR30 + RPDX.VALOR7 +RPDX.VALOR9 - RPDX.VALOR2) 
	                                   END	
                                   ELSE 
                                      CASE RPDX.CANTIDAD2
                                        WHEN 1 THEN                                    
	                                       RPDX.VALOR10 + RPDX.VALOR7 + RPDX.VALOR9 - ISNULL(FTR.VIVA,0)
                                        ELSE
	                                       RPDX.VALOR30 + RPDX.VALOR7 + RPDX.VALOR9
                                      END
                                   END
     FROM   RPDX LEFT JOIN FTR ON RPDX.CNS1 = FTR.N_FACTURA
     WHERE  RPDX.CNS = @CNSRPDX
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR ACTUALIZANDO VALOR8',16,1)
        RETURN
     END
     PRINT  '1 UPDATE'
      
     UPDATE RPDX SET VALOR3 = RPDX.VALOR11
	  WHERE  RPDX.CNS = @CNSRPDX
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR ACTUALIZANDO VALOR 3',16,1)
        RETURN
     END
     	   				
     PRINT ' PASE VALOR3'
     UPDATE RPDX SET VALOR4 = VALOR1 - COALESCE(VALOR2,0) - COALESCE(VALOR3,0) WHERE  RPDX.CNS = @CNSRPDX
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR ACTUALIZANDO VALOR 4',16,1)
        RETURN
     END     
     PRINT ' PASE VALOR4'
        
     IF @DESFIN > 0
     BEGIN
        UPDATE RPDX SET  VALOR5 = VALOR8 * @DESFIN  
        WHERE  RPDX.CNS         = @CNSRPDX   
        AND    RPDX.GRUPOETAREO = 'G'
        IF @@ERROR <> 0
        BEGIN
           ROLLBACK
           RAISERROR('ERROR ACTUALIZANDO VALOR 5 EN GLOSAS',16,1)
           RETURN
        END         
        IF @DF_SERV = 1
        BEGIN
           UPDATE RPDX SET  VALOR5 = VALOR8 * @DESFIN  
           FROM   FTR              
           WHERE  RPDX.CNS         = @CNSRPDX   
           AND    FTR.N_FACTURA    = RPDX.CNS1
           AND    RPDX.GRUPOETAREO = 'F'
           IF @@ERROR <> 0
           BEGIN
              ROLLBACK
              RAISERROR('ERROR ACTUALIZANDO VALOR 5 EN FACTURAS',16,1)
              RETURN
           END           
        END
        ELSE
        BEGIN
           UPDATE RPDX SET  VALOR5 = VALOR8 * @DESFIN  
           WHERE  RPDX.CNS         = @CNSRPDX              
           IF @@ERROR <> 0
           BEGIN
              ROLLBACK
              RAISERROR('ERROR ACTUALIZANDO VALOR 5',16,1)
              RETURN
           END           
        END
        
     END
     ELSE
     BEGIN
        UPDATE RPDX SET VALOR5 = 0 WHERE RPDX.CNS = @CNSRPDX
        IF @@ERROR <> 0
        BEGIN
           ROLLBACK
           RAISERROR('ERROR ACTUALIZANDO VALOR 5 = 0',16,1)
           RETURN
        END        
     END
     PRINT ' PASE DESFIN'          
     UPDATE RPDX SET RPDX.VALOR6 =COALESCE(RPDX.VALOR4,0) - COALESCE(RPDX.VALOR5 ,0)
     WHERE  RPDX.CNS = @CNSRPDX
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR ACTUALIZANDO VALOR 6',16,1)
        RETURN
     END     
     PRINT ' PASE VALOR6'
     UPDATE RPDX SET VALOR6 = 0, VALOR3 = 0, VALOR4= 0, VALOR5 = 0, VALOR7 = 0
     WHERE  RPDX.CNS = @CNSRPDX
     AND    CANTIDAD1 = 1
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR ACTUALIZANDO VALORES 6 3 4 5 7 EN CERO',16,1)
        RETURN
     END     
     PRINT ' PASE CEROS'
     CREATE TABLE #FPD (CNSFPAG VARCHAR(20),  
                        ITEM INT IDENTITY ,  
                        CNSCXC VARCHAR(20),  
                        N_FACTURA VARCHAR(16),                       
                        CERRADO SMALLINT,  
                        USUARIO VARCHAR(12),  
                        COMPANIA VARCHAR(2),  
                        PAGOTOTAL SMALLINT,
                        VLRFACTURA DECIMAL(14,2),
                        VLRGLOSA DECIMAL(14,2),
                        GLOSAAFECTAIMP SMALLINT,
                        VLRCOPAGO DECIMAL(14,2),
                        BASE DECIMAL(14,2),
                        VLRIMPUESTO DECIMAL(14,2),
                        VLRPAGOSIN DECIMAL(14,2),
                        VLRDTOFIN DECIMAL(14,2),
                        VALORPAGO DECIMAL(14,2), CLASE VARCHAR(1), 
                        CNSGLO VARCHAR(20), VLREXTRA DECIMAL(14,2),
                        SINPAGO SMALLINT,
                        OBSERVACION VARCHAR(MAX),
                        LEVANTADO BIT,
                        MOTIVO1 VARCHAR(20),
                        MOTIVO2 VARCHAR(20),
                        VLR_DTO_IND DECIMAL(14,2),
                        CODRESPTA VARCHAR(20),
                        VLR_ACEPTADO DECIMAL(14,2)
                        )  
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR CREANDO TABLA TEMPORAL',16,1)
        RETURN
     END                        
     PRINT ' CREE TABLA TEMP'

     SELECT @MAXITEM = COALESCE(MAX(ITEM),0) FROM FPAGD WHERE CNSFPAG = @CNSFPAG    
     --DBCC CHECKIDENT (#FPD, RESEED, 9 )

     INSERT INTO #FPD (CNSFPAG, CNSCXC, N_FACTURA, CERRADO, USUARIO,  
                       COMPANIA, PAGOTOTAL, VLRFACTURA, VLRGLOSA, GLOSAAFECTAIMP,
                       VLRCOPAGO, BASE, VLRIMPUESTO, VLRPAGOSIN, VLRDTOFIN, VALORPAGO,
                       CLASE, CNSGLO, VLREXTRA, SINPAGO, OBSERVACION, LEVANTADO, MOTIVO1, MOTIVO2,VLR_DTO_IND,CODRESPTA,VLR_ACEPTADO)
     SELECT @CNSFPAG, FCXCDV.CNSCXC, RPDX.CNS1, 0,  @USUARIO,  @COMPANIA, 1,
            VALOR1, VALOR2, CANTIDAD, VALOR7, VALOR8, VALOR3, 
			   VALOR4, VALOR5, VALOR6,
            GRUPOETAREO, CNS5, VALOR9, RPDX.CANTIDAD1, COALESCE(RPDX.STRINGMAX,''), CANTIDAD3, ID11, ID12,
            COALESCE(RPDX.VALOR12,0),ID15,COALESCE(RPDX.VALOR13,0)
     FROM   RPDX, FCXCDV  
     WHERE  RPDX.CNS        = @CNSRPDX  
     AND    FCXCDV.N_FACTURA = RPDX.CNS1   
     AND    FCXCDV.TIPO      = RPDX.GRUPOETAREO
     AND    COALESCE(FCXCDV.CNSGLO,'') = COALESCE(RPDX.CNS5,'')
     AND    FCXCDV.CNSCXC    = RPDX.CNS2
     AND    RPDX.GRUPOETAREO = 'G'
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR INSERTANDO EN TABLA TEMPORAL LAS GLOSAS',16,1)
        RETURN
     END     
     PRINT 'INSERTE GLOSAS'
     
     INSERT INTO #FPD (CNSFPAG, CNSCXC, N_FACTURA, CERRADO, USUARIO,  
                       COMPANIA, PAGOTOTAL, VLRFACTURA, VLRGLOSA, GLOSAAFECTAIMP,
                       VLRCOPAGO, BASE, VLRIMPUESTO, VLRPAGOSIN, VLRDTOFIN, VALORPAGO,
                       CLASE, CNSGLO, VLREXTRA, SINPAGO, OBSERVACION, MOTIVO1, MOTIVO2,VLR_DTO_IND,CODRESPTA,VLR_ACEPTADO)
     SELECT @CNSFPAG, FCXCDV.CNSCXC, RPDX.CNS1, 0,  @USUARIO,  @COMPANIA, 1,
            VALOR1, VALOR2, CANTIDAD, VALOR7, VALOR8, VALOR3, 
			   VALOR4, VALOR5, VALOR6,
            GRUPOETAREO, CNS5, VALOR9, RPDX.CANTIDAD1, COALESCE(RPDX.STRINGMAX,''), ID11, ID12,
            COALESCE(RPDX.VALOR12,0),ID15,COALESCE(RPDX.VALOR13,0)
     FROM   RPDX, FCXCDV  
     WHERE  RPDX.CNS        = @CNSRPDX  
     AND    FCXCDV.N_FACTURA = RPDX.CNS1   
     AND    FCXCDV.TIPO      = RPDX.GRUPOETAREO
     AND    COALESCE(FCXCDV.CNSGLO,'') = COALESCE(RPDX.CNS5,'')
     AND    FCXCDV.CNSCXC    = RPDX.CNS2
     AND    RPDX.GRUPOETAREO = 'R'
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR INSERTANDO EN TABLA TEMPORAL LAS RATIFICACIONES DE GLOSAS',16,1)
        RETURN
     END
     PRINT ' INSERTE RATIFICACION DE GLOSAS'
     
     INSERT INTO #FPD (CNSFPAG, CNSCXC, N_FACTURA, CERRADO, USUARIO,  
                       COMPANIA, PAGOTOTAL, VLRFACTURA, VLRGLOSA, GLOSAAFECTAIMP,
                       VLRCOPAGO, BASE, VLRIMPUESTO, VLRPAGOSIN, VLRDTOFIN, VALORPAGO,
                       CLASE, CNSGLO, VLREXTRA, SINPAGO, OBSERVACION, MOTIVO1, MOTIVO2,VLR_DTO_IND,CODRESPTA,VLR_ACEPTADO)
     SELECT @CNSFPAG, FCXCDV.CNSCXC, RPDX.CNS1, 0,  @USUARIO,  @COMPANIA, 1,
            VALOR1, VALOR2, CANTIDAD, VALOR7, VALOR8, VALOR3, 
			   VALOR4, VALOR5, VALOR6,
            GRUPOETAREO, CNS5, VALOR9, RPDX.CANTIDAD1, COALESCE(RPDX.STRINGMAX,''), ID11, ID12,
            COALESCE(RPDX.VALOR12,0),ID15,COALESCE(RPDX.VALOR13,0)
     FROM   RPDX, FCXCDV  
     WHERE  RPDX.CNS        = @CNSRPDX  
     AND    FCXCDV.N_FACTURA = RPDX.CNS1   
     AND    FCXCDV.TIPO      = RPDX.GRUPOETAREO
     AND    COALESCE(FCXCDV.CNSGLO,'') = COALESCE(RPDX.CNS5,'')
     AND    FCXCDV.CNSCXC    = RPDX.CNS2
     AND    RPDX.GRUPOETAREO = 'C'
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR INSERTANDO EN TABLA TEMPORAL LAS CONCILIACIONES',16,1)
        RETURN
     END
     PRINT ' INSERTE CONCILIACIONES'
          
     
     INSERT INTO #FPD (CNSFPAG, CNSCXC, N_FACTURA, CERRADO, USUARIO,  
                       COMPANIA, PAGOTOTAL, VLRFACTURA, VLRGLOSA, GLOSAAFECTAIMP,
                       VLRCOPAGO, BASE, VLRIMPUESTO, 
                       VLRPAGOSIN, VLRDTOFIN, VALORPAGO,
                       CLASE, CNSGLO, VLREXTRA, SINPAGO, OBSERVACION, MOTIVO1, MOTIVO2,VLR_DTO_IND,CODRESPTA,VLR_ACEPTADO)           
     SELECT @CNSFPAG, FCXCDV.CNSCXC, RPDX.CNS1, 0,  @USUARIO,  @COMPANIA, 1,
            VALOR1, VALOR2, CANTIDAD, VALOR7, VALOR8, VALOR3, 
			VALOR4, VALOR5, VALOR6,
            GRUPOETAREO, '', VALOR9, RPDX.CANTIDAD1, COALESCE(RPDX.STRINGMAX,''), ID11, ID12,
            COALESCE(RPDX.VALOR12,0),ID15,COALESCE(RPDX.VALOR13,0)
     FROM   RPDX, FCXCDV  
     WHERE  RPDX.CNS         = @CNSRPDX  
     AND    FCXCDV.N_FACTURA = RPDX.CNS1   
     AND    FCXCDV.TIPO      = RPDX.GRUPOETAREO
     AND    FCXCDV.CNSCXC    = RPDX.CNS2
     AND    RPDX.GRUPOETAREO = 'F'
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR INSERTANDO EN TABLE TEMPORAL LAS FACTURAS',16,1)
        RETURN
     END     
     PRINT ' INSERTE FACTURAS'
        
     --SELECT * FROM FPAGD
     INSERT INTO FPAGD (CNSFPAG, ITEM, CNSCXC, N_FACTURA, VALORPAGO, CERRADO, USUARIO,  
                        COMPANIA, VLRIMPUESTO, PAGOTOTAL, VLRAJUSTEPESO, VLRFACTURA,
                        VLRFACTURANDNC, CLASEPAG, TIPOGLOSA, VLRDTOFIN, VLRGLOSA,
                        GLOSAAFECTAIMP, VLRPAGOSIN, VLRCOPAGO, BASE, CNSRPDX, CLASE, 
                        CNSGLO, VLREXTRA, SINPAGO, OBSERVACION, LEVANTADO, MOTIVO1, 
                        MOTIVO2,VLROTROSDCTOS,CODRESPTA,VLR_ACEPTADO)  
     SELECT CNSFPAG, ITEM+@MAXITEM, CNSCXC, N_FACTURA, VALORPAGO, CERRADO, USUARIO,  
            COMPANIA, VLRIMPUESTO, PAGOTOTAL, 0, VLRFACTURA, 0, 'P', 'P', VLRDTOFIN,
            VLRGLOSA, GLOSAAFECTAIMP, VLRPAGOSIN, VLRCOPAGO, BASE, @CNSRPDX,  
            CLASE, CNSGLO, VLREXTRA, SINPAGO, OBSERVACION, LEVANTADO, MOTIVO1, MOTIVO2,
            CASE WHEN COALESCE(VLR_DTO_IND,0)<=0 THEN 0 ELSE VLR_DTO_IND END,CODRESPTA,VLR_ACEPTADO
     FROM   #FPD  
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR INSERTANDO DATOS REALES',16,1)
        RETURN
     END     
     IF EXISTS(SELECT * FROM RPDX WHERE CNS=@CNSRPDX+'_1')
     BEGIN
        UPDATE RPDX SET CNS1=FPAGD.CNSFPAG,CANTIDAD=FPAGD.ITEM
        FROM FPAGD INNER JOIN RPDX ON FPAGD.N_FACTURA=RPDX.ID1
        WHERE RPDX.CNS=@CNSRPDX+'_1'
        AND FPAGD.CNSFPAG=@CNSFPAG
     END
     PRINT ' PASE INSERCION REAL'
     SELECT @HOY = GETDATE()         
     PRINT ' INICIA IMPUESTO'
     IF @TRAEIMPUESTO = 1
     BEGIN  
       PRINT ' INGRESO IMPUESTO'
       INSERT INTO FPAGDI(CNSFPAG, N_FACTURA, IDIMPUESTO, IDCLASE, FACTOR, VLRIMPUESTO,
                          USUARIO, CNSCXC, BASE, ITEM, ITEMFIMPDV ) 
       SELECT @CNSFPAG, FTIMP.N_FACTURA, FTIMP.IDIMPUESTO, FTIMP.IDCLASE, FTIMP.FACTOR, FTIMP.VLRIMPTO, 
              @USUARIO, FPAGD.CNSCXC, FTIMP.BASE, FPAGD.ITEM , FTIMP.ITEMFIMPDV  
       FROM   FTIMP INNER JOIN FPAGD ON FTIMP.N_FACTURA = FPAGD.N_FACTURA  
                                    AND FTIMP.TIPO      = FPAGD.CLASE 
                                    AND COALESCE(FTIMP.CNSGLO,'') = COALESCE(FPAGD.CNSGLO,'')
       WHERE  FTIMP.CNS               = @CNSRPDX  
       AND    FPAGD.CNSFPAG           = @CNSFPAG
       AND    FPAGD.VLRIMPUESTO       > 0
       AND    (COALESCE(FTIMP.ESGLOBAL,0) = 0 OR COALESCE(FTIMP.ESGLOBAL,0) = 2)
       IF @@ERROR <> 0
       BEGIN
          ROLLBACK
          RAISERROR('ERROR INGRESANDO IMPUESTOS',16,1)
          RETURN
       END             
       PRINT 'VOY A TOTALES'        
       EXEC SPK_FPAG @CNSFPAG                  
       IF @@ERROR <> 0
       BEGIN
          ROLLBACK
          RAISERROR('ERROR LLAMANDO A SPK_FPAG',16,1)
          RETURN
       END        
     END
     DELETE FROM #FPD WHERE 1=1
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR BORRANDO TABLA TEMPORAL',16,1)
        RETURN
     END
     PRINT ' BORRO TEMPORAL'
     UPDATE FPAG SET DTOFNCIERO = @DESFIN WHERE CNSFPAG = @CNSFPAG
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR ACTUALIZANDO FPAG DTOFNCIERO',16,1)
        RETURN
     END     
     DROP TABLE #FPD
     IF @@ERROR <> 0
     BEGIN
        ROLLBACK
        RAISERROR('ERROR HACIENDO DROP A LA TABLA TEMPORAL',16,1)
        RETURN
     END     
     COMMIT
     PRINT 'VOY A TOTALES HOY'        
     EXEC SPK_FPAG @CNSFPAG                  
END

