IF EXISTS (SELECT name FROM sysobjects 
   WHERE name = 'SPK_ENTREGA_CXC' AND type = 'P')
   DROP PROCEDURE SPK_ENTREGA_CXC
GO
CREATE PROCEDURE DBO.SPK_ENTREGA_CXC 
@CNSCXC           VARCHAR(20), 
@QUIENRECIBIO     VARCHAR(50),
@FECHARECEP       DATETIME,
@NOREFERENCIAEXT  VARCHAR(20),
@CNSRPDX          VARCHAR(20),
@IDSEDE           VARCHAR(5) = NULL,
@NROGUIA	      VARCHAR(20)= NULL,
@AUDIT         BIT=0
WITH ENCRYPTION
AS
DECLARE @PLANDEPAGO   SMALLINT
DECLARE @N_FACTURA    VARCHAR(16)
DECLARE @CNSFCT       VARCHAR(40)
BEGIN   
   /* SE DEBE CREAR CURSOR PARA SABER SI SE DEBE GENERAR EL PLAN DE PAGOS*/
   PRINT 'INCIO CXC'
   DECLARE FTR_CURSOR CURSOR FOR  
   SELECT FTR.N_FACTURA, FTR.PLANDEPAGO, FTR.CNSFCT
   FROM   FTR, FCXCD
   WHERE  FTR.N_FACTURA   = FCXCD.N_FACTURA
   AND    FCXCD.CNSCXC    = @CNSCXC
   AND NOT EXISTS(SELECT * FROM FCXCDV WHERE FCXCD.N_FACTURA=FCXCDV.N_FACTURA AND FCXCD.CNSCXC=FCXCDV.CNSCXC)
   
   OPEN FTR_CURSOR  
   FETCH NEXT FROM FTR_CURSOR  
   INTO  @N_FACTURA, @PLANDEPAGO, @CNSFCT
   WHILE @@FETCH_STATUS = 0  
   BEGIN  
      IF @PLANDEPAGO = 1
      BEGIN
         INSERT INTO FCXCDV ( CNSCXC , N_FACTURA, CNSGLO , TIPO, SALDONETO, FECHA,
                              F_RECIBIDO, F_VENCE, SALDOINICIAL, MARCAPAGO) 
         SELECT @CNSCXC, @N_FACTURA, NULL, 'F', FTRPP.VALORCUOTA, @FECHARECEP,
                @FECHARECEP, FTRPP.FECHA, FTRPP.VALORCUOTA, 0
         FROM   FTRPP
         WHERE  FTRPP.CNSFTR = @CNSFCT
      END
      ELSE
      BEGIN    
         INSERT INTO FCXCDV (CNSCXC , N_FACTURA, CNSGLO , TIPO, SALDONETO, FECHA, 
                             F_RECIBIDO, F_VENCE, SALDOINICIAL, MARCAPAGO) 
         SELECT FCXCD.CNSCXC, FCXCD.N_FACTURA, NULL, 'F', FCXCD.SALDONETO, 
                NULL, NULL, NULL, FCXCD.VALORFACTURA, 0
         FROM   FCXCD LEFT JOIN 
                FCXCDV ON FCXCD.CNSCXC = FCXCDV.CNSCXC AND FCXCD.N_FACTURA = FCXCDV.N_FACTURA AND FCXCDV.TIPO='F'
         WHERE  FCXCD.CNSCXC = @CNSCXC 
                AND FCXCD.N_FACTURA = @N_FACTURA
                AND FCXCDV.CNSCXC IS NULL
         
         UPDATE FCXCDV SET FECHA = @FECHARECEP, F_RECIBIDO = @FECHARECEP, 
                           F_VENCE = @FECHARECEP + PPT.DIASVTO
         FROM   PPT, FTR
         WHERE  FTR.N_FACTURA = @N_FACTURA
         AND    PPT.IDTERCERO = FTR.IDTERCERO
         AND    PPT.IDPLAN    = FTR.IDPLAN
         AND    FCXCDV.CNSCXC = @CNSCXC
         
         UPDATE FCXCDV SET FECHA = @FECHARECEP, F_RECIBIDO = @FECHARECEP, 
                           F_VENCE = @FECHARECEP + 30   
         WHERE  FCXCDV.CNSCXC    = @CNSCXC
         AND    FCXCDV.F_VENCE IS NULL
         AND    FCXCDV.N_FACTURA = @N_FACTURA
                  
      END
      FETCH NEXT FROM FTR_CURSOR  
      INTO  @N_FACTURA, @PLANDEPAGO, @CNSFCT
   END
   CLOSE FTR_CURSOR  
   DEALLOCATE FTR_CURSOR         
   UPDATE FCXC SET F_RECIBIDO      = @FECHARECEP,
                   QUIENRECIBIO    = @QUIENRECIBIO,
                   NOREFERENCIAEXT = @NOREFERENCIAEXT,
                   INDRECIBIDO     = CASE WHEN @AUDIT=0 THEN  1 ELSE 0 END,   
				   NROGUIA         = @NROGUIA               
   WHERE  CNSCXC = @CNSCXC
   PRINT 'REVISO PRESUPUESTO'
   IF DBO.FNK_VALORVARIABLE('PRESUP_CXC_ACTIVADO')= 'SI'  AND  @AUDIT=0
   BEGIN 
      IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')<> 'DESDEFTR'  
      BEGIN
         PRINT 'ENVIO AUTOMATICO A PRESUPUESTO'
         EXEC DBO.SPK_ENTREGA_CXC_PTTO @CNSCXC,@IDSEDE
      END
   END
   PRINT 'ACTUALIZO'
   IF @AUDIT=0
   BEGIN
      UPDATE FTR SET FTR.INDCXC = 1 FROM FCXCD
      WHERE  FTR.N_FACTURA = FCXCD.N_FACTURA
      AND    FCXCD.CNSCXC  = @CNSCXC          
   END
   UPDATE FCXC SET CONTABILIZADA=0,NROCOMPROBANTE=NULL WHERE CNSCXC=@CNSCXC
END

