CREATE OR ALTER  PROCEDURE DBO.SPK_OK_BMOV
@BANCO            VARCHAR(3),
@SUCURSAL         VARCHAR(2),
@CTA_BCO          VARCHAR(40),   
@ITEM             INT,
@USUARIO          VARCHAR(12), 
@SYS_COMPUTERNAME VARCHAR(254), 
@COMPANIA         VARCHAR(2), 
@IDSEDE           VARCHAR(5), 
@NROCOMPROBANTE   VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @TOTALDB DECIMAL(14,2), @ANO  VARCHAR(4), @MES INT
DECLARE @TOTALCR DECIMAL(14,2)
DECLARE @ANTIGUA SMALLINT, @PROCEDENCIA VARCHAR(20), @AUX INT, @FECHAOK DATETIME, @IDOPERACION VARCHAR(20)
BEGIN  
   IF EXISTS( SELECT * FROM BMOV WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM AND ESTADO='O')
   BEGIN
      RAISERROR('Este Movimiento ya se Encuentra Confirmado',16,1)
      RETURN
   END
   SELECT @FECHAOK = FECHAOK FROM BMOV WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM
   IF ISNULL(@FECHAOK,'') = ''
   BEGIN
       SELECT   @ANO             = YEAR(FECHAOPERACION),
                @MES             = MONTH(FECHAOPERACION)
       FROM BMOV WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM
   END 
   ELSE
   BEGIN
      SELECT   @ANO             = YEAR(FECHAOK),
               @MES             = MONTH(FECHAOK)
      FROM BMOV WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM   
   END

   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)
   BEGIN
      RAISERROR('Periodo Contable NO Existe', 16, 1)
      RETURN
   END
   IF (SELECT COALESCE(CERRADO,0) FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES) = 1
   BEGIN
      RAISERROR('Periodo Contable Cerrado', 16, 1)
      RETURN
   END

   SELECT @ANTIGUA=ANTIGUA, @PROCEDENCIA=PROCEDENCIA, @IDOPERACION=IDOPERACION
   FROM BMOV WHERE BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND @CTA_BCO=CTA_BCO AND ITEM=@ITEM
   
   IF @ANTIGUA IS NULL
      SELECT @ANTIGUA = 0
   
   UPDATE BMOV SET ESTADO = 'O'
   WHERE  BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM
   
   IF @ANTIGUA = 0   
   BEGIN
      --SELECT @TOTALDB = SUM(VLROPERACION) 
      --FROM   BMOV INNER JOIN OFIN ON OFIN.IDOPERACION = BMOV.IDOPERACION
      --WHERE  ESTADO = 'O'
      --AND    BMOV.BANCO = @BANCO AND BMOV.SUCURSAL = @SUCURSAL AND BMOV.CTA_BCO = @CTA_BCO
      --AND    OFIN.TIPO = 'DB' 
      
      --SELECT @TOTALCR = SUM(VLROPERACION) 
      --FROM   BMOV INNER JOIN OFIN ON OFIN.IDOPERACION = BMOV.IDOPERACION
      --WHERE  ESTADO = 'O'
      --AND    BMOV.BANCO = @BANCO AND BMOV.SUCURSAL = @SUCURSAL AND BMOV.CTA_BCO = @CTA_BCO
      --AND    OFIN.TIPO = 'CR' 
      
      --IF @TOTALCR IS NULL
      --   SELECT @TOTALCR = 0
      --IF @TOTALDB IS NULL
      --   SELECT @TOTALDB = 0
      
      --PRINT ' DEBITO='+STR(@TOTALDB)
      --PRINT 'CREDITO='+STR(@TOTALCR)
      
      --UPDATE BCT SET SALDO = @TOTALDB - @TOTALCR
      --WHERE  BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO  
            
      EXEC SPK_RECALCULO_BANCOS @BANCO, @SUCURSAL, @CTA_BCO
   END   
   --------------------------------------------------------------------------------
   IF @PROCEDENCIA='BANCOS' OR @PROCEDENCIA='CONTAB'
   BEGIN
      SELECT @AUX = COUNT(*) 
      FROM   BMOVD INNER JOIN BMOV ON BMOV.BANCO    = BMOVD.BANCO 
                                AND BMOV.SUCURSAL = BMOVD.SUCURSAL 
                                AND BMOV.CTA_BCO  = BMOVD.CTA_BCO 
                                AND BMOV.ITEM     = BMOVD.ITEM 
      WHERE  BMOV.ESTADO   = 'O' 
      AND    BMOV.BANCO    = @BANCO 
      AND    BMOV.SUCURSAL = @SUCURSAL
      AND    BMOV.CTA_BCO  = @CTA_BCO
      AND    BMOV.ITEM     = @ITEM
      IF @AUX >0 
      BEGIN
         EXEC SPK_NC_CONTAB_BMOV @BANCO, @SUCURSAL, @CTA_BCO, @ITEM, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @IDSEDE, @NROCOMPROBANTE
      END

      IF 1=(SELECT ISNULL(TRASLADO,0) FROM OFIN WHERE IDOPERACION=@IDOPERACION)
      BEGIN
         IF EXISTS (SELECT 1 FROM OFIN INNER JOIN BCT ON BCT.BANCO=OFIN.BANCO AND BCT.SUCURSAL=OFIN.SUCURSAL AND BCT.CTA_BCO=OFIN.CTA_BCO 
                    WHERE OFIN.IDOPERACION=@IDOPERACION AND BCT.CTA_BCO<>@CTA_BCO)
         BEGIN
            PRINT 'Inserto Movimiento de banco a quien recibe'
            DECLARE @BANCO2 VARCHAR(3), @SUCURSAL2 VARCHAR(2), @CTA_BCO2 VARCHAR(50), @ITEM2 INT, @IDOPERACION2 VARCHAR(20)

            SELECT @BANCO2=BANCO, @SUCURSAL2=SUCURSAL, @CTA_BCO2=CTA_BCO, @IDOPERACION2=HOMOLOGO FROM OFIN WHERE IDOPERACION=@IDOPERACION

            SELECT @ITEM2=MAX(ITEM) FROM BMOV WHERE BANCO=@BANCO2 AND SUCURSAL=@SUCURSAL2 AND CTA_BCO=@CTA_BCO2
            SET @ITEM2=ISNULL(@ITEM2,0)+1

            INSERT INTO BMOV (
            BANCO, SUCURSAL, CTA_BCO, ITEM, FECHAOPERACION, NODOCUMENTO, NOTRANSFOPER, IDOPERACION, VLROPERACION, DESCRIPCION, 
            USUARIO, SYS_COMPUTERNAME, SALDOANTES, SALDODESP, TIPOCOBROFIN, USUARIOOPER, OKOPERACION, PROCEDENCIA, ESTADO, RAZONANULACION, 
            USUARIOANULA, SYS_COMPUTERNAME_ANULA, FECHAOK, FECHAANU, ANTIGUA, CONTABILIZADA, MARCACONT, NROCOMPROBANTE, CODCAJA, CNSFACJ, 
            NROASIENTO, CODUNG, CODPRG, GENCXP, CNSFCXP, IDSEDE )
            SELECT 
            @BANCO2, @SUCURSAL2, @CTA_BCO2, @ITEM2, FECHAOPERACION, NODOCUMENTO, NOTRANSFOPER, @IDOPERACION2, VLROPERACION, DESCRIPCION, 
            USUARIO, SYS_COMPUTERNAME, SALDOANTES, SALDODESP, TIPOCOBROFIN, USUARIOOPER, OKOPERACION, PROCEDENCIA, ESTADO, RAZONANULACION, 
            USUARIOANULA, SYS_COMPUTERNAME_ANULA, FECHAOK, FECHAANU, ANTIGUA, CONTABILIZADA, MARCACONT, NROCOMPROBANTE, CODCAJA, CNSFACJ, 
            NROASIENTO, CODUNG, CODPRG, GENCXP, CNSFCXP, IDSEDE 
            FROM BMOV WHERE BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND CTA_BCO=@CTA_BCO AND ITEM=@ITEM
             
            INSERT INTO BMOVD (
            BANCO, SUCURSAL, CTA_BCO, ITEM, RENGLON, FORMAPAGO, BANCODOC, NODOCUMENTO, VLRITEM, IDTERCERO, 
            RECAUDO, ENPAGOS, OK, DEVUELTO, CAUSALDEV, PROCEDENCIA, CODCAJA, CNSFACJ, IDTERCEROANT, VLRLEGALIZADO, 
            LLAVEDEVCHE, CUENTA, VLRAJUSTE, NROCOMPROBANTE, CCOSTO, RNOMI)
            SELECT 
            @BANCO2, @SUCURSAL2, @CTA_BCO2, @ITEM2, RENGLON, FORMAPAGO, BANCODOC, NODOCUMENTO, VLRITEM, IDTERCERO, 
            RECAUDO, ENPAGOS, OK, DEVUELTO, CAUSALDEV, PROCEDENCIA, CODCAJA, CNSFACJ, IDTERCEROANT, VLRLEGALIZADO, 
            LLAVEDEVCHE, CUENTA, VLRAJUSTE, NROCOMPROBANTE, CCOSTO, RNOMI
            FROM BMOVD WHERE BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND CTA_BCO=@CTA_BCO AND ITEM=@ITEM

            --Actualizo banco
            --SELECT @TOTALCR=0, @TOTALDB=0

            --SELECT @TOTALDB = SUM(VLROPERACION) 
            --FROM   BMOV INNER JOIN OFIN ON OFIN.IDOPERACION = BMOV.IDOPERACION
            --WHERE  ESTADO = 'O'
            --AND    BMOV.BANCO=@BANCO2 AND BMOV.SUCURSAL=@SUCURSAL2 AND BMOV.CTA_BCO=@CTA_BCO2
            --AND    OFIN.TIPO = 'DB' 
      
            --SELECT @TOTALCR = SUM(VLROPERACION) 
            --FROM   BMOV INNER JOIN OFIN ON OFIN.IDOPERACION = BMOV.IDOPERACION
            --WHERE  ESTADO = 'O'
            --AND    BMOV.BANCO=@BANCO2 AND BMOV.SUCURSAL=@SUCURSAL2 AND BMOV.CTA_BCO=@CTA_BCO2
            --AND    OFIN.TIPO = 'CR' 
            EXEC SPK_RECALCULO_BANCOS @BANCO2, @SUCURSAL2, @CTA_BCO2
         END
      END
   END
END

