CREATE OR ALTER PROCEDURE DBO.SPK_FACTURACI_EVENTO_PAQ
@NIT      VARCHAR(20),
@COMPANIA VARCHAR(2),
@IDSEDEUSU   VARCHAR(5),
@USUARIO  VARCHAR(12),
@IDTERCERO VARCHAR(20),
@IDPLAN VARCHAR(20),
@F_FACTURA    DATETIME,
@IDSERVICIOPAQ  VARCHAR(20),
@VLRPAQUETE     DECIMAL(14,2),
@MAXAFI_XFTR SMALLINT,
@OBSERVACIONF VARCHAR(500) = NULL,
@WITH_MARCA BIT = 1
WITH ENCRYPTION
AS
DECLARE @IDAFILIADO VARCHAR(20)
DECLARE @NOMBREAFI VARCHAR(70)
DECLARE @CNSFMAS   VARCHAR(20)
DECLARE @NPAQUETE   VARCHAR(256)
DECLARE @IDTERINSTALADO VARCHAR(20)
DECLARE @CNSFTR      VARCHAR(20)
DECLARE @N_FACTURA   VARCHAR(16)
DECLARE @N_FACTURA_AGRUPA   VARCHAR(16)
DECLARE @IDSEDE   VARCHAR(5)
DECLARE @SEDE_ANTERIOR VARCHAR(5) = NULL
DECLARE @BASE_IVA_SER      VARCHAR(20)
DECLARE @DV         SMALLINT, @TTEC VARCHAR(20),   @CUENTACXC VARCHAR(20), @NODESCUENTACOPAGO BIT, @CUENTACXC_RAD VARCHAR(20),   @MONEDA  VARCHAR(20) ,@IDDEP  VARCHAR(20)
    ,@EC BIT,   @OBSERVACION VARCHAR(2048),   @TIPOVENTA VARCHAR(10), @TV VARCHAR(20), @BLOQUEADIAN VARCHAR(5), @FACTSEDE VARCHAR(5), @VALORCOPAGO DECIMAL(14,2), @DESCUENTOS DECIMAL(14,2)
    ,@TIPOFIN VARCHAR(2), @IDFORMATOFTR VARCHAR(20), @VALORMODERADORA  DECIMAL(14,2), @SINCNT BIT,@SYS_COMPUTERNAME VARCHAR(254), @CONSECUTIVO VARCHAR(20)

BEGIN
    SET NOCOUNT ON
    PRINT 'EMPIEZO EL SPK DE SPK_FACTURACI_EVENTO_PAQ - VERSION OPTIMIZADA'
    PRINT 'VERIFICO VARIABLES'
    PRINT '@IDTERCERO > '+COALESCE(@IDTERCERO,'NADA TER')
	PRINT '@IDPLAN >'  + COALESCE(@IDPLAN,' SIN @IDPLAN')
	PRINT '@USUARIO >'  + COALESCE(@USUARIO,' SIN @USUARIO')
	PRINT '@IDSEDEUSU >'  + COALESCE(@IDSEDEUSU,' SIN @IDSEDEUSU')
    SELECT @IDTERINSTALADO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
	SELECT @BASE_IVA_SER = DATO FROM USVGS WITH (NOLOCK) WHERE IDVARIABLE='BASE_IVA_SERVICIOS'

    SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WITH (NOLOCK) WHERE USUARIO = @USUARIO

    CREATE TABLE #PacientesXFtr (
        IDAFILIADO VARCHAR(20),
        IDSEDE VARCHAR(2),
        CNSFCT VARCHAR(20),
        N_FACTURA VARCHAR(20),
	    CONSECUTIVO VARCHAR(20),
        VALORCOPAGO DECIMAL(14,2)
    );

    CREATE TABLE #FTRD1(CNSFTR VARCHAR(40), N_CUOTA	int IDENTITY, FECHA datetime,
				DB_CR varchar(2), AREAPRESTACION varchar(20), UBICACION varchar(16),
				VR_TOTAL float, IMPUTACION varchar(16), CCOSTO varchar (20),
				PREFIJO varchar(6), ANEXO varchar(1024), REFERENCIA varchar(40), 
				IDCIRUGIA varchar(20), CANTIDAD smallint, VALOR decimal(14,2),
				VLR_SERVICI decimal(14,2), VLR_COPAGOS decimal(14,2),
				VLR_PAGCOMP decimal(14,2), IDPROVEEDOR varchar(20),
				NOADMISION varchar(16), NOPRESTACION	varchar(16), NOITEM int, IDAFILIADO VARCHAR(20),	
				AREAFUNCONT varchar(20), N_FACTURA varchar(16),
				SUBCCOSTO varchar(4), PCOSTO	decimal(14,2), FECHAPREST datetime, IDPLAN VARCHAR(6),
				IDIMPUESTO VARCHAR(10),IDCLASE    VARCHAR(10),ITEM       INT,VLRIMPUESTO DECIMAL(14,2),
				PIVA        DECIMAL(14,2),VIVA        DECIMAL(14,2),CUENTA_FIMPDV VARCHAR(20),
			    PROCEDENCIA VARCHAR(10),PAQUETE SMALLINT,TCOPAGO VARCHAR(10)
	)

    -- ============================================================================
    -- FASE 1: PREPARACIÓN DE DATOS (SIN TRANSACCIÓN - MINIMIZA BLOQUEOS)
    -- ============================================================================
    PRINT '=== FASE 1: PREPARACIÓN DE DATOS (SIN TRANSACCIÓN) ==='

    IF @WITH_MARCA = 1
    BEGIN
        PRINT 'Valido sedes'
        IF EXISTS( 
            SELECT 1 FROM CIT WITH (NOLOCK)
            WHERE CIT.IDTERCEROCA=@IDTERCERO AND CIT.IDPLAN=@IDPLAN
            AND (@IDSEDEUSU IS NULL OR @IDSEDEUSU = CIT.IDSEDE)
            AND COALESCE(CIT.FACTURADA,0)=0 
            AND CIT.FACTURABLE=1
			AND CIT.ENFACT=1
            AND CIT.MARCAFAC = 1 
            AND CIT.USUARIONOFACTURABLE = @USUARIO
            AND NOT EXISTS (SELECT 1 FROM FDIAN WITH (NOLOCK) WHERE PROCEDENCIA='FTR' AND COALESCE(VENCIDA,0)=0 AND IDENTIFICADOR = CIT.IDSEDE)
        )
        BEGIN
            RAISERROR('Existen sedes en este proceso de facturacion que no cuentan con resolucion vigente. Comuniquese con el Administrador del Sistema.', 16, 1)
            RETURN
        END
    END

    -- Cursor para recorrer los pacientes por sede
    IF @WITH_MARCA = 1
    BEGIN
		IF DBO.FNK_VALORVARIABLE('FACTSEDEPACIENTE')='SI'
		BEGIN
			PRINT 'LLENO CURSOR DE PACIENTES CON SEDE DEL PACIENTE'
			DECLARE CursorPacientes CURSOR FOR 
			SELECT AFI.IDSEDE, AFI.IDAFILIADO, CONSECUTIVO, COALESCE(CIT.VALORCOPAGO,0)
			FROM CIT WITH (NOLOCK) INNER JOIN AFI WITH (NOLOCK) ON AFI.IDAFILIADO=CIT.IDAFILIADO
			WHERE 
			CIT.IDTERCEROCA=@IDTERCERO 
			AND CIT.IDPLAN=@IDPLAN
			--AND (@IDSEDEUSU IS NULL OR @IDSEDEUSU = CIT.IDSEDE)
			AND COALESCE(CIT.FACTURADA,0)=0 
			AND CIT.FACTURABLE=1
			AND CIT.ENFACT=1
			AND CIT.MARCAFAC = 1 
			AND CIT.USUARIONOFACTURABLE = @USUARIO
			ORDER BY AFI.IDSEDE, AFI.IDAFILIADO
		END
		ELSE
		BEGIN
			PRINT 'LLENO CURSOR DE PACIENTES'
			DECLARE CursorPacientes CURSOR FOR 
			SELECT IDSEDE, IDAFILIADO, CONSECUTIVO, COALESCE(CIT.VALORCOPAGO,0)
			FROM CIT WITH (NOLOCK)
			WHERE 
			CIT.IDTERCEROCA=@IDTERCERO 
			AND CIT.IDPLAN=@IDPLAN
			AND (@IDSEDEUSU IS NULL OR @IDSEDEUSU = CIT.IDSEDE)
			AND COALESCE(CIT.FACTURADA,0)=0 
			AND CIT.FACTURABLE=1
			AND CIT.ENFACT=1
			AND CIT.MARCAFAC = 1 
			AND CIT.USUARIONOFACTURABLE = @USUARIO
			ORDER BY IDSEDE, IDAFILIADO
		END
    END


    -- Cargar pacientes en tabla temporal (SIN TRANSACCIÓN - solo lectura)
    PRINT 'Cargando pacientes en tabla temporal...'
    OPEN CursorPacientes
    FETCH NEXT FROM CursorPacientes INTO @IDSEDE, @IDAFILIADO, @CONSECUTIVO, @VALORCOPAGO

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Ingreso el paciente sin consecutivos aún (se generarán dentro de la transacción)
        INSERT INTO #PacientesXFtr (IDAFILIADO, IDSEDE, CNSFCT, N_FACTURA, CONSECUTIVO, VALORCOPAGO) 
        SELECT @IDAFILIADO, @IDSEDE, NULL, NULL, @CONSECUTIVO, @VALORCOPAGO

        FETCH NEXT FROM CursorPacientes INTO @IDSEDE, @IDAFILIADO, @CONSECUTIVO, @VALORCOPAGO
    END

    CLOSE CursorPacientes
    DEALLOCATE CursorPacientes

	IF NOT EXISTS(SELECT 1 FROM #PacientesXFtr)
    BEGIN
        RAISERROR('No existen pacientes agrupados por facturas. Comuniquese con el Administrador del Sistema.', 16, 1)
        RETURN
    END

    -- Obtener parámetros de configuración (SIN TRANSACCIÓN)
    SELECT @DV = DIASVTO, @TTEC = TIPOTERCONTABLE, @NODESCUENTACOPAGO = NODESCUENTACOPAGO
	FROM   PPT WITH (NOLOCK) WHERE IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN
	PRINT 'DV-TTEC-NODESCUENTA'

	IF (SELECT SIIF FROM TER WITH (NOLOCK) WHERE IDTERCERO = @IDTERCERO)=1
		SELECT @OBSERVACION='#$'+COALESCE(SIIFCODIGOPCI,'')+';'+COALESCE(SIIFCONTRATO,'')+';'+COALESCE(SIIFCORREOSUPER,'')+'#$'
		FROM TER WITH (NOLOCK) WHERE IDTERCERO = @IDTERCERO 

    IF COALESCE(@TTEC,'')=''
    BEGIN
        SELECT @TTEC=DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART')
    END

	SELECT @CUENTACXC = CUENTA,@CUENTACXC_RAD=CUENTARAD FROM TTEC WITH (NOLOCK)
	WHERE TIPO = @TTEC
	PRINT 'CUENTACXC-CUENTACXCRAD > ' + @CUENTACXC + ' - ' + @CUENTACXC_RAD

	IF @DV IS NULL OR @DV = 0
		SELECT @DV = 30
	PRINT 'DV='+STR(@DV)

	SELECT @TV = CASE WHEN @TIPOVENTA IS NOT NULL THEN @TIPOVENTA ELSE 'Credito' END
	SELECT @EC = ENVIODICAJA FROM TER WITH (NOLOCK) WHERE IDTERCERO = @IDTERCERO
        
	IF @EC IS NULL
		SELECT @EC = 0

	SELECT @MONEDA = DATO FROM USVGS WITH (NOLOCK) WHERE IDVARIABLE = 'IDMONEDABASE'          
	SELECT @IDDEP = LEFT(DATO,20) FROM USVGS WITH (NOLOCK) WHERE IDVARIABLE = 'IDFDEPFACTURACION' 
    SELECT @BLOQUEADIAN = DBO.FNK_VALORVARIABLE('BLOQUEADIAN')
    SELECT @FACTSEDE = DBO.FNK_VALORVARIABLE('FACTSEDE')

    SELECT @IDFORMATOFTR=IDFORFTRCE FROM PPT WITH (NOLOCK) WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN

    -- ============================================================================
    -- FASE 2: INSERCIÓN/ACTUALIZACIÓN (CON TRANSACCIÓN CORTA)
    -- ============================================================================
    PRINT '=== FASE 2: INSERCIÓN CON TRANSACCIÓN CORTA ==='
    
    BEGIN TRY
        BEGIN TRANSACTION

        -- Generar consecutivos para cada grupo de factura (DENTRO DE LA TRANSACCIÓN)
        -- Agrupar pacientes por sede y cantidad máxima
        DECLARE @PacientesEnGrupo INT = 0
        SET @SEDE_ANTERIOR = ''
        SET @N_FACTURA = NULL
        SET @CNSFTR = NULL

        DECLARE CursorPacientesGrupo CURSOR FOR
        SELECT IDSEDE, IDAFILIADO, CONSECUTIVO, VALORCOPAGO
        FROM #PacientesXFtr
        ORDER BY IDSEDE, IDAFILIADO

        OPEN CursorPacientesGrupo
        FETCH NEXT FROM CursorPacientesGrupo INTO @IDSEDE, @IDAFILIADO, @CONSECUTIVO, @VALORCOPAGO

        WHILE @@FETCH_STATUS = 0
        BEGIN
            -- Si cambia la sede o superamos el máximo de pacientes, generamos una nueva factura
            IF @PacientesEnGrupo = 0 OR @PacientesEnGrupo >= @MAXAFI_XFTR OR @IDSEDE <> @SEDE_ANTERIOR
            BEGIN
                SET @N_FACTURA = SPACE(20)
	            EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @N_FACTURA OUTPUT   
	            SET @CNSFTR = SPACE(20)
	            EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
	            SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0)

                SET @PacientesEnGrupo = 0
                SET @SEDE_ANTERIOR = @IDSEDE
            END

            -- Actualizar el paciente con el número de factura que lo agrupa
            UPDATE #PacientesXFtr
            SET CNSFCT = @CNSFTR, N_FACTURA = @N_FACTURA
            WHERE IDAFILIADO = @IDAFILIADO AND CONSECUTIVO = @CONSECUTIVO

            SET @PacientesEnGrupo = @PacientesEnGrupo + 1

            FETCH NEXT FROM CursorPacientesGrupo INTO @IDSEDE, @IDAFILIADO, @CONSECUTIVO, @VALORCOPAGO
        END

        CLOSE CursorPacientesGrupo
        DEALLOCATE CursorPacientesGrupo

        PRINT 'Consecutivos generados para pacientes agrupados por factura'

        -- Preparar datos de FTRD con los consecutivos asignados
        PRINT 'LLENO #FTRD1'
        INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                        IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                        VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,PROCEDENCIA,
                        NOPRESTACION, NOITEM, IDAFILIADO, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, IDPLAN,IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO,
                       PIVA, VIVA,CUENTA_FIMPDV,TCOPAGO,PAQUETE) 
        SELECT P.CNSFCT, @F_FACTURA , 'DB', CIT.IDAREA, NULL, @VLRPAQUETE-P.VALORCOPAGO
                , NULL,CIT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, SER.IDSERVICIO, NULL,  1 
                ,CONVERT(DECIMAL(14,2),@VLRPAQUETE/1),  @VLRPAQUETE, P.VALORCOPAGO, 0, CIT.IDMEDICO, P.CONSECUTIVO,'CI'
                , P.CONSECUTIVO, 99, P.IDAFILIADO, NULL, P.N_FACTURA, CIT.SUBCCOSTO, CIT.VALORTOTALCOS, CIT.FECHA, CIT.IDPLAN,
                                   CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END,
                                   CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
                                   CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(@VLRPAQUETE-P.VALORCOPAGO))) ELSE NULL END,
                                   CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  @VLRPAQUETE-P.VALORCOPAGO ELSE NULL END ,
                                   CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VLRPAQUETE-P.VALORCOPAGO)) ELSE NULL END,
                                   CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  CASE WHEN @BASE_IVA_SER='CONIVA' 
                                                                               THEN  (SELECT @VLRPAQUETE-P.VALORCOPAGO -ROUND(@VLRPAQUETE-P.VALORCOPAGO/((VALOR+100)/100),0) 
                                                                               FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VLRPAQUETE-P.VALORCOPAGO))
                                                                           ELSE
                                                                           (SELECT ROUND(@VLRPAQUETE-P.VALORCOPAGO*(VALOR/100),0) 
                                                                           FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VLRPAQUETE-P.VALORCOPAGO)) END ELSE NULL END,
                                   CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VLRPAQUETE-P.VALORCOPAGO))  ELSE NULL END,
                             DBO.FNK_TRAE_TIPOCOPAGO(CIT.CONSECUTIVO,'CI'), 0
        FROM   #PacientesXFtr P 
        INNER JOIN CIT WITH (NOLOCK) ON CIT.CONSECUTIVO=P.CONSECUTIVO
        INNER JOIN SER WITH (NOLOCK) ON SER.IDSERVICIO=@IDSERVICIOPAQ

        IF NOT EXISTS(SELECT 1 FROM #FTRD1)
        BEGIN
            RAISERROR('No existe detalle de facturas. Comuniquese con el Administrador del Sistema.', 16, 1)
            ROLLBACK TRANSACTION
            RETURN
        END

        -- INSERT EN FTR (TABLA PRINCIPAL DE FACTURAS)
        PRINT 'Insertando en FTR...'
	    INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE, VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
					    IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION, TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
					    INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC, IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
					    MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
					    CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CODUNG , CODPRG, PAQUETE,
					    IDSEDE, RDIAN, CNSRESOL,IDFORMATO,COPAPROPIO,CP_VLR_COPAGOS,CAPITADA,FECHACAP_INI,FECHACAP_FIN, VALORMODERADORA,SINCNT)
	    SELECT DISTINCT P.CNSFCT, @COMPANIA, 'C', @IDTERCERO, P.N_FACTURA, CASE  WHEN  @F_FACTURA IS NOT NULL THEN @F_FACTURA ELSE DBO.FNK_GETDATE() END,
		    CASE  WHEN  @F_FACTURA IS NOT NULL THEN @F_FACTURA + @DV ELSE DBO.FNK_GETDATE() + @DV END
		    ,0, NULL, NULL, @MONEDA, NULL, 'P', NULL, 
			    NULL, @USUARIO, 'VARIOS', 'CI', 'M', COALESCE(@OBSERVACIONF, REPLACE(COALESCE(@OBSERVACION,''),'@N_FACTURA',P.N_FACTURA)), @TV,  0, 0, 0, 0, 
		    0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO, GETDATE(), 0, 0, 0, 
		    @IDPLAN, NULL, COALESCE(@TIPOFIN,'C'), NULL, NULL, NULL, @IDDEP, @TTEC,@CUENTACXC,@CUENTACXC_RAD, '' , '', 1, P.IDSEDE,
		    CASE WHEN @BLOQUEADIAN='SI' THEN
                CASE WHEN @FACTSEDE='SI' THEN 
                CASE WHEN EXISTS(SELECT TOP 1 CNSRESOL FROM FDIAN WITH (NOLOCK) WHERE IDENTIFICADOR=P.IDSEDE AND VENCIDA=0 AND PROCEDENCIA = 'FTR') THEN 1 ELSE 0 END
                ELSE 
                CASE WHEN EXISTS(SELECT TOP 1 CNSRESOL FROM FDIAN WITH (NOLOCK) WHERE VENCIDA=0 AND PROCEDENCIA = 'FTR') THEN 1 ELSE 0 END
                END
            ELSE 0 END, CASE WHEN @BLOQUEADIAN='SI' THEN
                CASE WHEN @FACTSEDE='SI' THEN 
                    ISNULL((SELECT TOP 1 CNSRESOL FROM FDIAN WITH (NOLOCK) WHERE IDENTIFICADOR=P.IDSEDE AND VENCIDA=0 AND PROCEDENCIA = 'FTR'), '')
                ELSE 
                ISNULL((SELECT TOP 1 CNSRESOL FROM FDIAN WITH (NOLOCK) WHERE VENCIDA=0 AND PROCEDENCIA = 'FTR'), '')
                END
            ELSE '' END,@IDFORMATOFTR ,0,0,0,NULL,NULL, COALESCE(@VALORMODERADORA,0),COALESCE(@SINCNT,0)
        FROM   #PacientesXFtr P

        -- INSERT EN FTRD (DETALLE DE FACTURA)
        PRINT 'Insertando en FTRD...'
        INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                        IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                        VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                        NOPRESTACION, NOITEM, IDAFI, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, IDPLAN,IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO,
                       PIVA, VIVA,CUENTA_FIMPDV,TCOPAGO,PAQUETE) 
        SELECT CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                        IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                        VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                        NOPRESTACION, NOITEM, IDAFILIADO, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, IDPLAN,IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO,
                       PIVA, VIVA,CUENTA_FIMPDV,TCOPAGO,PAQUETE
        FROM #FTRD1 

        -- ACTUALIZAR TOTALES EN FTR
        PRINT 'Actualizando totales de facturas...'
        UPDATE F
        SET 
                F.VALORSERVICIOS = D.VRSERV,
                F.VALORCOPAGO = D.TotalCopago,
                F.VALORPCOMP = D.TotalPagComp,
                F.VR_TOTAL = D.VRTOTAL
        FROM FTR F 
        JOIN (
                SELECT 
                CNSFTR,
                COALESCE(SUM(VLR_SERVICI),0) AS VRSERV,
                COALESCE(SUM(VR_TOTAL),0) AS VRTOTAL,
                SUM(VLR_COPAGOS) AS TotalCopago,
                SUM(VLR_PAGCOMP) AS TotalPagComp
                FROM FTRD
                WHERE CNSFTR IN (SELECT DISTINCT CNSFCT FROM #PacientesXFtr)
                GROUP BY CNSFTR
        ) D ON D.CNSFTR = F.CNSFCT
        WHERE F.CNSFCT IN (SELECT DISTINCT CNSFCT FROM #PacientesXFtr)

        -- ACTUALIZAR CIT COMO FACTURADO
        PRINT 'Actualizando CIT como facturado...'
        UPDATE C
        SET 
            C.FACTURADA = 1,
            C.N_FACTURA = P.N_FACTURA,
            C.MARCAFAC = 0,
            C.CNSFCT=P.CNSFCT,
            C.USUARIONOFACTURABLE=NULL
        FROM CIT C
        INNER JOIN #PacientesXFtr P ON C.CONSECUTIVO = P.CONSECUTIVO
        WHERE C.IDTERCEROCA = @IDTERCERO
            AND C.IDPLAN = @IDPLAN
            AND COALESCE(C.FACTURADA,0) = 0
            AND C.ENFACT=1
            AND C.FACTURABLE=1

        -- COMMIT DE LA TRANSACCIÓN
        COMMIT TRANSACTION
        PRINT '=== TRANSACCIÓN COMPLETADA EXITOSAMENTE ==='

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION
        
        PRINT '=== ERROR EN LA TRANSACCIÓN - ROLLBACK EJECUTADO ==='
        PRINT 'Los consecutivos de factura NO se perdieron (fueron revertidos)'
        
        -- Re-lanzar el error para que el procedimiento padre lo capture
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE()
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY()
        DECLARE @ErrorState INT = ERROR_STATE()
        
        RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState)
        
        -- Limpiar tablas temporales antes de salir
        IF OBJECT_ID('tempdb..#PacientesXFtr') IS NOT NULL DROP TABLE #PacientesXFtr;
        IF OBJECT_ID('tempdb..#FTRD1') IS NOT NULL DROP TABLE #FTRD1;
        
        RETURN
    END CATCH

    -- ============================================================================
    -- FASE 3: CONTABILIZACIÓN (FUERA DE TRANSACCIÓN - PROCESO SECUNDARIO)
    -- ============================================================================
    PRINT '=== FASE 3: CONTABILIZACIÓN ==='
    
    -- Verificar si la contabilización se hace por JOB o directamente
    DECLARE @CONTAB_POR_JOB VARCHAR(5) = DBO.FNK_VALORVARIABLE('CONTAB_FTR_JOB')
    
    IF @CONTAB_POR_JOB = 'SI'
    BEGIN
        -- CONTABILIZACIÓN POR TRABAJO (JOB)
        -- Insertar en tabla FTRCO para que el job lo procese después
        PRINT 'Contabilización delegada a JOB - Insertando en FTRCO...'
        
        INSERT INTO FTRCO(N_FACTURA, USUARIO, SYS_COMPUTERNAME, COMPANIA, SEDE)
        SELECT DISTINCT N_FACTURA, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, IDSEDE
        FROM #PacientesXFtr
        
        PRINT 'Facturas encoladas para contabilización por JOB: ' + CAST(@@ROWCOUNT AS VARCHAR(10))
    END
    ELSE
    BEGIN
        -- CONTABILIZACIÓN DIRECTA
        PRINT 'Contabilización directa de facturas...'
        
        DECLARE CONTA_FTR_CURSOR CURSOR FOR
        SELECT DISTINCT N_FACTURA, IDSEDE
        FROM #PacientesXFtr 
        
        OPEN CONTA_FTR_CURSOR;
        FETCH NEXT FROM CONTA_FTR_CURSOR INTO @N_FACTURA, @IDSEDE
         
        WHILE @@FETCH_STATUS = 0
        BEGIN
            BEGIN TRY
                EXEC SPK_NC_CONTAB_FTR @N_FACTURA, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''         
            END TRY
            BEGIN CATCH
                -- La contabilización puede fallar sin afectar la facturación
                PRINT 'Advertencia: Error en contabilización de factura ' + @N_FACTURA + ': ' + ERROR_MESSAGE()
            END CATCH
         
            FETCH NEXT FROM CONTA_FTR_CURSOR INTO @N_FACTURA, @IDSEDE;
        END
         
        CLOSE CONTA_FTR_CURSOR;
        DEALLOCATE CONTA_FTR_CURSOR;
    END

    -- Limpiar tablas temporales
    IF OBJECT_ID('tempdb..#PacientesXFtr') IS NOT NULL DROP TABLE #PacientesXFtr;
    IF OBJECT_ID('tempdb..#FTRD1') IS NOT NULL DROP TABLE #FTRD1;

    PRINT '=== PROCESO COMPLETADO ==='
END

