IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_LIBERA_FTR_COMER' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_LIBERA_FTR_COMER
END

GO
CREATE PROCEDURE DBO.SPK_LIBERA_FTR_COMER 
@N_FACTURA  VARCHAR(20)
WITH ENCRYPTION
AS  
DECLARE @EXISTE INT
DECLARE @SALDONETO DECIMAL(14,2)
DECLARE @CONTABILIZADO SMALLINT
DECLARE @F_FACTURA DATETIME
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @CNSCXC         VARCHAR(20)
DECLARE @CNSMOV         VARCHAR(20)
DECLARE @CNSFTR         VARCHAR(20)
BEGIN  
   PRINT 'CAPTURO DATOS'
   SELECT @CONTABILIZADO=CONTABILIZADA,@F_fACTURA=F_FACTURA,@NROCOMPROBANTE=FTR.NROCOMPROBANTE,@CNSCXC=FCXCD.CNSCXC 
   FROM FTR LEFT JOIN FCXCD ON FTR.N_FACTURA=FCXCD.N_FACTURA
   WHERE FTR.N_FACTURA=@N_fACTURA

   IF (SELECT COALESCE(CERRADO,2) FROM PRI WHERE FECHA_INI<=@F_FACTURA AND FECHA_fIN>@F_FACTURA)<>0
   BEGIN 
      RAISERROR('El periodo contable de la Factura no Esta Abierto o No Existe',1,26)
      RETURN
   END
   PRINT '@N_FACTURA ='+@N_FACTURA+' @CNSCXC='+@CNSCXC

   PRINT 'Retiro la Factura de Fcxcd'

   DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA AND CNSCXC=@CNSCXC
   DELETE FCXCD WHERE N_FACTURA=@N_FACTURA AND CNSCXC=@CNSCXC

   IF (SELECT COUNT(*) FROM FCXCD WHERE CNSCXC=@CNSCXC)<=0
   BEGIN
      UPDATE FCXC SET ESTADO='Inactivo' WHERE CNSCXC=@CNSCXC
   END

   IF COALESCE(@CONTABILIZADO,0)=1
   BEGIN
      UPDATE MCP SET ESTADO=0,ANULADO=1 WHERE NROCOMPROBANTE=@NROCOMPROBANTE
      UPDATE MCH SET ESTADO=0 WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   END
   ELSE
   BEGIN
      DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
      DELETE MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   END
   
   UPDATE FTR SET CONTABILIZADA=0,NROCOMPROBANTE=NULL,IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPFACTURACION'),
                  INDCARTERA=0,INDCXC=0,MARCA=0,INDASIGCXC=0,MARCACONT=0,IMPRESO=0, PIVA = 0, VIVA = 0, 
				  VR_TOTAL = 0, VALORSERVICIOS = 0,
                  ESTADO=CASE WHEN PROCEDENCIA='INVENTARIO' THEN 'L' ELSE ESTADO END
   WHERE N_FACTURA=@N_FACTURA
   
   IF EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTURA AND PROCEDENCIA='INVENTARIO')
   BEGIN
      SELECT @CNSMOV=NOREFERENCIA,@CNSFTR=CNSFCT 
      FROM FTR 
      WHERE N_FACTURA=@N_FACTURA 
      AND PROCEDENCIA='INVENTARIO'

      UPDATE IMOV SET FACTURADA=0,N_FACTURA=@N_fACTURA,NOCONSECUTIVO=@CNSFTR  WHERE CNSMOV=@CNSMOV

      DELETE FTRD WHERE N_fACTURA=@N_fACTURA AND CNSFTR=@CNSFTR
   END
END

