IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_ACTUALIZA_SALDO_BANCO' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_ACTUALIZA_SALDO_BANCO
END

GO
CREATE PROCEDURE DBO.SPK_ACTUALIZA_SALDO_BANCO 
@CNSFACJ            VARCHAR(20), 
@CODCAJA            VARCHAR(4) 
WITH ENCRYPTION
AS
DECLARE @TIPOPAGO			VARCHAR(3)
DECLARE @VALOR				DECIMAL(14,2)
DECLARE @USAR_CUENTACAJA	SMALLINT
DECLARE @CUENTA				VARCHAR(16)
BEGIN
	DECLARE CURSOR_PAGOS CURSOR FOR
	SELECT TIPOPAGO, VALOR FROM PCJ WHERE CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ
	
	OPEN CURSOR_PAGOS
	FETCH NEXT FROM CURSOR_PAGOS
	INTO @TIPOPAGO, @VALOR
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT @USAR_CUENTACAJA = ISNULL(USAR_CUENTACAJA,0) , @CUENTA = ISNULL(CUENTA,'') FROM FPA WHERE FORMAPAGO = @TIPOPAGO

		IF @USAR_CUENTACAJA = 1 -- SI LA CUENTA ES DE LA CAJA
			SELECT @CUENTA = ISNULL(CUENTA,'') FROM CAJ WHERE CODCAJA = @CODCAJA	

		IF @CUENTA <> '' 
			UPDATE BCT SET SALDO = (SALDO + @VALOR)	WHERE COD_CONTABLE = @CUENTA

		FETCH NEXT FROM CURSOR_PAGOS
		INTO @TIPOPAGO, @VALOR
	END

	CLOSE CURSOR_PAGOS
	DEALLOCATE CURSOR_PAGOS
END


