CREATE OR ALTER PROCEDURE DBO.SPK_COPAGO_AUT_CEHOSP_RELIQ
@IDAUT            VARCHAR(20), 
@PROCEDENCIA      VARCHAR(2),
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA         VARCHAR(2),
@IDSEDE           VARCHAR(5),
@USUARIO          VARCHAR(12)
WITH ENCRYPTION
AS
DECLARE @TIPOAFILIADO     VARCHAR(1),    @IDADMINISTRADORA  VARCHAR(20),   @GRUPOETNICO      VARCHAR(1),    @EDAD             DECIMAL(14,2),
        @TIPOAFILIADO2    VARCHAR(12),   @NIVELSOCIOEC      VARCHAR(2),    @IDPLAN           VARCHAR(6),    @PREFIJO          VARCHAR(6),
        @NIVELATENCION    VARCHAR(5),    @IDMODELOPCA       VARCHAR(5),    @COBRARCOPA       VARCHAR(12),   @EXPYP            SMALLINT,
        @TIPODEPAGO       VARCHAR(10),   @EXALTOCOSTO       SMALLINT,      @EXGRUPOETNICO    VARCHAR(1),    @FORMACOBRO       VARCHAR(10),
        @REDONDEO         VARCHAR(10),   @VALOR             DECIMAL(14,2), @VALORCOPAGO      DECIMAL(14,2), @MESES            DECIMAL(14,2),
        @FNACIM           DATETIME,      @EXEDAD            SMALLINT,      @VALORTOTAL1      DECIMAL(14,2), @AUXN             INT,
        @IDTERCEROCA      VARCHAR(20),   @IDTERCEROCAD      VARCHAR(20),   @DATOCONT         VARCHAR(20),   @VLRSERVICIO      DECIMAL(14,2),
        @VALORTOTALCOSTO  DECIMAL(14,2), @CALCULARPOR       VARCHAR(5),    @OK               INT,           @PART             SMALLINT,
        @AQUIENCOBRO      VARCHAR(1),    @NOAUTORIZACIONCIT VARCHAR(45),   @PYP              SMALLINT,      @ALTOCOSTO        SMALLINT,
        @IDAFILIADO       VARCHAR(20),   @IDPROVEEDOR       VARCHAR(20),   @IDAREA           VARCHAR(20),   @FECHAAUT         DATETIME,
        @COPAGOPROPIO     SMALLINT = 0,  @SOAT              SMALLINT = 0,  @NO_ITEM          SMALLINT,      @IDSERVICIO       VARCHAR(20),
        @VALORAUTD        DECIMAL(14,2)
DECLARE @AUTD TABLE (ID INT IDENTITY(1,1), NO_ITEM SMALLINT, IDSERVICIO VARCHAR(20))
DECLARE @FIX INT, @FIX_TO INT, @IDCJPLANEXTERNO VARCHAR(20), @IDCJTERCEROEXTERNO VARCHAR(20)
BEGIN 
	SELECT @IDCJPLANEXTERNO=LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE='IDCJPLANEXTERNO'
	SELECT @IDCJTERCEROEXTERNO=LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE='IDCJTERCEROEXTERNO'

    SELECT @PYP  = CASE CLASEORDEN WHEN 'PyP' THEN 1 ELSE 0 END, 
            @ALTOCOSTO = CASE ALTOCOSTO WHEN 'Si' THEN 1 ELSE 0 END,
            @IDAFILIADO = IDAFILIADO, @IDPROVEEDOR = IDPROVEEDOR, @IDAREA = IDAREA,
            @FECHAAUT   = FECHA, @COPAGOPROPIO = COALESCE(COPAGOPROPIO,0), @SOAT = ISNULL(SOAT,0)
    FROM   AUT
    WHERE  AUT.IDAUT = @IDAUT

    SELECT @TIPOAFILIADO = TIPOAFILIADO, @GRUPOETNICO  = GRUPOETNICO,  
            @EDAD =  DATEDIFF(DAY, FNACIMIENTO, GETDATE())/365.25,
            @NIVELSOCIOEC = NIVELSOCIOEC, @FNACIM = FNACIMIENTO
    FROM   AFI 
    WHERE  IDAFILIADO = @IDAFILIADO
   
    SELECT @IDTERCEROCAD = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'CEHOSPENTEGUB'

    IF @PROCEDENCIA = 'CE'
    BEGIN  
	    PRINT 'INGRESE'
      
	    INSERT INTO @AUTD (NO_ITEM, IDSERVICIO)
        SELECT  NO_ITEM, IDSERVICIO FROM AUTD WHERE IDAUT = @IDAUT
      
	    SELECT @FIX=1, @FIX_TO=COUNT(1) FROM @AUTD

        WHILE @FIX <= @FIX_TO
        BEGIN
		SELECT @NO_ITEM=NO_ITEM, @IDSERVICIO=IDSERVICIO FROM @AUTD WHERE ID=@FIX

            SELECT @IDADMINISTRADORA = IDTERCEROCA, @IDPLAN = IDPLAN, @IDTERCEROCA = IDTERCEROCA, @IDAREA = ISNULL(IDAREA,@IDAREA),
                @AQUIENCOBRO      = AQUIENCOBRO
            FROM   AUTD  LEFT JOIN CEN ON AUTD.CCOSTO=CEN.CCOSTO
            WHERE  IDAUT   = @IDAUT
            AND    NO_ITEM = @NO_ITEM          

            IF @IDPLAN = @IDCJPLANEXTERNO
                SELECT @VLRSERVICIO = DBO.FNK_VLRAUTORIZACION(@IDAUT, @NO_ITEM, @IDCJTERCEROEXTERNO, @IDPLAN, @IDAREA, @FECHAAUT) 
            ELSE
                SELECT @VLRSERVICIO = DBO.FNK_VLRAUTORIZACION(@IDAUT, @NO_ITEM, @IDADMINISTRADORA, @IDPLAN, @IDAREA, @FECHAAUT) 

            SELECT @VALORTOTALCOSTO = VLRCXP 
            FROM   VW_NOMBAS1 
            WHERE  IDPROVEEDOR = @IDPROVEEDOR
                            AND IDADMINISTRADORA = @IDADMINISTRADORA
                            AND IDPLAN           = @IDPLAN 
                            AND IDSERVICIO       = @IDSERVICIO
                            AND @FECHAAUT BETWEEN FECHAINIADM AND FECHAFINADM
                            AND @FECHAAUT BETWEEN FECHAINIPRO AND FECHAFINPRO
                            AND @FECHAAUT BETWEEN FECHAINIADMSER AND FECHAFINADMSER
                            AND @FECHAAUT BETWEEN FECHAINIPROSER AND FECHAFINPROSER
                            AND IDAREACA   = @IDAREA                        

            UPDATE AUTD SET VALOR = @VLRSERVICIO, VALORTOTALCOSTO = @VALORTOTALCOSTO, VALORPROV = @VALORTOTALCOSTO
				    ,AUTORIZADO = CASE 
							WHEN COALESCE(VALORCOPAGO,0) = 0 THEN 1
							ELSE AUTORIZADO
							END
            WHERE  IDAUT   = @IDAUT 
            AND    NO_ITEM = @NO_ITEM
            SELECT @VALORTOTAL1 = (AUTD.CANTIDAD * AUTD.VALOR) FROM AUTD WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM
            
            EXEC SPK_COPAGO_AUT_CEHOSP @IDAFILIADO,@IDAUT,@NO_ITEM,@IDSERVICIO,@PYP,@ALTOCOSTO,@VALORTOTALCOSTO,'CE',@SYS_COMPUTERNAME, @COMPANIA,@IDSEDE,@USUARIO,@IDPROVEEDOR,@IDAREA,@FECHAAUT,@COPAGOPROPIO,@SOAT
			
            SET @FIX += 1
        END --Termino While @AUTD
        DECLARE @VRTOTCOPAGO DECIMAL(14,2)
		IF (SELECT COALESCE(COPAGOPROPIO,0) FROM AUT WHERE IDAUT = @IDAUT) = 0
		BEGIN
			IF (SELECT SUM(VALORCOPAGO) FROM AUTD WHERE AUTD.IDAUT = @IDAUT)>0
			BEGIN
				IF (SELECT VALORCOPAGO FROM AUTD WHERE AUTD.IDAUT =  @IDAUT AND MARCACOPAGOORDEN = 1  ) >0
				BEGIN
					SELECT @VRTOTCOPAGO = VALORCOPAGO FROM AUTD WHERE AUTD.IDAUT =  @IDAUT AND MARCACOPAGOORDEN = 1
					UPDATE AUT SET VALORCOPAGO = @VRTOTCOPAGO , TIPOCOPAGO = 'M' WHERE IDAUT = @IDAUT
				END
				ELSE
				BEGIN
					SELECT @VRTOTCOPAGO = SUM(VALORCOPAGO) FROM AUTD WHERE AUTD.IDAUT = @IDAUT
					UPDATE AUT SET VALORCOPAGO = @VRTOTCOPAGO , TIPOCOPAGO = 'C' WHERE IDAUT = @IDAUT
				END
			END
			ELSE
			BEGIN
				UPDATE AUT SET VALORCOPAGO = 0 , TIPOCOPAGO = 'N', GENEROCAJA=0 WHERE IDAUT = @IDAUT 
			END
		END
		EXEC SPK_TOTALESAUT_CJN @IDAUT
    END
END

