IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_RETIRA_FACTURA_CONCI' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_RETIRA_FACTURA_CONCI
END
GO
CREATE PROCEDURE DBO.SPK_RETIRA_FACTURA_CONCI 
@IDFCONCI        VARCHAR(20),
@ITEM            INT,
@COMPANIA        VARCHAR(2),
@SEDE          VARCHAR(6),
@USUARIO       VARCHAR(20),
@SYS_COMPUTERNAME VARCHAR(255)
AS
DECLARE @CNSCXC      VARCHAR (12),      @N_FACTURA   VARCHAR(20),    @IDTERCERO    VARCHAR(16),       @ITEMFCXCDV    INT
DECLARE @TIPO        VARCHAR(2),        @VLRACEPTADO DECIMAL(18,2),  @VLRRECUPERAR DECIMAL (18,2),    @CNSFNOT       VARCHAR (20)
DECLARE @CNSGLO      VARCHAR (12),      @OBSERVACION VARCHAR (4000), @IDNOTA       VARCHAR (5),       @CONCEPTO      VARCHAR (512)
DECLARE @F_RECIBIDO  DATETIME,       @F_VENCE      DATETIME,          @CNSRPDX       VARCHAR(20)
DECLARE @GNOT        SMALLINT,          @SALDONETO   DECIMAL (14,2), @ITEM_FCONCID INT,               @FECHACONCILIA DATETIME
DECLARE @CODCONCEPTO VARCHAR(20),       @FNOT_FECHACONCILIA VARCHAR(20)
DECLARE @PROCENCIA   VARCHAR(20),       @CERRAR      BIT=1
DECLARE @HOY         DATETIME, @CNSFNOTDB  VARCHAR(20)
BEGIN
   SELECT @CNSCXC=CNSCXC,
   @N_FACTURA=N_FACTURA,
   @ITEMFCXCDV=ITEM_FCXCDV,
   @TIPO=TIPO,
   @ITEM_FCONCID=ITEM_FCONCID,
   @VLRACEPTADO=VLRACEPTADO,
   @VLRRECUPERAR=VLRRECUPERAR,
   @CNSGLO=CNSGLO,
   @OBSERVACION=OBSERVACION,
   @SALDONETO=SALDONETO,
   @CODCONCEPTO=CONDCONCEPTO,
   @CNSFNOT=CNSFNOT,
   @CNSFNOTDB=CNSNOTADB
   FROM FCONCID 
   WHERE IDFCONCI=@IDFCONCI AND ITEM_FCONCID=@ITEM
   
   IF @VLRACEPTADO>0
   BEGIN 
      SELECT @IDNOTA=DBO.FNK_VALORVARIABLE('IDCOPNOTACONCI')
      SELECT @CONCEPTO=DESCRIPCION FROM CPNT WHERE CODIGO=@IDNOTA
      SELECT @IDTERCERO=IDTERCERO,@HOY=GETDATE() FROM FTR WHERE N_FACTURA=@N_FACTURA
      SELECT @GNOT = 1
      IF COALESCE(@CODCONCEPTO,'')=''
         SET @CODCONCEPTO=@IDNOTA
               
      IF COALESCE(@CNSFNOTDB,'')=''
      BEGIN
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FNOTD', @CNSFNOT OUTPUT  
         SELECT @CNSFNOTDB = @SEDE+'D'+REPLACE(SPACE(8 - LEN(@CNSFNOT))+LTRIM(RTRIM(@CNSFNOT)),SPACE(1),0)      
      END
               
      --SE INSERTAN LOS DATOS DE LA NOTA DESDE LA CONCILIACION
      PRINT 'NUMERO DE LA NOTA......'+ @CNSFNOTDB
      IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOTDB AND ESTADO<>'A')
      BEGIN 
         INSERT INTO FNOT(CNSFNOT, CLASE, N_FACTURA, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                           MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA,
                           USUARIO, CNSCXC, CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU,
                           RAZONANU, PROCEDENCIA, CNSGLO, APLICADAA,LIBERAHADM, 
                           CONCEPTO, IDCONCEPTO,VALORCONCEPTO )  
         SELECT @CNSFNOTDB, 'D', @N_FACTURA, @IDTERCERO, @HOY, @VLRACEPTADO, @OBSERVACION,
                0, 0, 0, NULL, 0, @COMPANIA, @USUARIO, @CNSCXC, 0, 'O', NULL, NULL, NULL, NULL,
                  'CONCILIA', @CNSGLO, 'D', 0, 0, ISNULL(@CODCONCEPTO,@IDNOTA),@VLRACEPTADO
            
         INSERT INTO FNOTD(CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
                           VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION)
         SELECT @CNSFNOTDB, 'D', 1, 'D',COALESCE(@CODCONCEPTO,@IDNOTA) , @CONCEPTO, 1,
                  @VLRACEPTADO, @VLRACEPTADO, @COMPANIA, @USUARIO, LEFT(@OBSERVACION,500)
         END
      UPDATE FCONCID SET CNSNOTADB=@CNSFNOTDB WHERE IDFCONCI=@IDFCONCI AND ITEM_FCONCID=@ITEM_FCONCID
      SET @CNSRPDX = 'INTERNO'
      EXEC SPK_NOTASCXC @CNSFNOTDB, 'D', @CNSRPDX , @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME
   END   
   IF @VLRRECUPERAR>0
   BEGIN
      DELETE FCXCDV WHERE IDFCONCI=@IDFCONCI AND SALDOINICIAL=@VLRRECUPERAR

      EXEC SPK_RELIQUIDA_FTR @CNSCXC, @N_FACTURA

      EXEC SPK_NC_CONTAB_ANULA_CONCI @IDFCONCI,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,'',@ITEM_FCONCID

   END
   UPDATE FCONCID SET ESTADO='Anulada'  WHERE IDFCONCI=@IDFCONCI AND ITEM_FCONCID=@ITEM_FCONCID
END

