CREATE OR ALTER PROCEDURE DBO.SPK_NC_CONTAB_CXC 
@CNSFPAG          VARCHAR(20), 
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA         VARCHAR(2), 
@SEDE             VARCHAR(5),
@NROCOMPROBANTE   VARCHAR(20)
WITH ENCRYPTION
AS 
DECLARE @COM              VARCHAR(6)
DECLARE @NOREFERENCIA     VARCHAR(20)
DECLARE @ANO              VARCHAR(4)
DECLARE @MES              INT
DECLARE @IDMODELOCONT	  VARCHAR(2)
DECLARE @IDPLAN		     VARCHAR(6) 
DECLARE @TIPOTERCONTABLE  VARCHAR(10) 
DECLARE @VALORGLOSAS	     DECIMAL(14,2)
DECLARE @VALORIMPUESTOS	  DECIMAL(14,2)
DECLARE @VLR_DTO_IND  	  DECIMAL(14,2)
DECLARE @PREFIJO_USCXS    VARCHAR(10)
DECLARE @INGRESO          VARCHAR(10)
DECLARE @VLRAJUSTEPESO    DECIMAL(14,2)
DECLARE @VLRDTOFINAN      DECIMAL(14,2)
DECLARE @FECHATRA         DATETIME
DECLARE @CUE_OFIN		  VARCHAR(16), @PCJ_CUENTA VARCHAR(20) 
DECLARE @NROCOMPRORI      VARCHAR(20)
DECLARE @VLRMAXAJUSTERECAUDOS DECIMAL(14,2)
BEGIN
   SELECT * INTO #FP FROM FPAG WHERE CNSFPAG=@CNSFPAG
   SELECT * INTO #FPD FROM FPAGD WHERE CNSFPAG=@CNSFPAG
   
   SELECT   @ANO            = YEAR(FECHA),
            @MES            = MONTH(FECHA),
            @VALORIMPUESTOS = VLRIMPUESTOS,
            @VALORGLOSAS    = VLRGLOSAS,
            @VLRAJUSTEPESO  = VLRAJUSTEPESO,
            @VLRDTOFINAN    = VLRDTOFINAN,
            @INGRESO        = INGRESO,
            @FECHATRA       = FECHA
   FROM #FP
   SELECT @VLRMAXAJUSTERECAUDOS = COALESCE(
         TRY_CAST(DBO.FNK_VALORVARIABLE('VLRMAXAJUSTERECAUDOS') AS DECIMAL(14,2)), 
         0
   );
   SELECT @VLR_DTO_IND=SUM(ABS(COALESCE(VLROTROSDCTOS,0)))
   FROM #FPD
   WHERE COALESCE(VLROTROSDCTOS,0)<=@VLRMAXAJUSTERECAUDOS

   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)
   BEGIN
      Print 'Período Contable No Existe'
      RAISERROR('Período Contable No Existe',16,1)
      RETURN
   END  
   IF (SELECT CERRADO FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES) = 1
   BEGIN
      Print 'Período Contable Cerrado'
      RAISERROR('Período Contable Cerrado',16,1)
      RETURN
   END
   
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
   PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   IF ISNULL(@NROCOMPROBANTE,'') = '' -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   BEGIN
      SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD     
      SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD 
      IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
      BEGIN
         IF @INGRESO='GLOSAS'
         BEGIN
            SELECT @COM = RTRIM(LTRIM(COMMS.COMPROBANTE)) FROM COMMS WHERE IDSEDE = @SEDE AND COMMS.CLASE = 'CXC' AND TIPO = 'GLOSAS'
         END
         ELSE
         BEGIN
            SELECT @COM = RTRIM(LTRIM(COMMS.COMPROBANTE)) FROM COMMS WHERE IDSEDE = @SEDE AND COMMS.CLASE = 'CXC' AND TIPO = 'OTRAS'
         END
      END
      ELSE
      BEGIN
         IF @INGRESO='GLOSAS'
         BEGIN
            SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_CXC_GLOSA')))
         END
         ELSE 
         BEGIN
            IF @INGRESO='DEVOLUCION' AND COALESCE ( LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_CXC_DEVO'))),'')<>''
            BEGIN 
               SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_CXC_DEVO')))
            END 
            ELSE 
            BEGIN 
               SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_CXC')))
            END 
         END
      END
           
      SET @PREFIJO_USCXS='@COM'+@COM
      SET @NOREFERENCIA=SPACE(20)
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
      SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
      PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
         
      PRINT 'Comprobanrte Contable (MCP)'
      INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                       TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                       COMPROBANTE, IDTERCERO)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'CXC', @NOREFERENCIA, @ANO, @MES, CAST(STR(DAY(FECHA))+'/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME),
              0, 0, CNSFPAG, '', @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, 
              'RECAUDOS DE CUENTAS POR COBRAR', @SEDE, 0, @COM, (CASE WHEN #FP.IDTERCERO IS NULL THEN '' ELSE #FP.IDTERCERO END)
      FROM #FP  
   END  
   IF (SELECT COUNT(*) FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)>0
   BEGIN
      INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
      SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
      FROM   MCP
      WHERE  NROCOMPROBANTE = @NROCOMPROBANTE
      --se borran de mcp, mch
      DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
      DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE   
   END
   DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   IF EXISTS(SELECT * FROM MCPE WHERE LOTE='REV' AND NROCOMPROBANTE=@NROCOMPROBANTE)
   BEGIN
     PRINT 'Es una Reversion de Recuados... Busco el Original...'
     SELECT @NROCOMPRORI=REFERENCIA3 FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
     --SELECT DBO.FNK_COLUMNAS_TABLAS('MCHE')
     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, 
                 USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
                 ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP)
      SELECT @NROCOMPROBANTE, COMPANIA,CASE WHEN TIPO='DB' THEN 'CR' ELSE 'DB' END, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, 
             USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
             ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP
      FROM MCH 
      WHERE NROCOMPROBANTE=@NROCOMPRORI

      EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME 
      EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''

      PRINT 'Termino y me Regreso'
      RETURN
   END
   IF @INGRESO='CAJA'
   BEGIN
      PRINT 'Caja...'
      IF EXISTS(SELECT COMPANIA FROM PAR WHERE COMPANIA=@COMPANIA)
      BEGIN
         PRINT ' -Insertando MCH (Con COMPAÑIA en PAR)'
         DECLARE @CODCAJA VARCHAR(10)
         DECLARE @CNSFACJ VARCHAR(20)
         SELECT @CODCAJA=CODCAJA,@CNSFACJ=CNSFACJ FROM #FP
		   SELECT @PCJ_CUENTA = CASE WHEN COALESCE(PCJ.CUENTA,'') = '' THEN COALESCE(FPA.CUENTA,'') ELSE PCJ.CUENTA END
         FROM   #FP LEFT JOIN PCJ ON PCJ.CNSFACJ=#FP.CNSFACJ AND PCJ.CODCAJA=#FP.CODCAJA
					LEFT JOIN FPA ON FPA.FORMAPAGO=PCJ.TIPOPAGO
         PRINT 'VALIDO EL ASIENTO CONTABLE'
         IF EXISTS(SELECT * FROM FCJ WHERE COALESCE(N_FACTURAPOS,'')<>'' AND CNSFACJ=@CNSFACJ AND CODCAJA=@CODCAJA)
         BEGIN
            SELECT @PCJ_CUENTA=CUENTA  FROM KCDE WHERE TIPO='FTR_COPAGOS'
         END
         INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
 	                   REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA, 
                     N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
         SELECT @NROCOMPROBANTE, @COMPANIA,'DB', CASE WHEN UPPER(DBO.FNK_VALORVARIABLE('USARCUEPUENTE'))='SI' THEN 
                                                   PAR.CTA_CAJ_REC_NOLEG ELSE @PCJ_CUENTA END,
                #FP.IDTERCERO, '' AS CCOSTO, 'DEPOSITO DE CLIENTES EN CAJA, CNSPAGO No. '+#FP.CNSFPAG,
 	            CASE WHEN UPPER(DBO.FNK_VALORVARIABLE('CUE_IMP_RECAUDOS'))='SI' THEN (COALESCE(#FP.VLRITEMS,0) - @VALORIMPUESTOS) 
 	                 ELSE CASE WHEN  #FP.VLRAJUSTEPESO<>0 THEN  COALESCE(#FP.VALORPAGO,0) ELSE  COALESCE(#FP.VLRITEMS,0) END
 	            END,'',NULL,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL,
 	            '' AS IDAREA, 'S' AS CLASECONT, 1, 'DEP_CLIENTES', 'Movimiento', RTRIM(#FP.CODCAJA)+#FP.CNSFACJ,
                DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 'CXC', @CNSFPAG,
                FCJ.CODUNG, FCJ.CODPRG
         FROM #FP LEFT JOIN
              FCJ ON FCJ.CNSFACJ=#FP.CNSFACJ AND FCJ.CODCAJA=#FP.CODCAJA, PAR
         WHERE PAR.COMPANIA=@COMPANIA AND #FP.VLRTOTAL>0  
      END
      ELSE
      BEGIN 
         PRINT ' -Insertando Registro MCH Con Error... (No se encontró un COMPA?IA en PAR)'
         INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
 	                       REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA, 
                         N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO)
         SELECT @NROCOMPROBANTE,@COMPANIA,'DB','NO DEF.PAR',#FP.IDTERCERO,'' AS CCOSTO,
               'DEPOSITO DE CLIENTES EN CAJA, CNSPAGO No. '+#FP.CNSFPAG,
               #FP.VALORPAGO,'',NULL,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,
               '' AS IDAREA, 'S' AS CLASECONT, 1, 'DEP_CLIENTES', 'Movimiento',RTRIM(#FP.CODCAJA)+#FP.CNSFACJ,
               (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CNSFACJ=#FP.CNSFACJ AND CODCAJA=#FP.CODCAJA),
               (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CNSFACJ=#FP.CNSFACJ AND CODCAJA=#FP.CODCAJA),
	              'CXC',@CNSFPAG
         FROM #FP WHERE #FP.VLRTOTAL>0
      END
   END
   ELSE
   IF @INGRESO='BANCOS'
   BEGIN
      PRINT 'Bancos...'
      PRINT ' -Insertando MCH (Bancos)'
      
      -- ADD. JQUIROGA 20090421
      SELECT @CUE_OFIN = OFIN.CUENTA 
      FROM   #FP INNER JOIN BMOV ON BMOV.BANCO    = #FP.BANCO 
                                  AND BMOV.SUCURSAL = #FP.SUCURSAL 
                                  AND BMOV.CTA_BCO  = #FP.CTA_BCO 
                                  AND BMOV.ITEM     = #FP.ITEM
	               INNER JOIN OFIN ON OFIN.IDOPERACION = BMOV.IDOPERACION
      
      -- MOD. JQUIROGA 20090421
      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                      REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,
                      PROCESO,GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
      SELECT @NROCOMPROBANTE,@COMPANIA,'DB',
	          CASE 
			             WHEN UPPER(DBO.FNK_VALORVARIABLE('USARCUEPUENTE'))     = 'SI'  THEN PAR.CTA_CAJ_REC_NOLEG 
				          WHEN UPPER(DBO.FNK_VALORVARIABLE('CUEOFIN_CONTABCXC')) = 'SI' THEN @CUE_OFIN 
				          ELSE BMOVD.CUENTA 
             END,
             #FP.IDTERCERO,'' AS CCOSTO, 
             'DEPOSITO EN BANCO, CH '+(CASE WHEN #FP.NUMERODOCUMENTO IS NULL THEN '' ELSE #FP.NUMERODOCUMENTO END)+', '+
             ISNULL(#FP.BANCO,'')+' '+UPPER(CASE WHEN UPPER(DBO.FNK_VALORVARIABLE('USARCUEPUENTE'))='SI' THEN CUE.NOMCUENTA 
                                              ELSE CUE2.NOMCUENTA 
                                         END)+', RECAUDO No.'+#FP.CNSFPAG +'SEGUN COMPROBANTE: '+MCP.COMPROBANTE+' CNS: '+
                                         MCP.NOREFERENCIA+' FECHA: '+DBO.FNK_FECHA(MCP.FECHACONTABLE),
 	      CASE WHEN UPPER(DBO.FNK_VALORVARIABLE('CUE_IMP_RECAUDOS'))='SI' THEN  CASE WHEN   #FP.VLRAJUSTEPESO<>0 THEN  (COALESCE(#FP.VALORPAGO,0)) -COALESCE(@VLR_DTO_IND,0)
																						---VLRAJUSTEPESO
																						ELSE   (COALESCE(#FP.VLRITEMS,0))-COALESCE(@VLR_DTO_IND,0) END 
																						--+ ABS(VLRAJUSTEPESO)
 	               ELSE CASE WHEN  #FP.VLRAJUSTEPESO<>0 THEN  COALESCE(#FP.VALORPAGO,0)  -COALESCE(@VLR_DTO_IND,0)ELSE  COALESCE(#FP.VLRITEMS,0)-COALESCE(@VLR_DTO_IND,0) END
 	          END, /* JREYES FECHA: 20090512 REQ: 0100001332*/
             #FP.BANCO,#FP.SUCURSAL,#FP.NUMERODOCUMENTO,NULL,@USUARIO,
             DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL, '' AS IDAREA, 'S' AS CLASECONT, 1, 'DEP_CLIENTES_BANCO', 'Movimiento', 
             'CXC', @CNSFPAG, BMOV.CODUNG, BMOV.CODPRG
      FROM   #FP LEFT JOIN PAR   ON #FP.CNSFPAG     = #FP.CNSFPAG 
              LEFT JOIN CUE   ON CUE.CUENTA     = PAR.CTA_CAJ_REC_NOLEG 
                             AND CUE.COMPANIA   = PAR.COMPANIA 
              LEFT JOIN BMOVD ON BMOVD.BANCO    = #FP.BANCO 
                             AND BMOVD.SUCURSAL = #FP.SUCURSAL 
                             AND BMOVD.CTA_BCO  = #FP.CTA_BCO 
                             AND BMOVD.ITEM     = #FP.ITEM 
                             AND BMOVD.RENGLON  = #FP.RENGLON 
              LEFT JOIN BMOV  ON BMOV.BANCO     = #FP.BANCO 
                             AND BMOV.SUCURSAL  = #FP.SUCURSAL 
                             AND BMOV.CTA_BCO   = #FP.CTA_BCO 
                             AND BMOV.ITEM      = #FP.ITEM 
              LEFT JOIN CUE CUE2 ON BMOVD.CUENTA = CUE2.CUENTA
              LEFT JOIN MCP ON BMOV.NROCOMPROBANTE=MCP.NROCOMPROBANTE  
      WHERE  #FP.VLRTOTAL  > 0 
      AND    PAR.COMPANIA = @COMPANIA 
   END 
   ELSE 
   IF @INGRESO='CXP'
   BEGIN
      PRINT 'Ingreso por CXP.'
      PRINT ' -Insertando MCH (CXP)'
      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                       REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,
                       PROCESO,GENERA,CNSPAGO,N_FACTURA,F_FACTURAREF,F_VENCE,PROCEDENCIA,REFERENCIA_PRO,
                       CODUNG, CODPRG) 
      SELECT @NROCOMPROBANTE,@COMPANIA,'DB',FCXP.CUECREDITO,FCXP.IDTERCERO,'' AS CCOSTO,
             'CRUCE CXP FA: '+FPAGDCXP.NOREFERENCIA+', RECAUDO No.'+#FP.CNSFPAG,
             FPAGDCXP.VLRCRUCE,FPAGDCXP.NOREFERENCIA,FPAGDCXP.CNSFCXP,'',NULL,@USUARIO,
             DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,'' AS IDAREA, 'S' AS CLASECONT, 1, 'CRUCE_CXP', 'Movimiento',
             FPAGDCXP.CNSFPAG,FPAGDCXP.NOREFERENCIA,DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF),
             DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE),'CXC', @CNSFPAG, FCXP.CODUNG, FCXP.CODPRG
      FROM #FP, FPAGDCXP, FCXP  
      WHERE #FP.VLRTOTAL>0 AND #FP.CNSFPAG=FPAGDCXP.CNSFPAG AND FPAGDCXP.CNSFCXP=FCXP.CNSFCXP
   END
   ELSE
   IF @INGRESO='CONTAB'
   BEGIN
      PRINT 'Ingreso por Contabilidad'
   END
   ELSE
   IF @INGRESO='GLOSAS'
   BEGIN
      PRINT 'Glosas...?'
   END
   IF @INGRESO='DEVOLUCION'
   BEGIN 
      PRINT'DEVOLUCIONES'    
      INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                      REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                      CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', ISNULL(TTEC.CUENTA,'NO DEF.TTEC'),  
             #FP.IDTERCERO,'' AS CCOSTO,LEFT('DEVOLUCION  FACTURA: '+#FPD.N_FACTURA+CASE WHEN COALESCE(#FPD.OBSERVACION,'')<>'' THEN ' RAZON O MOTIVO:'+COALESCE(#FPD.OBSERVACION,'') ELSE '' END,511),
			 SUM(#FPD.VLRGLOSA), NULL, NULL, NULL, @USUARIO, 
             DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
             'CXC_DEVOLUCION', 'Movimiento','S', #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
             DBO.FNK_FECHA_SIN_HORA(#FP.FECHA),'CXC',@CNSFPAG, #FPD.CODUNG, #FPD.CODPRG
      FROM #FP INNER JOIN #FPD  ON #FP.CNSFPAG    = #FPD.CNSFPAG 
              LEFT JOIN FTR  ON #FPD.N_FACTURA = FTR.N_FACTURA 
              LEFT JOIN TTEC ON TTEC.TIPO     = FTR.TIPOTTEC 
      WHERE #FPD.VLRGLOSA>0
      GROUP BY TTEC.CUENTA, #FP.IDTERCERO, #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
              #FPD.CODUNG, #FPD.CODPRG,COALESCE(#FPD.OBSERVACION,'')
              
      PRINT 'INSERTANDO CREDITOS' 
      
      INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                      REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                      CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', ISNULL(TTEC.CUENTARAD,'NO DEF.TTEC'),  
             #FP.IDTERCERO,'' AS CCOSTO, 'DEVOLUCION  FACTURA '+#FPD.N_FACTURA, SUM(#FPD.VLRGLOSA), NULL, NULL, NULL, @USUARIO, 
             DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
             'CXC_DEVOLUCION', 'Movimiento','S', #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
             DBO.FNK_FECHA_SIN_HORA(#FP.FECHA),'CXC',@CNSFPAG, #FPD.CODUNG, #FPD.CODPRG
      FROM #FP INNER JOIN #FPD  ON #FP.CNSFPAG    = #FPD.CNSFPAG 
              LEFT JOIN FTR  ON #FPD.N_FACTURA = FTR.N_FACTURA 
              LEFT JOIN TTEC ON TTEC.TIPO     = FTR.TIPOTTEC 
      WHERE #FPD.VLRGLOSA>0
      GROUP BY TTEC.CUENTARAD, #FP.IDTERCERO, #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
              #FPD.CODUNG, #FPD.CODPRG   
      PRINT 'Poniendo Estado de CONTABILIZADA en La Tabla FPAG'
      
      --EXEC SPK_REVISAR_COMPROBANTE @COMPANIA,@NROCOMPROBANTE
      EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME 
      -- EXEC SPK_SUMA_DBCR @NROCOMPROBANTE
      
      DROP TABLE #FP
      DROP TABLE #FPD   
      
      RETURN                               
   END
   
   PRINT 'Contabilizando Impuestos...' 
   IF @VALORIMPUESTOS>0
   BEGIN 
      INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                       REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                       CLASECONT, VALOR_PORCIMP, BASE_IMP, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, 
                       CODUNG, CODPRG)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',
             COALESCE(NULLIF(LTRIM(RTRIM(FIMPDV.CUENTA)), ''), N'NO DEF.FIMPDV'),
             #FP.IDTERCERO, '' AS CCOSTO,
             CASE
                 WHEN FIMPDV.CUENTA IS NULL OR LTRIM(RTRIM(FIMPDV.CUENTA)) = '' THEN
                      N'IMP SIN FIMPDV ' + COALESCE(FPAGDI.IDIMPUESTO, N'?')
                      + N' CLASE ' + COALESCE(FPAGDI.IDCLASE, N'?')
                      + N' FA ' + #FPD.N_FACTURA
                 ELSE N'IMP POR ' + FIMPDV.IDIMPUESTO + N' CLASE ' + FIMPDV.IDCLASE + N' FA ' + #FPD.N_FACTURA
             END,
             SUM(FPAGDI.VLRIMPUESTO),
             COALESCE(FIMPDV.IDIMPUESTO, FPAGDI.IDIMPUESTO),
             COALESCE(FIMPDV.IDCLASE, FPAGDI.IDCLASE),
             COALESCE(FIMPDV.ITEM, FPAGDI.ITEMFIMPDV),
             NULL, @USUARIO,
             DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_IMPUESTOS',
            'Movimiento','S', FIMPDV.VALOR, FPAGDI.BASE, #FPD.N_FACTURA,
            DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 'CXC', @CNSFPAG, #FPD.CODUNG, #FPD.CODPRG
      FROM   #FP, #FPD INNER JOIN FPAGDI ON #FPD.CNSFPAG       = FPAGDI.CNSFPAG 
                                    AND #FPD.N_FACTURA     = FPAGDI.N_FACTURA 
                                    AND #FPD.ITEM          = FPAGDI.ITEM 
                    LEFT JOIN FIMPDV ON FPAGDI.IDIMPUESTO = FIMPDV.IDIMPUESTO 
                                    AND FPAGDI.IDCLASE    = FIMPDV.IDCLASE 
                                    AND FIMPDV.ITEM       = FPAGDI.ITEMFIMPDV
      WHERE  FPAGDI.VLRIMPUESTO > 0   
      GROUP BY COALESCE(NULLIF(LTRIM(RTRIM(FIMPDV.CUENTA)), ''), N'NO DEF.FIMPDV'),
             FIMPDV.CUENTA, IDTERCERO, #FPD.N_FACTURA, #FP.IDTERCERO, #FPD.N_FACTURA,
             FIMPDV.IDIMPUESTO, FIMPDV.IDCLASE, FIMPDV.ITEM, FIMPDV.VALOR, FPAGDI.BASE,
             FPAGDI.IDIMPUESTO, FPAGDI.IDCLASE, FPAGDI.ITEMFIMPDV,
             DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), #FPD.CODUNG, #FPD.CODPRG
   END
   
   IF @VALORGLOSAS>0 AND @INGRESO<>'DEVOLUCION'
   BEGIN 
      IF (SELECT MCUEORDEN_GLOSAS FROM PAR WHERE COMPANIA=@COMPANIA)='Si'
      BEGIN
         PRINT 'Contabilizando DB Glosas con Cuentas de Orden...' 
         INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                         REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                         CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
         SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', ISNULL(TTEC.CUEORDENGLOSADB,''), 
                #FP.IDTERCERO,'' AS CCOSTO, 'CUENTA DE ORDEN POR GLOSAS DE FA '+#FPD.N_FACTURA, SUM(#FPD.VLRGLOSA), #FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM))) , @USUARIO, 
                DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                'CUEORDENGLOSADB', 'Movimiento','S', #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
                DBO.FNK_FECHA_SIN_HORA(#FP.FECHA),'CXC',@CNSFPAG, #FPD.CODUNG, #FPD.CODPRG
         FROM  #FP INNER JOIN #FPD  ON #FP.CNSFPAG    = #FPD.CNSFPAG 
               LEFT JOIN FTR  ON #FPD.N_FACTURA = FTR.N_FACTURA 
               LEFT JOIN TTEC ON TTEC.TIPO     = FTR.TIPOTTEC /*LEFT JOIN
               PPT ON PPT.IDTERCERO = #FP.IDTERCERO AND PPT.IDPLAN = #FPD.IDPLAN LEFT JOIN
               TTEC TTEC2 ON PPT.TIPOTERCONTABLE = TTEC2.TIPO*/
         WHERE #FPD.VLRGLOSA>0
         GROUP BY TTEC.CUEORDENGLOSADB, #FP.IDTERCERO, #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
                 #FPD.CODUNG, #FPD.CODPRG,#FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM)))     
               
         PRINT 'Contabilizando CR Glosas con Cuentas de Orden...' 
         INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                         REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                         CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
         SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', ISNULL(TTEC.CUEORDENGLOSACR,''), 
                #FP.IDTERCERO,'' AS CCOSTO, 'CUENTA DE ORDEN POR GLOSAS DE FA '+#FPD.N_FACTURA, SUM(#FPD.VLRGLOSA), #FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM))), @USUARIO, 
                DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                'CUEORDENGLOSACR', 'Movimiento','S', #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
                DBO.FNK_FECHA_SIN_HORA(#FP.FECHA),'CXC',@CNSFPAG, #FPD.CODUNG, #FPD.CODPRG
         FROM #FP  INNER JOIN #FPD  ON #FP.CNSFPAG    = #FPD.CNSFPAG 
                  LEFT JOIN FTR  ON #FPD.N_FACTURA = FTR.N_FACTURA 
                  LEFT JOIN TTEC ON TTEC.TIPO     = FTR.TIPOTTEC 
         WHERE #FPD.VLRGLOSA>0
         GROUP BY TTEC.CUEORDENGLOSACR, #FP.IDTERCERO, #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
                 #FPD.CODUNG, #FPD.CODPRG,#FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM)))    
      END
      ELSE
      BEGIN
         IF DBO.FNK_VALORVARIABLE('CONTGLOSA_PORTTEC') = 'SI'
         BEGIN
            PRINT 'Contabilizando Glosas... Por Tercero Contable (TTEC)' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                            CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', ISNULL(TTEC.CTAGLOSADB,'NO DEF.TTEC'),  
                   #FP.IDTERCERO,'' AS CCOSTO, LEFT(('GLOSAS DE FA '+#FPD.N_FACTURA+CASE WHEN COALESCE(#FPD.OBSERVACION,'')<>'' THEN ' RAZON O MOTIVO:'+COALESCE(#FPD.OBSERVACION,'') ELSE '' END),512),
				   SUM(#FPD.VLRGLOSA), #FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM))), @USUARIO, 
                   DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                   'CXC_GLOSAS', 'Movimiento','S', #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
                   DBO.FNK_FECHA_SIN_HORA(#FP.FECHA),'CXC',@CNSFPAG, #FPD.CODUNG, #FPD.CODPRG
            FROM #FP INNER JOIN #FPD  ON #FP.CNSFPAG    = #FPD.CNSFPAG 
                    LEFT JOIN FTR  ON #FPD.N_FACTURA = FTR.N_FACTURA 
                    LEFT JOIN TTEC ON TTEC.TIPO     = FTR.TIPOTTEC 
            WHERE #FPD.VLRGLOSA>0
            GROUP BY TTEC.CTAGLOSADB, #FP.IDTERCERO, #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
                    #FPD.CODUNG, #FPD.CODPRG,#FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM))),
					COALESCE(#FPD.OBSERVACION,'')   
         END
         ELSE
         BEGIN
            PRINT 'Contabilizando Glosas... Por Dedicible (KCDE)' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                            CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', CASE WHEN CUE.CUENTA IS NULL THEN 'NO DEF.KCDE' ELSE CUE.CUENTA END, 
                   IDTERCERO,'' AS CCOSTO, LEFT(('GLOSAS DE FA '+N_FACTURA+CASE WHEN COALESCE(#FPD.OBSERVACION,'')<>'' THEN ' RAZON O MOTIVO:'+COALESCE(#FPD.OBSERVACION,'') ELSE '' END),512),
				    SUM(#FPD.VLRGLOSA), #FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM))), @USUARIO, 
                   DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                  'CXC_GLOSAS', 'Movimiento','S', N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
                  DBO.FNK_FECHA_SIN_HORA(#FP.FECHA),'CXC',@CNSFPAG, #FPD.CODUNG, #FPD.CODPRG
            FROM #FP,#FPD LEFT JOIN KCDE ON KCDE.IDMODELOCONT = @IDMODELOCONT AND KCDE.TIPO='CXC_GLOSAS' 
                        LEFT JOIN CUE  ON KCDE.CUENTA       = CUE.CUENTA    AND CUE.COMPANIA=@COMPANIA
            WHERE #FPD.VLRGLOSA>0
            GROUP BY CUE.CUENTA, IDTERCERO, N_FACTURA,DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), #FPD.CODUNG, #FPD.CODPRG,#FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM))),
			COALESCE(#FPD.OBSERVACION,'')
         END
      END
   END
   --SELECT * FROM FPAGD
   IF @VLRDTOFINAN>0 
   BEGIN
      PRINT 'Descuento financiero...'
      INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                      REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                      CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('CTADTOFINANCIERO'),'')=''
                                               THEN 'NO DEF.DTOFIN' ELSE DBO.FNK_VALORVARIABLE('CTADTOFINANCIERO') END, 
             IDTERCERO,'' AS CCOSTO, 'DESCUENTO FINANANCIERO '+N_FACTURA, SUM(#FPD.VLRDTOFIN), NULL, NULL, NULL, @USUARIO, 
             DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
             'CXC_DTOFINAN', 'Movimiento','S', N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
             DBO.FNK_FECHA_SIN_HORA(#FP.FECHA),'CXC',@CNSFPAG, #FPD.CODUNG, #FPD.CODPRG
      FROM #FP,#FPD 
      WHERE #FPD.VLRDTOFIN>0
      GROUP BY IDTERCERO, N_FACTURA,DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), #FPD.CODUNG, #FPD.CODPRG    
   END
   IF COALESCE(@VLR_DTO_IND,0)>0
   BEGIN
     PRINT 'Descuentos En recuados...'
      INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                      REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                      CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('CTA_DTO_IND_RECA_CXC'),'')=''
                                               THEN 'NO DEF DTO_IND' ELSE DBO.FNK_VALORVARIABLE('CTA_DTO_IND_RECA_CXC') END, 
             IDTERCERO,'' AS CCOSTO, 'DESCUENTOS EN RECAUDOS DE FACTURA: '+N_FACTURA,SUM(ABS(COALESCE(#FPD.VLROTROSDCTOS,0))), NULL, NULL, NULL, @USUARIO, 
             DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
             'CXC_DTO_IND', 'Movimiento','S', N_FACTURA, DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), 
             DBO.FNK_FECHA_SIN_HORA(#FP.FECHA),'CXC',@CNSFPAG, #FPD.CODUNG, #FPD.CODPRG
      FROM #FP,#FPD 
      WHERE ABS(COALESCE(#FPD.VLROTROSDCTOS,0))>0
      GROUP BY IDTERCERO, N_FACTURA,DBO.FNK_FECHA_SIN_HORA(#FP.FECHA), #FPD.CODUNG, #FPD.CODPRG 
   END
   IF @VLRAJUSTEPESO>0
   BEGIN
      IF @VLRAJUSTEPESO <= convert(decimal(14,2), DBO.FNK_VALORVARIABLE('RECAU_VLLIMITE_APROV')) 
      BEGIN
         IF EXISTS(SELECT TIPO FROM KCDE WHERE TIPO='CXC_AJ_AFAVOR')
         BEGIN
            PRINT 'Contabilizando Ajuste al Peso a Favor...Aprov' 
            --EL VALOR AJUSTE AL PESO ESTA DENTRO DEL VALOR PARA SER CONSIDERADO APROVECHAMIENTO
            
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                             REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                             CLASECONT, PROCEDENCIA, REFERENCIA_PRO)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', KCDE.CUENTA, IDTERCERO,'' AS CCOSTO, 
	                  'AJUSTE AL PESO ', ABS(#FP.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
	                  '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_AFAVOR', 'Movimiento','S','CXC',@CNSFPAG
            FROM #FP,KCDE
            WHERE KCDE.IDMODELOCONT=@IDMODELOCONT AND KCDE.TIPO='CXC_AJ_AFAVOR' AND #FP.VLRAJUSTEPESO>0
         END
         ELSE
         BEGIN
            PRINT 'Contabilizando Ajueste con Error... (No Existe KCDE=CXC_AJ_AFAVOR)' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                            CLASECONT, PROCEDENCIA, REFERENCIA_PRO)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 'NO DEF.KCDE', IDTERCERO,'' AS CCOSTO, 
	                 'AJUSTE AL PESO ', ABS(#FP.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
	                 '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_AFAVOR', 'Movimiento','S','CXC',@CNSFPAG
            FROM #FP
            WHERE #FP.VLRAJUSTEPESO>0
         END
      END
      ELSE
      BEGIN --ESTA POR ENCIMA DEL LIMITE ENTONCES ES REINTEGRO POR PAGAR
         IF EXISTS(SELECT TIPO FROM KCDE WHERE TIPO='CXC_AJ_AFAVOR_REI')
         BEGIN
            PRINT 'Contabilizando Ajuste al Peso a Favor...Reintegro por Pagar' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                            CLASECONT, PROCEDENCIA, REFERENCIA_PRO)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', KCDE.CUENTA, IDTERCERO,'' AS CCOSTO, 
	                  'AJUSTE AL PESO ', ABS(#FP.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
	                  '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_AFAVOR_REI', 'Movimiento','S','CXC',@CNSFPAG
            FROM #FP,KCDE
            WHERE KCDE.IDMODELOCONT=@IDMODELOCONT AND KCDE.TIPO='CXC_AJ_AFAVOR_REI' AND #FP.VLRAJUSTEPESO>0
         END
         ELSE
         BEGIN
            PRINT 'Contabilizando Ajuste con Error... (No Existe KCDE=CXC_AJ_AFAVOR_REI)' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                             REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                             CLASECONT, PROCEDENCIA, REFERENCIA_PRO)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 'NO DEF.KCDE', IDTERCERO,'' AS CCOSTO, 
	                  'AJUSTE AL PESO ', ABS(#FP.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
	                  '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_AFAVOR_REI', 'Movimiento','S','CXC',@CNSFPAG
            FROM #FP,KCDE
            WHERE #FP.VLRAJUSTEPESO>0
         END
      END
   END
   IF @VLRAJUSTEPESO<0
   BEGIN
      IF EXISTS(SELECT TIPO FROM KCDE WHERE TIPO='CXC_AJ_ENCONTRA')
      BEGIN
         PRINT 'Contabilizando Ajuste al Peso En Contra...' 
         INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                         REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                         CLASECONT, PROCEDENCIA, REFERENCIA_PRO)
         SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', KCDE.CUENTA, IDTERCERO,'' AS CCOSTO, 
	        'AJUSTE AL PESO ', ABS(#FP.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
	        '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_ENCONTRA', 'Movimiento','S','CXC',@CNSFPAG
         FROM #FP,KCDE
         WHERE KCDE.IDMODELOCONT=@IDMODELOCONT AND KCDE.TIPO='CXC_AJ_ENCONTRA' AND #FP.VLRAJUSTEPESO<0
      END
      ELSE
      BEGIN
         PRINT 'Contabilizando Ajueste con Error... (No Existe KCDE=CXC_AJ_ENCONTRA)' 
         INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                         REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                         CLASECONT, PROCEDENCIA, REFERENCIA_PRO)
         SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 'NO DEF.KCDE', IDTERCERO,'' AS CCOSTO, 
	        'AJUSTE AL PESO ', ABS(#FP.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
	        '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_ENCONTRA', 'Movimiento','S','CXC',@CNSFPAG
         FROM #FP
         WHERE #FP.VLRAJUSTEPESO>0
      END
   END
   
   PRINT 'Contabilizando CR a la CxC del Cliente...' 
   
   -- MOD.JQUIROGA 20090523 - REQ.1641
   INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                 	 REFERENCIA2 ,ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO,ESTADO, PROCESO, GENERA, 
                   CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 
          CASE WHEN COALESCE(FTR.CASTIGADA,0)=1 AND TCOBRO='Castigo'  THEN DBO.FNK_VALORVARIABLE('CUENTA_CART_CASTI') 
               WHEN  COALESCE(FTR.CASTIGADA,0)=1 AND TCOBRO='Dificil' THEN (SELECT B.CUEDIFCOB FROM FTR A INNER JOIN TTEC B ON A.TIPOTTEC=B.TIPO
                                                                            WHERE A.N_FACTURA=#FPD.N_FACTURA)  ELSE
             CASE WHEN UPPER(DBO.FNK_VALORVARIABLE('CONTABCXC')) = 'NO' THEN
		                     CASE WHEN UPPER(DBO.FNK_VALORVARIABLE('MAN_CTAS_DE_MORA')) = 'SI' THEN 
			                              CASE WHEN DATEDIFF(DAY, FTR.F_VENCE, GETDATE()) <= 360 THEN
		                                         CASE WHEN FCXC.ANTIGUA = 1 THEN 
		                                                   CASE WHEN ISNULL(FCXCD.CUENTA,'')='' THEN
		                                                             ISNULL((SELECT CUENTA FROM TTEC, PPT 
		                                                                     WHERE TTEC.TIPO = PPT.TIPOTERCONTABLE AND PPT.IDPLAN=FCXCD.IDPLAN AND 
		                                                                     PPT.IDTERCERO=FCXC.IDTERCERO),'NO DEF.TTEC')
		                                                        ELSE
		                                                             FCXCD.CUENTA
		                                                    END
		                                              ELSE
		                                                   CASE WHEN ISNULL(FCXCD.CUENTA,'')='' THEN
		                                                         ISNULL(FTR.CUENTACXC,'NO DEF.FTR')
		                                                        ELSE
		                                                        FCXCD.CUENTA
		                                                   END
					                                      END	
				                                  WHEN DATEDIFF(DAY, FTR.F_VENCE, GETDATE()) BETWEEN 360 AND 720 THEN DBO.FNK_VALORVARIABLE('CTA_FPAG_360_a_720')
				                                  WHEN DATEDIFF(DAY, FTR.F_VENCE, GETDATE()) BETWEEN 721 AND 1440 THEN DBO.FNK_VALORVARIABLE('CTA_FPAG_721_a_1440')
				                                  WHEN DATEDIFF(DAY, FTR.F_VENCE, GETDATE()) >= 1441 THEN DBO.FNK_VALORVARIABLE('CTA_FPAG_1441_SUPERI')
				                                  ELSE
					                                 'NO DEF.'
			                              END
		                          ELSE
			                             CASE WHEN FCXC.ANTIGUA = 1 THEN 
				                                      CASE WHEN ISNULL(FCXCD.CUENTA,'')='' THEN
						                                              ISNULL((SELECT CUENTA FROM TTEC, PPT 
						                                              WHERE TTEC.TIPO = PPT.TIPOTERCONTABLE AND PPT.IDPLAN=FCXCD.IDPLAN AND 
									                                           PPT.IDTERCERO=FCXC.IDTERCERO),'NO DEF.TTEC')
					                                          ELSE
						                                             FCXCD.CUENTA
				                                       END
				                                 ELSE
				                                     CASE WHEN ISNULL(FCXCD.CUENTA,'')='' THEN
						                                              ISNULL(FTR.CUENTACXC,'NO DEF.FTR')
					                                          ELSE
						                                             FCXCD.CUENTA
				                                     END
		  	                               END
                       END
             ELSE  
                  CASE   WHEN #FPD.CLASE='F' THEN (
                                                   SELECT CASE WHEN @INGRESO='CAJA' AND PROCEDENCIA='CAJA' THEN B.CUENTA ELSE B.CUENTARAD END FROM FTR A INNER JOIN TTEC B ON A.TIPOTTEC=B.TIPO
                                                   WHERE A.N_FACTURA=#FPD.N_FACTURA
                                                   ) 
                          WHEN #FPD.CLASE='G' THEN (
                                                   SELECT B.CUENTALG FROM FTR A INNER JOIN TTEC B ON A.TIPOTTEC=B.TIPO
                                                   WHERE A.N_FACTURA=#FPD.N_FACTURA
                                                   ) 
                          WHEN #FPD.CLASE='R' THEN (
                                                   SELECT B.CUENTALG FROM FTR A INNER JOIN TTEC B ON A.TIPOTTEC=B.TIPO
                                                   WHERE A.N_FACTURA=#FPD.N_FACTURA
                                                   )  
                          WHEN #FPD.CLASE='C' THEN (
                                                   SELECT B.CUENTACG FROM FTR A INNER JOIN TTEC B ON A.TIPOTTEC=B.TIPO
                                                   WHERE A.N_FACTURA=#FPD.N_FACTURA
                                                   )                                                                                                                                       
                   END
             END
         END,
         FTR.IDTERCERO, '' AS CCOSTO,
         CASE WHEN FCXC.ANTIGUA = 1 THEN 
               CASE WHEN ISNULL(FCXCD.IDPLAN,'')='' THEN
                    'NO EXISTE EL PLAN EN EL DETALLE DE LA CXC (FCXCD.IDPLAN), FA: '+#FPD.N_FACTURA
                    ELSE
                     ISNULL((SELECT RTRIM(TTEC.DETALLE)+' FA: '+#FPD.N_FACTURA FROM TTEC,PPT 
                            WHERE TTEC.TIPO = PPT.TIPOTERCONTABLE AND PPT.IDPLAN=FCXCD.IDPLAN AND 
                                 PPT.IDTERCERO=FCXC.IDTERCERO),'NO EXISTE EL PLAN EN EL DETALLE DE LA CXC (FCXCD.IDPLAN)')
               END
             ELSE
              CASE WHEN ISNULL(FTR.TIPOTTEC,'')='' THEN
                    ISNULL((SELECT RTRIM(TTEC.DETALLE)+' FA: '+#FPD.N_FACTURA FROM TTEC,PPT 
                           WHERE TTEC.TIPO = PPT.TIPOTERCONTABLE AND PPT.IDPLAN=FCXCD.IDPLAN AND 
                                 PPT.IDTERCERO=FCXC.IDTERCERO),'NO EXISTE O NO HAY RELACION CON TERCEROS CONTABLES DEL PLAN DE LA FACTURA (FTR.IDPLAN)')
                   ELSE
                    ISNULL((SELECT RTRIM(TTEC.DETALLE)+' FA: '+#FPD.N_FACTURA FROM TTEC 
                            WHERE TTEC.TIPO = FTR.TIPOTTEC),'NO EXISTE EL TIPO DE TERCERO DE LA FACTURA (FTR.TIPOTTEC)')
              END
        END, 
        CASE WHEN PAR.MCUEORDEN_GLOSAS='Si' THEN  SUM(COALESCE( #FPD.VLRFACTURA,0)- COALESCE( #FPD.VLRGLOSA,0)+COALESCE(#FPD.VLRDTOFIN,0))
        --+COALESCE(#FPD.VLROTROSDCTOS,0)) 
        ELSE CASE WHEN #FP.INGRESO='GLOSAS' THEN SUM(COALESCE(#FPD.VLRGLOSA,0)) ELSE SUM(COALESCE( #FPD.VALORPAGO,0))+SUM(COALESCE(#FPD.VLRIMPUESTO,0))+SUM(COALESCE(#FPD.VLRDTOFIN,0))
        --+SUM(COALESCE(#FPD.VLROTROSDCTOS,0))
        END END,
        #FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM))), @USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()), 
        '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_CLIENTE', 'Movimiento','S',
        #FPD.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(FCXC.FECHACXC), DBO.FNK_FECHA_SIN_HORA(FCXC.F_VENCE), 'CXC', @CNSFPAG, 
        #FPD.CODUNG, #FPD.CODPRG
   FROM PAR,#FP INNER JOIN #FPD ON #FP.CNSFPAG=#FPD.CNSFPAG 
			   INNER JOIN FTR ON FTR.N_FACTURA = #FPD.N_FACTURA
			   INNER JOIN FCXCD ON FCXCD.N_FACTURA=#FPD.N_FACTURA
			   INNER JOIN FCXC ON FCXC.CNSCXC = FCXCD.CNSCXC --AND FCXC.IDTERCERO = #FP.IDTERCERO
               --INNER JOIN FCXCDV ON #FPD.N_fACTURA=FCXCDV.N_FACTURA AND #FPD.CNSCXC=FCXCDV.CNSGLO AND #FPD.CNSGLO=FCXCDV.CNSGLO AND #FPD.CLASE=FCXCDV.TIPO
			   INNER JOIN FCXCDV ON #FPD.N_fACTURA=FCXCDV.N_FACTURA AND #FPD.CNSCXC=FCXCDV.CNSCXC AND COALESCE(#FPD.CNSGLO,'')=COALESCE(FCXCDV.CNSGLO,'') AND #FPD.CLASE=FCXCDV.TIPO
			   -- JGOMEZ REALIZA CAMBIO PARA EVITAR DUPLICADOS
			    AND #FPD.CNSCXC=FCXC.CNSCXC
   WHERE PAR.COMPANIA=@COMPANIA AND (CASE WHEN #FP.INGRESO='GLOSAS' THEN #FPD.VLRGLOSA ELSE COALESCE(#FPD.VALORPAGO,0)+COALESCE(#FPD.VLRIMPUESTO,0)+COALESCE(#FPD.VLRDTOFIN,0) END )>0
   GROUP BY FCXC.IDTERCERO, #FPD.N_FACTURA, FTR.CUENTACXC, FTR.PROCEDENCIA, FTR.TIPOTTEC, PAR.MCUEORDEN_GLOSAS, 
             DBO.FNK_FECHA_SIN_HORA(FCXC.FECHACXC), DBO.FNK_FECHA_SIN_HORA(FCXC.F_VENCE), FCXCD.CUENTA, FCXC.ANTIGUA,
             FCXCD.IDPLAN, #FP.IDTERCERO, FTR.IDTERCERO, #FPD.CODUNG, #FPD.CODPRG,FTR.F_VENCE,#FPD.CLASE, COALESCE(FTR.CASTIGADA,0),
             #FPD.CNSFPAG,#FPD.CNSCXC,LTRIM(RTRIM(STR(#FPD.ITEM))),#FP.INGRESO,FCXCDV.TCOBRO
   HAVING CASE WHEN PAR.MCUEORDEN_GLOSAS='Si' THEN SUM(COALESCE( #FPD.VLRFACTURA,0)- COALESCE( #FPD.VLRGLOSA,0)) ELSE SUM(#FPD.VLRFACTURA) END <>0

	--SE GENERA UN NUEVO COMPROBANTE POR FACTURA SI TIENE PAGOS EXTRAS JFRANCO 25/04/2020
	IF (SELECT COUNT(*) FROM #FPD WHERE CNSFPAG = @CNSFPAG AND COALESCE(VLREXTRA, 0)> 0 ) > 0
	BEGIN
		PRINT 'Ingreso a Contabilizar Valores Extras'
		EXEC SPK_NC_CONTAB_CXC_VLREXTRA @CNSFPAG, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @SEDE
	END

   -- SE BORRA LO QUE ESTABA COMENTARIZADO JJIMENEZ 30-04-14 QUEDA EN BACKUP ANTERIORES  
   PRINT 'Poniendo Estado de CONTABILIZADA en La Tabla FPAG'
  
   
   ----EXEC SPK_REVISAR_COMPROBANTE @COMPANIA,@NROCOMPROBANTE
   EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME 
   EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''
   -- EXEC SPK_SUMA_DBCR @NROCOMPROBANTE
   
   DROP TABLE #FP
   DROP TABLE #FPD
END

