CREATE OR ALTER PROCEDURE DBO.SPK_NC_CONTAB_CAJA_ING 
    @CNSFACJ            VARCHAR(20),
    @CODCAJA            VARCHAR(4),
    @USUARIO            VARCHAR(12),
    @SYS_COMPUTERNAME   VARCHAR(254),
    @COMPANIA           VARCHAR(2), 
    @SEDE               VARCHAR(5),
    @NROCOMPROBANTE     VARCHAR(20)
WITH ENCRYPTION
AS
BEGIN
    SET NOCOUNT ON;

    -- === Variables del sistema requeridas proceso caja ===
    DECLARE 
        @IDCJLEGDEPOSITO          VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO'),
        @CPCJ_REEMB               VARCHAR(20) = DBO.FNK_VALORVARIABLE('CPCJ_REEMB'),
        @IDCJRECEPCIONTRAS        VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJRECEPCIONTRAS'),
        @FACTURAPOS_ACTIVA        VARCHAR(20) = DBO.FNK_VALORVARIABLE('FACTURAPOS_ACTIVA'),
        @IDMODELOCONTABLE         VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE'),
        @COMPROBMULTISEDE         VARCHAR(20) = DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE'),
        @IDCON_TCOM_ICAJ          VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCON_TCOM_ICAJ'),
        @IDCON_TCOM_DEFAULT       VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT'),
        @TERCATAFILIADO           VARCHAR(20) = DBO.FNK_VALORVARIABLE('TERCATAFILIADO'),
        @IDCJFPADESCUENT_NOMI     VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJFPADESCUENT_NOMI'),
        @USARCUEPUENTE            VARCHAR(20) = DBO.FNK_VALORVARIABLE('USARCUEPUENTE'),
        @IDTERCONTABLEPART        VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART'),
        @IDCJAPERTURACAJA         VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJAPERTURACAJA'),
        @IDCJDEPCLIATER           VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJDEPCLIATER'),
        @IDCJCOPA                 VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJCOPA'),
        @IDCJABONOCP              VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJABONOCP'),
        @IDCJBONO                 VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJBONO'),
        @IDCJMODE                 VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJMODE'),
        @IDCJPACO                 VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDCJPACO');

    -- === Otras variables originales ===
    DECLARE @COM              VARCHAR(6)
    DECLARE @NOREFERENCIA     VARCHAR(20)
    DECLARE @ANO		        VARCHAR(4)
    DECLARE @MES              INT
    DECLARE @IDMODELOCONT	  VARCHAR(2)
    DECLARE @IDPLAN           VARCHAR(6) 
    DECLARE @TIPOTERCONTABLE  VARCHAR(10) 
    DECLARE @ESTADO           VARCHAR(1)
    DECLARE @PREFIJO_USCXS    VARCHAR(10)
    DECLARE @FECHATRA         DATETIME
    DECLARE @SALDO            DECIMAL(15,6)   
    DECLARE @TOTAL_CRUCE      DECIMAL(15,6)
    DECLARE @TOTAL_ORIGINAL   DECIMAL(15,6) 
    DECLARE @VALORIMPUESTOS	  DECIMAL(14,2)
    DECLARE @VLRAJUSTEPESO    DECIMAL(14,2)
    DECLARE @CNSFPAG          VARCHAR(20)
    DECLARE @CNSFCXP          VARCHAR(20)
    DECLARE @IDTERCERO_CXP    VARCHAR(20)
    DECLARE @N_FACTURA_CXP    VARCHAR(20)
    DECLARE @F_FACTURA_CXP    DATETIME
    DECLARE @F_VENCE_CXP      DATETIME
    DECLARE @OBSERVACION_CXP  VARCHAR(255)
    DECLARE @VALOR_CXP        DECIMAL(14,2)     
    DECLARE @CCOSTO_CXP       VARCHAR(20)
    DECLARE @IDAREA_CXP       VARCHAR(20)
    DECLARE @CUENTA_CXP       VARCHAR(16)
    DECLARE @CLASE_GENERA_CXP VARCHAR(10)
    DECLARE @IDAFILIADO       VARCHAR(20)
    DECLARE @IDCATEGORIA      VARCHAR(20)
    DECLARE @PROCESO          VARCHAR(10)    
    /*CAJA DE COMPENSACION*/
    DECLARE @PROCEDENCIA      VARCHAR(10)
    DECLARE @CUENTACXC        VARCHAR(16)
    DECLARE @IDTERCERO        VARCHAR(20)
    DECLARE @N_FACTURA        VARCHAR(16), @CNSCXC VARCHAR(20), @VEZFCXCDV INT
    DECLARE @ESLEGDEPO         INT
    DECLARE @DOCIDAFILIADO	  VARCHAR(20)
    DECLARE @IDTERCEROAFI	  VARCHAR(20)
    DECLARE @DESDEFTR BIT = 0
    DECLARE @N_FACT VARCHAR(20)
    BEGIN TRY

        PRINT 'SE ADICIONA VALIDACION DEL RECIBO DE CAJA'
        IF COALESCE(@NROCOMPROBANTE,'')='' AND EXISTS(SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ AND COALESCE(CONTABILIZADA,0)<>0 AND COALESCE(NROCOMPROBANTE,'')<>'')
        BEGIN
            PRINT 'MOVIMIENTO YA FUE ENVIADO A CONTABILIDAD O ESTA EN PROCESO DE CONTABILIZACION, ME REGRESO'
            RETURN
        END

        IF @FACTURAPOS_ACTIVA='SI' AND COALESCE(@NROCOMPROBANTE,'')<>''
        BEGIN
            /* bugfix/CESPER87 -- 2026-09-05
               N_FACTURAPOS = copago: embebe el asiento en el comprobante de la factura. */
            IF EXISTS(SELECT * FROM FCJ WITH (NOLOCK) WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ 
                AND ESTADO='P'
                AND COALESCE(N_FACTURAPOS,'')<>'')
            BEGIN       
                SELECT @DESDEFTR=1
                SELECT @N_FACT=COALESCE(N_FACTURAPOS,'') FROM FCJ WITH (NOLOCK) WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ 
            END
        END

        SELECT @COMPANIA = COALESCE(UBEQ.COMPANIA,'01'), @SEDE = COALESCE(USUSU.IDSEDE,'01') 
        FROM USUSU 
        INNER JOIN UBEQ ON USUSU.SYS_ComputerName = UBEQ.SYS_ComputerName
        WHERE USUSU.USUARIO = @USUARIO

        SELECT @PROCEDENCIA = PROCEDENCIA 
        FROM FCJ 
        WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA

        PRINT ''
        PRINT '     **************************************'
        PRINT '     ** ENVIO DE CAJA.ING A CONTABILIDAD **'
        PRINT '     **************************************'
        PRINT 'Seleccionando Informacion de : '+@CNSFACJ+' '+@CODCAJA
        PRINT 'Actualizaci? Temporal... Mientras se arregla lo del Saco en TFCJ'

        UPDATE FCJD SET VALORTOTAL = PCJ.VALOR
        FROM FCJD 
        INNER JOIN FCJ ON FCJD.CODCAJA = FCJ.CODCAJA AND FCJD.CNSFACJ = FCJ.CNSFACJ 
        INNER JOIN ( 
            SELECT CODCAJA, CNSFACJ, CANT = COUNT(*), VALORTOTAL = SUM(VALORTOTAL) 
            FROM FCJD 
            GROUP BY CODCAJA, CNSFACJ
        ) FCJD_X ON FCJ.CODCAJA = FCJD_X.CODCAJA AND FCJ.CNSFACJ = FCJD_X.CNSFACJ 
        LEFT JOIN ( 
            SELECT CODCAJA, CNSFACJ, VALOR = SUM(VALOR) 
            FROM PCJ 
            GROUP BY CODCAJA, CNSFACJ
        ) PCJ ON FCJ.CODCAJA = PCJ.CODCAJA AND FCJ.CNSFACJ = PCJ.CNSFACJ
        WHERE PCJ.VALOR <> FCJD.VALORTOTAL 
          AND FCJD_X.CANT = 1 
          AND FCJD.CODCAJA = @CODCAJA 
          AND FCJD.CNSFACJ = @CNSFACJ

        -- Creaci?n de tablas temporales
        SELECT * INTO #F FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA;
        IF NOT EXISTS (SELECT 1 FROM #F) 
        BEGIN 
            PRINT 'No se encontr? el recibo de caja.';
            RETURN; 
        END

        SELECT * INTO #FD FROM FCJD WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA;
        IF NOT EXISTS (SELECT 1 FROM #FD) 
        BEGIN 
            PRINT 'No se encontraron detalles del recibo.';
            RETURN; 
        END

        SELECT * INTO #FDD FROM PCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA;

        SELECT  @ESLEGDEPO = COUNT(*) FROM #FDD WHERE TIPOPAGO = @IDCJLEGDEPOSITO;

        IF (SELECT TOP 1 CONCEPTO FROM #FD) = @CPCJ_REEMB  
        BEGIN
            RETURN
        END 

        IF EXISTS(SELECT * FROM CAJ WHERE CODCAJA=@CODCAJA AND COALESCE(NOCONTAB,0)=1)
        BEGIN
            PRINT 'No se Genera comprobante'
            UPDATE FCJ SET CONTABILIZADA=1,NROCOMPROBANTE='NOCONTAB',NOCONTAB=1 
            WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ
            RETURN
        END

        IF (SELECT TOP 1 CONCEPTO FROM #FD) = @IDCJRECEPCIONTRAS AND LEFT(@NROCOMPROBANTE,2)<>'IX' 
        BEGIN
            RETURN
        END  

        SELECT @ESTADO = #F.ESTADO, @IDTERCERO = COALESCE(IDTERCERO,''), @IDAFILIADO = COALESCE(IDAFILIADO,'') FROM #F
        UPDATE #F SET CCOSTO = '' WHERE CCOSTO NOT IN (SELECT CCOSTO FROM CEN WHERE COMPANIA = @COMPANIA)

        SELECT @ANO = YEAR(FECHA), @MES = MONTH(FECHA), @FECHATRA = FECHA FROM #F

        IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)
        BEGIN
            RAISERROR('PERIODO NO EXISTE.',16,1)
            RETURN
        END

        PRINT '@IDTERCERO ='+COALESCE(@IDTERCERO,'SIN TERCERO')
        PRINT '@IDAFILIADO ='+COALESCE(@IDAFILIADO,'SIN TERCERO')

        IF EXISTS (SELECT 1 FROM MCP WHERE PROCEDENCIA='CAJA' AND REFERENCIA1=@CNSFACJ AND REFERENCIA2=@CODCAJA AND COALESCE(ANULADO,0)=0)
        BEGIN
            PRINT '@PROCEDENCIA=CAJA, MCP.PROCEDENCIA'
            PRINT '@CODCAJA='+@CODCAJA+ ', MCP.REFERENCIA1'
            PRINT '@CNSFACJ='+@CNSFACJ+ ', MCP.REFERENCIA2'
            IF @DESDEFTR=0
            BEGIN 
               PRINT 'Me regreso, Recibo de caja ya contabilizado...'
               RETURN
            END
            RETURN
        END

        SET @IDMODELOCONT = @IDMODELOCONTABLE
        PRINT '************************* @PROCEDENCIA: ' + @PROCEDENCIA

        IF COALESCE(@IDAFILIADO,'')<>'' AND EXISTS(SELECT * FROM AFI WHERE IDAFILIADO=@IDAFILIADO)
        BEGIN
            PRINT 'Crea el Afiliado como Tercero con la categoria de Afiliado'
            SELECT TOP 1 @IDAFILIADO = IDAFILIADO FROM #F
            SET @IDCATEGORIA = @TERCATAFILIADO
            PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '''+@IDAFILIADO+''','''+@IDCATEGORIA+''''
            EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
            PRINT 'Termine de configurar AFI'
            SELECT @IDTERCEROAFI = COALESCE(RUC,IDAFILIADO), @DOCIDAFILIADO = AFI.DOCIDAFILIADO FROM AFI WHERE IDAFILIADO=@IDAFILIADO
        END
        ELSE
        BEGIN
            IF EXISTS (SELECT * FROM TER WHERE IDTERCERO=@IDTERCERO)
            BEGIN
                SELECT @IDTERCEROAFI = @IDTERCERO
            END
            ELSE
            BEGIN 
                IF EXISTS(SELECT * FROM TER WHERE (NIT=@IDAFILIADO OR IDTERCERO=@IDAFILIADO) AND ESTADO='Activo')
                BEGIN
                    SELECT @IDTERCEROAFI = IDTERCERO FROM TER WHERE (NIT=@IDAFILIADO OR IDTERCERO=@IDAFILIADO) AND ESTADO='Activo'
                END
            END
        END

        PRINT 'IDTERCERO DEFINITIVO ' 
        IF ISNULL(@NROCOMPROBANTE,'') = '' OR LEFT(@NROCOMPROBANTE,2)='IX'
        BEGIN
            IF EXISTS (SELECT * FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA=@CODCAJA AND ( CONTABILIZADA=1 OR COALESCE(NROCOMPROBANTE,'')<>'') )
            BEGIN
                RAISERROR('Recibo ya se encuentra en contabilidad, Posible duplicidad', 16, 1)
                RETURN
            END
            SET @PROCESO='Nuevo'  
            IF LEFT(@NROCOMPROBANTE,2)='IX'
            BEGIN
                SET @COM = 'IX'   
                SET @NOREFERENCIA = @NROCOMPROBANTE
            END
            ELSE
            BEGIN
                SET @NROCOMPROBANTE = SPACE(20)
                EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT
                PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'')
                SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0)
                PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'')
                PRINT '@ESLEGDEPO :'+STR(@ESLEGDEPO)

                IF @COMPROBMULTISEDE = 'SI'
                BEGIN
                    IF @ESLEGDEPO >= 1
                    BEGIN 
                        SELECT @COM = COMPROBANTE FROM COMMS WHERE IDSEDE = @SEDE AND CLASE = 'CAJAING' AND TIPO = 'IDCJLEGDEPOSITO'
                    END
                    ELSE
                    BEGIN
                        SELECT @COM = RTRIM(LTRIM(
                            CASE WHEN EXISTS (
                                SELECT TOP 1 COMMS.COMPROBANTE
                                FROM #FD INNER JOIN COMMS ON #FD.CONCEPTO = COMMS.TIPO
                                WHERE COMMS.IDSEDE = @SEDE AND COMMS.CLASE = 'CAJAING'
                            ) THEN (
                                SELECT TOP 1 COMMS.COMPROBANTE
                                FROM #FD INNER JOIN COMMS ON #FD.CONCEPTO = COMMS.TIPO
                                WHERE COMMS.IDSEDE = @SEDE AND COMMS.CLASE = 'CAJAING'
                            ) ELSE (
                                CASE WHEN EXISTS (
                                    SELECT TOP 1 COM.COMPROBANTE 
                                    FROM CPCJ, COM, #FD 
                                    WHERE CPCJ.CODIGO = #FD.CONCEPTO AND CPCJ.COMPROBANTE = COM.COMPROBANTE AND COM.COMPANIA=@COMPANIA
                                ) THEN (
                                    SELECT TOP 1 COM.COMPROBANTE 
                                    FROM CPCJ, COM, #FD 
                                    WHERE CPCJ.CODIGO = #FD.CONCEPTO AND CPCJ.COMPROBANTE = COM.COMPROBANTE AND COM.COMPANIA=@COMPANIA
                                ) ELSE
                                    CASE WHEN @IDCON_TCOM_ICAJ <> '' OR @IDCON_TCOM_ICAJ IS NOT NULL THEN @IDCON_TCOM_ICAJ
                                         ELSE @IDCON_TCOM_DEFAULT 
                                    END 
                                END
                            ) END
                        ))
                    END
                END
                ELSE
                BEGIN
                    IF @ESLEGDEPO >= 1
                    BEGIN 
                        SELECT @COM = COMPROBANTE_EGR FROM FPA WHERE FORMAPAGO = @IDCJLEGDEPOSITO
                    END
                    ELSE
                    BEGIN            
                        SET @COM = RTRIM(LTRIM(
                            CASE WHEN EXISTS (
                                SELECT TOP 1 COM.COMPROBANTE 
                                FROM CPCJ, COM, #FD 
                                WHERE CPCJ.CODIGO = #FD.CONCEPTO AND CPCJ.COMPROBANTE = COM.COMPROBANTE AND COM.COMPANIA=@COMPANIA
                            ) THEN (
                                SELECT TOP 1 COM.COMPROBANTE 
                                FROM CPCJ, COM, #FD 
                                WHERE CPCJ.CODIGO = #FD.CONCEPTO AND CPCJ.COMPROBANTE = COM.COMPROBANTE AND COM.COMPANIA=@COMPANIA
                            ) ELSE
                                CASE WHEN @IDCON_TCOM_ICAJ <> '' OR @IDCON_TCOM_ICAJ IS NOT NULL THEN @IDCON_TCOM_ICAJ
                                     ELSE @IDCON_TCOM_DEFAULT 
                                END 
                            END
                        ))
                    END
                END
                SET @PREFIJO_USCXS = '@COM'+@COM
                SET @NOREFERENCIA = SPACE(20)
                EXEC SPK_GENCONSECUTIVO @COMPANIA,@COMPANIA,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
                SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
            END
            PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
            PRINT 'Comprobante Contable (MCP)'
            PRINT 'Comprobante Contable = '+@NROCOMPROBANTE

            INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                             TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                             COMPROBANTE, IDTERCERO, ANULADO)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'CAJA', @NOREFERENCIA, @ANO, @MES, CAST(STR(DAY(FECHA))+'/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME),
                   0, 0, @CNSFACJ, CODCAJA, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, LEFT(OBSERVACION,512) OBSERVACION, @SEDE, 1,
                   @COM, @IDTERCEROAFI, CASE WHEN #F.ESTADO='A' THEN 1 ELSE 0 END
            FROM #F

            IF (SELECT TOP 1 CONCEPTO FROM #FD) = @IDCJRECEPCIONTRAS
            BEGIN
                RETURN
            END         
        END
        ELSE
        BEGIN
            SET @PROCESO='Viejo'  
            PRINT 'DEPOSITOS DE CLIENTES A TERCEROS VIEJO'

            DECLARE CUR_CXP CURSOR FOR
            SELECT DISTINCT CNSFCXCXP
            FROM MCHE 
            WHERE MCHE.NROCOMPROBANTE = @NROCOMPROBANTE AND MCHE.PROCEDENCIA='CAJA' AND MCHE.REFERENCIA_PRO=@CNSFACJ 
            AND   MCHE.REFERENCIA2    = @CODCAJA AND MCHE.PROCESO='CXP_XDEPCLITER' AND MCHE.CLASE_GENERA='Contab'

            OPEN CUR_CXP               
            FETCH NEXT FROM CUR_CXP INTO @CNSFCXP
            WHILE @@FETCH_STATUS = 0
            BEGIN   
                PRINT 'Eliminando CXP con CNS='+@CNSFCXP
                EXEC SPK_ADMIN_CXP_CONTAB @CNSFCXP,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'DELETE',NULL,NULL,NULL
                FETCH NEXT FROM CUR_CXP INTO @CNSFCXP
            END
            CLOSE CUR_CXP
            DEALLOCATE CUR_CXP 

            SELECT @COM = COMPROBANTE, @NOREFERENCIA = NOREFERENCIA FROM MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE

            IF @ESTADO <> 'A'
            BEGIN
                DELETE MCHE 
                WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND PROCEDENCIA = 'CAJA' AND REFERENCIA_PRO = @CNSFACJ AND REFERENCIA2 = @CODCAJA  
                UPDATE MCPE SET OBSERVACION = #F.OBSERVACION FROM #F   
                WHERE MCPE.NROCOMPROBANTE = @NROCOMPROBANTE AND MCPE.PROCEDENCIA = 'CAJA' 
                  AND MCPE.REFERENCIA1 = @CNSFACJ AND MCPE.REFERENCIA2 = @CODCAJA  
            END
        END

        IF @ESTADO = 'A' AND LEFT(@NROCOMPROBANTE,2) <> 'IX'  
        BEGIN   
            PRINT 'ANULADA.'  
            PRINT 'Borrando Registros de MCH...'
            UPDATE MCPE SET ESTADO='2', ANULADO=1, TOTALDEBITO=0, TOTALCREDITO=0 
            WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE  
            PRINT 'Actualizando FCJ...'
            UPDATE FCJ SET CONTABILIZADA=1, MARCACONT = 0, NROCOMPROBANTE = @NROCOMPROBANTE 
            FROM #F WHERE FCJ.CNSFACJ=#F.CNSFACJ AND FCJ.CODCAJA=#F.CODCAJA  
            IF @PROCESO='Viejo'  
            BEGIN
                RETURN  
            END
        END  

        IF @@ERROR <> 0
        BEGIN 
            PRINT 'Errores...'
            RETURN
        END

        PRINT '************************@IDTERCEROAFI: ' + COALESCE(@IDTERCEROAFI,'')
        PRINT '*************************@DOCIDAFILIADO: '+ISNULL(@DOCIDAFILIADO,'')
        PRINT 'Insertando Asiento del Concepto de Caja. (DB)'  

        IF (SELECT TIPO FROM #F) = 'EXTERNO' AND (SELECT CLASER FROM #F) = 'C'
        BEGIN
            PRINT ' -Insertando Registro MCH Con Conceptos (DB)'
            INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
                             REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,
                             IDAREA,CLASECONT,ESTADO,PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO,
                             N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',
                CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
                    CASE WHEN FPA.REQBCO = 1 THEN BCT.COD_CONTABLE ELSE CAJ.CUENTA END
                    ELSE FPA.CUENTA 
                END,
                CASE WHEN FPA.CXC = 1 THEN #FDD.IDTERCERO ELSE @IDTERCEROAFI END,
                #F.CCOSTO,
                'INGRESO POR '+UPPER(CPCJ.DESCRIPCION)+', CAJA No.'+@CODCAJA+ ', RECIBO No.'+#F.CNSFACJ+', FORMAPAGO: '+UPPER(FPA.DESCRIPCION),
                SUM((#FDD.VALOR * 100 / #F.VALORTOTAL) * #FD.VALORTOTAL / 100),
                #F.CNSFACJ, #F.CODCAJA, CPCJ.CODIGO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                NULL, #F.AREAPRESTACION, 'S', 1, 'INGRESO_CAJ', 'Movimiento','CAJA',@CNSFACJ,
                CASE WHEN @IDCJLEGDEPOSITO = FPA.FORMAPAGO THEN LTRIM(RTRIM(#FDD.CODCAJADEP)) + #FDD.CNSFACJDEP 
                     ELSE LTRIM(RTRIM(#F.CODCAJA)) + #F.CNSFACJ END,
                CASE WHEN @IDCJLEGDEPOSITO = FPA.FORMAPAGO THEN 
                    (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CODCAJA = #FDD.CODCAJADEP AND CNSFACJ = #FDD.CNSFACJDEP) 
                    ELSE DBO.FNK_FECHA_SIN_HORA(#F.FECHA) END,
                CASE WHEN @IDCJLEGDEPOSITO = FPA.FORMAPAGO THEN 
                    (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CODCAJA = #FDD.CODCAJADEP AND CNSFACJ = #FDD.CNSFACJDEP) 
                    ELSE DBO.FNK_FECHA_SIN_HORA(#F.FECHA) END, 
                CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
            FROM #F 
            INNER JOIN #FD ON #F.CODCAJA = #FD.CODCAJA AND #F.CNSFACJ = #FD.CNSFACJ 
            INNER JOIN #FDD ON #FD.CODCAJA = #FDD.CODCAJA AND #FD.CNSFACJ = #FDD.CNSFACJ 
            INNER JOIN CAJ ON #F.CODCAJA = CAJ.CODCAJA 
            INNER JOIN CPCJ ON CPCJ.CODIGO = #FD.CONCEPTO 
            INNER JOIN FPA ON #FDD.TIPOPAGO = FPA.FORMAPAGO
            LEFT JOIN BCT ON #FDD.BANCO = BCT.BANCO AND #FDD.SUCURSAL = BCT.SUCURSAL AND #FDD.CTA_BCO = BCT.CTA_BCO 
            GROUP BY CAJ.CUENTA, FPA.CUENTA, BCT.COD_CONTABLE, #F.IDTERCERO, #F.CCOSTO, #F.CNSFACJ, #F.AREAPRESTACION, #F.CODCAJA,
                     CPCJ.DESCRIPCION, FPA.DESCRIPCION, CPCJ.CODIGO, FPA.CXC, #FDD.IDTERCERO,           
                     CASE WHEN FPA.CXC = 1 THEN #FDD.IDTERCERO ELSE 
                         CASE WHEN #F.IDAFILIADO IS NULL OR #F.IDAFILIADO = '' THEN #F.IDTERCERO 
                              ELSE CASE WHEN COALESCE(@IDTERCEROAFI,'') = '' THEN  
                                    CASE WHEN ISNULL(@DOCIDAFILIADO,'') <> '' THEN @DOCIDAFILIADO ELSE #F.IDAFILIADO END 
                                    ELSE @IDTERCEROAFI END END END, 
                     FPA.USAR_CUENTACAJA, FPA.FORMAPAGO, FPA.REQBCO,
                     #FDD.CNSFACJDEP, #FDD.CODCAJADEP, #F.FECHA, #F.CODUNG, #F.CODPRG
            HAVING SUM((#FDD.VALOR * 100 / #F.VALORTOTAL) * #FD.VALORTOTAL / 100) <> 0

            PRINT 'TERMINO INSERT DB........'
        END
        ELSE IF (SELECT TIPO FROM #F) = 'CREDITO'
        BEGIN
            PRINT ' -Insertando Registro MCH Sin Conceptos A DEBITO  TIPO CREDITO'
            INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR, REFERENCIA1, REFERENCIA2, 
                             ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, 
                             N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE,@COMPANIA,'DB',TER.CUENTA,@IDTERCEROAFI,#F.CCOSTO,
                   'VTA CREDITO: '+RTRIM(TER.RAZONSOCIAL)+', CAJA: '+@CODCAJA+', RECIBO: '+#F.CNSFACJ,
                   SUM(#FD.VALORTOTAL),#F.CNSFACJ,#F.CODCAJA,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                   NULL,LEFT(#F.AREAPRESTACION,10),'S',1,'INGRESO_CAJ', 'Movimiento','CAJA',@CNSFACJ,
                   CASE WHEN COALESCE(#F.N_FACTURA,'') <> '' THEN COALESCE(#F.N_FACTURA,'') ELSE RTRIM(#F.CODCAJA)+#F.CNSFACJ END,
                   DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA), 
                   CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                   CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
            FROM #FD,#F,TER
            WHERE #F.IDTERCERO = TER.IDTERCERO
            GROUP BY TER.CUENTA,#F.IDTERCERO,#F.CCOSTO,#F.CNSFACJ,LEFT(#F.AREAPRESTACION,10),#F.CODCAJA,
                     TER.RAZONSOCIAL, #F.IDAFILIADO, DBO.FNK_FECHA_SIN_HORA(#F.FECHA), #F.CODUNG, #F.CODPRG
            HAVING SUM(#FD.VALORTOTAL) <> 0

            PRINT ' -Insertando Registro MCH Con Error... (El Tercero no existe en TER)'
            INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                             REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO, GENERA,
                             PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE,@COMPANIA,'DB','NO DEF.TER',@IDTERCEROAFI,#F.CCOSTO,
                   'VTA CREDITO: '+#F.IDTERCERO+', CAJA: '+@CODCAJA+', RECIBO: '+#F.CNSFACJ,
                   SUM(#FD.VALORTOTAL),#F.CNSFACJ,#F.CODCAJA,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                   NULL,LEFT(#F.AREAPRESTACION,10),'S',1,'INGRESO_CAJ', 'Movimiento','CAJA',@CNSFACJ,
                   RTRIM(#F.CODCAJA)+#F.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA), 
                   CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                   CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
            FROM #FD,#F
            WHERE NOT #F.IDTERCERO IN (SELECT IDTERCERO FROM TER WHERE TER.IDTERCERO = #F.IDTERCERO)
            GROUP BY #F.IDTERCERO,#F.CCOSTO,#F.CNSFACJ,LEFT(#F.AREAPRESTACION,10),#F.CODCAJA, 
                     #F.IDAFILIADO, DBO.FNK_FECHA_SIN_HORA(#F.FECHA), #F.CODUNG, #F.CODPRG
            HAVING SUM(#FD.VALORTOTAL) <> 0
        END
        ELSE  
        BEGIN
            IF @PROCEDENCIA = 'CAJA'
            BEGIN
                PRINT 'INGRESO PROCEDENCIA CAJA'
                INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
                                 REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,
                                 IDAREA,CLASECONT,ESTADO,PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO,
                                 N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
                SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 
                    CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
                        CASE WHEN FPA.REQBCO = 1 THEN BCT.COD_CONTABLE ELSE CAJ.CUENTA END
                        ELSE FPA.CUENTA 
                    END,
                    CASE WHEN FPA.CXC = 1 THEN #FDD.IDTERCERO ELSE @IDTERCEROAFI END,
                    #F.CCOSTO,
                    UPPER(FPA.DESCRIPCION)+', CAJA No.'+@CODCAJA+', RECIBO No.'+#F.CNSFACJ, SUM(#FDD.VALOR),  
                    #F.CNSFACJ, #F.CODCAJA, FPA.FORMAPAGO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                    NULL, #F.AREAPRESTACION, 'S' , 1, 'INGRESO_CAJ', 'Movimiento', 'CAJA', @CNSFACJ,
                    RTRIM(#F.CODCAJA)+#F.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(#F.FECHA),  DBO.FNK_FECHA_SIN_HORA(#F.FECHA),
                    CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                    CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                FROM #F 
                INNER JOIN #FDD ON #F.CODCAJA = #FDD.CODCAJA AND #F.CNSFACJ = #FDD.CNSFACJ 
                INNER JOIN CAJ ON #F.CODCAJA = CAJ.CODCAJA 
                INNER JOIN FPA ON #FDD.TIPOPAGO = FPA.FORMAPAGO 
                LEFT JOIN BCT ON #FDD.BANCO = BCT.BANCO AND #FDD.SUCURSAL = BCT.SUCURSAL AND #FDD.CTA_BCO = BCT.CTA_BCO 
                GROUP BY CAJ.CUENTA, FPA.CUENTA, BCT.COD_CONTABLE, #F.IDTERCERO, #F.CCOSTO, #F.CNSFACJ, #F.AREAPRESTACION, #F.CODCAJA,
                         FPA.DESCRIPCION, FPA.FORMAPAGO,
                         CASE WHEN FPA.CXC = 1 THEN #FDD.IDTERCERO ELSE @IDTERCEROAFI END, 
                         FPA.USAR_CUENTACAJA, FPA.FORMAPAGO, FPA.REQBCO, #FDD.CNSFACJDEP,
                         #FDD.CODCAJADEP, #F.FECHA, #F.CODUNG, #F.CODPRG
                HAVING SUM(#FDD.VALOR) <> 0 
            END
            ELSE
            BEGIN
                PRINT ' -Insertando Registro MCH Sin Conceptos de Contado NO KAJA'
                INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
                                 REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,
                                 IDAREA,CLASECONT,ESTADO,PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO,
                                 N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
                SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 
                    CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
                        CASE WHEN FPA.REQBCO = 1 THEN BCT.COD_CONTABLE ELSE CAJ.CUENTA END
                        ELSE FPA.CUENTA 
                    END,
                    CASE WHEN FPA.CXC = 1 OR #FDD.TIPOPAGO = @IDCJFPADESCUENT_NOMI THEN 
                        COALESCE(#FDD.IDTERCERO,#F.IDTERCERO)
                    ELSE COALESCE(@IDTERCEROAFI,#F.IDTERCERO) END, 
                    #F.CCOSTO,
                    UPPER(FPA.DESCRIPCION)+', CAJA No.'+@CODCAJA+', RECIBO No.'+#F.CNSFACJ,
                    SUM((#FDD.VALOR * 100 / #F.VALORTOTAL) * #FD.VALORTOTAL / 100),
                    #F.CNSFACJ,#F.CODCAJA,FPA.FORMAPAGO,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                    NULL,#F.AREAPRESTACION, 'S', 1, 'INGRESO_CAJ', 'Movimiento', 'CAJA', @CNSFACJ,
                    CASE WHEN @IDCJLEGDEPOSITO = FPA.FORMAPAGO THEN LTRIM(RTRIM(#FDD.CODCAJADEP))+#FDD.CNSFACJDEP 
                         ELSE RTRIM(#F.CODCAJA)+#F.CNSFACJ END,
                    CASE WHEN @IDCJLEGDEPOSITO = FPA.FORMAPAGO THEN 
                        (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CODCAJA=#FDD.CODCAJADEP AND CNSFACJ=#FDD.CNSFACJDEP) 
                        ELSE DBO.FNK_FECHA_SIN_HORA(#F.FECHA) END,
                    CASE WHEN @IDCJLEGDEPOSITO = FPA.FORMAPAGO THEN 
                        (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CODCAJA=#FDD.CODCAJADEP AND CNSFACJ=#FDD.CNSFACJDEP) 
                        ELSE DBO.FNK_FECHA_SIN_HORA(#F.FECHA) END, 
                    CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                    CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                FROM #F 
                INNER JOIN #FD ON #F.CODCAJA = #FD.CODCAJA AND #F.CNSFACJ = #FD.CNSFACJ 
                INNER JOIN #FDD ON #FD.CODCAJA = #FDD.CODCAJA AND #FD.CNSFACJ = #FDD.CNSFACJ 
                INNER JOIN CAJ ON #F.CODCAJA = CAJ.CODCAJA 
                INNER JOIN FPA ON #FDD.TIPOPAGO = FPA.FORMAPAGO 
                LEFT JOIN BCT ON #FDD.BANCO = BCT.BANCO AND #FDD.SUCURSAL = BCT.SUCURSAL AND #FDD.CTA_BCO = BCT.CTA_BCO 
                GROUP BY CAJ.CUENTA, FPA.CUENTA, BCT.COD_CONTABLE, #F.IDTERCERO, #F.CCOSTO, #F.CNSFACJ, #F.AREAPRESTACION, #F.CODCAJA,
                         FPA.DESCRIPCION, FPA.FORMAPAGO,
                         CASE WHEN FPA.CXC = 1 OR #FDD.TIPOPAGO = @IDCJFPADESCUENT_NOMI THEN 
                            COALESCE(#FDD.IDTERCERO,#F.IDTERCERO)
                         ELSE COALESCE(@IDTERCEROAFI,#F.IDTERCERO) END, 
                         FPA.USAR_CUENTACAJA, FPA.FORMAPAGO, FPA.REQBCO, #FDD.CNSFACJDEP,
                         #FDD.CODCAJADEP, #F.FECHA, #F.CODUNG, #F.CODPRG
                HAVING SUM((#FDD.VALOR * 100 / #F.VALORTOTAL) * #FD.VALORTOTAL / 100) <> 0
            END
        END

        PRINT 'Insetardo Asiento del Concepto de Caja. (CR) SALIENDO' 

        IF (SELECT COUNT(*) FROM FCJPCXC A,#F WHERE A.CODCAJA = #F.CODCAJA AND A.CNSFACJ = #F.CNSFACJ AND COALESCE(#F.N_FACTURAPOS,'')='') > 0
        BEGIN
            UPDATE FCJ SET RECAUDO = 1 FROM #F WHERE FCJ.CODCAJA = #F.CODCAJA AND FCJ.CNSFACJ = #F.CNSFACJ AND COALESCE(#F.N_FACTURAPOS,'') = ''
            UPDATE #F SET RECAUDO = 1 
        END

        IF (SELECT RECAUDO FROM #F) = 1
        BEGIN
            PRINT 'Recaudos...'
            IF EXISTS(SELECT COMPANIA FROM PAR WHERE COMPANIA = @COMPANIA)
            BEGIN
                -- Cruce CxC: factura puede estar en N_FACTURA o en N_FACTURAPOS (FACTURAPOS)
                IF NOT EXISTS(
                    SELECT A.CNSFACJ
                    FROM FCJPCXC A, #F
                    WHERE A.CODCAJA = #F.CODCAJA
                      AND A.CNSFACJ = #F.CNSFACJ
                      AND (
                            (COALESCE(#F.N_FACTURA,'') <> '' AND #F.N_FACTURA = A.N_FACTURA)
                         OR (COALESCE(#F.N_FACTURAPOS,'') <> '' AND #F.N_FACTURAPOS = A.N_FACTURA)
                          )
                )
                BEGIN
                    PRINT 'Sin CxC'
                    INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO, 
                                     PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                    SELECT @NROCOMPROBANTE,@COMPANIA,'CR',
                           (CASE 
                                WHEN FPA.CXC = 1 THEN (SELECT CUENTA FROM TTEC WHERE TIPO = @IDTERCONTABLEPART)
                                WHEN COALESCE(FPA.CXC,0)=0 AND UPPER(@USARCUEPUENTE) = 'SI' THEN PAR.CTA_CAJ_REC_NOLEG 
                                WHEN COALESCE(#FDD.CUENTA,'') = '' AND (#F.IDPLAN IN (SELECT DATO FROM USVGS WHERE IDVARIABLE LIKE 'IDPLANPART%') OR COALESCE(#F.N_FACTURAPOS,'') <> '')
                                THEN (SELECT CUENTA FROM TTEC WHERE TIPO = @IDTERCONTABLEPART)
                                ELSE #FDD.CUENTA 
                            END),
                           @IDTERCEROAFI,#F.CCOSTO,
                           UPPER(FPA.DESCRIPCION)+(CASE WHEN #FDD.NUMERODOCUMENTO IS NULL THEN '' ELSE ', DOC.:'+#FDD.NUMERODOCUMENTO END)+
                           ', CLIENTE: '+UPPER(#F.NOMBRECLIENTE),
                           SUM((#FDD.VALOR * 100 / #F.VALORTOTAL) * #FD.VALORTOTAL / 100),COALESCE(@N_FACT,#F.CNSFACJ),#F.CODCAJA,
                           'CTA_CAJ_REC_NOLEG',NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,
                           LEFT(#F.AREAPRESTACION,10),'S',1,'DEP_CLIENTES', 'Movimiento',
                           CASE WHEN COALESCE(#F.N_FACTURA,'') <> '' THEN COALESCE(#F.N_FACTURA,'') ELSE RTRIM(#F.CODCAJA)+#F.CNSFACJ END,
                           DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA),'CAJA',@CNSFACJ, 
                           CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                           CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                    FROM #F,#FD,#FDD,FPA,PAR
                    WHERE PAR.COMPANIA = @COMPANIA AND #FDD.TIPOPAGO = FPA.FORMAPAGO
                    GROUP BY #F.IDTERCERO,#F.CCOSTO,#F.CNSFACJ,#F.N_FACTURA,#F.PROCEDENCIA,
                             LEFT(#F.AREAPRESTACION,10),#F.CODCAJA,FPA.DESCRIPCION,
                             #FDD.NUMERODOCUMENTO,#F.NOMBRECLIENTE,DBO.FNK_FECHA_SIN_HORA(#F.FECHA), FPA.CXC,
                             PAR.CTA_CAJ_REC_NOLEG, #F.IDAFILIADO, #FDD.CUENTA, #F.CODUNG, #F.CODPRG, #F.IDPLAN,#F.N_FACTURAPOS 
                END
                ELSE
                BEGIN
                    PRINT 'Con CxC'
                    PRINT 'Actualizando pagos '
                    IF (SELECT COUNT(*) FROM FCJPCXC WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA) > 0
                    BEGIN
                        UPDATE FCJ SET ENPAGOS = 1 WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
                    END   

                    DECLARE CUR_PAGOS CURSOR FOR
                    SELECT CNSFPAG FROM FCJPCXC WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA

                    OPEN CUR_PAGOS
                    FETCH NEXT FROM CUR_PAGOS INTO @CNSFPAG
                    WHILE @@FETCH_STATUS = 0
                    BEGIN
                        SELECT * INTO #P FROM FPAG WHERE CNSFPAG = @CNSFPAG
                        SELECT * INTO #PH FROM FPAGD WHERE CNSFPAG = @CNSFPAG
                        SELECT @VALORIMPUESTOS = VLRIMPUESTOS, @VLRAJUSTEPESO = VLRAJUSTEPESO FROM #P

                        PRINT 'Contabilizando Impuestos...' 
                        IF @VALORIMPUESTOS > 0
                        BEGIN 
                            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                             REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                             CLASECONT, VALOR_PORCIMP,BASE_IMP, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                            SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', FIMPDV.CUENTA, #P.IDTERCERO, '' AS CCOSTO, 
                                   'IMP POR '+FIMPDV.IDIMPUESTO+' CLASE '+FIMPDV.IDCLASE+' FA '+#PH.N_FACTURA, 
                                   SUM(FPAGDI.VLRIMPUESTO), FIMPDV.IDIMPUESTO, FIMPDV.IDCLASE, FIMPDV.ITEM, NULL, @USUARIO, 
                                   DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_IMPUESTOS', 
                                   'Movimiento','S', FIMPDV.VALOR, FPAGDI.BASE, #PH.N_FACTURA,
                                   DBO.FNK_FECHA_SIN_HORA(#P.FECHA), DBO.FNK_FECHA_SIN_HORA(#P.FECHA),'CAJA',@CNSFACJ, 
                                   CASE WHEN #PH.CODUNG = '' THEN NULL ELSE #PH.CODUNG END, 
                                   CASE WHEN #PH.CODPRG = '' THEN NULL ELSE #PH.CODPRG END
                            FROM #P,#PH,FPAGDI,FIMPDV  
                            WHERE #PH.CNSFPAG = FPAGDI.CNSFPAG AND #PH.N_FACTURA = FPAGDI.N_FACTURA AND
                                  FPAGDI.IDIMPUESTO = FIMPDV.IDIMPUESTO AND FPAGDI.IDCLASE = FIMPDV.IDCLASE AND
                                  FPAGDI.ITEMFIMPDV = FIMPDV.ITEM AND FPAGDI.VLRIMPUESTO > 0   
                            GROUP BY FIMPDV.CUENTA, IDTERCERO, #PH.N_FACTURA, #P.IDTERCERO, #PH.N_FACTURA,
                                     FIMPDV.IDIMPUESTO, FIMPDV.IDCLASE, FIMPDV.ITEM, FIMPDV.VALOR, FPAGDI.BASE,
                                     DBO.FNK_FECHA_SIN_HORA(#P.FECHA), #PH.CODUNG, #PH.CODPRG

                            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                             REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, 
                                             GENERA, CLASECONT, VALOR_PORCIMP, BASE_IMP, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA,
                                             REFERENCIA_PRO, CODUNG, CODPRG)
                            SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 'NO DEF.IMP', #P.IDTERCERO, '' AS CCOSTO, 
                                   'IMPUESTO NO EXISTE EN TABLA DE IMPUESTO: '+FPAGDI.IDIMPUESTO+' CLASE '+FPAGDI.IDCLASE+
                                   ' FA '+#PH.N_FACTURA, 
                                   SUM(FPAGDI.VLRIMPUESTO), FPAGDI.IDIMPUESTO, FPAGDI.IDCLASE, FPAGDI.ITEMFIMPDV, NULL, @USUARIO, 
                                   DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_IMPUESTOS',
                                   'Movimiento', 'S', (SUM(FPAGDI.VLRIMPUESTO)*100)/FPAGDI.BASE, FPAGDI.BASE,
                                   #PH.N_FACTURA,DBO.FNK_FECHA_SIN_HORA(#P.FECHA),DBO.FNK_FECHA_SIN_HORA(#P.FECHA),'CAJA',@CNSFACJ, 
                                   CASE WHEN #PH.CODUNG = '' THEN NULL ELSE #PH.CODUNG END, 
                                   CASE WHEN #PH.CODPRG = '' THEN NULL ELSE #PH.CODPRG END
                            FROM #P,#PH,FPAGDI
                            WHERE #PH.CNSFPAG = FPAGDI.CNSFPAG AND #PH.N_FACTURA = FPAGDI.N_FACTURA AND FPAGDI.VLRIMPUESTO > 0 AND
                                  NOT FPAGDI.IDIMPUESTO IN (SELECT FIMPDV.IDIMPUESTO FROM FIMPDV 
                                                           WHERE FPAGDI.IDIMPUESTO = FIMPDV.IDIMPUESTO AND
                                                                 FPAGDI.IDCLASE = FIMPDV.IDCLASE AND
                                                                 FPAGDI.ITEMFIMPDV = FIMPDV.ITEM)
                            GROUP BY IDTERCERO, #PH.N_FACTURA, #P.IDTERCERO, #PH.N_FACTURA, FPAGDI.IDIMPUESTO,
                                     FPAGDI.IDCLASE, FPAGDI.ITEMFIMPDV, FPAGDI.BASE, DBO.FNK_FECHA_SIN_HORA(#P.FECHA), #PH.CODUNG, #PH.CODPRG
                        END

                        IF @VLRAJUSTEPESO > 0
                        BEGIN
                            IF EXISTS(SELECT TIPO FROM KCDE WHERE TIPO='CXC_AJ_AFAVOR')
                            BEGIN
                                PRINT 'Contabilizando Ajuste al Peso a Favor...' 
                                INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                                 REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                                 CLASECONT, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
                                SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', KCDE.CUENTA, #P.IDTERCERO,'' AS CCOSTO, 
                                       'AJUSTE AL PESO ', ABS(#P.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                                       '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_AFAVOR', 'Movimiento','S','CXC',@CNSFPAG,
                                       RTRIM(#F.CODCAJA)+#F.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA), 
                                       CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                                       CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                                FROM #P,KCDE,#F
                                WHERE KCDE.IDMODELOCONT=@IDMODELOCONT AND KCDE.TIPO='CXC_AJ_AFAVOR' AND #P.VLRAJUSTEPESO>0
                            END
                            ELSE
                            BEGIN
                                PRINT 'Contabilizando Ajueste con Error... (No Existe KCDE=CXC_AJ_AFAVOR)' 
                                INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                                 REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                                 CLASECONT, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
                                SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 'NO DEF.KCDE', #P.IDTERCERO,'' AS CCOSTO, 
                                       'AJUSTE AL PESO ', ABS(#P.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                                       '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_AFAVOR', 'Movimiento','S','CAJA',@CNSFACJ,
                                       CASE WHEN COALESCE(#F.N_FACTURA,'')<>'' THEN COALESCE(#F.N_FACTURA,'') ELSE  RTRIM(#F.CODCAJA)+#F.CNSFACJ END,DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA), 
                                       CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                                       CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                                FROM #P,#F
                                WHERE #P.VLRAJUSTEPESO>0
                            END
                        END

                        IF @VLRAJUSTEPESO<0
                        BEGIN
                            IF EXISTS(SELECT TIPO FROM KCDE WHERE TIPO='CXC_AJ_ENCONTRA')
                            BEGIN
                                PRINT 'Contabilizando Ajuste al Peso En Contra...' 
                                INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                                 REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                                 CLASECONT, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
                                SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', KCDE.CUENTA, #P.IDTERCERO,'' AS CCOSTO, 
                                       'AJUSTE AL PESO ', ABS(#P.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                                       '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_ENCONTRA', 'Movimiento','S','CXC',@CNSFPAG,
                                       RTRIM(#F.CODCAJA)+#F.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA), 
                                       CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                                       CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                                FROM #P,KCDE,#F
                                WHERE KCDE.IDMODELOCONT=@IDMODELOCONT AND KCDE.TIPO='CXC_AJ_ENCONTRA' AND #P.VLRAJUSTEPESO<0
                            END
                            ELSE
                            BEGIN
                                PRINT 'Contabilizando Ajueste con Error... (No Existe KCDE=CXC_AJ_ENCONTRA)' 
                                INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                                 REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                                 CLASECONT, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
                                SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 'NO DEF.KCDE', #P.IDTERCERO,'' AS CCOSTO, 
                                       'AJUSTE AL PESO ', ABS(#P.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                                       '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_ENCONTRA', 'Movimiento','S','CAJA',@CNSFACJ,
                                       RTRIM(#F.CODCAJA)+#F.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA), 
                                       CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                                       CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                                FROM #P,#F
                                WHERE #P.VLRAJUSTEPESO < 0
                            END
                        END

                        DROP TABLE #P
                        DROP TABLE #PH

                        FETCH NEXT FROM CUR_PAGOS INTO @CNSFPAG
                    END
                    CLOSE CUR_PAGOS
                    DEALLOCATE CUR_PAGOS

                    SELECT @VEZFCXCDV = 0
                    IF (SELECT COUNT(*) FROM FCJPCXC WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA) = 1 AND
                       (( SELECT PROCEDENCIA FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA) = 'CE' OR
                        ( SELECT PROCEDENCIA FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA) = 'CITAS')
                    BEGIN
                        SELECT @N_FACTURA = N_FACTURA, @CNSCXC = CNSCXC FROM FCJPCXC WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
                        SELECT @VEZFCXCDV = COUNT(*) FROM FCXCDV WHERE N_FACTURA = @N_FACTURA AND @CNSCXC = @CNSCXC
                    END

                    PRINT 'TERCERO AFI :'+ @IDTERCEROAFI
                    INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO, 
                                     PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                    SELECT DISTINCT @NROCOMPROBANTE,@COMPANIA,'CR',FCXCD.CUENTA,@IDTERCEROAFI,#F.CCOSTO,
                           'FA '+FCJPCXC.N_FACTURA+', CXC '+FCJPCXC.CNSCXC+', NIT '+@DOCIDAFILIADO,
                           FCJPCXC.VALOR,COALESCE(@N_FACT,#F.CNSFACJ),#F.CODCAJA,'PAGO_CXC_CAJA',NULL,@USUARIO,
                           DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#F.AREAPRESTACION,10),'S',1,
                           'PAGO_CXC_CAJA', 'Movimiento', FCJPCXC.N_FACTURA, 
                           DBO.FNK_FECHA_SIN_HORA(FCXCDV.FECHA),DBO.FNK_FECHA_SIN_HORA(FCXCDV.F_VENCE),'CAJA',@CNSFACJ, 
                           CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                           CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                    FROM #F,FCXCD,FCXCDV,FCJPCXC
                    WHERE FCJPCXC.CODCAJA = #F.CODCAJA 
                      AND FCJPCXC.CNSFACJ = #F.CNSFACJ 
                      AND FCXCD.CNSCXC = FCJPCXC.CNSCXC 
                      AND FCXCD.N_FACTURA = FCJPCXC.N_FACTURA 
                      AND FCXCDV.CNSCXC = FCJPCXC.CNSCXC 
                      AND FCXCDV.N_FACTURA = FCJPCXC.N_FACTURA
                      AND FCXCDV.ITEM = CASE WHEN COALESCE(@VEZFCXCDV,0) = 1 THEN FCXCDV.ITEM ELSE FCJPCXC.ITEM_FCXCDV END

                    SELECT @TOTAL_CRUCE = SUM(VALOR) FROM FCJPCXC WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
                    IF (SELECT VALORTOTAL FROM #F) > @TOTAL_CRUCE
                    BEGIN
                        SELECT @SALDO = VALORTOTAL - @TOTAL_CRUCE, @TOTAL_ORIGINAL = VALORTOTAL FROM #F
                        UPDATE #F SET VALORTOTAL = @SALDO
                        UPDATE #FD SET VALORTOTAL = (VALORTOTAL * 100 / @TOTAL_ORIGINAL) * @SALDO / 100
                        UPDATE #FDD SET VALOR = (VALOR * 100 / @TOTAL_ORIGINAL) * @SALDO / 100
                        PRINT 'Contabiliza Excedente en el Pago a favor del Cliente.' 
                        INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                                         REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO, 
                                         PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                        SELECT @NROCOMPROBANTE,@COMPANIA,'CR',
                               (CASE WHEN FPA.CXC=1 THEN (SELECT CUENTA FROM TTEC WHERE TIPO=@IDTERCONTABLEPART)
                                                    ELSE CASE WHEN UPPER(@USARCUEPUENTE)='SI' THEN 
                                                          PAR.CTA_CAJ_REC_NOLEG ELSE #FDD.CUENTA END
                               END),@IDTERCEROAFI,#F.CCOSTO,
                               UPPER(FPA.DESCRIPCION)+(CASE WHEN #FDD.NUMERODOCUMENTO IS NULL THEN '' ELSE ', DOC.:'+#FDD.NUMERODOCUMENTO END)+
                               ', CLIENTE: '+UPPER(#F.NOMBRECLIENTE),
                               SUM((#FDD.VALOR * 100 / #F.VALORTOTAL) * #FD.VALORTOTAL / 100),#F.CNSFACJ,#F.CODCAJA,
                               'CTA_CAJ_REC_NOLEG',NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,
                               LEFT(#F.AREAPRESTACION,10),'S',1,'DEP_CLIENTES', 'Movimiento',
                               CASE WHEN COALESCE(#F.N_FACTURA,'') <> '' THEN COALESCE(#F.N_FACTURA,'') ELSE RTRIM(#F.CODCAJA)+#F.CNSFACJ END,
                               DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA),'CAJA',@CNSFACJ, 
                               CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                               CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                        FROM #F,#FD,#FDD,FPA,PAR
                        WHERE PAR.COMPANIA = @COMPANIA AND #FDD.TIPOPAGO = FPA.FORMAPAGO
                        GROUP BY #F.IDTERCERO,#F.CCOSTO,#F.CNSFACJ,
                                 LEFT(#F.AREAPRESTACION,10),#F.CODCAJA,FPA.DESCRIPCION,
                                 #FDD.NUMERODOCUMENTO,#F.NOMBRECLIENTE,DBO.FNK_FECHA_SIN_HORA(#F.FECHA),
                                 (CASE WHEN FPA.CXC=1 THEN (SELECT CUENTA FROM TTEC WHERE TIPO=@IDTERCONTABLEPART)
                                                      ELSE CASE WHEN UPPER(@USARCUEPUENTE)='SI' THEN 
                                                            PAR.CTA_CAJ_REC_NOLEG ELSE #FDD.CUENTA END
                                 END),PAR.CTA_CAJ_REC_NOLEG, #F.IDAFILIADO, #FDD.CUENTA, #F.CODUNG, #F.CODPRG,
                                 CASE WHEN COALESCE(#F.N_FACTURA,'') <> '' THEN COALESCE(#F.N_FACTURA,'') ELSE RTRIM(#F.CODCAJA)+#F.CNSFACJ END
                    END
                END
            END  
            ELSE 
            BEGIN 
                PRINT ' -Insertando Registro MCH Con Error... (No se encontrCuenta Puente de CAJA)'
                INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                                 REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO, 
                                 PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                SELECT @NROCOMPROBANTE,@COMPANIA,'CR','NO DEF.PAR',@IDTERCEROAFI,#F.CCOSTO,#F.CNSFACJ,
                       SUM(#FD.VALORTOTAL),#F.CNSFACJ,#F.CODCAJA,'CTA_CAJ_REC_NOLEG',NULL,@USUARIO,
                       DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#F.AREAPRESTACION,10),'S',0,
                       'DEP_CLIENTES', 'Movimiento', RTRIM(#F.CODCAJA)+#F.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(#F.FECHA), 
                       DBO.FNK_FECHA_SIN_HORA(#F.FECHA),'CAJA',@CNSFACJ, 
                       CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                       CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                FROM #F,#FD
                GROUP BY #F.IDTERCERO,#F.CCOSTO,#F.CNSFACJ,LEFT(#F.AREAPRESTACION,10),#F.CODCAJA, 
                         DBO.FNK_FECHA_SIN_HORA(#F.FECHA), #F.IDAFILIADO, #F.CODUNG, #F.CODPRG
            END
        END
        ELSE
        BEGIN
            PRINT 'No es Recaudo...' 
            IF (SELECT CLASER FROM #F) = 'S' OR (SELECT TIPO FROM #F)='CREDITO'
            BEGIN
                IF @PROCEDENCIA = 'CAJA'
                BEGIN
                    SELECT @IDTERCERO = IDTERCERO, @IDPLAN = IDPLAN, @N_FACTURA = N_FACTURA 
                    FROM FCJ 
                    WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA

                    SELECT @CUENTACXC = TTEC.CUENTA
                    FROM TTEC 
                    INNER JOIN PPT ON TTEC.TIPO = PPT.TIPOTERCONTABLE
                    WHERE PPT.IDTERCERO = DBO.FNK_VALORVARIABLE('IDTERCEROCAJACOM')
                      AND PPT.IDPLAN = @IDPLAN

                    INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA, 
                                     PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
                    SELECT @NROCOMPROBANTE, @COMPANIA,'CR', @CUENTACXC, @IDTERCEROAFI, #F.CCOSTO, 'PAGO N_FACTURA:'+@N_FACTURA, 
                           SUM(#FDD.VALOR), @CNSFACJ, @CODCAJA, @N_FACTURA, NULL, @USUARIO, DBO.FNK_FECHA_SIN_HORA(GETDATE()), NULL, 
                           #F.AREAPRESTACION, 'S', 1, '', 'Movimiento', 'CAJA', @CNSFACJ, @N_FACTURA, DBO.FNK_FECHA_SIN_HORA(GETDATE()),
                           DBO.FNK_FECHA_SIN_HORA(GETDATE()),  
                           CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                           CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                    FROM #F 
                    INNER JOIN #FDD ON #F.CNSFACJ = #FDD.CNSFACJ AND #F.CODCAJA = #FDD.CODCAJA
                    INNER JOIN FPA ON #FDD.TIPOPAGO = FPA.FORMAPAGO
                    WHERE FPA.FISICO = 1 
                    GROUP BY #F.CCOSTO, #F.AREAPRESTACION, #F.CODUNG, #F.CODPRG, DBO.FNK_FECHA_SIN_HORA(#F.FECHA)
                END
                ELSE
                BEGIN
                    PRINT ' -Insertando Registro MCH por Servicios por Prefijo.'
                    INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA, 
                                     PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
                    SELECT @NROCOMPROBANTE, @COMPANIA,'CR',
                           DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'VENTAS', 'CR', SER.PREFIJO, #F.CCOSTO, 'S', #FD.IDSERVICIO,0),
                           @IDTERCEROAFI,#F.CCOSTO,
                           'VENTA DE SERVICIOS: '+UPPER(PRE.NOM_PREFIJO),
                           SUM(#FD.VALORTOTAL),#F.CNSFACJ,#F.CODCAJA,'',NULL,@USUARIO,
                           DBO.FNK_FECHA_SIN_MLS(GETDATE()),SER.PREFIJO,#F.AREAPRESTACION,'S',1,
                           'COBRO_KMCOM', 'Movimiento','CAJA',@CNSFACJ,
                           RTRIM(#F.CODCAJA)+#F.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA), 
                           CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                           CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                    FROM #F 
                    INNER JOIN #FD ON #F.CNSFACJ = #FD.CNSFACJ 
                    LEFT JOIN SER ON #FD.IDSERVICIO = SER.IDSERVICIO 
                    LEFT JOIN PRE ON SER.PREFIJO = PRE.PREFIJO
                    GROUP BY #F.IDTERCERO,#F.CCOSTO,#F.CNSFACJ,#F.AREAPRESTACION,#F.CODCAJA,SER.PREFIJO,
                             PRE.NOM_PREFIJO, #F.IDAFILIADO, DBO.FNK_FECHA_SIN_HORA(#F.FECHA), #FD.IDSERVICIO, #F.CODUNG, #F.CODPRG
                END
            END    
            ELSE
            BEGIN
                PRINT ' -Insertando Registro MCH por Conceptos... ojo para depositos.........@DOCIDAFILIADO ='+@DOCIDAFILIADO
                INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                                 REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA, 
                                 N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CLASE_GENERA, CODUNG, CODPRG)
                SELECT @NROCOMPROBANTE,@COMPANIA,'CR',
                       (SELECT CASE WHEN @IDCJAPERTURACAJA = CPCJ.CODIGO THEN (SELECT CUENTA FROM CAJ WHERE CODCAJA=#F.CODCAJA) 
                                    ELSE CPCJ.CUENTA END),
                       CASE WHEN #FD.CONCEPTO = @IDCJDEPCLIATER THEN #FD.IDSERVICIO
                            ELSE COALESCE(@IDTERCEROAFI,@IDTERCERO) END,
                       #F.CCOSTO,
                       'PAGO CON '+UPPER(FPA.DESCRIPCION)+' '+(CASE WHEN #FDD.NUMERODOCUMENTO IS NULL THEN '' ELSE #FDD.NUMERODOCUMENTO END)+
                       ', CONCEPTO: '+UPPER(CPCJ.DESCRIPCION)+', EN CAJA No.'+#F.CODCAJA+', POR '+UPPER(#F.NOMBRECLIENTE)+', RECIBO No.'+#F.CNSFACJ,
                       SUM((#FDD.VALOR * 100 / #F.VALORTOTAL) * #FD.VALORTOTAL / 100),#F.CNSFACJ,#F.CODCAJA,CPCJ.CODIGO,NULL,
                       @USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#F.AREAPRESTACION,10),'S',1, 
                       CASE WHEN #FD.CONCEPTO = @IDCJDEPCLIATER THEN 'CXP_XDEPCLITER' ELSE 'COBRO_CPCJ' END, 
                       CASE WHEN #FD.CONCEPTO = @IDCJDEPCLIATER THEN 'Obligacion' ELSE 'Movimiento' END,
                       CASE CPCJ.CODIGO
                        WHEN @IDCJCOPA THEN #F.NOADMISION
                        WHEN @IDCJABONOCP THEN #F.NOADMISION
                        WHEN @IDCJBONO THEN #F.NOADMISION
                        WHEN @IDCJMODE THEN #F.NOADMISION
                        WHEN @IDCJPACO THEN #F.NOADMISION
                       ELSE RTRIM(#F.CODCAJA)+#F.CNSFACJ END,
                       DBO.FNK_FECHA_SIN_HORA(#F.FECHA),DBO.FNK_FECHA_SIN_HORA(#F.FECHA), 'CAJA',@CNSFACJ,
                       CASE WHEN #FD.CONCEPTO = @IDCJDEPCLIATER THEN 'Contab' ELSE NULL END, 
                       CASE WHEN #F.CODUNG = '' THEN NULL ELSE #F.CODUNG END, 
                       CASE WHEN #F.CODPRG = '' THEN NULL ELSE #F.CODPRG END
                FROM #F 
                INNER JOIN #FD ON #F.CNSFACJ = #FD.CNSFACJ 
                INNER JOIN #FDD ON #FD.CNSFACJ = #FDD.CNSFACJ 
                LEFT JOIN FPA ON #FDD.TIPOPAGO = FPA.FORMAPAGO 
                LEFT JOIN CPCJ ON #FD.CONCEPTO = CPCJ.CODIGO
                GROUP BY CPCJ.CUENTA,#F.IDTERCERO,#F.CCOSTO,#F.CNSFACJ,LEFT(#F.AREAPRESTACION,10),#F.CODCAJA,
                         FPA.DESCRIPCION,#FDD.NUMERODOCUMENTO,#F.NOMBRECLIENTE,CPCJ.CODIGO,CPCJ.DESCRIPCION,
                         #F.IDAFILIADO,DBO.FNK_FECHA_SIN_HORA(#F.FECHA),#F.NOADMISION,#FD.IDSERVICIO,#FD.CONCEPTO, 
                         #F.CODUNG, #F.CODPRG
                HAVING SUM((#FDD.VALOR * 100 / #F.VALORTOTAL) * #FD.VALORTOTAL / 100) <> 0

                PRINT 'DEPOSITOS DE CLIENTES A TERCEROS JOSE'
                DECLARE CUR_CXP CURSOR FOR
                SELECT MCHE.IDTERCERO, MCHE.N_FACTURA, MCHE.F_FACTURAREF, MCHE.F_VENCE, 
                       LEFT('CXP POR DEPOSITO A '+RTRIM(LTRIM(TER.RAZONSOCIAL))+' NIT. '+RTRIM(LTRIM(TER.NIT)),255),
                       MCHE.CCOSTO, MCHE.IDAREA, MCHE.CUENTA, MCHE.CLASE_GENERA, SUM(MCHE.VALOR)
                FROM MCHE 
                LEFT JOIN TER ON MCHE.IDTERCERO = TER.IDTERCERO
                WHERE MCHE.NROCOMPROBANTE = @NROCOMPROBANTE 
                  AND MCHE.PROCESO = 'CXP_XDEPCLITER' 
                  AND MCHE.CLASE_GENERA = 'Contab' 
                  AND MCHE.REFERENCIA1 = @CNSFACJ 
                  AND MCHE.REFERENCIA2 = @CODCAJA
                GROUP BY MCHE.IDTERCERO, MCHE.N_FACTURA, MCHE.F_FACTURAREF, MCHE.F_VENCE, 
                         LEFT('CXP POR DEPOSITO A '+RTRIM(LTRIM(TER.RAZONSOCIAL))+' NIT. '+RTRIM(LTRIM(TER.NIT)),255),
                         MCHE.CCOSTO, MCHE.IDAREA, MCHE.CUENTA, MCHE.CLASE_GENERA

                OPEN CUR_CXP
                FETCH NEXT FROM CUR_CXP INTO @IDTERCERO_CXP, @N_FACTURA_CXP, @F_FACTURA_CXP, @F_VENCE_CXP, @OBSERVACION_CXP, 
                                             @CCOSTO_CXP, @IDAREA_CXP, @CUENTA_CXP, @CLASE_GENERA_CXP, @VALOR_CXP
                WHILE @@FETCH_STATUS = 0
                BEGIN   
                    SET @CNSFCXP = SPACE(20)
                    EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FCXP',@CNSFCXP OUTPUT
                    SELECT @CNSFCXP = @SEDE + REPLACE(SPACE(8 - LEN(@CNSFCXP)) + LTRIM(RTRIM(@CNSFCXP)), SPACE(1), 0)
                    PRINT 'Insertando CXP con CNS='+@CNSFCXP
                    EXEC SPK_ADMIN_CXP_CONTAB 
                        @CNSFCXP,
                        @IDTERCERO_CXP,
                        @N_FACTURA_CXP,
                        @F_FACTURA_CXP,
                        @F_VENCE_CXP,
                        @USUARIO,
                        @OBSERVACION_CXP,
                        @COMPANIA,
                        @SYS_COMPUTERNAME,
                        @NROCOMPROBANTE,
                        @VALOR_CXP,     
                        @CCOSTO_CXP,
                        @IDAREA_CXP,  
                        'INSERT',
                        @CUENTA_CXP,
                        1,
                        @CLASE_GENERA_CXP

                    PRINT 'Actualizando Consecutivo de CXP en MCH.' 
                    UPDATE MCHE SET CNSFCXCXP = @CNSFCXP 
                    WHERE MCHE.NROCOMPROBANTE = @NROCOMPROBANTE AND MCHE.PROCESO = 'CXP_XDEPCLITER' AND MCHE.CLASE_GENERA = 'Contab' AND
                          MCHE.REFERENCIA1 = @CNSFACJ AND MCHE.REFERENCIA2 = @CODCAJA AND MCHE.IDTERCERO = @IDTERCERO_CXP AND 
                          MCHE.N_FACTURA = @N_FACTURA_CXP

                    FETCH NEXT FROM CUR_CXP INTO @IDTERCERO_CXP, @N_FACTURA_CXP, @F_FACTURA_CXP, @F_VENCE_CXP, @OBSERVACION_CXP, 
                                                 @CCOSTO_CXP, @IDAREA_CXP, @CUENTA_CXP, @CLASE_GENERA_CXP, @VALOR_CXP
                END
                CLOSE CUR_CXP
                DEALLOCATE CUR_CXP 
            END
        END

        -- COSTO MATERIALES Y MEDICAMENTOS
        PRINT 'Inserta por Servicio COSTO.'
        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                         REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                         ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                         CODUNG, CODPRG)
        SELECT @NROCOMPROBANTE, @COMPANIA, KMCOM.TIPO,DBO.FNK_NC_CUENTA_KMCOM('01',KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,
                                                        KMCOM.CCOSTO,KMCOM.CLASECONT,FCJD.IDSERVICIO,0),
               @IDTERCEROAFI, KMCOM.CCOSTO, 'COSTO DE '+UPPER(IART.IDARTICULO)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
               (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, FCJD.CONCEPTO, NULL, @USUARIO, 
               DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
               'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, 
               CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
        FROM #FD FCJD, KMCOM, IART, #F FCJ
        WHERE IART.IDARTICULO = FCJD.IDSERVICIO AND IART.IDITAR = KMCOM.PREFIJO AND
              KMCOM.IDAREA = FCJ.AREAPRESTACION AND KMCOM.CCOSTO = FCJ.CCOSTO AND KMCOM.IDTIPOCONT = 'COSTOS' AND 
              KMCOM.CLASECONT = 'S' AND KMCOM.TIPO = 'DB' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) > 0

        PRINT 'Inserta Costo NO Configurado por Servicio.'
        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                         REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                         ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                         CODUNG, CODPRG)
        SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 'NO DEF.KMCOM',@IDTERCEROAFI, 
               KMCOM.CCOSTO, 'COSTO DE '+UPPER(IART.IDARTICULO)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
               (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, FCJD.CONCEPTO, NULL, @USUARIO, 
               DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
               'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, 
               CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
        FROM #FD FCJD, KMCOM, IART, #F FCJ
        WHERE IART.IDARTICULO = FCJD.IDSERVICIO AND IART.IDITAR = KMCOM.PREFIJO AND
              KMCOM.IDAREA = FCJ.AREAPRESTACION AND KMCOM.CCOSTO = FCJ.CCOSTO AND KMCOM.IDTIPOCONT = 'COSTOS' AND 
              KMCOM.CLASECONT = 'S' AND KMCOM.TIPO = 'CR' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) > 0 AND
              NOT KMCOM.PREFIJO IN 
                (SELECT PREFIJO FROM KMCOM X WHERE X.IDAREA = FCJ.AREAPRESTACION AND X.CCOSTO = FCJ.CCOSTO AND 
                                             X.IDTIPOCONT = 'COSTOS' AND X.CLASECONT = 'S' AND X.TIPO = 'DB')

        PRINT 'Inserta Agrupado por Prefijo COSTO.'
        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                         REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                         ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                         CODUNG, CODPRG)
        SELECT @NROCOMPROBANTE, @COMPANIA, KMCOM.TIPO,DBO.FNK_NC_CUENTA_KMCOM('01',KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,
                                                        KMCOM.CCOSTO,KMCOM.CLASECONT,'',0), @IDTERCEROAFI, 
               KMCOM.CCOSTO, 'COSTO DE '+UPPER(ITAR.DESCRIPCION)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
               SUM(FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, '', NULL, @USUARIO, 
               DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
               'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, 
               CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
        FROM #FD FCJD, KMCOM, IART, #F FCJ, ITAR
        WHERE IART.IDARTICULO = FCJD.IDSERVICIO AND IART.IDITAR = ITAR.IDITAR AND IART.IDITAR = KMCOM.PREFIJO AND
              KMCOM.IDAREA = FCJ.AREAPRESTACION AND KMCOM.CCOSTO = FCJ.CCOSTO AND KMCOM.IDTIPOCONT = 'COSTOS' AND 
              KMCOM.CLASECONT = 'P' AND KMCOM.TIPO = 'DB' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) > 0
        GROUP BY KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,KMCOM.IDAREA,KMCOM.CCOSTO,KMCOM.CLASECONT,
                 FCJ.IDAFILIADO, FCJ.IDTERCERO,ITAR.DESCRIPCION,FCJ.CODCAJA,FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA),
                 FCJ.CODUNG, FCJ.CODPRG

        PRINT 'Inserta Costo NO Configurado por Servicio.'
        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                         REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                         ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                         CODUNG, CODPRG)
        SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 'NO DEF.KMCOM',@IDTERCEROAFI, 
               KMCOM.CCOSTO, 'COSTO DE '+UPPER(ITAR.DESCRIPCION)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
               SUM(FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, '', NULL, @USUARIO, 
               DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
               'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, 
               CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
        FROM #FD FCJD, KMCOM, IART, #F FCJ, ITAR
        WHERE IART.IDARTICULO = FCJD.IDSERVICIO AND IART.IDITAR = ITAR.IDITAR AND IART.IDITAR = KMCOM.PREFIJO AND
              KMCOM.IDAREA = FCJ.AREAPRESTACION AND KMCOM.CCOSTO = FCJ.CCOSTO AND KMCOM.IDTIPOCONT = 'COSTOS' AND 
              KMCOM.CLASECONT = 'P' AND KMCOM.TIPO = 'CR' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) > 0 AND 
              NOT KMCOM.PREFIJO IN 
                (SELECT PREFIJO FROM KMCOM X WHERE X.IDAREA = FCJ.AREAPRESTACION AND X.CCOSTO = FCJ.CCOSTO AND 
                                                   X.IDTIPOCONT = 'COSTOS' AND X.CLASECONT = 'P' AND X.TIPO = 'DB')
        GROUP BY KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,KMCOM.IDAREA,KMCOM.CCOSTO,KMCOM.CLASECONT,
                 FCJ.IDAFILIADO, FCJ.IDTERCERO,ITAR.DESCRIPCION,FCJ.CODCAJA,FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
                 FCJ.CODUNG, FCJ.CODPRG

        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                         REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                         ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                         CODUNG, CODPRG)
        SELECT @NROCOMPROBANTE, @COMPANIA, KMCOM.TIPO,DBO.FNK_NC_CUENTA_KMCOM('01',KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,
                                                        KMCOM.CCOSTO,KMCOM.CLASECONT,FCJD.IDSERVICIO,0),@IDTERCEROAFI, 
               KMCOM.CCOSTO, 'COSTO DE '+UPPER(IART.IDARTICULO)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
               (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, FCJD.CONCEPTO, NULL, @USUARIO, 
               DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
               'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, 
               CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
        FROM #FD FCJD, KMCOM, IART, #F FCJ
        WHERE IART.IDARTICULO = FCJD.IDSERVICIO AND IART.IDITAR = KMCOM.PREFIJO AND
              KMCOM.IDAREA = FCJ.AREAPRESTACION AND KMCOM.CCOSTO = FCJ.CCOSTO AND KMCOM.IDTIPOCONT = 'COSTOS' AND 
              KMCOM.CLASECONT = 'S' AND KMCOM.TIPO = 'CR' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) > 0

        PRINT 'Inserta Costo NO Configurado por Servicio.'
        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                         REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                         ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                         CODUNG, CODPRG)
        SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 'NO DEF.KMCOM',@IDTERCEROAFI, 
               KMCOM.CCOSTO, 'COSTO DE '+UPPER(IART.IDARTICULO)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
               (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, FCJD.CONCEPTO, NULL, @USUARIO, 
               DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
               'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, 
               CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
        FROM #FD FCJD, KMCOM, IART, #F FCJ
        WHERE IART.IDARTICULO = FCJD.IDSERVICIO AND IART.IDITAR = KMCOM.PREFIJO AND
              KMCOM.IDAREA = FCJ.AREAPRESTACION AND KMCOM.CCOSTO = FCJ.CCOSTO AND KMCOM.IDTIPOCONT = 'COSTOS' AND 
              KMCOM.CLASECONT = 'S' AND KMCOM.TIPO = 'DB' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) > 0 AND
              NOT KMCOM.PREFIJO IN 
                (SELECT PREFIJO FROM KMCOM X WHERE X.IDAREA = FCJ.AREAPRESTACION AND X.CCOSTO = FCJ.CCOSTO AND 
                                             X.IDTIPOCONT = 'COSTOS' AND X.CLASECONT = 'S' AND X.TIPO = 'CR')

        PRINT 'Inserta Agrupado por Prefijo COSTO.'
        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                         REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                         ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                         CODUNG, CODPRG)
        SELECT @NROCOMPROBANTE, @COMPANIA, KMCOM.TIPO,DBO.FNK_NC_CUENTA_KMCOM('01',KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,
                                                        KMCOM.CCOSTO,KMCOM.CLASECONT,'',0),@IDTERCEROAFI, 
               KMCOM.CCOSTO, 'COSTO DE '+UPPER(ITAR.DESCRIPCION)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
               SUM(FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, '', NULL, @USUARIO, 
               DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
               'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, 
               CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
        FROM #FD FCJD, KMCOM, IART, #F FCJ, ITAR
        WHERE IART.IDARTICULO = FCJD.IDSERVICIO AND IART.IDITAR = ITAR.IDITAR AND IART.IDITAR = KMCOM.PREFIJO AND
              KMCOM.IDAREA = FCJ.AREAPRESTACION AND KMCOM.CCOSTO = FCJ.CCOSTO AND KMCOM.IDTIPOCONT = 'COSTOS' AND 
              KMCOM.CLASECONT = 'P' AND KMCOM.TIPO = 'CR' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) > 0
        GROUP BY KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,KMCOM.IDAREA,KMCOM.CCOSTO,KMCOM.CLASECONT,
                 FCJ.IDAFILIADO, FCJ.IDTERCERO,ITAR.DESCRIPCION,FCJ.CODCAJA,FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
                 FCJ.CODUNG, FCJ.CODPRG

        PRINT 'Inserta Costo NO Configurado por Servicio.'
        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                         REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                         ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                         CODUNG, CODPRG)
        SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 'NO DEF.KMCOM',@IDTERCEROAFI, 
               KMCOM.CCOSTO, 'COSTO DE '+UPPER(ITAR.DESCRIPCION)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
               SUM(FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, '', NULL, @USUARIO, 
               DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
               'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
               CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, 
               CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
        FROM #FD FCJD, KMCOM, IART, #F FCJ, ITAR
        WHERE IART.IDARTICULO = FCJD.IDSERVICIO AND IART.IDITAR = ITAR.IDITAR AND IART.IDITAR = KMCOM.PREFIJO 
          AND KMCOM.IDAREA = FCJ.AREAPRESTACION AND KMCOM.CCOSTO = FCJ.CCOSTO AND KMCOM.IDTIPOCONT = 'COSTOS' 
          AND KMCOM.CLASECONT = 'P' AND KMCOM.TIPO = 'DB' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) > 0 
          AND NOT KMCOM.PREFIJO IN 
                (SELECT PREFIJO FROM KMCOM X 
                 WHERE X.IDAREA = FCJ.AREAPRESTACION AND X.CCOSTO = FCJ.CCOSTO 
                   AND X.IDTIPOCONT = 'COSTOS' AND X.CLASECONT = 'P' AND X.TIPO = 'CR')
        GROUP BY KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,KMCOM.IDAREA,KMCOM.CCOSTO,KMCOM.CLASECONT,
                 FCJ.IDAFILIADO, FCJ.IDTERCERO,ITAR.DESCRIPCION,FCJ.CODCAJA,FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
                 FCJ.CODUNG, FCJ.CODPRG

        -- DESDEFTR omite revisión solo cuando el asiento se embebe en comprobante de FACTURA.
        -- Si MCPE es propio del recibo de CAJA, siempre revisar y pasar a MCP.
        IF @DESDEFTR = 1
           AND EXISTS (
                SELECT 1
                FROM MCPE
                WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                  AND PROCEDENCIA = 'CAJA'
                  AND REFERENCIA1 = @CNSFACJ
                  AND REFERENCIA2 = @CODCAJA
           )
        BEGIN
            PRINT 'Comprobante propio de CAJA: se fuerza revisión/pase a MCP aunque DESDEFTR=1'
            SET @DESDEFTR = 0
        END

        IF @DESDEFTR = 0
        BEGIN
            EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME
            EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE, @COM, ''
        END

    END TRY
    BEGIN CATCH
        -- Manejo de errores
        DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrSev INT = ERROR_SEVERITY();
        DECLARE @ErrState INT = ERROR_STATE();

        -- Liberar cursores si est?n abiertos
        IF CURSOR_STATUS('global','CUR_CXP') >= -1
        BEGIN
            CLOSE CUR_CXP;
            DEALLOCATE CUR_CXP;
        END
        IF CURSOR_STATUS('global','CUR_PAGOS') >= -1
        BEGIN
            CLOSE CUR_PAGOS;
            DEALLOCATE CUR_PAGOS;
        END

        -- Eliminar tablas temporales si existen
        IF OBJECT_ID('tempdb..#F') IS NOT NULL DROP TABLE #F;
        IF OBJECT_ID('tempdb..#FD') IS NOT NULL DROP TABLE #FD;
        IF OBJECT_ID('tempdb..#FDD') IS NOT NULL DROP TABLE #FDD;
        IF OBJECT_ID('tempdb..#P') IS NOT NULL DROP TABLE #P;
        IF OBJECT_ID('tempdb..#PH') IS NOT NULL DROP TABLE #PH;

        RAISERROR(@ErrMsg, @ErrSev, @ErrState);
    END CATCH

    -- Limpieza final (aunque SQL Server lo hace autom?ticamente, es buena pr?ctica)
    IF OBJECT_ID('tempdb..#F') IS NOT NULL DROP TABLE #F;
    IF OBJECT_ID('tempdb..#FD') IS NOT NULL DROP TABLE #FD;
    IF OBJECT_ID('tempdb..#FDD') IS NOT NULL DROP TABLE #FDD;
END

