IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_PROXIMONUMEROFACTURA' AND TYPE = 'P')
   DROP PROCEDURE SPK_PROXIMONUMEROFACTURA

GO
CREATE PROCEDURE DBO.SPK_PROXIMONUMEROFACTURA  
@COMPANIA   VARCHAR(2),  
@IDSEDE     VARCHAR(5),  
@CCOSTO     VARCHAR(20) = NULL,
@NUEVOCONSECUTIVO  VARCHAR(20) OUTPUT  
WITH ENCRYPTION
AS 
DECLARE @NVOCONSEC   VARCHAR(20)
DECLARE @LONGFTRARS  INT
DECLARE @PREFIJOFAC  VARCHAR(10)
DECLARE @PRE         VARCHAR(20)
DECLARE @CNSFINAL    INT
DECLARE @CNSINICIAL  INT
DECLARE @CNSACTUAL   INT 
DECLARE @VENCIDA     SMALLINT
DECLARE @CNSNUEVO    INT
DECLARE @SEDEPPAL    VARCHAR(6)
DECLARE @CNSRESOL    VARCHAR(20)
BEGIN  
   DELETE RPDX WHERE CNS = 'N_FACTURA'
   IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI'
   BEGIN
      PRINT 'CON FDIAN'
      IF DBO.FNK_VALORVARIABLE('FACTSEDE')='NO'
      BEGIN
         SELECT @SEDEPPAL=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDSEDEPRINCIPAL')))
         IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@SEDEPPAL)
         BEGIN
            SELECT @SEDEPPAL=IDENTIFICADOR FROM FDIAN WHERE VENCIDA=0 AND PROCEDENCIA = 'FTR'
            IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@SEDEPPAL)
            BEGIN
               SELECT TOP 1 @SEDEPPAL=IDSEDE FROM FTR WHERE COALESCE(IDSEDE,'')<>'' ORDER BY F_FACTURA DESC
            END
         END
         SELECT @IDSEDE=@SEDEPPAL
      END

      SELECT @PREFIJOFAC=COALESCE(PREFIJO,'')
      FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA = 'FTR' 
	  
	  PRINT '@PREFIJOFAC ='+@PREFIJOFAC

	  IF COALESCE(@PREFIJOFAC,'')<>''
	  BEGIN
		SELECT @PRE = '@FTR_'+LTRIM(RTRIM(@PREFIJOFAC))
	  END
	  ELSE
	  BEGIN
		 SELECT @PRE = '@FTR'
	  END
      IF UPPER(DBO.FNK_VALORVARIABLE('MPREFAC_CCOSTO')) <> 'SI'
      BEGIN
         SELECT @CCOSTO=''

		 IF NOT EXISTS(SELECT PREFIJO FROM USCXS WHERE PREFIJO=@PRE)
		 BEGIN
			INSERT INTO USCXS (COMPANIA,IDSEDE,BODEGA,IDADICIONAL,PREFIJO,CONSECUTIVO,SERIE,LIMITE)  
	        VALUES(@COMPANIA,@IDSEDE,'','',@PRE,0,0,0)  
		 END

         SELECT @CNSACTUAL=CONSECUTIVO,@CNSNUEVO=CONSECUTIVO+1  FROM USCXS  
         WHERE PREFIJO=@PRE  AND COMPANIA=@COMPANIA AND IDSEDE=@IDSEDE

         SELECT @PREFIJOFAC=COALESCE(PREFIJO,''),@LONGFTRARS=COALESCE(LONGFTR,0),@CNSINICIAL=CNSINICIAL,@CNSFINAL=CNSFINAL,@VENCIDA=VENCIDA,@CNSRESOL=CNSRESOL
         FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA = 'FTR'
         AND CNSINICIAL<=@CNSNUEVO AND CNSFINAL+1>@CNSNUEVO
         PRINT '@CNSNUEVO='+STR(@CNSNUEVO)
         IF @CNSNUEVO>@CNSFINAL OR @CNSNUEVO<@CNSINICIAL
         BEGIN
            PRINT '@CNSNUEVO='+LTRIM(RTRIM(STR(@CNSNUEVO)))+'@CNSFINAL='+LTRIM(RTRIM(STR(@CNSFINAL)))+'@CNSINICIAL='+LTRIM(RTRIM(STR(@CNSINICIAL)))
            RAISERROR('Se ha terminado los consecutivos de facturacion Habilitados, No se puede Continuar',1,16)
            RETURN
         END
         IF COALESCE(@CNSRESOL,'')=''
         BEGIN
            RAISERROR('NO existe resolucion para este nro de factura, No se puede Continuar',1,16)
            RETURN
         END
         EXEC SPK_PROXIMOCONSECUTIVO @COMPANIA, @IDSEDE, @PRE, @NVOCONSEC OUTPUT 
          PRINT '@NVOCONSEC='+@NVOCONSEC
         IF LEN(@NVOCONSEC) > @LONGFTRARS
         BEGIN
            SET @LONGFTRARS = LEN(@NVOCONSEC)
         END
        -- SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
        -- SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC))+LTRIM(RTRIM(@NVOCONSEC))
      END
      ELSE
      BEGIN
         PRINT 'NUMFACTURA CON CCOSTO'
         SELECT @PRE = '@FTR'  
         SELECT @PREFIJOFAC = IDADICIONAL FROM USCXS WHERE PREFIJO = @PRE AND IDSEDE = LEFT(@CCOSTO,5)        
         EXEC SPK_PROXIMOCONSECUTIVO @COMPANIA, @CCOSTO, @PRE, @NVOCONSEC OUTPUT  
         IF LEN(@NVOCONSEC) > @LONGFTRARS
         BEGIN
            SET @LONGFTRARS = LEN(@NVOCONSEC)
         END
        -- SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
        -- SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC))+LTRIM(RTRIM(@NVOCONSEC))
      END
   END
  ELSE
  BEGIN
      SELECT @LONGFTRARS = DBO.FNK_VALORVARIABLE('LONGFTRARS')                 
      IF (@LONGFTRARS = 0 OR @LONGFTRARS IS NULL OR @LONGFTRARS='')
      BEGIN
         SELECT @LONGFTRARS = 8
      END
      IF UPPER(DBO.FNK_VALORVARIABLE('MPREFIJOFAC')) = 'SI'
      BEGIN
         PRINT 'MANEJO PREFIJO FAC'
         IF UPPER(DBO.FNK_VALORVARIABLE('MPREFAC_CCOSTO')) = 'SI'
         BEGIN
            PRINT 'NUMFACTURA CON CCOSTO'
            SELECT @PRE = '@FTR'            
            SELECT @PREFIJOFAC = IDADICIONAL FROM USCXS WHERE PREFIJO = @PRE AND IDSEDE = LEFT(@CCOSTO,5)        
            EXEC SPK_PROXIMOCONSECUTIVO @COMPANIA, @CCOSTO, @PRE, @NVOCONSEC OUTPUT  
            IF LEN(@NVOCONSEC) > @LONGFTRARS
            BEGIN
               SELECT @LONGFTRARS = LEN(@NVOCONSEC)
            END
            IF COALESCE(DBO.FNK_VALORVARIABLE('FTRQUITACEROS'),'')<>'SI'
            BEGIN 
               SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC)) + LTRIM(RTRIM(@NVOCONSEC))
            END
            ELSE
            BEGIN
               SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC)) + LTRIM(RTRIM(@NVOCONSEC))
            END         
         END
         ELSE
         BEGIN           
            IF @IDSEDE = '01'
            BEGIN
               SELECT @PREFIJOFAC = DBO.FNK_VALORVARIABLE('PREFIJOFAC')
            END
            ELSE
            BEGIN
               SELECT @PREFIJOFAC = DBO.FNK_VALORVARIABLE('PREFIJOFAC_'+LTRIM(RTRIM(@IDSEDE)))
            END
            PRINT 'PREFIJOFAC = '+ @PREFIJOFAC
         
            SET @PRE = '@FTR_'+LTRIM(RTRIM(@PREFIJOFAC))
            EXEC SPK_PROXIMOCONSECUTIVO @COMPANIA, @IDSEDE, @PRE, @NVOCONSEC OUTPUT  
            IF LEN(@NVOCONSEC) > @LONGFTRARS
            BEGIN
               SET @LONGFTRARS = LEN(@NVOCONSEC)--FTRQUITACEROS
            END
            --IF COALESCE(DBO.FNK_VALORVARIABLE('FTRQUITACEROS'),'')<>'SI'
            --BEGIN
            --   SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
            --   SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC))+LTRIM(RTRIM(@NVOCONSEC))
            --END
            --ELSE
            --BEGIN
            --   SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC))+LTRIM(RTRIM(@NVOCONSEC))
            --END       
         END
      END
      ELSE
      BEGIN
         PRINT 'NO MANEJA PREFIJO'     
         EXEC SPK_PROXIMOCONSECUTIVO @COMPANIA,@IDSEDE,'@FTR', @NVOCONSEC OUTPUT  
         IF LEN(@NVOCONSEC) > @LONGFTRARS
         BEGIN
            SET @LONGFTRARS = LEN(@NVOCONSEC)
         END
         --IF COALESCE(DBO.FNK_VALORVARIABLE('FTRQUITACEROS'),'')<>'SI'
         --BEGIN      
         --   SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         --END
      END 
   END      
 
   SELECT  @NUEVOCONSECUTIVO=@NVOCONSEC

END

