CREATE OR ALTER PROCEDURE DBO.SPK_APL_AJDEPRECIACION 
     @COMPANIA           VARCHAR(2),
     @SEDE               VARCHAR(5),
     @ANO                VARCHAR(4),
     @MES                INT,
     @USUARIO            VARCHAR(12),
     @SYS_COMPUTERNAME   VARCHAR(255),
     @NROCOMPROBANTE     VARCHAR(20)=NULL
WITH ENCRYPTION
AS
DECLARE @NROREFERENCIA   VARCHAR(20)
DECLARE @PRE             VARCHAR(20)
DECLARE @CUENTA_AJ_CUR   VARCHAR(16)
DECLARE @NATURALEZA_CUR  VARCHAR(2)
DECLARE @VALOR_CUR       DECIMAL(14,2)
DECLARE @FECHACONTABLE	 DATETIME
DECLARE @IDMODELOCONT    VARCHAR(2)
DECLARE @CON_ACTFIJO_CONTAXCC VARCHAR(2)
DECLARE @COM              VARCHAR(6)
DECLARE @NOREFERENCIA     VARCHAR(20)
DECLARE @PREFIJO_USCXS    VARCHAR(10)
DECLARE @IDTERCERO        VARCHAR(20)
BEGIN
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
   SET @CON_ACTFIJO_CONTAXCC = DBO.FNK_VALORVARIABLE('CON_ACTFIJO_CONTAXCC')
   SET @IDTERCERO = DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
   -- �ltimo d�a del per�odo contable (ej. ANO=2026, MES=3 ? 31/03/2026)
   SET @FECHACONTABLE = EOMONTH(DATEFROMPARTS(CAST(@ANO AS INT), @MES, 1))

   SELECT * INTO #IACTDIS FROM IACTDIS WHERE
   ANIO=@ANO AND MES=@MES

   
   --DELETE MCH WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND PROCESO='AJDEPRECIACION' AND PROCEDENCIA='AJDEP'
   IF COALESCE(@NROCOMPROBANTE,'')=''
   BEGIN
      SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      PRINT '@NROCOMPROBANTE:' + COALESCE(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      PRINT '@NROCOMPROBANTE:' + COALESCE(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD

      IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
      BEGIN
         SELECT @COM = RTRIM(LTRIM(COMMS.COMPROBANTE)) FROM COMMS WHERE IDSEDE = @SEDE AND COMMS.CLASE = 'DEPRECIACION' 
         IF @COM IS NULL
            SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEPR')))
      END
      ELSE
      BEGIN
         SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEPR')))
      END
      
      SET @PREFIJO_USCXS='@COM'+@COM
      SET @NOREFERENCIA=SPACE(20)
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
      SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
      PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA


      INSERT INTO MCPE (NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                           TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                           COMPROBANTE, IDTERCERO, ANULADO)
      SELECT @NROCOMPROBANTE,@COMPANIA,'AJDEP',@NOREFERENCIA,@ANO,@MES,@FECHACONTABLE,0,0 
      ,'','',@USUARIO,GETDATE(),'','DEPRECIACION GENERADA PARA LOS ACTIVOS DEL PERIDO CONTABLE '+@ANO+' '+CONVERT(VARCHAR,@MES), 
      @SEDE,0,DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEPR'),DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),0
   END
   IF (SELECT COUNT(*) FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)>0
   BEGIN
      INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                        REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                        RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
      SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, @FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                        REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                        RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
      FROM   MCP
      WHERE NROCOMPROBANTE=@NROCOMPROBANTE
      --se borran de mcp, mch
      DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
      DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE
   END
   ELSE
   BEGIN
      DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   END
   -- feature/IXCOLO338 -- 2026-09-05 -- Reabrir IACTD del comprobante por NROCOMPROBANTE; no exigir MCHE
   IF COALESCE(@NROCOMPROBANTE, '') <> ''
   BEGIN
      UPDATE IACTD
      SET CONTABILIZADA = 0
      FROM IACTD
      INNER JOIN IACT ON IACT.IDACTIVO = IACTD.IDACTIVO
      WHERE IACT.DEPRECIABLE = 1
        AND LTRIM(RTRIM(COALESCE(IACTD.NROCOMPROBANTE, ''))) = LTRIM(RTRIM(@NROCOMPROBANTE))
        AND YEAR(IACTD.FECHA) = @ANO
        AND MONTH(IACTD.FECHA) = @MES
        AND UPPER(LTRIM(RTRIM(COALESCE(IACTD.CLASE, '')))) <> 'NIIF'
   END
   -- DEBITO
   INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
               REFERENCIA1 ,REFERENCIA2 ,ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, 
               PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 
         DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT,'DEPRECIACION','DB',IACT.IDTIPOACTIVO,IACT.IDAREA,IACT.CCOSTO,'P',IACT.IDACTIVO),
         @IDTERCERO, IACT.CCOSTO, 'ACTIVO No. '+IACT.IDACTIVO+' - '+RTRIM(IACTT.DESCRIPCION)+', '+IACT.DESCRIPCION, 
         VALORDEPRECIADO, IACT.IDACTIVO, LEFT(TRIM(COALESCE(IACT.REFERENCIA, '')), 20),--IACT.REFERENCIA, 
         NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 
         IACT.IDTIPOACTIVO, IACT.IDAREA, 'P', 1, 'AJDEPRECIACION', 'Movimiento','AJDEP',@ANO+LTRIM(STR(@MES)),
         IACT.CODUNG, IACT.CODPRG
   FROM IACTD INNER JOIN  IACT ON IACTD.IDACTIVO=IACT.IDACTIVO AND YEAR(IACTD.FECHA)=@ANO AND MONTH(IACTD.FECHA)=@MES 
                                  AND COALESCE(IACTD.CONTABILIZADA,0)=0
              INNER JOIN  IACTT ON IACTT.IDTIPOACTIVO=IACT.IDTIPOACTIVO
   WHERE IACT.DEPRECIABLE = 1 AND IACT.IDACTIVO 
         NOT IN(SELECT #IACTDIS.IDACTIVO FROM #IACTDIS)
         AND COALESCE(IACT.ESTADO,'')<>'02'
         AND COALESCE(IACTD.VALORDEPRECIADO,0)>0
         AND UPPER(LTRIM(RTRIM(COALESCE(IACTD.CLASE, '')))) <> 'NIIF'

   -- CREDITO
   INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
               REFERENCIA1 ,REFERENCIA2 ,ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, 
               PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT,'DEPRECIACION','CR',IACT.IDTIPOACTIVO,IACT.IDAREA,IACT.CCOSTO,'P',IACT.IDACTIVO), 
         @IDTERCERO, IACT.CCOSTO, 'DEPRECIACION ACUMULADA: '+IACTT.DESCRIPCION, 
         SUM(VALORDEPRECIADO), IACT.IDACTIVO,LEFT(TRIM(COALESCE(IACT.REFERENCIA, '')), 20), --IACT.REFERENCIA, 
         NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 
         IACT.IDTIPOACTIVO, IACT.IDAREA, 'P', 1, 'AJDEPRECIACION', 'Movimiento','AJDEP',@ANO+LTRIM(STR(@MES)),
         IACT.CODUNG, IACT.CODPRG
   FROM IACTD INNER JOIN IACT ON IACTD.IDACTIVO=IACT.IDACTIVO AND YEAR(IACTD.FECHA)=@ANO AND MONTH(IACTD.FECHA)=@MES 
                                 AND COALESCE(IACTD.CONTABILIZADA,0)=0
              INNER JOIN  IACTT ON IACTT.IDTIPOACTIVO=IACT.IDTIPOACTIVO
   WHERE IACT.DEPRECIABLE = 1 AND IACT.IDACTIVO NOT IN(SELECT #IACTDIS.IDACTIVO FROM #IACTDIS)
   AND COALESCE(IACT.ESTADO,'')<>'02'
   AND COALESCE(IACTD.VALORDEPRECIADO,0)>0
   AND UPPER(LTRIM(RTRIM(COALESCE(IACTD.CLASE, '')))) <> 'NIIF'
   GROUP BY IACTT.DEPRECIACION,IACT.IDAREA,IACT.CCOSTO,IACT.IDACTIVO,IACT.IDTIPOACTIVO, 
            IACT.CODUNG, IACT.CODPRG, IACTT.DESCRIPCION, IACT.IDACTIVO, IACT.REFERENCIA

  ----------------------------------------------------------------------------------
  -- CONTABILIZACION SEGUN DISTRIBUCION IACTDIS.
  ----------------------------------------------------------------------------------

  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
              REFERENCIA1 ,REFERENCIA2 ,ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, 
              PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
  SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 
         DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT,'DEPRECIACION','DB',IACT.IDTIPOACTIVO,IACTDIS.CUENTA,IACTDIS.CCOSTO,'P',IACT.IDACTIVO),
         '', IACTDIS.CCOSTO, 'ACTIVO No. '+IACT.IDACTIVO+' - '+RTRIM(IACTT.DESCRIPCION)+', '+IACT.DESCRIPCION, 
        SUM(VALORDEPRECIADO) * (IACTDIS.PORCENTAJE /100)
        , IACTD.IDACTIVO, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 
         IACT.IDTIPOACTIVO, IACTDIS.CUENTA, 'P', 1, 'AJDEPRECIACION', 'Movimiento','AJDEP',@ANO+LTRIM(STR(@MES)),
         IACT.CODUNG, IACT.CODPRG
  FROM IACTD INNER JOIN IACT ON IACTD.IDACTIVO=IACT.IDACTIVO AND YEAR(IACTD.FECHA)=@ANO 
                                AND MONTH(IACTD.FECHA)=@MES AND COALESCE(IACTD.CONTABILIZADA,0)=0 
             INNER JOIN IACTT ON IACTT.IDTIPOACTIVO=IACT.IDTIPOACTIVO
	          INNER JOIN IACTDIS ON IACTDIS.IDACTIVO = IACT.idactivo AND IACTDIS.ANIO =YEAR(IACTD.FECHA) AND  IACTDIS.MES = MONTH(IACTD.FECHA)
  WHERE IACT.DEPRECIABLE = 1 AND  IACT.IDACTIVO IN(SELECT #IACTDIS.IDACTIVO FROM #IACTDIS)
  AND COALESCE(IACT.ESTADO,'')<>'02'
  AND COALESCE(IACTD.VALORDEPRECIADO,0)>0
  AND UPPER(LTRIM(RTRIM(COALESCE(IACTD.CLASE, '')))) <> 'NIIF'
  GROUP BY IACT.IDTIPOACTIVO,IACT.IDAREA, IACTDIS.CUENTA,IACTDIS.CCOSTO,IACTDIS.IDACTIVO,IACTT.DESCRIPCION,
		IACT.DESCRIPCION,IACTDIS.PORCENTAJE,IACTD.IDACTIVO,IACT.CODUNG,
		IACT.CODPRG,IACT.IDACTIVO

  -- CREDITO
   INSERT INTO MCHE (NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
               REFERENCIA1 ,REFERENCIA2 ,ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, 
               PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT,'DEPRECIACION','CR',IACT.IDTIPOACTIVO,IACTDIS.CUENTA,IACTDIS.CCOSTO,'P',IACT.IDACTIVO), 
         '', IACTDIS.CCOSTO, 'DEPREC. ACU.'+IACT.IDACTIVO+' - '+RTRIM(IACTT.DESCRIPCION)+', '+IACT.DESCRIPCION, 
         SUM(VALORDEPRECIADO) * (IACTDIS.PORCENTAJE /100), IACTD.IDACTIVO, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 
         IACT.IDTIPOACTIVO, IACTDIS.CUENTA, 'P', 1, 'AJDEPRECIACION', 'Movimiento','AJDEP',@ANO+LTRIM(STR(@MES)),
         IACT.CODUNG, IACT.CODPRG
   FROM IACTD INNER JOIN IACT ON IACTD.IDACTIVO=IACT.IDACTIVO AND YEAR(IACTD.FECHA)=@ANO AND MONTH(IACTD.FECHA)=@MES 
                                 AND COALESCE(IACTD.CONTABILIZADA,0)=0 
              INNER JOIN IACTT ON IACTT.IDTIPOACTIVO=IACT.IDTIPOACTIVO
	           INNER JOIN 	IACTDIS ON IACTDIS.IDACTIVO = IACT.idactivo AND IACTDIS.ANIO =YEAR(IACTD.FECHA) 
                           AND  IACTDIS.MES = MONTH(IACTD.FECHA)

   WHERE IACT.DEPRECIABLE = 1 AND IACT.idactivo IN(SELECT #IACTDIS.IDACTIVO FROM #IACTDIS)
   AND COALESCE(IACT.ESTADO,'')<>'02'
   AND COALESCE(IACTD.VALORDEPRECIADO,0)>0
   AND UPPER(LTRIM(RTRIM(COALESCE(IACTD.CLASE, '')))) <> 'NIIF'
   GROUP BY IACT.IDTIPOACTIVO,IACT.IDAREA,IACTDIS.CCOSTO,IACTDIS.IDACTIVO,IACTT.DESCRIPCION,
	      IACT.DESCRIPCION,IACTDIS.PORCENTAJE,IACTD.IDACTIVO,IACT.CODUNG,
	      IACT.CODPRG,IACT.IDACTIVO, IACTDIS.CUENTA

   ----------------------------------------------------------------------------------
   --FIN CONTABILIZACION SEGUN DISTRIBUCION IACTDIS.
   ----------------------------------------------------------------------------------

   PRINT 'Poniendo Estado de CONTABILIZADA en 1 a IACTD'
   UPDATE IACTD SET  CONTABILIZADA  = 1,NROCOMPROBANTE = @NROCOMPROBANTE
   FROM IACTD INNER JOIN IACT ON IACTD.IDACTIVO=IACT.IDACTIVO AND YEAR(IACTD.FECHA)=@ANO AND MONTH(IACTD.FECHA)=@MES 
                                 AND COALESCE(IACTD.CONTABILIZADA,0)=0 
              INNER JOIN IACTT ON IACTT.IDTIPOACTIVO=IACT.IDTIPOACTIVO
   WHERE IACT.DEPRECIABLE = 1
   AND IACTD.CLASE<>'Niif'

   UPDATE IACT SET FECHAULTDEPRECIACION = @FECHACONTABLE, DEPACUMHISTORICA     = IACTD.DEPACUMHISTORICA,
                   DEPACUMDIFERIDA      = IACTD.DEPACUMDIFERIDA, MESESDEPRECIADOS     = IACTD.MESESDEPRECIADOS
   FROM IACT INNER JOIN ( SELECT IDACTIVO            = IDACTIVO,
                           MESESDEPRECIADOS    = MAX(ITEM), 
                           DEPACUMHISTORICA    = SUM(DEPACUMHISTORICA), 
                           DEPACUMDIFERIDA     = SUM(DEPACUMDIFERIDA) 
                     FROM IACTD 
                     WHERE IACTD.NROCOMPROBANTE = @NROCOMPROBANTE
                     GROUP BY IACTD.IDACTIVO) AS IACTD ON IACTD.IDACTIVO=IACT.IDACTIVO 
             INNER JOIN IACTT ON IACTT.IDTIPOACTIVO=IACT.IDTIPOACTIVO
   WHERE IACT.DEPRECIABLE = 1
   AND COALESCE(IACT.ESTADO,'')<>'02'

   PRINT 'Actulizando Debitos y Creditos de MCP'
   EXEC SPK_NC_REVISAMCPE  @NROCOMPROBANTE,@COMPANIA,@USUARIO,@SEDE,@SYS_COMPUTERNAME
   DROP TABLE #IACTDIS
END

