CREATE OR ALTER PROCEDURE DBO.SPK_FACTURACE_ESCMA
@CNSRPDX       VARCHAR(20),
@NIT           VARCHAR(20),
@COMPANIA      VARCHAR(2),
@IDSEDE        VARCHAR(5),
@USUARIO       VARCHAR(12),
@IDTERCERO     VARCHAR(20),
@IDPLAN        VARCHAR(6),
@OBSERVACION   VARCHAR(255),
@IDTERCEROCA1  VARCHAR(20), 
@NOREFERENCIA  VARCHAR(20) = 'VARIOS',
@TFECHA        SMALLINT = 0,
@FECHAFAC      DATETIME = NULL
WITH ENCRYPTION
AS 
DECLARE @CNSFTR            VARCHAR(20),   @PRE          VARCHAR(20),   @CONSECFTR         INT,           @CNSRESOL          VARCHAR(50)
DECLARE @NVOCONSEC         VARCHAR(20),   @DATO         VARCHAR(80),   @DATO1             VARCHAR(80),   @DV                INT
DECLARE @DATO3             VARCHAR(20),   @DATO2        VARCHAR(80),   @VRTOTAL           DECIMAL(14,2), @VRSERV            DECIMAL(14,2) 
DECLARE @VRCOPA            DECIMAL(14,2), @VRPACO       DECIMAL(14,2), @OK                INT,           @OK1               INT
DECLARE @DESCUENTO         DECIMAL(14,2), @VRDTO        DECIMAL(14,2), @VRABONO           DECIMAL(14,2), @TTEC              VARCHAR(10)
DECLARE @DATOCCOSTO        VARCHAR(80),   @IDTERCEROCA  VARCHAR(20),   @SYS_COMPUTERNAME  VARCHAR(254),  @NODESCUENTACOPAGO SMALLINT
DECLARE @MABONO            SMALLINT,      @PABONO       DECIMAL(18,6), @IDAFILIADO        VARCHAR(20),   @CLASEFACTURA      VARCHAR(3)
DECLARE @CUENTACXC         VARCHAR(16),   @NUMTER       INT,		   @LIBERADA		  SMALLINT,		 @CANTAFI			INT
DECLARE @BASE_IVA_SER      VARCHAR(20),   @VIVA			DECIMAL(14,2), @PIVA              DECIMAL(14,2), @MIVA				SMALLINT
DECLARE @IDFORMATOFTR      VARCHAR(20)
BEGIN
	SELECT @BASE_IVA_SER = DATO FROM USVGS WHERE IDVARIABLE='BASE_IVA_SERVICIOS'

   SET @SYS_COMPUTERNAME = HOST_NAME()
   SELECT @DATOCCOSTO = DATO FROM USVGS WHERE IDVARIABLE = 'CCOSTOENPRESTACION'
   IF @NOREFERENCIA <> 'VARIOS'
   BEGIN
      IF LEFT(@NOREFERENCIA,2) = 'AT' 
      BEGIN
         PRINT 'AT'+ SUBSTRING(@NOREFERENCIA,3,18)
         SELECT @IDAFILIADO = IDAFILIADO FROM HACTRAN WHERE CNSHACTRAN = SUBSTRING(@NOREFERENCIA,3,18)

         IF EXISTS(SELECT * FROM FTR WHERE NOREFERENCIA=@NOREFERENCIA AND IDAFILIADO=@IDAFILIADO AND ESTADO='L')
         BEGIN
            SELECT @LIBERADA=1, @NVOCONSEC=N_FACTURA, @CNSFTR=CNSFCT FROM FTR WHERE NOREFERENCIA=@NOREFERENCIA AND IDAFILIADO=@IDAFILIADO AND ESTADO='L'
         END

         SELECT @CLASEFACTURA = 'AT'
         IF ISNULL(@IDTERCERO,'') = ''
         BEGIN
            SELECT TOP 1 @IDTERCERO = IDTERCEROCA
            FROM   CIT 
            WHERE  MARCAFAC   = 1 
            AND    CNSFACT    = @CNSRPDX 
            AND    CNSHACTRAN = SUBSTRING(@NOREFERENCIA,3,18)
         END
         IF ISNULL(@IDPLAN,'') = ''
         BEGIN
            SELECT TOP 1 @IDPLAN = IDPLAN
            FROM   AUT
            WHERE  MARCAFAC   = 1 
            AND    CNSFACT    = @CNSRPDX 
            AND    CNSHACTRAN = SUBSTRING(@NOREFERENCIA,3,18)            
         end
         IF ISNULL(@IDPLAN,'') = ''
         BEGIN
            SELECT TOP 1 @IDPLAN = IDPLAN
            FROM   CIT
            WHERE  MARCAFAC   = 1 
            AND    CNSFACT    = @CNSRPDX 
            AND    CNSHACTRAN = SUBSTRING(@NOREFERENCIA,3,18)            
         end
      END
      ELSE
      BEGIN
         IF @NOREFERENCIA = 'CEUNIFICADO'
		 BEGIN
            SELECT @CLASEFACTURA = 'CEU'
			   IF EXISTS(SELECT * FROM FTR WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND NOREFERENCIA=@NOREFERENCIA AND ESTADO='L')
			   BEGIN
			      SELECT @LIBERADA=1, @NVOCONSEC=N_FACTURA, @CNSFTR=CNSFCT FROM FTR WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND NOREFERENCIA=@NOREFERENCIA AND ESTADO='L'
			   END
         END
		 ELSE
         BEGIN
            IF @NOREFERENCIA = 'CEUNIFPE'
            BEGIN
			      PRINT 'CUE'
				  SELECT @CLASEFACTURA = 'CUE'
			      IF EXISTS(SELECT * FROM FTR WHERE IDTERCERO=@IDTERCERO AND IDAFILIADO=@IDTERCEROCA1 AND NOREFERENCIA=@NOREFERENCIA AND ESTADO='L')
			      BEGIN
			         SELECT @LIBERADA=1, @NVOCONSEC=N_FACTURA, @CNSFTR=CNSFCT FROM FTR WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND NOREFERENCIA=@NOREFERENCIA AND IDAFILIADO=@IDTERCEROCA1 AND ESTADO='L'
			      END
               SELECT @IDAFILIADO = @IDTERCEROCA1
            END
            ELSE
            BEGIN
               SELECT @CLASEFACTURA = 'ACE'
               SELECT @IDAFILIADO = IDAFILIADO FROM HADCE WHERE NOADMISIONCE = @NOREFERENCIA
            END
         END
      END
   END
   ELSE
   BEGIN  -- = 'VARIOS'
	  IF EXISTS(SELECT * FROM FTR WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND NOREFERENCIA=@NOREFERENCIA AND ESTADO='L')
	  BEGIN
		  SELECT @LIBERADA=1, @NVOCONSEC=N_FACTURA, @CNSFTR=CNSFCT FROM FTR WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND NOREFERENCIA=@NOREFERENCIA AND ESTADO='L'
	  END
      print 'estoy en VARIOS'
      IF ISNULL(@IDPLAN,'') = ''
      BEGIN
         RAISERROR('NO SE ESCOGIO PLAN DE FACTURACION.',16,1)
         RETURN
      END
   END
   IF ISNULL(@IDPLAN,'') = ''
   BEGIN
      SELECT TOP 1 @IDPLAN = ID1 FROM RPDX WHERE CNS = @CNSRPDX
   END
   
   SELECT @DV = DIASVTO, @TTEC= TIPOTERCONTABLE, @NODESCUENTACOPAGO = NODESCUENTACOPAGO,
          @MABONO = MABONO, @PABONO = PABONO
   FROM   PPT  
   WHERE  IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN
   
   SELECT @CUENTACXC = CUENTA FROM TTEC
   WHERE TIPO = @TTEC
   
   IF @DV IS NULL 
      SELECT @DV = 30
   IF @DV = 0
      SELECT @DV = 30
   
   SELECT @DATO3 = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'     
   SELECT @DATO2 = DATO FROM USVGS WHERE IDVARIABLE = 'IDMONEDABASE'
   
   CREATE TABLE #FTRD1(CNSFTR VARCHAR(40), N_CUOTA	INT IDENTITY, FECHA DATETIME,
                DB_CR VARCHAR(2), AREAPRESTACION VARCHAR(20), UBICACION VARCHAR(16),
                VR_TOTAL FLOAT, IMPUTACION VARCHAR(16), CCOSTO VARCHAR (20),
                PREFIJO VARCHAR(6), ANEXO VARCHAR(1024), REFERENCIA VARCHAR(40), 
                IDCIRUGIA VARCHAR(20), CANTIDAD SMALLINT, VALOR DECIMAL(14,2),
                VLR_SERVICI DECIMAL(14,2), VLR_COPAGOS DECIMAL(14,2),
                VLR_PAGCOMP DECIMAL(14,2), IDPROVEEDOR VARCHAR(20),
                NOADMISION VARCHAR(16), NOPRESTACION	VARCHAR(16), NOITEM INT,	
                AREAFUNCONT VARCHAR(20), N_FACTURA VARCHAR(16),
                SUBCCOSTO VARCHAR(4), PCOSTO	DECIMAL(14,2), FECHAPREST DATETIME, PROCEDENCIA VARCHAR(10),
				IDCLASE VARCHAR(10), ITEM SMALLINT, VLRIMPUESTO DECIMAL(14,2), 
				PIVA DECIMAL(14,2), VIVA DECIMAL(14,2), CUENTA_FIMPDV DECIMAL(14, 0),
				IDIMPUESTO VARCHAR(10),TCOPAGO VARCHAR(20))
   
   UPDATE AUT SET VALORCOPAGO = 0  
   WHERE  AUT.CNSFACT  = @CNSRPDX
   AND    AUT.MARCAFAC = 1
   AND    VALORCOPAGO IS NULL
   
   UPDATE AUT SET VALORTOTAL = 0  
   WHERE  AUT.CNSFACT    = @CNSRPDX
   AND    AUT.MARCAFAC   = 1
   AND    VALORTOTAL IS NULL
-- 
   SELECT @OK1 = ISNULL(COUNT(*) ,0)
   FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT       = AUT.IDAUT 
  --             LEFT JOIN TER  ON AUTD.IDTERCEROCA = TER.IDTERCERO
   WHERE  AUT.CNSFACT = @CNSRPDX 
   AND    (AUT.FACTURADA = 0 OR AUT.FACTURADA IS NULL OR AUT.FACTURADA=2) 
   AND    AUT.MARCAFAC = 1 
   AND    (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL) 
   AND    (AUTD.IDTERCEROCA = ( CASE @CLASEFACTURA WHEN  'CUE' THEN @IDTERCERO ELSE  CASE WHEN @IDTERCEROCA1='' THEN @IDTERCEROCA ELSE AUTD.IDTERCEROCA END END))
   AND    AUT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDTERCEROCA1 ELSE AUT.IDAFILIADO END
   
   IF @OK1 = 0  --SE ENTRA AQUI CUANDO ES UNA UNIFICADA CE Y CI  Y NO TIENE AUTDS PARA CREAR LA FTR SI EXISTEN DATOS EN CIT
   BEGIN
      PRINT 'CON 0 ITEMES EN AUTD'
      IF @CLASEFACTURA = 'AT'      
      BEGIN  
         PRINT 'AC TRAN CREA FACTURA SIN HIJOS PARA DEJAR LISTO FTR PARA LOS DATOS DE CIT'
         SELECT TOP 1 @IDTERCEROCA = IDTERCEROCA, @IDAFILIADO = IDAFILIADO 
         FROM   CIT 
         WHERE  MARCAFAC   = 1 
         AND    CNSFACT    = @CNSRPDX 
         AND    CNSHACTRAN = SUBSTRING(@NOREFERENCIA,3,18)
         
		   
         IF  COALESCE(@LIBERADA,0)=0
         BEGIN        
			   SET @CNSFTR = SPACE(20)
			   EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
			   SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0 )
			   SET @NVOCONSEC = SPACE(20)
			   EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT
         END

         IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI'
         BEGIN
            EXEC SPK_PREFIJOFACTURA @COMPANIA, @IDSEDE, @PRE OUTPUT  
            SELECT @CONSECFTR = CONSECUTIVO FROM USCXS WHERE COMPANIA = '01' AND IDSEDE = @IDSEDE AND PREFIJO = @PRE
            SELECT @CNSRESOL  = CNSRESOL FROM FDIAN WHERE IDENTIFICADOR = @IDSEDE AND VENCIDA = 0 AND PROCEDENCIA = 'FTR' AND PREFIJO=REPLACE(@PRE,'@FTR_','')
         END
         
         IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>'')
         BEGIN
             SELECT @IDFORMATOFTR=IDFORFTRCE  FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>''
         END
         ELSE
         BEGIN
             SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
         END

         IF  COALESCE(@LIBERADA,0)=0
         BEGIN
			   INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
				 		 VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
						 IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
						 TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
						 INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
						 IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
						 MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
						 CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,IDSEDE, RDIAN, CNSRESOL, IDFORMATO)
			   SELECT @CNSFTR, @COMPANIA, 'C', @IDTERCEROCA, @NVOCONSEC, 
					CASE @TFECHA 
					   WHEN 1 THEN @FECHAFAC 
					   ELSE GETDATE() 
					END, 
					CASE @TFECHA 
					   WHEN 1 THEN @FECHAFAC + @DV 
					   ELSE GETDATE() + @DV 
					END,
					0, NULL, NULL, LEFT(@DATO2,2), NULL, 'P', NULL, @IDAFILIADO, @USUARIO, @NOREFERENCIA,
					'CI', CASE ISNULL(@CLASEFACTURA,'') WHEN 'ACE' THEN 'I'
														ELSE 'M'
						  END, @OBSERVACION, 'Credito', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO,
					GETDATE(), 0, 0, 
					0, 
					@IDPLAN, NULL, 'C', NULL, NULL, NULL, @DATO3, @TTEC, @CUENTACXC,@IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''), @IDFORMATOFTR
         END
         ELSE
         BEGIN
            UPDATE FTR SET ESTADO='P',CONTABILIZADA=0, NROCOMPROBANTE=NULL, IDTERCERO=@IDTERCEROCA, IDPLAN=@IDPLAN, CUENTACXC=@CUENTACXC, TIPOTTEC=@TTEC, IDFORMATO=@IDFORMATOFTR
            WHERE N_FACTURA=@NVOCONSEC AND CNSFCT=@CNSFTR AND ESTADO='L'
         END

         INSERT INTO HACTRANF (CNSHACTRAN, N_FACTURA, CNS ) 
         SELECT DISTINCT SUBSTRING(@NOREFERENCIA,3,18), @NVOCONSEC, @CNSRPDX
      END 
      ELSE
      BEGIN
         IF @CLASEFACTURA = 'CEU'   --- FACTURACION DE CE UNIFICADA (CIT + AUT)
         BEGIN
            IF (SELECT COUNT(*) FROM CIT 
                WHERE  MARCAFAC   = 1 
                AND    CNSFACT    = @CNSRPDX) > 0
            BEGIN
               SELECT TOP 1 @IDTERCEROCA = IDTERCEROCA, @IDAFILIADO = IDAFILIADO 
               FROM   CIT 
               WHERE  MARCAFAC   = 1 
               AND    CNSFACT    = @CNSRPDX 
               IF  COALESCE(@LIBERADA,0)=0
			      BEGIN        
			         SET @CNSFTR = SPACE(20)
			         EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
			         SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0 )
               
			         SET @NVOCONSEC = SPACE(20)
			         EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT
			      END

               IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI'
               BEGIN
                  EXEC SPK_PREFIJOFACTURA @COMPANIA, @IDSEDE, @PRE OUTPUT  
                  SELECT @CONSECFTR = CONSECUTIVO FROM USCXS WHERE COMPANIA = '01' AND IDSEDE = @IDSEDE AND PREFIJO = @PRE
                  SELECT @CNSRESOL  = CNSRESOL FROM FDIAN WHERE IDENTIFICADOR = @IDSEDE AND VENCIDA = 0 AND PROCEDENCIA = 'FTR' AND PREFIJO=REPLACE(@PRE,'@FTR_','')
               END
         
                 IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>'')
                 BEGIN
                     SELECT @IDFORMATOFTR=IDFORFTRCE  FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>''
                 END
                 ELSE
                 BEGIN
                     SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
                 END

			      IF  COALESCE(@LIBERADA,0)=0
			      BEGIN
				      INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
								      VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
								      IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
								      TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
								      INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
								      IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
								      MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
								      CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,IDSEDE, RDIAN, CNSRESOL, IDFORMATO)
				      SELECT @CNSFTR, @COMPANIA, 'C', @IDTERCEROCA, @NVOCONSEC, 
					   CASE @TFECHA 
					  	    WHEN 1 THEN @FECHAFAC 
							    ELSE GETDATE() 
				      END, 
		            CASE @TFECHA 
						    WHEN 1 THEN @FECHAFAC + @DV 
						    ELSE GETDATE() + @DV 
					   END,
					   0, NULL, NULL, LEFT(@DATO2,2), NULL, 'P', NULL, @IDAFILIADO, @USUARIO, @NOREFERENCIA,
					   'CE', 'M', @OBSERVACION, 'Credito', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO,
					   GETDATE(), 0, 0, 
					   0, 
					   @IDPLAN, NULL, 'C', NULL, NULL, NULL, @DATO3, @TTEC, @CUENTACXC,@IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''), @IDFORMATOFTR
			      END
			      ELSE
			      BEGIN
			         UPDATE FTR SET ESTADO='P',CONTABILIZADA=0, NROCOMPROBANTE=NULL, IDTERCERO=@IDTERCEROCA, IDPLAN=@IDPLAN, CUENTACXC=@CUENTACXC, TIPOTTEC=@TTEC, IDFORMATO=@IDFORMATOFTR
			         WHERE N_FACTURA=@NVOCONSEC AND CNSFCT=@CNSFTR AND ESTADO='L'
			      END
            END
         END
         ELSE
         BEGIN
            IF @CLASEFACTURA = 'CUE'   --- FACTURACION DE CE UNIFICADA (CIT + AUT) de Programa Especial
            BEGIN 
               IF (SELECT COUNT(*) FROM CIT WHERE  MARCAFAC= 1 AND CNSFACT    = @CNSRPDX) > 0
               BEGIN
                  SELECT TOP 1 @IDTERCEROCA = IDTERCEROCA, @IDAFILIADO = IDAFILIADO 
                  FROM   CIT 
                  WHERE  MARCAFAC   = 1 
                  AND    CNSFACT    = @CNSRPDX 
                  IF  COALESCE(@LIBERADA,0)=0
			         BEGIN        
			            SET @CNSFTR = SPACE(20)
			            EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
			            SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0 )
               
			            SET @NVOCONSEC = SPACE(20)
			            EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT
			         END

                  IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI'
                  BEGIN
                     EXEC SPK_PREFIJOFACTURA @COMPANIA, @IDSEDE, @PRE OUTPUT  
                     SELECT @CONSECFTR = CONSECUTIVO FROM USCXS WHERE COMPANIA = '01' AND IDSEDE = @IDSEDE AND PREFIJO = @PRE
                     SELECT @CNSRESOL  = CNSRESOL FROM FDIAN WHERE IDENTIFICADOR = @IDSEDE AND VENCIDA = 0 AND PROCEDENCIA = 'FTR' AND PREFIJO=REPLACE(@PRE,'@FTR_','')
 
                  END
         
         
                     IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>'')
                     BEGIN
                         SELECT @IDFORMATOFTR=IDFORFTRCE  FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>''
                     END
                     ELSE
                     BEGIN
                         SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
                     END

			         IF  COALESCE(@LIBERADA,0)=0
			         BEGIN
				         INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
								         VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
								         IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
								         TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
								         INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
								         IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
								         MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
								         CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,IDSEDE, RDIAN, CNSRESOL, IDFORMATO)
				         SELECT @CNSFTR, @COMPANIA, 'C', @IDTERCEROCA, @NVOCONSEC, 
					      CASE @TFECHA 
					  	       WHEN 1 THEN @FECHAFAC 
							       ELSE GETDATE() 
				         END, 
		               CASE @TFECHA 
						       WHEN 1 THEN @FECHAFAC + @DV 
						       ELSE GETDATE() + @DV 
					      END,
					      0, NULL, NULL, LEFT(@DATO2,2), NULL, 'P', NULL, @IDAFILIADO, @USUARIO, @NOREFERENCIA,
					      'CE', 'M', @OBSERVACION, 'Credito', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO,
					      GETDATE(), 0, 0, 
					      0, 
					      @IDPLAN, NULL, 'C', NULL, NULL, NULL, @DATO3, @TTEC, @CUENTACXC,@IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''), @IDFORMATOFTR
			         END
			         ELSE
			         BEGIN
			            UPDATE FTR SET ESTADO='P',CONTABILIZADA=0, NROCOMPROBANTE=NULL, IDTERCERO=@IDTERCEROCA, IDPLAN=@IDPLAN, CUENTACXC=@CUENTACXC, TIPOTTEC=@TTEC, IDFORMATO=@IDFORMATOFTR
			            WHERE N_FACTURA=@NVOCONSEC AND CNSFCT=@CNSFTR AND ESTADO='L'
			         END
               END
               --
            END
         END
      END     
   END

   IF @NOREFERENCIA = 'VARIOS'
   BEGIN 
      SELECT AUT.IDAFILIADO , COUNT(*) AS VECES
      INTO   #X_AFI
      FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT       = AUT.IDAUT 
      WHERE  AUT.CNSFACT = @CNSRPDX 
      AND    (AUT.FACTURADA = 0 OR AUT.FACTURADA IS NULL OR AUT.FACTURADA=2) 
      AND    AUT.MARCAFAC = 1 AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL) 
      AND   (AUTD.IDTERCEROCA = (CASE WHEN @IDTERCEROCA1 = '' THEN @IDTERCEROCA ELSE AUTD.IDTERCEROCA END)) 
      AND   COALESCE(FACTURABLE,0)=1 
      AND   COALESCE(VALORTOTAL,0)>0 
      AND  COALESCE(AUT.DESCUENTO,0)<CASE WHEN AUT.TIPODTO='P' THEN 100 ELSE AUT.VALORTOTAL END
      GROUP BY AUT.IDAFILIADO
      SELECT @NUMTER = COALESCE(COUNT(*),0)
      FROM   #X_AFI

      IF @NUMTER = 1
      BEGIN 
         SELECT TOP 1 @IDAFILIADO = IDAFILIADO, @NOREFERENCIA = AUT.NOAUT
         FROM AUT INNER JOIN AUTD ON AUTD.IDAUT       = AUT.IDAUT 
                  LEFT JOIN TER  ON AUTD.IDTERCEROCA = TER.IDTERCERO
         WHERE AUT.CNSFACT = @CNSRPDX AND (AUT.FACTURADA = 0 OR AUT.FACTURADA IS NULL OR AUT.FACTURADA=2) AND
               AUT.MARCAFAC = 1 AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL) AND 
               (TER.IDTERCERO = (CASE WHEN @IDTERCEROCA1='' THEN TER.IDTERCERO ELSE @IDTERCEROCA1 END) OR
               (TER.IDTERCERO IS NULL AND @IDTERCEROCA=@IDTERCEROCA1 AND @IDTERCEROCA1<>'') OR
               (TER.IDTERCERO IS NULL AND @IDTERCEROCA1=''))
         AND   COALESCE(FACTURABLE,0)=1 
         AND   COALESCE(VALORTOTAL,0)>0 
         AND  COALESCE(AUT.DESCUENTO,0)<CASE WHEN AUT.TIPODTO='P' THEN 100 ELSE AUT.VALORTOTAL END
      END
      DROP TABLE #X_AFI
   END

   PRINT '@CLASEFACTURA = '+COALESCE(@CLASEFACTURA,'')
--
   IF COALESCE(@CLASEFACTURA,'') = '' 
      SELECT @CLASEFACTURA= 'VARIOS'

   DECLARE CUR_FTR CURSOR FOR
   SELECT DISTINCT CASE WHEN @IDTERCEROCA IS NULL THEN @IDTERCERO ELSE @IDTERCEROCA END
   FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT       = AUT.IDAUT 
              -- LEFT JOIN TER  ON AUTD.IDTERCEROCA = TER.IDTERCERO
   WHERE  AUT.CNSFACT = @CNSRPDX AND (AUT.FACTURADA = 0 OR AUT.FACTURADA IS NULL OR AUT.FACTURADA=2) AND
          AUT.MARCAFAC = 1 AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL) AND 
         (AUTD.IDTERCEROCA = (CASE WHEN @IDTERCEROCA1='' THEN @IDTERCEROCA ELSE AUTD.IDTERCEROCA END)) --OR
          AND   COALESCE(FACTURABLE,0)=1 
		    AND  ((COALESCE(VALORTOTAL,0)>0 AND @CLASEFACTURA <> 'CUE') OR (COALESCE(VALORTOTAL,0) = COALESCE(VALORTOTAL,0) AND @CLASEFACTURA = 'CUE'))
          AND   COALESCE(AUT.DESCUENTO,0)<CASE WHEN AUT.TIPODTO='P' THEN 100 ELSE AUT.VALORTOTAL END
          AND  AUT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDTERCEROCA1 ELSE AUT.IDAFILIADO END
         --(TER.IDTERCERO IS NULL AND @IDTERCEROCA=@IDTERCEROCA1 AND @IDTERCEROCA1<>'') OR
         --(TER.IDTERCERO IS NULL AND @IDTERCEROCA1=''))
   OPEN CUR_FTR
   FETCH NEXT FROM CUR_FTR
   INTO @IDTERCEROCA
   PRINT '@IDTERCEROCA='+@IDTERCEROCA 
   WHILE @@FETCH_STATUS = 0  
   BEGIN  
      PRINT 'Insertando en #FTRD1 AUT'

      INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                         IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                         VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                         NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, PROCEDENCIA,
						 IDIMPUESTO, IDCLASE, ITEM, VLRIMPUESTO, PIVA, VIVA, CUENTA_FIMPDV,TCOPAGO)
      SELECT @CNSFTR, GETDATE(), 'DB', AUT.IDAREA, NULL, 
             (AUTD.CANTIDAD * AUTD.VALOR) - CASE WHEN @NODESCUENTACOPAGO = 1 
                                                 THEN 0
                                                 ELSE ROUND(((AUTD.CANTIDAD * AUTD.VALOR) * AUT.VALORCOPAGO) / CASE AUT.VALORTOTAL WHEN 0 THEN 1 ELSE AUT.VALORTOTAL END ,0)
                                            END,
             NULL, CASE WHEN @DATOCCOSTO = 'SER:CCOSTO' THEN AUTD.CCOSTO ELSE AUT.CCOSTO END, SER.PREFIJO, 
             SER.DESCSERVICIO, AUTD.IDSERVICIO, NULL, AUTD.CANTIDAD, AUTD.VALOR, (AUTD.CANTIDAD * AUTD.VALOR), 
             CASE WHEN @NODESCUENTACOPAGO = 1 
             THEN 0 
             ELSE ROUND(((AUTD.CANTIDAD * AUTD.VALOR) * AUT.VALORCOPAGO) / CASE AUT.VALORTOTAL WHEN 0 THEN 1 ELSE AUT.VALORTOTAL END,0) 
             END, 
             0, AUT.IDPROVEEDOR, AUT.NOAUT, AUT.NOAUT, AUTD.NO_ITEM, NULL, 
             @NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO, AUT.FECHA, 'CE',
			    CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END,
             CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
             CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) ELSE NULL END,
             CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.CANTIDAD * AUTD.VALOR) ELSE NULL END ,
             CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) ELSE NULL END,
             CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  CASE WHEN AUTD.VALOR = 0 THEN NULL
														ELSE 
															 CASE WHEN @BASE_IVA_SER='CONIVA' 
																 THEN  (SELECT (AUTD.CANTIDAD * AUTD.VALOR) -ROUND((AUTD.CANTIDAD * AUTD.VALOR)/((VALOR+100)/100),0) 
																 FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)))
															 ELSE
																  (SELECT ROUND((AUTD.CANTIDAD * AUTD.VALOR)*(VALOR/100),0) 
																  FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) 
															 END
													    END
												  ELSE NULL 
												  END,
             CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)))  
												   ELSE NULL 
			                         		   END,
      DBO.FNK_TRAE_TIPOCOPAGO(AUT.NOAUT,'CE')
      FROM   AUT INNER JOIN AUTD ON AUT.IDAUT        = AUTD.IDAUT 
                 INNER JOIN SER  ON SER.IDSERVICIO   = AUTD.IDSERVICIO 
                 LEFT  JOIN TER  ON AUTD.IDTERCEROCA = TER.IDTERCERO
      WHERE  AUT.CNSFACT  = @CNSRPDX 
      AND    (AUTD.FACTURADA = 0 OR AUTD.FACTURADA IS NULL) 
      AND    AUT.MARCAFAC = 1 
      AND    (TER.IDTERCERO  = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCERO=@IDTERCEROCA)) 
      AND    COALESCE(FACTURABLE,0)=1 
      AND    ((COALESCE(VALORTOTAL,0)>0 AND @CLASEFACTURA <> 'CUE') OR (COALESCE(VALORTOTAL,0) = COALESCE(VALORTOTAL,0) AND @CLASEFACTURA = 'CUE'))
      AND    COALESCE(AUT.DESCUENTO,0)<CASE WHEN AUT.TIPODTO='P' THEN 100 ELSE CASE WHEN @CLASEFACTURA <> 'CUE' THEN AUT.VALORTOTAL ELSE 999999999 END  END
      AND    AUT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDTERCEROCA1 ELSE AUT.IDAFILIADO END
      
      SELECT @OK = ISNULL(COUNT(*),0) FROM #FTRD1
      IF @OK > 0
      BEGIN
         IF  COALESCE(@LIBERADA,0)=0
         BEGIN 
			   SET @CNSFTR = SPACE(20)
			   EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
			   SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0)   
			   SET @NVOCONSEC = SPACE(20)
			   EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT
		   END

         IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI'
         BEGIN
            EXEC SPK_PREFIJOFACTURA @COMPANIA, @IDSEDE, @PRE OUTPUT  
            SELECT @CONSECFTR = CONSECUTIVO FROM USCXS WHERE COMPANIA = '01' AND IDSEDE = @IDSEDE AND PREFIJO = @PRE
            SELECT @CNSRESOL  = CNSRESOL FROM FDIAN WHERE IDENTIFICADOR = @IDSEDE AND VENCIDA = 0 AND PROCEDENCIA = 'FTR' AND PREFIJO=REPLACE(@PRE,'@FTR_','')
 
         END
         
         
         IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>'')
         BEGIN
             SELECT @IDFORMATOFTR=IDFORFTRCE  FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>''
         END
         ELSE
         BEGIN
             SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
         END

         IF  COALESCE(@LIBERADA,0)=0
         BEGIN
			   INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
							    VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
							    IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
							    TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
							    INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
							    IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
							    MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
							    CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC, IDSEDE, RDIAN, CNSRESOL, IDFORMATO)
			   SELECT @CNSFTR, @COMPANIA, 'C', @IDTERCEROCA, @NVOCONSEC, 
					   CASE @TFECHA 
					      WHEN 1 THEN @FECHAFAC 
					      ELSE GETDATE() 
					   END, 
					   CASE @TFECHA 
					      WHEN 1 THEN @FECHAFAC +@DV
					      ELSE GETDATE() +@DV 
					   END,
					   0, NULL, NULL, LEFT(@DATO2,2), NULL, 'P', NULL, @IDAFILIADO, @USUARIO, @NOREFERENCIA,
					   'CE', CASE ISNULL(@CLASEFACTURA,'') WHEN 'ACE' THEN 'I'
														   ELSE 'M'
						     END, @OBSERVACION, 'Credito', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO,
					   GETDATE(), 0, 0, 
					   0, 
					   @IDPLAN, NULL, 'C', NULL, NULL, NULL, @DATO3, @TTEC, @CUENTACXC, @IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''), @IDFORMATOFTR
         END
         ELSE
         BEGIN
            UPDATE FTR SET ESTADO='P',CONTABILIZADA=0, NROCOMPROBANTE=NULL, IDTERCERO=@IDTERCEROCA, IDPLAN=@IDPLAN, CUENTACXC=@CUENTACXC, TIPOTTEC=@TTEC, IDFORMATO=@IDFORMATOFTR
            WHERE N_FACTURA=@NVOCONSEC AND CNSFCT=@CNSFTR AND ESTADO='L'
         END
		 
		   UPDATE #FTRD1 SET CANTIDAD = COALESCE(CANTIDAD,0), VALOR = COALESCE(VALOR,0), VLR_SERVICI = COALESCE(VLR_SERVICI,0),
							VR_TOTAL = COALESCE(VR_TOTAL,0), VLR_COPAGOS = COALESCE(VLR_COPAGOS,0), VLR_PAGCOMP = COALESCE(VLR_PAGCOMP,0)
         WHERE 1=1
         INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                     IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                     VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                     NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, PROCEDENCIA,
					 PIVA, VIVA, CUENTA_FIMPDV, IDIMPUESTO, IDCLASE, ITEM, VLRIMPUESTO,TCOPAGO)
         SELECT @CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                NOPRESTACION, NOITEM, AREAFUNCONT, @NVOCONSEC, SUBCCOSTO, PCOSTO, FECHAPREST, PROCEDENCIA,
				    PIVA, VIVA, CUENTA_FIMPDV, IDIMPUESTO, IDCLASE, ITEM, VLRIMPUESTO,TCOPAGO
         FROM   #FTRD1
         
		 --JFRANCO 20/03/2020 COLOCAMOS SI EL IVA SUMA AL TOTAL O NO 
		 UPDATE FTRD SET 
		 VR_TOTAL   =(VALOR*CANTIDAD)-COALESCE((@VRCOPA/(SELECT COUNT(1) FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC )), 0)+ 
					 (CASE WHEN COALESCE(FTRD.VIVA, 0) <> 0 
							THEN CASE WHEN @BASE_IVA_SER='CONIVA' 
								THEN 0 ELSE  COALESCE(VIVA,0) 
								END
						ELSE 0 END)
		 WHERE FTRD.N_FACTURA = @NVOCONSEC AND FTRD.VALOR>0

         IF @VRTOTAL IS NULL SELECT @VRTOTAL = 0
         IF @VRSERV IS NULL SELECT @VRSERV = 0
         IF @VRCOPA IS NULL SELECT @VRCOPA = 0
         IF @VRPACO IS NULL SELECT @VRPACO = 0  
		 
         IF @VRTOTAL < 0 SELECT @VRTOTAL = 0
         
         SELECT @DESCUENTO = 0, @VRDTO = 0
         IF @MABONO = 1
         BEGIN
            SELECT @VRABONO = ROUND(@VRTOTAL * (@PABONO / 100 ), 0)
         END
         ELSE
         BEGIN 
            SELECT @VRABONO = 0
         END
         
         UPDATE FTR SET DESCUENTO = @VRDTO, VR_ABONOS = @VRABONO
         WHERE  N_FACTURA = @NVOCONSEC
            
         --UPDATE FTR SET VR_TOTAL = VALORSERVICIOS - VALORCOPAGO - VALORPCOMP -DESCUENTO - VR_ABONOS
         --WHERE  N_FACTURA = @NVOCONSEC      
         
         -- GENERA LA DEDUCCION DE IMPUESTOS ESPERADA
         --SELECT @VRTOTAL = VR_TOTAL FROM FTR WHERE  N_FACTURA = @NVOCONSEC 
         
         IF @VRTOTAL < 0
         BEGIN
            UPDATE FTR SET VR_TOTAL = 0 WHERE  N_FACTURA = @NVOCONSEC      
         END

         IF @CLASEFACTURA <> 'CEU'
            EXEC SPK_FAC_IMPDEDUC @NIT, @CNSFTR, @NVOCONSEC, @VRTOTAL    
         
         UPDATE AUTD SET FACTURADA = 1, N_FACTURA = @NVOCONSEC, CNSFCT = @CNSFTR
         FROM   AUTD INNER JOIN 
                AUT ON AUT.IDAUT=AUTD.IDAUT INNER JOIN
                SER ON SER.IDSERVICIO = AUTD.IDSERVICIO 
         WHERE  AUT.CNSFACT = @CNSRPDX 
         AND    (AUTD.FACTURADA = 0 OR AUTD.FACTURADA IS NULL) AND AUT.MARCAFAC = 1 
         AND    (AUTD.IDTERCEROCA  = @IDTERCEROCA OR (AUTD.IDTERCEROCA IS NULL AND @IDTERCERO=@IDTERCEROCA)) 
         AND   COALESCE(FACTURABLE,0)=1 
         AND   ((COALESCE(VALORTOTAL,0)>0 AND @CLASEFACTURA <> 'CUE') OR (COALESCE(VALORTOTAL,0) = COALESCE(VALORTOTAL,0) AND @CLASEFACTURA = 'CUE'))
         AND    COALESCE(AUT.DESCUENTO,0)<CASE WHEN AUT.TIPODTO='P' THEN 100 ELSE CASE WHEN @CLASEFACTURA <> 'CUE' THEN AUT.VALORTOTAL ELSE 999999999 END  END
         AND    AUT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDTERCEROCA1 ELSE AUT.IDAFILIADO END
         -- SOAT
         UPDATE HACTRAND SET N_FCT_ASEG = @NVOCONSEC
         FROM   HACTRAND INNER JOIN AUT ON HACTRAND.NOREFERENCIA = AUT.NOAUT AND HACTRAND.PROCEDENCIA = 'CE'
         WHERE  AUT.CNSFACT  = @CNSRPDX
         AND    AUT.MARCAFAC = 1
         --
         TRUNCATE TABLE #FTRD1
      END
      FETCH NEXT FROM CUR_FTR
      INTO @IDTERCEROCA
   END
   CLOSE CUR_FTR
   DEALLOCATE CUR_FTR

   SELECT @VRTOTAL	= SUM(COALESCE(VR_TOTAL,0)), 
			@VRSERV = SUM(COALESCE(VLR_SERVICI,0)), 
			@VRPACO = SUM(COALESCE(VLR_PAGCOMP,0)), 
			@VRCOPA = SUM(COALESCE(VLR_COPAGOS,0)), 
			@VIVA	= SUM(COALESCE(VIVA,0))
    FROM  FTRD WHERE N_FACTURA = @NVOCONSEC

   UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = @VRCOPA, VALORPCOMP = @VRPACO, VIVA = @VIVA, 
		           VR_TOTAL = @VRSERV - @VRCOPA - @VRPACO - COALESCE(@VRDTO,0) - COALESCE(@VRABONO,0)
   WHERE N_FACTURA = @NVOCONSEC

   SELECT @VIVA=SUM(COALESCE(VIVA,0)) FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  
	IF @VIVA>0
	BEGIN
		SELECT TOP 1 @PIVA=PIVA ,@MIVA=1 FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  AND COALESCE(PIVA,0)<>0
		UPDATE FTR SET MIVA=@MIVA,PIVA=@PIVA,VIVA=@VIVA WHERE N_FACTURA = @NVOCONSEC
	END
   
   UPDATE AUT SET FACTURADA = (CASE WHEN NOFACT=0 THEN 1 ELSE CASE WHEN SIFACT=0 THEN 0 ELSE 2 END END), 
                  VFACTURAS = 0, MARCAFAC = 0, N_FACTURA = @NVOCONSEC 
   FROM AUT INNER JOIN (SELECT IDAUT, SUM(NOFACT) AS NOFACT, SUM(SIFACT) AS SIFACT 
                        FROM (SELECT AUT.IDAUT, 
                                     CASE WHEN AUTD.FACTURADA = 0 OR AUTD.FACTURADA IS NULL THEN COUNT(*) ELSE 0 END AS NOFACT,
                                     CASE WHEN AUTD.FACTURADA = 1 THEN COUNT(*) ELSE 0 END AS SIFACT
                              FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                              WHERE  AUT.CNSFACT = @CNSRPDX
                              GROUP BY AUT.IDAUT, AUTD.FACTURADA) AUTD_E
                        GROUP BY IDAUT) AUTD ON AUT.IDAUT=AUTD.IDAUT
   WHERE  AUT.CNSFACT  = @CNSRPDX AND COALESCE(AUT.FACTURADA,0)=0
   AND    AUT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDTERCEROCA1 ELSE AUT.IDAFILIADO END

   DROP TABLE #FTRD1
   
   SELECT @CANTAFI =COUNT (IDAFILIADO) FROM ( SELECT DISTINCT   IDAFILIADO  FROM AUTD INNER JOIN AUT ON AUT.IDAUT=AUTD.IDAUT WHERE AUTD.N_FACTURA=@NVOCONSEC) Z 

   IF(DBO.FNK_VALORVARIABLE('IDFORMATOFTR'))='03F2'
   BEGIN 
		IF COALESCE(@CANTAFI,0)>1
			BEGIN 
				UPDATE FTR SET        NOREFERENCIA='VARIOS'  ,	    IDAFILIADO  ='',		IDFORMATO='03F2'       WHERE N_FACTURA=@NVOCONSEC
			END 
        ELSE 
		   BEGIN 
			   UPDATE FTR SET 
			   NOREFERENCIA=(SELECT MAX(AUT.NOAUT)  FROM AUTD INNER JOIN AUT ON AUT.IDAUT=AUTD.IDAUT WHERE AUTD.N_FACTURA=@NVOCONSEC)  ,
				IDAFILIADO  =(SELECT MAX(IDAFILIADO) FROM AUTD INNER JOIN AUT ON AUT.IDAUT=AUTD.IDAUT WHERE AUTD.N_FACTURA=@NVOCONSEC) 
			   WHERE N_FACTURA=@NVOCONSEC
		   END 
   END 
   ELSE
   BEGIN
		IF COALESCE(@CANTAFI,0)>1
		BEGIN 
			UPDATE FTR SET IDAFILIADO='' WHERE N_FACTURA=@NVOCONSEC 
		END
   END
   IF COALESCE(@CLASEFACTURA,'') <> 'CEU' AND COALESCE(@CLASEFACTURA,'') <> 'CUE'
   BEGIN
      IF (SELECT DBO.FNK_VALORVARIABLE('CONTABFACCE_AUTOM') ) = 'SI'
      BEGIN
         EXEC SPK_NC_CONTAB_FTR @NVOCONSEC, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''
      END
   END
   ELSE
   BEGIN
      EXEC SPK_FACTURACI_ESCMA @CNSRPDX, @NIT, @COMPANIA, @IDSEDE, @USUARIO, @IDTERCERO, @IDPLAN, @OBSERVACION, @IDTERCERO, @FECHAFAC, @NVOCONSEC, @CNSFTR, @CLASEFACTURA, @IDTERCEROCA1
   END
END







