CREATE OR ALTER PROCEDURE DBO.SPK_NC_CONTAB_FNOT
@CNSFNOT          VARCHAR(20), 
@CLASE            VARCHAR(1),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA         VARCHAR(2), 
@SEDE             VARCHAR(5),
@NROCOMPROBANTE   VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @COM              VARCHAR(6)
DECLARE @NOREFERENCIA     VARCHAR(20)
DECLARE @ANO              VARCHAR(4)
DECLARE @MES              INT
DECLARE @IDMODELOCONT     VARCHAR(2)
DECLARE @TIPOTERCONTABLE  VARCHAR(10) 
DECLARE @PREFIJO_USCXS    VARCHAR(10)
DECLARE @FECHATRA         DATETIME
DECLARE @CNS              INT
DECLARE @TIPO             VARCHAR(1)
DECLARE @ITEM             INT
DECLARE @VR_TOTAL         DECIMAL(15,2)
DECLARE @VLR              DECIMAL(15,2)
DECLARE @CUENTA           VARCHAR(16)
DECLARE @DIAS_VCTO		   SMALLINT
DECLARE @F_VENCE_FTR	   DATETIME
DECLARE @TOTALCR            DECIMAL(15,2)
DECLARE @TOTALDB            DECIMAL(15,2)
DECLARE @COM_ARS            VARCHAR(6)
DECLARE @LIBERAHADM         SMALLINT
DECLARE @PROCEDENCIA        VARCHAR(10)
DECLARE @NROCOMPROBANTE_FTR VARCHAR(20)
DECLARE @NROCOMPROBANTEDEST VARCHAR(20)
DECLARE @N_FACTURA          VARCHAR(16)  
DECLARE @CUENTACONC         VARCHAR (16)
DECLARE @CUENTANOT          VARCHAR (16)
DECLARE @ORIGENFTR          VARCHAR(10)
DECLARE @TIPOR              VARCHAR(2)
DECLARE @CONTA              INT  
DECLARE @NROCOMPERROR       VARCHAR(20)
DECLARE @YARAD              INT
DECLARE @VANTE              BIT
DECLARE @CODCONCEPTO        VARCHAR(20)
DECLARE @ESANULACION        BIT
DECLARE @IDTIPOMOV VARCHAR(20)
DECLARE @LINEA  VARCHAR(120), @DIASVENCE INT, @PGP BIT,@CAPITADO INT 
DECLARE @VDB DECIMAL(14,2), @VCR DECIMAL(14,2), @VFNOT DECIMAL(14,2),@CASTIGADA INT,@TCOBRO VARCHAR(10)
BEGIN
   SELECT @CASTIGADA=COALESCE(FCXCDV.CASTIGADA,0),@TCOBRO=COALESCE(FCXCDV.TCOBRO,'')
   FROM FCXCDV INNER JOIN FNOT ON FCXCDV.N_fACTURA=FNOT.N_FACTURA AND FCXCDV.CNSGLO=FNOT.CNSGLO
   WHERE FNOT.CNSFNOT=@CNSFNOT

   

   IF COALESCE(@CASTIGADA,0)=1
   BEGIN
      IF COALESCE(@TCOBRO,'')='' OR COALESCE(@TCOBRO,'')='Castigo'
      BEGIN
         UPDATE FNOT SET CONTABILIZADA=1,NROCOMPROBANTE=NULL WHERE CNSFNOT=@CNSFNOT
         PRINT 'CARTERA CASTIGADA NO DEBO ENVIAR A CONTABILIDAD'
         RETURN   
      END
   END  
   SELECT @LINEA=DBO.FNK_VALORVARIABLE('IDCONNOTAS_CREDITO')
   IF COALESCE(@NROCOMPROBANTE,'') = ''
   BEGIN
      IF (SELECT COALESCE(CONTABILIZADA,0) FROM FNOT WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE ) = 1
      BEGIN
         RAISERROR('NOTA YA CONTABILIZADA.',16,1)
         RETURN
      END
   END   
   --SE REVISA SI LOS COMPROBANTES SE TOMAN DE ACUERDO A SEDE
   IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
   BEGIN
      SELECT @COM = RTRIM(LTRIM(COMMS.COMPROBANTE)) FROM COMMS WHERE IDSEDE = @SEDE AND COMMS.CLASE = 'NOTADBCR' AND TIPO = 'NOTADBCR'
   END
   ELSE
   BEGIN
      SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_NOTDBCR')))
   END
   
   SELECT @CONTA = COUNT(*) FROM MCP WHERE COMPROBANTE = @COM AND REFERENCIA1 = @CNSFNOT AND REFERENCIA2 = @CLASE AND COALESCE(ANULADO,0) <> 0
   SELECT @CONTA = COALESCE(@CONTA,0)
   
   IF @CONTA > 0
   BEGIN
      SELECT @NROCOMPERROR = NROCOMPROBANTE FROM MCP WHERE COMPROBANTE = @COM AND REFERENCIA1 = @CNSFNOT AND REFERENCIA2 = @CLASE AND COALESCE(ANULADO,0) <> 0
      PRINT 'CONSECUTIVO DE NOTA YA APARECE CONTABILIZADA EN EL NRO DE COMPROBANTE=' + @NROCOMPERROR
      RAISERROR('CONSECUTIVO DE NOTA YA APARECE EN UN COMPROBANTE ',16,1)
      RETURN
   END
     
   SELECT @ANO            = YEAR(F_NOTA),
          @MES            = MONTH(F_NOTA),
          @FECHATRA       = F_NOTA,
          @PROCEDENCIA    = PROCEDENCIA,
          @N_FACTURA      = N_FACTURA,
          @CODCONCEPTO    = IDCONCEPTO,
          @ESANULACION = CASE WHEN UPPER(FNOT.PROCEDENCIA)='FACTURA'  THEN 1 ELSE 0 END 
   FROM   FNOT
   WHERE  FNOT.CNSFNOT = @CNSFNOT 
   AND    FNOT.CLASE = @CLASE
   
   SELECT @ORIGENFTR=PROCEDENCIA  FROM FTR WHERE N_FACTURA=@N_FACTURA
   SELECT @PGP=0
   IF EXISTS(SELECT * FROM PPT INNER JOIN FTR ON PPT.IDTERCERO=FTR.IDTERCERO AND PPT.IDPLAN=FTR.IDPLAN WHERE COALESCE(PPT.PGP,0)=1 AND FTR.N_FACTURA=@N_FACTURA)
   BEGIN
      SELECT @PGP=1
   END
   SELECT @CAPITADO=0
   IF EXISTS(SELECT * FROM PPT INNER JOIN FTR ON PPT.IDTERCERO=FTR.IDTERCERO AND PPT.IDPLAN=FTR.IDPLAN WHERE COALESCE(PPT.CAPITADO,0)=1 AND FTR.N_FACTURA=@N_FACTURA)
   BEGIN
      SELECT @CAPITADO=1
   END

   SELECT @VANTE= CASE WHEN YEAR(F_FACTURA)<>YEAR(F_NOTA) THEN 1 ELSE 0 END,
   @ESANULACION=CASE WHEN COALESCE(@ESANULACION,0)=0 THEN CASE WHEN FNOT.VR_TOTAL>=FTR.VR_TOTAL AND FTR.SI=0 THEN 1 ELSE 0 END ELSE @ESANULACION END-- VALIDA ANULACION TOTAL
   FROM FTR INNER JOIN FNOT ON FTR.N_FACTURA=FNOT.N_FACTURA
   WHERE FTR.N_fACTURA=@N_FACTURA
   AND FNOT.CNSFNOT=@CNSFNOT
   IF NOT EXISTS(SELECT * FROM CUE WHERE CUENTA =LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING'))) AND TIPO='Detalle')
   BEGIN
      PRINT 'SI ES DE VIGENCIA ANTERIOR PERO NO TIENE LA CUENTA CONFIGURADA...'
      SELECT @VANTE=0
   END
   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)
   BEGIN
      PRINT 'Per�odo contable no Existe'
      RAISERROR('Per�odo contable no Existe',16,1)
      RETURN
   END
   IF COALESCE(@ESANULACION,0)=1 OR (SELECT MCUEORDEN_GLOSAS FROM PAR WHERE COMPANIA=@COMPANIA)='SI'
   BEGIN
      CREATE TABLE  #REF (
      CNS       INT IDENTITY(1,1),
      CNSFNOT   VARCHAR(20) COLLATE database_default,
      CLASE     VARCHAR(1)  COLLATE database_default,
      ITEM      INT, 
      TIPO      VARCHAR(1)  COLLATE database_default,
      CCOSTO    VARCHAR(20) COLLATE database_default, 
      IDAREA    VARCHAR(20) COLLATE database_default,
      PREFIJO   VARCHAR(6)  COLLATE database_default,
      N_FACTURA VARCHAR(20) COLLATE database_default,
      F_FACTURA DATETIME,
      F_VENCE   DATETIME,
      TIPOTTEC  VARCHAR(10) COLLATE database_default,
      VALOR     DECIMAL(15,2))
   
      INSERT INTO #REF (CNSFNOT, CLASE, ITEM, TIPO, CCOSTO, IDAREA, PREFIJO, N_FACTURA, F_FACTURA, F_VENCE, TIPOTTEC, VALOR)
      SELECT FNOTD.CNSFNOT, FNOTD.CLASE, FNOTD.ITEM, FNOTD.TIPO, 
             CASE WHEN FNOTD.TIPO='S' THEN FTRD.CCOSTO ELSE FTRPRC.CCOSTO END AS CCOSTO, 
             CASE WHEN FNOTD.TIPO='S' THEN FTRD.AREAPRESTACION ELSE FTRPRC.IDAREA END AS IDAREA, 
             CASE WHEN FNOTD.TIPO='S' THEN FTRD.PREFIJO ELSE FTRPRC.PREFIJO END AS PREFIJO, 
             FTR.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(FTR.F_FACTURA), DBO.FNK_FECHA_SIN_HORA(FTR.F_VENCE), FTR.TIPOTTEC,
             CASE WHEN FNOTD.TIPO='S' THEN FNOTD.VR_TOTAL ELSE ROUND(FNOTD.VR_TOTAL*FTRPRC.PORC*0.01,0) END VALOR
      FROM   FNOT INNER JOIN FNOTD ON FNOT.CNSFNOT    = FNOTD.CNSFNOT 
                                  AND FNOT.CLASE      = FNOTD.CLASE 
                   LEFT JOIN FTR   ON FNOT.N_FACTURA  = FTR.N_FACTURA 
                   LEFT JOIN FTRD  ON FNOTD.TIPO      = 'S' 
                                  AND FTR.N_FACTURA   = FTRD.N_FACTURA 
                                  AND FTRD.REFERENCIA = FNOTD.IDSERVICIO 
                                  AND FTRD.N_CUOTA    = FNOTD.ITEM --STORRES Y NVOOS 20260819 SE AGREGA LLAVES UNICAS DE LAS TABLAS PARA EVITAR DUPLICIDAD DE LA INFORMACION DE FTRD Y FNOTD
                   LEFT JOIN (SELECT FTR.N_FACTURA, FTRD.CCOSTO, FTRD.AREAPRESTACION AS IDAREA, FTRD.PREFIJO, 
                              SUM(COALESCE(FTRD.VR_TOTAL,(VLR_SERVICI-COALESCE(VLR_COPAGOS,0))))*100/FTR.VR_TOTAL AS PORC
                              FROM   FTR INNER JOIN FTRD ON FTR.N_FACTURA = FTRD.N_FACTURA 
                              WHERE  NOT FTR.N_FACTURA IS NULL AND FTR.VR_TOTAL<>0
                              GROUP BY FTR.N_FACTURA, FTRD.CCOSTO, FTRD.AREAPRESTACION, 
                                       FTRD.PREFIJO, FTR.VR_TOTAL) AS FTRPRC ON FTRPRC.N_FACTURA = FTR.N_FACTURA 
                                                                            AND FNOTD.TIPO       = 'C'  
      WHERE  FNOT.CNSFNOT=@CNSFNOT AND FNOT.CLASE=@CLASE  
      PRINT 'A ENTRAR A CURSOR VALORES'
      DECLARE CURFNOT CURSOR FOR
      SELECT ITEM, VR_TOTAL FROM FNOTD 
      WHERE  FNOTD.TIPO='C'
      AND    FNOTD.CNSFNOT = @CNSFNOT 
      AND    FNOTD.CLASE = @CLASE
      OPEN CURFNOT
      FETCH NEXT FROM CURFNOT
      INTO @ITEM, @VR_TOTAL
      WHILE @@FETCH_STATUS = 0
      BEGIN   
         SET @VLR = @VR_TOTAL - (SELECT SUM(VALOR) FROM #REF WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND ITEM=@ITEM)
         IF @VLR <> 0
         BEGIN
            PRINT 'Ajustando Valores por Redondeo en: '+STR(@VLR)
            SET @CNS = (SELECT MAX(CNS) FROM #REF WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND ITEM=@ITEM)
            UPDATE #REF SET VALOR = VALOR + @VLR WHERE CNS=@CNS
         END
         FETCH NEXT FROM CURFNOT
         INTO @ITEM, @VR_TOTAL
      END
      CLOSE CURFNOT
      DEALLOCATE CURFNOT
   END  
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
   IF ISNULL(@NROCOMPROBANTE,'') = '' -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   BEGIN
      SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      
      SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_NOTDBCR')))      
      SET @PREFIJO_USCXS='@COM'+@COM
      SET @NOREFERENCIA=SPACE(20)
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
      SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
      PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
      PRINT 'Comprobante Contable (MCP)'
      INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                       TOTALCREDITO, REFERENCIA1, REFERENCIA2,REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                       COMPROBANTE, IDTERCERO)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'NOTDBCR', @NOREFERENCIA, @ANO, @MES, 
             CAST(STR(DAY(F_NOTA))+'/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME), 0, 0, CNSFNOT, CLASE,@N_FACTURA, @USUARIO, 
             DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL,SUBSTRING(DBO.FNK_RTF(FNOT.OBSERVACION),1,470), @SEDE, 0, @COM, 
             (CASE WHEN FNOT.IDTERCERO IS NULL THEN '' ELSE FNOT.IDTERCERO END)
      FROM   FNOT 
      WHERE  FNOT.CNSFNOT = @CNSFNOT 
      AND    FNOT.CLASE   = @CLASE
   END
   ELSE
   BEGIN 
      DELETE FROM MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE --AND PROCEDENCIA='NOTDBCR'
      UPDATE MCPE SET OBSERVACION = SUBSTRING(DBO.FNK_RTF(FNOT.OBSERVACION),1,470) FROM FNOT
      WHERE  MCPE.NROCOMPROBANTE=@NROCOMPROBANTE AND MCPE.PROCEDENCIA='NOTDBCR' AND MCPE.REFERENCIA1=@CNSFNOT
      AND    FNOT.CNSFNOT = @CNSFNOT
      AND    FNOT.CLASE   = @CLASE
   END 
   IF (SELECT ESTADO FROM FNOT WHERE CNSFNOT=@CNSFNOT)='A'
   BEGIN
      PRINT 'La Nota Credito se Encuentra Anulada... se quita de mcpe '
      INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, 
                        ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
      SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, REFERENCIA3, USUARIO, FECHA, LOTE,DBO.FNK_RTF(OBSERVACION), IDSEDE, 
             ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
      FROM MCPE 
      WHERE NROCOMPROBANTE=@NROCOMPROBANTE

      UPDATE MCP SET ANULADO=1 WHERE NROCOMPROBANTE=@NROCOMPROBANTE

      EXEC SPK_REVISAR_COMPROBANTE @COMPANIA,@NROCOMPROBANTE

      DELETE FROM MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE 
      DELETE FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
      RETURN
   END    
   IF @CLASE='C'
   BEGIN
      PRINT 'Contabilizando Notas Credito...' 
      IF (SELECT PROCEDENCIA FROM FNOT WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE)='AUDITORIA'
      BEGIN
         PRINT 'Proviene de Auditoria.' 
         IF (SELECT MCUEORDEN_GLOSAS FROM PAR WHERE COMPANIA=@COMPANIA) = 'Si'
         BEGIN
            PRINT ' Si Usa cuentas de Orden.'
            PRINT ' Contabilizando DB Glosas con Cuentas de Orden...' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                             REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                             CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', CASE WHEN CUE.CUENTA IS NULL THEN 'NO CUEORDENGLOSA' ELSE CUE.CUENTA END, 
                   FNOT.IDTERCERO, #REF.CCOSTO, 'CUENTA DE ORDEN POR GLOSAS DE FA '+FNOT.N_FACTURA, SUM(#REF.VALOR), 
                   NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #REF.IDAREA, #REF.PREFIJO, 1, 
                   'CUEORDENGLOSADB', 'Movimiento','S', FNOT.N_FACTURA, #REF.F_FACTURA, #REF.F_VENCE, 'FNOT', @CNSFNOT,
                   FNOT.CODUNG, FNOT.CODPRG
            FROM   FNOT, #REF LEFT JOIN
                   TTEC ON TTEC.TIPO=#REF.TIPOTTEC LEFT JOIN 
                   CUE ON TTEC.CUEORDENGLOSACR=CUE.CUENTA AND CUE.COMPANIA=@COMPANIA
            WHERE  FNOT.CNSFNOT = @CNSFNOT
            AND    FNOT.CLASE   = @CLASE
            GROUP BY CUE.CUENTA, FNOT.IDTERCERO, #REF.CCOSTO, FNOT.N_FACTURA, #REF.IDAREA, #REF.PREFIJO, #REF.F_FACTURA, #REF.F_VENCE, 
                     FNOT.CODUNG, FNOT.CODPRG
            HAVING SUM(#REF.VALOR)>0
          
            PRINT ' Contabilizando CR Glosas con Cuentas de Orden...' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                            CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', CASE WHEN CUE.CUENTA IS NULL THEN 'NO CUEORDENGLOSA' ELSE CUE.CUENTA END, 
                   FNOT.IDTERCERO, #REF.CCOSTO, 'CUENTA DE ORDEN POR GLOSAS DE FA '+ FNOT.N_FACTURA, SUM(#REF.VALOR), 
                   NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #REF.IDAREA, #REF.PREFIJO, 1, 
                   'CUEORDENGLOSACR', 'Movimiento','S', FNOT.N_FACTURA, #REF.F_FACTURA, #REF.F_VENCE, 'FNOT', @CNSFNOT, 
                   FNOT.CODUNG, FNOT.CODPRG
            FROM   FNOT, #REF LEFT JOIN TTEC ON TTEC.TIPO            = #REF.TIPOTTEC 
                              LEFT JOIN CUE  ON TTEC.CUEORDENGLOSADB = CUE.CUENTA 
                                            AND CUE.COMPANIA         = @COMPANIA
            WHERE  FNOT.CNSFNOT = @CNSFNOT
            AND    FNOT.CLASE   = @CLASE
            GROUP BY CUE.CUENTA, FNOT.IDTERCERO, #REF.CCOSTO, FNOT.N_FACTURA, #REF.IDAREA, #REF.PREFIJO, #REF.F_FACTURA, #REF.F_VENCE, 
                     FNOT.CODUNG, FNOT.CODPRG
            HAVING SUM(#REF.VALOR)>0
         END
         ELSE
         BEGIN
            PRINT ' No Usa cuentas de Orden.'
            PRINT ' Debitos...'
            PRINT @VANTE
            IF DBO.FNK_VALORVARIABLE('IDCUENTANOTAS') = 'SI'
            BEGIN
               IF EXISTS(SELECT * FROM DBO.FNK_TABLA_DESTRING(@LINEA,',') WHERE CAMPO=''+@CODCONCEPTO+'')
               BEGIN
                  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                  REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                  CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                  SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',CASE WHEN COALESCE(@VANTE,0)=1 THEN LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING')))  ELSE CPNT.CUENTA END,
                         DBO.FNK_MUESTRAPROVEEDOR(FNOT.N_FACTURA,FNOTD.N_CUOTA),'' AS CCOSTO,'NOTA CREDITO FA: '+FNOT.N_FACTURA+' MOTIVO:'+
						 LTRIM(RTRIM(LEFT(DBO.FNK_RTF(FNOTD.OBSERVACION),470))) ,
                         FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                         DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                         'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FNOT.F_NOTA, FNOT.F_NOTA, 'NOTDBCR', @CNSFNOT,
                         FNOT.CODUNG, FNOT.CODPRG
                  FROM   FNOT INNER JOIN  FNOTD ON FNOT.CNSFNOT = FNOTD.CNSFNOT
                                               AND FNOT.CLASE   = FNOTD.CLASE
                               LEFT JOIN   CPNT ON FNOT.IDCONCEPTO = CPNT.CODIGO
                  WHERE  FNOT.CNSFNOT = @CNSFNOT
                  AND    FNOT.CLASE   = @CLASE
                  AND    CPNT.CODIGO=@CODCONCEPTO
                  AND    FNOTD.VR_TOTAL>0
               END
               ELSE
               BEGIN
                  IF EXISTS(SELECT * FROM CUE WHERE CUENTA =LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING')))) AND @VANTE=1
                  BEGIN
                     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                     REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                     CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                     SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING'))),
                            DBO.FNK_MUESTRAPROVEEDOR(FNOT.N_FACTURA,FNOTD.N_CUOTA),'' AS CCOSTO,left('NOTA CREDITO FA: '
                            +FNOT.N_FACTURA+' MOTIVO:'+LTRIM(RTRIM(LEFT(DBO.FNK_RTF(FNOTD.OBSERVACION),470))),512) , FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                            DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                            'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FNOT.F_NOTA, FNOT.F_NOTA, 'NOTDBCR', @CNSFNOT,
                            FNOT.CODUNG, FNOT.CODPRG
                     FROM   FNOT INNER JOIN  FNOTD ON FNOT.CNSFNOT = FNOTD.CNSFNOT
                                                  AND FNOT.CLASE   = FNOTD.CLASE
                                  LEFT JOIN   CPNT ON FNOTD.IDSERVICIO = CPNT.CODIGO
                     WHERE  FNOT.CNSFNOT = @CNSFNOT
                     AND    FNOT.CLASE   = @CLASE
                     AND    FNOTD.VR_TOTAL>0
                  END
                  ELSE
                  BEGIN
                     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                     REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                     CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                     SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',
                            CASE WHEN FNOTD.TIPO='C' THEN CPNT.CUENTA ELSE DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'VENTAS','CR',FNOTD.PREFIJO, FNOTD.CCOSTO,'P','',@PGP) END,
                            DBO.FNK_MUESTRAPROVEEDOR(FNOT.N_FACTURA,FNOTD.N_CUOTA),'' AS CCOSTO,left('NOTA CREDITO FA: '+FNOT.N_FACTURA+' MOTIVO:'+LTRIM(RTRIM(LEFT(DBO.FNK_RTF(FNOTD.OBSERVACION),470))),512) , FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                            DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                            'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FNOT.F_NOTA, FNOT.F_NOTA, 'NOTDBCR', @CNSFNOT,
                            FNOT.CODUNG, FNOT.CODPRG
                     FROM   FNOT INNER JOIN  FNOTD ON FNOT.CNSFNOT = FNOTD.CNSFNOT
                                                  AND FNOT.CLASE   = FNOTD.CLASE
                                  LEFT JOIN   CPNT ON FNOTD.IDSERVICIO = CPNT.CODIGO
                     WHERE  FNOT.CNSFNOT = @CNSFNOT
                     AND    FNOT.CLASE   = @CLASE
                     AND    FNOTD.VR_TOTAL>0
                  END
               END               
            END
            IF COALESCE( DBO.FNK_VALORVARIABLE('IDCUENTANOTAS'),'NO') = 'NO'
            BEGIN            
               INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
               SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',
                      CASE WHEN FNOTD.TIPO ='C' THEN KCDE.CUENTA 
						         WHEN FNOTD.TIPO ='S' AND DBO.FNK_VALORVARIABLE('GLOSASNOTS')='SI' THEN KCDE.CUENTA 
                                                ELSE DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'VENTAS','CR', FNOTD.PREFIJO, FNOTD.CCOSTO,'P','',@PGP) 
                      END,
                      DBO.FNK_MUESTRAPROVEEDOR(FNOT.N_FACTURA, FNOTD.N_CUOTA),'' AS CCOSTO,LEFT('NOTA CREDITO FA: '+ FNOT.N_FACTURA+' MOTIVO:'+LTRIM(RTRIM(LEFT(DBO.FNK_RTF(FNOTD.OBSERVACION),470))),512) , FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                      DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                      'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA, FTR.F_VENCE, 'NOTDBCR', @CNSFNOT,
                      FNOT.CODUNG, FNOT.CODPRG
               FROM   FNOT INNER JOIN FNOTD ON FNOT.CNSFNOT = FNOTD.CNSFNOT
                                           AND FNOT.CLASE   = FNOTD.CLASE,
                      KCDE, FTR
               WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT 
               AND    FNOT.CNSFNOT = @CNSFNOT
               AND    FNOT.CLASE   = @CLASE
               AND    KCDE.TIPO         = 'CXC_GLOSAS' 
               AND    FNOT.VR_TOTAL      <> 0 
               AND    FTR.N_FACTURA     = FNOT.N_FACTURA    
            END            
            IF DBO.FNK_VALORVARIABLE('NOTACREDITOAUD_CR') = 'FACTURA'  
            BEGIN 
               PRINT ' Credito desde FACTURA'
               INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,  
                                REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
               SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', FTR.CUENTACXC, FNOT.IDTERCERO, '' AS CCOSTO, 
                      'NOTA CREDITO FA: '+ FNOT.N_FACTURA+' MOTIVO:', FNOT.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                      DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                      'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA, FTR.F_VENCE, 'NOTDBCR', @CNSFNOT, 
                      FNOT.CODUNG, FNOT.CODPRG
               FROM   FNOT, FTR
               WHERE  FNOT.VR_TOTAL      <> 0 
               AND    FTR.N_FACTURA     = FNOT.N_FACTURA
               AND    FNOT.CNSFNOT = @CNSFNOT
               AND    FNOT.CLASE   = @CLASE
            END
            ELSE
            BEGIN 
               -- MOD.JQUIROGA 20090519 REQ.1642 - Generar Mov. CR con cuenta de TTEC de FTR 
			      IF UPPER(DBO.FNK_VALORVARIABLE('CTA_CR_FNOT_DE_TTEC')) = 'SI'
			      BEGIN 
				    PRINT ' Credito TTEC'  
				    SET @CUENTA = ''
                        
                        IF UPPER(DBO.FNK_VALORVARIABLE('MAN_CTAS_DE_MORA')) = 'SI'
				    BEGIN
				       SELECT @F_VENCE_FTR =  F_VENCE FROM FTR WHERE N_FACTURA IN (SELECT TOP 1 N_FACTURA FROM FNOT WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE)
					  SELECT @DIAS_VCTO = DATEDIFF(DAY, @F_VENCE_FTR, GETDATE())
                     
					      IF @DIAS_VCTO <= 360 
						      SELECT @CUENTA = ISNULL(TTEC.CUENTA,'') 
                                    FROM   FNOT INNER JOIN FTR  ON FTR.N_FACTURA = FNOT.N_FACTURA 
                                                INNER JOIN TTEC ON TTEC.TIPO = FTR.TIPOTTEC
                                    WHERE  FNOT.CNSFNOT = @CNSFNOT
                                    AND    FNOT.CLASE   = @CLASE
					      ELSE IF @DIAS_VCTO >360 AND @DIAS_VCTO<=720 
						      SELECT @CUENTA = DBO.FNK_VALORVARIABLE('CTA_FGLO_360_a_720')
					      ELSE IF @DIAS_VCTO >720 AND @DIAS_VCTO<=1440 
						      SELECT @CUENTA = DBO.FNK_VALORVARIABLE('CTA_FGLO_721_a_1440')
					      ELSE IF @DIAS_VCTO > 1440 
						      SELECT @CUENTA = DBO.FNK_VALORVARIABLE('CTA_FGLO_1441_SUPERI')
				      END
				      ELSE
				      BEGIN   --select * from ttec
				         PRINT 'INGRESA ELSE'
					      SELECT @CUENTA = ISNULL(TTEC.CTAGLOSADB,'') 
					      FROM   FNOT INNER JOIN FTR  ON FTR.N_FACTURA = FNOT.N_FACTURA 
					                  INNER JOIN TTEC ON TTEC.TIPO = FTR.TIPOTTEC
                               WHERE  FNOT.CNSFNOT = @CNSFNOT
                               AND    FNOT.CLASE   = @CLASE
				      END			      
				      IF LTRIM(RTRIM(@CUENTA)) = ''
				      BEGIN
				         PRINT 'NO ENCONTRO CUENTA'
				         SELECT @CUENTA = 'NO DEF.TTEC'
				      END
				      BEGIN
				         PRINT '- Insertando MCH CR con cuenta: ' + @CUENTA
                     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,  
                                      REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                      CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                     SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', @CUENTA, FNOT.IDTERCERO,'' AS CCOSTO, 
                            'NOTA CREDITO FA: '+ FNOT.N_FACTURA, FNOT.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                            DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                            'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA, FTR.F_VENCE, 'NOTDBCR', @CNSFNOT, 
                            FNOT.CODUNG, FNOT.CODPRG
                     FROM   FNOT, KCDE,FTR LEFT JOIN TTEC ON TTEC.TIPO = FTR.TIPOTTEC 
                     WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT 
                     AND    KCDE.TIPO         = 'CXC_GLOSAS' 
                     AND    FNOT.VR_TOTAL      <> 0 
                     AND    FTR.N_FACTURA     = FNOT.N_FACTURA
                     AND    FNOT.CNSFNOT = @CNSFNOT
                     AND    FNOT.CLASE   = @CLASE
                     
                     PRINT 'TERMINA TTEC'
                  END   
               END
			   ELSE
			   BEGIN
			      /*JEDM: 17.FEB.2011  LA PARTE CREDITO DE LA NOTA CREDITO DE AUDITORIA LA RECOGE DEL CONCEPTO DE NOTA*/
			      IF DBO.FNK_VALORVARIABLE('CTA_CR_FNOT_DE_CPNT') = 'SI'
			      BEGIN
					 PRINT 'Credito CPNT'

				    PRINT 'ES DE TIPO SERVICIO...CUENTA CREDITO DE TTECT'
				    INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,  
				                     REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
 				                     CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
				    SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', TTEC.CTAGLOSADB, FNOT.IDTERCERO,'' AS CCOSTO, 
					       'NOTA CREDITO FA: '+ FNOT.N_FACTURA, FNOTD.VR_TOTAL, FNOTD.IDSERVICIO, 'C', NULL, @USUARIO, 
					 	  DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
					       'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA, FTR.F_VENCE, 'NOTDBCR', @CNSFNOT, 
					       FNOT.CODUNG, FNOT.CODPRG
				    FROM   FNOT INNER JOIN FNOTD ON FNOT.CNSFNOT = FNOTD.CNSFNOT
                                                     AND FNOT.CLASE   = FNOTD.CLASE, FTR,TTEC
				    WHERE  FNOT.VR_TOTAL      > 0 
				    AND    FTR.N_FACTURA     = FNOT.N_FACTURA 
				    AND    FTR.TIPOTTEC = TTEC.TIPO
                        AND    FNOT.CNSFNOT = @CNSFNOT
                        AND    FNOT.CLASE   = @CLASE
					   
				  END
			      ELSE
			      BEGIN
					  PRINT ' Credito KCDE'  
					  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,  
								    REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
	 							    CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
					  SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', KCDE.CUENTA, FNOT.IDTERCERO,'' AS CCOSTO, 
						    'NOTA CREDITO FA: '+ FNOT.N_FACTURA, FNOT.VR_TOTAL, NULL, 'C', NULL, @USUARIO, 
						    DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
						    'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA, FTR.F_VENCE, 'NOTDBCR', @CNSFNOT, 
						    FNOT.CODUNG, FNOT.CODPRG
					  FROM   FNOT, KCDE,FTR
					  WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT 
					  AND    KCDE.TIPO         = 'CXC_GLOSAS' 
					  AND    FNOT.VR_TOTAL      <> 0 
					  AND    FTR.N_FACTURA     = FNOT.N_FACTURA
                           AND    FNOT.CNSFNOT = @CNSFNOT
                           AND    FNOT.CLASE   = @CLASE

                  END   
			   END
            END
         END  -- ELSE (SELECT MCUEORDEN_GLOSAS FROM PAR WHERE COMPANIA=@COMPANIA) = 'Si'
      END --IF (SELECT PROCEDENCIA FROM #T)='AUDITORIA'
      ELSE
      BEGIN
         IF     (SELECT PROCEDENCIA FROM FNOT WHERE FNOT.CNSFNOT = @CNSFNOT AND    FNOT.CLASE   = @CLASE)='NOTAS' 
             OR (SELECT PROCEDENCIA FROM FNOT WHERE FNOT.CNSFNOT = @CNSFNOT AND    FNOT.CLASE   = @CLASE)='FACTURA'
         BEGIN
            IF @ORIGENFTR<>'ARS'
            BEGIN
               IF DBO.FNK_VALORVARIABLE('IDCUENTANOTAS') = 'SI'
               BEGIN
                  PRINT 'IDCUENTASNOTAS = SI'
                  -- AGREGADO R.JAY 2009.04.01 PARA EVITAR NOTAS CON SERVICIOS Y NO CON CONCEPTOS
                  -- YA QUE EL CONCEPTO TRAE UNA CUENTA CONTABLE MIENTRAS QUE EL SERVICIO TRAE NULL
               IF EXISTS(SELECT * FROM DBO.FNK_TABLA_DESTRING(@LINEA,',') WHERE CAMPO=''+@CODCONCEPTO+'')
               BEGIN
                  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                  REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                  CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                  SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',CASE WHEN COALESCE(@VANTE,0)=1 
                                                               THEN LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING')))  ELSE  CPNT.CUENTA END,
                         DBO.FNK_MUESTRAPROVEEDOR(FNOT.N_FACTURA,FNOTD.N_CUOTA),'' AS CCOSTO,'NOTA CREDITO FA: '+FNOT.N_FACTURA , FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                         DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                         'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FNOT.F_NOTA, FNOT.F_NOTA, 'NOTDBCR', @CNSFNOT,
                         FNOT.CODUNG, FNOT.CODPRG
                  FROM   FNOT INNER JOIN  FNOTD ON FNOT.CNSFNOT = FNOTD.CNSFNOT
                                               AND FNOT.CLASE   = FNOTD.CLASE
                               LEFT JOIN   CPNT ON FNOT.IDCONCEPTO = CPNT.CODIGO
                  WHERE  FNOT.CNSFNOT = @CNSFNOT
                  AND    FNOT.CLASE   = @CLASE
                  AND    FNOTD.VR_TOTAL>0
                  AND    CPNT.CODIGO=@CODCONCEPTO
               END
               ELSE
               BEGIN
                  PRINT 'POR ACA VOY AL DEBITO'
				      print '@VANTE='+STR(COALESCE(@VANTE,0))
				      print '@pgp='+STR(COALESCE(@pgp,0))
                  PRINT 'VALIDO PROCEDENCIA FINANCIERO, CAPITA Y PGP '
                  IF COALESCE(@ESANULACION,0)=1 AND COALESCE(@VANTE,0)=0 
                  BEGIN
                     PRINT 'ES ANULACION BUSCO EL COMPROBANTE ORIGINAL DE LA FACTURA'
                     DECLARE @NROCOMPROBANTEFTR VARCHAR(20)
                     DECLARE @PYG DECIMAL(14,2)
                     DECLARE @NROASIENTO INT

                     DELETE MCHE WHERE NROCOMPROBANTE= @NROCOMPROBANTE AND TIPO='DB'

                     SELECT @NROCOMPROBANTEFTR=NROCOMPROBANTE FROM FTR WHERE N_FACTURA=@N_FACTURA

                     PRINT  '@NROCOMPROBANTEFTR='+@NROCOMPROBANTEFTR

                     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                      REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                      CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                     SELECT @NROCOMPROBANTE, COMPANIA,'DB', CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                      REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                      CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
                     FROM MCH 
                     WHERE NROCOMPROBANTE=@NROCOMPROBANTEFTR
                     AND TIPO='CR'

                  END
                  ELSE
                  BEGIN
                     PRINT 'NO ES ANULACION'
                        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                          REFERENCIA2,REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                          CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                        SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',
                                 CASE WHEN COALESCE(@VANTE,0)=1 
                                    THEN LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING')))  
                                    ELSE
                                    CASE WHEN FNOTD.TIPO='C' THEN CPNT.CUENTA 
								         WHEN FTR.PROCEDENCIA='FINANCIERO' THEN C2.CUENTA 
                                          ELSE DBO.FNK_NC_CUENTA_KMCOM('01','VENTAS','CR',FNOTD.PREFIJO, FNOTD.CCOSTO,'P','',@PGP) 
                                    END 
                                 END,
                                 DBO.FNK_MUESTRAPROVEEDOR(FNOT.N_FACTURA,FNOTD.N_CUOTA),'' AS CCOSTO,'NOTA CREDITO FA: '+FNOT.N_FACTURA ,
                                 CASE WHEN COALESCE(FNOTD.VALORIVA,0)>0 AND COALESCE(CNSMOV_DEV,'')='' THEN  FNOTD.VR_TOTAL-COALESCE(FNOTD.VALORIVA,0) ELSE  FNOTD.VR_TOTAL END,
                                 NULL, NULL,CASE WHEN COALESCE(FNOTD.VALORIVA,0)>0 THEN 'IVA' ELSE NULL END, NULL, @USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                                 'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FNOT.F_NOTA, FNOT.F_NOTA, 'NOTDBCR', @CNSFNOT,
                                 FNOT.CODUNG, FNOT.CODPRG
                        FROM   FNOT INNER JOIN  FNOTD ON FNOT.CNSFNOT = FNOTD.CNSFNOT
                                                      AND FNOT.CLASE   = FNOTD.CLASE
								      INNER JOIN FTR ON FTR.N_FACTURA = FNOT.N_FACTURA
                                       LEFT JOIN   CPNT ON FNOTD.IDSERVICIO = CPNT.CODIGO
                                       LEFT JOIN   CPNT C2 ON FNOT.IDCONCEPTO = C2.CODIGO
                        WHERE  FNOT.CNSFNOT = @CNSFNOT
                        AND    FNOT.CLASE   = @CLASE
                        AND    FNOTD.VR_TOTAL>0
                     END
                     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                       REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                       CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                     SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',FTRD.CUENTA_FIMPDV,
                              DBO.FNK_MUESTRAPROVEEDOR(FNOT.N_FACTURA,FNOTD.N_CUOTA),'' AS CCOSTO,'NOTA CREDITO FA: '+FNOT.N_FACTURA ,
                              FNOTD.VALORIVA,NULL, NULL, NULL, @USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                              'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FNOT.F_NOTA, FNOT.F_NOTA, 'NOTDBCR', @CNSFNOT,
                              FNOT.CODUNG, FNOT.CODPRG
                     FROM   FNOT INNER JOIN  FNOTD ON FNOT.CNSFNOT = FNOTD.CNSFNOT
                                                   AND FNOT.CLASE   = FNOTD.CLASE
                                    INNER JOIN FTRD ON FNOT.N_FACTURA=FTRD.N_FACTURA AND FNOTD.N_CUOTA=FTRD.N_CUOTA
                                    LEFT JOIN   CPNT ON FNOTD.IDSERVICIO = CPNT.CODIGO
                     WHERE  FNOT.CNSFNOT = @CNSFNOT
                     AND    FNOT.CLASE   = @CLASE
                     AND    COALESCE(FNOTD.VALORIVA,0)>0


                  END 
               END
               ELSE
------------------------------------------------------------------------------------ STORRES
			   BEGIN
                  IF EXISTS(SELECT * FROM DBO.FNK_TABLA_DESTRING(@LINEA,',') WHERE CAMPO=''+@CODCONCEPTO+'')
                  BEGIN
                     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                     REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                     CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                     SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',  CPNT.CUENTA ,
                            DBO.FNK_MUESTRAPROVEEDOR(FNOT.N_FACTURA,FNOTD.N_CUOTA),'' AS CCOSTO,'Directo - NOTA CREDITO FA: '+FNOT.N_FACTURA , FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                            DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                            'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FNOT.F_NOTA, FNOT.F_NOTA, 'NOTDBCR', @CNSFNOT,
                            FNOT.CODUNG, FNOT.CODPRG
                     FROM   FNOT INNER JOIN  FNOTD ON FNOT.CNSFNOT = FNOTD.CNSFNOT
                                                  AND FNOT.CLASE   = FNOTD.CLASE
                                  LEFT JOIN   CPNT ON FNOT.IDCONCEPTO = CPNT.CODIGO
                     WHERE  FNOT.CNSFNOT = @CNSFNOT
                     AND    FNOT.CLASE   = @CLASE
                     AND    FNOTD.VR_TOTAL>0
                     AND    CPNT.CODIGO=@CODCONCEPTO
                  END
                  ELSE 
                  BEGIN
						   PRINT 'INGRESO AQUI.........'
						   PRINT 'CSNOTA ='+@CNSFNOT
                     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
	                                 REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
	                                 CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                     SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',
                      CASE WHEN COALESCE(@VANTE,0)=1 
                           THEN LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING')))  
                           ELSE CASE WHEN FNOTD.TIPO='C' AND @CAPITADO=0 THEN  KCDE.CUENTA 
				                         WHEN @CAPITADO=1                    THEN KCDE.CUENTA  
                                     WHEN @CAPITADO=1                    THEN KCDE.CUENTA  
                                     ELSE DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'VENTAS','CR',FNOTD.PREFIJO, FNOTD.CCOSTO,'P','',@PGP) 
                                END 
                      END,
                      DBO.FNK_MUESTRAPROVEEDOR(FNOT.N_FACTURA,FNOTD.N_CUOTA),'' AS CCOSTO, 
                           LEFT('NOTA CREDITO FA: '+ FNOT.N_FACTURA+' MOTIVO:'+LTRIM(RTRIM(LEFT(DBO.FNK_RTF(FNOTD.OBSERVACION),470))),512) , FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
	                       DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
	                       'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
	                       FNOT.CODUNG, FNOT.CODPRG
	                   FROM   FNOT INNER JOIN FNOTD ON FNOT.CNSFNOT = @CNSFNOT 
                                                  AND FNOT.CLASE   = @CLASE,KCDE, FTR
	                   WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT                
	                   AND    KCDE.TIPO         = CASE WHEN DBO.FNK_VALORVARIABLE ('CUE_DBCR_ARS') = 'NO' THEN 'CXC_NTCR' ELSE 'CXC_NTDB' END -- JREYES 20090619 
	                   AND    FNOT.VR_TOTAL      <> 0 
	                   AND    FTR.N_FACTURA     = FNOT.N_FACTURA
                      AND    FNOT.CNSFNOT      = @CNSFNOT
                      AND    FNOT.CLASE        = @CLASE
                      AND    FNOTD.VR_TOTAL>0
					       AND    FNOTD.CNSFNOT=@CNSFNOT
                   END
               END    
------------------------------------------------------------------------------------------------------ STORRES
               PRINT ' Creditos...'
               IF dbo.FNK_VALORVARIABLE('CONTABCXC')= 'SI'
               BEGIN
                  PRINT 'INGRESO A CONTABCXC'
                  IF (SELECT COALESCE(COUNT(*),0) FROM FCXCD A INNER JOIN FCXC B ON A.CNSCXC=B.CNSCXC WHERE B.INDRECIBIDO=1 AND A.N_FACTURA=@N_FACTURA)=1
                  BEGIN
                     SELECT @CUENTANOT = CUENTARAD 
                     FROM   FTR A INNER JOIN TTEC B ON A.TIPOTTEC = B.TIPO 
                     WHERE  A.N_FACTURA = @N_FACTURA
                  END
                  ELSE
                  BEGIN
                     SELECT @CUENTANOT=CUENTA 
                     FROM FTR A INNER JOIN TTEC B ON A.TIPOTTEC=B.TIPO 
                     WHERE A.N_FACTURA=@N_FACTURA                  
                  END
                  IF COALESCE(@CUENTANOT,'')= ''
                  BEGIN
                     SELECT @CUENTANOT=CUENTACXC FROM FTR WHERE N_FACTURA=@N_FACTURA
                  END

                  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                   REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                   CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                  SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',@CUENTANOT, FNOT.IDTERCERO,'' AS CCOSTO, -- JREYES 20090619
                         'NOTA CREDITO FA: '+ FNOT.N_FACTURA ,FNOT.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                         DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                         'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
                         FNOT.CODUNG, FNOT.CODPRG
                  FROM   FNOT, FTR 
                  WHERE  FNOT.VR_TOTAL      <> 0 
	               AND    FTR.N_FACTURA     = FNOT.N_FACTURA
                  AND    FNOT.CNSFNOT = @CNSFNOT
                  AND    FNOT.CLASE   = @CLASE
                  PRINT 'TERMINO EL INSERT'

                  PRINT 'VALIDO PROCEDENCIA FINANCIERO, CAPITA Y PGP '
                  IF COALESCE(@ESANULACION,0)=1 AND COALESCE(@VANTE,0)=0 
                  BEGIN
                     PRINT 'REVISO EL COMPROBANTE AJUSTES DE COPAGOS O GANANCIA EN CAPITAS'

                     EXEC SPK_NC_SUMA_DBCR @NROCOMPROBANTE
         
                     SELECT @PYG=TOTALDEBITO-TOTALCREDITO FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE

                     PRINT '@PYG='+CAST(@PYG AS VARCHAR(20))

                     IF @PYG > 0 
                     BEGIN
                        PRINT 'INGRESO A AJUSTAR'
                        SELECT TOP 1 @NROASIENTO= NROASIENTO FROM MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND VALOR>=@PYG AND TIPO='DB'
                        IF COALESCE(@NROASIENTO,0) <> 0
                        BEGIN
                           PRINT 'SI ENCONTRE UNO'
                           UPDATE MCHE SET VALOR= VALOR - @PYG WHERE NROASIENTO=@NROASIENTO AND NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB'
                        END
                     END
                     EXEC SPK_NC_SUMA_DBCR @NROCOMPROBANTE
                  END
	            END
               ELSE
               BEGIN

                  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                     REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                     CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                  SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',FTR.CUENTACXC, FNOT.IDTERCERO,'' AS CCOSTO, -- JREYES 20090619
                         'NOTA CREDITO FA: '+ FNOT.N_FACTURA, FNOT.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                         DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                         'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
                         FNOT.CODUNG, FNOT.CODPRG
                  FROM   FNOT, FTR 
                  WHERE  FNOT.VR_TOTAL      <> 0 
	               AND    FTR.N_FACTURA     = FNOT.N_FACTURA
                  AND    FNOT.CNSFNOT = @CNSFNOT
                  AND    FNOT.CLASE   = @CLASE

	          END


               --------------------------------
               SELECT @VDB = SUM(VALOR) FROM MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND TIPO = 'DB'
               SELECT @VCR = SUM(VALOR) FROM MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND TIPO = 'CR'
               SELECT @VFNOT = VR_TOTAL FROM FNOT WHERE FNOT.CLASE = @CLASE AND FNOT.CNSFNOT=@CNSFNOT
               IF @VDB < @VCR
               BEGIN                 
                  UPDATE MCHE SET VALOR = CONVERT(decimal(14, 6),MCHE.VALOR)  + ( CONVERT(decimal(14, 6),@VFNOT) - CONVERT(decimal(14, 6),C.VALOR))
		            FROM (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCHE WHERE  NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB') AS B,
					        (SELECT SUM(CONVERT(decimal(14, 6),VALOR)) AS VALOR FROM MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' ) AS C
		            WHERE MCHE.NROASIENTO=B.NROASIENTO AND (@VFNOT-C.VALOR) <> 0 
               END
               IF @VDB > @VCR
               BEGIN
                  UPDATE MCHE SET VALOR = CONVERT(decimal(14, 6),MCHE.VALOR)  - ( CONVERT(decimal(14, 6),C.VALOR - CONVERT(decimal(14, 6),@VFNOT)))
		            FROM (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCHE WHERE  NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB') AS B,
					        (SELECT SUM(CONVERT(decimal(14, 6),VALOR)) AS VALOR FROM MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' ) AS C
		            WHERE MCHE.NROASIENTO=B.NROASIENTO AND (@VFNOT-C.VALOR) <> 0 
               END
               PRINT 'TERMINO SUMAS'
               --------------------------------
            END
            ELSE -- PROCEDENCIA NOTAS PROCEDENCIA ARS
            BEGIN
               INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                               REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                               CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
               SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',C.CUENTA_CR,A.IDTERCERO,'','NOTA CREDITO FACT: '+A.N_FACTURA,
                      B.VR_TOTAL,NULL,NULL,NULL, @USUARIO, 
                      DBO.FNK_FECHA_SIN_MLS(GETDATE()), D.AREAPRESTACION,D.NOPRESTACION, 1, 
                      'NOTAS_DBCR', 'Movimiento','S', A.N_FACTURA, A.F_NOTA,A.F_NOTA,'NOTDBCR',@CNSFNOT,
                      A.CODUNG, A.CODPRG
               FROM   FNOT A INNER JOIN FNOTD B ON A.CNSFNOT=B.CNSFNOT
                             INNER JOIN FTRD D ON A.N_FACTURA=D.N_FACTURA AND B.N_CUOTA=D.N_CUOTA
                             INNER JOIN CNTCF C ON D.TIPOCONTRATOARS=C.TIPOCONTRATOARS AND D.ARSTIPOCONTRATO=C.ARSTIPOCONTRATO AND D.NOPRESTACION=C.IDCONCEPTO
               WHERE  A.CNSFNOT = @CNSFNOT
               AND    A.CLASE   = @CLASE 
                          
               PRINT ' Creditos...'
               INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
               SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',C.CUENTA_DB,A.IDTERCERO,'','NOTA CREDITO FACT: '+A.N_FACTURA,
                      B.VR_TOTAL,NULL,NULL,NULL, @USUARIO, 
                      DBO.FNK_FECHA_SIN_MLS(GETDATE()), D.AREAPRESTACION,D.NOPRESTACION, 1, 
                      'NOTAS_DBCR', 'Movimiento','S', A.N_FACTURA, A.F_NOTA,A.F_NOTA,'NOTDBCR',@CNSFNOT,
                      A.CODUNG, A.CODPRG
               FROM   FNOT A INNER JOIN FNOTD B ON A.CNSFNOT=B.CNSFNOT
                             INNER JOIN FTRD D ON A.N_FACTURA=D.N_FACTURA AND B.N_CUOTA=D.N_CUOTA
                             INNER JOIN CNTCF C ON D.TIPOCONTRATOARS=C.TIPOCONTRATOARS AND D.ARSTIPOCONTRATO=C.ARSTIPOCONTRATO AND D.NOPRESTACION=C.IDCONCEPTO
               WHERE  A.CNSFNOT = @CNSFNOT
               AND    A.CLASE   = @CLASE 
               AND    B.VR_TOTAL>0
            END            
         END
         ELSE
         BEGIN
            PRINT '--CONCILIACIONES Y OTRAS PROCEDENCIAS'
            IF @PROCEDENCIA='CONCILIA'
            BEGIN
               SELECT @CUENTACONC=dbo.FNK_VALORVARIABLE('IDCOPNOTACONCI')              
               IF @CUENTACONC <> '' 
               BEGIN
                  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
	                                REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
	                                CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
	               SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',CASE WHEN COALESCE(@VANTE,0)=1 THEN LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING')))
                          ELSE CPNT.CUENTA END, FNOT.IDTERCERO,'' AS CCOSTO, 
	                      'NOTA CREDITO CONCI FA: '+ FNOT.N_FACTURA, FNOT.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
	                      DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
	                      'NOTAS_DBCR', 'Movimiento','C', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
	                      FNOT.CODUNG, FNOT.CODPRG
	               FROM   FNOT INNER JOIN FTR   ON FNOT.N_FACTURA=FTR.N_FACTURA
                              -- Un solo asiento por concepto de la nota (IDCONCEPTO / IDCOPNOTACONCI), no por IDSERVICIO de FNOTD
                              INNER JOIN CPNT  ON CPNT.CODIGO = COALESCE(NULLIF(RTRIM(FNOT.IDCONCEPTO),''), @CUENTACONC)
	               WHERE  FNOT.VR_TOTAL <> 0 
                  AND    FNOT.CNSFNOT   = @CNSFNOT
                  AND    FNOT.CLASE     = @CLASE
	               PRINT 'Debitos... conciliacion'
                  IF DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT')='IPS'
                  BEGIN  
                     IF dbo.FNK_VALORVARIABLE('CONTABCXC')= 'SI'
                     BEGIN      
                        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                      REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                      CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                        SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',CASE WHEN @CASTIGADA=1 THEN D.CUEDIFCOB
                                                                    WHEN B.TIPO='F' THEN D.CUENTARAD 
                                                                    WHEN B.TIPO='G' THEN D.CUENTALG
                                                                    WHEN B.TIPO='R' THEN D.CUENTALG
                                                                    WHEN B.TIPO='C' THEN D.CUENTACG
																	WHEN COALESCE(B.TIPO,'')='' THEN C.CUENTACXC_RAD
                                                                    ELSE 'NO.DEF.TIPO' END
                        ,     A.IDTERCERO,'' AS CCOSTO,'NOTA CREDITO CONCI FA: '+A.N_FACTURA, A.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                               DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                              'NOTAS_DBCR', 'Movimiento','S', A.N_FACTURA, C.F_FACTURA,C.F_VENCE,'NOTDBCR',@CNSFNOT, 
                              A.CODUNG, A.CODPRG
                        FROM    FNOT A INNER JOIN FTR     C ON A.N_FACTURA=C.N_FACTURA
									   INNER JOIN TTEC    D ON C.TIPOTTEC=D.TIPO
						               LEFT JOIN FCONCID B ON A.CNSFNOT=B.CNSFNOT
                                    
                                  
                        WHERE  A.CNSFNOT = @CNSFNOT
                        AND    A.CLASE   = @CLASE

	                     print'Creditos... Conciliacion'
	                     PRINT'GENERO REGISTRO EN CONTABILIDAD'
	                  END
	                  ELSE
	                  BEGIN
                        INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                  REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                    CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                        SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', CASE WHEN DBO.FNK_VALORVARIABLE ('CUE_DBCR_ARS') = 'NO' THEN FTR.CUENTACXC_RAD ELSE KCDE.CUENTA END , A.IDTERCERO,'' AS CCOSTO, -- JREYES 20090619
                             'NOTA CREDITO CONCI FA: '+A.N_FACTURA, A.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                              DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                             'NOTAS_DBCR', 'Movimiento','S', A.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
                             A.CODUNG, A.CODPRG
                        FROM   FNOT A, FTR, KCDE
                        WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT -- JREYES 20090619 
	                     AND    KCDE.TIPO         = 'CXC_NTCR' -- JREYES 20090619 
	                     AND    A.VR_TOTAL      <> 0 
	                     AND    FTR.N_FACTURA     = A.N_FACTURA
                        AND    A.CNSFNOT = @CNSFNOT
                        AND    A.CLASE   = @CLASE
	                     print'Creditos... Conciliacion'
	                     PRINT'GENERO REGISTRO EN CONTABILIDAD'	               
	                  END
                  END

--query2 
--query2      
                  ELSE
                  BEGIN
                     PRINT 'ARS'
                     SELECT @DIASVENCE = DATEDIFF(DAY,F_FACTURA,GETDATE()) FROM FTR WHERE N_FACTURA=@N_fACTURA
                     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                    REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                    CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                     SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', CASE WHEN @DIASVENCE>360 THEN C.CTAVIGENCIAANTE ELSE 
                            COALESCE(C.CUENTACXC,(SELECT TOP 1 CUENTA FROM MCH WHERE NROCOMPROBANTE=C.NROCOMPROBANTE AND TIPO='DB' AND MCH.N_FACTURA=C.N_FACTURA))
                            END, A.IDTERCERO,'' AS CCOSTO,'NOTA CREDITO CONCI FA: '+A.N_FACTURA, A.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                              DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                           'NOTAS_DBCR', 'Movimiento','S', A.N_FACTURA, C.F_FACTURA,C.F_VENCE,'NOTDBCR',@CNSFNOT, 
                           A.CODUNG, A.CODPRG
                     FROM    FNOT A INNER JOIN FCONCID B ON A.CNSFNOT=B.CNSFNOT
                                 INNER JOIN FTR     C ON A.N_FACTURA=C.N_FACTURA
                     WHERE  A.CNSFNOT = @CNSFNOT
                     AND    A.CLASE   = @CLASE
                     AND    C.N_FACTURA=@N_FACTURA
	                  print'Creditos... Conciliacion'
	                  PRINT'GENERO REGISTRO EN CONTABILIDAD'
                  END
	            END 
	            ELSE
	            BEGIN
	               PRINT 'NO EXISTE CONFIGURACION CONTABLE PARA CONCILIACIONES'
	               RAISERROR('NO EXISTE CONFIGURACION CONTABLE PARA CONCILIACIONES',16,1)
	               RETURN
	            END       
            END
            ELSE
            BEGIN
               PRINT '@PROCEDENCIA='+@PROCEDENCIA
               INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
	                               REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
	                               CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
	           SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',CASE WHEN COALESCE(@VANTE,0)=1 THEN LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING')))
                        ELSE  CPNT.CUENTA END , FNOT.IDTERCERO,COALESCE(FNOTD.CCOSTO,'') AS CCOSTO, 
	                   'NOTA CREDITO POR '+@PROCEDENCIA+' DE FA: '+ FNOT.N_FACTURA, FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
	                   DBO.FNK_FECHA_SIN_MLS(GETDATE()), COALESCE(FNOTD.IDAREA,'') AS IDAREA, COALESCE(FNOTD.PREFIJO,'') AS PREFIJO, 1, 
	                   'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
	                   FNOT.CODUNG, FNOT.CODPRG 
	           FROM   FNOT INNER JOIN FTR ON FTR.N_FACTURA=FNOT.N_fACTURA
                           INNER JOIN FNOTD ON FNOT.CNSFNOT=FNOTD.CNSFNOT
                           INNER JOIN CPNT  ON FNOTD.IDSERVICIO=CPNT.CODIGO
	           WHERE  FNOT.VR_TOTAL <> 0 
                      AND    FNOT.CNSFNOT   = @CNSFNOT
                      AND    FNOT.CLASE     = @CLASE
					  AND    FNOTD.VR_TOTAL <> 0
	           PRINT 'Debitos... '+@PROCEDENCIA
                     
               IF dbo.FNK_VALORVARIABLE('CONTABCXC')= 'SI'
               BEGIN      
                  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,REFERENCIA2, ITEMREF, 
				                   USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, 
								   PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)

				  SELECT X.NROCOMPROBANTE,X.COMPANIA,'CR',X.CUENTA,X.IDTERCERO,X.CCOSTO,X.DETALLE,SUM(X.VR_TOTAL),NULL,NULL,NULL,
						 X.USUARIO,X.FECHA,X.IDAREA,X.PREFIJO,1,'NOTAS_DBCR','Movimiento','S',X.N_FACTURA,X.F_FACTURA,X.F_VENCE,
						 'NOTDBCR',X.NOTA,X.CODUNG,X.CODPRG
				  FROM (
					  SELECT @NROCOMPROBANTE AS NROCOMPROBANTE, @COMPANIA AS COMPANIA,
															  CASE WHEN @CASTIGADA=1 THEN D.CUEDIFCOB
                                                    WHEN B.TIPO='F' THEN D.CUENTARAD 
																    WHEN B.TIPO='G' THEN D.CUENTALG
																    WHEN B.TIPO='R' THEN D.CUENTALG
																    WHEN B.TIPO='C' THEN D.CUENTACG
																    WHEN B.TIPO='P' THEN D.CUENTA
																   ELSE 'NO.DEF.TIPO' END AS CUENTA,
							A.IDTERCERO,'' AS CCOSTO,'NOTA CREDITO POR '+@PROCEDENCIA+' DE FA: '+A.N_FACTURA AS DETALLE, B.VR_TOTAL,
							@USUARIO AS USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()) AS FECHA, '' AS IDAREA, '' AS PREFIJO, 
							A.N_FACTURA, C.F_FACTURA, C.F_VENCE, @CNSFNOT AS NOTA, A.CODUNG, A.CODPRG
					  FROM    FNOT A INNER JOIN FNOTD   B ON A.CNSFNOT=B.CNSFNOT
									 INNER JOIN FTR     C ON A.N_FACTURA=C.N_FACTURA
									 INNER JOIN TTEC    D ON C.TIPOTTEC=D.TIPO
					  WHERE  A.CNSFNOT = @CNSFNOT
					  AND    A.CLASE   = @CLASE
					  AND    B.VR_TOTAL>0 ) X
				     GROUP BY X.NROCOMPROBANTE,X.COMPANIA,X.CUENTA,X.IDTERCERO,X.CCOSTO,X.DETALLE,X.USUARIO,X.FECHA,X.IDAREA,X.PREFIJO,
				          X.N_FACTURA,X.F_FACTURA,X.F_VENCE,X.NOTA,X.CODUNG,X.CODPRG
							  
	              PRINT 'Creditos... '+@PROCEDENCIA
	              PRINT 'GENERO REGISTRO EN CONTABILIDAD'
	            END
	            ELSE
	            BEGIN
                  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                              REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                              CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                  SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', CASE WHEN DBO.FNK_VALORVARIABLE ('CUE_DBCR_ARS') = 'NO' THEN FTR.CUENTACXC_RAD ELSE KCDE.CUENTA END , A.IDTERCERO,'' AS CCOSTO, -- JREYES 20090619
                        'NOTA CREDITO CONCI FA: '+A.N_FACTURA, A.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                        DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                        'NOTAS_DBCR', 'Movimiento','S', A.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
                        A.CODUNG, A.CODPRG
                  FROM   FNOT A, FTR, KCDE
                  WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT -- JREYES 20090619 
	                AND    KCDE.TIPO         = 'CXC_NTCR' -- JREYES 20090619 
	                AND    A.VR_TOTAL      <> 0 
	                AND    FTR.N_FACTURA     = A.N_FACTURA
                    AND    A.CNSFNOT = @CNSFNOT
                    AND    A.CLASE   = @CLASE
	              PRINT 'Creditos... '+@PROCEDENCIA
	              PRINT'GENERO REGISTRO EN CONTABILIDAD'
                END	
            END
         END
      END
   END -- IF  @CLASE='C'
   IF @CLASE='D'
   BEGIN
      PRINT 'Contabilizando Notas Debito...' 
      IF (SELECT PROCEDENCIA FROM FNOT WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE)='AUDITORIA'
      BEGIN
         PRINT 'Proviene de Auditoria.' 
         IF (SELECT MCUEORDEN_GLOSAS FROM PAR WHERE COMPANIA=@COMPANIA)='Si'
         BEGIN
            PRINT ' Si Usa cuentas de Orden.'
            PRINT ' Contabilizando DB Glosas con Cuentas de Orden...' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                            CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', CASE WHEN CUE.CUENTA IS NULL THEN 'NO CUEORDENGLOSA' ELSE CUE.CUENTA END, 
                   FNOT.IDTERCERO, #REF.CCOSTO, 'CUENTA DE ORDEN POR GLOSAS DE FA '+ FNOT.N_FACTURA, SUM(#REF.VALOR), 
                   NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #REF.IDAREA, #REF.PREFIJO, 1, 
                   'CUEORDENGLOSADB', 'Movimiento','S', FNOT.N_FACTURA, #REF.F_FACTURA, #REF.F_VENCE, 'FNOT', @CNSFNOT, 
                   FNOT.CODUNG, FNOT.CODPRG
            FROM   FNOT ,#REF LEFT JOIN TTEC ON TTEC.TIPO=#REF.TIPOTTEC 
                              LEFT JOIN CUE  ON TTEC.CUEORDENGLOSADB = CUE.CUENTA 
                                            AND CUE.COMPANIA         = @COMPANIA
            WHERE  FNOT.CNSFNOT = @CNSFNOT 
            AND    FNOT.CLASE = @CLASE
            GROUP BY CUE.CUENTA, FNOT.IDTERCERO, #REF.CCOSTO, FNOT.N_FACTURA, #REF.IDAREA, #REF.PREFIJO, #REF.F_FACTURA, #REF.F_VENCE, 
                     FNOT.CODUNG, FNOT.CODPRG
            HAVING SUM(#REF.VALOR)>0
            
            PRINT ' Contabilizando CR Glosas con Cuentas de Orden...' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA,    
                            CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', CASE WHEN CUE.CUENTA IS NULL THEN 'NO CUEORDENGLOSA' ELSE CUE.CUENTA END, 
                   FNOT.IDTERCERO, #REF.CCOSTO, 'CUENTA DE ORDEN POR GLOSAS DE FA '+FNOT.N_FACTURA, SUM(#REF.VALOR), 
                   NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #REF.IDAREA, #REF.PREFIJO, 1, 
                   'CUEORDENGLOSACR', 'Movimiento','S', FNOT.N_FACTURA, #REF.F_FACTURA, #REF.F_VENCE, 'FNOT', @CNSFNOT,
                   FNOT.CODUNG, FNOT.CODPRG
            FROM   FNOT,#REF LEFT JOIN TTEC ON TTEC.TIPO            = #REF.TIPOTTEC 
                             LEFT JOIN CUE  ON TTEC.CUEORDENGLOSACR = CUE.CUENTA 
                                           AND CUE.COMPANIA         = @COMPANIA
            WHERE  FNOT.CNSFNOT = @CNSFNOT
            AND    FNOT.CLASE   = @CLASE
            GROUP BY CUE.CUENTA, FNOT.IDTERCERO, #REF.CCOSTO, FNOT.N_FACTURA, #REF.IDAREA, #REF.PREFIJO, #REF.F_FACTURA, #REF.F_VENCE,
                     FNOT.CODUNG, FNOT.CODPRG
            HAVING SUM(#REF.VALOR)>0
         END
         ELSE
         BEGIN
            PRINT ' No Usa cuentas de Orden.'
            PRINT ' Debitos...'
            PRINT 'REVISANDO EL ESTADO DE LA FACTURA'
            --SELECT TOP 10 * FROM FTR
            SELECT @YARAD=COUNT(*) FROM FCXC A INNER JOIN FCXCD B ON A.CNSCXC=B.CNSCXC
            WHERE B.N_FACTURA=@N_FACTURA AND A.INDRECIBIDO=1 
            IF @YARAD>0 
            BEGIN 
               SELECT @CUENTANOT=CUENTACXC_RAD FROM FTR WHERE N_FACTURA=@N_FACTURA
            END
            ELSE
            BEGIN
               SELECT @CUENTANOT=CUENTACXC FROM FTR WHERE N_FACTURA=@N_FACTURA
            END
            
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                            CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',@CUENTANOT,FNOT.IDTERCERO,'' AS CCOSTO, 
                   'NOTA CREDITO FA: '+FNOT.N_FACTURA, FNOT.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                   DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                   'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT,
                   FNOT.CODUNG, FNOT.CODPRG
            FROM   FNOT, KCDE,FTR
            WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT 
            AND    KCDE.TIPO         = 'CXC_GLOSAS' 
            AND    FNOT.VR_TOTAL      <> 0 
            AND    FTR.N_FACTURA     = FNOT.N_FACTURA 
            AND    FNOT.CNSFNOT      = @CNSFNOT
            AND    FNOT.CLASE        = @CLASE
          
            PRINT  'Credito' 
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                            CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
            SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', KCDE.CUENTA,FNOT.IDTERCERO,'' AS CCOSTO, 
                   'NOTA CREDITO FA: '+FNOT.N_FACTURA, FNOT.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                   DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                   'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
                   FNOT.CODUNG, FNOT.CODPRG
            FROM   FNOT, KCDE,FTR
            WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT 
            AND    KCDE.TIPO         = 'CXC_NTDB' 
            AND    FNOT.VR_TOTAL      <> 0 
            AND    FTR.N_FACTURA     = FNOT.N_FACTURA
            AND    FNOT.CNSFNOT      = @CNSFNOT
            AND    FNOT.CLASE        = @CLASE
         END
      END 
      IF @PROCEDENCIA='CONCILIA'
      BEGIN
         PRINT 'REVERSION DE CONCILIACIONES.... '
         SELECT @CUENTACONC=dbo.FNK_VALORVARIABLE('IDCOPNOTACONCI')              
         IF @CUENTACONC <> '' 
         BEGIN
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
	                           REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
	                           CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
	         SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',CASE WHEN COALESCE(@VANTE,0)=1 THEN LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_REVDOC_AANTING')))
                     ELSE CPNT.CUENTA END, FNOT.IDTERCERO,'' AS CCOSTO, 
	                  'NOTA CREDITO ANULA  CONCI FA: '+ FNOT.N_FACTURA, FNOT.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
	                  DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
	                  'NOTAS_DBCR', 'Movimiento','D', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
	                  FNOT.CODUNG, FNOT.CODPRG
	         FROM   FNOT INNER JOIN FTR   ON FNOT.N_FACTURA=FTR.N_FACTURA
                        -- Contrapartida por concepto de la nota, un solo asiento (evita cruce con servicios de FNOTD)
                        INNER JOIN CPNT  ON CPNT.CODIGO = COALESCE(NULLIF(RTRIM(FNOT.IDCONCEPTO),''), @CUENTACONC)
	         WHERE  FNOT.VR_TOTAL <> 0 
            AND    FNOT.CNSFNOT   = @CNSFNOT
            AND    FNOT.CLASE     = @CLASE
	         PRINT 'Debitos... conciliacion '
            IF DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT')='IPS'
            BEGIN  
               IF dbo.FNK_VALORVARIABLE('CONTABCXC')= 'SI'
               BEGIN      
                  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                                 REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                                 CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                  SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',CASE WHEN @CASTIGADA=1 THEN D.CUEDIFCOB
                                                               WHEN B.TIPO='F' THEN D.CUENTARAD 
                                                               WHEN B.TIPO='G' THEN D.CUENTALG
                                                               WHEN B.TIPO='R' THEN D.CUENTALG
                                                               WHEN B.TIPO='C' THEN D.CUENTACG
                                                               WHEN COALESCE(B.TIPO,'')='' THEN C.CUENTACXC_RAD

                                                               ELSE 'NO.DEF.TIPO' END
                  ,     A.IDTERCERO,'' AS CCOSTO,'NOTA DEBITO CONCI FA: '+A.N_FACTURA, A.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                           DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                        'NOTAS_DBCR', 'Movimiento','S', A.N_FACTURA, C.F_FACTURA,C.F_VENCE,'NOTDBCR',@CNSFNOT, 
                        A.CODUNG, A.CODPRG

                  FROM    FNOT A INNER JOIN FTR     C ON A.N_FACTURA=C.N_FACTURA
                                 INNER JOIN TTEC    D ON C.TIPOTTEC=D.TIPO
								 LEFT JOIN FCONCID B ON A.CNSFNOT=B.CNSNOTADB
                              
                  WHERE  A.CNSFNOT = @CNSFNOT
                  AND    A.CLASE   = @CLASE

	               print'Creditos... Conciliacion'
	               PRINT'GENERO REGISTRO EN CONTABILIDAD'
	            END
	            ELSE
	            BEGIN
                  INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                              REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                              CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
                  SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', CASE WHEN DBO.FNK_VALORVARIABLE ('CUE_DBCR_ARS') = 'NO' THEN FTR.CUENTACXC_RAD ELSE KCDE.CUENTA END , A.IDTERCERO,'' AS CCOSTO, -- JREYES 20090619
                        'NOTA DEBITO CONCI FA: '+A.N_FACTURA, A.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                        DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                        'NOTAS_DBCR', 'Movimiento','S', A.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
                        A.CODUNG, A.CODPRG
                  FROM   FNOT A, FTR, KCDE
                  WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT -- JREYES 20090619 
	               AND    KCDE.TIPO         = 'CXC_NTCR' -- JREYES 20090619 
	               AND    A.VR_TOTAL      <> 0 
	               AND    FTR.N_FACTURA     = A.N_FACTURA
                  AND    A.CNSFNOT = @CNSFNOT
                  AND    A.CLASE   = @CLASE
	               print'Creditos... Conciliacion'
	               PRINT'GENERO REGISTRO EN CONTABILIDAD'	               
	            END
            END
         END
      END
      IF @PROCEDENCIA='NOTAS'
      BEGIN
         PRINT 'No Proviene de auditoria.'
         PRINT 'REVISANDO EL ESTADO DE LA FACTURA'
         --SELECT TOP 10 * FROM FTR
         SELECT @YARAD=COUNT(*) FROM FCXC A INNER JOIN FCXCD B ON A.CNSCXC=B.CNSCXC
         WHERE B.N_FACTURA=@N_FACTURA AND A.INDRECIBIDO=1 
         IF @YARAD>0 
         BEGIN 
            SELECT @CUENTANOT=CUENTACXC_RAD FROM FTR WHERE N_FACTURA=@N_FACTURA
         END
         ELSE
         BEGIN
            SELECT @CUENTANOT=CUENTACXC_RAD FROM FTR WHERE N_FACTURA=@N_FACTURA
         END
         INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                         REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                         CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
         SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', @CUENTANOT, --AGREGADO JJIMENEZ 2013.04.04 
                FNOT.IDTERCERO, '' AS CCOSTO, 'NOTA DEBITO FA: '+FNOT.N_FACTURA, FNOT.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
                DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
                'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
                FNOT.CODUNG, FNOT.CODPRG
         FROM   FNOT, KCDE,FTR
         WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT 
         AND    KCDE.TIPO         = 'CXC_NTCR' 
         AND    FNOT.VR_TOTAL      <> 0 
         AND    FTR.N_FACTURA     = FNOT.N_FACTURA
         AND    FNOT.CNSFNOT      = @CNSFNOT
         AND    FNOT.CLASE        = @CLASE
        
			PRINT ' Creditos...'
			IF EXISTS(SELECT * FROM DBO.FNK_TABLA_DESTRING(@LINEA,',') WHERE CAMPO=''+@CODCONCEPTO+'')
			BEGIN
				INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
								REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
								CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
				SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', CASE WHEN DBO.FNK_VALORVARIABLE('IDCUENTANOTAS') = 'SI' 
																THEN CPNT.CUENTA ELSE KCDE.CUENTA 
														END , FNOT.IDTERCERO,'' AS CCOSTO, 
					'NOTA DEBITO FA: '+FNOT.N_FACTURA, FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
					DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
					'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT,
					FNOT.CODUNG, FNOT.CODPRG
				FROM   FNOT, KCDE, FTR, FNOTD, CPNT
				WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT 
				AND    KCDE.TIPO         = 'CXC_NTDB' 
				AND	   FNOT.IDCONCEPTO   = CPNT.CODIGO
				AND    FNOT.VR_TOTAL      <> 0 
				AND    FTR.N_FACTURA     = FNOT.N_FACTURA
				AND    FNOT.CNSFNOT      = @CNSFNOT
				AND    FNOT.CLASE        = @CLASE
				AND    FNOTD.CNSFNOT     = @CNSFNOT
			END
			ELSE
			BEGIN
				INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
								REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
								CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
				SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', CASE WHEN FNOTD.TIPO='C' AND DBO.FNK_VALORVARIABLE('IDCUENTANOTAS') = 'SI' AND ISNULL(FTR.SI,0)=1 
																THEN CPNT.CUENTA ELSE   KCDE.CUENTA 
														END , FNOT.IDTERCERO,'' AS CCOSTO, 
					'NOTA DEBITO FA: '+FNOT.N_FACTURA, FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
					DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 
					'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT,
					FNOT.CODUNG, FNOT.CODPRG
				FROM   FNOT, KCDE, FTR, FNOTD
						LEFT JOIN   CPNT ON FNOTD.IDSERVICIO = CPNT.CODIGO
				WHERE  KCDE.IDMODELOCONT = @IDMODELOCONT 
				AND    KCDE.TIPO         = 'CXC_NTDB' 
				AND    FNOT.VR_TOTAL      <> 0 
				AND    FTR.N_FACTURA     = FNOT.N_FACTURA
				AND    FNOT.CNSFNOT      = @CNSFNOT
				AND    FNOT.CLASE        = @CLASE
				AND    FNOTD.CNSFNOT     = @CNSFNOT
		  END
      END 
      IF @PROCEDENCIA='AJUSTE'
      BEGIN
         PRINT '@PROCEDENCIA='+@PROCEDENCIA
         INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
	                           REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
	                           CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
	      SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', CPNT.CUENTA, FNOT.IDTERCERO,COALESCE(FNOTD.CCOSTO,'') AS CCOSTO, 
	               'NOTA DEBITO POR '+@PROCEDENCIA+' DE FA: '+ FNOT.N_FACTURA, FNOTD.VR_TOTAL, NULL, NULL, NULL, @USUARIO, 
	               DBO.FNK_FECHA_SIN_MLS(GETDATE()), COALESCE(FNOTD.IDAREA,'') AS IDAREA, COALESCE(FNOTD.PREFIJO,'') AS PREFIJO, 1, 
	               'NOTAS_DBCR', 'Movimiento','S', FNOT.N_FACTURA, FTR.F_FACTURA,FTR.F_VENCE,'NOTDBCR',@CNSFNOT, 
	               FNOT.CODUNG, FNOT.CODPRG 
	      FROM   FNOT INNER JOIN FTR ON FTR.N_FACTURA=FNOT.N_fACTURA
                     INNER JOIN FNOTD ON FNOT.CNSFNOT=FNOTD.CNSFNOT
                     INNER JOIN CPNT  ON FNOTD.IDSERVICIO=CPNT.CODIGO
	      WHERE  FNOT.VR_TOTAL <> 0 
                  AND    FNOT.CNSFNOT   = @CNSFNOT
                  AND    FNOT.CLASE     = @CLASE
				AND    FNOTD.VR_TOTAL <> 0
	      PRINT 'Debitos... '+@PROCEDENCIA
                         
         INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,REFERENCIA2, ITEMREF, 
				            USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, 
						PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)

		   SELECT X.NROCOMPROBANTE,X.COMPANIA,'DB',X.CUENTA,X.IDTERCERO,X.CCOSTO,X.DETALLE,SUM(X.VR_TOTAL),NULL,NULL,NULL,
				X.USUARIO,X.FECHA,X.IDAREA,X.PREFIJO,1,'NOTAS_DBCR','Movimiento','S',X.N_FACTURA,X.F_FACTURA,X.F_VENCE,
				'NOTDBCR',X.NOTA,X.CODUNG,X.CODPRG
		  FROM (
			SELECT @NROCOMPROBANTE AS NROCOMPROBANTE, @COMPANIA AS COMPANIA,D.CUENTARAD AS CUENTA,
				A.IDTERCERO,'' AS CCOSTO,'NOTA DEBITO POR '+@PROCEDENCIA+' DE FA: '+A.N_FACTURA AS DETALLE, B.VR_TOTAL,
				@USUARIO AS USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()) AS FECHA, '' AS IDAREA, '' AS PREFIJO, 
				A.N_FACTURA, C.F_FACTURA, C.F_VENCE, @CNSFNOT AS NOTA, A.CODUNG, A.CODPRG
			FROM    FNOT A INNER JOIN FNOTD   B ON A.CNSFNOT=B.CNSFNOT
							INNER JOIN FTR     C ON A.N_FACTURA=C.N_FACTURA
							INNER JOIN TTEC    D ON C.TIPOTTEC=D.TIPO
			WHERE  A.CNSFNOT = @CNSFNOT
			AND    A.CLASE   = @CLASE
			AND    B.VR_TOTAL>0 ) X
			GROUP BY X.NROCOMPROBANTE,X.COMPANIA,X.CUENTA,X.IDTERCERO,X.CCOSTO,X.DETALLE,X.USUARIO,X.FECHA,X.IDAREA,X.PREFIJO,
				   X.N_FACTURA,X.F_FACTURA,X.F_VENCE,X.NOTA,X.CODUNG,X.CODPRG
							  
	      PRINT 'Creditos... '+@PROCEDENCIA
	      PRINT 'GENERO REGISTRO EN CONTABILIDAD'
      END
   END  
   DECLARE @PROCEDECNIAFTR VARCHAR(20)
   DECLARE @NOREFENCIAFTR VARCHAR(20)
   SELECT @PROCEDECNIAFTR=FTR.PROCEDENCIA,@NOREFENCIAFTR=FTR.NOREFERENCIA FROM FNOT INNER JOIN  FTR ON FTR.N_FACTURA=FNOT.N_FACTURA
   WHERE FNOT.N_FACTURA=@N_FACTURA
   AND FNOT.CNSFNOT=@CNSFNOT
   AND FNOT.CLASE=@CLASE
   IF DBO.FNK_VALORVARIABLE('CONTAB_GASTOVEN_UNI')='SI' AND @PROCEDECNIAFTR='INVENTARIO'
   BEGIN
      PRINT 'Voy a reintegra el inventario...'
      SELECT @IDTIPOMOV=DBO.FNK_VALORVARIABLE('IDTIPOMOVDEV_CLIENTE')
      SELECT @NOREFENCIAFTR=CNSMOV FROM IMOV WHERE NODOCUMENTO=@CNSFNOT AND IDTIPOMOV=@IDTIPOMOV AND ESTADO=1
      PRINT '@NOREFENCIAFTR ='+@NOREFENCIAFTR
      EXEC SPK_NC_CONTAB_INV @NOREFENCIAFTR,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
     
   END

   IF EXISTS(SELECT * FROM MCHE INNER JOIN CUE ON MCHE.CUENTA=CUE.CUENTA  
            WHERE MCHE.NROCOMPROBANTE=@NROCOMPROBANTE
            AND MCHE.REFERENCIA3='IVA'
            AND COALESCE(CUE.MCUEGRAV,0)=1
            AND MCHE.PROCEDENCIA='NOTDBCR')
   BEGIN
      UPDATE MCHE SET CUENTA=CUENTAGRAV
      FROM MCHE INNER JOIN CUE ON MCHE.CUENTA=CUE.CUENTA  
      WHERE MCHE.NROCOMPROBANTE=@NROCOMPROBANTE
      AND MCHE.REFERENCIA3='IVA'
      AND COALESCE(CUE.MCUEGRAV,0)=1
      AND MCHE.PROCEDENCIA='NOTDBCR'
   END

   IF EXISTS(SELECT * FROM MCHE INNER JOIN CUE ON MCHE.CUENTA=CUE.CUENTA  
            WHERE MCHE.NROCOMPROBANTE=@NROCOMPROBANTE
            AND COALESCE(CUE.MCUEREV,0)=1
            AND MCHE.PROCEDENCIA='NOTDBCR'
            )
   BEGIN
      PRINT 'INGRESO A REVERSAR LAS CUENTAS' 

      UPDATE MCHE SET CUENTA=CUENTAREV
      FROM MCHE INNER JOIN CUE ON MCHE.CUENTA=CUE.CUENTA  
            WHERE MCHE.NROCOMPROBANTE=@NROCOMPROBANTE
            AND COALESCE(CUE.MCUEREV,0)=1
            AND MCHE.PROCEDENCIA='NOTDBCR'
   END
   EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME     
   EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''
   IF DBO.FNK_VALORVARIABLE('CONTAB_GASTOVEN_UNI')='SI' AND @PROCEDECNIAFTR='INVENTARIO'
   BEGIN
      IF EXISTS(SELECT * FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)
      BEGIN
         SELECT @IDTIPOMOV=DBO.FNK_VALORVARIABLE('IDTIPOMOVDEV_CLIENTE')
         SELECT @NOREFENCIAFTR=CNSMOV FROM IMOV WHERE NODOCUMENTO=@CNSFNOT AND IDTIPOMOV=@IDTIPOMOV AND ESTADO=1
         UPDATE IMOV SET SECONTABILIZA=1,CONTABILIZADA=1,NROCOMPROBANTE=@NROCOMPROBANTE WHERE NODOCUMENTO=@CNSFNOT AND IDTIPOMOV=@IDTIPOMOV AND ESTADO=1         
      END
   END 
END

