CREATE OR ALTER PROCEDURE DBO.SPK_APERTURA_DE_CAJA 
@CODCAJA   VARCHAR(4),
@CODCAJERO VARCHAR(20),
@CODTURNO  VARCHAR(4),
@SYS_COMPUTERNAME VARCHAR(254), 
@IDSEDE    VARCHAR(5),
@COMPANIA  VARCHAR(2),
@USUARIOLOG VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @NVOCONSEC  VARCHAR(20)
DECLARE @NVOCONSEC1 VARCHAR(20)
DECLARE @NVOCONSEC2 VARCHAR(20)
DECLARE @NOMCAJERO  VARCHAR(40)
DECLARE @DATO       VARCHAR(20)
DECLARE @FORMAPAGO  VARCHAR(3)
DECLARE @VALOR      DECIMAL(14,2)
DECLARE @FOFI       INT
DECLARE @CLASE      VARCHAR(9)
DECLARE @CNSCMREE   VARCHAR(20)
DECLARE @REEMBOLSO  DECIMAL(14,2)
BEGIN

   SELECT @FOFI = FOFI , @CLASE = CLASE
   FROM   CAJ
   WHERE  CODCAJA = @CODCAJA
   IF @CLASE = 'Menor'
   BEGIN
      SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJAPERTURACJMENOR'
   END   
   ELSE
   BEGIN
      SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJAPERTURACAJA'
   END   
   
   IF @DATO IS NULL
      RETURN
   
   IF @DATO = ''
      RETURN

   IF (SELECT COUNT(1) FROM ACJ WHERE CODCAJA = @CODCAJA AND ABIERTA = 1) > 0
   BEGIN
      RAISERROR(N'Existen sesiones de caja abiertas sin cerrar (ACJ). Debe regularizarlas antes de abrir nuevamente.', 16, 1)
      RETURN
   END
   
   EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@ACJ',  @NVOCONSEC OUTPUT  
   SELECT @NVOCONSEC = @IDSEDE + 'A' + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
   
   INSERT INTO ACJ(CNSACJ, CODCAJA, CODTURNO, ITEM, CODCAJERO, FECHAAPERTURA, FECHACIERRE,
                   ABIERTA, SALDOINICIAL, SALDOFINAL ) 
   SELECT @NVOCONSEC, @CODCAJA, @CODTURNO, 0, @CODCAJERO, GETDATE(), NULL, 1, 0, 0
   
   INSERT INTO ACJD( CNSACJ, FORMAPAGO, TIPO, SALDO, CODCAJERO  )
   SELECT @NVOCONSEC, CAJR.FORMAPAGO, 'Saldo Inicial', VALOR , @CODCAJERO
   FROM   CAJR, FPA
   WHERE  CAJR.CODCAJA = @CODCAJA
   AND    CAJR.VALOR > 0 
   AND    FPA.FORMAPAGO = CAJR.FORMAPAGO
   AND    FPA.CEROENAPERTURA = 0
      
   --EXEC SPK_GENCONSECUTIVO @COMPANIA, @CODCAJA, '@FCJ',  @NVOCONSEC1 OUTPUT  
   --SELECT @NVOCONSEC1 = REPLACE(SPACE(8 - LEN(@NVOCONSEC1))+LTRIM(RTRIM(@NVOCONSEC1)),SPACE(1),0)
     
   SELECT @NOMCAJERO = DESCRIPCION FROM CJR WHERE CODCAJERO = @CODCAJERO
   
   IF @CLASE = 'Menor'
   BEGIN
      INSERT INTO FCJ(CNSFACJ, CODCAJA, CLASE_FAC, NOADMISION, NOPRESTACION, IDPLAN, VALORTOTAL,
                      COMPANIA, IDAFILIADO, CERRADA, FECHA, TIPO, PROCEDENCIA, N_FACTURA,
                      IDTERCERO, NOMBRECLIENTE, CNSACJ, N_RECIBO, ESTADO, IMPRESO, MARCACONT,
                      CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO, SUBCCOSTO,
                      CLASER, IDCAUSALANUL, USUARIOANUL, SYS_COMPUTERNAMEANUL, FECHAANU,
                      TCNSFACJ, IDENTIFICADOR, SYS_COMPUTERNAME, OBSERVACION, RECAUDO, ENPAGOS,
                      TIPOEGRESO, IMPRESOTRAS, BANCO, SUCURSAL, CTA_BCO, USUARIO, DEAPERTURA, 
                      ARCHIVADO, DEVUELTO,USUARIOLOG)
      SELECT @NVOCONSEC, @CODCAJA, 'COBRO', @NVOCONSEC, NULL, NULL, 0, @COMPANIA, @CODCAJERO,
             1, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 'EXTERNO', 'CAJA', NULL, NULL, @NOMCAJERO, @NVOCONSEC, NULL, 'P',
             0, 0, 0, NULL, NULL, NULL, NULL, 'C', NULL, NULL, NULL, NULL, NULL, NULL, 
             @SYS_COMPUTERNAME, 'SALDOS INICIAL REEMBOLSO APERTURA DE CAJA MENOR', 0, 0, NULL, 0, NULL,
             NULL, NULL, @CODCAJERO, 0, 0, 0,@USUARIOLOG
      
      INSERT INTO FCJD(CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD,
                       VALORTOTAL, IDSERVICIO, CODCAJA, N_RECIBO, TDESCUENTO, TIPODCTO,
                       VLRDESCUENTO, DCTO)
      SELECT @NVOCONSEC, 1, @DATO, NULL, 0, 1, 0, NULL, @CODCAJA, NULL, 0, NULL, 0, 0
      
      EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@PCJ',  @NVOCONSEC2 OUTPUT  
      SELECT @NVOCONSEC2 = @IDSEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC2))+LTRIM(RTRIM(@NVOCONSEC2)),SPACE(1),0)
      
      SELECT @CNSCMREE = MAX(CNSCMREE) FROM CMREE WHERE CODCAJA = @CODCAJA
      
      SELECT @REEMBOLSO  = SUM(COALESCE(FCJD.VALORTOTAL,0))
      FROM   FCJD INNER JOIN FCJ ON FCJD.CNSFACJ = FCJ.CNSFACJ
                                AND FCJD.CODCAJA = FCJ.CODCAJA 
      WHERE  FCJ.CNSCMREE  =  @CNSCMREE
      AND    FCJ.CLASE_FAC =  'PAGO'
      AND    FCJ.ESTADO    <> 'A'   
      
      INSERT INTO PCJ(CNSPCJ, CNSFACJ, TIPOPAGO, VALOR, BANCO, NUMERODOCUMENTO, NUMEROAUTORIZA,
                      FECHA, CNSACJ, IDTERCERO, CODCAJA, IMPRESO, CODCAJADEP, CNSFACJDEP,
                      SUCURSAL, CTA_BCO, CNSDOC)  
      SELECT @NVOCONSEC2, @NVOCONSEC, DBO.FNK_VALORVARIABLE('IDCJFPAEFECTIVO'), @FOFI - @REEMBOLSO, NULL, NULL, NULL, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
             @NVOCONSEC, NULL, @CODCAJA, 0, NULL, NULL, NULL, NULL, NULL
      
   END
   ELSE
   BEGIN
      INSERT INTO FCJ(CNSFACJ, CODCAJA, CLASE_FAC, NOADMISION, NOPRESTACION, IDPLAN, VALORTOTAL,
                      COMPANIA, IDAFILIADO, CERRADA, FECHA, TIPO, PROCEDENCIA, N_FACTURA,
                      IDTERCERO, NOMBRECLIENTE, CNSACJ, N_RECIBO, ESTADO, IMPRESO, MARCACONT,
                      CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO, SUBCCOSTO,
                      CLASER, IDCAUSALANUL, USUARIOANUL, SYS_COMPUTERNAMEANUL, FECHAANU,
                      TCNSFACJ, IDENTIFICADOR, SYS_COMPUTERNAME, OBSERVACION, RECAUDO, ENPAGOS,
                      TIPOEGRESO, IMPRESOTRAS, BANCO, SUCURSAL, CTA_BCO, USUARIO, DEAPERTURA, ARCHIVADO, DEVUELTO,USUARIOLOG)
      SELECT @NVOCONSEC, @CODCAJA, 'COBRO', @NVOCONSEC, NULL, NULL, 0, @COMPANIA, @CODCAJERO,
             1, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 'EXTERNO', 'CAJA', NULL, NULL, @NOMCAJERO, @NVOCONSEC, NULL, 'P',
             0, 0, 0, NULL, NULL, NULL, NULL, 'C', NULL, NULL, NULL, NULL, NULL, NULL, 
             @SYS_COMPUTERNAME, 'SALDOS INICIALES APERTURA DE CAJA', 0, 0, NULL, 0, NULL,
             NULL, NULL, @CODCAJERO, 1, 0, 0,@USUARIOLOG
      
      INSERT INTO FCJD(CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD,
                       VALORTOTAL, IDSERVICIO, CODCAJA, N_RECIBO, TDESCUENTO, TIPODCTO,
                       VLRDESCUENTO, DCTO)
      SELECT @NVOCONSEC, 1, @DATO, NULL, 0, 1, 0, NULL, @CODCAJA, NULL, 0, NULL, 0, 0
      
      DECLARE CAJ_CURSOR CURSOR FOR
      SELECT  CAJR.FORMAPAGO, CAJR.VALOR
      FROM    CAJR, FPA  
      WHERE   CAJR.CODCAJA = @CODCAJA
      AND     CAJR.VALOR   > 0
      AND     FPA.FORMAPAGO = CAJR.FORMAPAGO
      AND     FPA.CEROENAPERTURA = 0
      OPEN CAJ_CURSOR  
      FETCH NEXT FROM CAJ_CURSOR  
      INTO @FORMAPAGO, @VALOR
      WHILE @@FETCH_STATUS = 0  
      BEGIN     
         PRINT 'FORMAPAGO='+@FORMAPAGO
         EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@PCJ',  @NVOCONSEC2 OUTPUT  
         SELECT @NVOCONSEC2 = @IDSEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC2))+LTRIM(RTRIM(@NVOCONSEC2)),SPACE(1),0)
      
         INSERT INTO PCJ(CNSPCJ, CNSFACJ, TIPOPAGO, VALOR, BANCO, NUMERODOCUMENTO, NUMEROAUTORIZA,
                         FECHA, CNSACJ, IDTERCERO, CODCAJA, IMPRESO, CODCAJADEP, CNSFACJDEP,
                         SUCURSAL, CTA_BCO, CNSDOC)  
         SELECT @NVOCONSEC2, @NVOCONSEC, @FORMAPAGO, @VALOR, NULL, NULL, NULL, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                @NVOCONSEC, NULL, @CODCAJA, 0, NULL, NULL, NULL, NULL, NULL
         
         FETCH NEXT FROM CAJ_CURSOR  
         INTO @FORMAPAGO, @VALOR
      END
      CLOSE CAJ_CURSOR
      DEALLOCATE CAJ_CURSOR
        
      DELETE FCJTD FROM FPA
      WHERE  FCJTD.CODCAJA = @CODCAJA
      AND    FPA.FORMAPAGO = FCJTD.FORMAPAGO
      AND    FPA.CEROENAPERTURA = 1
    
      DELETE CAJR FROM FPA
      WHERE  CAJR.CODCAJA  = @CODCAJA 
      AND    FPA.FORMAPAGO = CAJR.FORMAPAGO
      AND    FPA.CEROENAPERTURA = 1
   END
       
   EXEC SPK_TOTPCJ_EG @CODCAJA , @NVOCONSEC
   
   UPDATE CAJ SET ABIERTA = 1, CNSACJ  = @NVOCONSEC WHERE CODCAJA = @CODCAJA
END

