CREATE  OR ALTER PROCEDURE DBO.SPK_RETIRAFTR_DE_CXC 
@CNSCXC    VARCHAR(20), 
@N_FACTURA VARCHAR(16),
@USUARIO   VARCHAR(12),
@PROC      VARCHAR(1)='',
@CNSFPAG   VARCHAR(20)=NULL
WITH ENCRYPTION
AS
DECLARE 
 @OK0 INT
,@OK1 INT
,@OK2 INT
,@OK3 INT
,@ENVIO VARCHAR(6)
,@IDTERCERO VARCHAR(20)
,@IDSGSSS   VARCHAR(20)
,@RIPS_COPAGOS VARCHAR(10)
,@OBS VARCHAR(512)
,@MOTIVO1 VARCHAR(20)
,@MOTIVO2 VARCHAR(20)
,@FTR VARCHAR(20)
BEGIN
    SELECT @OK0 = SUM(VLRGLOSAS), @OK1 = SUM(VLRPAGOS), 
           @OK2 = SUM(VLRNOTADB), @OK3 = SUM(VLRNOTACR) 
    FROM   FCXCD 
    WHERE  CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA
    IF dbo.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
    BEGIN
		SELECT @FTR=SUBSTRING(@N_FACTURA,0,5)+REPLACE(SPACE(8-LEN(RIGHT(@N_FACTURA,LEN(@N_FACTURA)-5))),SPACE(1),0)+RIGHT(@N_FACTURA,LEN(@N_FACTURA)-5)
	END
    SELECT @IDTERCERO=IDTERCERO FROM FCXC WHERE CNSCXC=@CNSCXC
    
    IF @PROC = ''
    BEGIN
       IF @OK0 >0 OR @OK1 > 0 OR @OK2 > 0 OR @OK3 > 0
       BEGIN
          RETURN
       END   
    END
    ELSE
    BEGIN
       IF @PROC = 'R'
       BEGIN
          IF @OK0 >0 OR @OK1 > 0 
          BEGIN
             RETURN
          END   
       END
    END   

    IF @PROC='R'
    BEGIN
        SELECT @MOTIVO1=MOTIVO1, @MOTIVO2=MOTIVO2,
            @OBS='FACTURA DEVUELTA EN CONSECUTIVO = '+@CNSFPAG+CASE WHEN LEN(LTRIM(RTRIM(OBSERVACION)))>0 THEN ' Observación: '+LTRIM(RTRIM(OBSERVACION)) ELSE '' END
        FROM FPAGD 
        WHERE CNSFPAG=@CNSFPAG 
        AND N_FACTURA=@N_FACTURA
    END


    INSERT INTO FCXCR(CNSCXC, N_FACTURA, COMPANIA, VALORFACTURA, OBSERVACION, USUARIO, FECHA, PROCESO, MOTIVO1, MOTIVO2)
    SELECT @CNSCXC, @N_FACTURA, COMPANIA, VALORFACTURA, @OBS, @USUARIO, CONVERT(SMALLDATETIME,GETDATE()), IIF(@PROC='R','Devuelta','Retirada'), @MOTIVO1, @MOTIVO2
    FROM   FCXCD
    WHERE  CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA
       
    UPDATE FTR SET  INDCXC = 0, INDASIGCXC = 0 WHERE N_FACTURA = @N_FACTURA
      
    DELETE FROM FCXCDV WHERE  CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA
    DELETE FROM FCXCD WHERE  CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA
    
    
    --RECONTRUCCION DE RIRPS --
    
    --Limpio de RIPS
    SELECT @ENVIO=ENVIO FROM RIPS WHERE ISNULL(PORCXC,0)=1 AND CNSCXC=@CNSCXC AND IDTERCERO=@IDTERCERO

    IF dbo.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
    BEGIN        
        DELETE TRAMA_DATE WHERE IDTRAMA=@ENVIO AND NUMDOC_PAGO=@FTR
        DELETE TRAMA_DSER WHERE IDTRAMA=@ENVIO AND NUMDOC_PAGO=@FTR
        DELETE TRAMA_DFAC WHERE IDTRAMA=@ENVIO AND NUMDOC_PAGO=@FTR
        DELETE TRAMA_DFAR WHERE IDTRAMA=@ENVIO AND NUMDOC_PAGO=@FTR
        DELETE RIPSD WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND N_FACTURA=@N_FACTURA
    END
    ELSE
    BEGIN
       IF EXISTS(SELECT 1  FROM  RIPSD    WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND N_FACTURA=@N_FACTURA)
       BEGIN
           SELECT @IDSGSSS=IDPRESTADOR FROM RRIPS_AD WHERE ENVIO=@ENVIO
           SELECT @RIPS_COPAGOS = DBO.FNK_VALORVARIABLE('RIPS_COPAGOS')
           DELETE RRIPS_AF WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND NUMFACTURA=@N_FACTURA
           DELETE RRIPS_AD WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND NUMFACTURA=@N_FACTURA
           DELETE RRIPS_AC WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND NUMFACTURA=@N_FACTURA
           DELETE RRIPS_AP WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND NUMFACTURA=@N_FACTURA
           DELETE RRIPS_AH WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND NUMFACTURA=@N_FACTURA
           DELETE RRIPS_AU WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND NUMFACTURA=@N_FACTURA
           DELETE RRIPS_AM WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND NUMFACTURA=@N_FACTURA
           DELETE RRIPS_AN WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND NUMFACTURA=@N_FACTURA
           DELETE RRIPS_AT WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND NUMFACTURA=@N_FACTURA

           DELETE RIPSD    WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND N_FACTURA=@N_FACTURA
        
           INSERT INTO RRIPS_AD ( ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, CODCONCEPTO, CANTIDAD, VALORUNITARIO, TOTALCONCEPTO )
           SELECT @ENVIO, @IDTERCERO, RIPSD.N_FACTURA, @IDSGSSS, SER.CODIGORIPS, SUM(FTRD.CANTIDAD), 
                   CASE @RIPS_COPAGOS WHEN 'NO' THEN SUM(FTRD.VALOR)
                       ELSE SUM((FTRD.VALOR * FTRD.CANTIDAD)/(CASE FTRD.CANTIDAD WHEN 0 THEN 1 ELSE FTRD.CANTIDAD END))
                   END,              
                   SUM(FTRD.VALOR * FTRD.CANTIDAD)
           FROM   RIPSD INNER JOIN FTRD  ON RIPSD.N_FACTURA    = FTRD.N_FACTURA
                       INNER JOIN HPRED ON FTRD.NOPRESTACION  = HPRED.NOPRESTACION AND FTRD.NOITEM = HPRED.NOITEM
                       INNER JOIN HPRE  ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
                       INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
                           LEFT JOIN SER   ON HPRED.IDSERVICIO   = SER.IDSERVICIO
                           LEFT JOIN AFI   ON HADM.IDAFILIADO    = AFI.IDAFILIADO
                           LEFT JOIN PRE   ON SER.PREFIJO        = PRE.PREFIJO
           WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
           AND    RIPSD.PROCEDENCIA = 'SALUD' 
           AND    COALESCE(COALESCE(FTRD.ITFC,0),0)         <> 2   
		   AND NOT EXISTS(SELECT * FROM RIPSD X WHERE X.ENVIO= @ENVIO AND X.N_FACTURA=RIPSD.N_FACTURA)
           GROUP BY RIPSD.N_FACTURA, SER.CODIGORIPS

       END
    END
   
   -- EXEC SPK_RELIQUIDA_FTR @CNSCXC, @N_FACTURA 
END

