IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SPK_FAC_IMPDEDUC' AND type = 'P')
   DROP PROCEDURE SPK_FAC_IMPDEDUC

GO
CREATE PROCEDURE DBO.SPK_FAC_IMPDEDUC    
@IDTERCERO  VARCHAR(20),  
@CNSFTR     VARCHAR(40),   
@FACT       VARCHAR(16),   
@VLRANTEIVA DECIMAL(14,2)  
WITH ENCRYPTION
AS         
DECLARE @PROPIETARIO VARCHAR(20)  
DECLARE @HOY DATETIME  
DECLARE @TERCERO VARCHAR(20)
DECLARE @MAXITEM  INT
BEGIN  
   DELETE FROM FTRI WHERE N_FACTURA = @FACT  
   
   IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCERO)
   BEGIN
      SELECT @IDTERCERO= IDTERCERO FROM FTR WHERE N_FACTURA=@FACT
   END

   PRINT 'INGRESO A IMPUESTOS'
   PRINT '@IDTERCERO='+@IDTERCERO 
   PRINT '@VLRANTEIVA='+LTRIM(RTRIM(STR(@VLRANTEIVA))) 
   --SELECT TOP 1 @PROPIETARIO = IDTERCERO FROM TER WHERE NIT = @NIT  
   SELECT @HOY = GETDATE() 
                
   INSERT INTO FTRI(CNSFTR, TIPO, CLASEFTRI, IDIMPUESTO, IDCLASE, CODIGO,  
                    VALORFTRI, VALOR, N_FACTURA,ITEM)  
   SELECT @CNSFTR, 'R', 'IM', FIMXT.IDIMPUESTO, FIMXT.IDCLASE, NULL,   
          FIMPDV.VALOR, ROUND(@VLRANTEIVA * (FIMPDV.VALOR/100),0) , @FACT,ROW_NUMBER() OVER(ORDER  BY @CNSFTR  DESC)
   FROM  FIMXT, FIMPDV   
   WHERE FIMXT.IDIMPUESTO = FIMPDV.IDIMPUESTO   
   AND   FIMXT.IDCLASE    = FIMPDV.IDCLASE   
   AND   FIMXT.IDTERCERO  = @IDTERCERO  
   AND   FIMXT.TIPO       = 'D'
   AND   @HOY >= FIMPDV.FECHAINI   
   AND   @HOY <= FIMPDV.FECHAFIN  
   AND   @VLRANTEIVA >= COALESCE(FIMPDV.VALOR_INICIAL,0)
   AND   @VLRANTEIVA <= CASE COALESCE(FIMPDV.VALOR_FINAL,0) WHEN 0 THEN @VLRANTEIVA ELSE FIMPDV.VALOR_FINAL END

   /*COMENTARIZADO POR JJIMENEZ 26-02-2017  QUEDABA DOS VECES */   
   --SELECT @TERCERO = IDTERCERO FROM FTR WHERE N_FACTURA = @FACT     
   --SELECT @MAXITEM=MAX(ITEM) FROM FTRI WHERE  N_FACTURA = @FACT AND CNSFTR=@CNSFTR
   
   --INSERT INTO FTRI(CNSFTR, TIPO, CLASEFTRI, IDIMPUESTO, IDCLASE, CODIGO,  
   --                 VALORFTRI, VALOR, N_FACTURA,ITEM)  
   --SELECT @CNSFTR, 'R', 'IM', FIMXT.IDIMPUESTO, FIMXT.IDCLASE, NULL,   
   --       FIMPDV.VALOR, @VALORTOTAL * (FIMPDV.VALOR/100) , @FACT,
   --       COALESCE(@MAXITEM,0)+ROW_NUMBER() OVER(ORDER  BY @CNSFTR  DESC)
   --FROM  FIMXT, FIMPDV   
   --WHERE FIMXT.IDIMPUESTO = FIMPDV.IDIMPUESTO   
   --AND   FIMXT.IDCLASE    = FIMPDV.IDCLASE   
   --AND   FIMXT.IDTERCERO  = @TERCERO  
   --AND   FIMXT.TIPO       = 'D'
   --AND   @HOY >= FIMPDV.FECHAINI   
   --AND   @HOY <= FIMPDV.FECHAFIN  
     
END

