IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_CONTAB_RADICACXC' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_CONTAB_RADICACXC
END

GO
CREATE PROCEDURE DBO.SPK_CONTAB_RADICACXC 
@CNSCXC            VARCHAR(20),
@COMPANIA          VARCHAR(2),
@SEDE              VARCHAR(5),
@USUARIO           VARCHAR(12),
@SYS_COMPUTERNAME  VARCHAR(512),
@NROCOMPROBANTE    VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @ANO    VARCHAR(5)
DECLARE @MES    INT
DECLARE @COM     VARCHAR(5)
DECLARE @IDMODELOCONT    VARCHAR(2)
DECLARE @PREFIJO_USCXS   VARCHAR(10)
DECLARE @NOREFERENCIA    VARCHAR(20)
DECLARE @PROCEDENCIA     VARCHAR(20), @TIPOFAC   VARCHAR(1)
DECLARE @OBSERVACION     VARCHAR(255)
DECLARE @IDTERCERO       VARCHAR(50)
DECLARE @N_FACTURA1      VARCHAR(16), @N_FACTURA VARCHAR(16), @NOADMISION VARCHAR(16)
DECLARE @DONDE           INT
DECLARE @IDTERCEROFTR    VARCHAR(20), @IDPLANFTR VARCHAR(6)
DECLARE @TIPOTTEC        VARCHAR(10), @CUENTANO  VARCHAR(16), @CUENTACXC VARCHAR(16),  @CUENTACXCRAD VARCHAR(16)
BEGIN
   --CAPTURO DATOS PARA MCP --SELECT TOP 10 * FROM FCXC WHERE INDRECIBIDO=1
   SELECT @ANO=YEAR(F_RECIBIDO),@MES=MONTH(F_RECIBIDO), @IDTERCERO=IDTERCERO FROM FCXC WHERE CNSCXC=@CNSCXC
   --SE REVISA SI LOS COMPROBANTES SE TOMAN DE ACUERDO A SEDE
   IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
   BEGIN
      SELECT @COM = RTRIM(LTRIM(COMMS.COMPROBANTE)) 
      FROM   COMMS  
      WHERE  COMMS.IDSEDE = @SEDE AND COMMS.CLASE = 'RADICACXC' 
      AND    COMMS.TIPO = 'RADICACXC'
   END
   ELSE
   BEGIN
      SELECT  @COM=DBO.FNK_VALORVARIABLE('IDCON_TCOM_RADICA')
   END
   
   SELECT @OBSERVACION='REGISTRAMOS RADICACION DE FACTURAS A: '+RAZONSOCIAL+' CXC No.: '+@CNSCXC FROM TER WHERE IDTERCERO=@IDTERCERO

   PRINT 'CREANDO NUEVO MCP'            
   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA = @COMPANIA AND ANO=@ANO AND MES=@MES)
   BEGIN
      PRINT CAST(@ANO AS VARCHAR(4))+CAST(@MES AS VARCHAR(3))
      RAISERROR('EL PERIODO CONTABLE NO EXISTEN', 16, 1)
      RETURN
   END
   IF EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA = @COMPANIA AND ANO=@ANO AND MES=@MES AND COALESCE(CERRADO,0)=1)
   BEGIN
      PRINT CAST(@ANO AS VARCHAR(4))+CAST(@MES AS VARCHAR(3))
      RAISERROR('EL PERIODO ACTUAL CERRADO', 16, 1)
      RETURN
   END
   /***************************************************************************************************************/
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
   /***************************************************************************************************************/
   PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   IF ISNULL(@NROCOMPROBANTE,'') = '' -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   BEGIN
   	   
      SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	  PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	  SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	  PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	  --GENERO EL CONSECUTIVO DEL TIPO DE COMPROBANTE
   	  SET @PREFIJO_USCXS='@COM'+@COM
   	  SET @NOREFERENCIA=SPACE(20)
        
   	  EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
   	  SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
   	  PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
   	  PRINT 'Comprobante Contable (MCP)'
   	  
      INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                    TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                    COMPROBANTE, IDTERCERO, ANULADO )
      SELECT @NROCOMPROBANTE, @COMPANIA, 'RAD CXC', @NOREFERENCIA, @ANO, @MES,DBO.FNK_FECHA_SIN_HORA(F_RECIBIDO) ,
             0, 0,@CNSCXC, LEFT(QUIENRECIBIO,19), @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL,@OBSERVACION, 
             @SEDE, 0, @COM, IDTERCERO,0 FROM FCXC WHERE CNSCXC=@CNSCXC
   	  
   END	 
   SELECT @DONDE=COUNT(*) FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   IF @DONDE>0
   BEGIN
      INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
      SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
      FROM   MCP 
      WHERE NROCOMPROBANTE = @NROCOMPROBANTE
      --se borran de mcp, mch
      DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
      DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE   
   END
   DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   PRINT 'INSERTANDO MCHE CR'
   
   IF (SELECT COUNT(*) 
       FROM   FCXCD INNER JOIN FTR  ON FCXCD.N_FACTURA = FTR.N_FACTURA
       WHERE  FCXCD.CNSCXC = @CNSCXC 
       AND (COALESCE(FTR.CUENTACXC,'') = '' OR COALESCE(FTR.CUENTACXC_RAD,'') = '')) > 0
   BEGIN
      DECLARE NOC_C CURSOR FOR
      SELECT FTR.N_FACTURA, FTR.PROCEDENCIA, FTR.TIPOFAC, COALESCE(FTR.CUENTACXC,''), COALESCE(FTR.CUENTACXC_RAD,'') 
      FROM   FCXCD INNER JOIN FTR  ON FCXCD.N_FACTURA = FTR.N_FACTURA
      WHERE FCXCD.CNSCXC = @CNSCXC
      AND   (COALESCE(FTR.CUENTACXC,'') = '' OR COALESCE(FTR.CUENTACXC_RAD,'') = '')
      OPEN NOC_C
      FETCH NEXT FROM NOC_C
      INTO @N_FACTURA, @PROCEDENCIA, @TIPOFAC, @CUENTACXC, @CUENTACXCRAD
      WHILE @@FETCH_STATUS = 0    
      BEGIN         
         IF @PROCEDENCIA = 'CI' AND @TIPOFAC = 'M'
         BEGIN           
            SELECT TOP 1 @NOADMISION = NOADMISION FROM FTRD WHERE N_FACTURA = @N_FACTURA          
            SELECT @IDTERCEROFTR = IDCONTRATANTE, @IDPLANFTR = IDPLAN FROM CIT WHERE CONSECUTIVO = @NOADMISION
         END
         IF @PROCEDENCIA = 'CE' AND @TIPOFAC = 'M'
         BEGIN           
            SELECT TOP 1 @NOADMISION = NOADMISION FROM FTRD WHERE N_FACTURA = @N_FACTURA          
            SELECT @IDTERCEROFTR = AUT.IDCONTRATANTE, @IDPLANFTR = AUT.IDPLAN FROM   AUT WHERE  AUT.NOAUT = @NOADMISION
         END
         IF @PROCEDENCIA = 'CE' AND @TIPOFAC = 'I'
         BEGIN           
            SELECT @NOADMISION = NOREFERENCIA FROM FTR WHERE N_FACTURA = @N_FACTURA
            SELECT @IDTERCEROFTR = AUT.IDCONTRATANTE, @IDPLANFTR = AUT.IDPLAN FROM   AUT WHERE  AUT.NOAUT = @NOADMISION
         END
         IF @PROCEDENCIA = 'FINANCIERO'
         BEGIN
            PRINT 'ES FINANCIERO' 
            SELECT @IDTERCEROFTR = FTR.IDTERCERO, @IDPLANFTR = FTR.IDPLAN FROM FTR WHERE  FTR.N_FACTURA = @N_FACTURA
         END 
         SELECT @TIPOTTEC = TIPOTERCONTABLE FROM PPT WHERE IDTERCERO = @IDTERCEROFTR AND IDPLAN = @IDPLANFTR
         IF @CUENTACXC = ''
         BEGIN
            SELECT @CUENTANO = CUENTA FROM TTEC WHERE TIPO = @TIPOTTEC 
            UPDATE FTR SET CUENTACXC = @CUENTANO
            WHERE  FTR.N_FACTURA = @N_FACTURA
         END
         IF @CUENTACXCRAD = ''
         BEGIN
            PRINT '@TIPOTTEC ='+@TIPOTTEC 
            SELECT @CUENTANO = CUENTARAD FROM TTEC WHERE TIPO = @TIPOTTEC 
            
            UPDATE FTR SET CUENTACXC_RAD = @CUENTANO
            WHERE  FTR.N_FACTURA = @N_FACTURA
         END
         
         FETCH NEXT FROM NOC_C
         INTO @N_FACTURA, @PROCEDENCIA, @TIPOFAC, @CUENTACXC, @CUENTACXCRAD
      END
      CLOSE NOC_C
      DEALLOCATE NOC_C     
   END
      
   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA, TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
   	  				  REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
      				  N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
   SELECT @NROCOMPROBANTE,@COMPANIA,'CR', C.CUENTACXC, C.IDTERCERO, '',@OBSERVACION, A.SALDO,A.CNSCXC,
	       NULL,0,@USUARIO,dbo.FNK_FECHA_SIN_MLS(GETDATE()),NULL,NULL,'P',0,'RADCXC_CR','Movimiento',A.N_FACTURA,
	       C.F_FACTURA,C.F_VENCE,'RADCXC_CR','RADCXC_CR',NULL,C.CODUNG,C.CODPRG
	FROM   FCXCD A INNER JOIN FTR    C ON A.N_FACTURA=C.N_FACTURA
	WHERE  A.CNSCXC = @CNSCXC AND A.SALDO>0
      
   PRINT 'INSERTANDO MCHE DB'
	  	
   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
	                 REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
	  					  N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
	SELECT @NROCOMPROBANTE,@COMPANIA,'DB',CASE WHEN COALESCE(C.CUENTACXC_RAD,'')='' THEN  CASE WHEN COALESCE(TTEC.CUENTARAD,'')='' THEN TTEC2.CUENTARAD  ELSE TTEC.CUENTARAD END ELSE COALESCE(C.CUENTACXC_RAD,'') END, C.IDTERCERO, '', @OBSERVACION, A.SALDO, A.CNSCXC,
	  	   NULL,0,@USUARIO,dbo.FNK_FECHA_SIN_MLS(GETDATE()),NULL,NULL,'P',0,'RADCXC_CR','Movimiento',A.N_FACTURA,
	  	   C.F_FACTURA,C.F_VENCE,'RADCXC_DB','RADCXC_DB',NULL,C.CODUNG,C.CODPRG
	FROM   FCXCD A INNER JOIN FTR C ON A.N_FACTURA=C.N_FACTURA
				   LEFT JOIN TTEC   ON TTEC.TIPO  = C.TIPOTTEC 
													 AND TTEC.TIPOMOV  = 'DB'			
				   LEFT JOIN PPT    ON C.IDTERCERO= PPT.IDTERCERO 
                                     AND C.IDPLAN = PPT.IDPLAN 
                   LEFT JOIN TTEC TTEC2 ON TTEC2.TIPO = PPT.TIPOTERCONTABLE 
	WHERE  A.CNSCXC = @CNSCXC 
   AND    A.SALDO>0
	--BORRAMOS LA TEMPORAL	
   
   EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME 
   
   EXEC SPK_PASA_MCP_MCPNIIF 	 @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''        
END

