IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_CONTAB_CAJA_EGR' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_CONTAB_CAJA_EGR
END
GO
CREATE PROCEDURE DBO.SPK_CONTAB_CAJA_EGR
@CNSFACJ           VARCHAR(20),   
@CODCAJA           VARCHAR(4),   
@USUARIO           VARCHAR(12),  
@SYS_COMPUTERNAME  VARCHAR(254),  
@COMPANIA          VARCHAR(2),   
@SEDE              VARCHAR(5),  
@NROCOMPROBANTE    VARCHAR(20)  
WITH ENCRYPTION
AS  
DECLARE @COM             VARCHAR(6)  
DECLARE @NOREFERENCIA    VARCHAR(20)  
DECLARE @ANO             VARCHAR(4)  
DECLARE @MES             INT  
DECLARE @IDMODELOCONT    VARCHAR(2)  
DECLARE @IDPLAN          VARCHAR(6)   
DECLARE @TIPOTERCONTABLE VARCHAR(10)   
DECLARE @PROCEDENCIA     VARCHAR(10)  
DECLARE @CNSFCXP         VARCHAR(20)  
DECLARE @CNSFACJ_CUR     VARCHAR(20)  
DECLARE @CODCAJA_CUR     VARCHAR(4)    
DECLARE @CNSFCXPP_CUR    VARCHAR(20)  
DECLARE @VALORTOTAL_CUR  DECIMAL(14,2)  
DECLARE @OBSERVACION_CUR VARCHAR(255)  
DECLARE @TOTAL_COMPRA    DECIMAL(14,2)  
DECLARE @SW              INT  
DECLARE @ESTADO          VARCHAR(1)  
DECLARE @NOCHEQUE        VARCHAR(20)  
DECLARE @BANCO           VARCHAR(20)  
DECLARE @VALOR_CHEQUE    DECIMAL(14,2)  
DECLARE @PREFIJO_USCXS   VARCHAR(10)  
DECLARE @PROCESO         VARCHAR(12)  
DECLARE @FECHATRA        DATETIME  
DECLARE @CNSFCXPPM       VARCHAR(20)  
DECLARE @TIPOEGRESO      VARCHAR(8)
DECLARE @CLASECAJA       VARCHAR(8)
DECLARE @Q_FPAG          INT
DECLARE @IDCATEGORIA     VARCHAR(10)
BEGIN  
   PRINT ''
   PRINT '     **************************************'
   PRINT '     ** ENVIO DE CAJA.EGR A CONTABILIDAD **'
   PRINT '     **************************************'
   PRINT 'Llenando Tabla Temporal de FCJ'  
   SELECT * INTO #T FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA=@CODCAJA  
   SELECT * INTO #TH FROM FCJD WHERE CNSFACJ = @CNSFACJ AND CODCAJA=@CODCAJA  
   SELECT * INTO #THD FROM PCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA=@CODCAJA  
   
   UPDATE #T SET CCOSTO='' WHERE NOT CCOSTO IN (SELECT CCOSTO FROM CEN WHERE COMPANIA=@COMPANIA)  
   SELECT @ANO        = YEAR(FECHA),  
          @MES        = MONTH(FECHA),  
          @FECHATRA   = FECHA,
          @ESTADO     = ESTADO,
          @TIPOEGRESO = TIPOEGRESO
   FROM   #T  
    
   SELECT @IDCATEGORIA=IDCATEGORIA FROM CJTE WHERE TIPOEGRESO=@TIPOEGRESO

   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)  
   BEGIN
      RAISERROR('Período Contable No Existe', 16, 1)
      RETURN
      --PRINT 'Insertando Periodo Contable...'  
      --INSERT INTO PRI (COMPANIA,ANO,MES,NOMPERIODO,FECHA_INI,CERRADO,FECHA_FIN,AJUSTADO,PAAG,COMPROBANTE,  
      --       DOCUMENTO,NROCOMPROBANTE,TIPO_AJ,CERRADO_INV)  
      --SELECT @COMPANIA,@ANO,@MES,LEFT(DATENAME(MONTH,@FECHATRA),3)+' de '+@ANO,CAST('01/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME),  
      --       1,DBO.FNK_DIA_DEL_MES(@ANO,@MES,'ULTIMO'),1,0,'','','','Mensual',1  
       
      --PRINT 'Fijando Saldos Inicales...'  
      --EXEC SPK_FIJAR_SALDO_INICIAL @COMPANIA,@ANO,@MES  
   END  
   
   SET @SW=0  
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')  
   
   IF ISNULL(@NROCOMPROBANTE,'') = '' OR LEFT(@NROCOMPROBANTE,2)='IX'
   BEGIN  
      PRINT 'Generando Consecutivo...'  
      SET @PROCESO='Nuevo'  
      IF LEFT(@NROCOMPROBANTE,2)='IX'
      BEGIN
         SET @COM = 'IX'   
         SET @NOREFERENCIA = @NROCOMPROBANTE
      END
      ELSE
      BEGIN
         SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
         PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
         SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
         PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
         SET @COM = ''  
         --SE REVISA SI LOS COMPROBANTES SE TOMAN DE ACUERDO A SEDE
         IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
         BEGIN
            IF DBO.FNK_VALORVARIABLE('COMEGRESO_FPA') = 'SI'
            BEGIN
               SELECT @Q_FPAG = COALESCE(COUNT(*),0) FROM #THD
               IF @Q_FPAG > 1
               BEGIN
                  SELECT @COM = LTRIM(RTRIM(CASE WHEN EXISTS (SELECT TOP 1 COMMS.COMPROBANTE
                                                              FROM   #TH INNER JOIN COMMS ON #TH.CONCEPTO = COMMS.TIPO
                                                              WHERE  COMMS.IDSEDE = @SEDE
                                                              AND    COMMS.CLASE  = 'CAJAEGR')
                                                 THEN (SELECT TOP 1 COMMS.COMPROBANTE
                                                       FROM   #TH INNER JOIN COMMS ON #TH.CONCEPTO = COMMS.TIPO
                                                       WHERE  COMMS.IDSEDE = @SEDE
                                                       AND    COMMS.CLASE  = 'CAJAEGR')
                                                 ELSE DBO.FNK_VALORVARIABLE('IDCON_TCOM_ECAJ')
                                            END))
               END
               ELSE
               BEGIN                  
                  SELECT @COM = LTRIM(RTRIM(CASE WHEN EXISTS (SELECT TOP 1 COMMS.COMPROBANTE
                                                              FROM   #THD INNER JOIN COMMS ON #THD.TIPOPAGO = COMMS.TIPO
                                                              WHERE  COMMS.IDSEDE = @SEDE
                                                              AND    COMMS.CLASE  = 'CAJAEGR_FPA')
                                                 THEN (SELECT TOP 1 COMMS.COMPROBANTE
                                                              FROM   #THD INNER JOIN COMMS ON #THD.TIPOPAGO = COMMS.TIPO
                                                              WHERE  COMMS.IDSEDE = @SEDE
                                                              AND    COMMS.CLASE  = 'CAJAEGR_FPA')
                                                 ELSE (LTRIM(RTRIM(CASE WHEN EXISTS (SELECT TOP 1 COMMS.COMPROBANTE
                                                                                     FROM   #TH INNER JOIN COMMS ON #TH.CONCEPTO = COMMS.TIPO
                                                                                     WHERE  COMMS.IDSEDE = @SEDE
                                                                                     AND    COMMS.CLASE  = 'CAJAEGR')
                                                                        THEN (SELECT TOP 1 COMMS.COMPROBANTE
                                                                              FROM   #TH INNER JOIN COMMS ON #TH.CONCEPTO = COMMS.TIPO
                                                                              WHERE  COMMS.IDSEDE = @SEDE
                                                                              AND    COMMS.CLASE  = 'CAJAEGR')
                                                                        ELSE DBO.FNK_VALORVARIABLE('IDCON_TCOM_ECAJ')
                                                                   END)))
                                                 END))
               END
            END
            ELSE
            BEGIN
               
               SELECT @COM = LTRIM(RTRIM(CASE WHEN EXISTS (SELECT TOP 1 COMMS.COMPROBANTE
                                                              FROM   #TH INNER JOIN COMMS ON #TH.CONCEPTO = COMMS.TIPO
                                                              WHERE  COMMS.IDSEDE = @SEDE
                                                              AND    COMMS.CLASE  = 'CAJAEGR')
                                                 THEN (SELECT TOP 1 COMMS.COMPROBANTE
                                                       FROM   #TH INNER JOIN COMMS ON #TH.CONCEPTO = COMMS.TIPO
                                                       WHERE  COMMS.IDSEDE = @SEDE
                                                       AND    COMMS.CLASE  = 'CAJAEGR')
                                                 ELSE DBO.FNK_VALORVARIABLE('IDCON_TCOM_ECAJ')
                                            END))
            END
         END
         ELSE
         BEGIN
            /*REVISAMOS SI EL COMPROBANTE DE EGRESO DEPENDE DE LA FORMA DE PAGO*/
            IF DBO.FNK_VALORVARIABLE('COMEGRESO_FPA') = 'SI'
            BEGIN
               SELECT @Q_FPAG = COALESCE(COUNT(*),0) FROM #THD
               IF @Q_FPAG > 1
               BEGIN
                  SET @COM = (SELECT TOP 1 CPCJ.COMPROBANTE  
                              FROM   CPCJ INNER JOIN  #TH ON CPCJ.CODIGO = #TH.CONCEPTO  
                              GROUP BY CPCJ.COMPROBANTE )                
               END
               ELSE
               BEGIN
                  SELECT @COM = FPA.COMPROBANTE_EGR FROM #THD INNER JOIN FPA ON #THD.TIPOPAGO = FPA.FORMAPAGO
                  IF NOT EXISTS(SELECT COMPROBANTE FROM COM WHERE COMPROBANTE=@COM AND COMPANIA=@COMPANIA)  
                  BEGIN
                     SET @COM = (SELECT TOP 1 CPCJ.COMPROBANTE  
                                 FROM   CPCJ INNER JOIN  #TH ON CPCJ.CODIGO = #TH.CONCEPTO  
                                 GROUP BY CPCJ.COMPROBANTE )  
                                    
                  END
               END
            END
            ELSE
            BEGIN
               SET @COM = (SELECT TOP 1 CPCJ.COMPROBANTE  
                           FROM   CPCJ INNER JOIN  #TH ON CPCJ.CODIGO = #TH.CONCEPTO  
                           GROUP BY CPCJ.COMPROBANTE )  
            
            END
            IF NOT EXISTS(SELECT COMPROBANTE FROM COM WHERE COMPROBANTE=@COM AND COMPANIA=@COMPANIA)  
               SET @COM = (SELECT (CASE WHEN EXISTS (SELECT TOP 1 COM.COMPROBANTE FROM CJTE,COM,#T   
                                                     WHERE  CJTE.TIPOEGRESO  = #T.TIPOEGRESO 
                                                    AND    CJTE.COMPROBANTE = COM.COMPROBANTE 
                                                     AND    COM.COMPANIA     = @COMPANIA)   
                                        THEN (SELECT TOP 1 COM.COMPROBANTE   
                                              FROM   CJTE, COM, #T 
                                             WHERE  CJTE.TIPOEGRESO  = #T.TIPOEGRESO 
                                              AND    CJTE.COMPROBANTE = COM.COMPROBANTE 
                                              AND    COM.COMPANIA     = @COMPANIA)   
                                       ELSE  DBO.FNK_VALORVARIABLE('IDCON_TCOM_ECAJ') 
                                   END))  

            IF NOT EXISTS(SELECT COMPROBANTE FROM COM WHERE COMPROBANTE=@COM AND COMPANIA=@COMPANIA)  
            BEGIN
               SET @COM = DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT')  
            END
           
            IF NOT EXISTS(SELECT COMPROBANTE FROM COM WHERE COMPROBANTE = @COM AND COMPANIA = @COMPANIA )  
            BEGIN
               SET @COM = 'IX'  
            END
         END     
         SET @PREFIJO_USCXS = '@COM'+@COM  
         SET @NOREFERENCIA  = SPACE(20)  
         
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT     
         SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)  
         PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA  
         
         
         -- INICIO JEDM  
         UPDATE FCJ SET N_RECIBO = @NOREFERENCIA   
         WHERE  CODCAJA = @CODCAJA  
         AND    CNSFACJ = @CNSFACJ  
          -- FIN JEDM   
         
      END  
       
      PRINT 'Comprobante Contable (MCP)'  
      INSERT INTO MCP(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,  
                     TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,  
                      COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, ANULADO, RPT_COMPROBANTE)  
      SELECT @NROCOMPROBANTE, @COMPANIA, 'CAJA', @NOREFERENCIA, @ANO, @MES, CAST(STR(DAY(FECHA))+'/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME),  
             0, 0, @CNSFACJ, CODCAJA, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL,   
             LEFT(#T.OBSERVACION,512), @SEDE, 0, @COM, (CASE WHEN #T.IDTERCERO IS NULL THEN '' ELSE #T.IDTERCERO END),'','',0,'EGRESO'   
      FROM #T  
   END  
   ELSE  
   BEGIN  
      SET @PROCESO='Viejo'  
      IF @ESTADO<>'A'
      BEGIN
         SELECT @COM=COMPROBANTE,@NOREFERENCIA=NOREFERENCIA FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE  
         DELETE MCH 
         WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND PROCEDENCIA='CAJA' AND REFERENCIA_PRO=@CNSFACJ AND REFERENCIA2=@CODCAJA  
         UPDATE MCP SET OBSERVACION=#T.OBSERVACION FROM #T   
         WHERE MCP.NROCOMPROBANTE=@NROCOMPROBANTE AND MCP.PROCEDENCIA='CAJA' AND   
              MCP.REFERENCIA1=@CNSFACJ AND MCP.REFERENCIA2=@CODCAJA  
      END
   END  
      
   IF @ESTADO='A' AND LEFT(@NROCOMPROBANTE,2)<>'IX'  
   BEGIN   
      PRINT 'ANULADA.'
      PRINT 'Borrando Registros de MCH...'
      UPDATE MCP SET ESTADO='2', ANULADO=1, TOTALDEBITO=0, TOTALCREDITO=0 
      WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE  
      PRINT 'Actualizando FCJ...'
      UPDATE FCJ SET CONTABILIZADA=1, MARCACONT = 0, NROCOMPROBANTE = @NROCOMPROBANTE 
      FROM #T WHERE FCJ.CNSFACJ=#T.CNSFACJ AND FCJ.CODCAJA=#T.CODCAJA  
      IF @PROCESO='Viejo'  
      BEGIN
         RETURN  
      END
   END  
   
   IF @@ERROR<>0  
   BEGIN  
      PRINT 'Errores...'  
      RETURN   
   END  
      
   PRINT 'Insertando Asiento del Concepto de Caja. (DB)'   
   IF DBO.FNK_VALORVARIABLE('IDCJTECXP') = @TIPOEGRESO OR DBO.FNK_VALORVARIABLE('IDCJTEARS')=@TIPOEGRESO --EGRESO POR CXP  
   BEGIN  
      PRINT 'El Tipo de Egreso es de CXP'
      SET @SW=1  
      PRINT ' -Insertando Registro MCH. Para EGRESO POR CXP 1.'  
      IF DBO.FNK_VALORVARIABLE('IDCJTENOMINA') = @TIPOEGRESO   
      BEGIN
         INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,    
                         REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,  
                         CNSPAGO,N_FACTURA,F_FACTURAREF,F_VENCE,GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)    
         SELECT @NROCOMPROBANTE,@COMPANIA,'DB',  
                CASE WHEN FCXP.PROCEDENCIA='Nomina' THEN FCXPD.CUENTA_SER ELSE FCXP.CUECREDITO END, 
                FCXP.IDTERCERO, FCXPD.CCOSTO,  
                CASE WHEN FCXP.PROCEDENCIA='Nomina' 
                 THEN (SELECT NCON.DESCRIPCION+',   '+RTRIM(TER.RAZONSOCIAL) 
                            FROM NCON,TER 
                            WHERE NCON.CODCONCEPTO=FCXPD.IDSERVICIO AND TER.IDTERCERO=FCXPD.NOLOTE) 
                 ELSE 
                'PAGO NOMINA No. '+FCXP.NOREFERENCIA 
                 END,  
                SUM((FCXPD.VLR_NETO*#TH.VALORTOTAL)/FCXP.VLR_NETO),   
                #T.CNSFACJ,#T.CODCAJA,'',NULL,@USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
                (SELECT TOP 1 FCXPD.PREFIJO FROM FCXPD WHERE FCXPD.CNSFCXP=FCXPP.CNSFCXP),  
                (SELECT TOP 1 LEFT(FCXPD.IDAREA,10) FROM FCXPD WHERE FCXPD.CNSFCXP=FCXPP.CNSFCXP),'S',1,  
                'EGRESO_CXP_'+UPPER(FCXP.PROCEDENCIA),FCXPP.CNSFCXPP,  
                FCXP.NOREFERENCIA,DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF),  
                DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 'Movimiento','CAJA',@CNSFACJ, 
                CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, 
                CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
         FROM #T, #TH, FCXP, FCXPP, FCXPD  
         WHERE #TH.IDSERVICIO=FCXPP.CNSFCXPP AND FCXPP.CNSFCXP=FCXP.CNSFCXP AND FCXP.CNSFCXP=FCXPD.CNSFCXP
         GROUP BY FCXP.CUECREDITO, FCXP.IDTERCERO, FCXP.NOREFERENCIA, #T.CNSFACJ, FCXPD.NOLOTE, 
                  #T.CODCAJA, FCXPP.CNSFCXPP, DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF), DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE),
                       FCXP.PROCEDENCIA,FCXPP.CNSFCXP, FCXPD.CUENTA_SER, FCXPD.IDSERVICIO, FCXPD.IDAREA, FCXPD.CCOSTO, 
                       #T.CODUNG, #T.CODPRG, FCXP.OBSERVACION  
         HAVING SUM((FCXPD.VLR_NETO*#TH.VALORTOTAL)/FCXP.VLR_NETO)<>0 
      END
      ELSE
      BEGIN
         INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,    
                         REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,  
                         CNSPAGO,N_FACTURA,F_FACTURAREF,F_VENCE,GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)    
         SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',  
                CASE WHEN FCXP.PROCEDENCIA='Nomina' 
                     THEN DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', 'CR', FCXPD.PREFIJO, FCXPD.IDAREA, FCXPD.CCOSTO,'S',FCXP.CNSFCOM)
                     ELSE FCXP.CUECREDITO 
                END, 
                FCXP.IDTERCERO, FCXPD.CCOSTO,  
                CASE WHEN FCXP.PROCEDENCIA='Nomina' 
                     THEN 'PAGO NOMINA No. ' + FCXP.NOREFERENCIA 
                     ELSE CASE WHEN FCXP.OBSERVACION LIKE '%ANTICIPO%' 
                               THEN FCXP.OBSERVACION + '. DOCUMENTO No.' + FCXP.NOREFERENCIA  
                               ELSE 'PAGO FACTURA No. ' + FCXP.NOREFERENCIA 
                          END
                END,  
                SUM((FCXPD.VLR_NETO*#TH.VALORTOTAL)/FCXP.VLR_NETO),   
                #T.CNSFACJ, #T.CODCAJA, '', NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
                (SELECT TOP 1 FCXPD.PREFIJO FROM FCXPD WHERE FCXPD.CNSFCXP=FCXPP.CNSFCXP),  
                (SELECT TOP 1 LEFT(FCXPD.IDAREA,10) FROM FCXPD WHERE FCXPD.CNSFCXP=FCXPP.CNSFCXP),'S',1,  
                'EGRESO_CXP_'+UPPER(FCXP.PROCEDENCIA),FCXPP.CNSFCXPP,  
                FCXP.NOREFERENCIA,DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF),  
                DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 'Movimiento','CAJA',@CNSFACJ, 
                CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, 
                CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
         FROM  #T, #TH, FCXP, FCXPP, FCXPD  
         WHERE #TH.IDSERVICIO = FCXPP.CNSFCXPP 
         AND   FCXPP.CNSFCXP  = FCXP.CNSFCXP 
         AND   FCXP.CNSFCXP   = FCXPD.CNSFCXP
         GROUP BY FCXP.CUECREDITO, FCXP.IDTERCERO, FCXP.NOREFERENCIA, #T.CNSFACJ, #T.CODCAJA,      
                  FCXPP.CNSFCXPP, DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF),  
                  DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), FCXP.PROCEDENCIA, FCXPP.CNSFCXP,  
                  FCXPD.CUENTA_SER, FCXPD.IDAREA, FCXPD.CCOSTO, FCXP.CNSFCOM, #T.CODUNG, #T.CODPRG,
                  FCXP.OBSERVACION, FCXPD.PREFIJO  
         HAVING SUM((FCXPD.VLR_NETO*#TH.VALORTOTAL)/FCXP.VLR_NETO) <> 0 
      END
      PRINT 'Corrigiendo  MCH... 2.'  
      
      UPDATE MCH SET VALOR = MCH.VALOR + (#T.VALORTOTAL-C.VALOR)   
      FROM (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCH   
            WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' AND PROCESO LIKE 'EGRESO_CXP_%' AND REFERENCIA_PRO=@CNSFACJ) AS B,  
           (SELECT SUM(VALOR) AS VALOR FROM MCH   
            WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' AND PROCESO LIKE 'EGRESO_CXP_%' AND REFERENCIA_PRO=@CNSFACJ) AS C,  
           #T  
      WHERE MCH.NROASIENTO=B.NROASIENTO AND (#T.VALORTOTAL-C.VALOR)<>0  
      
      PRINT 'Contabilizando Cruces con CXC...'  
      SET @CNSFCXPPM=''  
      SELECT TOP 1 @CNSFCXPPM = FCXPP.CNSFCXPPM
      FROM #TH INNER JOIN   
           FCXPP ON #TH.IDSERVICIO=FCXPP.CNSFCXPP  
      IF @CNSFCXPPM IS NULL  
         SET @CNSFCXPPM = ''  
      IF (SELECT COUNT(*) FROM FCXPCXC WHERE CNSFCXPPM = @CNSFCXPPM)>0
      BEGIN  
         PRINT 'Insertando CXP con Cruces en CXC (DB) 1.'  
         INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,    
                         REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,  
                         CNSPAGO,N_FACTURA,F_FACTURAREF,F_VENCE,GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)    
         SELECT @NROCOMPROBANTE,@COMPANIA,'DB',FCXP.CUECREDITO, FCXP.IDTERCERO,  
               (SELECT TOP 1 FCXPD.CCOSTO FROM FCXPD WHERE FCXPD.CNSFCXP=FCXP.CNSFCXP),  
               'PAGO CON CRUCE FACTURA No. '+FCXP.NOREFERENCIA,  
               FCXPP.ABONO - ISNULL(#TH.VALORTOTAL,0),   
                @CNSFACJ,@CODCAJA,'',NULL,@USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
               (SELECT TOP 1 FCXPD.PREFIJO FROM FCXPD WHERE FCXPD.CNSFCXP=FCXP.CNSFCXP),  
               (SELECT TOP 1 LEFT(FCXPD.IDAREA,10) FROM FCXPD WHERE FCXPD.CNSFCXP=FCXP.CNSFCXP),'S',1,  
               'CRUCE_CXP_'+UPPER(FCXP.PROCEDENCIA),FCXPP.CNSFCXPP,  
               FCXP.NOREFERENCIA,DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF),  
               DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 'Movimiento','CAJA',@CNSFACJ, 
               CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, 
               CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
         FROM FCXPP LEFT JOIN  
              #TH ON #TH.IDSERVICIO=FCXPP.CNSFCXPP LEFT JOIN  
              #T ON #T.CODCAJA=#TH.CODCAJA LEFT JOIN
              FCXP ON FCXPP.CNSFCXP=FCXP.CNSFCXP  
         WHERE FCXPP.CNSFCXPPM=@CNSFCXPPM AND FCXPP.ABONO - ISNULL(#TH.VALORTOTAL,0)<>0 AND FCXPP.ESTADO<>'A'
           
         PRINT 'Insertando CXC con Cruces en CXP (CR) 2.'  
         INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,    
                         REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,  
                         CNSPAGO,N_FACTURA,F_FACTURAREF,F_VENCE,GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)    
         SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', FCXCD.CUENTA, FCXPCXC.IDTERCERO,  
               '', 'PAGO CON CRUCE FACTURA No. '+FCXPCXC.N_FACTURA, FCXPCXC.VALOR, @CNSFACJ, @CODCAJA, '', NULL, @USUARIO,   
               DBO.FNK_FECHA_SIN_MLS(GETDATE()),'','','S',1,'CRUCE_CXC',FCXPCXC.CNSCXC,  
               FCXPCXC.N_FACTURA, DBO.FNK_FECHA_SIN_HORA(FTRCONT.F_FACTURA),DBO.FNK_FECHA_SIN_HORA(FTRCONT.F_VENCE),   
               'Movimiento','CAJA',@CNSFACJ, 
                CASE WHEN FTR.CODUNG = '' THEN NULL ELSE FTR.CODUNG END, CASE WHEN FTR.CODPRG = '' THEN NULL ELSE FTR.CODPRG END
         FROM FCXPCXC LEFT JOIN  
              FCXC ON FCXPCXC.CNSCXC=FCXC.CNSCXC LEFT JOIN  
              FCXCD ON FCXCD.CNSCXC=FCXC.CNSCXC AND FCXPCXC.N_FACTURA=FCXCD.N_FACTURA LEFT JOIN  
              CUE ON FCXCD.CUENTA = CUE.CUENTA AND CUE.COMPANIA = @COMPANIA LEFT JOIN  
              FTRCONT ON FTRCONT.IDTERCERO=FCXC.IDTERCERO AND FTRCONT.N_FACTURA=FCXCD.N_FACTURA AND FTRCONT.CLASE=CUE.CLASE LEFT JOIN
              FTR ON FCXCD.N_FACTURA = FTR.N_FACTURA AND FCXC.IDTERCERO = FTR.IDTERCERO
         WHERE FCXPCXC.CNSFCXPPM=@CNSFCXPPM AND FCXPCXC.VALOR<>0  
      END  
   END  
   ELSE  
   IF DBO.FNK_VALORVARIABLE('IDCJTETRASLADO')=@TIPOEGRESO --EGRESO POR TRASLADO CAJA  
   BEGIN  
      SET @SW=0  
      PRINT 'Traslado.'  
      PRINT ' -Insertando Registro MCH...'    
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                      REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                      PROCESO,GENERA,N_FACTURA,F_FACTURAREF,F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
      SELECT @NROCOMPROBANTE,@COMPANIA,'DB',CAJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,  
         'INGRESO DE '+UPPER(FPA.DESCRIPCION)+', POR '+UPPER(CPCJ.DESCRIPCION)+', DE '+UPPER(RTRIM(TER.RAZONSOCIAL))+' A '+  
         (SELECT UPPER(RTRIM(TER.RAZONSOCIAL)) FROM TER WHERE TER.IDTERCERO=#T.IDTERCERO)+',  RECIBO No.'+#T.CNSFACJ,  
         SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),  
         #T.CNSFACJ,#T.CODCAJA,'',NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
         NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_TRASLADO', 'Movimiento',  
         RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
         CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM #T,#TH,#THD,CPCJ,CAJ,TER,FPA  
      WHERE #T.IDTERCERO=CAJ.CODCAJA AND #T.CODCAJA=TER.IDTERCERO AND #TH.CONCEPTO=CPCJ.CODIGO AND   
        FPA.FORMAPAGO=#THD.TIPOPAGO  
      GROUP BY CAJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,#T.CODCAJA,TER.RAZONSOCIAL,#T.CNSFACJ,#T.AREAPRESTACION,CPCJ.DESCRIPCION,  
           FPA.DESCRIPCION, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.CODUNG, #T.CODPRG   
  
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                     PROCESO,GENERA,N_FACTURA,F_FACTURAREF,F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
      SELECT @NROCOMPROBANTE,@COMPANIA,'CR',CAJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,  
            'EGRESO DE '+UPPER(FPA.DESCRIPCION)+', POR '+UPPER(CPCJ.DESCRIPCION)+  
            ', DE '+(SELECT UPPER(RTRIM(TER.RAZONSOCIAL)) FROM TER WHERE TER.IDTERCERO=#T.CODCAJA)+' A '+  
            UPPER(RTRIM(TER.RAZONSOCIAL))+',  RECIBO No.'+#T.CNSFACJ,  
            SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),  
            #T.CNSFACJ,#T.CODCAJA,'',NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
            NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_TRASLADO', 'Movimiento',  
            RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM #T,#TH,#THD,CPCJ,CAJ,TER,FPA  
      WHERE #T.CODCAJA=CAJ.CODCAJA AND #T.IDTERCERO=TER.IDTERCERO AND #TH.CONCEPTO=CPCJ.CODIGO AND  
            FPA.FORMAPAGO=#THD.TIPOPAGO  
      GROUP BY CAJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,#T.CODCAJA,TER.RAZONSOCIAL,  
               #T.CNSFACJ,#T.AREAPRESTACION,CPCJ.DESCRIPCION,FPA.DESCRIPCION,  
               DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.CODUNG, #T.CODPRG     
   END  
   ELSE    
   IF DBO.FNK_VALORVARIABLE('IDCJTECONSIGNACION')=@TIPOEGRESO 
   OR (@IDCATEGORIA=DBO.FNK_VALORVARIABLE('TERCATBANCO') AND @TIPOEGRESO NOT IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('IDCJTETRASBCOCAJA','IDCJTETRASLADOBCO'))) --EGRESO POR CONSIGNACION  
   BEGIN  
      SET @SW=0  
      PRINT 'Consignaciones a Bancos.'  
      PRINT ' -Insertando Registro MCH...'    

      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                      REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                      PROCESO,GENERA,N_FACTURA,F_FACTURAREF,F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
      SELECT @NROCOMPROBANTE,@COMPANIA,'DB',BCT.COD_CONTABLE,#T.IDTERCERO,#T.CCOSTO,  
             'CONSIGNACION '+ISNULL(CUE.NOMCUENTA,'')+', '+(CASE WHEN FCJTD.NUMERODOCUMENTO IS NULL THEN '' ELSE 'DOC No. '+FCJTD.NUMERODOCUMENTO END),  
             FCJTD.VALOR, #T.CNSFACJ, #T.CODCAJA, FCJTD.NUMERODOCUMENTO, NULL, @USUARIO,  
             DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_CONSIGNACION', 'Movimiento',  
             RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
             CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM #T,FCJTD,FPA,BCT LEFT JOIN
           CUE ON CUE.CUENTA = BCT.COD_CONTABLE AND CUE.COMPANIA=@COMPANIA
      WHERE #T.CODCAJA=FCJTD.CODCAJA AND  
            BCT.BANCO=#T.BANCO AND BCT.SUCURSAL=#T.SUCURSAL AND BCT.CTA_BCO=#T.CTA_BCO AND  
            FCJTD.FORMAPAGO=FPA.FORMAPAGO  
            AND FCJTD.ASIGNADO = 1  -- JEDM  
      UNION ALL  
      SELECT @NROCOMPROBANTE,@COMPANIA,'DB',BCT.COD_CONTABLE,#T.IDTERCERO,#T.CCOSTO,  
             'CONSIGNACION '+ISNULL(CUE.NOMCUENTA,''),  
             #THD.VALOR,#T.CNSFACJ,#T.CODCAJA,#THD.NUMERODOCUMENTO,NULL,@USUARIO,  
             DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
             NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_CONSIGNACION', 'Movimiento',  
             RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
             CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM   #T,#THD,FPA,BCT LEFT JOIN
             CUE ON CUE.CUENTA = BCT.COD_CONTABLE AND CUE.COMPANIA=@COMPANIA
      WHERE BCT.BANCO=#T.BANCO AND BCT.SUCURSAL=#T.SUCURSAL AND   
            BCT.CTA_BCO=#T.CTA_BCO AND #THD.TIPOPAGO=FPA.FORMAPAGO AND FPA.REQDOC=0   
      PRINT 'Credito.' 
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                     REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
                     N_FACTURA,F_FACTURAREF,F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
      SELECT @NROCOMPROBANTE,@COMPANIA,'CR',CAJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,  
            UPPER(CPCJ.DESCRIPCION)+', '+UPPER(FPA.DESCRIPCION)+', CAJA: '+UPPER(CAJ.DESCRIPCION),  
            SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),  
            #T.CNSFACJ,#T.CODCAJA,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
            NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_CONSIGNACION', 'Movimiento',  
            RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM #T,#TH,#THD,CPCJ,CAJ,TER,FPA  
      WHERE #T.CODCAJA=CAJ.CODCAJA AND #T.IDTERCERO=TER.IDTERCERO AND #TH.CONCEPTO=CPCJ.CODIGO AND  
            FPA.FORMAPAGO=#THD.TIPOPAGO  
      GROUP BY CAJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,#T.CODCAJA,TER.RAZONSOCIAL,  
               #T.CNSFACJ,#T.AREAPRESTACION,CPCJ.DESCRIPCION,FPA.DESCRIPCION,  
               DBO.FNK_FECHA_SIN_HORA(#T.FECHA), CAJ.DESCRIPCION, #T.CODUNG, #T.CODPRG 
   END  
   ELSE   
   IF DBO.FNK_VALORVARIABLE('IDCJTENOMINA')=@TIPOEGRESO --EGRESO POR NOMINA  
   BEGIN  
      SET @SW=0  
      PRINT 'Nomina.'  
      PRINT ' -Insertando Registro DB MCH...'    
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,    
                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,    
                     PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
      SELECT @NROCOMPROBANTE,@COMPANIA,'DB',CPCJ.CUENTA,#TH.IDSERVICIO, #T.CCOSTO, UPPER(#T.OBSERVACION),    
            SUM(#TH.VALORTOTAL),#T.CNSFACJ,#T.CODCAJA,#TH.IDSERVICIO,NULL,@USUARIO,    
            DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_NOMINA','Movimiento',    
            RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM #T LEFT JOIN 
            #TH ON #T.CODCAJA=#TH.CODCAJA LEFT JOIN 
            CJTE ON #T.TIPOEGRESO=CJTE.TIPOEGRESO LEFT JOIN 
            CPCJ ON CJTE.CODIGO=CPCJ.CODIGO
      GROUP BY CPCJ.CUENTA, #T.CCOSTO, #T.CNSFACJ, #T.CODCAJA, #TH.IDSERVICIO,
               #T.AREAPRESTACION, #T.OBSERVACION, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.CODUNG, #T.CODPRG    
  
      PRINT ' -Insertando Registro CR MCH...'    
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                     PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
      SELECT @NROCOMPROBANTE,@COMPANIA,'CR',  
            CASE WHEN FPA.USAR_CUENTACAJA=0 THEN FPA.CUENTA ELSE CASE WHEN BCT.BANCO IS NULL THEN CAJ.CUENTA ELSE BCT.COD_CONTABLE END END,  
            #THD.IDTERCERO,#T.CCOSTO,  
            ISNULL((SELECT A.RAZONSOCIAL FROM TER A WHERE #THD.IDTERCERO=A.IDTERCERO),'')+
            CASE WHEN #THD.NUMERODOCUMENTO IS NULL OR #THD.NUMERODOCUMENTO='' THEN '' ELSE ',  CH '+#THD.NUMERODOCUMENTO END,  
            #THD.VALOR,#T.CNSFACJ,#T.CODCAJA,#THD.NUMERODOCUMENTO,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
            NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_NOMINA', 'Movimiento',  
            RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM  #THD LEFT JOIN   
            BCT ON BCT.BANCO=#THD.BANCO AND BCT.SUCURSAL=#THD.SUCURSAL AND BCT.CTA_BCO=#THD.CTA_BCO LEFT JOIN   
            FPA ON FPA.FORMAPAGO=#THD.TIPOPAGO INNER JOIN   
            #TH ON #TH.IDSERVICIO=#THD.IDTERCERO AND #THD.NUMEROAUTORIZA = #TH.ITEM,   
            #T INNER JOIN CAJ ON #T.CODCAJA=CAJ.CODCAJA  
      ORDER BY #THD.NUMERODOCUMENTO  
   END   
   ELSE    
   IF DBO.FNK_VALORVARIABLE('IDCJTEDEVOLDOCUMENTO')=@TIPOEGRESO  
   BEGIN  
      SET @SW=0  
      PRINT 'Devolucion de Documentos.'  
      PRINT ' -Insertando Registro DB MCH...'    
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                     PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
      SELECT @NROCOMPROBANTE,@COMPANIA,'DB',CPCJ.CUENTA,#T.IDTERCERO,#T.CCOSTO, UPPER(#T.OBSERVACION),  
            SUM(#TH.VALORTOTAL),#T.CNSFACJ,#T.CODCAJA,#T.IDTERCERO,NULL,@USUARIO,  
            DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_DEVDOC','Movimiento',  
            RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM #T,#TH LEFT JOIN CPCJ ON #TH.CONCEPTO=CPCJ.CODIGO  
      GROUP BY CPCJ.CUENTA, #T.CCOSTO, #T.CNSFACJ, #T.CODCAJA, #T.IDTERCERO,  
               #T.AREAPRESTACION, #T.OBSERVACION, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.CODUNG, #T.CODPRG  
  
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                     REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
                     N_FACTURA,F_FACTURAREF,F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
      SELECT @NROCOMPROBANTE,@COMPANIA,'CR',CAJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,  
            UPPER(CPCJ.DESCRIPCION)+', '+UPPER(FPA.DESCRIPCION)+', '+UPPER(RTRIM(TER.RAZONSOCIAL)),  
            SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),  
            #T.CNSFACJ,#T.CODCAJA,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
            NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_DEVDOC', 'Movimiento',  
            RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM #T,#TH,#THD,CPCJ,CAJ,TER,FPA  
      WHERE #T.CODCAJA=CAJ.CODCAJA AND #T.IDTERCERO=TER.IDTERCERO AND #TH.CONCEPTO=CPCJ.CODIGO AND  
            FPA.FORMAPAGO=#THD.TIPOPAGO  
      GROUP BY CAJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,#T.CODCAJA,TER.RAZONSOCIAL,  
               #T.CNSFACJ,#T.AREAPRESTACION,CPCJ.DESCRIPCION,FPA.DESCRIPCION,  
               DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.CODUNG, #T.CODPRG  
   END  
   ELSE  
   IF DBO.FNK_VALORVARIABLE('IDCJTEDEVOLDEPOSITO')=@TIPOEGRESO
   BEGIN
      PRINT 'Devolucion de un Deposito.'  
      SET @SW = 1
      PRINT ' -Insertando Registro DB MCH...'    
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                     PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
      SELECT @NROCOMPROBANTE,@COMPANIA,'DB',CPCJ.CUENTA,#T.IDTERCERO,#T.CCOSTO, UPPER(#T.OBSERVACION),  
            SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),
            #T.CNSFACJ,#T.CODCAJA,#T.IDTERCERO,NULL,@USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,
            LEFT(#T.AREAPRESTACION,10),'S',1,'CAJA_DEVDEP','Movimiento', 
            ISNULL((SELECT NOADMISION FROM FCJ WHERE CODCAJA=#THD.CODCAJADEP AND CNSFACJ=#THD.CNSFACJDEP),
            RTRIM(#THD.CODCAJADEP)+#THD.CNSFACJDEP),
            DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM #T,#THD,#TH LEFT JOIN CPCJ ON #TH.CONCEPTO=CPCJ.CODIGO  
      GROUP BY CPCJ.CUENTA, #T.CCOSTO, #T.CNSFACJ, #T.CODCAJA, #T.IDTERCERO, #THD.CODCAJADEP, #THD.CNSFACJDEP, 
               #T.AREAPRESTACION, #T.OBSERVACION, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.CODUNG, #T.CODPRG           
   END
   ELSE
   IF DBO.FNK_VALORVARIABLE('IDCJTETRASLADOBCO')=@TIPOEGRESO -- TRASLADOS ENTRE BANCOS
   BEGIN
      SET @SW = 0
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                     REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
                     N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
      SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', BCT.COD_CONTABLE, #T.IDTERCERO, #T.CCOSTO, 
            CASE WHEN FPA.REQBCO = 1 
                  THEN CASE WHEN FPA.GENCHEQUE = 1 
                           THEN RTRIM(CUE.NOMCUENTA)+', INGRESO POR TRASLADO, CHEQUE No.'+LTRIM(RTRIM(ISNULL(#THD.NUMERODOCUMENTO,''))) 
                           ELSE RTRIM(CUE.NOMCUENTA)+CASE WHEN ISNULL(#THD.NUMERODOCUMENTO,'') = ''
                                                         THEN ', INGRESO POR TRASLADO' 
                                                         ELSE ', INGRESO POR TRASLADO, DOCUMENTO No.'+LTRIM(RTRIM(#THD.NUMERODOCUMENTO)) 
                                                      END
                           END 
                  ELSE 
                     RTRIM(CUE.NOMCUENTA)+', INGRESO POR TRASLADO, '+RTRIM(FPA.DESCRIPCION)
            END, 
            SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),#T.CNSFACJ,#T.CODCAJA,NULL,@USUARIO,  
            DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'TRASLADOBCO', 'Movimiento',  
            RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
            CASE WHEN #T.CODUNG = '' 
                  THEN NULL 
                  ELSE #T.CODUNG 
            END, 
            CASE WHEN #T.CODPRG = '' 
                  THEN NULL 
                  ELSE #T.CODPRG 
            END
      FROM   #T INNER JOIN #TH  ON #T.CODCAJA    = #TH.CODCAJA      AND #T.CNSFACJ  = #TH.CNSFACJ 
               INNER JOIN #THD ON #TH.CODCAJA   = #THD.CODCAJA     AND #TH.CNSFACJ = #THD.CNSFACJ 
               LEFT  JOIN FPA  ON #THD.TIPOPAGO = FPA.FORMAPAGO 
               LEFT  JOIN BCT  ON #T.BANCO      = BCT.BANCO        AND #T.SUCURSAL = BCT.SUCURSAL AND #T.CTA_BCO = BCT.CTA_BCO 
               LEFT  JOIN CUE  ON CUE.CUENTA    = BCT.COD_CONTABLE AND CUE.COMPANIA = @COMPANIA
      GROUP BY FPA.USAR_CUENTACAJA, FPA.REQBCO, BCT.COD_CONTABLE, #T.IDTERCERO, #T.CCOSTO, #T.CNSFACJ, 
               LEFT(#T.AREAPRESTACION,10), FPA.DESCRIPCION, #T.CODCAJA, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 
               #THD.NUMERODOCUMENTO, FPA.GENCHEQUE, CUE.NOMCUENTA, #T.CODUNG, #T.CODPRG
          
      PRINT ' -Insertando Registro CR MCH...'    
      INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                      REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                      PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
      SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',  
            CASE WHEN FPA.USAR_CUENTACAJA = 0 THEN FPA.CUENTA ELSE ISNULL(BCT.COD_CONTABLE,CAJ.CUENTA) END,  
            #THD.IDTERCERO, #T.CCOSTO,  
            ISNULL(CUE.NOMCUENTA+', ','')+'TRASLADO DE FONDOS '+
            CASE WHEN ISNULL(#THD.NUMERODOCUMENTO,'') = '' THEN '' ELSE ',  DOC. '+#THD.NUMERODOCUMENTO END,  
            #THD.VALOR, #THD.CNSFACJ, #THD.CODCAJA, #THD.NUMERODOCUMENTO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
            NULL, '' ,'S', 1, 'CAJA_TRASBANCO', 'Movimiento',  
            RTRIM(#THD.CODCAJA)+#THD.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 'CAJA', @CNSFACJ, 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM  #T INNER JOIN
            #THD ON #T.CODCAJA=#THD.CODCAJA AND #T.CNSFACJ=#THD.CNSFACJ LEFT JOIN   
            BCT  ON BCT.BANCO=#THD.BANCO AND BCT.SUCURSAL=#THD.SUCURSAL AND BCT.CTA_BCO=#THD.CTA_BCO LEFT JOIN   
            FPA  ON FPA.FORMAPAGO=#THD.TIPOPAGO LEFT JOIN   
            CAJ  ON #THD.CODCAJA=CAJ.CODCAJA LEFT JOIN
            CUE  ON CUE.CUENTA = CASE WHEN FPA.USAR_CUENTACAJA = 0 THEN FPA.CUENTA ELSE ISNULL(BCT.COD_CONTABLE,CAJ.CUENTA) END AND 
                  CUE.COMPANIA=@COMPANIA
      ORDER BY #THD.NUMERODOCUMENTO  
   END
   ELSE
   BEGIN  
      IF DBO.FNK_VALORVARIABLE('IDCJTETRASBCOCAJA')=@TIPOEGRESO -- TRASLADOS ENTRE BANCOS
      BEGIN
         SET @SW = 0
         ---------------------------------------------------------------------------------------------------------------------------------------
         PRINT 'Credito.' 
         INSERT INTO MCH(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1,  
                         REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                         PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)     
         SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', BCT.COD_CONTABLE, #THD.IDTERCERO, #T.CCOSTO,
                ISNULL(CUE.NOMCUENTA+', ','')+'TRASLADO DE FONDOS A CAJA'+ CASE WHEN ISNULL(#THD.NUMERODOCUMENTO,'') = '' THEN '' ELSE ',  DOC. '+#THD.NUMERODOCUMENTO END,
                #THD.VALOR, #THD.CNSFACJ, #THD.CODCAJA, #THD.NUMERODOCUMENTO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
                NULL, '' ,'S', 1,'TRASBANCO_CAJA', 'Movimiento', 
                RTRIM(#THD.CODCAJA)+#THD.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 'CAJA', @CNSFACJ, 
                CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
         FROM   #T INNER JOIN #THD ON #T.CODCAJA   = #THD.CODCAJA 
                                  AND #T.CNSFACJ   = #THD.CNSFACJ 
                    LEFT JOIN BCT  ON BCT.BANCO    = #THD.BANCO 
                                  AND BCT.SUCURSAL = #THD.SUCURSAL 
                                  AND BCT.CTA_BCO  = #THD.CTA_BCO
                    LEFT JOIN CAJ  ON #THD.CODCAJA = CAJ.CODCAJA 
                    LEFT JOIN CUE  ON CUE.CUENTA   = BCT.COD_CONTABLE
                                  AND CUE.COMPANIA = @COMPANIA
         ORDER BY #THD.NUMERODOCUMENTO 
         PRINT 'Débito'
         INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                         REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                         PROCESO,GENERA,N_FACTURA,F_FACTURAREF,F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
         SELECT @NROCOMPROBANTE,@COMPANIA,'DB', CAJ.CUENTA, #T.IDTERCERO, #T.CCOSTO,  
                'INGRESO DE '+UPPER(FPA.DESCRIPCION)+', POR '+UPPER(CPCJ.DESCRIPCION)+', DE '+UPPER(RTRIM(TER.RAZONSOCIAL))+' A '+  
                (SELECT UPPER(RTRIM(TER.RAZONSOCIAL)) FROM TER WHERE TER.IDTERCERO=#T.IDTERCERO)+',  RECIBO No.'+#T.CNSFACJ,  
                SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),  
                #T.CNSFACJ,#T.CODCAJA,'',NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),  
                NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'TRASLADO_BANCO_CAJA', 'Movimiento',  
                RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
                CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
         FROM   #T INNER JOIN #THD ON #T.CODCAJA    = #THD.CODCAJA 
                                  AND #T.CNSFACJ    = #THD.CNSFACJ 
                   INNER JOIN #TH  ON #T.CODCAJA    = #TH.CODCAJA 
                                  AND #T.CNSFACJ    = #TH.CNSFACJ 
                    LEFT JOIN CAJ  ON #T.CODCAJA    = CAJ.CODCAJA
                    LEFT JOIN TER  ON #T.IDTERCERO  = TER.IDTERCERO
                    LEFT JOIN CPCJ ON #TH.CONCEPTO  = CPCJ.CODIGO
                    LEFT JOIN FPA  ON FPA.FORMAPAGO = #THD.TIPOPAGO  
         GROUP BY CAJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,#T.CODCAJA,TER.RAZONSOCIAL,#T.CNSFACJ,#T.AREAPRESTACION,CPCJ.DESCRIPCION,  
                  FPA.DESCRIPCION, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.CODUNG, #T.CODPRG   
         ---------------------------------------------------------------------------------------------------------------------------------------
      END
      ELSE
      BEGIN         
         PRINT 'Otros Egresos.'  
         SET @SW=1  
         PRINT ' -Insertando Registro MCH. Con Tipos de Egreso' 
         SELECT @CLASECAJA =UPPER(CLASE) FROM CAJ WHERE CODCAJA = @CODCAJA 
         --Menor FCJD
         IF  @CLASECAJA = 'MENOR' AND DBO.FNK_VALORVARIABLE('HABILITA_CCAFCJMENOR') = 'SI'
         BEGIN
            PRINT ' CONTABILIZACION DE CAJA MENOR HABILITADA'    
            INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                           REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
                           PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
            SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',  DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT,'CAJA_MENOR','DB',#TH.CONCEPTO,#TH.IDAREA,#TH.CCOSTO,'P',''), #T.IDTERCERO, #T.CCOSTO,   
                     'EGRESO DE CAJA No.'+@CODCAJA+' POR '+UPPER(CJTE.DESCRIPCION)+', RECIBO No.'+#T.CNSFACJ,  
                     SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),#T.CNSFACJ,#T.CODCAJA,#T.TIPOEGRESO,NULL,@USUARIO,  
                     --DBO.FNK_FECHA_SIN_MLS(GETDATE()),CPCJ.CODIGO,LEFT(#T.AREAPRESTACION,10),'S',1,'EGRESOS', 'Movimiento',  
			            DBO.FNK_FECHA_SIN_MLS(GETDATE()),CPCJ.CODIGO,LEFT(#TH.IDAREA,10),'S',1,'EGRESOS', 'Movimiento',  
                     RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
                     CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
            FROM   #THD,#T LEFT JOIN CJTE ON #T.TIPOEGRESO = CJTE.TIPOEGRESO, #TH 
                           LEFT JOIN CPCJ ON #TH.CONCEPTO=CPCJ.CODIGO  
            GROUP BY #T.IDTERCERO,#T.CCOSTO,#T.CNSFACJ,LEFT(#TH.IDAREA,10),#T.CODCAJA,CPCJ.CODIGO,  
                  CJTE.DESCRIPCION,#T.TIPOEGRESO,DBO.FNK_FECHA_SIN_HORA(#T.FECHA), DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT,'CAJA_MENOR','DB',#TH.CONCEPTO,#TH.IDAREA,#TH.CCOSTO,'P',''),CPCJ.DESCRIPCION, 
                  #T.CODUNG, #T.CODPRG
         END
         ELSE
         BEGIN    
	         INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
		                      REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,  
		                      PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)      
	         SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', CPCJ.CUENTA, #T.IDTERCERO, #T.CCOSTO,   
		             'EGRESO DE CAJA No.'+@CODCAJA+' POR '+UPPER(CJTE.DESCRIPCION)+', RECIBO No.'+#T.CNSFACJ,  
		             SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),#T.CNSFACJ,#T.CODCAJA,#T.TIPOEGRESO,NULL,@USUARIO,  
		             DBO.FNK_FECHA_SIN_MLS(GETDATE()),CPCJ.CODIGO,LEFT(#T.AREAPRESTACION,10),'S',1,'EGRESOS', 'Movimiento',  
		             RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
		             CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
	         FROM   #THD,#T LEFT JOIN CJTE ON #T.TIPOEGRESO = CJTE.TIPOEGRESO, #TH 
                           LEFT JOIN CPCJ ON #TH.CONCEPTO  = CPCJ.CODIGO  
	         GROUP BY #T.IDTERCERO,#T.CCOSTO,#T.CNSFACJ,LEFT(#T.AREAPRESTACION,10),#T.CODCAJA,CPCJ.CODIGO,  
		               CJTE.DESCRIPCION,#T.TIPOEGRESO,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),CPCJ.CUENTA,CPCJ.DESCRIPCION, 
		               #T.CODUNG, #T.CODPRG  
         END  
      END
   END  
  
 IF @SW=1  
 BEGIN  
  PRINT 'Insertando Asiento del Concepto de Caja. (CR)'  
     -- Busqueda del Banco
     SET @BANCO=''
     SELECT TOP 1 @BANCO=BCO.BANCO, @NOCHEQUE=#THD.NUMERODOCUMENTO, @VALOR_CHEQUE=#THD.VALOR  
     FROM #THD,BCO,#T  
     WHERE #THD.BANCO=BCO.BANCO AND #THD.TIPOPAGO = DBO.FNK_VALORVARIABLE('IDFCJEGRECHEQUE')  
   
     IF EXISTS(SELECT BANCO FROM BCO WHERE BANCO=@BANCO)
     BEGIN
        UPDATE MCP SET BANCO=@BANCO, NOCHEQUE=@NOCHEQUE, VALOR_CHEQUE=@VALOR_CHEQUE  
        WHERE NROCOMPROBANTE=@NROCOMPROBANTE  
     END 
	  -- ADD. JQUIROGA 20090515 - Si es CXP, Registrar Mov. Credito por Tercero.
	IF DBO.FNK_VALORVARIABLE('IDCJTECXP') = @TIPOEGRESO
	BEGIN  
	   PRINT ' -Insertando Registro MCH con Egreso EFECTIVO'  
	   INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
					   REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
					   N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
	   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 
			 CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
			  CASE WHEN FPA.REQBCO = 1 THEN BCT.COD_CONTABLE ELSE CAJ.CUENTA END
			 ELSE 
			  FPA.CUENTA 
			 END,
			 FCXP.IDTERCERO, #T.CCOSTO, 
			 CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
			  CASE WHEN FPA.REQBCO = 1 THEN 
			   CASE WHEN FPA.GENCHEQUE = 1 
				THEN RTRIM(TER.RAZONSOCIAL)+', CHEQUE No.'+LTRIM(RTRIM(ISNULL(#THD.NUMERODOCUMENTO,''))) 
				ELSE RTRIM(TER.RAZONSOCIAL)+CASE WHEN ISNULL(#THD.NUMERODOCUMENTO,'')='' THEN '' ELSE ', DOCUMENTO No.'+LTRIM(RTRIM(#THD.NUMERODOCUMENTO)) END
			   END 
			  ELSE 
			   FPA.DESCRIPCION+', '+RTRIM(TER.RAZONSOCIAL)+', RECIBO CAJA No.'+#T.CNSFACJ 
			  END
			 ELSE 
			  FPA.DESCRIPCION+', '+RTRIM(TER.RAZONSOCIAL)+', RECIBO CAJA No.'+#T.CNSFACJ 
			 END,
			 SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),#T.CNSFACJ,#T.CODCAJA,NULL,@USUARIO,  
			 DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'FPA_EGRESO', 'Movimiento',  
			 RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
			 CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
	   FROM  #T INNER JOIN 
			 #TH  ON #T.CODCAJA=#TH.CODCAJA AND #T.CNSFACJ=#TH.CNSFACJ INNER JOIN 
			 #THD ON #TH.CODCAJA=#THD.CODCAJA AND #TH.CNSFACJ=#THD.CNSFACJ LEFT JOIN 
			 FPA  ON #THD.TIPOPAGO=FPA.FORMAPAGO LEFT JOIN
			 CAJ  ON #T.CODCAJA=CAJ.CODCAJA LEFT JOIN
			 BCT  ON #THD.BANCO=BCT.BANCO AND #THD.SUCURSAL=BCT.SUCURSAL AND #THD.CTA_BCO=BCT.CTA_BCO LEFT JOIN
			 FCXPP ON FCXPP.CNSFCXPP = #TH.IDSERVICIO INNER JOIN  
			 FCXP ON  FCXP.CNSFCXP = FCXPP.CNSFCXP LEFT JOIN
			 TER  ON TER.IDTERCERO = FCXP.IDTERCERO 
	   GROUP BY TER.RAZONSOCIAL, FPA.USAR_CUENTACAJA, FPA.REQBCO, BCT.COD_CONTABLE, CAJ.CUENTA, FPA.CUENTA, 
			   FCXP.IDTERCERO, #T.CCOSTO, #T.CNSFACJ, LEFT(#T.AREAPRESTACION,10), FPA.DESCRIPCION, 
			   #T.CODCAJA, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #THD.NUMERODOCUMENTO, FPA.GENCHEQUE, #T.CODUNG, #T.CODPRG  
	END
	ELSE
	BEGIN
   PRINT ' -Insertando Registro MCH con Egreso EFECTIVO'  
   INSERT INTO MCH(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                   REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
                   N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 
         CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
          CASE WHEN FPA.REQBCO = 1 THEN BCT.COD_CONTABLE ELSE CAJ.CUENTA END
         ELSE 
          FPA.CUENTA 
         END,
         #T.IDTERCERO, #T.CCOSTO, 
         CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
          CASE WHEN FPA.REQBCO = 1 THEN 
           CASE WHEN FPA.GENCHEQUE = 1 
            THEN RTRIM(TER.RAZONSOCIAL)+', CHEQUE No.'+LTRIM(RTRIM(ISNULL(#THD.NUMERODOCUMENTO,''))) 
            ELSE RTRIM(TER.RAZONSOCIAL)+CASE WHEN ISNULL(#THD.NUMERODOCUMENTO,'')='' THEN '' ELSE ', DOCUMENTO No.'+LTRIM(RTRIM(#THD.NUMERODOCUMENTO)) END
           END 
          ELSE 
           FPA.DESCRIPCION+', '+RTRIM(TER.RAZONSOCIAL)+', RECIBO CAJA No.'+#T.CNSFACJ 
          END
         ELSE 
          FPA.DESCRIPCION+', '+RTRIM(TER.RAZONSOCIAL)+', RECIBO CAJA No.'+#T.CNSFACJ 
         END,
         SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),#T.CNSFACJ,#T.CODCAJA,NULL,@USUARIO,  
         DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'FPA_EGRESO', 'Movimiento',  
         RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
         CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
   FROM  #T INNER JOIN 
         #TH  ON #T.CODCAJA=#TH.CODCAJA AND #T.CNSFACJ=#TH.CNSFACJ INNER JOIN 
         #THD ON #TH.CODCAJA=#THD.CODCAJA AND #TH.CNSFACJ=#THD.CNSFACJ LEFT JOIN 
         FPA  ON #THD.TIPOPAGO=FPA.FORMAPAGO LEFT JOIN
         CAJ  ON #T.CODCAJA=CAJ.CODCAJA LEFT JOIN
         BCT  ON #THD.BANCO=BCT.BANCO AND #THD.SUCURSAL=BCT.SUCURSAL AND #THD.CTA_BCO=BCT.CTA_BCO LEFT JOIN
         TER  ON TER.IDTERCERO = #T.IDTERCERO
   GROUP BY TER.RAZONSOCIAL, FPA.USAR_CUENTACAJA, FPA.REQBCO, BCT.COD_CONTABLE, CAJ.CUENTA, FPA.CUENTA, 
           #T.IDTERCERO, #T.CCOSTO, #T.CNSFACJ, LEFT(#T.AREAPRESTACION,10), FPA.DESCRIPCION, 
           #T.CODCAJA, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #THD.NUMERODOCUMENTO, FPA.GENCHEQUE, #T.CODUNG, #T.CODPRG  
   END  
   END  
   
   PRINT 'Colocando Estado de CONTABILIZADA en 1 a FCJ'  
   IF LEFT(@NROCOMPROBANTE,2)<>'IX'  
   BEGIN  
      UPDATE FCJ SET CONTABILIZADA=1, NROCOMPROBANTE=@NROCOMPROBANTE, MARCACONT=0  
      FROM #T WHERE FCJ.CNSFACJ=#T.CNSFACJ AND FCJ.CODCAJA=#T.CODCAJA  
   END  
  
   EXEC SPK_REVISAR_COMPROBANTE @COMPANIA,@NROCOMPROBANTE  
   EXEC SPK_SUMA_DBCR @NROCOMPROBANTE  
   
   /* CONFIRMACION AUTOMATICA DEL COMPROBANTE DE CAJA */
   IF (SELECT DBO.FNK_VALORVARIABLE('CONFIRCONT_CAJA_ATM') ) = 'SI'
   BEGIN
      EXEC SPK_NC_CONFIRMAR_CONTAB @NROCOMPROBANTE, @USUARIO, @COMPANIA, @SEDE, @SYS_COMPUTERNAME, @ANO, @MES, 'CAJA', @NOREFERENCIA, 'CONTABILIZAR'
   END

   DROP TABLE #T  
   DROP TABLE #TH  
   DROP TABLE #THD  
END

