IF EXISTS (SELECT name FROM sysobjects 
   WHERE NAME = 'SPK_BORRAPAGO' AND type = 'P')
   DROP PROCEDURE SPK_BORRAPAGO

GO
CREATE PROCEDURE DBO.SPK_BORRAPAGO
@CNSFPAG VARCHAR(20)
WITH ENCRYPTION
AS                
DECLARE @CNSCXC       VARCHAR(20)    
DECLARE @N_FACTURA    VARCHAR(16)  
DECLARE @ITEM         SMALLINT
DECLARE @CLASE        VARCHAR(1)
DECLARE @CNSGLO       VARCHAR(20)
DECLARE @SINPAGO      SMALLINT
DECLARE @TIPOGLOSA VARCHAR(1)
BEGIN
   DECLARE PAGD_CURSOR CURSOR FOR    
   SELECT CNSCXC, N_FACTURA, ITEM, TIPOGLOSA, SINPAGO, CLASE, CNSGLO
   FROM   FPAGD    
   WHERE  CNSFPAG = @CNSFPAG  
   AND    CERRADO = 0    
   --AND    CLASEPAG = 'P'   
   OPEN PAGD_CURSOR    
   FETCH NEXT FROM PAGD_CURSOR    
   INTO @CNSCXC, @N_FACTURA, @ITEM, @TIPOGLOSA, @SINPAGO, @CLASE, @CNSGLO
   WHILE @@FETCH_STATUS = 0    
   BEGIN           
      IF @CLASE = 'G'
      BEGIN
         UPDATE FCXCDV SET MARCAPAGO = 0
         WHERE  CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA AND TIPO = 'G' 
         AND    CNSGLO = @CNSGLO 
      END
      ELSE
      BEGIN
         UPDATE FCXCDV SET MARCAPAGO = 0
         WHERE  CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA AND TIPO = 'F' 
      END

      FETCH NEXT FROM PAGD_CURSOR    
      INTO @CNSCXC, @N_FACTURA, @ITEM, @TIPOGLOSA, @SINPAGO, @CLASE, @CNSGLO
   END    
   CLOSE PAGD_CURSOR    
   DEALLOCATE PAGD_CURSOR    
   DELETE FROM FPAGDI WHERE CNSFPAG = @CNSFPAG
   DELETE FROM FPAGD WHERE CNSFPAG = @CNSFPAG
   EXEC SPK_FPAG @CNSFPAG
END


