CREATE OR ALTER PROCEDURE DBO.SPK_CONTAB_MASIVA
@ANO              VARCHAR(4),
@MES              INT,
@COMPANIA         VARCHAR(2),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@SEDE             VARCHAR(5),
@PROCEDENCIA      VARCHAR(20),
@NROCOMPROBANTE   VARCHAR(20),
@REFERENCIA2      VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @CNS VARCHAR(20)
DECLARE @N_FACTURA     VARCHAR(20)
DECLARE @F_FACTURA     DATETIME
DECLARE @CNSFACJ       VARCHAR(20)
DECLARE @CODCAJA       VARCHAR(4)  
DECLARE @CLASE_FAC     VARCHAR(5)  
DECLARE @NROCOMPROBANTEDEST VARCHAR(20)
DECLARE @CONTABILIZADA INT
DECLARE @BANCO         VARCHAR(3)
DECLARE @SUCURSAL      VARCHAR(3)
DECLARE @CTA_BCO       VARCHAR(20)
DECLARE @ITEM          INT
BEGIN
 IF @PROCEDENCIA='FACTURA'
 BEGIN
    DECLARE CUR_CONTAB CURSOR FOR
    SELECT CNSFCT, N_FACTURA, F_FACTURA
    FROM   FTR 
    WHERE YEAR(F_FACTURA) = CAST(@ANO AS INT) 
    AND   MONTH(F_FACTURA)= @MES 
    AND   MARCACONT       = 1 
    AND   (CONTABILIZADA  = 0 OR CONTABILIZADA IS NULL)
    ORDER BY N_FACTURA
    
    OPEN CUR_CONTAB
    
    FETCH NEXT FROM CUR_CONTAB
    INTO @CNS, @N_FACTURA, @F_FACTURA
    WHILE @@FETCH_STATUS = 0 
    BEGIN   
       print 'CONTAB FACTURA NO.='+@N_FACTURA
       --PRINT STR(@CONT)+' '+@CNS+' '+@N_FACTURA+' '+CAST(@F_FACTURA AS VARCHAR(20))
       EXEC SPK_NC_CONTAB_FTR @N_FACTURA,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,@SEDE,@NROCOMPROBANTE
       FETCH NEXT FROM CUR_CONTAB
       INTO @CNS, @N_FACTURA, @F_FACTURA
    END
    CLOSE CUR_CONTAB
    DEALLOCATE CUR_CONTAB
 END
 ELSE
 IF @PROCEDENCIA='CAJA'
 BEGIN
   PRINT 'Caja...'
   --EXEC SPK_CONTAB_MASIVA '2004','4','01','KRYSTALOS','JEFE-SISTEMAS','00001',10,'CAJA'
   DECLARE CUR_CONTAB CURSOR FOR
   SELECT CNSFACJ, CODCAJA, FECHA, CLASE_FAC
   FROM FCJ
   WHERE YEAR(FECHA)=CAST(@ANO AS INT) AND MONTH(FECHA)=@MES AND MARCACONT=1 AND CODCAJA=@REFERENCIA2
   ORDER BY CODCAJA,FECHA,CNSFACJ
    
   OPEN CUR_CONTAB
    
   FETCH NEXT FROM CUR_CONTAB
   INTO @CNSFACJ, @CODCAJA, @F_FACTURA, @CLASE_FAC
    
   WHILE @@FETCH_STATUS = 0 
   BEGIN   
    --PRINT STR(@CONT)+' '+@CLASE_FAC+' : '+@CNSFACJ+' '+@CODCAJA+' '+@USUARIO+' '+@SYS_COMPUTERNAME+' '+@COMPANIA+' '+@SEDE
    IF @CLASE_FAC='COBRO'
      EXEC SPK_NC_CONTAB_CAJA_ING @CNSFACJ, @CODCAJA, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @SEDE, @NROCOMPROBANTE
      ELSE
      IF @CLASE_FAC='PAGO'
      EXEC SPK_NC_CONTAB_CAJA_EGR @CNSFACJ, @CODCAJA, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @SEDE, @NROCOMPROBANTE
	
      FETCH NEXT FROM CUR_CONTAB
      INTO @CNSFACJ, @CODCAJA, @F_FACTURA, @CLASE_FAC
    END
   CLOSE CUR_CONTAB
   DEALLOCATE CUR_CONTAB
 END
 ELSE
 IF @PROCEDENCIA='CXP'
 BEGIN
   PRINT 'CXP'
   DECLARE CUR_CONTAB CURSOR FOR
   SELECT CNSFCXP, NOREFERENCIA, F_FACTURAREF  
   FROM FCXP
   WHERE YEAR(F_FACTURAREF)=CAST(@ANO AS INT) AND MONTH(F_FACTURAREF)=@MES AND MARCACONT=1
   ORDER BY CNSFCXP
 
  OPEN CUR_CONTAB
 
  FETCH NEXT FROM CUR_CONTAB
  INTO @CNS, @N_FACTURA, @F_FACTURA
  WHILE @@FETCH_STATUS = 0 
  BEGIN   
   --PRINT STR(@CONT)+' '+@CNS+' '+@N_FACTURA+' '+CAST(@F_FACTURA AS VARCHAR(20))
   EXEC SPK_NC_CONTAB_CXP @CNS,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   FETCH NEXT FROM CUR_CONTAB
   INTO @CNS, @N_FACTURA, @F_FACTURA
  END
  CLOSE CUR_CONTAB
  DEALLOCATE CUR_CONTAB
 END
 ELSE
 IF @PROCEDENCIA='CXC'
 BEGIN
    PRINT 'CXC' --RECAUDOS
    DECLARE CUR_CONTAB CURSOR FOR
    SELECT CNSFPAG, IDTERCERO, FECHA
    FROM FPAG
    WHERE YEAR(FECHA)=CAST(@ANO AS INT) AND MONTH(FECHA)=@MES AND MARCACONT=1
    ORDER BY CNSFPAG
    
    OPEN CUR_CONTAB
    
    FETCH NEXT FROM CUR_CONTAB
    INTO @CNS, @N_FACTURA, @F_FACTURA
    WHILE @@FETCH_STATUS = 0 
    BEGIN   
       --PRINT STR(@CONT)+' '+@CNS+' '+@N_FACTURA+' '+CAST(@F_FACTURA AS VARCHAR(20))
       EXEC SPK_NC_CONTAB_CXC @CNS,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
       FETCH NEXT FROM CUR_CONTAB
       INTO @CNS, @N_FACTURA, @F_FACTURA
    END
    CLOSE CUR_CONTAB
    DEALLOCATE CUR_CONTAB
 END
 ELSE
 IF @PROCEDENCIA='RGLO'
 BEGIN
    PRINT 'RGLO' --RESPUESTA GLOSAS
    DECLARE CUR_CONTAB CURSOR FOR
    SELECT CNSGLO, IDTERCERO, FECHARESP
    FROM FGLO
    WHERE YEAR(FECHARESP)=CAST(@ANO AS INT) AND MONTH(FECHARESP)=@MES AND MARCACONT=1
    ORDER BY CNSGLO
    
    OPEN CUR_CONTAB
    
    FETCH NEXT FROM CUR_CONTAB
    INTO @CNS, @N_FACTURA, @F_FACTURA
    WHILE @@FETCH_STATUS = 0 
    BEGIN   
       --PRINT STR(@CONT)+' '+@CNS+' '+@N_FACTURA+' '+CAST(@F_FACTURA AS VARCHAR(20))
       EXEC SPK_CONTAB_FGLO @CNS,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
       FETCH NEXT FROM CUR_CONTAB
       INTO @CNS, @N_FACTURA, @F_FACTURA
    END
    CLOSE CUR_CONTAB
    DEALLOCATE CUR_CONTAB
 END
 ELSE
 IF @PROCEDENCIA='INV'
 BEGIN
    PRINT 'INV'
    -- Procesa lo marcado (MARCACONT=1) por bodega.
    -- NO filtrar por FECHACONF: el front lista por FECHAMOV y FECHACONF suele ser NULL u otro mes.
    -- Si se filtra por FECHACONF, el cursor queda en 0 filas y parece "OK" sin contabilizar.
    DECLARE @CNT_INV INT
    SELECT @CNT_INV = COUNT(1)
    FROM   IMOV
    WHERE  LTRIM(RTRIM(IDBODEGA)) = LTRIM(RTRIM(@REFERENCIA2))
    AND    MARCACONT = 1
    AND    COALESCE(CONTABILIZADA, 0) = 0

    PRINT CONCAT('INV a procesar=', COALESCE(@CNT_INV, 0), ' bodega=', COALESCE(@REFERENCIA2, ''))

    DECLARE CUR_CONTAB CURSOR LOCAL FAST_FORWARD FOR
    SELECT CNSMOV, IDBODEGA, FECHAMOV
    FROM   IMOV
    WHERE  LTRIM(RTRIM(IDBODEGA)) = LTRIM(RTRIM(@REFERENCIA2))
    AND    MARCACONT = 1
    AND    COALESCE(CONTABILIZADA, 0) = 0
    ORDER BY CNSMOV
    
    OPEN CUR_CONTAB   
    FETCH NEXT FROM CUR_CONTAB
    INTO @CNS, @N_FACTURA, @F_FACTURA
    WHILE @@FETCH_STATUS = 0 
    BEGIN   
       PRINT CONCAT('CONTAB INV CNSMOV=', @CNS)
       EXEC SPK_NC_CONTAB_INV @CNS,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE, @NROCOMPROBANTE
       FETCH NEXT FROM CUR_CONTAB
       INTO @CNS, @N_FACTURA, @F_FACTURA
    END
    CLOSE CUR_CONTAB
    DEALLOCATE CUR_CONTAB
 END
 ELSE
 IF @PROCEDENCIA='NOTDBCR'
 BEGIN
    PRINT 'NOTDBCR'
    DECLARE CUR_CONTAB CURSOR FOR
    SELECT CNSFNOT, CLASE, F_NOTA, N_FACTURA
    FROM FNOT
    WHERE YEAR(F_NOTA)=CAST(@ANO AS INT) AND MONTH(F_NOTA)=@MES AND MARCACONT=1 AND CLASE=@REFERENCIA2
    ORDER BY CNSFNOT

    OPEN CUR_CONTAB
    SET @NROCOMPROBANTEDEST = @NROCOMPROBANTE
    FETCH NEXT FROM CUR_CONTAB
    INTO @CNS, @CLASE_FAC, @F_FACTURA, @N_FACTURA
    WHILE @@FETCH_STATUS = 0 
    BEGIN   
       --  PRINT STR(@CONT)+' - CNSFNOT= '+@CNS+' '+@N_FACTURA+' '+CAST(@F_FACTURA AS VARCHAR(20))
       --EXEC SPK_CONTAB_FNOT @CNS,@CLASE_FAC,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE   
       IF (SELECT LIBERAHADM FROM FNOT WHERE CNSFNOT=@CNS AND CLASE=@CLASE_FAC) = 1
       BEGIN
          PRINT 'INGRESE A LIBERA NOTA'
          SELECT @NROCOMPROBANTE = NROCOMPROBANTE, @CONTABILIZADA = CONTABILIZADA FROM FTR WHERE N_FACTURA = @N_FACTURA
          IF @CONTABILIZADA=0 OR @CONTABILIZADA IS NULL
          BEGIN
             PRINT 'VOY A SPK_CONTAB_FTR'
             EXEC SPK_NC_CONTAB_FTR @N_FACTURA, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE, ''
          END
          PRINT 'VOY A SPK_REVERSAR_MCP CON NROCOMPROBANTE='+@NROCOMPROBANTE+ '--- CON @NROCOMPROBANTEDEST='+@NROCOMPROBANTEDEST
          UPDATE FTR SET ESTADO='A', TIPOANULACION='NC', CONTABILIZADA=1 WHERE N_FACTURA=@N_FACTURA
          EXEC SPK_REVERSAR_MCP @NROCOMPROBANTE, @N_FACTURA, 'FNOT', @CNS, @CLASE_FAC, 
                                @COMPANIA, @SEDE, @USUARIO, @SYS_COMPUTERNAME, @NROCOMPROBANTEDEST
       END  
       ELSE
       BEGIN
          EXEC SPK_NC_CONTAB_FNOT @CNS, @CLASE_FAC, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @SEDE, @NROCOMPROBANTEDEST
       END
       FETCH NEXT FROM CUR_CONTAB
       INTO @CNS, @CLASE_FAC, @F_FACTURA, @N_FACTURA
    END
   CLOSE CUR_CONTAB
   DEALLOCATE CUR_CONTAB
 END
 ELSE
 IF @PROCEDENCIA='BMOV'
 BEGIN
  PRINT 'BMOV' --RESPUESTA GLOSAS
  DECLARE CUR_CONTAB CURSOR FOR
  SELECT BANCO, SUCURSAL, CTA_BCO, ITEM, FECHAOPERACION
  FROM BMOV
  WHERE YEAR(FECHAOPERACION)=CAST(@ANO AS INT) AND MONTH(FECHAOPERACION)=@MES AND MARCACONT=1
  ORDER BY BANCO, SUCURSAL, CTA_BCO, ITEM

  OPEN CUR_CONTAB

  FETCH NEXT FROM CUR_CONTAB
  INTO @BANCO, @SUCURSAL, @CTA_BCO, @ITEM, @F_FACTURA
  WHILE @@FETCH_STATUS = 0 
  BEGIN   
   EXEC SPK_NC_CONTAB_BMOV @BANCO, @SUCURSAL, @CTA_BCO, @ITEM, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, 
                        @SEDE, @NROCOMPROBANTE
   FETCH NEXT FROM CUR_CONTAB
   INTO @BANCO, @SUCURSAL, @CTA_BCO, @ITEM, @F_FACTURA
  END
  CLOSE CUR_CONTAB
  DEALLOCATE CUR_CONTAB
 END
 /*
 SPK PARA CUENTA CORRIENTE CONTABLIZACION DE PRESTACIONES 
 COMENTADO POR JJIMENEZ 28.02.2019
 */
 --ELSE
 --IF @PROCEDENCIA='HPRE'
 --BEGIN
 -- PRINT 'HPRE'
 -- DECLARE CUR_CONTAB CURSOR FOR
 -- SELECT NOPRESTACION, FECHA
 -- FROM HPRE
 -- WHERE YEAR(FECHA)=CAST(@ANO AS INT) AND MONTH(FECHA)=@MES AND MARCACONT=1
 -- ORDER BY FECHA, NOPRESTACION

 -- OPEN CUR_CONTAB

 -- FETCH NEXT FROM CUR_CONTAB
 -- INTO @CNS, @F_FACTURA
 -- WHILE @@FETCH_STATUS = 0 
 -- BEGIN   
 --  --PRINT STR(@CONT)+' '+@CNS+' '+@N_FACTURA+' '+CAST(@F_FACTURA AS VARCHAR(20))
 --  EXEC SPK_CONTAB_HPRE @CNS,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
 --  FETCH NEXT FROM CUR_CONTAB
 --  INTO @CNS, @F_FACTURA
 -- END
 -- CLOSE CUR_CONTAB
 -- DEALLOCATE CUR_CONTAB
 --END
END

