CREATE OR ALTER PROCEDURE DBO.SPK_ADDSERCAP
    @CNSFTR      VARCHAR(20),
    @N_CUOTA     INT,
    @IDTERCERO   VARCHAR(20),
    @IDPLAN      VARCHAR(6),
    @FECHAINI    DATETIME,
    @FECHAFIN    DATETIME,
    @PROCEDENCIA VARCHAR(4),
    @CLASEORDEN  VARCHAR(10) = '',
    @IDPESPECIAL VARCHAR(5) = '',
    @RIESGO      VARCHAR(20) = '',
    @NOADMISION  VARCHAR(20) = NULL,
    @IDSEDE      VARCHAR(6) = NULL
WITH ENCRYPTION
AS
DECLARE @N_FACTURA  VARCHAR(20)
        ,@COPAGOPROP BIT
BEGIN
    SELECT @N_FACTURA = N_FACTURA, @COPAGOPROP = COALESCE(COPAPROPIO, 0)
    FROM FTR
    WHERE CNSFCT = @CNSFTR

    PRINT 'Asignando Servicios a la Factura No. ' + @N_FACTURA + ' PROCEDENCIA ' + @PROCEDENCIA

    INSERT INTO FTRDC (
        CNSFTR, N_CUOTA, PROCEDENCIA, FECHA, NOADMISION, PACIENTE, NOPRESTACION, NOITEM,
        IDSERVICIO, IDAREA, IDPLAN, CCOSTO, PREFIJO, CANTIDAD, VALOR, VALORTOTAL,
        VLR_COPAGO, VLR_PAGCOMP, VALOREXCEDENTE, DESCUENTO, TIPOTERCERO, CUENTA,
        ENRECAUDOS, IDSEDE, TCOPAGO
    )
    SELECT @CNSFTR, @N_CUOTA, A.PROCEDENCIA, A.FECHA, A.NOADMISION, A.PACIENTE,
           A.NOPRESTACION, A.NOITEM, A.IDSERVICIO, A.IDAREA, A.IDPLAN, A.CCOSTO, A.PREFIJO,
           A.CANTIDAD, A.VALOR, A.VALORTOTAL,
           CASE WHEN DBO.FNK_VALORVARIABLE('SOLO_COPA_RECAUDADO') = 'SI'
                     AND A.VALORCOPAGO > 0 AND A.ENCAJA = 0 THEN 0
                ELSE A.VALORCOPAGO END,
           A.VALORPCOMP, A.VALOREXCEDENTE, A.DESCUENTO, A.TIPOTERCONTABLE, TTEC.CUENTA,
           0, A.IDSEDE,
           CASE
               WHEN A.PROCEDENCIA = 'SALUD' AND A.VALORCOPAGO > 0 THEN '01'
               WHEN A.PROCEDENCIA IN ('CIT', 'ONCO', 'APLIM')
                   THEN DBO.FNK_TRAE_TIPOCOPAGO(A.NOADMISION, 'CI')
               WHEN A.PROCEDENCIA = 'INV' THEN 'C'
               ELSE DBO.FNK_TRAE_TIPOCOPAGO(A.NOADMISION, 'CE')
           END
    FROM VWK_CARGOS_HADMAUTCIT A
    LEFT JOIN TTEC ON A.TIPOTERCONTABLE = TTEC.TIPO
    WHERE A.FECHA >= @FECHAINI
    AND A.FECHA < @FECHAFIN + 1
    AND ISNULL(A.IDPLAN, '') = @IDPLAN
    AND A.IDTERCEROCA = @IDTERCERO
    AND COALESCE(A.FACTURADA, 0) = 0
    AND ISNULL(A.PROCEDENCIA, '') = CASE WHEN @PROCEDENCIA = 'TODA' THEN ISNULL(A.PROCEDENCIA, '') ELSE @PROCEDENCIA END
    AND ISNULL(A.CLASEORDEN, '') = CASE WHEN @CLASEORDEN IN ('TODAS', '') THEN ISNULL(A.CLASEORDEN, '') ELSE @CLASEORDEN END
    AND ISNULL(A.IDPESPECIAL, '') = CASE WHEN @IDPESPECIAL = '' THEN ISNULL(A.IDPESPECIAL, '') ELSE @IDPESPECIAL END
    AND ISNULL(A.RIESGO, '') = CASE WHEN @RIESGO = '' THEN ISNULL(A.RIESGO, '') ELSE @RIESGO END
    AND ISNULL(A.NOADMISION, '') = CASE WHEN COALESCE(@NOADMISION, '') = '' THEN ISNULL(A.NOADMISION, '') ELSE @NOADMISION END
    AND ISNULL(A.IDSEDE, '') = CASE WHEN COALESCE(@IDSEDE, '') = '' THEN ISNULL(A.IDSEDE, '') ELSE @IDSEDE END
    AND A.IDSERVICIO NOT IN (
        SELECT DISTINCT IDSERVICIOGESTION
        FROM MES
        WHERE COALESCE(DBO.FNK_VALORVARIABLE('FTRDC_INCLUYEGESTION'), 'SI') = 'NO'
        AND IDSERVICIOGESTION IS NOT NULL
    )
    AND A.IDSERVICIO NOT IN (
        IIF(COALESCE(DBO.FNK_VALORVARIABLE('FTRDC_INCLUYEGESTION'), 'SI') = 'NO', 'GEST0001', '')
    )
    AND A.IDSERVICIO NOT IN (
        SELECT DISTINCT CODIGO
        FROM TGEN
        WHERE COALESCE(DBO.FNK_VALORVARIABLE('FTRDC_EXCUYSERPLAN'), 'NO') = 'SI'
        AND TGEN.TABLA = 'EXCUYSERPLAN'
        AND TGEN.CAMPO = A.IDPLAN
        AND TGEN.CODIGO = A.IDSERVICIO
    )
    AND NOT EXISTS (
        SELECT 1
        FROM FTRDC
        WHERE CNSFTR = @CNSFTR
        AND N_CUOTA = @N_CUOTA
        AND PROCEDENCIA = A.PROCEDENCIA
        AND NOADMISION = A.NOADMISION
        AND NOPRESTACION = A.NOPRESTACION
        AND NOITEM = A.NOITEM
    )

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'HADM'
    BEGIN
        PRINT 'Colocando el N_Factura en HADMF...' + @N_FACTURA + ' NO ADMISION ' + COALESCE(@NOADMISION, '')

        INSERT INTO HADMF (NOADMISION, N_FACTURA, CNSFCT, ESTADO, N_FACTURAR, ANEXOUNICO, IDTERCERO, IDPLAN, DESCRIPCION, ITFC, CNSITFC)
        SELECT DISTINCT A.NOADMISION, @N_FACTURA, @CNSFTR, 'P', NULL, NULL, @IDTERCERO, @IDPLAN, 'FACTURA CAPITADA', 0, NULL
        FROM HPRED
        INNER JOIN VWK_CARGOS_HADMAUTCIT A ON HPRED.NOPRESTACION = A.NOPRESTACION AND HPRED.NOITEM = A.NOITEM
        WHERE A.FECHA >= @FECHAINI
        AND NOT EXISTS (
            SELECT 1 FROM HADMF
            WHERE A.NOADMISION = HADMF.NOADMISION AND HADMF.N_FACTURA = @N_FACTURA
        )
        AND A.FECHA < @FECHAFIN + 1
        AND A.IDPLAN = @IDPLAN
        AND A.IDTERCEROCA = @IDTERCERO
        AND A.PROCEDENCIA = 'HADM'
        AND COALESCE(A.FACTURADA, 0) = 0
        AND A.NOADMISION = CASE WHEN COALESCE(@NOADMISION, '') = '' THEN A.NOADMISION ELSE @NOADMISION END
        AND A.IDSEDE = CASE WHEN COALESCE(@IDSEDE, '') = '' THEN A.IDSEDE ELSE @IDSEDE END

        PRINT 'Asignando No. de Factura a las Prestaciones...'
        UPDATE HPRED SET FACTURADA = 1, N_FACTURA = @N_FACTURA
        FROM HPRED
        INNER JOIN VWK_CARGOS_HADMAUTCIT A ON HPRED.NOPRESTACION = A.NOPRESTACION AND HPRED.NOITEM = A.NOITEM
        WHERE A.FECHA >= @FECHAINI
        AND A.FECHA < @FECHAFIN + 1
        AND A.IDPLAN = @IDPLAN
        AND A.IDTERCEROCA = @IDTERCERO
        AND A.PROCEDENCIA = 'HADM'
        AND COALESCE(A.FACTURADA, 0) = 0
        AND A.NOADMISION = CASE WHEN COALESCE(@NOADMISION, '') = '' THEN A.NOADMISION ELSE @NOADMISION END
        AND A.IDSEDE = CASE WHEN COALESCE(@IDSEDE, '') = '' THEN A.IDSEDE ELSE @IDSEDE END
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'AUT'
    BEGIN
        PRINT 'Asignando No. de Factura a las Autorizaciones...'
        UPDATE AUTD SET FACTURADA = 1, N_FACTURA = @N_FACTURA
        FROM AUTD
        INNER JOIN FTRDC A ON AUTD.IDAUT = A.NOPRESTACION AND AUTD.NO_ITEM = A.NOITEM
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'AUT'

        UPDATE AUT SET FACTURADA = 1, N_FACTURA = @N_FACTURA
        FROM AUT
        INNER JOIN FTRDC A ON AUT.IDAUT = A.NOPRESTACION
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'AUT'
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'CIT'
    BEGIN
        PRINT 'Asignando No. de Factura a las Citas...'
        UPDATE CIT SET FACTURADA = 1, N_FACTURA = @N_FACTURA
        FROM CIT
        INNER JOIN FTRDC A ON CIT.CONSECUTIVO = A.NOPRESTACION
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'CIT'
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'ONCO'
    BEGIN
        PRINT 'Asignando No. de Factura a Oncolog�a...'
        UPDATE HCATDIMOV SET FACTURADA = 1, N_FACTURA = @N_FACTURA
        FROM HCATDIMOV
        INNER JOIN FTRDC A ON HCATDIMOV.CONSECUTIVOCIT = A.NOADMISION AND HCATDIMOV.ID = A.NOITEM
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'ONCO'

        UPDATE CIT SET FACTURADA = 1, N_FACTURA = @N_FACTURA
        FROM CIT
        INNER JOIN FTRDC A ON CIT.CONSECUTIVO = A.NOPRESTACION
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'ONCO'
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'APLIM'
    BEGIN
        PRINT 'Asignando No. de Factura a Aplicaci�n de Medicamentos...'
        UPDATE CIT SET FACTURADA = 1, N_FACTURA = @N_FACTURA
        FROM CIT
        INNER JOIN FTRDC A ON CIT.CONSECUTIVO = A.NOPRESTACION
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'APLIM'
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'INV'
    BEGIN
        PRINT 'Asignando No. de Factura a los Movimientos de Inventario...'
        UPDATE IMOV
        SET FACTURADA = 1,
            N_FACTURA = @N_FACTURA,
            NODOCUMENTO = @N_FACTURA,
            MARCACONT = 0,
            CNSITFC = @CNSFTR
        FROM IMOV
        INNER JOIN (
            SELECT DISTINCT COALESCE(A.NOPRESTACION, A.NOADMISION) AS CNSMOV
            FROM FTRDC A
            WHERE A.CNSFTR = @CNSFTR
              AND A.N_CUOTA = @N_CUOTA
              AND A.PROCEDENCIA = 'INV'
        ) X ON IMOV.CNSMOV = X.CNSMOV
        WHERE COALESCE(IMOV.FACTURADA, 0) = 0
    END

    /* Copago propio: moderadora en cero en relaci�n y cabecera (RIPS / DIAN) */
    IF @COPAGOPROP = 1
    BEGIN
        UPDATE FTRDC
        SET VLR_COPAGO = 0
        WHERE CNSFTR = @CNSFTR
          AND N_CUOTA = @N_CUOTA
          AND PROCEDENCIA <> 'HADM'
          AND (
                COALESCE(TCOPAGO, '') = '02'
                OR EXISTS (
                    SELECT 1
                    FROM MOCCD
                    WHERE TIPODEPAGO = 'Moderadora'
                      AND MOCCD.VALOR = FTRDC.VLR_COPAGO
                )
              );
    END

    EXEC DBO.SPK_TOTALFACTURFIN @N_FACTURA = @N_FACTURA;
END

