CREATE OR ALTER  PROCEDURE DBO.SPK_NC_CONTAB_BMOV
        @BANCO            VARCHAR(3), 
        @SUCURSAL         VARCHAR(2), 
        @CTA_BCO          VARCHAR(40), 
        @ITEM             INT, 
        @USUARIO          VARCHAR(12),
        @SYS_COMPUTERNAME VARCHAR(254),
        @COMPANIA         VARCHAR(2), 
        @SEDE             VARCHAR(5),
        @NROCOMPROBANTE   VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @COM              VARCHAR(6)
DECLARE @NOREFERENCIA     VARCHAR(20)
DECLARE @ANO              VARCHAR(4)
DECLARE @MES              INT
DECLARE @IDMODELOCONT     VARCHAR(2)
DECLARE @TIPOTERCONTABLE  VARCHAR(10) 
DECLARE @PREFIJO_USCXS    VARCHAR(10)
DECLARE @FECHATRA         DATETIME
DECLARE @TIPO             VARCHAR(2)
DECLARE @NOMOPERACION     VARCHAR(30)
DECLARE @CUENTA_OFIN      VARCHAR(16)
DECLARE @ESTADO           VARCHAR(1)
DECLARE @FECHAOK          DATETIME
DECLARE @CUENTA_OFIN2      VARCHAR(16)

BEGIN
 SELECT * INTO #T FROM BMOV   WHERE BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND CTA_BCO=@CTA_BCO AND ITEM=@ITEM
 SELECT * INTO #TH FROM BMOVD WHERE BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND CTA_BCO=@CTA_BCO AND ITEM=@ITEM --AND RECAUDO=0
 
 SELECT @FECHAOK = FECHAOK FROM #T
 SELECT @CUENTA_OFIN2=CUENTA from #TH  WHERE BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND CTA_BCO=@CTA_BCO AND ITEM=@ITEM

 IF ISNULL(@FECHAOK,'') = ''
 BEGIN
    SELECT   @ANO             = YEAR(#T.FECHAOPERACION),
             @MES             = MONTH(#T.FECHAOPERACION),
             @FECHATRA        = #T.FECHAOPERACION,
             @TIPO            = OFIN.TIPO,
             @NOMOPERACION    = OFIN.NOMOPERACION,
             @COM             = OFIN.COMPROBANTE, 
             @CUENTA_OFIN     = OFIN.CUENTA,
             @ESTADO          = #T.ESTADO
    FROM #T LEFT JOIN
         OFIN ON #T.IDOPERACION = OFIN.IDOPERACION
 END 
 ELSE
 BEGIN
    SELECT   @ANO             = YEAR(#T.FECHAOK),
             @MES             = MONTH(#T.FECHAOK),
             @FECHATRA        = #T.FECHAOPERACION,
             @TIPO            = OFIN.TIPO,
             @NOMOPERACION    = OFIN.NOMOPERACION,
             @COM             = OFIN.COMPROBANTE, 
             @CUENTA_OFIN     = OFIN.CUENTA,
             @ESTADO          = #T.ESTADO
    FROM #T LEFT JOIN
         OFIN ON #T.IDOPERACION = OFIN.IDOPERACION    
 END
 
   IF COALESCE(@CUENTA_OFIN,'')=''
      SET @CUENTA_OFIN=@CUENTA_OFIN2

   IF COALESCE(@CUENTA_OFIN,'')=''
      SELECT TOP 1 @CUENTA_OFIN=CUENTA
      FROM (SELECT DISTINCT TTEC.CUENTA, TTEC.DETALLE
            FROM TTEC INNER JOIN
                 PPT ON TTEC.TIPO = PPT.TIPOTERCONTABLE
            WHERE PPT.IDTERCERO=(SELECT TOP 1 IDTERCERO FROM #TH GROUP BY IDTERCERO ORDER BY COUNT(*) DESC)) X
      GROUP BY CUENTA, DETALLE

   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)
   BEGIN
      RAISERROR('Periodo Contable NO Existe', 16, 1)
      RETURN
   END
   IF (SELECT COALESCE(CERRADO,0) FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES) = 1
   BEGIN
      RAISERROR('Periodo Contable Cerrado', 16, 1)
      RETURN
   END


 SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
 IF ISNULL(@NROCOMPROBANTE,'') = '' -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
 BEGIN
    SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
    EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
    SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
    PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD

    IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
    BEGIN
       SELECT @COM = RTRIM(LTRIM(COMMS.COMPROBANTE)) 
       FROM   COMMS INNER JOIN #T ON #T.IDOPERACION = COMMS.TIPO
       WHERE  COMMS.IDSEDE = @SEDE 
       AND    COMMS.CLASE  = 'BMOV' 
    END 
    ELSE
    BEGIN
       SELECT @COM = OFIN.COMPROBANTE
       FROM #T LEFT JOIN OFIN ON #T.IDOPERACION = OFIN.IDOPERACION    
    END

    IF @COM IS NULL OR @COM =''
       SET @COM=DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT')
    IF @COM IS NULL OR @COM =''
       SET @COM='IX'

    SET @PREFIJO_USCXS='@COM'+@COM
    SET @NOREFERENCIA=SPACE(20)
    EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
    SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
    PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
    PRINT @NROCOMPROBANTE

    PRINT 'Comprobante Contable (MCPE)'
    INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                     TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                     COMPROBANTE, IDTERCERO)
    SELECT @NROCOMPROBANTE, @COMPANIA, 'BMOV', @NOREFERENCIA, @ANO, @MES, 
           CASE COALESCE(@FECHAOK,'') WHEN  '' THEN CAST(STR(DAY(#T.FECHAOPERACION))+'/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME)
                                      ELSE CAST(STR(DAY(#T.FECHAOK))+'/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME)
           END, 0, 0,
           BANCO+SUCURSAL+CTA_BCO, LTRIM(RTRIM(STR(ITEM))), @USUARIO, 
           DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, #T.DESCRIPCION, @SEDE, 0, @COM, 
           (SELECT TOP 1 IDTERCERO FROM #TH GROUP BY IDTERCERO ORDER BY COUNT(*) DESC)
    FROM #T  
 END
 --------------------------------
 IF (SELECT COUNT(*) FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)>0
 BEGIN
    UPDATE MCP 
    SET OBSERVACION = #T.DESCRIPCION, 
        IDTERCERO   = (SELECT TOP 1 IDTERCERO FROM #TH GROUP BY IDTERCERO ORDER BY COUNT(*) DESC)
    FROM #T 
    WHERE MCP.NROCOMPROBANTE=@NROCOMPROBANTE AND MCP.PROCEDENCIA='BMOV' AND 
          MCP.REFERENCIA1=#T.BANCO+#T.SUCURSAL+#T.CTA_BCO AND MCP.REFERENCIA2=LTRIM(RTRIM(STR(#T.ITEM)))
    INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                      REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                      RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
    SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                     REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                     RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
    FROM   MCP
    WHERE  NROCOMPROBANTE = @NROCOMPROBANTE
    --se borran de mcp, mch
    DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
    DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE   
 END
 DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE

 PRINT 'ESTADO: '+ISNULL(@ESTADO,'')

 IF @ESTADO = 'A'
 BEGIN
    UPDATE MCP SET ANULADO = 1, ESTADO = 2, TOTALDEBITO=0, TOTALCREDITO=0 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
    UPDATE BMOV SET CONTABILIZADA=1, MARCACONT=0, NROCOMPROBANTE=@NROCOMPROBANTE 
    WHERE BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND CTA_BCO=@CTA_BCO AND ITEM=@ITEM
    DROP TABLE #T
    DROP TABLE #TH
    RETURN
 END

 IF @TIPO='DB'
 BEGIN
    PRINT 'El Movimiento es de Ingreso'
    PRINT 'Contabilizando MCH DB...'
    INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, 
                     PREFIJO, ESTADO, PROCESO, GENERA, CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
    SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', BCT.COD_CONTABLE, #TH.IDTERCERO, COALESCE(#TH.CCOSTO,'') AS CCOSTO, 
           @NOMOPERACION+', '+BCO.DESCRIPCION+', CTA: '+BCT.CTA_BCO, #TH.VLRITEM, 
           #TH.NODOCUMENTO, #TH.BANCODOC, NULL, #TH.ITEM, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, 
           '' AS PREFIJO, 1, 'BMOV_DB', 'Movimiento','S', 
           CASE WHEN #TH.NODOCUMENTO IS NULL THEN 'SIN_DOCUMENTO' ELSE #TH.NODOCUMENTO END, 
           DBO.FNK_FECHA_SIN_HORA(#T.FECHAOPERACION), DBO.FNK_FECHA_SIN_HORA(#T.FECHAOPERACION),
           'BMOV', #TH.BANCO+#TH.SUCURSAL+#TH.CTA_BCO, #T.CODUNG, #T.CODPRG
    FROM   #TH LEFT JOIN  BCT ON #TH.BANCO    = BCT.BANCO 
                             AND #TH.SUCURSAL = BCT.SUCURSAL 
                             AND #TH.CTA_BCO  = BCT.CTA_BCO 
               LEFT JOIN  BCO ON BCT.BANCO    = BCO.BANCO,
           #T
    WHERE  #TH.VLRITEM<>0 

    PRINT 'Contabilizando MCH CR...'
    INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, 
                     PREFIJO, ESTADO, PROCESO, GENERA, CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
    SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', @CUENTA_OFIN, #TH.IDTERCERO, COALESCE(#TH.CCOSTO,'') AS CCOSTO, 
           @NOMOPERACION+', '+RTRIM(TER.RAZONSOCIAL), #TH.VLRITEM, 
           #TH.NODOCUMENTO, #TH.BANCODOC, NULL, #TH.ITEM, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, 
           '' AS PREFIJO, 1, 'BMOV_CR', 'Movimiento','S', 
           CASE WHEN #TH.NODOCUMENTO IS NULL THEN '' ELSE #TH.NODOCUMENTO END, 
           DBO.FNK_FECHA_SIN_HORA(#T.FECHAOPERACION), DBO.FNK_FECHA_SIN_HORA(#T.FECHAOPERACION),
           'BMOV', #TH.BANCO+#TH.SUCURSAL+#TH.CTA_BCO, #T.CODUNG, #T.CODPRG
    FROM   #TH LEFT JOIN TER ON #TH.IDTERCERO = TER.IDTERCERO,
           #T
    WHERE  #TH.VLRITEM<>0
 END
 ELSE
 BEGIN
    PRINT 'Contabilizando MCH DB...'
    INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, 
                     PREFIJO, ESTADO, PROCESO, GENERA, CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
    SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', @CUENTA_OFIN, #TH.IDTERCERO, COALESCE(#TH.CCOSTO,'') AS CCOSTO, 
           @NOMOPERACION+', '+RTRIM(TER.RAZONSOCIAL), #TH.VLRITEM, 
           #TH.NODOCUMENTO, #TH.BANCODOC, NULL, #TH.ITEM, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, 
           '' AS PREFIJO, 1, 'BMOV_DB', 'Movimiento','S', 
           CASE WHEN #TH.NODOCUMENTO IS NULL THEN '' ELSE #TH.NODOCUMENTO END, 
           DBO.FNK_FECHA_SIN_HORA(#T.FECHAOPERACION), DBO.FNK_FECHA_SIN_HORA(#T.FECHAOPERACION),
           'BMOV', #TH.BANCO+#TH.SUCURSAL+#TH.CTA_BCO, #T.CODUNG, #T.CODPRG
    FROM   #TH LEFT JOIN TER ON #TH.IDTERCERO = TER.IDTERCERO,
           #T
    WHERE  #TH.VLRITEM<>0

    PRINT 'Contabilizando MCH CR...'
    INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, 
                     PREFIJO, ESTADO, PROCESO, GENERA, CLASECONT, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
    SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', BCT.COD_CONTABLE, #TH.IDTERCERO, '' AS CCOSTO, 
           @NOMOPERACION+', '+BCO.DESCRIPCION+', CTA: '+BCT.CTA_BCO, #TH.VLRITEM, 
           #TH.NODOCUMENTO, #TH.BANCODOC, NULL, #TH.ITEM, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, 
           '' AS PREFIJO, 1, 'BMOV_CR', 'Movimiento','S', 
           CASE WHEN #TH.NODOCUMENTO IS NULL THEN '' ELSE #TH.NODOCUMENTO END, 
           DBO.FNK_FECHA_SIN_HORA(#T.FECHAOPERACION), DBO.FNK_FECHA_SIN_HORA(#T.FECHAOPERACION),
           'BMOV', #TH.BANCO+#TH.SUCURSAL+#TH.CTA_BCO, #T.CODUNG, #T.CODPRG
    FROM   #TH LEFT JOIN BCT ON #TH.BANCO=BCT.BANCO 
                            AND #TH.SUCURSAL=BCT.SUCURSAL 
                            AND #TH.CTA_BCO=BCT.CTA_BCO 
               LEFT JOIN BCO ON BCT.BANCO=BCO.BANCO,
           #T
    WHERE  #TH.VLRITEM<>0 
 END
 
 EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME 
 EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''
 DROP TABLE #T
 DROP TABLE #TH

END

