CREATE OR ALTER PROCEDURE DBO.SPK_RECALCULO_BANCOS  
@BANCO    VARCHAR(3),
@SUCURSAL VARCHAR(2),
@CTA_BCO  VARCHAR(40)
WITH ENCRYPTION
AS  
DECLARE @TOTALDB DECIMAL(14,2)
DECLARE @TOTALCR DECIMAL(14,2)
DECLARE @TARCRED BIT
DECLARE @CUPO DECIMAL(14,2)
BEGIN  

   IF EXISTS(SELECT * FROM BMOV WHERE ESTADO='C' AND PROCEDENCIA='CAJA' AND BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND CTA_BCO=@CTA_BCO)
   BEGIN
      PRINT 'AJUSTE DE ESTADOS MOVIMIENTOS GENERADOS EN CAJA'
      UPDATE BMOV SET ESTADO='O' WHERE ESTADO='C' AND PROCEDENCIA='CAJA' AND BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND CTA_BCO=@CTA_BCO
   END
   SELECT @TARCRED=COALESCE(TARCRED,0),@CUPO=CASE WHEN COALESCE(TARCRED,0)=1 THEN CUPODISP ELSE 0 END 
   FROM BCT WHERE BANCO=@BANCO AND SUCURSAL=@SUCURSAL AND CTA_BCO=@CTA_BCO

   SELECT @TOTALDB = SUM(VLROPERACION) 
   FROM BMOV INNER JOIN  OFIN ON BMOV.IDOPERACION=OFIN.IDOPERACION
   WHERE ESTADO = 'O'  
   AND BMOV.BANCO = @BANCO 
   AND BMOV.SUCURSAL = @SUCURSAL 
   AND BMOV.CTA_BCO = @CTA_BCO   
   AND OFIN.TIPO = 'DB'   
   
   SELECT @TOTALCR = SUM(VLROPERACION) 
   FROM BMOV INNER JOIN  OFIN ON BMOV.IDOPERACION=OFIN.IDOPERACION
   WHERE ESTADO = 'O'  
   AND BMOV.BANCO = @BANCO 
   AND BMOV.SUCURSAL = @SUCURSAL 
   AND BMOV.CTA_BCO = @CTA_BCO  
   AND OFIN.TIPO = 'CR'   
    
   IF COALESCE(@TOTALCR,0)=0 
   BEGIN
      SELECT @TOTALCR = 0  
   END
   IF COALESCE(@TOTALDB,0)=0 
   BEGIN 
      SELECT @TOTALDB = 0  
   END 
   PRINT 'DEBITO='+STR(@TOTALDB)  
   PRINT 'CREDITO='+STR(@TOTALCR) 
   PRINT 'VALOR SALDO'+STR(@TOTALDB-@TOTALCR) 
    
   UPDATE BCT SET SALDO =CASE WHEN @TARCRED=0 THEN  @TOTALDB - @TOTALCR  ELSE  ((@CUPO+ @TOTALDB) - @TOTALCR) END
   WHERE  BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO   

END

