CREATE OR ALTER PROCEDURE DBO.SPK_AJUSTE_FCXCDV_NC 
@ITEM          INT,
@CONCEPTO      VARCHAR(20),
@OBSERVACION   VARCHAR(512),
@VALOR         DECIMAL(14,2),
@COMPANIA      VARCHAR(2),  
@IDSEDE        VARCHAR(6),
@USUARIO       VARCHAR(20),
@FECHA         DATETIME
WITH ENCRYPTION
AS  
DECLARE @CNSFNOT VARCHAR(20)
DECLARE @IDTERCERO VARCHAR(20)
DECLARE @SALDONETO DECIMAL(14,2)
DECLARE @CNSCXC        VARCHAR(20)
DECLARE @N_FACTURA     VARCHAR(20)
DECLARE @CNSGLOSA      VARCHAR(20)
DECLARE @DESCONCEPTO   VARCHAR(80)
DECLARE @SYS_COMPUTERNAME VARCHAR(255)
DECLARE @CNSRPDX   VARCHAR(20)
DECLARE @TIPO   VARCHAR(1)
BEGIN  
   PRINT 'REVISO DATOS'
   IF @VALOR<=0
   BEGIN
      RETURN
   END
   SELECT @CNSCXC=CNSCXC,@N_fACTURA=N_FACTURA,@CNSGLOSA=CNSGLO,@SALDONETO=SALDONETO,@TIPO=TIPO FROM FCXCDV WHERE ITEM =@ITEM

   -- Ajuste NC desde Vencimientos: solo ítems C (cuota/saldo) o G (glosa) con saldo.
   IF @CNSCXC IS NULL OR @N_FACTURA IS NULL
   BEGIN
      RAISERROR('No se encontró el ítem de cartera (FCXCDV)', 16, 1)
      RETURN
   END
   IF @TIPO NOT IN ('C', 'G')
   BEGIN
      RAISERROR('Solo se permite nota crédito sobre ítems de cartera tipo C o G', 16, 1)
      RETURN
   END
   IF COALESCE(@SALDONETO, 0) <= 0
   BEGIN
      RAISERROR('El ítem de cartera no tiene saldo neto para ajustar', 16, 1)
      RETURN
   END

   SELECT @IDTERCERO=IDTERCERO,@SYS_COMPUTERNAME=HOST_NAME() FROM FTR WHERE N_fACTURA=@N_FACTURA
   SELECT @DESCONCEPTO=DESCRIPCION FROM CPNT WHERE CODIGO=@CONCEPTO
   IF @VALOR>@SALDONETO
   BEGIN
      RETURN
   END
   IF @FECHA IS NULL
      SET @FECHA=GETDATE()

   EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE,'@FNOTC', @CNSFNOT OUTPUT  
   SELECT @CNSFNOT = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFNOT))+LTRIM(RTRIM(@CNSFNOT)),SPACE(1),0)      
   --SE INSERTAN LOS DATOS DE LA NOTA DESDE LA CONCILIACION
   PRINT 'NUMERO DE LA NOTA......'+ @CNSFNOT
   INSERT INTO FNOT(CNSFNOT, CLASE, N_FACTURA, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                     MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA,
                     USUARIO, CNSCXC, CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU,
                     RAZONANU, PROCEDENCIA, CNSGLO, APLICADAA,LIBERAHADM, 
                     CONCEPTO, IDCONCEPTO )  
   SELECT @CNSFNOT, 'C', @N_FACTURA, @IDTERCERO, @FECHA, @VALOR, @OBSERVACION, 0, 0, 0, NULL, 0,
          @COMPANIA, @USUARIO, @CNSCXC, 0, 'O', NULL, NULL, NULL, NULL,
          'AJUSTE', @CNSGLOSA, @TIPO, 0, 0, @CONCEPTO
   -- INSERTANDO FNOTD
         
   INSERT INTO FNOTD(CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
                     VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION)
   SELECT @CNSFNOT, 'C', 1, @TIPO,@CONCEPTO , @DESCONCEPTO, 1,
          @VALOR, @VALOR, @COMPANIA, @USUARIO, @OBSERVACION

   PRINT 'Cierro la nota'
   SELECT @CNSRPDX = 'INTERNO'
   EXEC SPK_NOTASCXC @CNSFNOT, 'C', @CNSRPDX , @IDSEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME   

   EXEC SPK_RELIQUIDA_FTR @CNSCXC,@N_fACTURA
END

