CREATE OR ALTER  PROCEDURE DBO.SPK_PAGOSCAJA_AUT   
@NOAUT            VARCHAR(16),  
@SYS_COMPUTERNAME VARCHAR(254),  
@COMPANIA         VARCHAR(2),  
@SEDE             VARCHAR(5),   
@USUARIO          VARCHAR(12),  
@PART             SMALLINT  
WITH ENCRYPTION
AS    
DECLARE @OK         SMALLINT  
DECLARE @OK1        SMALLINT  
DECLARE @PREFCAJA   SMALLINT  
DECLARE @CODCAJA    VARCHAR(4)  
DECLARE @NVOCONSEC  VARCHAR(20)  
DECLARE @DATO       VARCHAR(80)  
DECLARE @CNSACJ     VARCHAR(20)  
DECLARE @TIPOCOPAGO VARCHAR(1)  
DECLARE @PREFIJO    VARCHAR(6)
DECLARE @VALORAUX   DECIMAL(14,2)
DECLARE @IDAUT      VARCHAR(20)
DECLARE @IDPLAN VARCHAR(20)
BEGIN  
   SELECT   @OK = ISNULL(COUNT(*),0) FROM AUT WHERE NOAUT = @NOAUT AND GENEROCAJA = 1  
     
   IF @OK > 0  
      RETURN  
     
   SELECT @TIPOCOPAGO = AUT.TIPOCOPAGO, @IDAUT = IDAUT,@IDPLAN=IDPLAN
   FROM   AUT 
   WHERE  NOAUT = @NOAUT  
   
   IF @TIPOCOPAGO IS NULL OR @TIPOCOPAGO =''  
      RETURN  
   
   SELECT @OK  = ISNULL(COUNT(*) ,0) FROM AUTD WHERE IDAUT = @IDAUT
   SELECT @OK1 = ISNULL(COUNT(*) ,0) FROM AUTD WHERE IDAUT = @IDAUT AND AQUIENCOBRO = 'P'
   IF @OK = @OK1
   BEGIN
      SELECT @PART = 1
   END
   IF  DBO.FNK_VALORVARIABLE('CLASE_IPS')='OPTICA' AND DBO.FNK_VALORVARIABLE('MANEJA_ABONO_PART')='SI'  AND @PART = 1
   BEGIN
      PRINT 'MANEJA ABONOS A FACTURA.... PROCESO DE OPTICA'
      RETURN
   END
   IF @PART = 0  
   BEGIN  
      SELECT @VALORAUX = VALORCOPAGO FROM AUT  WHERE AUT.NOAUT = @NOAUT  
      
      IF @VALORAUX > 0
      BEGIN
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@TFCJ', @NVOCONSEC OUTPUT    
         SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)   
         
         INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,  
                          IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, CERRADA, FECHA, 
                          PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE,  
                          CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO,  
                          SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_COMPUTERNAME)  
         SELECT @NVOCONSEC, NULL,  'COBRO', AUT.NOAUT, AUT.IDAUT, AUT.IDPLAN, AUT.VALORCOPAGO, @COMPANIA,  
                AFI.IDAFILIADO,AFI.TIPO_DOC, 0, GETDATE(), 'CE', 'AUT', AUT.IDCONTRATANTE, LEFT(LTRIM(RTRIM(AFI.PAPELLIDO))+' '+LTRIM(RTRIM(AFI.SAPELLIDO))  
                +' ' +LTRIM(RTRIM(AFI.PNOMBRE))+' '+ LTRIM(RTRIM(AFI.SNOMBRE)),40),    
                @CNSACJ, 'INTERNO', 0, 0, 0, 0, NULL, AUT.IDAREA, AUT.CCOSTO, AUT.SUBCCOSTO, 'C', AUT.PREFIJO,  
                @USUARIO, @SYS_COMPUTERNAME    
         FROM AUT, AFI  
         WHERE AUT.NOAUT = @NOAUT  
         AND AUT.IDAFILIADO = AFI.IDAFILIADO  

         SELECT @DATO=MOCC.CODIGOCPCJ
         FROM AUT INNER JOIN PPT ON AUT.IDTERCEROCA=PPT.IDTERCERO AND AUT.IDPLAN=PPT.IDPLAN
                  LEFT  JOIN MOCC ON PPT.IDMODELOPCA=MOCC.IDMODELOPC
         WHERE AUT.NOAUT = @NOAUT  
         IF COALESCE(@DATO,'')='' OR NOT EXISTS(SELECT * FROM CPCJ WHERE CODIGO=@DATO)
         BEGIN
            IF @TIPOCOPAGO =  'M'   
               SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJMODE'                              
            IF @TIPOCOPAGO =  'C'   
               SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJCOPA'   
         END
         IF EXISTS( SELECT * FROM USVGS WHERE IDVARIABLE LIKE 'IDPLANPART%' AND DATO=@IDPLAN)
	      BEGIN 
	         SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJPART'                              
         END 
         INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,  
                           TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)  
         SELECT NULL, @NVOCONSEC, 1,@DATO, AUT.IDAREA, AUT.VALORCOPAGO, 1, AUT.VALORCOPAGO,NULL, 0, 'N', 0, 0  
         FROM AUT  
         WHERE AUT.NOAUT =@NOAUT  
         INSERT INTO TFCJDD(CNSFACJ, ITEM, RENGLON, CODCAJA, PREFIJO, AREAFUNCIONAL, CCOSTO,
                            N_RECIBO, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
                            TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
         SELECT @NVOCONSEC, 1, 1, NULL, PREFIJO, IDAREA, CCOSTO, NULL, NULL, VALORCOPAGO, 1,
                VALORCOPAGO, NULL, NULL, NULL, NULL, NULL
         FROM AUT  
         WHERE AUT.NOAUT =@NOAUT  
      END
   END  
   ELSE  
   BEGIN  
      PRINT 'VOY POR EL PARTICULAR....'
      SELECT @VALORAUX = VALORTOTAL-CASE WHEN COALESCE(AUT.DESCUENTO,0)>0 THEN CASE WHEN AUT.TIPODTO='V' THEN AUT.DESCUENTO ELSE VALORTOTAL*(DESCUENTO/100) END ELSE 0 END
            , @OK1=COALESCE(FACTURADA,0) FROM AUT  WHERE AUT.NOAUT = @NOAUT  
      
	  IF  DBO.FNK_VALORVARIABLE('GENERA_PAGO_PART_FAC')='SI' AND @OK1=0 
		RETURN

      IF @VALORAUX > 0
      BEGIN
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@TFCJ', @NVOCONSEC OUTPUT    
         SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)   
         
         INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,  
                          IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, CERRADA, FECHA, PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE,  
                          CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO,  
                          SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_COMPUTERNAME)  
         SELECT @NVOCONSEC, NULL,  'COBRO', AUT.NOAUT, AUT.IDAUT, AUT.IDPLAN, @VALORAUX, @COMPANIA,  
                AFI.IDAFILIADO,AFI.TIPO_DOC, 0, GETDATE(), 'CE', 'AUT', AUT.IDCONTRATANTE, LEFT(LTRIM(RTRIM(AFI.PAPELLIDO))+' '+LTRIM(RTRIM(AFI.SAPELLIDO))  
                +' ' +LTRIM(RTRIM(AFI.PNOMBRE))+' '+ LTRIM(RTRIM(AFI.SNOMBRE)),40),    
                @CNSACJ, 'INTERNO', 0, 0, 0, 0, NULL, AUT.IDAREA, AUT.CCOSTO, AUT.SUBCCOSTO, 'C', AUT.PREFIJO,  
                @USUARIO, @SYS_COMPUTERNAME    
         FROM AUT, AFI  
         WHERE AUT.NOAUT = @NOAUT  
         AND AUT.IDAFILIADO = AFI.IDAFILIADO  
           
         SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJPART'                              
            
         INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,  
                           TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)  
         SELECT NULL, @NVOCONSEC, 1,@DATO, AUT.IDAREA, @VALORAUX, 1, @VALORAUX,NULL, 0, 'N', 0, 0  
         FROM AUT  
         WHERE AUT.NOAUT = @NOAUT  
         INSERT INTO TFCJDD(CNSFACJ, ITEM, RENGLON, CODCAJA, PREFIJO, AREAFUNCIONAL, CCOSTO,
                            N_RECIBO, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
                            TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
         SELECT @NVOCONSEC, 1, 1, NULL, PREFIJO, IDAREA, CCOSTO, NULL, NULL, @VALORAUX, 1,
                @VALORAUX, NULL, NULL, NULL, NULL, NULL
         FROM AUT  
         WHERE AUT.NOAUT =@NOAUT  
      END     
   END  
    
   UPDATE AUT SET GENEROCAJA = 1, NORECIBOCAJA = @NVOCONSEC, TIPOCAJA = 'TFCJ' WHERE NOAUT = @NOAUT  
    
END

