CREATE OR ALTER PROCEDURE DBO.SPK_RETIRA_FACTURA_FPAGD
@CNSFPAG  VARCHAR(20), 
@N_FACTURA VARCHAR(20),
@ITEM      SMALLINT,   
@SEDE     VARCHAR(5),
@COMPANIA VARCHAR(2),
@USUARIO  VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)
WITH ENCRYPTION
AS
DECLARE @INGRESO VARCHAR(20)
DECLARE @VALORPAGO DECIMAL(14,2)
DECLARE @NROCOMPRO VARCHAR(20)
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @CNSCXC VARCHAR(20)
BEGIN
   PRINT 'Comienzo Retiro de Factura'
   SELECT @INGRESO=INGRESO,@NROCOMPROBANTE=NROCOMPROBANTE FROM FPAG WHERE CNSFPAG=@CNSFPAG

   SELECT @VALORPAGO=VLRFACTURA,@CNSCXC=CNSCXC FROM FPAGD WHERE CNSFPAG=@CNSFPAG AND N_fACTURA=@N_FACTURA AND ITEM=@ITEM

   PRINT 'VOY A CONTABILIZAR'

   EXEC SPK_REVERSAR_RECUADO @NROCOMPROBANTE, @CNSFPAG, @COMPANIA, @SEDE,@USUARIO,@SYS_COMPUTERNAME,'',@N_FACTURA,@ITEM  
   
   IF @INGRESO='BANCOS'  AND(SELECT COALESCE(ESTADO,'') FROM FPAGD WHERE CNSFPAG=@CNSFPAG AND N_FACTURA=@N_FACTURA AND ITEM=@ITEM )='Retirada'
   BEGIN
      PRINT 'Actualizando Ingreso en Bancos...'    
      UPDATE BMOVD SET VLRLEGALIZADO = BMOVD.VLRLEGALIZADO - @VALORPAGO
      FROM   FPAG INNER JOIN BMOVD ON BMOVD.BANCO    = FPAG.BANCO 
                                  AND BMOVD.SUCURSAL = FPAG.SUCURSAL 
                                  AND BMOVD.CTA_BCO  = FPAG.CTA_BCO 
                                  AND BMOVD.ITEM     = FPAG.ITEM 
                                  AND BMOVD.RENGLON  = FPAG.RENGLON 
      WHERE  FPAG.CNSFPAG = @CNSFPAG
      
      UPDATE BMOVD SET ENPAGOS = CASE WHEN BMOVD.VLRITEM - BMOVD.VLRLEGALIZADO = 0 THEN 1 ELSE 0 END
      FROM   FPAG INNER JOIN BMOVD ON BMOVD.BANCO    = FPAG.BANCO 
                                  AND BMOVD.SUCURSAL = FPAG.SUCURSAL 
                                  AND BMOVD.CTA_BCO  = FPAG.CTA_BCO 
                                  AND BMOVD.ITEM     = FPAG.ITEM 
                                  AND BMOVD.RENGLON  = FPAG.RENGLON 
      WHERE  FPAG.CNSFPAG = @CNSFPAG
   END
   IF @INGRESO='GLOSAS'
   BEGIN
      DECLARE @CNSGLO VARCHAR(20)
      SELECT  @CNSGLO=CNSGLO FROM FPAGD WHERE CNSFPAG=@CNSFPAG AND N_FACTURA=@N_FACTURA AND ITEM=@ITEM
      IF COALESCE(@CNSGLO,'')=''
      BEGIN
         SELECT @CNSGLO=CNSGLO FROM FGLO WHERE CNSFPAG=@CNSFPAG AND N_FACTURA=@N_FACTURA
      END
      DELETE FGLOCG WHERE CNSGLO=@CNSGLO
      DELETE FGLOD WHERE CNSGLO=@CNSGLO
      DELETE FGLO WHERE CNSGLO=@CNSGLO

   END
   EXEC SPK_RELIQUIDA_FTR @CNSCXC,@N_FACTURA
END

