IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_SUMA_DBCR' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_SUMA_DBCR
END

GO
CREATE PROCEDURE DBO.SPK_SUMA_DBCR 
	@NROCOMPROBANTE   VARCHAR(20) 
WITH ENCRYPTION
AS
DECLARE @COMPANIA VARCHAR(2)
BEGIN
 SET @COMPANIA=(SELECT COMPANIA FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)

 UPDATE MCP SET 
  TOTALDEBITO  = X.DB,
  TOTALCREDITO = X.CR,
  ESTADO=CASE WHEN X.DB>0 AND X.DB=X.CR AND X.DB_C=X.CR_C AND X.DB=X.DB_C THEN 2 ELSE 
         CASE WHEN X.DB>0 AND X.DB=X.CR AND X.DB_P=X.CR_P AND X.DB=X.DB_P THEN 1 ELSE 0 END
        END
 FROM(
  SELECT
   DB  = SUM(CASE WHEN TIPO='DB' THEN ISNULL(B.VALOR,0) ELSE 0 END), 
   CR = SUM(CASE WHEN TIPO='CR' THEN ISNULL(B.VALOR,0) ELSE 0 END),
   DB_C  = SUM(CASE WHEN TIPO='DB' AND B.ESTADO=2 THEN ISNULL(B.VALOR,0) ELSE 0 END), 
   CR_C = SUM(CASE WHEN TIPO='CR' AND B.ESTADO=2 THEN ISNULL(B.VALOR,0) ELSE 0 END),
   DB_P  = SUM(CASE WHEN TIPO='DB' AND B.ESTADO=1 THEN ISNULL(B.VALOR,0) ELSE 0 END), 
   CR_P = SUM(CASE WHEN TIPO='CR' AND B.ESTADO=1 THEN ISNULL(B.VALOR,0) ELSE 0 END)
  FROM MCP A LEFT JOIN
       MCH B ON A.COMPANIA=B.COMPANIA AND A.NROCOMPROBANTE=B.NROCOMPROBANTE
  WHERE A.COMPANIA=@COMPANIA AND A.NROCOMPROBANTE=@NROCOMPROBANTE ) X 
 WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE
END


