CREATE OR ALTER PROCEDURE DBO.SPK_TRAERECIB_CAJA 
@CNSFACJ          VARCHAR(20),
@CNSACJ           VARCHAR(20),
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@CLASE_FAC        VARCHAR(5)
WITH ENCRYPTION
AS  
DECLARE @OK          SMALLINT
DECLARE @PREFCAJA    SMALLINT
DECLARE @CODCAJA     VARCHAR(4)
DECLARE @NVOCONSEC   VARCHAR(20)
DECLARE @DATO        VARCHAR(80)
DECLARE @TIPOCOPAGO  VARCHAR(1)
DECLARE @PREFIJO     VARCHAR(6)
DECLARE @TIPOEGRESO  VARCHAR(80)
DECLARE @CONCEPTO    VARCHAR(16)
DECLARE @VALOR       DECIMAL(14,2)
DECLARE @PROCEDENCIA VARCHAR(10)   
DECLARE @NOADMISION  VARCHAR(16)
DECLARE @IDAFILIADO  VARCHAR(20)
DECLARE @NOMCLIENTE  VARCHAR(100)
DECLARE @TERCAT      VARCHAR(10) 
DECLARE @CODUNG VARCHAR(2)
DECLARE @CODPRG VARCHAR(5)
DECLARE @IDSEDE VARCHAR(5)
DECLARE @CODCAJA_Q VARCHAR(4), @CNSFACJ_Q VARCHAR(20), @VALOR_Q DECIMAL(14,2)
DECLARE @CNSPCJ VARCHAR(20)
DECLARE @CUENTA_PCJ VARCHAR(16), @DETALLE_PCJ VARCHAR(40), @VEZ_PCJ INT
DECLARE @VALORFALTANTE DECIMAL(14,2), @VALOR_PCJ DECIMAL(14,2)
DECLARE @IDTERCEROAFI VARCHAR(20)
BEGIN
    SELECT   @OK = COUNT(*) FROM TFCJ WHERE CNSFACJ = @CNSFACJ
   
    IF ISNULL(@OK,0) = 0 
        RETURN
   
    SELECT @CODCAJA = CODCAJA, @OK = ABIERTA FROM ACJ  WHERE CNSACJ = @CNSACJ

    IF ISNULL(@OK,0) = 0 
        RETURN
   
    SELECT @PROCEDENCIA = PROCEDENCIA, @NOADMISION = NOADMISION, @IDAFILIADO = IDAFILIADO, @NOMCLIENTE = NOMBRECLIENTE
    FROM   TFCJ 
    WHERE  CNSFACJ = @CNSFACJ
   
    SELECT @OK = COUNT(*) FROM CAJ WHERE CODCAJA = @CODCAJA
    SELECT @IDSEDE = IDSEDE FROM UBEQ  WHERE CAJA    = @CODCAJA
    SELECT @CODUNG = CODUNG ,@CODPRG = CODPRG  FROM  SED WHERE IDSEDE =@IDSEDE
   
    IF ISNULL(@OK,0) = 0 
        RETURN


    --SE COLOCA EN BEGIN TRAN PARA CONTROLAR CONSECUTIVO
    BEGIN TRY 
	    SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDMPREFCAJA'
	    IF @CLASE_FAC = 'COBRO'
	    BEGIN
		    EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJ', @NVOCONSEC OUTPUT  
		    SELECT @NVOCONSEC = REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
	    END
	    ELSE
	    BEGIN
		    EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJE', @NVOCONSEC OUTPUT  
		    SELECT @NVOCONSEC = 'E'+REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
	    END
        
	    IF @DATO = 'SI'
	    BEGIN
		    SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDPREFCAJA'
		    IF @DATO IS NOT NULL
			    SELECT @NVOCONSEC = @DATO + @NVOCONSEC
	    END

	    IF @CLASE_FAC = 'COBRO' 
	    BEGIN
		    SELECT @TIPOEGRESO = NULL   
	    END
	    ELSE 
	    BEGIN 
		    SELECT @TIPOEGRESO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJTEDEVOLDEPOSITO'
	    END
   
	    PRINT 'Insertando Tercero...'
	    SET @TERCAT = DBO.FNK_VALORVARIABLE('TERCATCLIENTE')
	    EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @TERCAT 
        SELECT @IDTERCEROAFI=COALESCE(RUC,IDAFILIADO) FROM AFI WHERE IDAFILIADO=@IDAFILIADO

	    --SE REALIZA ARREGLO DE RECIBOS DE CAJA CUANDO SE LEGALIZA UN DEPOSITO DE TERCERO PARTICULAR QUE NO ES EL MISMO AFILIADO
	    -- IF (EXISTS (SELECT * FROM TER WHERE ESTADO='Activo' AND NIT = (SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO = @IDAFILIADO) ))
	    -- BEGIN
			--SELECT @IDAFILIADO= IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT = (SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO = @IDAFILIADO)
	    -- END 
	    PRINT 'Insertando en FCJ...'
        BEGIN TRY 
	        INSERT INTO FCJ (CNSFACJ, N_RECIBO, CODCAJA, CODTURNO_GEN, CODTURNO_TRA, CLASE_FAC, 
						        NOADMISION, NOPRESTACION, IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO, 
						        CERRADA, FECHA, PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE,  
						        CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE,
						        AREAPRESTACION, CCOSTO, SUBCCOSTO, CLASER, IDCAUSALANUL, USUARIOANUL, 
						        SYS_COMPUTERNAMEANUL, FECHAANU, TCNSFACJ, IDENTIFICADOR, 
						        SYS_COMPUTERNAME, OBSERVACION, USUARIO, TIPOEGRESO, ENPAGOS, RECAUDO,
						        DEAPERTURA, ARCHIVADO, DEVUELTO,CODUNG ,CODPRG,TIPO_DOC)
	        SELECT @NVOCONSEC, N_RECIBO, @CODCAJA, NULL, NULL, CLASE_FAC,TFCJ.NOADMISION, NOPRESTACION,
			        TFCJ.IDPLAN, VALORTOTAL, TFCJ.COMPANIA,COALESCE(AFI.IDAFILIADO,TFCJ.IDAFILIADO) IDAFILIADO, 0, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 
				    TFCJ.PROCEDENCIA, COALESCE (FTR.N_FACTURA, COALESCE (TFCJ.N_FACTURA,''))N_FACTURA,
				    CASE WHEN HADM.IDPLAN IN ( SELECT DATO FROM USVGS WHERE IDVARIABLE LIKE 'IDPLANPART%' AND DATO<>'') 
							    AND HADM.IDTERCERO <>( SELECT DBO.FNK_VALORVARIABLE ('IDTERCEROPARTICULAR') )
					        THEN HADM.IDTERCERO
					        ELSE 
							    @IDTERCEROAFI
			        END,
				    NOMBRECLIENTE, @CNSACJ, TIPO, 
			        'P',TFCJ.IMPRESO,TFCJ.MARCACONT,TFCJ.CONTABILIZADA, TFCJ.NROCOMPROBANTE,
			        AREAPRESTACION, CCOSTO, SUBCCOSTO, CLASER, NULL, NULL, NULL, 
			        NULL, TFCJ.CNSFACJ, IDENTIFICADOR, @SYS_COMPUTERNAME,TFCJ.OBSERVACION, @USUARIO, @TIPOEGRESO, 
			        0, 0, 0, 0, 0,@CODUNG ,@CODPRG,COALESCE(AFI.TIPO_DOC,TFCJ.TIPO_DOC)
	        FROM   TFCJ LEFT JOIN HADM ON TFCJ.PROCEDENCIA='SALUD' AND TFCJ.NOADMISION=HADM.NOADMISION 
				        LEFT JOIN FTR ON FTR.NOREFERENCIA=TFCJ.NOADMISION AND TFCJ.PROCEDENCIA='SALUD' AND FTR.ESTADO='P' 
									    AND FTR.PROCEDENCIA='SALUD' AND TFCJ.N_FACTURA=FTR.N_FACTURA
				        LEFT JOIN AFI ON TFCJ.IDAFILIADO= AFI. IDAFILIADO --CASE WHEN DBO.FNK_VALORVARIABLE ('IDAFILIADO_AUTOMAT')='SI' THEN AFI.DOCIDAFILIADO ELSE AFI. IDAFILIADO END
	        WHERE TFCJ. CNSFACJ   = @CNSFACJ AND COALESCE(FTR.TIPOANULACION,'') = ''
        END TRY 
        BEGIN CATCH 
            PRINT 'ERROR AL INGRESAR FCJ'
		    RETURN
	    END CATCH

	    SELECT @VALOR = VALORTOTAL FROM TFCJ WHERE  CNSFACJ   = @CNSFACJ 
	    IF @PROCEDENCIA = 'CITAS'
	    BEGIN
		    UPDATE CIT SET NORECIBOCAJA = @NVOCONSEC, CODCAJA = @CODCAJA, TIPOCAJA = 'FCJ' WHERE CONSECUTIVO = @NOADMISION
		    UPDATE FCJ SET IDTERCERO= @IDTERCEROAFI  WHERE CNSFACJ= @NVOCONSEC  AND CODCAJA=@CODCAJA
	    END
	    IF @PROCEDENCIA = 'CE'
	    BEGIN
		    SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJDEPOSITO'   
		    UPDATE AUT SET NORECIBOCAJA = @NVOCONSEC, CODCAJA = @CODCAJA, TIPOCAJA = 'FCJ' WHERE NOAUT = @NOADMISION 
		    UPDATE FCJ SET IDTERCERO= @IDTERCEROAFI  WHERE CNSFACJ= @NVOCONSEC  AND CODCAJA=@CODCAJA
        END      
        
	    IF @CLASE_FAC = 'COBRO' 
	    BEGIN   
            BEGIN TRY
		        INSERT INTO FCJD(CODCAJA, N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
								        TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
		        SELECT @CODCAJA, N_RECIBO, @NVOCONSEC, ITEM, IIF(EXISTS(SELECT 1 FROM CPCJ WHERE CODIGO=COALESCE(CAJ.IDCONCEPTO,'') AND CAJ.IDCONCEPTO<>''),CAJ.IDCONCEPTO,TFCJD.CONCEPTO), AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
								        TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO
		        FROM  TFCJD
                LEFT JOIN CAJ ON CAJ.CODCAJA=@CODCAJA
		        WHERE CNSFACJ = @CNSFACJ		  
            END TRY 
            BEGIN CATCH 
                PRINT 'ERROR AL INGRESAR FCJD1'
		        RETURN
	        END CATCH

		    IF @PROCEDENCIA = 'SALUD' 
		    BEGIN
			    PRINT '?S LIQUIDACION DE PARTICULAR'
			    --1. debo traer automaticamente todos los recibos de esta admision
			    --2. si es necesario debo generar el reintegro a paciente
			    SELECT @VALORFALTANTE = @VALOR 
            
			    SELECT TOP 1 @CUENTA_PCJ = CUENTA, @DETALLE_PCJ = DETALLE, @VEZ_PCJ = COUNT(*) 
			    FROM (SELECT DISTINCT TTEC.CUENTA, TTEC.DETALLE 
				    FROM   TTEC INNER JOIN PPT ON TTEC.TIPO = PPT.TIPOTERCONTABLE 
				    WHERE  PPT.IDTERCERO= @IDTERCEROAFI) X 
			    GROUP BY CUENTA, DETALLE
         
			    IF @VEZ_PCJ <> 1
			    BEGIN
				    SELECT @CUENTA_PCJ = '', @DETALLE_PCJ = ''           
			    END
         
			    DECLARE PCJC CURSOR FOR
			    SELECT CODCAJA, CNSFACJ, VALOR FROM QXDING WHERE NOINGRESO = @NOADMISION AND LEGALIZADO =0 AND DEVUELTO = 0
			    
                OPEN PCJC
			    FETCH NEXT FROM PCJC INTO @CODCAJA_Q, @CNSFACJ_Q, @VALOR_Q

			    WHILE @@FETCH_STATUS = 0  
			    BEGIN                  
				    --SELECT @CODCAJA_Q, @CNSFACJ_Q, @VALOR_Q
				    IF @VALOR_Q <= @VALORFALTANTE
				    BEGIN
				        SELECT @VALOR_PCJ = @VALOR_Q 
				    END
				    ELSE
				    BEGIN
				        SELECT @VALOR_PCJ = @VALORFALTANTE
				    END
				    SELECT @CNSPCJ = NULL
				    EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE,'@PCJ', @CNSPCJ OUTPUT  
				    SELECT @CNSPCJ = @IDSEDE+REPLACE(SPACE(8 - LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)
                
				    INSERT INTO PCJ (CODCAJA, CNSPCJ, CNSFACJ, TIPOPAGO, VALOR, BANCO, SUCURSAL, CTA_BCO, CNSDOC, NUMERODOCUMENTO, NUMEROAUTORIZA,
								        FECHA, CNSACJ, IDTERCERO, IMPRESO, CODCAJADEP, CNSFACJDEP, DOCORIGEN, BANCO_DEP, CTA_BCO_DEP, CUENTA,
								        VLR_DEVUELTO, VARIOS, TRASLADADO, TRASLADO_CNSFACJ, VALORREINTEGRO)
				    SELECT @CODCAJA, @CNSPCJ, @NVOCONSEC, DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO'), @VALOR_PCJ, '', '', '', '', '', '',DBO.FNK_FECHA_SIN_MLS(GETDATE()),
					        @CNSACJ, NULL, 0, @CODCAJA_Q, @CNSFACJ_Q, 0, '', '', @CUENTA_PCJ, 0, 0, '', '', @VALOR_Q - @VALOR_PCJ

				    SELECT @VALORFALTANTE = @VALORFALTANTE - @VALOR_PCJ
				    IF @VALORFALTANTE < 0
				    BEGIN
				        SELECT @VALORFALTANTE = 0 
				    END    
				    UPDATE QXDING SET VALORREINTEGRO = @VALOR_Q - @VALOR_PCJ WHERE  NOINGRESO = @NOADMISION AND CODCAJA = @CODCAJA_Q AND CNSFACJ = @CNSFACJ_Q

				    FETCH NEXT FROM PCJC INTO @CODCAJA_Q, @CNSFACJ_Q, @VALOR_Q
			    END
			    CLOSE PCJC
			    DEALLOCATE PCJC  
		    END 
		    ELSE
		        SELECT @VALORFALTANTE = @VALOR 

		    SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJPART'
		    IF EXISTS(SELECT 1 FROM QXDING WHERE NOINGRESO  =@NOADMISION AND PROCEDENCIA='CE') AND @DATO=(SELECT CONCEPTO FROM FCJD WHERE CODCAJA=@CODCAJA AND CNSFACJ= @NVOCONSEC)
		    BEGIN
			    PRINT 'TENGO DEPOSITOS ASIGNADOS..........'

			    SELECT @VALORFALTANTE = @VALOR 
            
			    SELECT TOP 1 @CUENTA_PCJ = CUENTA, @DETALLE_PCJ = DETALLE, @VEZ_PCJ = COUNT(*) 
			    FROM (SELECT DISTINCT TTEC.CUENTA, TTEC.DETALLE 
				    FROM   TTEC INNER JOIN PPT ON TTEC.TIPO = PPT.TIPOTERCONTABLE 
				    WHERE  PPT.IDTERCERO= @IDTERCEROAFI) X 
			    GROUP BY CUENTA, DETALLE
         
			    IF @VEZ_PCJ <> 1
			    BEGIN
				    SELECT @CUENTA_PCJ = '', @DETALLE_PCJ = ''           
			    END
         
			    DECLARE PCJC CURSOR FOR
			    SELECT CODCAJA, CNSFACJ, VALOR FROM QXDING WHERE NOINGRESO = @NOADMISION AND LEGALIZADO =0 AND DEVUELTO = 0 AND PROCEDENCIA='CE'
			    
                OPEN PCJC
			    FETCH NEXT FROM PCJC INTO @CODCAJA_Q, @CNSFACJ_Q, @VALOR_Q
			   
                WHILE @@FETCH_STATUS = 0  
			    BEGIN                  
				    --SELECT @CODCAJA_Q, @CNSFACJ_Q, @VALOR_Q
				    IF @VALOR_Q <= @VALORFALTANTE
				    BEGIN
				        SELECT @VALOR_PCJ = @VALOR_Q 
				    END
				    ELSE
				    BEGIN
				        SELECT @VALOR_PCJ = @VALORFALTANTE
				    END

				    SELECT @CNSPCJ = NULL
				    EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE,'@PCJ', @CNSPCJ OUTPUT  
				    SELECT @CNSPCJ = @IDSEDE+REPLACE(SPACE(8 - LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)
                
				    INSERT INTO PCJ (CODCAJA, CNSPCJ, CNSFACJ, TIPOPAGO, VALOR, BANCO, SUCURSAL, CTA_BCO, CNSDOC, NUMERODOCUMENTO, NUMEROAUTORIZA,
								        FECHA, CNSACJ, IDTERCERO, IMPRESO, CODCAJADEP, CNSFACJDEP, DOCORIGEN, BANCO_DEP, CTA_BCO_DEP, CUENTA,
								        VLR_DEVUELTO, VARIOS, TRASLADADO, TRASLADO_CNSFACJ, VALORREINTEGRO)
				    SELECT @CODCAJA, @CNSPCJ, @NVOCONSEC, DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO'), @VALOR_PCJ, '', '', '', '', '', '',DBO.FNK_FECHA_SIN_MLS(GETDATE()),
					        @CNSACJ, NULL, 0, @CODCAJA_Q, @CNSFACJ_Q, 0, '', '', @CUENTA_PCJ, 0, 0, '', '', @VALOR_Q - @VALOR_PCJ

				    SELECT @VALORFALTANTE = @VALORFALTANTE - @VALOR_PCJ
				    IF @VALORFALTANTE < 0
				    BEGIN
				        SELECT @VALORFALTANTE = 0 
				    END    
				    UPDATE QXDING SET VALORREINTEGRO = @VALOR_Q - @VALOR_PCJ,LEGALIZADO=1 WHERE  NOINGRESO = @NOADMISION AND CODCAJA = @CODCAJA_Q AND CNSFACJ = @CNSFACJ_Q
				    FETCH NEXT FROM PCJC INTO @CODCAJA_Q, @CNSFACJ_Q, @VALOR_Q
			    END
			    CLOSE PCJC
			    DEALLOCATE PCJC 
		    END
	    END
	    ELSE
	    BEGIN  
		    SELECT @CONCEPTO = CJTE.CODIGO FROM CJTE WHERE CJTE.TIPOEGRESO = @TIPOEGRESO
            BEGIN TRY 
		        INSERT INTO FCJD(CODCAJA, N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, 
						        CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
		        SELECT @CODCAJA, NULL, @NVOCONSEC, 1 , @CONCEPTO, NULL , @VALOR, 1, @VALOR, '', 0 , 'N', 0, 0
            END TRY 
            BEGIN CATCH 
                PRINT 'ERROR AL INGRESAR FCJD2'
		        RETURN
	        END CATCH   
	    END

        BEGIN TRY
	        INSERT INTO FCJDD(CODCAJA, CNSFACJ, ITEM, RENGLON, PREFIJO, AREAFUNCIONAL, CCOSTO, 
						    N_RECIBO, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
						    TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO )
	        SELECT @CODCAJA,@NVOCONSEC,  ITEM, RENGLON, PREFIJO, AREAFUNCIONAL, CCOSTO, N_RECIBO, 
			        CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO,
			        TIPODCTO, DCTO, VLRDESCUENTO
	        FROM  TFCJDD
	        WHERE CNSFACJ = @CNSFACJ
        END TRY 
        BEGIN CATCH 
            PRINT 'ERROR AL INGRESAR FCJDD'
		    RETURN
	    END CATCH
    END TRY 
    BEGIN CATCH  
        SELECT  
            ERROR_NUMBER() AS ErrorNumber  
            ,ERROR_SEVERITY() AS ErrorSeverity  
            ,ERROR_STATE() AS ErrorState  
            ,ERROR_PROCEDURE() AS ErrorProcedure  
            ,ERROR_LINE() AS ErrorLine  
            ,ERROR_MESSAGE() AS ErrorMessage;  
    END CATCH; 

	
	DELETE FROM TFCJDD WHERE CNSFACJ = @CNSFACJ
	DELETE FROM TFCJD  WHERE CNSFACJ = @CNSFACJ
	DELETE FROM TFCJ   WHERE CNSFACJ = @CNSFACJ

	IF EXISTS(SELECT 1 FROM TFCJ WHERE NOADMISION=@NOADMISION AND COALESCE(VALORTOTAL,0)=0 AND @CLASE_FAC = 'COBRO' AND PROCEDENCIA=@PROCEDENCIA )
	BEGIN
		DELETE FROM TFCJ WHERE   NOADMISION=@NOADMISION AND COALESCE(VALORTOTAL,0 )=0 AND @CLASE_FAC = 'COBRO'  AND PROCEDENCIA=@PROCEDENCIA
	END
END

