CREATE OR ALTER PROCEDURE DBO.SPK_RESPUESTAGLOSA 
@CNSGLO           VARCHAR(20),
@MODO             SMALLINT,
@SEDE             VARCHAR(5),
@COMPANIA         VARCHAR(2),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@LIBERA           BIT=0
WITH ENCRYPTION
AS
DECLARE @NVOCONSEC      VARCHAR(20)
DECLARE @IDTERCERO      VARCHAR(20)
DECLARE @N_FACTURA      VARCHAR(16)
DECLARE @VLRACEPTADO    DECIMAL(14,2)
DECLARE @VLRRECUPERAR   DECIMAL(14,2)
DECLARE @CNSCXC         VARCHAR(20)
DECLARE @ITEM           INT  
DECLARE @TIPORESPUESTA  VARCHAR(1)    
DECLARE @CNSGLO_O       VARCHAR(20)
DECLARE @CNSRPDX        VARCHAR(20)
DECLARE @PROCEDENCIA    VARCHAR(20)
DECLARE @GN             SMALLINT 
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @GNOT           SMALLINT    -- GENERA NOTA ?
DECLARE @RESPUESTA VARCHAR(255)
DECLARE @VR_DET DECIMAL(14,2), @EXCESO DECIMAL(14,2), @MAXITEM INT, @VR_MAXITEM DECIMAL(14,2)
BEGIN
   SELECT @COMPANIA=COMPANIA,@SEDE=IDSEDE FROM USUSU WHERE USUARIO=@USUARIO    
   SELECT @GNOT = 0
   IF EXISTS(SELECT * FROM FGLO WHERE CERRADA=1 AND CNSGLO=@CNSGLO)
   BEGIN
      PRINT 'GLOSA YA APLICADA'
      RETURN
   END
   SELECT @CNSCXC = CNSCXC, @N_FACTURA = N_FACTURA
   FROM   FGLO
   WHERE  CNSGLO = @CNSGLO
   
   UPDATE FGLOD SET VLRACEPTADO = 0 
   WHERE  VLRACEPTADO IS NULL
   AND    CNSGLO = @CNSGLO
   
   SELECT @TIPORESPUESTA = TIPORESPUESTA, @PROCEDENCIA = PROCEDENCIA,
          @GN = GENERANOTA, @NROCOMPROBANTE = COALESCE(NROCOMPROBANTE,''), @CNSGLO_O=COALESCE(CNSGLO_O,'') 
   FROM   FGLO 
   WHERE  CNSGLO = @CNSGLO

   IF @MODO = 1
   BEGIN
      UPDATE FGLOD SET VLRACEPTADO = VLRGLOSA, VLRRECUPERAR = 0,F_CIERRE= CASE WHEN F_CIERRE IS NULL THEN GETDATE() ELSE F_CIERRE END
      WHERE CNSGLO = @CNSGLO
      AND VLRGLOSA <> (VLRACEPTADO + VLRRECUPERAR)

      UPDATE FGLO SET VLRRECUPERAR = VLRGLOSA-VLRACEPTADO
      WHERE CNSGLO = @CNSGLO
      AND VLRGLOSA <> (VLRACEPTADO + VLRRECUPERAR)   
   END
   IF @MODO = 2 OR @MODO = 3
   BEGIN
      UPDATE FGLOD SET VLRRECUPERAR = VLRGLOSA-VLRACEPTADO ,F_CIERRE= CASE WHEN F_CIERRE IS NULL THEN GETDATE() ELSE F_CIERRE END
      WHERE CNSGLO = @CNSGLO
      AND VLRGLOSA <> (VLRACEPTADO + VLRRECUPERAR)

      UPDATE FGLO SET VLRRECUPERAR = VLRGLOSA-VLRACEPTADO
      WHERE CNSGLO = @CNSGLO
      AND VLRGLOSA <> (VLRACEPTADO + VLRRECUPERAR)
   END
   
   --ACTUALIZA VALORES EN GLOSA DESDE DETALLES
   IF @TIPORESPUESTA = 'I'
   BEGIN
      PRINT 'POR ITEM'
      SELECT @VLRACEPTADO = SUM(COALESCE(VLRACEPTADO,0)), @VLRRECUPERAR = SUM(COALESCE(VLRRECUPERAR,0))
      FROM   FGLOD
      WHERE  CNSGLO = @CNSGLO
      
      UPDATE FGLO SET VLRACEPTADO = @VLRACEPTADO, VLRRECUPERAR = @VLRRECUPERAR
      WHERE  CNSGLO = @CNSGLO
   END
   ELSE
   BEGIN
      PRINT 'TOTAL'
      SELECT @VLRACEPTADO = VLRACEPTADO, @VLRRECUPERAR = VLRRECUPERAR
      FROM   FGLO
      WHERE  CNSGLO = @CNSGLO
   END
   -- CREA NOTA CREDITO SI EL VALOR ACEPTADO ES > 0
   PRINT 'AQUI'   
   PRINT 'VLR ACEPTADO  = ' + STR(@VLRACEPTADO)
   PRINT 'VLR RECUPERAR = ' + STR(@VLRRECUPERAR)
   PRINT 'FIN'
   
   UPDATE FTRCXC SET SALDO=SALDO - @VLRACEPTADO
   FROM FTRCXC A INNER JOIN TTEC B ON A.TIPOTTEC=B.TIPO
   WHERE A.N_FACTURA=@N_FACTURA AND A.CUENTACXC=B.CTAGLOSADB
   
   UPDATE FGLO SET ABONADO = @VLRACEPTADO, SALDO = @VLRRECUPERAR
   WHERE  CNSGLO = @CNSGLO
   
   IF (@PROCEDENCIA = 'Recaudo') OR (@PROCEDENCIA = 'Auditoria' AND @GN = 1) 
   BEGIN
      IF @VLRACEPTADO > 0    
      BEGIN        
         IF @LIBERA=0
         BEGIN  
             SELECT @GNOT = 1
            --SE GENERA CONSECUTIVO DE NOTA
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FNOTC', @NVOCONSEC OUTPUT  
            SELECT @NVOCONSEC = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
            --SE INSERTAN LOS DATOS DE LA NOTA DESDE LA GLOSA
            INSERT INTO FNOT(CNSFNOT, CLASE, N_FACTURA, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, IDCONCEPTO,CNSRESOLFE,
                             MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA,
                             USUARIO, CNSCXC, CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU,
                             RAZONANU, PROCEDENCIA, CNSGLO, APLICADAA,CONCEPTO,TIPOCONCEPTO,VALORCONCEPTO,DETGENERADOS )  
            SELECT @NVOCONSEC, 'C',FGLO. N_FACTURA,FGLO. IDTERCERO, GETDATE(), VLRACEPTADO,
		    CASE WHEN TIPORESPUESTA='T' THEN dbo.FNK_RTF(OBSERVACIONRTA) 
                   ELSE (SELECT TOP 1 RESPUESTA FROM FGLOD WHERE CNSGLO=@CNSGLO) END,IDCONCEPTO,FTR.CNSRESOL,
                   0, 0, 0, NULL, 0, @COMPANIA, @USUARIO, CNSCXC, 0, 'O', NULL, NULL, NULL, NULL,
                   'AUDITORIA', CNSGLO, 'C',1,'V', VLRACEPTADO,0
            FROM   FGLO LEFT JOIN FTR ON FGLO.N_FACTURA=FTR.N_FACTURA
            WHERE  CNSGLO = @CNSGLO

           EXEC SPK_GENITEMS_NOTACR @NVOCONSEC,'C',@USUARIO,1

           -- Si GENITEMS no deja FNOTD (FTRD neto 0 por copagos, etc.), se arma desde la glosa
           DELETE FNOTD WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C' AND COALESCE(VR_TOTAL,0) <= 0
           IF NOT EXISTS (SELECT 1 FROM FNOTD WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C' AND COALESCE(VR_TOTAL,0) > 0)
           BEGIN
              PRINT N'GENITEMS no generó detalle; se arma FNOTD desde FGLOD'
              INSERT INTO FNOTD(CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
                                VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION,
                                IDAREA, CCOSTO, PREFIJO, N_CUOTA, N_FACTURA)
              SELECT @NVOCONSEC, 'C',
                     ROW_NUMBER() OVER (ORDER BY FGLOD.ITEM),
                     COALESCE(FGLOD.TIPO,'S'), FGLOD.IDSERVICIO, LEFT(CONVERT(VARCHAR(512), FGLOD.DESCRIPCION),511), 1,
                     FGLOD.VLRACEPTADO, FGLOD.VLRACEPTADO, @COMPANIA, @USUARIO,
                     LEFT(CONVERT(VARCHAR(2048), COALESCE(FGLOD.RESPUESTA, FGLOD.DESCRIPCION)),2047),
                     FTRD.AREAPRESTACION, FTRD.CCOSTO, FTRD.PREFIJO, FGLOD.N_CUOTA, FGLOD.N_FACTURA
              FROM FGLOD
              LEFT JOIN FTRD ON FTRD.N_FACTURA = FGLOD.N_FACTURA AND FTRD.N_CUOTA = FGLOD.N_CUOTA
              WHERE FGLOD.CNSGLO = @CNSGLO
                AND COALESCE(FGLOD.VLRACEPTADO,0) > 0
           END
           IF NOT EXISTS (SELECT 1 FROM FNOTD WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C' AND COALESCE(VR_TOTAL,0) > 0)
           BEGIN
              PRINT N'Sin ítems de FGLOD; se crea un ítem con el valor aceptado de la glosa'
              INSERT INTO FNOTD(CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
                                VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION,
                                IDAREA, CCOSTO, PREFIJO, N_CUOTA, N_FACTURA)
              SELECT @NVOCONSEC, 'C', 1, 'C',
                     COALESCE(FGLO.IDCONCEPTO,'01'),
                     LEFT(COALESCE(CPNT.DESCRIPCION, N'Aceptación de glosa'),511),
                     1, @VLRACEPTADO, @VLRACEPTADO, @COMPANIA, @USUARIO,
                     LEFT(COALESCE(DBO.FNK_RTF(FGLO.OBSERVACIONRTA), N''),2047),
                     NULL, NULL, NULL, NULL, FGLO.N_FACTURA
              FROM FGLO
              LEFT JOIN CPNT ON CPNT.CODIGO = FGLO.IDCONCEPTO
              WHERE FGLO.CNSGLO = @CNSGLO
           END
           SELECT @VR_DET = COALESCE(SUM(VR_TOTAL),0) FROM FNOTD WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C'
           IF @VR_DET > @VLRACEPTADO
           BEGIN
              SELECT @EXCESO = @VR_DET - @VLRACEPTADO
              WHILE @EXCESO > 0
              BEGIN
                 SET @MAXITEM = NULL
                 SET @VR_MAXITEM = NULL
                 SELECT TOP 1 @MAXITEM = ITEM, @VR_MAXITEM = VR_TOTAL
                 FROM FNOTD
                 WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C' AND VR_TOTAL > 0
                 ORDER BY ITEM DESC
                 IF @MAXITEM IS NULL
                    BREAK
                 IF @VR_MAXITEM >= @EXCESO
                 BEGIN
                    UPDATE FNOTD SET VR_TOTAL = VR_TOTAL - @EXCESO, VR_UNITARIO = VR_UNITARIO - @EXCESO
                    WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C' AND ITEM = @MAXITEM
                    SET @EXCESO = 0
                 END
                 ELSE
                 BEGIN
                    UPDATE FNOTD SET VR_TOTAL = 0, VR_UNITARIO = 0
                    WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C' AND ITEM = @MAXITEM
                    SET @EXCESO = @EXCESO - @VR_MAXITEM
                 END
              END
              DELETE FNOTD WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C' AND COALESCE(VR_TOTAL,0) <= 0
              SELECT @VR_DET = COALESCE(SUM(VR_TOTAL),0) FROM FNOTD WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C'
           END
           IF @VR_DET <= 0
           BEGIN
              DELETE FNOTD WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C'
              DELETE FNOT WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C'
              RAISERROR(N'No se pudo generar el detalle de la nota crédito. La glosa no se aplicó.',16,1)
              RETURN
           END
           UPDATE FNOT
           SET VR_TOTAL = @VR_DET, VALORCONCEPTO = @VR_DET, DETGENERADOS = 1
           WHERE CNSFNOT = @NVOCONSEC AND CLASE = 'C'
          
           --SE COMENTA PARA ASEGURAR LA CREACION DE DETALLE POR TEMAS DE RIPS JSON 

            -- SE CREA TABLA TEMPORAL PARA PODER MANEJAR EL ITEM DE MANERA IDENTITY
            --CREATE TABLE #FNOTD(CNSFNOT     VARCHAR(20)   COLLATE database_default, 
            --                    CLASE       VARCHAR(1)    COLLATE database_default, 
            --                    ITEM        SMALLINT      IDENTITY, 
            --                    TIPO        VARCHAR(1)    COLLATE database_default, 
            --                    IDSERVICIO  VARCHAR(20)   COLLATE database_default, 
            --                    DESCRIPCION VARCHAR(512)  COLLATE database_default, 
            --                    CANTIDAD    INT, 
            --                    VR_UNITARIO FLOAT , 
            --                    VR_TOTAL    FLOAT, 
            --                    COMPANIA    VARCHAR(2)    COLLATE database_default, 
            --                    USUARIO     VARCHAR(12)   COLLATE database_default, 
            --                    OBSERVACION VARCHAR(2048) COLLATE database_default,
            --                    IDAREA      VARCHAR(10)   COLLATE database_default,
            --                    CCOSTO      VARCHAR(20)   COLLATE database_default,
            --                    PREFIJO     VARCHAR(10)   COLLATE database_default,
            --                    N_CUOTA     SMALLINT, 
            --                    N_FACTURA   VARCHAR(16)   COLLATE database_default)
            -- SE CREAN LOS DETALLES DE LA NOTA CREDITO DESDE LOS DETALLE DE LA GLOSA
            --IF @TIPORESPUESTA = 'I' AND NOT EXISTS(SELECT * FROM FGLOD WHERE CNSGLO=@CNSGLO AND TIPO<>'S')
            --BEGIN
            --   PRINT 'ITEMS DE FGLOD POR TIPO = SERVICIO'
            --   --INSERT INTO #FNOTD(CNSFNOT, CLASE, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
            --   --                   VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION,
            --   --                   IDAREA,CCOSTO,PREFIJO, N_CUOTA, N_FACTURA)
            --   --SELECT @NVOCONSEC, 'C', FGLOD.TIPO, IDSERVICIO,LEFT(DESCRIPCION,511), 1, VLRACEPTADO,
            --   --       VLRACEPTADO, @COMPANIA, @USUARIO, SUBSTRING(FGLOD.RESPUESTA,1,2047),FTRD.AREAPRESTACION,FTRD.CCOSTO,FTRD.PREFIJO, 
            --   --       FGLOD.N_CUOTA, FTRD.N_FACTURA
            --   --FROM   FGLOD  INNER JOIN FTRD ON FGLOD.N_FACTURA=FTRD.N_FACTURA AND FGLOD.N_CUOTA=FTRD.N_CUOTA 
            --   --WHERE  CNSGLO = @CNSGLO  
            --   --AND    FGLOD.VLRACEPTADO > 0
            --   --AND    FGLOD.TIPO = 'S'

            --   ---- SE INSERTAN LOS DATOS A DETALLES DE NOTA DESDE LA TABLA TEMPORAL
            --   --INSERT INTO FNOTD(CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
            --   --                  VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION,IDAREA,
            --   --                  CCOSTO, PREFIJO, N_CUOTA, N_FACTURA)
            --   --SELECT CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
            --   --       VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, IDAREA,
            --   --       CCOSTO, PREFIJO, N_CUOTA, N_FACTURA
            --   --FROM #FNOTD 
            --   ---- SE BORRA TABLA TEMPORAL
         
            --   --DROP TABLE #FNOTD
            --   --PRINT 'ITEMS DE FGLOD POR TIPO = CONCEPTO'
            --   --INSERT INTO #FNOTD(CNSFNOT, CLASE, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
            --   --                   VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_FACTURA)
            --   --SELECT @NVOCONSEC, 'C', FGLOD.TIPO, IDSERVICIO, SUBSTRING(DESCRIPCION,1,511), 1, VLRACEPTADO,
            --   --       VLRACEPTADO, @COMPANIA, @USUARIO,  SUBSTRING(DESCRIPCION,1,511), @N_FACTURA
            --   --FROM   FGLOD  
            --   --WHERE  CNSGLO = @CNSGLO  
            --   --AND    FGLOD.VLRACEPTADO > 0
            --   --AND    FGLOD.TIPO = 'C'
            --END
            --ELSE                   
            --BEGIN
            --   EXEC SPK_GENITEMS_NOTACR @NVOCONSEC,'C',@USUARIO
            --   --INSERT INTO #FNOTD(CNSFNOT, CLASE, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
            --   --                   VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION)
            --   --SELECT @NVOCONSEC, 'C', 'C', FGLO.IDCONCEPTO, CPNT.DESCRIPCION, 1, FGLO.VLRACEPTADO,
            --   --       FGLO.VLRACEPTADO, @COMPANIA, @USUARIO,SUBSTRING(FGLO.OBSERVACIONRTA,1,2047)
            --   --FROM   FGLO, CPNT   
            --   --WHERE  FGLO.CNSGLO = @CNSGLO  
            --   --AND    FGLO.IDCONCEPTO = CPNT.CODIGO
            --   --AND    FGLO.VLRACEPTADO > 0
            --END

            UPDATE FGLO SET CNSFNOT = @NVOCONSEC
            WHERE  CNSGLO = @CNSGLO            
      END    
      ELSE
      BEGIN   
         SELECT @GNOT = 0
         SELECT @RESPUESTA=LEFT(DBO.FNK_RTF(RESPUESTA),255) FROM FGLOD WHERE CNSGLO=@CNSGLO
         EXEC DBO.SPK_ANULA_FACT @N_FACTURA,@COMPANIA,@SEDE,@USUARIO,@RESPUESTA,@SYS_COMPUTERNAME,@USUARIO
         SELECT @NVOCONSEC=CNSFNOT FROM FNOT WHERE N_FACTURA=@N_FACTURA

         UPDATE FGLO SET CNSFNOT = @NVOCONSEC  WHERE  CNSGLO = @CNSGLO           

      END
   END
END   
   -- SE GENERA SALDO DE LO QUE SE VA A RECUPERAR
   IF @VLRRECUPERAR > 0 
   BEGIN
      SELECT @CNSCXC = CNSCXC, @N_FACTURA = N_FACTURA 
      FROM   FGLO
      WHERE  CNSGLO = @CNSGLO
      -- REVISO QUE NO HAYA UNA RESPUESTA PREVIA DE LA MISMA GLOSA Y SI LA HAY SE RETIRA
      IF EXISTS(SELECT * FROM FCXCDV WHERE CNSGLO=@CNSGLO AND TIPO='G' AND N_FACTURA=@N_FACTURA)
      BEGIN
         DELETE FCXCDV WHERE CNSGLO=@CNSGLO AND TIPO='G' AND N_FACTURA=@N_FACTURA
      END
      -- SE COLOCA COMO SALDO DE LA GLOSA EL VALOR A RECUPERAR

      SELECT @ITEM  = MAX(ITEM) 
      FROM   FCXCDV 
      WHERE  CNSCXC    = @CNSCXC
      AND    N_FACTURA = @N_FACTURA
            
      INSERT INTO FCXCDV(CNSCXC, N_FACTURA, CNSGLO, TIPO, SALDONETO, FECHA, 
                         F_RECIBIDO, F_VENCE, SALDOINICIAL,MARCAPAGO) 
      SELECT @CNSCXC, @N_FACTURA, @CNSGLO, 
             CASE @CNSGLO_O WHEN '' THEN 'G' ELSE 'R' END, @VLRRECUPERAR, GETDATE(), 
             NULL, NULL, @VLRRECUPERAR, 0
   END
   -- SE CIERRA LA GLOSA Y SUS ITEMES
   UPDATE FGLOD SET CERRADA = 1 WHERE CNSGLO = @CNSGLO
   UPDATE FGLO SET CERRADA = 1, FECHARESP =CASE WHEN COALESCE(FECHARESP,'')='' THEN  GETDATE() ELSE FECHARESP END WHERE CNSGLO = @CNSGLO
   -- SE LLAMA AL SPK QUE CIERRA LA NOTA, LA APLICA Y RELIQUIDA CXC
   -- (INCLUYENDO GLOSAS POR QUE LA ENCUENTRA ESTA CERRADA)
   DECLARE @SALDOPF DECIMAL(14,2)
   SELECT @SALDOPF = SALDO FROM FGLO
   WHERE  CNSGLO = @CNSGLO
   PRINT 'SALDO DE GLOSA ANTES DE NOTAS ='+ STR(@SALDOPF)
   SELECT @CNSRPDX = 'INTERNO'
   IF @GNOT = 1
   BEGIN
      IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
      BEGIN
          UPDATE FNOT SET IDCONCEPTO='09', CONCEPTO=2 WHERE CNSFNOT=@NVOCONSEC
      END
      EXEC SPK_NOTASCXC @NVOCONSEC, 'C', @CNSRPDX, @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME
   END   

   EXEC SPK_RELIQUIDA_FTR @CNSCXC ,@N_FACTURA

   IF (SELECT CERRADA FROM FGLO WHERE CNSGLO = @CNSGLO)=1
   BEGIN
      PRINT 'Contabilización Automática.'+CHAR(13)+'RESPUESTA DE gLOSAS'
       IF (SELECT MCUEORDEN_GLOSAS FROM PAR WHERE COMPANIA = @COMPANIA)='Si'
       BEGIN
          EXEC SPK_CONTAB_FGLO @CNSGLO, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @SEDE, @NROCOMPROBANTE
       END
       ELSE
       BEGIN
          IF @VLRRECUPERAR>0
          BEGIN
             PRINT 'No MAneja Cuentas de Orden Solo se Contabiliza Valor a Recuperar'
             EXEC SPK_CONTAB_FGLO @CNSGLO, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @SEDE, @NROCOMPROBANTE
          END
       END
    END
END

