IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_GENNUMEROFACTURA' AND TYPE = 'P')
   DROP PROCEDURE SPK_GENNUMEROFACTURA

GO
CREATE PROCEDURE DBO.SPK_GENNUMEROFACTURA  
@COMPANIA   VARCHAR(2),  
@IDSEDE     VARCHAR(5),  
@CCOSTO     VARCHAR(20) = NULL,
@N_FACTURA  VARCHAR(20) OUTPUT,
@PROCEDENCIA VARCHAR(20)= NULL
WITH ENCRYPTION
AS  
DECLARE @NVOCONSEC   VARCHAR(20)
DECLARE @LONGFTRARS  INT
DECLARE @PREFIJOFAC  VARCHAR(10)
DECLARE @PRE         VARCHAR(20)
DECLARE @CNSFINAL    INT
DECLARE @CNSINICIAL  INT
DECLARE @CNSACTUAL   INT 
DECLARE @VENCIDA     SMALLINT
DECLARE @CNSNUEVO    INT
DECLARE @SEDEPPAL    VARCHAR(6)
DECLARE @CNSRESOL    VARCHAR(20)
BEGIN  
   IF ISNULL(@PROCEDENCIA,'')=''
      SET @PROCEDENCIA='FTR'

   DELETE RPDX WHERE CNS = 'N_FACTURA'
   IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI'
   BEGIN
      PRINT 'CON FDIAN'
      IF DBO.FNK_VALORVARIABLE('FACTSEDE')='NO' AND @PROCEDENCIA<>'FPOS'
      BEGIN
         PRINT 'FACTURA SIN SEDE'
         SELECT @SEDEPPAL=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDSEDEPRINCIPAL')))
         IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@SEDEPPAL)
         BEGIN
            SELECT @SEDEPPAL=IDENTIFICADOR FROM FDIAN WHERE VENCIDA=0 AND PROCEDENCIA=@PROCEDENCIA
            IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@SEDEPPAL)
            BEGIN
               SELECT TOP 1 @SEDEPPAL=IDSEDE FROM FTR ORDER BY F_FACTURA DESC
            END
         END
         SELECT @IDSEDE=@SEDEPPAL
      END
      IF NOT EXISTS(SELECT * FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA=@PROCEDENCIA)
      BEGIN
         PRINT '@IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')+' @PROCEDENCIA='+COALESCE(@PROCEDENCIA,'SIN PROCE')
         RAISERROR('No Existe Resolucion de Facturas Vigente, No se Puede Continuar',1,16)
         RETURN
      END
      SELECT @PREFIJOFAC=COALESCE(PREFIJO,'') FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA=@PROCEDENCIA
	  IF COALESCE(@PREFIJOFAC,'')<>''
	  BEGIN
		SELECT @PRE = '@'+@PROCEDENCIA+'_'+LTRIM(RTRIM(@PREFIJOFAC))
	  END
	  ELSE
	  BEGIN
		 SELECT @PRE = '@'+@PROCEDENCIA
	  END
      IF UPPER(DBO.FNK_VALORVARIABLE('MPREFAC_CCOSTO')) <> 'SI'
      BEGIN
         SELECT @CCOSTO=''
         IF NOT EXISTS(SELECT * FROM USCXS  WHERE PREFIJO=@PRE  AND COMPANIA=@COMPANIA AND IDSEDE=@IDSEDE)
         BEGIN
	         INSERT INTO USCXS (COMPANIA,IDSEDE,BODEGA,IDADICIONAL,PREFIJO,CONSECUTIVO,SERIE,LIMITE)  
	         VALUES(@COMPANIA,@IDSEDE,'','',@PRE,0,0,0)              
         END
         SELECT @CNSACTUAL=COALESCE(CONSECUTIVO,0),@CNSNUEVO=COALESCE(CONSECUTIVO,0)+1  FROM USCXS  WHERE PREFIJO=@PRE  AND COMPANIA=@COMPANIA AND IDSEDE=@IDSEDE

         SELECT @LONGFTRARS=COALESCE(LONGFTR,0),@CNSINICIAL=CNSINICIAL,@CNSFINAL=CNSFINAL,@VENCIDA=VENCIDA,@CNSRESOL=CNSRESOL
         FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA=@PROCEDENCIA
         AND COALESCE(CNSINICIAL,0)<=@CNSNUEVO AND CNSFINAL+1>@CNSNUEVO

         --SELECT * FROM FDIAN
         PRINT '@CNSNUEVO='+STR(@CNSNUEVO)

         IF @CNSNUEVO>@CNSFINAL+1 OR @CNSNUEVO<@CNSINICIAL
         BEGIN
            PRINT '@CNSNUEVO='+LTRIM(RTRIM(STR(@CNSNUEVO)))+'@CNSFINAL='+LTRIM(RTRIM(STR(@CNSFINAL)))+'@CNSINICIAL='+LTRIM(RTRIM(STR(@CNSINICIAL)))
            RAISERROR('Se ha terminado los consecutivos de facturacion Habilitados, No se puede Continuar',1,16)
            RETURN
         END
         IF COALESCE(@CNSRESOL,'')=''
         BEGIN
            RAISERROR('NO existe resolucion para este nro de factura, No se puede Continuar',1,16)
            RETURN
         END
         EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, @PRE, @NVOCONSEC OUTPUT 
          PRINT '@NVOCONSEC='+@NVOCONSEC
         IF LEN(@NVOCONSEC) > @LONGFTRARS
         BEGIN
            SET @LONGFTRARS = LEN(@NVOCONSEC)
         END
         SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC))+LTRIM(RTRIM(@NVOCONSEC))
      END
      ELSE
      BEGIN
         PRINT 'NUMFACTURA CON CCOSTO'
         SELECT @PRE = '@'+@PROCEDENCIA  
         SELECT @PREFIJOFAC = IDADICIONAL FROM USCXS WHERE PREFIJO = @PRE AND IDSEDE = LEFT(@CCOSTO,5)        
         EXEC SPK_GENCONSECUTIVO @COMPANIA, @CCOSTO, @PRE, @NVOCONSEC OUTPUT  
         IF LEN(@NVOCONSEC) > @LONGFTRARS
         BEGIN
            SET @LONGFTRARS = LEN(@NVOCONSEC)
         END
         SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC))+LTRIM(RTRIM(@NVOCONSEC))
      END
   END
  ELSE
  BEGIN
      SELECT @LONGFTRARS = DBO.FNK_VALORVARIABLE('LONGFTRARS')                 
      IF (@LONGFTRARS = 0 OR @LONGFTRARS IS NULL OR @LONGFTRARS='')
      BEGIN
         SELECT @LONGFTRARS = 8
      END
      IF UPPER(DBO.FNK_VALORVARIABLE('MPREFIJOFAC')) = 'SI'
      BEGIN
         PRINT 'MANEJO PREFIJO FAC'
         IF UPPER(DBO.FNK_VALORVARIABLE('MPREFAC_CCOSTO')) = 'SI'
         BEGIN
            PRINT 'NUMFACTURA CON CCOSTO'
            SELECT @PRE = '@'+@PROCEDENCIA           
            SELECT @PREFIJOFAC = IDADICIONAL FROM USCXS WHERE PREFIJO = @PRE AND IDSEDE = LEFT(@CCOSTO,5)        
            EXEC SPK_GENCONSECUTIVO @COMPANIA, @CCOSTO, @PRE, @NVOCONSEC OUTPUT  
            IF LEN(@NVOCONSEC) > @LONGFTRARS
            BEGIN
               SELECT @LONGFTRARS = LEN(@NVOCONSEC)
            END
            IF COALESCE(DBO.FNK_VALORVARIABLE('FTRQUITACEROS'),'')<>'SI'
            BEGIN 
               SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC)) + LTRIM(RTRIM(@NVOCONSEC))
            END
            ELSE
            BEGIN
               SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC)) + LTRIM(RTRIM(@NVOCONSEC))
            END         
         END
         ELSE
         BEGIN           
            IF @IDSEDE = '01'
            BEGIN
               SELECT @PREFIJOFAC = DBO.FNK_VALORVARIABLE('PREFIJOFAC')
            END
            ELSE
            BEGIN
               SELECT @PREFIJOFAC = DBO.FNK_VALORVARIABLE('PREFIJOFAC_'+LTRIM(RTRIM(@IDSEDE)))
            END
            PRINT 'PREFIJOFAC = '+ @PREFIJOFAC
         
            SET @PRE = '@'+@PROCEDENCIA+'_'+LTRIM(RTRIM(@PREFIJOFAC))
            EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, @PRE, @NVOCONSEC OUTPUT  
            IF LEN(@NVOCONSEC) > @LONGFTRARS
            BEGIN
               SET @LONGFTRARS = LEN(@NVOCONSEC)--FTRQUITACEROS
            END
            IF COALESCE(DBO.FNK_VALORVARIABLE('FTRQUITACEROS'),'')<>'SI'
            BEGIN
               SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC))+LTRIM(RTRIM(@NVOCONSEC))
            END
            ELSE
            BEGIN
               SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC))+LTRIM(RTRIM(@NVOCONSEC))
            END       
         END
      END
      ELSE
      BEGIN
         PRINT 'NO MANEJA PREFIJO'     
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE,'@FTR', @NVOCONSEC OUTPUT  
         IF LEN(@NVOCONSEC) > @LONGFTRARS
         BEGIN
            SET @LONGFTRARS = LEN(@NVOCONSEC)
         END
         IF COALESCE(DBO.FNK_VALORVARIABLE('FTRQUITACEROS'),'')<>'SI'
         BEGIN      
            SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         END
      END 
   END      
 
   SELECT  @N_FACTURA = @NVOCONSEC
   INSERT INTO RPDX (CNS,ID1) 
   SELECT 'N_FACTURA', @N_FACTURA
   PRINT '@N_FACTURA =' +@N_FACTURA
END
