IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_PASA_A_MCPE' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_PASA_A_MCPE
END

GO
CREATE PROCEDURE DBO.SPK_PASA_A_MCPE
@NROCOMPROBANTE VARCHAR(20),
@USUARIO        VARCHAR(12)
WITH ENCRYPTION
AS
BEGIN
   INSERT INTO MCPE(COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                    REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE,
                    RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO, CLASECAMBIO)
   SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                    REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, '0', ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE,
                    RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO, 2
   FROM   MCP
   WHERE  MCP.NROCOMPROBANTE = @NROCOMPROBANTE
   INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3,
                    N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO,
                    PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
                    ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP)
   SELECT NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3,
                    N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, '0',
                    PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
                    ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP
   FROM   MCH
   WHERE  MCH.NROCOMPROBANTE = @NROCOMPROBANTE
   IF EXISTS(SELECT * FROM MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE)
   BEGIN
      DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
   END
   IF  EXISTS(SELECT * FROM MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE) 
   BEGIN
       DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE 
   END  

   --ELIMINAR COMPROBANTES DE NIIF
   DECLARE @NIIF VARCHAR(20)
   SELECT @NIIF=NROCOMPROBANTE FROM MCPNIIF WHERE NROCOMPROBANTEMCP=@NROCOMPROBANTE
   IF EXISTS(SELECT * FROM MCHNIIF WHERE NROCOMPROBANTE=@NIIF) 
   BEGIN
      DELETE MCHNIIF WHERE NROCOMPROBANTE=@NIIF
   END
   IF  EXISTS(SELECT * FROM MCPNIIF WHERE NROCOMPROBANTE=@NIIF) 
   BEGIN
      DELETE MCPNIIF WHERE NROCOMPROBANTE=@NIIF
   END 
END

