CREATE OR ALTER PROCEDURE DBO.SPK_ANULARECIBO_CAJA  
@CODCAJA VARCHAR(4),  
@CNSFACJ VARCHAR(20),
@USUARIO VARCHAR(12),
@ANULAFAC BIT=0
WITH ENCRYPTION
AS  
DECLARE @CLASE_FAC   VARCHAR(5)
DECLARE @FPACHEQUE   VARCHAR(3)
DECLARE @BANCO       VARCHAR(3)
DECLARE @SUCURSAL    VARCHAR(2)
DECLARE @CTA_BCO     VARCHAR(40)
DECLARE @CNSDOC      VARCHAR(20)
DECLARE @NODOCUMENTO VARCHAR(20)
DECLARE @VALOR_DOC   DECIMAL(14,2)
DECLARE @TIPOEGRESO  VARCHAR(8)
DECLARE @NOADMISION  VARCHAR(16)
DECLARE @N_FACTURA_CUR   VARCHAR(20)
DECLARE @CNSCXC_CUR      VARCHAR(20)
DECLARE @CNSFPAG_CUR     VARCHAR(20)
DECLARE @VALOR_CUR       DECIMAL(14,2)
DECLARE @IDTERCERO_CUR   VARCHAR(20)
DECLARE @CERRADA         SMALLINT
DECLARE @PROCEDENCIA     VARCHAR(10)
DECLARE @NOPRESTACION    VARCHAR(20)
DECLARE @SEDE            VARCHAR(6)
DECLARE @TIPOPAGO		    VARCHAR(3)
DECLARE @IDTERCERO	    VARCHAR(20)
DECLARE @CNSDOC1		    VARCHAR(20)
DECLARE @IDCATEGORIA     VARCHAR(10)
DECLARE @CNSRESOL     VARCHAR(30)
DECLARE @N_FACTURA     VARCHAR(20)
DECLARE @N_FACTURAPOS     VARCHAR(20)
DECLARE @CNSFCXP     VARCHAR(20)
BEGIN   
	SELECT @CLASE_FAC = CLASE_FAC, @TIPOEGRESO = TIPOEGRESO, @CERRADA = CERRADA, @NOADMISION = NOADMISION, @PROCEDENCIA=PROCEDENCIA,
   @NOPRESTACION=NOPRESTACION, @CNSRESOL=CNSRESOL, @N_FACTURA=N_FACTURA,@N_FACTURAPOS=N_FACTURAPOS
	FROM FCJ WHERE  CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ 
   PRINT 'Revisando factura pos'
   IF COALESCE(@N_FACTURAPOS,'')<>''
   BEGIN
      IF EXISTS(SELECT  * FROM FTR WHERE N_FACTURA=@N_FACTURAPOS AND ESTADO='P' AND COALESCE(TIPOANULACION,'')<>'NC' AND @ANULAFAC=0)
      BEGIN
         RAISERROR('Factura Generada desde caja, se debe anular primero la Factura',16,1)
         RETURN
      END
   END
   SELECT @IDCATEGORIA=IDCATEGORIA FROM CJTE WHERE TIPOEGRESO=@TIPOEGRESO

	SELECT @TIPOPAGO = TIPOPAGO, @IDTERCERO = IDTERCERO, @CNSDOC1 = CNSDOC
	FROM PCJ 
	WHERE CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ
	AND TIPOPAGO = dbo.FNK_VALORVARIABLE('IDCJFPADESCUENT_NOMI')
   
	SELECT N_FACTURA,CNSCXC,CNSFPAG,VALOR,IDTERCERO INTO #A
	FROM FCJPCXC WHERE CNSFACJ=@CNSFACJ AND CODCAJA=@CODCAJA
	SELECT @FPACHEQUE = LEFT(DATO,3) FROM USVGS WHERE IDVARIABLE = 'IDCJFPACHEQUE'
   
	UPDATE FCJ SET ESTADO = 'A', CERRADA = 1, ARCHIVADO = 0
	WHERE  CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ  
     
	IF @CLASE_FAC = 'PAGO'
	BEGIN
		PRINT 'ES DE PAGO'
		DECLARE BCT_CURSOR CURSOR FOR
			SELECT  PCJ.BANCO, PCJ.SUCURSAL, PCJ.CTA_BCO,ISNULL(PCJ.CNSDOC,''), PCJ.NUMERODOCUMENTO, PCJ.VALOR
			FROM    PCJ
			WHERE   PCJ.CODCAJA   = @CODCAJA AND PCJ.CNSFACJ = @CNSFACJ  
			AND     PCJ.TIPOPAGO  = @FPACHEQUE
		  --AND     PCJ.IMPRESO > 0
		OPEN   BCT_CURSOR  
		FETCH NEXT FROM BCT_CURSOR  
		INTO   @BANCO, @SUCURSAL, @CTA_BCO, @CNSDOC, @NODOCUMENTO, @VALOR_DOC
		WHILE @@FETCH_STATUS = 0  
		BEGIN  
			PRINT 'CURSOR NODOCUMENTO=' + @NODOCUMENTO
			UPDATE BCTDD SET ESTADO = 'A', FECHAANU = GETDATE(), ANULADODESDE = 'CAJA',
							  USUARIOANU  = @USUARIO
			WHERE  BANCO       = @BANCO
			AND    SUCURSAL    = @SUCURSAL
			AND    CTA_BCO     = @CTA_BCO
			AND    CNSDOC      = @CNSDOC
			AND    NODOCUMENTO = @NODOCUMENTO
         
			PRINT  'Actualiza El saldo del Banco.'
			UPDATE BCT SET SALDO = SALDO - @VALOR_DOC
			WHERE BCT.BANCO=@BANCO AND BCT.SUCURSAL=@SUCURSAL AND BCT.CTA_BCO=@CTA_BCO  
         
			FETCH NEXT FROM BCT_CURSOR  
			INTO  @BANCO, @SUCURSAL, @CTA_BCO, @CNSDOC, @NODOCUMENTO, @VALOR_DOC
		END
		CLOSE BCT_CURSOR  
		DEALLOCATE BCT_CURSOR

		IF @TIPOEGRESO=DBO.FNK_VALORVARIABLE('IDCJTECONSIGNACION') 
       OR (@IDCATEGORIA=DBO.FNK_VALORVARIABLE('TERCATBANCO') AND @TIPOEGRESO NOT IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('IDCJTETRASBCOCAJA','IDCJTETRASLADOBCO'))) 
		BEGIN
			UPDATE FCJTD SET ASIGNADO = 0 WHERE CODCAJA = @CODCAJA
		END
		IF @TIPOEGRESO = DBO.FNK_VALORVARIABLE('IDCJTETRASLADO')
		BEGIN
			UPDATE FCJTD SET ASIGNADO = 0 WHERE CODCAJA = @CODCAJA
		END
		PRINT 'Anulando Movimiento en Bancos...'
		UPDATE BMOV SET ESTADO='A' WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ

		--EMPIEZO ANULACION DE DOCUMENTO SOPORTE
		IF COALESCE(@CNSRESOL,'')<>'' AND COALESCE(@N_FACTURA,'')<>''
		BEGIN
			SELECT @CNSFCXP=C.CNSFCXP FROM FCJ A INNER JOIN FCXP C ON C.PROCEDENCIA='CAJA' AND C.CAJAMENOR=A.CODCAJA AND A.N_FACTURA=C.N_FACTURA
			WHERE A.CODCAJA=@CODCAJA AND A.CNSFACJ=@CNSFACJ
			
			INSERT INTO FCXPDBCR (CNSFCXP,IDNOTA,ITEM,VALOR,TIPO,FECHA,OBSERVACION,ESTADO,PROCEDENCIA,CUENTA_DB,CUENTA_CR,USUARIO,SYS_COMPUTERNAME,
						MARCACONT,CONTABILIZADA,NROCOMPROBANTE,ENPRESUPUESTO,CCOSTO,NOREFERENCIA,VLR_NETO,IDSERVICIO,ESTADODIAN,CNSRESOL)
			SELECT C.CNSFCXP,DBO.FNK_VALORVARIABLE('IDNOTA_ANULAFCJDS'), 1, C.VALOR, 'DB', DBO.FNK_FECHA_SIN_MLS(GETDATE()),'ANULACION DOCUMENTO SOPORTE:'+A.N_FACTURA,'N','CXP',NULL,NULL,@USUARIO,HOST_NAME(),
					0, 1, A.NROCOMPROBANTE, 0, B.CCOSTO, A.N_FACTURA,C.VALOR,B.CONCEPTO,CASE DBO.FNK_VALORVARIABLE('FCXP_ENVIO_DIAN_AUTO') WHEN 'SI' THEN 1 ELSE 0 END, A.CNSRESOL
			FROM FCJ A INNER JOIN FCJD B ON A.CNSFACJ=B.CNSFACJ AND A.CODCAJA=B.CODCAJA
				INNER JOIN FCXP C ON C.PROCEDENCIA='CAJA' AND C.CAJAMENOR=A.CODCAJA AND A.N_FACTURA=C.N_FACTURA
			WHERE A.CODCAJA=@CODCAJA AND A.CNSFACJ=@CNSFACJ

			
			UPDATE FCXPP SET ESTADO='A' FROM FCXPP INNER JOIN FCXP ON FCXPP.CNSFCXP=FCXP.CNSFCXP WHERE FCXP.CNSFCXP=@CNSFCXP
			UPDATE FCXPPM SET ESTADO='A' FROM FCXPPM INNER JOIN FCXPP ON FCXPP.CNSFCXPPM=FCXPPM.CNSFCXPPM WHERE FCXPP.CNSFCXP=@CNSFCXP

			EXEC DBO.SPK_CALCULOVALORESCXP @CNSFCXP


		END

	END
	ELSE
	BEGIN
		IF (SELECT COALESCE(COUNT(*),0) FROM QXDING WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND NOINGRESO = @NOADMISION) > 0
		BEGIN
			DELETE QXDING WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND NOINGRESO = @NOADMISION
		END
	END
	IF @CLASE_FAC='COBRO' AND @PROCEDENCIA IN('CITAS','CE')
	BEGIN
		IF @PROCEDENCIA='CE'
		BEGIN
			SELECT @SEDE=IDSEDE FROM AUT  WHERE IDAUT=@NOADMISION
		END
		IF @PROCEDENCIA='CITAS'
		BEGIN
			SELECT @SEDE=IDSEDE FROM CIT   WHERE CONSECUTIVO=@NOADMISION
		END
		--IF NOT EXISTS (SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ AND (CLASE_FAC='PAGO' OR CERRADA=1 OR ESTADO='A'))
			EXEC SPK_DEVUELVERECIB_CAJA @CODCAJA,@CNSFACJ,'01',@SEDE
	END



	IF (SELECT COUNT(*) FROM PCJ WHERE CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ
		AND TIPOPAGO = dbo.FNK_VALORVARIABLE('IDCJFPADESCUENT_NOMI')) > 0
	BEGIN
		UPDATE PRS SET ENCAJA = 0, CODCAJA = '', CNSFACJ = '' WHERE IDDEUDOR = @IDTERCERO AND NUMDOCUMENTO = @CNSDOC1
	END

	DELETE FROM PCJ   WHERE  CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ  --AND IMPRESO = 0
	DELETE FROM FCJDD WHERE  CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ  
	DELETE FROM FCJD  WHERE  CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ  
   -- BORRADO DE CXC
	DECLARE CUR_CXC CURSOR FOR
		SELECT N_FACTURA,CNSCXC,CNSFPAG,VALOR,IDTERCERO
		FROM #A
	OPEN CUR_CXC
	FETCH NEXT FROM CUR_CXC
	INTO @N_FACTURA_CUR,@CNSCXC_CUR,@CNSFPAG_CUR,@VALOR_CUR,@IDTERCERO_CUR
	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC SPK_ADMIN_PAGOS 'CXC', @N_FACTURA_CUR, @CNSCXC_CUR, @CNSFPAG_CUR, 'DELETE', @VALOR_CUR,
                          @IDTERCERO_CUR, @USUARIO, '', '', '', '', 'CAJA', 'P',
                          NULL, NULL, @CNSFACJ, @CODCAJA, '', '', ''
		FETCH NEXT FROM CUR_CXC
		INTO @N_FACTURA_CUR,@CNSCXC_CUR,@CNSFPAG_CUR,@VALOR_CUR,@IDTERCERO_CUR
	END
	CLOSE CUR_CXC
	DEALLOCATE CUR_CXC
--   SE QUITA POR QUE SE REPITE Y SE HACE EN EL ANTERIOR CURSOR 
  -- DELETE FCJPCXC WHERE CNSFACJ=@CNSFACJ AND CODCAJA=@CODCAJA
	DELETE FCXCDV WHERE N_FACTURA= @N_FACTURA_CUR AND CNSCXC= @CNSCXC_CUR
	DELETE FCXCD WHERE N_FACTURA= @N_FACTURA_CUR AND CNSCXC= @CNSCXC_CUR 
	DELETE FCXC WHERE CNSCXC= @CNSCXC_CUR

	UPDATE FTR SET INDCARTERA=0 , INDCXC=0 , INDASIGCXC=0, EQUIMARCA='' WHERE N_FACTURA= @N_FACTURA_CUR
	DROP TABLE #A
END

