CREATE OR ALTER PROCEDURE DBO.SPK_APLICA_FNOT_MASIVA
	@CNSRPDX  VARCHAR(20),
	@COMPANIA VARCHAR(2),
	@IDSEDE   VARCHAR(20),
	@USUARIO  VARCHAR(20),
	@CLASE    VARCHAR(1)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

DECLARE @CNSCXC VARCHAR(20);
DECLARE @N_FACTURA VARCHAR(20);
DECLARE @TIPO VARCHAR(1);
DECLARE @VLRACEPTADO DECIMAL(14, 2);
DECLARE @CONCEPTO VARCHAR(20);
DECLARE @DESCRIPCION VARCHAR(512);
DECLARE @IDAREA VARCHAR(20);
DECLARE @CCOSTO VARCHAR(20);
DECLARE @PREFIJO VARCHAR(2);
DECLARE @OBSERVACION VARCHAR(512);
DECLARE @CNSFNOT VARCHAR(20);
DECLARE @IDTERCERO VARCHAR(20);
DECLARE @SYS_COMPUTERNAME VARCHAR(255);
DECLARE @ITEM INT;

BEGIN
	IF COALESCE(@CNSRPDX, '') = ''
		RAISERROR('@CNSRPDX es obligatorio', 16, 1);
	IF COALESCE(@COMPANIA, '') = ''
		RAISERROR('@COMPANIA es obligatorio', 16, 1);
	IF COALESCE(@IDSEDE, '') = ''
		RAISERROR('@IDSEDE es obligatorio', 16, 1);
	IF COALESCE(@USUARIO, '') = ''
		RAISERROR('@USUARIO es obligatorio', 16, 1);
	IF COALESCE(@CLASE, '') = ''
		RAISERROR('@CLASE es obligatorio', 16, 1);

	IF NOT EXISTS (SELECT 1 FROM RPDX WHERE CNS = @CNSRPDX)
		RAISERROR('No existen registros en RPDX para el consecutivo indicado', 16, 1);

	SELECT @SYS_COMPUTERNAME = HOST_NAME();

	DECLARE FNOTMASIVA CURSOR LOCAL FAST_FORWARD FOR
		SELECT FCXCD.CNSCXC,
			FTR.N_FACTURA,
			FTR.IDTERCERO,
			'F',
			RPDX.VALOR1,
			RPDX.ID2,
			RPDX.STRINGMEDIO2,
			RPDX.ID3,
			RPDX.ID4,
			RPDX.ID5,
			RPDX.STRINGGRANDE1,
			RPDX.ITEM
		FROM RPDX
		INNER JOIN FTR ON RPDX.ID1 = FTR.N_FACTURA
		LEFT JOIN FCXCD ON FTR.N_FACTURA = FCXCD.N_FACTURA
		WHERE RPDX.CNS = @CNSRPDX
			AND RPDX.VALOR1 > 0;

	OPEN FNOTMASIVA;
	FETCH NEXT FROM FNOTMASIVA
	INTO @CNSCXC, @N_FACTURA, @IDTERCERO, @TIPO, @VLRACEPTADO, @CONCEPTO, @DESCRIPCION, @IDAREA, @CCOSTO, @PREFIJO, @OBSERVACION, @ITEM;

	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@FNOTC', @CNSFNOT OUTPUT;
		SELECT @CNSFNOT = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFNOT)) + LTRIM(RTRIM(@CNSFNOT)), SPACE(1), '0');

		INSERT INTO FNOT (
			CNSFNOT, CLASE, N_FACTURA, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION,
			MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA,
			USUARIO, CNSCXC, CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU,
			RAZONANU, PROCEDENCIA, CNSGLO, APLICADAA, LIBERAHADM,
			CONCEPTO, IDCONCEPTO, VALORCONCEPTO, CNSMASIVO
		)
		SELECT @CNSFNOT, @CLASE, @N_FACTURA, @IDTERCERO, GETDATE(),
			@VLRACEPTADO, @OBSERVACION, 0, 0, 0, NULL, 0, @COMPANIA, @USUARIO, @CNSCXC, 0, 'O', NULL, NULL, NULL, NULL,
			'NOTAS', '', 'C', 0, 0, COALESCE(@CONCEPTO, ''), @VLRACEPTADO, @CNSRPDX;

		INSERT INTO FNOTD (
			CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
			VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION
		)
		SELECT @CNSFNOT, @CLASE, 1, CASE WHEN @CLASE = 'C' THEN 'C' ELSE 'S' END, COALESCE(@CONCEPTO, ''), @CONCEPTO, 1,
			@VLRACEPTADO, @VLRACEPTADO, @COMPANIA, @USUARIO, @OBSERVACION;

		EXEC SPK_NOTASCXC @CNSFNOT, 'C', @CNSRPDX, @IDSEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME;

		DELETE FROM RPDX WHERE CNS = @CNSRPDX AND ITEM = @ITEM;

		FETCH NEXT FROM FNOTMASIVA
		INTO @CNSCXC, @N_FACTURA, @IDTERCERO, @TIPO, @VLRACEPTADO, @CONCEPTO, @DESCRIPCION, @IDAREA, @CCOSTO, @PREFIJO, @OBSERVACION, @ITEM;
	END;

	CLOSE FNOTMASIVA;
	DEALLOCATE FNOTMASIVA;
END;

