IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_FACTURACE_ESCIN' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_FACTURACE_ESCIN
END

GO
CREATE PROCEDURE DBO.SPK_FACTURACE_ESCIN
@CNSRPDX      VARCHAR(20),
@NIT          VARCHAR(20),
@COMPANIA     VARCHAR(2),
@IDSEDE       VARCHAR(5),
@USUARIO      VARCHAR(12),
@IDTERCEROCA1 VARCHAR(20),
@CETIPOHOSP   VARCHAR(6) = FALSE,  -- PARAM. Que Especifica el tipo de manejo de Planes - Contratos 
@IDPLANPAR    VARCHAR(6) = NULL,    -- EL PLAN EN CEHOSP
@FECHAFAC     DATETIME   = NULL
WITH ENCRYPTION
AS 
DECLARE @NOAUT VARCHAR(16)
BEGIN
   DECLARE AUT_CURSOR CURSOR FOR
   SELECT  AUT.NOAUT   FROM AUT
   WHERE   AUT.CNSFACT  = @CNSRPDX  
   AND     AUT.MARCAFAC = 1
   AND   COALESCE(FACTURABLE,0)=1 
   AND   COALESCE(VALORTOTAL,0)>0 
   AND  COALESCE(AUT.DESCUENTO, 0) < CASE WHEN AUT.TIPODTO='P' THEN 100 ELSE AUT.VALORTOTAL END
   OPEN AUT_CURSOR  
   FETCH NEXT FROM AUT_CURSOR  
   INTO @NOAUT
   WHILE @@FETCH_STATUS = 0  
   BEGIN     
      EXEC SPK_FACTURACE_N @NOAUT, @NIT, @COMPANIA, @IDSEDE, @USUARIO, 
                           '', '', '', '', '','CE', @IDTERCEROCA1, @CETIPOHOSP, @IDPLANPAR, @FECHAFAC
      FETCH NEXT FROM AUT_CURSOR  
      INTO @NOAUT
   END
   CLOSE AUT_CURSOR
   DEALLOCATE AUT_CURSOR
END

