IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_GENNUMERO_BOLETA' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_GENNUMERO_BOLETA
END
GO
CREATE PROCEDURE DBO.SPK_GENNUMERO_BOLETA  
@COMPANIA   VARCHAR(2),  
@IDSEDE     VARCHAR(5),  
@CCOSTO     VARCHAR(20) = NULL,
@N_FACTURA  VARCHAR(20) OUTPUT  
WITH ENCRYPTION
AS  
DECLARE @NVOCONSEC   VARCHAR(20)
DECLARE @LONGFTRARS  INT
DECLARE @PREFIJOFAC  VARCHAR(10)
DECLARE @PRE         VARCHAR(20)
DECLARE @CNSFINAL    INT
DECLARE @CNSINICIAL  INT
DECLARE @CNSACTUAL   INT 
DECLARE @VENCIDA     SMALLINT
DECLARE @CNSNUEVO    INT
DECLARE @SEDEPPAL    VARCHAR(6)
DECLARE @CNSRESOL    VARCHAR(20)
BEGIN  
   PRINT 'CON FDIAN'
   IF DBO.FNK_VALORVARIABLE('FACTSEDE')='NO'
   BEGIN
      SELECT @SEDEPPAL=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDSEDEPRINCIPAL')))
      IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@SEDEPPAL)
      BEGIN
         SELECT @SEDEPPAL=IDENTIFICADOR FROM FDIAN WHERE VENCIDA=0 AND PROCEDENCIA='BOLE'
         IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@SEDEPPAL)
         BEGIN
            SELECT TOP 1 @SEDEPPAL=IDSEDE FROM FTR ORDER BY F_FACTURA DESC
         END
      END
      SELECT @IDSEDE=@SEDEPPAL
   END
   IF NOT EXISTS(SELECT * FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA='BOLE')
   BEGIN
      RAISERROR('No Existe Resolucion de Facturas Vigente, No se Puede Continuar',1,16)
      RETURN
   END
   SELECT @PREFIJOFAC=COALESCE(PREFIJO,'') FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA='BOLE'
   IF COALESCE(@PREFIJOFAC,'')<>''
   BEGIN
	   SELECT @PRE = '@FTR_'+LTRIM(RTRIM(@PREFIJOFAC))
   END
   ELSE
   BEGIN
	   SELECT @PRE = '@FTR'
   END
   PRINT  '@PRE ='+@PRE
   SELECT @CCOSTO=''
   IF EXISTS(SELECT * FROM USCXS  WHERE PREFIJO=@PRE  AND COMPANIA=@COMPANIA AND IDSEDE=@IDSEDE)
   BEGIN
      SELECT @CNSACTUAL=COALESCE(CONSECUTIVO,0),@CNSNUEVO=COALESCE(CONSECUTIVO,0)+1  
      FROM USCXS  WHERE PREFIJO=@PRE  AND COMPANIA=@COMPANIA AND IDSEDE=@IDSEDE
  END
  ELSE
  BEGIN
      SELECT @CNSACTUAL=0,@CNSNUEVO=1
  END
   
   SELECT @LONGFTRARS=COALESCE(LONGFTR,0),@CNSINICIAL=CNSINICIAL,@CNSFINAL=CNSFINAL,@VENCIDA=VENCIDA,@CNSRESOL=CNSRESOL
   FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA='BOLE'
   AND CNSINICIAL<=@CNSNUEVO AND CNSFINAL+1>@CNSNUEVO

   --SELECT * FROM FDIAN
   PRINT '@CNSNUEVO='+STR(COALESCE(@CNSNUEVO,0))

   IF @CNSNUEVO>@CNSFINAL+1 OR @CNSNUEVO<@CNSINICIAL
   BEGIN
      PRINT '@CNSNUEVO='+LTRIM(RTRIM(STR(@CNSNUEVO)))+'@CNSFINAL='+LTRIM(RTRIM(STR(@CNSFINAL)))+'@CNSINICIAL='+LTRIM(RTRIM(STR(@CNSINICIAL)))
      RAISERROR('Se ha terminado los consecutivos de facturacion Habilitados, No se puede Continuar',1,16)
      RETURN
   END
   IF COALESCE(@CNSRESOL,'')=''
   BEGIN
      RAISERROR('NO existe resolucion para este nro de factura, No se puede Continuar',1,16)
      RETURN
   END
   EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, @PRE, @NVOCONSEC OUTPUT 
      PRINT '@NVOCONSEC='+@NVOCONSEC
   IF LEN(@NVOCONSEC) > @LONGFTRARS
   BEGIN
      SET @LONGFTRARS = LEN(@NVOCONSEC)
   END
   SELECT @NVOCONSEC = REPLACE(SPACE(@LONGFTRARS - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
   SELECT @NVOCONSEC = LTRIM(RTRIM(@PREFIJOFAC))+LTRIM(RTRIM(@NVOCONSEC))

   SELECT  @N_FACTURA = @NVOCONSEC
END

