CREATE OR ALTER PROCEDURE DBO.SPK_GENERAR_RIPS_JSON
	@CNSFCT VARCHAR(20),
	@TIPODOC VARCHAR(20),
	@GENERAR VARCHAR(20) = N'SI',
	@SOLO_META VARCHAR(3) = NULL
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @CNSFACT VARCHAR(20) = RTRIM(LTRIM(@CNSFCT));
	DECLARE @ESGLOSA BIT;
	DECLARE @XML_BASE64 NVARCHAR(MAX);
	DECLARE @CNSFCT_FTR VARCHAR(20);
	DECLARE @CNSDOC_PERSIST VARCHAR(20);
	DECLARE @N_FACTURA VARCHAR(20);
	DECLARE @CAPITA BIT;
	DECLARE @TIPOFACT VARCHAR(2);
	DECLARE @TIPOCAP SMALLINT;
	DECLARE @PROCEDENCIA VARCHAR(20);
	DECLARE @IDPLAN VARCHAR(6);
	DECLARE @CUV VARCHAR(256);
	DECLARE @FRADICA_RIPS DATETIME;
	DECLARE @JSON_RESPUESTA VARCHAR(MAX);
	DECLARE @RIPSJSON VARCHAR(MAX);
	DECLARE @NOMBREXML VARCHAR(256);
	DECLARE @XML VARCHAR(MAX);
	DECLARE @NOMBREJSON VARCHAR(120);

		IF @TIPODOC='FACTURA'
		BEGIN
			PRINT ' IF @TIPODOC=FACTURA'
			SELECT @N_FACTURA=N_FACTURA, @CAPITA=COALESCE(CAPITADA,0), @TIPOFACT=TIPOFAC,@TIPOCAP=TIPOCAP, @PROCEDENCIA=PROCEDENCIA, @IDPLAN=FTR.IDPLAN, @CNSFCT_FTR=CNSFCT
			FROM FTR WHERE CNSFCT=@CNSFACT
		END
		ELSE IF @TIPODOC='AJUSTE'
		BEGIN
			SET @N_FACTURA = NULL
			SET @ESGLOSA = 0
			SET @CNSFCT_FTR = NULL

			/* Prioridad 1: glosa (CNSGLO) */
			SELECT TOP 1
				@N_FACTURA=FGLO.N_FACTURA,
				@CAPITA=COALESCE(FTR.CAPITADA,0),
				@TIPOFACT=FTR.TIPOFAC,
				@TIPOCAP=FTR.TIPOCAP,
				@ESGLOSA=1,
				@CNSFCT_FTR=FTR.CNSFCT
			FROM FGLO
			INNER JOIN FTR ON FTR.N_FACTURA=FGLO.N_FACTURA
			WHERE RTRIM(FGLO.CNSGLO)=@CNSFACT

			/* Prioridad 2: factura (CNSFCT) */
			IF COALESCE(@N_FACTURA,'')=''
			BEGIN
				SELECT TOP 1
					@N_FACTURA=FTR.N_FACTURA,
					@CAPITA=COALESCE(CAPITADA,0),
					@TIPOFACT=TIPOFAC,
					@TIPOCAP=TIPOCAP,
					@ESGLOSA=0,
					@CNSFCT_FTR=FTR.CNSFCT
				FROM FTR
				WHERE RTRIM(FTR.CNSFCT)=@CNSFACT
			END

			PRINT '@N_FACTURA='+COALESCE(@N_FACTURA,'NO TENGO NADA')
		END
		ELSE
		BEGIN
			SELECT @N_FACTURA=FTR.N_FACTURA, @CAPITA=COALESCE(CAPITADA,0), @TIPOFACT=TIPOFAC,@TIPOCAP=TIPOCAP
			FROM FNOT INNER JOIN  FTR ON FNOT.N_FACTURA=FTR.N_FACTURA
			WHERE FNOT.CNSFNOT=@CNSFACT
		END

		IF COALESCE(@CNSFCT_FTR,'')='' AND COALESCE(@N_FACTURA,'')<>''
			SELECT @CNSFCT_FTR=CNSFCT FROM FTR WHERE N_FACTURA=@N_FACTURA

		SELECT  @CUV  = COALESCE(FTRJSON.CUV,'')
			,@FRADICA_RIPS = COALESCE(FTRJSON.FRADICA_RIPS,'')
			,@JSON_RESPUESTA  = COALESCE(FTRJSON.JSON_RESPUESTA,'')
			,@RIPSJSON = COALESCE(FTRJSON.JSON_ENVIO,'')
		FROM FTRJSON INNER JOIN FTR ON FTRJSON.CNSFCT=FTR.CNSFCT
		WHERE FTR.N_FACTURA=@N_FACTURA

		/* Lectura post-job async: si GENERAR=NO y no hay JSON persistido, regenerar (mismo efecto que SSMS con GENERAR=SI). */
		IF UPPER(LTRIM(RTRIM(COALESCE(@GENERAR, N'SI')))) = N'NO'
		   AND COALESCE(@RIPSJSON, N'') = N''
		BEGIN
			SET @GENERAR = N'SI';
		END

		IF UPPER(LTRIM(RTRIM(COALESCE(@SOLO_META, N'')))) = N'SI'
		BEGIN
			SELECT N'OK' AS OK
			     , @CNSFACT AS CNSFCT
			     , @N_FACTURA AS N_FACTURA
			     , @TIPODOC AS TIPODOC
			     , CAST(COALESCE(@CAPITA, 0) AS BIT) AS ISCAPITA
			     , COALESCE(@TIPOCAP, 0) AS TIPOCAP
			     , @CUV AS CUV
			     , @FRADICA_RIPS AS FRADICA_RIPS
			     , @JSON_RESPUESTA AS JSON_RESPUESTA
			     , CASE WHEN COALESCE(@RIPSJSON, N'') <> N'' THEN 1 ELSE 0 END AS TIENE_JSON
			     , COALESCE(DATALENGTH(@RIPSJSON), 0) AS TAMANIO_BYTES
			     , CAST(NULL AS NVARCHAR(MAX)) AS RIPSJSON
			;
			RETURN;
		END

		IF COALESCE(@CUV,'')=''
			SELECT  @CUV=CUV FROM FTR WHERE N_FACTURA=@N_FACTURA

		PRINT CONCAT(
			'[SPK_GENERAR_RIPS_JSON] Contexto | CNSFCT=', COALESCE(@CNSFACT,''),
			' | CNSFCT_FTR=', COALESCE(@CNSFCT_FTR,''),
			' | N_FACTURA=', COALESCE(@N_FACTURA,''),
			' | TIPODOC=', COALESCE(@TIPODOC,''),
			' | CAPITA=', CONVERT(VARCHAR(5), COALESCE(@CAPITA,0)),
			' | TIPOCAP=', CONVERT(VARCHAR(10), COALESCE(@TIPOCAP,0)),
			' | TIPOFACT=', COALESCE(@TIPOFACT,''),
			' | PROCEDENCIA=', COALESCE(@PROCEDENCIA,''),
			' | IDPLAN=', COALESCE(@IDPLAN,''),
			' | GENERAR=', COALESCE(@GENERAR,''),
			' | SOLO_META=', COALESCE(@SOLO_META,''),
			' | TIENE_JSON_PERSISTIDO=', CASE WHEN COALESCE(@RIPSJSON,N'')<>N'' THEN 'SI' ELSE 'NO' END
		);

		IF EXISTS(SELECT 1 FROM FTR WHERE N_fACTURA=@N_FACTURA AND COALESCE(FACTE,0)=2)
		BEGIN
			PRINT 'DFDF'
			IF @TIPODOC='FACTURA' OR @TIPODOC='AJUSTE'
			BEGIN
				PRINT 'IF @TIPODOC=''FACTURA'' OR @TIPODOC=''AJUSTE'' VIENE : TIPODOC: '  +  @TIPODOC
				SELECT @NOMBREXML=@N_FACTURA+'.xml'
				IF COALESCE(@XML,'')=''
				BEGIN
					SELECT @XML = CAST('' AS XML).value('xs:base64Binary(sql:column("binaryValue"))', 'varchar(max)')
					FROM (
						SELECT [binaryValue] = CAST(dbo.FNK_AttachedDocument(COALESCE(@CNSFCT_FTR,@CNSFACT),'fv') AS VARBINARY(MAX))
					) AS conv;
				END
				IF COALESCE(@XML,'')=''
				BEGIN
					SELECT TOP 1 @XML=XML_BASE64
					FROM FDIANR
					WHERE CNSDOCUMENTO=COALESCE(@CNSFCT_FTR,@CNSFACT)
					  AND TIPO='FV'
					  AND METODO='SendBillSync'
					  AND COALESCE(XML_BASE64,'')<>''
					ORDER BY ITEM DESC
				END
			END

			BEGIN
				PRINT 'SINO ES FACTURA O AJUSTE'
				IF COALESCE(@CUV,'')='' AND @TIPODOC='AJUSTE'
				BEGIN
					  SELECT 'KO' KO
					  SELECT 'La Factura '+@N_FACTURA+'. No esta Registrada en el SISPRO, No se puede Continuar' AS ERROR
					  RETURN
				END

				SELECT @NOMBREXML=ATTACHED_DOCNAME FROM FTRE WHERE FTRN_FACTURA=@N_FACTURA AND N_FACTURA =  @CNSFACT
                SELECT @NOMBREJSON=@CNSFACT+'.json'

				IF @TIPODOC='AJUSTE'
				BEGIN
					PRINT 'VOY POR AJUSTES'
					SELECT TOP 1 @NOMBREXML=ATTACHED_DOCNAME,@NOMBREJSON=FTRN_FACTURA+'.json' FROM FTRE WHERE FTRN_FACTURA=@N_FACTURA
					IF @CAPITA= 1
					BEGIN
						IF EXISTS(SELECT 1 FROM FTR INNER JOIN PPT ON FTR.IDTERCERO=PPT.IDTERCERO AND FTR.IDPLAN=PPT.IDPLAN
								AND COALESCE(PPT.PGP,0)=1 AND FTR.N_FACTURA=@N_FACTURA)
						BEGIN
							IF COALESCE(@GENERAR,'SI')='SI'
							BEGIN
								PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] EXEC SPK_RIPS_JSON_AJUSTE_PGP @CNSFACT=', COALESCE(@CNSFACT,''), ', @URL_PATH=NULL (AJUSTE PGP)');
								EXEC SPK_RIPS_JSON_AJUSTE_PGP @CNSFACT,NULL,@RIPSJSON OUTPUT
							END
							IF COALESCE(@GENERAR,'SI')='SI'
							   AND COALESCE(@RIPSJSON,N'')<>N''
							   AND COALESCE(@CNSFACT,N'')<>N''
							BEGIN
								EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'AJUSTE', @CNSDOC = @CNSFACT, @JSON_ENVIO = @RIPSJSON;
							END
							SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(0 AS BIT) AS ISCAPITA , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
						END
						ELSE
						BEGIN
							IF COALESCE(@TIPOCAP,0)< 4
							BEGIN
								PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] AJUSTE CAPITA TIPOCAP<4: NO ejecuta generador (devuelve RIPSJSON actual). TIPOCAP=', CONVERT(VARCHAR(10), COALESCE(@TIPOCAP,0)));
								SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(@CAPITA AS BIT) AS ISCAPITA,@TIPOCAP AS TIPOCAP , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
							END
							IF COALESCE(@TIPOCAP,0)=4
							BEGIN
								PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] AJUSTE CAPITA TIPOCAP=4: NO ejecuta SPK_RIPS_JSON_FTR_CAPMASI (solo SELECT). N_FACTURA=', COALESCE(@N_FACTURA,''), ' TIPOCAP=', CONVERT(VARCHAR(10), COALESCE(@TIPOCAP,0)));
								SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(@CAPITA AS BIT) AS ISCAPITA,@TIPOCAP  AS TIPOCAP , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
							END
						END
						RETURN
					END
					IF COALESCE(@GENERAR,'SI')='SI'
					BEGIN
						PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] EXEC SPK_RIPS_JSON_AJUSTE_IND @CNSFACT=', COALESCE(@CNSFACT,''), ', @URL_PATH=NULL (AJUSTE IND)');
						EXEC SPK_RIPS_JSON_AJUSTE_IND @CNSFACT,NULL,@RIPSJSON OUTPUT
					END
					IF COALESCE(@GENERAR,'SI')='SI'
					   AND COALESCE(@RIPSJSON,N'')<>N''
					   AND COALESCE(@CNSFACT,N'')<>N''
					BEGIN
						EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'AJUSTE', @CNSDOC = @CNSFACT, @JSON_ENVIO = @RIPSJSON;
					END

					SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(0 AS BIT) AS ISCAPITA , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
					RETURN
				END

				IF @TIPODOC='NOTADB' OR  @TIPODOC='NOTACR'
				BEGIN
					PRINT 'IF @TIPODOC=''NOTADB'' OR  @TIPODOC=''NOTACR'''
					IF NOT EXISTS(SELECT 1 FROM FNOT WHERE N_fACTURA=@N_FACTURA AND CNSFNOT=@CNSFACT AND COALESCE(FACTE,0)=2)
					BEGIN
						SELECT 'KO' KO
						SELECT 'La Nota DB-CR no Existe o no se ha Notificado a la Dian' AS ERROR
						RETURN
					END

					IF @TIPODOC='NOTACR'
					BEGIN
						SELECT @XML= dbo.FNK_AttachedDocument(@CNSFACT,'NC')
						EXEC SPK_RIPS_JSON_NDBCR_IND @CNSFACT,NULL,@RIPSJSON OUTPUT
						IF COALESCE(@RIPSJSON,N'')<>N''
						   AND COALESCE(@CNSFACT,N'')<>N''
						BEGIN
							EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'NOTACR', @CNSDOC = @CNSFACT, @JSON_ENVIO = @RIPSJSON;
						END
						SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(0 AS BIT) AS ISCAPITA , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
						RETURN
					END
					ELSE
					BEGIN
						SELECT @XML= dbo.FNK_AttachedDocument(@CNSFACT,'ND')
						EXEC SPK_RIPS_JSON_NDBCR_IND @CNSFACT,NULL,@RIPSJSON OUTPUT
						IF COALESCE(@RIPSJSON,N'')<>N''
						   AND COALESCE(@CNSFACT,N'')<>N''
						BEGIN
							EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'NOTADB', @CNSDOC = @CNSFACT, @JSON_ENVIO = @RIPSJSON;
						END
						SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(0 AS BIT) AS ISCAPITA , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
						RETURN

					END
				END  -- DEL @TIPODOC='NOTADB' OR  @TIPODOC='NOTACR'
			END -- DEL SINO ES FACTURA O AJUSTE
			SELECT @NOMBREJSON=@N_FACTURA+'.json'
			IF @CAPITA= 1
            BEGIN
               IF EXISTS(SELECT 1 FROM FTR INNER JOIN PPT ON FTR.IDTERCERO=PPT.IDTERCERO AND FTR.IDPLAN=PPT.IDPLAN AND COALESCE(PPT.PGP,0)=1 AND FTR.N_FACTURA=@N_FACTURA)
               BEGIN
				   IF @TIPODOC='AJUSTE'
					BEGIN
						PRINT 'VOY POR AJUSTES'
						SELECT TOP 1 @NOMBREXML=ATTACHED_DOCNAME,@NOMBREJSON=FTRN_FACTURA+'.json' FROM FTRE WHERE FTRN_FACTURA=@N_FACTURA

						IF EXISTS(SELECT 1 FROM FTR INNER JOIN PPT ON FTR.IDTERCERO=PPT.IDTERCERO AND FTR.IDPLAN=PPT.IDPLAN
								AND COALESCE(PPT.PGP,0)=1 AND FTR.N_FACTURA=@N_FACTURA)
						BEGIN
								PRINT 'EXEC SPK_RIPS_JSON_NOTAAJUSTE_PGP '''+ @CNSFACT+''' ----- '
							IF COALESCE(@GENERAR,'SI')='SI'
							BEGIN
								PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] EXEC SPK_RIPS_JSON_NOTAAJUSTE_PGP @CNSFACT=', COALESCE(@CNSFACT,''), ', @URL_PATH=NULL');
								EXEC SPK_RIPS_JSON_NOTAAJUSTE_PGP @CNSFACT,NULL,@RIPSJSON OUTPUT
							END
							IF COALESCE(@GENERAR,'SI')='SI'
							   AND COALESCE(@RIPSJSON,N'')<>N''
							   AND COALESCE(@CNSFACT,N'')<>N''
							BEGIN
								EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'AJUSTE', @CNSDOC = @CNSFACT, @JSON_ENVIO = @RIPSJSON;
							END
							SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(0 AS BIT) AS ISCAPITA , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
						END
						ELSE
						BEGIN
							IF COALESCE(@TIPOCAP,0)< 4
							BEGIN
								PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] AJUSTE CAPITA no-PGP TIPOCAP<4: NO ejecuta generador. TIPOCAP=', CONVERT(VARCHAR(10), COALESCE(@TIPOCAP,0)));
								SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(@CAPITA AS BIT) AS ISCAPITA,@TIPOCAP AS TIPOCAP , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
							END
							IF COALESCE(@TIPOCAP,0)=4
							BEGIN
								PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] AJUSTE CAPITA no-PGP TIPOCAP=4: NO ejecuta SPK_RIPS_JSON_FTR_CAPMASI (solo SELECT). N_FACTURA=', COALESCE(@N_FACTURA,''));
								SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(@CAPITA AS BIT) AS ISCAPITA,@TIPOCAP  AS TIPOCAP , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
							END
						END
						RETURN

					END
					ELSE
					BEGIN
             PRINT ' FTR PPG '
				     PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] EXEC SPK_RIPS_JSON_FTR_PGP @N_FACTURA=', COALESCE(@N_FACTURA,''), ', @URL_PATH=NULL (FACTURA PGP)');
				     EXEC SPK_RIPS_JSON_FTR_PGP @N_FACTURA,NULL,@RIPSJSON OUTPUT
					   PRINT 'EXEC SPK_RIPS_JSON_FTR_PGP '''+ @CNSFACT+''' ----- '
					IF COALESCE(@RIPSJSON,N'')<>N''
					   AND COALESCE(@CNSFCT_FTR,@CNSFACT,N'')<>N''
					BEGIN
						SET @CNSDOC_PERSIST = COALESCE(@CNSFCT_FTR,@CNSFACT);
						EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'FACTURA', @CNSDOC = @CNSDOC_PERSIST, @JSON_ENVIO = @RIPSJSON;
					END
				     SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(0 AS BIT) AS ISCAPITA , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
             RETURN
					END
               END
               ELSE
               BEGIN
                  IF COALESCE(@TIPOCAP,0)< 4
                  BEGIN
					PRINT CONCAT(
						'[SPK_GENERAR_RIPS_JSON] FACTURA CAPITA TIPOCAP<4 -> EXEC SPK_RIPS_JSON_FTR_CAPI',
						' @N_FACTURA=', COALESCE(@N_FACTURA,''),
						' | CNSFCT=', COALESCE(@CNSFACT,''),
						' | TIPOCAP=', CONVERT(VARCHAR(10), COALESCE(@TIPOCAP,0)),
						' | GENERAR=', COALESCE(@GENERAR,'')
					);
	   			      EXEC SPK_RIPS_JSON_FTR_CAPI @N_FACTURA,NULL,@RIPSJSON OUTPUT
					IF COALESCE(@RIPSJSON,N'')<>N''
					   AND COALESCE(@CNSFCT_FTR,@CNSFACT,N'')<>N''
					BEGIN
						SET @CNSDOC_PERSIST = COALESCE(@CNSFCT_FTR,@CNSFACT);
						EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'FACTURA', @CNSDOC = @CNSDOC_PERSIST, @JSON_ENVIO = @RIPSJSON;
					END
		   		      SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(@CAPITA AS BIT) AS ISCAPITA,@TIPOCAP AS TIPOCAP , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
                  END
                  IF COALESCE(@TIPOCAP,0)=4
                  BEGIN
					PRINT CONCAT(
						'[SPK_GENERAR_RIPS_JSON] FACTURA CAPITA TIPOCAP=4 -> EXEC SPK_RIPS_JSON_FTR_CAPMASI',
						' @N_FACTURA=', COALESCE(@N_FACTURA,''),
						' | @URL_PATH=NULL',
						' | @RIPSJSON OUTPUT',
						' | CNSFCT=', COALESCE(@CNSFACT,''),
						' | CNSFCT_FTR=', COALESCE(@CNSFCT_FTR,''),
						' | TIPODOC=', COALESCE(@TIPODOC,''),
						' | CAPITA=', CONVERT(VARCHAR(5), COALESCE(@CAPITA,0)),
						' | TIPOCAP=', CONVERT(VARCHAR(10), COALESCE(@TIPOCAP,0)),
						' | TIPOFACT=', COALESCE(@TIPOFACT,''),
						' | PROCEDENCIA=', COALESCE(@PROCEDENCIA,''),
						' | IDPLAN=', COALESCE(@IDPLAN,''),
						' | GENERAR=', COALESCE(@GENERAR,'')
					);
		   		      EXEC SPK_RIPS_JSON_FTR_CAPMASI @N_FACTURA,NULL,@RIPSJSON OUTPUT
					PRINT CONCAT(
						'[SPK_GENERAR_RIPS_JSON] Retorno SPK_RIPS_JSON_FTR_CAPMASI | N_FACTURA=', COALESCE(@N_FACTURA,''),
						' | LEN_RIPSJSON=', CONVERT(VARCHAR(20), COALESCE(LEN(@RIPSJSON),0)),
						' | TIENE_JSON=', CASE WHEN COALESCE(@RIPSJSON,N'')<>N'' THEN 'SI' ELSE 'NO' END
					);
					IF COALESCE(@RIPSJSON,N'')<>N''
					   AND COALESCE(@CNSFCT_FTR,@CNSFACT,N'')<>N''
					BEGIN
						SET @CNSDOC_PERSIST = COALESCE(@CNSFCT_FTR,@CNSFACT);
						EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'FACTURA', @CNSDOC = @CNSDOC_PERSIST, @JSON_ENVIO = @RIPSJSON;
					END
		   		      SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(@CAPITA AS BIT) AS ISCAPITA,@TIPOCAP  AS TIPOCAP , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
                  END
               END
				RETURN
            END
            ELSE
            BEGIN
               /*
                 TIPOCAP=4 = capitación masiva -> SPK_RIPS_JSON_FTR_CAPMASI.
                 Antes solo se evaluaba dentro de CAPITA=1; si CAPITADA=0 (dato inconsistente)
                 caía en EVENTO/IND y fallaba. Aquí se prioriza TIPOCAP=4 para FACTURA.
               */
               IF COALESCE(@TIPOCAP,0)=4 AND @TIPODOC='FACTURA'
               BEGIN
					PRINT CONCAT(
						'[SPK_GENERAR_RIPS_JSON] FACTURA TIPOCAP=4 (CAPITA=', CONVERT(VARCHAR(5), COALESCE(@CAPITA,0)),
						') -> EXEC SPK_RIPS_JSON_FTR_CAPMASI',
						' @N_FACTURA=', COALESCE(@N_FACTURA,''),
						' | @URL_PATH=NULL',
						' | @RIPSJSON OUTPUT',
						' | CNSFCT=', COALESCE(@CNSFACT,''),
						' | CNSFCT_FTR=', COALESCE(@CNSFCT_FTR,''),
						' | TIPOFACT=', COALESCE(@TIPOFACT,''),
						' | PROCEDENCIA=', COALESCE(@PROCEDENCIA,''),
						' | IDPLAN=', COALESCE(@IDPLAN,''),
						' | GENERAR=', COALESCE(@GENERAR,'')
					);
					IF COALESCE(@GENERAR,'SI')='SI'
					BEGIN
						EXEC SPK_RIPS_JSON_FTR_CAPMASI @N_FACTURA,NULL,@RIPSJSON OUTPUT
						PRINT CONCAT(
							'[SPK_GENERAR_RIPS_JSON] Retorno SPK_RIPS_JSON_FTR_CAPMASI | N_FACTURA=', COALESCE(@N_FACTURA,''),
							' | LEN_RIPSJSON=', CONVERT(VARCHAR(20), COALESCE(LEN(@RIPSJSON),0)),
							' | TIENE_JSON=', CASE WHEN COALESCE(@RIPSJSON,N'')<>N'' THEN 'SI' ELSE 'NO' END
						);
					END
					IF COALESCE(@GENERAR,'SI')='SI'
					   AND COALESCE(@RIPSJSON,N'')<>N''
					   AND COALESCE(@CNSFCT_FTR,@CNSFACT,N'')<>N''
					BEGIN
						SET @CNSDOC_PERSIST = COALESCE(@CNSFCT_FTR,@CNSFACT);
						EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'FACTURA', @CNSDOC = @CNSDOC_PERSIST, @JSON_ENVIO = @RIPSJSON;
					END
					SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(@CAPITA AS BIT) AS ISCAPITA,@TIPOCAP AS TIPOCAP , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
					RETURN
               END

               PRINT'INGRESO POR EVENTO'
			      IF @TIPOFACT='M'
               BEGIN

					IF @TIPODOC='AJUSTE'
					BEGIN
						PRINT 'VOY POR AJUSTES DE FACTURA MASIVA'
						SELECT TOP 1 @NOMBREXML=ATTACHED_DOCNAME,@NOMBREJSON=FTRN_FACTURA+'.json' FROM FTRE WHERE FTRN_FACTURA=@N_FACTURA

						IF COALESCE(@GENERAR,'SI')='SI'
						BEGIN
							PRINT 'EXEC SPK_RIPS_JSON_NOTAAJUSTE_MAS ''' +@N_FACTURA +''''
							PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] EXEC SPK_RIPS_JSON_NOTAAJUSTE_MAS @N_FACTURA=', COALESCE(@N_FACTURA,''), ', @URL_PATH=NULL');
							EXEC SPK_RIPS_JSON_NOTAAJUSTE_MAS @N_FACTURA,NULL,@RIPSJSON OUTPUT
						END
						IF COALESCE(@GENERAR,'SI')='SI'
						   AND COALESCE(@RIPSJSON,N'')<>N''
						   AND COALESCE(@CNSFACT,N'')<>N''
						BEGIN
							EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'AJUSTE', @CNSDOC = @CNSFACT, @JSON_ENVIO = @RIPSJSON;
						END

						SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(0 AS BIT) AS ISCAPITA , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
						RETURN
					END


					IF COALESCE(@GENERAR,'SI')='SI'
					BEGIN
						/*
						  @XML ya puede venir en base64 desde el bloque FACTURA/AJUSTE
						  (FNK_AttachedDocument + xs:base64Binary, líneas ~137-150).
						  Si se vuelve a codificar aquí, xmlFevFile queda en base64 doble (UEQ5…)
						  y SISPRO responde FEV001 AttachedDocument inválido.
						*/
						IF COALESCE(@XML,'')=''
						BEGIN
							SELECT @XML = dbo.FNK_AttachedDocument(COALESCE(@CNSFCT_FTR,@CNSFACT),'fv')
							IF COALESCE(@XML,'')<>''
							BEGIN
								SELECT @XML_BASE64 = CAST('' AS XML).value('xs:base64Binary(sql:column("binaryValue"))', 'varchar(max)')
								FROM (
									SELECT [binaryValue] = CAST(@XML AS VARBINARY(MAX))
								) AS conv
								SET @XML = @XML_BASE64
							END
						END
						ELSE
						BEGIN
							-- Ya está en base64: no re-encodificar
							SET @XML_BASE64 = @XML
						END

						IF @PROCEDENCIA='AUTPG'
						BEGIN
							PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] EXEC SPK_RIPS_JSON_FTR_AUTPG @N_FACTURA=', COALESCE(@N_FACTURA,''), ' (TIPOFACT=M, PROCEDENCIA=AUTPG)');
							EXEC SPK_RIPS_JSON_FTR_AUTPG @N_FACTURA, NULL, @XML_BASE64, @RIPSJSON OUTPUT
						END
						ELSE IF @IDPLAN IN ('NEDXC','NEDXS')
						BEGIN
							PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] EXEC SPK_RIPS_JSON_FTR_CITPAQ @N_FACTURA=', COALESCE(@N_FACTURA,''), ' | IDPLAN=', COALESCE(@IDPLAN,''));
							EXEC SPK_RIPS_JSON_FTR_CITPAQ @N_FACTURA,NULL,@RIPSJSON OUTPUT
						END
						ELSE
						BEGIN
							PRINT CONCAT('[SPK_GENERAR_RIPS_JSON] EXEC SPK_RIPS_JSON_FTR_MAS @N_FACTURA=', COALESCE(@N_FACTURA,''), ' (TIPOFACT=M)');
							EXEC SPK_RIPS_JSON_FTR_MAS @N_FACTURA,NULL,@RIPSJSON OUTPUT
						END
					END
					IF COALESCE(@GENERAR,'SI')='SI'
					   AND COALESCE(@RIPSJSON,N'')<>N''
					   AND COALESCE(@CNSFCT_FTR,@CNSFACT,N'')<>N''
					BEGIN
						SET @CNSDOC_PERSIST = COALESCE(@CNSFCT_FTR,@CNSFACT);
						EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'FACTURA', @CNSDOC = @CNSDOC_PERSIST, @JSON_ENVIO = @RIPSJSON;
					END

					SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON, CAST(@CAPITA AS BIT) AS ISCAPITA , @CUV  CUV , @FRADICA_RIPS FRADICA_RIPS , @JSON_RESPUESTA JSON_RESPUESTA
					RETURN
               END
			      ELSE
			      BEGIN
                  IF COALESCE(@GENERAR,'SI')='SI'
				  BEGIN
					PRINT CONCAT(
						'[SPK_GENERAR_RIPS_JSON] FACTURA EVENTO IND -> EXEC SPK_RIPS_JSON_FTR_IND',
						' @N_FACTURA=', COALESCE(@N_FACTURA,''),
						' | CNSFCT=', COALESCE(@CNSFACT,''),
						' | CAPITA=', CONVERT(VARCHAR(5), COALESCE(@CAPITA,0)),
						' | TIPOCAP=', CONVERT(VARCHAR(10), COALESCE(@TIPOCAP,0)),
						' | TIPOFACT=', COALESCE(@TIPOFACT,''),
						' | PROCEDENCIA=', COALESCE(@PROCEDENCIA,'')
					);
				         EXEC SPK_RIPS_JSON_FTR_IND @N_FACTURA,NULL,@RIPSJSON OUTPUT
					PRINT CONCAT(
						'[SPK_GENERAR_RIPS_JSON] Retorno SPK_RIPS_JSON_FTR_IND | N_FACTURA=', COALESCE(@N_FACTURA,''),
						' | LEN_RIPSJSON=', CONVERT(VARCHAR(20), COALESCE(LEN(@RIPSJSON),0)),
						' | TIENE_JSON=', CASE WHEN COALESCE(@RIPSJSON,N'')<>N'' THEN 'SI' ELSE 'NO' END
					);
				  END
                  IF COALESCE(@GENERAR,'SI')='SI'
                     AND COALESCE(@RIPSJSON,N'')<>N''
                     AND COALESCE(@CNSFCT_FTR,@CNSFACT,N'')<>N''
                  BEGIN
                     SET @CNSDOC_PERSIST = COALESCE(@CNSFCT_FTR,@CNSFACT);
                     EXEC DBO.SPK_PERSISTIR_RIPSJSON_ENVIO @TIPODOC = N'FACTURA', @CNSDOC = @CNSDOC_PERSIST, @JSON_ENVIO = @RIPSJSON;
                  END
				      SELECT 'OK' OK,@XML AS XML_FACTURA, @NOMBREXML AS NOMBRE_XML,@RIPSJSON AS RIPSJSON,@NOMBREJSON AS NOMBREJSON , @CUV  CUV , @FRADICA_RIPS  FRADICA_RIPS, @JSON_RESPUESTA JSON_RESPUESTA
				      RETURN
			      END
            END
         -- END
		END
		ELSE
		BEGIN
			SELECT 'KO' KO
			IF COALESCE(@N_FACTURA,'')=''
				SELECT 'No se encontro factura ni glosa para CNSFCT='+COALESCE(@CNSFACT,'')+' FGLO.CNSGLO si hay glosa o FTR.CNSFCT si no hay glosa.' AS ERROR
			ELSE IF NOT EXISTS(SELECT 1 FROM FTR WHERE N_FACTURA=@N_FACTURA AND COALESCE(FACTE,0)=2)
				SELECT 'La factura '+@N_FACTURA+' no esta notificada a la DIAN (FACTE<>2).' AS ERROR
			ELSE
				SELECT 'Factura no Existe o no se ha Notificado a la Dian' AS ERROR
			RETURN
		END
END

