CREATE OR ALTER PROCEDURE DBO.SPK_ANULA_FACT
@N_FACTURA        VARCHAR(16),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@RAZONCAMBIO      VARCHAR(255),
@SYS_COMPUTERNAME VARCHAR(254),
@USUARIO2         VARCHAR(12),
@PART             BIT=0,
@IDCAUANULACION	  VARCHAR(5)=NULL,
@NOREINGERSO    BIT=0    
WITH ENCRYPTION
AS
DECLARE @PROCEDENCIA    VARCHAR(10)
DECLARE @TIPOFAC        VARCHAR(1)
DECLARE @CONTABILIZADA  SMALLINT
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @NVOCONSEC      VARCHAR(20)
DECLARE @NOADMISION     VARCHAR(16)
DECLARE @IDTERCERO      VARCHAR(20)
DECLARE @IDPLAN         VARCHAR(6)
DECLARE @TIPOADM        VARCHAR(2)
DECLARE @ESTACONTAB     SMALLINT
DECLARE @AUX            INT 
DECLARE @ESTADO         VARCHAR(1)
declare @ANOFACTURA     VARCHAR(4)
DECLARE @MESFACTURA     VARCHAR(2)
DECLARE @ANOACTUAL      VARCHAR(4)
DECLARE @MESACTUAL      VARCHAR(2)
DECLARE @ESTADOPERFTR   INT
DECLARE @ESTADOPERACT   INT
DECLARE @NVOCNSFNOT     VARCHAR(20)
DECLARE @CERRADOFTR     SMALLINT
DECLARE @CERRADOINV     SMALLINT  
DECLARE @CNSFMAS        VARCHAR(20)
DECLARE @CNSCXC         VARCHAR(20)
DECLARE @CNSMOV         VARCHAR(20)
DECLARE @FACTE          SMALLINT
DECLARE @FCOPA          SMALLINT
DECLARE @HOY            SMALLDATETIME=GETDATE()
DECLARE @HOY_SINH       DATE=CONVERT(DATE,@HOY)
DECLARE @CNSFTR         VARCHAR(20)
DECLARE @RECO           VARCHAR(20)
DECLARE @ESTADOPPTO     VARCHAR(10)
DECLARE @CNSPPTO        VARCHAR(10)
DECLARE @ESCOPAGOPE       BIT
DECLARE @CNSFPAG VARCHAR(20)
DECLARE @CNSFACJ VARCHAR(20)
DECLARE @CODCAJA VARCHAR(20)
DECLARE @LIBERAHADM BIT
DECLARE @N_FACTURA_EXTERNO  VARCHAR(16), @ESPHD BIT = 0 
DECLARE @VLR_FACTURA_TOT    DECIMAL(19,2)
DECLARE @VLR_NOTA_TOT       DECIMAL(19,2)
DECLARE @TIENE_IMPUESTO  BIT
DECLARE @MSG_MARGEN         VARCHAR(1000)
DECLARE @TIPOANULACION VARCHAR(5)
DECLARE @ESTADOFTR VARCHAR(2)
BEGIN
DECLARE @PAIS VARCHAR(20)
SET @PAIS = DBO.FNK_VALORVARIABLE('IXCOUNTRY')
    SET @FCOPA=0
    SELECT @NOADMISION     = NOREFERENCIA,
            @IDTERCERO      = IDTERCERO,
            @IDPLAN         = IDPLAN,
            @PROCEDENCIA    = PROCEDENCIA,
            @TIPOFAC        = TIPOFAC,
            @FACTE          = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN CASE WHEN COALESCE(FACTEP,'') NOT IN('101','102') THEN 0 ELSE 1 END ELSE FACTE END,
            @CONTABILIZADA  = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN CASE WHEN COALESCE(FACTEP,'') NOT IN('101','102') THEN 0 ELSE 1 END 
                            ELSE CASE WHEN COALESCE(FTR.FACTE,0)<>0  THEN 1 ELSE COALESCE(CONTABILIZADA,0) END END, 
            @NROCOMPROBANTE = COALESCE(NROCOMPROBANTE,''),
            @ANOFACTURA     = CONVERT(VARCHAR, YEAR(FTR.F_FACTURA)),
            @MESFACTURA     = CONVERT(VARCHAR, MONTH(FTR.F_FACTURA)),
            @CNSFMAS        = CNSFMAS,
            @FCOPA          = CASE WHEN TIPOFIN='N' THEN 1 ELSE 0 END,
            @CNSFTR         = CNSFCT,
            @ESCOPAGOPE     = CASE WHEN COALESCE(CP_CONVENIO,'')='Boleta' THEN 1 ELSE 0 END,
		    @N_FACTURA_EXTERNO = COALESCE(N_FACT_EXTERNO,''),
            @TIPOANULACION=COALESCE(TIPOANULACION,''),
            @ESTADOFTR=ESTADO
    FROM   FTR 
    WHERE  N_FACTURA   = @N_FACTURA

    IF @TIPOANULACION = 'NC' OR @ESTADOFTR='A'
    BEGIN
        RAISERROR('Factura anulada o con nota credito, no se puede procesar.',16,1)
        RETURN
    END
    IF EXISTS(SELECT * FROM FNOT WHERE N_FACTURA = @N_FACTURA AND CLASE='C' AND ESTADO<>'A')
    BEGIN
        RAISERROR('Factura con nota de crédito existente, no se puede procesar.',16,1)
        RETURN
    END
	IF @PROCEDENCIA = 'SALUD' AND EXISTS(SELECT 1 FROM PPT WHERE IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN AND PPT_TIPOADM = DBO.FNK_VALORVARIABLE('HTAD_HOSPITA'))
	BEGIN
		PRINT 'ES PHD'
		SET @ESPHD = 1
	END

    SELECT @ANOACTUAL  = CONVERT(VARCHAR, YEAR(@HOY)), @MESACTUAL = CONVERT(VARCHAR, MONTH(@HOY))

    IF @ANOACTUAL > @ANOFACTURA
    BEGIN
        SELECT @AUX = CERRADO FROM PRI WHERE ANO = @ANOFACTURA AND MES = 12
        IF @AUX = 1
        BEGIN
            IF DBO.FNK_VALORVARIABLE('FTR_ANULAEJERCANT') <> 'SI' 
            BEGIN
                RAISERROR('FACTURA DE UN EJERCICIO ANTERIOR DEBE CONFIGURARSE DE ACUERDO AL ART?CULO 106 DEL DECRETO 2649',16,1)
                RETURN 
            END
        END
    END

    SELECT @ESTADOPERFTR = COALESCE(CERRADO,0),@CERRADOINV=CERRADO_INV,
            @CERRADOFTR   = CERRADO_FAC 
    FROM   PRI 
    WHERE  ANO = @ANOFACTURA AND MES = @MESFACTURA 

    SELECT @ESTADOPERACT = COALESCE(CERRADO,0) FROM PRI WHERE ANO = @ANOACTUAL AND MES = @MESACTUAL

    IF @ESTADOPERFTR = 1 AND @ESTADOPERACT = 1 AND  DBO.FNK_VALORVARIABLE('FTR_ANULAEJERCANT') <> 'SI' 
    BEGIN
        RAISERROR('EL PERIODO DE LA FACTURA Y EL PERIODO ACTUAL ESTAN CERRADOS.',16,1)
        RETURN
    END
   
    SELECT @ESTACONTAB = CASE WHEN @FACTE=2 THEN 1 ELSE  @CONTABILIZADA END
    PRINT 'PROCEDENCIA= '+@PROCEDENCIA
    PRINT 'TIPOFACT= '+@TIPOFAC
    PRINT 'ESTADOPERFTR='+STR(@ESTADOPERFTR)
    PRINT 'FACTE='+STR(COALESCE(@FACTE,0))
    IF @FACTE<>0 AND @ESTADOPERFTR=0
    BEGIN
        PRINT 'Se obliga a generar nota credito cuando fue enviada a la  Dian'
        SELECT @ESTADOPERFTR=1,@CERRADOFTR=1
    END
    IF @PART=1
    BEGIN
        IF EXISTS(SELECT 1 FROM FPAGD WHERE N_FACTURA=@N_FACTURA)
        BEGIN
            SELECT @CNSFPAG=CNSFPAG,@CNSCXC=CNSCXC FROM FPAGD WHERE N_FACTURA=@N_FACTURA
            SELECT @CNSFACJ=CNSFACJ,@CODCAJA=CODCAJA FROM FPAG WHERE CNSFPAG=@CNSFPAG
            PRINT 'Desaplicando el pago'

            EXEC SPK_DESPAGOSCXC @CNSFPAG,@SEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,'DESAPLICAR'

            UPDATE FPAG SET ESTADO='Inactivo' WHERE CNSFPAG=@CNSFPAG
        END
        IF EXISTS(SELECT * FROM FCXCDV WHERE N_FACTURA=@N_FACTURA)
        BEGIN
            PRINT 'BORRANDO FCXC'
            SELECT @CNSCXC=CNSCXC FROM FCXCDV  WHERE N_FACTURA=@N_FACTURA
            DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA  AND CNSCXC=@CNSCXC
            DELETE FCXCD WHERE  N_FACTURA=@N_FACTURA  AND CNSCXC=@CNSCXC

            UPDATE FCXC SET ESTADO='Inactiva' WHERE  CNSCXC=@CNSCXC
     
            UPDATE FTR SET INDCARTERA=0,INDASIGCXC=0 WHERE N_FACTURA=@N_FACTURA
        END
        PRINT 'VALIDO RECIBO DE CAJA'

        IF EXISTS(SELECT 1 FROM FCJ INNER JOIN ACJ ON FCJ.CNSACJ=ACJ.CNSACJ WHERE FCJ.CODCAJA=@CODCAJA AND FCJ.CNSFACJ=@CNSFACJ  AND ( (@PAIS <> 'PERU' AND ACJ.ABIERTA = 1) OR (@PAIS = 'PERU'))) 
        BEGIN
            EXEC SPK_ANULARECIBO_CAJA @CODCAJA,@CNSFACJ,@USUARIO,1
        END
        ELSE
        BEGIN
            PRINT 'DEVUELVO EL RECIBO'
            UPDATE FCJ SET DEVUELTO=1 WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ
            EXEC SPK_DEVUELVERECIB_CAJA @CODCAJA,@CNSFACJ,'01',@SEDE
        END
    END
    IF EXISTS(SELECT * FROM FTR_DOCS WHERE N_FACTURA=@N_FACTURA)
    BEGIN
       DELETE  FTR_DOCS WHERE N_FACTURA=@N_FACTURA
    END
    IF @PROCEDENCIA = 'SALUD' 
    BEGIN
        SELECT @TIPOADM = TIPOADM FROM HADM WHERE NOADMISION = @NOADMISION 
        IF @ESTACONTAB = 0 AND  @FACTE = 0
        BEGIN
            UPDATE FTR SET ESTADO = 'A', RAZONANULACION=@RAZONCAMBIO WHERE  N_FACTURA = @N_FACTURA
            IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')) AND DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
            BEGIN
                SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                PRINT 'Retiro los recuados si Existe'
                UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                PRINT 'Retiro los Reconocimientos...'
                UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
            END

            IF COALESCE(@FCOPA,0)<>1
                UPDATE HPRED SET FACTURADA=0, N_FACTURA=NULL WHERE N_FACTURA = @N_FACTURA
            ELSE
                UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
      
            UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

            EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
            SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         
            -- el log debe mirarse donde apunta bdix revisar
            INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
            SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME 
            
            INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
            SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
            IF @TIPOFAC = 'I'
            BEGIN       
                UPDATE HADMF SET ESTADO = 'A' WHERE NOADMISION = @NOADMISION AND N_FACTURA = @N_FACTURA                   
                IF @TIPOADM = DBO.FNK_VALORVARIABLE('IDTARIFASOAT')
                BEGIN
                    DELETE HADM_S WHERE NOADMISION = @NOADMISION
                    DELETE HADM_T WHERE NOADMISION = @NOADMISION
                    UPDATE HADM SET FACTURADA = 0 WHERE NOADMISION = @NOADMISION
                END         
            END
            ELSE
            BEGIN           
                UPDATE FMAS SET FACTURADA = 0 WHERE CNSFMAS =@CNSFMAS
                UPDATE HADM SET FACTURADA = 0, N_FACTURA = '' WHERE N_FACTURA = @N_FACTURA 
            END
        END
        ELSE
        BEGIN
            IF @ESTACONTAB = 1 --ESTA CONTABILIZADA
            BEGIN
                PRINT 'ESTA CONTABILIZADA INGRESO ACA'
                --REVISAR EL PERIODO DE LA FACTURA
                IF @ESTADOPERFTR = 0  AND @CERRADOFTR=0  --ESTA ABIERTO ==> SE ANULA EL COMPROBANTE CONTABLE Y ACTUALIZA ESTADOS
                BEGIN
                    UPDATE MCP SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END
                    IF COALESCE(@FCOPA,0)<>1
                    BEGIN
                        PRINT 'LIBERO CARGOS'
                        UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
                    END
                    ELSE
                    BEGIN
                        PRINT 'LIBERO COPAGO'
                        UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
                    END
                        
                    UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA
                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                            @HOY, @SYS_COMPUTERNAME          
                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL  
         
                    IF @TIPOFAC = 'I'
                    BEGIN
                        UPDATE HADMF SET ESTADO = 'A' WHERE NOADMISION = @NOADMISION AND N_FACTURA = @N_FACTURA
                        IF @TIPOADM = DBO.FNK_VALORVARIABLE('IDTARIFASOAT')
                        BEGIN
                            DELETE HADM_S WHERE NOADMISION = @NOADMISION
                            DELETE HADM_T WHERE NOADMISION = @NOADMISION
                            UPDATE HADM SET FACTURADA = 0 WHERE NOADMISION = @NOADMISION
                        END
                    END
                    ELSE    --ES  MASIVA
                    BEGIN
                        UPDATE FMAS SET FACTURADA = 0 WHERE CNSFMAS =@CNSFMAS
                        UPDATE HADM SET FACTURADA = 0, N_FACTURA = '' WHERE N_FACTURA = @N_FACTURA 
                    END
                END
                ELSE
                BEGIN --EL PERIODO DE LA FACTURA ESTA CERRADO
                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME
                    
                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
                    
                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  
                    SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
                    
                    INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                                        MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                                        CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                                        CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                                        IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                                        VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
                    SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                            NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', 1, 
                            '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0

                    EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO

                    IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
                    BEGIN
                        UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
                    END

					-- Validacion margen de tolerancia (0.5-1 sol) para nota de credito sin impuesto
                    IF DBO.FNK_VALORVARIABLE('IXCOUNTRY') = 'PERU'
                       AND DBO.FNK_VALORVARIABLE('FNOT_VALIDA_TOLER') = 'SI'
                    BEGIN
						PRINT 'INGRESE A VALIDAR MARGEN DE TOLERANCIA'
                        -- Verificar si la factura NO tiene impuesto registrado en ningun item (PIVA = 0 en todos)
                        SELECT @TIENE_IMPUESTO = CASE WHEN COALESCE(SUM(COALESCE(PIVA, 0)), 0) > 0 THEN 1 ELSE 0 END
                        FROM   FTRD
                        WHERE  N_FACTURA = @N_FACTURA

						PRINT '@TIENE_IMPUESTO >'  + COALESCE(CAST(@TIENE_IMPUESTO AS VARCHAR),' SIN @TIENE_IMPUESTO')

                        IF COALESCE(@TIENE_IMPUESTO, 0) = 0
                        BEGIN
                            SELECT @VLR_FACTURA_TOT = VR_TOTAL FROM FTR  WHERE N_FACTURA = @N_FACTURA
                            SELECT @VLR_NOTA_TOT   = VR_TOTAL FROM FNOT WHERE CNSFNOT   = @NVOCNSFNOT
							PRINT '@VLR_NOTA_TOT >'  + COALESCE(CAST(@VLR_NOTA_TOT AS VARCHAR),' SIN @VLR_NOTA_TOT')
							PRINT '@VLR_NOTA_TOT >'  + COALESCE(CAST(@VLR_NOTA_TOT AS VARCHAR),' SIN @VLR_NOTA_TOT')
                            -- Margen de tolerancia fijo entre 0.5 y 1 sol (se usa 1.00)
                            IF ABS(COALESCE(@VLR_FACTURA_TOT, 0) - COALESCE(@VLR_NOTA_TOT, 0)) > 1.00
                            BEGIN
                                DELETE FNOTD WHERE CNSFNOT = @NVOCNSFNOT
                                DELETE FNOT  WHERE CNSFNOT = @NVOCNSFNOT
                                SET @MSG_MARGEN = 'NOTA DE CREDITO RECHAZADA: La diferencia entre el total de la factura ('
                                    + CAST(COALESCE(@VLR_FACTURA_TOT, 0) AS VARCHAR(20))
                                    + ') y el total de la nota de credito ('
                                    + CAST(COALESCE(@VLR_NOTA_TOT, 0) AS VARCHAR(20))
                                    + ') supera el margen de tolerancia permitido (0.5 a 1 sol). Verifique los valores antes de generar.'
                                RAISERROR(@MSG_MARGEN, 16, 1)
                                RETURN
                            END
                        END
                    END

                    EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME

                    UPDATE FTR SET RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC' WHERE N_FACTURA=@N_FACTURA
                    
                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR' AND EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                    BEGIN
                        SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                        PRINT 'Retiro los recuados si Existe'
                        UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                        DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                        UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                        PRINT 'Retiro los Reconocimientos...'
                        UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                        DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                        UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                        UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                    END
                    IF @TIPOFAC = 'M'  --MASIVA
                    BEGIN
                        UPDATE FMAS SET FACTURADA = 0 WHERE CNSFMAS =@CNSFMAS
                    END
                    IF COALESCE(@FCOPA,0)<>1
                    BEGIN
                        PRINT 'LIBERO CARGOS'
                        UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
                    END
                    ELSE
                    BEGIN
                        PRINT 'LIBERO COPAGO'
                        UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
                    END                        
                    UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA
                END                       
            END
            ELSE
            BEGIN
                IF @ESTACONTAB = 2  --ESTA CONTABILIZADA CON ERRORES
                BEGIN
                    UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END

                    IF COALESCE(@FCOPA,0)<>1
                    BEGIN
                        UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
                    END
                    ELSE
                    BEGIN
                        UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
                    END
                  
                    UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME
                    
                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
                    
                    IF @TIPOFAC = 'I'
                    BEGIN
                        UPDATE HADMF SET ESTADO = 'A' WHERE NOADMISION = @NOADMISION AND N_FACTURA = @N_FACTURA
                        IF @TIPOADM = DBO.FNK_VALORVARIABLE('IDTARIFASOAT')
                        BEGIN
                            DELETE HADM_S WHERE NOADMISION = @NOADMISION
                            DELETE HADM_T WHERE NOADMISION = @NOADMISION
                            UPDATE HADM SET FACTURADA = 0 WHERE NOADMISION = @NOADMISION
                        END         
                    END
                    ELSE
                    BEGIN  --MASIVA
                        UPDATE FMAS SET FACTURADA = 0 WHERE CNSFMAS =@CNSFMAS
                        UPDATE HADM SET FACTURADA = 0, N_FACTURA = '' WHERE N_FACTURA = @N_FACTURA 
                        UPDATE HADMF SET ESTADO = 'A' WHERE N_FACTURA = @N_FACTURA
                    END

                    DELETE MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    UPDATE MCPE SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                                    REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                                    RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
                    SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                            REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                            RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
                    FROM   MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    DELETE MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                END
                ELSE
                BEGIN -- NO DEFINIDO
                    PRINT 'NO DEFINIDO @ESTACONTAB <> 0, 1, 2'
                END
            END
        END
        /* ARREGLO DE HONORARIOS*/
        IF @TIPOFAC = 'I'
        BEGIN
            DELETE FXPD 
            FROM   FXPD INNER JOIN FXP ON FXPD.N_PRESUP  = FXP.N_PRESUP
                                    AND FXPD.IDTERCERO = FXP.IDTERCERO
            WHERE  FXP.NOREFERENCIA = @NOADMISION AND    FXP.PROCEDENCIA  = 'SALUD'
            DELETE FXP WHERE NOREFERENCIA = @NOADMISION AND PROCEDENCIA = 'SALUD'
        END
        ELSE
        BEGIN
            DELETE FXPD
            FROM   FXPD INNER JOIN FXP ON FXPD.N_PRESUP  = FXP.N_PRESUP
                                    AND FXPD.IDTERCERO = FXP.IDTERCERO
                        INNER JOIN ( SELECT NOADMISION, COUNT(*) VECES FROM FTRD 
                                    WHERE  N_FACTURA = @N_FACTURA 
                                    GROUP BY NOADMISION 
                                ) X ON FXP.NOREFERENCIA = X.NOADMISION 
                                    AND FXP.PROCEDENCIA  = 'SALUD'

            DELETE FXP 
            FROM   FXP INNER JOIN ( SELECT NOADMISION, COUNT(*) VECES FROM FTRD 
                                    WHERE  N_FACTURA = @N_FACTURA 
                                    GROUP BY NOADMISION 
                                ) X ON FXP.NOREFERENCIA = @NOADMISION 
                                    AND FXP.PROCEDENCIA = 'SALUD'
        END
        IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
        BEGIN
            UPDATE AUT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
	        WHERE  AUT.N_FACTURA =  @N_FACTURA AND FACTURADA = 1

		    UPDATE AUTD SET FACTURADA = 0, N_FACTURA = NULL
            WHERE  AUTD.N_FACTURA = @N_FACTURA AND FACTURADA = 1

            UPDATE CIT SET FACTURADA=0,N_FACTURA=NULL
            WHERE CIT.N_FACTURA=@N_FACTURA AND FACTURADA=1

			IF ISNULL(@ESPHD,0)=1
			BEGIN
				IF EXISTS(SELECT 1 FROM FCXCD WHERE N_FACTURA=@N_FACTURA)
				BEGIN
					PRINT 'Borro de FCXCD'
					SELECT @CNSCXC=CNSCXC FROM FCXCD WHERE N_FACTURA=@N_FACTURA
					DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA
					DELETE FCXCD WHERE N_FACTURA=@N_FACTURA

					PRINT 'ACTUALIZO VALORES FCXCD'
					EXEC SPK_RELIQUIDACXCQX @CNSCXC;
				END
				
				UPDATE CARTG SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA AND FACTURADA = 1
				UPDATE HADMF SET ESTADO = 'A' WHERE NOADMISION = @NOADMISION AND N_FACTURA = @N_FACTURA  
				UPDATE FTR SET ESTADO = 'A', RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC', IDCAUANULACION=@IDCAUANULACION, CLASEANULACION = IIF(@N_FACTURA_EXTERNO = '','A','N') WHERE N_FACTURA=@N_FACTURA 
			END
        END
    END

    IF @PROCEDENCIA='CI' OR  @PROCEDENCIA='CE'  OR  @PROCEDENCIA='AUTPG'
    BEGIN
        PRINT 'ES DE PROCEDENCIA = '+@PROCEDENCIA + ' // CONTABILIZADA = '+CONVERT(VARCHAR,@ESTACONTAB )
        IF @ESTACONTAB = 0 AND @FACTE = 0-- NO ESTA CONTABILIZADA
        BEGIN
            UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO WHERE  N_FACTURA = @N_FACTURA
            IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
            BEGIN
                IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                BEGIN
                    SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                    PRINT 'Retiro los recuados si Existe'
                    UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                    DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                    UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                    PRINT 'Retiro los Reconocimientos...'
                    UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                    DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                    UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                    UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                END
            END
        END
        ELSE
        BEGIN
            IF @ESTACONTAB = 1 --ESTA CONTABILIZADA
            BEGIN        
                PRINT 'ESTA CONTABILIZADA'
                IF @ESTADOPERFTR = 0  AND @CERRADOFTR=0 --ESTA ABIERTO ==> SE ANULA EL COMPROBANTE CONTABLE Y ACTUALIZA ESTADOS
                BEGIN
                    UPDATE MCP SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO   WHERE  N_FACTURA = @N_FACTURA

                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END
                  
                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
                END
                ELSE
                BEGIN 
	                --EL PERIODO DE LA FACTURA ESTA CERRADO
                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL

                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  
                    SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)

                    INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                                        MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                                        CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                                        CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                                        IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                                        VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
                    SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                            NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', 1, 
                            '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0

                    -- se generan los detalles de la nota credito
                    EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO

                    IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
                    BEGIN
                        UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
                    END

                    -- Validacion margen de tolerancia (0.5-1 sol) para nota de credito sin impuesto
                    IF DBO.FNK_VALORVARIABLE('IXCOUNTRY') = 'PERU'
                       AND DBO.FNK_VALORVARIABLE('FNOT_VALIDA_TOLER') = 'SI'
                    BEGIN
						PRINT 'INGRESE A VALIDAR MARGEN DE TOLERANCIA'
                        -- Verificar si la factura NO tiene impuesto registrado en ningun item (PIVA = 0 en todos)
                        SELECT @TIENE_IMPUESTO = CASE WHEN COALESCE(SUM(COALESCE(PIVA, 0)), 0) > 0 THEN 1 ELSE 0 END
                        FROM   FTRD
                        WHERE  N_FACTURA = @N_FACTURA

						PRINT '@TIENE_IMPUESTO >'  + COALESCE(CAST(@TIENE_IMPUESTO AS VARCHAR),' SIN @TIENE_IMPUESTO')

                        IF COALESCE(@TIENE_IMPUESTO, 0) = 0
                        BEGIN
                            SELECT @VLR_FACTURA_TOT = VR_TOTAL FROM FTR  WHERE N_FACTURA = @N_FACTURA
                            SELECT @VLR_NOTA_TOT   = VR_TOTAL FROM FNOT WHERE CNSFNOT   = @NVOCNSFNOT
							PRINT '@VLR_NOTA_TOT >'  + COALESCE(CAST(@VLR_NOTA_TOT AS VARCHAR),' SIN @VLR_NOTA_TOT')
							PRINT '@VLR_NOTA_TOT >'  + COALESCE(CAST(@VLR_NOTA_TOT AS VARCHAR),' SIN @VLR_NOTA_TOT')
                            -- Margen de tolerancia fijo entre 0.5 y 1 sol (se usa 1.00)
                            IF ABS(COALESCE(@VLR_FACTURA_TOT, 0) - COALESCE(@VLR_NOTA_TOT, 0)) > 1.00
                            BEGIN
                                DELETE FNOTD WHERE CNSFNOT = @NVOCNSFNOT
                                DELETE FNOT  WHERE CNSFNOT = @NVOCNSFNOT
                                SET @MSG_MARGEN = 'NOTA DE CREDITO RECHAZADA: La diferencia entre el total de la factura ('
                                    + CAST(COALESCE(@VLR_FACTURA_TOT, 0) AS VARCHAR(20))
                                    + ') y el total de la nota de credito ('
                                    + CAST(COALESCE(@VLR_NOTA_TOT, 0) AS VARCHAR(20))
                                    + ') supera el margen de tolerancia permitido (0.5 a 1 sol). Verifique los valores antes de generar.'
                                RAISERROR(@MSG_MARGEN, 16, 1)
                                RETURN
                            END
                        END
                    END

                    -- se aplica la nota credito
                    EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME

                    UPDATE FTR SET RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC' WHERE N_FACTURA=@N_FACTURA

                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END
                END
            END
            ELSE
            BEGIN
                IF @ESTACONTAB = 2 --ESTA CONTABILIZADA CON ERRORES
                BEGIN        
                    PRINT 'ESTA CONTABILIZADA CON ERRORES'   
                    UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END
                    DELETE MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE

                    UPDATE MCPE SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                                        REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                                        RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
                    SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                            REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                            RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
                    FROM   MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    DELETE MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                END
            END
        END
        --AQUI HACE LO MISMO LIBERAR ORIGEN ESTE SIN CONTABILIZAR O CONTABILIZADA O CONT CON ERRORES
        IF @PROCEDENCIA='CI' OR @NOADMISION='CEUNIFICADO'
        BEGIN
            IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND COALESCE(@ESCOPAGOPE,0)=1
            BEGIN
                UPDATE CIT SET NFACTURA = NULL WHERE  NFACTURA = @N_FACTURA 
                UPDATE AUTD SET NFACTURA=NULL WHERE NFACTURA=@N_FACTURA
			    
                IF DBO.FNK_VALORVARIABLE('LIBERA_RECIBO_CAJ')='SI'
			    BEGIN
				    SELECT @CNSFACJ=CNSFACJ,@CODCAJA=CODCAJA FROM FCJ WHERE N_FACTURA=@N_FACTURA
				    IF EXISTS(SELECT 1 FROM FCJ INNER JOIN ACJ ON FCJ.CNSACJ=ACJ.CNSACJ WHERE FCJ.CODCAJA=@CODCAJA AND FCJ.CNSFACJ=@CNSFACJ AND  ( (@PAIS <> 'PERU' AND ACJ.ABIERTA = 1) OR (@PAIS = 'PERU'))) 
				    BEGIN
					    PRINT 'ANULANDO EL RECIBO DE CAJA'      
					    EXEC SPK_ANULARECIBO_CAJA @CODCAJA,@CNSFACJ,@USUARIO
				    END
			    END
            END
            ELSE
            BEGIN
                IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
                BEGIN
                    UPDATE CIT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
                    WHERE  N_FACTURA =  @N_FACTURA AND FACTURADA = 1

                    UPDATE AUTD SET N_FACTURA=NULL,FACTURADA=0 WHERE N_FACTURA=@N_FACTURA AND FACTURADA=1
                    UPDATE AUT SET N_FACTURA=NULL,FACTURADA=0 WHERE N_FACTURA=@N_FACTURA  AND FACTURADA=1
                END
                ELSE
                BEGIN
                    UPDATE CIT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
                    WHERE  N_FACTURA =  @N_FACTURA AND FACTURADA = 1
                END
            END

	        DELETE FXPD 
	        FROM   FXPD INNER JOIN FXP  ON FXPD.N_PRESUP  = FXP.N_PRESUP
		                            AND FXPD.IDTERCERO = FXP.IDTERCERO
                        INNER JOIN FTRD ON FXP.NOREFERENCIA = FTRD.NOADMISION
            WHERE  FXP.PROCEDENCIA  = 'CI'
            AND    FTRD.N_FACTURA   = @N_FACTURA
               
            DELETE FXP 
            FROM   FXP INNER JOIN FTRD ON FXP.NOREFERENCIA = FTRD.NOADMISION
            WHERE  FXP.PROCEDENCIA = 'CI'
            AND    FTRD.N_FACTURA   = @N_FACTURA

            DELETE HACTRANFD WHERE N_FACTURA=@N_FACTURA
		    DELETE HACTRANF  WHERE N_FACTURA=@N_FACTURA

            IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND EXISTS(SELECT 1 FROM FTRD WHERE N_FACTURA=@N_FACTURA AND PROCEDENCIA='CE')
            BEGIN
                UPDATE AUT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
	            WHERE  AUT.N_FACTURA =  @N_FACTURA AND FACTURADA = 1

		        UPDATE AUTD SET FACTURADA = 0, N_FACTURA = NULL
                WHERE  AUTD.N_FACTURA = @N_FACTURA AND FACTURADA = 1
            END
        END

        IF @PROCEDENCIA='CE' OR @NOADMISION='CEUNIFICADO'
        BEGIN
            IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND COALESCE(@ESCOPAGOPE,0)=1
            BEGIN
                UPDATE AUTD SET NFACTURA = NULL WHERE  NFACTURA = @N_FACTURA 
            END
            ELSE
            BEGIN
                UPDATE AUT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
	            WHERE  AUT.N_FACTURA =  @N_FACTURA AND FACTURADA = 1

		        UPDATE AUTD SET FACTURADA = 0, N_FACTURA = NULL
                WHERE  AUTD.N_FACTURA = @N_FACTURA AND FACTURADA = 1
            END
             
            DELETE FXPD 
		    FROM   FXPD INNER JOIN FXP  ON FXPD.N_PRESUP  = FXP.N_PRESUP
		                                AND FXPD.IDTERCERO = FXP.IDTERCERO
                        INNER JOIN FTRD ON FXP.NOREFERENCIA = FTRD.NOADMISION
            WHERE  FXP.PROCEDENCIA  = 'CE'
            AND    FTRD.N_FACTURA   = @N_FACTURA
               
            DELETE FXP 
            FROM   FXP INNER JOIN FTRD ON FXP.NOREFERENCIA = FTRD.NOADMISION
            WHERE  FXP.PROCEDENCIA = 'CE'
            AND    FTRD.N_FACTURA   = @N_FACTURA
	
		    DELETE HACTRANFD WHERE N_FACTURA=@N_FACTURA
		    DELETE HACTRANF  WHERE N_FACTURA=@N_FACTURA

            IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND EXISTS(SELECT * FROM FTRD WHERE N_FACTURA=@N_FACTURA AND PROCEDENCIA IN('CI','CIT'))
            BEGIN 
                UPDATE CIT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
                WHERE  N_FACTURA =  @N_FACTURA AND FACTURADA = 1
            END
			IF @TIPOFAC='M' 
			BEGIN 
				UPDATE	CIT SET FACTURADA=0,N_FACTURA=NULL FROM CIT INNER JOIN FTRD ON CIT.CONSECUTIVO=FTRD.NOADMISION
				WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CI'

				UPDATE HCATDIMOV SET FACTURADA=0,N_FACTURA=NULL 
				FROM HCATDIMOV INNER JOIN FTRD ON FTRD.NOADMISION=HCATDIMOV.CONSECUTIVOCIT AND FTRD.NOITEM=HCATDIMOV.ID
				WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='ONCO'
			END
        END

        IF @PROCEDENCIA='AUTPG'
        BEGIN
            UPDATE CIT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
            WHERE  N_FACTURA =  @N_FACTURA
            
            UPDATE AUT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
            WHERE  N_FACTURA =  @N_FACTURA

            UPDATE AUTD SET FACTURADA = 0, N_FACTURA = NULL
            WHERE  N_FACTURA =  @N_FACTURA

            UPDATE AUTPG SET FACTURADO = 0,  N_FACTURA = NULL
            WHERE  N_FACTURA =  @N_FACTURA

        END
    END

    IF @PROCEDENCIA = 'FINANCIERO'
    BEGIN
        IF @ESTACONTAB = 0  AND @FACTE = 0
        BEGIN
            UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO WHERE  N_FACTURA = @N_FACTURA
            IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
            BEGIN
                IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                BEGIN
                    SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                    PRINT 'Retiro los recuados si Existe'
                    UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                    DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                    UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                    PRINT 'Retiro los Reconocimientos...'
                    UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                    DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                    UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                    UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                END
            END
            IF COALESCE(@FCOPA,0)<>1
            BEGIN
                UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
            END
            ELSE
            BEGIN
                UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
            END
      
            UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

            IF COALESCE(@SEDE,'')=''
            BEGIN 
                SELECT @SEDE=IDSEDE FROM FTR WHERE  COALESCE(N_FACTURA,'')=@N_FACTURA
            END

            EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
            SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         
            INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
            SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

            INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
            SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
        END
        ELSE
        BEGIN
            IF DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT') = 'COMER'
            BEGIN
                IF EXISTS(SELECT 1 FROM FCXCD WHERE N_FACTURA=@N_FACTURA)
                BEGIN
                    PRINT 'Borro de fcxcdv'
                    SELECT @CNSCXC=CNSCXC FROM FCXCD WHERE N_FACTURA=@N_FACTURA
                    DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA
                    DELETE FCXCD WHERE N_FACTURA=@N_FACTURA
                    UPDATE FCXC SET ESTADO='Inactiva',CERRADA=1 WHERE CNSCXC=@CNSCXC
                END
            END
            IF @ESTACONTAB = 1 --ESTA CONTABILIZADA
            BEGIN
                IF @ESTADOPERFTR = 0  AND @CERRADOFTR=0 --ESTA ABIERTO ==> SE ANULA EL COMPROBANTE CONTABLE Y ACTUALIZA ESTADOS
                BEGIN
                    UPDATE MCP SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END
                    IF COALESCE(@FCOPA,0)<>1
                    BEGIN
                        UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
                    END
                    ELSE
                    BEGIN
                        UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
                    END
                  
                    UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

                    PRINT '@SEDE='+COALESCE(@SEDE,'SIN SEDE')+' COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA') 
                    IF COALESCE(@SEDE,'')=''
                    BEGIN 
                        SELECT @SEDE=IDSEDE FROM FTR WHERE  COALESCE(N_FACTURA,'')=@N_FACTURA
                    END

                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL          
                END
                ELSE
                BEGIN --EL PERIODO DE LA FACTURA ESTA CERRADO
                -- SE DEBE ANULAR POR NOTA CREDITO
                -- se crea el encabezado de la Nota Credito
                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
 

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL

                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  
                    SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
                    
                    INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                                        MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                                        CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                                        CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                                        IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                                        VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
                    SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                            NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', 1, 
                            '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0

                    EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO
                    IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
                    BEGIN
                        UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
                        UPDATE FNOTD SET IDSERVICIO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE') WHERE CNSFNOT=@NVOCNSFNOT AND COALESCE(IDSERVICIO,'')=''
                    END

					-- Validacion margen de tolerancia (0.5-1 sol) para nota de credito sin impuesto
                    IF DBO.FNK_VALORVARIABLE('IXCOUNTRY') = 'PERU'
                       AND DBO.FNK_VALORVARIABLE('FNOT_VALIDA_TOLER') = 'SI'
                    BEGIN
						PRINT 'INGRESE A VALIDAR MARGEN DE TOLERANCIA'
                        -- Verificar si la factura NO tiene impuesto registrado en ningun item (PIVA = 0 en todos)
                        SELECT @TIENE_IMPUESTO = CASE WHEN COALESCE(SUM(COALESCE(PIVA, 0)), 0) > 0 THEN 1 ELSE 0 END
                        FROM   FTRD
                        WHERE  N_FACTURA = @N_FACTURA

						PRINT '@TIENE_IMPUESTO >'  + COALESCE(CAST(@TIENE_IMPUESTO AS VARCHAR),' SIN @TIENE_IMPUESTO')

                        IF COALESCE(@TIENE_IMPUESTO, 0) = 0
                        BEGIN
                            SELECT @VLR_FACTURA_TOT = VR_TOTAL FROM FTR  WHERE N_FACTURA = @N_FACTURA
                            SELECT @VLR_NOTA_TOT   = VR_TOTAL FROM FNOT WHERE CNSFNOT   = @NVOCNSFNOT
							PRINT '@VLR_NOTA_TOT >'  + COALESCE(CAST(@VLR_NOTA_TOT AS VARCHAR),' SIN @VLR_NOTA_TOT')
							PRINT '@VLR_NOTA_TOT >'  + COALESCE(CAST(@VLR_NOTA_TOT AS VARCHAR),' SIN @VLR_NOTA_TOT')
                            -- Margen de tolerancia fijo entre 0.5 y 1 sol (se usa 1.00)
                            IF ABS(COALESCE(@VLR_FACTURA_TOT, 0) - COALESCE(@VLR_NOTA_TOT, 0)) > 1.00
                            BEGIN
                                DELETE FNOTD WHERE CNSFNOT = @NVOCNSFNOT
                                DELETE FNOT  WHERE CNSFNOT = @NVOCNSFNOT
                                SET @MSG_MARGEN = 'NOTA DE CREDITO RECHAZADA: La diferencia entre el total de la factura ('
                                    + CAST(COALESCE(@VLR_FACTURA_TOT, 0) AS VARCHAR(20))
                                    + ') y el total de la nota de credito ('
                                    + CAST(COALESCE(@VLR_NOTA_TOT, 0) AS VARCHAR(20))
                                    + ') supera el margen de tolerancia permitido (0.5 a 1 sol). Verifique los valores antes de generar.'
                                RAISERROR(@MSG_MARGEN, 16, 1)
                                RETURN
                            END
                        END
                    END

                    EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME    
                    UPDATE FTR SET RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC' WHERE N_FACTURA=@N_FACTURA

                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END
                END                       
            END
            ELSE
            BEGIN
                IF @ESTACONTAB = 2  --ESTA CONTABILIZADA CON ERRORES
                BEGIN
                    PRINT 'ESTA CONTABILIZADA CON ERRORES'   
                    UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO   WHERE  N_FACTURA = @N_FACTURA
                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END
                    IF COALESCE(@FCOPA,0)<>1
                    BEGIN
                        UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
                    END
                    ELSE
                    BEGIN
                        UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
                    END
               
                    UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
              
                    DELETE MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    UPDATE MCPE SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                                    REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                                    RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
                    SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                            REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                            RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
                    FROM   MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    DELETE MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                END
                ELSE
                BEGIN -- NO DEFINIDO
                    PRINT 'NO DEFINIDO @ESTACONTAB <> 0, 1, 2'
                END
            END
        END
    END
--query 2
    IF @PROCEDENCIA = 'INVENTARIO'
    BEGIN
        IF DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT') = 'COMER'  OR DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT') = 'IPS' OR  DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
        BEGIN
            IF EXISTS(SELECT 1 FROM FCXCD WHERE N_FACTURA=@N_FACTURA)
            BEGIN
                SELECT @CNSCXC=CNSCXC FROM FCXCD WHERE N_FACTURA=@N_FACTURA
                DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA
                DELETE FCXCD WHERE N_FACTURA=@N_FACTURA
                UPDATE FCXC SET ESTADO='Inactiva',CERRADA=1 WHERE CNSCXC=@CNSCXC
            END

            IF @ESTACONTAB = 1 --ESTA CONTABILIZADA
            BEGIN
                IF @ESTADOPERFTR = 0  AND @CERRADOFTR=0 --ESTA ABIERTO ==> SE ANULA EL COMPROBANTE CONTABLE Y ACTUALIZA ESTADOS
                BEGIN
                    UPDATE MCP SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END
                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME
                    
                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL          
                END
                ELSE
                BEGIN
                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME
                    
                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
                    
                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  
                    SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
                    
                    INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                                        MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                                        CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                                        CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                                        IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                                        VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS,NOREINGRESO)
                    SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                            NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', 1, 
                            '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0,@NOREINGERSO

                    EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO

                    IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
                    BEGIN
                        UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
                    END

                    EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME    
                    UPDATE FTR SET RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC' WHERE N_FACTURA=@N_FACTURA  
                    
                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END               
                END                       
            END
            ELSE
            BEGIN
                IF @ESTACONTAB = 2  --ESTA CONTABILIZADA CON ERRORES
                BEGIN
                    PRINT 'ESTA CONTABILIZADA CON ERRORES'   
                    UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO     WHERE  N_FACTURA = @N_FACTURA

                    IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
                    BEGIN
                        IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                        BEGIN
                            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                            PRINT 'Retiro los recuados si Existe'
                            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                            PRINT 'Retiro los Reconocimientos...'
                            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                        END
                    END

                    EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
                    SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

                    INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
                    SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

                    INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
                    SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
              
                    DELETE MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    UPDATE MCPE SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                                    REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                                    RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
                    SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                            REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                            RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
                    FROM   MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                    DELETE MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
                END
                ELSE
                BEGIN
                   UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO WHERE  N_FACTURA = @N_FACTURA
                END
            END
            IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
            BEGIN
                IF EXISTS(SELECT 1 FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                BEGIN
                    SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                    PRINT 'Retiro los recuados si Existe'
                    UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                    DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                    UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                    PRINT 'Retiro los Reconocimientos...'
                    UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                    DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                    UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                    UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                END
            END

            SELECT  @CNSMOV=NOREFERENCIA  FROM FTR WHERE  N_FACTURA = @N_FACTURA

            IF EXISTS (SELECT 1 FROM IMOV WHERE CNSMOV = @CNSMOV AND IMOV.IDTIPOMOV IN (DBO.FNK_VALORVARIABLE('IDINVENTA_PARTICULAR') ,DBO.FNK_VALORVARIABLE('IDINVMOVVENTAFACTURA')   ))
            BEGIN
                UPDATE IMOV SET FACTURADA = 0 WHERE CNSMOV = @CNSMOV
            END

            IF NOT EXISTS (SELECT 1 FROM IMOV WHERE CNSMOV = @CNSMOV AND IMOV.IDTIPOMOV IN (DBO.FNK_VALORVARIABLE('IDINVENTA_PARTICULAR') ,DBO.FNK_VALORVARIABLE('IDINVMOVVENTAFACTURA')   ))
            BEGIN
                UPDATE IMOV SET FACTURADA = 0, N_FACTURA=NULL,F_FACTURA=NULL,F_VENCE=NULL WHERE CNSMOV = @CNSMOV
            END

            EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
            SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         
            INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
            SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

            INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
            SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL  
        END
    END 
    IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')<>'PERU'
    BEGIN
        IF DBO.FNK_VALORVARIABLE('FTR_ENVIO_DIAN_AUTO')='SI' AND EXISTS(SELECT 1 FROM FTR WHERE N_fACTURA=@N_FACTURA AND COALESCE(FACTE,0)=2)
        BEGIN
            UPDATE FNOT SET FACTE=1 WHERE CNSFNOT=@NVOCNSFNOT
        END
        ELSE
        BEGIN
            UPDATE FNOT SET FACTE=0 WHERE CNSFNOT=@NVOCNSFNOT
        END
    END
    IF @PROCEDENCIA = 'CAJA'
    BEGIN
        IF EXISTS(SELECT 1 FROM FCXCD WHERE N_FACTURA=@N_FACTURA)
        BEGIN
            PRINT 'Borro de fcxcdv'
            SELECT @CNSCXC=CNSCXC FROM FCXCD WHERE N_FACTURA=@N_FACTURA
            DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA
            DELETE FCXCD WHERE N_FACTURA=@N_FACTURA
            UPDATE FCXC SET ESTADO='Inactiva',CERRADA=1 WHERE CNSCXC=@CNSCXC
        END

        EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
        SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

        INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
        SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

        INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
        SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL          

        EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  

        SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
        INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                        MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                        CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                        CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                        IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                        VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
        SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', 1, 
                '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0

        EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO
        IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
        BEGIN
            UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
        END

        EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME

        UPDATE FTR SET RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC' WHERE N_FACTURA=@N_FACTURA

        IF EXISTS(SELECT 1 FROM FCJ INNER JOIN ACJ ON FCJ.CNSACJ=ACJ.CNSACJ WHERE FCJ.CODCAJA=@CODCAJA AND FCJ.CNSFACJ=@CNSFACJ  AND ( (@PAIS <> 'PERU' AND ACJ.ABIERTA = 1) OR (@PAIS = 'PERU'))) 
        BEGIN
            EXEC SPK_ANULARECIBO_CAJA @CODCAJA,@CNSFACJ,@USUARIO
        END
    END
    IF @PROCEDENCIA IN ('MAD','CMV')
    BEGIN
        IF EXISTS(SELECT 1 FROM FCXCD WHERE N_FACTURA=@N_FACTURA)
        BEGIN
            PRINT 'Borro de FCXCD'
            SELECT @CNSCXC=CNSCXC FROM FCXCD WHERE N_FACTURA=@N_FACTURA
            DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA
            DELETE FCXCD WHERE N_FACTURA=@N_FACTURA

		    PRINT 'ACTUALIZO VALORES'
		    EXEC SPK_RELIQUIDACXCQX @CNSCXC;
        END
     
	    SELECT @LIBERAHADM=COALESCE(AFECTAESTADO,0) FROM CAU WHERE IDCAUSAL = @IDCAUANULACION

        EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
        SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

        INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
        SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

        INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
        SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL          

        EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  

        SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
        INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                        MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                        CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                        CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                        IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                        VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
        SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', @LIBERAHADM, 
                '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0

        EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO
        IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
        BEGIN
            UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
        END

        EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME    
        
        UPDATE FTR SET ESTADO = 'A', RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC', IDCAUANULACION=@IDCAUANULACION, CLASEANULACION = IIF(@N_FACTURA_EXTERNO = '','A','N') WHERE N_FACTURA=@N_FACTURA 
        
        IF EXISTS(SELECT * FROM FCJ INNER JOIN ACJ ON FCJ.CNSACJ=ACJ.CNSACJ WHERE FCJ.CODCAJA=@CODCAJA AND FCJ.CNSFACJ=@CNSFACJ  AND ( (@PAIS <> 'PERU' AND ACJ.ABIERTA = 1) OR (@PAIS = 'PERU'))) 
        BEGIN
            EXEC SPK_ANULARECIBO_CAJA @CODCAJA,@CNSFACJ,@USUARIO
        END
    END
	IF @PROCEDENCIA = 'HPREP'
    BEGIN
      --  IF EXISTS(SELECT 1 FROM FCXCD WHERE N_FACTURA=@N_FACTURA)
      --  BEGIN
      --      PRINT 'Borro de FCXCD'
      --      SELECT @CNSCXC=CNSCXC FROM FCXCD WHERE N_FACTURA=@N_FACTURA
      --      DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA
      --      DELETE FCXCD WHERE N_FACTURA=@N_FACTURA

		    --PRINT 'ACTUALIZO VALORES'
		    --EXEC SPK_RELIQUIDACXCQX @CNSCXC;
      --  END
       SELECT @CODCAJA = CODCAJA, @CNSFACJ = CNSFACJ FROM FCJ WHERE N_FACTURA = @N_FACTURA
	    SELECT @LIBERAHADM=COALESCE(AFECTAESTADO,0) FROM CAU WHERE IDCAUSAL = @IDCAUANULACION

        EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
        SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

        INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
        SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, @HOY, @SYS_COMPUTERNAME

        INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
        SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL          

        EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  

        SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
        INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                        MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                        CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                        CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                        IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                        VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
        SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', @LIBERAHADM, 
                '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0

        EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO
        IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
        BEGIN
            UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
        END

        EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME    
        
        UPDATE FTR SET ESTADO = 'A', RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC', IDCAUANULACION=@IDCAUANULACION, CLASEANULACION = IIF(@N_FACTURA_EXTERNO = '','A','N') WHERE N_FACTURA=@N_FACTURA 
        IF EXISTS(SELECT 1 FROM FCJ INNER JOIN ACJ ON FCJ.CNSACJ=ACJ.CNSACJ WHERE FCJ.CODCAJA=@CODCAJA AND FCJ.CNSFACJ=@CNSFACJ  AND ( (@PAIS <> 'PERU' AND ACJ.ABIERTA = 1) OR (@PAIS = 'PERU'))) 
        BEGIN
            EXEC SPK_ANULARECIBO_CAJA @CODCAJA,@CNSFACJ,@USUARIO,1
        END
    END
END

