CREATE OR ALTER PROCEDURE DBO.SPK_DESPAGOSCXC
@CNSFPAG  VARCHAR(20),    
@SEDE     VARCHAR(5),
@COMPANIA VARCHAR(2),
@USUARIO  VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@ACCION VARCHAR(10)
WITH ENCRYPTION
AS                
DECLARE @CNSCXC         VARCHAR(20)    
DECLARE @N_FACTURA      VARCHAR(16)  
DECLARE @VLRPAGOS       DECIMAL(14,2)  
DECLARE @VLRIMPUESTO    DECIMAL(14,2)  
DECLARE @VLRGLOSAS      DECIMAL(14,2)  
DECLARE @AUX            DECIMAL(14,2)
DECLARE @NVOCONSEC      VARCHAR(20)
DECLARE @IDTERCERO      VARCHAR(20)
DECLARE @TIPOGLOSA      VARCHAR(1)
DECLARE @PAGO           DECIMAL(14,2)
DECLARE @OK             INT
DECLARE @DATO           VARCHAR(80)
DECLARE @OK1            INT
DECLARE @INGRESO        VARCHAR(10)
DECLARE @CNSFCXP        VARCHAR(20)
DECLARE @CNSFCXPP       VARCHAR(20) -- PARA ELIMINAR EL CONSECUTIVO DE PAGO
DECLARE @VLRCRUCE       DECIMAL(14,2)
DECLARE @NOREFERENCIA   VARCHAR(20)
DECLARE @FECHAPAGO      DATETIME
DECLARE @CUECREDITO     VARCHAR(16)
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @ITEM           SMALLINT
DECLARE @CLASE          VARCHAR(1)
DECLARE @CNSGLO         VARCHAR(20)
DECLARE @SINPAGO        SMALLINT
DECLARE @PORGLO         DECIMAL(14,6)
DECLARE @PORPAG         DECIMAL(14,6)
DECLARE @ENPRESUPUESTO  SMALLINT
DECLARE @CONSECUTIVOPTO VARCHAR(20)
DECLARE @RECO           VARCHAR(20)
DECLARE @CNSPAGOPTO     VARCHAR(20)
DECLARE @CERRADO        INT
DECLARE @CERRADOCART    INT
DECLARE @ESTADOPPTO     VARCHAR(20)
BEGIN   
                   
   SELECT @OK = COUNT(*) FROM FPAG WHERE CNSFPAG = @CNSFPAG 
   AND CERRADO = 1    
   IF @OK = 0 
   BEGIN
      RETURN
   END   
   SELECT @INGRESO = INGRESO, @FECHAPAGO = FECHAPAGO, @IDTERCERO = IDTERCERO, @NROCOMPROBANTE = NROCOMPROBANTE
   FROM   FPAG 
   WHERE  CNSFPAG = @CNSFPAG
   PRINT '@INGRESO='+@INGRESO
   IF @INGRESO = 'LEVANTA'  
   BEGIN
      EXEC SPK_LEVANTA_GLOSA @CNSFPAG, @USUARIO, @SEDE, 'D'
      RETURN
   END

   SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE= 'IDFDEPCARTERA'
      
   SELECT @OK = COUNT(*) FROM FGLO 
   WHERE FGLO.CNSFPAG = @CNSFPAG
      
   SELECT @OK1 = COUNT(*) FROM FGLO 
   WHERE FGLO.CNSFPAG = @CNSFPAG
   AND   FGLO.IDDEP   = @DATO
        
   IF @OK <> @OK1 
   BEGIN 
	   PRINT 'LAS GLOSAS YA ESTAN EN AUDITORIA.....'
      IF (SELECT  COUNT(*) FROM FGLO  WHERE FGLO.CNSFPAG = @CNSFPAG   AND CERRADA=1)<=0
      BEGIN
         PRINT 'Las quitamos del envio.....'
         DELETE ENTD FROM ENTD INNER JOIN FGLO ON ENTD.NODOCUMENTO=FGLO.CNSGLO AND ENTD.PROCESO='GLOSAS'
         WHERE FGLO.CNSFPAG = @CNSFPAG
         PRINT 'LUEGO BORRAMOS LAS GLOSAS'
         DELETE FROM FGLOD WHERE CNSGLO IN (SELECT CNSGLO FROM FGLO WHERE CNSFPAG = @CNSFPAG)
         DELETE FROM FGLO WHERE CNSFPAG = @CNSFPAG
      END
      ELSE
      BEGIN
         PRINT 'UNA O VARIAS GLOSAS YA FUERON RESPONDIDAS POR PARTE DE AUDITORIA'
         RETURN
      END
   END
   ELSE
   BEGIN
      DELETE FROM FGLOD WHERE CNSGLO IN (SELECT CNSGLO FROM FGLO WHERE CNSFPAG = @CNSFPAG)
      DELETE FROM FGLO WHERE CNSFPAG = @CNSFPAG
   END
   IF @ACCION='DESAPLICAR'
   BEGIN   
      UPDATE FPAG SET CERRADO = 0,CONTABILIZADO=0,NROCOMPROBANTE=NULL  WHERE CNSFPAG = @CNSFPAG     
      UPDATE FPAGD SET CERRADO = 0 WHERE CNSFPAG = @CNSFPAG
   END
   
   IF @INGRESO='BANCOS'
   BEGIN
      PRINT 'Actualizando Ingreso en Bancos...'    
      UPDATE BMOVD SET VLRLEGALIZADO = BMOVD.VLRLEGALIZADO - FPAG.VLRITEMS
      FROM   FPAG INNER JOIN BMOVD ON BMOVD.BANCO    = FPAG.BANCO 
                                  AND BMOVD.SUCURSAL = FPAG.SUCURSAL 
                                  AND BMOVD.CTA_BCO  = FPAG.CTA_BCO 
                                  AND BMOVD.ITEM     = FPAG.ITEM 
                                  AND BMOVD.RENGLON  = FPAG.RENGLON 
      WHERE  FPAG.CNSFPAG = @CNSFPAG
      
      UPDATE BMOVD SET ENPAGOS = CASE WHEN BMOVD.VLRITEM - BMOVD.VLRLEGALIZADO = 0 THEN 1 ELSE 0 END
      FROM   FPAG INNER JOIN BMOVD ON BMOVD.BANCO    = FPAG.BANCO 
                                  AND BMOVD.SUCURSAL = FPAG.SUCURSAL 
                                  AND BMOVD.CTA_BCO  = FPAG.CTA_BCO 
                                  AND BMOVD.ITEM     = FPAG.ITEM 
                                  AND BMOVD.RENGLON  = FPAG.RENGLON 
      WHERE  FPAG.CNSFPAG = @CNSFPAG
   END

   IF @INGRESO='CAJA'
   BEGIN
      PRINT 'Actualizando Ingreso en Caja...'    
      UPDATE FCJ SET VLRLEGALIZADO = FCJ.VLRLEGALIZADO - FPAG.VLRITEMS
      FROM   FPAG INNER JOIN FCJ ON FCJ.CODCAJA = FPAG.CODCAJA AND FCJ.CNSFACJ = FPAG.CNSFACJ
      WHERE  FPAG.CNSFPAG = @CNSFPAG
      
      UPDATE FCJ SET ENPAGOS = CASE WHEN FCJ.VALORTOTAL - FCJ.VLRLEGALIZADO = 0 THEN 1 ELSE 0 END
      FROM   FPAG INNER JOIN FCJ ON FCJ.CODCAJA = FPAG.CODCAJA AND FCJ.CNSFACJ = FPAG.CNSFACJ
      WHERE  FPAG.CNSFPAG = @CNSFPAG
      
   END     
   DECLARE CXCPAG_CURSOR CURSOR FOR    
   SELECT DISTINCT CNSCXC FROM FPAGD    
   WHERE FPAGD.CNSFPAG = @CNSFPAG    
   OPEN CXCPAG_CURSOR    
   FETCH NEXT FROM CXCPAG_CURSOR    
   INTO @CNSCXC    
   WHILE @@FETCH_STATUS = 0    
   BEGIN    
      EXEC SPK_RELIQUIDACXCQX @CNSCXC    
      FETCH NEXT FROM CXCPAG_CURSOR    
      INTO @CNSCXC    
   END    
   CLOSE CXCPAG_CURSOR    
   DEALLOCATE CXCPAG_CURSOR    
   -- CURSOR PARA ELIMINAR PAGOS CUANDO EL INGRESO ES TIPO CXP
   
   IF @INGRESO = 'CXP'
   BEGIN
      DECLARE CXP_CURSOR CURSOR FOR    
      SELECT  CNSFCXP, VLRCRUCE, NOREFERENCIA, CNSFCXPP
      FROM    FPAGDCXP    
      WHERE   FPAGDCXP.CNSFPAG = @CNSFPAG    
      OPEN    CXP_CURSOR    
      FETCH NEXT FROM CXP_CURSOR    
      INTO  @CNSFCXP, @VLRCRUCE, @NOREFERENCIA, @CNSFCXPP    
      WHILE @@FETCH_STATUS = 0    
      BEGIN    
         SELECT @CUECREDITO = CUECREDITO FROM FCXP WHERE CNSFCXP = @CNSFCXP
         EXEC SPK_ADMIN_PAGOS 'CXP', @NOREFERENCIA, @CNSFCXP, @CNSFCXPP, 'DELETE', 
                              @VLRCRUCE, @IDTERCERO, @USUARIO, @SYS_COMPUTERNAME,
                              @COMPANIA, @SEDE, @CNSFPAG,
                              '', 'P', '', @FECHAPAGO, '', '', @CUECREDITO, '', ''
         PRINT 'RECALCULANDO LA CXP'
         --RECALCULANDO LA CXP JJIMENEZ 18-03-2013                     
         EXEC SPK_CALCULOVALORESCXP @CNSFCXP
         FETCH NEXT FROM CXP_CURSOR    
         INTO  @CNSFCXP, @VLRCRUCE, @NOREFERENCIA, @CNSFCXPP    
      END   
      CLOSE CXP_CURSOR    
      DEALLOCATE CXP_CURSOR    
   
   END

   IF @INGRESO = 'DEVOLUCION'
   BEGIN
      PRINT '@INGRESO='+@INGRESO

      INSERT INTO FCXCD(CNSCXC,N_FACTURA,USUARIO,COMPANIA,VALORFACTURA,CERRADA,TIENEGLOSAS,TIENEDEVOLUCION,CUENTA,IDPLAN)
      SELECT CNSCXC,FPAGD.N_FACTURA,@USUARIO,@COMPANIA,FPAGD.VLRFACTURA,0,0,0,FTR.CUENTACXC_RAD,FTR.IDPLAN
      FROM FPAGD INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG
                 INNER JOIN FTR  ON FPAGD.N_FACTURA=FTR.N_FACTURA
      WHERE FPAGD.CNSFPAG=@CNSFPAG

     UPDATE FTR SET  INDCXC = 1, INDASIGCXC = 1 WHERE N_FACTURA IN(SELECT N_FACTURA FROM FPAGD WHERE CNSFPAG=@CNSFPAG)

      DELETE FCXCR
      FROM FCXCR INNER JOIN FPAGD ON FCXCR.CNSCXC=FPAGD.CNSCXC AND FCXCR.N_FACTURA=FPAGD.N_FACTURA
      WHERE FPAGD.CNSFPAG=@CNSFPAG

      INSERT INTO FCXCDV (CNSCXC, N_FACTURA, CNSGLO, TIPO, SALDOINICIAL, SALDONETO, FECHA, F_RECIBIDO, F_VENCE, MARCAPAGO, IDFCONCI, LEVANTADO, VLRLEVANTADO)
      SELECT FCXCD.CNSCXC,FPAGD.N_FACTURA,NULL,'F',FPAGD.VLRFACTURA,FPAGD.VLRFACTURA,GETDATE(),FCXC.F_RECIBIDO,FCXC.F_RECIBIDO+30,0,NULL,0,0
      FROM FPAGD INNER JOIN FCXCD ON FPAGD.CNSCXC=FCXCD.CNSCXC AND FCXCD.N_fACTURA=FPAGD.N_fACTURA
                 INNER JOIN FCXC  ON FCXCD.CNSCXC=FCXC.CNSCXC
      WHERE FPAGD.CNSFPAG=@CNSFPAG         
     
   END

   SELECT @CERRADO=COALESCE(A.CERRADO,0),@CERRADOCART=COALESCE(A.CERRADO_CARTERA,0) 
   FROM PRI A INNER JOIN  MCP B ON A.ANO=B.ANO AND A.MES=B.MES
   WHERE B.NROCOMPROBANTE=@NROCOMPROBANTE
			
   PRINT 'PASO A LA PARTE CONTABLE'
   PRINT 'CERRADO = '+STR(@CERRADO)+'CERRADOCARTERA = '+STR(@CERRADOCART)
   IF @CERRADO=1  --AND( @CERRADOCART=1 OR @CERRADOCART=0)
   BEGIN    
	   PRINT 'Contabilización...'
	   EXEC SPK_REVERSAR_RECUADO @NROCOMPROBANTE, @CNSFPAG, @COMPANIA, @SEDE,@USUARIO,@SYS_COMPUTERNAME,'','',0 	 
   END
   IF @CERRADO=0 AND @CERRADOCART=1
   BEGIN    
	   PRINT 'Contabilización...'
	   EXEC SPK_REVERSAR_RECUADO @NROCOMPROBANTE, @CNSFPAG, @COMPANIA, @SEDE,@USUARIO,@SYS_COMPUTERNAME,'','',0 
   END
   IF @CERRADO=0 AND @CERRADOCART=0
   BEGIN
      IF @ACCION='DESAPLICAR' 
      BEGIN
         PRINT 'ACTUALIZACION........'
         IF EXISTS (SELECT 1 FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)
         BEGIN
		      UPDATE MCP SET ESTADO=0,ANULADO=1 WHERE NROCOMPROBANTE=@NROCOMPROBANTE
         END
      /*20260812 STORRES SE AGREGA CONDICION PARA QUE ELIMINE LOS REGISTROS EN MCPE Y MCHE YA QUE 
                         CUANDO EL COMPROBANTE ESTA ERRADO EL COMPROBANTE QUEDA VIVO EN ERRADOS
      */
         ELSE 
            IF EXISTS (SELECT 1 FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE)
            BEGIN
		         DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
               DELETE MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
            END

		   PRINT 'LIBERANDO EL PAGO DE CONTABILIDAD.....'					
		   UPDATE FPAG SET CONTABILIZADO=0,NROCOMPROBANTE=NULL WHERE CNSFPAG=@CNSFPAG
      END
      ELSE
      BEGIN
	      PRINT 'Contabilización...'
	      EXEC SPK_REVERSAR_RECUADO @NROCOMPROBANTE, @CNSFPAG, @COMPANIA, @SEDE,@USUARIO,@SYS_COMPUTERNAME,'','',0        
      END
   END	
   DECLARE PAGD_CURSOR CURSOR FOR    
   SELECT CNSCXC, N_FACTURA, ITEM, TIPOGLOSA, SINPAGO, CLASE, CNSGLO
   FROM   FPAGD    
   WHERE  CNSFPAG = @CNSFPAG  
   AND    CERRADO = 0    
   --AND    CLASEPAG = 'P'   
   OPEN PAGD_CURSOR    
   FETCH NEXT FROM PAGD_CURSOR    
   INTO @CNSCXC, @N_FACTURA, @ITEM, @TIPOGLOSA, @SINPAGO, @CLASE, @CNSGLO
   WHILE @@FETCH_STATUS = 0    
   BEGIN           
      IF @CLASE = 'G'
      BEGIN
         UPDATE FCXCDV SET MARCAPAGO = 0
         WHERE  CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA AND TIPO <> 'F' 
         AND    CNSGLO = @CNSGLO 
      END
      ELSE
      BEGIN
         UPDATE FCXCDV SET MARCAPAGO = 0
         WHERE  CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA AND TIPO = 'F' 
      END
	   EXEC SPK_RELIQUIDA_FTR @CNSCXC,@N_FACTURA
  
      FETCH NEXT FROM PAGD_CURSOR    
      INTO @CNSCXC, @N_FACTURA, @ITEM, @TIPOGLOSA, @SINPAGO, @CLASE, @CNSGLO
   END    
   CLOSE PAGD_CURSOR    
   DEALLOCATE PAGD_CURSOR    
   /* B1*/
   
   UPDATE FTRCXC SET SALDO=A.SALDO + COALESCE(B.VLR_PAGO,0)
   FROM FTRCXC A INNER JOIN FPAGDC B ON A.N_FACTURA=B.N_FACTURA AND A.CCOSTO=B.CCOSTO
                  INNER JOIN TTEC   C ON A.TIPOTTEC=C.TIPO 
   WHERE B.CNSFPAG=@CNSFPAG AND A.CUENTACXC=C.CUENTARAD 
      
   UPDATE FTRCXC SET SALDO=A.SALDO - COALESCE(B.VLR_PAGO,0)
   FROM FTRCXC A INNER JOIN FPAGDC B ON A.N_FACTURA=B.N_FACTURA
                  INNER JOIN TTEC   C ON A.TIPOTTEC=C.TIPO 
   WHERE B.CNSFPAG=@CNSFPAG AND A.CUENTACXC=C.CTAGLOSADB 
          
   DELETE FPAGDC WHERE CNSFPAG=@CNSFPAG  
	
	IF DBO.FNK_VALORVARIABLE('PRESUP_CXC_ACTIVADO')= 'SI'
   BEGIN
		IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')= 'FACTURA'
		BEGIN
			DECLARE PAGD_CURSOR CURSOR FOR 
			SELECT ENPRESUPUESTO, CONSECUTIVOPTO, RECO, CNSPAGOPTO
			FROM   FPAGD    
			WHERE  CNSFPAG = @CNSFPAG  
			AND    COALESCE(ENPRESUPUESTO,0) = 1  
	   END
		ELSE 
		BEGIN
			DECLARE PAGD_CURSOR CURSOR FOR 
			SELECT ENPRESUPUESTO, CONSECUTIVOPTO, RECO, CNSPAGOPTO
			FROM   FPAGD    
			WHERE  CNSFPAG = @CNSFPAG  
			AND    COALESCE(ENPRESUPUESTO,0) = 1
			GROUP BY ENPRESUPUESTO, CONSECUTIVOPTO, RECO, CNSPAGOPTO  
		END
      OPEN PAGD_CURSOR    
      FETCH NEXT FROM PAGD_CURSOR    
      INTO @ENPRESUPUESTO, @CONSECUTIVOPTO, @RECO, @CNSPAGOPTO
      WHILE @@FETCH_STATUS = 0    
      BEGIN 
         IF EXISTS(SELECT * FROM PTRECA WHERE CNSPAGO = @CNSPAGOPTO AND COMPANIA =@COMPANIA AND CONSECUTIVO = @CONSECUTIVOPTO AND RECO = @RECO AND ESTADO='Confirmado' )
         BEGIN
            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE CNSPAGO = @CNSPAGOPTO AND COMPANIA =@COMPANIA AND CONSECUTIVO = @CONSECUTIVOPTO AND RECO = @RECO AND ESTADO='Confirmado' 
         END
			DELETE PTRECAD WHERE CNSPAGO = @CNSPAGOPTO AND COMPANIA =@COMPANIA AND CONSECUTIVO = @CONSECUTIVOPTO AND RECO = @RECO    
         UPDATE PTRECA SET ESTADO = 'Anulado' WHERE CNSPAGO = @CNSPAGOPTO AND COMPANIA =@COMPANIA AND CONSECUTIVO = @CONSECUTIVOPTO AND RECO = @RECO
         FETCH NEXT FROM PAGD_CURSOR    
         INTO @ENPRESUPUESTO, @CONSECUTIVOPTO, @RECO, @CNSPAGOPTO
      END
      CLOSE PAGD_CURSOR
      DEALLOCATE PAGD_CURSOR 
      UPDATE FPAGD SET ENPRESUPUESTO=0 WHERE CNSFPAG=@CNSFPAG
   END
   IF @ACCION='ANULAR'
   BEGIN
      PRINT 'SE CREA LA COPIA DEL RECUADO'
      EXEC SPK_COPIA_RECAUDO @CNSFPAG,@SEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME   
   END      
END

