CREATE OR ALTER PROCEDURE DBO.SPK_ANULANOTA_CR
@CNSFNOT             VARCHAR(20),
@NROCOMPROBANTE      VARCHAR(20),
@NROCOMPROBANTEDES   VARCHAR(20),
@SEDE						VARCHAR(2),
@COMPANIA				VARCHAR(5),
@USUARIO             VARCHAR(12),
@SYS_COMPUTERNAME    VARCHAR(254),
@PROCESO             VARCHAR(10)
WITH ENCRYPTION
AS
DECLARE @NVOCONSEC     VARCHAR(20)
DECLARE @NOREFERENCIA  VARCHAR(20)
DECLARE @PREFIJO_USCXS VARCHAR(20)
DECLARE @COM           VARCHAR(2)
DECLARE @FECHACONTABLE DATETIME
DECLARE @ANO           VARCHAR(4)
DECLARE @MES			  VARCHAR(2)
DECLARE @ANO_ANT       VARCHAR(4)
DECLARE @PROCENOTA     VARCHAR(20)
DECLARE @N_FACTURA     VARCHAR(20)
DECLARE @CUENTACR      VARCHAR(20)
DECLARE @ESTADO        VARCHAR(2)
DECLARE @CNSCXC        VARCHAR(20)
DECLARE @ANULAREVERSA  VARCHAR(10) 
DECLARE @ENMPC         SMALLINT
DECLARE @NVOCNSFNOT    VARCHAR(20)
BEGIN
   PRINT 'INGRESE'
   PRINT 'Valido Dian'
   IF EXISTS(SELECT  * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND FACTE=2) AND @PROCESO='NOTAS'
   BEGIN
      PRINT 'Ya fue enviado a la Dian, Debo Crear Nota Debito'
	   SELECT @ESTADO=ESTADO,@CNSCXC=CNSCXC,@N_FACTURA=N_FACTURA FROM FNOT WHERE CNSFNOT=@CNSFNOT
	   IF COALESCE(@ESTADO,'')='A'
	   BEGIN
		    RAISERROR('Nota Anulada, no se puede generar reversión',16,1)
		   RETURN
	   END 
      BEGIN TRY           
         EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTD',  @NVOCNSFNOT OUTPUT 
         SELECT @NVOCNSFNOT = @SEDE + 'D' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
      END TRY
      BEGIN CATCH
            RAISERROR('No se Genero el consecutivo de la nota debito',16,1)
            RETURN
      END CATCH
      PRINT '@NVOCNSFNOT='+@NVOCNSFNOT
      INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                        MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                        CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                        CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                        IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                        VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
      SELECT @NVOCNSFNOT,'D', N_FACTURA, CNSCXC, IDTERCERO,DBO.FNK_GETDATE(), VR_TOTAL,'Glosa Anulada desde Auditoria', 
                        MARCA, MARCACONT, IIF(COALESCE(@NROCOMPROBANTEDES,'') = '',0,1) CONTABILIZADA, @NROCOMPROBANTEDES, IMPRESO, COMPANIA, USUARIO, --STORRES - NVOOS 20260819 SE CAMBIA NRO COMPROBANTE Y SE AGREGA @NROCOMPROBANTEDES Y SE VALIDA QUE SI ESTA EN BLANCO CONTABILIZADA = 0 DE LO CONTRARIO ES 1
                        CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                        CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                        IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                        VALORCONCEPTO, @USUARIO, DETGENERADOS
      FROM FNOT 
      WHERE CNSFNOT=@CNSFNOT

      INSERT INTO FNOTD (CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, 
                          OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA, CCOSTO, IDAREA, PREFIJO, CUENTA )
      SELECT @NVOCNSFNOT,'D', ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, 
              N_CUOTA, PIVA, VALORIVA, N_FACTURA, CCOSTO, IDAREA, PREFIJO, CUENTA 
      FROM FNOTD 
      WHERE CNSFNOT=@CNSFNOT

      EXEC SPK_NOTASCXC @NVOCNSFNOT,'D', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME 

      EXEC SPK_RELIQUIDA_FTR @CNSCXC,@N_FACTURA

   END
   ELSE
   BEGIN
      SELECT @ANULAREVERSA='REVERSA'
      IF DBO.FNK_VALORVARIABLE('FNOT_ANULA_REVERSA')='ANULA'
      BEGIN
         IF(SELECT CERRADO  FROM PRI WHERE EXISTS(SELECT * FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND MCP.ANO=PRI.ANO AND MCP.MES=PRI.MES))=0
         BEGIN
            SELECT @ANULAREVERSA='ANULA'
         END
         ELSE
         BEGIN
            SELECT @ANULAREVERSA='REVERSA'
         END
      END
      IF @PROCESO='NOTAS' OR  @PROCESO='AJUSTE'
      BEGIN
	      SELECT @ESTADO=ESTADO,@CNSCXC=CNSCXC,@N_FACTURA=N_FACTURA FROM FNOT WHERE CNSFNOT=@CNSFNOT
	      IF COALESCE(@ESTADO,'')='A'
	      BEGIN
		      PRINT 'LA NOTA YA SE ENCUENTRA ANULADA'
            RAISERROR('Nota Credio Anulada,',16,1)
		      RETURN
	      END 
         IF EXISTS(SELECT * FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)
         BEGIN
            SELECT @ENMPC=1
         END
         ELSE
         BEGIN
            SELECT @ENMPC=0
         END
         IF @ANULAREVERSA='REVERSA' AND @ENMPC=1
         BEGIN
	         SELECT @COM = RTRIM(LTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_REVFTR')))
	         IF COALESCE(@NROCOMPROBANTEDES,'')=''
	         BEGIN
		         SELECT @ANO = YEAR(GETDATE()),@MES = MONTH(GETDATE())

		         SET @PREFIJO_USCXS='@COM'+@COM
		         SET @NOREFERENCIA=SPACE(20)
		         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
		         SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)

		         PRINT 'COM: '+@COM
		         PRINT 'Nuevo Comprobante: '+@NOREFERENCIA
				 
		         SET @NVOCONSEC = SPACE(20) 
		         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NVOCONSEC OUTPUT 
		         SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NVOCONSEC) > 8 THEN 8 ELSE LEN(@NVOCONSEC) END)+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

		         PRINT 'NROCOMPROBANTE: '+@NVOCONSEC

		         INSERT INTO MCPE(COMPANIA,NROCOMPROBANTE,PROCEDENCIA,NOREFERENCIA,ANO,MES,FECHACONTABLE,TOTALDEBITO,TOTALCREDITO,
					            REFERENCIA1,REFERENCIA2,USUARIO,FECHA,LOTE,OBSERVACION,IDSEDE,ESTADO,COMPROBANTE,IDTERCERO,REFERENCIA3,
					            BANCO,NOCHEQUE,ANULADO,RPT_COMPROBANTE,VALOR_CHEQUE,FECHARADICACION)
		         SELECT COMPANIA,@NVOCONSEC,'REVNOTDBCR', @NOREFERENCIA,@ANO,@MES,GETDATE(),TOTALDEBITO,TOTALCREDITO,
				          REFERENCIA1,REFERENCIA2,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),LOTE, LEFT('REVERSION NOTA CREDITO: '+OBSERVACION,512),
				          IDSEDE,ESTADO,@COM,IDTERCERO,@NROCOMPROBANTE,BANCO,NOCHEQUE,ANULADO,RPT_COMPROBANTE,VALOR_CHEQUE,FECHARADICACION
		         FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE
	         END	
	         DELETE 	MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTEDES
            INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA,      TIPO,      CUENTA,       IDTERCERO, CCOSTO,      DETALLE,      VALOR, 
                            REFERENCIA1,    REFERENCIA2,   ITEMREF,   USUARIO,      FECHA,     PREFIJO,     IDAREA,    
                            CLASECONT,      ESTADO,        PROCESO,   REFERENCIA3,  CNSPAGO,   GENERA,      F_FACTURAREF, 
                            F_VENCE,        VALOR_PORCIMP, BASE_IMP,  CLASE_GENERA, N_FACTURA, PROCEDENCIA,  
                            REFERENCIA_PRO, CONCILIADO,    CNSFCXCXP, CODUNG,       CODPRG,    ERROR )
            SELECT @NVOCONSEC, COMPANIA,CASE WHEN TIPO='DB' THEN 'CR' ELSE 'DB' END,CUENTA,
                   IDTERCERO, CCOSTO, 'REVERSION NOTA '+ DETALLE, VALOR, REFERENCIA1,REFERENCIA2, ITEMREF,
                   @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO, IDAREA, CLASECONT,1, 'REVERSION', REFERENCIA3, CNSPAGO, GENERA, F_FACTURAREF, F_VENCE,
                   VALOR_PORCIMP, BASE_IMP, CLASE_GENERA, N_FACTURA, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG,
                   CODPRG,ERROR
            FROM   MCH 
            WHERE  NROCOMPROBANTE = @NROCOMPROBANTE
      
            EXEC SPK_NC_REVISAMCPE @NVOCONSEC, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME

         END
         ELSE
         BEGIN
            IF @ENMPC=1
            BEGIN
               UPDATE MCP SET ESTADO=0, ANULADO=1 WHERE NROCOMPROBANTE=@NROCOMPROBANTE
               UPDATE MCH SET ESTADO=0  WHERE NROCOMPROBANTE=@NROCOMPROBANTE
            END
            ELSE
            BEGIN
               DELETE MCHE WHERE  NROCOMPROBANTE=@NROCOMPROBANTE
               DELETE MCPE WHERE  NROCOMPROBANTE=@NROCOMPROBANTE
            END
         END
	      UPDATE FNOT SET ESTADO='A' WHERE CNSFNOT=@CNSFNOT	

	      PRINT '@CNSCXC = '+COALESCE(@CNSCXC,'NO TENGO CXC')
	      PRINT 'N_FACTURA = '+COALESCE(@N_FACTURA,'NO TENGO N_FACTURA')
         IF COALESCE(@CNSCXC,'')<>''
         BEGIN
	      PRINT 'ENTRE ACA'
            EXEC SPK_RELIQUIDA_FTR @CNSCXC,@N_FACTURA
         PRINT 'SALGO'
         END
      END
	   IF @PROCESO='RGLO'
      BEGIN
         PRINT 'ingrese a Respuesta de Glosa'
	      SELECT @COM = RTRIM(LTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_REVFTR')))
	      IF COALESCE(@NROCOMPROBANTEDES,'')=''
	      BEGIN
		      SELECT @ANO = YEAR(GETDATE()),@MES = MONTH(GETDATE())

		      SET @PREFIJO_USCXS='@COM'+@COM
		      SET @NOREFERENCIA=SPACE(20)
		      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
		      SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)

		      PRINT 'COM: '+@COM
		      PRINT 'Nuevo Comprobante: '+@NOREFERENCIA
				 
		      SET @NVOCONSEC = SPACE(20) 
		      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NVOCONSEC OUTPUT 
		      SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NVOCONSEC) > 8 THEN 8 ELSE LEN(@NVOCONSEC) END)+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

		      PRINT 'NROCOMPROBANTE: '+@NVOCONSEC

		      INSERT INTO MCPE(COMPANIA,NROCOMPROBANTE,PROCEDENCIA,NOREFERENCIA,ANO,MES,FECHACONTABLE,TOTALDEBITO,TOTALCREDITO,
					         REFERENCIA1,REFERENCIA2,USUARIO,FECHA,LOTE,OBSERVACION,IDSEDE,ESTADO,COMPROBANTE,IDTERCERO,REFERENCIA3,
					         BANCO,NOCHEQUE,ANULADO,RPT_COMPROBANTE,VALOR_CHEQUE,FECHARADICACION)
		      SELECT COMPANIA,@NVOCONSEC,'REVNOTDBCR', @NOREFERENCIA,@ANO,@MES,GETDATE(),TOTALDEBITO,TOTALCREDITO,
				       REFERENCIA1,REFERENCIA2,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),LOTE, LEFT('REVERSION RESPUESTA DE GLOSA: '+OBSERVACION,512),
				       IDSEDE,ESTADO,@COM,IDTERCERO,@NROCOMPROBANTE,BANCO,NOCHEQUE,ANULADO,RPT_COMPROBANTE,VALOR_CHEQUE,FECHARADICACION
		      FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE
	      END	
	      DELETE 	MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTEDES
         INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA,      TIPO,      CUENTA,       IDTERCERO, CCOSTO,      DETALLE,      VALOR, 
                         REFERENCIA1,    REFERENCIA2,   ITEMREF,   USUARIO,      FECHA,     PREFIJO,     IDAREA,    
                         CLASECONT,      ESTADO,        PROCESO,   REFERENCIA3,  CNSPAGO,   GENERA,      F_FACTURAREF, 
                         F_VENCE,        VALOR_PORCIMP, BASE_IMP,  CLASE_GENERA, N_FACTURA, PROCEDENCIA,  
                         REFERENCIA_PRO, CONCILIADO,    CNSFCXCXP, CODUNG,       CODPRG,    ERROR )
         SELECT @NVOCONSEC, COMPANIA,CASE WHEN TIPO='DB' THEN 'CR' ELSE 'DB' END,CUENTA,
                IDTERCERO, CCOSTO, 'REVERSION RESPUESTA DE GLOSA: '+ DETALLE, VALOR, REFERENCIA1,REFERENCIA2, ITEMREF,
                @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO, IDAREA, CLASECONT,1, 'REVERSION', REFERENCIA3, CNSPAGO, GENERA, F_FACTURAREF, F_VENCE,
                VALOR_PORCIMP, BASE_IMP, CLASE_GENERA, N_FACTURA, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG,
                CODPRG,ERROR
         FROM   MCH 
         WHERE  NROCOMPROBANTE = @NROCOMPROBANTE
   
         EXEC SPK_NC_REVISAMCPE @NVOCONSEC, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME
      END
   END
   PRINT 'Colocando la Respuesta de Glosa Sin Enviar a Contabilidad'
   UPDATE FGLO SET CONTABILIZADA=0,NROCOMPROBANTE=NULL WHERE CNSGLO=@CNSFNOT
END

