IF EXISTS (SELECT name FROM sysobjects   WHERE NAME = 'SPK_REPORTES_VARIOS_CARTERA' AND type = 'P')
BEGIN
   DROP PROCEDURE SPK_REPORTES_VARIOS_CARTERA
END
GO
CREATE PROCEDURE DBO.SPK_REPORTES_VARIOS_CARTERA
@CNSRPDX      VARCHAR(20),
@FECHAINICIAL DATETIME,
@FECHAFINAL   DATETIME,
@IDTERCERO    VARCHAR (20) = ''
WITH ENCRYPTION
AS
DECLARE @IDTERCEROCUR VARCHAR(20)
DECLARE @ITEMCUR      INT
BEGIN
   DECLARE @CONSEC VARCHAR(20), @CNS_01 VARCHAR(20), @CNS_02 VARCHAR(20), @CNS_03 VARCHAR(20), @CNS_04 VARCHAR(20), @CNS_05 VARCHAR(20)
   SELECT @CONSEC = @CNSRPDX + '%'
   DELETE RPDX WHERE CNS LIKE @CONSEC
   SELECT @CNS_01 = @CNSRPDX + '_01', @CNS_02 = @CNSRPDX + '_02', @CNS_03 = @CNSRPDX + '_03', @CNS_04 = @CNSRPDX + '_04', @CNS_05 = @CNSRPDX + '_05'
   --Radicacion por empresa y recaudos legalizados POR REGIMEN
   INSERT INTO RPDX(CNS, STRINGMEDIO1, IDTERCERO, NOMBRE,  VALOR1, VALOR2, VALOR3, VALOR4, VALOR5, VALOR6, VALOR7, VALOR8, VALOR9)
   SELECT @CNS_01, Z.REGIMEN, Z.IDTERCERO, LEFT(Z.RAZONSOCIAL,150), SUM (CAPITADO) CAPITADO ,SUM(EVENTO)    EVENTO , SUM(CAPITADO) + SUM(EVENTO) TOTALRADICACION , 
	       ISNULL(VIGACT_CAPITADO,0) RECA_VIGACT_CAPITADO,ISNULL(VIGACT_EVENTO,0)RECA_VIGACT_EVENTO, 
	       ISNULL(VIGANT_CAPITADO,0) RECA_VIGANT_CAPITADO,ISNULL(VIGANT_EVENTO,0)RECA_VIGANT_EVENTO,
	       ISNULL(L.VR_LEGALIZADO,0) TOTALRECAIDEN, COALESCE (L.VALORPAGO,0)-COALESCE (L.VR_LEGALIZADO,0)TOTALRECAXIDEN 
   FROM (SELECT FCXC.IDTERCERO, TER.RAZONSOCIAL, COALESCE (TGEN.DESCRIPCION,'SIN_CNF') REGIMEN,
		   CASE WHEN FTR.CAPITADA=1 THEN FCXCD.VALORFACTURA ELSE 0 END CAPITADO, 
		   CASE WHEN FTR.CAPITADA=0 THEN FCXCD.VALORFACTURA ELSE 0 END EVENTO,
		   CASE WHEN YEAR (FTR.F_FACTURA)<YEAR  (GETDATE ()) THEN VALORFACTURA ELSE 0 END VIGENCIA_ANTERIOR,  
		   CASE WHEN YEAR (FTR.F_FACTURA)=YEAR  (GETDATE ()) THEN VALORFACTURA ELSE 0 END VIGENCIA_ACTUAL  
		   FROM FCXCD INNER JOIN FCXC ON FCXC.CNSCXC=FCXCD.CNSCXC
				      INNER JOIN FTR ON FCXCD.N_FACTURA=FTR.N_FACTURA
				      INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN  
				      INNER JOIN TER ON TER.IDTERCERO=FCXC.IDTERCERO
				      LEFT JOIN TGEN ON TGEN.CODIGO=PLN.REGIMEN2193 AND TGEN.CAMPO='REGIMEN' AND TGEN.TABLA='2193'
		   
		   WHERE  COALESCE (INDRECIBIDO,0)=1   AND DBO.FNK_FECHA_SIN_HORA( F_RECIBIDO) BETWEEN @FECHAINICIAL AND @FECHAFINAL )Z

   LEFT JOIN  (SELECT REGIMEN,IDTERCERO, SUM (VIGENCIA_ACTUAL_CAPITADO) VIGACT_CAPITADO ,SUM (VIGENCIA_ACTUAL_EVENTO)VIGACT_EVENTO ,
				     SUM (VIGENCIA_ANTERIOR_CAPITADO)VIGANT_CAPITADO,SUM (VIGENCIA_ANTERIOR_EVENTO)VIGANT_EVENTO
			    FROM (
						   SELECT 
						   COALESCE (TGEN.DESCRIPCION,'SIN_CNF') REGIMEN ,FPAG.IDTERCERO, 
		
						   CASE WHEN YEAR (FTR.F_FACTURA)=YEAR  (GETDATE ()) AND FTR.CAPITADA=1 THEN FPAGD.VALORPAGO ELSE 0 END VIGENCIA_ACTUAL_CAPITADO,
						   CASE WHEN YEAR (FTR.F_FACTURA)=YEAR  (GETDATE ()) AND FTR.CAPITADA=0 THEN FPAGD.VALORPAGO ELSE 0 END VIGENCIA_ACTUAL_EVENTO,		
						   CASE WHEN YEAR (FTR.F_FACTURA)<YEAR  (GETDATE ()) AND FTR.CAPITADA=0 THEN FPAGD.VALORPAGO ELSE 0 END VIGENCIA_ANTERIOR_EVENTO,
						   CASE WHEN YEAR (FTR.F_FACTURA)<YEAR  (GETDATE ()) AND FTR.CAPITADA=1 THEN FPAGD.VALORPAGO ELSE 0 END VIGENCIA_ANTERIOR_CAPITADO 
		  
						   FROM FPAGD 				   
								      INNER JOIN FPAG ON FPAG.CNSFPAG=FPAGD.CNSFPAG
								      INNER JOIN TER ON TER.IDTERCERO =FPAG.IDTERCERO
								      INNER JOIN FTR ON FPAGD.N_FACTURA=FTR.N_FACTURA
								      INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN  
								      LEFT JOIN TGEN ON TGEN.CODIGO=PLN.REGIMEN2193 AND TGEN.CAMPO='REGIMEN' AND TGEN.TABLA='2193'
		   
						   WHERE  COALESCE(FPAG.CERRADO,0)=1 AND FPAG.INGRESO='BANCOS' AND  DBO.FNK_FECHA_SIN_HORA(FPAG.FECHAPAGO) BETWEEN @FECHAINICIAL AND @FECHAFINAL )Z
			   GROUP BY REGIMEN,IDTERCERO) P ON P.REGIMEN=Z.REGIMEN AND P.IDTERCERO=Z.IDTERCERO

   LEFT JOIN (SELECT IDTERCERO, REGIMEN , SUM(VALORPAGO) VALORPAGO, SUM (VR_LEGALIZADO)  VR_LEGALIZADO 
 			     FROM (SELECT FPAG. IDTERCERO, RAZONSOCIAL,FPAG.CNSFPAG,COALESCE (TGEN.DESCRIPCION,'SIN_CNF')REGIMEN,MAX (FPAG.VALORPAGO) VALORPAGO ,SUM (FPAGD.VALORPAGO) VR_LEGALIZADO  
					     FROM FPAG 
						   INNER JOIN TER ON TER.IDTERCERO =FPAG.IDTERCERO
						   INNER JOIN FPAGD ON FPAG.CNSFPAG=FPAGD.CNSFPAG
						   INNER JOIN FTR ON FPAGD.N_FACTURA=FTR.N_FACTURA
						   INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN  
						   LEFT JOIN TGEN ON TGEN.CODIGO=PLN.REGIMEN2193 AND TGEN.CAMPO='REGIMEN' AND TGEN.TABLA='2193'

					   WHERE  COALESCE(FPAG.CERRADO,0)=1 AND FPAG.INGRESO='BANCOS' AND  DBO.FNK_FECHA_SIN_HORA(FPAG.FECHAPAGO) BETWEEN @FECHAINICIAL AND @FECHAFINAL

					   GROUP BY FPAG. IDTERCERO, RAZONSOCIAL,FPAG.CNSFPAG, COALESCE (TGEN.DESCRIPCION,'SIN_CNF'))Z
			   GROUP BY IDTERCERO, REGIMEN )L ON Z.IDTERCERO=L.IDTERCERO AND Z.REGIMEN=L.REGIMEN
   WHERE Z.REGIMEN <> 'Otros Deudores Por Ventas De Salud'
   GROUP BY  Z.IDTERCERO, Z.REGIMEN, Z.RAZONSOCIAL, ISNULL(VIGACT_CAPITADO,0) ,ISNULL(VIGACT_EVENTO,0), 
	   ISNULL(VIGANT_CAPITADO,0) ,ISNULL(VIGANT_EVENTO,0), ISNULL(L.VR_LEGALIZADO,0) , COALESCE (L.VALORPAGO,0)-COALESCE (L.VR_LEGALIZADO,0)
   ORDER BY Z.REGIMEN, Z.IDTERCERO
   ----reporte general de Pagos por Fecha de Pagos 
   INSERT INTO RPDX(CNS, ID1, ID2, FECHA1, FECHA2, IDTERCERO, NOMBRE,  VALOR1, VALOR2, VALOR3, ID3, VALOR4, VALOR5, VALOR6)
   SELECT @CNS_02, FPAG.CNSFPAG, FPAG.INGRESO, FPAG.FECHAPAGO ,FPAG.FECHA F_LEGALIZACION, FPAG.IDTERCERO, LEFT(X.RAZONSOCIAL,150) RAZONSOCIAL, 
          X.VALORPAGO, X.VR_LEGALIZADO, X.VALORPAGO-X.VR_LEGALIZADO SALDOPAGO,
	       FPAGD.N_FACTURA,FCXCD.VALORFACTURA VR_FACTURA, FPAGD.VALORPAGO VR_PAGOFACT, FCXCD.VALORFACTURA-FPAGD.VALORPAGO SALDOFACT
   FROM   FPAG INNER JOIN FPAGD ON FPAG.CNSFPAG=FPAGD.CNSFPAG 
		         INNER JOIN FCXCD ON FPAGD.N_FACTURA=FCXCD.N_FACTURA
		         INNER JOIN (SELECT FPAG.CNSFPAG,FPAG. IDTERCERO, RAZONSOCIAL,CASE WHEN  FPAG.CERRADO=1 THEN 'APLICADO' ELSE 'NO APLICADO' END ESTADO,
				                      MAX (FPAG.VALORPAGO) VALORPAGO ,SUM (FPAGD.VALORPAGO) VR_LEGALIZADO  
					            FROM   FPAG INNER JOIN TER ON TER.IDTERCERO =FPAG.IDTERCERO
						                     INNER JOIN FPAGD ON FPAG.CNSFPAG=FPAGD.CNSFPAG 
					            WHERE INGRESO='BANCOS'
                           GROUP BY FPAG.CNSFPAG,FPAG. IDTERCERO, RAZONSOCIAL, 
                                    CASE WHEN  FPAG.CERRADO=1 THEN 'APLICADO' ELSE 'NO APLICADO' END
                          ) X ON FPAG.CNSFPAG=X.CNSFPAG
   WHERE  INGRESO = 'BANCOS'  AND DBO.FNK_FECHA_SIN_HORA( FPAG.FECHAPAGO) BETWEEN @FECHAINICIAL AND @FECHAFINAL 
   AND    FPAG.IDTERCERO LIKE CASE WHEN @IDTERCERO = '' THEN FPAG.IDTERCERO ELSE @IDTERCERO END
   --REPORTE GENERAL DE CARTERA POR FACTURACION RADICADA
   INSERT INTO RPDX(CNS, FECHA1, IDTERCERO, NOMBRE, ID1, ID2, ID3, FECHA2, VALOR1, VALOR2, VALOR3, VALOR4, VALOR5, VALOR6, ID4, VALOR7, VALOR8, VALOR9)
   SELECT @CNS_03,  F_RECIBIDO, TER.IDTERCERO, LEFT(TER.RAZONSOCIAL,150) RAZONSOCIAL, LEFT(COALESCE (TGEN.DESCRIPCION,'SIN_CNF') ,20)TIPOSISTEMA,
          CASE WHEN FTR.CAPITADA = 1 THEN 'CAPITADA' ELSE 'EVENTO' END MODALIDAD, FCXCD.N_FACTURA, FTR.F_FACTURA,
	       VALORFACTURA  ,FCXCD.DEDUCCIONES, FCXCD.VLRPAGOS, FGLO. VLRGLOSA ,FGLO.VLRACEPTADO,VLRRECUPERAR,
	       CASE WHEN COALESCE (FGLO.N_FACTURA,'')='' THEN 'SINGLOS' ELSE CASE WHEN COALESCE (FGLO.CERRADA,0)=0 THEN 'NORESP' ELSE 'RESP' END END ESTADOG, 
          FCXCD.VLRNOTACR,FCXCD.VLRNOTADB,  FCXCD.SALDONETO 
   FROM   FCXCD INNER JOIN FCXC ON FCXC.CNSCXC=FCXCD.CNSCXC
		          INNER JOIN TER  ON TER.IDTERCERO=FCXC.IDTERCERO
		          INNER JOIN FTR  ON FCXCD.N_FACTURA=FTR.N_FACTURA
		          INNER JOIN PLN  ON FTR.IDPLAN=PLN.IDPLAN  
		           LEFT JOIN TGEN ON TGEN.CODIGO = PLN.REGIMEN2193  AND TGEN.CAMPO  = 'REGIMEN'  AND TGEN.TABLA  = '2193'
		           LEFT JOIN ( SELECT FGLO.N_FACTURA,
									SUM (COALESCE (FGLO.VLRGLOSA,0) )VLRGLOSA,SUM(COALESCE (FGLO.VLRACEPTADO,0))VLRACEPTADO,
									SUM (COALESCE (FGLO.VLRRECUPERAR,0))VLRRECUPERAR, MAX(COALESCE(FGLO.CERRADA,0))CERRADA FROM FGLO 
				   GROUP BY FGLO.N_FACTURA )FGLO ON FGLO.N_FACTURA=FCXCD.N_FACTURA
   WHERE  COALESCE (INDRECIBIDO,0)=1   
   AND    DBO.FNK_FECHA_SIN_HORA( F_RECIBIDO) BETWEEN @FECHAINICIAL AND @FECHAFINAL 
   AND    FCXC.IDTERCERO LIKE CASE WHEN @IDTERCERO = '' THEN FCXC.IDTERCERO ELSE @IDTERCERO END
   ORDER BY FCXCD.N_FACTURA
   ----RECAUDO POR REGIMEN 
   INSERT INTO RPDX(CNS, STRINGMEDIO1, VALOR1, VALOR2, VALOR3 )
   SELECT @CNS_04, REGIMEN, SUM (VIGENCIA_ANTERIOR) VIGENCIA_ANTERIOR ,SUM (VIGENCIA_ACTUAL)VIGENCIA_ACTUAL , SUM (VIGENCIA_ANTERIOR) + SUM (VIGENCIA_ACTUAL)TOTAL
   FROM (
		   SELECT COALESCE (TGEN.DESCRIPCION,'SIN_CNF')+' '+CASE WHEN FTR.CAPITADA=1 THEN 'CAPITADA' ELSE 'EVENTO' END  REGIMEN, 
		          CASE WHEN YEAR (FTR.F_FACTURA) < YEAR(GETDATE ()) THEN FPAGD.VALORPAGO ELSE 0 END VIGENCIA_ANTERIOR, 
		          CASE WHEN YEAR (FTR.F_FACTURA) = YEAR(GETDATE ()) THEN FPAGD.VALORPAGO ELSE 0 END VIGENCIA_ACTUAL
		   FROM   FPAGD INNER JOIN FPAG ON FPAG.CNSFPAG=FPAGD.CNSFPAG
				          INNER JOIN FTR  ON FPAGD.N_FACTURA = FTR.N_FACTURA
				          INNER JOIN PLN  ON FTR.IDPLAN  = PLN.IDPLAN  
				           LEFT JOIN TGEN ON TGEN.CODIGO = PLN.REGIMEN2193 
                                     AND TGEN.CAMPO  = 'REGIMEN' 
                                     AND TGEN.TABLA  = '2193'   
		   WHERE  COALESCE(FPAG.CERRADO,0)=1 
         AND    FPAG.INGRESO='BANCOS' 
         AND  DBO.FNK_FECHA_SIN_HORA(FPAG.FECHA) BETWEEN @FECHAINICIAL AND @FECHAFINAL ) Z
   GROUP BY REGIMEN
   ORDER BY REGIMEN
   ----RADICACION POR REGIMEN
   INSERT INTO RPDX(CNS, STRINGMEDIO1, VALOR1, VALOR2, VALOR3 )
   SELECT @CNS_05, REGIMEN, SUM (VIGENCIA_ANTERIOR) VIGENCIA_ANTERIOR ,SUM (VIGENCIA_ACTUAL)VIGENCIA_ACTUAL , SUM (VIGENCIA_ANTERIOR) + SUM (VIGENCIA_ACTUAL)TOTAL
   FROM (
		   SELECT COALESCE (TGEN.DESCRIPCION,'SIN_CNF')+' '+CASE WHEN FTR.CAPITADA=1 THEN 'CAPITADA' ELSE 'EVENTO' END  REGIMEN, 
		          CASE WHEN YEAR (FTR.F_FACTURA)<YEAR  (GETDATE ()) THEN VALORFACTURA ELSE 0 END VIGENCIA_ANTERIOR, 
		          CASE WHEN YEAR (FTR.F_FACTURA)=YEAR  (GETDATE ()) THEN VALORFACTURA ELSE 0 END VIGENCIA_ACTUAL
		   FROM   FCXCD INNER JOIN FCXC ON FCXC.CNSCXC=FCXCD.CNSCXC
			  	          INNER JOIN FTR  ON FCXCD.N_FACTURA=FTR.N_FACTURA
				          INNER JOIN PLN  ON FTR.IDPLAN  = PLN.IDPLAN  
				           LEFT JOIN TGEN ON TGEN.CODIGO = PLN.REGIMEN2193 
                                     AND TGEN.CAMPO  = 'REGIMEN' 
                                     AND TGEN.TABLA  = '2193'
		   WHERE  COALESCE (INDRECIBIDO,0) = 1   
         AND    DBO.FNK_FECHA_SIN_HORA( F_RECIBIDO) BETWEEN @FECHAINICIAL AND @FECHAFINAL ) Z
   GROUP BY REGIMEN
   ORDER BY REGIMEN
   -- RECAUDOS PENDIENTES POR LEGALIZAR 
   SELECT IDTERCERO,SUM(VLRITEM-VLRLEGALIZADO) VLRITEM,0 MARCA INTO #TX
   FROM BMOVD INNER JOIN BMOV ON BMOVD.BANCO=BMOV.BANCO AND BMOVD.SUCURSAL=BMOV.SUCURSAL AND BMOVD.CTA_BCO=BMOV.CTA_BCO AND BMOVD.ITEM=BMOV.ITEM
   WHERE COALESCE(RECAUDO,0)=1 AND ENPAGOS=0 AND VLRLEGALIZADO=0
   AND  DBO.FNK_FECHA_SIN_HORA(BMOV.FECHAOPERACION) BETWEEN @FECHAINICIAL AND @FECHAFINAL
   GROUP BY BMOVD.IDTERCERO

	DECLARE PG_RPDXX CURSOR FOR  
   SELECT IDTERCERO,ITEM FROM RPDX WHERE CNS=@CNS_01 
   ORDER BY STRINGMEDIO1 ASC
	OPEN PG_RPDXX    
	FETCH NEXT FROM PG_RPDXX    
	INTO @IDTERCEROCUR,@ITEMCUR
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
      UPDATE RPDX SET VALOR9=COALESCE(VALOR9,0)+COALESCE(#TX.VLRITEM,0)
      FROM RPDX INNER JOIN #TX ON RPDX.IDTERCERO=#TX.IDTERCERO
      WHERE RPDX.CNS=@CNS_01 
      AND RPDX.ITEM=@ITEMCUR
      AND #TX.MARCA=0

      UPDATE #TX SET MARCA=1
      FROM RPDX INNER JOIN #TX ON RPDX.IDTERCERO=#TX.IDTERCERO
      WHERE RPDX.CNS=@CNS_01 
      AND RPDX.ITEM=@ITEMCUR
	FETCH NEXT FROM PG_RPDXX    
	INTO @IDTERCEROCUR,@ITEMCUR
	END
	CLOSE PG_RPDXX
	DEALLOCATE PG_RPDXX

   DROP TABLE #TX
END

