CREATE OR ALTER  PROCEDURE DBO.SPK_APLICA_CONCILIACION 
@IDFCONCI         VARCHAR(20),
@SEDE             VARCHAR(5),
@COMPANIA         VARCHAR(2),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)
WITH ENCRYPTION
AS
DECLARE @CNSCXC      VARCHAR (12),      @N_FACTURA   VARCHAR(20),    @IDTERCERO    VARCHAR(16),       @ITEMFCXCDV    INT
DECLARE @TIPO        VARCHAR(2),        @VLRACEPTADO DECIMAL(18,2),  @VLRRECUPERAR DECIMAL (18,2),    @CNSFNOT       VARCHAR (20)
DECLARE @CNSGLO      VARCHAR (12),      @OBSERVACION VARCHAR (4000), @IDNOTA       VARCHAR (5),       @CONCEPTO      VARCHAR (512)
DECLARE @ITEM        INT,               @F_RECIBIDO  DATETIME,       @F_VENCE      DATETIME,          @CNSRPDX       VARCHAR(20)
DECLARE @GNOT        SMALLINT,          @SALDONETO   DECIMAL (14,2), @ITEM_FCONCID INT,               @FECHACONCILIA DATETIME
DECLARE @CODCONCEPTO VARCHAR(20),       @FNOT_FECHACONCILIA VARCHAR(20)
DECLARE @PROCENCIA   VARCHAR(20),       @CERRAR      BIT=1
DECLARE @HOY         DATETIME=GETDATE()
BEGIN
   SELECT @PROCENCIA=PROCEDENCIA FROM FCONCI WHERE IDFCONCI = @IDFCONCI

   IF @PROCENCIA='RECLA'
   BEGIN
      EXEC SPK_NC_CONTAB_RECLASIFIACXC    @IDFCONCI, @SEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,''
      PRINT 'Contabilizando Conciliacion '  
      
      UPDATE FCONCI SET ESTADO='Cerrada' WHERE IDFCONCI=@IDFCONCI
   END  

   IF @PROCENCIA='CXC' OR @PROCENCIA='CONCILIACION'
   BEGIN
      SELECT @GNOT = 0
      SET @FNOT_FECHACONCILIA = DBO.FNK_VALORVARIABLE('FNOT_FECHACONCILIA')

      IF (SELECT COALESCE(DBO.FNK_VALORVARIABLE('IDCOPNOTACONCI'),''))=''
      BEGIN 
         PRINT 'SIN CONFIGURACION DE NOTA'
         RAISERROR ('NO EXISTE CONFIGURACION PARA GENERAR LA NOTA CREDITO ', 16, 1)
         RETURN
      END  
   
      IF (SELECT ESTADO FROM FCONCI WHERE IDFCONCI = @IDFCONCI) = 'Cerrada'
      BEGIN
         RAISERROR ('CONCILIACION YA CERRADA', 16, 1)
         RETURN
      END
      
      SELECT @IDTERCERO=IDTERCERO, @FECHACONCILIA=CASE WHEN @FNOT_FECHACONCILIA='CONCILIACION' THEN CONVERT(SMALLDATETIME,FCONCI.FECHACONC) ELSE CONVERT(SMALLDATETIME,GETDATE()) END
	  FROM FCONCI WHERE IDFCONCI=@IDFCONCI
	  
	  --ESTE SE OMITE PORQUE SE TOMA EL CONCEPTO DE CADA REGISTRO DE FONCID, FTRE EXIGE UNA DESCRIPCION Y ESTE QUEDABA NULL 20220106 
      SELECT @IDNOTA=DBO.FNK_VALORVARIABLE('IDCOPNOTACONCI')
      SELECT @CONCEPTO=DESCRIPCION FROM CPNT WHERE CODIGO=@IDNOTA
      --PROCESO DE NOTAS
   
	  IF (SELECT COUNT(*) FROM PRI WHERE FECHA_INI <= @FECHACONCILIA AND    FECHA_FIN >= @FECHACONCILIA) = 0
         BEGIN
            RAISERROR ('Periodo Contable NO Existe.', 16, 1)
            RETURN
         END

      IF (SELECT COALESCE(CERRADO,0) FROM PRI WHERE FECHA_INI <= @FECHACONCILIA AND    FECHA_FIN >= @FECHACONCILIA) = 1
         BEGIN
            RAISERROR ('Periodo Contable Cerrado.', 16, 1)
            RETURN
         END
      
      --DECLARE FCONCI_C CURSOR FOR 
      DECLARE @TABLA TABLE (ID INT IDENTITY(1,1), ITEM_FCONCID INT)
      DECLARE @I INT, @I_TO INT

      INSERT INTO @TABLA (ITEM_FCONCID)
      SELECT DISTINCT ITEM_FCONCID FROM FCONCID WHERE IDFCONCI=@IDFCONCI AND ESTADO='Ingresada'

      SELECT @I=1, @I_TO=COUNT(1) FROM @TABLA

      WHILE @I<=@I_TO
      BEGIN
         SELECT @ITEM_FCONCID=ITEM_FCONCID FROM @TABLA WHERE ID=@I

         SELECT @CNSCXC=CNSCXC,
            @N_FACTURA=N_FACTURA,
            @ITEMFCXCDV=ITEM_FCXCDV,
            @TIPO=TIPO,
            @VLRACEPTADO=VLRACEPTADO,
            @VLRRECUPERAR=VLRRECUPERAR,
            @CNSGLO=CNSGLO,
            @OBSERVACION=OBSERVACION,
            @SALDONETO=SALDONETO,
            @CODCONCEPTO=CONDCONCEPTO,
            @CNSFNOT=CNSFNOT
         FROM FCONCID 
         WHERE IDFCONCI=@IDFCONCI AND ITEM_FCONCID=@ITEM_FCONCID AND ESTADO<>'Cerrada'


         BEGIN TRY
            IF @VLRACEPTADO>0
            BEGIN 
               SELECT @GNOT = 1
               IF COALESCE(@CODCONCEPTO,'')=''
                  SET @CODCONCEPTO=@IDNOTA
               
               IF COALESCE(@CNSFNOT,'')=''
               BEGIN
                  EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FNOTC', @CNSFNOT OUTPUT  
                  SELECT @CNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@CNSFNOT))+LTRIM(RTRIM(@CNSFNOT)),SPACE(1),0)      
               END
               
               --SE INSERTAN LOS DATOS DE LA NOTA DESDE LA CONCILIACION
               PRINT 'NUMERO DE LA NOTA......'+ @CNSFNOT
               IF EXISTS (SELECT 1 FROM FNOT WHERE CNSFNOT=@CNSFNOT AND ESTADO='A')
               BEGIN
                  EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FNOTC', @CNSFNOT OUTPUT  
                  SELECT @CNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@CNSFNOT))+LTRIM(RTRIM(@CNSFNOT)),SPACE(1),0)      
               END

               IF NOT EXISTS(SELECT 1 FROM FNOT WHERE CNSFNOT=@CNSFNOT)
               BEGIN
				  
				      SELECT @CONCEPTO=DESCRIPCION FROM CPNT WHERE CODIGO=@CODCONCEPTO
				  
                  INSERT INTO FNOT(CNSFNOT, CLASE, N_FACTURA, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                                   MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA,
                                   USUARIO, CNSCXC, CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU,
                                   RAZONANU, PROCEDENCIA, CNSGLO, APLICADAA,LIBERAHADM, 
                                   CONCEPTO, IDCONCEPTO,VALORCONCEPTO,TIPOCONCEPTO,DETGENERADOS )  
                  SELECT @CNSFNOT, 'C', @N_FACTURA, @IDTERCERO, CASE WHEN @FNOT_FECHACONCILIA='CONCILIACION' THEN @FECHACONCILIA ELSE @HOY END, 
                         @VLRACEPTADO, @OBSERVACION, 0, 0, 0, NULL, 0, @COMPANIA, @USUARIO, @CNSCXC, 0, 'O', NULL, NULL, NULL, NULL,
                         'CONCILIA', @CNSGLO, 'C', 0, 1, ISNULL(@CODCONCEPTO,@IDNOTA),@VLRACEPTADO,'V',0
            
                  --INSERT INTO FNOTD(CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD,
                  --                  VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION)
                  --SELECT @CNSFNOT, 'C', 1, 'C',COALESCE(@CODCONCEPTO,@IDNOTA) , @CONCEPTO, 1,
                  --       @VLRACEPTADO, @VLRACEPTADO, @COMPANIA, @USUARIO, LEFT(@OBSERVACION,500)

                  EXEC SPK_GENITEMS_NOTACR @CNSFNOT,'C',@USUARIO,1
                  SET @CNSRPDX = 'INTERNO'
                  EXEC SPK_NOTASCXC @CNSFNOT, 'C', @CNSRPDX , @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME
                END
                UPDATE FCONCID SET CNSFNOT=@CNSFNOT, CLASE='C' WHERE IDFCONCI=@IDFCONCI AND ITEM_FCONCID=@ITEM_FCONCID
             END

            IF @VLRRECUPERAR>0 
            BEGIN
               UPDATE FCXCDV SET SALDONETO=0 WHERE ITEM=@ITEMFCXCDV
         
               SELECT @ITEM  = MAX(ITEM)
               FROM   FCXCDV 
               WHERE  CNSCXC    = @CNSCXC
               AND    N_FACTURA = @N_FACTURA
         
               SELECT @F_RECIBIDO=F_RECIBIDO, @F_VENCE=F_VENCE FROM FCXCDV WHERE ITEM=@ITEMFCXCDV
         
               IF EXISTS (SELECT 1 FROM FCXCDV WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA AND TIPO='C')
               BEGIN
			      UPDATE FCXCDV 
				  SET IDFCONCI=@IDFCONCI, 
				      SALDOINICIAL=CASE WHEN @TIPO='C' THEN @VLRRECUPERAR ELSE SALDOINICIAL+@VLRRECUPERAR END,
					  SALDONETO=CASE WHEN @TIPO='C' THEN @VLRRECUPERAR ELSE SALDONETO+@VLRRECUPERAR END,
					  CNSGLO=NULL 
				  WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA AND TIPO='C' 
				  AND NOT EXISTS (SELECT * FROM FCONCID WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA AND TIPO=@TIPO AND ESTADO='Cerrada')
               END
               ELSE
               BEGIN
                  INSERT INTO FCXCDV(CNSCXC, N_FACTURA, CNSGLO, TIPO, SALDONETO, FECHA, 
                                     F_RECIBIDO, F_VENCE, SALDOINICIAL,MARCAPAGO,IDFCONCI) 
                  SELECT @CNSCXC, @N_FACTURA, @CNSGLO, 'C', @VLRRECUPERAR, @HOY, @F_RECIBIDO, @F_VENCE,
                         @VLRRECUPERAR, 0,@IDFCONCI
               END
            END

            UPDATE FCONCID SET ESTADO='Cerrada' 
            WHERE IDFCONCI=@IDFCONCI AND ITEM_FCONCID=@ITEM_FCONCID
			   EXEC SPK_RELIQUIDA_FTR @CNSCXC, @N_FACTURA
            
         END TRY
         BEGIN CATCH
            PRINT 'Error al generar nota, posiblemente por truncamiento'
            PRINT ERROR_MESSAGE()
            SET @CERRAR=0
         END CATCH

         SET @GNOT=0
         SET @I+=1
      END

      PRINT 'Contabilizando Conciliacion '
      IF @CERRAR=1
	   BEGIN
         IF(SELECT COUNT(1) FROM FCONCID WHERE IDFCONCI=@IDFCONCI AND VLRRECUPERAR>0 AND EXISTS(SELECT 1 FROM FTR WHERE COALESCE(CASTIGADA,0)=0 AND FCONCID.N_fACTURA=FTR.N_FACTURA))>0
         BEGIN
		      EXEC DBO.SPK_CONTAB_CONCI @IDFCONCI, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @SEDE, ''
	      END
         IF(SELECT COUNT(*) FROM FCONCID WHERE  IDFCONCI=@IDFCONCI AND ESTADO<>'Cerrada')<=0
         BEGIN
            UPDATE FCONCI SET ESTADO='Cerrada' WHERE IDFCONCI=@IDFCONCI
         END
      END
   END 
END

