IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_ADMIN_PAGOS' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_ADMIN_PAGOS
END

GO
CREATE  PROCEDURE DBO.SPK_ADMIN_PAGOS
@PROCEDENCIA      VARCHAR(10), 
@N_FACTURA        VARCHAR(20),
@CNS              VARCHAR(20), 
@CNSPAGO          VARCHAR(20),
@TAREA            VARCHAR(6), 
@VALOR            DECIMAL(14,2),
@IDTERCERO        VARCHAR(20),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(255),
@COMPANIA         VARCHAR(2),
@IDSEDE           VARCHAR(5),
@OBSERVACION      VARCHAR(255),
@PROCEDENCIA2     VARCHAR(10),
@ESTADO           VARCHAR(1), --C = Confirmado, P = Pagado
@CNSFCXPPM        VARCHAR(20),
@FECHAPAGO        DATETIME,
@CODCAJA          VARCHAR(4),
@CNSFACJ          VARCHAR(20),
@CUENTA           VARCHAR(16),
@CLASE            VARCHAR(1),
@CNSGLO           VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @VALORPAGO      DECIMAL(14,2)
DECLARE @VALOR_FACTURA  DECIMAL(14,2)
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @TIPOTTEC       VARCHAR(10) 
DECLARE @CNSCXC         VARCHAR(20)
BEGIN
   IF @PROCEDENCIA='CXP'
   BEGIN
      -- Posibles Estados en FCXP (CXP)
      -- 'N' Sin Ordenes de Pago
      -- 'C' Con Ordenes de Pago
      -- 'P' Pagado
      -- 'A' Anulado
      -- 'M' Elegido para Pagar (Pagos Masivos)
  
      -- Posibles Estados en FCXPP (Pagos en CXP)
      -- 'N' No Confirmado
      -- 'C' Confirmado
      -- 'P' Pagado
      -- 'A' Anulado
      IF @TAREA='INSERT'
      BEGIN
         PRINT 'Insertando Pago en FCXPP'
         INSERT INTO FCXPP (CNSFCXPP,CNSFCXP,FECHA,OBSERVACION,SALDOANTERIOR,ABONO,SALDONUEVO,FECHAPPAGO,
                           VALORPPAGO,USUARIO,USUARIOCONF,FECHACONF,SYS_COMPUTERNAME,CODCAJA,CNSFACJ,ESTADO,
                           IDTERCERO,N_RECIBO,IDCLASEIMP,VLR_IMPUESTOS,VLR_NETO,PROCEDENCIA,CNSFCXPPM)
         SELECT @CNSPAGO,@CNS,DBO.FNK_FECHA_SIN_HORA(@FECHAPAGO) AS FECHA,
               @OBSERVACION AS OBSERVACION,
               ROUND(DBO.FNK_SALDO_CUENTA('CXP',@CNS,@N_FACTURA,@CNSPAGO),2) AS SALDOANTERIOR,
               ROUND(@VALOR,2) AS ABONO,
               ROUND(DBO.FNK_SALDO_CUENTA('CXP',@CNS,@N_FACTURA,@CNSPAGO) - @VALOR,2) AS SALDONUEVO,
               '' AS FECHAPPAGO,0 AS VALORPPAGO,@USUARIO AS USUARIO,@USUARIO AS USUARIOCONF,
               DBO.FNK_FECHA_SIN_MLS(GETDATE()) AS FECHACONF, @SYS_COMPUTERNAME AS SYS_COMPUTERNAME,
               @CODCAJA AS CODCAJA, @CNSFACJ AS CNSFACJ, @ESTADO AS ESTADO, @IDTERCERO AS IDTERCERO,'' AS N_RECIBO,
               '' AS IDCLASEIMP,0 AS VLR_IMPUESTOS,ROUND(@VALOR,2) AS VLR_NETO, @PROCEDENCIA2 AS PROCEDENCIA,
               @CNSFCXPPM AS CNSFCXPPM
     
         UPDATE FCXP SET SALDO=SALDO-(CASE WHEN @ESTADO='P' THEN ROUND(@VALOR,2) ELSE 0 END),
                        ESTADO=(CASE WHEN SALDO-(CASE WHEN @ESTADO='P' THEN @VALOR ELSE 0 END)=0 THEN 'P' ELSE (CASE WHEN (SELECT SUM(FCXPP.ABONO) 
                                             FROM FCXPP 
                                             WHERE FCXPP.CNSFCXP=FCXP.CNSFCXP AND FCXPP.ESTADO<>'A' AND 
                                                   FCXPP.ABONO>0)>0 THEN 'C' ELSE 'N' END) END)
         WHERE CNSFCXP=@CNS

         EXEC SPK_CALCULOVALORESCXP @CNS
         
      END
      ELSE
      IF @TAREA='CHANGE'
      BEGIN 
         UPDATE FCXP SET SALDO=SALDO+(CASE WHEN @ESTADO='P' THEN ROUND((SELECT ABONO FROM FCXPP WHERE CNSFCXPP=@CNSPAGO),2) ELSE 0 END)
         WHERE CNSFCXP=@CNS
         
         UPDATE FCXPP SET
         ABONO              = ROUND(@VALOR,2),
         SALDOANTERIOR      = ROUND(DBO.FNK_SALDO_CUENTA('CXP',@CNS,@N_FACTURA,@CNSPAGO),2),
         SALDONUEVO         = ROUND(DBO.FNK_SALDO_CUENTA('CXP',@CNS,@N_FACTURA,@CNSPAGO) - @VALOR,2),
         FECHA              = DBO.FNK_FECHA_SIN_HORA(@FECHAPAGO),
         USUARIO            = @USUARIO,
         USUARIOCONF        = @USUARIO,
         FECHACONF          = DBO.FNK_FECHA_SIN_MLS(GETDATE()),
         SYS_COMPUTERNAME   = @SYS_COMPUTERNAME,
         VLR_NETO           = ROUND(@VALOR,2)
         WHERE CNSFCXPP=@CNSPAGO

         UPDATE FCXP SET SALDO=SALDO-(CASE WHEN @ESTADO='P' THEN ROUND(@VALOR,2) ELSE 0 END),
                        ESTADO=(CASE WHEN SALDO-(CASE WHEN @ESTADO='P' THEN ROUND(@VALOR,2) ELSE 0 END)=0 THEN 'P' 
                                    ELSE (CASE WHEN (SELECT SUM(FCXPP.ABONO) 
                                                      FROM FCXPP 
                                                      WHERE FCXPP.CNSFCXP=FCXP.CNSFCXP AND 
                                                            FCXPP.ESTADO<>'A' AND 
                                                            FCXPP.ABONO>0)>0 
                                                THEN 'C' 
                                                ELSE 'N' 
                                          END) 
                              END)
         WHERE CNSFCXP=@CNS
         EXEC SPK_CALCULOVALORESCXP @CNS
      END
      ELSE
      IF @TAREA='DELETE'
      BEGIN
         UPDATE FCXP SET SALDO=SALDO+(CASE WHEN @ESTADO='P' THEN ROUND((SELECT ABONO FROM FCXPP WHERE CNSFCXPP=@CNSPAGO),2) ELSE 0 END),
                           ESTADO=(CASE WHEN (SELECT SUM(FCXPP.ABONO) 
                                          FROM FCXPP 
                                          WHERE FCXPP.CNSFCXP=FCXP.CNSFCXP AND FCXPP.ESTADO<>'A' AND 
                                                FCXPP.ABONO>0)>0 THEN 'C' ELSE 'N' END)
         WHERE CNSFCXP=@CNS


         UPDATE FCXPP SET ESTADO='A',USUARIOCONF=@USUARIO,FECHACONF=GETDATE() WHERE CNSFCXPP=@CNSPAGO

         EXEC SPK_CALCULOVALORESCXP @CNS
      END
   END
   ELSE
   IF @PROCEDENCIA='CXC'
   BEGIN
      SELECT @TIPOTTEC = (SELECT TOP 1 TIPO FROM TTEC WHERE CUENTA=@CUENTA),
             @VALOR_FACTURA=(SELECT VR_TOTAL FROM FTR WHERE N_FACTURA=@N_FACTURA)
      IF @TAREA='INSERT'
      BEGIN 
         SELECT  @NROCOMPROBANTE=NROCOMPROBANTE FROM FCJ WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ

         UPDATE FCXC SET CONTABILIZADA=1,NROCOMPROBANTE=@NROCOMPROBANTE WHERE CNSCXC=@CNSCXC

         INSERT INTO FPAG (CNSFPAG,FECHAPAGO,IDTERCERO,IDMENSAJERO,FORMAPAGO,BANCO,NUMERODOCUMENTO,
                           NUMEROAUTORIZA,VALORPAGO,CERRADO,USUARIO,COMPANIA,VLRITEMS,VLRIMPUESTOS,
                           VLRAJUSTEPESO,AJUSTADAPESO,VLRGLOSAS,VLRTOTAL,VLRDTOFINAN,DTOFNCIERO,CNSFACJ,
                           CODCAJA,CONTABILIZADO,INGRESO,SUCURSAL,CTA_BCO,ITEM,RENGLON,FECHA,ESTADO,IDSEDE,
                           NOCONTABILIZA,NROCOMPROBANTE)
         SELECT @CNSPAGO AS CNSFPAG,DBO.FNK_FECHA_SIN_HORA(@FECHAPAGO) AS FECHAPAGO,@IDTERCERO AS IDTERCERO,
               @USUARIO AS IDMENSAJERO, DBO.FNK_VALORVARIABLE('IDCJCRUCECUENTAS') AS FORMAPAGO,'' AS BANCO,
               '' AS NUMERODOCUMENTO,'' AS NUMEROAUTORIZA,ROUND(@VALOR,2) AS VALORPAGO,0 AS CERRADO,
               @USUARIO AS USUARIO,@COMPANIA AS COMPANIA,ROUND(@VALOR_FACTURA,2) AS VLRITEMS,0 AS VALORIMPUESTOS,
               0 AS VALORAJUSTEPESO, 0 AS AJUSTADAPESO, 0 AS VLRGLOSAS,ROUND(@VALOR,2) AS VLRTOTAL,
               0 AS VLRDTOFINAN, 0 AS DTOFNCIERO,@CNSFACJ AS CNSFACJ,@CODCAJA AS CODCAJA,1 AS CONTABILIZADO,
               @PROCEDENCIA2 AS INGRESO, '' AS SUCURSAL,'' AS CTA_BCO,'' AS ITEM,'' AS RENGLON,DBO.FNK_FECHA_SIN_HORA(@FECHAPAGO),'Activo',@IDSEDE
               ,1,@NROCOMPROBANTE
                                                                                                                                                  
         INSERT INTO FPAGD (CNSFPAG,ITEM,CNSCXC,N_FACTURA,VALORPAGO,CERRADO,USUARIO,COMPANIA,VLRIMPUESTO,
                           PAGOTOTAL,VLRAJUSTEPESO,VLRFACTURA,VLRFACTURANDNC,CLASEPAG,TIPOGLOSA,VLRDTOFIN,
                           VLRGLOSA,GLOSAAFECTAIMP,VLRPAGOSIN,VLRCOPAGO,BASE,CNSRPDX,SINPAGO,CNSGLO,CLASE,
                           VLREXTRA,VLRIMPGLOBAL,TIPOTTEC)
         SELECT @CNSPAGO AS CNSFPAG,1 AS ITEM,@CNS AS CNSCXC,@N_FACTURA AS N_FACTURA,ROUND(@VALOR,2) AS VALORPAGO,
               0 AS CERRADO,@USUARIO AS USUARIO,@COMPANIA AS COMPANIA,0 AS VALORIMPUESTOS,1 AS PAGOTOTAL,
               0 AS VALORAJUSTEPESO,   
               ROUND(@VALOR,2) AS VLRFACTURA, 
               0 AS VLRFACTURANDNC,'P' AS CLASEPAG,'P' AS TIPOGLOSA,0 AS VLRDTOFIN, 0 AS VLRGLOSA,0 AS GLOSAAFECTAIMP,
               ROUND(@VALOR,2) AS VLRPAGOSIN,0 AS VLRCOPAGO,ROUND(@VALOR,2) AS BASE,'' AS CNSRPDX,0 AS SINPAGO,@CNSGLO, @CLASE,
               0 AS VLREXTRA,0 AS VLRIMPGLOBAL,@TIPOTTEC AS TIPOTTEC 
               
         IF @ESTADO='P'
            EXEC SPK_PAGOSCXC @CNSPAGO,@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME

         SET @VALORPAGO=(SELECT SUM(VALORPAGO) FROM FPAGD WHERE CNSFPAG=@CNSPAGO AND CERRADO=1) 
       
         UPDATE FPAG SET
            VALORPAGO     = ROUND(@VALORPAGO,2),
            VLRITEMS      = ROUND(@VALORPAGO,2),
            VLRTOTAL      = ROUND(@VALORPAGO,2)
         WHERE CNSFPAG=@CNSPAGO
      END 
      ELSE
      BEGIN
         IF @TAREA='CHANGE'
         BEGIN 
            IF @ESTADO='P'
               EXEC SPK_DESPAGOSCXC @CNSPAGo,@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,'DESAPLICAR'
       
            UPDATE FPAGD SET
               VALORPAGO     = ROUND(@VALOR,2),
               USUARIO       = @USUARIO,
               PAGOTOTAL     = 1,
               VLRFACTURA    = ROUND(@VALOR,2)/*ROUND(@VALOR_FACTURA,0)*/, 
               VLRPAGOSIN    = ROUND(@VALOR,2),
               BASE          = ROUND(@VALOR,2)
            WHERE CNSFPAG=@CNSPAGO AND N_FACTURA=@N_FACTURA
       
            SET @VALORPAGO=(SELECT SUM(VALORPAGO) FROM FPAGD WHERE CNSFPAG=@CNSPAGO AND CERRADO=1) 
       
            UPDATE FPAG SET
                  FECHAPAGO     = DBO.FNK_FECHA_SIN_HORA(@FECHAPAGO),
                  IDMENSAJERO   = @USUARIO, 
                  FORMAPAGO     = DBO.FNK_VALORVARIABLE('IDCJCRUCECUENTAS'),
                  VALORPAGO     = ROUND(@VALORPAGO,2),
                  USUARIO       = @USUARIO,
                  VLRITEMS      = ROUND(@VALOR_FACTURA,2),
                  VLRTOTAL      = ROUND(@VALORPAGO,2)
            WHERE CNSFPAG=@CNSPAGO
            IF @ESTADO='P'
               EXEC SPK_PAGOSCXC @CNSPAGo,@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME
            
            SELECT @NROCOMPROBANTE=NROCOMPROBANTE FROM FPAG WHERE CNSFPAG=@CNSPAGO
            --   EXEC SPK_CONTAB_CXC @CNSPAGO,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,
            --   @IDSEDE,@NROCOMPROBANTE,@FECHAPAGO
         END
         ELSE
         BEGIN
            IF @TAREA='DELETE'
            BEGIN
               IF @ESTADO='P'
               BEGIN
                  EXEC SPK_DESPAGOSCXC @CNSPAGO,@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,'DESAPLICAR'
               END
      
               DELETE FROM FPAGDI WHERE CNSFPAG=@CNSPAGO AND N_FACTURA=@N_FACTURA
               DELETE FROM FPAGD  WHERE CNSFPAG=@CNSPAGO AND N_FACTURA=@N_FACTURA
			      --SE AGREGA POR LLAVE FORANEA PRIMERO SE BORRA ESTE PARA BORRAR FPAG 
			      DELETE FROM FCJPCXC  WHERE CNSFPAG=@CNSPAGO AND N_FACTURA=@N_FACTURA
               DELETE FROM FPAG   WHERE CNSFPAG=@CNSPAGO
      
               SELECT @NROCOMPROBANTE=NROCOMPROBANTE FROM FPAG WHERE CNSFPAG=@CNSPAGO
               
               UPDATE MCP SET ESTADO=0,ANULADO=1,OBSERVACION='A N U L A D O' WHERE NROCOMPROBANTE=@NROCOMPROBANTE 
               DELETE MCH WHERE NROCOMPROBANTE=@NROCOMPROBANTE 
            END
         END
      END
   END
END

