CREATE OR ALTER PROCEDURE DBO.SPK_FACTURACE_CITAUT_COL
@NOAUT			VARCHAR(16),
@NIT			VARCHAR(20),
@COMPANIA		VARCHAR(2),
@IDSEDE			VARCHAR(5),
@USUARIO		VARCHAR(12),
@PRE1			VARCHAR(6),
@PRE2			VARCHAR(6),
@PRE3			VARCHAR(6),
@PRE4			VARCHAR(6),
@PRE5			VARCHAR(6),
@PROC			VARCHAR(2),
@IDTERCEROCA1	VARCHAR(20),
@CETIPOHOSP		VARCHAR(6) = FALSE,  -- PARAM. Que Especifica el tipo de manejo de Planes - Contratos 
@IDPLANPAR		VARCHAR(6) = NULL,    -- EL PLAN EN CEHOSP
@FECHAFAC		DATETIME   = NULL,
@TIPOFAC		VARCHAR(10)='Factura',
@IDTERCERO_RUC	VARCHAR(20) = NULL
WITH ENCRYPTION
AS 
DECLARE @IDAUT       VARCHAR(13), @PRE VARCHAR(20), @CONSECFTR INT, @CNSRESOL VARCHAR(50)
DECLARE @NVOCONSEC   VARCHAR(20)
DECLARE @CNSFTR      VARCHAR(20)
DECLARE @CERRADA     SMALLINT
DECLARE @FACTURADA   SMALLINT
DECLARE @FACTURABLE  SMALLINT
DECLARE @TIPOADM     VARCHAR(2)
DECLARE @IDTERCERO   VARCHAR(20)
DECLARE @IDPLAN      VARCHAR(6)
DECLARE @MONEDA      VARCHAR(20)
DECLARE @DATO1       VARCHAR(80)
DECLARE @IDTERCERO1  VARCHAR(20)  
DECLARE @OK          INT
DECLARE @CA          VARCHAR(15)
DECLARE @IDAFILIADO  VARCHAR(20)
DECLARE @IDAFILIADOTER VARCHAR(20)
DECLARE @DV          SMALLINT
DECLARE @TV          VARCHAR(10)
DECLARE @CCOSTO      VARCHAR(20)
DECLARE @IDAREA      VARCHAR(20)
DECLARE @EC          SMALLINT
DECLARE @IDTERCEROF  VARCHAR(20)
DECLARE @IDTERPART   VARCHAR(20)
DECLARE @DESCUENTO   DECIMAL(14,2)
DECLARE @TIPODTO     VARCHAR(1)
DECLARE @VRTOTAL     DECIMAL(14,2)
DECLARE @VRSERV      DECIMAL(14,2)
DECLARE @VRCOPA      DECIMAL(14,2)
DECLARE @VRPACO      DECIMAL(14,2)
DECLARE @VRDTO       DECIMAL(14,2)
DECLARE @VRABONO     DECIMAL(14,2)
DECLARE @VEZ         INT
DECLARE @DATO3             VARCHAR(20)
DECLARE @TTEC              VARCHAR(10)
DECLARE @TIPOFACTURACION   VARCHAR(1)
DECLARE @NODESCUENTACOPAGO SMALLINT
DECLARE @CUENTACXC         VARCHAR(16)
DECLARE @DATOCCOSTO        VARCHAR(80)
DECLARE @SOAT              SMALLINT
DECLARE @CNSHACTRAN        VARCHAR(20)
DECLARE @IDTERCEROCA       VARCHAR(20)
DECLARE @SANDER            DECIMAL (14,2) 
DECLARE @SYS_COMPUTERNAME  VARCHAR(254)
DECLARE @CODUNG VARCHAR(2)
DECLARE @CODPRG VARCHAR(2)
DECLARE @CUENTACXC_RAD     VARCHAR(16)
DECLARE @LIBERADA          SMALLINT
DECLARE @VENCIDA           SMALLINT
DECLARE @IDAFIAUX          VARCHAR(20)
DECLARE @IDCATEGORIA       VARCHAR(10)--CAT
DECLARE @IDFORMATOFTR      VARCHAR(20)
DECLARE @MIVA              SMALLINT
DECLARE @PIVA              DECIMAL(14,2)
DECLARE @VIVA              DECIMAL(14,2)
DECLARE @N_FACTURAORI      VARCHAR(20)
DECLARE @VLRAUTDTOTAL      DECIMAL(14,2)
DECLARE @VARIOS            INT
DECLARE @BASE_IVA_SER      VARCHAR(20)
DECLARE @LIBERTER		   VARCHAR(20)
DECLARE @ESOPTICA		   VARCHAR(2)
DECLARE @OBSERVACION	   VARCHAR(2040)
DECLARE @MONTO             DECIMAL(14,2)
DECLARE @ESPARTPERU   BIT
DECLARE @PREFIJOFAC VARCHAR(20)
BEGIN
	SELECT  @SYS_COMPUTERNAME = HOST_NAME(),@LIBERADA=0
	-- SACAR DE DONDE SE TOMA EL CCOSTO
	IF @EC IS NULL
			SELECT @EC = 0
         
	SELECT @DATOCCOSTO = DATO FROM USVGS WHERE IDVARIABLE = 'CCOSTOENPRESTACION'
	SELECT @MONEDA = DATO FROM USVGS WHERE IDVARIABLE = 'IDMONEDABASE'
	--SELECT @BASE_IVA_SER = DATO FROM USVGS WHERE IDVARIABLE='BASE_IVA_SERVICIOS'
	SELECT @LIBERTER=DATO FROM USVGS WHERE IDVARIABLE='LIBERTER'
	SELECT @ESOPTICA=DATO FROM USVGS WHERE IDVARIABLE='IPS_MAN_OPTICA'
	PRINT 'INGRESE' 

	IF COALESCE(@LIBERTER,'')<>'SI'
	BEGIN 
		IF EXISTS(SELECT * FROM FTR WHERE NOREFERENCIA=@NOAUT AND PROCEDENCIA='CI' AND ESTADO='L' AND TIPOFIN='C')
		BEGIN
			PRINT 'SI TENGO LIBREACION'
			SELECT @LIBERADA=1,@NVOCONSEC=N_FACTURA , @CNSFTR=CNSFCT 
         FROM FTR WHERE NOREFERENCIA=@NOAUT 
         AND PROCEDENCIA='CI' AND ESTADO='L' AND TIPOFIN='C'
		END
		SELECT  @FACTURADA = FACTURADA,  @FACTURABLE = FACTURABLE,
				@IDTERCERO = IDTERCEROCA,  @IDPLAN = CIT.IDPLAN,
				@IDAFILIADO = CIT.IDAFILIADO, @DESCUENTO = DESCUENTO, @TIPODTO = TIPODTO, 
				@CCOSTO=CCOSTO, @IDTERCERO1 =IDTERCEROCA, @SOAT = SOAT,
				@CNSHACTRAN = CNSHACTRAN 
		FROM    CIT INNER JOIN AFI ON AFI.IDAFILIADO=CIT.IDAFILIADO WHERE CONSECUTIVO = @NOAUT 
		print 'terceroca' + @IDTERCERO 
		PRINT  'facturada='+STR(@FACTURADA)+' - '+@NOAUT
	END 
	ELSE 
	BEGIN
		IF EXISTS(SELECT * FROM FTR WHERE IDTERCERO=@IDTERCEROCA1 AND ESTADO='L' AND TIPOFIN='C' AND F_FACTURA>GETDATE()-2)
		BEGIN
	   		PRINT 'SI TENGO LIBREACION POR TERCERO'
				
			SELECT TOP 1  @LIBERADA=1,@NVOCONSEC=N_FACTURA , @CNSFTR=CNSFCT FROM FTR WHERE IDTERCERO=@IDTERCEROCA1 
			AND ESTADO='L' AND TIPOFIN='C' AND F_FACTURA>GETDATE()-2
		END 
		IF @PROC='CI'
		BEGIN
			SELECT  @FACTURADA =CASE WHEN FACTURADA=1 AND COALESCE(N_FACTURA,'')='' THEN 0 ELSE FACTURADA END,  @FACTURABLE = FACTURABLE,
				@IDTERCERO = IDTERCEROCA,  @IDPLAN = CIT.IDPLAN,
				@IDAFILIADO = CIT.IDAFILIADO, @DESCUENTO = DESCUENTO, @TIPODTO = TIPODTO, 
				@CCOSTO=CCOSTO, @IDTERCERO1 =IDTERCEROCA, @SOAT = SOAT,
				@CNSHACTRAN = CNSHACTRAN 
			FROM    CIT INNER JOIN AFI ON AFI.IDAFILIADO=CIT.IDAFILIADO WHERE CONSECUTIVO = @NOAUT 
			print 'terceroca' + @IDTERCERO 
			PRINT   'facturada='+STR(@FACTURADA)+' - '+@NOAUT
		END 
	END 
	

	SELECT @DATO3 = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'     
	IF @FACTURADA = 1
	BEGIN
		PRINT 'ME DEVUELVO POR QUE YA ESTA FACTURADA'
		RETURN 
	END 
	PRINT 'No esta Facturada'
	IF @FACTURABLE = 0
	BEGIN
		PRINT 'ME DEVUELVO NO ES FACTURABLE'
		RETURN
	END
   IF COALESCE(@IDTERCERO_RUC,'')=''
   BEGIN
      SELECT @IDTERCERO_RUC=@IDTERCERO,@IDTERCEROCA=@IDTERCERO

   END
	CREATE TABLE #FTRD1(CNSFTR VARCHAR(40), N_CUOTA	int IDENTITY, FECHA datetime,
				DB_CR varchar(2), AREAPRESTACION varchar(20), UBICACION varchar(16),
				VR_TOTAL float, IMPUTACION varchar(16), CCOSTO varchar (20),
				PREFIJO varchar(6), ANEXO varchar(1024), REFERENCIA varchar(40), 
				IDCIRUGIA varchar(20), CANTIDAD smallint, VALOR decimal(14,2),
				VLR_SERVICI decimal(14,2), VLR_COPAGOS decimal(14,2),
				VLR_PAGCOMP decimal(14,2), IDPROVEEDOR varchar(20),
				NOADMISION varchar(16), NOPRESTACION	varchar(16), NOITEM int,	
				AREAFUNCONT varchar(20), N_FACTURA varchar(16),
				SUBCCOSTO varchar(4), PCOSTO	decimal(14,2), FECHAPREST datetime, IDPLAN VARCHAR(6),
				IDIMPUESTO VARCHAR(10),
				IDCLASE    VARCHAR(10),
				ITEM       SMALLINT,
				VLRIMPUESTO DECIMAL(14,2),
				PIVA        DECIMAL(14,2),
				VIVA        DECIMAL(14,2),
				CUENTA_FIMPDV VARCHAR(20),
            PROCEDENCIA VARCHAR(10),
            TCOPAGO VARCHAR(10)
				) --FTRD

   IF @PROC = 'CI' 
   BEGIN
	   UPDATE CIT SET CANTIDADC=1 WHERE CONSECUTIVO=@NOAUT AND COALESCE(CANTIDADC,0)=0     
   END 
	PRINT 'INGRESE EL CURSOR PARA FACTURAR.................'
	PRINT '@IDTERCEROCA='+COALESCE(@IDTERCEROCA,'NO TENGO TERCERO')
	PRINT '@IDPLAN='+@IDPLAN

	PRINT @NOAUT + ' ' +CASE WHEN @IDTERCEROCA IS NULL THEN '?' ELSE @IDTERCEROCA END
	PRINT @PROC
	PRINT @NODESCUENTACOPAGO
	PRINT @DATOCCOSTO


   PRINT 'ES DE CITAS'
   DECLARE @MENOSVIVA DECIMAL(14,2)
   SELECT @MENOSVIVA=VALORCOPAGO- CASE WHEN COALESCE(SER.IVA,'')='SER' THEN (SELECT VALORCOPAGO -ROUND(VALORCOPAGO/((VALOR+100)/100),4) 
															   FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),VALORCOPAGO))
                                                ELSE 0 END 
   FROM CIT INNER JOIN SER ON CIT.IDSERVICIO=SER.IDSERVICIO
   WHERE CONSECUTIVO=@NOAUT

   PRINT '@MENOSVIVA='+CAST(@MENOSVIVA AS VARCHAR(20))

   INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
		   IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
		   VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
		   NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, IDPLAN,IDIMPUESTO, IDCLASE,ITEM ,
         VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV,PROCEDENCIA,TCOPAGO)
	SELECT @CNSFTR, GETDATE(), 'DB', CIT.IDAREA, NULL,VALORTOTAL, 
				NULL, CIT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, CIT.IDSERVICIO, NULL, COALESCE(CIT.CANTIDADC,1) CANTIDAD,
         VALORTOTAL, CIT.VALORTOTAL, COALESCE(VALORCOPAGO,0), 0,CIT.IDMEDICO, @NOAUT, @NOAUT, 1, NULL, @NVOCONSEC, CIT.SUBCCOSTO,
            CIT.VALORTOTALCOS, CIT.FECHA, CIT.IDPLAN,
				CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END,
				CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
				CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(), CIT.VALORTOTAL)) ELSE NULL END,				 
            CIT.VALORTOTAL,CASE WHEN COALESCE(SER.IVA,'')='SER' THEN 
            (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(), VALORTOTAL)) ELSE NULL END,
				CASE WHEN COALESCE(SER.IVA,'')='SER' THEN (CIT.VALORTOTAL-CIT.VALORCOPAGO) - ((CIT.VALORTOTAL-CIT.VALORCOPAGO)/1.18)  ELSE NULL END,
				CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),CIT.VALORTOTAL))  
            ELSE NULL END,'CI',DBO.FNK_TRAE_TIPOCOPAGO(CIT.CONSECUTIVO,'CI')
	FROM   CIT INNER JOIN SER ON SER.IDSERVICIO = CIT.IDSERVICIO 
				LEFT JOIN TER ON TER.IDTERCERO = CIT.IDTERCEROCA
	WHERE  CIT.CONSECUTIVO   = @NOAUT              
   AND    COALESCE(FACTURADA,0)=0
   AND  1=0
   --AND    COALESCE(VALORTOTAL,0)>0
   PRINT 'AGREGO SERVICIOS DE AUT'

   INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
		   IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
		   VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
		   NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, IDPLAN,IDIMPUESTO, IDCLASE,ITEM ,
         VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV,PROCEDENCIA,TCOPAGO)
 	SELECT @CNSFTR, GETDATE(), 'DB', AUT.IDAREA, NULL, 
			(AUTD.VALOR*AUTD.CANTIDAD), 
			NULL, CASE WHEN @DATOCCOSTO = 'SER:CCOSTO' THEN AUTD.CCOSTO ELSE AUT.CCOSTO END, SER.PREFIJO,
			CASE WHEN dbo.FNK_VALORVARIABLE('MANEJA_GARANTIA_SER') = 'SI' THEN 
				CASE WHEN dbo.FNK_VALORVARIABLE('CLASE_IPS') = 'OPTICA' THEN  CASE WHEN COALESCE(SER.GARANTIA, 0) = 0 THEN COALESCE(SER.DESCSERVICIO, '')+' '+'Producto sin Garantia'
																													ELSE COALESCE(SER.DESCSERVICIO, '')+' '+COALESCE(SER.COMENTARIOS, '')
																													END
																			ELSE SER.DESCSERVICIO
																			END
																	ELSE SER.DESCSERVICIO
																	END,
			AUTD.IDSERVICIO, NULL, AUTD.CANTIDAD,AUTD.VALOR,(AUTD.VALOR*AUTD.CANTIDAD), 
			AUTD.VALORCOPAGO,0, AUT.IDPROVEEDOR, @NOAUT, AUTD.IDAUT, AUTD.NO_ITEM, NULL, 
			@NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO,AUT.FECHA, AUT.IDPLAN,
		CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END,
		CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
		CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),AUTD.VALOREXCEDENTE)) ELSE NULL END,
		CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  ((AUTD.VALOR*AUTD.CANTIDAD)-AUTD.VALORCOPAGO)  ELSE NULL END ,
		CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),AUTD.VALOREXCEDENTE)) ELSE NULL END,
		CASE WHEN COALESCE(SER.IVA,'')='SER' THEN (SELECT ROUND((((AUTD.VALOR*AUTD.CANTIDAD)-AUTD.VALORCOPAGO)*(VALOR/100))/AUTD.CANTIDAD,2) FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),AUTD.VALOREXCEDENTE)) ELSE NULL END,
		CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),AUTD.VALOREXCEDENTE))  ELSE NULL END,'CE',
      DBO.FNK_TRAE_TIPOCOPAGO(AUT.NOAUT,'CE')
	FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT     = AUT.IDAUT 
				  INNER JOIN SER  ON SER.IDSERVICIO = AUTD.IDSERVICIO 
				  LEFT JOIN TER  ON TER.IDTERCERO  = AUTD.IDTERCEROCA
	WHERE ( AUT.CONSECUTIVOCIT = @NOAUT   OR IDAFILIADO=@IDAFILIADO)
	AND AUTD.IDPLAN=@IDPLAN
   AND COALESCE(AUTD.NOCOBRABLE,0)=0
   AND COALESCE(AUTD.FACTURADA,0)=0
   AND COALESCE(AUT.MARCAFAC,0)=1
   AND COALESCE(AUT.CNSFACT,'')=@USUARIO



      
   PRINT 'AJUSTO VALOR COPAGO SI TIENE IVA'
   UPDATE #FTRD1 SET VALOR=VALOR/(1+(PIVA/100))--,VLR_COPAGOS=CASE WHEN COALESCE(VLR_COPAGOS,0)>0 THEN  VLR_COPAGOS/(1+(PIVA/100)) ELSE 0 END
   WHERE COALESCE(PIVA,0)>0

   UPDATE #FTRD1 SET VLRIMPUESTO=((VLR_SERVICI-COALESCE(VLR_COPAGOS,0))/(1+(PIVA/100))),
   VIVA=(VLR_SERVICI-COALESCE(VLR_COPAGOS,0))-((VLR_SERVICI-COALESCE(VLR_COPAGOS,0))/(1+(PIVA/100)))
   WHERE COALESCE(PIVA,0)>0

   --UPDATE #FTRD1 SET VLR_SERVICI=(VALOR*CANTIDAD)+COALESCE(VLR_COPAGOS,0)
   --WHERE COALESCE(PIVA,0)>0
      
   SELECT @OK = COUNT(*) FROM #FTRD1
   IF @OK <=0
   BEGIN
      RAISERROR('No fueron Asignados items para Facturar',16,1)
      RETURN
   END
   IF (SELECT SUM(COALESCE(VLR_SERVICI,0)-COALESCE(VLR_COPAGOS,0)) FROM #FTRD1) <=0
   BEGIN
      RAISERROR('La sumatoria de los Items a Facturar Es Cero',16,1)
      RETURN
   END

   SELECT @DV = DIASVTO, @TTEC = TIPOTERCONTABLE
   FROM   PPT 
   WHERE  IDTERCERO = @IDTERCEROCA AND IDPLAN = @IDPLAN
		
   IF ISNULL(@DV,0) <= 0
	   SET @DV = 30
		
   SELECT @CUENTACXC = CUENTA, @CUENTACXC_RAD=CUENTARAD FROM TTEC
   WHERE TIPO = @TTEC 
  
   SELECT @IDTERPART = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJTERCEROEXTERNO'
               
   IF @IDTERCEROCA = @IDTERPART 
   BEGIN   
      SELECT @TV = 'Contado'           
      SELECT @IDTERCEROF = @IDAFILIADO
      SELECT @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
      PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
      EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA,@PROC,@NOAUT
         
	   SELECT @ESPARTPERU = 1
	   SELECT @IDTERCEROF=IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=( 
	   SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO=@IDAFILIADO ) 
      IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCEROF)
      BEGIN
      SELECT @IDTERCEROF=RUC FROM AFI WHERE IDAFILIADO=@IDAFILIADO
      END
   END 
   ELSE
   BEGIN
      SELECT @IDTERCEROF = @IDTERCERO
   END         
   SELECT @OK = COALESCE(COUNT(*),0) FROM TER WHERE IDTERCERO = @IDTERCEROF
   PRINT 'ANTES DE IF OK = 0'       
   IF @OK = 0
   BEGIN
      SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
      PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
      EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
   END
   --SELECT * FROM #FTRD1
   --PRINT 'ME DEVUELVO'
   --RETURN
      
      PRINT 'Valido el Moto Permitido'
   SELECT @MONTO=SUM(COALESCE(VLR_SERVICI,0))  FROM #FTRD1
      IF DBO.FNK_VALIDA_TOPE_FACTURA(CASE WHEN @PROC='CI' THEN 'CITAS' ELSE 'CE' END,@MONTO)=0
   BEGIN
	   RAISERROR('El monto a Facturar Sobrepasa el Valor Autorizado, No se Puede Generar la Factura ',16,1)
      RETURN
   END
	IF @PROC = 'CE'
	BEGIN
		IF COALESCE(@LIBERTER,'')<>'SI'
		BEGIN 
			IF EXISTS(SELECT * FROM FTR WHERE NOREFERENCIA=@NOAUT AND PROCEDENCIA='CE' AND ESTADO='L')
			BEGIN
				SELECT @LIBERADA=1,@NVOCONSEC=N_FACTURA , @CNSFTR=CNSFCT FROM FTR 
				WHERE NOREFERENCIA=@NOAUT 
				AND PROCEDENCIA='CE' AND ESTADO='L' AND N_FACTURA= CASE WHEN COALESCE(@N_FACTURAORI,'')<>'' THEN COALESCE(@N_FACTURAORI,'') ELSE FTR.N_fACTURA END
			END
			ELSE
			BEGIN
				SELECT @LIBERADA=0
			END
		END
		ELSE
		BEGIN 
			IF EXISTS(SELECT * FROM FTR WHERE IDTERCERO=@IDTERCEROCA1 AND ESTADO='L')
			BEGIN
				SELECT TOP 1  @LIBERADA=1,@NVOCONSEC=N_FACTURA , @CNSFTR=CNSFCT FROM FTR WHERE IDTERCERO=@IDTERCEROCA1 
				AND ESTADO='L' 
			END 
		END 
	END
	IF  COALESCE(@LIBERADA,0)=0
	BEGIN            
		EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
		SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0)         
		PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
		PRINT '->>>>>>>>> @IDTERCEROF:  ' +  @IDTERCEROF
		PRINT '->>>>>>>>> @IDAFILIADO:  ' +  @IDAFILIADO
		PRINT '->>>>>>>>> @TV:          ' +  @TV
		PRINT '->>>>>>>>> @ESPARTPERU:  ' 

      PRINT 'AQUI LLAMO A NUMFACTURA'         
      SET @NVOCONSEC = SPACE(20)
      EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
      PRINT 'REGRESE DE NUMFACTURA'
   END
   PRINT '@NVOCONSEC='+@NVOCONSEC  
	IF @PROC = 'CE'
	BEGIN
		SELECT @IDFORMATOFTR=IDFORFTRCE FROM PPT WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLAN
	END
	IF @PROC = 'CI'
	BEGIN
		SELECT @IDFORMATOFTR=IDFORFTRCIT FROM PPT WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLAN
	END
	IF COALESCE(@IDFORMATOFTR,'')=''
	BEGIN
		SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
	END
	/* SE REVISA SI EL PARAMETRO @FECHAFAC VIENE CON FECHA PARA COLOCARLE ESA FECHA A LA FACTURA SI NO SE COLOCA GETDATE()*/
	IF ISNULL(@FECHAFAC,'') = ''
	BEGIN
		SELECT @FECHAFAC =DBO.FNK_GETDATE()
	END
	   PRINT ' N_FACTURA = '+ CASE WHEN @NVOCONSEC IS NULL THEN 'NO FACTURA' ELSE @NVOCONSEC END
	   PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
	   IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
      BEGIN
         IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
         BEGIN
            SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA='FTR'
         END
         ELSE
         BEGIN
            SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = 'FTR'
         END
      END
	   IF @PREFIJOFAC<>LEFT(@NVOCONSEC,LEN(@PREFIJOFAC))
	   BEGIN
         RAISERROR('Inconsistencia entre el prefijo de factura y el nro generado',16,1)
         RETURN			
	   END     
	   IF  COALESCE(@LIBERADA,0)=0
	   BEGIN
		   PRINT 'VOY A INSERTAR FTR...'
		   PRINT '@DESCUENTO ANTES DEL INSERT=  :::::::::'+STR(@DESCUENTO)
			
		   IF (@IDTERCEROCA = dbo.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') AND EXISTS (SELECT * FROM TER WHERE ESTADO='Activo' AND NIT=@IDAFIAUX ))
		   BEGIN
				   SELECT @IDAFILIADOTER= IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=@IDAFIAUX 
		   END 
		   PRINT '@IDAFILIADOTER '+ @IDAFILIADOTER
		   INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
					   VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
					   IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
					   TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
					   INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
					   IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
					   MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
					   CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CAPITADA,CODUNG, CODPRG,
                  IDSEDE, RDIAN,CNSRESOL,IDFORMATO,OBSERVACION1)
		   SELECT @CNSFTR, @COMPANIA, 'C', CASE WHEN COALESCE(@IDTERCERO_RUC,'')<>'' THEN @IDTERCERO_RUC ELSE  CASE WHEN @TV='Contado' AND COALESCE(@ESPARTPERU,0) =1 THEN (CASE @IDTERCEROCA WHEN dbo.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') 
																								   THEN @IDTERCEROF  
																								   ELSE @IDTERCERO END) ELSE  @IDTERCEROCA END END
																								   , 
				   @NVOCONSEC, @FECHAFAC, @FECHAFAC + @DV,
				   0, NULL, NULL, LEFT(@MONEDA,2), NULL, 'P', NULL, 
				   @IDAFILIADO, @USUARIO, @NOAUT,
				   @PROC, 'I', REPLACE(COALESCE(@OBSERVACION,''),'@N_FACTURA',@NVOCONSEC), @TV, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO,
				   GETDATE(), 0, 0, 0, @IDPLAN, NULL, CASE WHEN @ESPARTPERU = 1 AND @TIPOFAC='Boleta' THEN 'N' ELSE 'C' END, NULL, @IDAREA, @CCOSTO, @DATO3, @TTEC,
				   @CUENTACXC,@CUENTACXC_RAD, 0 ,@CODUNG, @CODPRG, @IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,
               COALESCE(@CNSRESOL,''),@IDFORMATOFTR,'CITAUT'
	   END
	   ELSE
	   BEGIN
		   PRINT 'ACTUALIZO FTR FACTURA LIBERADA...........'
		   UPDATE FTR SET ESTADO='P',CONTABILIZADA=0,NROCOMPROBANTE=NULL,NOREFERENCIA=@NOAUT, IDAFILIADO=@IDAFILIADO,PROCEDENCIA=@PROC,
			   IDTERCERO= CASE WHEN COALESCE(@IDTERCERO_RUC,'')<>'' THEN @IDTERCERO_RUC ELSE  CASE WHEN @TV='Contado' AND COALESCE(@ESPARTPERU,0) =1 THEN (CASE @IDTERCEROCA WHEN dbo.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') 
																								   THEN @IDTERCEROF  
																								   ELSE @IDTERCERO END) ELSE  @IDTERCEROCA END END
			   ,IDPLAN=@IDPLAN,CUENTACXC= @CUENTACXC, CUENTACXC_RAD=@CUENTACXC_RAD,
			   TIPOTTEC=@TTEC, F_FACTURA=@FECHAFAC, F_VENCE=@FECHAFAC + @DV,FECHAFAC=GETDATE(), DESCUENTO = @DESCUENTO --  STORRES SE AGREGA CAMPO DE DESCUENTOPARA QUE SE ACTUALIZE
		   WHERE N_FACTURA=@NVOCONSEC AND CNSFCT=@CNSFTR AND ESTADO='L'
	   END
			
	   UPDATE #FTRD1 SET 
	   CANTIDAD    = CASE WHEN CANTIDAD    IS NULL THEN 0 ELSE CANTIDAD    END,
	   VALOR       = CASE WHEN VALOR       IS NULL THEN 0 ELSE VALOR       END,
	   VLR_SERVICI = CASE WHEN VLR_SERVICI IS NULL THEN 0 ELSE VLR_SERVICI END,
	   VR_TOTAL    = CASE WHEN VR_TOTAL    IS NULL THEN 0 ELSE VR_TOTAL    END,
	   VLR_COPAGOS = CASE WHEN VLR_COPAGOS IS NULL THEN 0 ELSE VLR_COPAGOS END,
	   VLR_PAGCOMP = CASE WHEN VLR_PAGCOMP IS NULL THEN 0 ELSE VLR_PAGCOMP END
      WHERE 1=1
         
	   --UPDATE #FTRD1 SET VLR_SERVICI=VLR_COPAGOS, VALOR=VLR_COPAGOS/CANTIDAD, VR_TOTAL=0
	   --WHERE VLR_COPAGOS>VLR_SERVICI
         
         
	   INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
				   IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
				   VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
				   NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
				   IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV,PROCEDENCIA,TCOPAGO)
	   SELECT @CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
		   IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
		   VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
		   NOPRESTACION, NOITEM, AREAFUNCONT, @NVOCONSEC, SUBCCOSTO, PCOSTO, FECHAPREST,
		   IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV,PROCEDENCIA,TCOPAGO       
	   FROM #FTRD1


	   SELECT @VIVA=SUM(COALESCE(VIVA,0)) FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  
	   IF @VIVA>0
	   BEGIN
		   SELECT TOP 1 @PIVA=PIVA ,@MIVA=1 FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  AND COALESCE(PIVA,0)<>0            
		   UPDATE FTR SET MIVA=@MIVA,PIVA=@PIVA,VIVA=@VIVA WHERE N_FACTURA = @NVOCONSEC
	   END


	   SELECT @VRTOTAL = SUM(VR_TOTAL), @VRSERV = SUM(VLR_SERVICI),@VRCOPA = SUM(VLR_COPAGOS)  ,
		   @VRPACO  = SUM(VLR_PAGCOMP)
	   FROM FTRD WHERE N_FACTURA = @NVOCONSEC

	   PRINT '***********************************VALOR ***********************'
	   PRINT @VRTOTAL    
	   PRINT @VRSERV 
	   IF @VRTOTAL < 0
	   BEGIN
		   SELECT @VRTOTAL = 0
	   END
         
	   IF @DESCUENTO IS NULL
		   SELECT @DESCUENTO = 0
          
	   PRINT '@DESCUENTO=  :::::::::'+STR(@DESCUENTO)

	   IF @DESCUENTO > 0
	   BEGIN
		   IF @TIPODTO = 'P'
			   SELECT @VRDTO = ROUND(@VRTOTAL * (COALESCE(@DESCUENTO,0)/100),0)
		   ELSE 
			   SELECT @VRDTO = COALESCE(@DESCUENTO,0) 
		   END           
	   ELSE
	   BEGIN
		   SELECT @VRDTO = 0
	   END
         
	   IF COALESCE(@VRABONO,0)=0
	   BEGIN
		   SELECT @VRABONO = 0
	   END
         
	   UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = ROUND(@VRCOPA,2), VALORPCOMP = @VRPACO,
			   --VR_TOTAL = @VRTOTAL+CASE WHEN @BASE_IVA_SER='CONIVA' THEN 0 ELSE  COALESCE(@VIVA,0) END, //SE VUELVE A ACTUALIZAR ABAJO
			   DESCUENTO = IIF(@ESOPTICA='SI',0,@VRDTO), VR_ABONOS = @VRABONO
	   WHERE N_FACTURA = @NVOCONSEC
         
      
         
	   UPDATE FTR SET VR_TOTAL = COALESCE(VALORSERVICIOS,0) - COALESCE(VALORCOPAGO,0) - COALESCE(VALORPCOMP,0) - COALESCE(DESCUENTO,0) - COALESCE(VR_ABONOS,0)+CASE WHEN @BASE_IVA_SER='CONIVA' THEN 0 ELSE 0 END
	   WHERE  N_FACTURA = @NVOCONSEC  
         
	   IF (SELECT SIIF FROM TER WHERE IDTERCERO = @IDTERCEROCA)=1
	   BEGIN
		   SELECT @OBSERVACION='#$'+COALESCE(SIIFCODIGOPCI,'')+';'+COALESCE(SIIFCONTRATO,@NVOCONSEC)+';'+COALESCE(SIIFCORREOSUPER,'')+'#$'
		   FROM TER WHERE IDTERCERO = @IDTERCEROCA
		   UPDATE FTR SET OBSERVACION=@OBSERVACION WHERE N_FACTURA=@NVOCONSEC
	   END
            
	   UPDATE FTR SET VR_TOTAL = 0
	   WHERE  VR_TOTAL < 0
	   AND    N_FACTURA = @NVOCONSEC      
      
	   IF @EC <> 1
      BEGIN
		   EXEC SPK_FAC_IMPDEDUC @NIT, @CNSFTR, @NVOCONSEC, @VRSERV
      END
  
      UPDATE AUTD SET N_FACTURA=@NVOCONSEC, FACTURADA=1, CNSFCT=@CNSFTR
      FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                  INNER JOIN SER ON SER.IDSERVICIO = AUTD.IDSERVICIO 
                  LEFT JOIN  TER ON TER.IDTERCERO = AUTD.IDTERCEROCA
	   WHERE (AUT.CONSECUTIVOCIT = @NOAUT OR IDAFILIADO=@IDAFILIADO)            
	   AND COALESCE(AUTD.FACTURADA,0)=0 
	   AND AUTD.IDTERCEROCA=@IDTERCEROCA
	   AND AUTD.IDPLAN=@IDPLAN
      AND COALESCE(AUTD.NOCOBRABLE,0)=0


   UPDATE AUT SET AUT.FACTURADA = 1, AUT.N_FACTURA = @NVOCONSEC,
	   AUT.CNSFCT    = @CNSFTR, AUT.VFACTURAS = 0,
	   AUT.MARCAFAC  = 0
   WHERE (CONSECUTIVOCIT = @NOAUT OR IDAFILIADO=@IDAFILIADO)
   AND EXISTS(SELECT * FROM AUTD WHERE AUT.IDAUT=AUTD.IDAUT AND N_FACTURA=@NVOCONSEC)

   UPDATE CIT SET CIT.FACTURADA = 1,   CIT.N_FACTURA = @NVOCONSEC,
		   CIT.CNSFCT    = @CNSFTR, CIT.VFACTURAS = 0,
			   CIT.MARCAFAC  = 0
   WHERE CONSECUTIVO = @NOAUT

  -- CONTABILIZA FACTURA
   EXEC SPK_NC_CONTAB_FTR @NVOCONSEC, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''

   DROP TABLE #FTRD1
   
END




