IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_NC_CONFIRMAR_CONTAB' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_NC_CONFIRMAR_CONTAB
END

GO
CREATE PROCEDURE DBO.SPK_NC_CONFIRMAR_CONTAB
@NROCOMPROBANTE   VARCHAR(20), 
@USUARIO          VARCHAR(12),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@SYS_COMPUTERNAME VARCHAR(254),
@ANO              INT,
@MES              INT,  
@PROCEDENCIA      VARCHAR(20),
@NOREFERENCIA     VARCHAR(20),
@TAREA            VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @T                SMALLINT
DECLARE @PROCESO          VARCHAR(20) 
DECLARE @IDMODELOCONT     VARCHAR(2)
DECLARE @NOMCUENTA        VARCHAR(60)
DECLARE @ESTADO           VARCHAR(8)
DECLARE @ELTIPO           VARCHAR(7)
DECLARE @ANO_INI          INT
DECLARE @MES_INI          INT
DECLARE @ANO_FIN          INT
DECLARE @MES_FIN          INT
DECLARE @CUENTA           VARCHAR(16)
DECLARE @CCOSTO           VARCHAR(20)
DECLARE @DEBITOS          DECIMAL(15,2)
DECLARE @CREDITOS         DECIMAL(15,2)
DECLARE @BANCO            VARCHAR(3)
DECLARE @SUCURSAL         VARCHAR(2)
DECLARE @CTA_BCO          VARCHAR(15)
DECLARE @VALOR            DECIMAL(15,2) 
DECLARE @IDOPERACION      VARCHAR(20)
DECLARE @N_FACTURA        VARCHAR(20)
DECLARE @REFERENCIA1      VARCHAR(20)
DECLARE @ITEMBMOV         DECIMAL(15,0)
DECLARE @FECHACONTABLE    DATETIME
DECLARE @EL_ANO           INT
DECLARE @FECHAINI         DATETIME
DECLARE @FECHAFIN         DATETIME
DECLARE @CERRADO          SMALLINT
BEGIN
   PRINT ''
   PRINT '     *************************************'
   PRINT '     ******** '+@TAREA+' ************'
   PRINT '     *************************************'
   SELECT @CERRADO = COALESCE(PRI.CERRADO,0) FROM PRI WHERE ANO = @ANO AND MES = @MES
   IF @CERRADO = 1
   BEGIN
      RAISERROR ('El Periodo Contable esta Cerrado.', 16, 1)
      RETURN
   END
   IF (SELECT ISNULL(ANULADO,0) FROM MCP WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE) = 1
   BEGIN
      RAISERROR ('El Comprobante %s se encuentra Anulado.', 16, 1, @NROCOMPROBANTE)
      RETURN
   END   
   IF (SELECT ISNULL(ANULADO,0) FROM MCP WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE ) =1
   BEGIN
      UPDATE MCH SET ESTADO=0 WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE
      UPDATE MCP SET ESTADO=0, MARCA = 0, SYS_COMPUTERNAME_MARCA = NULL WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE 
      RAISERROR('El Comprobante está Anulado, por lo tanto sus valores no afectan los Saldos.', 16, 1)
      RETURN  
   END   
   IF @TAREA='CONTABILIZAR'  
   BEGIN
      EXEC SPK_REVISAR_COMPROBANTE @COMPANIA, @NROCOMPROBANTE  
      EXEC SPK_SUMA_DBCR @NROCOMPROBANTE                       
      IF (SELECT ESTADO FROM MCP WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE) <> '1'
      BEGIN
         RAISERROR ('El Comprobante %s no está preparado para su Contabilización.', 16, 1, @NROCOMPROBANTE)
         RETURN
      END   
      IF (SELECT COUNT(*) 
          FROM   MCH LEFT JOIN TER ON MCH.IDTERCERO=TER.IDTERCERO 
          WHERE  MCH.COMPANIA=@COMPANIA AND MCH.NROCOMPROBANTE = @NROCOMPROBANTE 
          AND    TER.IDTERCERO IS NULL 
          AND    ISNULL(MCH.IDTERCERO,'')<>'') > 0
      BEGIN
         RAISERROR ('El Comprobante %s contiene Terceros no configurados en la tabla de Terceros.', 16, 1, @NROCOMPROBANTE)
         RETURN
      END 
      UPDATE MCH SET ESTADO=2 WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE = @NROCOMPROBANTE
      UPDATE MCP SET ESTADO=2, MARCA = 0, SYS_COMPUTERNAME_MARCA = NULL WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE = @NROCOMPROBANTE     
   END
   ELSE
   BEGIN
      IF (SELECT ESTADO FROM MCP WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE) <> 2
      BEGIN
         RAISERROR ('El Comprobante %s no está preparado para su Descontabilización.', 16, 1, @NROCOMPROBANTE)
         RETURN
      END  
      UPDATE MCP SET ESTADO=1, MARCA = 0, SYS_COMPUTERNAME_MARCA = NULL WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE 
      UPDATE MCH SET ESTADO=1 WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE          
   END
END

