IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_PRI' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_PRI
END
GO
CREATE PROCEDURE DBO.SPK_PRI @COMPANIA VARCHAR(2)='01'
WITH ENCRYPTION
AS
/* 
Fecha:		 2020-09-07
Descripción: Procedimiento que creará el periodo contable actual en caso de no estar creado
SET NOCOUNT ON
*/
DECLARE @HOY DATE=CONVERT(DATE,GETDATE())
BEGIN
   IF NOT EXISTS (SELECT * FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=DATEPART(YEAR,@HOY) AND MES=DATEPART(MONTH,@HOY))
   BEGIN
      INSERT INTO PRI (COMPANIA, ANO, MES, NOMPERIODO, FECHA_INI, CERRADO, FECHA_FIN, AJUSTADO, PAAG, COMPROBANTE, 
         DOCUMENTO, NROCOMPROBANTE, TIPO_AJ, CERRADO_INV, NROCOMPROBANTE_AJI, COMPROBANTE_AJI, NOREFERENCIA_AJI,  
         CERRADO_CARTERA, DESALDOSINICIALES, CERRADO_FAC, SI, CIERREFISCAL, EJERCICIOMES, BDATOS, CIERRECOSTOS, 
         CIERREIMP, CERRADO_PPTO, CERRADONIIF, DETCARTERANIIF, DETINVENTARIONIIF,  COMP_DETCARTERA, COMP_DETINVENTARIO, 
         SINIIF, CERRADO_CXP, MCIERRECOSTOS, NROCOMTRASCOSTO, CIERRE_TRASCOSTOS)
      SELECT @COMPANIA, DATEPART(YEAR,@HOY) AS ANO, DATEPART(MONTH,@HOY) AS MES,
         (UPPER(DATENAME(MM,@HOY))+' '+DATENAME(YYYY,@HOY)) AS NOMPERIODO, 
         DATEADD(DAY,-(DATEPART(DAY,@HOY))+1,@HOY) AS FECHA_INI, 0 AS CERRADO, 
         DATEADD(SECOND,-1,CONVERT(DATETIME,DATEADD(DAY,1,DATEADD(DAY,-(DATEPART(DAY,@HOY)),DATEADD(MONTH,1,@HOY))))) AS FECHA_FIN, 0 AS AJUSTADO, 
         0 AS PAAG, '' AS COMPROBANTE, '' AS DOCUMENTO, '' AS NROCOMPROBANTE, 'Mensual' AS TIPO_AJ, 
         0 AS CERRADO_INV, '' AS NROCOMPROBANTE_AJI, '' AS COMPROBANTE_AJI, '' AS NOREFERENCIA_AJI,  
         0 AS CERRADO_CARTERA, 0 AS DESALDOSINICIALES, 0 AS CERRADO_FAC, 0 AS SI, 0 AS CIERREFISCAL, 
         0 AS EJERCICIOMES, '' AS BDATOS, 0 AS CIERRECOSTOS, 0 AS CIERREIMP, 0 AS CERRADO_PPTO, 
         0 AS CERRADONIIF, 0 AS DETCARTERANIIF, 0 AS DETINVENTARIONIIF,  '' AS COMP_DETCARTERA, 
         '' AS COMP_DETINVENTARIO, 0 AS SINIIF, 0 AS CERRADO_CXP, 0 AS MCIERRECOSTOS, '' AS NROCOMTRASCOSTO, 
         0 AS CIERRE_TRASCOSTOS
   END
END

