CREATE OR ALTER PROCEDURE DBO.SPQ_IACTH @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @IDSEDE VARCHAR(5), @DATOS VARCHAR(MAX), @PROCESO VARCHAR(20)
DECLARE @CNSIACTH VARCHAR(20), @IDACTIVO VARCHAR(20), @IDEVENTO VARCHAR(10), @FECHAEVENTO DATETIME, @VALOR DECIMAL(14, 2), @CCOSTO VARCHAR(20), @IDAREA VARCHAR(20)
DECLARE @NODOCUMENTO VARCHAR(20), @TIPODOCU VARCHAR(2), @OBSERVACION VARCHAR(255), @ESTADO VARCHAR(20), @SYS_COMPUTERNAME VARCHAR(254)
DECLARE @MARCACONT SMALLINT, @CONTABILIZADA SMALLINT, @NROCOMPROBANTE VARCHAR(20), @CODUNG VARCHAR(20), @CODPRG VARCHAR(20), @CUENTA VARCHAR(16)
DECLARE @SUBCCOSTO VARCHAR(4), @SECONTABILIZA BIT, @CLASEMMTO VARCHAR(20), @FECHAMTTO DATETIME, @GARANTIA VARCHAR(255), @PARADA VARCHAR(3), @FINIPARADA DATETIME
DECLARE @FFINPARADA DATETIME, @FPROXIMO DATETIME, @APLICADA BIT

BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME
	FROM USUSU
	WHERE USUARIO = @USUARIO

	SELECT @IDSEDE = IDSEDE
	FROM UBEQ
	WHERE SYS_ComputerName = @SYS_COMPUTERNAME

	IF @METODO = 'GUARDAR'
	BEGIN
		BEGIN TRY
			SELECT @PROCESO = PROCESO, @CNSIACTH = CNSIACTH, @IDACTIVO = IDACTIVO, @IDEVENTO = IDEVENTO, @FECHAEVENTO = FECHAEVENTO, @VALOR = VALOR, @CCOSTO = CCOSTO, 
				@IDAREA = IDAREA, @NODOCUMENTO = NODOCUMENTO, @TIPODOCU = TIPODOCU, @OBSERVACION = OBSERVACION, @ESTADO = ESTADO, @MARCACONT = MARCACONT, @CONTABILIZADA 
				= CONTABILIZADA, @NROCOMPROBANTE = NROCOMPROBANTE, @CODUNG = CODUNG, @CODPRG = CODPRG, @CUENTA = CUENTA, @SUBCCOSTO = SUBCCOSTO, @SECONTABILIZA = 
				SECONTABILIZA, @CLASEMMTO = CLASEMMTO, @FECHAMTTO = FECHAMTTO, @GARANTIA = GARANTIA, @PARADA = PARADA, @FINIPARADA = FINIPARADA, @FFINPARADA = 
				FFINPARADA, @FPROXIMO = FPROXIMO, @APLICADA = APLICADA
			FROM OPENJSON(@PARAMETROS) WITH (
					PROCESO VARCHAR(20) '$.PROCESO', CNSIACTH VARCHAR(20) '$.CNSIACTH', IDACTIVO VARCHAR(20) '$.IDACTIVO', IDEVENTO VARCHAR(10) '$.IDEVENTO', 
					FECHAEVENTO DATETIME '$.FECHAEVENTO', VALOR DECIMAL(14, 2) '$.VALOR', CCOSTO VARCHAR(20) '$.CCOSTO', IDAREA VARCHAR(20) '$.IDAREA', NODOCUMENTO 
					VARCHAR(20) '$.NODOCUMENTO', TIPODOCU VARCHAR(2) '$.TIPODOCU', OBSERVACION VARCHAR(255) '$.OBSERVACION', ESTADO VARCHAR(20) '$.ESTADO', 
					MARCACONT SMALLINT '$.MARCACONT', CONTABILIZADA SMALLINT '$.CONTABILIZADA', NROCOMPROBANTE VARCHAR(20) '$.NROCOMPROBANTE', CODUNG VARCHAR(20
					) '$.CODUNG', CODPRG VARCHAR(20) '$.CODPRG', CUENTA VARCHAR(16) '$.CUENTA', SUBCCOSTO VARCHAR(4) '$.SUBCCOSTO', SECONTABILIZA BIT 
					'$.SECONTABILIZA', CLASEMMTO VARCHAR(20) '$.CLASEMMTO', FECHAMTTO DATETIME '$.FECHAMTTO', GARANTIA VARCHAR(255) '$.GARANTIA', PARADA VARCHAR(
						3) '$.PARADA', FINIPARADA DATETIME '$.FINIPARADA', FFINPARADA DATETIME '$.FFINPARADA', FPROXIMO DATETIME '$.FPROXIMO', APLICADA BIT 
					'$.APLICADA'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE, @PREFIJO = '@IACTH', @LONGITUD = 8, @NVOCONSEC = @CNSIACTH OUTPUT

					INSERT INTO [IACTH] (
						[CNSIACTH], [IDACTIVO], [IDEVENTO], [FECHAEVENTO], [VALOR], [CCOSTO], [IDAREA], [NODOCUMENTO], [TIPODOCU], [OBSERVACION], [ESTADO], 
						[USUARIO], [SYS_Computername], [MARCACONT], [CONTABILIZADA], [NROCOMPROBANTE], [CODUNG], [CODPRG], [CUENTA], [SUBCCOSTO], 
						[SECONTABILIZA], [CLASEMMTO], [FECHAMTTO], [GARANTIA], [PARADA], [FINIPARADA], [FFINPARADA], [FPROXIMO], [APLICADA]
						)
					SELECT @CNSIACTH, @IDACTIVO, @IDEVENTO, @FECHAEVENTO, @VALOR, @CCOSTO, @IDAREA, @NODOCUMENTO, @TIPODOCU, @OBSERVACION, @ESTADO, @USUARIO, 
						@SYS_COMPUTERNAME, @MARCACONT, @CONTABILIZADA, @NROCOMPROBANTE, @CODUNG, @CODPRG, @CUENTA, @SUBCCOSTO, @SECONTABILIZA, @CLASEMMTO, 
						@FECHAMTTO, @GARANTIA, @PARADA, @FINIPARADA, @FFINPARADA, @FPROXIMO, @APLICADA
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					UPDATE IACTH
					SET IDEVENTO = @IDEVENTO, FECHAEVENTO = @FECHAEVENTO, VALOR = @VALOR, CCOSTO = @CCOSTO, IDAREA = @IDAREA, NODOCUMENTO = @NODOCUMENTO, TIPODOCU = 
						@TIPODOCU, OBSERVACION = @OBSERVACION, ESTADO = @ESTADO, USUARIO = @USUARIO, SYS_Computername = @SYS_Computername, MARCACONT = @MARCACONT, 
						CONTABILIZADA = @CONTABILIZADA, NROCOMPROBANTE = @NROCOMPROBANTE, CODUNG = @CODUNG, CODPRG = @CODPRG, CUENTA = @CUENTA, SUBCCOSTO = @SUBCCOSTO, 
						SECONTABILIZA = @SECONTABILIZA, CLASEMMTO = @CLASEMMTO, FECHAMTTO = @FECHAMTTO, GARANTIA = @GARANTIA, PARADA = @PARADA, FINIPARADA = 
						@FINIPARADA, FFINPARADA = @FFINPARADA, FPROXIMO = @FPROXIMO, APLICADA = @APLICADA
					WHERE CNSIACTH = @CNSIACTH
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'ELIMINAR'
	BEGIN
		SELECT @CNSIACTH = CNSIACTH
		FROM OPENJSON(@PARAMETROS) WITH (CNSIACTH VARCHAR(20) '$.CNSIACTH')

		BEGIN TRY
			DELETE
			FROM IACTH
			WHERE CNSIACTH = @CNSIACTH
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END
END


