CREATE OR ALTER PROCEDURE DBO.SPQ_GEN_AUT
@JSON  NVARCHAR(MAX) 
WITH ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX) ,@MODELO           VARCHAR(100)    ,@METODO         VARCHAR(100)  ,@USUARIO        VARCHAR(12)
		 ,@GRUPO              VARCHAR(8)    ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE           VARCHAR(5)    ,@A              INT
       ,@DATAGEN            NVARCHAR(MAX) ,@DATATMP          NVARCHAR(MAX)   ,@TIPOENTREGA    varchar(20)   ,@MISMAAUT       BIT
       ,@IDAUT              VARCHAR(20)   ,@NOAUT            VARCHAR(20)     ,@ID             INT           ,@IDBODEGA       VARCHAR(20)
       ,@HOY                DATETIME      ,@FIX              INT             ,@FIXTO          INT           ,@SEDEAUT        VARCHAR(5)
       ,@F_AUT              DATETIME -- SE AGREGA FECHA DE AUTORIZADO POR EL MEDICO JAG 17/01/2022

DECLARE @AUT	TABLE (
	ID			INT PRIMARY KEY IDENTITY(1,1), 
	ITEM		INT,
	CONSECUTIVO VARCHAR(20),
	USUARIO		VARCHAR(12),
	PREFIJO		VARCHAR(6),
	IDAFILIADO	VARCHAR(20),
	IDTERCERO	VARCHAR(20),
	IDPLAN		VARCHAR(6),
	IDAREA		VARCHAR(20),
	CCOSTO		VARCHAR(20),
	NROAUT		VARCHAR(20),
	IDPROVEEDOR VARCHAR(20),
	IDMEDICO	VARCHAR(20),
	FECHA       DATETIME
)
DECLARE @AUTD	TABLE (
	ID			INT PRIMARY KEY IDENTITY(1,1),
	ID_AUT	INT,
	IDSERVICIO	VARCHAR(20),
	CANTIDAD	DECIMAL(18,6),
	CODCUPS		VARCHAR(20),
	AMBITO		VARCHAR(2),
	MARCA		TINYINT,
	NROAUT		VARCHAR(20),
   TABLA       VARCHAR(20)
)
BEGIN
SET LANGUAGE Spanish; 
	SET DATEFORMAT dmy
	SELECT @A = ISJSON(@JSON)
	IF @A = 0 
	BEGIN
		RAISERROR('Json: Formato Erroneo',16,1)
		RETURN
	END
	--PRINT 'INGRESE A SPQ_FME_COL'
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)     AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
	-- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
	PRINT 'USUARIO:'+@USUARIO
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
	IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
	PRINT 'SEDE='+@SEDE

   IF @METODO = 'AUTORIZAR'
   BEGIN
      SELECT @DATAGEN  = DATAGEN, @DATATMP= DATATMP
      FROM OPENJSON (@PARAMETROS)
      WITH(
         DATAGEN   NVARCHAR(MAX)     AS JSON,
         DATATMP   NVARCHAR(MAX)     AS JSON
      )
      SELECT @TIPOENTREGA = JSON_VALUE(@DATAGEN,'$.tipoEntrega.value')    
      SELECT @MISMAAUT    = JSON_VALUE(@DATAGEN,'$.mismaAut')
      
      SELECT * INTO #DATATMP
      FROM  OPENJSON (@DATATMP)
	   WITH (
		    ID                INT             '$.ID'              
         ,IDAFILIADO        VARCHAR(20)     '$.IDAFILIADO'
         ,IDMEDICO          VARCHAR(12)     '$.IDMEDICO'        
         ,ITEMRED           INT             '$.ITEMRED'         
         ,CODOM             VARCHAR(10)     '$.CODOM'           
         ,CONSECUTIVO       VARCHAR(13)     '$.CONSECUTIVO'     
         ,FECHA             DATE            '$.FECHA'           
         ,NOMBRE            VARCHAR(45)     '$.NOMBRE'          
         ,DESCRIPCION       VARCHAR(45)     '$.DESCRIPCION'     
         ,PREFIJO           VARCHAR(6)      '$.PREFIJO'         
         ,NOM_PREFIJO       VARCHAR(60)     '$.NOM_PREFIJO'     
         ,IDSERVICIO        VARCHAR(20)     '$.IDSERVICIO'      
         ,CODCUPS           VARCHAR(20)     '$.CODCUPS'         
         ,DESCSERVICIO      VARCHAR(255)    '$.DESCSERVICIO'    
         ,TIPOFRECUENCIA    VARCHAR(20)     '$.TIPOFRECUENCIA'  
         ,IDAREA            VARCHAR(20)     '$.IDAREA'          
         ,CCOSTO            VARCHAR(20)     '$.CCOSTO'          
         ,IDTERCERO         VARCHAR(20)     '$.IDTERCERO'       
         ,IDPLAN            VARCHAR(6)      '$.IDPLAN'          
         ,NOADMISION        VARCHAR(16)     '$.NOADMISION'      
         ,IDSEDE            VARCHAR(5)      '$.IDSEDE' 
         ,CANTIDAD          DECIMAL(14,2)   '$.CANTIDAD'        
         ,ENCPPAF           VARCHAR(20)     '$.ENCPPAF'         
         ,REQAUTORIZACION   SMALLINT        '$.REQAUTORIZACION' 
         ,PNUMAUTORIZA_OBL  SMALLINT        '$.PNUMAUTORIZA_OBL'
         ,IDPROVEEDORDEF    VARCHAR(20)     '$.IDPROVEEDORDEF'  
         ,NOAUTORIZA        VARCHAR(20)     '$.NOAUTORIZA'      
	   ) 
      SET @HOY = CONVERT(SMALLDATETIME,GETDATE())
      DECLARE @NOAUTORIZA_AUT VARCHAR(20) 
      SELECT @NOAUTORIZA_AUT = CONSECUTIVO FROM #DATATMP GROUP BY CONSECUTIVO --STORRES
      IF COALESCE(@MISMAAUT,0) = 1
      BEGIN
         INSERT INTO @AUT (CONSECUTIVO, PREFIJO, IDAFILIADO, IDTERCERO, IDPLAN, IDAREA, CCOSTO, NROAUT, IDPROVEEDOR, IDMEDICO, FECHA)
         SELECT CONSECUTIVO, MIN(PREFIJO), IDAFILIADO, IDTERCERO, IDPLAN, IDAREA, CCOSTO, NOAUTORIZA, IDPROVEEDORDEF, IDMEDICO, FECHA
         FROM   #DATATMP
         GROUP BY CONSECUTIVO, IDAFILIADO, IDTERCERO, IDPLAN, IDAREA, CCOSTO, NOAUTORIZA, IDPROVEEDORDEF, IDMEDICO, FECHA
      END
      ELSE
      BEGIN 
         INSERT INTO @AUT (CONSECUTIVO, PREFIJO, IDAFILIADO, IDTERCERO, IDPLAN, IDAREA, CCOSTO, NROAUT, IDPROVEEDOR, IDMEDICO, FECHA)
         SELECT DISTINCT CONSECUTIVO, PREFIJO, IDAFILIADO, IDTERCERO, IDPLAN, IDAREA, CCOSTO, NOAUTORIZA, IDPROVEEDORDEF, IDMEDICO, FECHA
         FROM   #DATATMP
      END

      --SELECT TOP 500 * FROM @AUT

      DECLARE C_AUT CURSOR FOR
      SELECT DISTINCT ID FROM  @AUT
      OPEN C_AUT
      FETCH NEXT FROM C_AUT INTO @ID
      WHILE @@fetch_status = 0
      BEGIN
         PRINT 'Genero consecutivo IDAUT'
		   EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@AUT',@IDAUT OUTPUT
		   SELECT @IDAUT = @SEDE + RIGHT('00000000'+CONVERT(VARCHAR(8),@IDAUT),8)
		   PRINT @IDAUT
      
		   PRINT 'Genero consecutivo NOAUT'
		   EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@AUTF',@NOAUT OUTPUT
		   SELECT @NOAUT = @SEDE + RIGHT('00000000'+CONVERT(VARCHAR(8),@NOAUT),8)
		   PRINT @NOAUT

         SELECT @F_AUT= MAX(#DATATMP.FECHA) 
         FROM   #DATATMP INNER JOIN @AUT A ON #DATATMP.NOAUTORIZA = A.NROAUT
         WHERE  A.ID = @ID

         SELECT @F_AUT= MAX(#DATATMP.FECHA) FROM #DATATMP WHERE #DATATMP.NOAUTORIZA = @NOAUTORIZA_AUT
         SELECT @F_AUT = CASE WHEN @F_AUT IS NULL  THEN FECHA ELSE @F_AUT END  FROM @AUT WHERE CONSECUTIVO = @NOAUTORIZA_AUT -- STORRES
         INSERT INTO AUT (  IDAUT, NOAUT, FECHA, FECHAVENCE, IDAFILIADO, NUMCARNET, IDPLAN, PREFIJO, IDSEDE, TIPOAUTORIZACION, 
			                     ALTOCOSTO, ATENCION, IMPUTABLE_A, IDSOLICITANTE, IDPROVEEDOR, ESTADO, AUTORIZADOPOR, FECHAAUTORIZA, IDPESPECIAL, AUTORIZADO, 
			                     USUARIO, IDCAUSAEXT, AMBITO, FINALIDAD, PERSONAL_AT, DXPPAL, TIPOURGENCIA, SPD, IDCONTRATANTE, TIPOCOPAGO, 
			                     CLASECONT, FECHAGEN, PROCEDENCIA, IDAREAH, IDAREA, CCOSTO, NIVELATENCION, FACTURADA, FACTURABLE, IDIPS, 
			                     CLASECONTRATO, ENPAQUETE, SOAT, COBRARA, IDTERCEROCA, CONSECUTIVOHCA, SYS_COMPUTERNAME, TIPOUSUARIO, IDPLAN_AFI, IDTERCERO_AFI, 
			                     CLASEORDEN, URGENCIA, VALORBENEFICIO, VALOREXEDENTE, VALORTOTALCOSTO, VALORCOPAGOCOSTO, IMPRESO, CXPGEN, CXCGEN, PEDIDOINV,
			                     ESCONTINUACION, SEMANASCOT, LIQUIDAPC, ESDEINV, VFACTURAS, DESCUENTO, MARCAFAC, PERIODICIDAD, CONTINUACION, MARCAENV,
			                     COPAGOPROPIO, ESDELAB, ENLAB, PIDECCOSTO, RIESGO, NUMAUTORIZA, TIPOAFILIADO, MENTREGA
		                   )
         SELECT @IDAUT, @NOAUT,COALESCE( CASE WHEN DBO.FNK_VALORVARIABLE('AUT_FECHA_GENERA')='SI' THEN @F_AUT ELSE @HOY END, @HOY) FECHA , 
				    DATEADD(DAY,COALESCE(PRE.VIGENCIA,0), CASE WHEN DBO.FNK_VALORVARIABLE('AUT_FECHA_GENERA')='SI' THEN @F_AUT ELSE @HOY END ) FECHAVENCE,
			       AFI.IDAFILIADO, AFI.NUMCARNET, A.IDPLAN, A.PREFIJO, COALESCE(CIT.IDSEDE,@SEDE) IDSEDE, 'Previa' TIPOAUTORIZACION, 
			       'No' ALTOCOSTO, 'Ambulatoria' ATENCION, 'Administradora' IMPUTABLE_A, A.IDMEDICO IDSOLICITANTE, 
				    COALESCE(A.IDPROVEEDOR,AFI.IDPROVEEDOR) IDPROVEEDOR, 'Pendiente' ESTADO, @USUARIO AUTORIZADOPOR,
				    CASE WHEN DBO.FNK_VALORVARIABLE('AUT_FECHA_GENERA')='SI' THEN @F_AUT ELSE @HOY END FECHAAUTORIZA, CIT.IDPESPECIAL, 0 AUTORIZADO, 
			       @USUARIO, COALESCE(HCA.CAUSA_EXT,(SELECT DATO FROM USVGS WHERE IDVARIABLE='IDCAUSAEXTERNA')) IDCAUSAEXT, LEFT(COALESCE(HCA.AMBITO,'1') ,2)AMBITO, 
                CASE WHEN COALESCE(HCA.FINALIDAD,'')<>'' THEN HCA.FINALIDAD 
                     ELSE (CASE WHEN COALESCE(PRE.FINALIDAD,'')<>'' THEN PRE.FINALIDAD 
                                ELSE (SELECT DATO FROM USVGS WHERE IDVARIABLE='FINCONSULTADEFAULT') 
                           END) 
                END AS FINALIDAD, 
                MES.PERSONAL_AT, CASE (SELECT DATO FROM USVGS WHERE IDVARIABLE='AUTDXDESDEHC') WHEN 'NO' THEN '' ELSE COALESCE(HCA.IDDX,'') END DXPPAL, 'NA' TIPOURGENCIA
				    , 0 SPD, A.IDTERCERO IDCONTRATANTE, 'N' TIPOCOPAGO, 
			       'ENGE' CLASECONT, @HOY FECHAGEN, 'HC' PROCEDENCIA, COALESCE(CIT.IDAREAH,AFU.IDAREAH)IDAREAH, CEN.IDAREA, CEN.CCOSTO, '1' NIVELATENCION,
				    0 FACTURADA, 1 FACTURABLE, AFI.IDPROVEEDOR IDIPS, 
			       CASE PPT.CAPITADO WHEN 1 THEN 'C' ELSE 'E' END CLASECONTRARTO, 
			       0 ENPAQUETE, 0 SOAT, 'C' COBRARA, A.IDTERCERO IDTERCEROCA, COALESCE(HCA.CONSECUTIVO,'') CONSECUTIVOHCA, @SYS_COMPUTERNAME SYS_COMPUTERNAME
				    , USUSU.TIPO TIPOUSUARIO, AFI.IDPLAN IDPLAN_AFI, AFI.IDADMINISTRADORA IDTERCERO_AFI, 
			       COALESCE(CIT.CLASEORDEN,'Normal') CLASEORDEN, 0 URGENCIA, 0 VALORBENEFICIO, 0 VALOREXEDENTE, 0 VALORTOTALCOSTO, 0 VALORCOPAGOCOSTO, 0 IMPRESO, 0 CXPGEN,
				    0 CXCGEN, 0 PEDIDOINV,
			       0 ESCONTINUACION, 0 SEMANASCOT, 0 LIQUIDAPC, ISNULL(MINVENTARIOS,0) ESDEINV, 0 VFACTURAS, 0 DESCUENTO, 0 MARCAFAC, 0 PERIODICIDAD, 0 CONTINUACION, 0 MARCAENV,
			       0 COPAGOPROPIO, 0 ESDELAB, 0 ENLAB, 0 PIDECCOSTO, (CASE HCA.RIESGO WHEN '' THEN NULL ELSE HCA.RIESGO END) RIESGO, 
				    A.NROAUT NUMAUTORIZA,left( AFI.TIPOAFILIADO,1) TIPOAFILIADO, @TIPOENTREGA
		   FROM   @AUT A INNER JOIN AFI      ON AFI.IDAFILIADO=A.IDAFILIADO
                       INNER JOIN USUSU    ON USUSU.USUARIO=@USUARIO
			              INNER JOIN PRE	    ON A.PREFIJO=PRE.PREFIJO
			              LEFT  JOIN HCA      ON HCA.CONSECUTIVO=A.CONSECUTIVO
			              LEFT  JOIN CIT      ON CIT.CONSECUTIVO=HCA.NOADMISION AND ISNULL(CIT.CONSECUTIVO,'')<>'' AND CIT.IDAFILIADO=HCA.IDAFILIADO
			              LEFT  JOIN MED      ON MED.IDMEDICO=A.IDMEDICO
			              LEFT  JOIN MES      ON MES.IDEMEDICA=MED.IDEMEDICA
			              LEFT  JOIN PPT      ON PPT.IDTERCERO=(CASE ISNULL(A.IDTERCERO,'') WHEN '' THEN COALESCE(CIT.IDCONTRATANTE,AFI.IDADMINISTRADORA) ELSE A.IDTERCERO END)
                                          AND PPT.IDPLAN=(CASE ISNULL(A.IDPLAN,'') WHEN '' THEN COALESCE(CIT.IDPLAN,AFI.IDPLAN) ELSE A.IDPLAN END)
			              LEFT  JOIN UBEQ     ON UBEQ.SYS_ComputerName=@SYS_COMPUTERNAME
			              LEFT  JOIN CEN      ON CEN.CCOSTO=(CASE ISNULL(A.CCOSTO,'') WHEN '' THEN COALESCE(CIT.CCOSTO,UBEQ.CCOSTO) ELSE A.CCOSTO END)
			              LEFT  JOIN AFU      ON CEN.IDAREA=AFU.IDAREA
		   WHERE A.ID = @ID
		   UPDATE AUT SET FECHAVENCE = FECHA+30, MENTREGA = 'Institucional' WHERE  IDAUT = @IDAUT

         INSERT INTO @AUTD (ID_AUT, IDSERVICIO, CANTIDAD, CODCUPS, AMBITO, MARCA, NROAUT, TABLA)
	      SELECT A.ID, S.IDSERVICIO, SUM(S.CANTIDAD), SER.CODCUPS, SER.AMBITO, S.CANTIDAD, S.NOAUTORIZA, 'HCA'
         FROM   @AUT A  INNER JOIN #DATATMP S ON A.IDAFILIADO   = S.IDAFILIADO 
			                                    AND A.CONSECUTIVO  = S.CONSECUTIVO 
                                             AND A.PREFIJO      = (CASE @MISMAAUT WHEN 1 THEN A.PREFIJO ELSE S.PREFIJO END)
                        INNER JOIN SER    ON S.IDSERVICIO       = SER.IDSERVICIO
         WHERE  A.ID = @ID
         GROUP BY A.ID, S.IDSERVICIO, SER.CODCUPS, SER.AMBITO, S.CANTIDAD, S.NOAUTORIZA --STORRES

         INSERT INTO AUTD ( IDAUT, NO_ITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALORCOPAGOCOSTO, VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, 
			                   IMPRESO, AUTORIZADO, COMENTARIOS, PCOBERTURA, OBS, NORDEN, CCOSTO, CODIGOCPCJ, MARCAPAGO, NOAUTORIZEXT, 
			                   ESDELAB, ENLAB, IDTERCEROCA, IDCONTRATO, FACTURADA, N_FACTURA, CNSFCT, AQUIENCOBRO, MARCACOPAGOORDEN, VALORPROV, 
			                   PCOSTO, ITFC, CNSITFC, SYS_COMPUTERNAME, NOCOBRABLE, MDOSIFICACION, CANTIDIA, DIAS, FRECUENCIA, CODCUPS, 
			                   POSOLOGIA, SINCRONIZADO, APOYODG_AMBITO, CITAAUTORIZADA, CLASEPOSOLOGIA, MARCA, USUARIOMARCA, 
			                   NUM_ORDEN, PROCESADA, PRIORIDAD )
		   SELECT @IDAUT, ROW_NUMBER() OVER (ORDER BY D.ID), D.IDSERVICIO, D.CANTIDAD, 0, 0, 0, 0, 0, A.IDPLAN,
			       0, 0, '', 100, '', '', A.CCOSTO, '', 0, D.NROAUT, 
			       0, 0, A.IDTERCERO, 'SIN_DEFINIR', 0, '', '', 'N', 0, NULL, 
			       0, 0, NULL, @SYS_COMPUTERNAME, 0, 0, 0, 0, 0, D.CODCUPS, 
			       '', 0, D.AMBITO, 0, 'Tomar', 0, '', 0, 0, 0
		   FROM   @AUT A INNER JOIN @AUTD D ON A.ID = D.ID_AUT --(CASE @MISMAAUT WHEN 1 THEN A.ITEM ELSE D.ITEM_AUT END)
		   WHERE  A.ID = @ID 

         EXEC SPK_CONFIRMAR_AUT @IDAUT

		   IF DBO.FNK_VALORVARIABLE('PEDIRFARMACIACE') = 'SI'
		   BEGIN
			   SELECT @SEDEAUT = IDSEDE FROM AUT WHERE IDAUT = @IDAUT
			   SELECT @IDBODEGA = ISNULL(IDBODEGA,IDBODEGA2) FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
			   EXEC SPK_PEDIDOINVCE @IDAUT, @IDBODEGA, '01', @SEDEAUT, @USUARIO, @SYS_COMPUTERNAME
		   END

		   PRINT 'Cambio el campo HCATD.APLICADA 0=SinAutorizar, 1=Autorizado, 2=NoAutorizado'
		   UPDATE HCATD SET APLICADA =1
		   FROM   @AUT A INNER JOIN @AUTD D ON A.ID = D.ID_AUT
			              INNER JOIN HCATD   ON HCATD.CONSECUTIVO = A.CONSECUTIVO 
                                         AND HCATD.IDSERVICIO  = D.IDSERVICIO
		   WHERE  A.ID = @ID 
         AND    COALESCE(A.CONSECUTIVO,'') <> '' 

         FETCH NEXT FROM C_AUT INTO @ID
      END
      CLOSE C_AUT  
      DEALLOCATE C_AUT


      SELECT 'OK' OK
      --SELECT @TIPOENTREGA TIPOENTREGA,@MISMAAUT MISMAAUT
      --SELECT * FROM #DATATMP
      --SELECT * FROM @AUT

      RETURN
   END
   RETURN
END




