CREATE OR ALTER PROCEDURE DBO.SPQ_CXT_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY           INT 
       ,@PROCESO            VARCHAR(20)    ,@CXT    NVARCHAR(MAX)
              ,@CODCAJA     VARCHAR(4)
       ,@CODTURNO     VARCHAR(4)
       ,@CODCAJERO     VARCHAR(20)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_CXT_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'CRUDCXT'
   BEGIN
      PRINT 'CRUDCXT'
      SELECT @CXT  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@CXT ,'$.PROCESO')
      --Leo Campos enviados y los coloco en las variables respectivas
      SELECT @CODCAJA = JSON_VALUE(@CXT , '$.CODCAJA' )
      SELECT @CODTURNO = JSON_VALUE(@CXT , '$.CODTURNO' )
      SELECT @CODCAJERO = JSON_VALUE(@CXT , '$.CODCAJERO' )

      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'
         BEGIN TRY
			INSERT INTO @TBLERRORES(ERROR) 
			SELECT 'EL TURNO YA EXISTE PARA ESTA CAJA'
			WHERE EXISTS (SELECT 1 FROM CXT WHERE CODCAJA = @CODCAJA AND CODTURNO = @CODTURNO)

			IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
			BEGIN
				INSERT INTO CXT(CODCAJA,CODTURNO,CODCAJERO)
				SELECT @CODCAJA,@CODTURNO,@CODCAJERO
				SELECT @IDENTITY = SCOPE_IDENTITY()
			END
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK ,@IDENTITY CNS 
         RETURN
      END

      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         BEGIN TRY
            UPDATE CXT SET
                    CODCAJA = @CODCAJA,CODTURNO = @CODTURNO,CODCAJERO = @CODCAJERO
            WHERE CODCAJA = @CODCAJA
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END

	  IF UPPER(@PROCESO) = 'ELIMINAR'
		BEGIN
			PRINT 'ELIMINAR'
			BEGIN TRY
				IF COALESCE(@CODCAJA,'')=''
				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'EL CODIGO DE LA CAJA ES OBLIGATORIO'

				IF COALESCE(@CODTURNO,'')='' 
				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'EL CODIGO DEL TURNO ES OBLIGATORIO'

				IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
				BEGIN
					DELETE FROM CXT WHERE  CODCAJA = @CODCAJA AND CODTURNO = @CODTURNO
				END		
			END TRY

			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH

			IF(SELECT COUNT(*) FROM @TBLERRORES) >0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			SELECT 'OK' OK
			RETURN
		END
      RETURN
   END
END


