CREATE OR ALTER PROCEDURE DBO.SPQ_EVENTOAF @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @DATOS VARCHAR(MAX)
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @IDSEDE VARCHAR(5)
DECLARE @PROCESO VARCHAR(20), @IDEVENTO VARCHAR(10), @IDEVENTOEDITE VARCHAR(10), @DESCRIPCION VARCHAR(100), @ESTADO VARCHAR(26), @PIDEESTADO VARCHAR(2), @PIDEVALOR 
	VARCHAR(2), @PIDECCOSTO VARCHAR(2), @MUEVECONTABILIDAD VARCHAR(2), @COMPROBANTE VARCHAR(2), @TIPO VARCHAR(10), @BAJA SMALLINT

BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	IF @METODO = 'GUARDAR'
	BEGIN
		BEGIN TRY
			SELECT @PROCESO = PROCESO, @IDEVENTO = IDEVENTO, @DESCRIPCION = DESCRIPCION, @ESTADO = ESTADO, @PIDEESTADO = PIDEESTADO, @PIDEVALOR = PIDEVALOR, @PIDECCOSTO = 
				PIDECCOSTO, @MUEVECONTABILIDAD = MUEVECONTABILIDAD, @COMPROBANTE = COMPROBANTE, @TIPO = TIPO, @BAJA = BAJA
			FROM OPENJSON(@PARAMETROS) WITH (
					PROCESO VARCHAR(20) '$.PROCESO', IDEVENTO VARCHAR(10) '$.IDEVENTO', DESCRIPCION VARCHAR(100) '$.DESCRIPCION', ESTADO VARCHAR(26) '$.ESTADO', 
					PIDEESTADO VARCHAR(2) '$.PIDEESTADO', PIDEVALOR VARCHAR(2) '$.PIDEVALOR', PIDECCOSTO VARCHAR(2) '$.PIDECCOSTO', MUEVECONTABILIDAD VARCHAR(2) 
					'$.MUEVECONTABILIDAD', COMPROBANTE VARCHAR(2) '$.COMPROBANTE', TIPO VARCHAR(10) '$.TIPO', BAJA SMALLINT '$.BAJA'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL ID EVENTO ', @IDEVENTO, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM IACTE
							WHERE IDEVENTO = @IDEVENTO
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						INSERT INTO IACTE (IDEVENTO, DESCRIPCION, PIDEESTADO, PIDEVALOR, PIDECCOSTO, ESTADO, MUEVECONTABILIDAD, COMPROBANTE, TIPO, BAJA
							)
						SELECT @IDEVENTO, @DESCRIPCION, @PIDEESTADO, @PIDEVALOR, @PIDECCOSTO, @ESTADO, @MUEVECONTABILIDAD, @COMPROBANTE, @TIPO, @BAJA
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					SELECT @DATOS = DATOS
					FROM OPENJSON(@PARAMETROS) WITH (DATOS NVARCHAR(MAX) AS JSON)

					SELECT @IDEVENTOEDITE = IDEVENTOEDITE
					FROM OPENJSON(@DATOS) WITH (IDEVENTOEDITE VARCHAR(10) '$.IDEVENTOEDITE')

					IF (@IDEVENTOEDITE <> @IDEVENTO)
					BEGIN
						INSERT INTO @TBLERRORES (ERROR)
						SELECT CONCAT ('EL CODIGO ', @IDEVENTO, ' YA SE ENCUENTRA REGISTRADO')
						WHERE EXISTS (
								SELECT 1
								FROM IACTE
								WHERE IDEVENTO = @IDEVENTO
								)

						IF (
								SELECT COUNT(*)
								FROM @TBLERRORES
								) <= 0
						BEGIN
							UPDATE IACTE
							SET IDEVENTO = @IDEVENTO, DESCRIPCION = @DESCRIPCION, PIDEESTADO = @PIDEESTADO, PIDEVALOR = @PIDEVALOR, PIDECCOSTO = @PIDECCOSTO, ESTADO = 
								@ESTADO, MUEVECONTABILIDAD = @MUEVECONTABILIDAD, COMPROBANTE = @COMPROBANTE, TIPO = @TIPO, BAJA = @BAJA
							WHERE IDEVENTO = @IDEVENTOEDITE
						END
					END
					ELSE
					BEGIN
						UPDATE IACTE
						SET DESCRIPCION = @DESCRIPCION, PIDEESTADO = @PIDEESTADO, PIDEVALOR = @PIDEVALOR, PIDECCOSTO = @PIDECCOSTO, ESTADO = @ESTADO, 
							MUEVECONTABILIDAD = @MUEVECONTABILIDAD, COMPROBANTE = @COMPROBANTE, TIPO = @TIPO, BAJA = @BAJA
						WHERE IDEVENTO = @IDEVENTO
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'ELIMINAR'
	BEGIN
		SELECT @IDEVENTO = IDEVENTO
		FROM OPENJSON(@PARAMETROS) WITH (IDEVENTO VARCHAR(10) '$.IDEVENTO')

		BEGIN TRY
			DELETE
			FROM IACTE
			WHERE IDEVENTO = @IDEVENTO
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END
END


