CREATE OR ALTER PROCEDURE DBO.SPQ_CJR_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY           INT 
       ,@PROCESO            VARCHAR(20)    ,@CJR    NVARCHAR(MAX)
              ,@CODCAJERO     VARCHAR(20)
       ,@DESCRIPCION     VARCHAR(40)
       ,@CLASE     VARCHAR(9)
       ,@FECHACREACION     DATETIME
       ,@FECHACREACION_STR VARCHAR(10)
       ,@ESTADO     VARCHAR(8)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_CJR_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'CRUDCJR'
   BEGIN
      PRINT 'CRUDCJR'
      SELECT @CJR  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@CJR ,'$.PROCESO')
      --Leo Campos enviados y los coloco en las variables respectivas
      SELECT @CODCAJERO = JSON_VALUE(@CJR , '$.CODCAJERO' )
      SELECT @DESCRIPCION = JSON_VALUE(@CJR , '$.DESCRIPCION' )
      SELECT @CLASE = JSON_VALUE(@CJR , '$.CLASE' )
      SELECT @FECHACREACION = GETDATE()
      SELECT @ESTADO = JSON_VALUE(@CJR , '$.ESTADO' )

      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'
         BEGIN TRY
			 INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'EL CAJERO YA EXISTE'
				WHERE EXISTS (SELECT 1 FROM CJR WHERE CODCAJERO = @CODCAJERO)

				IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
				BEGIN
					INSERT INTO CJR(CODCAJERO,DESCRIPCION,CLASE,FECHACREACION,ESTADO)
					SELECT @CODCAJERO,@DESCRIPCION,@CLASE,@FECHACREACION,@ESTADO
					SELECT @IDENTITY = SCOPE_IDENTITY()
				END
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK ,@IDENTITY CNS 
         RETURN
      END

      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         BEGIN TRY
            UPDATE CJR SET
                    CODCAJERO = @CODCAJERO,DESCRIPCION = @DESCRIPCION,CLASE = @CLASE,ESTADO = @ESTADO
            WHERE CODCAJERO = @CODCAJERO
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END

	  IF UPPER(@PROCESO) = 'ELIMINAR'
	  	BEGIN
			PRINT 'ELIMINAR'
			BEGIN TRY
				SELECT @CODCAJERO = JSON_VALUE(@CJR, '$.CODCAJERO')

				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'EL CAJERO TIENE TURNOS ASIGNADO'
				WHERE EXISTS (SELECT 1 FROM CXT WHERE CODCAJERO = @CODCAJERO)

				IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
				BEGIN
					DELETE FROM CJR WHERE CODCAJERO = @CODCAJERO
				END		
			END TRY

			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH

			IF(SELECT COUNT(*) FROM @TBLERRORES) >0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			SELECT 'OK' OK
			RETURN
		END
      RETURN
   END
END


