CREATE OR ALTER PROCEDURE DBO.SPQ_FEVRIPS_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@CNSFTR VARCHAR(20)                ,@TIPODOC   VARCHAR(2)

BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='NOTA_AJUSTE'     
   BEGIN         
      SELECT @CNSFTR=CNSFCT,@TIPODOC=TIPODOC       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSFCT  VARCHAR(20)   '$.CNSFCT',
      TIPODOC  VARCHAR(20)   '$.TIPODOC'
      )
      IF EXISTS(SELECT * FROM FTRJSON WHERE CNSFCT=@CNSFTR)
      BEGIN
         SELECT 'OK'OK,JSON_QUERY(JSON_ENVIO, '$.rips') AS JSON_ENVIO,CUV FROM FTRJSON WHERE CNSFCT=@CNSFTR
         RETURN
      END
      ELSE
      BEGIN
         SELECT 'KO'OK, 'No se Encontro el dato buscado, verifique e intente de nuevo 'ERROR
      END
   END  

END

