CREATE OR ALTER PROCEDURE DBO.SPQ_CONTABILIDAD_2
    @JSON NVARCHAR(MAX) 
WITH ENCRYPTION
AS
BEGIN
   
    SET NOCOUNT ON;

	DECLARE @PARAMETROS NVARCHAR(MAX),		@MODELO VARCHAR(100),		@METODO			VARCHAR(100),		@QUERY				VARCHAR(MAX),
			@USUARIO VARCHAR(20),			@CNSFACJ VARCHAR(20),		@NOADMISION		VARCHAR(16),		@IDKPAGE			INT,
			@DOCIDAFILIADO VARCHAR(20),		@DocumentoID VARCHAR (50),
			@PAGOS NVARCHAR(MAX) ,			@VALOR DECIMAL(18,2) ,		@CNSFCJ			VARCHAR(20),		@CONORDEN			VARCHAR(2),
			@ITEM			INT,			@REFERENCIA	VARCHAR(20),	@PROCEDENCIA	VARCHAR(25),		@OBSERVACION		VARCHAR(200),
			@ESTADO VARCHAR(25),			@CONSECUTIVO INT,			@IDAFILIADO		VARCHAR(20),		@VLRCOPAGO			DECIMAL(16,2),
			@IDPLAN			VARCHAR(6),		@N_FACTURA VARCHAR(16),		@TCNSFACJ		VARCHAR(15),		@PAGOSTFCJ			NVARCHAR(MAX),
			@IDKPAGED			INT,		@CODCAJA VARCHAR(15),		@NOMBRECLIENTE	VARCHAR(20),		@COMPUTERNAME		VARCHAR(20),
			@VALORPAGADOD	DECIMAL(18,2),	@COMPANIA  VARCHAR(2),		@CLASE_FAC		VARCHAR(20),		@IDTERCERO			VARCHAR(20),
			@VLRPENDIENTE	DECIMAL(18,2),	@TIPO VARCHAR(50),			@CLASE			VARCHAR(50),		@FECHAPAGO			DATE,			@FECHA				DATETIME,
			@CNSACJ VARCHAR(20),			@SYS_COMPUTERNAME VARCHAR(20), @SEDE		VARCHAR(16),		@CODIGOVOUCHER		VARCHAR(100),	@NROCOMPROBANTE		VARCHAR(50),
			@USUCAJA VARCHAR (50),			@RAZONANULACION VARCHAR(100)  ,@NOPRESTACION VARCHAR(20),	    @ULTIMO_ANO			INT,			@IDSEDE				VARCHAR(5),
			@ULTIMO_MES INT,		        @SIGUIENTE_ANO INT,        @SIGUIENTE_MES	INT,				@PERIODO_EXISTE		BIT,	        @NOMPERIODO			VARCHAR(13),
			@ANO INT,						@PERIODO_ABIERTO_EXISTE BIT, @FECHA_INI		DATE,				@FECHA_FIN			DATE,			@ANULAR_TRASLADO	BIT,
			@CNSLOG VARCHAR(20),			@EXISTE_TRASLADO BIT, 		@PERIODO_ANO	VARCHAR(4),			@PERIODO_MES		SMALLINT, 		@PERIODO_NOMBRE		VARCHAR(50),
			@CUENTA_INICIAL VARCHAR(20),	@CUENTA_FINAL VARCHAR(20),	 @ANO_INI		INT,				@MES_INI			INT,			@ANO_FIN			INT,
			@MES_FIN INT,					@CTA_INI VARCHAR(16),		@CTA_FIN		VARCHAR(16),        @PROCESO			VARCHAR(20),    @PERIODO_ANTERIOR	VARCHAR(6),
            @ANO_ANT INT,			        @MES_ANT INT,				@REGISTROS		NVARCHAR(MAX),		@CNSCIRUNI			INT,			@CNSPRO				VARCHAR(20),
			@MES SMALLINT,					@N_INICIAL VARCHAR(2),		@PYG			VARCHAR(2),			@PYGNIIF			VARCHAR(2), 	@ANOMESCERRAR		VARCHAR(6),
			@ANOMES VARCHAR(6),				@ULTIMO_ANO_CERRADO INT,	@ULTIMO_MES_CERRADO INT,			@ERRORES_INTEGRIDAD INT,			@NVOCONSEC			INT,
			@GEN_FILE BIT,					@CNSEXOFGE VARCHAR(20), 	@CNS			VARCHAR(20),		@WHERE				NVARCHAR(MAX),	@IDTERCEROINI		VARCHAR(20),
			@IDTERCEROFIN VARCHAR(20),		@CCOSTOINI VARCHAR(20),		@CCOSTOFIN		VARCHAR(20),		@TIPOMOVIMIENTO		VARCHAR(2),		@DOCUMENTO			VARCHAR(20),
			@CODUNG VARCHAR(5),				@CODPRG VARCHAR(20),		@SINCIERRE		BIT,				@TIPO_REPORTE		VARCHAR(20),	@CODPRES			VARCHAR(20), @CODPRES_ANT	VARCHAR(20),
			@DESCRIPCION VARCHAR(60),		@CUENTA_UTI VARCHAR(16),	@CUENTA_PER		VARCHAR(16),		@CUENTA_CIE			VARCHAR(16),	@IDFORMATO			VARCHAR(10),
			@TITULO VARCHAR(60),			@FORMULA	VARCHAR(1024),	@VARIABLETOTAL	VARCHAR(20),		@ITEM_ANT			VARCHAR(3),		@CORRIENTE			SMALLINT	
		;DECLARE @TBLERRORES TABLE(CONTINUA VARCHAR(2), ERROR VARCHAR(500))  
		SET DATEFORMAT dmy
		SELECT *
		INTO #JSON
		FROM OPENJSON (@json)
		WITH (
			MODELO         VARCHAR(100)     '$.MODELO',
			METODO         VARCHAR(100)     '$.METODO',
			USUARIO         VARCHAR(20)     '$.USUARIO',
			DOCIDAFILIADO VARCHAR(20)		'$.DOCIDAFILIADO',
			PARAMETROS     NVARCHAR(MAX)  AS JSON
		)
		SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO, @DOCIDAFILIADO= DOCIDAFILIADO-- , @TCNSFACJ= CNSFACJ
		FROM #JSON
		DECLARE @LOG_ERR TABLE (ERROR VARCHAR(500))
		
		IF @METODO = 'OBTENER_PERIODO_A_CERRAR'
		BEGIN  
			BEGIN TRY
				PRINT '1 VALIDACIONES'
				-- VALIDACI?N 1: Existencia de Per?odo de Saldos Iniciales
				IF (SELECT COUNT(1) FROM PRI WHERE COALESCE(SI,0) = 1) <> 1
				BEGIN
					SELECT 'KO' AS OK, 
						   ERROR = 'Inconsistencia en Cierres Contables. NO EXISTE Per?odo de Saldos Iniciales.'
					RETURN
				END
				-- VALIDACI?N 2: SI Abierto con Per?odos Cerrados
				PRINT '2 VALIDACIONES'
				IF EXISTS(SELECT 1 FROM PRI WHERE SI=1 AND COALESCE(CERRADO,0)=0)
				BEGIN
					IF (SELECT COUNT(1) FROM PRI WHERE COALESCE(SI,0) = 0 AND COALESCE(CERRADO,0)=1) > 0
					BEGIN
						SELECT 'KO' AS OK,
							   ERROR = 'Inconsistencia en Cierres Contables. El Per?odo de Saldos Iniciales No Est? Cerrado Y Existen Per?odos Siguientes Cerrados.'
						RETURN
					END
					ELSE
					BEGIN
						-- El per?odo a cerrar es el SI
						SELECT @ANOMESCERRAR = ANOMES FROM PRI WHERE SI=1 AND COALESCE(CERRADO,0)=0
					END
				END
        
				-- VALIDACI?N 3: Secuencia de Per?odos
				PRINT '3 VALIDACIONES'
				IF @ANOMESCERRAR IS NULL
				BEGIN
					DECLARE CUR_APER CURSOR FOR
					SELECT ANOMES, ANO, MES FROM PRI WHERE COALESCE(SI,0) = 0 AND COALESCE(CERRADO,0)=0 ORDER BY ANO, MES
					OPEN CUR_APER
					FETCH NEXT FROM CUR_APER INTO @ANOMES, @ANO, @MES
            
					WHILE @@FETCH_STATUS = 0
					BEGIN
						-- Verificar si existen per?odos posteriores cerrados
						IF EXISTS(SELECT 1 FROM PRI WHERE COALESCE(SI,0) = 0 AND TRY_CAST(ANOMES AS INT) > TRY_CAST(@ANOMES AS INT) AND COALESCE(CERRADO,0) = 1)
						BEGIN
							CLOSE CUR_APER
							DEALLOCATE CUR_APER
                    
							SELECT 'KO' AS OK,
								   ERROR = 'Inconsistencia en Cierres Contables. El Per?odo ' + 
										   CAST(@ANO AS VARCHAR) + '-' + RIGHT('0' + CAST(@MES AS VARCHAR), 2) + 
										   ' NO se ha Cerrado, Y Existen Per?odos Siguientes Cerrados.'
							RETURN
						END
						ELSE
						BEGIN
							-- VALIDACI?N 4: Cierre Fiscal
							PRINT '4 VALIDACIONES'
							IF EXISTS(SELECT 1 FROM PRI WHERE ANOMES=@ANOMES AND MES IN (SELECT MESDECIERRE FROM PAR WHERE COMPANIA = '01'))
							BEGIN
								-- Es un per?odo de cierre fiscal
								IF (SELECT COALESCE(CIERREFISCAL,0) FROM PRI WHERE ANOMES=@ANOMES) = 1
								BEGIN
									-- Verificar comprobantes sin confirmar o con errores
									IF (SELECT COUNT(1) FROM MCP WHERE COALESCE(ESTADO,0) <> 2 AND COALESCE(ANULADO,0) = 0 AND ANOMES=@ANOMES) > 0
									BEGIN
										CLOSE CUR_APER
										DEALLOCATE CUR_APER
                                
										SELECT 'KO' AS OK,
											   ERROR = 'Existen Comprobantes con errores o sin confirmar en el per?odo.'
										RETURN
									END 
									ELSE
									BEGIN
										SET @ANOMESCERRAR = @ANOMES
									END
								END
								ELSE
								BEGIN
									CLOSE CUR_APER
									DEALLOCATE CUR_APER
                            
									SELECT 'KO' AS OK,
										   ERROR = 'Inconsistencia en Cierres Contables. El Per?odo ' + 
												   CAST(@ANO AS VARCHAR) + '-' + RIGHT('0' + CAST(@MES AS VARCHAR), 2) + 
												   ' Es de Cierre Fiscal, Y No se ha hecho el proceso de cierre de cuentas 4,5 y 6.'
									RETURN
								END
							END
							ELSE
							BEGIN
								-- No es cierre fiscal, este es el per?odo a cerrar
								SET @ANOMESCERRAR = @ANOMES
							END
                    
							-- Salir del cursor
							BREAK
						END
                
						FETCH NEXT FROM CUR_APER INTO @ANOMES, @ANO, @MES
					END
            
					CLOSE CUR_APER
					DEALLOCATE CUR_APER
				END

				-- VALIDACI?N 5: Traslado de Costos
				PRINT '5 VALIDACIONES'
				IF @ANOMESCERRAR IS NOT NULL
				BEGIN
					IF DBO.FNK_VALORVARIABLE('CONTABGENTRASLACOSTO') = 'SI'
					BEGIN
              
						IF (SELECT COALESCE(CIERRE_TRASCOSTOS,0) FROM PRI WHERE ANO=@ANO AND MES=@MES) = 0
						BEGIN
							SELECT 'KO' AS OK,
								   ERROR = 'No Se Ha Realizado el Traslado de Costos Para Este Mes.'
							RETURN
						END
					END
				END

				-- VALIDACI?N 6: Resultado Final
				PRINT '6 VALIDACIONES'
				IF COALESCE(@ANOMESCERRAR,'') = ''
				BEGIN        
					SELECT 'KO' AS OK, ERROR = 'No Existe un Per?odo Que Cerrar.';
					RETURN
				END
        
				-- RETORNO EXITOSO

				SELECT 'OK' AS OK,  ANO, MES, COMPANIA, NOMPERIODO,  ANOMES FROM PRI WHERE ANOMES = @ANOMESCERRAR
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END
		IF @METODO = 'VALIDAR_PERIODO_BASICO'
		BEGIN
			DECLARE @DIACOM DATE
    
			BEGIN TRY
				SELECT @ANO = ANO,@MES = MES,@COMPANIA = COMPANIA
				FROM OPENJSON(@PARAMETROS)
				WITH (
					ANO INT,
					MES INT,
					COMPANIA VARCHAR(2)
				)
        
				-- Construir ANOMES
				SET @ANOMES = CAST(@ANO AS VARCHAR(4)) + RIGHT('0' + CAST(@MES AS VARCHAR(2)), 2)
        
				-- Obtener fecha del per?odo
				SET @DIACOM = DATEFROMPARTS(@ANO, @MES, 1)
        
				-- VALIDACI?N 1: Movimientos de Inventario Pendientes
				IF DBO.FNK_VALORVARIABLE('VALIDAINVCIERRECONT') = 'SI'
				BEGIN
					IF (SELECT COUNT(1) 
						FROM IMOV 
						WHERE FECHAMOV >= @DIACOM 
						  AND FECHAMOV <= EOMONTH(@DIACOM) 
						  AND COALESCE(ESTADO,0) = 0
						  AND IDTIPOMOV IN (SELECT IDTIPOMOV FROM ITMO WHERE SECONTABILIZA=1)) > 0
					BEGIN
						SELECT 'KO' AS OK,
							   ERROR = 'HAY MOVIMIENTOS DE INVENTARIO PENDIENTES POR CONFIRMAR PARA ESTE PERIODO CONTABLE'
						RETURN
					END
				END
        
				-- VALIDACI?N 2: Per?odo de Saldos Iniciales ?nico
				IF (SELECT COUNT(*) FROM PRI WHERE COALESCE(SI,0) = 1) <> 1
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'MAS DE UN PERIODO DEFINIDO COMO DE SALDOS INICIALES.'
					RETURN
				END
        
				-- VALIDACI?N 3: Verificar que el Per?odo NO est? ya Cerrado
				IF (SELECT COALESCE(CERRADO,0) FROM PRI WHERE ANOMES=@ANOMES) = 1
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'EL PERIODO YA ESTA CERRADO'
					RETURN
				END
        
				-- VALIDACI?N 4: Comprobantes sin Confirmar
				IF (SELECT COUNT(1) 
					FROM MCP 
					WHERE COALESCE(ESTADO,0) <> 2 
					  AND COALESCE(ANULADO,0) = 0 
					  AND ANOMES=@ANOMES) > 0
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = N'FALTAN COMPROBANTES POR CONFIRMAR',
						   ERRORES_DETALLE = (
							   SELECT
								   N'COMPROBANTES' AS MODULO,
								   MCP.NROCOMPROBANTE AS REFERENCIA,
								   CONCAT(
									   N'Sin confirmar. Tipo=', COALESCE(MCP.COMPROBANTE, N''),
									   N' | Estado=', COALESCE(CONVERT(VARCHAR(10), MCP.ESTADO), N''),
									   N' | Procedencia=', COALESCE(MCP.PROCEDENCIA, N''),
									   N' | NoRef=', COALESCE(MCP.NOREFERENCIA, N''),
									   N' | Usuario=', COALESCE(MCP.USUARIO, N'')
								   ) AS ERROR
							   FROM MCP
							   WHERE COALESCE(ESTADO, 0) <> 2
								 AND COALESCE(ANULADO, 0) = 0
								 AND ANOMES = @ANOMES
							   FOR JSON PATH
						   )
					RETURN
				END
        
				-- VALIDACI?N 5: Comprobantes con Errores (MCPE)
				IF (SELECT COUNT(1) FROM MCPE WHERE ANO=@ANO AND MES=@MES AND COALESCE(CLASECONTB,'') <> 'NIIF') > 0
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = N'EN EL PERIODO EXISTEN COMPROBANTES CON ERRORES (MCPE).',
						   ERRORES_DETALLE = (
							   SELECT
								   N'MCPE' AS MODULO,
								   COALESCE(MCPE.NROCOMPROBANTE, MCPE.NOREFERENCIA, N'') AS REFERENCIA,
								   CONCAT(
									   N'Comprobante con error. Procedencia=', COALESCE(MCPE.PROCEDENCIA, N''),
									   N' | Clase=', COALESCE(MCPE.CLASECONTB, N'')
								   ) AS ERROR
							   FROM MCPE
							   WHERE ANO = @ANO
								 AND MES = @MES
								 AND COALESCE(CLASECONTB, '') <> 'NIIF'
							   FOR JSON PATH
						   )
					RETURN
				END
        
				-- TODAS LAS VALIDACIONES B?SICAS PASARON
				SELECT 'OK' AS OK,
					   MENSAJE = 'Validaciones b?sicas completadas exitosamente',
					   ANO = @ANO,
					   MES = @MES,
					   ANOMES = @ANOMES
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error en validaciones b?sicas: ' + ERROR_MESSAGE(),
					   ERROR_LINE = ERROR_LINE()
				RETURN
			END CATCH
    
			RETURN
		END
		IF @METODO = 'EJECUTAR_CIERRE_PERIODO'
		BEGIN
			BEGIN TRY
				-- Extraer par?metros
				SELECT 
					@ANO = ANO,
					@MES = MES,
					@COMPANIA = COMPANIA
				FROM OPENJSON(@PARAMETROS)
				WITH (
					ANO INT,
					MES INT,
					COMPANIA VARCHAR(2)
				)
        
				SET @ANOMES = CAST(@ANO AS VARCHAR(4)) + RIGHT('0' + CAST(@MES AS VARCHAR(2)), 2)
        
				-- EJECUCI?N DEL CIERRE
				PRINT 'Ejecutando SPK_CIERRA_PERIODOCONTABLE...'
				EXEC SPK_CIERRA_PERIODOCONTABLE @ANO, @MES, @USUARIO
				PRINT 'SPK_CIERRA_PERIODOCONTABLE completado'
        
				-- LOG DE AUDITOR?A
				SELECT @COMPANIA = COMPANIA FROM USUSU WHERE USUARIO = @USUARIO
				SET @FECHA = GETDATE()
				SELECT @IDSEDE = IDSEDE 
				FROM UBEQ 
				WHERE SYS_ComputerName = (SELECT SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO)
        
				-- Generar consecutivo para log
				EXEC DBO.SPK_GENCONSECUTIVO
					@COMPANIA  = @COMPANIA,
					@SEDE      = @IDSEDE,
					@PREFIJO   = '@LOG',
					@NVOCONSEC = @NVOCONSEC OUTPUT
        
				SET @CNSLOG = @IDSEDE + RIGHT('00000000' + CAST(@NVOCONSEC AS VARCHAR(8)), 8);
        
				-- Insertar en USLOG (Log principal)
				INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName, TABLA)
				VALUES (
					@CNSLOG,
					@COMPANIA,
					'PERIODO ' + CAST(@ANO AS VARCHAR) + '-' + CAST(@MES AS VARCHAR),
					'CIERRE PERIODO',
					'CIERRE',
					'PERIODO ' + CAST(@ANO AS VARCHAR) + '-' + CAST(@MES AS VARCHAR),
					@USUARIO,
					@FECHA,
					HOST_NAME(),
					'PRI'
				)
        
				-- Insertar en USLOGH (Detalle del log)
				INSERT INTO USLOGH (CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
				VALUES (@CNSLOG, 1, 'PRI:CERRADO', '0', '1')
        
				-- RETORNO EXITOSO
				SELECT 'OK' AS OK,
					   MENSAJE = 'Periodo cerrado exitosamente',
					   ANO = @ANO,
					   MES = @MES,
					   ANOMES = @ANOMES,
					   CNSLOG = @CNSLOG
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al ejecutar el cierre: ' + ERROR_MESSAGE(),
					   ERROR_LINE = ERROR_LINE(),
					   ERROR_PROCEDURE = ERROR_PROCEDURE()
				RETURN
			END CATCH
    
			RETURN
		END
		IF @METODO = 'INICIAR_CIERRE_PERIODO'
		BEGIN
			BEGIN TRY
				DECLARE @JSON_JOB_CIERRE NVARCHAR(MAX);

				SELECT
					@ANO = ANO,
					@MES = MES,
					@COMPANIA = COMPANIA
				FROM OPENJSON(@PARAMETROS)
				WITH (
					ANO INT,
					MES INT,
					COMPANIA VARCHAR(2)
				);

				IF EXISTS (
					SELECT 1
					FROM PROCESO_JOB WITH (NOLOCK)
					WHERE TIPO = N'CIERRE_PERIODO'
					  AND ESTADO IN (N'PENDIENTE', N'PROCESANDO')
					  AND JSON_VALUE(PARAMETROS, '$.ANO') = CAST(@ANO AS VARCHAR(10))
					  AND JSON_VALUE(PARAMETROS, '$.MES') = CAST(@MES AS VARCHAR(10))
					  AND JSON_VALUE(PARAMETROS, '$.COMPANIA') = @COMPANIA
				)
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = N'Ya existe un cierre de periodo en ejecución para el mismo periodo.';
					RETURN;
				END;

				SET @JSON_JOB_CIERRE = (
					SELECT
						'PROCESO_JOB' AS MODELO,
						'INICIAR_JOB' AS METODO,
						@USUARIO AS USUARIO,
						JSON_QUERY((
							SELECT
								'CIERRE_PERIODO' AS TIPO,
								JSON_QUERY(@PARAMETROS) AS PARAMETROS
							FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
						)) AS PARAMETROS
					FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
				);

				EXEC DBO.SPQ_PROCESO_JOB @JSON_JOB_CIERRE;
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK, ERROR = ERROR_MESSAGE();
			END CATCH

			RETURN;
		END
		IF @METODO = 'EJECUTAR_CIERRE_PERIODO_ASYNC'
		BEGIN
			BEGIN TRY
				DECLARE @RESULTADO_CIERRE NVARCHAR(MAX);

				SELECT
					@CNS = CNS,
					@ANO = ANO,
					@MES = MES,
					@COMPANIA = COMPANIA
				FROM OPENJSON(@PARAMETROS)
				WITH (
					CNS VARCHAR(20),
					ANO INT,
					MES INT,
					COMPANIA VARCHAR(2)
				);

				IF COALESCE(@CNS, '') = ''
				BEGIN
					SELECT 'KO' AS OK, ERROR = N'CNS es requerido.';
					RETURN;
				END;

				SET @ANOMES = CAST(@ANO AS VARCHAR(4)) + RIGHT('0' + CAST(@MES AS VARCHAR(2)), 2);

				UPDATE PROCESO_JOB
				SET ESTADO = N'PROCESANDO',
					FECHA_INICIO = COALESCE(FECHA_INICIO, GETDATE())
				WHERE CNS = @CNS;

				SELECT 'OK' AS OK, CNS = @CNS, ESTADO = N'PROCESANDO';

				BEGIN TRY
					PRINT N'Ejecutando SPK_CIERRA_PERIODOCONTABLE (async)...';
					EXEC SPK_CIERRA_PERIODOCONTABLE @ANO, @MES, @USUARIO;

					SELECT @COMPANIA = COMPANIA FROM USUSU WHERE USUARIO = @USUARIO;
					SET @FECHA = GETDATE();
					SELECT @IDSEDE = IDSEDE
					FROM UBEQ
					WHERE SYS_ComputerName = (SELECT SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO);

					EXEC DBO.SPK_GENCONSECUTIVO
						@COMPANIA  = @COMPANIA,
						@SEDE      = @IDSEDE,
						@PREFIJO   = '@LOG',
						@NVOCONSEC = @NVOCONSEC OUTPUT;

					SET @CNSLOG = @IDSEDE + RIGHT('00000000' + CAST(@NVOCONSEC AS VARCHAR(8)), 8);

					INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName, TABLA)
					VALUES (
						@CNSLOG,
						@COMPANIA,
						N'PERIODO ' + CAST(@ANO AS VARCHAR) + N'-' + CAST(@MES AS VARCHAR),
						N'CIERRE PERIODO',
						N'CIERRE',
						N'PERIODO ' + CAST(@ANO AS VARCHAR) + N'-' + CAST(@MES AS VARCHAR),
						@USUARIO,
						@FECHA,
						HOST_NAME(),
						N'PRI'
					);

					INSERT INTO USLOGH (CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
					VALUES (@CNSLOG, 1, N'PRI:CERRADO', N'0', N'1');

					SET @RESULTADO_CIERRE = (
						SELECT
							OK = N'OK',
							MENSAJE = N'Periodo cerrado exitosamente',
							ANO = @ANO,
							MES = @MES,
							ANOMES = @ANOMES,
							CNSLOG = @CNSLOG
						FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
					);

					UPDATE PROCESO_JOB
					SET ESTADO = N'COMPLETADO',
						FECHA_FIN = GETDATE(),
						RESULTADO_JSON = @RESULTADO_CIERRE
					WHERE CNS = @CNS;
				END TRY
				BEGIN CATCH
					UPDATE PROCESO_JOB
					SET ESTADO = N'ERROR',
						FECHA_FIN = GETDATE(),
						ERROR_MESSAGE = ERROR_MESSAGE()
					WHERE CNS = @CNS;
				END CATCH
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK, ERROR = ERROR_MESSAGE();
			END CATCH

			RETURN;
		END
		--PROCESO ABRIR PERIODO
		IF @METODO = 'OBTENER_PERIODO_A_ABRIR'
		BEGIN
			BEGIN TRY
				SELECT @COMPANIA = COMPANIA FROM USUSU WHERE USUARIO = @USUARIO;
				IF @COMPANIA IS NULL
				BEGIN
					SELECT 'KO' AS OK, 'Usuario sin compa??a asignada' AS ERROR;
					RETURN;
				END
			
				IF NOT EXISTS (SELECT 1 FROM PRI WHERE SI=1)
				BEGIN
					SELECT 'KO' AS OK, 'NO EXISTE UN PERIODO DE SALDOS INICIALES' AS ERROR;
					RETURN;
				END

				IF NOT EXISTS (SELECT 1 FROM PRI WHERE COALESCE(CERRADO, 0) = 1)
				BEGIN
					SELECT 'KO' AS OK, 'NO EXISTE PERIODO PENDIENTE POR ABRIR' AS ERROR;
					RETURN;
				END
				
				SELECT TOP 1 
					@ANO = ANO,
					@MES = MES,
					@NOMPERIODO = NOMPERIODO
				FROM PRI 
				WHERE COALESCE(CERRADO, 0) = 1 
				ORDER BY ANO + CASE WHEN MES < 10 THEN '0' + CONVERT(VARCHAR(1), MES) ELSE CONVERT(VARCHAR(2), MES) END DESC;

				IF @ANO IS NULL OR @MES IS NULL
				BEGIN
					SELECT 'KO' AS OK, 'No se pudo obtener el periodo a abrir' AS ERROR;
					RETURN;
				END
				 SELECT 
					'OK' AS OK,
					@ANO AS ANO,
					@MES AS MES,
					@NOMPERIODO AS NOMPERIODO,
					@COMPANIA AS COMPANIA,CONCAT('Periodo ', @NOMPERIODO, ' listo para abrir') AS MENSAJE;
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,ERROR_MESSAGE() AS ERROR;
			END CATCH
		END
		--VALIDAR INTEGRIDAD PARA ABRIR Y CERRAR PERIODOS
		IF @METODO = 'VALIDAR_INTEGRIDAD_PERIODO'
		BEGIN
			DECLARE @EXCLUIR_CIERRE_FISCAL BIT = 0

			BEGIN TRY
				SELECT 
					@ANO = ANO,
					@MES = MES,
					@EXCLUIR_CIERRE_FISCAL = COALESCE(EXCLUIR_CIERRE_FISCAL, 0)
				FROM OPENJSON(@PARAMETROS)
				WITH (
					ANO VARCHAR(4) '$.ANO',
					MES SMALLINT '$.MES',
					EXCLUIR_CIERRE_FISCAL BIT '$.EXCLUIR_CIERRE_FISCAL'
				);
        
				print CONCAT (@ANO,',',@MES)
				
				IF @EXCLUIR_CIERRE_FISCAL = 1
				BEGIN
					SELECT @ERRORES_INTEGRIDAD = COUNT(*)
					FROM DBO.FNK_REVISION_ANTES_CIERRE_PERIODO(@ANO, @MES) R
					WHERE UPPER(COALESCE(R.MODULO, N'')) NOT LIKE N'%CIERRE%FISCAL%'
					  AND UPPER(COALESCE(R.ERROR, N'')) NOT LIKE N'%CIERRE FISCAL%'
					  AND UPPER(COALESCE(R.ERROR, N'')) NOT LIKE N'%CIERRE DE CUENTAS 4,5 Y 6%'
					  AND UPPER(COALESCE(R.ERROR, N'')) NOT LIKE N'%CUENTAS 4,5 Y 6%'
				END
				ELSE
				BEGIN
					SELECT @ERRORES_INTEGRIDAD = COUNT(*)
					FROM DBO.FNK_REVISION_ANTES_CIERRE_PERIODO(@ANO, @MES)
				END

				PRINT 'SALI DE LAS VALIDACION SIN ERRORES'
				IF @ERRORES_INTEGRIDAD > 0
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'Se encontraron ' + CAST(@ERRORES_INTEGRIDAD AS VARCHAR) + ' errores de integridad.',
						   ERRORES_DETALLE = (
							   SELECT MODULO, REFERENCIA, ERROR
							   FROM DBO.FNK_REVISION_ANTES_CIERRE_PERIODO(@ANO, @MES) R
							   WHERE @EXCLUIR_CIERRE_FISCAL = 0
								  OR (
									   UPPER(COALESCE(R.MODULO, N'')) NOT LIKE N'%CIERRE%FISCAL%'
								   AND UPPER(COALESCE(R.ERROR, N'')) NOT LIKE N'%CIERRE FISCAL%'
								   AND UPPER(COALESCE(R.ERROR, N'')) NOT LIKE N'%CIERRE DE CUENTAS 4,5 Y 6%'
								   AND UPPER(COALESCE(R.ERROR, N'')) NOT LIKE N'%CUENTAS 4,5 Y 6%'
								  )
							   FOR JSON PATH
						   )
					RETURN
				END
				
				--Validar traslados 
				IF  DBO.FNK_VALORVARIABLE('CONTABGENTRASLACOSTO') = 'SI' 
				BEGIN
					SELECT 
						@EXISTE_TRASLADO = CIERRE_TRASCOSTOS, @NROCOMPROBANTE = NROCOMTRASCOSTO
					FROM PRI 
					WHERE ANO = @ANO AND MES = @MES;
				END        
				-- Si no hay errores
				SELECT 
					'OK' AS OK,'Todas las validaciones pasaron correctamente' AS MENSAJE,
					COALESCE(@EXISTE_TRASLADO, 0) AS EXISTE_TRASLADO,
					@NROCOMPROBANTE AS NROCOMPROBANTE;
        
			END TRY
			BEGIN CATCH
				SELECT 
					'KO' AS OK,'Error en validaciones: ' + ERROR_MESSAGE() AS ERROR;
			END CATCH
		END
		IF @METODO = 'EJECUTAR_ABRIR_PERIODO'
		BEGIN                
			BEGIN TRY
				SELECT 
					@ANO = ANO,
					@MES = MES,
					@ANULAR_TRASLADO = COALESCE(ANULAR_TRASLADO, 0)
				FROM OPENJSON(@PARAMETROS)
				WITH (
					ANO VARCHAR(4) '$.ANO',
					MES SMALLINT '$.MES',
					ANULAR_TRASLADO BIT '$.ANULAR_TRASLADO'
				);

				SELECT @COMPANIA = COMPANIA FROM USUSU WHERE USUARIO = @USUARIO;
				SET @FECHA = GETDATE();

				SELECT @IDSEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = (SELECT SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO);

				-- Obtener el consecutivo real
				EXEC DBO.SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@LOG', @NVOCONSEC OUTPUT;
				PRINT @NVOCONSEC
				-- CORRECCI?N AQU?: Usar @NVOCONSEC en lugar de '@LOG'
				SET @CNSLOG = @IDSEDE + RIGHT('00000000' + CAST(@NVOCONSEC AS VARCHAR(8)), 8);
				PRINT @CNSLOG
				BEGIN TRANSACTION;
            
					IF @ANULAR_TRASLADO = 1
					BEGIN
						SELECT @NROCOMPROBANTE = NROCOMTRASCOSTO FROM PRI WHERE ANO = @ANO AND MES = @MES;
						IF @NROCOMPROBANTE IS NOT NULL
						BEGIN
							UPDATE MCP SET ANULADO = 1, ESTADO = 0 WHERE NROCOMPROBANTE = @NROCOMPROBANTE;
							UPDATE PRI SET CIERRE_TRASCOSTOS = 0, NROCOMTRASCOSTO = NULL WHERE ANO = @ANO AND MES = @MES;
						END
					END

					EXEC SPK_ABRE_PERIODOCONTABLE @ANO, @MES, @USUARIO;

					-- Mover los INSERTs dentro de la transacci?n para mayor seguridad
					INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName, TABLA)
					VALUES (@CNSLOG, @COMPANIA, CONCAT('PERIODO ', @ANO, '-', @MES), 'ABRIR PERIODO', 'ABRIR', CONCAT('PERIODO ', @ANO, '-', @MES), @USUARIO, @FECHA, (SELECT SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO), 'PRI');
            
					INSERT INTO USLOGH (CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
					VALUES (@CNSLOG, 1, 'PRI:CERRADO', '1', '0');    

				COMMIT TRANSACTION;

				SELECT 
					'OK' AS OK,
					CONCAT('Periodo ', @ANO, '-', @MES, ' abierto exitosamente') AS MENSAJE,
					@ANO AS ANO,
					@MES AS MES;

			END TRY
			BEGIN CATCH
				-- Solo hacer ROLLBACK si hay una transacci?n activa
				IF @@TRANCOUNT > 0
					ROLLBACK TRANSACTION;

				SELECT 
					'KO' AS OK,
					ERROR_MESSAGE() AS ERROR;
			END CATCH
		END
		--Estado de resultado (traer datos, bsucar resultado, tomar fotos) ok
		IF @METODO ='TRAER_DATOS_ER'
		BEGIN
			BEGIN TRY    
				SELECT TOP 1 @PERIODO_ANO = ANO,@PERIODO_MES = MES,	@PERIODO_NOMBRE = NOMPERIODO
				FROM PRI 
				WHERE CERRADO = 0 
				ORDER BY ANO, MES DESC;       
				--Periodos
				IF @PERIODO_ANO IS NULL 
				BEGIN 	
					SELECT TOP 1 @PERIODO_ANO = ANO, @PERIODO_MES = MES, @PERIODO_NOMBRE = NOMPERIODO 	FROM PRI ORDER BY ANO DESC, MES DESC;
				END
				--Cuentas iniciales y finales
				SELECT @CUENTA_INICIAL = MIN(CUE.CUENTA), @CUENTA_FINAL = MAX(CUE.CUENTA)
				FROM CUE 
				INNER JOIN 
				(SELECT MIN(N_INICIAL) NINI, MAX(N_INICIAL) NFIN 
					FROM NTZ WHERE COALESCE(PYG,'NO') <> 'NO') X ON LEFT(CUE.CUENTA,1) >= X.NINI AND LEFT(CUE.CUENTA,1) <= X.NFIN
				WHERE CUE.TIPO = 'Detalle'
				
 				-- CNSPRO DEL LA TABLA TEMPORAL 
				SELECT TOP 1 @PROCESO = (CAST(CNSPRO AS BIGINT) + 1) FROM TBALANCETERFAC  ORDER BY CNSPRO DESC

				
				SELECT 
					'OK' AS OK,
					@PERIODO_ANO AS ANO_INICIAL,
					@PERIODO_MES AS MES_INICIAL,
					@PERIODO_ANO AS ANO_FINAL,
					@PERIODO_MES AS MES_FINAL,
					@PERIODO_NOMBRE AS PERIODO_NOMBRE,
					@CUENTA_INICIAL AS CUENTA_INICIAL,
					@CUENTA_FINAL AS CUENTA_FINAL,
					@PROCESO AS CNSPRO;
        
			END TRY 
			BEGIN CATCH
				SELECT 
					'KO' AS OK,
					ERROR_MESSAGE() AS ERROR;
			END CATCH
		END
		IF @METODO = 'NUEVA_BUSQUEDA_ER'
		BEGIN
			DECLARE @REGISTROS_ELIMINADOS INT
    
			BEGIN TRY
				-- Extraer par?metros
				SELECT @PROCESO = PROCESO
				FROM OPENJSON(@PARAMETROS)
				WITH (PROCESO VARCHAR(20))
        
				IF @PROCESO IS NULL OR @PROCESO = ''
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'El par?metro PROCESO es requerido'
					RETURN
				END
				-- Eliminar registros de TBALANCETERFAC
				DELETE FROM TBALANCETERFAC WHERE CNSPRO = @PROCESO
				SET @REGISTROS_ELIMINADOS = @@ROWCOUNT
        
				-- Retorno exitoso
				SELECT 'OK' AS OK,
					   MENSAJE = 'Registros eliminados correctamente',
					   PROCESO = @PROCESO,
					   REGISTROS_ELIMINADOS = @REGISTROS_ELIMINADOS
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al eliminar registros: ' + ERROR_MESSAGE(),
					   ERROR_LINE = ERROR_LINE()
				RETURN
			END CATCH
    
			RETURN
		END
		IF @METODO = 'BUSCAR_ESTADO_RESULTADOS'
		BEGIN
			BEGIN TRY
				SELECT 	@ANO_INI = ANO_INI, @MES_INI = MES_INI, @ANO_FIN = ANO_FIN, @MES_FIN = MES_FIN, @CTA_INI = CTA_INI, @CTA_FIN = CTA_FIN, @PROCESO = PROCESO 
				FROM OPENJSON(@PARAMETROS)
				WITH (
					ANO_INI INT '$.ANO_INICIAL',
					MES_INI INT '$.MES_INICIAL',
					ANO_FIN INT '$.ANO_FINAL',
					MES_FIN INT '$.MES_FINAL',
					CTA_INI NVARCHAR(10) '$.CUENTA_INICIAL',
					CTA_FIN NVARCHAR(10) '$.CUENTA_FINAL',
					PROCESO VARCHAR(20) '$.CNSPRO'
				);
				PRINT CONCAT('ANTES DEL IF',@PROCESO )
				IF @PROCESO IS NULL OR @PROCESO =''
				BEGIN
					SELECT TOP 1 @PROCESO = (CNSPRO + 1) FROM TBALANCETERFAC  ORDER BY CNSPRO DESC
				END
				
				PRINT @PROCESO
				-- Limpiar la tabla
				DELETE FROM TBALANCETERFAC WHERE CNSPRO = @PROCESO;
				-- Validar par?metros

				IF @ANO_INI IS NULL OR @MES_INI IS NULL OR @ANO_FIN IS NULL OR @MES_FIN IS NULL
				BEGIN
					SELECT 'KO' AS OK, 'Debe especificar los periodos inicial y final' AS ERROR;
					RETURN;
				END
        
				IF @CTA_INI IS NULL OR @CTA_FIN IS NULL
				BEGIN
					SELECT 'KO' AS OK, 'Debe especificar las cuentas inicial y final' AS ERROR;
					RETURN;
				END        
				-- Calcular periodo anterior para acumulado anterior
				IF @MES_INI = 1
				BEGIN
					SELECT @ANO_ANT = @ANO_INI - 1, @MES_ANT = 12;
				END
				ELSE
				BEGIN
					SELECT @ANO_ANT = @ANO_INI, @MES_ANT = @MES_INI - 1;
				END
				print 'Aqui'
				SELECT @COMPANIA = COMPANIA, @IDSEDE = IDSEDE FROM USUSU 	WHERE USUARIO = @USUARIO;
				
				PRINT  CONCAT('ER',',',@PROCESO,',',@ANO_INI,',',@MES_INI,',',@ANO_FIN,',',@MES_FIN,',',@CTA_INI,',',@CTA_FIN,',','1',',','6',',',@COMPANIA,',',@IDSEDE)
				EXEC DBO.SPK_BALANCE 'ER', @PROCESO,@ANO_INI,@MES_INI,@ANO_FIN,@MES_FIN,@CTA_INI,@CTA_FIN,1,6,'','',@COMPANIA,@IDSEDE,'','',0;
        
				-- Devolver resultados principales
				
				SELECT  'OK' AS OK,@PROCESO, CUENTA, NOMCUENTA AS NOMBRE, COALESCE(SI, 0) AS ACUM_ANTERIOR, COALESCE(DB, 0) AS DB, COALESCE(CR, 0) AS CR,
						COALESCE(SF, 0) AS SF, COALESCE(SM, 0) AS MES,  COALESCE(SF, 0) AS ACUMULADO_ACTUAL, TIPO
				FROM TBALANCETERFAC
				WHERE CNSPRO = @PROCESO
					AND TIPO IN ('Detalle', 'Suma','Total_General') 
				ORDER BY CUENTA;
        
				-- Devolver totales en segundo recordset
				 SELECT 
					CASE CUENTA
						WHEN '5' THEN 'GASTOS OPERACIONALES DE ADMINISTRACION'
						WHEN '6' THEN 'COSTOS'
						WHEN '4' THEN 'INGRESOS'
						ELSE CUENTA
					END AS CUENTA,
					COALESCE(SI, 0) AS SI,
					COALESCE(DB, 0) AS DB,
					COALESCE(CR, 0) AS CR,
					COALESCE(SF, 0) AS SF,
					CASE CUENTA
						WHEN '5' THEN 1
						WHEN '6' THEN 2
						WHEN '4' THEN 4
						ELSE 99
					END AS ORDEN
				FROM TBALANCETERFAC
				WHERE CNSPRO = @PROCESO
					AND CUENTA IN ('5', '6', '4')
				UNION ALL
				-- TOTAL CUENTAS DEBITO (Gastos + Costos)
				SELECT 'TOTAL CUENTAS DEBITO' AS CUENTA,SUM(COALESCE(SI, 0)) AS SI,	SUM(COALESCE(DB, 0)) AS DB,	SUM(COALESCE(CR, 0)) AS CR,	SUM(COALESCE(SF, 0)) AS SF,3 AS ORDEN
				FROM TBALANCETERFAC
				WHERE CNSPRO = @PROCESO AND CUENTA IN ('5', '6')
				UNION ALL
				-- TOTAL CUENTAS CREDITO (Ingresos)
				SELECT 	'TOTAL CUENTAS CREDITO' AS CUENTA,COALESCE(SI, 0) AS SI,COALESCE(DB, 0) AS DB,COALESCE(CR, 0) AS CR,COALESCE(SF, 0) AS SF,5 AS ORDEN
				FROM TBALANCETERFAC
				WHERE CNSPRO = @PROCESO AND CUENTA = '4'
				ORDER BY ORDEN;				
        
			END TRY
			BEGIN CATCH				
            
				SELECT 
					'KO' AS OK,
					ERROR_MESSAGE() AS ERROR;
			END CATCH
		END
		IF @METODO = 'TOMAR_FOTO_MES_ER'
		BEGIN
			DECLARE @CNSHIS VARCHAR(11)
			DECLARE @YA_EXISTE INT
    
			BEGIN TRY
				
				SELECT @ANO = ANO,@MES = MES,@CNSPRO = CNSPRO
				FROM OPENJSON(@PARAMETROS)
				WITH (
					ANO INT,
					MES INT,
					CNSPRO VARCHAR(20)
				)
        
				IF @CNSPRO IS NULL OR @CNSPRO = ''
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'El par?metro CNSPRO es requerido'
					RETURN
				END
        
				-- Obtener IDSEDE del usuario
				SELECT @IDSEDE = IDSEDE 
				FROM UBEQ 
				WHERE SYS_ComputerName = (SELECT SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO)
        
				IF @IDSEDE IS NULL
					SET @IDSEDE = '001'
        
				-- Validar si ya existe una foto para este mes        
				IF EXISTS (SELECT 1 FROM TBALANCEH WHERE ANO = @ANO  AND MES = @MES AND CLASEH = 'ESTRES')
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'Ya existe una foto para este mes (' + CAST(@ANO AS VARCHAR) + '-' + RIGHT('0' + CAST(@MES AS VARCHAR), 2) + ')'
					RETURN
				END
        
				-- Validar que existan datos en TBALANCETERFAC con ese CNSPRO
				IF NOT EXISTS (SELECT 1 FROM TBALANCETERFAC WHERE CNSPRO = @CNSPRO)
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'No se encontraron datos para el proceso ' + @CNSPRO
					RETURN
				END
        
				-- Generar consecutivo
				EXEC DBO.SPK_GENCONSECUTIVO
					@COMPANIA  = '01',
					@SEDE      = @IDSEDE,
					@PREFIJO   = '@TBALANCEH',
					@NVOCONSEC = @NVOCONSEC OUTPUT
        
				SET @CNSHIS = @IDSEDE + RIGHT('00000000' + CONVERT(VARCHAR(8), @NVOCONSEC), 8)
        
				-- Insertar snapshot en TBALANCEH
				INSERT INTO TBALANCEH ( CNSPRO, ANO, MES, CUENTA, IDTERCERO, CCOSTO, N_FACTURA, NOMCUENTA, SI, DB, CR, SF, SM, NTZ, TIPO, CLASEH )
				SELECT @CNSHIS,	@ANO,@MES,CUENTA,IDTERCERO,	CCOSTO,	N_FACTURA,	NOMCUENTA,	SI,	DB,	CR,	SF,	SM,	NTZ,TIPO,'ESTRES'
				FROM TBALANCETERFAC
				WHERE CNSPRO = @CNSPRO
        
				-- Retorno exitoso
				SELECT 'OK' AS OK,
					   MENSAJE = 'Foto del mes tomada correctamente',
					   CNSHIS = @CNSHIS,
					   ANO = @ANO,
					   MES = @MES,
					   REGISTROS_INSERTADOS = @@ROWCOUNT
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al tomar la foto del mes: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END
		IF @METODO = 'TOMAR_FOTO_ANO_ER'
		BEGIN
   
			BEGIN TRY
				-- Extraer par?metros
				SELECT 
					@ANO = ANO,
					@CNSPRO = CNSPRO
				FROM OPENJSON(@PARAMETROS)
				WITH (
					ANO INT,
					CNSPRO VARCHAR(20)
				)
        
				IF @CNSPRO IS NULL OR @CNSPRO = ''
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'El par?metro CNSPRO es requerido'
					RETURN
				END
        
				-- Obtener IDSEDE del usuario
				SELECT @IDSEDE = IDSEDE 
				FROM UBEQ 
				WHERE SYS_ComputerName = (SELECT SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO)
        
				IF @IDSEDE IS NULL
					SET @IDSEDE = '001'
        
				-- Validar si ya existe una foto para este a?o (MES=13)
				SELECT @YA_EXISTE = COUNT(*) 
				FROM TBALANCEH 
				WHERE ANO = @ANO 
				  AND MES = 13 
				  AND CLASEH = 'ESTRES'
        
				IF @YA_EXISTE > 0
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'Ya existe una foto para este a?o (' + CAST(@ANO AS VARCHAR) + ')'
					RETURN
				END
        
				-- Validar que existan datos en TBALANCETERFAC con ese CNSPRO
				IF NOT EXISTS (SELECT 1 FROM TBALANCETERFAC WHERE CNSPRO = @CNSPRO)
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'No se encontraron datos para el proceso ' + @CNSPRO
					RETURN
				END
        
				-- Generar consecutivo
				EXEC DBO.SPK_GENCONSECUTIVO
					@COMPANIA  = '01',
					@SEDE      = @IDSEDE,
					@PREFIJO   = '@TBALANCEH',
					@NVOCONSEC = @NVOCONSEC OUTPUT
        
				SET @CNSHIS = @IDSEDE + RIGHT('00000000' + CONVERT(VARCHAR(8), @NVOCONSEC), 8)
        
				-- Insertar snapshot en TBALANCEH con MES=13 para a?o completo
				INSERT INTO TBALANCEH (	CNSPRO, ANO, MES, CUENTA, IDTERCERO, CCOSTO, N_FACTURA, NOMCUENTA, SI, DB, CR, SF, SM, NTZ, TIPO, CLASEH)
				SELECT @CNSHIS,	@ANO,13,CUENTA,IDTERCERO,CCOSTO,N_FACTURA,NOMCUENTA,SI,	DB,	CR,SF,SM,NTZ,TIPO,'ESTRES'
				FROM TBALANCETERFAC
				WHERE CNSPRO = @CNSPRO
        
				-- Retorno exitoso
				SELECT 'OK' AS OK,
					   MENSAJE = 'Foto del a?o tomada correctamente',
					   CNSHIS = @CNSHIS,
					   ANO = @ANO,
					   MES = 13,
					   REGISTROS_INSERTADOS = @@ROWCOUNT
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al tomar la foto del a?o: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END
		--PROCESOS -> CIRCULAR UNICA ok 
		IF @METODO = 'CRUD_CIRUNI'
		BEGIN
			SELECT @REGISTROS = REGISTRO
			FROM OPENJSON(@PARAMETROS)
			WITH (
				REGISTRO NVARCHAR(MAX) AS JSON
			)
			PRINT @REGISTROS
			SET @PROCESO = JSON_VALUE(@REGISTROS, '$.PROCESO')
			PRINT @PROCESO
			PRINT @PARAMETROS
   
			SELECT 	@CNSCIRUNI = CNSCIRUNI,@ANO = ANO,@MES = MES,@CNSPRO = CNSPRO,@OBSERVACION = OBSERVACION
			FROM OPENJSON(@REGISTROS)
			WITH (
				CNSCIRUNI INT '$.CNSCIRUNI',
				ANO INT '$.ano',
				MES INT '$.mes',
				CNSPRO VARCHAR(50) '$.cnspro',
				OBSERVACION VARCHAR(500) '$.observacion'
			)
    
			BEGIN TRY
				-- INSERTAR
				IF UPPER(@PROCESO) = 'INSERTAR'
				BEGIN
					IF EXISTS (SELECT 1 FROM CIRUNI WHERE ANO = @ANO AND MES = @MES)
					BEGIN
						SELECT 'KO' AS OK
						SELECT ERROR = 'Ya existe un registro para el a?o ' + CAST(@ANO AS VARCHAR) + ' y mes ' + CAST(@MES AS VARCHAR)
						RETURN
					END
            
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN						
						INSERT INTO CIRUNI (ANO,MES,FECHA,USUARIO,CNSPRO,OBSERVACION,ESTADO)
						VALUES (@ANO,@MES,GETDATE(),@USUARIO,@CNSPRO,@OBSERVACION,'Nuevo')
					END
				END
				-- EDITAR
				IF UPPER(@PROCESO) = 'EDITAR'
				BEGIN
					IF EXISTS (SELECT 1 FROM CIRUNI WHERE ANO = @ANO AND MES = @MES AND CNSCIRUNI <> @CNSCIRUNI)
					BEGIN
						SELECT 'KO' AS OK
						SELECT ERROR = 'Ya existe otro registro para el a?o ' + CAST(@ANO AS VARCHAR) + ' y mes ' + CAST(@MES AS VARCHAR)
						RETURN
					END
            
					UPDATE CIRUNI
					SET 
						ANO = @ANO,
						MES = @MES,
						CNSPRO = @CNSPRO,
						OBSERVACION = @OBSERVACION,
						USUARIO = @USUARIO,
						FECHA = GETDATE()
					WHERE CNSCIRUNI = @CNSCIRUNI
				END
				-- ELIMINAR
				IF UPPER(@PROCESO) = 'ELIMINAR'
				BEGIN
            
					DELETE FROM CIRUNI WHERE CNSCIRUNI = @CNSCIRUNI
            
					SELECT 'OK' AS OK
					RETURN
				END
        
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
    
			-- Retornar errores si existen
			IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
			BEGIN
				SELECT 'KO' AS OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
    
			-- Todo ok
			SELECT 'OK' AS OK
			RETURN
		END
		IF @METODO = 'GENERAR_CIRCULAR'
		BEGIN
   
			BEGIN TRY
				SELECT 	@CNSCIRUNI = CNSCIRUNI, @GEN_FILE = GEN_FILE
				FROM OPENJSON(@PARAMETROS)
				WITH (
					CNSCIRUNI INT,
					GEN_FILE BIT
				)
        
				-- Validar que existe el registro
				IF NOT EXISTS (SELECT 1 FROM CIRUNI WHERE CNSCIRUNI = @CNSCIRUNI)
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'No existe el registro de circular ?nica con ID: ' + CAST(@CNSCIRUNI AS VARCHAR)
					RETURN
				END
       
				--EXEC DBO.SPK_CIRCULARUNICA @CNSCIRUNI, @GEN_FILE
        
				-- Retorno exitoso
				IF @GEN_FILE = 1
				BEGIN
					PRINT 'DENTRO DE GENFILE1 PARA XML'
					EXEC DBO.SPK_CIRCULARUNICA @CNSCIRUNI, @GEN_FILE
					SELECT 'OK' AS OK,
						   MENSAJE = 'Archivos XML generados exitosamente',
						   CNSCIRUNI = @CNSCIRUNI
				END
				ELSE
				BEGIN
					PRINT ''
					EXEC DBO.SPK_CIRCULARUNICA @CNSCIRUNI
					SELECT 'OK' AS OK,
						   MENSAJE = 'Circular ?nica procesada exitosamente',
						   CNSCIRUNI = @CNSCIRUNI
				END
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al generar circular ?nica: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END
		-- Obtener XML de circular ?nica para exportaci?n en frontend (FTS y GTS)
		IF @METODO = 'OBTENER_CIRCULAR_XML'
		BEGIN
			BEGIN TRY
				SELECT @CNSCIRUNI = CNSCIRUNI
				FROM OPENJSON(@PARAMETROS)
				WITH (CNSCIRUNI INT)

				IF @CNSCIRUNI IS NULL
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'El par?metro CNSCIRUNI es requerido'
					RETURN
				END

				IF NOT EXISTS (SELECT 1 FROM CIRUNI WHERE CNSCIRUNI = @CNSCIRUNI)
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'No existe el registro de circular ?nica con ID: ' + CAST(@CNSCIRUNI AS VARCHAR)
					RETURN
				END

				-- Retorna columnas XML como NVARCHAR para consumo en frontend
				SELECT 
					CNSCIRUNI,
					ANO,
					MES,
					CAST(FT001 AS NVARCHAR(MAX)) AS FT001,
					CAST(FT002 AS NVARCHAR(MAX)) AS FT002,
					CAST(FT003 AS NVARCHAR(MAX)) AS FT003,
					CAST(FT004 AS NVARCHAR(MAX)) AS FT004,
					CAST(FT005 AS NVARCHAR(MAX)) AS FT005,
					CAST(FT006 AS NVARCHAR(MAX)) AS FT006,
					CAST(FT007 AS NVARCHAR(MAX)) AS FT007,
					CAST(FT008 AS NVARCHAR(MAX)) AS FT008,
					CAST(FT009 AS NVARCHAR(MAX)) AS FT009,
					CAST(FT010 AS NVARCHAR(MAX)) AS FT010,
					CAST(GT010 AS NVARCHAR(MAX)) AS GT010
				FROM CIRUNI
				WHERE CNSCIRUNI = @CNSCIRUNI

			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al obtener XML: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
			RETURN
		END
		--parametrizacion -> naturaleza ok
		IF @METODO = 'CRUD_NATURALEZA'
		BEGIN
			 SELECT @REGISTROS = REGISTRO
			FROM OPENJSON(@PARAMETROS)
			WITH (
				REGISTRO NVARCHAR(MAX) AS JSON
			)
    
			-- Extraer PROCESO
			SET @PROCESO = JSON_VALUE(@REGISTROS, '$.PROCESO')
    
			-- Extraer los valores del registro
			SELECT   @N_INICIAL = NINICIAL,  @TIPO = TIPO, @PYG = PYG, @PYGNIIF = PYGNIIF
			FROM OPENJSON(@REGISTROS)
			WITH (
				NINICIAL VARCHAR(2) '$.ninicial',
				TIPO VARCHAR(20) '$.tipo',
				PYG VARCHAR(50) '$.pyg',
				PYGNIIF VARCHAR(50) '$.pygniif'
			)
    
			BEGIN TRY
				IF UPPER(@PROCESO) = 'INSERTAR'
				BEGIN
					IF @N_INICIAL IS NULL OR LTRIM(RTRIM(@N_INICIAL)) = ''
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('N. Inicial es requerido')
					END
            
					IF @TIPO IS NULL OR LTRIM(RTRIM(@TIPO)) = ''
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Tipo es requerido')
					END
            
					-- Validar si ya existe un registro con el mismo N_INICIAL
					IF EXISTS (SELECT 1 FROM NTZ WHERE N_INICIAL = @N_INICIAL)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Ya existe un registro con N. Inicial: ' + @N_INICIAL)
					END
            
					-- Si no hay errores, insertar
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						INSERT INTO NTZ (  N_INICIAL,TIPO,PYG, PYGNIIF)
						VALUES ( @N_INICIAL,@TIPO,@PYG, @PYGNIIF)
					END
				END
        
				-- EDITAR
				IF UPPER(@PROCESO) = 'EDITAR'
				BEGIN
					DECLARE @N_INICIAL_ORIGINAL VARCHAR(2)
            
					SELECT @N_INICIAL_ORIGINAL = JSON_VALUE(@REGISTROS, '$.N_INICIAL')
            
					IF @N_INICIAL IS NULL OR LTRIM(RTRIM(@N_INICIAL)) = ''
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('N. Inicial es requerido')
					END
            
					IF @TIPO IS NULL OR LTRIM(RTRIM(@TIPO)) = ''
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Tipo es requerido')
					END
            
					-- Verificar si ya existe otro registro con el mismo N_INICIAL
					IF EXISTS (SELECT 1 FROM NTZ WHERE N_INICIAL = @N_INICIAL AND N_INICIAL <> @N_INICIAL_ORIGINAL)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Ya existe otro registro con N. Inicial: ' + @N_INICIAL)
					END
            
					-- Si no hay errores, actualizar
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						UPDATE NTZ
						SET 
							N_INICIAL = @N_INICIAL,
							TIPO = @TIPO,
							PYG = @PYG,
							PYGNIIF = @PYGNIIF
						WHERE N_INICIAL = @N_INICIAL_ORIGINAL
					END
				END
        
				-- ELIMINAR
				IF UPPER(@PROCESO) = 'ELIMINAR'
				BEGIN
					SELECT @N_INICIAL = JSON_VALUE(@REGISTROS, '$.N_INICIAL')
            
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						DELETE FROM NTZ WHERE N_INICIAL = @N_INICIAL
					END
				END
        
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
    
			-- Retornar errores si existen
			IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
			BEGIN
				SELECT 'KO' AS OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
    
			-- Todo ok
			SELECT 'OK' AS OK
			RETURN
		END
		--Consultar historicos de balances
		IF @METODO = 'OBTENER_PERIODOS_DISPONIBLES'
		BEGIN
			BEGIN TRY
				-- Retornar per?odos disponibles con formato amigable
				SELECT ANO+CASE WHEN MES<10 THEN '0'+CAST(MES AS VARCHAR(2))ELSE CAST(MES AS VARCHAR(2)) END,CASE WHEN MES<>13 THEN DATENAME(MONTH,CAST('01'+'/'+CAST(MES AS VARCHAR(2))+'/'+ANO AS VARCHAR(10)))+' De '+ANO ELSE 'Todo '+ANO END 
				FROM TBALANCEH  GROUP BY ANO,MES  ORDER BY ANO,MES
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al obtener per?odos: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END
		IF @METODO = 'OBTENER_DATOS_PERIODO'
		BEGIN
			BEGIN TRY
				SET @ANO = JSON_VALUE(@PARAMETROS, '$.ANO')
				SET @MES = JSON_VALUE(@PARAMETROS, '$.MES')
				SET @CLASE = JSON_VALUE(@PARAMETROS, '$.CLASE')
				SET @CUENTA_INICIAL = JSON_VALUE(@PARAMETROS, '$.CUENTA_INICIAL')
				SET @CUENTA_FINAL = JSON_VALUE(@PARAMETROS, '$.CUENTA_FINAL')
				SET @IDTERCERO = JSON_VALUE(@PARAMETROS, '$.IDTERCERO')
				-- Validar par?metros
				IF @ANO IS NULL OR @MES IS NULL
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'Par?metros ANO y MES son requeridos'
					RETURN
				END
  
				SELECT TBA.CNSPRO,TBA.CUENTA,TBA.NOMCUENTA,TBA.IDTERCERO,TER.RAZONSOCIAL,TBA.CCOSTO,TBA.N_FACTURA,TBA.SI,TBA.DB,TBA.CR,	TBA.SM,	TBA.SF,	TBA.CLASEH
				FROM TBALANCEH TBA
				LEFT JOIN VWK_TEXCA TER ON TER.IDTERCERO = TBA.IDTERCERO  
				WHERE TBA.ANO = @ANO 
				  AND TBA.MES = @MES
				  AND (@CLASE IS NULL OR @CLASE = '' OR TBA.CLASEH = @CLASE)
				  AND (@CUENTA_INICIAL IS NULL OR TBA.CUENTA >= @CUENTA_INICIAL)
				  AND (@CUENTA_FINAL IS NULL OR TBA.CUENTA <= @CUENTA_FINAL)
				  AND (@IDTERCERO IS NULL OR TBA.IDTERCERO = @IDTERCERO)
				ORDER BY CUENTA, IDTERCERO
        
			END TRY 
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al obtener datos: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END
		IF @METODO = 'ELIMINAR_FOTO_BALANCE'
		BEGIN
			BEGIN TRY    
				-- Extraer par?metros
				SET @CNSPRO = JSON_VALUE(@PARAMETROS, '$.CNSPRO')
				-- Validar par?metro obligatorio
				IF @CNSPRO IS NULL
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'Par?metro CNSPRO es requerido'
					RETURN
				END
				-- Eliminar registros
				DELETE FROM TBALANCEH WHERE CNSPRO = @CNSPRO
        
				SET @REGISTROS_ELIMINADOS = @@ROWCOUNT
				-- Retornar resultado
				SELECT 'OK' AS OK,
					   MENSAJE = 'Se eliminaron ' + CAST(@REGISTROS_ELIMINADOS AS VARCHAR(10)) + ' registros correctamente',
					   REGISTROS_ELIMINADOS = @REGISTROS_ELIMINADOS
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al eliminar foto: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END
		IF @METODO = 'IMPRIMIR_BPRUEBA'
		BEGIN
			BEGIN TRY
				
				SET @ANO = JSON_VALUE(@PARAMETROS, '$.ANO')
				SET @MES = JSON_VALUE(@PARAMETROS, '$.MES')
				SET @CLASE = JSON_VALUE(@PARAMETROS, '$.CLASE')
				SET @CUENTA_INICIAL = JSON_VALUE(@PARAMETROS, '$.CUENTA_INICIAL')
				SET @CUENTA_FINAL = JSON_VALUE(@PARAMETROS, '$.CUENTA_FINAL')
				SET @IDTERCERO = JSON_VALUE(@PARAMETROS, '$.IDTERCERO')
				        
				-- Validar par?metros
				IF @ANO IS NULL OR @MES IS NULL
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'Par?metros ANO y MES son requeridos'
					RETURN
				END

				SELECT @IDSEDE = IDSEDE 
				FROM UBEQ 
				WHERE SYS_ComputerName = (SELECT SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO)
				 IF @IDSEDE IS NULL
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'No se encontr? IDSEDE para el usuario'
					RETURN
				END

				SELECT 'OK'AS OK,@USUARIO AS USUARIO,CASE WHEN DBO.FNK_VALORVARIABLE('RAZONSOCIALENSEDES')='TER' THEN (SELECT RAZONSOCIAL FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'))ELSE
				COALESCE(SED.DESCRIPCION,TER.RAZONSOCIAL) END RAZONSOCIAL,TER.NIT,TER.DV,COALESCE(SED.DIRECCION,TER.DIRECCION)DIRECCION,COALESCE(SED.TELEFONOS,TER.TELEFONOS)TELEFONOS,
				CIU.NOMBRE CIUDAD,DEP.NOMBRE AS DPTO,COALESCE(SED.EMAIL,TER.EMAIL)EMAIL,SED.CODHABILITA, COALESCE(TER.RAZONSOCIAL,SED.DESCRIPCION) AS RAZONSOCIAL2
				FROM SED INNER JOIN TER ON SED.NIT=TER.NIT
						INNER JOIN CIU ON COALESCE(SED.CIUDAD,TER.CIUDAD)=CIU.CIUDAD
						LEFT  JOIN DEP ON CIU.DPTO=DEP.DPTO
				WHERE IDSEDE=@IDSEDE
  
				SELECT 
					TBA.CUENTA AS CUENTA,
					TBA.NOMCUENTA AS NOMBRECUENTA, 
					TBA.SI AS SALDO_INICIAL,
					TBA.DB AS DEBITO,
					TBA.CR AS CREDITO,	
					TBA.SM AS SALDO_MES,	
					TBA.SF AS SALDO_FINAL	
				FROM TBALANCEH TBA
				WHERE TBA.ANO = @ANO 
				  AND TBA.MES = @MES
				  AND TBA.CUENTA <> 'TOTAL GENERAL'
				  AND (@CLASE IS NULL OR @CLASE = '' OR TBA.CLASEH = @CLASE)
				  AND (@CUENTA_INICIAL IS NULL OR TBA.CUENTA >= @CUENTA_INICIAL)
				  AND (@CUENTA_FINAL IS NULL OR TBA.CUENTA <= @CUENTA_FINAL)
				  AND (@IDTERCERO IS NULL OR TBA.IDTERCERO = @IDTERCERO)
				ORDER BY CUENTA, IDTERCERO


        
			END TRY 
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al obtener datos: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END
		IF @METODO = 'IMPRIMIR_ESTRES'
		BEGIN
			BEGIN TRY      
				-- Extraer par?metros
				SET @ANO = JSON_VALUE(@PARAMETROS, '$.ANO')
				SET @MES = JSON_VALUE(@PARAMETROS, '$.MES')
				SET @CLASE = JSON_VALUE(@PARAMETROS, '$.CLASE')
				SET @CUENTA_INICIAL = JSON_VALUE(@PARAMETROS, '$.CUENTA_INICIAL')
				SET @CUENTA_FINAL = JSON_VALUE(@PARAMETROS, '$.CUENTA_FINAL')
				SET @IDTERCERO = JSON_VALUE(@PARAMETROS, '$.IDTERCERO')
				SET @CNSPRO =  JSON_VALUE(@PARAMETROS, '$.CNSPRO')
        
				-- Validar par?metros obligatorios
				IF @ANO IS NULL OR @MES IS NULL
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'Par?metros ANO y MES son requeridos'
					RETURN
				END
        
				-- Result Set 1: Datos de empresa
				SELECT @IDSEDE = IDSEDE 
				FROM UBEQ 
				WHERE SYS_ComputerName = (SELECT SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO)
				
				IF @IDSEDE IS NULL
				BEGIN
					SELECT 'KO' AS OK,
						   ERROR = 'No se encontr? IDSEDE para el usuario'
					RETURN
				END

				SELECT 'OK'AS OK,@USUARIO AS USUARIO,
					   CASE WHEN DBO.FNK_VALORVARIABLE('RAZONSOCIALENSEDES')='TER' 
							THEN (SELECT RAZONSOCIAL FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'))
							ELSE COALESCE(SED.DESCRIPCION,TER.RAZONSOCIAL) 
					   END RAZONSOCIAL,
					   TER.NIT,
					   TER.DV,
					   COALESCE(SED.DIRECCION,TER.DIRECCION) DIRECCION,
					   COALESCE(SED.TELEFONOS,TER.TELEFONOS) TELEFONOS,
					   CIU.NOMBRE CIUDAD,
					   DEP.NOMBRE AS DPTO,
					   COALESCE(SED.EMAIL,TER.EMAIL) EMAIL,
					   SED.CODHABILITA, 
					   COALESCE(TER.RAZONSOCIAL,SED.DESCRIPCION) AS RAZONSOCIAL2
				FROM SED 
				INNER JOIN TER ON SED.NIT=TER.NIT
				INNER JOIN CIU ON COALESCE(SED.CIUDAD,TER.CIUDAD)=CIU.CIUDAD
				LEFT  JOIN DEP ON CIU.DPTO=DEP.DPTO
				WHERE IDSEDE=@IDSEDE
        
				-- Result Set 2: Datos de cuentas
				SELECT 
					TBA.CUENTA,
					TBA.NOMCUENTA AS NOMBRECUENTA,
					TBA.SM AS SALDO_MES,
					TBA.SF AS SALDO_FINAL,
					TBA.CLASEH
				FROM TBALANCEH TBA
				WHERE TBA.ANO = @ANO 
				  AND TBA.MES = @MES
				  AND (@CLASE IS NULL OR @CLASE = '' OR TBA.CLASEH = @CLASE)
				  AND (@CUENTA_INICIAL IS NULL OR TBA.CUENTA >= @CUENTA_INICIAL)
				  AND (@CUENTA_FINAL IS NULL OR TBA.CUENTA <= @CUENTA_FINAL)
				  AND (@IDTERCERO IS NULL OR TBA.IDTERCERO = @IDTERCERO)
				ORDER BY CUENTA
        
				-- Result Set 3: Totales de cuentas 4, 5, 6
				SELECT '4' AS CUENTA, SM AS SALDO_MES, SF AS SALDO_FINAL 
				FROM TBALANCEH WHERE CNSPRO = @CNSPRO AND CUENTA = '4'
				UNION ALL
				SELECT '5' AS CUENTA, SM AS SALDO_MES, SF AS SALDO_FINAL 
				FROM TBALANCEH WHERE CNSPRO = @CNSPRO AND CUENTA = '5'
				UNION ALL
				SELECT '6' AS CUENTA, SM AS SALDO_MES, SF AS SALDO_FINAL 
				FROM TBALANCEH WHERE CNSPRO = @CNSPRO AND CUENTA = '6'
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al obtener datos: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END
		--procesos generar exogena y cerrar 
		IF @METODO = 'CRUD_GEN_EXOGENA'
		BEGIN
			PRINT @PARAMETROS
			-- Extraer par?metros del JSON
			SET @PROCESO = JSON_VALUE(@PARAMETROS, '$.PROCESO')
			SET @CNSEXOFGE = JSON_VALUE(@PARAMETROS, '$.CNSEXOFGE')
			SET @ANO = JSON_VALUE(@PARAMETROS, '$.ANO')
			SET @MES = JSON_VALUE(@PARAMETROS, '$.MES')
			SET @OBSERVACION = JSON_VALUE(@PARAMETROS, '$.OBSERVACION')
			SET @USUARIO = JSON_VALUE(@PARAMETROS,'$.USUARIO')
			SET @CNSPRO = JSON_VALUE(@PARAMETROS, '$.CNSPRO')
			SET @FECHA_INI = JSON_VALUE(@PARAMETROS, '$.FINICIAL')
			SET @FECHA_FIN = JSON_VALUE(@PARAMETROS, '$.FFINAL')
			SET @ESTADO = JSON_VALUE(@PARAMETROS, '$.ESTADO')
			BEGIN TRY
				PRINT @PROCESO
				BEGIN TRANSACTION
				-- ========== PROCESO: INSERTAR ==========
				IF @PROCESO = 'INSERTAR'
				BEGIN
					print 'entro a insertar'
					-- Validaciones
					IF @ANO IS NULL OR @MES IS NULL 
					BEGIN
						SELECT 'KO' AS OK, 'A?o y mes es requerido' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					IF @MES < 1 OR @MES > 12
					BEGIN
						SELECT 'KO' AS OK, 'El mes debe estar entre 1 y 12' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					-- Validar que el balance existe
					IF @CNSPRO IS NOT NULL  AND  @CNSPRO > 0
					BEGIN
						PRINT'ENTRO AQUI'
						IF NOT EXISTS (SELECT 1 FROM TBALANCEH WHERE CNSPRO = @CNSPRO)
						BEGIN
							SELECT 'KO' AS OK, 'El balance seleccionado no existe' AS ERROR
							ROLLBACK TRANSACTION
							RETURN
						END
					END
					PRINT @USUARIO
					SELECT @COMPANIA= COMPANIA, @IDSEDE =IDSEDE  FROM USUSU WHERE USUARIO = @USUARIO;
					SET @FECHA = GETDATE();
					PRINT CONCAT('COMPA?IOA', @COMPANIA)
					PRINT CONCAT('SEDE', @IDSEDE)

					EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE,'EXOFGE',  @CONSECUTIVO OUTPUT
            
					-- Formato: IDSEDE + Consecutivo (8 d?gitos)
					SET @CNSEXOFGE = RTRIM(@IDSEDE) + RIGHT('00000000' + CAST(@CONSECUTIVO AS VARCHAR), 8)

					PRINT @CNSEXOFGE

					-- Insertar nuevo registro
					INSERT INTO EXOFGE (CNSEXOFGE,ANO,	MES,OBSERVACION,USUARIO,FECHA,ESTADO,CNSPRO,FINICIAL,FFINAL	)
					VALUES (@CNSEXOFGE,	@ANO,@MES,@OBSERVACION,	@USUARIO,GETDATE(),	'Nuevo',@CNSPRO,@FECHA_INI,	@FECHA_FIN)
					SELECT 
						'OK' AS OK, 
						'Registro creado exitosamente' AS MENSAJE,
						@CNSEXOFGE AS CNSEXOFGE
				END
				-- ========== PROCESO: EDITAR ==========
				ELSE IF @PROCESO = 'EDITAR'
				BEGIN
					-- Validaciones
					IF @CNSEXOFGE IS NULL
					BEGIN
						SELECT 'KO' AS OK, 'El consecutivo es requerido' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
           
					IF @MES < 1 OR @MES > 12
					BEGIN
						SELECT 'KO' AS OK, 'El mes debe estar entre 1 y 12' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					-- Validar que el balance existe
					IF @CNSPRO IS NOT NULL  AND  @CNSPRO > 0
					BEGIN
						PRINT'ENTRO AQUI'
						IF NOT EXISTS (SELECT 1 FROM TBALANCEH WHERE CNSPRO = @CNSPRO)
						BEGIN
							SELECT 'KO' AS OK, 'El balance seleccionado no existe' AS ERROR
							ROLLBACK TRANSACTION
							RETURN
						END
					END
					-- Verificar que el registro existe
					IF NOT EXISTS (SELECT 1 FROM EXOFGE WHERE CNSEXOFGE = @CNSEXOFGE)
					BEGIN
						SELECT 'KO' AS OK, 'El registro no existe' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					-- Verificar que no est? cerrado
					IF EXISTS (SELECT 1 FROM EXOFGE WHERE CNSEXOFGE = @CNSEXOFGE AND ESTADO = 'Cerrado')
					BEGIN
						SELECT 'KO' AS OK, 'No se puede editar un registro cerrado' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					-- Validar que no exista otro registro con ese a?o y mes (excepto el actual)
            
					-- Actualizar registro
					UPDATE EXOFGE
					SET 
						ANO = @ANO,
						MES = @MES,
						OBSERVACION = @OBSERVACION,
						CNSPRO = @CNSPRO,
						FINICIAL = @FECHA_INI,
						FFINAL = @FECHA_FIN
					WHERE CNSEXOFGE = @CNSEXOFGE
					SELECT 
						'OK' AS OK, 
						'Registro actualizado exitosamente' AS MENSAJE,
						@CNSEXOFGE AS CNSEXOFGE
				END
				-- ========== PROCESO: ELIMINAR ==========
				ELSE IF @PROCESO = 'ELIMINAR'
				BEGIN
					PRINT 'ENTRE A ELIMINAR'
					-- Validaciones
					IF @CNSEXOFGE IS NULL
					BEGIN
						SELECT 'KO' AS OK, 'El consecutivo es requerido' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					-- Verificar que el registro existe
					IF NOT EXISTS (SELECT 1 FROM EXOFGE WHERE CNSEXOFGE = @CNSEXOFGE)
					BEGIN
						SELECT 'KO' AS OK, 'El registro no existe' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					-- Verificar que no est? cerrado
					IF EXISTS (SELECT 1 FROM EXOFGE WHERE CNSEXOFGE = @CNSEXOFGE AND ESTADO = 'Cerrado')
					BEGIN
						SELECT 'KO' AS OK, 'No se puede eliminar un registro cerrado' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					IF EXISTS (SELECT 1 FROM EXOFGEN WHERE CNSEXOFGE = @CNSEXOFGE)
					BEGIN
						SELECT 'KO' AS OK, 'No se puede eliminar ya tiene registros generados' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END

					-- Eliminar detalles relacionados en EXOFGEN
					PRINT @CNSEXOFGE
					DELETE  FROM EXOFGE WHERE CNSEXOFGE = @CNSEXOFGE
					IF NOT EXISTS (SELECT 1 FROM EXOFGE WHERE CNSEXOFGE = @CNSEXOFGE)
					BEGIN
						SELECT 	'OK' AS OK, 'Registro eliminado exitosamente' AS MENSAJE
					END
					ELSE
					BEGIN
						SELECT 	'KO' AS OK, 'Error al eliminar registro' AS MENSAJE
					END

				END
				ELSE IF @PROCESO = 'CERRAR_EXOGENA'
				BEGIN
					PRINT 'ENTRE A CERRAR EXOGENA '
					-- Validaciones
					IF @CNSEXOFGE IS NULL
					BEGIN
						SELECT 'KO' AS OK, 'El consecutivo es requerido para cerrar' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					-- Verificar que el registro existe
					IF NOT EXISTS (SELECT 1 FROM EXOFGE WHERE CNSEXOFGE = @CNSEXOFGE)
					BEGIN
						SELECT 'KO' AS OK, 'El registro no existe' AS ERROR
						ROLLBACK TRANSACTION
						RETURN
					END
					-- Verificar que ESTE estado nuevo
					IF EXISTS (SELECT 1 FROM EXOFGE WHERE CNSEXOFGE = @CNSEXOFGE AND ESTADO = 'Nuevo')
					BEGIN
						UPDATE EXOFGE
						SET ESTADO ='Cerrado'
						WHERE CNSEXOFGE = @CNSEXOFGE AND ESTADO = 'Nuevo' 
						SELECT 	'OK' AS OK, 'Registro cerrado exitosamente' AS MENSAJE
						
					END
					ELSE
					BEGIN
						SELECT 	'KO' AS OK, 'Error al cerrar registro' AS MENSAJE
					END

				END
				ELSE
				BEGIN
					SELECT 'KO' AS OK, 'Proceso no v?lido' AS ERROR
					ROLLBACK TRANSACTION
					RETURN
				END
				COMMIT TRANSACTION
			END TRY
			BEGIN CATCH
				IF @@TRANCOUNT > 0
					ROLLBACK TRANSACTION
				SELECT 
					'KO' AS OK,
					ERROR_MESSAGE() AS ERROR,
					ERROR_NUMBER() AS ERROR_NUMBER,
					ERROR_LINE() AS ERROR_LINE
			END CATCH
		END
		IF @METODO = 'GENERAR_EXOGENA'
		BEGIN
			SET @CNSEXOFGE = JSON_VALUE(@PARAMETROS, '$.CNSEXOFGE')
			BEGIN TRY
				IF @CNSEXOFGE IS NULL OR @CNSEXOFGE = ''
				BEGIN
					SELECT 'KO' AS OK, 'El consecutivo es requerido' AS ERROR
					RETURN
				END
				SELECT @ESTADO = ESTADO,@CNSPRO = CNSPRO FROM EXOFGE WHERE CNSEXOFGE = @CNSEXOFGE

				IF @ESTADO IS NULL 
				BEGIN
					SELECT 'KO' AS OK, 'El registro no existe' AS ERROR
					RETURN
				END
				-- Validar que el estado sea 'Nuevo'
				IF @ESTADO <> 'Nuevo'
				BEGIN
					SELECT 'KO' AS OK, 'Solo se pueden generar registros con estado Nuevo' AS ERROR
					RETURN
				END
				-- Ejecutar el stored procedure de generaci?n
				EXEC SPK_NC_GENERA_EXOGENA  @CNSEXOFGE, @CNSPRO
				-- Verificar si se generaron datos
				DECLARE @TOTAL_GENERADOS INT
				SELECT @TOTAL_GENERADOS = COUNT(*) 
				FROM EXOFGEN 
				WHERE CNSEXOFGE = @CNSEXOFGE
				IF @TOTAL_GENERADOS > 0
				BEGIN
					SELECT 
						'OK' AS OK, 
						'Informaci?n ex?gena generada exitosamente. Total de registros: ' + CAST(@TOTAL_GENERADOS AS VARCHAR) AS MENSAJE,
						@TOTAL_GENERADOS AS TOTAL_REGISTROS
				END
				ELSE
				BEGIN
					SELECT 
						'OK' AS OK, 
						'Proceso ejecutado pero no se generaron registros. Verifique la configuraci?n de formatos y datos contables.' AS MENSAJE,
						0 AS TOTAL_REGISTROS
				END
			END TRY
			BEGIN CATCH
				SELECT 
					'KO' AS OK,
					ERROR_MESSAGE() AS ERROR,
					ERROR_NUMBER() AS ERROR_NUMBER,
					ERROR_LINE() AS ERROR_LINE
			END CATCH
		END
		IF @METODO = 'EXPORTAR_DATOS_EXOGENA'
		BEGIN  
			SET @CNSEXOFGE = JSON_VALUE(@PARAMETROS, '$.CNSEXOFGE')
			BEGIN TRY
				IF @CNSEXOFGE IS NULL OR @CNSEXOFGE = ''
				BEGIN
					SELECT 'KO' AS OK, 'El consecutivo es requerido' AS ERROR
					RETURN
				END
				-- Verificar que el registro existe
				IF NOT EXISTS (SELECT 1 FROM EXOFGEN WHERE CNSEXOFGE = @CNSEXOFGE)
				BEGIN
					SELECT 'KO' AS OK, 'El registro no datos generados ' AS ERROR
					RETURN
				END
				-- Obtener todos los datos de EXOFGEN sin l?mite de paginaci?n
				SELECT IDFORMATO, IDCONCEPTO, TIPODOC, IDTERCERO, DV, PAPELLIDO, SAPELLIDO, PNOMBRE, 
					SNOMBRE, RAZONSOCIAL, DIRECCION, DPTO, CIUDAD, PAIS, DEBITO, CREDITO, VALOR,
					VALOR1, VALOR2, VALOR3, VALOR4, VALOR5, VALOR6, VALOR7, VALOR8, VALOR9, VALOR10,
					VALOR11, VALOR12, VALOR13, VALOR14, VALOR15, VALOR16, VALOR17, VALOR18, VALOR19, 
					VALOR20,VALOR21, VALOR22, VALOR23, VALOR24, VALOR25, VALOR26, VALOR27, 
					VALOR28, VALOR29, VALOR30, VALOR31, VALOR32
				FROM EXOFGEN
				WHERE CNSEXOFGE = @CNSEXOFGE
				ORDER BY IDFORMATO, IDCONCEPTO, TIPODOC, IDTERCERO
			END TRY
			BEGIN CATCH
				SELECT 
					'KO' AS OK,
					ERROR_MESSAGE() AS ERROR,
					ERROR_NUMBER() AS ERROR_NUMBER,
					ERROR_LINE() AS ERROR_LINE
			END CATCH
		END
		--consultas libros auxiliares
		IF @METODO = 'INICIAR_BUSQUEDA_LIBROS_AUXILIARES'
		BEGIN    
			BEGIN TRY
				-- Obtener IDSEDE
				SELECT @COMPANIA= COMPANIA, @IDSEDE =IDSEDE  FROM USUSU WHERE USUARIO = @USUARIO;
				-- Generar consecutivo ?nico usando SPK_GENCONSECUTIVO
				EXEC DBO.SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@RPDX', @NVOCONSEC OUTPUT
				SET @CNS = @IDSEDE + RIGHT('00000000' + CONVERT(VARCHAR(8), @NVOCONSEC), 8)
				print @cns
				 -- Insertar registro en RPDX_JOBS con estado PENDING
				INSERT INTO RPDX_JOBS (CNS, USUARIO, ESTADO)
				VALUES (@CNS, @USUARIO, 'PENDIENTE')
				  -- RETORNAR CNS INMEDIATAMENTE
				SELECT 'OK' AS OK, CNS = @CNS, ESTADO = 'PENDIENTE'
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK, ERROR = ERROR_MESSAGE()
			END CATCH
    
			RETURN
		END
		IF @METODO = 'EJECUTAR_BUSQUEDA_ASYNC'
		BEGIN
    
			BEGIN TRY
				-- Obtener CNS
				SELECT 
					@CNS= CNS,
					@FECHA_INI = FECHAINI,
					@FECHA_FIN = FECHAFIN,
					@IDTERCEROINI = COALESCE(IDTERCEROINI, ''),
					@IDTERCEROFIN = COALESCE(IDTERCEROFIN, ''),
					@CTA_INI = COALESCE(CUENTAINI, ''),
					@CTA_FIN = COALESCE(CUENTAFIN, ''),
					@CCOSTOINI = COALESCE(CCOSTOINI, ''),
					@CCOSTOFIN = COALESCE(CCOSTOFIN, ''),
					@TIPOMOVIMIENTO = COALESCE(TIPOMOVIMIENTO, 'TO'),
					@DOCUMENTO = COALESCE(DOCUMENTO, ''),
					@CODUNG = COALESCE(CODUNG, ''),
					@CODPRG = COALESCE(CODPRG, ''),
					@SINCIERRE = COALESCE(SINCIERRE, 0),
					@NROCOMPROBANTE = NULLIF(RTRIM(NROCOMPROBANTE), '')
				FROM OPENJSON(@PARAMETROS)
				WITH (
					CNS VARCHAR(20),
					FECHAINI DATETIME,
					FECHAFIN DATETIME,
					IDTERCEROINI VARCHAR(20),
					IDTERCEROFIN VARCHAR(20),
					CUENTAINI VARCHAR(16),
					CUENTAFIN VARCHAR(16),
					CCOSTOINI VARCHAR(20),
					CCOSTOFIN VARCHAR(20),
					TIPOMOVIMIENTO VARCHAR(2),
					DOCUMENTO VARCHAR(20),
					CODUNG VARCHAR(5),
					CODPRG VARCHAR(20),
					SINCIERRE BIT,
					NROCOMPROBANTE  VARCHAR(50) 
				)

				IF @CNS IS NULL
				BEGIN
					SELECT 'KO' AS OK, ERROR = 'CNS es requerido'
					RETURN
				END

				PRINT @CNS

				        -- Construir WHERE
				IF @DOCUMENTO <> ''
					SET @WHERE = ' N_FACTURA = ''' + @DOCUMENTO + ''' AND CODUNG = CASE WHEN ''' + @CODUNG + ''' = ''TODOS'' THEN CODUNG ELSE ''' + @CODUNG + ''' END AND CODPRG = CASE WHEN ''' + @CODPRG + ''' = ''TODOS'' THEN CODPRG ELSE ''' + @CODPRG + ''' END ORDER BY CUENTA, CCOSTO, IDTERCERO, FECHAMOV, N_FACTURA, CODUNG, CODPRG'
				ELSE
					SET @WHERE = ' CODUNG = CASE WHEN ''' + @CODUNG + ''' = ''TODOS'' THEN CODUNG ELSE ''' + @CODUNG + ''' END AND CODPRG = CASE WHEN ''' + @CODPRG + ''' = ''TODOS'' THEN CODPRG ELSE ''' + @CODPRG + ''' END ORDER BY CUENTA, CCOSTO, IDTERCERO, FECHAMOV, N_FACTURA, CODUNG, CODPRG'
        
				IF @TIPOMOVIMIENTO = 'TO'
					SET @WHERE = 'WHERE ' + @WHERE
				ELSE IF @TIPOMOVIMIENTO = 'DB'
					SET @WHERE = 'WHERE DB > 0 AND ' + @WHERE
				ELSE IF @TIPOMOVIMIENTO = 'CR'
					SET @WHERE = 'WHERE CR > 0 AND ' + @WHERE
        
				-- Actualizar a PROCESSING
				UPDATE RPDX_JOBS SET ESTADO = 'PROCESANDO' WHERE CNS = @CNS

				SELECT 'OK' AS OK, CNS = @CNS, ESTADO = 'PROCESANDO'
             
				-- Ejecutar SPK (despu?s de retornar)
				BEGIN TRY
					 PRINT CONCAT('EXEC DBO.NC_SPK_GEN_LIBROAUXILIAR', @FECHA_INI,@FECHA_FIN,@IDTERCEROINI,@IDTERCEROFIN,@CTA_INI,@CTA_FIN,@CCOSTOINI,@CCOSTOFIN,@WHERE,@CNS,@SINCIERRE, @NROCOMPROBANTE)
					EXEC DBO.NC_SPK_GEN_LIBROAUXILIAR @FECHA_INI,@FECHA_FIN,@IDTERCEROINI,@IDTERCEROFIN,@CTA_INI,@CTA_FIN,@CCOSTOINI,@CCOSTOFIN,@WHERE,	@CNS,@SINCIERRE, @NROCOMPROBANTE
					
					IF EXISTS(SELECT 1 FROM RPDX2 WHERE CNS = @CNS )
					BEGIN
						UPDATE RPDX_JOBS SET ESTADO = 'COMPLETADO', FECHA_FIN = GETDATE() WHERE CNS = @CNS
					END
				END TRY
				BEGIN CATCH
					UPDATE RPDX_JOBS 
					SET ESTADO = 'ERROR', FECHA_FIN = GETDATE(), ERROR_MESSAGE = ERROR_MESSAGE()
					WHERE CNS = @CNS
				END CATCH
        
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK, ERROR = ERROR_MESSAGE()
			END CATCH
    
			RETURN
		END
		IF @METODO = 'CONSULTAR_ESTADO_JOB'
		BEGIN
 
			BEGIN TRY
				DECLARE @JSON_CONSULTA_JOB NVARCHAR(MAX);

				SELECT @CNS = CNS
				FROM OPENJSON(@PARAMETROS)
				WITH (CNS VARCHAR(20))
        
				IF @CNS IS NULL
				BEGIN
					SELECT 'KO' AS OK, ERROR = 'CNS es requerido'
					RETURN
				END

				SET @JSON_CONSULTA_JOB = (
					SELECT
						'PROCESO_JOB' AS MODELO,
						'CONSULTAR_ESTADO_JOB' AS METODO,
						@USUARIO AS USUARIO,
						JSON_QUERY((
							SELECT @CNS AS CNS
							FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
						)) AS PARAMETROS
					FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
				);

				EXEC DBO.SPQ_PROCESO_JOB @JSON_CONSULTA_JOB;
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK,
					   ERROR = 'Error al consultar estado: ' + ERROR_MESSAGE()
				RETURN
			END CATCH
    
			RETURN
		END 
		IF @METODO = 'REPORTES_PDF_ACUMULADOS_LIBROS_AUX'
		BEGIN
			--  Leer CNS desde JSON
			SELECT 
				@CNS = CNS, 
				@TIPO_REPORTE = TIPO_REPORTE
			FROM OPENJSON(@PARAMETROS)
			WITH (	CNS VARCHAR(20),
					TIPO_REPORTE VARCHAR(20)
			);
			PRINT @TIPO_REPORTE
			-- 1? SALDO INICIAL POR CUENTA
			SELECT 
				ID1 AS cuenta,
				STRINGMEDIO1 AS razon_social,
				SUM(CASE WHEN VALOR10 = 1 THEN VALOR1 ELSE 0 END) AS saldoInicial
			FROM RPDX2
			WHERE CNS = @CNS
			GROUP BY ID1,STRINGMEDIO1
			ORDER BY ID1
			OPTION (RECOMPILE);
			-- 2? MOVIMIENTOS CON SALDO ACUMULADO
			IF @TIPO_REPORTE = 'TERCERO_AGRUPADO'
			BEGIN
				PRINT 'ENTRO A REPORTE AGRUPADO POR CUENTA Y TERCERO'
				SELECT  ID1 AS cuenta,ID2 AS ccosto,	ID3 AS tercero,	FECHA3 AS fecha,ID4 AS documento,ID5 AS t_comprobante,
					ID6 AS consecutivo,	STRINGMEDIO1 AS razon_social,STRINGMEDIO2 AS nombre_cuenta,	STRINGMEDIO3 AS nombre_ccosto,
					STRINGGRANDE1 AS detalle,VALOR1 AS si,VALOR2 AS debito,	VALOR3 AS credito,
					VALOR4 AS saldo
				FROM RPDX2
				WHERE CNS = @CNS
				ORDER BY ID1, FECHA3, ID4, ID2, ID3
				OPTION (RECOMPILE);
				
			END
			ELSE
			BEGIN
			   SELECT  ID1 AS cuenta,ID2 AS ccosto,	ID3 AS tercero,	FECHA3 AS fecha,ID4 AS documento,ID5 AS t_comprobante,
					ID6 AS consecutivo,	STRINGMEDIO1 AS razon_social,STRINGMEDIO2 AS nombre_cuenta,	STRINGMEDIO3 AS nombre_ccosto,
					STRINGGRANDE1 AS detalle,VALOR1 AS si,VALOR2 AS debito,	VALOR3 AS credito,
					VALOR4 AS saldo
				FROM RPDX2
				WHERE CNS = @CNS
				  AND VALOR10 > 0
				  AND (VALOR2 <> 0 OR VALOR3 <> 0)
				ORDER BY ID1, FECHA3, ID4, ID2, ID3
				OPTION (RECOMPILE); 
			END
			--3 TOTAL GENERAL DEL INFORME
			SELECT
				SUM(CASE WHEN VALOR10 = 1 THEN VALOR1 ELSE 0 END) AS saldoInicialGeneral,
				SUM(VALOR2) AS totalDebitoGeneral,
				SUM(VALOR3) AS totalCreditoGeneral,
				 SUM(
						CASE WHEN VALOR10 = 1 THEN VALOR1 ELSE 0 END
					) + SUM(VALOR2) - SUM(VALOR3) AS saldoFinalGeneral
			FROM RPDX2
			WHERE CNS = @CNS;
			--4. SI TIPO TERCERO ES IGUAL = TERCERO_DOC
			IF @TIPO_REPORTE = 'TERCERO_DOC'
			BEGIN
				 SELECT ID1 AS CUENTA,ID3 AS TERCERO,SUM(VALOR1) AS SALDO_INICIAL_TERCERO, STRINGMEDIO3 AS NOMBRE_CCOTO
				 FROM RPDX2 
				 WHERE CNS =@CNS AND VALOR10 > 0  
				 GROUP BY ID1,ID3,STRINGMEDIO3 
				 ORDER BY ID1,ID3,STRINGMEDIO3 
				 OPTION (RECOMPILE);
			END

			
		END
		--consultas analisis de vencimientos
		IF @METODO = 'ANALISIS_VENCIMIENTO'
		BEGIN
			print @PARAMETROS
			SELECT 
				@ANO = ANO,
				@MES = MES,
				@TIPO_REPORTE = TIPO_REPORTE
			FROM OPENJSON(@PARAMETROS)
			WITH (	
					TIPO_REPORTE VARCHAR(3),
					ANO VARCHAR(5),
					MES VARCHAR(2)
			);
			PRINT @TIPO_REPORTE
			IF @ANO IS NULL OR @MES IS NULL
			BEGIN
				SELECT 'KO' AS OK,ERROR = 'Par?metros ANO y MES son requeridos'
				RETURN
			END
			IF @TIPO_REPORTE IS NULL
			BEGIN
				SELECT 'KO' AS OK,ERROR = 'Par?metros TIPO DE REPORTE es requerido'
				RETURN
			END
			-- Obtener IDSEDE
			SELECT @COMPANIA= COMPANIA, @IDSEDE =IDSEDE  FROM USUSU WHERE USUARIO = @USUARIO;
			-- Generar consecutivo ?nico usando SPK_GENCONSECUTIVO
			EXEC DBO.SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@RPDX', @NVOCONSEC OUTPUT
			SET @CNS = @IDSEDE + RIGHT('00000000' + CONVERT(VARCHAR(8), @NVOCONSEC), 8)
			print @cns
			print @COMPANIA
			print @IDSEDE
			--EXEC SPK_NC_ANAVTO '01','2022','10','0100000654','','','','CXC','','Todos',''
			BEGIN TRY
				EXEC SPK_NC_ANAVTO @COMPANIA,@ANO,@MES,@CNS,@CUENTA_INICIAL,@CUENTA_FINAL,@IDTERCERO,@TIPO_REPORTE,@CCOSTOINI,'Todos',''
				IF (SELECT COUNT(*) FROM RPDX2 WHERE CNS = @CNS) > 0
				BEGIN
					SELECT 'OK' AS OK
					SELECT * FROM RPDX2 WHERE CNS=@CNS
					SELECT 
						SUM(VALOR2) AS DE_0_30,SUM(VALOR3) AS DE_31_60,	SUM(VALOR4) AS DE_61_90,
						SUM(VALOR5) AS DE_91_120,SUM(VALOR7) AS DE_121_150,	SUM(VALOR8) AS DE_151_180,
						SUM(VALOR9) AS DE_181_360,SUM(VALOR1) AS TOTAL_SALDO,SUM(VALOR10) AS MAS_DE_360,
						SUM(VALOR11) AS POR_VENCER
					FROM RPDX2 WHERE CNS=@CNS
				END
			END TRY
			BEGIN CATCH
				SELECT 'KO' AS OK, ERROR = 'NO SE ENCONTRO INFORMACION EN ANALISIS DE VENCIMIENTO'
			END CATCH
		END
		IF @METODO = 'CRUD_KPRES'
		BEGIN
			SELECT @REGISTROS = REGISTRO
			FROM OPENJSON(@PARAMETROS)
			WITH (
				REGISTRO NVARCHAR(MAX) AS JSON
			)
			SET @PROCESO = JSON_VALUE(@REGISTROS, '$.PROCESO')
			-- Extraer los valores del registro
			SELECT 
				@CODPRES = CODPRES,
				@CODPRES_ANT = CODPRES_ANT,
				@DESCRIPCION = DESCRIPCION,
				@CUENTA_UTI = CUENTA_UTI,
				@CUENTA_PER = CUENTA_PER,
				@CUENTA_CIE = CUENTA_CIE,
				@IDFORMATO = IDFORMATO
			FROM OPENJSON(@REGISTROS)
			WITH (
				CODPRES VARCHAR(20) '$.CODPRES',
				DESCRIPCION VARCHAR(60) '$.DESCRIPCION',
				CUENTA_UTI VARCHAR(16) '$.CUENTA_UTI',
				CUENTA_PER VARCHAR(16) '$.CUENTA_PER',
				CUENTA_CIE VARCHAR(16) '$.CUENTA_CIE',
				IDFORMATO VARCHAR(10) '$.IDFORMATO',
				CODPRES_ANT VARCHAR(20) '$.CODPRES_ANT'
			)
			BEGIN TRY 
				-- INSERTAR
				IF UPPER(@PROCESO) = 'INSERTAR'
				BEGIN
					IF @CODPRES IS NULL OR LTRIM(RTRIM(@CODPRES)) = ''
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('C?digo es requerido')
					END
					IF EXISTS (SELECT 1 FROM KPRES WHERE CODPRES = @CODPRES)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Ya existe un registro con C?digo: ' + @CODPRES)
					END
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						INSERT INTO KPRES (CODPRES, DESCRIPCION, CUENTA_UTI, CUENTA_PER, CUENTA_CIE, IDFORMATO)
						VALUES (@CODPRES, @DESCRIPCION, @CUENTA_UTI, @CUENTA_PER, @CUENTA_CIE, @IDFORMATO)
					END
				END
				IF UPPER(@PROCESO) = 'EDITAR'
				BEGIN
					PRINT 'EDITAR'
					print @CODPRES
					PRINT @CODPRES_ANT
					IF @CODPRES IS NULL OR LTRIM(RTRIM(@CODPRES)) = ''
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('C?digo es requerido')
					END
					
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						UPDATE KPRES
						SET 
							CODPRES = @CODPRES,
							DESCRIPCION = @DESCRIPCION,
							CUENTA_UTI = @CUENTA_UTI,
							CUENTA_PER = @CUENTA_PER,
							CUENTA_CIE = @CUENTA_CIE,
							IDFORMATO = @IDFORMATO
						WHERE CODPRES = @CODPRES_ANT
					END
				END
				-- ELIMINAR
				IF UPPER(@PROCESO) = 'ELIMINAR'
				BEGIN
					-- Validar dependencias (Opcional, pero recomendado)
					IF EXISTS (SELECT 1 FROM KPRESD WHERE CODPRES = @CODPRES)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('No se puede eliminar: La agrupaci?n tiene items asociados (KPRESD). Elim?nelos primero.')
					END
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						DELETE FROM KPRES WHERE CODPRES = @CODPRES
					END
				END
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
			IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
			BEGIN
				SELECT 'KO' AS OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			SELECT 'OK' AS OK
			RETURN
		END
		IF @METODO = 'CRUD_KPRESD'
		BEGIN
			SELECT @REGISTROS = REGISTRO
			FROM OPENJSON(@PARAMETROS)
			WITH (
				REGISTRO NVARCHAR(MAX) AS JSON
			)
			SET @PROCESO = JSON_VALUE(@REGISTROS, '$.PROCESO')
			-- Extraer los valores del registro
			SELECT 
				@CODPRES = CODPRES, 
				@ITEM = ITEM,
				@TITULO = TITULO,
				@VARIABLETOTAL = VARIABLETOTAL,
				@TIPO = TIPO,
				@FORMULA = FORMULA,
				@ITEM_ANT = ITEM_ANT
			FROM OPENJSON(@REGISTROS)
			WITH (
				CODPRES VARCHAR(20) '$.CODPRES',
				ITEM INT '$.ITEM',
				TITULO VARCHAR(255) '$.TITULO',
				VARIABLETOTAL VARCHAR(50) '$.VARIABLETOTAL',
				TIPO VARCHAR(20) '$.TIPO',
				FORMULA VARCHAR(1024) '$.FORMULA',
				ITEM_ANT VARCHAR(3) '$.ITEM_ANT'
			)
			BEGIN TRY
				-- INSERTAR
				IF UPPER(@PROCESO) = 'INSERTAR'
				BEGIN
					IF @CODPRES IS NULL 
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('C?digo de presupuesto (CODPRES) es requerido')
					END
					IF @ITEM IS NULL
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Item es requerido')
					END
					IF NOT EXISTS (SELECT 1 FROM KPRES WHERE CODPRES = @CODPRES)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('No existe el codigo en la tabla principal ' + CAST(@CODPRES AS VARCHAR))
					END
					IF EXISTS (SELECT 1 FROM KPRESD WHERE CODPRES = @CODPRES AND ITEM = @ITEM)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Ya existe el Item ' + CAST(@ITEM AS VARCHAR) + ' para el crear grupos ' + @CODPRES)
					END
					-- Si no hay errores, insertar
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						INSERT INTO KPRESD (
							CODPRES, ITEM, TITULO, VARIABLETOTAL, TIPO, FORMULA
						)
						VALUES (
							@CODPRES, @ITEM, @TITULO, @VARIABLETOTAL, @TIPO, @FORMULA
						)
					END
				END
				-- EDITAR
				IF UPPER(@PROCESO) = 'EDITAR'
				BEGIN
					IF @CODPRES IS NULL 
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('C?digo de presupuesto (CODPRES) es requerido')
					END
					IF @ITEM IS NULL
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Item es requerido')
					END
					IF(@ITEM <> @ITEM_ANT)
					BEGIN
						IF EXISTS (SELECT 1 FROM KPRESD WHERE ITEM = @ITEM)
						BEGIN
							INSERT INTO @TBLERRORES(ERROR) VALUES ('Ya existe otro item con el mismo valor')
						END
					END

					-- Si no hay errores, actualizar
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						UPDATE KPRESD
						SET ITEM = @ITEM,
							TITULO = @TITULO,
							VARIABLETOTAL = @VARIABLETOTAL,
							TIPO = @TIPO,
							FORMULA = @FORMULA
						WHERE CODPRES = @CODPRES AND ITEM = @ITEM_ANT
					END
				END
				-- ELIMINAR
				IF UPPER(@PROCESO) = 'ELIMINAR'
				BEGIN
					-- Validar dependencias si necesario (ej. KPRESDR)
					IF EXISTS (SELECT 1 FROM KPRESDR WHERE CODPRES = @CODPRES AND ITEM = @ITEM)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('No se puede eliminar: El item tiene rangos asociados (KPRESDR). Elim?nelos primero.')
					END
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						DELETE FROM KPRESD WHERE CODPRES = @CODPRES AND ITEM = @ITEM
					END
				END
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
			-- Retornar errores si existen
			IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
			BEGIN
				SELECT 'KO' AS OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			-- Todo ok
			SELECT 'OK' AS OK
			RETURN
		END
		IF @METODO = 'CRUD_KPRESDR'
		BEGIN
			DECLARE @TITULO_ANT VARCHAR(60);
			SELECT @REGISTROS = REGISTRO
			FROM OPENJSON(@PARAMETROS)
			WITH (
				REGISTRO NVARCHAR(MAX) AS JSON
			)
			SET @PROCESO = JSON_VALUE(@REGISTROS, '$.PROCESO')
			
			-- Extraer los valores del registro
			SELECT 
				@CODPRES = CODPRES, 
				@ITEM = ITEM,
				@TITULO = TITULO,
				@CUENTA_INICIAL = CUENTAINI,
				@CUENTA_FINAL = CUENTAFIN,
				@VARIABLETOTAL = VARIABLETOTAL,
				@CORRIENTE = CASE WHEN CORRIENTE = 1 THEN 1 ELSE 0 END,
				@CONORDEN = ORDEN,
				@TITULO_ANT = TITULO_ANT
			FROM OPENJSON(@REGISTROS)
			WITH (
				CODPRES VARCHAR(20) '$.CODPRES',
				ITEM INT '$.ITEM',
				TITULO VARCHAR(60) '$.TITULO',
				TITULO_ANT VARCHAR(60) '$.TITULO_ANT',
				CUENTAINI VARCHAR(16) '$.CUENTAINI',
				CUENTAFIN VARCHAR(16) '$.CUENTAFIN',
				VARIABLETOTAL VARCHAR(20) '$.VARIABLETOTAL',
				CORRIENTE INT '$.CORRIENTE',
				ORDEN INT '$.ORDEN'
			)  
			BEGIN TRY
				-- INSERTAR
				IF UPPER(@PROCESO) = 'INSERTAR'
				BEGIN
					IF @CODPRES IS NULL
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('C?digo de presupuesto (CODPRES) es requerido')
					END
					IF @ITEM IS NULL
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Item es requerido')
					END
					IF @VARIABLETOTAL IS NULL 
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Totalizar es requerido')
					END
					IF @TITULO IS NULL OR @TITULO = ''
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('T?tulo es requerido')
					END
					IF EXISTS (SELECT 1 FROM KPRESDR WHERE CODPRES = @CODPRES AND ITEM = @ITEM AND TITULO = @TITULO)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Ya existe un rango con el T?tulo: ' + @TITULO)
					END
			
					-- Si no hay errores, insertar
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						INSERT INTO KPRESDR (
							CODPRES, ITEM, TITULO, CUENTAINI, CUENTAFIN, VARIABLETOTAL, CORRIENTE, ORDEN
						)
						VALUES (
							@CODPRES, @ITEM, @TITULO, @CUENTA_INICIAL, @CUENTA_FINAL, @VARIABLETOTAL, @CORRIENTE, @CONORDEN
						)
					END
				END
				-- EDITAR
				IF UPPER(@PROCESO) = 'EDITAR'
				BEGIN
					IF @TITULO_ANT IS NULL SET @TITULO_ANT = @TITULO
					IF EXISTS (SELECT 1 FROM KPRESDR WHERE CODPRES = @CODPRES AND ITEM = @ITEM AND TITULO = @TITULO AND TITULO <> @TITULO_ANT)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('Ya existe otro rango con el T?tulo: ' + @TITULO)
					END
					IF NOT EXISTS (SELECT 1 FROM KPRESDR WHERE CODPRES = @CODPRES AND ITEM = @ITEM AND TITULO = @TITULO_ANT)
					BEGIN
						INSERT INTO @TBLERRORES(ERROR) VALUES ('No existe el registro para actualizar')
					END
					-- Si no hay errores, actualizar
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						UPDATE KPRESDR
						SET 
							TITULO = @TITULO,
							CUENTAINI = @CUENTA_INICIAL,
							CUENTAFIN = @CUENTA_FINAL,
							VARIABLETOTAL = @VARIABLETOTAL,
							CORRIENTE = @CORRIENTE,
							ORDEN = @CONORDEN
						WHERE CODPRES = @CODPRES AND ITEM = @ITEM AND TITULO = @TITULO_ANT
					END
				END
				-- ELIMINAR
				IF UPPER(@PROCESO) = 'ELIMINAR'
				BEGIN
					IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
					BEGIN
						DELETE FROM KPRESDR WHERE CODPRES = @CODPRES AND ITEM = @ITEM AND TITULO = @TITULO
					END
				END
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
			-- Retornar errores si existen
			IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
			BEGIN
				SELECT 'KO' AS OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			-- Todo ok
			SELECT 'OK' AS OK
			RETURN
		END
END

