CREATE OR ALTER PROC DBO.SPQ_VALIDADIAN2
	@IDSEDE VARCHAR(5), 
	@CCOSTO VARCHAR(20),
	@CONTINUA SMALLINT  = 1 OUTPUT,
	@CANTIDAD INT = 1
WITH ENCRYPTION
AS
DECLARE @SALIDA INT
DECLARE @CNSFINAL VARCHAR(20), @DIASFALTAN INT, @CNSRESOL VARCHAR(50), @FECHAVEN DATETIME, @FECHAVENCERT DATETIME
DECLARE @CNSFINAL_INT INT, @ULTIMO_REQUERIDO INT
BEGIN
	SET @CONTINUA = 1
	IF COALESCE(@CANTIDAD, 0) <= 0 SET @CANTIDAD = 1

	EXEC SPK_PROXIMONUMEROFACTURA '01', @IDSEDE, @CCOSTO , @SALIDA OUTPUT 
	PRINT '@SALIDA='+STR(@SALIDA)

	IF UPPER(dbo.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI' 
	BEGIN
		IF UPPER(DBO.FNK_VALORVARIABLE('FACTSEDE'))='SI'
		BEGIN
			SELECT @CNSFINAL = CNSFINAL, @FECHAVEN=FECHAVEN, @CNSRESOL=CNSRESOL, @DIASFALTAN = DATEDIFF(DAY,GETDATE(),FECHAVEN) FROM FDIAN 
			WHERE  IDENTIFICADOR = @IDSEDE 
			AND    CNSINICIAL   <= @SALIDA 
			AND    CNSFINAL+1    > @SALIDA  
			AND    COALESCE(VENCIDA,0) = 0
			AND    PROCEDENCIA   = 'FTR'
		END
		ELSE
		BEGIN
			SELECT @CNSFINAL = CNSFINAL, @FECHAVEN=FECHAVEN, @CNSRESOL=CNSRESOL, @DIASFALTAN = DATEDIFF(DAY,GETDATE(),FECHAVEN) FROM FDIAN 
			WHERE  IDENTIFICADOR = DBO.FNK_VALORVARIABLE('IDSEDEPRINCIPAL')
			AND    CNSINICIAL   <= @SALIDA 
			AND    CNSFINAL+1    > @SALIDA
			AND    COALESCE(VENCIDA,0) = 0 
			AND    PROCEDENCIA   = 'FTR'
		END
		IF COALESCE(@CNSFINAL, '') = ''
		BEGIN
			SELECT @CNSFINAL=CNSFINAL, @FECHAVEN=FECHAVEN, @CNSRESOL=CNSRESOL,@DIASFALTAN=DATEDIFF(DAY,GETDATE(),FECHAVEN) FROM FDIAN 
			WHERE  CNSINICIAL  <= @SALIDA
			AND    CNSFINAL+1   > @SALIDA
			AND    COALESCE(VENCIDA,0) = 0 
			AND    PROCEDENCIA  = 'FTR'
			IF COALESCE(@CNSFINAL, '') = ''
			BEGIN
				SELECT @CONTINUA = 3
			END
		END
		IF @CONTINUA <> 3
		BEGIN
			SET @CNSFINAL_INT = TRY_CAST(@CNSFINAL AS INT)
			SET @ULTIMO_REQUERIDO = @SALIDA + @CANTIDAD - 1

			IF @SALIDA > @CNSFINAL_INT
			BEGIN
				SELECT @CONTINUA=0
				UPDATE FDIAN SET VENCIDA = 1 WHERE CNSRESOL = @CNSRESOL
			END
			ELSE IF @ULTIMO_REQUERIDO > @CNSFINAL_INT
			BEGIN
				SELECT @CONTINUA=6
			END
			ELSE
			BEGIN
				IF @FECHAVEN < GETDATE()+1
				BEGIN
					SELECT @CONTINUA=2
					UPDATE FDIAN SET VENCIDA = 1 WHERE  CNSRESOL = @CNSRESOL
				END
			END
		END

		PRINT 'CONTINUA=' + CAST(@CONTINUA AS VARCHAR)
		IF(@CONTINUA=1)
		BEGIN				
			SELECT @FECHAVENCERT=FECHA1 FROM TGEN WHERE TABLA = 'FDIAN' AND CAMPO = 'SOFTWARE' AND CODIGO = 'FVCERTIFICADO'
	
			DECLARE @ALERTA_RESOL BIT = 0, @ALERTA_CERT BIT = 0

			IF @DIASFALTAN <= 30 SET @ALERTA_RESOL = 1

			IF DATEDIFF(DAY, GETDATE(), @FECHAVENCERT) <= 30 SET @ALERTA_CERT = 1

			IF @ALERTA_RESOL = 1 AND @ALERTA_CERT = 1
				SET @CONTINUA = 9
			ELSE IF @ALERTA_RESOL = 1
				SET @CONTINUA = 4
			ELSE IF @ALERTA_CERT = 1
				SET @CONTINUA = 5
		END
	END
END

