CREATE OR ALTER PROCEDURE DBO.SPQ_FACT_MASI_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@IDAUT VARCHAR(20)                 ,@CNSFACT  VARCHAR(20)

BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='MARCAR_AUT'     
   BEGIN         
      SELECT @IDAUT=IDAUT,@CNSFACT=CNSFACT      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      IDAUT VARCHAR(20) '$.IDAUT',
      CNSFACT  VARCHAR(20)   '$.CNSFACT'
      )
      IF COALESCE(@CNSFACT,'')=''
		BEGIN
         IF EXISTS(SELECT * FROM TGEN WHERE TABLA='FTRUSUMARCA' AND CAMPO=@USUARIO)
         BEGIN
            PRINT 'BUSCO EL CNS'
            SELECT @CNSFACT=COALESCE(CODIGO,'') FROM TGEN WHERE TABLA='FTRUSUMARCA' AND CAMPO=@USUARIO
         END
         ELSE
         BEGIN
            BEGIN TRY           
			      SELECT @CNSFACT=''
			      SELECT @COMPANIA='01', @IDSEDE=IDSEDE FROM USUSU WHERE USUARIO=@USUARIO
			      EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSFACT OUTPUT  
			      SELECT @CNSFACT = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFACT))+LTRIM(RTRIM(@CNSFACT)),SPACE(1),0) 
               
               INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
               SELECT 'FTRUSUMARCA',@USUARIO,@CNSFACT,'Cnsfactura masiva'

               SELECT * FROM TGEN WHERE TABLA='FTRUSUMARCA' AND CAMPO=@USUARIO
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH 
         END
		END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      BEGIN TRY           
          UPDATE AUT SET MARCAFAC=1-COALESCE(MARCAFAC,0),CNSFACT=CASE WHEN COALESCE(MARCAFAC,0)=0 THEN @CNSFACT ELSE NULL END WHERE IDAUT=@IDAUT               
      END TRY
      BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,@CNSFACT CNSFACT
      SELECT ROW_NUMBER() OVER(ORDER  BY IDAUT  DESC)ID, IDAUT,DOCIDAFILIADO,NOMBREAFI,IDAUT,PREFIJO,NOM_PREFIJO, VALORTOTAL  ,MARCAFAC,CNSFACT
      FROM VWK_AUT_FTR WHERE MARCAFAC=1 AND CNSFACT=@CNSFACT
      RETURN 
   END  
   IF @METODO='VALIDAR_MARCA'     
   BEGIN         
      SELECT @CNSFACT =CNSFACT
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSFACT  VARCHAR(20)   '$.CNSFACT'
      )

      IF COALESCE(@CNSFACT,'')=''
		BEGIN
         IF EXISTS(SELECT * FROM TGEN WHERE TABLA='FTRUSUMARCA' AND CAMPO=@USUARIO)
         BEGIN
            PRINT 'BUSCO EL CNS'
            SELECT @CNSFACT=COALESCE(CODIGO,'') FROM TGEN WHERE TABLA='FTRUSUMARCA' AND CAMPO=@USUARIO
         END
      END

      IF COALESCE(@CNSFACT,'')<>''
      BEGIN
         SELECT 'OK' OK,@CNSFACT CNSFACT
         SELECT ROW_NUMBER() OVER(ORDER  BY IDAUT  DESC)ID, IDAUT,DOCIDAFILIADO,NOMBREAFI,IDAUT,PREFIJO,NOM_PREFIJO, VALORTOTAL  ,MARCAFAC,CNSFACT
         FROM VWK_AUT_FTR WHERE MARCAFAC=1 AND CNSFACT=@CNSFACT
         RETURN 
      END              
   END  
END

