CREATE OR ALTER PROCEDURE DBO.SPQ_IACTR @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @DATOS VARCHAR(MAX)
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @IDSEDE VARCHAR(5), @PROCESO VARCHAR(20)
DECLARE @IDACTIVO VARCHAR(20), @ITEM SMALLINT, @IDTERCERO VARCHAR(20), @FECHAASIG DATETIME, @FECHARET DATETIME
DECLARE @SYS_COMPUTERNAME VARCHAR(254), @ESTADO VARCHAR(12), @VALIDADO VARCHAR(2), @OBSERVACION VARCHAR(255)
DECLARE @ESTAEQUI VARCHAR(10), @USO_BASI VARCHAR(10), @ALMACENA VARCHAR(10), @REVI_ACCESO VARCHAR(10), @MANUALES VARCHAR(10)
DECLARE @CARGO VARCHAR(20)

BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME
	FROM USUSU
	WHERE USUARIO = @USUARIO

	IF @METODO = 'GUARDAR'
	BEGIN
		BEGIN TRY
			SELECT @PROCESO = PROCESO, @IDACTIVO = IDACTIVO, @ITEM = ITEM, @IDTERCERO = IDTERCERO, @FECHAASIG = FECHAASIG, @FECHARET = FECHARET, @ESTADO = ESTADO, @VALIDADO 
				= VALIDADO, @OBSERVACION = OBSERVACION, @ESTAEQUI = ESTAEQUI, @USO_BASI = USO_BASI, @ALMACENA = ALMACENA, @REVI_ACCESO = REVI_ACCESO, @MANUALES = 
				MANUALES, @CARGO = CARGO
			FROM OPENJSON(@PARAMETROS) WITH (
					IDACTIVO VARCHAR(20) '$.IDACTIVO', ITEM SMALLINT '$.ITEM', IDTERCERO VARCHAR(20) '$.IDTERCERO', FECHAASIG DATETIME '$.FECHAASIG', FECHARET 
					DATETIME '$.FECHARET', USUARIO VARCHAR(12) '$.USUARIO', SYS_COMPUTERNAME VARCHAR(254) '$.SYS_COMPUTERNAME', ESTADO VARCHAR(12) '$.ESTADO', 
					VALIDADO VARCHAR(2) '$.VALIDADO', OBSERVACION VARCHAR(255) '$.OBSERVACION', ESTAEQUI VARCHAR(10) '$.ESTAEQUI', USO_BASI VARCHAR(10) 
					'$.USO_BASI', ALMACENA VARCHAR(10) '$.ALMACENA', REVI_ACCESO VARCHAR(10) '$.REVI_ACCESO', MANUALES VARCHAR(10) '$.MANUALES', CARGO VARCHAR(20
					) '$.CARGO', PROCESO VARCHAR(20) '$.PROCESO'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL ITEM ', @ITEM, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM IACTR
							WHERE IDACTIVO = @IDACTIVO AND IDTERCERO = @IDTERCERO AND ITEM = @ITEM
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						INSERT INTO [IACTR] (
							[IDACTIVO], [ITEM], [IDTERCERO], [FECHAASIG], [FECHARET], [USUARIO], [SYS_COMPUTERNAME], [FECHAMOV], [ESTADO], [VALIDADO], 
							[OBSERVACION], [ESTAEQUI], [USO_BASI], [ALMACENA], [REVI_ACCESO], [MANUALES], [CARGO]
							)
						SELECT @IDACTIVO, @ITEM, @IDTERCERO, @FECHAASIG, @FECHARET, @USUARIO, @SYS_COMPUTERNAME, GETDATE(), @ESTADO, @VALIDADO, @OBSERVACION, '', 
							@USO_BASI, @ALMACENA, @REVI_ACCESO, @MANUALES, @CARGO
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL EMPLEADO ', @IDTERCERO, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM IACTR
							WHERE IDACTIVO = @IDACTIVO AND IDTERCERO = @IDTERCERO AND ITEM <> @ITEM
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						UPDATE IACTR
						SET IDTERCERO = @IDTERCERO, FECHAASIG = @FECHAASIG, FECHARET = @FECHARET, USUARIO = @USUARIO, SYS_COMPUTERNAME = @SYS_COMPUTERNAME, ESTADO = 
							@ESTADO, VALIDADO = @VALIDADO, OBSERVACION = @OBSERVACION, ESTAEQUI = @ESTAEQUI, USO_BASI = @USO_BASI, ALMACENA = @ALMACENA, REVI_ACCESO = 
							@REVI_ACCESO, MANUALES = @MANUALES, CARGO = @CARGO, FECHAMOV = GETDATE()
						WHERE IDACTIVO = @IDACTIVO AND ITEM = @ITEM
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'ELIMINAR'
	BEGIN
		SELECT @IDACTIVO = IDACTIVO, @IDTERCERO = IDTERCERO, @ITEM = ITEM
		FROM OPENJSON(@PARAMETROS) WITH (IDACTIVO VARCHAR(20) '$.IDACTIVO', IDTERCERO VARCHAR(20) '$.IDTERCERO', ITEM SMALLINT '$.ITEM')

		BEGIN TRY
			DELETE
			FROM IACTR
			WHERE IDACTIVO = @IDACTIVO AND IDTERCERO = @IDTERCERO AND ITEM = @ITEM
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'RETIRAR'
	BEGIN
		SELECT @IDACTIVO = IDACTIVO, @IDTERCERO = IDTERCERO, @ITEM = ITEM
		FROM OPENJSON(@PARAMETROS) WITH (IDACTIVO VARCHAR(20) '$.IDACTIVO', IDTERCERO VARCHAR(20) '$.IDTERCERO', ITEM SMALLINT '$.ITEM')

		BEGIN TRY
			UPDATE IACTR
			SET FECHAMOV = GETDATE(), FECHARET = GETDATE(), SYS_COMPUTERNAME = @SYS_COMPUTERNAME, USUARIO = @USUARIO, ESTADO = 'Retirado'
			WHERE IDACTIVO = @IDACTIVO AND IDTERCERO = @IDTERCERO AND ITEM = @ITEM
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END
END


