CREATE OR ALTER PROCEDURE DBO.SPQ_TIPOAF @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @IDSEDE VARCHAR(5)
DECLARE @PROCESO VARCHAR(20), @IDTIPOACTIVO VARCHAR(20), @DESCRIPCION VARCHAR(1000), @ESTADO VARCHAR(16), @PIDEMODELO VARCHAR(2), @PIDEMARCA VARCHAR(2), 
	@PIDESERIAL VARCHAR(2), @PIDEREFERENCIA VARCHAR(2), @PIDENOESCRITURA VARCHAR(2), @PIDELINDEROS VARCHAR(2), @PIDENOPARTES VARCHAR(2), @PIDEMATRICULA VARCHAR(2
	), @VIDAUTIL SMALLINT, @BASEDEPRECIABLE DECIMAL(14, 0), @TIPOSALV VARCHAR(10), @TIPOVIDA VARCHAR(10), @CLASE VARCHAR(10), @DATOS VARCHAR(MAX), 
	@IDTIPOACTIVOEDITE VARCHAR(20), @IDACTIVO VARCHAR(20), @DEPRECIABLE SMALLINT, @CODIGO VARCHAR(20), @OPCIONESLIBRES INT, @IDTGEN INT

BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	IF @METODO = 'GUARDAR'
	BEGIN
		BEGIN TRY
			SELECT @PROCESO = PROCESO, @IDTIPOACTIVO = IDTIPOACTIVO, @DESCRIPCION = DESCRIPCION, @ESTADO = ESTADO, @PIDEMODELO = PIDEMODELO, @PIDEMARCA = PIDEMARCA, 
				@PIDESERIAL = PIDESERIAL, @PIDEREFERENCIA = PIDEREFERENCIA, @PIDENOESCRITURA = PIDENOESCRITURA, @PIDELINDEROS = PIDELINDEROS, @PIDENOPARTES = 
				PIDENOPARTES, @PIDEMATRICULA = PIDEMATRICULA, @VIDAUTIL = VIDAUTIL, @BASEDEPRECIABLE = BASEDEPRECIABLE, @TIPOSALV = TIPOSALV, @TIPOVIDA = TIPOVIDA, 
				@CLASE = CLASE
			FROM OPENJSON(@PARAMETROS) WITH (
					PROCESO VARCHAR(20) '$.PROCESO', IDTIPOACTIVO VARCHAR(20) '$.IDTIPOACTIVO', DESCRIPCION VARCHAR(100) '$.DESCRIPCION', ESTADO VARCHAR(16) 
					'$.ESTADO', PIDEMODELO VARCHAR(2) '$.PIDEMODELO', PIDEMARCA VARCHAR(2) '$.PIDEMARCA', PIDESERIAL VARCHAR(2) '$.PIDESERIAL', PIDEREFERENCIA 
					VARCHAR(2) '$.PIDEREFERENCIA', PIDENOESCRITURA VARCHAR(2) '$.PIDENOESCRITURA', PIDELINDEROS VARCHAR(2) '$.PIDELINDEROS', PIDENOPARTES 
					VARCHAR(2) '$.PIDENOPARTES', PIDEMATRICULA VARCHAR(2) '$.PIDEMATRICULA', VIDAUTIL SMALLINT '$.VIDAUTIL', BASEDEPRECIABLE DECIMAL(14, 0) 
					'$.BASEDEPRECIABLE', TIPOSALV VARCHAR(10) '$.TIPOSALV', TIPOVIDA VARCHAR(10) '$.TIPOVIDA', CLASE VARCHAR(10) '$.CLASE'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL ID ', @IDTIPOACTIVO, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM IACTT
							WHERE IDTIPOACTIVO = @IDTIPOACTIVO
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						INSERT INTO IACTT (
							IDTIPOACTIVO, DESCRIPCION, ESTADO, CUENTA, PIDEMODELO, PIDEMARCA, PIDESERIAL, PIDEREFERENCIA, PIDENOESCRITURA, PIDELINDEROS, 
							PIDENOPARTES, PIDEMATRICULA, CODIGOGASTODEP, DEPRECIACION, CUENTAAJINFLACION, VIDAUTIL, BASEDEPRECIABLE, TIPOSALV, TIPOVIDA, CLASE
							)
						SELECT @IDTIPOACTIVO, @DESCRIPCION, @ESTADO, '', @PIDEMODELO, @PIDEMARCA, @PIDESERIAL, @PIDEREFERENCIA, @PIDENOESCRITURA, @PIDELINDEROS, 
							@PIDENOPARTES, @PIDEMATRICULA, '', '', '', @VIDAUTIL, @BASEDEPRECIABLE, @TIPOSALV, @TIPOVIDA, @CLASE
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					SELECT @DATOS = DATOS
					FROM OPENJSON(@PARAMETROS) WITH (DATOS NVARCHAR(MAX) AS JSON)

					SELECT @IDTIPOACTIVOEDITE = IDTIPOACTIVOEDITE
					FROM OPENJSON(@DATOS) WITH (IDTIPOACTIVOEDITE VARCHAR(20) '$.IDTIPOACTIVOEDITE')

					IF (@IDTIPOACTIVOEDITE <> @IDTIPOACTIVO)
					BEGIN
						INSERT INTO @TBLERRORES (ERROR)
						SELECT CONCAT ('EL CODIGO ', @IDTIPOACTIVO, ' YA SE ENCUENTRA REGISTRADO')
						WHERE EXISTS (
								SELECT 1
								FROM IACTT
								WHERE IDTIPOACTIVO = @IDTIPOACTIVO
								)

						IF (
								SELECT COUNT(*)
								FROM @TBLERRORES
								) <= 0
						BEGIN
							UPDATE IACTT
							SET IDTIPOACTIVO = @IDTIPOACTIVO, DESCRIPCION = @DESCRIPCION, ESTADO = @ESTADO, PIDEMODELO = @PIDEMODELO, PIDEMARCA = @PIDEMARCA, 
								PIDESERIAL = @PIDESERIAL, PIDEREFERENCIA = @PIDEREFERENCIA, PIDENOESCRITURA = @PIDENOESCRITURA, PIDELINDEROS = @PIDELINDEROS, 
								PIDENOPARTES = @PIDENOPARTES, PIDEMATRICULA = @PIDEMATRICULA, VIDAUTIL = @VIDAUTIL, BASEDEPRECIABLE = @BASEDEPRECIABLE, TIPOSALV = 
								@TIPOSALV, TIPOVIDA = @TIPOVIDA, CLASE = @CLASE
							WHERE IDTIPOACTIVO = @IDTIPOACTIVOEDITE
						END
					END
					ELSE
					BEGIN
						UPDATE IACTT
						SET DESCRIPCION = @DESCRIPCION, ESTADO = @ESTADO, PIDEMODELO = @PIDEMODELO, PIDEMARCA = @PIDEMARCA, PIDESERIAL = @PIDESERIAL, PIDEREFERENCIA = 
							@PIDEREFERENCIA, PIDENOESCRITURA = @PIDENOESCRITURA, PIDELINDEROS = @PIDELINDEROS, PIDENOPARTES = @PIDENOPARTES, PIDEMATRICULA = 
							@PIDEMATRICULA, VIDAUTIL = @VIDAUTIL, BASEDEPRECIABLE = @BASEDEPRECIABLE, TIPOSALV = @TIPOSALV, TIPOVIDA = @TIPOVIDA, CLASE = @CLASE
						WHERE IDTIPOACTIVO = @IDTIPOACTIVO
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'GUARDAR_TIPOACTIVO_USUARIO'
	BEGIN
		BEGIN TRY
			SELECT @PROCESO = PROCESO, @IDTIPOACTIVO = IDTIPOACTIVO, @CODIGO = CODIGO, @DESCRIPCION = DESCRIPCION, @OPCIONESLIBRES = OPCIONESLIBRES, @IDTGEN = IDTGEN
			FROM OPENJSON(@PARAMETROS) WITH (
					PROCESO VARCHAR(20) '$.PROCESO', IDTIPOACTIVO VARCHAR(20) '$.IDTIPOACTIVO', CODIGO VARCHAR(20) '$.CODIGO', DESCRIPCION VARCHAR(1000) 
					'$.DESCRIPCION', OPCIONESLIBRES INT '$.OPCIONESLIBRES', IDTGEN INT '$.IDTGEN'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL EMPLEADO YA SE ENCUENTRA ASIGNADO AL TIPO DE ACTIVO ', @IDTIPOACTIVO)
					WHERE EXISTS (
							SELECT 1
							FROM TGEN
							WHERE TABLA = 'TIPOACTXUSUARIO' AND CAMPO = @IDTIPOACTIVO AND CODIGO = @CODIGO
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						INSERT INTO TGEN (TABLA, CAMPO, CODIGO, DESCRIPCION, OPCIONESLIBRES)
						SELECT 'TIPOACTXUSUARIO', @IDTIPOACTIVO, @CODIGO, @DESCRIPCION, @OPCIONESLIBRES
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL EMPLEADO YA SE ENCUENTRA ASIGNADO AL TIPO DE ACTIVO ', @IDTIPOACTIVO)
					WHERE EXISTS (
							SELECT 1
							FROM TGEN
							WHERE TABLA = 'TIPOACTXUSUARIO' AND CAMPO = @IDTIPOACTIVO AND CODIGO = @CODIGO AND IDTGEN <> @IDTGEN
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						UPDATE TGEN
						SET CODIGO = @CODIGO, DESCRIPCION = @DESCRIPCION, OPCIONESLIBRES = @OPCIONESLIBRES
						WHERE IDTGEN = @IDTGEN
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'ELIMINAR'
	BEGIN
		SELECT @IDTIPOACTIVO = IDTIPOACTIVO
		FROM OPENJSON(@PARAMETROS) WITH (IDTIPOACTIVO VARCHAR(20) '$.IDTIPOACTIVO')

		BEGIN TRY
			DELETE
			FROM IACTT
			WHERE IDTIPOACTIVO = @IDTIPOACTIVO
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'GENERAR_DEP'
	BEGIN
		SELECT @IDTIPOACTIVO = IDTIPOACTIVO, @TIPOSALV = TIPOSALV, @BASEDEPRECIABLE = BASEDEPRECIABLE
		FROM OPENJSON(@PARAMETROS) WITH (IDTIPOACTIVO VARCHAR(20) '$.IDTIPOACTIVO', TIPOSALV VARCHAR(10) '$.TIPOSALV', BASEDEPRECIABLE DECIMAL(14, 0) '$.BASEDEPRECIABLE'
				)

		BEGIN TRY
			UPDATE IACT
			SET DEPRECIABLE = CASE 
					WHEN PRECIOCOMPRA >= @BASEDEPRECIABLE
						THEN 1
					ELSE 0
					END, VALORSALVAMENTO = CASE 
					WHEN @TIPOSALV = 'VALOR'
						THEN @BASEDEPRECIABLE
					ELSE (PRECIOCOMPRA * @BASEDEPRECIABLE) / 100
					END
			WHERE IDTIPOACTIVO = @IDTIPOACTIVO

			DELETE IACTD
			FROM IACTD
			INNER JOIN IACT ON IACTD.IDACTIVO = IACT.IDACTIVO
			WHERE ISNULL(IACT.DEPRECIABLE, 0) = 0 AND ISNULL(IACTD.CONTABILIZADA, 0) = 0 AND IACT.IDTIPOACTIVO = @IDTIPOACTIVO

			DECLARE CURSOR_DEPACT CURSOR
			FOR
			SELECT IDACTIVO, DEPRECIABLE
			FROM IACT
			WHERE IDTIPOACTIVO = @IDTIPOACTIVO

			OPEN CURSOR_DEPACT

			FETCH NEXT
			FROM CURSOR_DEPACT
			INTO @IDACTIVO, @DEPRECIABLE

			WHILE @@FETCH_STATUS = 0
			BEGIN
				IF @DEPRECIABLE = 1
				BEGIN
					EXEC SPK_GEN_DEPRECIACION @IDACTIVO
				END

				FETCH NEXT
				FROM CURSOR_DEPACT
				INTO @IDACTIVO, @DEPRECIABLE
			END

			CLOSE CURSOR_DEPACT

			DEALLOCATE CURSOR_DEPACT
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END
END

