CREATE OR ALTER PROCEDURE DBO.SPQ_FPA_COL
@JSON  NVARCHAR(MAX)
WITH   ENCRYPTION
AS
DECLARE  @PARAMETROS NVARCHAR(MAX), @MODELO   VARCHAR(100), @METODO     VARCHAR(100)
DECLARE  @USUARIO    VARCHAR(20),   @GRUPO      VARCHAR(8), @FORMAPAGO VARCHAR(20), @CUENTA VARCHAR(16)
DECLARE  @ERRORES AS TABLE(ERROR VARCHAR(MAX))
BEGIN
	SELECT  @MODELO = MODELO , @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS=PARAMETROS
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)
	--SELECT @MODELO = MODELO , @METODO = METODO , @USUARIO = USUARIO
	--FROM #JSON
	
	--CREAR
	IF @METODO = 'CREA_FPA'
	BEGIN
		BEGIN TRY
			SELECT @FORMAPAGO = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO')
			SELECT @CUENTA = JSON_VALUE(@PARAMETROS, '$.CUENTA')
	
			IF COALESCE(@FORMAPAGO,'')='' 
				INSERT INTO @ERRORES
				SELECT 'Codigo es obligatorio'
			ELSE
			BEGIN
				-- INSERTAMOS
				INSERT INTO FPA(FORMAPAGO, DESCRIPCION, FISICO, REQBCO, REQDOC, REQAUT, CXC, AUTINT, MEDIOPAGO, TEDEVOLUCION, CUENTA, CEROENAPERTURA, 
								USAR_CUENTACAJA, REQCTA_BCO_DEP, GENCHEQUE, COMPROBANTE_EGR, DATAFONO)

				SELECT	LTRIM(RTRIM(@FORMAPAGO)),						LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.DESCRIPCION'))),		JSON_VALUE(@PARAMETROS, '$.FISICO'),				JSON_VALUE(@PARAMETROS, '$.REQBCO'),
						JSON_VALUE(@PARAMETROS, '$.REQDOC'),			JSON_VALUE(@PARAMETROS, '$.REQAUT'),						JSON_VALUE(@PARAMETROS, '$.CXC'),					JSON_VALUE(@PARAMETROS, '$.AUTINT'),
						JSON_VALUE(@PARAMETROS, '$.MEDIOPAGO'),			JSON_VALUE(@PARAMETROS, '$.TEDEVOLUCION'),					IIF(@CUENTA <> '', LTRIM(RTRIM(@CUENTA)), NULL),											
						JSON_VALUE(@PARAMETROS, '$.CEROENAPERTURA'),	JSON_VALUE(@PARAMETROS, '$.USAR_CUENTACAJA'),				JSON_VALUE(@PARAMETROS, '$.REQCTA_BCO_DEP'),		JSON_VALUE(@PARAMETROS, '$.GENCHEQUE'),				
						JSON_VALUE(@PARAMETROS, '$.COMPROBANTE_EGR'),	JSON_VALUE(@PARAMETROS, '$.DATAFONO')

				--RETURN
				SELECT OK='OK'
				RETURN
			END
		END TRY
		BEGIN CATCH
			INSERT INTO @ERRORES(ERROR) SELECT ERROR_MESSAGE()            
		END CATCH


		IF (SELECT COUNT(1) FROM @ERRORES)>0
		BEGIN
			SELECT OK='KO'
			SELECT * FROM @ERRORES
			RETURN
		END
	END
	--ACTUALIZA 
	IF @METODO = 'ACTUALIZA_FPA'
	BEGIN
		BEGIN TRY
			SELECT @FORMAPAGO = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO')
			SELECT @CUENTA = JSON_VALUE(@PARAMETROS, '$.CUENTA')
	
			IF COALESCE(@FORMAPAGO,'')='' 
				INSERT INTO @ERRORES
				SELECT 'Codigo es obligatorio'
			ELSE
			BEGIN
				-- ACTUALIZAMOS
				UPDATE FPA
				SET 
					DESCRIPCION		= LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.DESCRIPCION'))), 
					FISICO			= JSON_VALUE(@PARAMETROS, '$.FISICO'), 
					REQBCO			= JSON_VALUE(@PARAMETROS, '$.REQBCO'),
					REQDOC			= JSON_VALUE(@PARAMETROS, '$.REQDOC'), 
					REQAUT			= JSON_VALUE(@PARAMETROS, '$.REQAUT'), 
					CXC				= JSON_VALUE(@PARAMETROS, '$.CXC'),
					AUTINT			= JSON_VALUE(@PARAMETROS, '$.AUTINT'),
					MEDIOPAGO		= JSON_VALUE(@PARAMETROS, '$.MEDIOPAGO'), 
					TEDEVOLUCION	= JSON_VALUE(@PARAMETROS, '$.TEDEVOLUCION'), 
					CUENTA			= IIF(@CUENTA <> '', LTRIM(RTRIM(@CUENTA)), NULL),
					CEROENAPERTURA	= JSON_VALUE(@PARAMETROS, '$.CEROENAPERTURA'), 
					USAR_CUENTACAJA = JSON_VALUE(@PARAMETROS, '$.USAR_CUENTACAJA'),
					REQCTA_BCO_DEP	= JSON_VALUE(@PARAMETROS, '$.REQCTA_BCO_DEP'), 
					GENCHEQUE		= JSON_VALUE(@PARAMETROS, '$.GENCHEQUE'), 
					COMPROBANTE_EGR = JSON_VALUE(@PARAMETROS, '$.COMPROBANTE_EGR'), 
					DATAFONO		= JSON_VALUE(@PARAMETROS, '$.DATAFONO')
				WHERE
					FORMAPAGO = @FORMAPAGO
				--RETURN
				SELECT OK='OK'
				RETURN
			END
		END TRY
		BEGIN CATCH
			INSERT INTO @ERRORES(ERROR) SELECT ERROR_MESSAGE()            
		END CATCH


		IF (SELECT COUNT(1) FROM @ERRORES)>0
		BEGIN
			SELECT OK='KO'
			SELECT * FROM @ERRORES
			RETURN
		END
	END
	--ELIMINAR CJ
	IF @METODO = 'ELIMINAR_FPA'
	BEGIN
		BEGIN TRY
			SELECT @FORMAPAGO = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO')
	
			IF COALESCE(@FORMAPAGO,'')='' 
				INSERT INTO @ERRORES
				SELECT 'Codigo es obligatorio'
			ELSE
			BEGIN
				DELETE FROM FPA WHERE FORMAPAGO =  @FORMAPAGO

				--RETURN
				SELECT OK='OK'
				RETURN
			END
		END TRY
		BEGIN CATCH
			INSERT INTO @ERRORES(ERROR) SELECT ERROR_MESSAGE()            
		END CATCH

		IF (SELECT COUNT(1) FROM @ERRORES)>0
		BEGIN
			SELECT OK='KO'
			SELECT * FROM @ERRORES
			RETURN
		END
	END
END


