CREATE OR ALTER PROCEDURE DBO.SPQ_CPCJ_COL
@JSON  NVARCHAR(MAX)
WITH   ENCRYPTION
AS
DECLARE  @PARAMETROS NVARCHAR(MAX), @MODELO   VARCHAR(100), @METODO     VARCHAR(100)
DECLARE  @USUARIO    VARCHAR(20),   @GRUPO      VARCHAR(8), @CODIGO VARCHAR(20), @CUENTA VARCHAR(16)
DECLARE  @ERRORES AS TABLE(ERROR VARCHAR(MAX))
BEGIN
	SELECT  @MODELO = MODELO , @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS=PARAMETROS
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)
	--SELECT @MODELO = MODELO , @METODO = METODO , @USUARIO = USUARIO
	--FROM #JSON
	
	--CREAR
	IF @METODO = 'CREA_CPCJ'
	BEGIN
		BEGIN TRY
			SELECT @CODIGO = JSON_VALUE(@PARAMETROS, '$.CODIGO')
			SELECT @CUENTA = JSON_VALUE(@PARAMETROS, '$.CUENTA')
	
			IF COALESCE(@CODIGO,'')='' 
				INSERT INTO @ERRORES
				SELECT 'Codigo es obligatorio'
			ELSE
			BEGIN
				-- INSERTAMOS
				INSERT INTO CPCJ(CODIGO, DESCRIPCION, CUENTA, TIPO, TIPORECIBO, UNICO, COMPROBANTE, GENERAFACTURA, PIDEIMPTO, ESTADO, DECAJAMENOR, HOMOLOGODIAN)

				SELECT	LTRIM(RTRIM(@CODIGO)),							LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.DESCRIPCION'))),		IIF(@CUENTA <>'',@CUENTA,NULL),				
						JSON_VALUE(@PARAMETROS, '$.TIPO'),				JSON_VALUE(@PARAMETROS, '$.TIPORECIBO'),					JSON_VALUE(@PARAMETROS, '$.UNICO'),					
						JSON_VALUE(@PARAMETROS, '$.COMPROBANTE'),		JSON_VALUE(@PARAMETROS, '$.GENERAFACTURA'),					JSON_VALUE(@PARAMETROS, '$.PIDEIMPTO'),	
						JSON_VALUE(@PARAMETROS, '$.ESTADO'),			JSON_VALUE(@PARAMETROS, '$.DECAJAMENOR'),					JSON_VALUE(@PARAMETROS, '$.HOMOLOGODIAN')

				--RETURN
				SELECT OK='OK'
				RETURN
			END
		END TRY
		BEGIN CATCH
			INSERT INTO @ERRORES(ERROR) SELECT ERROR_MESSAGE()            
		END CATCH


		IF (SELECT COUNT(1) FROM @ERRORES)>0
		BEGIN
			SELECT OK='KO'
			SELECT * FROM @ERRORES
			RETURN
		END
	END
	--ACTUALIZA 
	IF @METODO = 'ACTUALIZA_CPCJ'
	BEGIN
		BEGIN TRY
			SELECT @CODIGO = JSON_VALUE(@PARAMETROS, '$.CODIGO')
			SELECT @CUENTA = JSON_VALUE(@PARAMETROS, '$.CUENTA')
	
			IF COALESCE(@CODIGO,'')='' 
				INSERT INTO @ERRORES
				SELECT 'Codigo es obligatorio'
			ELSE
			BEGIN
				-- ACTUALIZAMOS
				UPDATE CPCJ
				SET 
					DESCRIPCION		= LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.DESCRIPCION'))), 
					CUENTA			= IIF(@CUENTA <>'',@CUENTA,NULL), 
					TIPO			= JSON_VALUE(@PARAMETROS, '$.TIPO'),
					TIPORECIBO		= JSON_VALUE(@PARAMETROS, '$.TIPORECIBO'), 
					UNICO			= JSON_VALUE(@PARAMETROS, '$.UNICO'), 
					COMPROBANTE		= JSON_VALUE(@PARAMETROS, '$.COMPROBANTE'),
					GENERAFACTURA	= JSON_VALUE(@PARAMETROS, '$.GENERAFACTURA'),
					PIDEIMPTO		= JSON_VALUE(@PARAMETROS, '$.PIDEIMPTO'), 
					ESTADO			= JSON_VALUE(@PARAMETROS, '$.ESTADO'), 
					DECAJAMENOR		= JSON_VALUE(@PARAMETROS, '$.DECAJAMENOR'),
					HOMOLOGODIAN	= JSON_VALUE(@PARAMETROS, '$.HOMOLOGODIAN')
				WHERE
					CODIGO = @CODIGO
				--RETURN
				SELECT OK='OK'
				RETURN
			END
		END TRY
		BEGIN CATCH
			INSERT INTO @ERRORES(ERROR) SELECT ERROR_MESSAGE()            
		END CATCH


		IF (SELECT COUNT(1) FROM @ERRORES)>0
		BEGIN
			SELECT OK='KO'
			SELECT * FROM @ERRORES
			RETURN
		END
	END
	--ELIMINAR CJ
	IF @METODO = 'ELIMINAR_CPCJ'
	BEGIN
		BEGIN TRY
			SELECT @CODIGO = JSON_VALUE(@PARAMETROS, '$.CODIGO')
	
			IF COALESCE(@CODIGO,'')='' 
				INSERT INTO @ERRORES
				SELECT 'Codigo es obligatorio'
			ELSE
			BEGIN
				DELETE FROM CPCJ WHERE CODIGO =  @CODIGO

				--RETURN
				SELECT OK='OK'
				RETURN
			END
		END TRY
		BEGIN CATCH
			INSERT INTO @ERRORES(ERROR) SELECT ERROR_MESSAGE()            
		END CATCH

		IF (SELECT COUNT(1) FROM @ERRORES)>0
		BEGIN
			SELECT OK='KO'
			SELECT * FROM @ERRORES
			RETURN
		END
	END
END

