CREATE OR ALTER PROCEDURE  DBO.SPQ_CARTERA_IMPRESION
@JSON  NVARCHAR(MAX)
WITH ENCRYPTION
AS  
DECLARE	 @PARAMETROS  NVARCHAR(MAX)     
         ,@MODELO    VARCHAR(100)         
         ,@METODO    VARCHAR(100)	
         ,@USUARIO      VARCHAR(12)
         ,@CNSFPAG VARCHAR(20)                ,@CNSGLOI VARCHAR(20)				   ,@COMPANIA VARCHAR(2)
         ,@IDSEDE      VARCHAR(5)		       ,@SYS_COMPUTERNAME VARCHAR(200)  
         ,@N_FACTURA   VARCHAR(20)
BEGIN  
	SET DATEFORMAT dmy
   SET LANGUAGE Spanish;
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)
	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));


   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA,'01'),
   @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_COMPUTERNAME,HOST_NAME())
   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
   WHERE USUSU.USUARIO=@USUARIO

   IF @METODO='FPAG'     
   BEGIN  
      PRINT 'Ingreso a Pagos'
      SELECT @CNSFPAG=CNSFPAG        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSFPAG  VARCHAR(20)   '$.CNSFPAG' 
      )
      IF NOT EXISTS(SELECT * FROM FPAG WHERE CNSFPAG=@CNSFPAG)
      BEGIN
         SELECT 'KO'OK,'No se Encontro el Pago. Verifique e intente de nuevo'
      END
      SELECT 'OK'OK,CNSFPAG,FPAG.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,DBO.FNK_FECHA_DDMMAA(FPAG.FECHA) FECHA,
              FPAG.INGRESO,FPAG.BANCO,BCO.DESCRIPCION AS N_BANCO,BMOVD.CTA_BCO,BMOVD.NODOCUMENTO,
              FPAG.CODCAJA,CAJ.DESCRIPCION AS N_CAJA,FPAG.CNSFACJ,FPAG.OBSERVACION,VLRAJUSTEPESO,
              CASE WHEN FPAG.CERRADO=0 THEN 'PAGO NO APLICADO -- NO DEFINITIVO' ELSE '' END TITULO,
              CONCAT(DBO.FNK_FECHA_DDMMAA(FPAG.FECHA),' ',CONVERT(VARCHAR,DBO.FNK_GETDATE(),108))FIMPRESION,
              @USUARIO USUARIO,(SELECT COALESCE(SYS_COMPUTERNAME,HOST_NAME()) FROM USUSU WHERE USUARIO=@USUARIO)EQUIPO
      FROM FPAG INNER JOIN TER ON FPAG.IDTERCERO=TER.IDTERCERO
                LEFT JOIN  BMOVD ON FPAG.BANCO=BMOVD.BANCO AND FPAG.SUCURSAL=BMOVD.SUCURSAL AND FPAG.CTA_BCO=BMOVD.CTA_BCO
                                     AND FPAG.ITEM=BMOVD.ITEM AND FPAG.RENGLON=BMOVD.RENGLON
                LEFT JOIN  FCJ ON FPAG.CODCAJA=FCJ.CODCAJA AND FPAG.CNSFACJ=FCJ.CNSFACJ
                LEFT JOIN  BCO ON BMOVD.BANCO=BCO.BANCO
                LEFT JOIN  CAJ ON FPAG.CODCAJA=CAJ.CODCAJA
      WHERE FPAG.CNSFPAG=@CNSFPAG

      SELECT N_FACTURA,CNSCXC,VLRFACTURA,VLRGLOSA,GLOSAAFECTAIMP,VLRCOPAGO,BASE,VLRIMPUESTO,VLRPAGOSIN,VLRDTOFIN,SINPAGO,VALORPAGO,
             VLREXTRA,OBSERVACION
      FROM FPAGD
      WHERE FPAGD.CNSFPAG=@CNSFPAG
      ORDER BY N_FACTURA

      SELECT FPAGDI.IDIMPUESTO,FPAGDI.IDCLASE,FIMPD.DESCRIPCION,SUM(VLRIMPUESTO) VLRIMPUESTO
      FROM FPAGDI INNER JOIN FIMPD ON FPAGDI.IDIMPUESTO=FIMPD.IDIMPUESTO AND FPAGDI.IDCLASE=FIMPD.IDCLASE
      WHERE CNSFPAG=@CNSFPAG
      GROUP BY FPAGDI.IDIMPUESTO,FPAGDI.IDCLASE,FIMPD.DESCRIPCION
      
   END  
   IF @METODO='FGLOI'
   BEGIN
      PRINT 'Ingreso a Impresión respuesta Glosa'
      SELECT @CNSGLOI =CNSGLOI       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSGLOI  VARCHAR(20)   '$.CNSGLOI'
      )
      IF NOT EXISTS(SELECT * FROM FGLOI WHERE CNSGLOI=@CNSGLOI)
      BEGIN
         SELECT 'KO'OK,'No se Encontro el Pago. Verifique e intente de nuevo'
      END
      SELECT 'OK'OK,TER.NIT,TER.RAZONSOCIAL,DBO.FNK_FECHA_DDMMAA(FGLOI.FECHA)FECHA,DBO.FNK_FECHA_DDMMAA(DBO.FNK_GETDATE())FECHAIMP,
      CNSGLOI,IMPRESIONES,@SYS_COMPUTERNAME AS EQUIPO,@USUARIO AS USUARIO
      FROM FGLOI INNER JOIN TER ON FGLOI.IDTERCERO=TER.IDTERCERO
      WHERE FGLOI.CNSGLOI=@CNSGLOI
      
      SELECT FGLO.RADICADO, FTR.VR_TOTAL,FGLO.N_FACTURA,dbo.FNK_FECHA_DDMMAA(FTR.F_FACTURA)F_FACTURA,dbo.FNK_FECHA_DDMMAA(FCXC.F_RECIBIDO)F_RECIBIDO,
			 COALESCE(AFI.DOCIDAFILIADO,'') AS DOCIDAFILIADO, COALESCE(AFI.NOMBREAFI,'') AS NOMBREAFI,
             MOTIVO=(SELECT FGLOCG.CNSGLO, FGLOCG.CNSFCGLO,FCGLO.DESCRIPCION,REPLACE(REPLACE(LTRIM(RTRIM(FGLOCG.OBSERVACION)),CHAR(13),''),CHAR(10),'')OBSERVACION
                    FROM FGLOCG INNER JOIN FCGLO ON FGLOCG.CNSFCGLO=FCGLO.CNSFCGLO 
                    WHERE CNSGLO=FGLO.CNSGLO FOR JSON PATH ),
           LTRIM(RTRIM(dbo.FNK_RTF(FGLO.OBSERVACION)))OBSERVACION,LTRIM(RTRIM(dbo.FNK_RTF(FGLO.OBSERVACIONRTA)))OBSERVACIONRTA,
         VLRGLOSA,VLRACEPTADO,VLRRECUPERAR
      FROM FGLOI INNER JOIN FGLOID ON FGLOID.CNSGLOI=FGLOI.CNSGLOI
                 INNER JOIN FGLO ON FGLOID.CNSGLO=FGLO.CNSGLO
                 INNER JOIN FTR ON FGLO.N_FACTURA=FTR.N_FACTURA
                 LEFT JOIN FCXC ON FGLO.CNSCXC=FCXC.CNSCXC
                 LEFT JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
      WHERE FGLOI.CNSGLOI=@CNSGLOI
      AND FGLO.TIPORESPUESTA='T'
      ORDER BY FGLO.CNSGLO,N_FACTURA

      SELECT FTR.VR_TOTAL,dbo.FNK_FECHA_DDMMAA(FTR.F_FACTURA)F_FACTURA,dbo.FNK_FECHA_DDMMAA(FCXC.F_RECIBIDO)F_RECIBIDO,
   			 COALESCE(AFI.DOCIDAFILIADO,'') AS DOCIDAFILIADO, COALESCE(AFI.NOMBREAFI,'') AS NOMBREAFI, FGLO.N_FACTURA,
             FGLO.N_FACTURA,
             MOTIVO=(SELECT FGLOCG.CNSGLO, FGLOCG.CNSFCGLO,FCGLO.DESCRIPCION  
                    FROM FGLOCG INNER JOIN FCGLO ON FGLOCG.CNSFCGLO=FCGLO.CNSFCGLO 
                    WHERE CNSGLO=FGLO.CNSGLO FOR JSON PATH ),
         FGLOD.CODGLOSA AS COD_GLOSA,
         FGLOD.IDSERVICIO AS COD_SERVICIO,
         FGLOD.DESCRIPCION AS DESCRIPCION_SERVICIO,
         FGLOD.OBSERVACION,FGLOD.RESPUESTA,
         FGLOD.VLRGLOSA,FGLOD.VLRACEPTADO,FGLOD.VLRRECUPERAR
      FROM FGLOI INNER JOIN FGLOID ON FGLOID.CNSGLOI=FGLOI.CNSGLOI
                 INNER JOIN FGLO ON FGLOID.CNSGLO=FGLO.CNSGLO
                 INNER JOIN FGLOD ON FGLO.CNSGLO=FGLOD.CNSGLO
                 INNER JOIN FTR ON FGLO.N_FACTURA=FTR.N_FACTURA
                 LEFT  JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
                 LEFT JOIN FCXC ON FGLO.CNSCXC=FCXC.CNSCXC
      WHERE FGLOI.CNSGLOI=@CNSGLOI
      AND FGLO.TIPORESPUESTA='I'
      ORDER BY FGLO.CNSGLO,FGLO.N_FACTURA


   END
	IF @METODO = 'FGLOI_IND'
	BEGIN
	  SELECT @CNSGLOI = CNSGLOI, @N_FACTURA = N_FACTURA
	  FROM OPENJSON (@PARAMETROS)
	  WITH (
		CNSGLOI   VARCHAR(20) '$.CNSGLOI',
		N_FACTURA VARCHAR(20) '$.N_FACTURA'
	  );

	  IF @CNSGLOI IS NULL OR NULLIF(LTRIM(RTRIM(@N_FACTURA)), '') IS NULL
	  BEGIN
		SELECT 'KO' AS OK, 'Parámetros incompletos (CNSGLOI y N_FACTURA).' AS ERROR;
		RETURN;
	  END;

	  IF NOT EXISTS (SELECT 1 FROM FGLOI WHERE CNSGLOI = @CNSGLOI)
	  BEGIN
		SELECT 'KO' AS OK, 'No se encontró el registro de impresión. Verifique e intente de nuevo.' AS ERROR;
		RETURN;
	  END;

	  IF NOT EXISTS (
		SELECT 1
		FROM FGLOI
		INNER JOIN FGLOID ON FGLOID.CNSGLOI = FGLOI.CNSGLOI
		INNER JOIN FGLO ON FGLOID.CNSGLO = FGLO.CNSGLO
		WHERE FGLOI.CNSGLOI = @CNSGLOI AND FGLO.N_FACTURA = @N_FACTURA
	  )
	  BEGIN
		SELECT 'KO' AS OK, 'La factura no está asociada a esta impresión. Verifique e intente de nuevo.' AS ERROR;
		RETURN;
	  END;

	  SELECT 'OK' AS OK, TER.NIT, TER.RAZONSOCIAL,
			 DBO.FNK_FECHA_DDMMAA(FGLOI.FECHA) AS FECHA,
			 DBO.FNK_FECHA_DDMMAA(DBO.FNK_GETDATE()) AS FECHAIMP,
			 CNSGLOI, IMPRESIONES, @SYS_COMPUTERNAME AS EQUIPO, @USUARIO AS USUARIO
	  FROM FGLOI
	  INNER JOIN TER ON FGLOI.IDTERCERO = TER.IDTERCERO
	  WHERE FGLOI.CNSGLOI = @CNSGLOI;

	  SELECT FGLO.RADICADO, FTR.VR_TOTAL, FGLO.N_FACTURA,
			 DBO.FNK_FECHA_DDMMAA(FTR.F_FACTURA) AS F_FACTURA,
			 DBO.FNK_FECHA_DDMMAA(FCXC.F_RECIBIDO) AS F_RECIBIDO,
			 COALESCE(AFI.DOCIDAFILIADO,'') AS DOCIDAFILIADO, COALESCE(AFI.NOMBREAFI,'') AS NOMBREAFI,
			 MOTIVO = (
			   SELECT FGLOCG.CNSGLO, FGLOCG.CNSFCGLO, FCGLO.DESCRIPCION,
					  REPLACE(REPLACE(LTRIM(RTRIM(FGLOCG.OBSERVACION)), CHAR(13), ''), CHAR(10), '') AS OBSERVACION
			   FROM FGLOCG
			   INNER JOIN FCGLO ON FGLOCG.CNSFCGLO = FCGLO.CNSFCGLO
			   WHERE CNSGLO = FGLO.CNSGLO
			   FOR JSON PATH
			 ),
			 LTRIM(RTRIM(DBO.FNK_RTF(FGLO.OBSERVACION))) AS OBSERVACION,
			 LTRIM(RTRIM(DBO.FNK_RTF(FGLO.OBSERVACIONRTA))) AS OBSERVACIONRTA,
			 VLRGLOSA, VLRACEPTADO, VLRRECUPERAR
	  FROM FGLOI
	  INNER JOIN FGLOID ON FGLOID.CNSGLOI = FGLOI.CNSGLOI
	  INNER JOIN FGLO ON FGLOID.CNSGLO = FGLO.CNSGLO
	  INNER JOIN FTR ON FGLO.N_FACTURA = FTR.N_FACTURA
	  LEFT JOIN FCXC ON FGLO.CNSCXC = FCXC.CNSCXC
	  LEFT JOIN AFI ON FTR.IDAFILIADO = AFI.IDAFILIADO
	  WHERE FGLOI.CNSGLOI = @CNSGLOI
		AND FGLO.N_FACTURA = @N_FACTURA
		AND FGLO.TIPORESPUESTA = 'T'
	  ORDER BY FGLO.CNSGLO, N_FACTURA;

	  SELECT FTR.VR_TOTAL,
			 DBO.FNK_FECHA_DDMMAA(FTR.F_FACTURA) AS F_FACTURA,
			 DBO.FNK_FECHA_DDMMAA(FCXC.F_RECIBIDO) AS F_RECIBIDO,
			 COALESCE(AFI.DOCIDAFILIADO,'') AS DOCIDAFILIADO, COALESCE(AFI.NOMBREAFI,'') AS NOMBREAFI, FGLO.N_FACTURA,
			 MOTIVO = (
			   SELECT FGLOCG.CNSGLO, FGLOCG.CNSFCGLO, FCGLO.DESCRIPCION
			   FROM FGLOCG
			   LEFT JOIN FCGLO ON FGLOCG.CNSFCGLO = FCGLO.CNSFCGLO
			   WHERE CNSGLO = FGLO.CNSGLO
			   FOR JSON PATH
			 ),
             FGLOD.CODGLOSA AS COD_GLOSA,
             FGLOD.IDSERVICIO AS COD_SERVICIO,
             FGLOD.DESCRIPCION AS DESCRIPCION_SERVICIO,
			 FGLOD.OBSERVACION, FGLOD.RESPUESTA,
			 FGLOD.VLRGLOSA, FGLOD.VLRACEPTADO, FGLOD.VLRRECUPERAR
	  FROM FGLOI
	  INNER JOIN FGLOID ON FGLOID.CNSGLOI = FGLOI.CNSGLOI
	  INNER JOIN FGLO ON FGLOID.CNSGLO = FGLO.CNSGLO
	  INNER JOIN FGLOD ON FGLO.CNSGLO = FGLOD.CNSGLO
	  INNER JOIN FTR ON FGLO.N_FACTURA = FTR.N_FACTURA
	  LEFT JOIN AFI ON FTR.IDAFILIADO = AFI.IDAFILIADO
	  LEFT JOIN FCXC ON FGLO.CNSCXC = FCXC.CNSCXC
	  WHERE FGLOI.CNSGLOI = @CNSGLOI
		AND FGLO.N_FACTURA = @N_FACTURA
		AND FGLO.TIPORESPUESTA = 'I'
	  ORDER BY FGLO.CNSGLO, FGLO.N_FACTURA;
	END;
   IF @METODO='BUSCA_FACTURA'     
   BEGIN         
      SELECT @N_FACTURA=N_FACTURA        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )
      IF EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTURA)
      BEGIN
         SELECT 'OK'OK
         IF NOT  EXISTS(SELECT * FROM ENTD WHERE NODOCUMENTO=@N_FACTURA)
         BEGIN
            SELECT FTR.N_FACTURA,TER.NIT,TER.RAZONSOCIAL,''CNSENTREGA,FTR.VR_TOTAL,FDEP.NOMBRE,DBO.FNK_FECHA_DDMMAA(FTR.F_FACTURA)FECHA FROM 
            FTR LEFT JOIN FDEP ON FTR.IDDEP=FDEP.IDDEP 
                LEFT JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
            WHERE N_FACTURA=@N_FACTURA 
            SELECT 'NADA'AS NADA
         END
         ELSE
         BEGIN
            DECLARE @CNSENTREGA VARCHAR(20)
            DECLARE @FECHAMAX DATETIME
            SELECT TOP 1 @CNSENTREGA=ENT.CNSENTREGA,@FECHAMAX=ENT.FECHAENTREGA
            FROM ENTD INNER JOIN ENT ON ENTD.CNSENTREGA=ENT.CNSENTREGA
            WHERE ENTD.NODOCUMENTO=@N_FACTURA
            ORDER BY ENT.FECHAENTREGA DESC

            SELECT FTR.N_FACTURA,TER.NIT,TER.RAZONSOCIAL,@CNSENTREGA AS CNSENTREGA,FTR.VR_TOTAL,FDEP.NOMBRE,DBO.FNK_FECHA_DDMMAA(@FECHAMAX) AS FECHA FROM 
            FTR LEFT JOIN FDEP ON FTR.IDDEP=FDEP.IDDEP 
                LEFT JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
            WHERE N_FACTURA=@N_FACTURA
            SELECT ''AS NADA
            SELECT ENT.CNSENTREGA,DBO.FNK_FECHA_DDMMAA(ENT.FECHAENTREGA)F_ENTREGA,ENT.ENT_ENTREGA,FDEP.NOMBRE AS ENTENTREGA,
                   ENT.ENT_RECIBE,DEP.NOMBRE AS ENRECIBE, ENT.USUARIOENTREGA,ENT.USUARIORECIBE
            FROM ENT INNER JOIN ENTD ON ENT.CNSENTREGA=ENTD.CNSENTREGA
                     LEFT  JOIN FDEP ON ENT.ENT_ENTREGA=FDEP.IDDEP
                     LEFT  JOIN FDEP DEP ON ENT.ENT_RECIBE=DEP.IDDEP
            WHERE ENTD.NODOCUMENTO=@N_FACTURA
            AND ENTD.PROCESO='FACTURAS'

         END
         IF EXISTS(SELECT * FROM FCXCDV WHERE N_FACTURA=@N_FACTURA)
         BEGIN
            SELECT TOP 1 @CNSGLOI=CNSCXC FROM  FCXCDV WHERE N_FACTURA=@N_FACTURA
            SELECT 1 AS ENCXC,@CNSGLOI AS CNSCXC
         END
      END
      ELSE
      BEGIN
         SELECT 'KO'OK,'Factura no encontrada en el Maestro de Facturas, Verifique e intente de nuevo'ERROR
      END
      RETURN
   END  
END

