CREATE OR ALTER PROCEDURE DBO.SPQ_FNOT_COL @JSON NVARCHAR(MAX)
WITH ENCRYPTION
AS
SET DATEFORMAT dmy;
SET NOCOUNT ON;

DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX));
DECLARE @PARAMETROS NVARCHAR(MAX);
DECLARE @MODELO VARCHAR(100);
DECLARE @METODO VARCHAR(100);
DECLARE @USUARIO VARCHAR(12);
DECLARE @COMPANIA VARCHAR(2);
DECLARE @IDSEDE VARCHAR(5);
DECLARE @SYS_COMPUTERNAME VARCHAR(200);
DECLARE @DATOS VARCHAR(MAX);
DECLARE @PROCESO VARCHAR(20);
DECLARE @CNSFNOT VARCHAR(20);
DECLARE @CLASE VARCHAR(20);
DECLARE @N_FACTURA VARCHAR(20);
DECLARE @F_NOTA VARCHAR(20);
DECLARE @OBSERVACION VARCHAR(520);
DECLARE @PROCEDENCIA VARCHAR(20);
DECLARE @IDCONCEPTO VARCHAR(20);
DECLARE @NIT VARCHAR(20);
DECLARE @RAZONSOCIAL VARCHAR(120);
DECLARE @DESCRIPCION VARCHAR(120);
DECLARE @CONCEPTO BIT;
DECLARE @TIPOCONCEPTO VARCHAR(20);
DECLARE @VALORCONCEPTO DECIMAL(14, 2);
DECLARE @SALDOFACTURA DECIMAL(14, 2);
DECLARE @VALOR DECIMAL(14, 2);
DECLARE @CNSCXC VARCHAR(20);
DECLARE @IDTERCERO VARCHAR(20);
DECLARE @N_FACTU VARCHAR(20);
DECLARE @IDCOPCENTO VARCHAR(20);
DECLARE @DESCONCEPTO VARCHAR(120);
DECLARE @VALORNT DECIMAL(14, 2);
DECLARE @OBSERVA VARCHAR(512);
DECLARE @NROLINEAS INT;
DECLARE @ERROR VARCHAR(256);
DECLARE @IDTER VARCHAR(20);
DECLARE @RAZONS VARCHAR(120);
DECLARE @CNSRPDX VARCHAR(20);
DECLARE @TIPO VARCHAR(2);
DECLARE @N_CUOTA INT;
DECLARE @IDSERVICIO VARCHAR(20);
DECLARE @PREFIJO VARCHAR(20);
DECLARE @IDAREA VARCHAR(20);
DECLARE @CCOSTO VARCHAR(20);
DECLARE @CANTIDAD INT;
DECLARE @VR_UNITARIO DECIMAL(14, 2);
DECLARE @VR_TOTAL DECIMAL(14, 2);
DECLARE @DETGENERADOS BIT;
DECLARE @NROCOMPROBANTE VARCHAR(20);
DECLARE @USUARIOSOL VARCHAR(20);
DECLARE @RAZONANULA VARCHAR(255);
DECLARE @ITEM INT;
DECLARE @IXCOUNTRY VARCHAR(20);
DECLARE @PIVA DECIMAL(7, 2);
DECLARE @VIVA DECIMAL(14, 2);
DECLARE @VLR_ITEM DECIMAL(14, 2);

BEGIN
	IF COALESCE(@JSON, '') = ''
	BEGIN
		SELECT 'KO' AS OK, 'JSON vac'+NCHAR(237)+'o o no v'+NCHAR(225)+'lido' AS ERROR;
		RETURN;
	END
	SELECT *
	INTO #JSON
	FROM OPENJSON(@JSON) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT @MODELO = MODELO,
		@METODO = METODO,
		@PARAMETROS = PARAMETROS,
		@USUARIO = USUARIO
	FROM #JSON;

	SELECT @IXCOUNTRY = DBO.FNK_VALORVARIABLE('IXCOUNTRY');

	IF @METODO = 'FNOT_CRUD'
	BEGIN
		SELECT @DATOS=DATOS        
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			DATOS NVARCHAR(MAX) AS JSON 
			)           
      
			SELECT @PROCESO=PROCESO, @CNSFNOT=CNSFNOT,@CLASE=CLASE,@N_FACTURA=N_FACTURA,@CNSCXC=CNSCXC,@F_NOTA=F_NOTA,
				@OBSERVACION=OBSERVACION,@PROCEDENCIA=PROCEDENCIA,@IDCONCEPTO=IDCONCEPTO,@NIT=NIT,@RAZONSOCIAL=RAZONSOCIAL,
				@DESCRIPCION=DESCRIPCION,@CONCEPTO=CASE WHEN CONCEPTO='true' THEN 1 ELSE 0 END,@TIPOCONCEPTO=CASE WHEN TIPOCONCEPTO='Porcentaje' OR TIPOCONCEPTO='P' THEN 'P'ELSE 'V' END,
            @VALORCONCEPTO=VALORCONCEPTO,	@SALDOFACTURA=SALDOFACTURA,@VALOR=VALOR,@IDTERCERO=IDTERCERO,
            @USUARIOSOL=USUARIOSOL, @RAZONANULA=RAZONANULA
			FROM   OPENJSON (@DATOS)
			WITH   (  
			PROCESO VARCHAR(20)          '$.PROCESO',
			CNSFNOT VARCHAR(20)          '$.CNSFNOT',
			CLASE VARCHAR(20)            '$.CLASE',
			N_FACTURA VARCHAR(20)        '$.N_FACTURA',
			CNSCXC VARCHAR(20)           '$.CNSCXC',
			F_NOTA VARCHAR(20)           '$.F_NOTA',
			OBSERVACION VARCHAR(520)      '$.OBSERVACION',
			PROCEDENCIA VARCHAR(20)      '$.PROCEDENCIA',
			IDCONCEPTO VARCHAR(20)     '$.IDCONCEPTO',
			NIT VARCHAR(20)            '$.NIT',
			IDTERCERO VARCHAR(20)      '$.IDTERCERO',
			RAZONSOCIAL VARCHAR(120)      '$.RAZONSOCIAL',
			DESCRIPCION VARCHAR(120)      '$.DESCRIPCION',
			CONCEPTO VARCHAR(20)         '$.CONCEPTO',
			TIPOCONCEPTO VARCHAR(20)     '$.TIPOCONCEPTO.value',
			VALORCONCEPTO DECIMAL(14,2)    '$.VALORCONCEPTO',
			SALDOFACTURA DECIMAL(14,2)   '$.SALDOFACTURA',
			VALOR DECIMAL(14,2)          '$.VALOR',
			USUARIOSOL VARCHAR(20)       '$.USUARIOSOL',
			RAZONANULA VARCHAR(255)      '$.RAZONANULA'
			)

		/* Anular nota sin aplicar: solo CERRADA=0; marca ESTADO=A (no DELETE). */
		IF @PROCESO='ANULAR'
		BEGIN
			IF NOT EXISTS(SELECT 1 FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
			BEGIN
				SELECT 'KO' KO, 'Nota no encontrada, Verifique e intente de nuevo' ERROR
				RETURN
			END
			IF EXISTS(SELECT 1 FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND (COALESCE(CERRADA,0)=1 OR ESTADO='A'))
			BEGIN
				SELECT 'KO' KO, 'Solo se pueden anular por este medio notas sin aplicar (abiertas). Si ya está aplicada utilice la opción Anular Nota.' ERROR
				RETURN
			END
			IF LEN(LTRIM(RTRIM(COALESCE(@RAZONANULA,'')))) < 10
			BEGIN
				SELECT 'KO' KO, 'Debe indicar el motivo de anulación (mínimo 10 caracteres).' ERROR
				RETURN
			END
			BEGIN TRY
				UPDATE FNOT SET
					ESTADO = 'A',
					USUARIOANU = @USUARIO,
					USUARIOSOL = COALESCE(NULLIF(LTRIM(RTRIM(@USUARIOSOL)), ''), @USUARIO),
					FECHAANU = DBO.FNK_GETDATE(),
					RAZONANU = @RAZONANULA
				WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
			IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK, ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK' OK, @CNSFNOT AS CNSFNOT, 0 AS DETGENERADOS
			RETURN
		END

		IF NOT EXISTS (SELECT 1 FROM FTR WHERE N_FACTURA = @N_FACTURA)
		BEGIN
			SELECT 'KO' AS KO, 'Factura no encontrada. Verifique e intente de nuevo' AS ERROR;
			RETURN;
		END
		IF @PROCESO='Nueva' 
		BEGIN
			IF EXISTS(SELECT * FROM FNOT WHERE N_FACTURA=@N_FACTURA AND CERRADA=0 AND ESTADO='O')
			BEGIN
			SELECT 'KO'KO,'Existe una Nota en proceso para esta Factura, No se Puede Continuar'ERROR
			RETURN
			END
			SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
			@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
			FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
			WHERE USUSU.USUARIO=@USUARIO
			BEGIN TRY
			SELECT @CNSFNOT=''
			IF @CLASE='C'
			BEGIN
			   EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@FNOTC', @CNSFNOT OUTPUT  
			END
			ELSE
			BEGIN
				EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@FNOTD', @CNSFNOT OUTPUT  
			END
			SELECT @CNSFNOT = @IDSEDE + LTRIM(RTRIM(@CLASE)) + REPLACE(SPACE(8 - LEN(@CNSFNOT)) + LTRIM(RTRIM(@CNSFNOT)), SPACE(1), '0');

			INSERT INTO FNOT(CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, MARCA, MARCACONT, 
							CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, CERRADA, ESTADO, USUARIOANU,  
							USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, 
							ENPRESUPUESTO, IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO, TIPOCONCEPTO,  
							VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS, CONSECUTIVOPPTO, RECO, FACTE, CNSRESOLFE, 
							PREFIJODIANFE, CNSDIANFE, CNSMASIVO, ZIPKEY, CUDE, FACTEP, RUTARPTA, DOCUMENTOID, DOCUXMLXZIPID,
							XMLZIPID, SOLICITUDJSON, RESPUESTAJSON, PDF) 
			SELECT @CNSFNOT, @CLASE, @N_FACTURA, @CNSCXC,@IDTERCERO, DBO.FNK_GETDATE(),0,@OBSERVACION, 0, 0, 
							0, NULL, 0, @COMPANIA, @USUARIO, 0, 'O', NULL,NULL, NULL, NULL, 'NOTAS', NULL,
							CASE WHEN COALESCE(@CNSCXC,'')='' THEN 'F' ELSE'C' END,0, NULL, NULL, 0, NULL, NULL, 
							@CONCEPTO,@IDCONCEPTO, COALESCE(@TIPOCONCEPTO,'P'),COALESCE(@VALORCONCEPTO,100), NULL, 0, NULL, NULL, NULL, NULL,NULL, NULL,
							NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0

			END TRY
			BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT ERROR AS ERROR FROM  @TBLERRORES 
			RETURN
			END CATCH
		END
		IF @PROCESO='Editar'
		BEGIN
			IF EXISTS(SELECT * FROM FNOT WHERE N_FACTURA=@N_FACTURA AND CERRADA=0 AND ESTADO='O' AND CNSFNOT<>@CNSFNOT)
			BEGIN
			SELECT 'KO'KO,'Existe una Nota en proceso para esta Factura, No se Puede Continuar'ERROR
			RETURN
			END
			BEGIN TRY       
			   UPDATE FNOT SET N_FACTURA=@N_FACTURA,IDTERCERO=@IDTERCERO,CNSCXC=@CNSCXC,IDCONCEPTO=@IDCONCEPTO,
			   CONCEPTO=@CONCEPTO,TIPOCONCEPTO=@TIPOCONCEPTO,VALORCONCEPTO=@VALORCONCEPTO,OBSERVACION=@OBSERVACION
			   WHERE CNSFNOT=@CNSFNOT
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
		END
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
      SELECT @DETGENERADOS=0
      IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE='C' AND CONCEPTO=1)
      BEGIN
         EXEC SPK_GENITEMS_NOTACR @CNSFNOT,@CLASE,@USUARIO 
         SELECT @DETGENERADOS=1
      END
		SELECT 'OK' OK,@CNSFNOT AS CNSFNOT, @DETGENERADOS AS DETGENERADOS
		RETURN 
	END  
	IF @METODO='FNOT_ADDDETA'     
	BEGIN   
		SELECT @CNSFNOT=CNSFNOT,@CLASE=CLASE       
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			CNSFNOT VARCHAR(20) '$.CNSFNOT',
			CLASE   VARCHAR(2) '$.CLASE'
			)           
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			SELECT 'KO'KO,'Nota no encontrada, Verifique e intente de nuevo'ERROR
			RETURN
		END
      --20250801 -- STORRES -- EL DETALLE MASIVO ESTA CONFIGURADO O PROGRAMADO PARA LA NOTAS CREDITO Y CAUSA ERROR AL INTENTAR USARLO POR EL DEBITO
		IF @CLASE <> 'C'
		BEGIN
			SELECT 'KO'KO,'Nota no es Credito, Debe ingresar el detalle individualmente'ERROR
			RETURN
		END
		BEGIN TRY           
			EXEC SPK_GENITEMS_NOTACR @CNSFNOT,@CLASE,@USUARIO                   
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK,@CNSFNOT CNSFNOT
		RETURN 
	END   
	IF @METODO='FNOT_DELDETA'     
	BEGIN   
		SELECT @CNSFNOT=CNSFNOT,@CLASE=CLASE       
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			CNSFNOT VARCHAR(20) '$.CNSFNOT',
			CLASE   VARCHAR(2) '$.CLASE'
			)   
            
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			SELECT 'KO'KO,'Nota no encontrada, Verifique e intente de nuevo'ERROR
			RETURN
		END
		BEGIN TRY           
			EXEC SPK_DESITEMS_NOTACR @CNSFNOT,@CLASE,@USUARIO                   
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK,@CNSFNOT CNSFNOT
		RETURN 
	END  
	IF @METODO='FNOT_APLICAR'     
	BEGIN   
		SELECT @CNSFNOT=CNSFNOT,@CLASE=CLASE       
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			CNSFNOT VARCHAR(20) '$.CNSFNOT',
			CLASE   VARCHAR(2) '$.CLASE'
			)   
            
		IF NOT EXISTS(SELECT 1 FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			SELECT 'KO'KO,'Nota no encontrada, Verifique e intente de nuevo'ERROR
			RETURN
		END
		IF NOT EXISTS(SELECT 1 FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			SELECT 'KO'KO,'Nota Sin Detalles, no se puede Aplicar, Verifique e intente de nuevo 'ERROR
			RETURN
		END
		SELECT @F_NOTA=F_NOTA,@VALOR=VR_TOTAL,@N_FACTURA=N_FACTURA,@CNSCXC=CNSCXC 
		FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE

		IF NOT EXISTS(SELECT 1 FROM PRI WHERE FECHA_INI<=@F_NOTA AND FECHA_FIN>=@F_NOTA AND COALESCE(CERRADO_CARTERA,0)=0)
		BEGIN
			SELECT 'KO'KO,'Periodo de Cartera Cerrado o no Existe, Verique e Intente de Nuevo'ERROR
			RETURN
		END
		IF NOT EXISTS(SELECT 1 FROM PRI WHERE FECHA_INI<=@F_NOTA AND FECHA_FIN>=@F_NOTA AND COALESCE(CERRADO,0)=0)
		BEGIN
			SELECT 'KO'KO,'Periodo de Contable Cerrado o no Existe, Verique e Intente de Nuevo'ERROR
			RETURN
		END
		IF COALESCE(@VALOR,0)<=0
		BEGIN
			SELECT 'KO'KO,'El valor de la nota Credito no Puede ser Menor o Igual a Cero'ERROR
			RETURN
		END
        IF EXISTS(SELECT 1 FROM FTR WHERE N_FACTURA=@N_FACTURA AND ESTADO='P' AND COALESCE(TIPOANULACION,'')='' AND VR_TOTAL<=@VALOR) AND @CLASE<>'D'
		BEGIN
			SELECT 'KO'KO,'Inconsistencia. No se permite aplicar una nota por el 100% del valor de la factura, se debe anular desde el modulo de facturación 'ERROR
			RETURN
		END      
		IF NOT EXISTS(SELECT 1 FROM FTR WHERE N_FACTURA=@N_FACTURA AND ESTADO='P' AND COALESCE(TIPOANULACION,'')='')
		BEGIN
			SELECT 'KO'KO,'Inconsistencia en la Factura, Verifique el estado de la Factura'ERROR
			RETURN
		END
		IF @CLASE='C'
		BEGIN
			EXEC SPK_RELIQUIDA_FTR @CNSCXC,@N_FACTURA
		END
		IF @CLASE='C' AND NOT EXISTS(SELECT 1 FROM VWK_CXCDIASVTO WHERE N_FACTURA=@N_FACTURA AND CNSCXC=CASE WHEN COALESCE(@CNSCXC,'')='' THEN 'NO RADICADA' ELSE @CNSCXC END AND SALDONETO>=@VALOR AND TIPO='F' AND CLASEINFO='SINGLO' )
		BEGIN
			SELECT 'KO'KO,'Verique los Saldos, el Saldo de la Factura no cubre el Valor de la Nota 'ERROR
			RETURN
		END
		SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		WHERE USUSU.USUARIO=@USUARIO

		BEGIN TRY   
			EXEC SPK_NOTASCXC @CNSFNOT,@CLASE,'',@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME               
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK,@CNSFNOT CNSFNOT
		RETURN 
	END
	IF @METODO='CARGAR_NOTAS'
	BEGIN
			
		DECLARE @LINEA AS VARCHAR(MAX)

      SELECT  @NROLINEAS=COUNT(*)
		FROM OPENJSON(@PARAMETROS, '$.LINEAS') 

      IF @NROLINEAS>0
      BEGIN

		   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		   @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		   WHERE USUSU.USUARIO=@USUARIO

         SELECT @CNSRPDX=''
		   EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSRPDX OUTPUT  
		   SELECT @CNSRPDX = @IDSEDE+REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0) 

		   DECLARE SUBIR_CURSOR CURSOR FOR   
	      SELECT VALUE 
		   FROM OPENJSON(@PARAMETROS, '$.LINEAS')		  
		   OPEN SUBIR_CURSOR  
		   FETCH NEXT FROM SUBIR_CURSOR INTO @LINEA
		   WHILE @@FETCH_STATUS = 0  
		   BEGIN  	  
            SELECT
               @N_FACTU     = MAX(CASE WHEN ORD = 1 THEN VAL END),
               @IDCONCEPTO  = MAX(CASE WHEN ORD = 2 THEN VAL END),
               @DESCONCEPTO = MAX(CASE WHEN ORD = 3 THEN VAL END),
               @VALOR       = CONVERT(DECIMAL(14,2), NULLIF(LTRIM(RTRIM(MAX(CASE WHEN ORD = 4 THEN VAL END))), N'')),
               @OBSERVA     = MAX(CASE WHEN ORD = 5 THEN VAL END)
            FROM DBO.FNK_SPLIT_TEXCEL(CAST(@LINEA AS NVARCHAR(MAX)), 5);

            SET @ERROR=''
            IF NOT EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTU AND ESTADO='P' AND COALESCE(TIPOANULACION,'')='')
            BEGIN
               SELECT @IDTER='',@RAZONS=''
               SET @ERROR += 'Factura no existe o se encuentra anulada, no se puede procesar'
            END
            ELSE 
            BEGIN
               SELECT @IDTER=TER.NIT,@RAZONS=RAZONSOCIAL
               FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO 
               WHERE N_FACTURA=@N_FACTU
            END
            IF NOT EXISTS(SELECT * FROM VWK_CXCDIASVTO WHERE N_FACTURA=@N_FACTU AND TIPO='F' AND SALDONETO>=@VALOR)
            BEGIN
               SET @ERROR +='Factura no tiene Saldo en Cartera en su tipo F no se puede subir'
            END
            IF NOT EXISTS(SELECT * FROM CPNT WHERE CODIGO=@IDCONCEPTO)
            BEGIN
               SET @ERROR +='Id.Concpeto no existe, o no esta homologando ante la Dian'
            END
            IF COALESCE(@VALOR,0)<=0
            BEGIN
               SET @ERROR +='Valor de la nota no puede ser menor o igual a cero, No se Puede Subir' 
            END

            INSERT INTO RPDX(CNS,ID1,ID2,ID3,STRINGMEDIO2,STRINGMEDIO1,VALOR1,STRINGGRANDE1,STRINGGRANDE2,CANTIDAD)
            SELECT @CNSRPDX,@N_FACTU,@IDCONCEPTO,@IDTER,@DESCONCEPTO,@RAZONS,@VALOR,@OBSERVA,@ERROR,CASE WHEN LEN(@ERROR)>1 THEN 1 ELSE 0 END 

		   FETCH NEXT FROM SUBIR_CURSOR INTO @LINEA
		   END  
		  
		   CLOSE SUBIR_CURSOR  
		   DEALLOCATE SUBIR_CURSOR  

         SELECT @NROLINEAS=COUNT(*) FROM RPDX WHERE CNS=@CNSRPDX AND CANTIDAD=1


         SELECT 'OK' OK,@CNSRPDX CNSRPDX,@NROLINEAS ERRADOS
         RETURN

      END
      ELSE
      BEGIN
         SELECT 'KO','No se encontraron Datos para Procesar, Verfique e intente de nuevo' ERROR
         RETURN
      END
	END
	/* Carga masiva por lotes desde JSON (front): primera llamada sin CNSRPDX genera consecutivo;
	   siguientes lotes reutilizan el mismo CNSRPDX para acumular filas en RPDX (mismo flujo que CNSSUBIR en FPAG). */
	IF @METODO='CARGAR_NOTAS_LOTE'
	BEGIN
		DECLARE @LINEA_LOTE AS VARCHAR(MAX)
		DECLARE @CNSRPDX_SOL VARCHAR(20) = NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.CNSRPDX'))), '')
		DECLARE @CLASE_LOTE VARCHAR(2) = NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.CLASE'))), '')
		DECLARE @ANULARFACT_LOTE VARCHAR(2) = 'NO'
		DECLARE @FACTE_FTR SMALLINT
		DECLARE @VR_TOTAL_FTR DECIMAL(14, 2)
		DECLARE @SALDO_FTR DECIMAL(14, 2)

		SELECT  @NROLINEAS=COUNT(*)
		FROM OPENJSON(@PARAMETROS, '$.LINEAS')

		IF @NROLINEAS>0
		BEGIN
			SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
			@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
			FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
			WHERE USUSU.USUARIO=@USUARIO

			IF @CNSRPDX_SOL IS NOT NULL
			BEGIN
				IF NOT EXISTS(SELECT 1 FROM RPDX WHERE CNS=@CNSRPDX_SOL)
				BEGIN
					SELECT 'KO' OK,'El CNSRPDX indicado no existe en RPDX. Revise el lote o reinicie la carga.' ERROR
					RETURN
				END
				SET @CNSRPDX=@CNSRPDX_SOL
			END
			ELSE
			BEGIN
				SELECT @CNSRPDX=''
				EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSRPDX OUTPUT
				SELECT @CNSRPDX = @IDSEDE+REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
			END

			DECLARE SUBIR_CURSOR_LOTE CURSOR FOR
			SELECT [value]
			FROM OPENJSON(@PARAMETROS, '$.LINEAS')
			OPEN SUBIR_CURSOR_LOTE
			FETCH NEXT FROM SUBIR_CURSOR_LOTE INTO @LINEA_LOTE
			WHILE @@FETCH_STATUS = 0
			BEGIN
				SET @ANULARFACT_LOTE = 'NO'

				IF @CLASE_LOTE = 'C'
				BEGIN
					SELECT
						@N_FACTU     = MAX(CASE WHEN ORD = 1 THEN VAL END),
						@IDCONCEPTO  = MAX(CASE WHEN ORD = 2 THEN VAL END),
						@DESCONCEPTO = MAX(CASE WHEN ORD = 3 THEN VAL END),
						@VALOR       = CONVERT(DECIMAL(14,2), NULLIF(LTRIM(RTRIM(MAX(CASE WHEN ORD = 4 THEN VAL END))), N'')),
						@OBSERVA     = MAX(CASE WHEN ORD = 5 THEN VAL END),
						@ANULARFACT_LOTE = UPPER(LTRIM(RTRIM(MAX(CASE WHEN ORD = 6 THEN VAL END))))
					FROM DBO.FNK_SPLIT_TEXCEL(CAST(@LINEA_LOTE AS NVARCHAR(MAX)), 6);
				END
				ELSE
				BEGIN
					SELECT
						@N_FACTU     = MAX(CASE WHEN ORD = 1 THEN VAL END),
						@IDCONCEPTO  = MAX(CASE WHEN ORD = 2 THEN VAL END),
						@DESCONCEPTO = MAX(CASE WHEN ORD = 3 THEN VAL END),
						@VALOR       = CONVERT(DECIMAL(14,2), NULLIF(LTRIM(RTRIM(MAX(CASE WHEN ORD = 4 THEN VAL END))), N'')),
						@OBSERVA     = MAX(CASE WHEN ORD = 5 THEN VAL END)
					FROM DBO.FNK_SPLIT_TEXCEL(CAST(@LINEA_LOTE AS NVARCHAR(MAX)), 5);
				END

				SET @ERROR=''
				SET @FACTE_FTR = NULL
				SET @VR_TOTAL_FTR = NULL
				SET @SALDO_FTR = NULL
				IF @CLASE_LOTE = 'C' AND @ANULARFACT_LOTE NOT IN ('SI', 'NO')
				BEGIN
					SET @ERROR += 'ANULARFACT debe ser SI o NO'
				END
				IF NOT EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTU AND ESTADO='P' AND COALESCE(TIPOANULACION,'')='')
				BEGIN
					SELECT @IDTER='',@RAZONS=''
					SET @ERROR += 'Factura no existe o se encuentra anulada, no se puede procesar'
				END
				ELSE
				BEGIN
					SELECT @IDTER=TER.NIT,@RAZONS=RAZONSOCIAL,
						@FACTE_FTR=FTR.FACTE,@VR_TOTAL_FTR=FTR.VR_TOTAL
					FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
					WHERE N_FACTURA=@N_FACTU
				END
				IF @CLASE_LOTE = 'C' AND LEN(@ERROR) = 0
				BEGIN
					IF COALESCE(@FACTE_FTR, 0) NOT IN (2, 6)
						SET @ERROR += 'La factura debe estar notificada (FACTE=2) o prevalidada (FACTE=6) ante la DIAN'
				END
				IF @CLASE_LOTE = 'C' AND @ANULARFACT_LOTE = 'SI' AND LEN(@ERROR) = 0
				BEGIN
					SELECT TOP 1 @SALDO_FTR = SALDONETO
					FROM VWK_CXCDIASVTO
					WHERE N_FACTURA = @N_FACTU AND TIPO = 'F' AND CLASEINFO = 'SINGLO'
					ORDER BY SALDONETO DESC
					IF COALESCE(@VALOR, 0) <> COALESCE(@VR_TOTAL_FTR, 0)
						OR COALESCE(@SALDO_FTR, 0) <> COALESCE(@VR_TOTAL_FTR, 0)
						SET @ERROR += 'Para anular la factura (ANULARFACT=SI) el valor de la nota y el saldo en cartera deben ser iguales al valor total de la factura (VR_TOTAL)'
				END
				IF NOT EXISTS(SELECT * FROM VWK_CXCDIASVTO WHERE N_FACTURA=@N_FACTU AND TIPO='F' AND SALDONETO>=@VALOR)
				BEGIN
					SET @ERROR +='Factura no tiene Saldo en Cartera en su tipo F no se puede subir'
				END
				IF NOT EXISTS(SELECT * FROM CPNT WHERE CODIGO=@IDCONCEPTO)
				BEGIN
					SET @ERROR +='Id.Concpeto no existe, o no esta homologando ante la Dian'
				END
				IF COALESCE(@VALOR,0)<=0
				BEGIN
					SET @ERROR +='Valor de la nota no puede ser menor o igual a cero, No se Puede Subir'
				END

				INSERT INTO RPDX(CNS,ID1,ID2,ID3,STRINGMEDIO2,STRINGMEDIO1,VALOR1,STRINGGRANDE1,STRINGMEDIO3,STRINGGRANDE2,CANTIDAD)
				SELECT @CNSRPDX,@N_FACTU,@IDCONCEPTO,@IDTER,@DESCONCEPTO,@RAZONS,@VALOR,@OBSERVA,
					CASE WHEN @CLASE_LOTE = 'C' THEN @ANULARFACT_LOTE ELSE NULL END,
					@ERROR,CASE WHEN LEN(@ERROR)>1 THEN 1 ELSE 0 END

				FETCH NEXT FROM SUBIR_CURSOR_LOTE INTO @LINEA_LOTE
			END

			CLOSE SUBIR_CURSOR_LOTE
			DEALLOCATE SUBIR_CURSOR_LOTE

			SELECT @NROLINEAS=COUNT(*) FROM RPDX WHERE CNS=@CNSRPDX AND CANTIDAD=1

			SELECT 'OK' OK,@CNSRPDX CNSRPDX,@NROLINEAS ERRADOS
			RETURN
		END
		ELSE
		BEGIN
			SELECT 'KO','No se encontraron Datos para Procesar, Verfique e intente de nuevo' ERROR
			RETURN
		END
	END
   IF @METODO='FNOT_CREARMASIVO'     
   BEGIN         
      DECLARE @JSON_FTR NVARCHAR(MAX)
      DECLARE @NF_ANULAR VARCHAR(20)
      DECLARE @OBS_ANULAR VARCHAR(512)
      DECLARE @ITEM_ANULAR INT
      DECLARE @MSG_ANULAR VARCHAR(MAX)
      DECLARE @CNT_OK INT
      DECLARE @CNT_ERR INT
      DECLARE @MSG_NOTA VARCHAR(80)

      SELECT @CNSRPDX=CNSRPDX,@CLASE=CLASE        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
        CNSRPDX VARCHAR(20) '$.CNSRPDX',
        CLASE VARCHAR(2) '$.CLASE'
            )
      IF NOT EXISTS(SELECT * FROM RPDX WHERE CNS=@CNSRPDX)
      BEGIN
         SELECT 'KO'KO,'El Consecutivo no fue encontrado.'ERROR
         RETURN
      END
		SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		WHERE USUSU.USUARIO=@USUARIO

      SET @MSG_NOTA = CASE WHEN @CLASE = 'C' THEN 'Nota crédito creada' ELSE 'Nota débito creada' END

      IF OBJECT_ID('tempdb..#LOG_MASIVO') IS NOT NULL
         DROP TABLE #LOG_MASIVO

      SELECT
         ITEM,
         ID1 AS N_FACTURA,
         ID2 AS IDCONCEPTO,
         VALOR1 AS VALOR,
         STRINGGRANDE1 AS OBSERVACION,
         UPPER(LTRIM(RTRIM(COALESCE(STRINGMEDIO3, '')))) AS ANULARFACT,
         CAST(CASE WHEN COALESCE(CANTIDAD, 0) = 1 THEN 'ERROR' ELSE 'PENDIENTE' END AS VARCHAR(12)) AS ESTADO,
         CAST(CASE WHEN COALESCE(CANTIDAD, 0) = 1 THEN COALESCE(STRINGGRANDE2, 'Fila no validada') ELSE '' END AS VARCHAR(MAX)) AS MENSAJE
      INTO #LOG_MASIVO
      FROM RPDX
      WHERE CNS = @CNSRPDX

      DELETE RPDX WHERE CNS=@CNSRPDX AND CANTIDAD=1

      /* Notas crédito con ANULARFACT=SI: se reservan para ANULARFAC (FTR_COL); el resto sigue SPK_APLICA_FNOT_MASIVA. */
      IF @CLASE = 'C'
      BEGIN
         IF OBJECT_ID('tempdb..#ANULAR_FACT_MASIVO') IS NOT NULL
            DROP TABLE #ANULAR_FACT_MASIVO

         SELECT ITEM, ID1 AS N_FACTURA, STRINGGRANDE1 AS OBSERVACION
         INTO #ANULAR_FACT_MASIVO
         FROM RPDX
         WHERE CNS = @CNSRPDX
           AND UPPER(LTRIM(RTRIM(COALESCE(STRINGMEDIO3, '')))) = 'SI'

         DELETE FROM RPDX
         WHERE CNS = @CNSRPDX
           AND UPPER(LTRIM(RTRIM(COALESCE(STRINGMEDIO3, '')))) = 'SI'         
      END

      IF EXISTS (SELECT 1 FROM RPDX WHERE CNS = @CNSRPDX)
      BEGIN
			
         BEGIN TRY           
            EXEC SPK_APLICA_FNOT_MASIVA @CNSRPDX, @COMPANIA, @IDSEDE, @USUARIO, @CLASE
            UPDATE #LOG_MASIVO
            SET ESTADO = 'OK', MENSAJE = @MSG_NOTA
            WHERE ESTADO = 'PENDIENTE'
              AND (@CLASE <> 'C' OR UPPER(COALESCE(ANULARFACT, '')) <> 'SI')
         END TRY
         BEGIN CATCH
            --INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()

            UPDATE #LOG_MASIVO
            SET ESTADO = 'ERROR', MENSAJE = ERROR_MESSAGE()
            WHERE ESTADO = 'PENDIENTE'
              AND (@CLASE <> 'C' OR UPPER(COALESCE(ANULARFACT, '')) <> 'SI')
         END CATCH
      END

      IF @CLASE = 'C' AND OBJECT_ID('tempdb..#ANULAR_FACT_MASIVO') IS NOT NULL
      BEGIN
         DECLARE CUR_ANULAR_FACT_MASIVO CURSOR LOCAL FAST_FORWARD FOR
            SELECT ITEM, N_FACTURA, OBSERVACION
            FROM #ANULAR_FACT_MASIVO

         OPEN CUR_ANULAR_FACT_MASIVO
         FETCH NEXT FROM CUR_ANULAR_FACT_MASIVO INTO @ITEM_ANULAR, @NF_ANULAR, @OBS_ANULAR
         WHILE @@FETCH_STATUS = 0
         BEGIN

            SET @JSON_FTR = (
               SELECT
                  'FTR_COL' AS MODELO,
                  'ANULARFAC' AS METODO,
                  @USUARIO AS USUARIO,
                  JSON_QUERY((
                     SELECT
                        @NF_ANULAR AS N_FACTURA,
                        @USUARIO AS USUANULA,
                        COALESCE(NULLIF(LTRIM(RTRIM(@OBS_ANULAR)), N''), N'Anulación masiva notas crédito') AS OBSANULA,
                        CAST(0 AS BIT) AS PART
                     FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
                  )) AS PARAMETROS
               FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
            )

            IF OBJECT_ID('tempdb..#R_ANULAR_FTR') IS NOT NULL
               DROP TABLE #R_ANULAR_FTR
            /* ANULARFAC devuelve 2 resultsets (OK/KO y luego ERROR); INSERT EXEC los une en una columna. */
            CREATE TABLE #R_ANULAR_FTR (MSG VARCHAR(MAX))

            BEGIN TRY
               INSERT INTO #R_ANULAR_FTR (MSG)
               EXEC SPQ_FTR_COL @JSON_FTR

               SET @MSG_ANULAR = NULL
               SELECT @MSG_ANULAR = COALESCE(@MSG_ANULAR + ' | ', '') + MSG
               FROM #R_ANULAR_FTR
               WHERE MSG NOT IN ('OK', 'KO')

               IF COALESCE(@MSG_ANULAR, '') <> ''
               BEGIN
                  UPDATE #LOG_MASIVO
                  SET ESTADO = 'ERROR', MENSAJE = @MSG_ANULAR
                  WHERE ITEM = @ITEM_ANULAR
               END
               ELSE IF EXISTS (SELECT 1 FROM #R_ANULAR_FTR WHERE MSG = 'KO')
                  OR NOT EXISTS (SELECT 1 FROM #R_ANULAR_FTR WHERE MSG = 'OK')
               BEGIN
                  UPDATE #LOG_MASIVO
                  SET ESTADO = 'ERROR', MENSAJE = 'Error al anular la factura mediante ANULARFAC.'
                  WHERE ITEM = @ITEM_ANULAR
               END
               ELSE
               BEGIN
                  UPDATE #LOG_MASIVO
                  SET ESTADO = 'OK', MENSAJE = 'Factura anulada mediante ANULARFAC'
                  WHERE ITEM = @ITEM_ANULAR
               END
            END TRY
            BEGIN CATCH
               UPDATE #LOG_MASIVO
               SET ESTADO = 'ERROR', MENSAJE = ERROR_MESSAGE()
               WHERE ITEM = @ITEM_ANULAR
            END CATCH

            DROP TABLE #R_ANULAR_FTR

            FETCH NEXT FROM CUR_ANULAR_FACT_MASIVO INTO @ITEM_ANULAR, @NF_ANULAR, @OBS_ANULAR
         END

         CLOSE CUR_ANULAR_FACT_MASIVO
         DEALLOCATE CUR_ANULAR_FACT_MASIVO
         DROP TABLE #ANULAR_FACT_MASIVO
      END

      UPDATE #LOG_MASIVO
      SET ESTADO = 'ERROR', MENSAJE = COALESCE(NULLIF(MENSAJE, ''), 'No procesada')
      WHERE ESTADO = 'PENDIENTE'

      SELECT @CNT_OK = COUNT(*) FROM #LOG_MASIVO WHERE ESTADO = 'OK'
      SELECT @CNT_ERR = COUNT(*) FROM #LOG_MASIVO WHERE ESTADO = 'ERROR'

      IF @CNT_ERR > 0
      BEGIN
         /* OK en el 1.er resultset para no disparar el diálogo global Aviso Importante.
            El detalle va en recordsets[1] solo para el Excel de log. */
         SELECT 'OK' OK, 'KO' RESULTADO, @CNT_OK OKCOUNT, @CNT_ERR ERRCOUNT
         SELECT ITEM, N_FACTURA, ANULARFACT, VALOR, OBSERVACION, ESTADO, MENSAJE
         FROM #LOG_MASIVO
         ORDER BY ITEM
         RETURN
      END
      DELETE RPDX WHERE CNS=@CNSRPDX
      SELECT 'OK' OK, 'OK' RESULTADO, @CNT_OK OKCOUNT, @CNT_ERR ERRCOUNT
      SELECT ITEM, N_FACTURA, ANULARFACT, VALOR, OBSERVACION, ESTADO, MENSAJE
      FROM #LOG_MASIVO
      ORDER BY ITEM
      RETURN       
   END   
   IF @METODO='FNOT_LIMPIARPDX'     
   BEGIN         
      SELECT @CNSRPDX=CNSRPDX      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
        CNSRPDX VARCHAR(20) '$.CNSRPDX'
      )
      IF EXISTS(SELECT * FROM RPDX WHERE CNS=@CNSRPDX)
      BEGIN
         DELETE RPDX WHERE CNS=@CNSRPDX
      END
      SELECT 'OK' OK
      RETURN
    END
   IF @METODO='FNOT_CRUDFNOTD'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
      SELECT @PROCESO=PROCESO, @CNSFNOT=CNSFNOT,@CLASE=CLASE,@ITEM=CONVERT(INT,ITEM),@TIPO=TIPO,@N_FACTURA=N_FACTURA,@N_CUOTA=N_CUOTA,@IDSERVICIO=IDSERVICIO,
             @DESCRIPCION=DESCRIPCION,@PREFIJO=PREFIJO,@IDAREA=IDAREA,@CCOSTO=CCOSTO,@CANTIDAD=CANTIDAD,@VR_UNITARIO=VR_UNITARIO,
             @VR_TOTAL=VR_TOTAL,@OBSERVACION=OBSERVACION,@VIVA =VIVA,@PIVA =PIVA            
      FROM   OPENJSON (@DATOS)
      WITH   ( 
         PROCESO VARCHAR(20)           '$.PROCESO',
         CNSFNOT VARCHAR(20)           '$.CNSFNOT',
         CLASE VARCHAR(20)             '$.CLASE',
         ITEM  VARCHAR(10)             '$.item',
         TIPO VARCHAR(3)               '$.TIPO',
         N_FACTURA VARCHAR(20)         '$.N_FACTURA',
         N_CUOTA INT                   '$.N_CUOTA',
         IDSERVICIO VARCHAR(20)        '$.IDSERVICIO',
         DESCRIPCION VARCHAR(120)      '$.DESCRIPCION',
         PREFIJO VARCHAR(20)           '$.PREFIJO',
         IDAREA  VARCHAR(20)           '$.IDAREA',
         CCOSTO VARCHAR(20)            '$.CCOSTO',
         CANTIDAD INT                  '$.CANTIDAD',
         VR_UNITARIO DECIMAL(14,2)     '$.VR_UNITARIO',
         VIVA  DECIMAL(14,2)   '$.VIVA',
         PIVA  DECIMAL(7,2)   '$.PIVA',
         VR_TOTAL DECIMAL(14,2)        '$.VR_TOTAL',
         OBSERVACION VARCHAR(256)      '$.OBSERVACION'      
      )  
      
      IF NOT EXISTS(SELECT  * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND ESTADO='O' AND CERRADA=0)
      BEGIN
         SELECT 'KO'KO,'Nota No Encontrada, Revise e intente de nuevo'ERROR
         RETURN
      END
      IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
      BEGIN
         SELECT @VR_UNITARIO=@VR_TOTAL
      END
      IF @PROCESO='Nuevo'
      BEGIN
		   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		   @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		   WHERE USUSU.USUARIO=@USUARIO

         SELECT @ITEM=COALESCE(MAX(ITEM),0)+1 FROM FNOTD WHERE  CNSFNOT=@CNSFNOT AND CLASE=@CLASE
         
         BEGIN TRY           
            INSERT INTO FNOTD(CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO, VR_TOTAL, COMPANIA, 
                              USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA, CCOSTO, IDAREA, PREFIJO, CUENTA )
            SELECT @CNSFNOT, @CLASE, @ITEM, @TIPO, @IDSERVICIO, @DESCRIPCION, @CANTIDAD, @VR_UNITARIO, @VR_TOTAL, @COMPANIA, 
                   @USUARIO, @OBSERVACION, @N_CUOTA, @PIVA, @VIVA, @N_FACTURA, @CCOSTO, @IDAREA, @PREFIJO, NULL  
       
            IF EXISTS(SELECT * FROM FTRD WHERE N_FACTURA=@N_FACTURA AND N_CUOTA=@N_CUOTA)
            BEGIN
               UPDATE FTRD SET VLRNOTACR=COALESCE(VLRNOTACR,0)+@VR_TOTAL   WHERE N_FACTURA=@N_FACTURA AND N_CUOTA=@N_CUOTA
            END
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         IF @PROCESO='Editar'
         BEGIN
            IF EXISTS(SELECT * FROM FTRD WHERE N_FACTURA=@N_FACTURA AND N_CUOTA=@N_CUOTA)
            BEGIN
               SELECT @VLR_ITEM=VR_TOTAL FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND  ITEM=@ITEM AND CLASE=@CLASE
               IF @VLR_ITEM<>@VR_TOTAL
               BEGIN
                  UPDATE FTRD SET VLRNOTACR=VLRNOTACR-@VLR_ITEM WHERE N_FACTURA=@N_FACTURA AND N_CUOTA=@N_CUOTA
                  UPDATE FTRD SET VLRNOTACR=VLRNOTACR+@VR_TOTAL WHERE N_FACTURA=@N_FACTURA AND N_CUOTA=@N_CUOTA
               END
            END
            UPDATE FNOTD SET IDSERVICIO = @IDSERVICIO, DESCRIPCION = @DESCRIPCION, CANTIDAD = @CANTIDAD, VR_UNITARIO = @VR_UNITARIO,
                             VR_TOTAL = @VR_TOTAL, N_CUOTA = @N_CUOTA, N_FACTURA = @N_FACTURA, CCOSTO = @CCOSTO, PREFIJO = @PREFIJO,
                             IDAREA = @IDAREA, OBSERVACION = @OBSERVACION, PIVA = @PIVA, VALORIVA = @VIVA
            WHERE CNSFNOT=@CNSFNOT
            AND CLASE=@CLASE
            AND ITEM=@ITEM
         END
         ELSE
         BEGIN
            IF EXISTS(SELECT * FROM FTRD WHERE N_FACTURA=@N_FACTURA AND N_CUOTA=@N_CUOTA)
            BEGIN
               SELECT @VLR_ITEM=VR_TOTAL FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND  ITEM=@ITEM AND CLASE=@CLASE
               UPDATE FTRD SET VLRNOTACR=VLRNOTACR-@VLR_ITEM WHERE N_FACTURA=@N_FACTURA AND N_CUOTA=@N_CUOTA
            END
            DELETE FNOTD WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND ITEM=@ITEM
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @VR_TOTAL=SUM(VR_TOTAL) FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE
      UPDATE FNOT SET VR_TOTAL=@VR_TOTAL WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE
      SELECT 'OK' OK
      RETURN 
  END
	IF @METODO='FNOT_ANULANOTA'     
	BEGIN   
		SELECT @CNSFNOT=CNSFNOT,@CLASE=CLASE,@USUARIOSOL=USUARIOSOL,@RAZONANULA=RAZONANULA     
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			CNSFNOT VARCHAR(20) '$.CNSFNOT',
			CLASE   VARCHAR(2) '$.CLASE',
         USUARIOSOL VARCHAR(20) '$.USUARIOSOL',
         RAZONANULA VARCHAR(255) '$.RAZONANULA'
			)   
            
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			SELECT 'KO'KO,'Nota no encontrada, Verifique e intente de nuevo'ERROR
			RETURN
		END
		
        IF EXISTS(SELECT 1 FROM FNOT WHERE CNSFNOT=@CNSFNOT AND COALESCE(FACTE,0)<>0)
		BEGIN
			SELECT 'KO'KO,'La NOTA no puede ser Anulada porque corresponde a una factura Electronica y ya se ha procesado.','Facturacion Electronica'ERROR
			RETURN
		END
		
		
      SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		WHERE USUSU.USUARIO=@USUARIO
      SELECT @NROCOMPROBANTE=NROCOMPROBANTE,@PROCEDENCIA=PROCEDENCIA FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE 
		BEGIN TRY           
			EXEC DBO.SPK_ANULANOTA_CR @CNSFNOT,@NROCOMPROBANTE,'',@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,@PROCEDENCIA     --AQUI SE DEBE VALIDAR LA PROCEDENCIA PARA DEFINIR EL TIPO DE ANULACION             
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
      UPDATE FNOT SET ESTADO='A',USUARIOANU=@USUARIO,USUARIOSOL=@USUARIOSOL,
      FECHAANU=DBO.FNK_GETDATE(),RAZONANU=@RAZONANULA 
      WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE

		SELECT 'OK' OK,@CNSFNOT CNSFNOT
		RETURN 
	END  
   IF @METODO='FNOT_ENVIARSUNAT'     
   BEGIN         
      SELECT @CNSFNOT=CNSFNOT, @N_FACTURA=N_FACTURA       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSFNOT  VARCHAR(20)   '$.CNSFNOT',
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )
      IF @IXCOUNTRY !='PERU'
      BEGIN
         SELECT 'KO' AS KO, 'Variable pais no es Per'+NCHAR(250) AS ERROR
         RETURN
      END
      IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND N_FACTURA=@N_FACTURA AND COALESCE(FACTEP,'')<>'OK')
      BEGIN
         SELECT 'KO'KO,'Nota No esta Pendiente de Enviar 'ERROR
         RETURN
      END
      BEGIN TRY           
         EXEC SPK_GENERA_JSON_PERU_NOTADBCR @CNSFNOT,@N_FACTURA               
      END TRY
      BEGIN CATCH
              INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='FNOT_ENCOLAR'     
   BEGIN
      DECLARE @FACTE_DEST SMALLINT
      DECLARE @FACTE_FTR_ENC SMALLINT
      DECLARE @N_FACTURA_ENC VARCHAR(20)
      DECLARE @PREVALIDA_ACTIVA VARCHAR(20)

      SELECT @CNSFNOT= CNSFNOT      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSFNOT  VARCHAR(20)   '$.CNSFNOT'
      )

      SET @PREVALIDA_ACTIVA = UPPER(COALESCE(DBO.FNK_VALORVARIABLE('FTR_PREVALIDA_ACTIVA'), 'NO'))
      SET @FACTE_DEST = 1
      SET @FACTE_FTR_ENC = NULL
      SET @N_FACTURA_ENC = NULL

      SELECT @N_FACTURA_ENC = NULLIF(LTRIM(RTRIM(N_FACTURA)), '')
      FROM FNOT WHERE CNSFNOT = @CNSFNOT

      IF @N_FACTURA_ENC IS NOT NULL
         AND EXISTS (SELECT 1 FROM FTR WHERE N_FACTURA = @N_FACTURA_ENC)
      BEGIN
         SELECT @FACTE_FTR_ENC = COALESCE(FACTE, 0)
         FROM FTR WHERE N_FACTURA = @N_FACTURA_ENC

         IF @FACTE_FTR_ENC = 6
            SET @FACTE_DEST = 5
         ELSE IF @FACTE_FTR_ENC = 2
            SET @FACTE_DEST = 1
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Factura ' + @N_FACTURA_ENC + ' no se ha notificado a la DIAN (requiere FACTE=2) ni prevalidada (FACTE=6)'
         END
      END
      ELSE
      BEGIN
         -- Nota sin factura asociada: variable SI ? cola prevalidacion (5)
         IF @PREVALIDA_ACTIVA = 'SI'
            SET @FACTE_DEST = 5
      END

      IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND (CERRADA=0 OR ESTADO='A'))
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se puede enviar a la Dian una nota '+ IIF(CERRADA=0,'Sin Confirmar','Anulada') FROM FNOT WHERE CNSFNOT=@CNSFNOT
      END
      IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND FACTE IN (1,5) AND  CONVERT(DATE,F_NOTA)=CONVERT(DATE,DBO.FNK_GETDATE()))
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Esta nota ya esta en proceso de envio, Validar proceso Dian '
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND (FACTE=1 OR FACTE=3 OR FACTE=5 OR  CONVERT(DATE,F_NOTA)<>CONVERT(DATE,DBO.FNK_GETDATE()))
                 AND MONTH(F_NOTA)=MONTH(DBO.FNK_GETDATE()))
      BEGIN
         UPDATE FNOT SET F_NOTA=DBO.FNK_GETDATE(),FACTE=@FACTE_DEST WHERE CNSFNOT=@CNSFNOT

         SELECT 'OK'OK
         RETURN
      END
      IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND (FACTE=1 OR FACTE=3 OR FACTE=5 OR  FACTE=0) AND  CONVERT(DATE,F_NOTA)<>CONVERT(DATE,DBO.FNK_GETDATE())
                 AND MONTH(F_NOTA)<MONTH(DBO.FNK_GETDATE()) AND DATEDIFF(MONTH,F_NOTA,DBO.FNK_GETDATE())<=3)
      BEGIN
         SELECT @NROCOMPROBANTE=NROCOMPROBANTE FROM FNOT WHERE CNSFNOT=@CNSFNOT
         IF EXISTS(SELECT *FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE)
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'El comprobante contable de esta nota presenta errores contables, no se puede continuar'
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         IF EXISTS(SELECT *FROM MCP INNER JOIN PRI ON MCP.ANOMES=PRI.ANOMES 
                    WHERE MCP.NROCOMPROBANTE=@NROCOMPROBANTE AND PRI.CERRADO=1)
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'El Periodo contable para el comprobante contable esta Cerrado, no se puede continuar'
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         UPDATE MCP SET FECHACONTABLE=DBO.FNK_GETDATE(),MES=MONTH(DBO.FNK_GETDATE()) WHERE NROCOMPROBANTE=@NROCOMPROBANTE
         UPDATE FNOT SET F_NOTA=DBO.FNK_GETDATE(),FACTE=@FACTE_DEST WHERE CNSFNOT=@CNSFNOT

         SELECT 'OK'OK
         RETURN
      END
      IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND COALESCE(FACTE,0)=0 AND  MONTH(F_NOTA)=MONTH(DBO.FNK_GETDATE()))
      BEGIN
         UPDATE FNOT SET F_NOTA= CASE WHEN  CONVERT(DATE,F_NOTA)<CONVERT(DATE,DBO.FNK_GETDATE()) THEN  DBO.FNK_GETDATE() ELSE F_NOTA END ,FACTE=@FACTE_DEST WHERE CNSFNOT=@CNSFNOT

         SELECT 'OK'OK
         RETURN
      END
   END
   IF @METODO='FNOT_DESENCOLAR'     
   BEGIN         
      SELECT @CNSFNOT= CNSFNOT      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSFNOT  VARCHAR(20)   '$.CNSFNOT' 
      ) 
      PRINT 'DESENCOLAR '+COALESCE(@CNSFNOT,'NO TENGO CNSFNOT')
      IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND (CERRADA=0 OR ESTADO='A'))
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se puede enviar a la Dian una nota '+ IIF(CERRADA=0,'Sin Confirmar','Anulada') FROM FNOT WHERE CNSFNOT=@CNSFNOT
      END
      IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND COALESCE(FACTE,0) NOT IN(1,3,5)) 
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'El estado de la nota no permite desencolar , Validar proceso Dian '
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      UPDATE FNOT SET FACTE=0 WHERE CNSFNOT=@CNSFNOT

      SELECT 'OK'OK
      RETURN

   END  
   IF @METODO='FNOT_ACTUALIZAR_FECHA'     
	BEGIN   
		SELECT @CNSFNOT=CNSFNOT, @CLASE=CLASE       
		FROM OPENJSON (@PARAMETROS)
		WITH (           
			CNSFNOT VARCHAR(20) '$.CNSFNOT',
			CLASE   VARCHAR(2)  '$.CLASE'
		)   
    
		-- Validar que la nota exista
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			SELECT 'KO' KO, 'Nota no encontrada, Verifique e intente de nuevo' ERROR
			RETURN
		END
    
		-- Validar que la nota est? cerrada
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND CERRADA=1)
		BEGIN
			SELECT 'KO' KO, 'La nota debe estar cerrada para actualizar la fecha' ERROR
			RETURN
		END
    
		-- Validar estados permitidos (FACTE 0, 1, 3 o 5)
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE 
					  AND (FACTE = '0' OR FACTE = '1' OR FACTE = '3' OR FACTE = '5'))
		BEGIN
			SELECT 'KO' KO, 'El estado de la nota no permite actualizar la fecha' ERROR
			RETURN
		END
    
		-- Validar que no est? anulada
		IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND ESTADO='Activo')
		BEGIN
			SELECT 'KO' KO, 'No se puede actualizar la fecha de una nota anulada' ERROR
			RETURN
		END
    
		-- Obtener informaci?n del usuario
		SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),
			   @COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
			   @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		FROM USUSU 
		LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		WHERE USUSU.USUARIO=@USUARIO
    
		BEGIN TRY
			-- Actualizar la fecha de la nota a la fecha/hora actual
			UPDATE FNOT 
			SET F_NOTA = DBO.FNK_GETDATE()
			WHERE CNSFNOT = @CNSFNOT 
			AND CLASE = @CLASE
        
			-- Si tiene comprobante contable, actualizar tambi?n la fecha contable
			SELECT @NROCOMPROBANTE = NROCOMPROBANTE 
			FROM FNOT 
			WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
        
			IF @NROCOMPROBANTE IS NOT NULL AND @NROCOMPROBANTE <> ''
			BEGIN              
			  -- Actualizar fecha del comprobante
				UPDATE MCP 
				SET FECHACONTABLE = DBO.FNK_GETDATE(),
					MES = MONTH(DBO.FNK_GETDATE())
				WHERE NROCOMPROBANTE = @NROCOMPROBANTE
			END
        
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
    
		IF(SELECT COUNT(*) FROM @TBLERRORES) > 0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
    
		SELECT 'OK' OK, @CNSFNOT CNSFNOT, 
			   CONVERT(VARCHAR(20), DBO.FNK_GETDATE(), 120) NUEVA_FECHA
		RETURN 
	END

END

