CREATE OR ALTER PROCEDURE DBO.SPQ_BMOV
@JSON  NVARCHAR(MAX)
WITH   ENCRYPTION
AS
DECLARE
       @PARAMETROS NVARCHAR(MAX)
	   , @MODELO     NVARCHAR(MAX)
	   , @METODO     VARCHAR(100)
	   , @MODELOACT	 NVARCHAR(MAX)
	   , @USUARIO    VARCHAR(20)
	   , @ID	     INT
	   , @BANCO		 VARCHAR(5)
	   , @SUCURSAL	 VARCHAR(2)
	   , @CTA_BCO    VARCHAR(20)
	   , @NODOCUMENTO VARCHAR(10)
	   , @DATO		 VARCHAR(10)
	   , @IDTERCERO  VARCHAR(20)
	   , @DESCRIPCION VARCHAR(30)
	   , @ITEM	     INT  -- STORRES 20260623 SE CAMBIA E TIPO DE CAMPO DE SMALLINT A INT.
	   , @ITEM2	     INT  -- STORRES 20260623 SE CAMBIA E TIPO DE CAMPO DE SMALLINT A INT.
	   , @VALOR      DECIMAL(14,2)
	   , @CNSFCXPP   VARCHAR(10)
	   , @CODCAJA    VARCHAR(10)
	   , @CNSFACJ    VARCHAR(10)
	   , @FECHA      VARCHAR(10)
	   , @SYS_COMPUTERNAME VARCHAR(100)
	   , @COMPANIA   VARCHAR(5)
	   , @IDSEDE     VARCHAR(5)
	   , @PROCEDENCIA  VARCHAR(20)
	   , @FECHAOPERACION VARCHAR(10)
	   , @IDOPERACION  VARCHAR(20)
	   , @VLROPERACION DECIMAL(9,2)
	   , @FECHAOK      VARCHAR(10)
	   , @GENCXP       BIT
	   , @RENGLON      INT
	   , @FORMAPAGO    VARCHAR(5)
	   , @BANCODOC     VARCHAR(5)
	   , @CUENTA       VARCHAR(50)
	   , @RECAUDO      SMALLINT
	   , @NROCOMPROBANTE VARCHAR(20)
	   , @ESTADO       VARCHAR(1)
	   , @COMPROBANTE  VARCHAR(2)
	   , @NOREFERENCIA VARCHAR(20)
	   , @ANO          VARCHAR(4)
	   , @MES          VARCHAR(2)
	   , @AHORA        DATETIME = CONVERT(SMALLDATETIME, GETDATE())
      ,@RNOMI         BIT
      ,@NOMINA        BIT
      ,@CCOSTO        VARCHAR(20)
      ,@DISTRIBUCION_JSON NVARCHAR(MAX)
	   ,@IDTERCERO_AGREGADOR VARCHAR(40)
      ,@IDTERCERONVO_DIST   VARCHAR(40)
      ,@VALORDISTRI         DECIMAL(14, 2)

DECLARE @TBLERRORES TABLE(CONTINUA VARCHAR(2), ERROR VARCHAR(500));
BEGIN
SET LANGUAGE Spanish;
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
   FROM OPENJSON (@json)
	WITH (
	   MODELO         VARCHAR(100)      '$.MODELO', 
	   METODO         VARCHAR(100)      '$.METODO',
	   USUARIO        VARCHAR(20)       '$.USUARIO',
	   PARAMETROS     NVARCHAR(MAX)  AS JSON
	)
  SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
  @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
  FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
   WHERE USUSU.USUARIO=@USUARIO
	IF @METODO = 'GUARDABMOV'
	BEGIN
		SELECT
			@BANCO			= JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL		= JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO		= JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@PROCEDENCIA    = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@ITEM			= JSON_VALUE(@PARAMETROS, '$.ITEM'),
			@FECHAOPERACION = JSON_VALUE(@PARAMETROS, '$.FECHAOPERACION'),
			@IDOPERACION    = JSON_VALUE(@PARAMETROS, '$.IDOPERACION'),
			@DESCRIPCION    = JSON_VALUE(@PARAMETROS, '$.DESCRIPCION'),
			@FECHAOK        = JSON_VALUE(@PARAMETROS, '$.FECHAOK'),
			@GENCXP         = JSON_VALUE(@PARAMETROS, '$.GENCXP'),
			@SYS_COMPUTERNAME  = JSON_VALUE(@PARAMETROS, '$.SYS_ComputerName'),
			@IDSEDE         = JSON_VALUE(@PARAMETROS, '$.IDSEDE'),
			@COMPANIA         = JSON_VALUE(@PARAMETROS, '$.COMPANIA'),
			@VALOR			= JSON_VALUE(@PARAMETROS, '$.VLROPERACION'),
			@CODCAJA         = JSON_VALUE(@PARAMETROS, '$.CAJA');


		   IF NOT EXISTS(SELECT ITEM FROM BMOV WHERE CTA_BCO = @CTA_BCO AND SUCURSAL = @SUCURSAL AND BANCO = @BANCO)
		   BEGIN
			 SELECT @ITEM = 1
		   END
		   ELSE 
		   BEGIN 
			SELECT @ITEM = MAX(ITEM)+1  FROM BMOV WHERE CTA_BCO = @CTA_BCO AND SUCURSAL = @SUCURSAL AND BANCO = @BANCO
		   END


		   IF NOT EXISTS(SELECT 1 FROM PRI WHERE ANO=YEAR(CAST(@FECHAOK + ' ' + CONVERT(VARCHAR(8), @AHORA, 108) AS DATETIME)) and MES=MONTH(CAST(@FECHAOK + ' ' + CONVERT(VARCHAR(8), @AHORA, 108) AS DATETIME)) AND COMPANIA = @COMPANIA)
		   BEGIN
			 SELECT 'KO'OK, 'No existe periodo contable'ERROR
			 RETURN
		   END

		   IF (SELECT CERRADO FROM PRI WHERE ANO=YEAR(CAST(@FECHAOK + ' ' + CONVERT(VARCHAR(8), @AHORA, 108) AS DATETIME)) and MES=MONTH(CAST(@FECHAOK + ' ' + CONVERT(VARCHAR(8), @AHORA, 108) AS DATETIME)) AND COMPANIA = @COMPANIA) = '1'
		   BEGIN
			 SELECT 'KO'OK, 'Periodo contable est? cerrado, no se puede contabilizar'ERROR
			 RETURN
		   END
         BEGIN TRY           
		      INSERT INTO BMOV ( BANCO, SUCURSAL, CTA_BCO, ITEM, FECHAOPERACION, NODOCUMENTO, IDOPERACION, VLROPERACION, DESCRIPCION, USUARIO, SYS_COMPUTERNAME
		                       , SALDOANTES, SALDODESP, PROCEDENCIA, ESTADO, FECHAOK, NROCOMPROBANTE, CODCAJA, CNSFACJ, NROASIENTO, CODUNG, CODPRG, GENCXP, IDSEDE )
		      SELECT @BANCO, @SUCURSAL, @CTA_BCO, @ITEM, CAST(@FECHAOPERACION + ' ' + CONVERT(VARCHAR(8), @AHORA, 108) AS DATETIME), '',@IDOPERACION, 0, UPPER(@DESCRIPCION), @USUARIO, @SYS_COMPUTERNAME
		             , 0, 0, @PROCEDENCIA, 'P', CAST(@FECHAOK + ' ' + CONVERT(VARCHAR(8), @AHORA, 108) AS DATETIME), '', COALESCE(@CODCAJA, ''), '' , NULL ,'' ,'' ,@GENCXP ,@IDSEDE                    
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
             RETURN
         END
         SELECT @RECAUDO=COALESCE(RECAUDO,0),@RNOMI=COALESCE(RNOMI,0)  FROM OFIN WHERE IDOPERACION=@IDOPERACION
		   SELECT 'OK'OK,@ITEM ITEM,  @RECAUDO RECAUDO,@RNOMI NOMINA
         RETURN 
	
	END
	IF @METODO = 'ACTUALIZABMOV'
	BEGIN
		SELECT	@BANCO      = JSON_VALUE(@PARAMETROS, '$.BANCO'),
				@SUCURSAL   = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
				@CTA_BCO    = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
				@PROCEDENCIA    = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
				@ITEM       = JSON_VALUE(@PARAMETROS, '$.ITEM'),
				@FECHAOPERACION = JSON_VALUE(@PARAMETROS, '$.FECHAOPERACION'),
				@IDOPERACION    = JSON_VALUE(@PARAMETROS, '$.IDOPERACION'),
				@DESCRIPCION    = JSON_VALUE(@PARAMETROS, '$.DESCRIPCION'),
				@FECHAOK        = JSON_VALUE(@PARAMETROS, '$.FECHAOK'),
				@GENCXP         = JSON_VALUE(@PARAMETROS, '$.GENCXP'),
				@SYS_COMPUTERNAME  = JSON_VALUE(@PARAMETROS, '$.SYS_ComputerName'),
				@IDSEDE         = JSON_VALUE(@PARAMETROS, '$.IDSEDE'),
				@CODCAJA         = JSON_VALUE(@PARAMETROS, '$.CAJA');


			UPDATE BMOV
			SET 
				FECHAOPERACION = @FECHAOPERACION,
				IDOPERACION = @IDOPERACION,
				DESCRIPCION = @DESCRIPCION,
				FECHAOK = @FECHAOK,
				GENCXP = @GENCXP,
				SYS_COMPUTERNAME = @SYS_COMPUTERNAME,
				IDSEDE = @IDSEDE,
				CODCAJA = @CODCAJA
			WHERE ITEM = @ITEM AND CTA_BCO = @CTA_BCO AND SUCURSAL = @SUCURSAL AND BANCO = @BANCO;

			SELECT 'OK'OK
	

	END
	IF @METODO = 'ANULARBMOV'
	BEGIN
		SELECT	@BANCO      = JSON_VALUE(@PARAMETROS, '$.BANCO'),
				@SUCURSAL   = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
				@CTA_BCO    = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
				@PROCEDENCIA    = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
				@ITEM       = JSON_VALUE(@PARAMETROS, '$.ITEM'),
				@DESCRIPCION    = JSON_VALUE(@PARAMETROS, '$.RAZONANULACION'),
				@SYS_COMPUTERNAME  = COALESCE(JSON_VALUE(@PARAMETROS, '$.SYS_ComputerName'), @SYS_COMPUTERNAME),
				@IDSEDE         = COALESCE(JSON_VALUE(@PARAMETROS, '$.IDSEDE'), @IDSEDE),
				@COMPANIA       = COALESCE(JSON_VALUE(@PARAMETROS, '$.COMPANIA'), @COMPANIA);

		IF @BANCO IS NULL OR @SUCURSAL IS NULL OR @CTA_BCO IS NULL OR @ITEM IS NULL
		BEGIN
			SELECT 'KO' OK, 'Datos incompletos para anular el movimiento.' ERROR
			RETURN
		END

		IF NOT EXISTS (
			SELECT 1 FROM BMOV
			WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO
			  AND ITEM = @ITEM AND ESTADO = 'P'
		)
		BEGIN
			SELECT 'KO' OK, 'Solo se pueden anular movimientos en estado pendiente.' ERROR
			RETURN
		END

		SELECT @NROCOMPROBANTE = NULLIF(TRIM(NROCOMPROBANTE), '')
		FROM BMOV
		WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM

		BEGIN TRY
			BEGIN TRANSACTION

			UPDATE BMOV
				SET ESTADO = 'A',
					RAZONANULACION = @DESCRIPCION,
					FECHAANU = @AHORA,
					SYS_COMPUTERNAME_ANULA = @SYS_COMPUTERNAME,
					USUARIOANULA = @USUARIO
				WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM

			EXEC SPK_CONTAB_BMOV
				@BANCO,
				@SUCURSAL,
				@CTA_BCO,
				@ITEM,
				@USUARIO,
				@SYS_COMPUTERNAME,
				@COMPANIA,
				@IDSEDE,
				@NROCOMPROBANTE

			COMMIT TRANSACTION
		END TRY
		BEGIN CATCH
			IF @@TRANCOUNT > 0
				ROLLBACK TRANSACTION

			SELECT 'KO' OK, ERROR_MESSAGE() ERROR
			RETURN
		END CATCH

		SELECT 'OK' OK
		RETURN
	END
	IF @METODO = 'GETFORMAPAGOS'
	BEGIN
		SELECT FORMAPAGO, DESCRIPCION, CUENTA FROM FPA
	END
	IF @METODO = 'TERCONTABLE'
	BEGIN
		SELECT @IDTERCERO = JSON_VALUE(@PARAMETROS, '$.IDTERCERO');

		SELECT CUENTA, DETALLE, COUNT(*) AS CANTIDAD
		FROM (
			SELECT DISTINCT TTEC.CUENTA, TTEC.DETALLE
			FROM TTEC
			INNER JOIN PPT ON TTEC.TIPO = PPT.TIPOTERCONTABLE
			WHERE PPT.IDTERCERO = @IDTERCERO
		) X
		GROUP BY CUENTA, DETALLE

	  RETURN
	END
	IF @METODO = 'GUARDABMOVD'
	BEGIN
      
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@PROCEDENCIA = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM'),
			@RENGLON = JSON_VALUE(@PARAMETROS, '$.RENGLON'),
			@FORMAPAGO = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO'),
			@BANCODOC = JSON_VALUE(@PARAMETROS, '$.BANCODOC'),
			@NODOCUMENTO = JSON_VALUE(@PARAMETROS, '$.NODOCUMENTO'),
			@VALOR = JSON_VALUE(@PARAMETROS, '$.VLRITEM'),
			@IDTERCERO = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
			@CODCAJA = COALESCE(
				NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.CODCAJA'))), ''),
				JSON_VALUE(@PARAMETROS, '$.CAJA.CODCAJA')
			),
			@CUENTA = JSON_VALUE(@PARAMETROS, '$.CUENTA'),
			@RECAUDO = JSON_VALUE(@PARAMETROS, '$.RECAUDO'),
			@NOMINA = JSON_VALUE(@PARAMETROS, '$.NOMINA'),
			@CCOSTO = JSON_VALUE(@PARAMETROS, '$.CCOSTO')
         ;

			SELECT @ITEM2 = COALESCE(MAX(RENGLON),0)+1 FROM BMOVD WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO  AND ITEM = @ITEM;
			BEGIN TRY    
				INSERT INTO BMOVD (BANCO, SUCURSAL, CTA_BCO, ITEM, RENGLON, FORMAPAGO, BANCODOC, NODOCUMENTO, VLRITEM, IDTERCERO, RECAUDO, ENPAGOS, OK, DEVUELTO, CAUSALDEV, PROCEDENCIA, CODCAJA, CNSFACJ, IDTERCEROANT, VLRLEGALIZADO, LLAVEDEVCHE, CUENTA, VLRAJUSTE, NROCOMPROBANTE, CCOSTO, RNOMI)
				VALUES (@BANCO, @SUCURSAL, @CTA_BCO, @ITEM, @ITEM2, @FORMAPAGO, @BANCODOC, @NODOCUMENTO, @VALOR, @IDTERCERO, @RECAUDO, NULL, NULL, NULL, NULL, @PROCEDENCIA, @CODCAJA, NULL, NULL, NULL, NULL, @CUENTA, NULL, NULL, @CCOSTO, @NOMINA);
			
				SELECT @VALOR = COALESCE(SUM(VLRITEM),0) FROM BMOVD WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM

				UPDATE BMOV 
				   SET VLROPERACION = @VALOR
				 WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM= @ITEM
			
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
			IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK, ERROR FROM @TBLERRORES
			
			END
			SELECT 'OK'OK

	
	END
	IF @METODO = 'DETALLESMOV'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@PROCEDENCIA = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM');

			SELECT BMOVD.BANCO, BMOVD.SUCURSAL, BMOVD.CTA_BCO, BMOVD.ITEM, BMOVD.RENGLON
			     , BMOVD.FORMAPAGO, FPA.DESCRIPCION
				 , BMOVD.BANCODOC, BMOVD.NODOCUMENTO
			     , BMOVD.VLRITEM
				 , BMOVD.IDTERCERO,TER.NIT, TER.RAZONSOCIAL
				 , BMOVD.RECAUDO, BMOVD.RNOMI AS NOMINA,CCOSTO
				 , BMOVD.ENPAGOS, BMOVD.OK, BMOVD.DEVUELTO, BMOVD.CAUSALDEV
				 , BMOVD.PROCEDENCIA, BMOVD.CODCAJA, BMOVD.CNSFACJ, BMOVD.IDTERCEROANT, BMOVD.VLRLEGALIZADO, BMOVD.LLAVEDEVCHE
				 , BMOVD.CUENTA, DETALLE = (SELECT TOP 1 DETALLE FROM TTEC WHERE CUENTA = BMOVD.CUENTA )
				 , BMOVD.VLRAJUSTE, BMOVD.NROCOMPROBANTE, BMOVD.CCOSTO, BMOVD.RNOMI
			FROM BMOVD
			INNER JOIN TER ON BMOVD.IDTERCERO =  TER.IDTERCERO
			INNER JOIN FPA ON FPA.FORMAPAGO =  BMOVD.FORMAPAGO
			WHERE BMOVD.BANCO = @BANCO AND BMOVD.SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM


	
	END
	IF @METODO = 'ACTUALIZABMOVD'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@PROCEDENCIA = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM'),
			@RENGLON = JSON_VALUE(@PARAMETROS, '$.RENGLON'),
			@FORMAPAGO = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO'),
			@BANCODOC = JSON_VALUE(@PARAMETROS, '$.BANCODOC'),
			@NODOCUMENTO = JSON_VALUE(@PARAMETROS, '$.NODOCUMENTO'),
			@VALOR = JSON_VALUE(@PARAMETROS, '$.VLRITEM'),
			@IDTERCERO = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
			@CODCAJA = COALESCE(
				NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.CODCAJA'))), ''),
				JSON_VALUE(@PARAMETROS, '$.CAJA.CODCAJA')
			),
			@CUENTA = JSON_VALUE(@PARAMETROS, '$.CUENTA'),
			@RECAUDO = JSON_VALUE(@PARAMETROS, '$.RECAUDO'),
			@NOMINA = JSON_VALUE(@PARAMETROS, '$.NOMINA'),
			@CCOSTO = JSON_VALUE(@PARAMETROS, '$.CCOSTO');


		UPDATE BMOVD
		SET 
			FORMAPAGO  = @FORMAPAGO,
			BANCODOC   = @BANCODOC,
			NODOCUMENTO = @NODOCUMENTO,
			VLRITEM   = @VALOR,
			IDTERCERO = @IDTERCERO,
			RECAUDO   = @RECAUDO,
			CUENTA    = @CUENTA,
			CODCAJA   = @CODCAJA,
         CCOSTO    = @CCOSTO,
         RNOMI     = @NOMINA
		WHERE 
		    CTA_BCO = @CTA_BCO
			AND BANCO = @BANCO
			AND SUCURSAL = @SUCURSAL
			AND ITEM = @ITEM
			AND RENGLON = @RENGLON

		SELECT @VALOR = COALESCE(SUM(VLRITEM),0) FROM BMOVD WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM

		UPDATE BMOV 
		SET VLROPERACION = @VALOR
		WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM= @ITEM

		SELECT 'OK'OK
	
	END
	IF @METODO = 'ELIMINABMOVD'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@PROCEDENCIA = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM'),
			@RENGLON = JSON_VALUE(@PARAMETROS, '$.RENGLON');

		DELETE BMOVD
		WHERE 
		    CTA_BCO = @CTA_BCO
			AND BANCO = @BANCO
			AND SUCURSAL = @SUCURSAL
			AND ITEM = @ITEM
			AND RENGLON = @RENGLON

		SELECT @VALOR = COALESCE(SUM(VLRITEM),0) FROM BMOVD WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM = @ITEM

		UPDATE BMOV 
		SET VLROPERACION = @VALOR
		WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO AND ITEM= @ITEM

		SELECT 'OK'OK
	
	END
	IF @METODO = 'DESCONFIRMAVAL'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@PROCEDENCIA = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM');

		IF (SELECT COUNT(*) FROM BMOVD WHERE CTA_BCO = @CTA_BCO AND BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND ITEM = @ITEM AND ENPAGOS=1) > 0
		BEGIN
			SELECT 'KO'OK, 'Este Recaudo ya se Encuentra En Pagos En Cartera... No Se puede Desaplicar'ERROR
		
		END

		SELECT @AHORA = FECHAOPERACION 
		FROM BMOV 
		WHERE CTA_BCO = @CTA_BCO
			AND BANCO = @BANCO
			AND SUCURSAL = @SUCURSAL
			AND ITEM = @ITEM

		--SELECT @AHORA
		-- 1 PERIODO CERRADO | 0 PERIODO ABIERTO
		IF (SELECT TOP 1 CERRADO FROM PRI WHERE FECHA_INI<= CONVERT(SMALLDATETIME, @AHORA) AND FECHA_FIN+1 > CONVERT(SMALLDATETIME, @AHORA) ORDER BY ANO,MES DESC ) = 1
		BEGIN
			SELECT 'PREGUNTA'OK, 'El periodo contable de Este Movimiento ya Esta cerrado, No podr? volver a Confirmar el Movimiento en la misma fecha.'ERROR
		END
		ELSE
		BEGIN
			SELECT 'OK'OK
		END
	
	END
	IF @METODO = 'DESCONFIRMABMOV'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@PROCEDENCIA = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM'),
			@SYS_COMPUTERNAME  = JSON_VALUE(@PARAMETROS, '$.SYS_ComputerName'),
			@IDSEDE  = JSON_VALUE(@PARAMETROS, '$.IDSEDE'),
			@COMPANIA  = JSON_VALUE(@PARAMETROS, '$.COMPANIA');


		SELECT @NROCOMPROBANTE = NROCOMPROBANTE 
		FROM BMOV 
		WHERE CTA_BCO = @CTA_BCO
			AND BANCO = @BANCO
			AND SUCURSAL = @SUCURSAL
			AND ITEM = @ITEM


		IF (SELECT COUNT(*) FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE) > 0
		BEGIN
			DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
			DELETE MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
		END
		ELSE
		BEGIN
			print 'aqui 2'
			SELECT @ESTADO = ESTADO, @COMPROBANTE = COMPROBANTE, @NOREFERENCIA = NOREFERENCIA, @ANO = ANO, @MES = MES FROM MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE

			IF @ESTADO = 2
			BEGIN
				IF (SELECT CERRADO FROM PRI WHERE COMPANIA = '1' AND ANO = @ANO AND MES = @MES) = 1
				BEGIN
					EXEC SPK_REVERSAR_MCP_BANCO @NROCOMPROBANTE, @COMPANIA, @IDSEDE, @USUARIO, @SYS_COMPUTERNAME
				END
				ELSE
				BEGIN
					UPDATE MCP SET ESTADO=1 WHERE NROCOMPROBANTE=@NROCOMPROBANTE
					UPDATE MCH SET ESTADO=1 WHERE NROCOMPROBANTE=@NROCOMPROBANTE
				END
			END

			EXEC SPK_DESOK_BMOV @BANCO, @SUCURSAL, @CTA_BCO, @ITEM, @NROCOMPROBANTE

			UPDATE BMOV 
			SET NROCOMPROBANTE = NULL,
				CONTABILIZADA = 0,
			 NROASIENTO = NULL
			WHERE CTA_BCO = @CTA_BCO
			AND BANCO = @BANCO
			AND SUCURSAL = @SUCURSAL
			AND ITEM = @ITEM

			SELECT 'OK'OK
		END

	END
	IF @METODO = 'GENCXPBMOV'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@PROCEDENCIA = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM'),
			@SYS_COMPUTERNAME  = JSON_VALUE(@PARAMETROS, '$.SYS_ComputerName'),
			@IDSEDE  = JSON_VALUE(@PARAMETROS, '$.IDSEDE'),
			@COMPANIA  = JSON_VALUE(@PARAMETROS, '$.COMPANIA');


			IF EXISTS(SELECT 1 FROM BMOV WHERE CTA_BCO = @CTA_BCO AND BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND ITEM = @ITEM AND BMOV.GENCXP = 1 AND COALESCE(BMOV.CNSFCXP,'')<>'' )
			BEGIN
				SELECT 'KO'OK, 'Ya se Genero la Cxp para este Movimiento Bancario'ERROR
			
			END

			IF EXISTS(SELECT 1 FROM BMOV WHERE CTA_BCO = @CTA_BCO AND BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND ITEM = @ITEM AND BMOV.ESTADO <> 'O' AND BMOV.CONTABILIZADA<>1 )
			BEGIN
				SELECT 'KO'OK, 'No se puede contabilizar. 'ERROR
			
			END
			BEGIN TRY 

				EXEC SPK_GENCXP_MOVIN_BANCO @BANCO, @SUCURSAL, @CTA_BCO, @ITEM, @USUARIO, @IDSEDE
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
			IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK, ERROR FROM @TBLERRORES
			
			END
			SELECT 'OK'OK
	
	END
	IF @METODO = 'GENCXPBCTTAR'
	BEGIN
		-- Genera la FCXP consolidada del periodo (mes/ano) para una tarjeta de credito
		-- (cuenta BCT con TARCRED=1). Consolida todas las cuotas pendientes en BCTTAR
		-- mas los cargos manuales capturados del extracto: interes, seguros, impuestos.
		DECLARE @ANOCUOTA         SMALLINT
		DECLARE @MESCUOTA         SMALLINT
		DECLARE @VLR_INTERES      DECIMAL(14,2)
		DECLARE @VLR_SEGUROS      DECIMAL(14,2)
		DECLARE @VLR_IMPUESTOS_TC DECIMAL(14,2)
		DECLARE @VLR_GASTOS_TC    DECIMAL(14,2)
		DECLARE @IDTERCERO_BANCO  VARCHAR(20)
		DECLARE @CNSFCXP_OUT      VARCHAR(20)

		SELECT
			@BANCO            = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL         = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO          = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@ANOCUOTA         = JSON_VALUE(@PARAMETROS, '$.ANOCUOTA'),
			@MESCUOTA         = JSON_VALUE(@PARAMETROS, '$.MESCUOTA'),
			@VLR_INTERES      = JSON_VALUE(@PARAMETROS, '$.VLR_INTERES'),
			@VLR_SEGUROS      = JSON_VALUE(@PARAMETROS, '$.VLR_SEGUROS'),
			@VLR_IMPUESTOS_TC = JSON_VALUE(@PARAMETROS, '$.VLR_IMPUESTOS'),
			@VLR_GASTOS_TC    = JSON_VALUE(@PARAMETROS, '$.VLR_GASTOS'),
			@IDTERCERO_BANCO  = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
			@SYS_COMPUTERNAME = JSON_VALUE(@PARAMETROS, '$.SYS_ComputerName'),
			@IDSEDE           = JSON_VALUE(@PARAMETROS, '$.IDSEDE'),
			@COMPANIA         = JSON_VALUE(@PARAMETROS, '$.COMPANIA');

		IF @BANCO IS NULL OR @SUCURSAL IS NULL OR @CTA_BCO IS NULL
		   OR @ANOCUOTA IS NULL OR @MESCUOTA IS NULL
		   OR @IDTERCERO_BANCO IS NULL OR LTRIM(RTRIM(@IDTERCERO_BANCO)) = ''
		BEGIN
			SELECT 'KO' OK, 'Datos incompletos: BANCO, SUCURSAL, CTA_BCO, ANOCUOTA, MESCUOTA e IDTERCERO son obligatorios.' ERROR
		
		END

		-- Validacion 1: la cuenta debe ser tarjeta de credito
		IF NOT EXISTS (SELECT 1 FROM BCT
		               WHERE BANCO    = @BANCO
		                 AND SUCURSAL = @SUCURSAL
		                 AND CTA_BCO  = @CTA_BCO
		                 AND COALESCE(TARCRED, 0) = 1)
		BEGIN
			SELECT 'KO' OK, 'La cuenta no esta marcada como tarjeta de credito (BCT.TARCRED=1).' ERROR
		
		END

		-- Validacion 1.b: el periodo no puede ser futuro (solo mes actual o vencido)
		IF (@ANOCUOTA * 100 + @MESCUOTA) > (YEAR(GETDATE()) * 100 + MONTH(GETDATE()))
		BEGIN
			SELECT 'KO' OK,
			       'No se puede generar la CxP de un periodo futuro. Solo se permite el mes actual o meses ya vencidos.' ERROR
		
		END

		-- Validacion 2: idempotencia, no se ha generado ya la CxP del periodo
		IF EXISTS (SELECT 1 FROM BCTTAR
		           WHERE BANCO    = @BANCO
		             AND SUCURSAL = @SUCURSAL
		             AND CTA_BCO  = @CTA_BCO
		             AND ANOCUOTA = @ANOCUOTA
		             AND MESCUOTA = @MESCUOTA
		             AND ESTADO   = 'C'
		             AND COALESCE(CNSFCXP, '') <> '')
		BEGIN
			SELECT 'KO' OK, 'Ya se genero la CxP para este periodo de tarjeta de credito.' ERROR
		
		END

		-- Validacion 3: deben existir cuotas pendientes en el periodo
		IF NOT EXISTS (SELECT 1 FROM BCTTAR
		               WHERE BANCO    = @BANCO
		                 AND SUCURSAL = @SUCURSAL
		                 AND CTA_BCO  = @CTA_BCO
		                 AND ANOCUOTA = @ANOCUOTA
		                 AND MESCUOTA = @MESCUOTA
		                 AND ESTADO   = 'P')
		BEGIN
			SELECT 'KO' OK, 'No hay cuotas pendientes para el periodo seleccionado.' ERROR
		
		END

		BEGIN TRY
			SET @CNSFCXP_OUT = SPACE(20)
			EXEC SPK_GEN_CXP_BCTTAR
				@BANCO, @SUCURSAL, @CTA_BCO,
				@ANOCUOTA, @MESCUOTA,
				@VLR_INTERES, @VLR_SEGUROS, @VLR_IMPUESTOS_TC, @VLR_GASTOS_TC,
				@IDTERCERO_BANCO,
				@USUARIO, @COMPANIA, @IDSEDE, @SYS_COMPUTERNAME,
				@CNSFCXP_OUT OUTPUT
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
		
		END

		SELECT 'OK' OK, @CNSFCXP_OUT CNSFCXP
	
	END
	IF @METODO = 'CONFIRMARBMOV'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@PROCEDENCIA = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM'),
			@SYS_COMPUTERNAME  = JSON_VALUE(@PARAMETROS, '$.SYS_ComputerName'),
			@IDSEDE  = JSON_VALUE(@PARAMETROS, '$.IDSEDE'),
			@COMPANIA  = JSON_VALUE(@PARAMETROS, '$.COMPANIA'),
			@NROCOMPROBANTE  = JSON_VALUE(@PARAMETROS, '$.NROCOMPROBANTE');

			BEGIN TRY  
				EXEC SPK_OK_BMOV @BANCO, @SUCURSAL, @CTA_BCO, @ITEM, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @IDSEDE, @NROCOMPROBANTE
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
			IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK, ERROR FROM @TBLERRORES
			
			END
			SELECT 'OK'OK
	END
	IF @METODO = N'DISTRUYE_ADRES'
	BEGIN
		DELETE FROM @TBLERRORES WHERE 1=1;

		SELECT
			  @BANCO             = JSON_VALUE(@PARAMETROS, N'$.BANCO')
			, @SUCURSAL          = JSON_VALUE(@PARAMETROS, N'$.SUCURSAL')
			, @CTA_BCO           = JSON_VALUE(@PARAMETROS, N'$.CTA_BCO')
			, @ITEM              = JSON_VALUE(@PARAMETROS, N'$.ITEM')
			, @RENGLON           = JSON_VALUE(@PARAMETROS, N'$.RENGLON')
			, @IDTERCERONVO_DIST = LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, N'$.IDTERCERONVO')))
			, @VALORDISTRI       = JSON_VALUE(@PARAMETROS, N'$.VALORDISTRI');

		IF @BANCO IS NULL OR @SUCURSAL IS NULL OR @CTA_BCO IS NULL
		   OR @ITEM IS NULL OR @RENGLON IS NULL
		   OR @IDTERCERONVO_DIST IS NULL OR NULLIF(@IDTERCERONVO_DIST, N'') IS NULL
		   OR @VALORDISTRI IS NULL
		BEGIN
			SELECT 'KO' OK, N'Datos incompletos: BANCO, SUCURSAL, CTA_BCO, ITEM, RENGLON, IDTERCERONVO y VALORDISTRI son obligatorios.' ERROR;
		;
		END

		IF COALESCE(@VALORDISTRI, CAST(0 AS DECIMAL(14, 2))) <= 0
		BEGIN
			SELECT 'KO' OK, N'VALORDISTRI debe ser mayor que cero.' ERROR;
		;
		END

		IF NOT EXISTS (
				SELECT 1
				  FROM dbo.BMOV AS M WITH (NOLOCK)
				 WHERE M.BANCO = @BANCO
				   AND M.SUCURSAL = @SUCURSAL
				   AND M.CTA_BCO = @CTA_BCO
				   AND M.ITEM = @ITEM
				   AND COALESCE(M.ESTADO, N'') = N'O'
		   )
		BEGIN
			SELECT 'KO' OK, N'El movimiento no existe o no est? en estado operativo abierto para esta operaci?n.' ERROR;
		;
		END

		IF NOT EXISTS (
				SELECT 1 FROM dbo.TER AS T WITH (NOLOCK)
				 WHERE T.IDTERCERO = @IDTERCERONVO_DIST
		   )
		BEGIN
			SELECT 'KO' OK, N'El tercero destino (IDTERCERONVO) no existe en TER.' ERROR;
		;
		END

		BEGIN TRY
			DECLARE
				  @DISPONIBLE  DECIMAL(14, 2)
				, @VLR_ANT     DECIMAL(14, 2)
				, @VLRL_ANT    DECIMAL(14, 2)
				, @RENGLON_NVO INT
				, @IDTER_ORI   VARCHAR(40)
				, @ORI_ENPAGOS SMALLINT;

			SET @IDTER_ORI = NULL;

			SELECT
				  @DISPONIBLE = COALESCE(O.VLRITEM, 0) - COALESCE(O.VLRLEGALIZADO, 0)
				, @VLR_ANT    = COALESCE(O.VLRITEM, 0)
				, @VLRL_ANT   = COALESCE(O.VLRLEGALIZADO, 0)
				, @PROCEDENCIA = COALESCE(O.PROCEDENCIA, N'')
				, @IDTER_ORI  = O.IDTERCERO
				, @ORI_ENPAGOS = COALESCE(O.ENPAGOS, 0)
			  FROM dbo.BMOVD AS O WITH (UPDLOCK, ROWLOCK)
			 WHERE O.BANCO = @BANCO
			   AND O.SUCURSAL = @SUCURSAL
			   AND O.CTA_BCO = @CTA_BCO
			   AND O.ITEM = @ITEM
			   AND O.RENGLON = @RENGLON;

			IF @@ROWCOUNT = 0 OR @IDTER_ORI IS NULL
			BEGIN
				SELECT 'KO' OK, N'No se encontr? el rengl?n BMOVD indicado para distribuir.' ERROR;
			;
			END

			IF COALESCE(@ORI_ENPAGOS, 0) <> 0
			BEGIN
				SELECT 'KO' OK, N'Este rengl?n ya tiene ENPAGOS; no se puede distribuir.' ERROR;
			;
			END

			IF COALESCE(@IDTER_ORI, N'') = @IDTERCERONVO_DIST
			BEGIN
				SELECT 'KO' OK, N'El tercero destino no puede ser el mismo que el del rengl?n origen.' ERROR;
			;
			END

			IF @VALORDISTRI > @DISPONIBLE
			BEGIN
				SELECT 'KO' OK, N'VALORDISTRI supera el saldo disponible (VLRITEM - VLRLEGALIZADO).' ERROR;
			;
			END

			IF (@VLR_ANT - @VALORDISTRI) < @VLRL_ANT
			BEGIN
				SELECT 'KO' OK, N'Distribuci?n inv?lida: el nuevo VLRITEM ser?a menor que VLRLEGALIZADO del origen.' ERROR;
			;
			END

			SELECT @RENGLON_NVO = COALESCE(MAX(D.RENGLON), 0) + 1
			  FROM dbo.BMOVD AS D WITH (ROWLOCK)
			 WHERE D.BANCO = @BANCO
			   AND D.SUCURSAL = @SUCURSAL
			   AND D.CTA_BCO = @CTA_BCO
			   AND D.ITEM = @ITEM;

			IF @RENGLON_NVO IS NULL SET @RENGLON_NVO = 1;

			BEGIN TRANSACTION TDISTRUYE;

			INSERT INTO dbo.BMOVD (
				  BANCO, SUCURSAL, CTA_BCO, ITEM, RENGLON
				, FORMAPAGO, BANCODOC, NODOCUMENTO, VLRITEM, IDTERCERO
				, RECAUDO, ENPAGOS, OK, DEVUELTO, CAUSALDEV
				, PROCEDENCIA, CODCAJA, CNSFACJ, IDTERCEROANT, VLRLEGALIZADO
				, LLAVEDEVCHE, CUENTA, VLRAJUSTE, NROCOMPROBANTE, CCOSTO, RNOMI
			)
			SELECT
				  O.BANCO, O.SUCURSAL, O.CTA_BCO, O.ITEM, @RENGLON_NVO
				, O.FORMAPAGO, O.BANCODOC, O.NODOCUMENTO, @VALORDISTRI, @IDTERCERONVO_DIST
				, O.RECAUDO, NULL, NULL, NULL, NULL
				, O.PROCEDENCIA, O.CODCAJA, O.CNSFACJ, O.IDTERCEROANT, CAST(0 AS DECIMAL(14, 2))
				, O.LLAVEDEVCHE, O.CUENTA, NULL, O.NROCOMPROBANTE, O.CCOSTO, O.RNOMI
			  FROM dbo.BMOVD AS O
			 WHERE O.BANCO = @BANCO
			   AND O.SUCURSAL = @SUCURSAL
			   AND O.CTA_BCO = @CTA_BCO
			   AND O.ITEM = @ITEM
			   AND O.RENGLON = @RENGLON;

			IF @@ROWCOUNT <> 1
			BEGIN
				ROLLBACK TRANSACTION TDISTRUYE;
				SELECT 'KO' OK, N'No se insert? la l?nea de distribuci?n.' ERROR;
			;
			END

			UPDATE dbo.BMOVD
			   SET VLRITEM = COALESCE(VLRITEM, 0) - @VALORDISTRI
			 WHERE BANCO = @BANCO
			   AND SUCURSAL = @SUCURSAL
			   AND CTA_BCO = @CTA_BCO
			   AND ITEM = @ITEM
			   AND RENGLON = @RENGLON;

			IF @@ROWCOUNT <> 1
			BEGIN
				ROLLBACK TRANSACTION TDISTRUYE;
				SELECT 'KO' OK, N'No se pudo actualizar el rengl?n origen (VLRITEM).' ERROR;
			;
			END

			--SELECT @VALOR = COALESCE(SUM(D.VLRITEM), 0)
			--  FROM dbo.BMOVD AS D
			-- WHERE D.BANCO = @BANCO
			--   AND D.SUCURSAL = @SUCURSAL
			--   AND D.CTA_BCO = @CTA_BCO
			--   AND D.ITEM = @ITEM;

			--UPDATE dbo.BMOV
			--   SET VLROPERACION = @VALOR
			-- WHERE BANCO = @BANCO
			--   AND SUCURSAL = @SUCURSAL
			--   AND CTA_BCO = @CTA_BCO
			--   AND ITEM = @ITEM;

				SELECT @NROCOMPROBANTE=NROCOMPROBANTE
				  FROM dbo.BMOV AS M WITH (NOLOCK)
				 WHERE M.BANCO = @BANCO
				   AND M.SUCURSAL = @SUCURSAL
				   AND M.CTA_BCO = @CTA_BCO
				   AND M.ITEM = @ITEM
				   AND COALESCE(M.ESTADO, N'') = N'O'

      EXEC SPK_NC_CONTAB_DISTRI_ADRES @NROCOMPROBANTE,'01',@IDTERCERONVO_DIST,@RENGLON_NVO,@VALORDISTRI,@IDSEDE,@USUARIO,@SYS_COMPUTERNAME
			COMMIT TRANSACTION TDISTRUYE;

			SELECT N'OK' OK, N'Distribuci?n registrada.' AS MENSAJE;
		END TRY
		BEGIN CATCH
			IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION TDISTRUYE;
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
			SELECT N'KO' OK, ERROR FROM @TBLERRORES;
		;
		END CATCH

	;
	END
	IF @METODO = 'REPORTE_LISTADO_MOVIMIENTOS'
	BEGIN
		DECLARE @FINICIAL VARCHAR(20)
		DECLARE @FFINAL VARCHAR(20)
		DECLARE @ESTADO_FILTRO VARCHAR(5)
		DECLARE @TIPO_MOV VARCHAR(5)
		DECLARE @PROCEDENCIA_FILTRO VARCHAR(20)

		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@FINICIAL = NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.FINICIAL'))), ''),
			@FFINAL = NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.FFINAL'))), ''),
			@ESTADO_FILTRO = NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.ESTADO'))), ''),
			@TIPO_MOV = NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.TIPO_MOV'))), ''),
			@PROCEDENCIA_FILTRO = NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'))), ''),
			@IDTERCERO = NULLIF(LTRIM(RTRIM(JSON_VALUE(@PARAMETROS, '$.IDTERCERO'))), '');

		IF @BANCO IS NULL OR @SUCURSAL IS NULL OR @CTA_BCO IS NULL
		BEGIN
			SELECT 'KO' OK, N'Datos incompletos: BANCO, SUCURSAL y CTA_BCO son obligatorios.' ERROR;
			RETURN;
		END

		SELECT
			BMOV.ESTADO,
			BMOV.ITEM,
			BMOVD.RENGLON,
			BMOV.IDOPERACION,
			OFIN.NOMOPERACION,
			FORMAT(BMOV.FECHAOPERACION, 'yyyy-MM-dd') AS FECHAOPERACION,
			OFIN.TIPO,
			BMOVD.VLRITEM,
			BMOVD.FORMAPAGO,
			TER.NIT,
			TER.RAZONSOCIAL,
			BMOVD.CODCAJA,
			BMOVD.CNSFACJ,
			BMOVD.CUENTA,
			BMOVD.RECAUDO,
			COALESCE(BMOVD.RNOMI, 0) AS NOMINA
		FROM dbo.BMOV AS BMOV WITH (NOLOCK)
		INNER JOIN dbo.BMOVD AS BMOVD WITH (NOLOCK)
			ON BMOV.BANCO = BMOVD.BANCO
		   AND BMOV.SUCURSAL = BMOVD.SUCURSAL
		   AND BMOV.CTA_BCO = BMOVD.CTA_BCO
		   AND BMOV.ITEM = BMOVD.ITEM
		INNER JOIN dbo.OFIN AS OFIN WITH (NOLOCK)
			ON BMOV.IDOPERACION = OFIN.IDOPERACION
		INNER JOIN dbo.TER AS TER WITH (NOLOCK)
			ON BMOVD.IDTERCERO = TER.IDTERCERO
		WHERE BMOV.BANCO = @BANCO
		  AND BMOV.SUCURSAL = @SUCURSAL
		  AND BMOV.CTA_BCO = @CTA_BCO
		  AND (COALESCE(@ESTADO_FILTRO, 'T') = 'T' OR BMOV.ESTADO = @ESTADO_FILTRO)
		  AND (COALESCE(@TIPO_MOV, 'T') = 'T' OR OFIN.TIPO = @TIPO_MOV)
		  AND (
				COALESCE(@PROCEDENCIA_FILTRO, 'T') = 'T'
				OR @PROCEDENCIA_FILTRO = 'TODAS'
				OR BMOV.PROCEDENCIA = @PROCEDENCIA_FILTRO
			  )
		  AND (
				@FINICIAL IS NULL
				OR BMOV.FECHAOPERACION >= CAST(@FINICIAL AS DATETIME)
			  )
		  AND (
				@FFINAL IS NULL
				OR BMOV.FECHAOPERACION <= CAST(@FFINAL + ' 23:59:59' AS DATETIME)
			  )
		  AND (
				@IDTERCERO IS NULL
				OR BMOVD.IDTERCERO = @IDTERCERO
			  )
		ORDER BY BMOV.ITEM, BMOVD.RENGLON;

		RETURN;
	END
    IF @METODO ='ACTUALIZA_TERCERO'
    BEGIN
        SELECT
            @BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
            @SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
            @CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
            @ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM'),
            @RENGLON = JSON_VALUE(@PARAMETROS, '$.RENGLON'),
            @IDTERCERO = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
            @BANCODOC = JSON_VALUE(@PARAMETROS, '$.BANCODOC'),
            @NODOCUMENTO = JSON_VALUE(@PARAMETROS, '$.NODOCUMENTO'),
            @CUENTA = JSON_VALUE(@PARAMETROS, '$.CUENTA'),
            @SYS_COMPUTERNAME = COALESCE(JSON_VALUE(@PARAMETROS, '$.SYS_ComputerName'), @SYS_COMPUTERNAME),
            @IDSEDE = COALESCE(JSON_VALUE(@PARAMETROS, '$.IDSEDE'), @IDSEDE),
            @COMPANIA = COALESCE(JSON_VALUE(@PARAMETROS, '$.COMPANIA'), @COMPANIA);

        IF @BANCO IS NULL OR @SUCURSAL IS NULL OR @CTA_BCO IS NULL
           OR @ITEM IS NULL OR @RENGLON IS NULL
           OR @IDTERCERO IS NULL OR LTRIM(RTRIM(@IDTERCERO)) = ''
        BEGIN
            SELECT 'KO' OK, 'Datos incompletos para cambiar tercero.' ERROR
            RETURN
        END

        IF NOT EXISTS (
            SELECT 1 FROM BMOV
            WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO
              AND ITEM = @ITEM AND PROCEDENCIA = 'BANCOS'
              AND ESTADO = 'O' AND COALESCE(CONTABILIZADA, 0) = 1
        )
        BEGIN
            SELECT 'KO' OK, 'El movimiento no cumple las condiciones para cambiar tercero.' ERROR
            RETURN
        END

        IF NOT EXISTS (
            SELECT 1 FROM BMOVD
            WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO
              AND ITEM = @ITEM AND RENGLON = @RENGLON
        )
        BEGIN
            SELECT 'KO' OK, 'No se encontró el renglón del detalle.' ERROR
            RETURN
        END

        SELECT @NROCOMPROBANTE = NULLIF(TRIM(NROCOMPROBANTE), '')
        FROM BMOV
        WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO
          AND ITEM = @ITEM

        IF @NROCOMPROBANTE IS NULL
        BEGIN
            SELECT 'KO' OK, 'No se encontró número de comprobante contable para actualizar.' ERROR
            RETURN
        END

        BEGIN TRY
            BEGIN TRANSACTION

            UPDATE BMOVD
            SET IDTERCERO = @IDTERCERO,
                BANCODOC = @BANCODOC,
                NODOCUMENTO = @NODOCUMENTO,
                CUENTA = @CUENTA
            WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO
              AND ITEM = @ITEM AND RENGLON = @RENGLON

            EXEC SPK_MCP_ACT_TER
                @NROCOMPROBANTE,
                @COMPANIA,
                @IDTERCERO,
                @IDSEDE,
                @USUARIO,
                @SYS_COMPUTERNAME

            COMMIT TRANSACTION
        END TRY
        BEGIN CATCH
            IF @@TRANCOUNT > 0
                ROLLBACK TRANSACTION

            SELECT 'KO' OK, ERROR_MESSAGE() ERROR
            RETURN
        END CATCH

        SELECT 'OK' OK
        RETURN
    END
END

