CREATE OR ALTER PROCEDURE DBO.SPQ_OFIN_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY           INT 
       ,@PROCESO            VARCHAR(20)    ,@OFIN    NVARCHAR(MAX)
              ,@IDOPERACION     VARCHAR(20)
       ,@NOMOPERACION     VARCHAR(80)
       ,@TIPO     VARCHAR(2)
       ,@COMPROBANTE     VARCHAR(2)
       ,@CUENTA     VARCHAR(16)
       ,@RECAUDO     SMALLINT
       ,@MCCOSTO     SMALLINT
       ,@GENCXP     BIT
       ,@RNOMI     BIT
       ,@TRASLADO     BIT
       ,@BANCO     VARCHAR(3)
       ,@SUCURSAL     VARCHAR(2)
       ,@CTA_BCO     VARCHAR(40)
       ,@HOMOLOGO     VARCHAR(20)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_OFIN_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'CRUDOFIN'
   BEGIN
      PRINT 'CRUDOFIN'
      SELECT @OFIN  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@OFIN ,'$.PROCESO')
      --Leo Campos enviados y los coloco en las variables respectivas
      SELECT @IDOPERACION = JSON_VALUE(@OFIN , '$.IDOPERACION' )
      SELECT @NOMOPERACION = JSON_VALUE(@OFIN , '$.NOMOPERACION' )
      SELECT @TIPO = JSON_VALUE(@OFIN , '$.TIPO' )
      SELECT @COMPROBANTE = JSON_VALUE(@OFIN , '$.COMPROBANTE' )
      SELECT @CUENTA = JSON_VALUE(@OFIN , '$.CUENTA' )
      SELECT @RECAUDO = CAST(JSON_VALUE(@OFIN , '$.RECAUDO' ) AS BIT)
      SELECT @MCCOSTO = CAST(JSON_VALUE(@OFIN , '$.MCCOSTO' ) AS BIT)
      SELECT @GENCXP = CAST(JSON_VALUE(@OFIN , '$.GENCXP' ) AS BIT)
      SELECT @RNOMI = CAST(JSON_VALUE(@OFIN , '$.RNOMI' ) AS BIT)
      SELECT @TRASLADO = CAST(JSON_VALUE(@OFIN , '$.TRASLADO' ) AS BIT)
      SELECT @BANCO = JSON_VALUE(@OFIN , '$.BANCO' )
      SELECT @SUCURSAL = JSON_VALUE(@OFIN , '$.SUCURSAL' )
      SELECT @CTA_BCO = JSON_VALUE(@OFIN , '$.CTA_BCO' )
      SELECT @HOMOLOGO = JSON_VALUE(@OFIN , '$.HOMOLOGO' )

      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'
         BEGIN TRY
			INSERT INTO @TBLERRORES(ERROR) 
			SELECT 'LA OPERACION FINANCIERA YA EXISTE'
			WHERE EXISTS (SELECT 1 FROM OFIN WHERE IDOPERACION = @IDOPERACION)

			IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
			BEGIN
				INSERT INTO OFIN(IDOPERACION,NOMOPERACION,TIPO,COMPROBANTE,CUENTA,RECAUDO,MCCOSTO,
								 GENCXP,RNOMI,TRASLADO,BANCO,SUCURSAL,CTA_BCO,HOMOLOGO)
				SELECT @IDOPERACION,@NOMOPERACION,@TIPO,@COMPROBANTE,@CUENTA,@RECAUDO,@MCCOSTO,
								 @GENCXP,@RNOMI,@TRASLADO,@BANCO,@SUCURSAL,@CTA_BCO,@HOMOLOGO
				SELECT @IDENTITY = SCOPE_IDENTITY()
			END
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK ,@IDENTITY CNS 
         RETURN
      END

      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         BEGIN TRY
            UPDATE OFIN SET
                    IDOPERACION = @IDOPERACION,NOMOPERACION = @NOMOPERACION,TIPO = @TIPO,COMPROBANTE = @COMPROBANTE,CUENTA = @CUENTA,RECAUDO = @RECAUDO,MCCOSTO = @MCCOSTO,
                             GENCXP = @GENCXP,RNOMI = @RNOMI,TRASLADO = @TRASLADO,BANCO = @BANCO,SUCURSAL = @SUCURSAL,CTA_BCO = @CTA_BCO,HOMOLOGO = @HOMOLOGO
            WHERE IDOPERACION = @IDOPERACION
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END

	  IF UPPER(@PROCESO) = 'ELIMINAR'
		BEGIN
			PRINT 'ELIMINAR'
			BEGIN TRY
				IF COALESCE(@IDOPERACION,'')=''
				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'EL CODIGO DE LA OPERACION FINANCIERA ES OBLIGATORIO'

				IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
				BEGIN
					DELETE FROM OFIN WHERE IDOPERACION = @IDOPERACION
				END		
			END TRY

			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH

			IF(SELECT COUNT(*) FROM @TBLERRORES) >0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			SELECT 'OK' OK
			RETURN
		END
      RETURN
   END
END


