CREATE OR ALTER PROCEDURE DBO.SPQ_CONF_CAJA_2
@JSON  NVARCHAR(MAX) 
WITH
ENCRYPTION
AS
DECLARE  @PARAMETROS      NVARCHAR(MAX) ,@MODELO           VARCHAR(100) ,@METODO            VARCHAR(100)  ,@USUARIO         VARCHAR(12),
			@GRUPO           VARCHAR(8)    ,@SYS_COMPUTERNAME VARCHAR(254) ,@IDSEDE            VARCHAR(5)    ,@USUNOMBRE       VARCHAR(100),
			@FECHA           VARCHAR(10)   ,@IDEMEDICA        VARCHAR(4)	,@FECHA1            DATETIME		 ,@SQL             VARCHAR(MAX),
			@IDMEDICO        VARCHAR(20)	 ,@HORA             VARCHAR(10)	,@IDDX              VARCHAR(10)	 ,@CONSECUTIVO     VARCHAR(20),
			@IDAFILIADO      VARCHAR(20)   ,@IDPLAN           VARCHAR(10)  ,@IDTERCERO         VARCHAR(20)   ,@IDSERVICIO      VARCHAR(20),
			@NOMBREACOMPA    VARCHAR(120)  ,@TELEFONOACOMPA   VARCHAR(20)  ,@PARENTESCOACOMPA  VARCHAR(20)   ,@MODELOCITA      VARCHAR(50),
			@CLASEORDEN      VARCHAR(20)   ,@IDPESPECIAL      VARCHAR(20)  ,@IDTERCEROCA       VARCHAR(20)   ,@NOAUTORIZACION  VARCHAR(20),
		   @FECHA2          DATE          ,@CONSECUTIVOANT   VARCHAR(20)  ,@CONSECUTIVONUE    VARCHAR(20)   ,@TIPOCITA        VARCHAR(20),
		   @NOMBRE          VARCHAR(100)  ,@ATENCION         VARCHAR(50)  ,@CCOSTO            VARCHAR(570)  ,@PARTICULAR      BIT,
		   @FECHAINCIO      DATETIME      ,@FECHAFINAL       DATETIME     ,@COMPANIA          VARCHAR(2)	,@ITEM		INT ,
         @IDAUT           VARCHAR(20)   ,@NO_ITEM          SMALLINT     ,@PYP               SMALLINT      ,@ALTOCOSTO       SMALLINT,
		   @VALORAUTD       DECIMAL(12,4) ,@FECHAAUT         DATETIME     ,@COPAGOPROPIO      SMALLINT      ,@SOAT            SMALLINT,
		   @PROCEDENCIA     VARCHAR(20)   ,@IDPROVEEDOR      VARCHAR(20)  ,@IDAREA            VARCHAR(20)   ,@PARTICULAR_TIME DECIMAL(14,2),
         @FECHAINI        DATE          ,@FECHAFIN         DATE         ,@IDESPECIALIDAD    VARCHAR(20),	@TIPOEGRESO  VARCHAR(20) ,
         @I               INT           ,@I_TO             INT		      ,@OBSERVCION        VARCHAR(200)	 ,@CAUSA           VARCHAR(20),
         @OBSERVACION     VARCHAR(200)  ,@HOY              SMALLDATETIME=GETDATE()                        ,@VLR_UNIT        INT, 
         @CANTIDAD        INT           ,@UNS              VARCHAR(20)  ,@CONDICIONAL       VARCHAR(10),	@TIPOCAJA VARCHAR(20),
         @CODCAJA         VARCHAR(10)   ,@DATO             VARCHAR(100) ,@CODCAJERO         VARCHAR(20)   ,@CODTURNO        VARCHAR(4)       ,@CNSFACJ   VARCHAR(20)
        ,@CNSACJ          VARCHAR(20)   ,@NOADMISION       VARCHAR(20)  ,@CONCEPTO          VARCHAR(30)   ,@TOTAL           DECIMAL(20,4)   
        ,@TOTALFCJ        DECIMAL(12,4) ,@FALTANTE         DECIMAL(14,2),@CERRADA           SMALLINT      ,@CNSPCJ          VARCHAR(20)   
        ,@AUX             NVARCHAR(MAX) ,@PROCESO          VARCHAR(20)  ,@VALOR             DECIMAL(12,4) ,@SELECCIONADOS   VARCHAR(1000)
        ,@CNSFACJDEP      VARCHAR(50)   ,@CODCAJADEP       NVARCHAR(MAX),@CTA_BCO           VARCHAR(40)   ,@NUMEROAUTORIZA  VARCHAR(20)
        ,@NUMERODOCUMENTO VARCHAR(20)   ,@SUCURSAL         VARCHAR(20)  ,@TERCERO           NVARCHAR(MAX) ,@TIPOPAGO        NVARCHAR(MAX)
        ,@TIPO_TERCERO    NVARCHAR(MAX) ,@BANCODATO        NVARCHAR(MAX),@CNSDOC            VARCHAR(20)   ,@NUM_CUENTA      NVARCHAR(MAX)		,@NUMERO_CUENTA VARCHAR(20)
        ,@N_FACTURA       VARCHAR(16)   ,@ESTADO           VARCHAR(1)   ,@FECHAFCJ          DATE          ,@NROCOMPROBANTE  VARCHAR(20)
	     ,@FORMAPAGO       VARCHAR(20)	 ,@DESCRIPCION      VARCHAR(200)	,@DATOS             NVARCHAR(MAX) ,@DATOD           NVARCHAR(MAX)	   ,@TIPO VARCHAR(20)
	     ,@RECAUDO         BIT		       ,@NOMBREAFI        VARCHAR(200)	,@DESC_NUMDOCUMENTO VARCHAR(20)	 ,@PAG_IDPAGARE VARCHAR(20),@IDCJFPAEFECTIVO VARCHAR(10)
        ,@CLASE_FAC       VARCHAR(5)		,@NODOCUMENTO VARCHAR(20)
        ,@TRASLADO_CNSFACJ VARCHAR(20) ,@CERRADO_PRI SMALLINT ,@ESTADO_MCP VARCHAR(1) ,@CNSRESOL_FCJ VARCHAR(50) ,@N_FACTURA_FCJ VARCHAR(16),
       @ANOMES_MCP       VARCHAR(30) ,@CONTABILIZADA_FCJ SMALLINT ,@CLASE_CAJ VARCHAR(9)	,@BANCO VARCHAR(20)
DECLARE @FECHA_AUT DATETIME, @FECHAI    VARCHAR(10)

DECLARE @TABLERRR		TABLE (ERROR VARCHAR(200))

BEGIN 
	SET LANGUAGE Spanish;  
	SET DATEFORMAT dmy
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
	-- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIOpl,   --PRINT 'USUARIO:'+@USUARIO
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO), @USUNOMBRE = NOMBRE FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME, @COMPANIA = COMPANIA, @CODCAJERO= CODCAJERO FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @IDSEDE = IDSEDE , @IDAREA=  IDAREA ,  @CCOSTO =CCOSTO FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
	PRINT '@USUARIO='+@USUARIO

	
   IF @METODO = 'INSERTA_RECIBO'
	BEGIN
     SELECT @DATOS = DATOS, @DATOD = DATOD, @CODCAJA = CODCAJA
     FROM OPENJSON(@PARAMETROS) WITH  (	DATOS		NVARCHAR(MAX) AS JSON ,
										DATOD       NVARCHAR(MAX) AS JSON,
										CODCAJA		VARCHAR(20) '$.CODCAJA')
       SELECT * INTO #DATOS
	  FROM OPENJSON(@DATOS) 
      WITH (	
            TIPO          VARCHAR(30)   '$.TIPO' ,
            RECAUDO         BIT   '$.RECAUDO' , 
            IDTERCERO			VARCHAR(50)   '$.IDTERCERO' , 
            NOADMISION			VARCHAR(20)   '$.NOADMISION' , 
            IDAFILIADO			VARCHAR(20)   '$.IDAFILIADO' , 
            OBSERVACION         VARCHAR(200)   '$.OBSERVACION' ,
            FECHA				VARCHAR(10)		'$.FECHA' ,
            HORA				VARCHAR(5)		'$.HORA' 
            --CODCAJADEP        NVARCHAR(MAX)   AS JSON, 
              )
    SELECT * INTO #DATOD
	FROM OPENJSON(@DATOD) 
      WITH (	
            CANTIDAD			INT  '$.CANTIDAD' ,
            DESCRIPCION			NVARCHAR(MAX)   AS JSON, 
            TOTAL				VARCHAR(50)   '$.TOTAL' , 
            TIPO				VARCHAR(20)   '$.TIPO'
              )
	
	SELECT @TIPO = TIPO FROM #DATOS
	SELECT @CNSACJ = CNSACJ FROM CAJ WHERE CODCAJA = @CODCAJA 
	IF @TIPO = 'INTERNO'
	BEGIN
		SELECT @NOADMISION = NOADMISION,  @IDTERCERO = IDTERCERO, @OBSERVACION = OBSERVACION FROM #DATOS
		SELECT  @IDAFILIADO = IDAFILIADO, @IDPLAN = IDPLAN FROM HADM WHERE  NOADMISION = @NOADMISION
		SELECT @NOMBREAFI = NOMBREAFI FROM AFI WHERE  IDAFILIADO = @IDAFILIADO
		PRINT '@NOADMISION' + @NOADMISION
	END
	IF @TIPO = 'EXTERNO'
	BEGIN
		SELECT  @IDAFILIADO = IDAFILIADO, @OBSERVACION = OBSERVACION , @IDTERCERO = IDTERCERO FROM #DATOS
		SELECT @NOMBREAFI = NOMBREAFI FROM AFI WHERE  IDAFILIADO = @IDAFILIADO
	END
	IF ( @RECAUDO = 1 AND COALESCE(@IDTERCERO,'')<>'') 
	BEGIN
		SELECT @NOMBREAFI = RAZONSOCIAL FROM TER WHERE  @IDTERCERO = IDTERCERO
	END

       
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN

         BEGIN TRY
		 --FECHA
			SELECT  @FECHAI = REPLACE(JSON_VALUE(@DATOS ,'$.FECHA'),'-','')
			SELECT @HORA =		JSON_VALUE(@DATOS ,'$.HORA')
			--SELECT DBO.FNK_GETDATE()
			SELECT @FECHA_AUT = CONVERT(DATETIME,CONCAT(@FECHAI,' ',@HORA))
			SET @CNSFACJ=NULL
			EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJ',@CNSFACJ OUTPUT
			SELECT @CNSFACJ =  REPLACE(SPACE(8 - LEN(@CNSFACJ))+LTRIM(RTRIM(@CNSFACJ)),SPACE(1),0)
	
			 INSERT INTO FCJ (CNSFACJ,TIPO,CODCAJA,COMPANIA, CLASE_FAC,CNSACJ,ESTADO,USUARIO,SYS_ComputerName,IDTERCERO, FECHA, TIPOEGRESO, OBSERVACION, PROCEDENCIA, VALORTOTAL , USUARIOLOG
			 ,BANCO, SUCURSAL, CTA_BCO, NOADMISION, CERRADA, ARCHIVADO, IDPLAN, IDAFILIADO, NOMBRECLIENTE , DEAPERTURA , RECAUDO , ENPAGOS, IMPRESO , AREAPRESTACION, CCOSTO , CLASER
			 , TCNSFACJ , IDENTIFICADOR , DEVUELTO )
			 
			 SELECT @CNSFACJ, CASE WHEN @TIPO='EXTERNO' THEN 'EXTERNO' ELSE 'INTERNO' END , @CODCAJA, @COMPANIA, 'COBRO', @CNSACJ, 'P', @CODCAJERO, @SYS_COMPUTERNAME, IDTERCERO, @FECHA_AUT, null, @OBSERVACION, 'CAJA',0, @USUARIO
			, null,null,null, @NOADMISION, 0, 0, @IDPLAN, @IDAFILIADO, @NOMBREAFI , 0  , COALESCE( RECAUDO ,0 ) , 0, 0 ,@IDAREA ,@CCOSTO ,'C' , '', '' , 0
			FROM #DATOS

			INSERT INTO FCJD (CODCAJA, CNSFACJ, ITEM, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, TIPODCTO)
			SELECT @CODCAJA, @CNSFACJ, ROW_NUMBER()  OVER (ORDER BY TIPO),  (SELECT VALOR FROM OPENJSON(DESCRIPCION) WITH (VALOR VARCHAR(20) '$.value')), TOTAL, 1, TOTAL, 'N'
			FROM #DATOD

			--SELECT TOP 100  (SELECT VALOR FROM OPENJSON(DESCRIPCION) WITH (VALOR VARCHAR(20) '$.value')), * FROM #DATOD

			UPDATE FCJ SET VALORTOTAL =  (SELECT SUM (VALORTOTAL) FROM FCJD WHERE FCJD.CODCAJA = @CODCAJA AND FCJD.CNSFACJ = @CNSFACJ  ) WHERE FCJ.CODCAJA = @CODCAJA AND FCJ.CNSFACJ = @CNSFACJ
		
         END TRY
         BEGIN CATCH
           INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         
		 IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
	      BEGIN
		      SELECT 'KO' OK
		      SELECT ERROR FROM @TBLERRORES
		      RETURN
	      END	
	      SELECT 'OK'OK
       END
    END
	IF @METODO = 'APROVECHAMIENTO'
	BEGIN
		SELECT @CODCAJA = CODCAJA, @CNSFACJ = CNSFACJ, @VALOR = VALOR
		FROM OPENJSON(@PARAMETROS)
		WITH(	CODCAJA		VARCHAR(20)		'$.CODCAJA' ,CNSFACJ		VARCHAR(20)		 '$.CNSFACJ'
				,VALOR		DECIMAL(14,2)	'$.VALOR')
	
		IF COALESCE(@VALOR,0) = 0
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'Debe de ingresar un numero mayor a 0'
		END
		IF NOT EXISTS (SELECT * FROM FCJD WHERE CNSFACJ= @CNSFACJ AND CODCAJA= @CODCAJA)
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'No cuenta con Movimiento de Detalle.'
		END
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				SELECT @ITEM =     MAX(ITEM) FROM FCJD WHERE CNSFACJ= @CNSFACJ AND CODCAJA= @CODCAJA
		
				INSERT INTO FCJD (CODCAJA, N_RECIBO, CNSFACJ,ITEM , CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, 
					CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO, PCOSTOUNIT, ESIMPTOGEN, 
					CUENTACM, CCOSTO, IDAREA)
				SELECT CODCAJA, N_RECIBO, CNSFACJ, @ITEM +1 , DBO.FNK_VALORVARIABLE ('IDCJAPROVECHAMIENTO') , AREAFUNCIONAL, 
					@VALOR, 1, @VALOR, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO, PCOSTOUNIT, ESIMPTOGEN, 
					CUENTACM, CCOSTO, IDAREA 
				FROM   FCJD  
					WHERE  FCJD.CODCAJA= @CODCAJA
					AND    FCJD.CNSFACJ= @CNSFACJ
					AND    FCJD.ITEM   = @ITEM

				EXEC SPK_TOTFCJ_IN @CODCAJA , @CNSFACJ

			END TRY
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
		END 
	END	
	IF @METODO = 'DELETE_FCJD'
	BEGIN
		SELECT @CODCAJA = CODCAJA, @CNSFACJ = CNSFACJ, @CONCEPTO = CONCEPTO
		FROM OPENJSON(@PARAMETROS)
		WITH(	CODCAJA		VARCHAR(20)		'$.CODCAJA' ,CONCEPTO		VARCHAR(20)		 '$.CONCEPTO'
				,CNSFACJ	VARCHAR(20)		'$.CNSFACJ')
	
		IF EXISTS(SELECT  * FROM FCJ WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND COALESCE(CERRADA,0) = 1 )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El registro ya se encuentra cerrado'
		END
		IF EXISTS(SELECT  * FROM FCJ WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND COALESCE(ESTADO,'') = 'D' )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El registro ya se encuentra desechado'
		END
		IF EXISTS(SELECT  * FROM PCJ WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'Para editar los Conceptos de Pago, elimine las formas de pago.'
		END
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				DELETE FROM FCJD WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND CONCEPTO = @CONCEPTO
				UPDATE FCJ SET VALORTOTAL =  (SELECT SUM (VALORTOTAL) FROM FCJD WHERE FCJD.CODCAJA = @CODCAJA AND FCJD.CNSFACJ = @CNSFACJ  ) WHERE FCJ.CODCAJA = @CODCAJA AND FCJ.CNSFACJ = @CNSFACJ

			END TRY
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
			SELECT	COALESCE((SELECT SUM(VALOR) FROM PCJ WHERE  PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ),0) [MONTOTOTAL]
					, FCJ.VALORTOTAL - COALESCE((SELECT SUM(VALOR) FROM PCJ WHERE  PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ),0) [MONTOPENDIENTE]
			FROM [dbo].[FCJ] 
			WHERE  FCJ.CODCAJA = @CODCAJA AND FCJ.CNSFACJ = @CNSFACJ
		END 
	END
	IF @METODO = 'INSERTA_FCJD'
	BEGIN
		SELECT @CODCAJA = CODCAJA, @CNSFACJ = CNSFACJ, @CONCEPTO = CONCEPTO, @VALOR = VALOR, @PROCESO = PROCESO
		FROM OPENJSON(@PARAMETROS)
		WITH(	CODCAJA		VARCHAR(20)		'$.CODCAJA' ,CONCEPTO		VARCHAR(20)		 '$.CONCEPTO'
				,CNSFACJ	VARCHAR(20)		'$.CNSFACJ' ,VALOR			DECIMAL(14,2)		'$.VALOR'
				,PROCESO	VARCHAR(20)		 '$.PROCESO')
	
		IF EXISTS(SELECT  * FROM FCJ WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND COALESCE(CERRADA,0) = 1 )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El registro ya se encuentra cerrado'
		END
		IF EXISTS(SELECT  * FROM FCJ WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND COALESCE(ESTADO,'') = 'D' )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El registro ya se encuentra desechado'
		END
		IF EXISTS(SELECT  * FROM PCJ WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'Para editar los Conceptos de Pago, elimine las formas de pago.'
		END
		IF @PROCESO = 'Insertar' AND EXISTS (SELECT * FROM FCJD WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND CONCEPTO = @CONCEPTO)
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'Ya existe el concepto creado'
		END
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				IF @PROCESO = 'Insertar'
				BEGIN
					INSERT INTO FCJD (CODCAJA, CNSFACJ, ITEM, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, TIPODCTO)
					SELECT @CODCAJA, @CNSFACJ,COALESCE((SELECT MAX (ITEM )FROM FCJD WHERE  FCJD.CODCAJA = @CODCAJA AND FCJD.CNSFACJ = @CNSFACJ ),0) +1 , @CONCEPTO, COALESCE(@VALOR,0), 1, COALESCE(@VALOR,0), 'N'
				END
				IF @PROCESO = 'Editar'
				BEGIN
					UPDATE FCJD SET VALORUNITARIO = @VALOR, VALORTOTAL = @VALOR WHERE FCJD.CODCAJA = @CODCAJA AND FCJD.CNSFACJ = @CNSFACJ AND CONCEPTO = @CONCEPTO
				END
				UPDATE FCJ SET VALORTOTAL =  (SELECT SUM (VALORTOTAL) FROM FCJD WHERE FCJD.CODCAJA = @CODCAJA AND FCJD.CNSFACJ = @CNSFACJ  ) WHERE FCJ.CODCAJA = @CODCAJA AND FCJ.CNSFACJ = @CNSFACJ

			END TRY
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
			SELECT	COALESCE((SELECT SUM(VALOR) FROM PCJ WHERE  PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ),0) [MONTOTOTAL]
					, FCJ.VALORTOTAL - COALESCE((SELECT SUM(VALOR) FROM PCJ WHERE  PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ),0) [MONTOPENDIENTE]
			FROM [dbo].[FCJ] 
			WHERE  FCJ.CODCAJA = @CODCAJA AND FCJ.CNSFACJ = @CNSFACJ
		END 
	END
	IF @METODO = 'EDITA_FCJ'
	BEGIN
		SELECT @CODCAJA = CODCAJA, @CNSFACJ = CNSFACJ, @FECHA = FECHA, @HORA = HORA, @TIPO = TIPO
				, @IDTERCERO = IDTERCERO, @NOADMISION = NOADMISION, @RECAUDO = RECAUDO, @OBSERVACION = OBSERVACION
		FROM OPENJSON(@PARAMETROS)
		WITH(	CODCAJA			VARCHAR(20)		'$.CODCAJA' ,IDTERCERO		VARCHAR(20)		 '$.IDTERCERO'
				,TIPO			VARCHAR(20)		'$.TIPO' ,FECHA		VARCHAR(20)		 '$.FECHA'
				,HORA			VARCHAR(5)		 '$.HORA',NOADMISION		VARCHAR(20)		 '$.NOADMISION'
				,CNSFACJ		VARCHAR(20)		'$.CNSFACJ' ,RECAUDO	BIT		'$.RECAUDO' 
				,OBSERVACION	VARCHAR(MAX)		 '$.OBSERVACION')
	
		IF EXISTS(SELECT  * FROM FCJ WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND COALESCE(CERRADA,0) = 1 )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El registro ya se encuentra cerrado'
		END
		IF EXISTS(SELECT  * FROM FCJ WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA AND COALESCE(ESTADO,'') = 'D' )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El registro ya se encuentra desechado'
		END
		IF  EXISTS (SELECT * FROM FCJD WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA) AND 1 = 2
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'Existe conceptos de pago, debe de eliminarlos, para que se pueda editar.'
		END
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				SELECT  @FECHA = REPLACE(@FECHA,'-','')
				SELECT @FECHA_AUT = CONVERT(DATETIME,CONCAT(@FECHA,' ',@HORA))

				UPDATE FCJ SET OBSERVACION = @OBSERVACION, RECAUDO = @RECAUDO, FECHA = @FECHA_AUT , IDTERCERO = @IDTERCERO, NOADMISION = @NOADMISION, TIPO = @TIPO WHERE  FCJ.CODCAJA = @CODCAJA AND FCJ.CNSFACJ = @CNSFACJ
				UPDATE FCJ SET VALORTOTAL =  (SELECT SUM (VALORTOTAL) FROM FCJD WHERE FCJD.CODCAJA = @CODCAJA AND FCJD.CNSFACJ = @CNSFACJ  ) WHERE FCJ.CODCAJA = @CODCAJA AND FCJ.CNSFACJ = @CNSFACJ

			END TRY
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
		END 
	END
	IF @METODO = 'IMPRIME_ARQUEO_EGRESO'
	BEGIN
      SELECT  @CODCAJA = CODCAJA, @CNSFACJ = CNSFACJ, @CNSACJ = CNSACJ
      FROM OPENJSON(@PARAMETROS)WITH(
	   CODCAJA        VARCHAR(20)    '$.CODCAJA' ,
	   CNSFACJ        VARCHAR(20)    '$.CNSFACJ' ,
	   CNSACJ         VARCHAR(20)    '$.CNSACJ' 
      )

		IF NOT EXISTS (SELECT ACJ.CNSACJ, ACJ.CODCAJA, CAJ.DESCRIPCION, 
				convert(varchar,ACJ.FECHAAPERTURA,103)+' '+convert(varchar,ACJ.FECHAAPERTURA,8) FECHAAPERTURA,
				ACJ.CODTURNO, TUR.DESCRIPCION, ACJ.CODCAJERO, CJR.DESCRIPCION, 
				convert(varchar,ACJ.FECHACIERRE,103)+' '+convert(varchar,ACJ.FECHACIERRE,8) FECHACIERRE, 
				IIF(ACJ.ABIERTA=0,'NO','SI') ABIERTA
			FROM ACJ 
				INNER JOIN CAJ ON ACJ.CODCAJA = CAJ.CODCAJA
				INNER JOIN TUR ON TUR.CODTURNO = ACJ.CODTURNO
				INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
			WHERE ACJ.CODCAJA = @CODCAJA AND ACJ.CNSACJ = @CNSACJ)
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'No cuenta con Arquedo de Caja.'
		END
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				SELECT 'OK' OK,ACJ.CNSACJ, ACJ.CODCAJA, CAJ.DESCRIPCION, 
					convert(varchar,ACJ.FECHAAPERTURA,103)+' '+convert(varchar,ACJ.FECHAAPERTURA,8) FECHAAPERTURA,
					ACJ.CODTURNO, TUR.DESCRIPCION [DESC_TURNO], ACJ.CODCAJERO, CJR.DESCRIPCION [NOM_CAJERO], 
					convert(varchar,ACJ.FECHACIERRE,103)+' '+convert(varchar,ACJ.FECHACIERRE,8) FECHACIERRE, 
					IIF(ACJ.ABIERTA=0,'NO','SI') ABIERTA
					,SED.DESCRIPCION [SED_NOMBRE], SED.DIRECCION [SED_DIRECCION]
					, SED.TELEFONOS [SED_TELEFONOS],   SED.NIT [SED_NIT], SED.DV [SED_DV], TERSED.NIT [NIT_ASEG], TERSED.RAZONSOCIAL [ASEG_NOMBRE],CIUSED.NOMBRE [SED_CIUDAD]
				FROM ACJ 
					INNER JOIN CAJ ON ACJ.CODCAJA = CAJ.CODCAJA
					INNER JOIN TUR ON TUR.CODTURNO = ACJ.CODTURNO
					INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
					LEFT JOIN SED ON SED.IDSEDE = @IDSEDE
					LEFT JOIN TER TERSED ON SED.NIT = TERSED.NIT AND COALESCE(TERSED.RAZONSOCIAL,'') <> ''
					LEFT JOIN CIU CIUSED ON SED.CIUDAD = CIUSED.CIUDAD
				WHERE ACJ.CODCAJA = @CODCAJA AND ACJ.CNSACJ = @CNSACJ
				ORDER BY FECHAAPERTURA ASC

         /*DETALLE*/
         SELECT 'OK' OK, FCJ.CNSFACJ, FCJ.FECHA, FCJ.NOMBRECLIENTE, FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION [CONCEPTO], 
                SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  PCJ.VALOR ELSE 0 END) INGRESOS, 
                SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  PCJ.VALOR ELSE 0 END)  EGRESOS
         FROM FCJ INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
                  INNER JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
                  INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO 
                  LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
         WHERE FCJ.CNSACJ=@CNSACJ
         AND FCJ.CERRADA=1 
         AND COALESCE(FCJ.DEAPERTURA,0) <>1 
         AND FCJ.ESTADO<>'A' AND FCJ.CLASE_FAC = 'COBRO'
         GROUP BY  FCJ.CNSFACJ, FCJ.FECHA, FCJ.NOMBRECLIENTE, FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION
         UNION ALL
         SELECT  'OK' OK, FCJ.CNSACJ, FCJ.FECHA, ACJ.CODCAJERO+'-'+ CJR.DESCRIPCION [NOMBRECLIENTE] , FCJD.CONCEPTO+'-'+CPCJ.DESCRIPCION [CONCEPTO] , FCJ.VALORTOTAL INGRESOS, 0 EGRESOS 
         FROM FCJ 
               INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
               INNER JOIN ACJ ON FCJ.CNSACJ = ACJ.CNSACJ AND FCJ.CODCAJA = ACJ.CODCAJA
               INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
               LEFT JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
               LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
         WHERE  FCJ.CNSACJ = @CNSACJ AND FCJ.CODCAJA = @CODCAJA AND FCJ.CNSFACJ = @CNSACJ
         UNION ALL
         SELECT 'OK' OK,  FCJ.N_RECIBO CNSFACJ, FCJ.FECHA, FCJ.IDTERCERO+'-'+TER.RAZONSOCIAL [NOMBRECLIENTE], FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION [CONCEPTO], 
                SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  PCJ.VALOR ELSE 0 END) INGRESOS, 
                SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  PCJ.VALOR ELSE 0 END)  EGRESOS
         FROM FCJ INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
                  INNER JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
                  INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO 
                  LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
                  --LEFT JOIN CAJ ON FCJ.IDTERCERO = CAJ.CODCAJA
				  LEFT JOIN TER ON FCJ.IDTERCERO = TER.IDTERCERO
         WHERE FCJ.CNSACJ=@CNSACJ
         AND FCJ.CERRADA=1 
         AND COALESCE(FCJ.DEAPERTURA,0) <>1 
         AND FCJ.ESTADO<>'A' AND FCJ.CLASE_FAC = 'PAGO'
         GROUP BY  FCJ.N_RECIBO , FCJ.FECHA, FCJ.IDTERCERO+'-'+TER.RAZONSOCIAL , FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION
         
         /*Total Recibos*/
         SELECT SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  PCJ.VALOR ELSE 0 END) INGRESOS, 
                SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  PCJ.VALOR ELSE 0 END)  EGRESOS
         FROM FCJ INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
                  INNER JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
                  INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO 
                  LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
         WHERE FCJ.CNSACJ=@CNSACJ
         AND FCJ.CERRADA=1 
         AND COALESCE(FCJ.DEAPERTURA,0) <>1 
         AND FCJ.ESTADO<>'A'

         /*SUB TOTAL*/
         SELECT PCJ.TIPOPAGO,FPA.DESCRIPCION,SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  PCJ.VALOR ELSE 0 END) [VLR_INGRESO], 
            SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  PCJ.VALOR ELSE 0 END) [VLR_EGRESOS],
            SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  PCJ.VALOR ELSE 0 END)-SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  PCJ.VALOR ELSE 0 END) [VLR_SALDO]
         FROM FCJ INNER JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
                  INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO 
         WHERE FCJ.CNSACJ=@CNSACJ
         AND FCJ.CERRADA=1 
         AND COALESCE(FCJ.DEAPERTURA,0) <>1  
         AND FCJ.ESTADO<>'A'
         GROUP BY PCJ.TIPOPAGO,FPA.DESCRIPCION

         /*CAJERO IMPRIME*/
         SELECT CJR.CODCAJERO+' - '+CJR.DESCRIPCION [NOM_CAJERO] FROM  USUSU 
            LEFT JOIN CJR ON USUSU.CODCAJERO = CJR.CODCAJERO
         WHERE USUSU.USUARIO = @USUARIO

         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
      END
   END 
	IF @METODO = 'FORMA_PAGO_EGRESO_NO'
	BEGIN
	SELECT @CODCAJA = CODCAJA
	   FROM OPENJSON (@PARAMETROS)
	   WITH		 (CODCAJA				VARCHAR(5)		'$.CODCAJA'
					)

		SELECT 'OK' AS OK
		/* TIPOS DE EGRESO */
		SELECT  CJTE.TIPOEGRESO value, CJTE.DESCRIPCION label, CJTE.IDCATEGORIA
			, CAST( CASE WHEN U1.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS BIT) CONSIGNACION
			,CAST( CASE WHEN U2.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS BIT) ESBANCO
			,CAST( CASE WHEN U3.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS BIT) TRASLADOBANCOCAJA
			,CAST( CASE WHEN U4.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS BIT) ESTRASLADO
			,CAST( CASE WHEN U5.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS BIT) ESNOMINA
			,CAST( CASE WHEN U6.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS BIT) TRASLADOENTREBANCOS
			,CAST( CASE WHEN U7.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS BIT) ESDEVOLUCION
			--, TERCEROS= (SELECT  IDTERCERO value, RAZONSOCIAL label, VWK_TEXCA.IDCATEGORIA  
			--			FROM VWK_TEXCA 
			--			WHERE VWK_TEXCA.IDCATEGORIA = CJTE.IDCATEGORIA AND ESTADO = 'Activo' AND CJTE.MTERCERO = 1 FOR JSON PATH)  
			, CJTE.MTERCERO
		FROM CJTE
			LEFT JOIN USVGS U1 ON U1.IDVARIABLE = 'IDCJTECONSIGNACION' 
			LEFT JOIN USVGS U2 ON U2.IDVARIABLE = 'TERCATBANCO' 
			LEFT JOIN USVGS U3 ON U3.IDVARIABLE = 'IDCJTETRASBCOCAJA' 
			LEFT JOIN USVGS U4 ON U4.IDVARIABLE = 'IDCJTETRASLADO' 
			LEFT JOIN USVGS U5 ON U5.IDVARIABLE = 'IDCJTENOMINA' 
			LEFT JOIN USVGS U6 ON U6.IDVARIABLE = 'IDCJTETRASLADOBCO' 
			LEFT JOIN USVGS U7 ON U7.IDVARIABLE = 'IDCJTEDEVOLDEPOSITO' 
		WHERE EXISTS(SELECT  * FROM TGEN WHERE TABLA = @CODCAJA AND  CAMPO = 'TIPOEGRESO' AND CODIGO = CJTE.TIPOEGRESO )
			AND EXISTS (SELECT   IDTERCERO, RAZONSOCIAL FROM VWK_TEXCA WHERE VWK_TEXCA.IDCATEGORIA = CJTE.IDCATEGORIA AND ESTADO = 'Activo' AND CJTE.MTERCERO = 1 )

		/* FORMAS DE PAGO */
		SELECT
			FPA.FORMAPAGO value
			,FPA.DESCRIPCION label
			,FISICO = CAST(FISICO AS BIT)
			,REQBCO = CAST(REQBCO AS BIT)
			,REQDOC = CAST(REQDOC AS BIT)
			,REQAUT = CAST(REQAUT AS BIT)
			,CXC = CAST(CXC AS BIT)
			,AUTINT = CAST(AUTINT AS BIT)
			,MEDIOPAGO  = CAST(MEDIOPAGO AS BIT)
			,TEDEVOLUCION = CAST(TEDEVOLUCION AS BIT)
			,CUENTA
			,CEROENAPERTURA = CAST(CEROENAPERTURA AS BIT)
			,USAR_CUENTACAJA = CAST(USAR_CUENTACAJA AS BIT)  
			,REQCTA_BCO_DEP = CAST(REQCTA_BCO_DEP AS BIT)
			,GENCHEQUE = CAST(GENCHEQUE AS BIT)
			,COMPROBANTE_EGR
			,DATAFONO = CAST(COALESCE(DATAFONO,0) AS BIT)
			,PAGARE = CAST(CASE WHEN U1.DATO = FPA.FORMAPAGO THEN 1 ELSE 0 END AS BIT)
			,DESCUENTO_NOMINA = CAST(CASE WHEN U2.DATO = FPA.FORMAPAGO THEN 1 ELSE 0 END AS BIT)
			,TERCEROS = (SELECT TER.IDTERCERO value, TER.RAZONSOCIAL label FROM BCO INNER JOIN TER ON BCO.IDTERCERO = TER.IDTERCERO WHERE CAST(REQBCO AS BIT) = 1 FOR JSON PATH)
		FROM FPA
			INNER JOIN TGEN ON FPA.FORMAPAGO = TGEN.CODIGO AND TGEN.CAMPO = 'FORMAPAGO' AND TGEN.TABLA = @CODCAJA
			LEFT JOIN USVGS U1 ON U1.IDVARIABLE = 'IDFPAPAGARE'
			LEFT JOIN USVGS U2 ON U2.IDVARIABLE = 'IDCJFPADESCUENT_NOMI'

	END
	IF @METODO = 'ESTADO_CAJA'
	BEGIN
		SELECT @CODCAJA = CODCAJA
	   FROM OPENJSON (@PARAMETROS)
	   WITH		 (CODCAJA				VARCHAR(5)		'$.CODCAJA'
			   )

		SELECT 'OK' AS OK
		SELECT CAJ.CODCAJA
			,CAJ.DESCRIPCION
			,CAJ.TIPO
			,CAJ.CLASE
			,CAJ.FOFI
			,CAJ.ESTADO
			,CAJ.ABIERTA
			,CASE
				WHEN CAJ.ABIERTA = 1 THEN
					CASE WHEN (SELECT COUNT(1) FROM ACJ WHERE CAJ.CNSACJ = ACJ.CNSACJ AND ACJ.CODCAJA = CAJ.CODCAJA AND ACJ.ABIERTA = 1) = 1
						THEN N'Abierta'
						ELSE N'ABIERTA ERROR'
					END
				WHEN (SELECT COUNT(1) FROM ACJ WHERE ACJ.CODCAJA = CAJ.CODCAJA AND ACJ.ABIERTA = 1) > 0
					THEN N'ABIERTA ERROR'
				ELSE N'Cerrada'
				END [ESTACAJA]
			,CAJ.CNSACJ
		FROM [dbo].[CAJ]
		WHERE 1=1
			AND CAJ.CODCAJA = @CODCAJA
			AND CAJ.ESTADO IN ('Activo','Inactivo')

	END
	IF @METODO = 'FORMA_TIPOEGRESO'
	BEGIN
		SELECT @FORMAPAGO =  FORMAPAGO, @CODCAJA = CODCAJA, @DESCRIPCION = DESCRIPCION
	   FROM OPENJSON (@PARAMETROS)
	   WITH		 (FORMAPAGO				VARCHAR(20)		'$.FORMAPAGO'
				   ,CODCAJA				VARCHAR(5)		'$.CODCAJA'
				   ,DESCRIPCION			VARCHAR(100)    '$.DESCRIPCION'
			   )

		BEGIN TRY 
			SELECT 'OK'OK
			SELECT  CJTE.TIPOEGRESO value, CJTE.DESCRIPCION label, CJTE.IDCATEGORIA
			,CAST( CASE WHEN U1.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS INT) CONSIGNACION
			,CAST( CASE WHEN U2.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS INT) ESBANCO
			,CAST( CASE WHEN U3.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS INT) TRASLADOBANCOCAJA
			,CAST( CASE WHEN U4.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS INT) ESTRASLADO
			,CAST( CASE WHEN U5.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS INT) ESNOMINA
			,CAST( CASE WHEN U6.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS INT) TRASLADOENTREBANCOS
			,CAST( CASE WHEN U7.DATO = CJTE.TIPOEGRESO THEN 1 ELSE 0 END AS INT) ESDEVOLUCION
			, TERCEROS= (SELECT   IDTERCERO value, RAZONSOCIAL label, VWK_TEXCA.IDCATEGORIA  
						FROM VWK_TEXCA 
						WHERE VWK_TEXCA.IDCATEGORIA = CJTE.IDCATEGORIA AND ESTADO = 'Activo' AND CJTE.MTERCERO = 1 FOR JSON PATH)  
			, CJTE.MTERCERO
		FROM CJTE
			LEFT JOIN USVGS U1 ON U1.IDVARIABLE = 'IDCJTECONSIGNACION' 
			LEFT JOIN USVGS U2 ON U2.IDVARIABLE = 'TERCATBANCO' 
			LEFT JOIN USVGS U3 ON U3.IDVARIABLE = 'IDCJTETRASBCOCAJA' 
			LEFT JOIN USVGS U4 ON U4.IDVARIABLE = 'IDCJTETRASLADO' 
			LEFT JOIN USVGS U5 ON U5.IDVARIABLE = 'IDCJTENOMINA' 
			LEFT JOIN USVGS U6 ON U6.IDVARIABLE = 'IDCJTETRASLADOBCO' 
			LEFT JOIN USVGS U7 ON U7.IDVARIABLE = 'IDCJTEDEVOLDEPOSITO' 
		WHERE EXISTS(SELECT  * FROM TGEN WHERE TABLA = @CODCAJA AND CJTE.TIPOEGRESO = @FORMAPAGO  AND  CAMPO = 'TIPOEGRESO' AND CODIGO = CJTE.TIPOEGRESO )
			AND EXISTS (SELECT   IDTERCERO, RAZONSOCIAL FROM VWK_TEXCA WHERE VWK_TEXCA.IDCATEGORIA = CJTE.IDCATEGORIA AND ESTADO = 'Activo' AND CJTE.MTERCERO = 1 )
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF EXISTS(SELECT 1 FROM @TBLERRORES)
		BEGIN
			SELECT 'KO' AS OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		SELECT 'OK' AS OK

		RETURN
	END
	IF @METODO = 'BUSCA_CHEQUE'
	BEGIN
		SELECT @BANCO = BANCO, @SUCURSAL = SUCURSAL, @CTA_BCO = CTA_BCO, @TIPOPAGO = TIPOPAGO
		FROM OPENJSON(@PARAMETROS)
		WITH(	BANCO	VARCHAR(20)		'$.BANCO',SUCURSAL	VARCHAR(20)		'$.SUCURSAL',CTA_BCO	VARCHAR(20)		'$.CTA_BCO'
			,TIPOPAGO	VARCHAR(20)		'$.TIPOPAGO')


		SELECT 'OK'OK , (SELECT COUNT(DISTINCT CNSDOC) FROM BCTDD WHERE BANCO = @BANCO AND  SUCURSAL = @SUCURSAL 
		AND  CTA_BCO = @CTA_BCO AND ESTADO = 'N') VENTANA

		IF (SELECT COUNT(DISTINCT CNSDOC) FROM BCTDD WHERE BANCO = @BANCO AND  SUCURSAL = @SUCURSAL 
		AND  CTA_BCO = @CTA_BCO AND ESTADO = 'N')>0
		BEGIN
			SELECT DISTINCT CNSDOC value, CNSDOC label FROM BCTDD WHERE BANCO = @BANCO AND  SUCURSAL = @SUCURSAL 
			AND  CTA_BCO = @CTA_BCO AND ESTADO = 'N'
		END
	END
	--IF @METODO = 'BUSCA_NODOCUMENTO_CHEQUE'
	--BEGIN

	--	SELECT @SUCURSAL = SUCURSAL, @CTA_BCO = CTA_BCO, @TIPOPAGO = TIPOPAGO, @CNSDOC = CNSDOC
	--	FROM OPENJSON(@PARAMETROS)
	--	WITH(	SUCURSAL	VARCHAR(20)		'$.SUCURSAL',CTA_BCO	VARCHAR(20)		'$.CTA_BCO'
	--		,TIPOPAGO	VARCHAR(20)		'$.TIPOPAGO',CNSDOC	VARCHAR(20)		'$.CNSDOC')
	--    SET @BANCO = COALESCE(@BANCO, JSON_VALUE(@PARAMETROS, '$.BANCO.value'));

	--	IF EXISTS (SELECT 1 FROM BCTD WHERE CNSDOC = @CNSDOC AND MCNSALFA = 1)
	--	BEGIN
	--		SELECT 'ES ALFA HAY QUE ACTUALIZAR BCTDD'
	--		RETURN
	--	END

	--	SELECT 'OK' OK
	--	SELECT @NODOCUMENTO =  MIN(NODOCUMENTO)  FROM BCTDD WHERE BANCO = @BANCO AND  SUCURSAL = @SUCURSAL 
	--	AND  CTA_BCO = @CTA_BCO AND ESTADO = 'N' AND CNSDOC = @CNSDOC

	--	SELECT NODOCUMENTO, CNSALFA  FROM BCTDD WHERE BANCO = @BANCO AND  SUCURSAL = @SUCURSAL 
	--	AND  CTA_BCO = @CTA_BCO AND ESTADO = 'N' AND CNSDOC = @CNSDOC AND NODOCUMENTO = @NODOCUMENTO

	--END

	IF @METODO = 'BUSCA_NODOCUMENTO_CHEQUE'
	BEGIN
		DECLARE @CNSALFA VARCHAR(20), @IDTERCERO_BCTDD VARCHAR(20)

		SELECT @SUCURSAL = SUCURSAL, @CTA_BCO = CTA_BCO, @TIPOPAGO = TIPOPAGO, @CNSDOC = CNSDOC
		FROM OPENJSON(@PARAMETROS)
		WITH (SUCURSAL VARCHAR(20) '$.SUCURSAL', CTA_BCO  VARCHAR(20) '$.CTA_BCO', TIPOPAGO VARCHAR(20) '$.TIPOPAGO', CNSDOC   VARCHAR(20) '$.CNSDOC');
		
		SET @BANCO = COALESCE(JSON_VALUE(@PARAMETROS, '$.BANCO'), JSON_VALUE(@PARAMETROS, '$.BANCO.value'))
		
		SELECT @NODOCUMENTO = MIN(NODOCUMENTO)
		FROM BCTDD
		WHERE BANCO    = @BANCO
		  AND SUCURSAL = @SUCURSAL
		  AND CTA_BCO  = @CTA_BCO
		  AND ESTADO   = 'N'
		  AND CNSDOC   = @CNSDOC;
		 
		SELECT @CNSALFA = CNSALFA, @IDTERCERO_BCTDD = IDTERCERO
		FROM BCTDD
		WHERE BANCO       = @BANCO
		  AND SUCURSAL    = @SUCURSAL
		  AND CTA_BCO     = @CTA_BCO
		  AND CNSDOC      = @CNSDOC
		  AND NODOCUMENTO = @NODOCUMENTO;

		IF EXISTS (
			SELECT 1
			FROM BCTD
			WHERE BANCO    = @BANCO
			  AND SUCURSAL = @SUCURSAL
			  AND CTA_BCO  = @CTA_BCO
			  AND CNSDOC   = @CNSDOC
			  AND COALESCE(MCNSALFA, 0) = 1
		)
		AND COALESCE(NULLIF(LTRIM(RTRIM(@CNSALFA)), ''), '') = ''
		BEGIN
			SELECT 'OK' OK;
			SELECT
				@NODOCUMENTO AS NODOCUMENTO,
				CAST(NULL AS VARCHAR(20)) AS CNSALFA,
				CAST(1 AS BIT) AS REQ_CNSALFA,
				@IDTERCERO_BCTDD AS IDTERCERO; 
			RETURN;
		END;

		SELECT 'OK' OK;
		SELECT NODOCUMENTO, CNSALFA, CAST(0 AS BIT) AS REQ_CNSALFA, IDTERCERO
		FROM BCTDD
		WHERE BANCO       = @BANCO
		  AND SUCURSAL    = @SUCURSAL
		  AND CTA_BCO     = @CTA_BCO
		  AND ESTADO      = 'N'
		  AND CNSDOC      = @CNSDOC
		  AND NODOCUMENTO = @NODOCUMENTO;
	END
	IF @METODO = 'EDIT_EGRESO'
	BEGIN
		SELECT  @CODCAJA = CODCAJA, @CNSFACJ = CNSFACJ, @FECHA = FECHA, @HORA = HORA, @IDTERCERO = IDTERCERO, @TIPOCAJA = TIPOCAJA, @OBSERVACION = OBSERVACION
			,@TIPOEGRESO = TIPOEGRESO, @CTA_BCO = CTA_BCO, @BANCO = BANCO, @SUCURSAL = SUCURSAL
		FROM OPENJSON(@PARAMETROS)WITH(
		CODCAJA        VARCHAR(20)    '$.CODCAJA' , FECHA        VARCHAR(10)    '$.FECHA' ,OBSERVACION        VARCHAR(500)    '$.OBSERVACION' ,
		CNSFACJ        VARCHAR(20)    '$.CNSFACJ' ,HORA        VARCHAR(5)    '$.HORA' ,			TIPOEGRESO        VARCHAR(20)    '$.TIPOEGRESO' ,
		IDTERCERO     VARCHAR(20)    '$.IDTERCERO' ,TIPOCAJA     VARCHAR(20)    '$.TIPOCAJA',CTA_BCO     VARCHAR(50)    '$.CTA_BCO' 
		,BANCO			VARCHAR(20)    '$.BANCO' ,SUCURSAL     VARCHAR(20)    '$.SUCURSAL' )
      /*STORRES - 20250520 -- SE QUITA VALIDACION DE CAJAMENOR POR QUE ESTOS SI PUEDEN EDITAR SIEMPRE Y CUANDO NO ESTE CONFIRMADO EL COMPROBATE
		IF @TIPOCAJA = 'Menor' 
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'No puede editar por ser caja Menor'
		END
      STORRES - 20250520 -- SE QUITA VALIDACION DE CAJAMENOR POR QUE ESTOS SI PUEDEN EDITAR SIEMPRE Y CUANDO NO ESTE CONFIRMADO EL COMPROBATE
      */

		IF EXISTS (SELECT * FROM FCJ WHERE CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ AND COALESCE(CERRADA,0) = 1 )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El registro ya se encuentra cerrado'
		END
		/* Egreso CXP: encabezado FCJ no editable */
		IF EXISTS (
			SELECT 1
			FROM FCJ
			WHERE FCJ.CODCAJA = @CODCAJA
			  AND FCJ.CNSFACJ = @CNSFACJ
			  AND FCJ.TIPOEGRESO = DBO.FNK_VALORVARIABLE('IDCJTECXP')
		)
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT N'Egreso CXP: no se permite modificar el encabezado del comprobante.'
		END
	
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				SELECT  @FECHAI = REPLACE(@FECHA,'-','')
				SELECT @FECHA_AUT = CONVERT(DATETIME,CONCAT(@FECHAI,' ',@HORA))

				IF COALESCE(@FECHA,'')=''
				BEGIN
					SELECT @FECHA_AUT =   CONVERT(DATETIME,CONCAT(CONVERT(VARCHAR(8), GETDATE(), 112),' ', CONVERT(VARCHAR(5), GETDATE(), 108)   )) 
				END
				UPDATE FCJ SET FECHA = @FECHA_AUT, IDTERCERO = @IDTERCERO, OBSERVACION = @OBSERVACION, TIPOEGRESO = @TIPOEGRESO  
							,CTA_BCO = @CTA_BCO, BANCO = @BANCO, SUCURSAL = @SUCURSAL
				WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
		END 
	END
END

