CREATE OR ALTER PROCEDURE DBO.SPQ_VERIF_IACT_PARTIC @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @DATOS VARCHAR(MAX), @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @IDSEDE VARCHAR(5), @PROCESO VARCHAR(20)
--
DECLARE @CNSVERIF INT, @FECHA DATETIME, @TIPO VARCHAR(20), @REFERENCIA1 VARCHAR(20), @REFERENCIA2 VARCHAR(20), @REFERENCIA3 VARCHAR(20)
DECLARE @REFERENCIA4 VARCHAR(20), @CUMPLE BIT, @OBS VARCHAR(1024)
DECLARE @REFERENCIA5 VARCHAR(20), @REFERENCIA6 VARCHAR(20), @REFERENCIA7 VARCHAR(20), @REFERENCIA8 VARCHAR(20), @REFERENCIA9 VARCHAR(20)
DECLARE @REFERENCIA10 VARCHAR(20), @REFERENCIA11 VARCHAR(20), @REFERENCIA12 VARCHAR(20), @FECHA1 DATETIME
DECLARE @CANTIDAD SMALLINT, @REFERENCIA13 VARCHAR(1024), @SYS_COMPUTERNAME VARCHAR(250), @IDACTIVO VARCHAR(20), @IDTERCERO VARCHAR(20)

--
BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	IF @METODO = 'GUARDAR'
	BEGIN
		SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME
		FROM USUSU
		WHERE USUARIO = @USUARIO

		SELECT @IDSEDE = IDSEDE
		FROM UBEQ
		WHERE SYS_ComputerName = @SYS_COMPUTERNAME

		BEGIN TRY
			SELECT @PROCESO = PROCESO, @CNSVERIF = CNSVERIF, @FECHA = FECHA, @TIPO = TIPO, @REFERENCIA1 = REFERENCIA1, @REFERENCIA2 = REFERENCIA2, @REFERENCIA3 = 
				REFERENCIA3, @REFERENCIA4 = REFERENCIA4, @CUMPLE = CUMPLE, @OBS = OBS, @REFERENCIA5 = REFERENCIA5, @REFERENCIA6 = REFERENCIA6, @REFERENCIA7 = 
				REFERENCIA7, @REFERENCIA8 = REFERENCIA8, @REFERENCIA9 = REFERENCIA9, @REFERENCIA10 = REFERENCIA10, @REFERENCIA11 = REFERENCIA11, @REFERENCIA12 = 
				REFERENCIA12, @FECHA1 = FECHA1, @CANTIDAD = CANTIDAD, @REFERENCIA13 = REFERENCIA13
			FROM OPENJSON(@PARAMETROS) WITH (
					PROCESO VARCHAR(20) '$.PROCESO', CNSVERIF INT '$.CNSVERIF', FECHA DATETIME '$.FECHA', TIPO VARCHAR(20) '$.TIPO', REFERENCIA1 VARCHAR(20) 
					'$.REFERENCIA1', REFERENCIA2 VARCHAR(20) '$.REFERENCIA2', REFERENCIA3 VARCHAR(20) '$.REFERENCIA3', REFERENCIA4 VARCHAR(20) '$.REFERENCIA4', 
					CUMPLE BIT '$.CUMPLE', OBS VARCHAR(1024) '$.OBS', REFERENCIA5 VARCHAR(20) '$.REFERENCIA5', REFERENCIA6 VARCHAR(20) '$.REFERENCIA6', 
					REFERENCIA7 VARCHAR(20) '$.REFERENCIA7', REFERENCIA8 VARCHAR(20) '$.REFERENCIA8', REFERENCIA9 VARCHAR(20) '$.REFERENCIA9', REFERENCIA10 
					VARCHAR(20) '$.REFERENCIA10', REFERENCIA11 VARCHAR(20) '$.REFERENCIA11', REFERENCIA12 VARCHAR(20) '$.REFERENCIA12', FECHA1 DATETIME 
					'$.FECHA1', CANTIDAD SMALLINT '$.CANTIDAD', REFERENCIA13 VARCHAR(1024) '$.REFERENCIA13'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL EMPLEADO ', @REFERENCIA2, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM VERIF
							WHERE REFERENCIA1 = @REFERENCIA1 AND REFERENCIA2 = @REFERENCIA2
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						INSERT INTO [VERIF] (
							[FECHA], [TIPO], [REFERENCIA1], [REFERENCIA2], [REFERENCIA3], [REFERENCIA4], [CUMPLE], [OBS], [USUARIO], [EQUIPO], [REFERENCIA5], 
							[REFERENCIA6], [REFERENCIA7], [REFERENCIA8], [REFERENCIA9], [REFERENCIA10], [REFERENCIA11], [REFERENCIA12], [FECHA1], [CANTIDAD], 
							[REFERENCIA13]
							)
						SELECT @FECHA, @TIPO, @REFERENCIA1, @REFERENCIA2, @REFERENCIA3, @REFERENCIA4, @CUMPLE, @OBS, @USUARIO, @SYS_COMPUTERNAME, @REFERENCIA5, 
							@REFERENCIA6, @REFERENCIA7, @REFERENCIA8, @REFERENCIA9, @REFERENCIA10, @REFERENCIA11, @REFERENCIA12, @FECHA1, @CANTIDAD, 
							@REFERENCIA13
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL EMPLEADO ', @REFERENCIA2, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM VERIF
							WHERE REFERENCIA1 = @REFERENCIA1 AND REFERENCIA2 = @REFERENCIA2 AND CNSVERIF <> @CNSVERIF
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						UPDATE VERIF
						SET FECHA = @FECHA, REFERENCIA1 = @REFERENCIA1, REFERENCIA2 = @REFERENCIA2, REFERENCIA3 = @REFERENCIA3, USUARIO = @USUARIO, EQUIPO = 
							@SYS_COMPUTERNAME
						WHERE CNSVERIF = @CNSVERIF
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'ELIMINAR'
	BEGIN
		SELECT @CNSVERIF = CNSVERIF
		FROM OPENJSON(@PARAMETROS) WITH (CNSVERIF INT '$.CNSVERIF')

		BEGIN TRY
			DELETE
			FROM VERIF
			WHERE CNSVERIF = @CNSVERIF
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'INFO_VERIF'
	BEGIN
		SELECT @IDACTIVO = IDACTIVO, @IDTERCERO = IDTERCERO
		FROM OPENJSON(@PARAMETROS) WITH (IDACTIVO VARCHAR(20) '$.IDACTIVO', IDTERCERO VARCHAR(20) '$.IDTERCERO')

		SELECT 'OK' OK

		SELECT IACT.*, TER.RAZONSOCIAL AS FABRICANTE, T.RAZONSOCIAL, IACTR.FECHAASIG, IACTR.USO_BASI, IACTR.ALMACENA, IACTR.REVI_ACCESO, IACTR.MANUALES, IACTR.
			OBSERVACION
		FROM IACT
		INNER JOIN TER ON TER.IDTERCERO = IACT.IDTERCERO
		INNER JOIN IACTR ON IACTR.IDACTIVO = IACT.IDACTIVO
		INNER JOIN TER AS T ON T.IDTERCERO = IACTR.IDTERCERO
		WHERE IACT.IDACTIVO = @IDACTIVO AND IACTR.IDTERCERO = @IDTERCERO

		SELECT *
		FROM IACTEQU
		WHERE IDACTIVO = @IDACTIVO

		SELECT TER.RAZONSOCIAL, TER.NIT, VERIF.REFERENCIA3 AS CARGO
		FROM VERIF
		INNER JOIN TER ON TER.IDTERCERO = VERIF.REFERENCIA2
		WHERE REFERENCIA1 = @IDACTIVO AND REFERENCIA4 = @IDTERCERO

		RETURN
	END
END


