CREATE OR ALTER PROCEDURE DBO.SPQ_FNT_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY           INT 
       ,@PROCESO            VARCHAR(20)    ,@FNT    NVARCHAR(MAX)
              ,@IDNOTA     VARCHAR(20)
       ,@DESCRIPCION     VARCHAR(80)
       ,@TIPO     VARCHAR(2)
       ,@COMPROBANTE     VARCHAR(2)
       ,@CUENTA     VARCHAR(16)
       ,@DECRUCES     SMALLINT
       ,@AFCOSTO     SMALLINT
       ,@HOMOLOGODIAN     VARCHAR(5)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_FNT_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'CRUDFNT'
   BEGIN
      PRINT 'CRUDFNT'
      SELECT @FNT  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@FNT ,'$.PROCESO')
      --Leo Campos enviados y los coloco en las variables respectivas
      SELECT @IDNOTA = JSON_VALUE(@FNT , '$.IDNOTA' )
      SELECT @DESCRIPCION = JSON_VALUE(@FNT , '$.DESCRIPCION' )
      SELECT @TIPO = JSON_VALUE(@FNT , '$.TIPO' )
      SELECT @COMPROBANTE = JSON_VALUE(@FNT , '$.COMPROBANTE' )
      SELECT @CUENTA = JSON_VALUE(@FNT , '$.CUENTA' )
      SELECT @DECRUCES = CAST(JSON_VALUE(@FNT , '$.DECRUCES' ) AS BIT)
      SELECT @AFCOSTO = CAST(JSON_VALUE(@FNT , '$.AFCOSTO' ) AS BIT)
      SELECT @HOMOLOGODIAN = JSON_VALUE(@FNT , '$.HOMOLOGODIAN' )

      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'
         BEGIN TRY
			INSERT INTO @TBLERRORES(ERROR) 
			SELECT 'EL TIPO DE NOTA YA EXISTE'
			WHERE EXISTS (SELECT 1 FROM FNT WHERE IDNOTA = @IDNOTA)

			IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
			BEGIN
				INSERT INTO FNT(IDNOTA,DESCRIPCION,TIPO,COMPROBANTE,CUENTA,DECRUCES,AFCOSTO,
								 HOMOLOGODIAN)
				SELECT @IDNOTA,@DESCRIPCION,@TIPO,@COMPROBANTE,@CUENTA,@DECRUCES,@AFCOSTO,
								 @HOMOLOGODIAN
				SELECT @IDENTITY = SCOPE_IDENTITY()
			END
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK ,@IDENTITY CNS 
         RETURN
      END

      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         BEGIN TRY
            UPDATE FNT SET
                    IDNOTA = @IDNOTA,DESCRIPCION = @DESCRIPCION,TIPO = @TIPO,COMPROBANTE = @COMPROBANTE,CUENTA = @CUENTA,DECRUCES = @DECRUCES,AFCOSTO = @AFCOSTO,
                             HOMOLOGODIAN = @HOMOLOGODIAN
            WHERE IDNOTA = @IDNOTA
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END

	  IF UPPER(@PROCESO) = 'ELIMINAR'
		BEGIN
			PRINT 'ELIMINAR'
			BEGIN TRY
				IF COALESCE(@IDNOTA,'')=''
				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'EL CODIGO DEL TIPO DE NOTA ES OBLIGATORIO'

				IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
				BEGIN
					DELETE FROM FNT WHERE IDNOTA = @IDNOTA
				END		
			END TRY

			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH

			IF(SELECT COUNT(*) FROM @TBLERRORES) >0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			SELECT 'OK' OK
			RETURN
		END
      RETURN
   END
END


