CREATE OR ALTER PROCEDURE DBO.SPQ_GEN_DEPRECIACION @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @IDSEDE VARCHAR(5)
DECLARE @PROCESO VARCHAR(20)
DECLARE @MAXITEM INT, @MESES INT, @MESESADEPRECIAR INT, @MESESDEPRECIADOS INT
DECLARE @FECHA DATETIME, @VALORADEPRECIAR DECIMAL(15, 6), @PRECIOCOMPRA DECIMAL(14, 2), @VALORSALVAMENTO DECIMAL(14, 2), @PRECIOCOMERCIAL DECIMAL(14, 2)
DECLARE @DEPACUMHISTORICA DECIMAL(14, 2), @DEPACUMDIFERIDA DECIMAL(14, 2), @CUENTA VARCHAR(16), @AJUSTEACUMULADO DECIMAL(12, 2)
DECLARE @MESDERE INT, @VLRDEPRE DECIMAL(14, 2), @IDACTIVO VARCHAR(20), @SI BIT

BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	IF @METODO = 'GENERAR_DEPRECIACION'
	BEGIN
		SELECT @IDACTIVO = IDACTIVO
		FROM OPENJSON(@PARAMETROS) WITH (IDACTIVO VARCHAR(20) '$.IDACTIVO')

		BEGIN TRY
			EXEC SPK_GEN_DEPRECIACION @IDACTIVO
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'OBTENER_IACT'
	BEGIN
		SELECT @IDACTIVO = IDACTIVO
		FROM OPENJSON(@PARAMETROS) WITH (IDACTIVO VARCHAR(20) '$.IDACTIVO')

		SELECT OK = 'OK', DEPRECIABLE, MESESDEPRECIADOS, VALORSALVAMENTO, MESESADEPRECIAR, FECHAULTDEPRECIACION, DEPACUMDIFERIDA, DEPACUMHISTORICA
		FROM IACT
		WHERE IACT.IDACTIVO = @IDACTIVO

		RETURN
	END
END

