CREATE OR ALTER PROCEDURE DBO.SPQ_GRUPAC @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @IDSEDE VARCHAR(5), @DATOS VARCHAR(MAX)
DECLARE @PROCESO VARCHAR(20), @CODIGO VARCHAR(20), @DESCRIPCION VARCHAR(1000), @CODIGOEDITE VARCHAR(20), @CAMPO VARCHAR(20), @IDTGEN INT

BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	IF @METODO = 'GUARDAR'
	BEGIN
		BEGIN TRY
			SELECT @PROCESO = PROCESO, @CODIGO = CODIGO, @DESCRIPCION = DESCRIPCION
			FROM OPENJSON(@PARAMETROS) WITH (PROCESO VARCHAR(20) '$.PROCESO', CODIGO VARCHAR(20) '$.CODIGO', DESCRIPCION VARCHAR(1000) '$.DESCRIPCION'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL CODIGO ', @CODIGO, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM TGEN
							WHERE TABLA = 'ACTIVOSFIJOS' AND CAMPO = 'GRUPOS' AND CODIGO = @CODIGO
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						INSERT INTO TGEN (TABLA, CAMPO, CODIGO, DESCRIPCION)
						SELECT 'ACTIVOSFIJOS', 'GRUPOS', @CODIGO, @DESCRIPCION
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					SELECT @DATOS = DATOS
					FROM OPENJSON(@PARAMETROS) WITH (DATOS NVARCHAR(MAX) AS JSON)

					SELECT @CODIGOEDITE = CODIGOEDITE
					FROM OPENJSON(@DATOS) WITH (CODIGOEDITE VARCHAR(20) '$.CODIGOEDITE')

					IF (@CODIGOEDITE <> @CODIGO)
					BEGIN
						INSERT INTO @TBLERRORES (ERROR)
						SELECT CONCAT ('EL CODIGO ', @CODIGO, ' YA SE ENCUENTRA REGISTRADO')
						WHERE EXISTS (
								SELECT 1
								FROM TGEN
								WHERE TABLA = 'ACTIVOSFIJOS' AND CAMPO = 'GRUPOS' AND CODIGO = @CODIGO
								)

						IF (
								SELECT COUNT(*)
								FROM @TBLERRORES
								) <= 0
						BEGIN
							UPDATE TGEN
							SET CODIGO = @CODIGO, DESCRIPCION = @DESCRIPCION
							WHERE TABLA = 'ACTIVOSFIJOS' AND CAMPO = 'GRUPOS' AND CODIGO = @CODIGOEDITE
						END
					END
					ELSE
					BEGIN
						UPDATE TGEN
						SET DESCRIPCION = @DESCRIPCION
						WHERE TABLA = 'ACTIVOSFIJOS' AND CAMPO = 'GRUPOS' AND CODIGO = @CODIGO
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'GUARDAR_SUBGRUP'
	BEGIN
		BEGIN TRY
			SELECT @PROCESO = PROCESO, @CAMPO = CAMPO, @CODIGO = CODIGO, @DESCRIPCION = DESCRIPCION, @IDTGEN = IDTGEN
			FROM OPENJSON(@PARAMETROS) WITH (
					PROCESO VARCHAR(20) '$.PROCESO', CAMPO VARCHAR(20) '$.CAMPO', CODIGO VARCHAR(20) '$.CODIGO', DESCRIPCION VARCHAR(1000) '$.DESCRIPCION', 
					OPCIONESLIBRES INT '$.OPCIONESLIBRES', IDTGEN INT '$.IDTGEN'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL CODIGO ', @CODIGO, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM TGEN
							WHERE TABLA = 'ACTIVOSFIJOS' AND CAMPO = @CAMPO AND CODIGO = @CODIGO
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						INSERT INTO TGEN (TABLA, CAMPO, CODIGO, DESCRIPCION)
						SELECT 'ACTIVOSFIJOS', @CAMPO, @CODIGO, @DESCRIPCION
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL CODIGO ', @CODIGO, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM TGEN
							WHERE TABLA = 'ACTIVOSFIJOS' AND CAMPO = @CAMPO AND CODIGO = @CODIGO AND IDTGEN <> @IDTGEN
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						UPDATE TGEN
						SET CODIGO = @CODIGO, DESCRIPCION = @DESCRIPCION
						WHERE IDTGEN = @IDTGEN
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'ELIMINAR'
	BEGIN
		SELECT @CODIGO = CODIGO
		FROM OPENJSON(@PARAMETROS) WITH (CODIGO VARCHAR(20) '$.CODIGO')

		BEGIN TRY
			DELETE
			FROM TGEN
			WHERE TABLA = 'ACTIVOSFIJOS' AND CAMPO = 'GRUPOS' AND CODIGO = @CODIGO
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'ELIMINAR_SUBGRUP'
	BEGIN
		SELECT @CODIGO = CODIGO, @CAMPO = CAMPO
		FROM OPENJSON(@PARAMETROS) WITH (CODIGO VARCHAR(20) '$.CODIGO', CAMPO VARCHAR(20) '$.CAMPO')

		BEGIN TRY
			DELETE
			FROM TGEN
			WHERE TABLA = 'ACTIVOSFIJOS' AND CAMPO = @CAMPO AND CODIGO = @CODIGO
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END
END


