CREATE OR ALTER PROCEDURE DBO.SPQ_FDIANCER_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY           INT 
       ,@PROCESO            VARCHAR(20)    ,@FDIANCER    NVARCHAR(MAX)
              ,@ID     INT
       ,@DESCRIPCION     VARCHAR(255)
       ,@CLAVE     VARCHAR(255)
       ,@FECHAEXPEDICION     DATE
       ,@FECHAEXPEDICION_STR VARCHAR(10)
       ,@FECHAVENCE     DATE
       ,@FECHAVENCE_STR VARCHAR(10)
       ,@PROVEEDOR     VARCHAR(255)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_FDIANCER_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'CRUDFDIANCER'
   BEGIN
      PRINT 'CRUDFDIANCER'
      SELECT @FDIANCER  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@FDIANCER ,'$.PROCESO')
      SELECT @ID = JSON_VALUE(@FDIANCER , '$.ID' )
      SELECT @DESCRIPCION = JSON_VALUE(@FDIANCER , '$.DESCRIPCION' )
      SELECT @CLAVE = JSON_VALUE(@FDIANCER , '$.CLAVE' )
      SELECT @FECHAEXPEDICION_STR = JSON_VALUE(@FDIANCER , '$.FECHAEXPEDICION')
      SELECT @FECHAEXPEDICION = CONVERT(DATE, SUBSTRING(@FECHAEXPEDICION_STR,9,2)+'/'+SUBSTRING(@FECHAEXPEDICION_STR,6,2)+'/'+SUBSTRING(@FECHAEXPEDICION_STR,1,4))
      SELECT @FECHAVENCE_STR = JSON_VALUE(@FDIANCER , '$.FECHAVENCE')
      SELECT @FECHAVENCE = CONVERT(DATE, SUBSTRING(@FECHAVENCE_STR,9,2)+'/'+SUBSTRING(@FECHAVENCE_STR,6,2)+'/'+SUBSTRING(@FECHAVENCE_STR,1,4))
      SELECT @PROVEEDOR = JSON_VALUE(@FDIANCER , '$.PROVEEDOR' )
      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'
         BEGIN TRY
            INSERT INTO FDIANCER(DESCRIPCION,CLAVE,FECHAEXPEDICION,FECHAVENCE,PROVEEDOR)
            SELECT @DESCRIPCION,@CLAVE,@FECHAEXPEDICION,@FECHAVENCE,@PROVEEDOR
            SELECT @IDENTITY = SCOPE_IDENTITY()
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK ,@IDENTITY CNS 
         RETURN
      END
      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
				BEGIN TRY
					IF (SELECT COUNT(1)  FROM  FDIANCER WHERE ID = @ID) >0
						UPDATE FDIANCER SET
								  DESCRIPCION = @DESCRIPCION,CLAVE = @CLAVE,FECHAEXPEDICION = @FECHAEXPEDICION,FECHAVENCE = @FECHAVENCE,PROVEEDOR = @PROVEEDOR
						WHERE ID = @ID
					ELSE
						INSERT INTO @TBLERRORES(ERROR) SELECT 'No se encontró la firma digital'
				END TRY
				BEGIN CATCH
					INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
				END CATCH
         
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END
		IF UPPER(@PROCESO) = 'BORRAR'
      BEGIN
         BEGIN TRY
				IF (SELECT COUNT(1)  FROM  FDIANCER WHERE ID = @ID) >0
					DELETE FDIANCER WHERE ID = @ID
				ELSE
					INSERT INTO @TBLERRORES(ERROR) SELECT 'No se encontró la firma digital'
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END
      RETURN
   END
	IF UPPER(@METODO) = 'GETVENCIMIENTO' 
   BEGIN
      BEGIN TRY
			IF (SELECT coalesce( dbo.FNK_VALORVARIABLE('DIANCERTIFICADO'),'')  ) ='SI' 
			BEGIN 
				PRINT  coalesce( dbo.FNK_VALORVARIABLE('DIANCERTIFICADO'),'') + ' ENTRE A REVISAR LOS DIAS '
				IF (SELECT coalesce( dbo.FNK_VALORVARIABLE('DIASNOTIFICACERT'),0)  ) > 0
				BEGIN	
					PRINT coalesce( dbo.FNK_VALORVARIABLE('DIASNOTIFICACERT'),'0') + ' SON LOS DIAS '
					SELECT TOP 1   'OK' OK 
						, FECHAVENCE 
						, [ESTAVENCIDA] = IIF(DATEDIFF( day, GETDATE()  , FECHAVENCE  ) < 0 ,1 ,IIF(DATEDIFF( day, GETDATE()  , FECHAVENCE  ) < coalesce( dbo.FNK_VALORVARIABLE('DIASNOTIFICACERT'),0) ,2 ,0 ) )  
						, [DIASXVENCER] = DATEDIFF( day, GETDATE()  , FECHAVENCE  )   
						, [NOMBREFIRMA] = DESCRIPCION 
					FROM FDIANCER 
					ORDER BY FECHAVENCE DESC
				END	
				ELSE
					INSERT INTO @TBLERRORES(ERROR) SELECT 'La variable DIASNOTIFICACERT no esta configurada'
			END
			ELSE
			BEGIN 
				PRINT 'No tiene Configurada la variable DIANCERTIFICADO o no valida el vencimiento de la firma'
			END
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN
   END
END




