CREATE OR ALTER PROCEDURE DBO.SPQ_TUR_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY           INT 
       ,@PROCESO            VARCHAR(20)    ,@TUR    NVARCHAR(MAX)
              ,@CODTURNO     VARCHAR(4)
       ,@DESCRIPCION     VARCHAR(40)
       ,@FECHAINICIAL     DATETIME
       ,@HORAINICIAL	TIME
       ,@FECHAFINAL     DATETIME
	   ,@FECHAACTUAL	DATE = GETDATE()
       ,@HORAFINAL	 TIME
       ,@LUNES     SMALLINT
       ,@MARTES     SMALLINT
       ,@MIERCOLES     SMALLINT
       ,@JUEVES     SMALLINT
       ,@VIERNES     SMALLINT
       ,@SABADO     SMALLINT
       ,@DOMINGO     SMALLINT
       ,@FESTIVO     SMALLINT
       ,@ESTADO     VARCHAR(8)
       ,@DIASIGUIENTE     SMALLINT
       ,@CLASE     VARCHAR(30)
       ,@HDIA     INT
       ,@HNOCHE     INT
       ,@HDIAFIN     INT
       ,@HNOCHEFIN     INT
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_TUR_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'CRUDTUR'
   BEGIN
      PRINT 'CRUDTUR'
      SELECT @TUR  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@TUR ,'$.PROCESO')
      --Leo Campos enviados y los coloco en las variables respectivas
      SELECT @CODTURNO = JSON_VALUE(@TUR , '$.CODTURNO' )
      SELECT @DESCRIPCION = JSON_VALUE(@TUR , '$.DESCRIPCION' )
      SELECT @HORAINICIAL = JSON_VALUE(@TUR , '$.FECHAINICIAL')
      SELECT @FECHAINICIAL = CAST(@FECHAACTUAL AS DATETIME) + CAST(@HORAINICIAL AS DATETIME)
      SELECT @HORAFINAL = JSON_VALUE(@TUR , '$.FECHAFINAL')
      SELECT @FECHAFINAL = CAST(@FECHAACTUAL AS DATETIME) + CAST(@HORAFINAL AS DATETIME)
      SELECT @LUNES = CAST(JSON_VALUE(@TUR , '$.LUNES' ) AS BIT) 
      SELECT @MARTES = CAST(JSON_VALUE(@TUR , '$.MARTES' ) AS BIT)
      SELECT @MIERCOLES = CAST(JSON_VALUE(@TUR , '$.MIERCOLES' ) AS BIT)
      SELECT @JUEVES = CAST(JSON_VALUE(@TUR , '$.JUEVES' ) AS BIT)
      SELECT @VIERNES = CAST(JSON_VALUE(@TUR , '$.VIERNES' ) AS BIT)
      SELECT @SABADO = CAST(JSON_VALUE(@TUR , '$.SABADO' ) AS BIT)
      SELECT @DOMINGO = CAST(JSON_VALUE(@TUR , '$.DOMINGO' ) AS BIT)
      SELECT @FESTIVO = CAST(JSON_VALUE(@TUR , '$.FESTIVO' ) AS BIT)
      SELECT @ESTADO = JSON_VALUE(@TUR , '$.ESTADO' )
      SELECT @DIASIGUIENTE = CAST(JSON_VALUE(@TUR , '$.DIASIGUIENTE' ) AS BIT)
      SELECT @CLASE = JSON_VALUE(@TUR , '$.CLASE' )
      SELECT @HDIA = COALESCE(JSON_VALUE(@TUR , '$.HDIA' ), 0)
      SELECT @HNOCHE = COALESCE(JSON_VALUE(@TUR , '$.HNOCHE' ), 0)
      SELECT @HDIAFIN = COALESCE(JSON_VALUE(@TUR , '$.HDIAFIN' ), 0)
      SELECT @HNOCHEFIN = COALESCE(JSON_VALUE(@TUR , '$.HNOCHEFIN' ), 0)
      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'
		 
         BEGIN TRY
			INSERT INTO @TBLERRORES(ERROR) 
			SELECT 'EL TURNO YA EXISTE'
			WHERE EXISTS (SELECT 1 FROM TUR WHERE CODTURNO = @CODTURNO)

			IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
			BEGIN
				INSERT INTO TUR(CODTURNO,DESCRIPCION,FECHAINICIAL,FECHAFINAL,LUNES,MARTES,MIERCOLES,
								 JUEVES,VIERNES,SABADO,DOMINGO,FESTIVO,ESTADO,DIASIGUIENTE,
								 CLASE,HDIA,HNOCHE,HDIAFIN,HNOCHEFIN)
				SELECT @CODTURNO,@DESCRIPCION,@FECHAINICIAL,@FECHAFINAL,@LUNES,@MARTES,@MIERCOLES,
								 @JUEVES,@VIERNES,@SABADO,@DOMINGO,@FESTIVO,@ESTADO,@DIASIGUIENTE,
								 @CLASE,@HDIA,@HNOCHE,@HDIAFIN,@HNOCHEFIN
				SELECT @IDENTITY = SCOPE_IDENTITY()
			END
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK ,@IDENTITY CNS 
         RETURN
      END

      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         BEGIN TRY
            UPDATE TUR SET
                    CODTURNO = @CODTURNO,DESCRIPCION = @DESCRIPCION,FECHAINICIAL = @FECHAINICIAL,FECHAFINAL = @FECHAFINAL,LUNES = @LUNES,MARTES = @MARTES,MIERCOLES = @MIERCOLES,
                             JUEVES = @JUEVES,VIERNES = @VIERNES,SABADO = @SABADO,DOMINGO = @DOMINGO,FESTIVO = @FESTIVO,ESTADO = @ESTADO,DIASIGUIENTE = @DIASIGUIENTE,
                             CLASE = @CLASE,HDIA = @HDIA,HNOCHE = @HNOCHE,HDIAFIN = @HDIAFIN,HNOCHEFIN = @HNOCHEFIN
            WHERE CODTURNO = @CODTURNO
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END

	  IF UPPER(@PROCESO) = 'ELIMINAR'
		BEGIN
			PRINT 'ELIMINAR'
			BEGIN TRY
				SELECT @CODTURNO = JSON_VALUE(@TUR, '$.CODTURNO')

				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'EL TURNO TIENE CAJERO ASIGNADO'
				WHERE EXISTS (SELECT 1 FROM CXT WHERE CODTURNO = @CODTURNO)

				IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
				BEGIN
					DELETE FROM TUR WHERE CODTURNO = @CODTURNO
				END		
			END TRY

			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH

			IF(SELECT COUNT(*) FROM @TBLERRORES) >0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			SELECT 'OK' OK
			RETURN
		END
      RETURN
   END
END




