CREATE OR ALTER PROCEDURE DBO.SPQ_CAJ_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY           INT 
       ,@PROCESO            VARCHAR(20)    ,@CAJ    NVARCHAR(MAX)
              ,@CODCAJA     VARCHAR(4)
       ,@DESCRIPCION     VARCHAR(40)
       ,@TIPO     VARCHAR(5)
       ,@CLASE     VARCHAR(9)
       ,@FOFI     INT
       ,@FECHACREACION     DATETIME
       ,@FECHACREACION_STR VARCHAR(10)
       ,@ESTADO     VARCHAR(8)
       ,@ABIERTA     SMALLINT
       ,@CNSACJ     VARCHAR(20)
       ,@INVTIPOMOV     VARCHAR(2)
       ,@IDBODEGA     VARCHAR(20)
       ,@INVTIPODOCU     VARCHAR(2)
       ,@CUENTA     VARCHAR(16)
       ,@RECIBETRASLADO     SMALLINT
       ,@ACEPTARECAUDO     SMALLINT
       ,@MAXPAGOCM     DECIMAL(9,2)
       ,@CUENTACXP_CM     VARCHAR(16)
       ,@COMPROBANTE_CM     VARCHAR(2)
       ,@TIPOEGRESO     VARCHAR(8)
       ,@RESPONSABLE     VARCHAR(20)
       ,@ANTICIPOS     SMALLINT
       ,@COMPROBANTE_ANT     VARCHAR(2)
       ,@CUENTA_ANT     VARCHAR(16)
       ,@REEMBOLSO     TINYINT
       ,@NOCONTAB     BIT
       ,@CLASEFAC     VARCHAR(10)
       ,@IDCONCEPTO   VARCHAR(16)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_CAJ_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'CRUDCAJ'
   BEGIN
      PRINT 'CRUDCAJ'
      SELECT @CAJ  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@CAJ ,'$.PROCESO')
      --Leo Campos enviados y los coloco en las variables respectivas
      SELECT @CODCAJA = JSON_VALUE(@CAJ , '$.CODCAJA' )
      SELECT @DESCRIPCION = JSON_VALUE(@CAJ , '$.DESCRIPCION' )
      SELECT @TIPO = JSON_VALUE(@CAJ , '$.TIPO' )
      SELECT @CLASE = JSON_VALUE(@CAJ , '$.CLASE' )
      SELECT @FOFI = JSON_VALUE(@CAJ , '$.FOFI' )
      SELECT @FECHACREACION_STR = JSON_VALUE(@CAJ , '$.FECHACREACION')
      SELECT @FECHACREACION = CONVERT(DATE, SUBSTRING(@FECHACREACION_STR,9,2)+'/'+SUBSTRING(@FECHACREACION_STR,6,2)+'/'+SUBSTRING(@FECHACREACION_STR,1,4))
      SELECT @ESTADO = JSON_VALUE(@CAJ , '$.ESTADO' )
      SELECT @INVTIPOMOV = JSON_VALUE(@CAJ , '$.INVTIPOMOV' )
      SELECT @IDBODEGA = JSON_VALUE(@CAJ , '$.IDBODEGA' )
      SELECT @INVTIPODOCU = JSON_VALUE(@CAJ , '$.INVTIPODOCU' )
      SELECT @CUENTA = JSON_VALUE(@CAJ , '$.CUENTA' )
      SELECT @RECIBETRASLADO = JSON_VALUE(@CAJ , '$.RECIBETRASLADO' )
      SELECT @ACEPTARECAUDO = JSON_VALUE(@CAJ , '$.ACEPTARECAUDO' )
      SELECT @MAXPAGOCM = JSON_VALUE(@CAJ , '$.MAXPAGOCM' )
      SELECT @CUENTACXP_CM = JSON_VALUE(@CAJ , '$.CUENTACXP_CM' )
      SELECT @COMPROBANTE_CM = JSON_VALUE(@CAJ , '$.COMPROBANTE_CM' )
      SELECT @TIPOEGRESO = JSON_VALUE(@CAJ , '$.TIPOEGRESO' )
      SELECT @RESPONSABLE = JSON_VALUE(@CAJ , '$.RESPONSABLE' )
      SELECT @ANTICIPOS = JSON_VALUE(@CAJ , '$.ANTICIPOS' )
      SELECT @COMPROBANTE_ANT = JSON_VALUE(@CAJ , '$.COMPROBANTE_ANT' )
      SELECT @CUENTA_ANT = JSON_VALUE(@CAJ , '$.CUENTA_ANT' )
      SELECT @REEMBOLSO = JSON_VALUE(@CAJ , '$.REEMBOLSO' )
      SELECT @NOCONTAB = CAST(JSON_VALUE(@CAJ , '$.NOCONTAB' ) AS BIT) 
      SELECT @CLASEFAC = JSON_VALUE(@CAJ , '$.CLASEFAC' )
      SELECT @IDCONCEPTO = JSON_VALUE(@CAJ , '$.IDCONCEPTO' )

      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'
         BEGIN TRY
            INSERT INTO CAJ(CODCAJA,DESCRIPCION,TIPO,CLASE,FOFI,FECHACREACION,ESTADO,
                              INVTIPOMOV,IDBODEGA,INVTIPODOCU,CUENTA,RECIBETRASLADO,
                             ACEPTARECAUDO,MAXPAGOCM,CUENTACXP_CM,COMPROBANTE_CM,TIPOEGRESO,RESPONSABLE,ANTICIPOS,
                             COMPROBANTE_ANT,CUENTA_ANT,REEMBOLSO,NOCONTAB,CLASEFAC, IDCONCEPTO)
            SELECT @CODCAJA,@DESCRIPCION,@TIPO,@CLASE,@FOFI,GETDATE(),@ESTADO,
                             @INVTIPOMOV,@IDBODEGA,@INVTIPODOCU,@CUENTA,@RECIBETRASLADO,
                             @ACEPTARECAUDO,@MAXPAGOCM,@CUENTACXP_CM,@COMPROBANTE_CM,@TIPOEGRESO,@RESPONSABLE,@ANTICIPOS,
                             @COMPROBANTE_ANT,@CUENTA_ANT,@REEMBOLSO,@NOCONTAB,@CLASEFAC, @IDCONCEPTO
            --SELECT @IDENTITY = SCOPE_IDENTITY()
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK --,@IDENTITY CNS 
         RETURN
      END

      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         BEGIN TRY
            UPDATE CAJ SET
                    CODCAJA = @CODCAJA,DESCRIPCION = @DESCRIPCION,TIPO = @TIPO,CLASE = @CLASE,FOFI = @FOFI,ESTADO = @ESTADO,
                             INVTIPOMOV = @INVTIPOMOV,IDBODEGA = @IDBODEGA,INVTIPODOCU = @INVTIPODOCU,CUENTA = @CUENTA,RECIBETRASLADO = @RECIBETRASLADO,
                             ACEPTARECAUDO = @ACEPTARECAUDO,MAXPAGOCM = @MAXPAGOCM,CUENTACXP_CM = @CUENTACXP_CM,COMPROBANTE_CM = @COMPROBANTE_CM,TIPOEGRESO = @TIPOEGRESO,RESPONSABLE = @RESPONSABLE,ANTICIPOS = @ANTICIPOS,
                             COMPROBANTE_ANT = @COMPROBANTE_ANT,CUENTA_ANT = @CUENTA_ANT,REEMBOLSO = @REEMBOLSO,NOCONTAB = @NOCONTAB,CLASEFAC = @CLASEFAC, IDCONCEPTO = @IDCONCEPTO
            WHERE CODCAJA = @CODCAJA
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END
      RETURN
   END
END

