CREATE OR ALTER PROCEDURE DBO.SPQ_CAJA_RPT
@JSON  NVARCHAR(MAX) 
WITH
ENCRYPTION
AS
DECLARE  @PARAMETROS      NVARCHAR(MAX) ,@MODELO           VARCHAR(100) ,@METODO            VARCHAR(100)  ,@USUARIO         VARCHAR(12),
			@GRUPO           VARCHAR(8)    ,@SYS_COMPUTERNAME VARCHAR(254) ,@IDSEDE            VARCHAR(5)    ,@USUNOMBRE       VARCHAR(100),
			@FECHA           VARCHAR(10)   ,@IDEMEDICA        VARCHAR(4)	,@FECHA1            DATETIME		 ,@SQL             VARCHAR(MAX),
			@IDMEDICO        VARCHAR(20)	 ,@HORA             VARCHAR(10)	,@IDDX              VARCHAR(10)	 ,@CONSECUTIVO     VARCHAR(20),
			@IDAFILIADO      VARCHAR(20)   ,@IDPLAN           VARCHAR(10)  ,@IDTERCERO         VARCHAR(20)   ,@IDSERVICIO      VARCHAR(20),
			@NOMBREACOMPA    VARCHAR(120)  ,@TELEFONOACOMPA   VARCHAR(20)  ,@PARENTESCOACOMPA  VARCHAR(20)   ,@MODELOCITA      VARCHAR(50),
			@CLASEORDEN      VARCHAR(20)   ,@IDPESPECIAL      VARCHAR(20)  ,@IDTERCEROCA       VARCHAR(20)   ,@NOAUTORIZACION  VARCHAR(20),
		   @FECHA2          DATE          ,@CONSECUTIVOANT   VARCHAR(20)  ,@CONSECUTIVONUE    VARCHAR(20)   ,@TIPOCITA        VARCHAR(20),
		   @NOMBRE          VARCHAR(100)  ,@ATENCION         VARCHAR(50)  ,@CCOSTO            VARCHAR(570)  ,@PARTICULAR      BIT,
		   @FECHAINCIO      DATETIME      ,@FECHAFINAL       DATETIME     ,@COMPANIA          VARCHAR(2)	,@ITEM		INT ,
         @IDAUT           VARCHAR(20)   ,@NO_ITEM          SMALLINT     ,@PYP               SMALLINT      ,@ALTOCOSTO       SMALLINT,
		   @VALORAUTD       DECIMAL(12,4) ,@FECHAAUT         DATETIME     ,@COPAGOPROPIO      SMALLINT      ,@SOAT            SMALLINT,
		   @PROCEDENCIA     VARCHAR(20)   ,@IDPROVEEDOR      VARCHAR(20)  ,@IDAREA            VARCHAR(20)   ,@PARTICULAR_TIME DECIMAL(14,2),
         @FECHAINI        DATE          ,@FECHAFIN         DATE         ,@IDESPECIALIDAD    VARCHAR(20),   
         @I               INT           ,@I_TO             INT		      ,@OBSERVCION        VARCHAR(200)	 ,@CAUSA           VARCHAR(20),
         @OBSERVACION     VARCHAR(200)  ,@HOY              SMALLDATETIME=GETDATE()                        ,@VLR_UNIT        INT, 
         @CANTIDAD        INT           ,@UNS              VARCHAR(20)  ,@CONDICIONAL       VARCHAR(10),
         @CODCAJA         VARCHAR(10)   ,@DATO             VARCHAR(100) ,@CODCAJERO         VARCHAR(20)   ,@CODTURNO        VARCHAR(4)       ,@CNSFACJ   VARCHAR(20)
        ,@CNSACJ          VARCHAR(20)   ,@NOADMISION       VARCHAR(20)  ,@CONCEPTO          VARCHAR(30)   ,@TOTAL           DECIMAL(12,4)   
        ,@TOTALFCJ        DECIMAL(12,4) ,@FALTANTE         DECIMAL(14,2),@CERRADA           SMALLINT      ,@CNSPCJ          VARCHAR(20)   
        ,@AUX             NVARCHAR(MAX) ,@PROCESO          VARCHAR(20)  ,@VALOR             DECIMAL(12,4) ,@SELECCIONADOS   VARCHAR(1000)
        ,@CNSFACJDEP      VARCHAR(50)   ,@CODCAJADEP       NVARCHAR(MAX),@CTA_BCO           VARCHAR(40)   ,@NUMEROAUTORIZA  VARCHAR(20)
        ,@NUMERODOCUMENTO VARCHAR(20)   ,@SUCURSAL         VARCHAR(20)  ,@TERCERO           NVARCHAR(MAX) ,@TIPOPAGO        NVARCHAR(MAX)
        ,@TIPO_TERCERO    NVARCHAR(MAX) ,@BANCODATO        NVARCHAR(MAX),@CNSDOC            VARCHAR(20)   ,@NUM_CUENTA      NVARCHAR(MAX)		,@NUMERO_CUENTA VARCHAR(20)
        ,@N_FACTURA       VARCHAR(16)   ,@ESTADO           VARCHAR(1)   ,@FECHAFCJ          DATE          ,@NROCOMPROBANTE  VARCHAR(20)
	     ,@FORMAPAGO       VARCHAR(20)	 ,@DESCRIPCION      VARCHAR(200)	,@DATOS             NVARCHAR(MAX) ,@DATOD           NVARCHAR(MAX)	   ,@TIPO VARCHAR(20)
	     ,@RECAUDO         BIT		       ,@NOMBREAFI        VARCHAR(200)	,@DESC_NUMDOCUMENTO VARCHAR(20)	 ,@PAG_IDPAGARE VARCHAR(20),@IDCJFPAEFECTIVO VARCHAR(10)
        ,@CLASE_FAC       VARCHAR(5), @CNSRPDX VARCHAR(20)
        ,@TRASLADO_CNSFACJ VARCHAR(20) ,@CERRADO_PRI SMALLINT ,@ESTADO_MCP VARCHAR(1) ,@CNSRESOL_FCJ VARCHAR(50) ,@N_FACTURA_FCJ VARCHAR(16),
       @ANOMES_MCP       VARCHAR(30) ,@CONTABILIZADA_FCJ SMALLINT ,@CLASE_CAJ VARCHAR(9)
	   ,@CUENTAINI       VARCHAR(16)
	   ,@CUENTAFIN       VARCHAR(16),@NOINCLUIRCAJA VARCHAR(100)
	   ,@USUARIO_TFCJ    VARCHAR(12)
	   DECLARE @CAJAS TABLE (CODCAJA VARCHAR(20))
DECLARE @TABLERRR		TABLE (ERROR VARCHAR(200))

BEGIN 
	SET LANGUAGE Spanish;  
	SET DATEFORMAT dmy
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
	-- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIOpl,   --PRINT 'USUARIO:'+@USUARIO
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO), @USUNOMBRE = NOMBRE FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME, @COMPANIA = COMPANIA, @CODCAJERO= CODCAJERO FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @IDSEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
	PRINT '@USUARIO='+@USUARIO
	
	IF @METODO = 'RPT_RECIBOS_PAGADOS_TURNO'
	BEGIN
      SELECT  @CODCAJA = CODCAJA, @CNSACJ = CNSACJ
      FROM OPENJSON(@PARAMETROS)WITH( CODCAJA VARCHAR(20) '$.CODCAJA', CNSACJ VARCHAR(20) '$.CNSACJ' )
		
		SELECT 'OK' OK,ACJ.CNSACJ, ACJ.CODCAJA, CAJ.DESCRIPCION, 
			ACJ.FECHAAPERTURA,ACJ.FECHACIERRE, 
			ACJ.CODTURNO, TUR.DESCRIPCION [DESC_TURNO], ACJ.CODCAJERO, CJR.DESCRIPCION [NOM_CAJERO], 
			IIF(ACJ.ABIERTA=0,'NO','SI') ABIERTA
			,SED.DESCRIPCION [SED_NOMBRE], SED.DIRECCION [SED_DIRECCION]
			, SED.TELEFONOS [SED_TELEFONOS],   SED.NIT [SED_NIT], SED.DV [SED_DV], TERSED.NIT [NIT_ASEG], TERSED.RAZONSOCIAL [ASEG_NOMBRE],CIUSED.NOMBRE [SED_CIUDAD]
		FROM ACJ 
			INNER JOIN CAJ ON ACJ.CODCAJA = CAJ.CODCAJA
			INNER JOIN TUR ON TUR.CODTURNO = ACJ.CODTURNO
			INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
			LEFT JOIN SED ON SED.IDSEDE = @IDSEDE
			LEFT JOIN TER TERSED ON SED.NIT = TERSED.NIT AND COALESCE(TERSED.RAZONSOCIAL,'') <> ''
			LEFT JOIN CIU CIUSED ON SED.CIUDAD = CIUSED.CIUDAD
		WHERE  ACJ.CNSACJ = @CNSACJ
		ORDER BY FECHAAPERTURA ASC

		SELECT CLASE_FAC, FECHA, CNSFACJ, N_RECIBO, ESTADO,'ANULADO' NOMBRECLIENTE,'ANULADO' CONCEPTO, 0 VLR_INGRESO,0 VLR_EGRESO 
		FROM FCJ WHERE CNSACJ = @CNSACJ AND FCJ.ESTADO = 'A' 
		--ORDER BY  N_RECIBO  ASC
		UNION ALL
		SELECT FCJ.CLASE_FAC, FCJ.FECHA, FCJ.CNSFACJ, FCJ.N_RECIBO, FCJ.ESTADO,FCJ.IDAFILIADO+' - '+ FCJ.NOMBRECLIENTE [NOMBRECLIENTE],  FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION [CONCEPTO], FCJ.VALORTOTAL [VLR_INGRESO] , 0 [VLR_EGRESO] FROM FCJ 
			INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
			INNER JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
			INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO 
			LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
		WHERE FCJ.CNSACJ = @CNSACJ AND FCJ.ESTADO <> 'A' AND FCJ.CLASE_FAC = 'COBRO' AND FCJ.CERRADA = 1 
		GROUP BY  FCJ.CLASE_FAC, FCJ.CNSFACJ, FCJ.FECHA, FCJ.NOMBRECLIENTE, FCJD.CONCEPTO,CPCJ.DESCRIPCION,FCJ.N_RECIBO, FCJ.ESTADO, FCJ.VALORTOTAL,FCJ.IDAFILIADO, FCJ.NOMBRECLIENTE 
		--ORDER BY  FCJ.N_RECIBO  ASC
		UNION ALL
		SELECT FCJ.CLASE_FAC, FCJ.FECHA, FCJ.CNSFACJ, FCJ.N_RECIBO, FCJ.ESTADO,FCJ.IDTERCERO+' - '+ FCJ.NOMBRECLIENTE [NOMBRECLIENTE],  FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION [CONCEPTO], 0 [VLR_INGRESO] , FCJ.VALORTOTAL [VLR_EGRESO] FROM FCJ 
			INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
			INNER JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
			INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO 
			LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
		WHERE FCJ.CNSACJ = @CNSACJ AND FCJ.ESTADO <> 'A' AND FCJ.CLASE_FAC = 'PAGO' AND FCJ.CERRADA = 1 
		GROUP BY  FCJ.CLASE_FAC, FCJ.CNSFACJ, FCJ.FECHA, FCJ.NOMBRECLIENTE, FCJD.CONCEPTO,CPCJ.DESCRIPCION,FCJ.N_RECIBO, FCJ.ESTADO, FCJ.VALORTOTAL,FCJ.IDTERCERO, FCJ.NOMBRECLIENTE 

		SELECT SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  FCJ.VALORTOTAL ELSE 0 END) INGRESOS, 
			SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  FCJ.VALORTOTAL ELSE 0 END)  EGRESOS,
			SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  FCJ.VALORTOTAL ELSE 0 END) - SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  FCJ.VALORTOTAL ELSE 0 END) TOTAL
		FROM FCJ
		WHERE FCJ.CNSACJ=@CNSACJ
		AND FCJ.CERRADA=1 
		AND FCJ.ESTADO<>'A'

		SELECT 'OK' OK
	END
	IF @METODO = 'RPT_FORMA_PAGO_TURNO'
	BEGIN
      SELECT  @CODCAJA = CODCAJA, @CNSACJ = CNSACJ
      FROM OPENJSON(@PARAMETROS)WITH( CODCAJA VARCHAR(20) '$.CODCAJA', CNSACJ VARCHAR(20) '$.CNSACJ' )
		
		SELECT 'OK' OK,ACJ.CNSACJ, ACJ.CODCAJA, CAJ.DESCRIPCION, 
			ACJ.FECHAAPERTURA,ACJ.FECHACIERRE, 
			ACJ.CODTURNO, TUR.DESCRIPCION [DESC_TURNO], ACJ.CODCAJERO, CJR.DESCRIPCION [NOM_CAJERO], 
			IIF(ACJ.ABIERTA=0,'NO','SI') ABIERTA
			,SED.DESCRIPCION [SED_NOMBRE], SED.DIRECCION [SED_DIRECCION]
			, SED.TELEFONOS [SED_TELEFONOS],   SED.NIT [SED_NIT], SED.DV [SED_DV], TERSED.NIT [NIT_ASEG], TERSED.RAZONSOCIAL [ASEG_NOMBRE],CIUSED.NOMBRE [SED_CIUDAD]
		FROM ACJ 
			INNER JOIN CAJ ON ACJ.CODCAJA = CAJ.CODCAJA
			INNER JOIN TUR ON TUR.CODTURNO = ACJ.CODTURNO
			INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
			LEFT JOIN SED ON SED.IDSEDE = @IDSEDE
			LEFT JOIN TER TERSED ON SED.NIT = TERSED.NIT AND COALESCE(TERSED.RAZONSOCIAL,'') <> ''
			LEFT JOIN CIU CIUSED ON SED.CIUDAD = CIUSED.CIUDAD
		WHERE  ACJ.CNSACJ = @CNSACJ
		ORDER BY FECHAAPERTURA ASC

		SELECT FCJ.CLASE_FAC, FCJ.CNSFACJ, FCJ.N_RECIBO, FCJ.IDAFILIADO TIPOEGRESO, FCJ.IDAFILIADO+' - '+ FCJ.NOMBRECLIENTE [NOMBRECLIENTE], FPA.DESCRIPCION, FPA.FORMAPAGO,PCJ.VALOR VLR_INGRESO, 0 VLR_EGRESO 
		,FCJ.TIPO 
		FROM FCJ 
			INNER JOIN PCJ ON FCJ.CNSFACJ = PCJ.CNSFACJ AND FCJ.CODCAJA = PCJ.CODCAJA
			INNER JOIN FPA ON PCJ.TIPOPAGO = FPA.FORMAPAGO
		WHERE FCJ.CNSACJ = @CNSACJ  AND FCJ.CLASE_FAC = 'COBRO' AND( COALESCE(FCJ.N_RECIBO,'')<>'' OR FCJ.TIPO <> 'INTERNO') --AND FCJ.TIPO = 'EXTERNO'
		UNION ALL
		SELECT FCJ.CLASE_FAC, FCJ.CNSFACJ, FCJ.N_RECIBO, FCJ.TIPOEGRESO, FCJ.IDTERCERO+' - '+ TER.RAZONSOCIAL [NOMBRECLIENTE], FPA.DESCRIPCION, FPA.FORMAPAGO,0 VLR_INGRESO, PCJ.VALOR VLR_EGRESO
		,FCJ.TIPO 
		FROM FCJ 
			INNER JOIN PCJ ON FCJ.CNSFACJ = PCJ.CNSFACJ AND FCJ.CODCAJA = PCJ.CODCAJA
			INNER JOIN FPA ON PCJ.TIPOPAGO = FPA.FORMAPAGO
			INNER JOIN TER ON FCJ.IDTERCERO = TER.IDTERCERO
		WHERE FCJ.CNSACJ = @CNSACJ AND FCJ.ESTADO <> 'A' AND FCJ.CLASE_FAC = 'PAGO' AND FCJ.CERRADA = 1 
		ORDER BY CLASE_FAC ASC, CNSFACJ ASC

		SELECT SUM (CASE WHEN FCJ.CLASE_FAC = 'COBRO' THEN PCJ.VALOR ELSE 0 END )VLR_INGRESO
			, SUM (CASE WHEN FCJ.CLASE_FAC = 'PAGO' THEN PCJ.VALOR ELSE 0 END )VLR_EGRESO
			, SUM (CASE WHEN FCJ.CLASE_FAC = 'COBRO' THEN PCJ.VALOR ELSE 0 END ) - SUM (CASE WHEN FCJ.CLASE_FAC = 'PAGO' THEN PCJ.VALOR ELSE 0 END ) TOTAL
		FROM FCJ 
			INNER JOIN PCJ ON FCJ.CNSFACJ = PCJ.CNSFACJ AND FCJ.CODCAJA = PCJ.CODCAJA
		WHERE FCJ.CNSACJ = @CNSACJ AND FCJ.ESTADO <> 'A' AND FCJ.CERRADA = 1 
		SELECT 'OK' OK
	END
	IF @METODO = 'IMPRIME_ARQUEO_EGRESO'
	BEGIN
		SELECT  @CODCAJA = CODCAJA, @CNSFACJ = CNSFACJ, @CNSACJ = CNSACJ
		FROM OPENJSON(@PARAMETROS)WITH(
			CODCAJA        VARCHAR(20)    '$.CODCAJA' ,
			CNSFACJ        VARCHAR(20)    '$.CNSFACJ' ,
			CNSACJ         VARCHAR(20)    '$.CNSACJ' )

		IF NOT EXISTS (SELECT ACJ.CNSACJ, ACJ.CODCAJA, CAJ.DESCRIPCION, 
				convert(varchar,ACJ.FECHAAPERTURA,103)+' '+convert(varchar,ACJ.FECHAAPERTURA,8) FECHAAPERTURA,
				ACJ.CODTURNO, TUR.DESCRIPCION, ACJ.CODCAJERO, CJR.DESCRIPCION, 
				convert(varchar,ACJ.FECHACIERRE,103)+' '+convert(varchar,ACJ.FECHACIERRE,8) FECHACIERRE, 
				IIF(ACJ.ABIERTA=0,'NO','SI') ABIERTA
			FROM ACJ 
				INNER JOIN CAJ ON ACJ.CODCAJA = CAJ.CODCAJA
				INNER JOIN TUR ON TUR.CODTURNO = ACJ.CODTURNO
				INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
			WHERE ACJ.CODCAJA = @CODCAJA AND ACJ.CNSACJ = @CNSACJ)
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'No cuenta con Arqueo de Caja.'
		END
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE

		BEGIN
			BEGIN TRY
				SELECT 'OK' OK,ACJ.CNSACJ, ACJ.CODCAJA, CAJ.DESCRIPCION, 
					convert(varchar,ACJ.FECHAAPERTURA,103)+' '+convert(varchar,ACJ.FECHAAPERTURA,8) FECHAAPERTURA,
					ACJ.CODTURNO, TUR.DESCRIPCION [DESC_TURNO], ACJ.CODCAJERO, CJR.DESCRIPCION [NOM_CAJERO], 
					convert(varchar,ACJ.FECHACIERRE,103)+' '+convert(varchar,ACJ.FECHACIERRE,8) FECHACIERRE, 
					IIF(ACJ.ABIERTA=0,'NO','SI') ABIERTA
					,SED.DESCRIPCION [SED_NOMBRE], SED.DIRECCION [SED_DIRECCION]
					, SED.TELEFONOS [SED_TELEFONOS],   SED.NIT [SED_NIT], SED.DV [SED_DV], TERSED.NIT [NIT_ASEG], TERSED.RAZONSOCIAL [ASEG_NOMBRE],CIUSED.NOMBRE [SED_CIUDAD]
				FROM ACJ 
					INNER JOIN CAJ ON ACJ.CODCAJA = CAJ.CODCAJA
					INNER JOIN TUR ON TUR.CODTURNO = ACJ.CODTURNO
					INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
					LEFT JOIN SED ON SED.IDSEDE = @IDSEDE
					LEFT JOIN TER TERSED ON SED.NIT = TERSED.NIT AND COALESCE(TERSED.RAZONSOCIAL,'') <> ''
					LEFT JOIN CIU CIUSED ON SED.CIUDAD = CIUSED.CIUDAD
				WHERE ACJ.CODCAJA = @CODCAJA AND ACJ.CNSACJ = @CNSACJ
				ORDER BY FECHAAPERTURA ASC


				/*DETALLE*/
				SELECT 'OK' OK, FCJ.CNSFACJ, FCJ.FECHA, FCJ.NOMBRECLIENTE, FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION [CONCEPTO], 
					SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  FCJD.VALORTOTAL ELSE 0 END) INGRESOS, 
					SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  FCJD.VALORTOTAL ELSE 0 END)  EGRESOS
				FROM FCJ INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
						LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
				WHERE FCJ.CNSACJ=@CNSACJ
				AND FCJ.CERRADA=1 
				AND COALESCE(FCJ.DEAPERTURA,0) <>1 
				AND FCJ.ESTADO<>'A' AND FCJ.CLASE_FAC = 'COBRO'
				GROUP BY  FCJ.CNSFACJ, FCJ.FECHA, FCJ.NOMBRECLIENTE, FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION         
				UNION ALL
				SELECT  'OK' OK, FCJ.CNSACJ, FCJ.FECHA, ACJ.CODCAJERO+'-'+ CJR.DESCRIPCION [NOMBRECLIENTE] , FCJD.CONCEPTO+'-'+CPCJ.DESCRIPCION [CONCEPTO] , FCJ.VALORTOTAL INGRESOS, 0 EGRESOS 
				FROM FCJ 
					INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
					INNER JOIN ACJ ON FCJ.CNSACJ = ACJ.CNSACJ AND FCJ.CODCAJA = ACJ.CODCAJA
					INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
					LEFT JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
					LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
				WHERE  FCJ.CNSACJ = @CNSACJ AND FCJ.CODCAJA = @CODCAJA AND FCJ.CNSFACJ = @CNSACJ AND DEAPERTURA=1
				UNION ALL
				SELECT 'OK' OK,  FCJD.CNSFACJ, FCJ.FECHA, FCJ.IDTERCERO+'-'+TER.RAZONSOCIAL [NOMBRECLIENTE], FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION [CONCEPTO], 
					SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  FCJD.VALORTOTAL ELSE 0 END) INGRESOS, 
					SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  FCJD.VALORTOTAL ELSE 0 END)  EGRESOS
				FROM FCJ INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
						LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
						LEFT JOIN TER ON FCJ.IDTERCERO = TER.IDTERCERO
				WHERE FCJ.CNSACJ=@CNSACJ
				AND FCJ.CERRADA=1 
				AND COALESCE(FCJ.DEAPERTURA,0) <>1 
				AND FCJ.ESTADO<>'A' AND FCJ.CLASE_FAC = 'PAGO'
				GROUP BY  FCJD.CNSFACJ , FCJ.FECHA, FCJ.IDTERCERO+'-'+TER.RAZONSOCIAL , FCJD.CONCEPTO+' - '+CPCJ.DESCRIPCION
         
				/*Total Recibos*/
				SELECT SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  PCJ.VALOR ELSE 0 END) INGRESOS, 
					SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  PCJ.VALOR ELSE 0 END)  EGRESOS
				FROM FCJ INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
						INNER JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
						INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO 
						LEFT  JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
				WHERE FCJ.CNSACJ=@CNSACJ
				AND FCJ.CERRADA=1 
				AND COALESCE(FCJ.DEAPERTURA,0) <>1 
				AND FCJ.ESTADO<>'A'

				/*SUB TOTAL*/
				SELECT PCJ.TIPOPAGO,FPA.DESCRIPCION,SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  PCJ.VALOR ELSE 0 END) [VLR_INGRESO], 
				SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  PCJ.VALOR ELSE 0 END) [VLR_EGRESOS],
				SUM(CASE WHEN FCJ.CLASE_FAC='COBRO' THEN  PCJ.VALOR ELSE 0 END)-SUM(CASE WHEN FCJ.CLASE_FAC='PAGO' THEN  PCJ.VALOR ELSE 0 END) [VLR_SALDO]
				FROM FCJ INNER JOIN PCJ ON FCJ.CODCAJA=PCJ.CODCAJA AND FCJ.CNSFACJ=PCJ.CNSFACJ 
						INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO 
				WHERE FCJ.CNSACJ=@CNSACJ
				AND FCJ.CERRADA=1 
				AND COALESCE(FCJ.DEAPERTURA,0) <>1  
				AND FCJ.ESTADO<>'A'
				GROUP BY PCJ.TIPOPAGO,FPA.DESCRIPCION

				/*CAJERO IMPRIME*/
				SELECT CJR.CODCAJERO+' - '+CJR.DESCRIPCION [NOM_CAJERO] FROM  USUSU 
				LEFT JOIN CJR ON USUSU.CODCAJERO = CJR.CODCAJERO
				WHERE USUSU.USUARIO = @USUARIO

			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
			END CATCH
			IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK' OK
		END
	END 

	IF @METODO = 'IMPRIME_ARQUEO_EGRESO_FPA'
	BEGIN
		SELECT @CODCAJA = CODCAJA, @CNSFACJ = CNSFACJ, @CNSACJ = CNSACJ
		FROM OPENJSON(@PARAMETROS) WITH (
			CODCAJA VARCHAR(20) '$.CODCAJA',
			CNSFACJ VARCHAR(20) '$.CNSFACJ',
			CNSACJ  VARCHAR(20) '$.CNSACJ'
		)

		IF NOT EXISTS (
			SELECT 1
			FROM ACJ
			WHERE ACJ.CODCAJA = @CODCAJA AND ACJ.CNSACJ = @CNSACJ
		)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'No cuenta con Arqueo de Caja.'
		END

		IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		BEGIN TRY
			/* Cabecera */
			SELECT 'OK' OK, ACJ.CNSACJ, ACJ.CODCAJA, CAJ.DESCRIPCION,
				CONVERT(VARCHAR, ACJ.FECHAAPERTURA, 103) + ' ' + CONVERT(VARCHAR, ACJ.FECHAAPERTURA, 8) FECHAAPERTURA,
				ACJ.CODTURNO, TUR.DESCRIPCION [DESC_TURNO], ACJ.CODCAJERO, CJR.DESCRIPCION [NOM_CAJERO],
				CONVERT(VARCHAR, ACJ.FECHACIERRE, 103) + ' ' + CONVERT(VARCHAR, ACJ.FECHACIERRE, 8) FECHACIERRE,
				IIF(ACJ.ABIERTA = 0, 'NO', 'SI') ABIERTA,
				SED.DESCRIPCION [SED_NOMBRE], SED.DIRECCION [SED_DIRECCION],
				SED.TELEFONOS [SED_TELEFONOS], SED.NIT [SED_NIT], SED.DV [SED_DV],
				TERSED.NIT [NIT_ASEG], TERSED.RAZONSOCIAL [ASEG_NOMBRE], CIUSED.NOMBRE [SED_CIUDAD]
			FROM ACJ
				INNER JOIN CAJ ON ACJ.CODCAJA = CAJ.CODCAJA
				INNER JOIN TUR ON TUR.CODTURNO = ACJ.CODTURNO
				INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
				LEFT JOIN SED ON SED.IDSEDE = @IDSEDE
				LEFT JOIN TER TERSED ON SED.NIT = TERSED.NIT AND COALESCE(TERSED.RAZONSOCIAL, '') <> ''
				LEFT JOIN CIU CIUSED ON SED.CIUDAD = CIUSED.CIUDAD
			WHERE ACJ.CODCAJA = @CODCAJA AND ACJ.CNSACJ = @CNSACJ
			ORDER BY FECHAAPERTURA ASC

			/* DETALLE — mismo orden que IMPRIME_ARQUEO_EGRESO + FORMAS_PAGO JSON */
			SELECT
				D.OK,
				D.CNSFACJ,
				D.FECHA,
				D.NOMBRECLIENTE,
				D.CONCEPTO,
				D.INGRESOS,
				D.EGRESOS,
				D.FORMAS_PAGO
			FROM (
				/* COBRO */
				SELECT
					1 AS ORD_TIPO,
					'OK' OK,
					FCJ.CNSFACJ,
					FCJ.FECHA,
					FCJ.NOMBRECLIENTE,
					FCJD.CONCEPTO + ' - ' + CPCJ.DESCRIPCION [CONCEPTO],
					SUM(CASE WHEN FCJ.CLASE_FAC = 'COBRO' THEN FCJD.VALORTOTAL ELSE 0 END) INGRESOS,
					SUM(CASE WHEN FCJ.CLASE_FAC = 'PAGO' THEN FCJD.VALORTOTAL ELSE 0 END) EGRESOS,
					(
						SELECT
							P.TIPOPAGO,
							F.FORMAPAGO AS FORMA_PAGO,
							SUM(P.VALOR) AS MONTO
						FROM PCJ P
							INNER JOIN FPA F ON P.TIPOPAGO = F.FORMAPAGO
						WHERE P.CODCAJA = FCJ.CODCAJA
							AND P.CNSFACJ = FCJ.CNSFACJ
						GROUP BY P.TIPOPAGO, F.FORMAPAGO
						ORDER BY P.TIPOPAGO
						FOR JSON PATH
					) AS FORMAS_PAGO
				FROM FCJ
					INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
					LEFT JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
				WHERE FCJ.CNSACJ = @CNSACJ
					AND FCJ.CERRADA = 1
					AND COALESCE(FCJ.DEAPERTURA, 0) <> 1
					AND FCJ.ESTADO <> 'A'
					AND FCJ.CLASE_FAC = 'COBRO'
				GROUP BY
					FCJ.CNSFACJ,
					FCJ.CODCAJA,
					FCJ.FECHA,
					FCJ.NOMBRECLIENTE,
					FCJD.CONCEPTO + ' - ' + CPCJ.DESCRIPCION

				UNION ALL

				/* DE APERTURA */
				SELECT
					2 AS ORD_TIPO,
					'OK' OK,
					FCJ.CNSFACJ,
					FCJ.FECHA,
					ACJ.CODCAJERO + '-' + CJR.DESCRIPCION [NOMBRECLIENTE],
					FCJD.CONCEPTO + '-' + CPCJ.DESCRIPCION [CONCEPTO],
					FCJ.VALORTOTAL INGRESOS,
					0 EGRESOS,
					(
						SELECT
							P.TIPOPAGO,
							F.FORMAPAGO AS FORMA_PAGO,
							SUM(P.VALOR) AS MONTO
						FROM PCJ P
							INNER JOIN FPA F ON P.TIPOPAGO = F.FORMAPAGO
						WHERE P.CODCAJA = FCJ.CODCAJA
							AND P.CNSFACJ = FCJ.CNSFACJ
						GROUP BY P.TIPOPAGO, F.FORMAPAGO
						ORDER BY P.TIPOPAGO
						FOR JSON PATH
					) AS FORMAS_PAGO
				FROM FCJ
					INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
					INNER JOIN ACJ ON FCJ.CNSACJ = ACJ.CNSACJ AND FCJ.CODCAJA = ACJ.CODCAJA
					INNER JOIN CJR ON ACJ.CODCAJERO = CJR.CODCAJERO
					LEFT JOIN PCJ ON FCJ.CODCAJA = PCJ.CODCAJA AND FCJ.CNSFACJ = PCJ.CNSFACJ
					LEFT JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
				WHERE FCJ.CNSACJ = @CNSACJ
					AND FCJ.CODCAJA = @CODCAJA
					AND FCJ.CNSFACJ = @CNSFACJ
					AND FCJ.DEAPERTURA = 1

				UNION ALL

				/* PAGO */
				SELECT
					3 AS ORD_TIPO,
					'OK' OK,
					FCJD.CNSFACJ,
					FCJ.FECHA,
					FCJ.IDTERCERO + '-' + TER.RAZONSOCIAL [NOMBRECLIENTE],
					FCJD.CONCEPTO + ' - ' + CPCJ.DESCRIPCION [CONCEPTO],
					SUM(CASE WHEN FCJ.CLASE_FAC = 'COBRO' THEN FCJD.VALORTOTAL ELSE 0 END) INGRESOS,
					SUM(CASE WHEN FCJ.CLASE_FAC = 'PAGO' THEN FCJD.VALORTOTAL ELSE 0 END) EGRESOS,
					(
						SELECT
							P.TIPOPAGO,
							F.FORMAPAGO AS FORMA_PAGO,
							SUM(P.VALOR) AS MONTO
						FROM PCJ P
							INNER JOIN FPA F ON P.TIPOPAGO = F.FORMAPAGO
						WHERE P.CODCAJA = FCJ.CODCAJA
							AND P.CNSFACJ = FCJ.CNSFACJ
						GROUP BY P.TIPOPAGO, F.FORMAPAGO
						ORDER BY P.TIPOPAGO
						FOR JSON PATH
					) AS FORMAS_PAGO
				FROM FCJ
					INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
					LEFT JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
					LEFT JOIN TER ON FCJ.IDTERCERO = TER.IDTERCERO
				WHERE FCJ.CNSACJ = @CNSACJ
					AND FCJ.CERRADA = 1
					AND COALESCE(FCJ.DEAPERTURA, 0) <> 1
					AND FCJ.ESTADO <> 'A'
					AND FCJ.CLASE_FAC = 'PAGO'
				GROUP BY
					FCJD.CNSFACJ,
					FCJ.CNSFACJ,
					FCJ.CODCAJA,
					FCJ.FECHA,
					FCJ.IDTERCERO + '-' + TER.RAZONSOCIAL,
					FCJD.CONCEPTO + ' - ' + CPCJ.DESCRIPCION
			) D
			ORDER BY D.ORD_TIPO, D.FECHA, D.CNSFACJ, D.CONCEPTO

			/* Total recibos */
			SELECT
				SUM(CASE WHEN FCJ.CLASE_FAC = 'COBRO' THEN PCJ.VALOR ELSE 0 END) INGRESOS,
				SUM(CASE WHEN FCJ.CLASE_FAC = 'PAGO' THEN PCJ.VALOR ELSE 0 END) EGRESOS
			FROM FCJ
				INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA
				INNER JOIN PCJ ON FCJ.CODCAJA = PCJ.CODCAJA AND FCJ.CNSFACJ = PCJ.CNSFACJ
				INNER JOIN FPA ON PCJ.TIPOPAGO = FPA.FORMAPAGO
				LEFT JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
			WHERE FCJ.CNSACJ = @CNSACJ
				AND FCJ.CERRADA = 1
				AND COALESCE(FCJ.DEAPERTURA, 0) <> 1
				AND FCJ.ESTADO <> 'A'

			/* Subtotal por forma de pago */
			SELECT
				PCJ.TIPOPAGO,
				FPA.DESCRIPCION,
				SUM(CASE WHEN FCJ.CLASE_FAC = 'COBRO' THEN PCJ.VALOR ELSE 0 END) [VLR_INGRESO],
				SUM(CASE WHEN FCJ.CLASE_FAC = 'PAGO' THEN PCJ.VALOR ELSE 0 END) [VLR_EGRESOS],
				SUM(CASE WHEN FCJ.CLASE_FAC = 'COBRO' THEN PCJ.VALOR ELSE 0 END)
					- SUM(CASE WHEN FCJ.CLASE_FAC = 'PAGO' THEN PCJ.VALOR ELSE 0 END) [VLR_SALDO]
			FROM FCJ
				INNER JOIN PCJ ON FCJ.CODCAJA = PCJ.CODCAJA AND FCJ.CNSFACJ = PCJ.CNSFACJ
				INNER JOIN FPA ON PCJ.TIPOPAGO = FPA.FORMAPAGO
			WHERE FCJ.CNSACJ = @CNSACJ
				AND FCJ.CERRADA = 1
				AND COALESCE(FCJ.DEAPERTURA, 0) <> 1
				AND FCJ.ESTADO <> 'A'
			GROUP BY PCJ.TIPOPAGO, FPA.DESCRIPCION

			/* Cajero imprime */
			SELECT CJR.CODCAJERO + ' - ' + CJR.DESCRIPCION [NOM_CAJERO]
			FROM USUSU
				LEFT JOIN CJR ON USUSU.CODCAJERO = CJR.CODCAJERO
			WHERE USUSU.USUARIO = @USUARIO

		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR) SELECT ERROR_MESSAGE();
		END CATCH

		IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'IMPRIMIR_RECIBO_FCJ'
	BEGIN
		SELECT @CNSFACJ = CNSFACJ , @CODCAJA = CODCAJA
		FROM OPENJSON (@PARAMETROS)
		WITH (
			CNSFACJ			VARCHAR(20)    '$.CNSFACJ',
			CODCAJA			VARCHAR(4)     '$.CODCAJA'
			)
		SELECT 'OK'OK, PROCEDENCIA = CASE CLASE_FAC WHEN 'COBRO' THEN 'INGRESO' ELSE 'EGRESO' END,FCJ.NOADMISION CONSECUTIVO, AFI.TIPO_DOC, AFI.DOCIDAFILIADO,COALESCE( AFI.NOMBREAFI, CJR.DESCRIPCION)NOMBREAFI , AFI.DIRECCION, AFI.SEXO, FCJ.IDPLAN, PLN.DESCPLAN, FCJ.IDTERCERO, TER.RAZONSOCIAL
							, CASE WHEN DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') = FCJ.IDTERCERO THEN 1 ELSE 0 END ESPART
							, AFI.CELULAR, AFI.TELEFONORES,AFI.EDAD, COALESCE( AFI.IDALTERNA,'')IDALTERNA , CIUAFI.NOMBRE [CIU_NOMBRE], AFI.EMAIL, AFI.IDTIPOAFILIACION,AFI.ESTADO_CIVIL
							, NIVELSOCIOEC, AFI.TIPOAFILIADO
							, CASE   WHEN AFI.TIPOAFILIADO = 'C' THEN 'Cotizante'
									WHEN AFI.TIPOAFILIADO = 'B' THEN 'Beneficiario'
									WHEN AFI.TIPOAFILIADO = 'J' THEN 'Jubilado'
									WHEN AFI.TIPOAFILIADO = 'A' THEN 'Adicional'
									WHEN AFI.TIPOAFILIADO = 'S' THEN 'Sustitución Pensional'
									WHEN AFI.TIPOAFILIADO = 'Sb' THEN 'Subsidiado'
									WHEN AFI.TIPOAFILIADO = 'SR' THEN 'Sin régimen'
									WHEN AFI.TIPOAFILIADO = 'TA' THEN 'Tomador/Amparado'
									WHEN AFI.TIPOAFILIADO = 'RE' THEN 'Régimen Especiales o de Excepción'
									WHEN AFI.TIPOAFILIADO = 'SN' THEN 'S/N'
									WHEN AFI.TIPOAFILIADO = 'S/' THEN 'S/N'
									WHEN AFI.TIPOAFILIADO = 'S/N' THEN 'S/N' ELSE '' END [TIPOAFI_NOMBRE]
			,CONVERT (DATE ,FCJ.FECHA) FECHA, CONVERT(varchar,FCJ.FECHA,104) FECHAFORMATO, CONVERT (DATETIME ,FCJ.FECHA) FECHACOMPLETA, DATEPART(HOUR, FCJ.FECHA) HORA
			,Format(FCJ.FECHA,'dd/MM/yyyy hh:mm tt') AS FECHA_HORARIO,   CONVERT(varchar,FCJ.FECHA,104) FECHACITA
			,COALESCE(FCJ.OBSERVACION,'Sin Observacion') OBSERVACION, SED.IDSEDE, SED.DESCRIPCION [SED_NOMBRE], SED.DIRECCION [SED_DIRECCION]
			,SED.TELEFONOS [SED_TELEFONOS],  SED.DESCRIPCION [SED_CIUDAD], SED.NIT [SED_NIT], SED.DV [SED_DV]
			,FCJ.N_RECIBO , FCJ.CNSFACJ, FCJ.CODCAJA, FCJ.CLASE_FAC, FCJ.NOADMISION, FCJ.VALORTOTAL,FCJ.ESTADO, FCJ.CERRADA
			,FCJ.N_FACTURA, M.NOREFERENCIA AS NROCOMPROBANTE, COALESCE(FCJ.USUARIO, CJR.CODCAJERO) USUARIO,COALESCE( USUSU.NOMBRE, CJR.DESCRIPCION) [USUSU_NOMBRE], USUSU.CODCAJERO [COD_CAJERO]
		FROM FCJ 

		LEFT JOIN USUSU ON FCJ.USUARIO = USUSU.USUARIO
		LEFT JOIN CJR ON FCJ.USUARIO = CJR.CODCAJERO
		LEFT JOIN AFI ON FCJ.IDAFILIADO = AFI.IDAFILIADO
		LEFT JOIN SED ON @IDSEDE = SED.IDSEDE
		LEFT JOIN TER ON FCJ.IDTERCERO = TER.IDTERCERO
		LEFT JOIN PLN ON FCJ.IDTERCERO = PLN.IDPLAN
		LEFT JOIN CIU CIUAFI ON AFI.CIUDAD = CIUAFI.CIUDAD
		LEFT JOIN MCP M ON M.NROCOMPROBANTE = FCJ.NROCOMPROBANTE
		WHERE FCJ.CNSFACJ = @CNSFACJ
		AND   FCJ.CODCAJA =@CODCAJA

		SELECT FCJ.NOADMISION, FCJD.CONCEPTO,  CPCJ.DESCRIPCION CONCEPTO_DESC,  FCJD.VALORUNITARIO, FCJD.CANTIDAD, FCJD.VALORTOTAL, FCJD.DCTO, FCJD.VLRDESCUENTO 
		FROM   FCJ INNER JOIN FCJD ON FCJ.CNSFACJ = FCJD.CNSFACJ AND FCJ.CODCAJA = FCJD.CODCAJA  
				INNER JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO
		WHERE  FCJ.CNSFACJ = @CNSFACJ
		AND    FCJ.CODCAJA = @CODCAJA
         
		SELECT PCJ.CODCAJA, PCJ.CNSPCJ, PCJ.CNSFACJ, PCJ.TIPOPAGO, FPA.DESCRIPCION, PCJ.VALOR, PCJ.FECHA, PCJ.CNSACJ,PCJ.BANCO,BCO.DESCRIPCION [BANCO_DESC], PCJ.NUMEROAUTORIZA, PCJ.NUMERODOCUMENTO
		FROM  PCJ 
		INNER JOIN FPA ON PCJ.TIPOPAGO=  FPA.FORMAPAGO 
		LEFT JOIN BCO ON PCJ.BANCO = BCO.BANCO
		WHERE  CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ

		SELECT SUM(PCJ.VALOR) VALOR_FPA FROM PCJ  
		WHERE  CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ

		SELECT TER.RAZONSOCIAL, FCJPCXC.CNSFACJ, FCJPCXC.CODCAJA, FCJPCXC.CNSCXC, FCJPCXC.N_FACTURA, FCJPCXC.ITEM_FCXCDV, FCJPCXC.IDTERCERO, FCJPCXC.VALOR, FCJPCXC.ESTADO, FCJPCXC.CNSFPAG
			,FCJPCXC.TIPOCXC, FCJPCXC.VLR_IMPUESTOS FROM  FCJPCXC
		LEFT JOIN TER ON FCJPCXC.IDTERCERO = TER.IDTERCERO
		WHERE  FCJPCXC.CODCAJA = @CODCAJA AND FCJPCXC.CNSFACJ = @CNSFACJ

		SELECT  FCJPCXC.CNSFACJ, FCJPCXC.CODCAJA,COALESCE( SUM(FCJPCXC.VALOR),0) VALOR, COALESCE(SUM( FCJPCXC.VLR_IMPUESTOS),0) IMPUESTO FROM  FCJPCXC
		WHERE FCJPCXC.CODCAJA = @CODCAJA AND FCJPCXC.CNSFACJ = @CNSFACJ
		GROUP BY FCJPCXC.CNSFACJ, FCJPCXC.CODCAJA
		RETURN
	END
	
	IF @METODO = 'UPDATE_PRINT'	
	BEGIN
		SELECT
			@CODCAJA = JSON_VALUE(@PARAMETROS, '$.CODCAJA'),
			@CNSFACJ = JSON_VALUE(@PARAMETROS, '$.CNSFACJ')
		BEGIN TRY
			UPDATE FCJ SET IMPRESO=COALESCE(IMPRESO,0)+1 WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ
		END TRY
		BEGIN CATCH
			SELECT 'KO' OK
			SELECT ERROR = 'Hubo un error al intentar imprimir, error:'+ERROR_MESSAGE()
			RETURN
		END CATCH
		SELECT 'OK' OK
	END

		IF @METODO = 'rptRPF_LGD'	
		BEGIN
			SELECT
				@FECHAINI      = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
				@FECHAFIN      = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
				@CLASE_FAC     = JSON_VALUE(@PARAMETROS, '$.CLASE_FAC'),
				@IDTERCERO     = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
				@CODCAJERO     = JSON_VALUE(@PARAMETROS, '$.CODCAJERO'),
				@FORMAPAGO     = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO'),
				@CONCEPTO      = JSON_VALUE(@PARAMETROS, '$.CONCEPTO'),
				@NOINCLUIRCAJA = JSON_VALUE(@PARAMETROS, '$.NOINCLUIRCAJA');

			INSERT INTO @CAJAS(CODCAJA)
			SELECT value
			FROM OPENJSON(@PARAMETROS, '$.CODCAJA');

			SELECT 'OK' OK;

			-- DETALLE
			SELECT 
				ROW_NUMBER() OVER(ORDER BY FCJ.CODCAJA, FCJ.CNSFACJ ) ITEM,
				FCJ.CODCAJA,
				FCJ.CODCAJA AS CAJA,
				CAJ.DESCRIPCION AS NOMBRE_CAJA, 
				CJR.DESCRIPCION AS NOMBRE_CAJERO,
				FCJ.CNSFACJ,
				CONVERT(VARCHAR(10), FCJ.FECHA, 103) AS FECHA,
				COALESCE(CIT.TIPOCITA, '') AS TIPOCITA,
				COALESCE(SED.DESCRIPCION, '') AS SEDE,
				COALESCE(FCJ.VALORTOTAL,0) VALORTOTAL,
				FCJ.PROCEDENCIA,
				ORIGEN_RECAUDO = CASE
					WHEN FCJ.PROCEDENCIA = 'CITAS' AND COALESCE(CIT.IDAPLIM, 0) > 0
						THEN 'Aplicación de medicamentos (Agenda de aplicaciones)'
					WHEN FCJ.PROCEDENCIA = 'CITAS'
						THEN 'Citas (Agenda)'
					WHEN FCJ.PROCEDENCIA = 'CE' AND AUT.PEDIDOINV>0
						THEN 'Farmacia (Entrega de medicamentos)'
					WHEN FCJ.PROCEDENCIA = 'CE' AND isnull(AUT.PEDIDOINV,0)<1
						THEN 'Autorizador (otros)'
					ELSE COALESCE(FCJ.PROCEDENCIA, '')
				END,
				COALESCE(TER.NIT,'') NIT,
				COALESCE(DBO.FNK_LIMPIATEXTO(TER.RAZONSOCIAL,' a-zA-Z 0-9'),'') RAZONSOCIAL,
                PLN.DESCPLAN,
				ACJ.CODCAJERO,
				COALESCE(FCJ.N_FACTURA,'') N_FACTURA,
				DBO.FNK_ESTADOFCJ(FCJ.CODCAJA, FCJ.CNSFACJ) ESTADO,
				COALESCE(FCJ.OBSERVACION,'') OBSERVACION,
                EPS=DBO.FNK_LIMPIATEXTO(COALESCE(T2.RAZONSOCIAL,''),' a-zA-Z 0-9'),
                CAUSA_ANULA=COALESCE(CAU.DESCCAUSAL,''),
                OBS_ANULA=COALESCE(FCJ.DETALLEANULACION,'')
			
			FROM FCJ
			LEFT JOIN FCJD ON FCJD.CNSFACJ = FCJ.CNSFACJ AND FCJD.CODCAJA = FCJ.CODCAJA
            LEFT JOIN CIT ON CIT.CONSECUTIVO=FCJ.NOADMISION AND FCJ.PROCEDENCIA='CITAS'
			LEFT JOIN SED ON SED.IDSEDE = CIT.IDSEDE
            LEFT JOIN AUT ON AUT.IDAUT=FCJ.NOADMISION AND FCJ.PROCEDENCIA='CE'
            LEFT JOIN PLN ON PLN.IDPLAN=COALESCE(CIT.IDPLAN, AUT.IDPLAN)
			LEFT JOIN TER  ON TER.IDTERCERO = FCJ.IDTERCERO
            LEFT JOIN CAU ON CAU.IDCAUSAL=FCJ.IDCAUSALANUL
            LEFT JOIN AFI  ON AFI.IDAFILIADO=FCJ.IDAFILIADO
			LEFT JOIN TER T2  ON T2.IDTERCERO = AFI.IDADMINISTRADORA
			LEFT JOIN ACJ  ON ACJ.CNSACJ = FCJ.CNSACJ
			LEFT JOIN PCJ  ON PCJ.CNSFACJ = FCJ.CNSFACJ AND PCJ.CODCAJA = FCJ.CODCAJA
			LEFT JOIN CAJ  ON CAJ.CODCAJA = FCJ.CODCAJA
			LEFT JOIN CJR  ON CJR.CODCAJERO = ACJ.CODCAJERO
			WHERE CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
			  AND FCJ.CLASE_FAC = @CLASE_FAC
			  AND COALESCE(FCJ.DEAPERTURA,0) IN (0,2)
			  AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
			  AND (COALESCE(@CONCEPTO,'') = '' OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO,',',0,NULL)))
			  AND (COALESCE(@CODCAJERO,'') = '' OR ACJ.CODCAJERO = @CODCAJERO)
			  AND (COALESCE(@IDTERCERO,'') = '' OR FCJ.IDTERCERO = @IDTERCERO)
			  AND (COALESCE(@FORMAPAGO,'') = '' OR PCJ.TIPOPAGO = @FORMAPAGO)
			  AND (COALESCE(@NOINCLUIRCAJA,'') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA,',',0,NULL)));

			--RESUMEN POR ESTADO
			SELECT 
				UPPER(DBO.FNK_ESTADOFCJ(FCJ.CODCAJA, FCJ.CNSFACJ)) ESTADO,
				COUNT(1) CANTIDAD,
				SUM(VALORTOTAL) VALOR
			FROM FCJ
			LEFT JOIN TER ON TER.IDTERCERO = FCJ.IDTERCERO
			LEFT JOIN ACJ ON ACJ.CNSACJ = FCJ.CNSACJ
			LEFT JOIN PCJ ON PCJ.CNSFACJ = FCJ.CNSFACJ AND PCJ.CODCAJA = FCJ.CODCAJA
			WHERE CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
			  AND FCJ.CLASE_FAC = @CLASE_FAC
			  AND COALESCE(FCJ.DEAPERTURA,0) IN (0,2)
			  AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
			  AND (COALESCE(@CODCAJERO,'') = '' OR ACJ.CODCAJERO = @CODCAJERO)
			  AND (COALESCE(@IDTERCERO,'') = '' OR FCJ.IDTERCERO = @IDTERCERO)
			  AND (COALESCE(@FORMAPAGO,'') = '' OR PCJ.TIPOPAGO = @FORMAPAGO)
			  AND (COALESCE(@NOINCLUIRCAJA,'') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA,',',0,NULL)))
			GROUP BY DBO.FNK_ESTADOFCJ(FCJ.CODCAJA, FCJ.CNSFACJ);

			--RESUMEN POR FORMA DE PAGO
			SELECT 
				FPA.FORMAPAGO,
				FPA.DESCRIPCION,
				SUM(PCJ.VALOR) VALOR
			FROM FCJ
			INNER JOIN PCJ ON PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ
			INNER JOIN FPA ON FPA.FORMAPAGO = PCJ.TIPOPAGO
			LEFT JOIN TER  ON TER.IDTERCERO = FCJ.IDTERCERO
			LEFT JOIN FCJD ON FCJD.CNSFACJ = FCJ.CNSFACJ AND FCJD.CODCAJA = FCJ.CODCAJA
			LEFT JOIN ACJ  ON ACJ.CNSACJ = FCJ.CNSACJ
			WHERE CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
			  AND FCJ.CLASE_FAC = @CLASE_FAC
			  AND COALESCE(FCJ.DEAPERTURA,0) IN (0,2)
			  AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
			  AND (COALESCE(@CONCEPTO,'') = '' OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO,',',0,NULL)))
			  AND (COALESCE(@CODCAJERO,'') = '' OR ACJ.CODCAJERO = @CODCAJERO)
			  AND (COALESCE(@IDTERCERO,'') = '' OR FCJ.IDTERCERO = @IDTERCERO)
			  AND (COALESCE(@FORMAPAGO,'') = '' OR FPA.FORMAPAGO = @FORMAPAGO)
			  AND (COALESCE(@NOINCLUIRCAJA,'') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA,',',0,NULL)))
			GROUP BY FPA.FORMAPAGO, FPA.DESCRIPCION;
		END

		IF @METODO = 'rptRPF_FPDSUB'
		BEGIN
			SELECT 
				@FECHAINI      = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
				@FECHAFIN      = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
				@CLASE_FAC     = JSON_VALUE(@PARAMETROS, '$.CLASE_FAC'),
				@IDTERCERO     = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
				@CODCAJERO     = JSON_VALUE(@PARAMETROS, '$.CODCAJERO'),
				@FORMAPAGO     = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO'),
				@CONCEPTO      = JSON_VALUE(@PARAMETROS, '$.CONCEPTO'),
				@NOINCLUIRCAJA = JSON_VALUE(@PARAMETROS, '$.NOINCLUIRCAJA');

			-- Tabla con los CODCAJA 
			INSERT INTO @CAJAS (CODCAJA)
			SELECT value
			FROM OPENJSON(@PARAMETROS, '$.CODCAJA');

			SELECT 'OK' OK;

			SELECT 
				FPA.FORMAPAGO, 
				FPA.DESCRIPCION, 
				FCJ.CODCAJA, 
				CAJ.DESCRIPCION AS NOMBRE_CAJA,
				FCJ.CNSFACJ, 		
				CONVERT(VARCHAR(10), FCJ.FECHA, 103) AS FECHA,
				COALESCE(PCJ.VALOR, 0) AS VALORTOTAL, 
				TER.IDTERCERO,
				COALESCE(DBO.FNK_LIMPIATEXTO(TER.RAZONSOCIAL,' a-zA-Z 0-9'), '') AS RAZONSOCIAL,
				ACJ.CODCAJERO,
				CJR.DESCRIPCION AS NOMBRE_CAJERO,
				PCJ.TIPOPAGO, 
				FCJ.NROCOMPROBANTE,
				ESTADOMCP = CASE 
								WHEN MCP.ANULADO = 1 THEN 'A' 
								ELSE CASE MCP.ESTADO 
										WHEN 0 THEN 'E' 
										WHEN 1 THEN 'P' 
										WHEN 2 THEN 'C' 
										ELSE '?' 
									 END 
							END,
				PCJ.NUMERODOCUMENTO
			FROM FCJ
			INNER JOIN PCJ ON PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ
			LEFT JOIN FPA ON FPA.FORMAPAGO = PCJ.TIPOPAGO
			LEFT JOIN MCP ON MCP.NROCOMPROBANTE = FCJ.NROCOMPROBANTE
			LEFT JOIN TER ON TER.IDTERCERO = FCJ.IDTERCERO
			LEFT JOIN FCJD ON FCJD.CNSFACJ = FCJ.CNSFACJ AND FCJD.CODCAJA = FCJ.CODCAJA
			LEFT JOIN ACJ ON ACJ.CNSACJ = FCJ.CNSACJ
			LEFT JOIN CAJ ON CAJ.CODCAJA = FCJ.CODCAJA
			LEFT JOIN CJR  ON CJR.CODCAJERO = ACJ.CODCAJERO
			WHERE CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
			  AND FCJ.CLASE_FAC = @CLASE_FAC
			  AND COALESCE(FCJ.DEAPERTURA, 0) IN (0, 2)
			  AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
			  AND (COALESCE(@CONCEPTO, '') = '' OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO, ',', 0, NULL)))
			  AND (COALESCE(@CODCAJERO, '') = '' OR ACJ.CODCAJERO = @CODCAJERO)
			  AND (COALESCE(@IDTERCERO, '') = '' OR FCJ.IDTERCERO = @IDTERCERO)
			  AND (COALESCE(@FORMAPAGO, '') = '' OR FPA.FORMAPAGO = @FORMAPAGO)
			  AND (COALESCE(@NOINCLUIRCAJA, '') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA, ',', 0, NULL)))
			ORDER BY FPA.FORMAPAGO, FPA.DESCRIPCION, FCJ.FECHA;
		END

		IF @METODO = 'rptRPF_FPA'
		BEGIN
			SELECT 
				@FECHAINI      = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
				@FECHAFIN      = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
				@CLASE_FAC     = JSON_VALUE(@PARAMETROS, '$.CLASE_FAC'),
				@IDTERCERO     = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
				@CODCAJERO     = JSON_VALUE(@PARAMETROS, '$.CODCAJERO'),
				@FORMAPAGO     = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO'),
				@CONCEPTO      = JSON_VALUE(@PARAMETROS, '$.CONCEPTO'),
				@NOINCLUIRCAJA = JSON_VALUE(@PARAMETROS, '$.NOINCLUIRCAJA');
   
			INSERT INTO @CAJAS(CODCAJA)
			SELECT value
			FROM OPENJSON(@PARAMETROS, '$.CODCAJA');

			SELECT 'OK' OK;

			SELECT 
				FPA.FORMAPAGO,
				FPA.DESCRIPCION,
				COALESCE(PCJ.VALOR, 0) AS VALORTOTAL
			FROM FCJ
			INNER JOIN PCJ ON PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ
			INNER JOIN FPA ON FPA.FORMAPAGO = PCJ.TIPOPAGO
			LEFT JOIN TER ON TER.IDTERCERO = FCJ.IDTERCERO
			LEFT JOIN FCJD ON FCJD.CNSFACJ = FCJ.CNSFACJ AND FCJD.CODCAJA = FCJ.CODCAJA
			LEFT JOIN ACJ ON ACJ.CNSACJ = FCJ.CNSACJ
			WHERE 
				CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
				AND FCJ.CLASE_FAC = @CLASE_FAC
				AND COALESCE(FCJ.DEAPERTURA, 0) IN (0, 2)
				AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
				AND (COALESCE(@CONCEPTO, '') = '' OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO, ',', 0, NULL)))
				AND (COALESCE(@CODCAJERO, '') = '' OR ACJ.CODCAJERO = @CODCAJERO)
				AND (COALESCE(@IDTERCERO, '') = '' OR FCJ.IDTERCERO = @IDTERCERO)
				AND (COALESCE(@FORMAPAGO, '') = '' OR FPA.FORMAPAGO = @FORMAPAGO)
				AND (COALESCE(@NOINCLUIRCAJA, '') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA, ',', 0, NULL)))
			ORDER BY FPA.FORMAPAGO, FPA.DESCRIPCION;
		END

		IF @METODO = 'rptRPF_CDSUB'
		BEGIN
			SELECT 
				@FECHAINI      = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
				@FECHAFIN      = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
				@CLASE_FAC     = JSON_VALUE(@PARAMETROS, '$.CLASE_FAC'),
				@IDTERCERO     = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
				@CODCAJERO     = JSON_VALUE(@PARAMETROS, '$.CODCAJERO'),
				@FORMAPAGO     = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO'),
				@CONCEPTO      = JSON_VALUE(@PARAMETROS, '$.CONCEPTO'),
				@NOINCLUIRCAJA = JSON_VALUE(@PARAMETROS, '$.NOINCLUIRCAJA');

			INSERT INTO @CAJAS(CODCAJA)
			SELECT value
			FROM OPENJSON(@PARAMETROS, '$.CODCAJA');

			SELECT 'OK' OK;

			-- DETALLE DE FACTURAS
			SELECT 
				ROW_NUMBER() OVER(ORDER BY FCJ.CODCAJA, FCJ.CNSFACJ) ITEM,
				FCJ.CODCAJA,
				CAJ.DESCRIPCION AS NOMBRE_CAJA,
				FCJ.CNSFACJ,
				FCJ.FECHA,
				COALESCE(DBO.FNK_LIMPIATEXTO(TER.RAZONSOCIAL,' a-zA-Z 0-9'),'') AS RAZONSOCIAL,
				TER.IDTERCERO,
				COALESCE(PCJ.VALOR, 0) AS VALORTOTAL,
				ACJ.CODCAJERO,
				CJR.DESCRIPCION AS NOMBRE_CAJERO,
				FCJ.NROCOMPROBANTE,
				FCJD.CONCEPTO,
				CPCJ.DESCRIPCION,
				UPPER(DBO.FNK_ESTADOFCJ(FCJ.CODCAJA, FCJ.CNSFACJ)) AS ESTADO
			FROM FCJ
			INNER JOIN PCJ ON PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ
			INNER JOIN FPA ON FPA.FORMAPAGO = PCJ.TIPOPAGO
			LEFT JOIN TER ON TER.IDTERCERO = FCJ.IDTERCERO
			LEFT JOIN FCJD ON FCJD.CNSFACJ = FCJ.CNSFACJ AND FCJD.CODCAJA = FCJ.CODCAJA
			LEFT JOIN ACJ ON ACJ.CNSACJ = FCJ.CNSACJ
			LEFT JOIN CPCJ ON CPCJ.CODIGO = FCJD.CONCEPTO
			LEFT JOIN CAJ ON CAJ.CODCAJA = FCJ.CODCAJA
			LEFT JOIN CJR ON CJR.CODCAJERO = ACJ.CODCAJERO
			WHERE 
				CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
				AND FCJ.CLASE_FAC = @CLASE_FAC
				AND COALESCE(FCJ.DEAPERTURA,0) IN (0,2)
				AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
				AND (COALESCE(@CONCEPTO, '') = '' OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO, ',', 0, NULL)))
				AND (COALESCE(@CODCAJERO, '') = '' OR ACJ.CODCAJERO = @CODCAJERO)
				AND (COALESCE(@IDTERCERO, '') = '' OR FCJ.IDTERCERO = @IDTERCERO)
				AND (COALESCE(@FORMAPAGO, '') = '' OR FPA.FORMAPAGO = @FORMAPAGO)
				AND (COALESCE(@NOINCLUIRCAJA, '') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA, ',', 0, NULL)));

			-- RESUMEN POR FORMA DE PAGO Y CONCEPTO
			SELECT 
				FPA.FORMAPAGO,
				FPA.DESCRIPCION,
				COALESCE(FCJ.VALORTOTAL, 0) AS VALORTOTAL,
				FCJD.CONCEPTO,
				CPCJ.DESCRIPCION AS DESC_CONCEPTO
			FROM FCJ
			INNER JOIN PCJ ON PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ
			INNER JOIN FPA ON FPA.FORMAPAGO = PCJ.TIPOPAGO
			LEFT JOIN TER ON TER.IDTERCERO = FCJ.IDTERCERO
			LEFT JOIN FCJD ON FCJD.CNSFACJ = FCJ.CNSFACJ AND FCJD.CODCAJA = FCJ.CODCAJA
			LEFT JOIN ACJ ON ACJ.CNSACJ = FCJ.CNSACJ
			LEFT JOIN CPCJ ON CPCJ.CODIGO = FCJD.CONCEPTO
			WHERE 
				CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
				AND FCJ.CLASE_FAC = @CLASE_FAC
				AND COALESCE(FCJ.DEAPERTURA,0) IN (0,2)
				AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
				AND (COALESCE(@CONCEPTO, '') = '' OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO, ',', 0, NULL)))
				AND (COALESCE(@CODCAJERO, '') = '' OR ACJ.CODCAJERO = @CODCAJERO)
				AND (COALESCE(@IDTERCERO, '') = '' OR FCJ.IDTERCERO = @IDTERCERO)
				AND (COALESCE(@FORMAPAGO, '') = '' OR FPA.FORMAPAGO = @FORMAPAGO)
				AND (COALESCE(@NOINCLUIRCAJA, '') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA, ',', 0, NULL)))
			ORDER BY FPA.FORMAPAGO, FPA.DESCRIPCION;
		END

		IF @METODO = 'rptRPF_CA'
		BEGIN
			SELECT 
				@FECHAINI      = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
				@FECHAFIN      = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
				@CLASE_FAC     = JSON_VALUE(@PARAMETROS, '$.CLASE_FAC'),
				@IDTERCERO     = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
				@CODCAJERO     = JSON_VALUE(@PARAMETROS, '$.CODCAJERO'),
				@FORMAPAGO     = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO'),
				@CONCEPTO      = JSON_VALUE(@PARAMETROS, '$.CONCEPTO'),
				@NOINCLUIRCAJA = JSON_VALUE(@PARAMETROS, '$.NOINCLUIRCAJA');

			INSERT INTO @CAJAS(CODCAJA)
			SELECT value
			FROM OPENJSON(@PARAMETROS, '$.CODCAJA');

			SELECT 'OK' OK;

			-- DETALLE
			SELECT 
				COALESCE(PCJ.VALOR, 0) AS VALORTOTAL,  
				FCJD.CONCEPTO, 
				CPCJ.DESCRIPCION,
				UPPER(DBO.FNK_ESTADOFCJ(FCJ.CODCAJA, FCJ.CNSFACJ)) AS ESTADO
			FROM FCJ
			LEFT JOIN FCJD ON FCJD.CODCAJA = FCJ.CODCAJA AND FCJD.CNSFACJ = FCJ.CNSFACJ
			LEFT JOIN PCJ ON PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ
			LEFT JOIN CPCJ ON CPCJ.CODIGO = FCJD.CONCEPTO
			LEFT JOIN ACJ ON ACJ.CNSACJ = FCJ.CNSACJ
			WHERE 
				CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
				AND FCJ.CLASE_FAC = @CLASE_FAC
				AND COALESCE(FCJ.DEAPERTURA, 0) IN (0, 2)
				AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
				AND (COALESCE(@CONCEPTO, '') = '' OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO, ',', 0, NULL)))
				AND (COALESCE(@CODCAJERO, '') = '' OR ACJ.CODCAJERO = @CODCAJERO)
				AND (COALESCE(@IDTERCERO, '') = '' OR FCJ.IDTERCERO = @IDTERCERO)
				AND (COALESCE(@FORMAPAGO, '') = '' OR PCJ.TIPOPAGO = @FORMAPAGO)
				AND (COALESCE(@NOINCLUIRCAJA, '') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA, ',', 0, NULL)));

			-- RESUMEN POR FORMA DE PAGO Y CONCEPTO
			SELECT 
				FPA.FORMAPAGO,
				FPA.DESCRIPCION,
				COALESCE(PCJ.VALOR, 0) AS VALORTOTAL,
				FCJD.CONCEPTO,
				CPCJ.DESCRIPCION AS DESC_CONCEPTO
			FROM FCJ
			INNER JOIN PCJ ON PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ
			INNER JOIN FPA ON FPA.FORMAPAGO = PCJ.TIPOPAGO
			LEFT JOIN FCJD ON FCJD.CNSFACJ = FCJ.CNSFACJ AND FCJD.CODCAJA = FCJ.CODCAJA
			LEFT JOIN CPCJ ON CPCJ.CODIGO = FCJD.CONCEPTO
			LEFT JOIN ACJ ON ACJ.CNSACJ = FCJ.CNSACJ
			WHERE 
				CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
				AND FCJ.CLASE_FAC = @CLASE_FAC
				AND COALESCE(FCJ.DEAPERTURA, 0) IN (0, 2)
				AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
				AND (COALESCE(@CONCEPTO, '') = '' OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO, ',', 0, NULL)))
				AND (COALESCE(@CODCAJERO, '') = '' OR ACJ.CODCAJERO = @CODCAJERO)
				AND (COALESCE(@IDTERCERO, '') = '' OR FCJ.IDTERCERO = @IDTERCERO)
				AND (COALESCE(@FORMAPAGO, '') = '' OR PCJ.TIPOPAGO = @FORMAPAGO)
				AND (COALESCE(@NOINCLUIRCAJA, '') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA, ',', 0, NULL)))
			ORDER BY FPA.FORMAPAGO, FPA.DESCRIPCION;
		END

	IF @METODO = 'rptRPF_MB'
		BEGIN
			SELECT 
				@FECHAINI      = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
				@FECHAFIN      = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
				@CLASE_FAC     = JSON_VALUE(@PARAMETROS, '$.CLASE_FAC'),
				@IDTERCERO     = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
				@CODCAJERO     = JSON_VALUE(@PARAMETROS, '$.CODCAJERO'),
				@FORMAPAGO     = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO'),
				@CONCEPTO      = JSON_VALUE(@PARAMETROS, '$.CONCEPTO'),
				@NOINCLUIRCAJA = JSON_VALUE(@PARAMETROS, '$.NOINCLUIRCAJA');

			INSERT INTO @CAJAS(CODCAJA)
			SELECT value
			FROM OPENJSON(@PARAMETROS, '$.CODCAJA');

			SELECT 'OK' OK;

			-- DETALLE
			SELECT 
				FPA.FORMAPAGO, 
				FPA.DESCRIPCION, 
				FCJ.CODCAJA, 
				CAJ.DESCRIPCION AS CAJA, 
				FCJ.CNSFACJ, 
				FCJ.FECHA, 
				COALESCE(PCJ.VALOR, 0) AS VALORTOTAL, 
				BCO.IDTERCERO,
				COALESCE(DBO.FNK_LIMPIATEXTO(TER.RAZONSOCIAL,' a-zA-Z 0-9'), '') AS RAZONSOCIAL,
				CJR.DESCRIPCION AS CAJERO, 
				PCJ.TIPOPAGO, 
				FCJ.NROCOMPROBANTE,
				ESTADOMCP = CASE 
								WHEN MCP.ANULADO = 1 THEN 'A' 
								ELSE CASE MCP.ESTADO WHEN 0 THEN 'E' WHEN 1 THEN 'P' WHEN 2 THEN 'C' ELSE '?' END
							 END,
				PCJ.NUMERODOCUMENTO, 
				BCT.BANCO, 
				BCT.CTA_BCO, 
				BSU.SUCURSAL, 
				BSU.DESCRIPCION AS DESC_SUC, 
				BCO.DESCRIPCION AS DESC_BCO
			FROM FCJ
			INNER JOIN PCJ ON PCJ.CODCAJA = FCJ.CODCAJA AND PCJ.CNSFACJ = FCJ.CNSFACJ
			INNER JOIN FPA ON FPA.FORMAPAGO = PCJ.TIPOPAGO
			LEFT JOIN MCP ON MCP.NROCOMPROBANTE = FCJ.NROCOMPROBANTE
			LEFT JOIN FCJD ON FCJD.CNSFACJ = FCJ.CNSFACJ AND FCJD.CODCAJA = FCJ.CODCAJA
			LEFT JOIN ACJ ON ACJ.CNSACJ = FCJ.CNSACJ
			LEFT JOIN BCT ON BCT.BANCO = PCJ.BANCO AND BCT.SUCURSAL = PCJ.SUCURSAL AND BCT.CTA_BCO = PCJ.CTA_BCO
			LEFT JOIN BSU ON BSU.BANCO = BCT.BANCO AND BSU.SUCURSAL = BCT.SUCURSAL
			LEFT JOIN BCO ON BCO.BANCO = BSU.BANCO
			LEFT JOIN TER ON BCO.IDTERCERO = TER.IDTERCERO
			LEFT JOIN CJR ON CJR.CODCAJERO = ACJ.CODCAJERO
			LEFT JOIN CAJ ON CAJ.CODCAJA = FCJ.CODCAJA
			WHERE 
				CAST(FCJ.FECHA AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
				AND FCJ.CLASE_FAC = @CLASE_FAC
				AND COALESCE(FCJ.DEAPERTURA, 0) IN (0, 2)
				AND (NOT EXISTS(SELECT 1 FROM @CAJAS) OR FCJ.CODCAJA IN (SELECT CODCAJA FROM @CAJAS))
				AND (COALESCE(@CODCAJERO, '') = '' OR ACJ.CODCAJERO = @CODCAJERO)
				AND (COALESCE(@IDTERCERO, '') = '' OR FCJ.IDTERCERO = @IDTERCERO)
				AND (COALESCE(@FORMAPAGO, '') = '' OR FPA.FORMAPAGO = @FORMAPAGO)
				AND (COALESCE(@CONCEPTO, '') = '' OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO, ',', 0, NULL)))
				AND (COALESCE(@NOINCLUIRCAJA, '') = '' OR FCJ.CODCAJA NOT IN (SELECT ITEM FROM FNK_SPLIT1(@NOINCLUIRCAJA, ',', 0, NULL)))
				AND FPA.REQBCO = 1
			ORDER BY FPA.FORMAPAGO, FPA.DESCRIPCION, FCJ.FECHA;
		END

	
	IF @METODO = 'rpt_COBROSNR'
	BEGIN
		SELECT 
			@FECHAINI     = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
			@FECHAFIN     = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
			@ESTADO		  = JSON_VALUE(@PARAMETROS, '$.ESTADO'),
			@PROCEDENCIA  = JSON_VALUE(@PARAMETROS, '$.PROCEDENCIA'),
			@IDSEDE       = JSON_VALUE(@PARAMETROS, '$.IDSEDE'),
			@USUARIO_TFCJ = JSON_VALUE(@PARAMETROS, '$.USUARIO_TFCJ')

		
		SELECT 'OK' OK

		SELECT TFCJ.CNSFACJ, TFCJ.USUARIO, TFCJ.CLASE_FAC, TFCJ.FECHA, COALESCE(TFCJD.CONCEPTO, '') AS CONCEPTO , COALESCE(CPCJ.DESCRIPCION, '') AS DESC_CONCEPTO
			, TFCJ.VALORTOTAL, COALESCE(DBO.FNK_LIMPIATEXTO(TFCJ.NOMBRECLIENTE,' a-zA-Z 0-9'),'')NOMBRECLIENTE
			, USUSU.NOMBRE
			, CASE COALESCE(TFCJ.ESTADO, '')
				  WHEN 'A' THEN 'Anulado'
				  ELSE 'Pendiente'
				END AS ESTADO
		FROM TFCJ
		LEFT JOIN TFCJD ON TFCJD.CNSFACJ=TFCJ.CNSFACJ
		LEFT JOIN CPCJ ON CPCJ.CODIGO = TFCJD.CONCEPTO
		LEFT JOIN USUSU ON USUSU.USUARIO = TFCJ.USUARIO
		WHERE 
			CAST(TFCJ.FECHA AS DATE) >= @FECHAINI
        AND CAST(TFCJ.FECHA AS DATE) <= @FECHAFIN
        AND TFCJ.CLASE_FAC = 'COBRO'
        AND TFCJ.VALORTOTAL > 0
        AND (
            @ESTADO IS NULL OR @ESTADO = ''
            OR (@ESTADO = '0' AND COALESCE(TFCJ.ESTADO, '') <> 'A')
            OR (@ESTADO = 'A' AND TFCJ.ESTADO = 'A')
        )
        AND (@PROCEDENCIA IS NULL OR @PROCEDENCIA = '' OR TFCJ.PROCEDENCIA = @PROCEDENCIA)
        AND (@IDSEDE IS NULL OR @IDSEDE = '' OR TFCJ.IDSEDE = @IDSEDE)
        AND (@USUARIO_TFCJ IS NULL OR @USUARIO_TFCJ = '' OR TFCJ.USUARIO = @USUARIO_TFCJ)
	END

	IF @METODO = 'rpt_R_A'
	BEGIN
		SELECT 
			@FECHAINI = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
			@FECHAFIN = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
			@CODCAJA = JSON_VALUE(@PARAMETROS, '$.CODCAJA')
		
		SELECT 'OK' OK

		SELECT FCJ.CNSFACJ, FCJ.N_RECIBO, FCJ.FECHA, FCJ.FECHAANU, FCJ.DETALLEANULACION, CAU.DESCCAUSAL
		FROM FCJ
		LEFT JOIN CAU ON CAU.IDCAUSAL = FCJ.IDCAUSALANUL
		WHERE 
			CAST(FCJ.FECHA AS DATE)>=@FECHAINI AND CAST(FCJ.FECHA AS DATE)<=@FECHAFIN 
			AND FCJ.ESTADO = 'A'
			AND FCJ.CODCAJA=@CODCAJA
	END

	IF @METODO = 'rpt_TO_CON_SER'
	BEGIN
		SELECT 
			@CNSACJ = JSON_VALUE(@PARAMETROS, '$.CNSACJ')	

		SELECT 'OK' OK

		SELECT VWK_CJCPT.CNSFACJ, VWK_CJCPT.CONCEPTO, VWK_CJCPT.NOMCONCEPTO, VWK_CJCPT.IDAFILIADO, VWK_CJCPT.NOMAFILIADO, VWK_CJCPT.IDTERCERO, VWK_CJCPT.RAZONSOCIAL
		, VWK_CJCPT.VALORTOTAL, VWK_CJCPT.PREFIJO, VWK_CJCPT.NOM_PREFIJO
		FROM VWK_CJCPT
		WHERE VWK_CJCPT.CNSACJ=@CNSACJ
	END

	IF @METODO = 'TOTAL_ING_EGR_FCJ'
	BEGIN
		SELECT 
			@FECHAINI = NULLIF(JSON_VALUE(@PARAMETROS, '$.FECHAINI'), ''),
			@FECHAFIN = NULLIF(JSON_VALUE(@PARAMETROS, '$.FECHAFIN'), ''),
			@CODCAJA  = NULLIF(JSON_VALUE(@PARAMETROS, '$.CODCAJA'), ''),
			@CONCEPTO = JSON_VALUE(@PARAMETROS, '$.CONCEPTO');

		SELECT 'OK' OK;

		-- INGRESOS
		SELECT 
			SUM(FCJ.VALORTOTAL) AS TotalIngresos
		FROM FCJ 
			LEFT JOIN TER ON FCJ.IDTERCERO = TER.IDTERCERO
			LEFT JOIN PCJ ON FCJ.CODCAJA = PCJ.CODCAJA AND FCJ.CNSFACJ = PCJ.CNSFACJ
			INNER JOIN FPA ON PCJ.TIPOPAGO = FPA.FORMAPAGO
			LEFT JOIN FCJD ON FCJD.CODCAJA=FCJ.CODCAJA AND FCJD.CNSFACJ=FCJ.CNSFACJ AND FCJD.IDTERCERO=FCJ.IDTERCERO
		WHERE CLASE_FAC = 'COBRO'
		  AND FCJ.ESTADO = 'P'
		  AND COALESCE(CERRADA, 0) = 1 
		  AND COALESCE(DEAPERTURA, 0) = 0
		  AND (COALESCE(@CONCEPTO,'') = '' 
			OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO,',',0,NULL)))
		  AND (@FECHAINI IS NULL OR CAST(FCJ.FECHA AS DATE) >= CAST(@FECHAINI AS DATE))
		  AND (@FECHAFIN IS NULL OR CAST(FCJ.FECHA AS DATE) <= CAST(@FECHAFIN AS DATE))
		  AND (@CODCAJA IS NULL OR FCJ.CODCAJA = @CODCAJA)

		-- EGRESOS
		SELECT 
			SUM(CASE WHEN COALESCE(FPA.FISICO, 0) = 1 THEN PCJ.VALOR ELSE 0 END) AS TotalEgrEfectivo, 
			SUM(CASE WHEN COALESCE(FPA.FISICO, 0) = 0 AND COALESCE(PCJ.BANCO, '') <> ''  THEN PCJ.VALOR ELSE 0 END) AS TotalEgrBancos,
			SUM(CASE WHEN COALESCE(FPA.FISICO, 0) = 0 AND COALESCE(PCJ.BANCO, '') = ''  THEN PCJ.VALOR ELSE 0 END) AS TotalEgrOtrasFPA
		FROM FCJ 
			LEFT JOIN TER ON FCJ.IDTERCERO = TER.IDTERCERO
			LEFT JOIN PCJ ON FCJ.CODCAJA = PCJ.CODCAJA AND FCJ.CNSFACJ = PCJ.CNSFACJ
			INNER JOIN FPA ON PCJ.TIPOPAGO = FPA.FORMAPAGO
			LEFT JOIN FCJD ON FCJD.CODCAJA=FCJ.CODCAJA AND FCJD.CNSFACJ=FCJ.CNSFACJ AND FCJD.IDTERCERO=FCJ.IDTERCERO
		WHERE CLASE_FAC = 'PAGO'
		  AND FCJ.ESTADO = 'P'
		  AND COALESCE(CERRADA, 0) = 1 
		  AND COALESCE(DEAPERTURA, 0) = 0
		  AND (COALESCE(@CONCEPTO,'') = ''
			OR FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO,',',0,NULL)))
		  AND (@FECHAINI IS NULL OR CAST(FCJ.FECHA AS DATE) >= CAST(@FECHAINI AS DATE))
		  AND (@FECHAFIN IS NULL OR CAST(FCJ.FECHA AS DATE) <= CAST(@FECHAFIN AS DATE))
		  AND (@CODCAJA IS NULL OR FCJ.CODCAJA = @CODCAJA)
	END

	IF @METODO = 'SEGUIMIENTO_CONTABLE'
	BEGIN
		SELECT 
			@FECHAINI = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
			@FECHAFIN = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
			@CODCAJA   = NULLIF(JSON_VALUE(@PARAMETROS, '$.CODCAJA'), ''),
			@CONCEPTO = JSON_VALUE(@PARAMETROS, '$.CONCEPTO')

			SELECT TOP 1 @CNSFACJ=FCJ.CNSFACJ, @NROCOMPROBANTE = COALESCE(FCJ.NROCOMPROBANTE, '')
			FROM FCJ
			WHERE CONVERT(DATE, FCJ.FECHA) 
			  BETWEEN CONVERT(DATE, @FECHAINI) AND CONVERT(DATE, @FECHAFIN) 
		  AND (@CODCAJA IS NULL OR FCJ.CODCAJA = @CODCAJA)
		  AND (
				COALESCE(@CONCEPTO,'') = '' 
				OR EXISTS (
					SELECT 1 
					FROM FCJD 
					WHERE FCJD.CNSFACJ = FCJ.CNSFACJ 
					  AND FCJD.CODCAJA = FCJ.CODCAJA
					  AND FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO,',',0,NULL))
				)
			  );

		SELECT 'OK' AS OK;

		SELECT 
			FCJ.CODCAJA,
			FCJ.CNSFACJ, 
			COALESCE(FCJ.NROCOMPROBANTE, '') AS NROCOMPROBANTE, 
			FCJ.N_RECIBO,
			FCJ.FECHA, 
			CASE WHEN FCJ.CERRADA = 0 THEN 'NO' WHEN FCJ.CERRADA = 1 THEN 'SI' END AS CERRADA,
			FCJ.IDAFILIADO,
			COALESCE(TER.IDTERCERO,'') AS IDTERCERO, 
			COALESCE(TER.RAZONSOCIAL, '') AS RAZONSOCIAL, 
			COALESCE(FCJ.VALORTOTAL,0) AS VALORTOTAL, 
			FCJ.NOADMISION, 
			FCJ.CLASE_FAC, 
			COALESCE(TER.NIT, '') AS NIT,
			CASE 
				WHEN FCJ.DEAPERTURA = 1 THEN 'De apertura' 
				WHEN FCJ.DEAPERTURA IN (2,3) THEN 'Traslado'
				ELSE CASE 
					WHEN FCJ.ESTADO='A' THEN 'Anulado'
					WHEN FCJ.ESTADO='D' THEN 'Desecho'
					WHEN FCJ.ESTADO='P' THEN IIF(FCJ.CERRADA='1', 'Confirmado','Pendiente')							
				END 
			END AS ESTADO,
			AFI.NOMBREAFI, 
			AFI.DOCIDAFILIADO,
			MCP.TOTALDEBITO,
			MCP.TOTALCREDITO,
			MCP.ANULADO
		FROM FCJ
		LEFT JOIN TER ON TER.IDTERCERO = FCJ.IDTERCERO
		LEFT JOIN AFI ON AFI.IDAFILIADO = FCJ.IDAFILIADO
		LEFT JOIN FCJD ON FCJD.CODCAJA=FCJ.CODCAJA AND FCJD.CNSFACJ=FCJ.CNSFACJ AND FCJD.IDTERCERO=FCJ.IDTERCERO
		LEFT JOIN MCP ON MCP.REFERENCIA1=FCJ.CNSFACJ AND MCP.NROCOMPROBANTE=FCJ.NROCOMPROBANTE-- AND FCJD.IDTERCERO=FCJ.IDTERCERO

		WHERE (
			(@FECHAINI IS NULL OR @FECHAFIN IS NULL) 
			OR (CONVERT(DATE, FCJ.FECHA) BETWEEN CONVERT(DATE, @FECHAINI) AND CONVERT(DATE, @FECHAFIN))
		)
		  AND (@CODCAJA IS NULL OR FCJ.CODCAJA = @CODCAJA)
		  AND (
				COALESCE(@CONCEPTO,'') = '' 
				OR EXISTS (
					SELECT 1 
					FROM FCJD 
					WHERE FCJD.CNSFACJ = FCJ.CNSFACJ 
					  AND FCJD.CODCAJA = FCJ.CODCAJA
					  AND FCJD.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO,',',0,NULL))
				)
			  );

		SELECT 
			FCJD.CNSFACJ,
			FCJD.CODCAJA,
			FCJD.CONCEPTO,
			FCJD.CANTIDAD,
			FCJD.VALORUNITARIO,
			FCJD.VALORTOTAL,
			FCJD.VLRDESCUENTO,
			CPCJ.DESCRIPCION AS DESCRIPCION
		FROM FCJD
		LEFT JOIN CPCJ ON CPCJ.CODIGO = FCJD.CONCEPTO
		WHERE FCJD.CODCAJA = ISNULL(@CODCAJA, FCJD.CODCAJA)
		  AND EXISTS (
				SELECT 1 
				FROM FCJ
				WHERE FCJ.CNSFACJ = FCJD.CNSFACJ
				  AND FCJ.CODCAJA = FCJD.CODCAJA
				  AND CONVERT(DATE, FCJ.FECHA) BETWEEN CONVERT(DATE, @FECHAINI) AND CONVERT(DATE, @FECHAFIN)
				  AND (@CODCAJA IS NULL OR FCJ.CODCAJA = @CODCAJA)
				  AND (
						COALESCE(@CONCEPTO,'') = '' 
						OR EXISTS (
							SELECT 1 
							FROM FCJD FCJD2
							WHERE FCJD2.CNSFACJ = FCJ.CNSFACJ
							  AND FCJD2.CODCAJA = FCJ.CODCAJA
							  AND FCJD2.CONCEPTO IN (SELECT ITEM FROM FNK_SPLIT1(@CONCEPTO,',',0,NULL))
						)
				  )
		  );

		  SELECT MCH.NROCOMPROBANTE,MCH.CUENTA, CUE.NOMCUENTA, MCH.TIPO, CUE.TIPO AS TIPO_CUE, MCH.VALOR
			FROM MCH
			LEFT JOIN CUE ON CUE.CUENTA = MCH.CUENTA 
		  WHERE MCH.NROCOMPROBANTE=@NROCOMPROBANTE

		  SELECT PCJ.CNSFACJ, PCJ.TIPOPAGO, FPA.DESCRIPCION, PCJ.VALOR, PCJ.BANCO, PCJ.SUCURSAL, PCJ.CTA_BCO
			FROM PCJ
		    LEFT JOIN FPA ON FPA.FORMAPAGO = PCJ.TIPOPAGO
		  WHERE PCJ.CNSFACJ=@CNSFACJ AND (@CODCAJA IS NULL OR PCJ.CODCAJA = @CODCAJA)-- PCJ.CODCAJA=@CODCAJA
	END

	IF @METODO= 'GET_CUENTAS'
	BEGIN
		EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE, @PREFIJO = '@RPDX', @EXTRA = '', @DEFAULT = 8, @NVOCONSEC = @CNSRPDX OUTPUT

		SELECT 'OK' OK, @CNSRPDX CNSRPDX, MIN(CUENTA) CUENTAINI, MAX(CUENTA) CUENTAFIN FROM CAJ
	END

	IF @METODO = 'LIMPIA_RPDX'
	BEGIN
		DELETE FROM RPDX WHERE CNS = JSON_VALUE(@PARAMETROS, '$.CNSRPDX')
		SELECT 'OK' OK
	END

	IF @METODO = 'AUX_CAJA'
	BEGIN
		BEGIN TRY
			SELECT	
				@FECHAINI        = JSON_VALUE(@PARAMETROS, '$.FECHAINI'), 
				@FECHAFIN        = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'), 
				@CUENTAINI       = JSON_VALUE(@PARAMETROS, '$.CUENTAINI'), 
				@CUENTAFIN       = JSON_VALUE(@PARAMETROS, '$.CUENTAFIN'),
				@CNSRPDX       = JSON_VALUE(@PARAMETROS, '$.CNSRPDX')

			IF @CNSRPDX IS NULL
				EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE, @PREFIJO = '@RPDX', @EXTRA = '', @DEFAULT = 8, @NVOCONSEC = @CNSRPDX OUTPUT


			DELETE FROM RPDX WHERE CNS = @CNSRPDX

			EXEC DBO.NC_SPK_GEN_LIBROAUXILIAR @FECHAINI,@FECHAFIN,'','',@CUENTAINI,@CUENTAFIN
				,'','','',@CNSRPDX,0

		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' AS OK, @CNSRPDX AS CNSRPDX;
	END

	IF @METODO = 'rpt_FLUJO_CAJ'
	BEGIN
		SELECT 
			@FECHAINI   = JSON_VALUE(@PARAMETROS, '$.FECHAINI'),
			@FECHAFIN   = JSON_VALUE(@PARAMETROS, '$.FECHAFIN'),
			@CODCAJA    = JSON_VALUE(@PARAMETROS, '$.CODCAJA'),
			@FORMAPAGO  = JSON_VALUE(@PARAMETROS, '$.FORMAPAGO');

		SELECT 'OK' AS OK;

		SELECT 
			ACJ.CNSACJ,
			ACJ.CODCAJERO,
			CJR.DESCRIPCION AS NOMBRE_CAJERO,
			ACJ.FECHAAPERTURA,
			ACJ.FECHACIERRE,
			CASE WHEN ACJ.ABIERTA = 1 THEN 'Abierta' ELSE 'Cerrada' END AS ESTADO,
			DETALLES = (SELECT 
				  FPA.FORMAPAGO,
				  FPA.DESCRIPCION,
				  SUM(COALESCE(ACJD.SALDO, 0)) AS SALDOINICIAL,
				  SUM(CASE WHEN FCJ.CLASE_FAC = 'COBRO' THEN PCJ.VALOR ELSE 0 END) AS INGRESOS,
				  SUM(CASE WHEN FCJ.CLASE_FAC = 'PAGO' THEN PCJ.VALOR ELSE 0 END) AS EGRESOS
				FROM FCJ
					INNER JOIN PCJ ON PCJ.CNSFACJ = FCJ.CNSFACJ AND PCJ.CODCAJA = FCJ.CODCAJA
					LEFT JOIN ACJD ON ACJD.CNSACJ = ACJ.CNSACJ AND ACJD.FORMAPAGO = PCJ.TIPOPAGO AND ACJD.TIPO = 'Saldo Inicial'
					LEFT JOIN FPA ON FPA.FORMAPAGO = PCJ.TIPOPAGO		
				WHERE FCJ.CODCAJA=ACJ.CODCAJA AND FCJ.CNSACJ=ACJ.CNSACJ					
					AND (COALESCE(@FORMAPAGO, '') = '' OR PCJ.TIPOPAGO = @FORMAPAGO)
					AND ISNULL(FCJ.DEAPERTURA,0)<>1
					AND FCJ.CERRADA = 1 AND ISNULL(FCJ.ESTADO,'')<>'A'
				GROUP BY FPA.FORMAPAGO, FPA.DESCRIPCION
				FOR JSON PATH
				)
		FROM ACJ
			LEFT JOIN CJR ON CJR.CODCAJERO = ACJ.CODCAJERO				
		WHERE 
			ACJ.CODCAJA = @CODCAJA
			AND (
				(ACJ.FECHACIERRE >= @FECHAINI AND ACJ.FECHACIERRE < DATEADD(DAY, 1, @FECHAFIN) AND ACJ.ABIERTA = 0)
				OR ACJ.FECHACIERRE IS NULL
			)
			AND EXISTS(SELECT 1 FROM FCJ WHERE FCJ.CNSACJ=ACJ.CNSACJ AND ISNULL(FCJ.DEAPERTURA,0)<>1
						AND FCJ.CERRADA = 1 AND ISNULL(FCJ.ESTADO,'')<>'A'
						)
		ORDER BY ACJ.FECHAAPERTURA, ACJ.CNSACJ
	END
END

