CREATE OR ALTER PROCEDURE DBO.SPQ_CONTAB_IACT @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @SEDE VARCHAR(5), @PROCESO VARCHAR(20), @COMPANIA VARCHAR(2)
DECLARE @SYS_COMPUTERNAME VARCHAR(254)
DECLARE @COM VARCHAR(6), @NOREFERENCIA VARCHAR(20), @ANO VARCHAR(4), @MES INT, @IDMODELOCONT VARCHAR(2)
DECLARE @IDPLAN VARCHAR(6), @TIPOTERCONTABLE VARCHAR(10), @PREFIJO_USCXS VARCHAR(10), @FECHATRA DATETIME, @IDEVENTO VARCHAR(20)
DECLARE @TIPO VARCHAR(20), @CUENTA_ACT VARCHAR(20), @IDTERCERO_CIA VARCHAR(20), @IDACTIVO VARCHAR(20), @CCOSTO_IACT VARCHAR(20)
DECLARE @IDAREA_IACT VARCHAR(20), @IDITAR VARCHAR(20), @IDTIPOACTIVO VARCHAR(20), @CODUNG VARCHAR(5), @CODPRG VARCHAR(20)
DECLARE @VALOR DECIMAL(14, 2), @DEP_ACUMULADA DECIMAL(14, 2), @AJU_ACUMULADO DECIMAL(14, 2), @AJU_DEPACUMULADA DECIMAL(14, 2)
DECLARE @BAJA SMALLINT, @PRECIOCOMERCIAL DECIMAL(14, 2), @CNSIACTH VARCHAR(20), @NROCOMPROBANTE VARCHAR(20)

BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	IF @METODO = 'GENERAR'
	BEGIN
		SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME
		FROM USUSU
		WHERE USUARIO = @USUARIO

		SELECT @SEDE = IDSEDE, @COMPANIA = COMPANIA
		FROM UBEQ
		WHERE SYS_ComputerName = @SYS_COMPUTERNAME

		BEGIN TRY
			SELECT @CNSIACTH = CNSIACTH, @NROCOMPROBANTE = NROCOMPROBANTE
			FROM OPENJSON(@PARAMETROS) WITH (CNSIACTH VARCHAR(20) '$.CNSIACTH', NROCOMPROBANTE VARCHAR(20) '$.NROCOMPROBANTE')

			SELECT *
			INTO #TEMPORAL
			FROM IACTH
			WHERE CNSIACTH = @CNSIACTH

			SELECT @IDTERCERO_CIA = DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')

			SELECT @ANO = YEAR(#TEMPORAL.FECHAEVENTO), @MES = MONTH(#TEMPORAL.FECHAEVENTO), @FECHATRA = #TEMPORAL.FECHAEVENTO, @IDEVENTO = #TEMPORAL.IDEVENTO, 
				@TIPO = IACTE.TIPO, @CUENTA_ACT = IACT.CUENTA, @IDACTIVO = #TEMPORAL.IDACTIVO, @CCOSTO_IACT = IACT.CCOSTO, @IDAREA_IACT = IACT.IDAREA, @IDITAR = IACT.
				IDITAR, @IDTIPOACTIVO = IACT.IDTIPOACTIVO, @CODUNG = IACT.CODUNG, @CODPRG = IACT.CODPRG, @VALOR = ISNULL(IACT.PRECIOCOMPRA, 0), @DEP_ACUMULADA = 
				ISNULL(IACT.DEPACUMHISTORICA, 0), @AJU_ACUMULADO = ISNULL(IACT.AJUSTEACUMULADO, 0), @AJU_DEPACUMULADA = ISNULL(IACT.AJUSTEDEPACUMULADA, 0), 
				@BAJA = ISNULL(IACTE.BAJA, 0), @PRECIOCOMERCIAL = IACT.PRECIOCOMERCIAL
			FROM #TEMPORAL
			INNER JOIN IACTE ON #TEMPORAL.IDEVENTO = IACTE.IDEVENTO
			INNER JOIN IACT ON #TEMPORAL.IDACTIVO = IACT.IDACTIVO

			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'EL PERIODO CONTABLE NO EXISTE'
			WHERE NOT EXISTS (
					SELECT COMPANIA, ANO, MES
					FROM PRI
					WHERE COMPANIA = @COMPANIA AND ANO = @ANO AND MES = @MES
					)

			IF (
					SELECT COUNT(*)
					FROM @TBLERRORES
					) <= 0
			BEGIN
				SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')

				IF @NROCOMPROBANTE = '' OR LEFT(@NROCOMPROBANTE, 2) = 'IX'
				BEGIN
					IF LEFT(@NROCOMPROBANTE, 2) = 'IX'
					BEGIN
						SET @COM = 'IX'
					END
					ELSE
					BEGIN
						--   SET @NROCOMPROBANTE=SPACE(20)
						--   EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT   
						--   SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - LEN(@NROCOMPROBANTE))+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0)
						/***********************************************/
						PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE, '') -- AGREGADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD

						IF ISNULL(@NROCOMPROBANTE, '') = '' -- AGREGADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
						BEGIN
							SET @NROCOMPROBANTE = SPACE(20)

							EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@MCP', @NROCOMPROBANTE OUTPUT

							PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE, '') -- AGREGADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD

							SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE 
											WHEN LEN(@NROCOMPROBANTE) > 8
												THEN 8
											ELSE LEN(@NROCOMPROBANTE)
											END) + LTRIM(RTRIM(@NROCOMPROBANTE)), SPACE(1), 0) -- AGREGADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD

							PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE, '') -- AGREGADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
						END

						/*****************************************************/
						--SE REVISA SI LOS COMPROBANTES SE TOMAN DE ACUERDO A SEDE
						IF (
								SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')
								) = 'SI'
						BEGIN
							SELECT @COM = RTRIM(LTRIM(COMMS.COMPROBANTE))
							FROM COMMS
							INNER JOIN #TEMPORAL ON COMMS.TIPO = @IDEVENTO
							WHERE IDSEDE = @SEDE AND COMMS.CLASE = 'IACT'
						END
						ELSE
						BEGIN
							SELECT @COM = COMPROBANTE
							FROM IACTE
							WHERE IDEVENTO = @IDEVENTO
						END

						IF @COM = '' OR @COM IS NULL
							SET @COM = DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT')

						IF @COM = '' OR @COM IS NULL
							SET @COM = 'IX'
					END

					SET @PREFIJO_USCXS = '@COM' + @COM
					SET @NOREFERENCIA = SPACE(20)

					EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, @PREFIJO_USCXS, @NOREFERENCIA OUTPUT

					SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA)) + LTRIM(RTRIM(@NOREFERENCIA)), SPACE(1), 0)

					PRINT 'Nuevo Comprobante: ' + @COM + ' ' + @NOREFERENCIA
					PRINT 'Comprobanrte Contable (MCP)'

					INSERT INTO MCPE (
						NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, 
						USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO, COMPROBANTE, IDTERCERO
						)
					SELECT @NROCOMPROBANTE, @COMPANIA, 'IACT', @NOREFERENCIA, @ANO, @MES, @FECHATRA, 0, 0, CNSIACTH, IDEVENTO, @USUARIO, DBO.FNK_FECHA_SIN_MLS(
							GETDATE()), NULL, OBSERVACION, @SEDE, 0, @COM, @IDTERCERO_CIA
					FROM #TEMPORAL
				END
				ELSE
				BEGIN
					IF (
							SELECT COUNT(*)
							FROM MCP
							WHERE NROCOMPROBANTE = @NROCOMPROBANTE
							) > 0
					BEGIN
						INSERT INTO MCPE (
							COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, 
							REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, 
							RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
							)
						SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, 
							REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, 
							RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
						FROM MCP
						WHERE NROCOMPROBANTE = @NROCOMPROBANTE

						--se borran de mcp, mch
						DELETE MCH
						WHERE NROCOMPROBANTE = @NROCOMPROBANTE

						DELETE MCP
						WHERE NROCOMPROBANTE = @NROCOMPROBANTE
					END
					ELSE
					BEGIN
						DELETE MCHE
						WHERE NROCOMPROBANTE = @NROCOMPROBANTE
					END
				END

				IF @TIPO = 'Entrada' --Entradas de Activos
				BEGIN
					PRINT 'Contabilizando Entradas'
					PRINT ' -Insertando Registro MCH. DB...'

					INSERT INTO MCHE (
						NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, 
						PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
						)
					SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', @CUENTA_ACT, @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, #TEMPORAL.VALOR, #TEMPORAL.
						IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA, 'S', 1
						, 'MOV_ENT_ACT', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
					FROM #TEMPORAL
					WHERE #TEMPORAL.VALOR <> 0

					PRINT ' -Insertando Registro MCH. CR...'

					INSERT INTO MCHE (
						NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, 
						PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
						)
					SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'MOV_ACTIVOS', 'CR', #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA, 
							#TEMPORAL.CCOSTO, 'S', @IDTIPOACTIVO), @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, #TEMPORAL.VALOR, #TEMPORAL.
						IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA, 'S', 1
						, 'MOV_ENT_ACT', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
					FROM #TEMPORAL
					WHERE #TEMPORAL.VALOR <> 0
				END
				ELSE IF @TIPO = 'Salida' -- Salidad de Activos 
				BEGIN
					PRINT 'Contabilizando Salidas'

					IF @BAJA = 1
					BEGIN
						-- Baja Depreciación Acumulada
						IF @DEP_ACUMULADA > 0
						BEGIN
							PRINT ' -Insertando Registro MCH. DB Baja Depreciación Acumulada...'

							INSERT INTO MCHE (
								NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO
								, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
								)
							SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'DEPRECIACION', 'CR', @IDTIPOACTIVO, #TEMPORAL.IDAREA
									, #TEMPORAL.CCOSTO, 'S', #TEMPORAL.IDACTIVO), @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, @DEP_ACUMULADA, 
								#TEMPORAL.IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #TEMPORAL.IDEVENTO, 
								#TEMPORAL.IDAREA, 'S', 1, 'DEP_BAJ_ACUMULADA', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
							FROM #TEMPORAL
						END

						-- Baja Ajuste Depreciación Acumulada
						IF @AJU_DEPACUMULADA > 0
						BEGIN
							PRINT ' -Insertando Registro MCH. DB Baja de Ajuste Depreciación Acumulada...'

							INSERT INTO MCHE (
								NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO
								, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
								)
							SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'DEPRECIACION_AJI', 'CR', #TEMPORAL.IDEVENTO, 
									#TEMPORAL.IDAREA, #TEMPORAL.CCOSTO, 'S', @IDTIPOACTIVO), @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, 
								@AJU_DEPACUMULADA, #TEMPORAL.IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 
								#TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA, 'S', 1, 'V', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
							FROM #TEMPORAL
						END

						PRINT ' -Insertando Registro MCH DB para Gasto por Baja de Activo...'

						-- Gasto por Baja de Activo
						INSERT INTO MCHE (
							NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, 
							FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
							)
						SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'MOV_ACTIVOS', 'DB', #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA
								, #TEMPORAL.CCOSTO, 'S', @IDTIPOACTIVO), @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, abs(@PRECIOCOMERCIAL) + 
							COALESCE(@AJU_ACUMULADO, 0) - COALESCE(@DEP_ACUMULADA, 0) - COALESCE(@AJU_DEPACUMULADA, 0), #TEMPORAL.IDEVENTO, #TEMPORAL.CNSIACTH, 
							@IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA, 'S', 1, 'IACT_BAJ_GASTO', 
							'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
						FROM #TEMPORAL

						-- Baja del Activo Fijo
						PRINT ' -Insertando Registro MCH. CR Baja del Activo Fijo...'

						INSERT INTO MCHE (
							NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, 
							FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
							)
						SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', @CUENTA_ACT, @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, abs(COALESCE(
									@PRECIOCOMERCIAL, 0)), #TEMPORAL.IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()
							), #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA, 'S', 1, 'IACT_BAJA_ACT', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
						FROM #TEMPORAL
						WHERE #TEMPORAL.VALOR <> 0

						-- Baja del Ajuste por Inflación
						IF @AJU_ACUMULADO > 0
						BEGIN
							PRINT ' -Insertando Registro MCH. CR Baja Ajuste Acumulado del Activo...'

							INSERT INTO MCHE (
								NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO
								, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
								)
							SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'INFLACION', 'DB', #TEMPORAL.IDEVENTO, #TEMPORAL.
									IDAREA, #TEMPORAL.CCOSTO, 'S', @IDTIPOACTIVO), @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, @AJU_ACUMULADO, 
								#TEMPORAL.IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #TEMPORAL.IDEVENTO, 
								#TEMPORAL.IDAREA, 'S', 1, 'IACT_BAJA_AJI', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
							FROM #TEMPORAL
						END
					END
					ELSE
					BEGIN
						PRINT ' -Insertando Registro MCH. DB...'

						INSERT INTO MCHE (
							NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, 
							FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
							)
						SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'MOV_ACTIVOS', 'DB', #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA
								, #TEMPORAL.CCOSTO, 'S', @IDTIPOACTIVO), @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, #TEMPORAL.VALOR, #TEMPORAL.
							IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA, 
							'S', 1, 'MOV_ENT_ACT', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
						FROM #TEMPORAL
						WHERE #TEMPORAL.VALOR <> 0

						PRINT ' -Insertando Registro MCH. CR...'

						INSERT INTO MCHE (
							NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, 
							FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
							)
						SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', @CUENTA_ACT, @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, #TEMPORAL.VALOR, 
							#TEMPORAL.IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #TEMPORAL.IDEVENTO, 
							#TEMPORAL.IDAREA, 'S', 1, 'MOV_ENT_ACT', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
						FROM #TEMPORAL
						WHERE #TEMPORAL.VALOR <> 0
					END
				END
				ELSE IF @TIPO = 'Traslado' -- Traslado de Activos 
				BEGIN
					PRINT 'Contabilizando Traslados'
					PRINT ' -Insertando Registro MCH. DB...'

					INSERT INTO MCHE (
						NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, 
						PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
						)
					SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'MOV_ACTIVOS', 'DB', #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA, 
							#TEMPORAL.CCOSTO, 'S', @IDTIPOACTIVO), @IDTERCERO_CIA, #TEMPORAL.CCOSTO, #TEMPORAL.OBSERVACION, #TEMPORAL.VALOR, #TEMPORAL.
						IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #TEMPORAL.IDEVENTO, #TEMPORAL.IDAREA, 'S', 1
						, 'MOV_TRASL_ACT', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
					FROM #TEMPORAL
					WHERE #TEMPORAL.VALOR <> 0

					PRINT ' -Insertando Registro MCH. CR...'

					INSERT INTO MCHE (
						NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, 
						PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
						)
					SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', @CUENTA_ACT, @IDTERCERO_CIA, @CCOSTO_IACT, #TEMPORAL.OBSERVACION, #TEMPORAL.VALOR, #TEMPORAL.
						IDEVENTO, #TEMPORAL.CNSIACTH, @IDACTIVO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), #TEMPORAL.IDEVENTO, @IDAREA_IACT, 'S', 1, 
						'MOV_TRASL_ACT', 'Movimiento', 'IACT', @CNSIACTH, @CODUNG, @CODPRG
					FROM #TEMPORAL
					WHERE #TEMPORAL.VALOR <> 0
				END
				ELSE
					PRINT 'No Existe el TIPO de Evento. ' + ISNULL(@TIPO, '')

				IF LEFT(@NROCOMPROBANTE, 2) <> 'IX'
				BEGIN
					PRINT 'Poniendo Estado de CONTABILIZADA en 1a Tabla IACTH'

					UPDATE IACTH
					SET CONTABILIZADA = 1, MARCACONT = 0, NROCOMPROBANTE = @NROCOMPROBANTE, APLICADA = 1
					WHERE IACTH.CNSIACTH = @CNSIACTH
				END

				EXEC SPQ_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME

				EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE, @COM, ''

				DROP TABLE #TEMPORAL
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK

		RETURN
	END
END


