CREATE OR ALTER PROCEDURE DBO.SPQ_FCONCI_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy

DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
	
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@PROCESO VARCHAR(20)               ,@ESTADO VARCHAR(20)             ,@FECHACONC DATETIME
      ,@FECHADIG DATETIME                 ,@IDTERCERO VARCHAR(20)          ,@CNSEXTERNO INT
      ,@VALOR DECIMAL(14,2)               ,@FECHAPAGCONC DATETIME         ,@OBSERVACION VARCHAR(255)
      ,@IDFCONCI VARCHAR(20)              ,@PORCENTAJE DECIMAL(14,2)      ,@FUNCIONARIOADMIN VARCHAR(120)
      ,@TIPO VARCHAR(20)                  ,@CONDCONCEPTO VARCHAR(20)      ,@N_FACTURA VARCHAR(20)
      ,@CNSCXC VARCHAR(20)                ,@ITEM_FCXCDV INT               ,@CNSGLO VARCHAR(20)
      ,@SALDONETO DECIMAL(14,2)           ,@VLRRECUPERAR DECIMAL(14,2)    ,@VLRACEPTADO DECIMAL(14,2)
      ,@CONCEPTO VARCHAR(24)              ,@CNSFCGLO VARCHAR(20)          ,@ITEM_FCONCID INT	      
	  ,@ITEM INT						  ,@CNSNOTADB VARCHAR(20)		  ,@CNSFNOT VARCHAR(20)
	  -- Variables para métodos adicionales
	  ,@VLRACEPTADO_ITEM DECIMAL(18,2)   ,@CNSNOTADB_ITEM VARCHAR(20)    ,@ESTADO_ITEM VARCHAR(20)
	  ,@NUEVO_CONSECUTIVO VARCHAR(20)    ,@PREFIJO VARCHAR(10)
	  ,@CONTADOR INT = 0
	  ,@FECHACONC_CONFIRMAR DATE         ,@PERIODO_CERRADO BIT = 0
	  ,@ESTADO_FINAL VARCHAR(20)         ,@FNOT_FECHACONCILIA VARCHAR(20)
	  ,@ITEM_ACTUAL INT                  ,@ITEM_CREDITO INT

BEGIN

	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

	SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),  @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())   
	FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
	WHERE USUSU.USUARIO=@USUARIO

-- MÉTODO 1:CRUD CONCI
	IF @METODO='CRUD_FCONCI'     
	BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @PROCESO=PROCESO,@IDFCONCI=IDFCONCI,@ESTADO=ESTADO,@FECHACONC=CONVERT(DATE,FECHACONC),@FECHADIG=CONVERT(DATE,FECHADIG),
             @IDTERCERO=IDTERCERO,@CNSEXTERNO=CNSEXTERNO,@VALOR=VALOR,@FECHAPAGCONC=CONVERT(DATE,FECHAPAGCONC),
             @OBSERVACION=OBSERVACION,@FUNCIONARIOADMIN=FUNCIONARIOADMIN,@TIPO=TIPO,@PORCENTAJE=PORCENTAJE   
      FROM   OPENJSON (@DATOS)
      WITH   ( 
         PROCESO VARCHAR(20)             '$.PROCESO',
         IDFCONCI  VARCHAR(20)           '$.IDFCONCI',
         ESTADO VARCHAR(20)              '$.ESTADO',
         FECHACONC VARCHAR(20)           '$.FECHACONC',
         FECHADIG VARCHAR(20)            '$.FECHADIG',
         IDTERCERO VARCHAR(20)           '$.IDTERCERO',
         CNSEXTERNO INT				     '$.CNSEXTERNO',
         VALOR DECIMAL(14,2)             '$.VALOR',
         FECHAPAGCONC VARCHAR(20)        '$.FECHAPAGCONC',
         OBSERVACION VARCHAR(255)        '$.OBSERVACION',
         FUNCIONARIOADMIN  VARCHAR(120)   '$.FUNCIONARIOADMIN',
         TIPO VARCHAR(20)                '$.TIPO.value',
         PORCENTAJE DECIMAL(7,2)          '$.PORCENTAJE'
      ) 

	IF @PROCESO='Borrar'
	BEGIN
        IF EXISTS(SELECT 1 FROM FCONCID WHERE IDFCONCI = @IDFCONCI)
		BEGIN 
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'La conciliación tiene detalles y no puede eliminarse.';
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END

        DELETE FROM FCONCI WHERE IDFCONCI = @IDFCONCI;
        SELECT 'OK' AS OK;
        RETURN;
    END

      IF @PROCESO='Nueva'
      BEGIN
         BEGIN TRY           
               SET @IDFCONCI=''
		       EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@CONCI', @IDFCONCI OUTPUT  
		       SET @IDFCONCI = @IDSEDE + REPLACE(SPACE(8 - LEN(@IDFCONCI))+LTRIM(RTRIM(@IDFCONCI)),SPACE(1),0)
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
                 SELECT 'KO' OK, ERROR FROM @TBLERRORES
                 RETURN
         END CATCH

         INSERT INTO FCONCI(IDFCONCI, IDTERCERO, FECHACONC, CNSEXTERNO, USUARIO, FECHADIG, ESTADO, VALOR, FUNCIONARIOADMIN, OBSERVACION, FECHA_PAGCONC, TIPO, PORCENTAJE, CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA,  IDSEDE)
         SELECT @IDFCONCI, @IDTERCERO, @FECHACONC, @CNSEXTERNO, @USUARIO, @FECHADIG, 'Ingresada', @VALOR, @FUNCIONARIOADMIN,@OBSERVACION,@FECHAPAGCONC, @TIPO, @PORCENTAJE, 0, NULL, 'CXC', @IDSEDE
      END

      IF @PROCESO='Editar'
      BEGIN
         IF EXISTS(SELECT 1 FROM FCONCI WHERE IDFCONCI=@IDFCONCI AND ESTADO='Ingresada')
         BEGIN
            UPDATE FCONCI SET IDTERCERO=@IDTERCERO, FECHACONC=@FECHACONC, CNSEXTERNO=@CNSEXTERNO,VALOR=@VALOR,FUNCIONARIOADMIN=@FUNCIONARIOADMIN,
                   OBSERVACION=@OBSERVACION, FECHA_PAGCONC=@FECHAPAGCONC, TIPO=@TIPO, PORCENTAJE=@PORCENTAJE
            WHERE IDFCONCI=@IDFCONCI
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro Conciliación o ya Esta cerrada, Verifique e intente de nuevo '
         END
      END

      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK 
      RETURN 
   END    

-- MÉTODO 2:CRUD CONCID
	IF @METODO='CRUD_FCONCID'     
	BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @PROCESO=PROCESO, @ESTADO=ESTADO, @IDFCONCI=IDFCONCI, @CONDCONCEPTO=CONDCONCEPTO, @N_FACTURA=N_FACTURA, @CNSCXC=CNSCXC,
         @ITEM_FCXCDV=ITEM_FCXCDV, @TIPO=TIPO, @CNSGLO=CNSGLO, @SALDONETO=SALDONETO,@VLRRECUPERAR=VLRRECUPERAR,@VLRACEPTADO=VLRACEPTADO,
         @CNSFCGLO=CNSFCGLO,@OBSERVACION=OBSERVACION,@ITEM_FCONCID=ITEM_FCONCID
      FROM   OPENJSON (@DATOS)
      WITH   (  
         PROCESO VARCHAR(20)        '$.PROCESO',
         ESTADO VARCHAR(20)         '$.ESTADO',
         IDFCONCI VARCHAR(20)       '$.IDFCONCI',
         ITEM_FCONCID  INT          '$.ITEM_FCONCID',
         CONDCONCEPTO VARCHAR(20)   '$.CONDCONCEPTO',
         N_FACTURA VARCHAR(20)      '$.N_FACTURA',
         CNSCXC VARCHAR(20)         '$.CNSCXC',
         ITEM_FCXCDV INT            '$.ITEM_FCXCDV',
         TIPO VARCHAR(20)           '$.TIPO',
         CNSGLO VARCHAR(20)         '$.CNSGLO',
         SALDONETO DECIMAL(14,2)    '$.SALDONETO',
         VLRRECUPERAR DECIMAL(14,2) '$.VLRRECUPERAR',
         VLRACEPTADO DECIMAL(14,2)  '$.VLRACEPTADO',
         CNSFCGLO VARCHAR(20)       '$.CNSFCGLO',
		 CNSNOTADB VARCHAR(20)      '$.CNSNOTADB',
         OBSERVACION VARCHAR(255)   '$.OBSERVACION'    
       )    

       IF EXISTS(SELECT 1 FROM FCONCI WHERE IDFCONCI=@IDFCONCI AND ESTADO='Ingresada')
       BEGIN
          IF @PROCESO='Nueva'
          BEGIN
             IF NOT EXISTS(SELECT 1 FROM FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCXCDV=@ITEM_FCXCDV)
             BEGIN
                SELECT @ITEM_FCONCID=COALESCE(MAX(ITEM_FCONCID),0)+1 FROM FCONCID WHERE IDFCONCI=@IDFCONCI

                INSERT INTO FCONCID(IDFCONCI, ITEM_FCONCID, CNSCXC, N_FACTURA, ITEM_FCXCDV, TIPO, CNSGLO, SALDONETO, VLRACEPTADO, VLRRECUPERAR, 
                                    CNSFNOT, CLASE, ESTADO, OBSERVACION, CONDCONCEPTO, CNSFCGLO, CNSNOTADB, NROCOMPROBANTE_A )
                SELECT @IDFCONCI, @ITEM_FCONCID, @CNSCXC, @N_FACTURA, @ITEM_FCXCDV, @TIPO, @CNSGLO, @SALDONETO, @VLRACEPTADO, @VLRRECUPERAR, 
                       @CNSFNOT, 'C', @ESTADO, @OBSERVACION, @CONDCONCEPTO, @CNSFCGLO, @CNSNOTADB, NULL 
             END
             ELSE
             BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT 'Ya existe este item en esta conciliación. Verifique e intente de nuevo'
             END
          END

          IF @PROCESO='Editar'
          BEGIN
             IF EXISTS(SELECT 1 FROM FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCXCDV=@ITEM_FCXCDV  AND ITEM_FCONCID=@ITEM_FCONCID)
             BEGIN
               UPDATE FCONCID SET VLRACEPTADO=@VLRACEPTADO,VLRRECUPERAR=@VLRRECUPERAR,CONDCONCEPTO=@CONDCONCEPTO,CNSFCGLO=@CNSFCGLO,OBSERVACION=@OBSERVACION
               WHERE IDFCONCI=@IDFCONCI
               AND ITEM_FCXCDV=@ITEM_FCXCDV
               AND ITEM_FCONCID=@ITEM_FCONCID
             END
             ELSE
             BEGIN
                DELETE FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCONCID=@ITEM_FCONCID

                SELECT @ITEM_FCONCID=COALESCE(MAX(ITEM_FCONCID),0)+1 FROM FCONCID WHERE IDFCONCI=@IDFCONCI

                INSERT INTO FCONCID(IDFCONCI, ITEM_FCONCID, CNSCXC, N_FACTURA, ITEM_FCXCDV, TIPO, CNSGLO, SALDONETO, VLRACEPTADO, VLRRECUPERAR, 
                                    CNSFNOT, CLASE, ESTADO, OBSERVACION, CONDCONCEPTO, CNSFCGLO, CNSNOTADB, NROCOMPROBANTE_A )
                SELECT @IDFCONCI, @ITEM_FCONCID, @CNSCXC, @N_FACTURA, @ITEM_FCXCDV, @TIPO, @CNSGLO, @SALDONETO, @VLRACEPTADO, @VLRRECUPERAR, 
                       @CNSFNOT, 'C', @ESTADO, @OBSERVACION, @CONDCONCEPTO, @CNSFCGLO, @CNSNOTADB, NULL 
             END
          END

          IF @PROCESO='Borrar'
          BEGIN
              IF EXISTS(SELECT 1 FROM FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCXCDV=@ITEM_FCXCDV  AND ITEM_FCONCID=@ITEM_FCONCID)
              BEGIN
                  DELETE FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCXCDV=@ITEM_FCXCDV  AND ITEM_FCONCID=@ITEM_FCONCID
              END
              ELSE
              BEGIN
                 INSERT INTO @TBLERRORES(ERROR)
                 SELECT 'Item no encontrado. Varifique los datos e intente de nuevo '
              END
          END
       END
       ELSE
       BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Conciliación no Encontrada o ya fue cerrada, Verifique e intente de nuevo '
       END

       IF(SELECT COUNT(*) FROM @TBLERRORES)>0
       BEGIN
          SELECT 'KO' OK, ERROR FROM @TBLERRORES
          RETURN
       END

       SELECT 'OK' OK 
       RETURN 
   END  

-- MÉTODO 3: LIMPIAR_FCONCID
	IF @METODO = 'LIMPIAR_FCONCID'
	BEGIN  
		SELECT @IDFCONCI = IDFCONCI
		FROM OPENJSON(@PARAMETROS)
		WITH (
			IDFCONCI VARCHAR(20) '$.IDFCONCI'
		)
    
		IF @IDFCONCI IS NULL OR @IDFCONCI = ''
		BEGIN
			SELECT 'KO' AS OK, 'IDFCONCI es requerido' AS ERROR
			RETURN
		END
    
		DELETE FROM FCONCID 
		WHERE IDFCONCI = @IDFCONCI 
		  AND ESTADO = 'Ingresada'
    
		SELECT 'OK' AS OK, 'Registros eliminados correctamente' AS MENSAJE
		RETURN
	END

-- MÉTODO 4: CONFIRMAR_CONCILIACION
	IF @METODO = 'CONFIRMAR_CONCILIACION'
	BEGIN
		SELECT @IDFCONCI = IDFCONCI
		FROM OPENJSON(@PARAMETROS)
		WITH (
			IDFCONCI VARCHAR(20) '$.IDFCONCI'
		)
		
		IF @IDFCONCI IS NULL OR @IDFCONCI = ''
		BEGIN
			SELECT 'KO' AS OK, 'IDFCONCI es requerido' AS ERROR
			RETURN
		END
    
		SELECT @FECHACONC = FECHACONC
		FROM FCONCI
		WHERE IDFCONCI = @IDFCONCI
    
		IF @FECHACONC IS NULL
		BEGIN
			SELECT 'KO' AS OK, 'Conciliación no encontrada' AS ERROR
			RETURN
		END
    
		BEGIN TRY
			SELECT @FNOT_FECHACONCILIA = DBO.FNK_VALORVARIABLE('FNOT_FECHACONCILIA')
			IF @FNOT_FECHACONCILIA = 'CONCILIACION'
			BEGIN
				SELECT @PERIODO_CERRADO = COALESCE(CERRADO, 0)
				FROM PRI
				WHERE FECHA_INI <= @FECHACONC
				  AND FECHA_FIN >= @FECHACONC
            
				IF @PERIODO_CERRADO = 1
				BEGIN
					SELECT 'KO' AS OK, 
						'Tiene Configurado Como Fecha de la Nota Crédito Generada en la Conciliación ' + CHAR(13) + CHAR(10) + 
						'La Fecha de Conciliación y El Período Esta Cerrado.' AS ERROR
					RETURN
				END
			END
        
			DECLARE cursor_confirmar CURSOR FOR
			SELECT ITEM_FCONCID, VLRACEPTADO, CNSFNOT
			FROM FCONCID
			WHERE IDFCONCI = @IDFCONCI
			  AND VLRACEPTADO > 0
        
			OPEN cursor_confirmar
			FETCH NEXT FROM cursor_confirmar INTO @ITEM_FCONCID, @VLRACEPTADO, @CNSFNOT
        
			WHILE @@FETCH_STATUS = 0
			BEGIN

				IF @CNSFNOT IS NULL OR @CNSFNOT = ''
				BEGIN
					SET @PREFIJO = @IDSEDE + 'C'
					EXEC SPK_GENCONSECUTIVO @IDSEDE, '01', '@FNOTC', @NUEVO_CONSECUTIVO OUTPUT
					SET @NUEVO_CONSECUTIVO = @PREFIJO + RIGHT('00000000' + LTRIM(RTRIM(@NUEVO_CONSECUTIVO)), 8)
                
					UPDATE FCONCID
					SET CNSFNOT = @NUEVO_CONSECUTIVO
					WHERE IDFCONCI = @IDFCONCI
					  AND ITEM_FCONCID = @ITEM_FCONCID
				END
            
				FETCH NEXT FROM cursor_confirmar INTO @ITEM_FCONCID, @VLRACEPTADO, @CNSFNOT
			END
        
			CLOSE cursor_confirmar
			DEALLOCATE cursor_confirmar

			EXEC SPK_APLICA_CONCILIACION 
				@IDFCONCI, 
				@IDSEDE, 
				@COMPANIA, 
				@USUARIO, 
				@SYS_COMPUTERNAME

			SELECT @ESTADO_FINAL = ESTADO
			FROM FCONCI
			WHERE IDFCONCI = @IDFCONCI
        
			IF UPPER(@ESTADO_FINAL) <> 'CERRADA'
			BEGIN
				SELECT 'KO' AS OK, 'La Conciliación No se ha aplicado correctamente, revise y vuelva a intentarlo' AS ERROR
				RETURN
			END
        
			SELECT 'OK' AS OK, 'La Conciliación se ha aplicado correctamente' AS MENSAJE
			RETURN
		END TRY
		BEGIN CATCH
			IF CURSOR_STATUS('global', 'cursor_confirmar') >= 0
			BEGIN
				CLOSE cursor_confirmar
				DEALLOCATE cursor_confirmar
			END        
			SELECT 'KO' AS OK, 'ERROR: ' + ERROR_MESSAGE() AS ERROR
			RETURN
		END CATCH
	END
-- MÉTODO 5: ANULAR_CONCILIACION 
	IF @METODO = 'ANULAR_CONCILIACION'
	BEGIN
		SELECT @IDFCONCI = IDFCONCI
		FROM OPENJSON(@PARAMETROS)
		WITH (IDFCONCI VARCHAR(20) '$.IDFCONCI')
    
		DECLARE @ItemActual        INT;
		    
		SET @CONTADOR = 0;
		SET @PREFIJO = @IDSEDE + 'D';

		BEGIN TRY
			BEGIN TRANSACTION;

			DECLARE Cursor_DetalleConciliacion CURSOR LOCAL FAST_FORWARD FOR
			SELECT ITEM_FCONCID, VLRACEPTADO, CNSNOTADB
			FROM FCONCID
			WHERE IDFCONCI = @IDFCONCI AND UPPER(ESTADO) = 'CERRADA'
			ORDER BY ITEM_FCONCID;

			OPEN Cursor_DetalleConciliacion;

			FETCH NEXT FROM Cursor_DetalleConciliacion 
			INTO @ItemActual, @VLRACEPTADO, @CNSNOTADB;

			WHILE @@FETCH_STATUS = 0
			BEGIN
            
				IF @VLRACEPTADO > 0 AND (@CNSNOTADB IS NULL OR @CNSNOTADB = '')
				BEGIN					
					SET @NUEVO_CONSECUTIVO = '';
					EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@FNOTD', @NUEVO_CONSECUTIVO OUTPUT;
					SET @NUEVO_CONSECUTIVO = @PREFIJO + RIGHT('00000000' + LTRIM(RTRIM(@NUEVO_CONSECUTIVO)), 8);
                
					UPDATE FCONCID SET CNSNOTADB = @NUEVO_CONSECUTIVO 
					WHERE IDFCONCI = @IDFCONCI AND ITEM_FCONCID = @ItemActual;
				END

				EXEC SPK_RETIRA_FACTURA_CONCI 
					@IDFCONCI, 
					@ItemActual, 
					@COMPANIA, 
					@IDSEDE, 
					@USUARIO, 
					@SYS_COMPUTERNAME;

				SET @CONTADOR = @CONTADOR + 1;

				FETCH NEXT FROM Cursor_DetalleConciliacion 
				INTO @ItemActual, @VLRACEPTADO, @CNSNOTADB;
			END

			CLOSE Cursor_DetalleConciliacion;
			DEALLOCATE Cursor_DetalleConciliacion;

			UPDATE FCONCID SET ESTADO = 'Anulada' WHERE IDFCONCI = @IDFCONCI AND UPPER(ESTADO) = 'CERRADA';
			UPDATE FCONCI  SET ESTADO = 'Anulada' WHERE IDFCONCI = @IDFCONCI;

			COMMIT TRANSACTION;

			SELECT 'OK' AS OK, 'Conciliación anulada: ' + CAST(@CONTADOR AS VARCHAR) + ' items procesados.' AS MENSAJE;

		END TRY
		BEGIN CATCH
			IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        
			IF CURSOR_STATUS('local', 'Cursor_DetalleConciliacion') >= 0
			BEGIN
				CLOSE Cursor_DetalleConciliacion;
				DEALLOCATE Cursor_DetalleConciliacion;
			END

			SELECT 'KO' AS OK, ERROR_MESSAGE() AS ERROR;
		END CATCH
		RETURN;
	END

-- MÉTODO 6: ANULAR_ITEM
	IF @METODO = 'ANULAR_ITEM'
	BEGIN
		SELECT  
			@IDFCONCI = IDFCONCI,
			@ITEM = ITEM
		FROM OPENJSON(@PARAMETROS)
		WITH (
			IDFCONCI VARCHAR(20) '$.IDFCONCI',
			ITEM     INT         '$.ITEM'
		);

		IF @IDFCONCI IS NULL OR @IDFCONCI = '' OR @ITEM IS NULL
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'IDFCONCI e ITEM son requeridos';
			SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
			RETURN;
		END

		SELECT @ESTADO_ITEM = ESTADO, @VLRACEPTADO_ITEM = VLRACEPTADO, @CNSNOTADB_ITEM = CNSNOTADB
		FROM FCONCID
		WHERE IDFCONCI = @IDFCONCI
		  AND ITEM_FCONCID = @ITEM

		IF @ESTADO_ITEM IS NULL
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'No se encontró el ítem de conciliación o no pertenece al registro enviado';
			SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
			RETURN;
		END

		IF UPPER(@ESTADO_ITEM) <> 'CERRADA'
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'Solo se pueden anular items con estado CERRADA';
			SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
			RETURN;
		END

		BEGIN TRY

			IF @VLRACEPTADO_ITEM > 0
			BEGIN
				IF @CNSNOTADB_ITEM IS NOT NULL AND @CNSNOTADB_ITEM <> ''
				BEGIN
					INSERT INTO @TBLERRORES(ERROR)
					SELECT 'Esta Factura cuenta con consecutivo de nota debito. Verifique';
					SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
					RETURN;
				END
				
				SET @PREFIJO = @IDSEDE + 'D'
				EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@FNOTD', @NUEVO_CONSECUTIVO OUTPUT
				SET @NUEVO_CONSECUTIVO = @PREFIJO + RIGHT('00000000' + LTRIM(RTRIM(@NUEVO_CONSECUTIVO)), 8)
				
				UPDATE FCONCID
				SET CNSNOTADB = @NUEVO_CONSECUTIVO
				WHERE IDFCONCI = @IDFCONCI
				  AND ITEM_FCONCID = @ITEM
			END
			
			EXEC SPK_RETIRA_FACTURA_CONCI 
				@IDFCONCI, 
				@ITEM, 
				@COMPANIA, 
				@IDSEDE, 
				@USUARIO, 
				@SYS_COMPUTERNAME

		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR)
			SELECT ERROR_MESSAGE();
		END CATCH

		IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
		BEGIN
			SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
			RETURN;
		END

		SELECT 'OK' AS OK, 'Factura anulada correctamente' AS MENSAJE;
		RETURN;
	END   

-- MÉTODO 7: IMPRIMIR CONCILIACIÓN
	IF @METODO = 'IMPRIMIR'
	BEGIN
		SELECT @IDFCONCI = JSON_VALUE(@PARAMETROS, '$.IDFCONCI')
		IF ISNULL(@IDFCONCI, '') = ''
		BEGIN
			SELECT 'KO' AS OK, 'IDFCONCI es requerido para imprimir conciliación' AS ERROR
			RETURN
		END

		SELECT
			CIU.NOMBRE AS CIUDAD,
			SED.IDSEDE,
			SED.NIT AS NIT_SEDE,
			SED.DESCRIPCION AS DESCRIPCION_SEDE,
			SED.DIRECCION AS DIRECCION_SEDE,
			SED.TELEFONOS AS TELEFONOS,
			FCONCI.IDFCONCI,
			FCONCI.FECHACONC,
			FCONCI.FECHADIG,
			FCONCI.ESTADO,
			FCONCI.OBSERVACION,
			FCONCI.VALOR,
			FCONCI.CNSEXTERNO,
			FCONCI.FUNCIONARIOADMIN,
			TER.IDTERCERO,
			TER.RAZONSOCIAL,
			FECHA_IMPRESION = CURRENT_TIMESTAMP,
			BASE = IIF(
				DBO.FNK_VALORVARIABLE('BDATA_PRODUCCION') = DB_NAME(),
				'OK',
				'DEMO'
			),

			FCONCID = (
				SELECT
					FCONCID.ITEM_FCONCID,
					FCONCID.CNSCXC,
					FCONCID.N_FACTURA,
					FCONCID.TIPO,
					N_GLOSA = COALESCE(FCONCID.CNSGLO, ''),
					FCONCID.SALDONETO,
					FCONCID.VLRACEPTADO,
					FCONCID.VLRRECUPERAR 
				FROM FCONCID 
				WHERE FCONCID.IDFCONCI = FCONCI.IDFCONCI
				ORDER BY FCONCID.ITEM_FCONCID
				FOR JSON PATH
			)

		FROM FCONCI 
		INNER JOIN TER ON TER.IDTERCERO = FCONCI.IDTERCERO
		LEFT JOIN SED ON SED.IDSEDE = FCONCI.IDSEDE
		LEFT JOIN CIU ON SED.CIUDAD = CIU.CIUDAD
		WHERE FCONCI.IDFCONCI = @IDFCONCI
		RETURN
	END

	-- MÉTODO 7: CARGA EXCEL
	IF @METODO = 'CARGA_EXCEL_FCONCID'
	BEGIN
		DECLARE @DETALLE NVARCHAR(MAX) 
		SELECT 
			@IDFCONCI = JSON_VALUE(@PARAMETROS, '$.IDFCONCI'), 
			@USUARIO = JSON_VALUE(@PARAMETROS, '$.USUARIO'), 
			@DETALLE = JSON_QUERY(@PARAMETROS, '$.DETALLE') 
			
			IF NOT EXISTS (SELECT 1 FROM FCONCI WHERE IDFCONCI = @IDFCONCI AND UPPER(ESTADO) = 'INGRESADA') 
			BEGIN 
				SELECT 'KO' AS OK, 'La conciliación no existe o no está en estado Ingresada' AS MENSAJE 
				RETURN 
			END

			SELECT 
				N_FACTURA, 
				TIPO, 
				CNSGLO, 
				VLRACEPTADO, 
				CODCONCEPTO, 				
				CAST(0 AS BIT) ERROR,
				CAST('' AS VARCHAR(500)) AS SMSERROR
			INTO #EXCEL_FCONCID 
			FROM OPENJSON(@DETALLE) 
			WITH ( 
				N_FACTURA VARCHAR(20) '$.N_FACTURA', 
				TIPO VARCHAR(20) '$.TIPO', 
				CNSGLO VARCHAR(20) '$.CNSGLO', 
				VLRACEPTADO DECIMAL(14,2)'$.VLRACEPTADO', 
				CODCONCEPTO VARCHAR(20) '$.CONDCONCEPTO'
				) 
		
		--Validaciones en excel 
		--1.Si esta vacío 
		IF NOT EXISTS (SELECT 1 FROM #EXCEL_FCONCID) 
		BEGIN 
			SELECT 'KO' AS OK, 'El archivo Excel no contiene registros' AS MENSAJE 
			RETURN 
		END 
		--2.campos obligatorios 
		--IF EXISTS ( SELECT 1 FROM #EXCEL_FCONCID WHERE ISNULL(N_FACTURA,'') = ''  )
		--BEGIN 
		--	SELECT 'KO' AS OK, 'Hay filas con campos obligatorios vacíos' AS MENSAJE
		--	RETURN 
		--END
		
		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='El numero de factura es obligatorio'
		FROM #EXCEL_FCONCID A
		WHERE ERROR=0 AND COALESCE(N_FACTURA,'')=''
		
		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='El tipo es obligatorio'
		FROM #EXCEL_FCONCID A
		WHERE ERROR=0 AND COALESCE(TIPO,'')=''

		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='El codigo de concepto es obligatorio'
		FROM #EXCEL_FCONCID A
		WHERE ERROR=0 AND COALESCE(CODCONCEPTO,'')=''

		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='La Factura  y el Tipo no existe en FCXCDV'
		FROM #EXCEL_FCONCID A
		WHERE ERROR=0 AND NOT EXISTS(SELECT 1 FROM FCXCDV WHERE N_FACTURA = A.N_FACTURA AND TIPO=A.TIPO)
		
		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='La factura no pertenece al tercero de la conciliación'
		FROM #EXCEL_FCONCID A
		INNER JOIN FCONCI ON FCONCI.IDFCONCI=@IDFCONCI
		WHERE ERROR=0 AND NOT EXISTS(SELECT 1 FROM FTR WHERE FTR.N_FACTURA = A.N_FACTURA AND FTR.IDTERCERO=FCONCI.IDTERCERO)
		
		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='La factura al ser tipo glosa, ratificacion o conciliacion debe tener asociada el consecutivo de glosa'
		FROM #EXCEL_FCONCID A
		WHERE A.ERROR=0 AND A.TIPO IN('G','C','R') AND COALESCE(A.CNSGLO,'')=''
		
		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='El saldo de la factura es menor o igual a 0 (cero)'
		FROM #EXCEL_FCONCID A
		WHERE A.ERROR=0 AND A.TIPO IN('G','C','R') 
			AND EXISTS (SELECT 1 FROM FCXCDV V WHERE V.N_FACTURA=A.N_FACTURA AND A.TIPO=V.TIPO AND A.CNSGLO=V.CNSGLO AND COALESCE(V.SALDONETO,0)<=0)

		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='El saldo de la factura es menor o igual a 0 (cero)'
		FROM #EXCEL_FCONCID A
		WHERE A.ERROR=0 AND A.TIPO NOT IN('G','C','R') 
			AND EXISTS (SELECT 1 FROM FCXCDV V WHERE V.N_FACTURA=A.N_FACTURA AND A.TIPO=V.TIPO AND COALESCE(V.SALDONETO,0)<=0)
			
		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='El saldo de la factura es menor al valor aceptado'
		FROM #EXCEL_FCONCID A
		WHERE A.ERROR=0 AND A.TIPO IN('G','C','R')
		    --AND NOT EXISTS (SELECT 1 FROM FCXCDV V WHERE V.N_FACTURA=A.N_FACTURA AND A.TIPO=V.TIPO AND A.CNSGLO=V.CNSGLO AND COALESCE(V.SALDONETO,0)<=A.VLRACEPTADO)   NV13082026
			AND NOT EXISTS (SELECT 1 FROM FCXCDV V WHERE V.N_FACTURA=A.N_FACTURA AND A.TIPO=V.TIPO AND A.CNSGLO=V.CNSGLO AND COALESCE(V.SALDONETO,0) >= A.VLRACEPTADO)

		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='El saldo de la factura es menor al valor aceptado'
		FROM #EXCEL_FCONCID A
		WHERE A.ERROR=0 AND A.TIPO NOT IN('G','C','R') 
			AND NOT EXISTS (SELECT 1 FROM FCXCDV V WHERE V.N_FACTURA=A.N_FACTURA AND A.TIPO=V.TIPO AND COALESCE(V.SALDONETO,0) >= A.VLRACEPTADO)
			
		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='La factura y tipo de factura ya existe en esta conciliación'
		FROM #EXCEL_FCONCID A
		INNER JOIN FCONCID ON FCONCID.IDFCONCI=@IDFCONCI AND FCONCID.N_FACTURA=A.N_FACTURA AND FCONCID.TIPO=A.TIPO
		WHERE ERROR=0 
		
		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='La factura y tipo de factura ya existe en otra conciliación'
		FROM #EXCEL_FCONCID A
		WHERE ERROR=0 AND EXISTS (SELECT 1 FROM FCONCID D WHERE D.N_FACTURA=A.N_FACTURA AND D.TIPO=A.TIPO AND D.IDFCONCI<>@IDFCONCI AND D.ESTADO='INGRESADA')

		UPDATE #EXCEL_FCONCID SET ERROR=1, SMSERROR='El concepto ingresado no existe en la tabla de configuracion CPNT'
		FROM #EXCEL_FCONCID A
		WHERE NOT EXISTS (SELECT 1 FROM CPNT C WHERE C.CODIGO=A.CODCONCEPTO)

		--Inserción masiva 
		DECLARE @BASE_ITEM INT 
		
		SELECT @BASE_ITEM = COALESCE(MAX(ITEM_FCONCID),0) FROM FCONCID WHERE IDFCONCI = @IDFCONCI 

		INSERT INTO FCONCID ( 
					IDFCONCI, 
					ITEM_FCONCID, 
					CNSCXC, 
					N_FACTURA, 
					ITEM_FCXCDV, 
					TIPO, 
					CNSGLO, 
					SALDONETO, 
					VLRACEPTADO, 
					VLRRECUPERAR, 
					CLASE, 
					ESTADO, 
					OBSERVACION, 
					CONDCONCEPTO ) 
		SELECT 
			@IDFCONCI, 
			ROW_NUMBER() OVER (ORDER BY (SELECT 1)) + @BASE_ITEM, 
			V.CNSCXC,
			V.N_FACTURA,
			V.ITEM,
			A.TIPO, 
			A.CNSGLO,
			V.SALDONETO, 
			COALESCE(A.VLRACEPTADO,0), 
			COALESCE(V.SALDONETO,0)-COALESCE(A.VLRACEPTADO,0) VLRRECUPERAR, 
			'C', 
			'Ingresada', 
			'', 
			A.CODCONCEPTO 
		FROM #EXCEL_FCONCID A
		INNER JOIN FCXCDV V ON V.N_FACTURA=A.N_FACTURA AND V.TIPO=A.TIPO
		WHERE A.ERROR=0

		SELECT 'OK' AS OK, 'Carga Excel realizada correctamente' AS MENSAJE

		SELECT * FROM #EXCEL_FCONCID A 
		WHERE A.ERROR=1
	END
END

