CREATE OR ALTER PROCEDURE DBO.SPQ_BCTC
@JSON  NVARCHAR(MAX)
WITH   ENCRYPTION
AS
DECLARE
    @PARAMETROS NVARCHAR(MAX)
    , @MODELO     NVARCHAR(MAX)
    , @METODO     VARCHAR(100)
    , @MODELOACT	 NVARCHAR(MAX)
    , @USUARIO    VARCHAR(20),
	   
    @BANCO VARCHAR(5),
    @SUCURSAL VARCHAR(30),
    @TIPO_CUENTA VARCHAR(20),
    @CTA_BCO VARCHAR(20),
    @F_APERTURA DATE,
    @COD_CONTABLE VARCHAR(20),
    @SALDO DECIMAL(18, 2),
    @FORMATODEPAGO VARCHAR(50),
    @FORMATOCHEQUE VARCHAR(50),
    @IDFORMATO VARCHAR(50),
    @ESTADO VARCHAR(10),
    @SIMEV VARCHAR(20),
    @RIESGO VARCHAR(20),
    @ENTIDAD_CALIFICADORA VARCHAR(20),
    @OTRA_CALIFICADORA VARCHAR(50),
    @IDMONEDA VARCHAR(10),
    @GRAVAMEN VARCHAR(10),
    @ESTADO_BCO VARCHAR(20),
    @FECHA DATETIME,
    @FECHAINICIAL DATETIME,
    @FECHAFINAL DATETIME,
    @FECHACON DATETIME,
    @SALDOB DECIMAL(18, 2),
    @SALDOCONT DECIMAL(18, 2),
    @OBSERVACION VARCHAR(500),
    @CONSECUTIVO VARCHAR(20),
    @DESCRIPCION VARCHAR(500),
    @CODIGO VARCHAR(20),
    @OPERACION VARCHAR(10),
    @IDTERCERO VARCHAR(20),
    @VALOR DECIMAL(18, 2),
    @TIPO VARCHAR(20),
    @ITEM smallint,
    @TODOS VARCHAR(16),
	@AHORA DATETIME = CONVERT(SMALLDATETIME, GETDATE()),
    @CCI VARCHAR(20),
    @TIPOCUE VARCHAR(20),
    @SEDEB  VARCHAR(6),
    @TIPO_PLANO VARCHAR(20),
    @TARCRED BIT,
    @CUPODISP DECIMAL(14,2)
DECLARE @TBLERRORES TABLE(CONTINUA VARCHAR(2), ERROR VARCHAR(500));
BEGIN
SET LANGUAGE Spanish;
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
   FROM OPENJSON (@json)
	WITH (
	   MODELO         VARCHAR(100)      '$.MODELO', 
	   METODO         VARCHAR(100)      '$.METODO',
	   USUARIO        VARCHAR(20)       '$.USUARIO',
	   PARAMETROS     NVARCHAR(MAX)  AS JSON
	)

	IF @METODO = 'GUARDARBCT'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@TIPO_CUENTA = JSON_VALUE(@PARAMETROS, '$.TIPO_CUENTA'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@F_APERTURA = JSON_VALUE(@PARAMETROS, '$.F_APERTURA'),
			@COD_CONTABLE = JSON_VALUE(@PARAMETROS, '$.COD_CONTABLE'),
			@FORMATODEPAGO = JSON_VALUE(@PARAMETROS, '$.FORMATODEPAGO'),
			@FORMATOCHEQUE = JSON_VALUE(@PARAMETROS, '$.FORMATOCHEQUE'),
			@IDFORMATO = JSON_VALUE(@PARAMETROS, '$.IDFORMATO'),
			@ESTADO = JSON_VALUE(@PARAMETROS, '$.ESTADO'),
			@SIMEV = JSON_VALUE(@PARAMETROS, '$.SIMEV'),
			@RIESGO = JSON_VALUE(@PARAMETROS, '$.RIESGO'),
			@ENTIDAD_CALIFICADORA = JSON_VALUE(@PARAMETROS, '$.ENTIDAD_CALIFICADORA'),
			@OTRA_CALIFICADORA = JSON_VALUE(@PARAMETROS, '$.OTRA_CALIFICADORA'),
			@IDMONEDA = JSON_VALUE(@PARAMETROS, '$.IDMONEDA'),
			@GRAVAMEN = JSON_VALUE(@PARAMETROS, '$.GRAVAMEN'),
			@ESTADO_BCO =  JSON_VALUE(@PARAMETROS, '$.ESTADO_BCO'),
			@CCI =  JSON_VALUE(@PARAMETROS, '$.CCI'),
			@TIPOCUE =  JSON_VALUE(@PARAMETROS, '$.TIPOCUE'),
			@SEDEB =  JSON_VALUE(@PARAMETROS, '$.IDSEDE'),
			@TIPO_PLANO =  JSON_VALUE(@PARAMETROS, '$.TIPO_PLANO'),
         @TARCRED =  JSON_VALUE(@PARAMETROS, '$.TARCRED'),
         @CUPODISP=  JSON_VALUE(@PARAMETROS, '$.CUPODISP');


			IF NOT EXISTS(SELECT 1 FROM BCT WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO)
			BEGIN
				-- Insertar en la tabla BCT
				INSERT INTO BCT (
					BANCO, SUCURSAL, TIPO_CUENTA, CTA_BCO, F_APERTURA, COD_CONTABLE, SALDO,
					FORMATODEPAGO, FORMATOCHEQUE, IDFORMATO, ESTADO, SIMEV, RIESGO,
					ENTIDAD_CALIFICADORA, OTRA_CALIFICADORA, IDMONEDA, GRAVAMEN, ESTADO_BCO,CCI,TIPOCUE,IDSEDE, TIPO_PLANO,TARCRED,CUPODISP
				)
				VALUES (
					@BANCO, @SUCURSAL, @TIPO_CUENTA, @CTA_BCO, @F_APERTURA, @COD_CONTABLE, 0,
					@FORMATODEPAGO, @FORMATOCHEQUE, @IDFORMATO, @ESTADO, @SIMEV, @RIESGO,
					@ENTIDAD_CALIFICADORA, @OTRA_CALIFICADORA, @IDMONEDA, @GRAVAMEN, @ESTADO_BCO,@CCI,@TIPOCUE,@SEDEB, @TIPO_PLANO,@TARCRED,@CUPODISP
				);

				SELECT 'OK' OK
			END
			ELSE
			BEGIN
				SELECT 'KO'OK, 'Ya hay un registro de ese Banco, sucursal y N. Cuenta.'ERROR
			END

		RETURN
	END
	IF @METODO = 'ACTUALIZABCT'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@TIPO_CUENTA = JSON_VALUE(@PARAMETROS, '$.TIPO_CUENTA'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@F_APERTURA = JSON_VALUE(@PARAMETROS, '$.F_APERTURA'),
			@COD_CONTABLE = JSON_VALUE(@PARAMETROS, '$.COD_CONTABLE'),
			@FORMATODEPAGO = JSON_VALUE(@PARAMETROS, '$.FORMATODEPAGO'),
			@FORMATOCHEQUE = JSON_VALUE(@PARAMETROS, '$.FORMATOCHEQUE'),
			@IDFORMATO = JSON_VALUE(@PARAMETROS, '$.IDFORMATO'),
			@ESTADO = JSON_VALUE(@PARAMETROS, '$.ESTADO'),
			@SIMEV = JSON_VALUE(@PARAMETROS, '$.SIMEV'),
			@RIESGO = JSON_VALUE(@PARAMETROS, '$.RIESGO'),
			@ENTIDAD_CALIFICADORA = JSON_VALUE(@PARAMETROS, '$.ENTIDAD_CALIFICADORA'),
			@OTRA_CALIFICADORA = JSON_VALUE(@PARAMETROS, '$.OTRA_CALIFICADORA'),
			@IDMONEDA = JSON_VALUE(@PARAMETROS, '$.IDMONEDA'),
			@GRAVAMEN = JSON_VALUE(@PARAMETROS, '$.GRAVAMEN'),
			@ESTADO_BCO =  JSON_VALUE(@PARAMETROS, '$.ESTADO_BCO'),
			@CCI =  JSON_VALUE(@PARAMETROS, '$.CCI'),
			@TIPOCUE =  JSON_VALUE(@PARAMETROS, '$.TIPOCUE'),
			@SEDEB =  JSON_VALUE(@PARAMETROS, '$.IDSEDE'),
			@TIPO_PLANO =  JSON_VALUE(@PARAMETROS, '$.TIPO_PLANO'),
         @TARCRED =  JSON_VALUE(@PARAMETROS, '$.TARCRED'),
         @CUPODISP=  JSON_VALUE(@PARAMETROS, '$.CUPODISP');         

		-- Validar la existencia del código de banco
		IF EXISTS(SELECT 1 FROM BCT WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO)
		BEGIN
			-- Actualizar en la tabla BCT
			UPDATE BCT
			SET
				TIPO_CUENTA = @TIPO_CUENTA,
				F_APERTURA = @F_APERTURA,
				COD_CONTABLE = @COD_CONTABLE,
				FORMATODEPAGO = @FORMATODEPAGO,
				FORMATOCHEQUE = @FORMATOCHEQUE,
				IDFORMATO = @IDFORMATO,
				ESTADO = @ESTADO,
				SIMEV = @SIMEV,
				RIESGO = @RIESGO,
				ENTIDAD_CALIFICADORA = @ENTIDAD_CALIFICADORA,
				OTRA_CALIFICADORA = @OTRA_CALIFICADORA,
				IDMONEDA = @IDMONEDA,
				GRAVAMEN = @GRAVAMEN,
				ESTADO_BCO = @ESTADO_BCO,
                CCI=@CCI,
                TIPOCUE=@TIPOCUE,
                IDSEDE=@SEDEB,
                TIPO_PLANO=@TIPO_PLANO,
                TARCRED=@TARCRED,
                CUPODISP=@CUPODISP
			WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO;

			SELECT 'OK' AS OK;
		END
		ELSE
		BEGIN
			SELECT 'KO' AS OK, 'Ya hay un registro de ese Banco, sucursal y N. Cuenta.' AS ERROR;
		END

		RETURN
	END
	IF @METODO = 'ELIMINABCT'
	BEGIN
		SELECT
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO');

		-- Validar la existencia del código de banco
		IF EXISTS(SELECT 1 FROM BCT WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO)
		BEGIN
			
			IF EXISTS(SELECT * FROM BMOV WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO)
			BEGIN
				SELECT 'KO' AS OK, 'Cuenta con movimientos no se puede eliminar.' AS ERROR;
				RETURN
			END

			-- Eliminar el registro de la tabla BCT
			DELETE FROM BCT WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL AND CTA_BCO = @CTA_BCO;
			SELECT 'OK' AS OK;
		END
		ELSE
		BEGIN
			SELECT 'KO' AS OK, 'No existe un registro con ese Banco, sucursal y N. Cuenta.' AS ERROR;
		END
		RETURN
	END
	IF @METODO = 'GUARDACONCILIACION'
	BEGIN
		SELECT 
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@FECHA = CONVERT(DATE, GETDATE()), -- Obtener la fecha actual
			@ESTADO = 'Abierta',
			@FECHACON = JSON_VALUE(@PARAMETROS, '$.FECHACON'),
			@SALDOB = JSON_VALUE(@PARAMETROS, '$.SALDOB'),
			@SALDOCONT = JSON_VALUE(@PARAMETROS, '$.SALDOCONT'),
			@OBSERVACION = JSON_VALUE(@PARAMETROS, '$.OBSERVACION'),
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO');

			SELECT @CONSECUTIVO = NULL 
			EXEC SPK_GENCONSECUTIVO '01', '01', '@BCTC',  @CONSECUTIVO OUTPUT  
			SELECT @CONSECUTIVO = '01' +  REPLACE(SPACE(8 - LEN(@CONSECUTIVO))+LTRIM(RTRIM(@CONSECUTIVO)),SPACE(1),0)

			INSERT INTO BCTC ( CNSBCTC, FECHA, BANCO, SUCURSAL, CTA_BCO, SALDOB, SALDOCONT, OBSERVIACION, ESTADO, FECHACON, USUARIO )
			VALUES (@CONSECUTIVO, @FECHA,@BANCO, @SUCURSAL, @CTA_BCO, @SALDOB, @SALDOCONT, @OBSERVACION, @ESTADO, @FECHACON, @USUARIO )
			
			SELECT 'OK' AS OK;

			--SELECT * FROM USCXS  
		RETURN
	END
	IF @METODO = 'GETCONCILIACIONES'
	BEGIN
		SELECT 
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO');

		   SELECT BCTC.CNSBCTC, FORMAT(BCTC.FECHA, 'yyyy-MM-dd') AS FECHA, BCTC.BANCO, BCO.DESCRIPCION AS DESC_BANCO, BCTC.SUCURSAL, BSU.DESCRIPCION AS DESC_SUCURSAL, BCTC.CTA_BCO
				   , CAST(BCTC.SALDOB AS VARCHAR(20)) AS SALDOB, CAST(BCTC.SALDOCONT AS VARCHAR(20)) AS SALDOCONT
				   , BCTC.OBSERVIACION AS OBSERVACION, BCTC.ESTADO, FORMAT(BCTC.FECHACON, 'yyyy-MM-dd') AS FECHACON, BCTC.USUARIO, USUSU.NOMBRE
		   FROM BCTC  INNER JOIN BCT ON BCTC.BANCO    = BCT.BANCO
                                  AND BCTC.SUCURSAL = BCT.SUCURSAL
                                  AND BCTC.CTA_BCO  = BCT.CTA_BCO
	                 INNER JOIN BSU ON BCT.BANCO     = BSU.BANCO
                                  AND BCT.SUCURSAL  = BSU.SUCURSAL
                    INNER JOIN BCO ON BSU.BANCO     = BCO.BANCO 
	                 INNER JOIN USUSU ON BCTC.USUARIO = USUSU.USUARIO
			WHERE BCTC.BANCO = @BANCO AND BCTC.SUCURSAL = @SUCURSAL AND BCTC.CTA_BCO = @CTA_BCO 
		RETURN
	END
	IF @METODO = 'ACTUALIZACONCILIACION'
	BEGIN
		SELECT 
			@CONSECUTIVO = JSON_VALUE(@PARAMETROS, '$.CNSBCTC'),
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
			@FECHA = CONVERT(DATE, GETDATE()), -- Obtener la fecha actual
			@ESTADO = 'Abierta',
			@FECHACON = JSON_VALUE(@PARAMETROS, '$.FECHACON'),
			@SALDOB = JSON_VALUE(@PARAMETROS, '$.SALDOB'),
			@SALDOCONT = JSON_VALUE(@PARAMETROS, '$.SALDOCONT'),
			@OBSERVACION = JSON_VALUE(@PARAMETROS, '$.OBSERVACION');


			UPDATE BCTC SET
				FECHACON = @FECHACON,
				SALDOB =  @SALDOB,
				SALDOCONT = @SALDOCONT,
				OBSERVIACION = @OBSERVACION
			WHERE CNSBCTC = @CONSECUTIVO
	
			SELECT 'OK' AS OK;

			--SELECT * FROM USCXS  
		RETURN
	END
	IF @METODO = 'CIERRACONCILIACION'
	BEGIN
		SELECT @CONSECUTIVO = JSON_VALUE(@PARAMETROS, '$.CNSBCTC');

		IF NOT EXISTS (SELECT 1 FROM BCTC WHERE CNSBCTC = @CONSECUTIVO)
		BEGIN
			SELECT 'KO' AS OK, 'No existe la conciliación indicada.' AS ERROR;
			RETURN
		END

		IF EXISTS (
			SELECT 1
			FROM BCTC
			WHERE CNSBCTC = @CONSECUTIVO
			  AND UPPER(LTRIM(RTRIM(ESTADO))) = 'CERRADA'
		)
		BEGIN
			SELECT 'KO' AS OK, 'La conciliación ya se encuentra cerrada.' AS ERROR;
			RETURN
		END

		UPDATE BCTC
		SET ESTADO = 'Cerrada'
		WHERE CNSBCTC = @CONSECUTIVO;

		SELECT 'OK' AS OK;
		RETURN
	END
	IF @METODO = 'GUARDAOPERACION'
	BEGIN
		SELECT @CODIGO = JSON_VALUE(@PARAMETROS, '$.CODIGO'), @DESCRIPCION = JSON_VALUE(@PARAMETROS, '$.DESCRIPCION');

		IF EXISTS(SELECT 1 FROM TGEN WHERE TABLA = 'GENERAL' AND CAMPO = 'BCTC' AND CODIGO = @CODIGO AND @DESCRIPCION = @DESCRIPCION)
		BEGIN
			SELECT 'KO'OK, 'Ya existe un registro con ese código y descripción.'ERROR
		END
		ELSE
		BEGIN
			INSERT INTO TGEN (TABLA, CAMPO, CODIGO, DESCRIPCION)
			VALUES('GENERAL','BCTC',@CODIGO, UPPER(@DESCRIPCION))
		END
	END
	IF @METODO = 'OPERACIONES'
	BEGIN
		SELECT TABLA, CAMPO, CODIGO, DESCRIPCION
		FROM TGEN 
		WHERE TABLA = 'GENERAL' AND CAMPO = 'BCTC'
	END
	IF @METODO = 'ELIMINAOPERACION'
	BEGIN
		SELECT @CODIGO = JSON_VALUE(@PARAMETROS, '$.CODIGO'), @DESCRIPCION = JSON_VALUE(@PARAMETROS, '$.DESCRIPCION');
		DELETE TGEN WHERE TABLA = 'GENERAL' AND CAMPO = 'BCTC' AND CODIGO = @CODIGO AND @DESCRIPCION = @DESCRIPCION
	END
	IF @METODO = 'GUARDABCTCD'
	BEGIN
		SELECT @CONSECUTIVO = JSON_VALUE(@PARAMETROS, '$.CNSBCTC'), 
			   @FECHA = JSON_VALUE(@PARAMETROS, '$.FECHAMOV'),
			   @OPERACION = JSON_VALUE(@PARAMETROS, '$.OPERACION'),
			   @IDTERCERO  = JSON_VALUE(@PARAMETROS, '$.BENEFICIARIO '),
			   @VALOR  = JSON_VALUE(@PARAMETROS, '$.VALOR '),
			   @TIPO  = JSON_VALUE(@PARAMETROS, '$.TIPO '),
			   @OBSERVACION  = JSON_VALUE(@PARAMETROS, '$.DETALLE ');

		SELECT TOP 1 @ITEM = ITEM
		FROM BCTCD
		WHERE CNSBCTC = @CONSECUTIVO 
		ORDER BY ITEM DESC;

		SET @ITEM = ISNULL(@ITEM, 0) + 1;

		INSERT INTO BCTCD (CNSBCTC, ITEM, FECHAMOV, OPERACION, BENEFICIARIO, DETALLE, VALOR, TIPO)
		VALUES (@CONSECUTIVO, @ITEM, @FECHA, @OPERACION, @IDTERCERO, @OBSERVACION, @VALOR, @TIPO);

		

		RETURN
	END
	IF @METODO = 'GETBCTCD'
	BEGIN
		SELECT @CONSECUTIVO = JSON_VALUE(@PARAMETROS, '$.CNSBCTC');

		SELECT BCTCD.CNSBCTC, BCTCD.ITEM, FORMAT(BCTCD.FECHAMOV, 'yyyy-MM-dd') AS FECHAMOV
		     , BCTCD.OPERACION, TGEN.DESCRIPCION
		     , BCTCD.BENEFICIARIO, TER.RAZONSOCIAL, TER.TIPO_ID
			 , BCTCD.DETALLE, CAST(BCTCD.VALOR AS VARCHAR(20)) AS VALOR, BCTCD.TIPO 
		FROM BCTCD 
		INNER JOIN TER ON BCTCD.BENEFICIARIO = TER.IDTERCERO
		INNER JOIN TGEN ON TABLA = 'GENERAL' AND CAMPO = 'BCTC' AND BCTCD.OPERACION = TGEN.CODIGO
		WHERE CNSBCTC = @CONSECUTIVO;

	END
	IF @METODO = 'ACTUALIZABCTCD'
	BEGIN
		SELECT @CONSECUTIVO = JSON_VALUE(@PARAMETROS, '$.CNSBCTC'), 
			   @ITEM = JSON_VALUE(@PARAMETROS, '$.ITEM'),
			   @FECHA = JSON_VALUE(@PARAMETROS, '$.FECHAMOV'),
			   @OPERACION = JSON_VALUE(@PARAMETROS, '$.OPERACION'),
			   @IDTERCERO  = JSON_VALUE(@PARAMETROS, '$.BENEFICIARIO '),
			   @VALOR  = JSON_VALUE(@PARAMETROS, '$.VALOR '),
			   @TIPO  = JSON_VALUE(@PARAMETROS, '$.TIPO '),
			   @OBSERVACION  = JSON_VALUE(@PARAMETROS, '$.DETALLE ');

		IF EXISTS(SELECT 1 FROM BCTCD WHERE CNSBCTC = @CONSECUTIVO AND ITEM = @ITEM)
		BEGIN
			UPDATE BCTCD 
			SET FECHAMOV = @FECHA,
			    OPERACION = @OPERACION,
				BENEFICIARIO = @IDTERCERO,
				DETALLE = @OBSERVACION,
				VALOR = @VALOR,
				TIPO = @TIPO
			WHERE CNSBCTC = @CONSECUTIVO AND ITEM = @ITEM

			SELECT 'OK'OK, ''ERROR
			RETURN
		END
		ELSE
		BEGIN
			SELECT 'KO'OK, 'No se encuentra registro'ERROR
			RETURN
		END

	END

	IF @METODO = 'REPORTE_CONSIGNACIONES'
		BEGIN
			SELECT 
				@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
				@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
				@TIPO_CUENTA = JSON_VALUE(@PARAMETROS, '$.TIPO_CUENTA'),
				@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO'),
				@IDTERCERO = JSON_VALUE(@PARAMETROS, '$.IDTERCERO'),
				@TIPO = JSON_VALUE(@PARAMETROS, '$.TIPO'),
				@FECHAINICIAL = JSON_VALUE(@PARAMETROS, '$.FINICIAL'),
				@TODOS  = JSON_VALUE(@PARAMETROS, '$.TODOS'),
				@FECHAFINAL = JSON_VALUE(@PARAMETROS, '$.FFINAL');

			SELECT RESULT = (
				SELECT TOP 500
					BMOVD.ITEM,
					BMOVD.IDTERCERO,
					TER.RAZONSOCIAL,
					TER.NIT,
					TERTOTALITEM = (
						SELECT SUM(BMOVD2.VLRITEM)
						FROM BMOVD AS BMOVD2
						WHERE BMOVD2.ITEM = BMOVD.ITEM
						  AND BMOVD2.IDTERCERO = BMOVD.IDTERCERO
						  AND BMOVD2.BANCO = @BANCO
						  AND BMOVD2.SUCURSAL = @SUCURSAL
						  AND BMOVD2.CTA_BCO = @CTA_BCO
					),
					TERTOTALLEGALIZADO = (
						SELECT SUM(BMOVD2.VLRLEGALIZADO)
						FROM BMOVD AS BMOVD2
						WHERE BMOVD2.ITEM = BMOVD.ITEM
						  AND BMOVD2.IDTERCERO = BMOVD.IDTERCERO
						  AND BMOVD2.BANCO = @BANCO
						  AND BMOVD2.SUCURSAL = @SUCURSAL
						  AND BMOVD2.CTA_BCO = @CTA_BCO
					),
					TERTOTALXLEGALIZAR = (
						SELECT SUM(BMOVD2.VLRITEM - BMOVD2.VLRLEGALIZADO)
						FROM BMOVD AS BMOVD2
						WHERE BMOVD2.ITEM = BMOVD.ITEM
						  AND BMOVD2.IDTERCERO = BMOVD.IDTERCERO
						  AND BMOVD2.BANCO = @BANCO
						  AND BMOVD2.SUCURSAL = @SUCURSAL
						  AND BMOVD2.CTA_BCO = @CTA_BCO
					),
					DETAILS = (
						SELECT
							TER.NIT ,
							TER.RAZONSOCIAL,
							BMOVD2.RENGLON,
							BMOVD2.FORMAPAGO,
							BMOVD2.VLRITEM,
							BMOVD2.VLRLEGALIZADO,
							(BMOVD2.VLRITEM - BMOVD2.VLRLEGALIZADO) AS PORLEGALIZAR,
							BMOV.ESTADO,
							BMOV.DESCRIPCION,
							BMOV.NROCOMPROBANTE,
							CONCAT(BMOVD2.CODCAJA,'-',BMOVD2.CNSFACJ) AS CAJACNSFACJ,
						   CASE 
							  WHEN COALESCE(BMOVD2.RECAUDO,0) = 1 THEN 'SI'
							  ELSE 'NO'
							END AS RECAUDO,
							BMOVD2.PROCEDENCIA,
							FORMAT(BMOV.FECHAOPERACION,'dd/MM/yyyy') AS FECHAOPERACION,
							OFIN.NOMOPERACION,
							@TIPO AS TIPO
						FROM BMOVD AS BMOVD2
						INNER JOIN BMOV ON BMOV.ITEM = BMOVD2.ITEM AND BMOV.CTA_BCO = BMOVD2.CTA_BCO
						INNER JOIN TER ON BMOVD2.IDTERCERO = TER.IDTERCERO
						INNER JOIN OFIN ON BMOV.IDOPERACION = OFIN.IDOPERACION
						WHERE BMOVD2.ITEM = BMOVD.ITEM
						  AND BMOVD2.IDTERCERO = BMOVD.IDTERCERO
						  AND BMOVD2.BANCO = @BANCO
						  AND BMOVD2.SUCURSAL = @SUCURSAL
						  AND BMOVD2.CTA_BCO = @CTA_BCO
						  AND (@TIPO != 'Legalizadas' OR BMOVD2.VLRLEGALIZADO >= BMOVD2.VLRITEM)
						  AND (@TIPO != 'No Legalizadas' OR BMOVD2.VLRLEGALIZADO < BMOVD2.VLRITEM)
						FOR JSON PATH
					)
				FROM BMOVD
				INNER JOIN TER ON BMOVD.IDTERCERO = TER.IDTERCERO
				INNER JOIN BMOV ON BMOV.ITEM = BMOVD.ITEM AND BMOV.CTA_BCO = BMOVD.CTA_BCO
				WHERE BMOVD.BANCO = @BANCO
				  AND BMOVD.SUCURSAL = @SUCURSAL
				  AND BMOVD.CTA_BCO = @CTA_BCO
				  AND (@FECHAINICIAL IS NULL OR @FECHAINICIAL = '' OR BMOV.FECHAOPERACION >= @FECHAINICIAL)
				  AND (@FECHAFINAL IS NULL OR @FECHAFINAL = '' OR BMOV.FECHAOPERACION <= @FECHAFINAL)
				  AND (@TODOS != 'TERCERO' OR BMOVD.IDTERCERO = @IDTERCERO)
				GROUP BY BMOVD.ITEM, BMOVD.IDTERCERO, TER.RAZONSOCIAL, TER.NIT
				ORDER BY BMOVD.ITEM
				FOR JSON PATH
			)

			RETURN
		END

	IF @METODO = 'RELIQUIDAR'
	BEGIN
		SELECT 
			@BANCO = JSON_VALUE(@PARAMETROS, '$.BANCO'),
			@SUCURSAL = JSON_VALUE(@PARAMETROS, '$.SUCURSAL'),
			@TIPO_CUENTA = JSON_VALUE(@PARAMETROS, '$.TIPO_CUENTA'),
			@CTA_BCO = JSON_VALUE(@PARAMETROS, '$.CTA_BCO');

			EXEC SPK_RECALCULO_BANCOS @BANCO, @SUCURSAL, @CTA_BCO
	END

	IF @METODO = 'IMPRIMIR_CONCILIACION'
	BEGIN
		SELECT @CONSECUTIVO = JSON_VALUE(@PARAMETROS, '$.CNSBCTC');

		-- 1. Cabecera de la conciliación
		SELECT
			BCTC.CNSBCTC,
			BCTC.BANCO,
			BCO.DESCRIPCION AS DESC_BANCO,
			BCTC.SUCURSAL,
			BSU.DESCRIPCION AS DESC_SUCURSAL,
			BCTC.CTA_BCO,
			CAST(BCTC.SALDOB AS DECIMAL(18, 2)) AS SALDOB,
			CAST(BCTC.SALDOCONT AS DECIMAL(18, 2)) AS SALDOCONT,
			CAST((BCTC.SALDOB - BCTC.SALDOCONT) AS DECIMAL(18, 2)) AS DIFERENCIA,
			UPPER(CONCAT(BCO.DESCRIPCION, ' ', BSU.DESCRIPCION)) AS NOMBRE_BANCO_SUC,
			FORMAT(BCTC.FECHACON, 'dd/MM/yyyy') AS FECHACON,
			'OK' AS OK
		FROM BCTC
		INNER JOIN BCO ON BCTC.BANCO = BCO.BANCO
		INNER JOIN BSU ON BCTC.BANCO = BSU.BANCO AND BCTC.SUCURSAL = BSU.SUCURSAL
		WHERE BCTC.CNSBCTC = @CONSECUTIVO;

		-- 2. Totales agrupados por operación
		SELECT
			BCTCD.OPERACION,
			TGEN.DESCRIPCION,
			CAST(SUM(BCTCD.VALOR) AS DECIMAL(18, 2)) AS TOTAL
		FROM BCTCD
		INNER JOIN TGEN ON TGEN.TABLA = 'GENERAL' AND TGEN.CAMPO = 'BCTC' AND BCTCD.OPERACION = TGEN.CODIGO
		WHERE BCTCD.CNSBCTC = @CONSECUTIVO
		GROUP BY BCTCD.OPERACION, TGEN.DESCRIPCION
		ORDER BY BCTCD.OPERACION;

		-- 3. Detalle de la conciliación
		SELECT
			BCTCD.CNSBCTC,
			BCTCD.ITEM,
			BCTCD.OPERACION,
			TGEN.DESCRIPCION AS DESC_OPERACION,
			FORMAT(BCTCD.FECHAMOV, 'dd/MM/yyyy') AS FECHAMOV,
			BCTCD.DETALLE,
			TER.RAZONSOCIAL AS BENEFICIARIO,
			CAST(BCTCD.VALOR AS DECIMAL(18, 2)) AS VALOR,
			BCTCD.TIPO
		FROM BCTCD
		INNER JOIN TER ON BCTCD.BENEFICIARIO = TER.IDTERCERO
		INNER JOIN TGEN ON TGEN.TABLA = 'GENERAL' AND TGEN.CAMPO = 'BCTC' AND BCTCD.OPERACION = TGEN.CODIGO
		WHERE BCTCD.CNSBCTC = @CONSECUTIVO
		ORDER BY BCTCD.OPERACION, BCTCD.ITEM;

		RETURN;
	END
END

