CREATE OR ALTER PROCEDURE DBO.SPQ_BCO
@JSON  NVARCHAR(MAX)
WITH   ENCRYPTION
AS
DECLARE
         @PARAMETROS NVARCHAR(MAX)
	   , @MODELO     NVARCHAR(MAX)
	   , @METODO     VARCHAR(100)
	   , @MODELOACT	 NVARCHAR(MAX)
	   , @USUARIO    VARCHAR(20)
	   , @ID	     INT
	   , @BANCO		 VARCHAR(5)
	   , @CODACH     VARCHAR(20)
	   , @IDTERCERO  VARCHAR(20)
	   , @DESCRIPCION VARCHAR(30)
	   , @SUCURSAL	 VARCHAR(2)
	   , @DIRECCION  VARCHAR(100)
	   , @TELEFONO1  VARCHAR(20)
	   , @TELEFONO2  VARCHAR(20)
	   , @CONTACTO   VARCHAR(60)
	   , @CARGO		 VARCHAR(40)
	   , @AHORA      DATETIME = CONVERT(SMALLDATETIME, GETDATE())

DECLARE @TBLERRORES TABLE(CONTINUA VARCHAR(2), ERROR VARCHAR(500));

BEGIN
SET LANGUAGE Spanish;
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
   FROM OPENJSON (@json)
	WITH (
	   MODELO         VARCHAR(100)      '$.MODELO', 
	   METODO         VARCHAR(100)      '$.METODO',
	   USUARIO        VARCHAR(20)       '$.USUARIO',
	   PARAMETROS     NVARCHAR(MAX)  AS JSON
	)

	IF @METODO = 'GUARDAR'
	BEGIN
		SELECT @BANCO = BANCO, @DESCRIPCION = DESCRIPCION, @CODACH = CODACH, @IDTERCERO =  IDTERCERO
		FROM OPENJSON(@PARAMETROS)
		WITH( BANCO			VARCHAR(5)	 '$.BANCO',
              DESCRIPCION	VARCHAR(30)	 '$.DESCRIPCION',
              CODACH		VARCHAR(20)	 '$.CODACH',
              IDTERCERO     VARCHAR(20)	 '$.IDTERCERO'
         )
		 --select @BANCO, @DESCRIPCION, @CODACH, @IDTERCERO

		 IF EXISTS(SELECT * FROM BCO WHERE BANCO = @BANCO)
		 BEGIN
			SELECT 'KO'OK, 'CODIGO DE BANCO YA EXISTE'ERROR
			RETURN
		 END

		 IF EXISTS(SELECT * FROM BCO WHERE IDTERCERO = @IDTERCERO)
		 BEGIN
			SELECT 'KO'OK, 'TERCERO YA SE ENCUENTRA REGISTRADP'ERROR
			RETURN
		 END

		 IF (SELECT COUNT(1) FROM @TBLERRORES) = 0
		 BEGIN
			INSERT INTO BCO(BANCO, DESCRIPCION, CODACH, IDTERCERO)
			SELECT @BANCO, UPPER(@DESCRIPCION), @CODACH, @IDTERCERO
			SELECT 'OK'OK
		 END

		RETURN
	END
	IF @METODO = 'EDITAR'
	BEGIN
		SELECT @BANCO = BANCO, @DESCRIPCION = DESCRIPCION, @CODACH = CODACH, @IDTERCERO = IDTERCERO
		FROM OPENJSON(@PARAMETROS)
		WITH( BANCO         VARCHAR(5)   '$.BANCO',
			  DESCRIPCION   VARCHAR(30)  '$.DESCRIPCION',
			  CODACH        VARCHAR(20)  '$.CODACH',
			  IDTERCERO     VARCHAR(20)  '$.IDTERCERO'
		)

		IF NOT EXISTS(SELECT * FROM BCO WHERE BANCO = @BANCO)
		BEGIN
			SELECT 'KO' OK, 'CODIGO DE BANCO NO EXISTE' ERROR
			RETURN
		END

		UPDATE BCO
		SET
			DESCRIPCION = UPPER(@DESCRIPCION),
			CODACH		= @CODACH,
			IDTERCERO	= @IDTERCERO
		WHERE BANCO		= @BANCO

		SELECT 'OK' OK

		RETURN
	END
	IF @METODO = 'ELIMINAR'
	BEGIN
		SELECT @BANCO = BANCO FROM OPENJSON(@PARAMETROS) WITH( BANCO VARCHAR(5) '$.BANCO')

		IF NOT EXISTS(SELECT * FROM BCO WHERE BANCO = @BANCO)
		BEGIN
			SELECT 'KO' OK, 'Código de banco no existe.' ERROR
			RETURN
		END
		IF EXISTS(SELECT * FROM BCO INNER JOIN BSU ON BCO.BANCO = BSU.BANCO WHERE BCO.BANCO = @BANCO)
		BEGIN
			SELECT 'KO' OK, 'No se puede eliminar un banco con sucursales' ERROR
			RETURN
		END

		DELETE BCO WHERE BANCO = @BANCO

		SELECT 'OK' OK

		RETURN
	END
	IF @METODO = 'GUARDARBSU'
	BEGIN
		SELECT @BANCO		= BANCO, 
			   @SUCURSAL	= SUCURSAL, 
			   @DESCRIPCION = DESCRIPCION, 
			   @DIRECCION	= DIRECCION,
			   @TELEFONO1	= TELEFONO1,
			   @TELEFONO2	= TELEFONO2,
			   @CONTACTO	= CONTACTO,
			   @CARGO		= CARGO
		FROM OPENJSON(@PARAMETROS)
		WITH( BANCO			VARCHAR(5)	 '$.BANCO',
              SUCURSAL		VARCHAR(2)	 '$.SUCURSAL',
              DESCRIPCION	VARCHAR(30)	 '$.DESCRIPCION',
              DIRECCION		VARCHAR(100) '$.DIRECCION',
              TELEFONO1     VARCHAR(20)	 '$.TELEFONO1',
              TELEFONO2     VARCHAR(20)	 '$.TELEFONO2',
              CONTACTO      VARCHAR(60)	 '$.CONTACTO',
              CARGO			VARCHAR(40)	 '$.CARGO'
         )
		 --select @BANCO, @DESCRIPCION, @CODACH, @IDTERCERO

		 IF EXISTS(SELECT * FROM BSU WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL)
		 BEGIN
			SELECT 'KO'OK, 'Sucursal ya existe.'ERROR
			RETURN
		 END

		INSERT INTO BSU(BANCO, SUCURSAL, DESCRIPCION, DIRECCION, TELEFONO1, TELEFONO2, CONTACTO, CARGO)
		SELECT @BANCO,@SUCURSAL, UPPER(@DESCRIPCION), UPPER(@DIRECCION), @TELEFONO1, @TELEFONO2, @CONTACTO, @CARGO

		SELECT 'OK'OK

		RETURN
	END
	IF @METODO = 'EDITARBSU'
	BEGIN
		SELECT @BANCO		= BANCO, 
			   @SUCURSAL	= SUCURSAL, 
			   @DESCRIPCION = DESCRIPCION, 
			   @DIRECCION	= DIRECCION,
			   @TELEFONO1	= TELEFONO1,
			   @TELEFONO2	= TELEFONO2,
			   @CONTACTO	= CONTACTO,
			   @CARGO		= CARGO
		FROM OPENJSON(@PARAMETROS)
		WITH( BANCO			VARCHAR(5)	 '$.BANCO',
              SUCURSAL		VARCHAR(2)	 '$.SUCURSAL',
              DESCRIPCION	VARCHAR(30)	 '$.DESCRIPCION',
              DIRECCION		VARCHAR(100) '$.DIRECCION',
              TELEFONO1     VARCHAR(20)	 '$.TELEFONO1',
              TELEFONO2     VARCHAR(20)	 '$.TELEFONO2',
              CONTACTO      VARCHAR(60)	 '$.CONTACTO',
              CARGO			VARCHAR(40)	 '$.CARGO'
         )

		IF NOT EXISTS(SELECT * FROM BSU WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL)
		 BEGIN
			SELECT 'KO'OK, 'Sucursal no existe.'ERROR
			RETURN
		 END

		 UPDATE BSU 
		 SET DESCRIPCION = @DESCRIPCION,
			 DIRECCION   = @DIRECCION,
			 TELEFONO1   = @TELEFONO1,
			 TELEFONO2   = @TELEFONO2,
			 CONTACTO    = @CONTACTO,
			 CARGO       = @CARGO
		 WHERE BANCO = @BANCO AND @SUCURSAL = SUCURSAL
		 SELECT 'OK'OK


	END
	IF @METODO = 'ELIMINARBSU'
	BEGIN
		SELECT @BANCO	 = BANCO, 
			   @SUCURSAL = SUCURSAL 
		FROM OPENJSON(@PARAMETROS) 
		WITH( BANCO			VARCHAR(5)	 '$.BANCO',
              SUCURSAL		VARCHAR(2)	 '$.SUCURSAL')

		IF NOT EXISTS(SELECT * FROM BSU WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL)
		BEGIN
			SELECT 'KO'OK, 'Sucursal no existe.'ERROR
			RETURN
		END

		DELETE BSU WHERE BANCO = @BANCO AND SUCURSAL = @SUCURSAL
		SELECT 'OK' OK

		RETURN
	END
END






