CREATE OR ALTER PROCEDURE DBO.SPQ_FSEG_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)          ,@CNSSEG VARCHAR(20)
      ,@CNSCXC VARCHAR(20)                ,@N_FACTURA VARCHAR(20)          ,@ACCION SMALLINT
      ,@PROCESO VARCHAR(20)               ,@FECHA DATETIME                 ,@F_ADVERTENCIA DATETIME
      ,@QUIENATENDIO VARCHAR(50)          ,@OBSERVACION VARCHAR(512)       ,@VALOR DECIMAL(14,2)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   
   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),  
   @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())   
   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
   WHERE USUSU.USUARIO=@USUARIO
   IF @METODO='TRAE_DATOS'     
   BEGIN         
      SELECT @CNSCXC=CNSCXC,@N_FACTURA=N_FACTURA        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSCXC  VARCHAR(20)   '$.CNSCXC',
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )

      SELECT 'OK'OK

      SELECT CNSSEG,CNSCXC, DBO.FNK_FECHA_GRINGA(FECHA)FECHA,QUIENATENDIO,OBSERVACION,VALOR,USUARIO,DBO.FNK_FECHA_GRINGA(FECHA)F_PROXIMA,
             CASE WHEN CERRADA=1 THEN 'CERRADA' ELSE 'ABIERTA' END ESTADO,N_FACTURA
      FROM FSEG
      WHERE CNSCXC=@CNSCXC
      AND N_FACTURA=CASE WHEN COALESCE(@N_FACTURA,'')<>'' THEN @N_FACTURA ELSE N_FACTURA END

      RETURN
                   
   END  
   IF @METODO='PROCESO_FSEG'     
   BEGIN         
      SELECT @CNSSEG=CNSSEG,@ACCION=ACCION
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSSEG  VARCHAR(20)   '$.CNSSEG',
      ACCION  SMALLINT   '$.ACCION'
      )
      PRINT '@CNSSEG='+@CNSSEG+'@ACCION'+STR(@ACCION)
      IF @ACCION='1'
      BEGIN
         IF EXISTS(SELECT * FROM FSEG WHERE CNSSEG=@CNSSEG AND CERRADA=0)
         BEGIN
            UPDATE FSEG SET CERRADA=1 WHERE CNSSEG=@CNSSEG AND CERRADA=0
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se encontro item de seguimiento o ya esta Cerrado '
         END
      END
      IF @ACCION='3'
      BEGIN
         IF EXISTS(SELECT * FROM FSEG WHERE CNSSEG=@CNSSEG AND CERRADA=0)
         BEGIN
            DELETE FSEG WHERE  CNSSEG=@CNSSEG AND CERRADA=0
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se encontro item de seguimiento o ya esta Cerrado '
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK 
      RETURN 
   END  
   IF @METODO='FSEG_CRUD'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT 
         @PROCESO=PROCESO,@CNSSEG=CNSSEG, @FECHA=CONVERT(DATE,FECHA), @CNSCXC=CNSCXC, @N_FACTURA=N_FACTURA,  @F_ADVERTENCIA=CONVERT(DATE,F_ADVERTENCIA),
         @QUIENATENDIO=QUIENATENDIO, @OBSERVACION=OBSERVACION, @VALOR=VALOR      
      FROM   OPENJSON (@DATOS)
      WITH   (  
         PROCESO VARCHAR(20)        '$.PROCESO',
         CNSSEG  VARCHAR(20)        '$.CNSSEG',
         FECHA VARCHAR(20)          '$.FECHA',
         CNSCXC VARCHAR(20)         '$.CNSCXC',
         N_FACTURA VARCHAR(20)      '$.N_FACTURA',
         F_ADVERTENCIA VARCHAR(20)  '$.F_ADVERTENCIA',
         QUIENATENDIO VARCHAR(50)   '$.QUIENATENDIO',
         OBSERVACION VARCHAR(512)   '$.OBSERVACION',
         VALOR DECIMAL(14,2)        '$.VALOR'      
      )  
      IF @PROCESO='Nuevo'
      BEGIN
         IF EXISTS(SELECT * FROM FCXC WHERE CNSCXC=@CNSCXC)
         BEGIN
            BEGIN TRY           
               PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')  +COALESCE(@COMPANIA,'CIA') 
               SELECT @CNSSEG=''
		         EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@FSEG', @CNSSEG OUTPUT  
               PRINT '@CNSCXC='+COALESCE(@CNSSEG,'')   
		         SELECT @CNSSEG = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSSEG))+LTRIM(RTRIM(@CNSSEG)),SPACE(1),0)
		         PRINT '@CNSCXC='+COALESCE(@CNSSEG,'')                                  
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
                    SELECT 'KO',ERROR FROM @TBLERRORES
                    RETURN
            END CATCH

            INSERT INTO FSEG(CNSSEG, CNSCXC, FECHA, IDTERCERO, F_ADVERTENCIA, QUIENATENDIO, OBSERVACION, VALOR, USUARIO, COMPANIA, CERRADA, N_FACTURA)
            SELECT @CNSSEG, CNSCXC, DBO.FNK_GETDATE(), IDTERCERO, @F_ADVERTENCIA, @QUIENATENDIO, @OBSERVACION, @VALOR, @USUARIO, @COMPANIA, 0, @N_FACTURA
            FROM FCXC WHERE CNSCXC=@CNSCXC

         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro la Cuenta de cobro o ya no tiene Saldo, verifique e intente de nuevo '
         END
      END
      IF @PROCESO='Editar'
      BEGIN
         IF EXISTS(SELECT * FROM FSEG WHERE CNSSEG=@CNSSEG)
         BEGIN
            UPDATE FSEG SET QUIENATENDIO=@QUIENATENDIO,OBSERVACION=@OBSERVACION,F_ADVERTENCIA=@F_ADVERTENCIA,VALOR=@VALOR
            WHERE CNSSEG=@CNSSEG
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro Seguimiento, Verifique e intente de nuevo '
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK 
      RETURN 
   END  
END




