CREATE OR ALTER PROCEDURE DBO.SPQ_APLICAR_IACTH @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @SEDE VARCHAR(5), @PROCESO VARCHAR(20), @COMPANIA VARCHAR(2)
DECLARE @SYS_COMPUTERNAME VARCHAR(254)
DECLARE @CNSIACTH VARCHAR(20), @IDACTIVO VARCHAR(20), @IDAREA VARCHAR(20)
DECLARE @CCOSTO VARCHAR(20), @VALOR DECIMAL(14, 2), @NROCOMPROBANTE VARCHAR(20), @ESTADO VARCHAR(20), @TIPO VARCHAR(10)
DECLARE @CUENTA VARCHAR(20), @MUEVECONTABILIDAD VARCHAR(5)

BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	IF @METODO = 'GENERAR'
	BEGIN
		BEGIN TRY
			SELECT @CNSIACTH = CNSIACTH, @NROCOMPROBANTE = NROCOMPROBANTE
			FROM OPENJSON(@PARAMETROS) WITH (CNSIACTH VARCHAR(20) '$.CNSIACTH', NROCOMPROBANTE VARCHAR(20) '$.NROCOMPROBANTE')

			SELECT @NROCOMPROBANTE = A.NROCOMPROBANTE, @IDACTIVO = A.IDACTIVO, @VALOR = A.VALOR, @ESTADO = A.ESTADO, @TIPO = B.TIPO, @MUEVECONTABILIDAD = B.
				MUEVECONTABILIDAD
			FROM IACTH A
			INNER JOIN IACTE B ON A.IDEVENTO = B.IDEVENTO
			WHERE A.CNSIACTH = @CNSIACTH

			IF @TIPO = 'Traslado'
			BEGIN
				PRINT 'Trasladando...'

				IF COALESCE(@MUEVECONTABILIDAD, '') <> 'No'
				BEGIN
					SELECT TOP 1 @CUENTA = CUENTA, @CCOSTO = CCOSTO, @IDAREA = IDAREA, @IDACTIVO = REFERENCIA3
					FROM MCH
					WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND MCH.TIPO = 'DB'

					IF EXISTS (
							SELECT 1
							FROM CUE
							WHERE CUENTA = @CUENTA
							)
					BEGIN
						UPDATE IACT
						SET CCOSTO = @CCOSTO, IDAREA = @IDAREA, CUENTA = @CUENTA, ESTADO = @ESTADO
						WHERE IDACTIVO = @IDACTIVO

						UPDATE IACTH
						SET CUENTA = @CUENTA
						WHERE IDACTIVO = @IDACTIVO
					END
				END
			END
			ELSE IF @TIPO = 'Salida'
			BEGIN
				PRINT 'Sacando...'

				UPDATE IACT
				SET ESTADO = @ESTADO
				WHERE IDACTIVO = @IDACTIVO
			END
			ELSE IF @TIPO = 'Entrada'
			BEGIN
				PRINT 'Metiendo...'

				UPDATE IACT
				SET PRECIOCOMERCIAL = PRECIOCOMERCIAL + @VALOR, ESTADO = @ESTADO
				WHERE IDACTIVO = @IDACTIVO
			END

			UPDATE IACTH
			SET APLICADA = 1
			WHERE CNSIACTH = @CNSIACTH

			EXEC SPK_GEN_DEPRECIACION @IDACTIVO
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK

		RETURN
	END
END


