CREATE OR ALTER PROCEDURE DBO.SPQ_AUTPG
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS				NVARCHAR(MAX)	,@MODELO			VARCHAR(100)    ,@METODO			VARCHAR(100)	,@USUARIO       VARCHAR(12)
        ,@GRUPO					VARCHAR(8)		,@SYS_COMPUTERNAME	VARCHAR(254)    ,@SEDE				VARCHAR(5)		,@A             INT
        ,@IDENTITY				INT				,@ID				INT				,@PROCESO			VARCHAR(20)		,@AUTPG			NVARCHAR(MAX)
        ,@ANOMES				VARCHAR(6)		,@IDAFILIADO		VARCHAR(20)		,@IDTERCEROCA		VARCHAR(20)		,@IDPLAN		VARCHAR(6)
		,@IDPESPECIAL			VARCHAR(5)		,@ESTADO			VARCHAR(20)		,@NOAUTORIZACION    VARCHAR(45)		,@FECHAAUTORIZACION     DATETIME	,@FECHAAUTORIZACION_STR VARCHAR(10)
        ,@FVENCEAUTORIZACION    DATETIME		,@FVENCEAUTORIZACION_STR VARCHAR(10),@USUARIOGENERA     VARCHAR(20)		,@FECHAGENERA   DATETIME
        ,@FECHAGENERA_STR		VARCHAR(10)		,@UNIDADATENCION    VARCHAR(20)		,@IDSEDE			VARCHAR(5)		,@IDDX			VARCHAR(10)			,@MOTIVORECHAZO			VARCHAR(20)
        ,@OBSRECHAZO			VARCHAR(2000)	,@IDSERVICIO		VARCHAR(20)		,@ENFACT			BIT				,@FACTURABLE    BIT					,@FACTURADO				BIT
		,@N_FACTURA				VARCHAR(16)		,@USUENVIA_AFACT	VARCHAR(16)		,@FECHAENVIO_AFACT  DATETIME		,@FECHAENVIO_AFACT_STR VARCHAR(10)	,@MAXAFI_XFTR			SMALLINT 
		,@IDSERVICIOPAQ			VARCHAR(20)		,@VALORPAQ			DECIMAL(14,2)	,@CNSFACTPAQ		VARCHAR(20)		,@NIT			VARCHAR(20)			,@F_FACTURA				DATETIME
		,@COMPANIA				VARCHAR(4)		,@MARCA				BIT				,@USUARIO_MARCA		VARCHAR(12)		,@TOTAL_REGISTROS INT = 0
	    ,@REGISTROS_VALIDOS		INT = 0			,@DATOS				NVARCHAR(MAX)	,@WITHMARCA			BIT				,@OBSERVACION	VARCHAR(500)		,@UNIDAD_ATENCION VARCHAR(20)
		,@PROCEPAQ				VARCHAR(20)
		,@IDCAUSAL_NO_FACT		VARCHAR(20)		,@OBS_NO_ENV_FACT	VARCHAR(500)	,@ORIGEN_NO_ENV		VARCHAR(20)
		,@FORZAR_ENVIO_DUPLICADO BIT
		,@CONFLICT_REF			VARCHAR(40)
		,@DUPCHK_INI			DATETIME
		,@DUPCHK_FIN			DATETIME
DECLARE @CITAS TABLE(CONSECUTIVO VARCHAR(20))
DECLARE @TOTAL_PACIENTES INT
BEGIN
    SET LANGUAGE Spanish
    SET DATEFORMAT dmy
   
    SELECT @A = ISJSON(@JSON)
    IF @A = 0
    BEGIN
        RAISERROR('Json: Formato Erroneo',16,1)
        RETURN
    END
    PRINT 'INGRESE A SPQ_AUTPG'
    SELECT *
    INTO #JSON
    FROM OPENJSON (@json)
    WITH (
        MODELO         VARCHAR(100)     '$.MODELO',
        METODO         VARCHAR(100)     '$.METODO',
        USUARIO        VARCHAR(12)      '$.USUARIO',
        PARAMETROS     NVARCHAR(MAX)     AS JSON
    )
   
    SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
    FROM #JSON

    DECLARE @TBLERRORES TABLE(ERROR VARCHAR(MAX))
    SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
    SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
    SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
    IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'

	IF @METODO = 'INSERTAR_PACIENTE'
	BEGIN
		SELECT
			@ANOMES = ANOMES,
			@IDTERCEROCA = IDTERCEROCA,
			@IDAFILIADO = IDAFILIADO,
			@IDPESPECIAL = IDPESPECIAL
		FROM OPENJSON(@PARAMETROS)
		WITH (
			ANOMES        VARCHAR(6)  '$.ANOMES',
			IDTERCEROCA   VARCHAR(20) '$.IDTERCEROCA',
			IDAFILIADO    VARCHAR(20) '$.IDAFILIADO',
			IDPESPECIAL   VARCHAR(5)  '$.IDPESPECIAL'
		);

		BEGIN TRY
			-- Unidad de atención (TOP 1 y control NULL)
			SELECT TOP (1) @UNIDAD_ATENCION = M.IDROL
			FROM MPE M WITH (NOLOCK)
			WHERE M.IDPESPECIAL = @IDPESPECIAL;

			IF @UNIDAD_ATENCION IS NULL
			BEGIN
				SELECT 'KO' AS OK;
				SELECT 'Programa inválido: no se encontró unidad de atención (MPE.IDROL)' AS ERROR;
				RETURN;
			END

			-- Afiliado existe y está activo
			IF NOT EXISTS (SELECT 1 FROM AFI WITH (NOLOCK) WHERE IDAFILIADO = @IDAFILIADO AND ESTADO = 'Activo')
			BEGIN
				SELECT 'KO' AS OK;
				SELECT 'Afiliado inválido o inactivo' AS ERROR;
				RETURN;
			END

			-- La entidad seleccionada debe coincidir con la administradora del afiliado
			IF EXISTS (
				SELECT 1
				FROM AFI B WITH (NOLOCK)
				WHERE B.IDAFILIADO = @IDAFILIADO
				  AND B.IDADMINISTRADORA <> @IDTERCEROCA
			)
			BEGIN
				SELECT 'KO' AS OK;
				SELECT 'El afiliado no pertenece a la aseguradora (entidad) seleccionada' AS ERROR;
				RETURN;
			END

			-- Ya registrado en este periodo y entidad (misma unidad)
			IF EXISTS (
				SELECT 1
				FROM AUTPG WITH (NOLOCK)
				WHERE IDAFILIADO = @IDAFILIADO
				  AND ANOMES = @ANOMES
				  AND UNIDADATENCION = @UNIDAD_ATENCION
				  AND IDTERCEROCA = @IDTERCEROCA
			)
			BEGIN
				SELECT 'KO' AS OK;
				SELECT 'Este paciente ya se encuentra registrado en este periodo y entidad' AS ERROR;
				RETURN;
			END

			-- Afiliado activo en el programa seleccionado
			IF NOT EXISTS (
				SELECT 1
				FROM AFIPE WITH (NOLOCK)
				WHERE IDAFILIADO = @IDAFILIADO
				  AND IDPESPECIAL = @IDPESPECIAL
				  AND ESTADO = 'Activo'
			)
			BEGIN
				SELECT 'KO' AS OK;
				SELECT 'Este paciente no se encuentra activo en el programa seleccionado' AS ERROR;
				RETURN;
			END

			-- Validación: el MISMO afiliado activo en varios programas de la misma unidad
			IF EXISTS (
				SELECT 1
				FROM AFIPE A WITH (NOLOCK)
				INNER JOIN MPE C WITH (NOLOCK) ON C.IDPESPECIAL = A.IDPESPECIAL
				WHERE A.IDAFILIADO = @IDAFILIADO
				  AND A.ESTADO = 'Activo'
				  AND C.IDROL = @UNIDAD_ATENCION
				GROUP BY A.IDAFILIADO
				HAVING COUNT(DISTINCT A.IDPESPECIAL) > 1
			)
			BEGIN
				INSERT INTO @TBLERRORES(ERROR)
				VALUES ('El paciente se encuentra activo en varios programas de esta misma unidad de atención');
			END

			-- Validación: el plan del afiliado debe pertenecer a la aseguradora seleccionada
			IF EXISTS (
				SELECT 1
				FROM AFIPE A WITH (NOLOCK)
				INNER JOIN AFI B WITH (NOLOCK) ON B.IDAFILIADO = A.IDAFILIADO
				LEFT JOIN PROT P WITH (NOLOCK) ON P.ID = A.IDPROT
				WHERE A.IDAFILIADO = @IDAFILIADO
				  AND A.IDPESPECIAL = @IDPESPECIAL
				  AND A.ESTADO = 'Activo'
				  AND B.ESTADO = 'Activo'
				  AND NOT EXISTS (
					  SELECT 1
					  FROM PPT WITH (NOLOCK)
					  WHERE PPT.IDTERCERO = @IDTERCEROCA
						AND PPT.IDPLAN = COALESCE(P.IDPLAN, B.IDPLAN)
						AND PPT.ESTADO = 'Activo'
				  )
			)
			BEGIN
				INSERT INTO @TBLERRORES(ERROR)
				SELECT TOP (1) 'El afiliado tiene un plan que no pertenece a la aseguradora seleccionada. Plan: ' +
					   COALESCE(P.IDPLAN, B.IDPLAN)
				FROM AFIPE A WITH (NOLOCK)
				INNER JOIN AFI B WITH (NOLOCK) ON B.IDAFILIADO = A.IDAFILIADO
				LEFT JOIN PROT P WITH (NOLOCK) ON P.ID = A.IDPROT
				WHERE A.IDAFILIADO = @IDAFILIADO
				  AND A.IDPESPECIAL = @IDPESPECIAL
				  AND A.ESTADO = 'Activo'
				  AND B.ESTADO = 'Activo'
			END

			IF (SELECT COUNT(*) FROM @TBLERRORES) <= 0
			BEGIN
				INSERT INTO AUTPG (ANOMES, IDAFILIADO, IDTERCEROCA, IDPLAN, IDPESPECIAL, UNIDADATENCION,
					ESTADO, USUARIOGENERA, FECHAGENERA, IDDX, IDSEDE
				)
				SELECT @ANOMES, A.IDAFILIADO, @IDTERCEROCA, COALESCE(P.IDPLAN, B.IDPLAN), A.IDPESPECIAL,
					C.IDROL, 'Generado', @USUARIO, GETDATE(), A.DXPE, B.IDSEDE
				FROM AFIPE A
				INNER JOIN AFI B ON B.IDAFILIADO = A.IDAFILIADO
				INNER JOIN MPE C ON C.IDPESPECIAL = A.IDPESPECIAL
				LEFT JOIN PROT P ON P.ID = A.IDPROT
				WHERE A.IDAFILIADO = @IDAFILIADO
				  AND A.IDPESPECIAL = @IDPESPECIAL
				  AND C.IDROL = @UNIDAD_ATENCION
				  AND A.ESTADO = 'Activo'
				  AND B.ESTADO = 'Activo'
				  AND NOT EXISTS (
					  SELECT 1
					  FROM AUTPG D
					  WHERE D.ANOMES = @ANOMES
						AND D.IDTERCEROCA = @IDTERCEROCA
						AND D.IDAFILIADO = A.IDAFILIADO
						AND D.UNIDADATENCION = C.IDROL
				  )
			END
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
		END CATCH

		IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
		BEGIN
			SELECT 'KO' AS OK;
			SELECT ERROR FROM @TBLERRORES;
			RETURN;
		END

		SELECT 'OK' AS OK;
		RETURN;
	END

    IF @METODO = 'ENVIARA_FACT'
    BEGIN
        PRINT 'ENVIARA_FACT'
        BEGIN TRY
            SELECT @ID = JSON_VALUE(@PARAMETROS ,'$.ID')
            SELECT @A = JSON_VALUE(@PARAMETROS ,'$.ACCION')

			IF @A = 1 AND EXISTS (SELECT 1 FROM AUTPG WITH (NOLOCK) WHERE ID = @ID AND COALESCE(NO_ENVIAR_FACT, 0) = 1)
			BEGIN
				SELECT 'KO' AS OK;
				SELECT 'El registro está marcado como No enviado a facturación. Revise la causal y Reactivar para facturar.' AS ERROR;
				RETURN;
			END

			SET @FORZAR_ENVIO_DUPLICADO = IIF(COALESCE(TRY_CAST(JSON_VALUE(@PARAMETROS, '$.FORZAR_ENVIO_DUPLICADO') AS TINYINT), 0) <> 0, 1, 0);
			IF @A = 1 AND COALESCE(@FORZAR_ENVIO_DUPLICADO, 0) = 0
			BEGIN
				SELECT @IDAFILIADO = IDAFILIADO, @ANOMES = ANOMES FROM AUTPG WITH (NOLOCK) WHERE ID = @ID;
				IF COALESCE(@IDAFILIADO, '') <> '' AND COALESCE(@ANOMES, '') <> ''
				BEGIN
					SET @CONFLICT_REF = NULL;
					SELECT TOP (1) @CONFLICT_REF = CONVERT(VARCHAR(20), AP.ID)
					FROM AUTPG AP WITH (NOLOCK)
					WHERE AP.IDAFILIADO = @IDAFILIADO
					  AND AP.ANOMES = @ANOMES
					  AND AP.ID <> @ID
					  AND (COALESCE(AP.ENFACT, 0) = 1 OR COALESCE(AP.FACTURADO, 0) = 1)
					  AND COALESCE(AP.NO_ENVIAR_FACT, 0) = 0
					ORDER BY AP.ID;
					IF @CONFLICT_REF IS NOT NULL
					BEGIN
						SELECT 'KO' AS OK;
						SELECT ERROR_CODE = 'DUPLICADO_FACTURACION_MISMO_PERIODO'
							, ERROR = CONCAT(N'Otro registro de programa (AUTPG) del mismo paciente y período ', @ANOMES, N' ya está en facturación. Referencia AUTPG.ID=', @CONFLICT_REF, N'. Utilice confirmación forzada si autoriza continuar.')
							, ORIGEN_CONFLICTO = 'PROGRAMA'
							, ID_CONFLICTO = @CONFLICT_REF
							, ANOMES = @ANOMES
							, IDAFILIADO = @IDAFILIADO;
						RETURN;
					END
					SET @DUPCHK_INI = TRY_CONVERT(DATETIME, CONCAT(@ANOMES, '01'), 112);
					SET @DUPCHK_FIN = DATEADD(MONTH, 1, @DUPCHK_INI);
					SET @CONFLICT_REF = NULL;
					IF @DUPCHK_INI IS NOT NULL
					BEGIN
						SELECT TOP (1) @CONFLICT_REF = C.CONSECUTIVO
						FROM CIT C WITH (NOLOCK)
						WHERE C.IDAFILIADO = @IDAFILIADO
						  AND C.FECHA >= @DUPCHK_INI AND C.FECHA < @DUPCHK_FIN
						  AND (COALESCE(C.ENFACT, 0) = 1 OR COALESCE(C.FACTURADA, 0) = 1)
						  AND COALESCE(C.NO_ENVIAR_FACT, 0) = 0
						ORDER BY C.CONSECUTIVO;
					END
					IF @CONFLICT_REF IS NOT NULL
					BEGIN
						SELECT 'KO' AS OK;
						SELECT ERROR_CODE = 'DUPLICADO_FACTURACION_MISMO_PERIODO'
							, ERROR = CONCAT(N'Existe cita (CIT) en facturación o facturada en el mismo período ', @ANOMES, N'. Referencia CIT.CONSECUTIVO=', @CONFLICT_REF, N'. Utilice confirmación forzada si autoriza continuar.')
							, ORIGEN_CONFLICTO = 'EVENTO'
							, ID_CONFLICTO = @CONFLICT_REF
							, ANOMES = @ANOMES
							, IDAFILIADO = @IDAFILIADO;
						RETURN;
					END
				END
			END

            -- Registrar en log antes de actualizar
            INSERT INTO AUTPG_LOG (IDAUTPG, ACCION, USUARIO, FECHA, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO)
            SELECT ID, 
                CASE WHEN @A=1 THEN 'ENVIAR' ELSE 'REGRESAR' END AS ACCION, @USUARIO, GETDATE(), USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO
            FROM AUTPG WHERE ID=@ID AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') AND COALESCE(AUTPG.FACTURADO, 0)=0 AND COALESCE(AUTPG.VALORPAQ,0)>0
				AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0

			UPDATE AUTPG SET ENFACT = @A, USUENVIA_AFACT=IIF(@A=1, @USUARIO, NULL), FECHAENVIO_AFACT=IIF(@A=1, GETDATE(), NULL), VALORCOPAGO=COALESCE(X.VALORCOPAGO,0)
            FROM AUTPG
            INNER JOIN AFI ON AFI.IDAFILIADO=AUTPG.IDAFILIADO AND AFI.ESTADO='Activo'
            LEFT JOIN (
                SELECT A.IDTERCEROCA, IDPLAN, IDAFILIADO, A.ANOMES, A.FECHA, A.VALORCOPAGO
                    , ITEM=ROW_NUMBER() OVER (
                        PARTITION BY A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES
                        ORDER BY
                            CASE WHEN A.PROCEDENCIA = 'CIT' THEN 0 WHEN A.PROCEDENCIA = 'AUT' THEN 1 ELSE 2 END,
                            A.TIPO_CITA ASC,
                            A.FECHA DESC,
                            A.NOADMISION DESC,
                            A.NOPRESTACION DESC,
                            A.NOITEM DESC
                    )
                FROM VWK_CARGOS_HADMAUTCIT_ART A
                WHERE A.VALORCOPAGO>0 AND A.ENCAJA=1
            ) X ON X.IDAFILIADO=AUTPG.IDAFILIADO AND X.IDTERCEROCA=AUTPG.IDTERCEROCA AND X.IDPLAN=AUTPG.IDPLAN AND X.ITEM=1 AND AUTPG.ANOMES=X.ANOMES AND X.FECHA<GETDATE()
            WHERE ID=@ID AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') AND COALESCE(AUTPG.FACTURADO, 0)=0 AND COALESCE(AUTPG.VALORPAQ,0)>0
				AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0

            UPDATE AUTPG SET FECHAATENCION=COALESCE(X.FECHAATENCION, CONVERT(DATE, AUTPG.ANOMES + '01'))
            FROM AUTPG
            INNER JOIN AFI ON AFI.IDAFILIADO=AUTPG.IDAFILIADO AND AFI.ESTADO='Activo'
            LEFT JOIN (
                SELECT A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES, A.FECHA, A.VALORCOPAGO, A.FECHA AS FECHAATENCION
                    , ITEM=ROW_NUMBER() OVER (
                        PARTITION BY A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES 
                        ORDER BY A.TIPO_CITA ASC, A.FECHA DESC
                    )
                FROM VWK_CARGOS_HADMAUTCIT_ART A
                WHERE A.FECHA<GETDATE()
            ) X ON X.IDAFILIADO=AUTPG.IDAFILIADO AND X.IDTERCEROCA=AUTPG.IDTERCEROCA AND X.IDPLAN=AUTPG.IDPLAN AND X.ITEM=1 AND AUTPG.ANOMES=X.ANOMES
            WHERE ID=@ID 
                AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') 
                AND COALESCE(AUTPG.FACTURADO, 0)=0 
                AND COALESCE(AUTPG.VALORPAQ,0)>0
				AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0
        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END

    IF @METODO = 'ENVIARA_FACT_TODOS'
    BEGIN
        PRINT 'ENVIARA_FACT_TODOS'
        BEGIN TRY
		    SELECT @IDTERCEROCA=IDTERCERO, @UNIDAD_ATENCION=UNIDAD_ATENCION, @ANOMES=PERIODO, @IDSEDE=IDSEDE
            FROM OPENJSON (@PARAMETROS)
            WITH(
			    IDTERCERO   VARCHAR(20)   '$.IDTERCERO', IDPLAN   VARCHAR(6)   '$.IDPLAN', PERIODO   VARCHAR(6)   '$.PERIODO'
			    , IDSEDE   VARCHAR(5)   '$.IDSEDE', UNIDAD_ATENCION   VARCHAR(20)   '$.UNIDAD_ATENCION'
            )

		    IF COALESCE(@IDTERCEROCA,'') = '' OR COALESCE(@UNIDAD_ATENCION,'') = '' OR COALESCE(@ANOMES,'') = ''
		    BEGIN
			    SELECT 'KO' OK
			    SELECT 'EXISTEN VARIABLES OBLIGATORIAS QUE NO SE HAN SUMINISTRADO, POR FAVOR CONTACTE AL EQUIPO DE SISTEMAS.' ERROR
			    RETURN
		    END

            -- Registrar en log antes de actualizar (masivo)
            INSERT INTO AUTPG_LOG (IDAUTPG, ACCION, USUARIO, FECHA, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO)
            SELECT ID, 'ENVIAR', @USUARIO, GETDATE(), @USUARIO, GETDATE(), ENFACT, FACTURABLE, FACTURADO, ESTADO
            FROM AUTPG
            WHERE AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.ANOMES=@ANOMES AND AUTPG.UNIDADATENCION=@UNIDAD_ATENCION AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') 
                AND COALESCE(AUTPG.ENFACT,0) = 0 AND COALESCE(AUTPG.FACTURABLE, 1) = 1  AND COALESCE(AUTPG.FACTURADO, 0)=0 AND COALESCE(AUTPG.VALORPAQ,0)>0
				AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0

			UPDATE AUTPG SET ENFACT = 1, FACTURABLE = 1, USUENVIA_AFACT=@USUARIO, FECHAENVIO_AFACT=GETDATE(), VALORCOPAGO=COALESCE(X.VALORCOPAGO,0)
            FROM AUTPG
            INNER JOIN AFI ON AFI.IDAFILIADO=AUTPG.IDAFILIADO AND AFI.ESTADO='Activo'
            LEFT JOIN (
                SELECT A.IDTERCEROCA, IDPLAN, IDAFILIADO, A.ANOMES, A.FECHA, A.VALORCOPAGO
                    , ITEM=ROW_NUMBER() OVER (
                        PARTITION BY A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES
                        ORDER BY
                            CASE WHEN A.PROCEDENCIA = 'CIT' THEN 0 WHEN A.PROCEDENCIA = 'AUT' THEN 1 ELSE 2 END,
                            A.TIPO_CITA ASC,
                            A.FECHA DESC,
                            A.NOADMISION DESC,
                            A.NOPRESTACION DESC,
                            A.NOITEM DESC
                    )
                FROM VWK_CARGOS_HADMAUTCIT_ART A
                WHERE A.VALORCOPAGO>0 AND A.ENCAJA=1
            ) X ON X.IDAFILIADO=AUTPG.IDAFILIADO AND X.IDTERCEROCA=AUTPG.IDTERCEROCA AND X.IDPLAN=AUTPG.IDPLAN AND X.ITEM=1 AND AUTPG.ANOMES=X.ANOMES AND X.FECHA<GETDATE()
		    WHERE AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.ANOMES=@ANOMES AND AUTPG.UNIDADATENCION=@UNIDAD_ATENCION AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') 
            AND COALESCE(AUTPG.ENFACT,0) = 0 AND COALESCE(AUTPG.FACTURABLE, 1) = 1  AND COALESCE(AUTPG.FACTURADO, 0)=0 AND COALESCE(AUTPG.VALORPAQ,0)>0
			AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0

            SELECT @TOTAL_PACIENTES = @@ROWCOUNT

            UPDATE AUTPG SET FECHAATENCION=COALESCE(X.FECHAATENCION, CONVERT(DATE, AUTPG.ANOMES + '01'))
            FROM AUTPG
            INNER JOIN AFI ON AFI.IDAFILIADO=AUTPG.IDAFILIADO AND AFI.ESTADO='Activo'
            LEFT JOIN (
                SELECT A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES, A.FECHA, A.VALORCOPAGO, A.FECHA AS FECHAATENCION
                    , ITEM=ROW_NUMBER() OVER (
                        PARTITION BY A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES 
                        ORDER BY A.TIPO_CITA ASC, A.FECHA DESC
                    )
                FROM VWK_CARGOS_HADMAUTCIT_ART A
                WHERE A.FECHA<GETDATE()
            ) X ON X.IDAFILIADO=AUTPG.IDAFILIADO AND X.IDTERCEROCA=AUTPG.IDTERCEROCA AND X.IDPLAN=AUTPG.IDPLAN AND X.ITEM=1 AND AUTPG.ANOMES=X.ANOMES
		    WHERE AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.ANOMES=@ANOMES AND AUTPG.UNIDADATENCION=@UNIDAD_ATENCION AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') 
            AND COALESCE(AUTPG.ENFACT,0) = 0 AND COALESCE(AUTPG.FACTURABLE, 1) = 1  AND COALESCE(AUTPG.FACTURADO, 0)=0 AND COALESCE(AUTPG.VALORPAQ,0)>0
			AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0
            
		END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK, TOTAL_REGISTROS = @TOTAL_PACIENTES
        SELECT '' OK
        SELECT Error='Paciente no enviado a facturacion porque no esta autorizado, paciente no activo, ya esta en facturacion, no es facturable o en contratacion no tiene configurado el valor del paquete'
            ,AFI.DOCIDAFILIADO DocIdAfiliado
            ,AFI.NOMBREAFI NombreAfiliado
        FROM AUTPG
            LEFT JOIN AFI ON AFI.IDAFILIADO=AUTPG.IDAFILIADO
		    WHERE AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.ANOMES=@ANOMES AND AUTPG.UNIDADATENCION=@UNIDAD_ATENCION 
            AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') 
            AND COALESCE(AUTPG.ENFACT,0) = 0
			AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0            
        RETURN
    END

    IF @METODO = 'RECHAZAR_FACTURACION'
    BEGIN
        DECLARE @WHERE VARCHAR(1024), @CMD VARCHAR(2048)
        DECLARE @TEMP_ID INT, @TEMP_USUENVIA VARCHAR(16), @TEMP_FECHAENVIO DATETIME, @TEMP_ENFACT BIT, @TEMP_FACTURABLE BIT, @TEMP_ESTADO VARCHAR(30)
        PRINT 'RECHAZAR_FACTURACION'
        BEGIN TRY                      
            SELECT @ID = JSON_VALUE(@PARAMETROS ,'$.ID'), 
                @MOTIVORECHAZO = JSON_VALUE(@PARAMETROS ,'$.MOTIVORECHAZO'), 
                @OBSRECHAZO = JSON_VALUE(@PARAMETROS ,'$.OBSRECHAZO'),
                @MARCA = JSON_VALUE(@PARAMETROS ,'$.MASIVO'),
                @WHERE = JSON_VALUE(@PARAMETROS ,'$.WHERE')

            IF @MARCA=1
            BEGIN
                -- Registrar en log antes de actualizar (masivo).
                -- Crear tabla temporal para almacenar los IDs que se van a rechazar
                DECLARE @SQL_LOG NVARCHAR(MAX)
                IF OBJECT_ID('tempdb..#TEMP_RECHAZAR') IS NOT NULL
                    DROP TABLE #TEMP_RECHAZAR
                CREATE TABLE #TEMP_RECHAZAR (
                    ID               INT NOT NULL,
                    USUENVIA_AFACT   VARCHAR(16) NULL,
                    FECHAENVIO_AFACT DATETIME NULL,
                    ENFACT           BIT NULL,
                    FACTURABLE       BIT NULL,
                    FACTURADO        BIT NULL,
                    ESTADO           VARCHAR(30) NULL
                )
                SELECT @SQL_LOG = N'INSERT INTO #TEMP_RECHAZAR (ID, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO)
                SELECT ID, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO
                FROM AUTPG
                WHERE FACTURABLE=1 AND ENFACT=1 AND COALESCE(FACTURADO,0)=0 AND COALESCE(N_FACTURA,'''')='''' AND ESTADO IN (''Autorizado'',''Autorizado Recuperado'')'
                IF COALESCE(@WHERE,'') <> ''
                    SELECT @SQL_LOG = @SQL_LOG + N' AND ' + @WHERE
                EXEC sp_executesql @SQL_LOG
                
                INSERT INTO AUTPG_LOG (IDAUTPG, ACCION, USUARIO, FECHA, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, MOTIVORECHAZO, OBSRECHAZO)
                SELECT ID, 'RECHAZAR', @USUARIO, GETDATE(), USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, @MOTIVORECHAZO, @OBSRECHAZO
                FROM #TEMP_RECHAZAR
                
                -- Conservar USUENVIA_AFACT y FECHAENVIO_AFACT (trazabilidad del envío original a facturación).
                SELECT @CMD='UPDATE AUTPG SET ENFACT = 0, FACTURABLE = 0, ESTADO=''Rechazado Facturacion''
                , MOTIVORECHAZO='''+@MOTIVORECHAZO+''', OBSRECHAZO='''+@OBSRECHAZO+'''
                WHERE FACTURABLE=1 AND ENFACT=1 AND COALESCE(FACTURADO,0)=0 AND COALESCE(N_FACTURA,'''')='''' AND ESTADO IN  (''Autorizado'',''Autorizado Recuperado'')'
                IF COALESCE(@WHERE,'') <> ''
                    SELECT @CMD = @CMD + ' AND ' + @WHERE
                EXEC (@CMD)
                
                DROP TABLE #TEMP_RECHAZAR
            END
            ELSE
            BEGIN
                -- Registrar en log antes de actualizar (individual)
                SELECT @TEMP_USUENVIA=USUENVIA_AFACT, @TEMP_FECHAENVIO=FECHAENVIO_AFACT, @TEMP_ENFACT=ENFACT, @TEMP_FACTURABLE=FACTURABLE, @TEMP_ESTADO=ESTADO
                FROM AUTPG WHERE ID=@ID
                
                INSERT INTO AUTPG_LOG (IDAUTPG, ACCION, USUARIO, FECHA, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, MOTIVORECHAZO, OBSRECHAZO)
                SELECT ID, 'RECHAZAR', @USUARIO, GETDATE(), USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, @MOTIVORECHAZO, @OBSRECHAZO
                FROM AUTPG WHERE ID=@ID
                
                UPDATE AUTPG SET ENFACT = 0, FACTURABLE = 0, ESTADO='Rechazado Facturacion', MOTIVORECHAZO=@MOTIVORECHAZO, OBSRECHAZO=@OBSRECHAZO WHERE ID=@ID
            END
        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END

    IF @METODO = 'EXPORTAR_EXCEL'
    BEGIN
        PRINT 'EXPORTAR_EXCEL'
        BEGIN TRY
		    SELECT @IDTERCEROCA=IDTERCERO, @IDPLAN=IDPLAN, @ANOMES=PERIODO, @IDSEDE=IDSEDE
            FROM OPENJSON (@PARAMETROS)
            WITH(
			    IDTERCERO   VARCHAR(20)   '$.IDTERCERO', IDPLAN   VARCHAR(6)   '$.IDPLAN', PERIODO   VARCHAR(6)   '$.PERIODO'
			    , IDSEDE   VARCHAR(5)   '$.IDSEDE'
            )

            -- Actualizar FECHAATENCION antes de exportar (COMENTADO - Se actualiza manualmente con el botón)
            /*
            UPDATE AUTPG SET FECHAATENCION=COALESCE(X.FECHAATENCION, CONVERT(DATE, AUTPG.ANOMES + '01'))
            FROM AUTPG
            INNER JOIN AFI ON AFI.IDAFILIADO=AUTPG.IDAFILIADO AND AFI.ESTADO='Activo'
            LEFT JOIN (
                SELECT A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES, A.FECHA, A.VALORCOPAGO, A.FECHA AS FECHAATENCION
                    , ITEM=ROW_NUMBER() OVER (
                        PARTITION BY A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES 
                        ORDER BY A.TIPO_CITA ASC, A.FECHA DESC
                    )
                FROM VWK_CARGOS_HADMAUTCIT_ART A
                WHERE A.FECHA<GETDATE()
            ) X ON X.IDAFILIADO=AUTPG.IDAFILIADO 
                AND X.IDTERCEROCA=AUTPG.IDTERCEROCA 
                AND X.IDPLAN=AUTPG.IDPLAN 
                AND X.ITEM=1 
                AND AUTPG.ANOMES=X.ANOMES
            WHERE AUTPG.FACTURABLE = 1
                AND AUTPG.ENFACT = 1
                AND (@ANOMES IS NULL OR AUTPG.ANOMES = @ANOMES)
                AND (@IDTERCEROCA IS NULL OR AUTPG.IDTERCEROCA = @IDTERCEROCA)
                AND (@IDPLAN IS NULL OR AUTPG.IDPLAN = @IDPLAN)
                AND (@IDSEDE IS NULL OR AUTPG.IDSEDE = @IDSEDE)
                AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado')
                AND COALESCE(AUTPG.FACTURADO,0) = 0
                AND COALESCE(AUTPG.MARCA, 0) = 0
                AND COALESCE(AUTPG.VALORPAQ,0)>0
            */

		    SELECT 'OK' OK 
            SELECT AUTPG.ID, AUTPG.ANOMES, AFI.TIPO_DOC, AFI.DOCIDAFILIADO, COALESCE(AFI.PAPELLIDO,'') PAPELLIDO, COALESCE(AFI.SAPELLIDO,'') SAPELLIDO, COALESCE(AFI.PNOMBRE,'') PNOMBRE
                , COALESCE(AFI.SNOMBRE,'') SNOMBRE, AUTPG.NOAUTORIZACION, COALESCE(AUTPG.N_FACTURA,'') N_FACTURA, TER.RAZONSOCIAL AS ASEGURADORA, PLN.DESCPLAN, SED.DESCRIPCION AS SEDE,  ROL.DESCRIPCION AS UNIDADATENCION,SER.DESCSERVICIO SERVICIO, AUTPG.FECHAATENCION, AUTPG.ESTADO
				, COALESCE(AUTPG.VALORPAQ,0) AS SUBTOTAL, COALESCE(AUTPG.VALORCOPAGO,0) VALORCOPAGO, COALESCE(AUTPG.VALORPAQ,0)-COALESCE(AUTPG.VALORCOPAGO,0) AS VALORNETO
		    FROM AUTPG
		    INNER JOIN AFI ON AUTPG.IDAFILIADO = AFI.IDAFILIADO
		    LEFT JOIN PLN ON AUTPG.IDPLAN = PLN.IDPLAN
		    LEFT JOIN TER ON AUTPG.IDTERCEROCA = TER.IDTERCERO
		    LEFT JOIN SED ON AUTPG.IDSEDE = SED.IDSEDE
		    LEFT JOIN MPE ON MPE.IDPESPECIAL = AUTPG.IDPESPECIAL
		    LEFT JOIN ROL ON ROL.IDROL = MPE.IDROL
			LEFT JOIN SER ON SER.IDSERVICIO = AUTPG.IDSERVICIO
		    WHERE AUTPG.FACTURABLE = 1
				AND AUTPG.ENFACT = 1
			    AND (@ANOMES IS NULL OR AUTPG.ANOMES = @ANOMES)
			    AND (@IDTERCEROCA IS NULL OR AUTPG.IDTERCEROCA = @IDTERCEROCA)
			    AND (@IDPLAN IS NULL OR AUTPG.IDPLAN = @IDPLAN)
			    AND (@IDSEDE IS NULL OR AUTPG.IDSEDE = @IDSEDE)
				AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado')
				AND COALESCE(AUTPG.FACTURADO,0) = 0
			    AND COALESCE(AUTPG.MARCA, 0) = 0
        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END
   
    IF @METODO = 'EXPORTAR_FORMATO_AUTPG'
    BEGIN
        PRINT 'EXPORTAR_EXCEL'
        BEGIN TRY
		    SELECT @IDTERCEROCA=IDTERCERO, @ANOMES=ANOMES
            FROM OPENJSON (@PARAMETROS)
            WITH(
                ANOMES              VARCHAR(6)   '$.ANOMES'
			    ,IDTERCERO          VARCHAR(20)   '$.IDTERCERO'
                ,UNIDAD_ATENCION    VARCHAR(6)   '$.UNIDAD_ATENCION'
            )
        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END

	IF @METODO = 'PROCESAR_IMPORTACION_EXCEL'
	BEGIN
		PRINT 'PROCESAR_IMPORTACION_EXCEL'
		BEGIN TRY

			SELECT @IDTERCEROCA = JSON_VALUE(@PARAMETROS,'$.IDTERCERO')
			SELECT @IDPLAN = JSON_VALUE(@PARAMETROS,'$.IDPLAN')
			SELECT @ANOMES = JSON_VALUE(@PARAMETROS,'$.PERIODO')
			SELECT @IDSEDE = JSON_VALUE(@PARAMETROS,'$.IDSEDE')
			SELECT @USUARIO_MARCA = JSON_VALUE(@PARAMETROS,'$.USUARIO')

			PRINT '@IDTERCEROCA >'  + COALESCE(@IDTERCEROCA,' SIN @IDTERCEROCA')
			PRINT '@IDPLAN >'  + COALESCE(@IDPLAN,' SIN @IDPLAN')
			PRINT '@ANOMES >'  + COALESCE(@ANOMES,' SIN @ANOMES')
			PRINT '@IDSEDE >'  + COALESCE(@IDSEDE,' SIN @IDSEDE')
			PRINT '@USUARIO_MARCA >'  + COALESCE(@USUARIO_MARCA,' SIN @USUARIO_MARCA')

			SELECT @DATOS = DATOS
			FROM OPENJSON(@PARAMETROS)
			WITH (
				DATOS NVARCHAR(MAX) AS JSON
			)

			SELECT	ID, TIPO_DOC, DOCIDAFILIADO, PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE, NOAUTORIZACION, ASEGURADORA, DESCPLAN, ESTADO
			INTO #EXCEL_IMPORT
			FROM OPENJSON(@DATOS)
			WITH (
				ID                  INT    '$.ID',
				TIPO_DOC			VARCHAR(3)     '$.TIPO_DOC',
				DOCIDAFILIADO       VARCHAR(20)     '$.DOCIDAFILIADO',
				PAPELLIDO           VARCHAR(30)    '$.PAPELLIDO',
				SAPELLIDO           VARCHAR(30)    '$.SAPELLIDO',
				PNOMBRE				VARCHAR(30)    '$.PNOMBRE',
				SNOMBRE				VARCHAR(30)    '$.SNOMBRE',
				NOAUTORIZACION      VARCHAR(45)     '$.NOAUTORIZACION',
				ASEGURADORA         VARCHAR(120)    '$.ASEGURADORA',
				DESCPLAN            VARCHAR(45)    '$.DESCPLAN',
				ESTADO              VARCHAR(20)     '$.ESTADO'
			)
		
			SET @TOTAL_REGISTROS = @@ROWCOUNT

			UPDATE AUTPG SET MARCA = 0, USUARIO_MARCA = NULL
			WHERE USUARIO_MARCA = @USUARIO_MARCA

			UPDATE AUTPG SET MARCA = 1, USUARIO_MARCA = @USUARIO_MARCA
			FROM AUTPG A
			INNER JOIN #EXCEL_IMPORT E ON A.ID = E.ID
			WHERE A.IDTERCEROCA = @IDTERCEROCA
				AND A.IDPLAN = @IDPLAN
				AND A.ANOMES = @ANOMES
				AND (@IDSEDE IS NULL OR A.IDSEDE = @IDSEDE)
				AND COALESCE(A.FACTURABLE,0) = 1
				AND COALESCE(A.FACTURADO,0) = 0
                AND A.VALORPAQ>0

			SET @REGISTROS_VALIDOS = @@ROWCOUNT
			DROP TABLE #EXCEL_IMPORT
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK, @TOTAL_REGISTROS AS TOTAL_REGISTROS, @REGISTROS_VALIDOS AS REGISTROS_VALIDOS
		RETURN
	END

	IF @METODO = 'MARCAR_TODOS_IMPORTADOS'
	BEGIN
		PRINT 'MARCAR_TODOS_IMPORTADOS'
		BEGIN TRY
			SELECT @USUARIO_MARCA = JSON_VALUE(@PARAMETROS,'$.USUARIO')
			SELECT @MARCA = CAST(JSON_VALUE(@PARAMETROS,'$.MARCA') AS BIT)

			UPDATE AUTPG SET MARCA = @MARCA
			WHERE USUARIO_MARCA = @USUARIO_MARCA AND FACTURADO = 0 
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK, @@ROWCOUNT AS REGISTROS_ACTUALIZADOS
		RETURN
	END

	IF @METODO = 'LIMPIAR_IMPORTACION'
	BEGIN
		PRINT 'LIMPIAR_IMPORTACION'
		BEGIN TRY
			SELECT @USUARIO_MARCA = JSON_VALUE(@PARAMETROS,'$.USUARIO')
			UPDATE AUTPG SET MARCA = 0, USUARIO_MARCA = NULL
			WHERE USUARIO_MARCA = @USUARIO_MARCA
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK, @@ROWCOUNT AS REGISTROS_LIMPIADOS
		RETURN
	END

	IF @METODO = 'ELIMINAR_REGISTRO_IMPORTADO'
	BEGIN
		PRINT 'ELIMINAR_REGISTRO_IMPORTADO'
		BEGIN TRY
			SELECT @ID = JSON_VALUE(@PARAMETROS,'$.ID')
			SELECT @USUARIO_MARCA = JSON_VALUE(@PARAMETROS,'$.USUARIO')
			UPDATE AUTPG SET MARCA = 0, USUARIO_MARCA = NULL
			WHERE ID = @ID AND USUARIO_MARCA = @USUARIO_MARCA AND FACTURADO = 0
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK, @@ROWCOUNT AS REGISTROS_ELIMINADOS
		RETURN
	END

    IF @METODO = 'VALIDADIAN_AUTPG'
	BEGIN
		PRINT 'VALIDADIAN_AUTPG'
		BEGIN TRY
			SELECT @IDTERCEROCA=IDTERCERO, @IDPLAN=IDPLAN, @ANOMES=PERIODO, @IDSEDE=IDSEDE, @WITHMARCA=WITHMARCA
			FROM OPENJSON (@PARAMETROS)
			WITH(
				IDTERCERO   VARCHAR(20)   '$.IDTERCERO', IDPLAN   VARCHAR(6)   '$.IDPLAN', PERIODO   VARCHAR(6)   '$.PERIODO'
				, IDSEDE   VARCHAR(5)   '$.IDSEDE', WITHMARCA BIT
			)

			DECLARE @CONTINUA_DIAN SMALLINT = 1
			DECLARE @SedeVal VARCHAR(5), @CantFactVal INT

			IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) <> 'SI'
			BEGIN
				SELECT 'OK' OK, 1 CONTINUA
				RETURN
			END

			;WITH PacientesOrdenados AS (
				SELECT
					AUTPG.IDSEDE,
					ROW_NUMBER() OVER (PARTITION BY AUTPG.IDSEDE ORDER BY AUTPG.IDAFILIADO) AS RowNum,
					COALESCE(NULLIF(PPT.MAXAFI_XFTR, 0), 20) AS MAXAFI_XFTR
				FROM AUTPG WITH (NOLOCK)
				INNER JOIN PPT WITH (NOLOCK) ON PPT.IDTERCERO = AUTPG.IDTERCEROCA AND PPT.IDPLAN = AUTPG.IDPLAN
				WHERE AUTPG.ANOMES = @ANOMES
					AND AUTPG.IDTERCEROCA = @IDTERCEROCA
					AND AUTPG.IDPLAN = @IDPLAN
					AND (@IDSEDE IS NULL OR @IDSEDE = AUTPG.IDSEDE)
					AND (AUTPG.FACTURADO = 0 OR AUTPG.FACTURADO IS NULL)
					AND AUTPG.FACTURABLE = 1
					AND AUTPG.ENFACT = 1
					AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado')
					AND (@WITHMARCA IS NULL OR (AUTPG.MARCA = 1 AND AUTPG.USUARIO_MARCA = @USUARIO))
					AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0
			),
			FacturasPorSede AS (
				SELECT
					IDSEDE,
					COUNT(DISTINCT CONCAT(IDSEDE, '-', (RowNum - 1) / NULLIF(MAXAFI_XFTR, 0))) AS CANTIDAD_FACTURAS
				FROM PacientesOrdenados
				GROUP BY IDSEDE
			)
			SELECT IDSEDE, CANTIDAD_FACTURAS
			INTO #ValidaDianSedes
			FROM FacturasPorSede

			IF NOT EXISTS (SELECT 1 FROM #ValidaDianSedes)
			BEGIN
				DROP TABLE #ValidaDianSedes
				SELECT 'OK' OK, 1 CONTINUA
				RETURN
			END

			DECLARE cur_valida_autpg CURSOR LOCAL FAST_FORWARD FOR
				SELECT IDSEDE, CANTIDAD_FACTURAS FROM #ValidaDianSedes

			OPEN cur_valida_autpg
			FETCH NEXT FROM cur_valida_autpg INTO @SedeVal, @CantFactVal

			WHILE @@FETCH_STATUS = 0
			BEGIN
				DECLARE @ContinuaSede SMALLINT = 1
				EXEC SPQ_VALIDADIAN2 @SedeVal, NULL, @ContinuaSede OUTPUT, @CantFactVal

				IF @ContinuaSede IN (0, 2, 3, 6)
				BEGIN
					SET @CONTINUA_DIAN = @ContinuaSede
					BREAK
				END

				IF @ContinuaSede IN (4, 5, 9) AND @CONTINUA_DIAN = 1
					SET @CONTINUA_DIAN = @ContinuaSede

				FETCH NEXT FROM cur_valida_autpg INTO @SedeVal, @CantFactVal
			END

			CLOSE cur_valida_autpg
			DEALLOCATE cur_valida_autpg
			DROP TABLE #ValidaDianSedes

			SELECT 'OK' OK, @CONTINUA_DIAN CONTINUA
		END TRY
		BEGIN CATCH
			IF OBJECT_ID('tempdb..#ValidaDianSedes') IS NOT NULL DROP TABLE #ValidaDianSedes
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		RETURN
	END

    IF @METODO = 'CONTEOAUTORIZADO'
	BEGIN
		PRINT 'CONTEOAUTORIZADO'
		BEGIN TRY
			SELECT @IDTERCEROCA=IDTERCERO, @IDPLAN=IDPLAN, @ANOMES=PERIODO, @IDSEDE=IDSEDE, @WITHMARCA=WITHMARCA
			FROM OPENJSON (@PARAMETROS)
			WITH(
				IDTERCERO   VARCHAR(20)   '$.IDTERCERO', IDPLAN   VARCHAR(6)   '$.IDPLAN', PERIODO   VARCHAR(6)   '$.PERIODO'
				, IDSEDE   VARCHAR(5)   '$.IDSEDE', WITHMARCA BIT
			)

            IF NOT EXISTS (SELECT 1 FROM AUTPG WHERE AUTPG.ANOMES=@ANOMES AND AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.IDPLAN=@IDPLAN
                AND AUTPG.FACTURADO=0 AND AUTPG.FACTURABLE=1 AND AUTPG.ESTADO='Autorizado' AND (@WITHMARCA IS NULL OR (AUTPG.MARCA = 1 AND AUTPG.USUARIO_MARCA = @USUARIO))
				AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0
			)
			BEGIN
				SELECT 'KO' OK
				SELECT 'No se encontraron items para facturar.' ERROR
				RETURN
			END
               
			SELECT 'OK' OK
			;WITH PacientesOrdenados AS (
				SELECT
					AUTPG.IDSEDE,
					AUTPG.IDAFILIADO,
					ROW_NUMBER() OVER (PARTITION BY AUTPG.IDSEDE ORDER BY AUTPG.IDAFILIADO) AS RowNum,
					COALESCE(NULLIF(PPT.MAXAFI_XFTR, 0), 20) AS MAXAFI_XFTR,
					PLN.IDSERVICIO,
					SER.DESCSERVICIO
				FROM AUTPG WITH (NOLOCK)
				INNER JOIN PPT WITH (NOLOCK) ON PPT.IDTERCERO = AUTPG.IDTERCEROCA AND PPT.IDPLAN = AUTPG.IDPLAN
				INNER JOIN PLN WITH (NOLOCK) ON PLN.IDPLAN = AUTPG.IDPLAN
				LEFT JOIN SER WITH (NOLOCK) ON SER.IDSERVICIO = PLN.IDSERVICIO
				WHERE AUTPG.ANOMES = @ANOMES
					AND AUTPG.IDTERCEROCA = @IDTERCEROCA
					AND AUTPG.IDPLAN = @IDPLAN
					AND AUTPG.FACTURADO = 0
					AND AUTPG.FACTURABLE = 1
					AND AUTPG.ENFACT = 1
					AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado')
					AND (@IDSEDE IS NULL OR @IDSEDE = AUTPG.IDSEDE)
					AND (@WITHMARCA IS NULL OR (AUTPG.MARCA = 1 AND AUTPG.USUARIO_MARCA = @USUARIO))
					AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0
			)
			SELECT
				COUNT(1) CANTIDAD,
				COUNT(DISTINCT CONCAT(IDSEDE, '-', (RowNum - 1) / NULLIF(MAXAFI_XFTR, 0))) CANTIDAD_FACTURAS,
				MAX(MAXAFI_XFTR) MAX_AFILIADOS_FACTURA,
				MAX(IDSERVICIO) IDSERVICIOPAQ,
				MAX(DESCSERVICIO) DESCSERVICIO
			FROM PacientesOrdenados

		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK
		RETURN
	END
    
    IF @METODO = 'ENVIARA_EVENTO'
    BEGIN
        SELECT @ID=JSON_VALUE(@PARAMETROS, '$.ID')
        SELECT @ANOMES=ANOMES FROM AUTPG WHERE ID=@ID

        UPDATE CIT SET CLASEORDEN='Normal' 
        FROM CIT
            INNER JOIN AUTPG ON ID=@ID AND CIT.IDAFILIADO=AUTPG.IDAFILIADO
            INNER JOIN MPE ON MPE.IDPESPECIAL=CIT.IDPESPECIAL
            INNER JOIN MPEMES ON MPEMES.IDPESPECIAL=MPE.IDPESPECIAL
        WHERE AUTPG.ESTADO='Rechazado' AND CIT.IDEMEDICA=MPEMES.IDEMEDICA AND CIT.ANOMES=@ANOMES
        SELECT 'OK' OK
    END

    IF @METODO = 'RETIRAR_COPAGO'
    BEGIN
        SELECT @ID=JSON_VALUE(@PARAMETROS, '$.ID')
        SELECT @ANOMES=ANOMES FROM AUTPG WHERE ID=@ID
        UPDATE AUTPG SET VALORCOPAGO=0 WHERE ID=@ID AND FACTURADO=0 AND FACTURABLE=1 AND ENFACT=1
        SELECT 'OK' OK
    END

    IF @METODO = 'FACTURAR_AUTPG'
    BEGIN
        PRINT 'FACTURAR_AUTPG'
        BEGIN TRY
            SELECT @IDTERCEROCA=IDTERCERO, @IDPLAN=IDPLAN, @ANOMES=PERIODO, @IDSEDE=IDSEDE, @MAXAFI_XFTR=MAX_AFILIADOS_FACTURA,@IDSERVICIOPAQ=IDSERPAQ
		        ,@OBSERVACION =OBSERVACION
            FROM OPENJSON (@PARAMETROS)
            WITH(
                IDTERCERO   VARCHAR(20)   '$.IDTERCERO', IDPLAN   VARCHAR(6)   '$.IDPLAN', PERIODO   VARCHAR(6)   '$.PERIODO'
                , IDSEDE   VARCHAR(5)   '$.IDSEDE', MAX_AFILIADOS_FACTURA SMALLINT '$.MAX_AFILIADOS_FACTURA', IDSERPAQ VARCHAR(20) '$.IDSERPAQ'
			    , OBSERVACION VARCHAR(500) '$.OBSERVACION'
            )
               
            IF NOT EXISTS (SELECT 1 FROM AUTPG WHERE AUTPG.ANOMES=@ANOMES AND AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.IDPLAN=@IDPLAN
                AND AUTPG.FACTURADO=0 AND AUTPG.FACTURABLE=1 AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado')
				AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0
            )
            BEGIN
                SELECT 'KO' OK
                SELECT 'No se encontraron items para facturar.' ERROR
                RETURN
            END

            SELECT @VALORPAQ = VALOR 
			FROM SERTOT 
			WHERE IDTERCERO = @IDTERCEROCA AND IDPLAN = @IDPLAN AND IDSERVICIO = @IDSERVICIOPAQ
			AND CONVERT(DATE, @ANOMES+'01') BETWEEN SERTOT.FECHAINI AND SERTOT.FECHAFIN
            
            SELECT @F_FACTURA=DBO.FNK_GETDATE(),@COMPANIA='01',@NIT=NIT
			FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
			IF COALESCE(@NIT,'')='' 
			BEGIN
				INSERT INTO @TBLERRORES(ERROR)
				SELECT 'Tercero facturador no identificado, revise configuración de terceros.' 
			END
            IF COALESCE(@IDSERVICIOPAQ,'')=''
			BEGIN
				INSERT INTO @TBLERRORES(ERROR)
				SELECT 'Servicio del paquete no proporcionado, comuniquese con el departamento de sistemas.' 
			END
            IF NOT EXISTS(SELECT * FROM SER WHERE IDSERVICIO=@IDSERVICIOPAQ)
		    BEGIN
            INSERT INTO @TBLERRORES(ERROR)
			    SELECT 'El paquete asociado no existe en el Maestro de Servicios, Verifique e intente de nuevo.'
		    END
		    IF COALESCE(@VALORPAQ,0)<=0
		    BEGIN
            INSERT INTO @TBLERRORES(ERROR)
			    SELECT 'Valor del Paquete no puede ser menor o igual a cero(0)'
		    END
            IF COALESCE(@MAXAFI_XFTR,0)<=0
		    BEGIN
            INSERT INTO @TBLERRORES(ERROR)
			    SELECT 'Nro. de afiliados por factura no puede ser menor o igual a cero(0)'
		    END
			IF(SELECT COUNT(1) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			EXEC SPK_FACTURA_AUTPG @NIT, @COMPANIA, @IDSEDE, @USUARIO, @IDTERCEROCA, @IDPLAN, @ANOMES, @F_FACTURA, @IDSERVICIOPAQ, @VALORPAQ, @MAXAFI_XFTR, @OBSERVACION

        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END

    IF @METODO = 'FACTURAR_AUTPG_IMPORTADOS'
    BEGIN
        PRINT 'FACTURAR_AUTPG_IMPORTADOS'
        BEGIN TRY
            SELECT @IDTERCEROCA=IDTERCERO, @IDPLAN=IDPLAN, @ANOMES=PERIODO, @IDSEDE=IDSEDE, @MAXAFI_XFTR=MAX_AFILIADOS_FACTURA,@IDSERVICIOPAQ=IDSERPAQ
		        ,@OBSERVACION =OBSERVACION
            FROM OPENJSON (@PARAMETROS)
            WITH(
                IDTERCERO   VARCHAR(20)   '$.IDTERCERO', IDPLAN   VARCHAR(6)   '$.IDPLAN', PERIODO   VARCHAR(6)   '$.PERIODO'
                , IDSEDE   VARCHAR(5)   '$.IDSEDE', MAX_AFILIADOS_FACTURA SMALLINT '$.MAX_AFILIADOS_FACTURA', IDSERPAQ VARCHAR(20) '$.IDSERPAQ'
			    , OBSERVACION VARCHAR(500) '$.OBSERVACION'
            )
               
            IF NOT EXISTS (SELECT 1 FROM AUTPG WHERE AUTPG.ANOMES=@ANOMES AND AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.IDPLAN=@IDPLAN
                AND AUTPG.FACTURADO=0 AND AUTPG.FACTURABLE=1 AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') AND AUTPG.MARCA = 1 AND AUTPG.USUARIO_MARCA = @USUARIO
				AND COALESCE(AUTPG.NO_ENVIAR_FACT, 0) = 0
            )
            BEGIN
                SELECT 'KO' OK
                SELECT 'No se encontraron items para facturar.' ERROR
                RETURN
            END

		    IF COALESCE(@IDSERVICIOPAQ,'') = ''
		    BEGIN
			    SELECT TOP 1 @MAXAFI_XFTR=COALESCE(PPT.MAXAFI_XFTR,20), @IDSERVICIOPAQ=PLN.IDSERVICIO FROM AUTPG 
			    INNER JOIN PPT ON PPT.IDTERCERO=AUTPG.IDTERCEROCA AND PPT.IDPLAN=AUTPG.IDPLAN
			    INNER JOIN PLN ON PLN.IDPLAN=AUTPG.IDPLAN
			    WHERE AUTPG.ANOMES=@ANOMES AND AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.IDPLAN=@IDPLAN 
		    END

            SELECT @VALORPAQ = VALOR 
			FROM SERTOT 
			WHERE IDTERCERO = @IDTERCEROCA AND IDPLAN = @IDPLAN AND IDSERVICIO = @IDSERVICIOPAQ
			AND CONVERT(DATE, @ANOMES+'01') BETWEEN SERTOT.FECHAINI AND SERTOT.FECHAFIN

			SELECT @F_FACTURA=DBO.FNK_GETDATE(),@COMPANIA='01',@NIT=NIT
			FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
			IF COALESCE(@NIT,'')='' 
			BEGIN
				INSERT INTO @TBLERRORES(ERROR)
				SELECT 'Tercero facturador no identificado, revise configuración de terceros.' 
			END
            IF COALESCE(@IDSERVICIOPAQ,'')=''
			BEGIN
				INSERT INTO @TBLERRORES(ERROR)
				SELECT 'Servicio del paquete no proporcionado, comuniquese con el departamento de sistemas.' 
			END
            IF NOT EXISTS(SELECT * FROM SER WHERE IDSERVICIO=@IDSERVICIOPAQ)
		    BEGIN
            INSERT INTO @TBLERRORES(ERROR)
			    SELECT 'El paquete asociado no existe en el Maestro de Servicios, Verifique e intente de nuevo.'
		    END
		    IF COALESCE(@VALORPAQ,0)<=0
		    BEGIN
            INSERT INTO @TBLERRORES(ERROR)
			    SELECT 'Valor del Paquete no puede ser menor o igual a cero(0)'
		    END
            IF COALESCE(@MAXAFI_XFTR,0)<=0
		    BEGIN
            INSERT INTO @TBLERRORES(ERROR)
			    SELECT 'Nro. de afiliados por factura no puede ser menor o igual a cero(0)'
		    END
			IF(SELECT COUNT(1) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			EXEC SPK_FACTURA_AUTPG @NIT, @COMPANIA, @IDSEDE, @USUARIO, @IDTERCEROCA, @IDPLAN, @ANOMES, @F_FACTURA, @IDSERVICIOPAQ, @VALORPAQ, @MAXAFI_XFTR, @OBSERVACION, 1

        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END

	IF @METODO = 'FACTURAR_EVENTO_PAQ'
    BEGIN
        PRINT 'FACTURAR_EVENTO_PAQ'
        BEGIN TRY
            SELECT @IDTERCEROCA=IDTERCEROPAQ, @IDPLAN=IDPLANPAQ, @IDSEDE=IDSEDE, @MAXAFI_XFTR=MAX_AFILIADOS_FACTURA,@IDSERVICIOPAQ=IDSERPAQ
		        ,@OBSERVACION =OBSERVACION,@CNSFACTPAQ=CNSFACTPAQ,@VALORPAQ=VALORPAQ,@PROCEPAQ=PROCEPAQ
            FROM OPENJSON (@PARAMETROS)
            WITH(
                IDTERCEROPAQ   VARCHAR(20)   '$.DATOS.IDTERCEROPAQ', IDPLANPAQ   VARCHAR(6)   '$.DATOS.IDPLANPAQ', IDSEDE   VARCHAR(5)   '$.IDSEDE'
				, MAX_AFILIADOS_FACTURA SMALLINT '$.MAX_AFILIADOS_FACTURA', IDSERPAQ VARCHAR(20) '$.DATOS.IDSERPAQ'
			    , OBSERVACION VARCHAR(500) '$.OBSERVACION', CNSFACTPAQ VARCHAR(20)       '$.DATOS.CNSFACTPAQ'
				,VALORPAQ DECIMAL(14,2)          '$.DATOS.VALORPAQ',PROCEPAQ    VARCHAR(20)         '$.DATOS.PROCEPAQ'
            )
               
            IF NOT EXISTS (SELECT 1 FROM VWK_CARGOS_HADMAUTCIT_ART WHERE MARCAFAC=1
				AND USUMARCA=@USUARIO
				--AND CNSFACT=@CNSFACTPAQ
				AND PROCEDENCIA=@PROCEPAQ
            )
            BEGIN
                SELECT 'KO' OK
                SELECT 'No se encontraron items para facturar.' ERROR
                RETURN
            END

            SELECT @F_FACTURA=DBO.FNK_GETDATE(),@COMPANIA='01',@NIT=NIT
			FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')

			IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
			BEGIN
				IF UPPER(@IDSEDE) = 'TODAS' AND COALESCE(DBO.FNK_VALORVARIABLE('FACTSEDEPACIENTE'),'') <> 'SI'
				BEGIN
					INSERT INTO @TBLERRORES(ERROR)
					SELECT 'Escogio Todas las Sedes y esta IPS Tiene configurado Facturación por Sede'
				END
			END
			ELSE
				SELECT @IDSEDE=UBEQ.IDSEDE 
				FROM USUSU INNER JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME 
				WHERE USUARIO=@USUARIO

			IF COALESCE(@NIT,'')='' 
			BEGIN
				INSERT INTO @TBLERRORES(ERROR)
				SELECT 'Tercero facturador no identificado, revise configuración de terceros.' 
			END
            IF COALESCE(@IDSERVICIOPAQ,'')=''
			BEGIN
				INSERT INTO @TBLERRORES(ERROR)
				SELECT 'Servicio del paquete no proporcionado, comuniquese con el departamento de sistemas.' 
			END
            IF NOT EXISTS(SELECT * FROM SER WHERE IDSERVICIO=@IDSERVICIOPAQ)
		    BEGIN
            INSERT INTO @TBLERRORES(ERROR)
			    SELECT 'El paquete asociado no existe en el Maestro de Servicios, Verifique e intente de nuevo.'
		    END
		    IF COALESCE(@VALORPAQ,0)<=0
		    BEGIN
            INSERT INTO @TBLERRORES(ERROR)
			    SELECT 'Valor del Paquete no puede ser menor o igual a cero(0)'
		    END
            IF COALESCE(@MAXAFI_XFTR,0)<=0
		    BEGIN
            INSERT INTO @TBLERRORES(ERROR)
			    SELECT 'Nro. de afiliados por factura no puede ser menor o igual a cero(0)'
		    END
			IF(SELECT COUNT(1) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			EXEC SPK_FACTURACI_EVENTO_PAQ @NIT, @COMPANIA, @IDSEDE, @USUARIO, @IDTERCEROCA, @IDPLAN, @F_FACTURA, @IDSERVICIOPAQ, @VALORPAQ, @MAXAFI_XFTR, @OBSERVACION

        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END
    IF @METODO='RECALCULAR_COPAGOS'
    BEGIN
        SELECT @ANOMES=JSON_VALUE(@PARAMETROS,'$.PERIODO')
        SELECT @IDTERCEROCA=JSON_VALUE(@PARAMETROS,'$.IDTERCERO')
        SELECT @IDPLAN=JSON_VALUE(@PARAMETROS,'$.IDPLAN')

        IF COALESCE(@ANOMES,'')='' OR COALESCE(@IDTERCEROCA,'')='' OR COALESCE(@IDPLAN,'')=''
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR='Por favor debe especificar, periodo tercero y plan para dicho calculo'
            RETURN
        END

        UPDATE AUTPG SET  VALORCOPAGO=COALESCE(X.VALORCOPAGO,0)
        FROM AUTPG
        INNER JOIN AFI ON AFI.IDAFILIADO=AUTPG.IDAFILIADO AND AFI.ESTADO='Activo'
        INNER JOIN (
            SELECT A.IDTERCEROCA, IDPLAN, IDAFILIADO, A.ANOMES, A.FECHA, A.VALORCOPAGO
                , ITEM=ROW_NUMBER() OVER (
                    PARTITION BY A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES
                    ORDER BY
                        CASE WHEN A.PROCEDENCIA = 'CIT' THEN 0 WHEN A.PROCEDENCIA = 'AUT' THEN 1 ELSE 2 END,
                        A.TIPO_CITA ASC,
                        A.FECHA DESC,
                        A.NOADMISION DESC,
                        A.NOPRESTACION DESC,
                        A.NOITEM DESC
                )
            FROM VWK_CARGOS_HADMAUTCIT_ART A
            WHERE A.VALORCOPAGO>0 AND A.ENCAJA=1
        ) X ON X.IDAFILIADO=AUTPG.IDAFILIADO AND X.IDTERCEROCA=AUTPG.IDTERCEROCA AND X.IDPLAN=AUTPG.IDPLAN AND X.ITEM=1 AND AUTPG.ANOMES=X.ANOMES AND X.FECHA<GETDATE()
        WHERE AUTPG.ANOMES=@ANOMES AND AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.IDPLAN=@IDPLAN
        AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') 
        AND COALESCE(AUTPG.FACTURADO, 0)=0 
        AND COALESCE(AUTPG.VALORPAQ,0)>0
        AND AUTPG.ENFACT=1
        AND AUTPG.FACTURABLE=1
        AND COALESCE(AUTPG.VALORCOPAGO,0)=0
        SELECT 'OK' OK
    END

    IF @METODO='ACTUALIZAR_FECHAATENCION'
    BEGIN
        SELECT @ANOMES=JSON_VALUE(@PARAMETROS,'$.PERIODO')
        SELECT @IDTERCEROCA=JSON_VALUE(@PARAMETROS,'$.IDTERCERO')
        SELECT @IDPLAN=JSON_VALUE(@PARAMETROS,'$.IDPLAN')

        IF COALESCE(@ANOMES,'')='' OR COALESCE(@IDTERCEROCA,'')='' OR COALESCE(@IDPLAN,'')=''
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR='Por favor debe especificar, periodo tercero y plan para actualizar la fecha de atención'
            RETURN
        END

        UPDATE AUTPG SET FECHAATENCION=COALESCE(X.FECHAATENCION, CONVERT(DATE, AUTPG.ANOMES + '01'))
        FROM AUTPG
        INNER JOIN AFI ON AFI.IDAFILIADO=AUTPG.IDAFILIADO AND AFI.ESTADO='Activo'
        LEFT JOIN (
            SELECT A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES, A.FECHA, A.VALORCOPAGO, A.FECHA AS FECHAATENCION
                , ITEM=ROW_NUMBER() OVER (
                    PARTITION BY A.IDTERCEROCA, A.IDPLAN, A.IDAFILIADO, A.ANOMES 
                    ORDER BY A.TIPO_CITA ASC, A.FECHA DESC
                )
            FROM VWK_CARGOS_HADMAUTCIT_ART A
            WHERE A.FECHA<GETDATE()
        ) X ON X.IDAFILIADO=AUTPG.IDAFILIADO 
            AND X.IDTERCEROCA=AUTPG.IDTERCEROCA 
            AND X.IDPLAN=AUTPG.IDPLAN 
            AND X.ITEM=1 
            AND AUTPG.ANOMES=X.ANOMES
        WHERE AUTPG.ANOMES=@ANOMES AND AUTPG.IDTERCEROCA=@IDTERCEROCA AND AUTPG.IDPLAN=@IDPLAN
        AND AUTPG.ESTADO IN ('Autorizado','Autorizado Recuperado') 
        AND COALESCE(AUTPG.FACTURADO, 0)=0 
        AND COALESCE(AUTPG.VALORPAQ,0)>0
        AND AUTPG.ENFACT=1
        AND AUTPG.FACTURABLE=1
        SELECT 'OK' OK, @@ROWCOUNT AS REGISTROS_ACTUALIZADOS
    END

    IF @METODO = 'LISTAR_CAUSALES_NO_FACT'
    BEGIN
        SELECT 'OK' OK
        SELECT CODIGO, DESCRIPCION
        FROM TGEN WITH (NOLOCK)
        WHERE TABLA = 'AUTPG' AND CAMPO = 'NO_ENV_FACT_CAUSAL'
        ORDER BY DESCRIPCION
        RETURN
    END

    IF @METODO = 'MARCAR_NO_ENVIAR_FACT'
    BEGIN
        BEGIN TRY
            SELECT @ID = JSON_VALUE(@PARAMETROS, '$.ID')
            SELECT @IDCAUSAL_NO_FACT = JSON_VALUE(@PARAMETROS, '$.IDCAUSAL')
            SELECT @OBS_NO_ENV_FACT = JSON_VALUE(@PARAMETROS, '$.OBSERVACION')
            SELECT @ORIGEN_NO_ENV = JSON_VALUE(@PARAMETROS, '$.ORIGEN')

            IF COALESCE(@IDCAUSAL_NO_FACT, '') = ''
            BEGIN
                SELECT 'KO' OK
                SELECT 'Debe indicar la causal (IDCAUSAL).' ERROR
                RETURN
            END
            IF NOT EXISTS (
                SELECT 1 FROM TGEN WITH (NOLOCK)
                WHERE TABLA = 'AUTPG' AND CAMPO = 'NO_ENV_FACT_CAUSAL' AND CODIGO = @IDCAUSAL_NO_FACT
            )
            BEGIN
                SELECT 'KO' OK
                SELECT 'Causal no registrada en TGEN (AUTPG / NO_ENV_FACT_CAUSAL).' ERROR
                RETURN
            END

            IF NOT EXISTS (
                SELECT 1 FROM AUTPG WITH (NOLOCK)
                WHERE ID = @ID
                  AND ESTADO IN ('Autorizado', 'Autorizado Recuperado')
                  AND COALESCE(FACTURADO, 0) = 0
                  AND COALESCE(ENFACT, 0) = 0
                  AND COALESCE(NO_ENVIAR_FACT, 0) = 0
                  AND COALESCE(VALORPAQ, 0) > 0
            )
            BEGIN
                SELECT 'KO' OK
                SELECT 'El registro no admite esta acción (estado, envío o facturación previa, ya excluido o sin valor de paquete).' ERROR
                RETURN
            END

            INSERT INTO AUTPG_LOG (IDAUTPG, ACCION, USUARIO, FECHA, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, MOTIVORECHAZO, OBSRECHAZO, OBSERVACIONES)
            SELECT ID, 'NO_ENV_FACT', @USUARIO, GETDATE(), USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, @IDCAUSAL_NO_FACT, @OBS_NO_ENV_FACT, CONCAT_WS('|', 'ORIGEN', COALESCE(@ORIGEN_NO_ENV, 'UI'))
            FROM AUTPG WHERE ID = @ID

            UPDATE AUTPG SET
                NO_ENVIAR_FACT = 1,
                FACTURABLE_ANTES_NOFACT = FACTURABLE,
                FACTURABLE = 0,
                IDCAUSAL_NO_FACT = @IDCAUSAL_NO_FACT,
                OBS_NO_ENV_FACT = @OBS_NO_ENV_FACT,
                USU_NO_ENV_FACT = @USUARIO,
                FECHA_NO_ENV_FACT = GETDATE()
            WHERE ID = @ID
        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END

    IF @METODO = 'REVERTIR_NO_ENVIAR_FACT'
    BEGIN
        BEGIN TRY
            SELECT @ID = JSON_VALUE(@PARAMETROS, '$.ID')
            SELECT @OBS_NO_ENV_FACT = JSON_VALUE(@PARAMETROS, '$.OBSERVACION')

            IF NOT EXISTS (
                SELECT 1 FROM AUTPG WITH (NOLOCK)
                WHERE ID = @ID AND COALESCE(NO_ENVIAR_FACT, 0) = 1 AND COALESCE(ENFACT, 0) = 0 AND COALESCE(FACTURADO, 0) = 0
            )
            BEGIN
                SELECT 'KO' OK
                SELECT 'Solo puede revertir exclusión en registros marcados como No enviado a facturación, sin envío a facturación y sin facturar.' ERROR
                RETURN
            END

            INSERT INTO AUTPG_LOG (IDAUTPG, ACCION, USUARIO, FECHA, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, MOTIVORECHAZO, OBSRECHAZO, OBSERVACIONES)
            SELECT ID, 'REVERT_NO_FACT', @USUARIO, GETDATE(), USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, NULL, @OBS_NO_ENV_FACT, CONCAT_WS('|', 'ORIGEN', COALESCE(JSON_VALUE(@PARAMETROS, '$.ORIGEN'), 'UI'))
            FROM AUTPG WHERE ID = @ID

            UPDATE AUTPG SET
                NO_ENVIAR_FACT = 0,
                FACTURABLE = COALESCE(FACTURABLE_ANTES_NOFACT, 1),
                FACTURABLE_ANTES_NOFACT = NULL,
                IDCAUSAL_NO_FACT = NULL,
                OBS_NO_ENV_FACT = NULL,
                USU_NO_ENV_FACT = NULL,
                FECHA_NO_ENV_FACT = NULL
            WHERE ID = @ID
        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END

    IF @METODO = 'PROCESAR_NO_ENV_FACT_MASIVO'
    BEGIN
        DECLARE @FILAS_NO_ENV NVARCHAR(MAX)
        BEGIN TRY
            SELECT @FILAS_NO_ENV = JSON_QUERY(@PARAMETROS, '$.FILAS')
            IF @FILAS_NO_ENV IS NULL OR ISJSON(@FILAS_NO_ENV) = 0
            BEGIN
                SELECT 'KO' OK
                SELECT 'FILAS debe ser un arreglo JSON válido.' ERROR
                RETURN
            END

            IF OBJECT_ID('tempdb..#NVF') IS NOT NULL DROP TABLE #NVF
            CREATE TABLE #NVF (
                ID INT NOT NULL,
                ACCION VARCHAR(12) NOT NULL,
                IDCAUSAL VARCHAR(20) NULL,
                OBSERVACION VARCHAR(500) NULL
            )

            INSERT INTO #NVF (ID, ACCION, IDCAUSAL, OBSERVACION)
            SELECT J.ID, UPPER(LTRIM(RTRIM(J.ACCION))), J.IDCAUSAL, J.OBSERVACION
            FROM OPENJSON(@FILAS_NO_ENV)
            WITH (
                ID INT '$.ID',
                ACCION VARCHAR(12) '$.ACCION',
                IDCAUSAL VARCHAR(20) '$.IDCAUSAL',
                OBSERVACION VARCHAR(500) '$.OBSERVACION'
            ) J

            IF NOT EXISTS (SELECT 1 FROM #NVF)
            BEGIN
                SELECT 'KO' OK
                SELECT 'No se recibieron filas para procesar.' ERROR
                RETURN
            END

            INSERT INTO AUTPG_LOG (IDAUTPG, ACCION, USUARIO, FECHA, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, MOTIVORECHAZO, OBSRECHAZO, OBSERVACIONES)
            SELECT A.ID, 'NO_ENV_FACT', @USUARIO, GETDATE(), A.USUENVIA_AFACT, A.FECHAENVIO_AFACT, A.ENFACT, A.FACTURABLE, A.FACTURADO, A.ESTADO, N.IDCAUSAL, N.OBSERVACION, CONCAT_WS('|', 'ORIGEN', 'MASIVO')
            FROM AUTPG A WITH (NOLOCK)
            INNER JOIN #NVF N ON N.ID = A.ID
            INNER JOIN TGEN G WITH (NOLOCK) ON G.TABLA = 'AUTPG' AND G.CAMPO = 'NO_ENV_FACT_CAUSAL' AND G.CODIGO = N.IDCAUSAL
            WHERE N.ACCION IN ('MARCAR', 'M')
              AND COALESCE(A.ESTADO, '') IN ('Autorizado', 'Autorizado Recuperado')
              AND COALESCE(A.FACTURADO, 0) = 0
              AND COALESCE(A.ENFACT, 0) = 0
              AND COALESCE(A.NO_ENVIAR_FACT, 0) = 0
              AND COALESCE(A.VALORPAQ, 0) > 0
              AND COALESCE(N.IDCAUSAL, '') <> ''

            UPDATE A SET
                NO_ENVIAR_FACT = 1,
                FACTURABLE_ANTES_NOFACT = A.FACTURABLE,
                FACTURABLE = 0,
                IDCAUSAL_NO_FACT = N.IDCAUSAL,
                OBS_NO_ENV_FACT = N.OBSERVACION,
                USU_NO_ENV_FACT = @USUARIO,
                FECHA_NO_ENV_FACT = GETDATE()
            FROM AUTPG A
            INNER JOIN #NVF N ON N.ID = A.ID
            INNER JOIN TGEN G WITH (NOLOCK) ON G.TABLA = 'AUTPG' AND G.CAMPO = 'NO_ENV_FACT_CAUSAL' AND G.CODIGO = N.IDCAUSAL
            WHERE N.ACCION IN ('MARCAR', 'M')
              AND COALESCE(A.ESTADO, '') IN ('Autorizado', 'Autorizado Recuperado')
              AND COALESCE(A.FACTURADO, 0) = 0
              AND COALESCE(A.ENFACT, 0) = 0
              AND COALESCE(A.NO_ENVIAR_FACT, 0) = 0
              AND COALESCE(A.VALORPAQ, 0) > 0
              AND COALESCE(N.IDCAUSAL, '') <> ''

            INSERT INTO AUTPG_LOG (IDAUTPG, ACCION, USUARIO, FECHA, USUENVIA_AFACT, FECHAENVIO_AFACT, ENFACT, FACTURABLE, FACTURADO, ESTADO, MOTIVORECHAZO, OBSRECHAZO, OBSERVACIONES)
            SELECT A.ID, 'REVERT_NO_FACT', @USUARIO, GETDATE(), A.USUENVIA_AFACT, A.FECHAENVIO_AFACT, A.ENFACT, A.FACTURABLE, A.FACTURADO, A.ESTADO, NULL, N.OBSERVACION, CONCAT_WS('|', 'ORIGEN', 'MASIVO')
            FROM AUTPG A WITH (NOLOCK)
            INNER JOIN #NVF N ON N.ID = A.ID
            WHERE N.ACCION IN ('REVERTIR', 'R')
              AND COALESCE(A.NO_ENVIAR_FACT, 0) = 1
              AND COALESCE(A.ENFACT, 0) = 0
              AND COALESCE(A.FACTURADO, 0) = 0

            UPDATE A SET
                NO_ENVIAR_FACT = 0,
                FACTURABLE = COALESCE(A.FACTURABLE_ANTES_NOFACT, 1),
                FACTURABLE_ANTES_NOFACT = NULL,
                IDCAUSAL_NO_FACT = NULL,
                OBS_NO_ENV_FACT = NULL,
                USU_NO_ENV_FACT = NULL,
                FECHA_NO_ENV_FACT = NULL
            FROM AUTPG A
            INNER JOIN #NVF N ON N.ID = A.ID
            WHERE N.ACCION IN ('REVERTIR', 'R')
              AND COALESCE(A.NO_ENVIAR_FACT, 0) = 1
              AND COALESCE(A.ENFACT, 0) = 0
              AND COALESCE(A.FACTURADO, 0) = 0

            DROP TABLE #NVF
        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END

    IF @METODO = 'CONSULTAR_LOG'
    BEGIN
        PRINT 'CONSULTAR_LOG'
        BEGIN TRY
            DECLARE @IDAUTPG INT, @FECHA_INICIO DATETIME, @FECHA_FIN DATETIME, @USUARIO_LOG VARCHAR(16), @ACCION_LOG VARCHAR(32)
            
            SELECT @IDAUTPG = JSON_VALUE(@PARAMETROS,'$.IDAUTPG'),
                @FECHA_INICIO = JSON_VALUE(@PARAMETROS,'$.FECHA_INICIO'),
                @FECHA_FIN = JSON_VALUE(@PARAMETROS,'$.FECHA_FIN'),
                @USUARIO_LOG = JSON_VALUE(@PARAMETROS,'$.USUARIO'),
                @ACCION_LOG = JSON_VALUE(@PARAMETROS,'$.ACCION')

            SELECT 'OK' OK
            SELECT 
                L.ID,
                L.IDAUTPG,
                L.ACCION,
                L.USUARIO,
                L.FECHA,
                L.USUENVIA_AFACT,
                L.FECHAENVIO_AFACT,
                L.ENFACT,
                L.FACTURABLE,
                L.FACTURADO,
                L.ESTADO,
                L.MOTIVORECHAZO,
                L.OBSRECHAZO,
                L.OBSERVACIONES,
                A.NOAUTORIZACION,
                AFI.DOCIDAFILIADO,
                AFI.NOMBREAFI,
                TER.RAZONSOCIAL AS ASEGURADORA,
                PLN.DESCPLAN,
                CAU.DESCCAUSAL AS DESC_MOTIVORECHAZO,
                TGNOF.DESCRIPCION AS DESC_CAUSAL_NO_FACT
            FROM AUTPG_LOG L
            INNER JOIN AUTPG A ON A.ID = L.IDAUTPG
            LEFT JOIN AFI ON AFI.IDAFILIADO = A.IDAFILIADO
            LEFT JOIN TER ON TER.IDTERCERO = A.IDTERCEROCA
            LEFT JOIN PLN ON PLN.IDPLAN = A.IDPLAN
            LEFT JOIN CAU ON CAU.IDCAUSAL = L.MOTIVORECHAZO
            LEFT JOIN TGEN TGNOF ON TGNOF.TABLA = 'AUTPG' AND TGNOF.CAMPO = 'NO_ENV_FACT_CAUSAL' AND TGNOF.CODIGO = L.MOTIVORECHAZO
                AND L.ACCION IN ('NO_ENV_FACT', 'REVERT_NO_FACT')
            WHERE (@IDAUTPG IS NULL OR L.IDAUTPG = @IDAUTPG)
                AND (@FECHA_INICIO IS NULL OR L.FECHA >= @FECHA_INICIO)
                AND (@FECHA_FIN IS NULL OR L.FECHA <= @FECHA_FIN)
                AND (@USUARIO_LOG IS NULL OR L.USUARIO = @USUARIO_LOG)
                AND (@ACCION_LOG IS NULL OR L.ACCION = @ACCION_LOG)
            ORDER BY L.FECHA DESC
        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
        IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
        BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
        END
        SELECT 'OK' OK
        RETURN
    END
END

