CREATE OR ALTER PROCEDURE DBO.SPQ_IACTEQU @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @DATOS VARCHAR(MAX)
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @IDSEDE VARCHAR(5), @PROCESO VARCHAR(20)
DECLARE @IDACTIVO VARCHAR(20), @IDTIPOACTIVO VARCHAR(20), @SERIAL VARCHAR(50), @MODELOIACTEQU VARCHAR(20), @MARCA VARCHAR(20), @DESCRIPCION VARCHAR(255)
DECLARE @ITEM SMALLINT, @ESTADO VARCHAR(10), @NROINTERNO VARCHAR(20)

BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	IF @METODO = 'GUARDAR'
	BEGIN
		BEGIN TRY
			SELECT @PROCESO = PROCESO, @IDACTIVO = IDACTIVO, @IDTIPOACTIVO = IDTIPOACTIVO, @SERIAL = SERIAL, @MODELOIACTEQU = MODELOIACTEQU, @MARCA = MARCA, @DESCRIPCION 
				= DESCRIPCION, @ITEM = ITEM, @ESTADO = ESTADO, @NROINTERNO = NROINTERNO
			FROM OPENJSON(@PARAMETROS) WITH (
					IDACTIVO VARCHAR(20) '$.IDACTIVO', IDTIPOACTIVO VARCHAR(20) '$.IDTIPOACTIVO', SERIAL VARCHAR(50) '$.SERIAL', MODELOIACTEQU VARCHAR(20) 
					'$.MODELO', MARCA VARCHAR(20) '$.MARCA', DESCRIPCION VARCHAR(255) '$.DESCRIPCION', ITEM SMALLINT '$.ITEM', ESTADO VARCHAR(10) '$.ESTADO', 
					NROINTERNO VARCHAR(20) '$.NROINTERNO', PROCESO VARCHAR(20) '$.PROCESO'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT CONCAT ('EL ITEM ', @ITEM, ' YA SE ENCUENTRA REGISTRADO')
					WHERE EXISTS (
							SELECT 1
							FROM IACTEQU
							WHERE IDACTIVO = @IDACTIVO AND IDTIPOACTIVO = @IDTIPOACTIVO AND ITEM = @ITEM
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						INSERT INTO IACTEQU (IDACTIVO, IDTIPOACTIVO, SERIAL, MODELO, MARCA, DESCRIPCION, ITEM, ESTADO, NROINTERNO)
						SELECT @IDACTIVO, @IDTIPOACTIVO, @SERIAL, @MODELOIACTEQU, @MARCA, @DESCRIPCION, @ITEM, @ESTADO, @NROINTERNO
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					UPDATE IACTEQU
					SET SERIAL = @SERIAL, MODELO = @MODELOIACTEQU, MARCA = @MARCA, DESCRIPCION = @DESCRIPCION, ESTADO = @ESTADO, NROINTERNO = @NROINTERNO
					WHERE IDACTIVO = @IDACTIVO AND IDTIPOACTIVO = @IDTIPOACTIVO AND ITEM = @ITEM
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'ELIMINAR'
	BEGIN
		SELECT @IDACTIVO = IDACTIVO, @IDTIPOACTIVO = IDTIPOACTIVO, @ITEM = ITEM
		FROM OPENJSON(@PARAMETROS) WITH (IDACTIVO VARCHAR(20) '$.IDACTIVO', IDTIPOACTIVO VARCHAR(20) '$.IDTIPOACTIVO', ITEM SMALLINT '$.ITEM')

		BEGIN TRY
			DELETE
			FROM IACTEQU
			WHERE IDACTIVO = @IDACTIVO AND IDTIPOACTIVO = @IDTIPOACTIVO AND ITEM = @ITEM
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END
END


