CREATE OR ALTER PROCEDURE DBO.SPQ_IACT @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @DATOS VARCHAR(MAX), @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(20), @IDSEDE VARCHAR(5), @PROCESO VARCHAR(20)
--
DECLARE @IDACTIVO VARCHAR(20), @IDTIPOACTIVO VARCHAR(20), @DESCRIPCION VARCHAR(512), @FECHACOMPRA DATETIME, @PRECIOCOMPRA DECIMAL(14, 2)
DECLARE @PRECIOCOMERCIAL DECIMAL(14, 2)
DECLARE @REFERENCIA VARCHAR(20), @MODELOIACT VARCHAR(20), @MARCA VARCHAR(20), @NOESCRITURA VARCHAR(20), @LINDEROS VARCHAR(254), @NOPARTE VARCHAR(20)
DECLARE @MATRICULA VARCHAR(20)
DECLARE @SERIAL VARCHAR(50), @CCOSTO VARCHAR(20), @UBICACION VARCHAR(255), @RESPONSABLE VARCHAR(20), @IDTERCERO VARCHAR(20)
DECLARE @ESTADO VARCHAR(20), @DEPACUMHISTORICA DECIMAL(14, 2), @DEPACUMDIFERIDA DECIMAL(14, 2), @FECHAULTDEPRECIACION DATETIME, @TIPOASOCIACION VARCHAR(20)
DECLARE @IDACTIVOGRUPO VARCHAR(20), @CODIGOINTERNO VARCHAR(20), @CODIGOBARRA VARCHAR(20), @CUENTA VARCHAR(16), @IDBODEGA VARCHAR(20)
DECLARE @MESESADEPRECIAR SMALLINT, @MESESDEPRECIADOS SMALLINT, @VALORSALVAMENTO DECIMAL(14, 2), @AJUSTEACUMULADO DECIMAL(14, 2), @IDAREA VARCHAR(20)
DECLARE @NOLOTE VARCHAR(20)
DECLARE @CATEGORIA VARCHAR(20), @IDITAR VARCHAR(2), @IDARTICULO VARCHAR(20), @CODPRG VARCHAR(20), @CODUNG VARCHAR(5)
DECLARE @CUENTA_AJINFLACION VARCHAR(16), @CUENTA_AJDEPRECIACION VARCHAR(16), @CUENTA_AJINFLA_DEP VARCHAR(16), @AJUSTEDEPACUMULADA DECIMAL(14, 2)
DECLARE @DEPRECIABLE SMALLINT
DECLARE @SUBCCOSTO VARCHAR(4), @ICODALTERNO VARCHAR(30), @IDTIPONIIF VARCHAR(20), @PRECIOCOMERCIALNIIF DECIMAL(14, 2), @DEPACUMHISTORICANIIF DECIMAL(14, 2)
DECLARE @DEPACUMDIFERIDANIIF DECIMAL(14, 2), @FECHAULTDEPRECNIIF DATETIME, @VALORSALVAMENTONIIF DECIMAL(14, 2), @MESESADEPRECIARNIIF SMALLINT
DECLARE @MESESDEPRECIADOSNIIF SMALLINT, @SECTOR VARCHAR(20), @CLASEGRUPO VARCHAR(20), @FPRIMERMTTO DATETIME, @NROMTTOANUAL SMALLINT
DECLARE @FULTIMOMTTO DATETIME
DECLARE @CLASEMMTO VARCHAR(20), @ANOFAB VARCHAR(4), @RINVIMA VARCHAR(20), @ESTAUSO VARCHAR(20), @VOLTAMAX VARCHAR(10), @VOLTAMIN VARCHAR(10)
DECLARE @CORRIENTEMAX VARCHAR(10), @FUSIBLE VARCHAR(10), @POTENCIA VARCHAR(10), @FRECUENCIA VARCHAR(10), @VELOCIDAD VARCHAR(10)
DECLARE @PESO VARCHAR(10), @PRESION VARCHAR(10), @TEMPOPERA VARCHAR(10), @HUMEREL VARCHAR(10), @TECNODOMI VARCHAR(20), @RIESGO VARCHAR(10)
DECLARE @CLASEQUI VARCHAR(10), @FUNCIONAMIENTO VARCHAR(10), @SECALIBRA VARCHAR(2), @PERIOCALI SMALLINT, @FULTIMACALI DATETIME, @PARADA VARCHAR(3)
DECLARE @IDFOTO VARCHAR(50), @M_OPERE BIT, @M_MMTO BIT, @M_PARTES BIT, @PLANO_ELECT BIT, @PLANO_ELEC BIT
DECLARE @PLANO_NEU BIT, @PLANO_MECA BIT, @USO VARCHAR(10), @TIPO_MMTO VARCHAR(20), @ALTERNATIVA VARCHAR(20)
DECLARE @PROPIEDAD VARCHAR(100), @GARANTIA VARCHAR(512), @M_DESPIECE BIT, @TIPOELEMENTO VARCHAR(20), @REFRIGERANTE VARCHAR(20), @PLACA_ACTUAL VARCHAR(20), 
	@PLACA_ANTIGUA VARCHAR(20)
DECLARE @CAPACIDAD VARCHAR(20), @CAPACITOR VARCHAR(20), @SYS_COMPUTERNAME VARCHAR(254)

--
BEGIN
	SELECT @MODELO = MODELO, @METODO = METODO, @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	IF @METODO = 'GUARDAR'
	BEGIN
		SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME
		FROM USUSU
		WHERE USUARIO = @USUARIO

		SELECT @IDSEDE = IDSEDE
		FROM UBEQ
		WHERE SYS_ComputerName = @SYS_COMPUTERNAME

		BEGIN TRY
			SELECT @PROCESO = PROCESO, @IDACTIVO = IDACTIVO, @IDTIPOACTIVO = IDTIPOACTIVO, @DESCRIPCION = DESCRIPCION, @FECHACOMPRA = FECHACOMPRA, @PRECIOCOMPRA = 
				PRECIOCOMPRA, @PRECIOCOMERCIAL = PRECIOCOMERCIAL, @REFERENCIA = REFERENCIA, @MODELOIACT = MODELOIACT, @MARCA = MARCA, @NOESCRITURA = NOESCRITURA, 
				@LINDEROS = LINDEROS, @NOPARTE = NOPARTE, @MATRICULA = MATRICULA, @SERIAL = SERIAL, @CCOSTO = CCOSTO, @UBICACION = UBICACION, @RESPONSABLE = RESPONSABLE, 
				@IDTERCERO = IDTERCERO, @ESTADO = ESTADO, @DEPACUMHISTORICA = DEPACUMHISTORICA, @DEPACUMDIFERIDA = DEPACUMDIFERIDA, @FECHAULTDEPRECIACION = 
				FECHAULTDEPRECIACION, @TIPOASOCIACION = TIPOASOCIACION, @IDACTIVOGRUPO = IDACTIVOGRUPO, @CODIGOINTERNO = CODIGOINTERNO, @CODIGOBARRA = CODIGOBARRA
				, @CUENTA = CUENTA, @IDBODEGA = IDBODEGA, @MESESADEPRECIAR = MESESADEPRECIAR, @MESESDEPRECIADOS = MESESDEPRECIADOS, @VALORSALVAMENTO = 
				VALORSALVAMENTO, @AJUSTEACUMULADO = AJUSTEACUMULADO, @IDAREA = IDAREA, @NOLOTE = NOLOTE, @CATEGORIA = CATEGORIA, @IDITAR = IDITAR, @IDARTICULO = 
				IDARTICULO, @CODPRG = CODPRG, @CODUNG = CODUNG, @CUENTA_AJINFLACION = CUENTA_AJINFLACION, @CUENTA_AJDEPRECIACION = CUENTA_AJDEPRECIACION, 
				@CUENTA_AJINFLA_DEP = CUENTA_AJINFLA_DEP, @AJUSTEDEPACUMULADA = AJUSTEDEPACUMULADA, @DEPRECIABLE = DEPRECIABLE, @SUBCCOSTO = SUBCCOSTO, 
				@ICODALTERNO = ICODALTERNO, @IDTIPONIIF = IDTIPONIIF, @PRECIOCOMERCIALNIIF = PRECIOCOMERCIALNIIF, @DEPACUMHISTORICANIIF = DEPACUMHISTORICANIIF, 
				@DEPACUMDIFERIDANIIF = DEPACUMDIFERIDANIIF, @FECHAULTDEPRECNIIF = FECHAULTDEPRECNIIF, @VALORSALVAMENTONIIF = VALORSALVAMENTONIIF, 
				@MESESADEPRECIARNIIF = MESESADEPRECIARNIIF, @MESESDEPRECIADOSNIIF = MESESDEPRECIADOSNIIF, @SECTOR = SECTOR, @CLASEGRUPO = CLASEGRUPO, @FPRIMERMTTO 
				= FPRIMERMTTO, @NROMTTOANUAL = NROMTTOANUAL, @FULTIMOMTTO = FULTIMOMTTO, @CLASEMMTO = CLASEMMTO, @ANOFAB = ANOFAB, @RINVIMA = RINVIMA, @ESTAUSO = ESTAUSO
				, @VOLTAMAX = VOLTAMAX, @VOLTAMIN = VOLTAMIN, @CORRIENTEMAX = CORRIENTEMAX, @FUSIBLE = FUSIBLE, @POTENCIA = POTENCIA, @FRECUENCIA = FRECUENCIA, 
				@VELOCIDAD = VELOCIDAD, @PESO = PESO, @PRESION = PRESION, @TEMPOPERA = TEMPOPERA, @HUMEREL = HUMEREL, @TECNODOMI = TECNODOMI, @RIESGO = RIESGO, @CLASEQUI = 
				CLASEQUI, @FUNCIONAMIENTO = FUNCIONAMIENTO, @SECALIBRA = SECALIBRA, @PERIOCALI = PERIOCALI, @FULTIMACALI = FULTIMACALI, @PARADA = PARADA, @IDFOTO = 
				IDFOTO, @M_OPERE = M_OPERE, @M_MMTO = M_MMTO, @M_PARTES = M_PARTES, @PLANO_ELECT = PLANO_ELECT, @PLANO_ELEC = PLANO_ELEC, @PLANO_NEU = PLANO_NEU, 
				@PLANO_MECA = PLANO_MECA, @USO = USO, @TIPO_MMTO = TIPO_MMTO, @ALTERNATIVA = ALTERNATIVA, @PROPIEDAD = PROPIEDAD, @GARANTIA = GARANTIA, @M_DESPIECE = 
				M_DESPIECE, @TIPOELEMENTO = TIPOELEMENTO, @REFRIGERANTE = REFRIGERANTE, @CAPACIDAD = CAPACIDAD, @CAPACITOR = CAPACITOR, @PLACA_ACTUAL = PLACA_ACTUAL, 
				@PLACA_ANTIGUA = PLACA_ANTIGUA
			FROM OPENJSON(@PARAMETROS) WITH (
					PROCESO VARCHAR(20) '$.PROCESO', IDACTIVO VARCHAR(20) '$.IDACTIVO', IDTIPOACTIVO VARCHAR(20) '$.IDTIPOACTIVO', DESCRIPCION VARCHAR(512) 
					'$.DESCRIPCION', FECHACOMPRA DATETIME '$.FECHACOMPRA', PRECIOCOMPRA DECIMAL(14, 2) '$.PRECIOCOMPRA', PRECIOCOMERCIAL DECIMAL(14, 2) 
					'$.PRECIOCOMERCIAL', REFERENCIA VARCHAR(20) '$.REFERENCIA', MODELOIACT VARCHAR(20) '$.MODELO', MARCA VARCHAR(20) '$.MARCA', NOESCRITURA 
					VARCHAR(20) '$.NOESCRITURA', LINDEROS VARCHAR(254) '$.LINDEROS', NOPARTE VARCHAR(20) '$.NOPARTE', MATRICULA VARCHAR(20) '$.MATRICULA', SERIAL 
					VARCHAR(50) '$.SERIAL', CCOSTO VARCHAR(20) '$.CCOSTO', UBICACION VARCHAR(255) '$.UBICACION', RESPONSABLE VARCHAR(20) '$.RESPONSABLE', 
					IDTERCERO VARCHAR(20) '$.IDTERCERO', ESTADO VARCHAR(20) '$.ESTADO', DEPACUMHISTORICA DECIMAL(14, 2) '$.DEPACUMHISTORICA', DEPACUMDIFERIDA 
					DECIMAL(14, 2) '$.DEPACUMDIFERIDA', FECHAULTDEPRECIACION DATETIME '$.FECHAULTDEPRECIACION', TIPOASOCIACION VARCHAR(20) '$.TIPOASOCIACION', 
					IDACTIVOGRUPO VARCHAR(20) '$.IDACTIVOGRUPO', CODIGOINTERNO VARCHAR(20) '$.CODIGOINTERNO', CODIGOBARRA VARCHAR(20) '$.CODIGOBARRA', CUENTA 
					VARCHAR(16) '$.CUENTA', IDBODEGA VARCHAR(20) '$.IDBODEGA', MESESADEPRECIAR SMALLINT '$.MESESADEPRECIAR', MESESDEPRECIADOS SMALLINT 
					'$.MESESDEPRECIADOS', VALORSALVAMENTO DECIMAL(14, 2) '$.VALORSALVAMENTO', AJUSTEACUMULADO DECIMAL(14, 2) '$.AJUSTEACUMULADO', IDAREA VARCHAR
					(20) '$.IDAREA', NOLOTE VARCHAR(20) '$.NOLOTE', CATEGORIA VARCHAR(20) '$.CATEGORIA', IDITAR VARCHAR(2) '$.IDITAR', IDARTICULO VARCHAR(20) 
					'$.IDARTICULO', CODPRG VARCHAR(20) '$.CODPRG', CODUNG VARCHAR(5) '$.CODUNG', CUENTA_AJINFLACION VARCHAR(16) '$.CUENTA_AJINFLACION', 
					CUENTA_AJDEPRECIACION VARCHAR(16) '$.CUENTA_AJDEPRECIACION', CUENTA_AJINFLA_DEP VARCHAR(16) '$.CUENTA_AJINFLA_DEP', AJUSTEDEPACUMULADA 
					DECIMAL(14, 2) '$.AJUSTEDEPACUMULADA', DEPRECIABLE SMALLINT '$.DEPRECIABLE', SUBCCOSTO VARCHAR(4) '$.SUBCCOSTO', ICODALTERNO VARCHAR(30) 
					'$.ICODALTERNO', IDTIPONIIF VARCHAR(20) '$.IDTIPONIIF', PRECIOCOMERCIALNIIF DECIMAL(14, 2) '$.PRECIOCOMERCIALNIIF', DEPACUMHISTORICANIIF 
					DECIMAL(14, 2) '$.DEPACUMHISTORICANIIF', DEPACUMDIFERIDANIIF DECIMAL(14, 2) '$.DEPACUMDIFERIDANIIF', FECHAULTDEPRECNIIF DATETIME 
					'$.FECHAULTDEPRECNIIF', VALORSALVAMENTONIIF DECIMAL(14, 2) '$.VALORSALVAMENTONIIF', MESESADEPRECIARNIIF SMALLINT '$.MESESADEPRECIARNIIF', 
					MESESDEPRECIADOSNIIF SMALLINT '$.MESESDEPRECIADOSNIIF', SECTOR VARCHAR(20) '$.SECTOR', CLASEGRUPO VARCHAR(20) '$.CLASEGRUPO', FPRIMERMTTO 
					DATETIME '$.FPRIMERMTTO', NROMTTOANUAL SMALLINT '$.NROMTTOANUAL', FULTIMOMTTO DATETIME '$.FULTIMOMTTO', CLASEMMTO VARCHAR(20) '$.CLASEMMTO', 
					ANOFAB VARCHAR(4) '$.ANOFAB', RINVIMA VARCHAR(20) '$.RINVIMA', ESTAUSO VARCHAR(20) '$.ESTAUSO', VOLTAMAX VARCHAR(10) '$.VOLTAMAX', VOLTAMIN 
					VARCHAR(10) '$.VOLTAMIN', CORRIENTEMAX VARCHAR(10) '$.CORRIENTEMAX', FUSIBLE VARCHAR(10) '$.FUSIBLE', POTENCIA VARCHAR(10) '$.POTENCIA', 
					FRECUENCIA VARCHAR(10) '$.FRECUENCIA', VELOCIDAD VARCHAR(10) '$.VELOCIDAD', PESO VARCHAR(10) '$.PESO', PRESION VARCHAR(10) '$.PRESION', 
					TEMPOPERA VARCHAR(10) '$.TEMPOPERA', HUMEREL VARCHAR(10) '$.HUMEREL', TECNODOMI VARCHAR(20) '$.TECNODOMI', RIESGO VARCHAR(10) '$.RIESGO', 
					CLASEQUI VARCHAR(10) '$.CLASEQUI', FUNCIONAMIENTO VARCHAR(10) '$.FUNCIONAMIENTO', SECALIBRA VARCHAR(2) '$.SECALIBRA', PERIOCALI SMALLINT 
					'$.PERIOCALI', FULTIMACALI DATETIME '$.FULTIMACALI', PARADA VARCHAR(3) '$.PARADA', IDFOTO VARCHAR(50) '$.IDFOTO', M_OPERE BIT '$.M_OPERE', 
					M_MMTO BIT '$.M_MMTO', M_PARTES BIT '$.M_PARTES', PLANO_ELECT BIT '$.PLANO_ELECT', PLANO_ELEC BIT '$.PLANO_ELEC', PLANO_NEU BIT '$.PLANO_NEU', 
					PLANO_MECA BIT '$.PLANO_MECA', USO VARCHAR(10) '$.USO', TIPO_MMTO VARCHAR(20) '$.TIPO_MMTO', ALTERNATIVA VARCHAR(20) '$.ALTERNATIVA', 
					PROPIEDAD VARCHAR(100) '$.PROPIEDAD', GARANTIA VARCHAR(512) '$.GARANTIA', M_DESPIECE BIT '$.M_DESPIECE', TIPOELEMENTO VARCHAR(20) 
					'$.TIPOELEMENTO', REFRIGERANTE VARCHAR(20) '$.REFRIGERANTE', CAPACIDAD VARCHAR(20) '$.CAPACIDAD', CAPACITOR VARCHAR(20) '$.CAPACITOR', 
					PLACA_ACTUAL VARCHAR(20) '$.PLACA_ACTUAL', PLACA_ANTIGUA VARCHAR(20) '$.PLACA_ANTIGUA'
					)

			IF UPPER(@PROCESO) = 'INSERTAR'
			BEGIN
				BEGIN TRY
					DECLARE @PRECNS VARCHAR(20) = 'ACT'
					DECLARE @NUEVOCNS VARCHAR(20)
					DECLARE @LONGITUD INT = 10
					DECLARE @PREFIJO VARCHAR(20) = CONCAT ('@IACT_', @PRECNS)

					EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE, @PREFIJO = @PREFIJO, @LONGITUD = @LONGITUD, @LLAMADO = 'ANT', @NVOCONSEC = @NUEVOCNS OUTPUT

					SELECT @IDACTIVO = @PRECNS + REPLACE(SPACE(@LONGITUD - LEN(@NUEVOCNS)) + LTRIM(RTRIM(@NUEVOCNS)), SPACE(1), '0');

					INSERT INTO @TBLERRORES (ERROR)
					SELECT 'EL SERIAL YA EXISTE, EL SERIAL DEBE SER UNICO PARA CADA ACTIVO'
					WHERE EXISTS (
							SELECT SERIAL
							FROM IACT
							WHERE SERIAL = @SERIAL
							)

					INSERT INTO @TBLERRORES (ERROR)
					SELECT 'CODALTERNO DUPLICADO, EL CODALTERNO DEBE SER UNICO PARA CADA ACTIVO'
					WHERE EXISTS (
							SELECT ICODALTERNO
							FROM IACT
							WHERE ICODALTERNO = @ICODALTERNO AND IDACTIVO <> @IDACTIVO
							)

					INSERT INTO @TBLERRORES (ERROR)
					SELECT 'CODIGOINTERNO DUPLICADO,EL CODIGOINTERNO DEBE SER UNICO PARA CADA ACTIVO'
					WHERE EXISTS (
							SELECT CODIGOINTERNO
							FROM IACT
							WHERE CODIGOINTERNO = @CODIGOINTERNO
							)

					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						INSERT INTO [IACT] (
							[IDACTIVO], [IDTIPOACTIVO], [DESCRIPCION], [FECHACOMPRA], [PRECIOCOMPRA], [PRECIOCOMERCIAL], [REFERENCIA], [MODELO], [MARCA], 
							[NOESCRITURA], [LINDEROS], [NOPARTE], [MATRICULA], [SERIAL], [CCOSTO], [UBICACION], [RESPONSABLE], [IDTERCERO], [ESTADO], 
							[DEPACUMHISTORICA], [DEPACUMDIFERIDA], [FECHAULTDEPRECIACION], [TIPOASOCIACION], [IDACTIVOGRUPO], [CODIGOINTERNO], [CODIGOBARRA]
							, [CUENTA], [IDBODEGA], [MESESADEPRECIAR], [MESESDEPRECIADOS], [VALORSALVAMENTO], [AJUSTEACUMULADO], [IDAREA], [NOLOTE], 
							[CATEGORIA], [IDITAR], [IDARTICULO], [CODPRG], [CODUNG], [CUENTA_AJINFLACION], [CUENTA_AJDEPRECIACION], [CUENTA_AJINFLA_DEP], 
							[AJUSTEDEPACUMULADA], [DEPRECIABLE], [SUBCCOSTO], [ICODALTERNO], [IDTIPONIIF], [PRECIOCOMERCIALNIIF], [DEPACUMHISTORICANIIF], 
							[DEPACUMDIFERIDANIIF], [FECHAULTDEPRECNIIF], [VALORSALVAMENTONIIF], [MESESADEPRECIARNIIF], [MESESDEPRECIADOSNIIF], [SECTOR], 
							[CLASEGRUPO], [FPRIMERMTTO], [NROMTTOANUAL], [FULTIMOMTTO], [CLASEMMTO], [ANOFAB], [RINVIMA], [ESTAUSO], [VOLTAMAX], [VOLTAMIN], 
							[CORRIENTEMAX], [FUSIBLE], [POTENCIA], [FRECUENCIA], [VELOCIDAD], [PESO], [PRESION], [TEMPOPERA], [HUMEREL], [TECNODOMI], [RIESGO], 
							[CLASEQUI], [FUNCIONAMIENTO], [SECALIBRA], [PERIOCALI], [FULTIMACALI], [PARADA], [IDFOTO], [M_OPERE], [M_MMTO], [M_PARTES], 
							[PLANO_ELECT], [PLANO_ELEC], [PLANO_NEU], [PLANO_MECA], [USO], [TIPO_MMTO], [ALTERNATIVA], [PROPIEDAD], [GARANTIA], [M_DESPIECE], 
							[TIPOELEMENTO], [REFRIGERANTE], [CAPACIDAD], [CAPACITOR], [PLACA_ACTUAL], [PLACA_ANTIGUA]
							)
						SELECT @IDACTIVO, @IDTIPOACTIVO, @DESCRIPCION, @FECHACOMPRA, @PRECIOCOMPRA, @PRECIOCOMERCIAL, @REFERENCIA, @MODELOIACT, @MARCA, 
							@NOESCRITURA, @LINDEROS, @NOPARTE, @MATRICULA, @SERIAL, @CCOSTO, @UBICACION, @RESPONSABLE, @IDTERCERO, @ESTADO, @DEPACUMHISTORICA, 
							@DEPACUMDIFERIDA, @FECHAULTDEPRECIACION, @TIPOASOCIACION, @IDACTIVOGRUPO, @CODIGOINTERNO, @CODIGOBARRA, @CUENTA, @IDBODEGA, 
							@MESESADEPRECIAR, @MESESDEPRECIADOS, @VALORSALVAMENTO, @AJUSTEACUMULADO, @IDAREA, @NOLOTE, @CATEGORIA, @IDITAR, @IDARTICULO, 
							@CODPRG, @CODUNG, @CUENTA_AJINFLACION, @CUENTA_AJDEPRECIACION, @CUENTA_AJINFLA_DEP, @AJUSTEDEPACUMULADA, @DEPRECIABLE, @SUBCCOSTO
							, @ICODALTERNO, @IDTIPONIIF, @PRECIOCOMERCIALNIIF, @DEPACUMHISTORICANIIF, @DEPACUMDIFERIDANIIF, @FECHAULTDEPRECNIIF, 
							@VALORSALVAMENTONIIF, @MESESADEPRECIARNIIF, @MESESDEPRECIADOSNIIF, @SECTOR, @CLASEGRUPO, @FPRIMERMTTO, @NROMTTOANUAL, 
							@FULTIMOMTTO, @CLASEMMTO, @ANOFAB, @RINVIMA, @ESTAUSO, @VOLTAMAX, @VOLTAMIN, @CORRIENTEMAX, @FUSIBLE, @POTENCIA, @FRECUENCIA, 
							@VELOCIDAD, @PESO, @PRESION, @TEMPOPERA, @HUMEREL, @TECNODOMI, @RIESGO, @CLASEQUI, @FUNCIONAMIENTO, @SECALIBRA, @PERIOCALI, 
							@FULTIMACALI, @PARADA, @IDFOTO, @M_OPERE, @M_MMTO, @M_PARTES, @PLANO_ELECT, @PLANO_ELEC, @PLANO_NEU, @PLANO_MECA, @USO, @TIPO_MMTO, 
							@ALTERNATIVA, @PROPIEDAD, @GARANTIA, @M_DESPIECE, @TIPOELEMENTO, @REFRIGERANTE, @CAPACIDAD, @CAPACITOR, @PLACA_ACTUAL, 
							@PLACA_ANTIGUA
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK, @IDACTIVO CNS

				RETURN
			END

			IF UPPER(@PROCESO) = 'EDITAR'
			BEGIN
				BEGIN TRY
					INSERT INTO @TBLERRORES (ERROR)
					SELECT 'EL SERIAL YA EXISTE, EL SERIAL DEBE SER UNICO PARA CADA ACTIVO'
					WHERE EXISTS (
							SELECT SERIAL
							FROM IACT
							WHERE SERIAL = @SERIAL AND IDTIPOACTIVO <> @IDTIPOACTIVO AND IDACTIVO <> @IDACTIVO
							)

					--20250909 STORRES -- SE AGREGA UN FILTRO PARA QUE NO TOME EL MISMO ACTIVO 
					IF (LTRIM(RTRIM(ISNULL(@ICODALTERNO, ''))) <> '')
					BEGIN
						INSERT INTO @TBLERRORES (ERROR)
						SELECT 'CODIGO ALTERNO DUPLICADO, EL CODIGO ALTERNO DEBE SER UNICO PARA CADA ACTIVO'
						WHERE EXISTS (
								SELECT ICODALTERNO
								FROM IACT
								WHERE ICODALTERNO = @ICODALTERNO AND IDTIPOACTIVO <> @IDTIPOACTIVO AND IDACTIVO <> @IDACTIVO
									--20250909 STORRES -- SE AGREGA UN FILTRO PARA QUE NO TOME EL MISMO ACTIVO 
								)
					END

					INSERT INTO @TBLERRORES (ERROR)
					SELECT 'CODIGOINTERNO DUPLICADO,EL CODIGOINTERNO DEBE SER UNICO PARA CADA ACTIVO'
					WHERE EXISTS (
							SELECT CODIGOINTERNO
							FROM IACT
							WHERE CODIGOINTERNO = @CODIGOINTERNO AND IDTIPOACTIVO <> @IDTIPOACTIVO AND IDACTIVO <> @IDACTIVO
							)

					--20250909 STORRES -- SE AGREGA UN FILTRO PARA QUE NO TOME EL MISMO ACTIVO 
					IF (
							SELECT COUNT(*)
							FROM @TBLERRORES
							) <= 0
					BEGIN
						UPDATE IACT
						SET IDTIPOACTIVO = @IDTIPOACTIVO, DESCRIPCION = @DESCRIPCION, FECHACOMPRA = @FECHACOMPRA, PRECIOCOMPRA = @PRECIOCOMPRA, PRECIOCOMERCIAL = 
							@PRECIOCOMERCIAL, REFERENCIA = @REFERENCIA, MODELO = @MODELOIACT, MARCA = @MARCA, NOESCRITURA = @NOESCRITURA, LINDEROS = @LINDEROS, 
							NOPARTE = @NOPARTE, MATRICULA = @MATRICULA, SERIAL = @SERIAL, CCOSTO = @CCOSTO, UBICACION = @UBICACION, RESPONSABLE = @RESPONSABLE, 
							IDTERCERO = @IDTERCERO, ESTADO = @ESTADO, DEPACUMHISTORICA = @DEPACUMHISTORICA, DEPACUMDIFERIDA = @DEPACUMDIFERIDA, 
							FECHAULTDEPRECIACION = @FECHAULTDEPRECIACION, TIPOASOCIACION = @TIPOASOCIACION, IDACTIVOGRUPO = @IDACTIVOGRUPO, CODIGOINTERNO = 
							@CODIGOINTERNO, CODIGOBARRA = @CODIGOBARRA, CUENTA = @CUENTA, IDBODEGA = @IDBODEGA, MESESADEPRECIAR = @MESESADEPRECIAR, 
							MESESDEPRECIADOS = @MESESDEPRECIADOS, VALORSALVAMENTO = @VALORSALVAMENTO, AJUSTEACUMULADO = @AJUSTEACUMULADO, IDAREA = @IDAREA, NOLOTE 
							= @NOLOTE, CATEGORIA = @CATEGORIA, IDITAR = @IDITAR, IDARTICULO = @IDARTICULO, CODPRG = @CODPRG, CODUNG = @CODUNG, CUENTA_AJINFLACION = 
							@CUENTA_AJINFLACION, CUENTA_AJDEPRECIACION = @CUENTA_AJDEPRECIACION, CUENTA_AJINFLA_DEP = @CUENTA_AJINFLA_DEP, AJUSTEDEPACUMULADA 
							= @AJUSTEDEPACUMULADA, DEPRECIABLE = @DEPRECIABLE, SUBCCOSTO = @SUBCCOSTO, ICODALTERNO = @ICODALTERNO, IDTIPONIIF = @IDTIPONIIF, 
							PRECIOCOMERCIALNIIF = @PRECIOCOMERCIALNIIF, DEPACUMHISTORICANIIF = @DEPACUMHISTORICANIIF, DEPACUMDIFERIDANIIF = 
							@DEPACUMDIFERIDANIIF, FECHAULTDEPRECNIIF = @FECHAULTDEPRECNIIF, VALORSALVAMENTONIIF = @VALORSALVAMENTONIIF, MESESADEPRECIARNIIF = 
							@MESESADEPRECIARNIIF, MESESDEPRECIADOSNIIF = @MESESDEPRECIADOSNIIF, SECTOR = @SECTOR, CLASEGRUPO = @CLASEGRUPO, FPRIMERMTTO = 
							@FPRIMERMTTO, NROMTTOANUAL = @NROMTTOANUAL, FULTIMOMTTO = @FULTIMOMTTO, CLASEMMTO = @CLASEMMTO, ANOFAB = @ANOFAB, RINVIMA = @RINVIMA, 
							ESTAUSO = @ESTAUSO, VOLTAMAX = @VOLTAMAX, VOLTAMIN = @VOLTAMIN, CORRIENTEMAX = @CORRIENTEMAX, FUSIBLE = @FUSIBLE, POTENCIA = @POTENCIA, 
							FRECUENCIA = @FRECUENCIA, VELOCIDAD = @VELOCIDAD, PESO = @PESO, PRESION = @PRESION, TEMPOPERA = @TEMPOPERA, HUMEREL = @HUMEREL, TECNODOMI = 
							@TECNODOMI, RIESGO = @RIESGO, CLASEQUI = @CLASEQUI, FUNCIONAMIENTO = @FUNCIONAMIENTO, SECALIBRA = @SECALIBRA, PERIOCALI = @PERIOCALI, 
							FULTIMACALI = @FULTIMACALI, PARADA = @PARADA, M_OPERE = @M_OPERE, M_MMTO = @M_MMTO, M_PARTES = @M_PARTES, PLANO_ELECT = @PLANO_ELECT, 
							PLANO_ELEC = @PLANO_ELEC, PLANO_NEU = @PLANO_NEU, PLANO_MECA = @PLANO_MECA, USO = @USO, TIPO_MMTO = @TIPO_MMTO, ALTERNATIVA = @ALTERNATIVA, 
							PROPIEDAD = @PROPIEDAD, GARANTIA = @GARANTIA, M_DESPIECE = @M_DESPIECE, TIPOELEMENTO = @TIPOELEMENTO, REFRIGERANTE = @REFRIGERANTE, 
							CAPACIDAD = @CAPACIDAD, CAPACITOR = @CAPACITOR, PLACA_ACTUAL = @PLACA_ACTUAL, PLACA_ANTIGUA = @PLACA_ANTIGUA
						WHERE IDACTIVO = @IDACTIVO
					END
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH

				IF (
						SELECT COUNT(*)
						FROM @TBLERRORES
						) > 0
				BEGIN
					SELECT 'KO' OK

					SELECT ERROR
					FROM @TBLERRORES

					RETURN
				END

				SELECT 'OK' OK, @IDACTIVO CNS

				RETURN
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES (ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK

			SELECT ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK
	END

	IF @METODO = 'TRE_TIPOACT'
	BEGIN
		SELECT 'OK' OK

		SELECT @IDTIPOACTIVO = JSON_VALUE(@PARAMETROS, '$.IDTIPOACTIVO')

		SELECT CAST(IIF(PIDELINDEROS = 'SI', 1, 0) AS BIT) AS PIDELINDEROS, CAST(IIF(PIDEMODELO = 'SI', 1, 0) AS BIT) AS PIDEMODELO, CAST(IIF(PIDENOESCRITURA = 'SI', 1, 0) AS 
				BIT) AS PIDENOESCRITURA, CAST(IIF(PIDEMARCA = 'SI', 1, 0) AS BIT) AS PIDEMARCA, CAST(IIF(PIDESERIAL = 'SI', 1, 0) AS BIT) AS PIDESERIAL, CAST(IIF(
					PIDENOPARTES = 'SI', 1, 0) AS BIT) AS PIDENOPARTES, CAST(IIF(PIDEREFERENCIA = 'SI', 1, 0) AS BIT) AS PIDEREFERENCIA, CAST(IIF(PIDEMATRICULA = 'SI', 1, 0
				) AS BIT) AS PIDEMATRICULA
		FROM IACTT
		WHERE IDTIPOACTIVO = @IDTIPOACTIVO

		RETURN
	END

	IF @METODO = 'OBTENER_FOTO'
	BEGIN
		SELECT @IDACTIVO = IDACTIVO
		FROM OPENJSON(@PARAMETROS) WITH (IDACTIVO VARCHAR(20) '$.IDACTIVO')

		SELECT OK = 'OK', A.NOMBRE NOMBRE_FOTO, A.DICOM FOTO
		FROM IACT
		LEFT JOIN ARCHIVOS A ON A.ID = IACT.IDFOTO
		WHERE IACT.IDACTIVO = @IDACTIVO

		RETURN
	END

	IF @METODO = 'INFO_HV_IACT'
	BEGIN
		SELECT @IDACTIVO = IDACTIVO
		FROM OPENJSON(@PARAMETROS) WITH (IDACTIVO VARCHAR(20) '$.IDACTIVO')

		SELECT 'OK' OK

		SELECT IACT.*, TER.RAZONSOCIAL AS FABRICANTE
		FROM IACT
		INNER JOIN TER ON TER.IDTERCERO = IACT.IDTERCERO
		WHERE IACT.IDACTIVO = @IDACTIVO

		SELECT *
		FROM IACTEQU
		WHERE IDACTIVO = @IDACTIVO

		RETURN
	END
END

