CREATE OR ALTER PROCEDURE DBO.SPQ_KMCOM_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy

DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE @PARAMETROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @USUARIO VARCHAR(12), @COMPANIA VARCHAR(2), @IDSEDE VARCHAR(5), @SYS_COMPUTERNAME 
	VARCHAR(200), @DATOS VARCHAR(MAX), @IDMODELOCONT VARCHAR(2), @IDTIPOCONT VARCHAR(20), @IDAREA VARCHAR(20), @CCOSTO VARCHAR(20), @CLASECONT VARCHAR(20), 
	@PROCESO VARCHAR(20), @PREFIJO VARCHAR(20), @CUENTADB VARCHAR(20), @CUENTACR VARCHAR(20), @CUENTAIPS VARCHAR(20), @PGP BIT, @CUENTAPGP VARCHAR(20), @CAPITA BIT, 
	@CUENTACAPI VARCHAR(20), @TIPO VARCHAR(4), @IDSERVICIO VARCHAR(20), @IDSERVICIOANT VARCHAR(20), @CUENTAANT VARCHAR(20), @MIVA BIT, @CUENTAIVA VARCHAR(20)

BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (MODELO VARCHAR(100) '$.MODELO', METODO VARCHAR(100) '$.METODO', USUARIO VARCHAR(12) '$.USUARIO', PARAMETROS NVARCHAR(MAX) AS JSON
			)

	SELECT @MODELO = MODELO, @METODO = METODO, @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON

	IF @METODO = 'TRAER_KTCO'
	BEGIN
		SELECT 'OK' OK

		SELECT IDTIPOCONT, DESCRIPCION
		FROM KTCO
		WHERE 1 = CASE 
				WHEN DBO.FNK_VALORVARIABLE('IDPROCESOCONTABLE') <> 'MIXTO'
					THEN CASE 
							WHEN IDTIPOCONT IN ('NIIF_DEPRECIACION', 'NIIF_INGRESO', 'PRESTACIONES')
								THEN 0
							ELSE 1
							END
				ELSE 1
				END
		ORDER BY IDTIPOCONT

		RETURN
	END

	IF @METODO = 'TRAE_CUENTAS'
	BEGIN
		PRINT '@PARAMETROS =' + COALESCE(@PARAMETROS, '')

		SELECT @IDTIPOCONT = IDTIPOCONT, @PREFIJO = PREFIJO, @CCOSTO = CCOSTO
		FROM OPENJSON(@PARAMETROS) WITH (IDTIPOCONT VARCHAR(20) '$.IDTIPOCONT', PREFIJO VARCHAR(20) '$.PREFIJO', CCOSTO VARCHAR(20) '$.CCOSTO')

		SELECT 'OK' OK, CUENTADB, CUE.NOMCUENTA AS NOMCUENTADB, CUENTACR, X.NOMCUENTA AS NOMCUENTACR
		FROM (
			SELECT COALESCE(DB.IDTIPOCONT, CR.IDTIPOCONT) IDTIPOCONT, COALESCE(DB.PREFIJO, CR.PREFIJO) PREFIJO, COALESCE(DB.CCOSTO, CR.CCOSTO) CCOSTO, COALESCE(
					DB.CUENTADB, '') CUENTADB, COALESCE(CUENTACR, '') CUENTACR
			FROM (
				SELECT IDTIPOCONT, CCOSTO, PREFIJO, CUENTA AS CUENTADB
				FROM KMCOM
				WHERE TIPO = 'DB'
				) DB
			FULL JOIN (
				SELECT IDTIPOCONT, CCOSTO, PREFIJO, CUENTA AS CUENTACR
				FROM KMCOM
				WHERE TIPO = 'CR'
				) CR ON DB.IDTIPOCONT = CR.IDTIPOCONT AND DB.CCOSTO = CR.CCOSTO AND DB.PREFIJO = CR.PREFIJO
			) KM
		LEFT JOIN CUE ON KM.CUENTADB = CUE.CUENTA
		LEFT JOIN CUE X ON KM.CUENTACR = X.CUENTA
		WHERE KM.IDTIPOCONT = @IDTIPOCONT AND CCOSTO = @CCOSTO AND PREFIJO = @PREFIJO

		IF @IDTIPOCONT = 'VENTAS'
		BEGIN
			SELECT 'OK' OK, KMCOM.CUENTAIPS, CUE.NOMCUENTA AS NOMCUENTAIPS, COALESCE(KMCOM.MPGP, 0) PGP, KMCOM.CUECRPGP AS CUENTAPGP, P.NOMCUENTA AS NOMCUENTAPGP, 
				COALESCE(KMCOM.MCAPITA, 0) CAPITA, KMCOM.CUECRCAP AS CUENTACAPI, C.NOMCUENTA AS NOMCUENTACAPI
			FROM KMCOM
			LEFT JOIN CUE ON KMCOM.CUENTAIPS = CUE.CUENTA
			LEFT JOIN CUE AS P ON KMCOM.CUECRPGP = P.CUENTA
			LEFT JOIN CUE AS C ON KMCOM.CUECRCAP = C.CUENTA
			WHERE KMCOM.IDTIPOCONT = @IDTIPOCONT AND KMCOM.CCOSTO = @CCOSTO AND KMCOM.PREFIJO = @PREFIJO
		END
	END

	IF @METODO = 'CRUD_KMCOM'
	BEGIN
		SELECT @DATOS = DATOS
		FROM OPENJSON(@PARAMETROS) WITH (DATOS NVARCHAR(MAX) AS JSON)

		SELECT @IDMODELOCONT = IDMODELOCONT, @IDTIPOCONT = IDTIPOCONT, @IDAREA = IDAREA, @CCOSTO = CCOSTO, @CLASECONT = CLASECONT, @PROCESO = PROCESO, @PREFIJO = PREFIJO, 
			@CUENTADB = CUENTADB, @CUENTACR = CUENTACR, @CUENTAIPS = CUENTAIPS, @PGP = CASE 
				WHEN COALESCE(PGP, 'false') = 'true'
					THEN 1
				ELSE 0
				END, @CUENTAPGP = CUENTAPGP, @TIPO = TIPO, @CAPITA = CASE 
				WHEN COALESCE(CAPITA, 'false') = 'true'
					THEN 1
				ELSE 0
				END, @CUENTACAPI = CUENTACAPI, @MIVA = CASE 
				WHEN COALESCE(MIVA, 'false') = 'true'
					THEN 1
				ELSE 0
				END, @CUENTAIVA = CUENTAIVA
		FROM OPENJSON(@DATOS) WITH (
				IDMODELOCONT VARCHAR(3) '$.IDMODELOCONT', IDTIPOCONT VARCHAR(20) '$.IDTIPOCONT', IDAREA VARCHAR(20) '$.IDAREA', CCOSTO VARCHAR(20) '$.CCOSTO', 
				CLASECONT VARCHAR(20) '$.CLASECONT', PROCESO VARCHAR(20) '$.PROCESO', NOMAREA VARCHAR(20) '$.NOMAREA', PREFIJO VARCHAR(20) '$.PREFIJO', CUENTADB 
				VARCHAR(20) '$.CUENTADB', CUENTACR VARCHAR(20) '$.CUENTACR', CUENTAIPS VARCHAR(20) '$.CUENTAIPS', PGP VARCHAR(20) '$.PGP', CUENTAPGP VARCHAR(20) 
				'$.CUENTAPGP', CAPITA VARCHAR(20) '$.CAPITA', TIPO VARCHAR(20) '$.TIPO', CUENTACAPI VARCHAR(20) '$.CUENTACAPI', MIVA VARCHAR(20) '$.MIVA', 
				CUENTAIVA VARCHAR(20) '$.CUENTAIVA'
				)

		IF NOT EXISTS (
				SELECT *
				FROM CEN
				WHERE CCOSTO = @CCOSTO AND IDAREA = @IDAREA
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Centro de Costo no Valido, Verifique e intente de nuevo'
		END

		IF NOT EXISTS (
				SELECT *
				FROM CUE
				WHERE CUENTA = @CUENTADB AND TIPO = 'Detalle'
				) AND @IDTIPOCONT NOT IN ('VENTAS', 'NOMINA')
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Cuenta contable Debito No Valida, Verifique e intente de nuevo'
		END

		IF NOT EXISTS (
				SELECT *
				FROM CUE
				WHERE CUENTA = @CUENTACR AND TIPO = 'Detalle'
				) AND @IDTIPOCONT NOT IN ('VENTAS', 'CXP_SERVICIOS', 'CXP_COMPRAS', 'CXP_SALUD', 'NOMINA')
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Cuenta contable Credito No Valida, Verifique e intente de nuevo'
		END

		IF @IDTIPOCONT = 'VENTAS' AND NOT EXISTS (
				SELECT *
				FROM PRE
				WHERE PREFIJO = @PREFIJO
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Prefijo no Valido, Verifique e intente de nuevo'
		END

		IF @IDTIPOCONT = 'CAJA_MENOR' AND NOT EXISTS (
				SELECT *
				FROM CPCJ
				WHERE CODIGO = @PREFIJO AND COALESCE(DECAJAMENOR, 0) = 1
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Concepto de Caja no Valido, Verifique e intente de nuevo'
		END

		IF @IDTIPOCONT = 'CXP_COMPRAS' AND NOT EXISTS (
				SELECT *
				FROM ITAR
				WHERE IDITAR = @PREFIJO
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Tipo de Articulo no Valido, Verifique e intente de nuevo'
		END

		PRINT 'HOLA' + @PREFIJO

		IF @IDTIPOCONT = 'CXP_SERVICIOS' AND NOT EXISTS (
				SELECT *
				FROM FCTSER
				WHERE IDTIPOSER = @PREFIJO
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Tipo de Servicio no Valido, Verifique e intente de nuevo'
		END

		IF @IDTIPOCONT = 'DEPRECIACION' AND NOT EXISTS (
				SELECT *
				FROM IACTT
				WHERE IDTIPOACTIVO = @PREFIJO
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Tipo de Activo  no Valido, Verifique e intente de nuevo'
		END

		IF @IDTIPOCONT = 'DESCUENTOS' AND NOT EXISTS (
				SELECT *
				FROM SER
				WHERE PREFIJO = @PREFIJO
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Tipo de Activo  no Valido, Verifique e intente de nuevo'
		END

		IF @IDTIPOCONT = 'MOV_ACTIVOS' AND NOT EXISTS (
				SELECT *
				FROM IACTE
				WHERE IDEVENTO = @PREFIJO
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Evento de Activo  no Valido, Verifique e intente de nuevo'
		END

		IF @IDTIPOCONT = 'MOV_INVENTARIO' AND NOT EXISTS (
				SELECT *
				FROM ITMO
				WHERE IDTIPOMOV = @PREFIJO
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Tipo de Movimiento  no Valido, Verifique e intente de nuevo'
		END

		IF @IDTIPOCONT = 'NOMINA' AND NOT EXISTS (
				SELECT *
				FROM NCON
				WHERE CODCONCEPTO = @PREFIJO
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'Tipo de Movimiento  no Valido, Verifique e intente de nuevo'
		END

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK, ERROR
			FROM @TBLERRORES

			RETURN
		END

		IF @PROCESO = 'Nuevo'
		BEGIN
			IF @IDTIPOCONT <> 'VENTAS'
			BEGIN
				IF NOT EXISTS (
						SELECT *
						FROM KMCOM
						WHERE IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND CCOSTO = @CCOSTO AND CUENTA = @CUENTADB
						) AND COALESCE(@CUENTADB, '') <> ''
				BEGIN
					INSERT INTO KMCOM (
						IDMODELOCONT, IDTIPOCONT, TIPO, PREFIJO, IDAREA, CCOSTO, CUENTA, CLASECONT, ESTADO, CUENTAIPS, NIIF, CTA_PASIVOEST, MPGP, CUECRPGP, MCAPITA, 
						CUECRCAP, MIVA, CUENTAIVA
						)
					SELECT @IDMODELOCONT, @IDTIPOCONT, 'DB', @PREFIJO, @IDAREA, @CCOSTO, @CUENTADB, @CLASECONT, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, @MIVA, 
						@CUENTAIVA
				END
			END

			IF COALESCE(@CUENTACR, '') <> ''
			BEGIN
				IF @IDTIPOCONT = 'CXP_COMPRAS'
				BEGIN
					SELECT @MIVA = 0, @CUENTAIVA = NULL
				END

				INSERT INTO KMCOM (
					IDMODELOCONT, IDTIPOCONT, TIPO, PREFIJO, IDAREA, CCOSTO, CUENTA, CLASECONT, ESTADO, CUENTAIPS, NIIF, CTA_PASIVOEST, MPGP, CUECRPGP, MCAPITA, 
					CUECRCAP, MIVA, CUENTAIVA
					)
				SELECT @IDMODELOCONT, @IDTIPOCONT, 'CR', @PREFIJO, @IDAREA, @CCOSTO, @CUENTACR, @CLASECONT, NULL, IIF(@IDTIPOCONT = 'VENTAS', @CUENTAIPS, NULL), 0, 
					NULL, IIF(@IDTIPOCONT = 'VENTAS', @PGP, NULL), IIF(@IDTIPOCONT = 'VENTAS', @CUENTAPGP, NULL), IIF(@IDTIPOCONT = 'VENTAS', @CAPITA, NULL), IIF(
						@IDTIPOCONT = 'VENTAS', @CUENTACAPI, NULL), @MIVA, @CUENTAIVA
			END
		END

		IF @PROCESO = 'Editar'
		BEGIN
			IF @IDTIPOCONT <> 'VENTAS'
			BEGIN
				IF NOT EXISTS (
						SELECT *
						FROM KMCOM
						WHERE KMCOM.IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND CCOSTO = @CCOSTO AND IDAREA = @IDAREA AND TIPO = 'DB'
						)
				BEGIN
					INSERT INTO KMCOM (
						IDMODELOCONT, IDTIPOCONT, TIPO, PREFIJO, IDAREA, CCOSTO, CUENTA, CLASECONT, ESTADO, CUENTAIPS, NIIF, CTA_PASIVOEST, MPGP, CUECRPGP, MCAPITA, 
						CUECRCAP, MIVA, CUENTAIVA
						)
					SELECT @IDMODELOCONT, @IDTIPOCONT, 'DB', @PREFIJO, @IDAREA, @CCOSTO, @CUENTADB, @CLASECONT, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, @MIVA, 
						@CUENTAIVA
				END
				ELSE
				BEGIN
					IF COALESCE(@CUENTADB, '') <> ''
					BEGIN
						UPDATE KMCOM
						SET CUENTA = @CUENTADB, MIVA = @MIVA, CUENTAIVA = @MIVA
						WHERE KMCOM.IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND CCOSTO = @CCOSTO AND IDAREA = @IDAREA AND TIPO = 'DB'
					END
					ELSE
					BEGIN
						DELETE KMCOM
						WHERE KMCOM.IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND CCOSTO = @CCOSTO AND IDAREA = @IDAREA AND TIPO = 'DB'
					END
				END

				IF @IDTIPOCONT = 'CXP_COMPRAS'
				BEGIN
					SELECT @MIVA = 0, @CUENTAIVA = NULL
				END

				IF NOT EXISTS (
						SELECT *
						FROM KMCOM
						WHERE KMCOM.IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND CCOSTO = @CCOSTO AND IDAREA = @IDAREA AND TIPO = 'CR'
						)
				BEGIN
					INSERT INTO KMCOM (
						IDMODELOCONT, IDTIPOCONT, TIPO, PREFIJO, IDAREA, CCOSTO, CUENTA, CLASECONT, ESTADO, CUENTAIPS, NIIF, CTA_PASIVOEST, MPGP, CUECRPGP, MCAPITA, 
						CUECRCAP, MIVA, CUENTAIVA
						)
					SELECT @IDMODELOCONT, @IDTIPOCONT, 'CR', @PREFIJO, @IDAREA, @CCOSTO, @CUENTACR, @CLASECONT, NULL, IIF(@IDTIPOCONT = 'VENTAS', @CUENTAIPS, NULL), 
						0, NULL, IIF(@IDTIPOCONT = 'VENTAS', @PGP, NULL), IIF(@IDTIPOCONT = 'VENTAS', @CUENTAPGP, NULL), IIF(@IDTIPOCONT = 'VENTAS', @CAPITA, NULL), 
						IIF(@IDTIPOCONT = 'VENTAS', @CUENTACAPI, NULL), @MIVA, @CUENTAIVA
				END
				ELSE
				BEGIN
					IF COALESCE(@CUENTACR, '') <> ''
					BEGIN
						UPDATE KMCOM
						SET CUENTA = @CUENTACR, MIVA = @MIVA, CUENTAIVA = @MIVA
						WHERE KMCOM.IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND CCOSTO = @CCOSTO AND IDAREA = @IDAREA AND TIPO = 'CR'
					END
					ELSE
					BEGIN
						DELETE KMCOM
						WHERE KMCOM.IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND CCOSTO = @CCOSTO AND IDAREA = @IDAREA AND TIPO = 'CR'
					END
				END
			END

			IF @IDTIPOCONT = 'VENTAS'
			BEGIN
				UPDATE KMCOM
				SET CUENTAIPS = @CUENTAIPS, MPGP = @PGP, CUECRPGP = CASE 
						WHEN COALESCE(@PGP, 0) = 1
							THEN @CUENTAPGP
						ELSE NULL
						END, MCAPITA = @CAPITA, CUECRCAP = CASE 
						WHEN COALESCE(@CAPITA, 0) = 1
							THEN @CUENTACAPI
						ELSE NULL
						END, MIVA = @MIVA, CUENTAIVA = @MIVA, CUENTA = @CUENTACR
				WHERE KMCOM.IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND CCOSTO = @CCOSTO AND IDAREA = @IDAREA AND TIPO = 'CR'
			END
		END

		IF @PROCESO = 'Borrar'
		BEGIN
			DELETE KMCOM
			WHERE KMCOM.IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND CCOSTO = @CCOSTO AND IDAREA = @IDAREA
		END

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK, ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK

		RETURN
	END

	IF @METODO = 'CRUD_KMCOMS'
	BEGIN
		SELECT @DATOS = DATOS
		FROM OPENJSON(@PARAMETROS) WITH (DATOS NVARCHAR(MAX) AS JSON)

		SELECT @IDMODELOCONT = IDMODELOCONT, @IDTIPOCONT = IDTIPOCONT, @IDAREA = IDAREA, @CCOSTO = CCOSTO, @CLASECONT = CLASECONT, @PROCESO = PROCESO, @PREFIJO = PREFIJO, 
			@CUENTADB = CUENTADB, @CUENTACR = CUENTACR, @CUENTAIPS = CUENTAIPS, @IDSERVICIO = IDSERVICIO, @TIPO = TIPO, @IDSERVICIOANT = IDSERVICIOANT, @CUENTAANT = 
			CUENTAANT, @MIVA = CASE 
				WHEN COALESCE(MIVA, 'false') = 'true'
					THEN 1
				ELSE 0
				END, @CUENTAIVA = CUENTAIVA
		FROM OPENJSON(@DATOS) WITH (
				IDMODELOCONT VARCHAR(3) '$.IDMODELOCONT', IDTIPOCONT VARCHAR(20) '$.IDTIPOCONT', IDAREA VARCHAR(20) '$.IDAREA', CCOSTO VARCHAR(20) '$.CCOSTO', 
				CLASECONT VARCHAR(20) '$.CLASECONT', PROCESO VARCHAR(20) '$.PROCESO', PREFIJO VARCHAR(20) '$.PREFIJO', CUENTADB VARCHAR(20) '$.CUENTADB', CUENTACR 
				VARCHAR(20) '$.CUENTACR', CUENTAIPS VARCHAR(20) '$.CUENTAIPS', IDSERVICIO VARCHAR(20) '$.IDSERVICIO', TIPO VARCHAR(20) '$.TIPO', IDSERVICIOANT 
				VARCHAR(20) '$.IDSERVICIOANT', CUENTAANT VARCHAR(20) '$.CUENTAANT', MIVA VARCHAR(20) '$.MIVA', CUENTAIVA VARCHAR(20) '$.CUENTAIVA'
				)

		IF @PROCESO <> 'Borrar' AND NOT EXISTS (
				SELECT *
				FROM CUE
				WHERE (CUENTA = @CUENTADB OR CUENTA = @CUENTACR) AND TIPO = 'Detalle'
				)
		BEGIN
			INSERT INTO @TBLERRORES (ERROR)
			SELECT 'La cuenta contable no es valida, verifique e intente de nuevo'
		END

		IF @IDTIPOCONT = 'VENTAS'
		BEGIN
			IF NOT EXISTS (
					SELECT *
					FROM SER
					WHERE IDSERVICIO = @IDSERVICIO AND ESTADO = 'Activo'
					)
			BEGIN
				INSERT INTO @TBLERRORES (ERROR)
				SELECT 'El Servicio no existe o esta Inactivo, verifique e intente de nuevo'
			END
		END

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK, ERROR
			FROM @TBLERRORES

			RETURN
		END

		IF @PROCESO = 'Nuevo'
		BEGIN
			PRINT 'NUEVO...'

			IF NOT EXISTS (
					SELECT *
					FROM KMCOMS
					WHERE CUENTA = @CUENTADB AND TIPO = 'DB' AND IDSERVICIO = @IDSERVICIO AND IDMODELOCONT = @IDMODELOCONT AND IDTIPOCONT = @IDTIPOCONT AND PREFIJO = 
						@PREFIJO AND IDAREA = @IDAREA AND CCOSTO = @CCOSTO
					)
			BEGIN
				BEGIN TRY
					PRINT 'INSERTANDO EL DB'

					INSERT INTO KMCOMS (
						IDMODELOCONT, IDTIPOCONT, TIPO, PREFIJO, IDAREA, CCOSTO, IDSERVICIO, CUENTA, ESTADO, CUENTAIPS, CTA_PASIVOEST, PGP, CUEPGP, CAPITA, 
						CUECAPITA, MIVA, CUENTAIVA
						)
					SELECT @IDMODELOCONT, @IDTIPOCONT, 'DB', @PREFIJO, @IDAREA, @CCOSTO, @IDSERVICIO, @CUENTADB, 'Activo', @CUENTAIPS, NULL, NULL, NULL, NULL, NULL, 
						@MIVA, @CUENTAIVA
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH
			END
			ELSE
			BEGIN
				INSERT INTO @TBLERRORES (ERROR)
				SELECT 'Ya existe un registro con esta Exepción, no se puede continuar, Verifique e intente de nuevo'
			END

			IF NOT EXISTS (
					SELECT *
					FROM KMCOMS
					WHERE CUENTA = @CUENTACR AND TIPO = 'CR' AND IDSERVICIO = @IDSERVICIO AND IDMODELOCONT = @IDMODELOCONT AND IDTIPOCONT = @IDTIPOCONT AND PREFIJO = 
						@PREFIJO AND IDAREA = @IDAREA AND CCOSTO = @CCOSTO
					)
			BEGIN
				BEGIN TRY
					PRINT 'INSERTANDO EL CR'

					INSERT INTO KMCOMS (
						IDMODELOCONT, IDTIPOCONT, TIPO, PREFIJO, IDAREA, CCOSTO, IDSERVICIO, CUENTA, ESTADO, CUENTAIPS, CTA_PASIVOEST, PGP, CUEPGP, CAPITA, 
						CUECAPITA, MIVA, CUENTAIVA
						)
					SELECT @IDMODELOCONT, @IDTIPOCONT, 'CR', @PREFIJO, @IDAREA, @CCOSTO, @IDSERVICIO, @CUENTACR, 'Activo', @CUENTAIPS, NULL, NULL, NULL, NULL, NULL, 
						@MIVA, @CUENTAIVA
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH
			END
			ELSE
			BEGIN
				INSERT INTO @TBLERRORES (ERROR)
				SELECT 'Ya existe un registro con esta Exepción, no se puede continuar, Verifique e intente de nuevo'
			END
		END

		IF @PROCESO = 'Editar'
		BEGIN
			IF NOT EXISTS (
					SELECT *
					FROM KMCOMS
					WHERE CUENTA = @CUENTADB AND TIPO = 'DB' AND IDSERVICIO = @IDSERVICIO AND IDMODELOCONT = @IDMODELOCONT AND IDTIPOCONT = @IDTIPOCONT AND PREFIJO = 
						@PREFIJO AND IDAREA = @IDAREA AND CCOSTO = @CCOSTO
					)
			BEGIN
				BEGIN TRY
					INSERT INTO KMCOMS (
						IDMODELOCONT, IDTIPOCONT, TIPO, PREFIJO, IDAREA, CCOSTO, IDSERVICIO, CUENTA, ESTADO, CUENTAIPS, CTA_PASIVOEST, PGP, CUEPGP, CAPITA, 
						CUECAPITA, MIVA, CUENTAIVA
						)
					SELECT @IDMODELOCONT, @IDTIPOCONT, 'DB', @PREFIJO, @IDAREA, @CCOSTO, @IDSERVICIO, @CUENTADB, 'Activo', @CUENTAIPS, NULL, NULL, NULL, NULL, NULL, 
						@MIVA, @CUENTAIVA
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH
			END
			ELSE
			BEGIN
				BEGIN TRY
					UPDATE KMCOMS
					SET CUENTA = @CUENTADB, IDSERVICIO = @IDSERVICIO, MIVA = @MIVA, CUENTAIVA = @CUENTAIVA
					WHERE IDMODELOCONT = @IDMODELOCONT AND TIPO = 'DB' AND IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND IDAREA = @IDAREA AND CCOSTO = @CCOSTO AND 
						IDSERVICIO = @IDSERVICIOANT
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH
			END

			IF NOT EXISTS (
					SELECT *
					FROM KMCOMS
					WHERE CUENTA = @CUENTACR AND TIPO = 'CR' AND IDSERVICIO = @IDSERVICIO AND IDMODELOCONT = @IDMODELOCONT AND IDTIPOCONT = @IDTIPOCONT AND PREFIJO = 
						@PREFIJO AND IDAREA = @IDAREA AND CCOSTO = @CCOSTO
					)
			BEGIN
				BEGIN TRY
					INSERT INTO KMCOMS (
						IDMODELOCONT, IDTIPOCONT, TIPO, PREFIJO, IDAREA, CCOSTO, IDSERVICIO, CUENTA, ESTADO, CUENTAIPS, CTA_PASIVOEST, PGP, CUEPGP, CAPITA, 
						CUECAPITA, MIVA, CUENTAIVA
						)
					SELECT @IDMODELOCONT, @IDTIPOCONT, 'CR', @PREFIJO, @IDAREA, @CCOSTO, @IDSERVICIO, @CUENTACR, 'Activo', @CUENTAIPS, NULL, NULL, NULL, NULL, NULL, 
						@MIVA, @CUENTAIVA
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH
			END
			ELSE
			BEGIN
				BEGIN TRY
					UPDATE KMCOMS
					SET CUENTA = @CUENTACR, IDSERVICIO = @IDSERVICIO, MIVA = @MIVA, CUENTAIVA = @CUENTAIVA
					WHERE IDMODELOCONT = @IDMODELOCONT AND TIPO = 'CR' AND IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND IDAREA = @IDAREA AND CCOSTO = @CCOSTO AND 
						IDSERVICIO = @IDSERVICIOANT
				END TRY

				BEGIN CATCH
					INSERT INTO @TBLERRORES (ERROR)
					SELECT ERROR_MESSAGE()
				END CATCH
			END
		END

		IF @PROCESO = 'Borrar'
		BEGIN
			DELETE KMCOMS
			WHERE IDMODELOCONT = @IDMODELOCONT AND IDTIPOCONT = @IDTIPOCONT AND PREFIJO = @PREFIJO AND IDAREA = @IDAREA AND CCOSTO = @CCOSTO AND IDSERVICIO = @IDSERVICIOANT
		END

		IF (
				SELECT COUNT(*)
				FROM @TBLERRORES
				) > 0
		BEGIN
			SELECT 'KO' OK, ERROR
			FROM @TBLERRORES

			RETURN
		END

		SELECT 'OK' OK

		RETURN
	END

	IF @METODO = 'VALIDA_CODNOMI'
	BEGIN
		SELECT @PREFIJO = PREFIJO
		FROM OPENJSON(@PARAMETROS) WITH (PREFIJO VARCHAR(20) '$.CODCONCEPTO')

		IF EXISTS (
				SELECT *
				FROM NCON
				INNER JOIN NCOND ON NCON.CODCONCEPTO = NCOND.CODCONCEPTO
				WHERE NCON.CODCONCEPTO = @PREFIJO AND TIPO = 'Egreso' AND COALESCE(NCOND.VALOR_EMPRESA, 0) = 0
				)
		BEGIN
			SELECT TOP 1 'OK' OK, 'Egreso' TIPO, KMCOM.CUENTA, CUE.NOMCUENTA
			FROM KMCOM
			INNER JOIN CUE ON KMCOM.CUENTA = CUE.CUENTA
			WHERE IDTIPOCONT = 'NOMINA' AND KMCOM.TIPO = 'CR' AND PREFIJO = DBO.FNK_VALORVARIABLE('IDCONPSALARIO')
		END
		ELSE
		BEGIN
			SELECT 'OK' OK, 'Ingreso' TIPO
		END

		RETURN
	END
END

