CREATE OR ALTER PROCEDURE DBO.SPQ_FCXCR
    @JSON NVARCHAR(MAX)
WITH ENCRYPTION
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    -- 1. Declaración de variables
    DECLARE 
        @CNSCXC VARCHAR(20), @N_FACTURA VARCHAR(16), @MOTIVO1 VARCHAR(20), @MOTIVO2 VARCHAR(20),               
        @OBSERVACION VARCHAR(512), @COD_RESPUESTA VARCHAR(20), @RESPUESTA VARCHAR(1025), @ESTADO VARCHAR(10),
        @REGISTROS NVARCHAR(MAX), @MODELO VARCHAR(100), @METODO VARCHAR(100), @PARAMETROS NVARCHAR(MAX),
        @PROCESO VARCHAR(20), @SYS_COMPUTERNAME VARCHAR(256), @GRUPO VARCHAR(8), @IDSEDE VARCHAR(5),	
        @USUARIO VARCHAR(12), @ENVIAR VARCHAR(20),
        @SQL NVARCHAR(MAX), @CONTADOR_REGISTROS INT, @ERROR VARCHAR(4000), @CNSDEVOL VARCHAR(20),
        @NODOCUMENTO VARCHAR(20), @CNSENTREGAORI VARCHAR(20), @COORFACTURACION VARCHAR(20),
        @COORCARTERA VARCHAR(20), @IDTERCERO VARCHAR(20), @CNSPAGO VARCHAR(20),
        @SEDE VARCHAR(5), @MSEDE VARCHAR(5), @CONSECUTIVO_RAW VARCHAR(20), @USURESP VARCHAR(12),
        @OK VARCHAR(10);


    -- Tabla para capturar errores y retornarlos al frontend
    DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
    DECLARE @RESUL TABLE(DATO1 NVARCHAR(MAX), DATO2 NVARCHAR(MAX));

    -- 2. Parseo inicial del JSON
    SELECT 
        @MODELO      = MODELO, 
        @METODO      = METODO, 
        @PARAMETROS  = PARAMETROS,
        @USUARIO     = USUARIO
    FROM OPENJSON(@JSON)
    WITH (
        MODELO      VARCHAR(100)    '$.MODELO',
        METODO      VARCHAR(100)    '$.METODO',
        PARAMETROS  NVARCHAR(MAX)   AS JSON,
        USUARIO     VARCHAR(12)     '$.USUARIO'
    );

    PRINT 'USUARIO: ' + ISNULL(@USUARIO, 'NO PROPORCIONADO');

    IF @USUARIO IS NOT NULL
    BEGIN
        SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO), @SYS_COMPUTERNAME = SYS_COMPUTERNAME 
        FROM USUSU WHERE USUARIO = @USUARIO;

        SELECT @IDSEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME;
        IF COALESCE(@IDSEDE, '') = '' SET @IDSEDE = '01';
    END
    PRINT 'SEDE: ' + ISNULL(@IDSEDE, '01');

    -- 3. Lógica por Método
    IF @METODO = 'DEFINIR_FACTURA'
    BEGIN
        SELECT @REGISTROS = REGISTRO, @PROCESO = PROCESO
        FROM OPENJSON(@PARAMETROS)
        WITH (REGISTRO NVARCHAR(MAX) AS JSON, PROCESO VARCHAR(20) '$.PROCESO');

        SELECT 
            @CNSCXC = CNSCXC, @N_FACTURA = N_FACTURA, @OBSERVACION = OBSERVACION,
            @COD_RESPUESTA = COD_RESPUESTA, @RESPUESTA = RESPUESTA, @ESTADO = ESTADO
        FROM OPENJSON(@REGISTROS)
        WITH (
            CNSCXC VARCHAR(20) '$.CNSCXC', N_FACTURA VARCHAR(16) '$.N_FACTURA',
            OBSERVACION VARCHAR(512) '$.OBSERVACION', COD_RESPUESTA VARCHAR(20) '$.COD_RESPUESTA',
            RESPUESTA VARCHAR(1025) '$.RESPUESTA', ESTADO VARCHAR(10) '$.ESTADO'
        );

        BEGIN TRY
            IF UPPER(@PROCESO) = 'EDITAR'
            BEGIN
                IF EXISTS (SELECT 1 FROM FCXCR WHERE CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA AND ESTADO <> '')
                    THROW 50001, 'Esta factura ya ha sido procesada.', 1;

                UPDATE FCXCR
                SET OBSERVACION = @OBSERVACION,
                    COD_RESPUESTA = @COD_RESPUESTA,
                    RESPUESTA = @RESPUESTA,
                    USURESP = @USUARIO,
                    ESTADO = @ESTADO
                WHERE CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA;
            END
            ELSE IF UPPER(@PROCESO) = 'LIBERAR'
            BEGIN
                IF EXISTS (SELECT 1 FROM FCXCR WHERE CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA AND ESTADO = '')
                    THROW 50002, 'Primero debe procesar la factura.', 1;

                UPDATE FCXCR SET ESTADO = '' WHERE CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA;
            END
        END TRY
        BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) VALUES (ERROR_MESSAGE());
        END CATCH

        -- Salto al retorno unificado
        GOTO FIN_PROCEDIMIENTO;
    END
    ELSE IF @METODO = 'ENVIAR_FACTURA'
    BEGIN         
        SELECT 
            @CNSCXC = CNSCXC, @N_FACTURA = N_FACTURA, @ENVIAR = ENVIAR,
            @SEDE = COALESCE(SEDE, @IDSEDE, '01'),
            @MSEDE = COALESCE(MSEDE, SEDE, @IDSEDE, '01'),
            @CNSPAGO = CNSPAGO
        FROM OPENJSON(@PARAMETROS)
        WITH (
            CNSCXC VARCHAR(20) '$.CNSCXC', N_FACTURA VARCHAR(20) '$.N_FACTURA',
            ENVIAR VARCHAR(20) '$.ENVIAR', SEDE VARCHAR(5) '$.SEDE',
            MSEDE VARCHAR(5) '$.MSEDE', CNSPAGO VARCHAR(20) '$.CNSPAGO'
        );

        IF @ENVIAR = 'DEVOL'
        BEGIN
            PRINT 'VOY A DEVOLVER FACTURAS';
            DECLARE @IDDEPFACT VARCHAR(20) = DBO.FNK_VALORVARIABLE('IDFDEPFACTURACION');

            SET @SQL = N'EXEC SPQ_JSON ''{"MODELO":"ENT_COL","METODO":"CRUD_ENT","PARAMETROS":{"DATOS":{"CNSENTREGA":"","PROCESO":"DEVFACT","FCXCR":"True","FECHA":null,"REQSEDE":"0","IDSEDE":"","DEP_RECIBE":"' + 
                       REPLACE(@IDDEPFACT, '''', '''''') + '","ESTADO":"","CERRADO":"","USU_ENVIA":""}},"USUARIO":"' + 
                       REPLACE(@USUARIO, '''', '''''') + '"}''';

            BEGIN TRY 
                INSERT INTO @RESUL(DATO1, DATO2) EXEC (@SQL);
                SELECT @CONTADOR_REGISTROS = COUNT(*) FROM @RESUL;
                
                IF @CONTADOR_REGISTROS = 0
                    INSERT INTO @TBLERRORES(ERROR) VALUES ('No se recibió respuesta válida de SPQ_JSON para la devolución.');
            END TRY 
            BEGIN CATCH 
                INSERT INTO @TBLERRORES(ERROR) VALUES ('Error ejecutando SPQ_JSON: ' + ERROR_MESSAGE());
            END CATCH
           
            SELECT TOP 1 @OK=DATO1, @CNSDEVOL = DATO2 FROM @RESUL;
            IF @OK<>'OK'
            BEGIN
               INSERT INTO @TBLERRORES(ERROR) SELECT TOP 1 DATO2 FROM @RESUL;
               GOTO FIN_PROCEDIMIENTO;
            END
            -- ? CAMBIO SOLICITADO: Se registra en @TBLERRORES en lugar de THROW
            IF @CNSDEVOL IS NULL
                INSERT INTO @TBLERRORES(ERROR) VALUES ('El campo CNSDEVOL vino vacío desde el servicio externo.');

            -- Si ya hay error, no continuamos con la lógica de devolución
            IF (SELECT COUNT(*) FROM @TBLERRORES) = 0
            BEGIN
                PRINT '@CNSDEVOL = ' + @CNSDEVOL;

                INSERT INTO ENTD(CNSENTREGA, NODOCUMENTO, PROCESO, ESTADO, USUARIOVERIFICA, MARCA, VALORENTREGA, OBSERVACION, ENDEVO, CNSDEVOL)
                SELECT @CNSDEVOL, N_FACTURA, 'DEVFACT', 0, NULL, 0, NULL, OBSERVACION, 0, NULL
                FROM FCXCR WHERE CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA;
                UPDATE FCXCR SET CNSDEVCXC=@CNSDEVOL,ENVIA='DEVOL' WHERE CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA;
                SELECT @SYS_COMPUTERNAME = COALESCE(U.SYS_ComputerName, HOST_NAME())   
                FROM USUSU U LEFT JOIN UBEQ E ON U.SYS_ComputerName = E.SYS_ComputerName
                WHERE U.USUARIO = @USUARIO;
                        
                DECLARE ENTDDEV_CURSOR CURSOR LOCAL FAST_FORWARD FOR 
                SELECT NODOCUMENTO FROM ENTD WHERE CNSENTREGA = @CNSDEVOL;
                
                OPEN ENTDDEV_CURSOR;    
                FETCH NEXT FROM ENTDDEV_CURSOR INTO @NODOCUMENTO;
                
                WHILE @@FETCH_STATUS = 0    
                BEGIN 
                    SELECT TOP 1 @CNSENTREGAORI = CNSENTREGA 
                    FROM ENTD 
                    WHERE NODOCUMENTO = @NODOCUMENTO AND PROCESO = 'FACTURAS' AND COALESCE(ENDEVO, 0) = 0;

                    IF @CNSENTREGAORI IS NOT NULL
                        UPDATE ENTD SET ENDEVO = 1, CNSDEVOL = @CNSDEVOL 
                        WHERE CNSENTREGA = @CNSENTREGAORI AND NODOCUMENTO = @NODOCUMENTO;
                    
                    FETCH NEXT FROM ENTDDEV_CURSOR INTO @NODOCUMENTO;
                END
                
                CLOSE ENTDDEV_CURSOR;
                DEALLOCATE ENTDDEV_CURSOR;
            END
        END
        ELSE IF @ENVIAR = 'CXC'
        BEGIN
            PRINT 'VOY A CREAR UNA NUEVA CXC';

            SELECT @OBSERVACION = LTRIM(RTRIM(OBSERVACION)) FROM USVGS WHERE IDVARIABLE = 'FCXC_OBSERVACION_DEF';
            SELECT @COORFACTURACION = DBO.FNK_VALORVARIABLE('USUARIOJEFEFACTURA'), 
                   @COORCARTERA = DBO.FNK_VALORVARIABLE('USUARIOJEFECARTERA');
            SELECT @IDTERCERO = IDTERCERO FROM FPAG WHERE CNSFPAG = @CNSPAGO;

            BEGIN TRY
                PRINT 'LLAMANDO A GENCONSECUTIVO @SEDE=' + ISNULL(@SEDE, 'SIN SEDE'); 
                EXEC SPK_GENCONSECUTIVO '01', @SEDE, '@CXC', @CONSECUTIVO_RAW OUTPUT;  

                IF COALESCE(@CONSECUTIVO_RAW, '') = ''
                    INSERT INTO @TBLERRORES(ERROR) VALUES ('No se pudo generar el consecutivo para CXC.');
                ELSE
                    SELECT @CONSECUTIVO_RAW = @SEDE + RIGHT(REPLICATE('0', 8) + LTRIM(RTRIM(@CONSECUTIVO_RAW)), 8);
            END TRY
            BEGIN CATCH
                INSERT INTO @TBLERRORES(ERROR) VALUES ('Error generando consecutivo: ' + ERROR_MESSAGE());
            END CATCH

            IF (SELECT COUNT(*) FROM @TBLERRORES) = 0
            BEGIN
                BEGIN TRY
                    INSERT INTO FCXC(CNSCXC, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT, 
                                    ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA, 
                                    ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA, 
                                    NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE)
                    SELECT @CONSECUTIVO_RAW, DBO.FNK_GETDATE(), @IDTERCERO, NULL, NULL, 0, NULL, NULL, NULL, @USUARIO, '01', 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, @OBSERVACION, NULL, 'CARTERA', 
                           0, 0, 0, NULL, 0, NULL, @SEDE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Activa', @COORFACTURACION, @COORCARTERA, 0, NULL, NULL, NULL, @MSEDE;                    
                END TRY
                BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) VALUES ('Error insertando cabecera FCXC: ' + ERROR_MESSAGE());
                END CATCH

                BEGIN TRY
                    INSERT INTO FCXCD(CNSCXC, N_FACTURA, USUARIO, COMPANIA, VALORFACTURA, DEDUCCIONES, VALORFACTURANETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, MARCAPAGO, 
                                    NT_MARCAP, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, NROCOMPROBANTE, CUENTA, DESCRIPCION, NOREFERENCIAEXT, ENCOBROJUR, IDPLAN, ITFC, CNSITFC, VLRFCES, VLRLEVANTADO, MARCA, USURESP, RESPUESTA, 
                                    RAZONDEVOL)
                    SELECT @CONSECUTIVO_RAW, FTR.N_FACTURA, @USUARIO, '01', FTR.VR_TOTAL, 0, FTR.VR_TOTAL, 0, 0, 0, FTR.VR_TOTAL, FTR.VR_TOTAL, 0, 0, 0, 0, 
                            0, 0, 0, 0, NULL, FTR.CUENTACXC, 'Respuesta Devolución de Facturas', NULL, 0, FTR.IDPLAN, 0, NULL, 0, 0, 0,COALESCE(FCXCR.USURESP,@USUARIO), COALESCE(FCXCR.RESPUESTA,''), 
                            COALESCE(FCXCR.OBSERVACION,'')
                    FROM FCXCR INNER JOIN FTR ON FCXCR.N_FACTURA = FTR.N_FACTURA
                    WHERE FCXCR.CNSCXC = @CNSCXC 
                    AND FCXCR.N_FACTURA = @N_FACTURA;

                    UPDATE FCXCR SET CNSDEVCXC=@CONSECUTIVO_RAW,ENVIA='CXC' WHERE CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA;

                    IF @@ROWCOUNT = 0
                        INSERT INTO @TBLERRORES(ERROR) VALUES ('No se insertaron detalles en FCXCD. Verifique las facturas asociadas al pago.');
                END TRY
                BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) VALUES ('Error insertando detalle FCXCD: ' + ERROR_MESSAGE());
                END CATCH

                IF (SELECT COUNT(*) FROM @TBLERRORES) = 0
                BEGIN
                    UPDATE FTR 
                    SET INDCARTERA = 1, FECHAPASOCXC = DBO.FNK_GETDATE(),
                        IDDEP = DBO.FNK_VALORVARIABLE('IDFDEPCARTERA'), INDASIGENT = 0, INDASIGCXC = 1,
                        CLASE = CASE WHEN COALESCE(FTR.CLASE, '') <> 'C' THEN 'C' ELSE FTR.CLASE END
                    FROM FTR INNER JOIN FCXCD ON FTR.N_FACTURA = FCXCD.N_FACTURA
                    WHERE FCXCD.CNSCXC = @CONSECUTIVO_RAW;

                    EXEC SPK_RELIQUIDACXCQX @CONSECUTIVO_RAW;
                    PRINT 'CXC CREADA EXITOSAMENTE: ' + @CONSECUTIVO_RAW;
                END
            END
        END
    END
    -- ?? RETORNO UNIFICADO PARA FRONTEND
    FIN_PROCEDIMIENTO:
    IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
    BEGIN
        SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
    END
    ELSE
    BEGIN
        SELECT 'OK' AS OK;
    END
    RETURN;
END;

