CREATE OR ALTER PROCEDURE DBO.SPQ_FDIAN_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY           INT 
       ,@PROCESO            VARCHAR(20)    ,@FDIAN    NVARCHAR(MAX)
	    ,@CNSRESOL			VARCHAR(50),@CNSRESOL_ANT			VARCHAR(50)
       ,@DESCRIPCION     VARCHAR(100)
       ,@TIPO     VARCHAR(20)
       ,@TITULO     VARCHAR(500)
       ,@F_RESOLUCION     DATETIME
       ,@FECHAINI     DATETIME
       ,@FECHAVEN     DATETIME
       ,@CNSINICIAL     VARCHAR(20)
       ,@CNSFINAL     VARCHAR(20)
       ,@CNSACTUAL     BIGINT
       ,@IDENTIFICADOR     VARCHAR(20)
       ,@PREFIJO     VARCHAR(10)
       ,@PROCEDENCIA     VARCHAR(20)
       ,@VENCIDA     SMALLINT
       ,@LONGFTR     SMALLINT
       ,@CLAVETECNICA     VARCHAR(200)
       ,@AMBIENTE     INT
       ,@FTRELECTRONICA     BIT
       ,@TIPO_DOCUMENTO     VARCHAR(20)
       ,@TIPO_OPERACION     VARCHAR(20)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy

   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_FDIAN_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE

   IF @METODO = 'GET_DATOS_FDIAN'
	BEGIN
		SELECT 'OK' OK
		
		SELECT TABLA, CAMPO, CODIGO, DESCRIPCION, FECHA1, IDTGEN FROM TGEN WHERE TABLA = 'FDIAN' AND CAMPO = 'CONTACTO'
      UNION
      SELECT TABLA, CAMPO, CODIGO, DESCRIPCION, FECHA1, IDTGEN FROM TGEN WHERE TABLA = 'FDIAN' AND CAMPO = 'SOFTWARE'
      UNION
      SELECT TABLA, CAMPO, CODIGO, DESCRIPCION, FECHA1, IDTGEN FROM TGEN WHERE TABLA = 'FDIAN' AND CAMPO = 'SOFTWARE_NOMINA'
		RETURN
	END

   IF @METODO = 'CRUDFDIAN'
   BEGIN
      PRINT 'CRUDFDIAN'
      SELECT @FDIAN  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@FDIAN ,'$.PROCESO')
      --Leo Campos enviados y los coloco en las variables respectivas
      SELECT @CNSRESOL = JSON_VALUE(@FDIAN , '$.CNSRESOL' )
      SELECT @CNSRESOL_ANT = JSON_VALUE(@FDIAN , '$.CNSRESOL_ANT' )
      SELECT @DESCRIPCION = JSON_VALUE(@FDIAN , '$.DESCRIPCION' )
      SELECT @TIPO = JSON_VALUE(@FDIAN , '$.TIPO' )
      SELECT @TITULO = JSON_VALUE(@FDIAN, '$.TITULO')
      SELECT @F_RESOLUCION = CAST(JSON_VALUE(@FDIAN, '$.F_RESOLUCION') AS DATE)
      SELECT @FECHAINI = CAST(JSON_VALUE(@FDIAN,'$.FECHAINI' ) AS DATE)
      SELECT @FECHAVEN = CAST(JSON_VALUE(@FDIAN, '$.FECHAVEN') AS DATE)
      SELECT @CNSINICIAL = JSON_VALUE(@FDIAN, '$.CNSINICIAL')
      SELECT @CNSFINAL = JSON_VALUE(@FDIAN, '$.CNSFINAL')
      SELECT @CNSACTUAL = JSON_VALUE(@FDIAN, '$.CNSACTUAL')
      SELECT @IDENTIFICADOR = JSON_VALUE(@FDIAN, '$.IDENTIFICADOR')
      SELECT @PREFIJO = JSON_VALUE(@FDIAN, '$.PREFIJO')
      SELECT @PROCEDENCIA = JSON_VALUE(@FDIAN, '$.PROCEDENCIA')
      SELECT @VENCIDA = CAST(JSON_VALUE(@FDIAN, '$.VENCIDA') AS BIT)
      SELECT @LONGFTR = JSON_VALUE(@FDIAN, '$.LONGFTR')
      SELECT @CLAVETECNICA = JSON_VALUE(@FDIAN, '$.CLAVETECNICA')
      SELECT @AMBIENTE = JSON_VALUE(@FDIAN, '$.AMBIENTE')
	  SELECT @FTRELECTRONICA = CAST(JSON_VALUE(@FDIAN, '$.FTRELECTRONICA') AS BIT)
	  SELECT @TIPO_DOCUMENTO = JSON_VALUE(@FDIAN, '$.TIPO_DOCUMENTO')
      SELECT @TIPO_OPERACION = JSON_VALUE(@FDIAN, '$.TIPO_OPERACION')

      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'

         BEGIN TRY
			INSERT INTO @TBLERRORES(ERROR) 
			SELECT 'LA RESOLUCION DIAN YA EXISTE'
			WHERE EXISTS (SELECT 1 FROM FDIAN WHERE CNSRESOL = @CNSRESOL)

			IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
			BEGIN
				INSERT INTO FDIAN (CNSRESOL ,F_RESOLUCION ,CNSINICIAL ,CNSFINAL ,DESCRIPCION ,FECHAVEN ,TIPO ,IDENTIFICADOR ,TITULO ,VENCIDA ,PREFIJO ,
                   FECHAINI ,CLAVETECNICA ,CNSACTUAL ,FTRELECTRONICA ,LONGFTR ,AMBIENTE ,TIPO_OPERACION ,TIPO_DOCUMENTO ,PROCEDENCIA ) 
				SELECT @CNSRESOL ,@F_RESOLUCION ,@CNSINICIAL ,@CNSFINAL ,@DESCRIPCION ,@FECHAVEN ,@TIPO ,@IDENTIFICADOR ,@TITULO ,@VENCIDA ,@PREFIJO ,
                   @FECHAINI ,@CLAVETECNICA ,@CNSACTUAL ,@FTRELECTRONICA ,@LONGFTR ,@AMBIENTE ,@TIPO_OPERACION ,@TIPO_DOCUMENTO ,@PROCEDENCIA
				SELECT @IDENTITY = SCOPE_IDENTITY()
			END
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK ,@IDENTITY CNS 
         RETURN
      END

      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         BEGIN TRY
            UPDATE FDIAN SET
                   CNSRESOL = @CNSRESOL, DESCRIPCION = @DESCRIPCION,TIPO = @TIPO,F_RESOLUCION = @F_RESOLUCION,CNSINICIAL = @CNSINICIAL,CNSFINAL = @CNSFINAL,
					FECHAVEN = @FECHAVEN,IDENTIFICADOR = @IDENTIFICADOR,TITULO = @TITULO,VENCIDA = @VENCIDA,PREFIJO = @PREFIJO,
					FECHAINI = @FECHAINI,CLAVETECNICA = @CLAVETECNICA,CNSACTUAL = @CNSACTUAL,FTRELECTRONICA = @FTRELECTRONICA,LONGFTR = @LONGFTR,
				    AMBIENTE = @AMBIENTE,TIPO_OPERACION = @TIPO_OPERACION,TIPO_DOCUMENTO = @TIPO_DOCUMENTO,PROCEDENCIA = @PROCEDENCIA
            WHERE CNSRESOL = @CNSRESOL_ANT
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END

	  IF UPPER(@PROCESO) = 'ELIMINAR'
		BEGIN
			PRINT 'ELIMINAR'
			BEGIN TRY
				IF COALESCE(@CNSRESOL,'')=''
				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'EL CODIGO DE RESOLUCION DIAN ES OBLIGATORIO'

				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'ESTA RESOLUCION YA FUE USADA EN FACTURACION. NO ES POSIBLE ELIMINAR.'
				WHERE EXISTS (SELECT 1 FROM FTR WHERE CNSRESOL = @CNSRESOL)

				IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
				BEGIN
					DELETE FROM FDIAN WHERE CNSRESOL = @CNSRESOL
				END		
			END TRY

			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH

			IF(SELECT COUNT(*) FROM @TBLERRORES) >0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			SELECT 'OK' OK
			RETURN
		END
      RETURN
   END

   IF @METODO = 'CRUDFTRDIAN'
   BEGIN
      PRINT 'CRUDFTRDIAN'
      SELECT @FDIAN  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@FDIAN ,'$.PROCESO')

      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         BEGIN TRY
            DECLARE @DATOS NVARCHAR(MAX)

            SELECT @DATOS  = DATOS
            FROM OPENJSON (@FDIAN)
            WITH(
               DATOS   NVARCHAR(MAX)     AS JSON
            )

            CREATE TABLE #DatosTGEN (
                 IDTGEN INT,
                 CAMPO NVARCHAR(50),
                 CODIGO NVARCHAR(50),
                 DESCRIPCION NVARCHAR(MAX)
             );

             INSERT INTO #DatosTGEN (IDTGEN, CAMPO, CODIGO, DESCRIPCION)
             SELECT 
                 JSON_VALUE(Value, '$.IDTGEN') AS IDTGEN,
                 JSON_VALUE(Value, '$.CAMPO') AS CAMPO,
                 JSON_VALUE(Value, '$.CODIGO') AS CODIGO,
                 JSON_VALUE(Value, '$.DESCRIPCION') AS DESCRIPCION
             FROM OPENJSON(@DATOS);

             DECLARE @IDTGEN INT, @CODIGO VARCHAR(20), @DESCRIPCION_TGEN VARCHAR(1000);

             DECLARE cursorDatos CURSOR FOR
                 SELECT IDTGEN, CODIGO, DESCRIPCION
                 FROM #DatosTGEN;

             OPEN cursorDatos;

             FETCH NEXT FROM cursorDatos INTO @IDTGEN, @CODIGO, @DESCRIPCION_TGEN;

             WHILE @@FETCH_STATUS = 0
             BEGIN
                 IF @CODIGO = 'FVCERTIFICADO'
                 BEGIN
                     UPDATE TGEN
                     SET FECHA1 = TRY_CAST(@DESCRIPCION_TGEN AS DATETIME)
                     WHERE IDTGEN = @IDTGEN;
                 END
                 ELSE
                 BEGIN
                     UPDATE TGEN
                     SET DESCRIPCION = @DESCRIPCION_TGEN
                     WHERE IDTGEN = @IDTGEN;
                 END

                 FETCH NEXT FROM cursorDatos INTO @IDTGEN, @CODIGO, @DESCRIPCION_TGEN;
             END

             CLOSE cursorDatos;
             DEALLOCATE cursorDatos;

             DROP TABLE #DatosTGEN
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END

      RETURN
   END
END





