CREATE OR ALTER PROCEDURE DBO.SPQ_FCXC_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
DECLARE @CNSENTREGA VARCHAR(20)           ,@PROCESO  VARCHAR(20)           ,@REQSEDE BIT
        ,@DEP_RECIBE VARCHAR(20)          ,@IDSEDEF  VARCHAR(5)            ,@N_FACTURA VARCHAR(20)
        ,@F_INICIAL DATE                  ,@F_FINAL  DATE                  ,@IDTERCERO VARCHAR(20)
        ,@PROCEDENCIA VARCHAR(20)         ,@IDPLAN      VARCHAR(20)
        ,@MSEDE BIT                       ,@CNSCXC VARCHAR(20)             ,@OBSERVACION VARCHAR(2048)
        ,@COORFACTURACION VARCHAR(20)     ,@COORCARTERA VARCHAR(20)        ,@PIDEADICION VARCHAR(20)
        ,@MODALIDAD VARCHAR(20)          ,@ATENCION VARCHAR(20)           ,@MES      VARCHAR(20)
        ,@ANO      VARCHAR(20)           ,@REGIMEN  VARCHAR(20)           ,@VALORCXC  DECIMAL(14,2)
        ,@FECHARAD DATE                  ,@QRECIBE VARCHAR(50)            ,@NRORADICA VARCHAR(30)
        ,@NROGUIA   VARCHAR(20)          ,@CNSRPDX  VARCHAR(20)           ,@VLLETRAS VARCHAR(1024)
        ,@NROLETRAS SMALLINT			,@MEC_FACT VARCHAR(10)			,@TIPOCXC  VARCHAR(20)
		,@CNSFNOT  VARCHAR(20)			,@CLASEANULACION VARCHAR(10)	,@TOTAL INT
		,@INICIO INT					,@FIN INT						,@LIMITE INT
		,@SINAUTSITEDS BIT         ,@FECHARADI DATE           ,@CANTI INT        ,@BAND INT=0        ,@CNSCXCN VARCHAR(20)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),  @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())   
   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
    WHERE USUSU.USUARIO=@USUARIO

   IF @METODO='TRAER_DEF'     
   BEGIN         
      SELECT @OBSERVACION=OBSERVACION FROM USVGS WHERE IDVARIABLE='FCXC_OBSERVACION_DEF'
      SELECT 'OK'OK ,@OBSERVACION AS OBSERVACION
      RETURN
   END   
   IF @METODO='TRAER_TTEC'     
   BEGIN           
      SELECT 'OK'OK 
      SELECT TIPO value,DETALLE label FROM TTEC
      RETURN
   END 
   IF @METODO='CRUD_FCXC'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
         
         SELECT @CNSCXC=CNSCXC,@IDTERCERO=IDTERCERO,@OBSERVACION=OBSERVACION,@MSEDE=CONVERT(INT,REQSEDE),@IDSEDEF=IDSEDEF,@MODALIDAD=MODALIDAD,
                @ATENCION=ATENCION,@MES=CONVERT(INT,MES),@ANO=ANO,@REGIMEN=REGIMEN
         FROM   OPENJSON (@DATOS)
         WITH   (  
         CNSCXC VARCHAR(20)       '$.CNSCXC',
         IDTERCERO VARCHAR(20)    '$.IDTERCERO',
         OBSERVACION VARCHAR(512) '$.OBSERVACION',
         REQSEDE     BIT          '$.REQSEDE',
         IDSEDEF     VARCHAR(6)   '$.IDSEDE',
         MODALIDAD   VARCHAR(20)  '$.MODALIDAD',
         ATENCION   VARCHAR(20)   '$.ATENCION',
         MES         VARCHAR(20)  '$.MES',
         ANO         VARCHAR(20)  '$.ANO',
         REGIMEN     VARCHAR(20)  '$.REGIMEN'
         ) 
       IF COALESCE(@CNSCXC,'')=''
       BEGIN
          IF DBO.FNK_VALORVARIABLE('USUARIOJEFECARTERA')=''
         BEGIN
            SELECT 'KO' KO, 'Debe llenar la variable USUARIOJEFECARTERA con el usuario del jefe de Cartera, Verifique e Intente de nuevo' ERROR
            RETURN
         END
         IF NOT EXISTS(SELECT * FROM USUSU WHERE USUARIO=RTRIM(RTRIM(DBO.FNK_VALORVARIABLE('USUARIOJEFECARTERA'))))
         BEGIN
            SELECT 'KO' KO, 'El dato de la Variable USUARIOJEFECARTERA no es Valido, Valide e Intente de nuevo ' ERROR
            RETURN
         END
         IF DBO.FNK_VALORVARIABLE('USUARIOJEFEFACTURA')=''
         BEGIN
            SELECT 'KO' KO,'Debe llenar la variable USUARIOJEFEFACTURA con el usuario del jefe de Cartera, Verifique e Intente de nuevo' ERROR
            RETURN
         END
         IF NOT EXISTS(SELECT * FROM USUSU WHERE USUARIO=RTRIM(RTRIM(DBO.FNK_VALORVARIABLE('USUARIOJEFEFACTURA'))))
         BEGIN
            SELECT 'KO' KO, 'El dato de la Variable USUARIOJEFEFACTURA no es Valido, Valide e Intente de nuevo ' ERROR
            RETURN
         END
         PRINT 'Creando la CXC'

         SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
         WHERE USUARIO=@USUARIO
         --SELECT @OBSERVACION=LTRIM(RTRIM(OBSERVACION)) FROM USVGS WHERE IDVARIABLE='FCXC_OBSERVACION_DEF'
         SELECT @COORFACTURACION= DBO.FNK_VALORVARIABLE('USUARIOJEFEFACTURA'),@COORCARTERA=DBO.FNK_VALORVARIABLE('USUARIOJEFECARTERA')
         SELECT TOP 1 @IDTERCERO=FTR.IDTERCERO FROM FTR INNER JOIN ENTD ON FTR.N_FACTURA=ENTD.NODOCUMENTO
         WHERE ENTD.CNSENTREGA=@CNSENTREGA
         IF @MSEDE=1 AND COALESCE(@IDSEDEF,'')<>''
         BEGIN
            SELECT @IDSEDE=@IDSEDEF
         END
         IF EXISTS(SELECT * FROM FCXC WHERE IDTERCERO=@IDTERCERO AND CERRADA=0 AND INDRECIBIDO=0 AND IDSEDE=@IDSEDE AND USUARIO=@USUARIO 
                   AND COALESCE(CONTABILIZADA,0) = 0 AND COALESCE(VALORCXC,0) = 0) -- STORRES Valida si no esta contabilizada y valor de la CXC deve ser cero
         BEGIN 
            SELECT 'KO' KO, 'Existe una CXC para este Tercero, Esta Sede y Este usuario, Es necesario Definir la Anterior , Valide e Intente de nuevo ' ERROR
            RETURN
         END
         BEGIN TRY
            PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')  +COALESCE(@COMPANIA,'CIA') 
            SELECT @CNSCXC=''
		      EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@CXC', @CNSCXC OUTPUT  
            PRINT '@CNSCXC='+COALESCE(@CNSCXC,'')   
		      SELECT @CNSCXC = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSCXC))+LTRIM(RTRIM(@CNSCXC)),SPACE(1),0)
		      PRINT '@CNSCXC='+COALESCE(@CNSCXC,'')                    
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            SELECT ERROR AS ERROR FROM  @TBLERRORES 
            RETURN
         END CATCH

         BEGIN TRY
            INSERT INTO FCXC(CNSCXC, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT, 
                              ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA, 
                              ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA, 
                              NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE)
            SELECT @CNSCXC, DBO.FNK_GETDATE(), @IDTERCERO, NULL, NULL, 0, NULL, NULL, NULL, @USUARIO,@COMPANIA, 0, 0, 0, 0, NULL,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,@OBSERVACION, NULL, 'CARTERA', 
            0, 0, 0, NULL, 0, NULL, @IDSEDE, @MODALIDAD, @ATENCION, @MES, @ANO, @REGIMEN, NULL, NULL, NULL, 'Activa',@COORFACTURACION,@COORCARTERA,0, NULL, NULL, NULL, @MSEDE                    
            END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
               SELECT ERROR AS ERROR FROM  @TBLERRORES 
               RETURN
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK,@CNSCXC CNSCXC
         RETURN 
      END
      ELSE
      BEGIN
         PRINT 'VOY A ACTUALIZAR'
         DECLARE @IDTERCEROA VARCHAR(20)
         SELECT @IDTERCEROA=IDTERCERO FROM FCXC WHERE CNSCXC=@CNSCXC
         IF @IDTERCEROA<>@IDTERCERO AND EXISTS(SELECT * FROM FCXCD WHERE CNSCXC=@CNSCXC)
         BEGIN
            SELECT 'KO' KO,'Cuenta de Cobro con Detalle, No se puede Actualizar el Responsable de Pago' ERROR
            RETURN
         END
         IF EXISTS(SELECT * FROM FCXC WHERE CNSCXC=@CNSCXC AND INDRECIBIDO=1)
         BEGIN
            SELECT 'KO' KO,'Cuenta de Cobro Radicada, No se pueden Realizar Cambios' ERROR
            RETURN
         END
      END   
      PRINT 'Pase las Validaciones'
      BEGIN TRY           
          UPDATE FCXC SET IDTERCERO=@IDTERCERO,OBSERVACION=@OBSERVACION,MODALIDAD=@MODALIDAD,ATENCION=@ATENCION,
                          ANO=@ANO,MES=@MES,REGIMEN=@REGIMEN
          WHERE CNSCXC=@CNSCXC
      END TRY
      BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,@CNSCXC CNSCXC
      RETURN 
   END
   IF @METODO='MARCAR_FACT'
   BEGIN 
      SELECT @N_FACTURA=N_FACTURA,@TIPOCXC=TIPOCXC,@CNSFNOT=CNSFNOT
      FROM   OPENJSON (@PARAMETROS)
      WITH (
         N_FACTURA VARCHAR(20)  '$.N_FACTURA',
         CNSFNOT VARCHAR(20)  '$.CNSFNOT',
         TIPOCXC VARCHAR(20)  '$.TIPOCXC'
      ) 
      IF COALESCE(@N_FACTURA,'')<>''
      BEGIN
         SELECT @SYS_COMPUTERNAME=COALESCE(SYS_COMPUTERNAME,HOST_NAME()) FROM USUSU WHERE USUARIO=@USUARIO
         BEGIN TRY
			IF COALESCE(@TIPOCXC,'')='FNOT' AND COALESCE(@CNSFNOT,'')<>''
			BEGIN
				UPDATE FNOT SET MARCA=CASE COALESCE(MARCA,0) WHEN 1 THEN 0 ELSE 1 END,USUMARCA=CASE COALESCE(MARCA,0) WHEN 1 THEN '' ELSE @USUARIO END  WHERE CNSFNOT = @CNSFNOT AND N_FACTURA=@N_FACTURA 
			END
			ELSE
			BEGIN
				UPDATE FTR SET MARCA=CASE COALESCE(MARCA,0) WHEN 1 THEN 0 ELSE 1 END,EQUIMARCA=CASE COALESCE(MARCA,0) WHEN 1 THEN '' ELSE @SYS_COMPUTERNAME END  WHERE N_FACTURA=@N_FACTURA        
			END

         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Documento No Encontrado' 
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
    END  

   IF @METODO='ASIGNAR_FACT'
   BEGIN 
      SELECT @CNSCXC=CNSCXC
      FROM   OPENJSON (@PARAMETROS)
      WITH (
         CNSCXC VARCHAR(20) '$.CNSCXC'
      ) 
      PRINT 'Cuenta de Cobro='+COALESCE(@CNSCXC,'SIN CXC')
      IF COALESCE(@CNSCXC,'')<>''
      BEGIN
         IF EXISTS(SELECT * FROM FCXC WHERE CNSCXC=@CNSCXC AND CERRADA=0 AND INDRECIBIDO= 0) -- STORRES SE QUITA VALIDACIONES DE MAS
         BEGIN
            PRINT 'VOY A INSERTAR'
            SELECT @SYS_COMPUTERNAME=COALESCE(SYS_COMPUTERNAME,HOST_NAME()),@COMPANIA=COALESCE(COMPANIA,'01') FROM USUSU WHERE USUARIO=@USUARIO
            BEGIN TRY           
               INSERT INTO FCXCD(CNSCXC, N_FACTURA, USUARIO, COMPANIA, VALORFACTURA, DEDUCCIONES, VALORFACTURANETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, 
                                 SALDO, SALDONETO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, MARCAPAGO,  NT_MARCAP, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, 
                                 NROCOMPROBANTE, CUENTA, DESCRIPCION, NOREFERENCIAEXT, ENCOBROJUR, IDPLAN, ITFC, CNSITFC, VLRFCES, VLRLEVANTADO, 
                                 MARCA, USURESP, RESPUESTA,  RAZONDEVOL)
               SELECT @CNSCXC, N_FACTURA, @USUARIO, @COMPANIA, VR_TOTAL, 0, VR_TOTAL, 0, 0, 0, VR_TOTAL, VR_TOTAL,
                        0, 0, 0, 0,  NULL, 0, 0, 0, NULL, CUENTACXC,'Traida desde Quasar', null, 0, IDPLAN, 0, NULL, 0, 0, 0, NULL, NULL,  NULL
               FROM FTR
               WHERE MARCA=1
               AND COALESCE(EQUIMARCA,'')=@SYS_COMPUTERNAME
               AND FTR.ESTADO='P' 
               AND COALESCE(CLASEANULACION,'')<>'NC' 
               AND COALESCE(VR_TOTAL,0)>0 
               AND COALESCE(CONTABILIZADA,0)<>0
               AND NOT EXISTS(SELECT * FROM FCXCD WHERE FCXCD.N_FACTURA=FTR.N_FACTURA)
               AND COALESCE(INDCARTERA,0)=1 
               AND INDCXC=0 
               AND INDASIGCXC=0  
               AND IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPCARTERA')  
               
               UPDATE FTR SET MARCA=0, EQUIMARCA=NULL,INDASIGCXC=1,INDCXC=1
               FROM FTR INNER JOIN FCXCD ON FTR.N_FACTURA=FCXCD.N_FACTURA
               WHERE FTR.MARCA=1 AND EQUIMARCA=@SYS_COMPUTERNAME
               AND FCXCD.CNSCXC=@CNSCXC

               EXEC SPK_RELIQUIDACXCQX @CNSCXC 
         
            END TRY
            BEGIN CATCH
                  INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Facturas no Agregadas a la Cuenta de Cobro, Valide e intente de nuevo'
         END
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Cuenta de Cobro Cerrada  o Presenta inconsistencias en su Creacion, Valide e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      PRINT 'ACTUALIZO VALORES'
      EXEC SPK_RELIQUIDACXCQX @CNSCXC
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='MARCAR_TODAS'
   BEGIN 
      SELECT @DATOS=DATOS
      FROM   OPENJSON (@PARAMETROS)
      WITH (
         DATOS NVARCHAR(MAX) AS JSON
      ) 
      SELECT @F_INICIAL=F_INICIAL,@F_FINAL=DATEADD(DAY,1,F_FINAL),@IDTERCERO=IDTERCERO, @PROCEDENCIA=PROCEDENCIA,
      @IDSEDEF=IDSEDEF,@IDPLAN=IDPLAN,@CNSENTREGA=CNSENTREGA,@MEC_FACT=MEC_FACT
      FROM   OPENJSON (@DATOS)
      WITH   (
      F_INICIAL DATE         '$.F_INICIAL',
      F_FINAL   DATE         '$.F_FINAL',
      IDTERCERO VARCHAR(20)  '$.IDTERCERO',
      PROCEDENCIA VARCHAR(20) '$.PROCEDENCIA',
      IDSEDEF     VARCHAR(5)  '$.IDSEDE',
      IDPLAN      VARCHAR(6)  '$.IDPLAN',
      CNSENTREGA  VARCHAR(20)  '$.CNSENTREGA',
      MEC_FACT  VARCHAR(10)  '$.MEC_FACT'
      )
      SELECT @SYS_COMPUTERNAME=COALESCE(SYS_COMPUTERNAME,HOST_NAME()) FROM USUSU WHERE USUARIO=@USUARIO
      UPDATE FTR SET MARCA=1, EQUIMARCA=@SYS_COMPUTERNAME 
      WHERE MARCA=0 
      AND COALESCE(EQUIMARCA,'')=''
      AND F_FACTURA>=@F_INICIAL
      AND F_FACTURA<@F_FINAL
      AND IDTERCERO=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE IDTERCERO END
      AND IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE IDPLAN END
      AND IDSEDE=CASE WHEN COALESCE(@IDSEDEF,'Todas')<>'Todas' THEN @IDSEDEF ELSE IDSEDE END
      AND PROCEDENCIA=CASE WHEN COALESCE(@PROCEDENCIA,'Todas')<>'Todas' THEN @PROCEDENCIA ELSE PROCEDENCIA END
      AND (COALESCE(@MEC_FACT, 'Todos') = 'Todos' OR MEC_FACT = @MEC_FACT)
      AND FTR.ESTADO='P' 
      AND COALESCE(CLASEANULACION,'')<>'NC' 
      AND COALESCE(VR_TOTAL,0)>0 
      AND COALESCE(CONTABILIZADA,0)<>0
      AND NOT EXISTS(SELECT * FROM FCXCD WHERE FCXCD.N_FACTURA=FTR.N_FACTURA)
      AND COALESCE(INDCARTERA,0)=1 
      AND INDCXC=0 
      AND INDASIGCXC=0  
      AND IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPCARTERA') 
      AND 1=CASE WHEN COALESCE(@CNSENTREGA,'')<>'' THEN CASE WHEN  EXISTS(SELECT * FROM ENTD WHERE  FTR.N_FACTURA=ENTD.NODOCUMENTO AND PROCESO='FACTURAS' AND COALESCE(ENDEVO,0)<>1  AND ENTD.CNSENTREGA=@CNSENTREGA)  THEN 1 ELSE 0 END ELSE 1 END

      SELECT 'OK' OK
      RETURN 
   END

   IF @METODO='MARCAR_TODAS_REMESAS'
   BEGIN 
      SELECT @DATOS=DATOS, @SINAUTSITEDS=SINAUTSITEDS
      FROM   OPENJSON (@PARAMETROS)
      WITH (
         DATOS NVARCHAR(MAX) AS JSON, SINAUTSITEDS BIT
      ) 
      SELECT @F_INICIAL=F_INICIAL,@F_FINAL=DATEADD(DAY,1,F_FINAL),@IDTERCERO=IDTERCERO, @PROCEDENCIA=PROCEDENCIA,
      @IDSEDEF=IDSEDEF,@IDPLAN=IDPLAN,@CNSENTREGA=CNSENTREGA,@MEC_FACT=MEC_FACT
      FROM   OPENJSON (@DATOS)
      WITH   (
      F_INICIAL DATE         '$.F_INICIAL',
      F_FINAL   DATE         '$.F_FINAL',
      IDTERCERO VARCHAR(20)  '$.IDTERCERO',
      PROCEDENCIA VARCHAR(20) '$.PROCEDENCIA',
      IDSEDEF     VARCHAR(5)  '$.IDSEDE',
      IDPLAN      VARCHAR(6)  '$.IDPLAN',
      CNSENTREGA  VARCHAR(20)  '$.CNSENTREGA',
      MEC_FACT  VARCHAR(10)  '$.MEC_FACT'
      )
      SELECT @SYS_COMPUTERNAME=COALESCE(SYS_COMPUTERNAME,HOST_NAME()) FROM USUSU WHERE USUARIO=@USUARIO
      UPDATE FTR SET MARCA=1, EQUIMARCA=@SYS_COMPUTERNAME 
      WHERE MARCA=0 
      AND COALESCE(EQUIMARCA,'')=''
      AND F_FACTURA>=@F_INICIAL
      AND F_FACTURA<@F_FINAL
      AND IDTERCERO=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE IDTERCERO END
      AND IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE IDPLAN END
      AND IDSEDE=CASE WHEN COALESCE(@IDSEDEF,'Todas')<>'Todas' THEN @IDSEDEF ELSE IDSEDE END
      AND PROCEDENCIA=CASE WHEN COALESCE(@PROCEDENCIA,'Todas')<>'Todas' THEN @PROCEDENCIA ELSE PROCEDENCIA END
      AND (COALESCE(@MEC_FACT, 'Todos') = 'Todos' OR MEC_FACT = @MEC_FACT)
      AND FTR.ESTADO='P' 
      AND COALESCE(CLASEANULACION,'')<>'NC' 
      AND COALESCE(VR_TOTAL,0)>0 
      AND COALESCE(CONTABILIZADA,0)<>0
      AND NOT EXISTS(SELECT * FROM FCXCD WHERE FCXCD.N_FACTURA=FTR.N_FACTURA)
      AND COALESCE(INDCARTERA,0)=1 
      AND INDCXC=0 
      AND INDASIGCXC=0  
      AND IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPCARTERA') 
      AND 1=CASE WHEN COALESCE(@CNSENTREGA,'')<>'' THEN CASE WHEN  EXISTS(SELECT * FROM ENTD WHERE  FTR.N_FACTURA=ENTD.NODOCUMENTO AND PROCESO='FACTURAS' AND COALESCE(ENDEVO,0)<>1  AND ENTD.CNSENTREGA=@CNSENTREGA)  THEN 1 ELSE 0 END ELSE 1 END
	  AND (
		COALESCE(@SINAUTSITEDS,0) = 0 OR EXISTS (SELECT 1 FROM MAD WHERE COALESCE(MSITEDS,0) =1 AND (MAD.N_FACTURA = FTR.N_FACTURA OR MAD.N_FACTURA_PPS = FTR.N_FACTURA))
	  )

      SELECT 'OK' OK
      RETURN 
   END

   IF @METODO='MARCAR_TODAS_FNOT'
   BEGIN 
      SELECT @DATOS=DATOS
      FROM   OPENJSON (@PARAMETROS)
      WITH (
         DATOS NVARCHAR(MAX) AS JSON
      ) 
      SELECT @F_INICIAL=F_INICIAL,@F_FINAL=DATEADD(DAY,1,F_FINAL),@IDTERCERO=IDTERCERO, @PROCEDENCIA=PROCEDENCIA,
      @IDSEDEF=IDSEDEF,@IDPLAN=IDPLAN,@CNSENTREGA=CNSENTREGA,@MEC_FACT=MEC_FACT,@CLASEANULACION=CLASEANULACION
      FROM   OPENJSON (@DATOS)
      WITH   (
      F_INICIAL DATE         '$.F_INICIAL',
      F_FINAL   DATE         '$.F_FINAL',
      IDTERCERO VARCHAR(20)  '$.IDTERCERO',
      PROCEDENCIA VARCHAR(20) '$.PROCEDENCIA',
      IDSEDEF     VARCHAR(5)  '$.IDSEDE',
      IDPLAN      VARCHAR(6)  '$.IDPLAN',
      CNSENTREGA  VARCHAR(20)  '$.CNSENTREGA',
      MEC_FACT  VARCHAR(10)  '$.MEC_FACT',
      CLASEANULACION  VARCHAR(10)  '$.CLASEANULACION'
      )
      SELECT @SYS_COMPUTERNAME=COALESCE(SYS_COMPUTERNAME,HOST_NAME()) FROM USUSU WHERE USUARIO=@USUARIO
      UPDATE FNOT SET MARCA=1, USUMARCA=@USUARIO 
      WHERE MARCA=0 
      AND COALESCE(USUMARCA,'')=''
      AND F_NOTA>=@F_INICIAL
      AND F_NOTA<@F_FINAL
      AND IDTERCERO=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE IDTERCERO END
      --AND PROCEDENCIA=CASE WHEN COALESCE(@PROCEDENCIA,'Todas')<>'Todas' THEN @PROCEDENCIA ELSE PROCEDENCIA END
      --AND (COALESCE(@MEC_FACT, 'Todos') = 'Todos' OR MEC_FACT = @MEC_FACT)
      --AND FTR.ESTADO='P'
      AND COALESCE(VR_TOTAL,0)>0
	  AND NOT EXISTS(SELECT * FROM FCXCD WHERE FCXCD.N_FACTURA=FNOT.N_FACTURA)

      SELECT 'OK' OK
      RETURN 
   END
   IF @METODO='LIMPIAR_FACT'
   BEGIN 
      
      SELECT @SYS_COMPUTERNAME=COALESCE(SYS_COMPUTERNAME,HOST_NAME()) FROM USUSU WHERE USUARIO=@USUARIO

      UPDATE FTR SET MARCA=0, EQUIMARCA=NULL WHERE MARCA=1 AND EQUIMARCA=@SYS_COMPUTERNAME 
      AND FTR.ESTADO='P' 
      AND COALESCE(CLASEANULACION,'')<>'NC' 
      AND COALESCE(VR_TOTAL,0)>0 
      AND COALESCE(CONTABILIZADA,0)<>0
      AND NOT EXISTS(SELECT * FROM FCXCD WHERE FCXCD.N_FACTURA=FTR.N_FACTURA)
      AND COALESCE(INDCARTERA,0)=1 
      AND INDCXC=0 
      AND INDASIGCXC=0  
      AND IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPCARTERA') 

      SELECT 'OK' OK, COALESCE(CONVERT(VARCHAR,MIN(F_FACTURA),103),CONVERT(VARCHAR,GETDATE(),103)) F_FACTURA FROM FTR 
      WHERE FTR.ESTADO='P' 
      AND COALESCE(CLASEANULACION,'')<>'NC' 
      AND COALESCE(VR_TOTAL,0)>0 
      AND COALESCE(CONTABILIZADA,0)<>0
      AND NOT EXISTS(SELECT * FROM FCXCD WHERE FCXCD.N_FACTURA=FTR.N_FACTURA)
      AND COALESCE(INDCARTERA,0)=1 
      AND INDCXC=0 
      AND INDASIGCXC=0  
      AND IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPCARTERA') 
      RETURN 
   END 
   
   IF @METODO='LIMPIAR_FACT_FNOT'
   BEGIN 
      
      UPDATE FNOT SET MARCA=0, USUMARCA=NULL WHERE MARCA=1 AND USUMARCA=@USUARIO  

      SELECT 'OK' OK
      RETURN 
   END 
   IF @METODO='QUITAFACT_FCXC'     
   BEGIN         
      SELECT @CNSCXC=CNSCXC,@N_FACTURA=N_FACTURA,@OBSERVACION=MOTIVO      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         CNSCXC VARCHAR(20)     '$.CNSCXC',
         N_FACTURA VARCHAR(20) '$.N_FACTURA',
         MOTIVO  VARCHAR(512)  '$.MOTIVO'
            )           
      
      IF EXISTS(SELECT * FROM FCXC WHERE CNSCXC=@CNSCXC AND (CERRADA=1 OR INDRECIBIDO=1))
      BEGIN
         SELECT 'KO' KO,'La Cuenta de Cobro se Encuentra Cerrada o ya Fue Radicada, No se Permiten Hacer Cambios' ERROR
         RETURN
      END
      IF EXISTS(SELECT * FROM FCXCD WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA)
      BEGIN
         BEGIN TRY           
            INSERT INTO FCXCR(CNSCXC, N_FACTURA, COMPANIA, VALORFACTURA, OBSERVACION, USUARIO, FECHA, ITFC, CNSITFC, CONTABILIZADA, NROCOMPROBANTE,
                              USURESP, RESPUESTA, ESTADO, PROCESO, MOTIVO1, MOTIVO2, COD_RESPUESTA,  COD_REP1, COD_REP2)
            SELECT @CNSCXC, @N_FACTURA,'01', VALORFACTURA, @OBSERVACION, @USUARIO, DBO.FNK_GETDATE(), 0, NULL, 0, NULL, NULL,
                   NULL, NULL, 'Retirada', NULL, NULL,  NULL,  NULL, NULL
            FROM FCXCD WHERE CNSCXC=@CNSCXC
            AND FCXCD.N_FACTURA=@N_FACTURA

            UPDATE FTR SET INDCXC=0,INDASIGCXC=0  WHERE N_FACTURA=@N_FACTURA  

            DELETE FCXCD WHERE CNSCXC=@CNSCXC AND FCXCD.N_FACTURA=@N_FACTURA                               
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         EXEC SPK_RELIQUIDACXCQX @CNSCXC
         SELECT 'OK' OK
         RETURN 
      END
      ELSE
      BEGIN
         SELECT 'KO' KO,'No Fue encontrada la Factura en la Cuenta de Cobro, Verifique e intente de nuevo' Error
         RETURN         
      END
   END 
   IF @METODO='CIERRA_FCXC'     
   BEGIN         
      SELECT @CNSCXC=CNSCXC      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         CNSCXC VARCHAR(20)  '$.CNSCXC'
            )   
      IF NOT EXISTS(SELECT * FROM FCXCD WHERE CNSCXC=@CNSCXC)
      BEGIN
         SELECT 'KO' KO,'Cuenta de Cobro Sin detalles, No se Puede Continuar' ERROR
         RETURN
      END
      IF EXISTS(SELECT * FROM FCXC WHERE CNSCXC=@CNSCXC AND CERRADA=0 AND INDRECIBIDO=0)
      BEGIN
         BEGIN TRY           
            UPDATE FCXC SET CERRADA=1,USUCIERRA=@USUARIO WHERE CNSCXC=@CNSCXC                    
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Cuenta de Cobro ya Cerrada o Esta Radicada No se Permiten Cambios'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END      
   IF @METODO='ABRIR_FCXC'     
   BEGIN         
      SELECT  @CNSCXC=CNSCXC      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         CNSCXC VARCHAR(20)  '$.CNSCXC'
            )           
      IF EXISTS(SELECT * FROM FCXC WHERE CNSCXC=@CNSCXC AND CERRADA=1 AND INDRECIBIDO=0)
      BEGIN
         BEGIN TRY           
            UPDATE FCXC SET CERRADA=0,USUCIERRA=NULL WHERE CNSCXC=@CNSCXC                    
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
          INSERT INTO @TBLERRORES(ERROR) SELECT 'Cuenta de Cobro ya Abierta o Esta Radicada No se Permiten Cambios'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END 
   IF @METODO='RADICA_FCXC'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
      
      SELECT @CNSCXC=CNSCXC,@FECHARAD=CONVERT(DATE,FECHARAD),@QRECIBE=QRECIBE,@NRORADICA=NRORADICA,@NROGUIA=NROGUIA,@CNSRPDX=CNSRPDX
      FROM   OPENJSON (@DATOS)
      WITH   (
            CNSCXC VARCHAR(20)  '$.CNSCXC',
            CNSRPDX  VARCHAR(20)   '$.CNSRPDX',
            FECHARAD DATE        '$.FECHARAD',
            QRECIBE VARCHAR(50)  '$.QRECIBE',
            NRORADICA VARCHAR(30) '$.NRORADICA',
            NROGUIA   VARCHAR(20) '$.NROGUIA'
         ) 

       IF EXISTS(SELECT * FROM FCXC WHERE CNSCXC=@CNSCXC AND INDRECIBIDO=0)
       BEGIN
          IF @FECHARAD>CONVERT(DATE,DBO.FNK_GETDATE())
          BEGIN
              INSERT INTO @TBLERRORES(ERROR) SELECT 'Fecha de Radicación Mayor a la Fecha Actual'
          END
          IF @FECHARAD<(DBO.FNK_GETDATE()-30) AND DBO.FNK_VALORVARIABLE ('RAD_MAS2MESES') = 'SI'
          BEGIN
              INSERT INTO @TBLERRORES(ERROR) SELECT 'Fecha de Radicación Menor a Dos periodos Contables'
          END
          IF NOT EXISTS(SELECT * FROM PRI WHERE CONVERT(DATE,FECHA_INI)<=@FECHARAD AND CONVERT(DATE,FECHA_FIN)>=@FECHARAD  AND CERRADO=0 )
          BEGIN
              INSERT INTO @TBLERRORES(ERROR) SELECT 'Periodo Contable  Cerrado, Radicación no Permitida'
          END
          IF NOT EXISTS(SELECT * FROM PRI WHERE CONVERT(DATE,FECHA_INI)<=@FECHARAD AND CONVERT(DATE,FECHA_FIN)>=@FECHARAD  AND CERRADO_CARTERA=0 )
          BEGIN
              INSERT INTO @TBLERRORES(ERROR) SELECT 'Cartera Cerrada, Radicación no Permitida'
          END
          IF EXISTS(SELECT * FROM FNOT INNER JOIN FCXCD ON FNOT.N_FACTURA=FCXCD.N_FACTURA WHERE FCXCD.CNSCXC=@CNSCXC AND FNOT.ESTADO<>'A' AND FNOT.CERRADA=0)
          BEGIN
              INSERT INTO @TBLERRORES(ERROR) SELECT 'Una o Varias Facturas De Esta CXC Tienen Notas Pendientes Por Aplicar, Debe Aplicarlas Primero'
          END
          IF EXISTS(SELECT * FROM FTR INNER JOIN FCXCD ON FTR.N_FACTURA=FCXCD.N_FACTURA WHERE  FCXCD.CNSCXC=@CNSCXC AND CONVERT(DATE,FTR.F_FACTURA)>@FECHARAD)
          BEGIN
             INSERT INTO @TBLERRORES(ERROR) SELECT 'La fecha de radicación es menor a la ultima fecha de las facturas relacionadas'
          END        
          IF EXISTS (SELECT 1 FROM FCXCD INNER JOIN FTR ON FCXCD.N_FACTURA = FTR.N_FACTURA  WHERE FCXCD.CNSCXC = @CNSCXC AND NOT (FTR.ESTADO = 'P' AND ISNULL(FTR.TIPOANULACION,'') <> 'NC'))
          BEGIN
              INSERT INTO @TBLERRORES(ERROR)
              SELECT 'Todas las facturas de la cuenta de cobro deben estar en estado P y no tener Nota Crédito.'
          END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         IF EXISTS(SELECT  * FROM RPDX WHERE CNS=@CNSRPDX)
         BEGIN
            DECLARE RPDXFRAD_CURSOR CURSOR FOR 
            SELECT FECHA1,COUNT(*) FROM RPDX
            WHERE  CNS=@CNSRPDX
            GROUP BY FECHA1
            ORDER BY 2 DESC
            OPEN RPDXFRAD_CURSOR    
            FETCH NEXT FROM RPDXFRAD_CURSOR    
            INTO @FECHARADI,@CANTI
            WHILE @@FETCH_STATUS = 0    
            BEGIN 
               IF @BAND=0
               BEGIN
                  UPDATE FCXCD SET CNSCXC=@CNSCXCN,NOREFERENCIAEXT=ID2
                  FROM FCXCD INNER JOIN RPDX ON FCXCD.CNSCXC=RPDX.ID3 AND FCXCD.N_FACTURA=RPDX.ID1
                  WHERE CNSCXC=@CNSCXC
                  AND RPDX.CNS=@CNSRPDX
                  AND RPDX.FECHA1=@FECHARADI

                  FETCH NEXT FROM RPDXFRAD_CURSOR    
                  INTO @FECHARADI,@CANTI
                  SET @BAND=1
                  CONTINUE
               END
               SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
               FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
               WHERE USUARIO=@USUARIO

			      SET @CNSCXCN = NULL;
			      EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CXC', @CNSCXCN OUTPUT;
			      PRINT '@CNSCXC >'  + COALESCE(@CNSCXCN,' SIN @CNSCXC')
			      SET @CNSCXCN = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSCXCN)) + LTRIM(RTRIM(@CNSCXCN)), SPACE(1), '0');
			      PRINT '@CNSCXC >'  + COALESCE(@CNSCXCN,' SIN @CNSCXC')

				   INSERT INTO FCXC(CNSCXC, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT, 
								     ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA, 
								     ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA, 
								     NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE,TIPOCXC)
				   SELECT @CNSCXCN, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT, 
								     ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA, 
								     ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA, 
								     NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE,TIPOCXC
               FROM FCXC WHERE CNSCXC=@CNSCXC

               UPDATE FCXCD SET CNSCXC=@CNSCXCN,NOREFERENCIAEXT=ID2
               FROM FCXCD INNER JOIN RPDX ON FCXCD.CNSCXC=RPDX.ID3 AND FCXCD.N_FACTURA=RPDX.ID1
               WHERE CNSCXC=@CNSCXC
               AND RPDX.CNS=@CNSRPDX
               AND RPDX.FECHA1=@FECHARADI

               IF DBO.FNK_VALORVARIABLE('CONTABCXC')='SI'
               BEGIN
                  BEGIN TRY           
                       EXEC SPK_CONTAB_RADICACXC @CNSCXCN,@COMPANIA,@IDSEDE,@USUARIO,@SYS_COMPUTERNAME,''
                  END TRY
                  BEGIN CATCH
                        INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
                  END CATCH   
               END


               FETCH NEXT FROM RPDXFRAD_CURSOR    
               INTO  @FECHARADI,@CANTI
            END
            CLOSE RPDXFRAD_CURSOR
            DEALLOCATE RPDXFRAD_CURSOR
         END
         SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
         FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
         WHERE USUARIO=@USUARIO
         SELECT @MSEDE=MSEDE,@IDSEDEF=IDSEDE FROM FCXC WHERE CNSCXC=@CNSCXC
         IF @MSEDE=1 AND COALESCE(@IDSEDEF,'')<>''
         BEGIN
            SELECT @IDSEDE=@IDSEDEF
         END
         BEGIN TRY
            PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')  +COALESCE(@COMPANIA,'CIA') 
            SELECT @CNSRPDX=''
		      EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSRPDX OUTPUT   
		      SELECT @CNSRPDX = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
		      PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'')                               
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         BEGIN TRY           
            EXEC SPK_ENTREGA_CXC @CNSCXC,@QRECIBE,@FECHARAD,@NRORADICA,@CNSRPDX,@IDSEDE,@NROGUIA
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         IF DBO.FNK_VALORVARIABLE('CONTABCXC')='SI'
         BEGIN
            BEGIN TRY           
                 EXEC SPK_CONTAB_RADICACXC @CNSCXC,@COMPANIA,@IDSEDE,@USUARIO,@SYS_COMPUTERNAME,''
            END TRY
            BEGIN CATCH
                  INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH   
         END
       END
       ELSE
       BEGIN
          INSERT INTO @TBLERRORES(ERROR) SELECT 'Cuenta de Cobro ya Radicada o Presenta Inconsistencias'  
       END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END 
   IF @METODO = 'PROCESAR_RADICACION_MULTI_FECHA'     
   BEGIN         
      -- ==========================================
      -- 0. INICIALIZACIÓN Y LIMPIEZA
      -- ==========================================
      SET @CNSCXC     = NULL;
      SET @CNSRPDX    = NULL;
      SET @FECHARAD   = NULL;
      SET @QRECIBE    = NULL;
      SET @NRORADICA  = NULL;
      SET @NROGUIA    = NULL;
      SET @BAND       = 0; 
   
      DELETE FROM @TBLERRORES WHERE 1=1;

      -- ==========================================
      -- 1. LECTURA DE PARÁMETROS
      -- ==========================================
      SELECT 
             @CNSCXC     = CNSCXC,
             @CNSRPDX    = CNSRPDX,
             @FECHARAD   = CONVERT(DATE, COALESCE(FECHARAD, GETDATE())),
             @QRECIBE    = QRECIBE,
             @NRORADICA  = NRORADICA,
             @NROGUIA    = NROGUIA
      FROM OPENJSON(@PARAMETROS)
      WITH (
           CNSCXC    VARCHAR(20) '$.CNSCXC',
           CNSRPDX   VARCHAR(20) '$.CNSRPDX',
           FECHARAD  VARCHAR(20) '$.FECHARAD',
           QRECIBE   VARCHAR(50) '$.QRECIBE',
           NRORADICA VARCHAR(30) '$.NRORADICA',
           NROGUIA   VARCHAR(20) '$.NROGUIA'
      );

      IF @CNSCXC IS NULL OR @CNSRPDX IS NULL
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) VALUES ('Parámetros JSON incompletos.');
         SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
         RETURN;
      END

      -- ==========================================
      -- 2. VALIDACIONES GLOBALES PREVIAS
      -- ==========================================
      IF EXISTS(SELECT 1 FROM FCXC WHERE CNSCXC = @CNSCXC AND INDRECIBIDO = 0)
      BEGIN
         IF @FECHARAD > CONVERT(DATE, DBO.FNK_GETDATE())
            INSERT INTO @TBLERRORES(ERROR) VALUES ('Fecha de Radicación Mayor a la Fecha Actual');
      
         IF NOT EXISTS(SELECT 1 FROM PRI WHERE CONVERT(DATE, FECHA_INI) <= @FECHARAD AND CONVERT(DATE, FECHA_FIN) >= @FECHARAD AND CERRADO = 0)
            INSERT INTO @TBLERRORES(ERROR) VALUES ('Periodo Contable Cerrado');

         -- Validaciones adicionales (Notas, Cartera, etc.)
         IF EXISTS(SELECT 1 FROM FNOT INNER JOIN FCXCD ON FNOT.N_FACTURA = FCXCD.N_FACTURA WHERE FCXCD.CNSCXC = @CNSCXC AND FNOT.ESTADO <> 'A' AND FNOT.CERRADA = 0)
            INSERT INTO @TBLERRORES(ERROR) VALUES ('Facturas con Notas Pendientes por Aplicar');

         IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
         BEGIN
            SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
            RETURN;
         END

         IF @IDSEDE IS NULL
         BEGIN
            INSERT INTO @TBLERRORES(ERROR) VALUES ('No se encontró Sede para el usuario.');
            SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
            RETURN;
         END

         -- ==========================================
         -- FASE 1: REORGANIZACIÓN DE DATOS (MOVIMIENTO DE FACTURAS)
         -- Objetivo: Dejar las tablas FCXC y FCXCD listas ANTES de radicar.
         -- ==========================================
      
         DECLARE @FECHA_ITERACION DATE;
         DECLARE @CANTIDAD_ITERACION INT;
         DECLARE @CNSCXCN_NUEVO VARCHAR(50);
      
         -- Tabla temporal para guardar la lista de CXCs a procesar al final
         -- Estructura: Consecutivo, FechaRadicacion
         DECLARE @TMP_CXCS_A_RADICAR TABLE (
             CNSCXC_PROCESAR VARCHAR(50),
             FECHA_RADICACION DATE
         );

         -- Cursor ordenado: Primero la mayoritaria (para no generar consecutivo nuevo para ella)
         DECLARE CURSOR_FECHAS_RADICACION CURSOR LOCAL FAST_FORWARD FOR 
         SELECT FECHA1, COUNT(*) as CANTIDAD
         FROM RPDX
         WHERE CNS = @CNSRPDX
         GROUP BY FECHA1
         ORDER BY CANTIDAD DESC, FECHA1 ASC; 

         OPEN CURSOR_FECHAS_RADICACION;
         FETCH NEXT FROM CURSOR_FECHAS_RADICACION INTO @FECHA_ITERACION, @CANTIDAD_ITERACION;

         WHILE @@FETCH_STATUS = 0
         BEGIN
            PRINT 'FASE 1 - Procesando Fecha: ' + CONVERT(VARCHAR, @FECHA_ITERACION) + ' (Cantidad: ' + CAST(@CANTIDAD_ITERACION AS VARCHAR) + ')';
         
            IF @BAND = 0
            BEGIN
               -- === CASO MAYORITARIO ===
               PRINT '>>> Fecha MAYORITARIA. Se conserva el consecutivo original: ' + @CNSCXC;
            
               -- Solo actualizamos referencia externa si es necesario, pero NO movemos CNSCXC
               UPDATE FCXCD 
               SET NOREFERENCIAEXT = ID2
               FROM FCXCD 
               INNER JOIN RPDX ON FCXCD.CNSCXC = RPDX.ID3 AND FCXCD.N_FACTURA = RPDX.ID1
               WHERE FCXCD.CNSCXC = @CNSCXC 
                 AND RPDX.CNS = @CNSRPDX
                 AND RPDX.FECHA1 = @FECHA_ITERACION;

               -- Guardamos para radicar después
               INSERT INTO @TMP_CXCS_A_RADICAR (CNSCXC_PROCESAR, FECHA_RADICACION)
               VALUES (@CNSCXC, @FECHA_ITERACION);

               SET @BAND = 1;
               SET @CNSCXCN_NUEVO = @CNSCXC; -- Para referencia
            END
            ELSE
            BEGIN
               -- === CASO SECUNDARIO (Minoritario) ===
               PRINT '>>> Fecha SECUNDARIA. Creando nueva CXC y moviendo facturas...';
            
               SET @CNSCXCN_NUEVO = NULL;

               -- 1. Generar Consecutivo
               BEGIN TRY
                  EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CXC', @CNSCXCN_NUEVO OUTPUT;
               
                  IF @CNSCXCN_NUEVO IS NOT NULL
                  BEGIN
                     SET @CNSCXCN_NUEVO = @IDSEDE + REPLACE(SPACE(8 - LEN(LTRIM(RTRIM(@CNSCXCN_NUEVO)))) + LTRIM(RTRIM(@CNSCXCN_NUEVO)), SPACE(1), '0');
                  END
                  ELSE
                  BEGIN
                     RAISERROR('Error generando consecutivo (NULL)', 16, 1);
                  END
               END TRY
               BEGIN CATCH
                  INSERT INTO @TBLERRORES(ERROR) VALUES ('Error generando consecutivo: ' + ERROR_MESSAGE());
                  FETCH NEXT FROM CURSOR_FECHAS_RADICACION INTO @FECHA_ITERACION, @CANTIDAD_ITERACION;
                  CONTINUE;
               END CATCH

               -- 2. INSERTAR PADRE (FCXC) PRIMERO
               BEGIN TRY
                  INSERT INTO FCXC(
                     CNSCXC, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, 
                     NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, 
                     CNSANT, ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, 
                     SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA, 
                     ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, 
                     MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA, 
                     NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE, TIPOCXC
                  )
                  SELECT 
                     @CNSCXCN_NUEVO, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, @FECHA_ITERACION, QUIENRECIBIO, 
                     NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, 
                     CNSANT, ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, 
                     SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA, 
                     ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, 
                     MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA, 
                     NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE, TIPOCXC
                  FROM FCXC 
                  WHERE CNSCXC = @CNSCXC;
               END TRY
               BEGIN CATCH
                  INSERT INTO @TBLERRORES(ERROR) VALUES ('Error insertando cabecera FCXC: ' + ERROR_MESSAGE());
                  FETCH NEXT FROM CURSOR_FECHAS_RADICACION INTO @FECHA_ITERACION, @CANTIDAD_ITERACION;
                  CONTINUE;
               END CATCH

               -- 3. MOVER HIJOS (FCXCD) AL NUEVO PADRE
               BEGIN TRY
                  UPDATE FCXCD 
                  SET CNSCXC = @CNSCXCN_NUEVO, 
                      NOREFERENCIAEXT = ID2
                  FROM FCXCD 
                  INNER JOIN RPDX ON FCXCD.CNSCXC = RPDX.ID3 AND FCXCD.N_FACTURA = RPDX.ID1
                  WHERE FCXCD.CNSCXC = @CNSCXC 
                    AND RPDX.CNS = @CNSRPDX
                    AND RPDX.FECHA1 = @FECHA_ITERACION;
               END TRY
               BEGIN CATCH
                  INSERT INTO @TBLERRORES(ERROR) VALUES ('Error actualizando detalles FCXCD: ' + ERROR_MESSAGE());
                  FETCH NEXT FROM CURSOR_FECHAS_RADICACION INTO @FECHA_ITERACION, @CANTIDAD_ITERACION;
                  CONTINUE;
               END CATCH

               -- Guardamos esta nueva CXC para radicar después
               INSERT INTO @TMP_CXCS_A_RADICAR (CNSCXC_PROCESAR, FECHA_RADICACION)
               VALUES (@CNSCXCN_NUEVO, @FECHA_ITERACION);
            END

            FETCH NEXT FROM CURSOR_FECHAS_RADICACION INTO @FECHA_ITERACION, @CANTIDAD_ITERACION;
         END

         CLOSE CURSOR_FECHAS_RADICACION;
         DEALLOCATE CURSOR_FECHAS_RADICACION;

         -- Verificar errores en Fase 1 antes de continuar
         IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
         BEGIN
            SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
            RETURN;
         END

         -- ==========================================
         -- FASE 2: RADICACIÓN Y CONTABILIZACIÓN
         -- Objetivo: Ahora que los datos están limpios y separados, procedemos a radicar.
         -- ==========================================
      
         DECLARE @CNS_ACTUAL_RADICAR VARCHAR(50);
         DECLARE @FECHA_ACTUAL_RADICAR DATE;

         DECLARE CURSOR_RADICACION_FINAL CURSOR LOCAL FAST_FORWARD FOR 
         SELECT CNSCXC_PROCESAR, FECHA_RADICACION FROM @TMP_CXCS_A_RADICAR;

         OPEN CURSOR_RADICACION_FINAL;
         FETCH NEXT FROM CURSOR_RADICACION_FINAL INTO @CNS_ACTUAL_RADICAR, @FECHA_ACTUAL_RADICAR;

         WHILE @@FETCH_STATUS = 0
         BEGIN
            PRINT 'FASE 2 - Radicando CXC: ' + @CNS_ACTUAL_RADICAR + ' Fecha: ' + CONVERT(VARCHAR, @FECHA_ACTUAL_RADICAR);

            BEGIN TRY
               -- 1. Radicar (Entrega)
               -- Nota: Usamos el consecutivo específico de esta iteración (@CNS_ACTUAL_RADICAR)
               -- y la fecha específica. Los parámetros globales (@QRECIBE, etc.) se mantienen.
               EXEC SPK_RELIQUIDACXCQX @CNS_ACTUAL_RADICAR
               EXEC SPK_ENTREGA_CXC @CNS_ACTUAL_RADICAR, @QRECIBE, @FECHA_ACTUAL_RADICAR, @NRORADICA, @CNSRPDX, @IDSEDE, @NROGUIA;
            
               -- 2. Contabilizar (Si aplica)
               IF DBO.FNK_VALORVARIABLE('CONTABCXC') = 'SI'
               BEGIN
                  EXEC SPK_CONTAB_RADICACXC @CNS_ACTUAL_RADICAR, @COMPANIA, @IDSEDE, @USUARIO, @SYS_COMPUTERNAME, '';
               END
            END TRY
            BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) VALUES ('Error en Radicación/Contabilidad para CXC ' + @CNS_ACTUAL_RADICAR + ': ' + ERROR_MESSAGE());
               -- Decisión: ¿Continuar con las demás o fallar todo? 
               -- Aquí continuamos para intentar radicar el resto, pero se reportará el error al final.
            END CATCH

            FETCH NEXT FROM CURSOR_RADICACION_FINAL INTO @CNS_ACTUAL_RADICAR, @FECHA_ACTUAL_RADICAR;
         END

         CLOSE CURSOR_RADICACION_FINAL;
         DEALLOCATE CURSOR_RADICACION_FINAL;

         -- ==========================================
         -- 3. CIERRE Y SALIDA
         -- ==========================================
         IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
         BEGIN
            SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
            RETURN;
         END

         SELECT 'OK' AS OK;
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) VALUES ('Cuenta de Cobro ya Radicada o Inconsistente');  
         SELECT 'KO' AS OK, ERROR FROM @TBLERRORES;
         RETURN;
      END
   END
   IF @METODO='CONTAB_FCXC'     
   BEGIN         
      SELECT @CNSCXC = CNSCXC        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
           CNSCXC VARCHAR(20) '$.CNSCXC'
      )                 
      IF NOT EXISTS(SELECT  * FROM FCXC WHERE COALESCE(CONTABILIZADA,0)=0 AND CNSCXC=@CNSCXC)
      BEGIN
         SELECT 'KO'KO,'Cuenta por cobrar no encontrada o ya esta en contabilidad'ERROR
         RETURN
      END
      SELECT @IDSEDE=IDSEDE FROM FCXC WHERE CNSCXC=@CNSCXC
      SELECT @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,UBEQ.SYS_ComputerName,HOST_NAME()),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA,'01')
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
      WHERE USUSU.USUARIO=@USUARIO
      BEGIN TRY           
         EXEC SPK_CONTAB_RADICACXC @CNSCXC,@COMPANIA,@IDSEDE,@USUARIO,@SYS_COMPUTERNAME,''
      END TRY
      BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END
   IF @METODO='IMPRIMIR_FCXC'
   BEGIN 
      SELECT @CNSCXC=CNSCXC
      FROM   OPENJSON (@PARAMETROS)
      WITH (
        CNSCXC VARCHAR(20)  '$.CNSCXC'
      ) 
      IF EXISTS(SELECT * FROM FCXC WHERE CNSCXC=@CNSCXC)
      BEGIN
         
         SELECT @VLLETRAS=LTRIM(RTRIM(TRIM(DBO.FNK_DE_VALORES_A_LETRAS(FCXC.VALORCXC))))
         FROM FCXC WHERE CNSCXC=@CNSCXC

         IF CHARINDEX('/100',@NROLETRAS,1)>0
         BEGIN 
            SELECT @NROLETRAS=LEN(@VLLETRAS)-9
            SELECT @VLLETRAS=SUBSTRING(@VLLETRAS,0,@NROLETRAS)
         END
         ELSE
         BEGIN 
            IF LEN(@VLLETRAS)<4
            BEGIN
               SELECT @VLLETRAS='Cero.'
            END
         END

         SELECT 'OK' OK,CNSCXC,FCXC.IDTERCERO,TER.NIT,TER.DV,TER.RAZONSOCIAL,FCXC.VALORCXC,
			 @VLLETRAS+' PESOS M/CTE. ' AS LETRAS,DBO.FNK_VALORVARIABLE('IDCARGOCARTERA') CARGO1,
			 USUSU.NOMBRE,UPPER(CONVERT(VARCHAR,FCXC.FECHACXC,6))  AS FECHACXC,
			 CASE WHEN EXISTS(SELECT DICOM FROM ARCHIVOS WHERE ID = USU.IDFIRMA ) 
			 THEN  (SELECT DICOM FROM ARCHIVOS WHERE ID = USU.IDFIRMA)
			 ELSE '' END DICOM
			 ,DBO.FNK_VALORVARIABLE('IDJEFECARTERA') CARGO2,USU.NOMBRE AS NOMBRE2,
			 CASE WHEN EXISTS(SELECT DICOM FROM ARCHIVOS WHERE ID = USUSU.IDFIRMA ) 
			 THEN  (SELECT DICOM FROM ARCHIVOS WHERE ID = USUSU.IDFIRMA)
			 ELSE '' END DICOM1,(SELECT COUNT(*) FROM FCXCD WHERE CNSCXC=FCXC.CNSCXC)CANT,
			 LTRIM(RTRIM(COALESCE(DBO.FNK_RTF(FCXC.OBSERVACION),'')))OBSERVACION
         FROM FCXC INNER JOIN TER ON FCXC.IDTERCERO=TER.IDTERCERO
                   LEFT  JOIN USUSU ON FCXC.COORCARTERA=USUSU.USUARIO
                   LEFT  JOIN USUSU USU ON FCXC.COORFACTURACION =USU.USUARIO
         WHERE FCXC.CNSCXC=@CNSCXC

         
		 SELECT  FCXCD.N_FACTURA,CONCAT(COALESCE(AFI.DOCIDAFILIADO,''),'-',COALESCE(AFI.NOMBREAFI,''))NOMBREAFI,CONVERT(VARCHAR,FTR.F_FACTURA,103)F_FACTURA,
         FTR.VR_TOTAL,COALESCE(FTR.VIVA,0)VIVA,FTR.VALORSERVICIOS,FTR.VALORCOPAGO,FTR.VALORPCOMP
         FROM FCXCD INNER JOIN FTR ON FCXCD.N_FACTURA=FTR.N_FACTURA
                    LEFT  JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
         WHERE FCXCD.CNSCXC=@CNSCXC
		 ORDER BY DBO.FNK_LIMPIATEXTO(FCXCD.N_FACTURA,'0-9')

         IF EXISTS(SELECT * FROM FCXC WHERE CNSCXC=@CNSCXC AND COALESCE(MSEDE,0)=1)
         BEGIN
            SELECT @IDSEDE=IDSEDE FROM FCXC WHERE CNSCXC=@CNSCXC
            PRINT 'BUSCO SEDE'
            SELECT TER.RAZONSOCIAL,TER.NIT,TER.DIRECCION,TER.TELEFONOS,CIU.NOMBRE CIUDAD,TER.EMAIL,DEP.NOMBRE AS NDPTO
            FROM SED INNER JOIN TER ON SED.NIT=TER.NIT
                       INNER JOIN CIU ON TER.CIUDAD=CIU.CIUDAD
                       INNER JOIN DEP ON CIU.DPTO=DEP.DPTO
            WHERE IDSEDE=@IDSEDE
         END
         ELSE
         BEGIN
            SELECT TER.RAZONSOCIAL,TER.NIT,TER.DIRECCION,TER.TELEFONOS,CIU.NOMBRE CIUDAD,TER.EMAIL,DEP.NOMBRE AS NDPTO
            FROM TER INNER JOIN CIU ON TER.CIUDAD=CIU.CIUDAD
                     INNER JOIN DEP ON CIU.DPTO=DEP.DPTO
            WHERE TER.IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
         END
         RETURN
      END
      ELSE
      BEGIN
         SELECT 'KO' OK,' Erro al Cargar los Datos'
         RETURN         
      END
   END     

   IF @METODO='NRORAD_FCXCD' 
   BEGIN       
      DECLARE @CONTINUA BIT
      SELECT @CNSCXC=CNSCXC,@N_FACTURA=N_FACTURA,@NRORADICA=NRORADICA,@CONTINUA=CONTINUA      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         CNSCXC VARCHAR(20) '$.CNSCXC',
         N_FACTURA VARCHAR(20) '$.N_FACTURA',
         NRORADICA VARCHAR(30) '$.NRORADICA',
         CONTINUA  BIT '$.CONTINUA'
            )   
            
      IF EXISTS(SELECT  * FROM FCXCD WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA)
      BEGIN TRY           
            UPDATE FCXCD SET NOREFERENCIAEXT=@NRORADICA  WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA
            IF @CONTINUA=1
            BEGIN
               IF EXISTS(SELECT * FROM FCXCD WHERE  CNSCXC=@CNSCXC AND COALESCE(NOREFERENCIAEXT,'')='' )
               BEGIN
                  SELECT TOP 1 @N_FACTURA=COALESCE(N_FACTURA,'') FROM FCXCD WHERE  CNSCXC=@CNSCXC AND COALESCE(NOREFERENCIAEXT,'')=''
               END
               ELSE
               BEGIN
                  SELECT @N_FACTURA=''
               END
            END  
            ELSE
            BEGIN
               SELECT @N_FACTURA=''
            END
      END TRY
      BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,@N_FACTURA N_FACTURA
      RETURN 
   END
   IF @METODO='LISTA_ENTREGA'     
   BEGIN         
      SELECT @CNSCXC=CNSCXC        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSCXC VARCHAR(20) '$.CNSCXC'
      )

      SELECT @IDTERCERO=IDTERCERO FROM FCXC WHERE CNSCXC=@CNSCXC

      SELECT 'OK' OK

      SELECT 'Todas' value, 'Todas las Entregas' label
      UNION ALL 
      SELECT DISTINCT ENT.CNSENTREGA,ENT.CNSENTREGA
      FROM ENT INNER JOIN ENTD ON ENT.CNSENTREGA=ENTD.CNSENTREGA
               INNER JOIN FTR  ON ENTD.NODOCUMENTO=FTR.N_FACTURA
               LEFT  JOIN USUSU ON ENT.USUARIOENTREGA=USUSU.USUARIO
      WHERE ENT.PROCESO='FACTURAS'
      AND ENT.ESTADO=1
      AND FTR.IDTERCERO=@IDTERCERO
      AND COALESCE(ENTD.ENDEVO,0)=0
      AND NOT EXISTS(SELECT * FROM FCXCD WHERE FCXCD.N_FACTURA=FTR.N_FACTURA)
      RETURN              
   END
   IF @METODO='BORRAR_MARCADAS'     
   BEGIN         
      SELECT @CNSCXC=CNSCXC,@OBSERVACION=MOTIVO
      FROM   OPENJSON (@PARAMETROS)
      WITH (
         CNSCXC VARCHAR(20) '$.CNSCXC',
         MOTIVO  VARCHAR(512)  '$.MOTIVO'
      ) 
      PRINT 'Cuenta de Cobro='+COALESCE(@CNSCXC,'SIN CXC')
      IF COALESCE(@CNSCXC,'')<>'' 
      BEGIN
         BEGIN TRY    
         
            INSERT INTO FCXCR(CNSCXC, N_FACTURA, COMPANIA, VALORFACTURA, OBSERVACION, USUARIO, FECHA, ITFC, CNSITFC, CONTABILIZADA, NROCOMPROBANTE,
                              USURESP, RESPUESTA, ESTADO, PROCESO, MOTIVO1, MOTIVO2, COD_RESPUESTA,  COD_REP1, COD_REP2)
            SELECT @CNSCXC, @N_FACTURA,'01', VALORFACTURA, @OBSERVACION, @USUARIO, DBO.FNK_GETDATE(), 0, NULL, 0, NULL, NULL,
                   NULL, NULL, 'Retirada', NULL, NULL,  NULL,  NULL, NULL
            FROM FCXCD WHERE CNSCXC=@CNSCXC
            AND FCXCD.N_FACTURA=@N_FACTURA
            AND COALESCE(FCXCD.MARCA,0)=1

            UPDATE FTR SET MARCA=0, EQUIMARCA=NULL,INDASIGCXC=0,INDCXC=0
            FROM FTR INNER JOIN FCXCD ON FTR.N_FACTURA=FCXCD.N_FACTURA
            WHERE FCXCD.CNSCXC=@CNSCXC
            AND COALESCE(FCXCD.MARCA,0)=1
            
            DELETE FCXCD WHERE CNSCXC=@CNSCXC AND COALESCE(FCXCD.MARCA,0)=1

            EXEC SPK_RELIQUIDACXCQX @CNSCXC 

         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se encontro la cuenta de cobro, verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 

   END  
   IF @METODO='MARCAR_FACTU'     
   BEGIN         
      SELECT @CNSCXC=CNSCXC,@N_FACTURA=N_FACTURA        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSCXC VARCHAR(20) '$.CNSCXC',
      N_FACTURA VARCHAR(20) '$.N_FACTURA'
      )
      IF EXISTS(SELECT  * FROM FCXCD WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA)
      BEGIN
         UPDATE FCXCD SET MARCA=1-MARCA WHERE CNSCXC=@CNSCXC AND N_FACTURA=@N_FACTURA
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Cuenta de cobro y factura no encontrada, verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='SALIR_FCXCD'     
   BEGIN         
      SELECT @CNSCXC=CNSCXC       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSCXC VARCHAR(20) '$.CNSCXC'
      )
      PRINT '@CNSCXC ='+@CNSCXC
      IF EXISTS(SELECT  * FROM FCXCD WHERE CNSCXC=@CNSCXC)
      BEGIN
         UPDATE FCXCD SET MARCA= 0 WHERE CNSCXC=@CNSCXC
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN    
   END 
   
   IF @METODO='GENERAR_REMESAS'
   BEGIN
	BEGIN TRY
		DECLARE @TIPO_FACT VARCHAR(10)
		SELECT @DATOS=DATOS ,@TIPOCXC=TIPOCXC
		FROM   OPENJSON (@PARAMETROS)
		WITH (DATOS NVARCHAR(MAX) AS JSON, TIPOCXC VARCHAR(20)  '$.TIPOCXC') 

		SELECT @IDTERCERO=IDTERCERO,@OBSERVACION=OBSERVACION,@MSEDE=CONVERT(INT,REQSEDE),@IDSEDEF=IDSEDEF,@MODALIDAD=MODALIDAD,
				@ATENCION=ATENCION,@MES=CONVERT(INT,MES),@ANO=ANO,@REGIMEN=REGIMEN
			FROM   OPENJSON (@DATOS)
			WITH   (
			IDTERCERO VARCHAR(20)    '$.IDTERCERO',
			OBSERVACION VARCHAR(512) '$.OBSERVACION',
			REQSEDE     BIT          '$.REQSEDE',
			IDSEDEF     VARCHAR(6)   '$.IDSEDE',
			MODALIDAD   VARCHAR(20)  '$.MODALIDAD',
			ATENCION   VARCHAR(20)   '$.ATENCION',
			MES         VARCHAR(20)  '$.MES',
			ANO         VARCHAR(20)  '$.ANO',
			REGIMEN     VARCHAR(20)  '$.REGIMEN'
			) 

		IF DBO.FNK_VALORVARIABLE('USUARIOJEFECARTERA')=''
         BEGIN
            SELECT 'KO' KO, 'Debe llenar la variable USUARIOJEFECARTERA con el usuario del jefe de Cartera, Verifique e Intente de nuevo' ERROR
            RETURN
         END
         IF NOT EXISTS(SELECT * FROM USUSU WHERE USUARIO=RTRIM(RTRIM(DBO.FNK_VALORVARIABLE('USUARIOJEFECARTERA'))))
         BEGIN
            SELECT 'KO' KO, 'El dato de la Variable USUARIOJEFECARTERA no es Valido, Valide e Intente de nuevo ' ERROR
            RETURN
         END
         IF DBO.FNK_VALORVARIABLE('USUARIOJEFEFACTURA')=''
         BEGIN
            SELECT 'KO' KO,'Debe llenar la variable USUARIOJEFEFACTURA con el usuario del jefe de Cartera, Verifique e Intente de nuevo' ERROR
            RETURN
         END
         IF NOT EXISTS(SELECT * FROM USUSU WHERE USUARIO=RTRIM(RTRIM(DBO.FNK_VALORVARIABLE('USUARIOJEFEFACTURA'))))
         BEGIN
            SELECT 'KO' KO, 'El dato de la Variable USUARIOJEFEFACTURA no es Valido, Valide e Intente de nuevo ' ERROR
            RETURN
         END

		 PRINT 'INICIO PROCESO DE GENERACION DE REMESAS' 
		SELECT @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_COMPUTERNAME,HOST_NAME()),@IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
         WHERE USUARIO=@USUARIO
		SELECT @OBSERVACION = LTRIM(RTRIM(OBSERVACION)) FROM USVGS WHERE IDVARIABLE = 'FCXC_OBSERVACION_DEF';
		SELECT @COORFACTURACION = DBO.FNK_VALORVARIABLE('USUARIOJEFEFACTURA');
		SELECT @COORCARTERA = DBO.FNK_VALORVARIABLE('USUARIOJEFECARTERA');
		PRINT '@IDTERCERO >'  + COALESCE(@IDTERCERO,' SIN @IDTERCERO')

		IF @MSEDE=1 AND COALESCE(@IDSEDEF,'')<>''
         BEGIN
            SELECT @IDSEDE=@IDSEDEF
         END
		SET @MES = MONTH(GETDATE());
		SET @ANO = YEAR(GETDATE());
--QUERY2
--QUERY2
		IF COALESCE(@TIPOCXC,'')='FNOT'
		BEGIN
			PRINT 'REMESA DE ABONO'
			SELECT ROW_NUMBER() OVER (ORDER BY CNSFNOT) AS RN, CNSFNOT, N_FACTURA, IDTERCERO
			INTO #FNOT_MARCADAS
			FROM FNOT
			WHERE MARCA = 1
				AND COALESCE(USUMARCA, '') = @USUARIO
				AND NOT EXISTS(SELECT * FROM FCXCD WHERE FCXCD.N_FACTURA=FNOT.N_FACTURA)

			-- Validar mecanismos / procedencias homogéneas (igual que remesas FTR)
			IF (SELECT COUNT(DISTINCT COALESCE(FTR.MEC_FACT,''))
			    FROM #FNOT_MARCADAS fm
			    INNER JOIN FTR ON FTR.N_FACTURA = fm.N_FACTURA) > 1
			BEGIN
				SELECT 'KO' KO, 'Las notas marcadas pertenecen a diferentes mecanismos (CPM / PPS / MER). Por favor, revise y desmarque las que no correspondan.' ERROR
				DROP TABLE #FNOT_MARCADAS;
				RETURN;
			END

			IF (SELECT COUNT(DISTINCT COALESCE(FTR.PROCEDENCIA,''))
			    FROM #FNOT_MARCADAS fm
			    INNER JOIN FTR ON FTR.N_FACTURA = fm.N_FACTURA) > 1
			BEGIN
				SELECT 'KO' KO, 'Las notas marcadas pertenecen a diferentes procedencias (MAD / PHD / CMV). Por favor, revise y desmarque las que no correspondan.' ERROR
				DROP TABLE #FNOT_MARCADAS;
				RETURN;
			END

			-- Validar que para PHD (SALUD) todas las facturas pertenezcan al mismo plan
			IF EXISTS (SELECT 1 FROM #FNOT_MARCADAS fm
			           INNER JOIN FTR ON FTR.N_FACTURA = fm.N_FACTURA
			           WHERE FTR.PROCEDENCIA = 'SALUD')
			BEGIN
				IF (SELECT COUNT(DISTINCT FTR.IDPLAN)
				    FROM #FNOT_MARCADAS fm
				    INNER JOIN FTR ON FTR.N_FACTURA = fm.N_FACTURA
				    WHERE FTR.PROCEDENCIA = 'SALUD') > 1
				BEGIN
					SELECT 'KO' KO, 'Para remesas PHD (abonos) todas las facturas deben pertenecer al mismo plan. Por favor, seleccione un plan y desmarque las que no correspondan.' ERROR
					DROP TABLE #FNOT_MARCADAS;
					RETURN;
				END
			END

			-- Inicialización
			SET @TOTAL = (SELECT COUNT(*) FROM #FNOT_MARCADAS);
			SELECT @INICIO = 1, @FIN = 990, @LIMITE = 990;

			WHILE @INICIO <= @TOTAL
			BEGIN
				-- Generar consecutivo
				SET @CNSCXC = NULL;
				EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CXC', @CNSCXC OUTPUT;
				PRINT '@CNSCXC >'  + COALESCE(@CNSCXC,' SIN @CNSCXC')
				SET @CNSCXC = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSCXC)) + LTRIM(RTRIM(@CNSCXC)), SPACE(1), '0');
				PRINT '@CNSCXC >'  + COALESCE(@CNSCXC,' SIN @CNSCXC')

				PRINT 'VOY A CREAR FCXC' 
				-- Insertar FCXC
				INSERT INTO FCXC(CNSCXC, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT, 
								  ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA, 
								  ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA, 
								  NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE,TIPOCXC)
				SELECT @CNSCXC, DBO.FNK_GETDATE(), @IDTERCERO, NULL, NULL, 0, NULL, NULL, NULL, @USUARIO,@COMPANIA, 0, 0, 0, 0, NULL,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,@OBSERVACION, NULL, 'CARTERA', 
				0, 0, 0, NULL, 0, NULL, @IDSEDE, @MODALIDAD, @ATENCION, @MES, @ANO, @REGIMEN, NULL, NULL, NULL, 'Activa',@COORFACTURACION,@COORCARTERA,0, NULL, NULL, NULL, @MSEDE,@TIPOCXC 

				PRINT 'VOY A CREAR FCXCD' 
				-- Insertar en FCXCD las facturas del lote actual
				INSERT INTO FCXCD(CNSCXC, N_FACTURA, USUARIO, COMPANIA, VALORFACTURA, DEDUCCIONES, VALORFACTURANETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, 
									 SALDO, SALDONETO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, MARCAPAGO,  NT_MARCAP, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, 
									 NROCOMPROBANTE, CUENTA, DESCRIPCION, NOREFERENCIAEXT, ENCOBROJUR, IDPLAN, ITFC, CNSITFC, VLRFCES, VLRLEVANTADO, 
									 MARCA, USURESP, RESPUESTA,  RAZONDEVOL,CNSFNOT)
				   SELECT @CNSCXC, FTR.N_FACTURA, @USUARIO, @COMPANIA, FTR.VR_TOTAL, 0, FTR.VR_TOTAL, 0, 0, 0, VR_TOTAL, VR_TOTAL,
							0, 0, 0, 0,  NULL, 0, 0, 0, NULL, FTR.CUENTACXC,'Traida desde Quasar', null, 0, FTR.IDPLAN, 0, NULL, 0, 0, 0, NULL, NULL,  NULL,FM.CNSFNOT
				FROM FTR
				INNER JOIN #FNOT_MARCADAS FM ON FM.N_FACTURA = FTR.N_FACTURA
				WHERE FM.RN BETWEEN @INICIO AND @FIN;

				-- Actualizar facturas como asignadas
				UPDATE FTR
				SET INDASIGCXC = 1,
					INDCXC = 1
				WHERE N_FACTURA IN (
					SELECT N_FACTURA FROM #FNOT_MARCADAS WHERE RN BETWEEN @INICIO AND @FIN
				);

				UPDATE FNOT SET CNSCXC = @CNSCXC WHERE CNSFNOT IN (
					SELECT CNSFNOT FROM #FNOT_MARCADAS WHERE RN BETWEEN @INICIO AND @FIN
				)

				PRINT 'ACTUALIZO VALORES'
				EXEC SPK_RELIQUIDACXCQX @CNSCXC;

				-- Avanzar al siguiente lote
				SET @INICIO = @INICIO + @LIMITE;
				SET @FIN = @FIN + @LIMITE;
			END

			-- Limpiar temporal
			DROP TABLE #FNOT_MARCADAS;	
		END
		ELSE
		BEGIN
			SELECT ROW_NUMBER() OVER (ORDER BY N_FACTURA) AS RN, N_FACTURA, IDTERCERO, IDPLAN, CUENTACXC, MEC_FACT, PROCEDENCIA
			INTO #FACTURAS_MARCADAS
			FROM FTR
			WHERE MARCA = 1
				AND COALESCE(EQUIMARCA, '') = @SYS_COMPUTERNAME
				AND ESTADO = 'P'
				AND COALESCE(CLASEANULACION, '') <> 'NC'
				AND COALESCE(VR_TOTAL, 0) > 0
				AND COALESCE(CONTABILIZADA, 0) <> 0
				AND NOT EXISTS (SELECT 1 FROM FCXCD WHERE FCXCD.N_FACTURA = FTR.N_FACTURA)
				AND COALESCE(INDCARTERA, 0) = 1
				AND INDCXC = 0
				AND INDASIGCXC = 0
				AND IDDEP = DBO.FNK_VALORVARIABLE('IDFDEPCARTERA');

			-- Validar que existen facturas marcadas
			IF NOT EXISTS(SELECT 1 FROM #FACTURAS_MARCADAS)
			BEGIN
				SELECT 'KO' KO, 'No existen facturas marcadas. Por favor, valide.' ERROR
				DROP TABLE #FACTURAS_MARCADAS;
				RETURN;
			END

			-- Validar que todas las facturas sean del mismo mecanismo
			IF (SELECT COUNT(DISTINCT MEC_FACT) FROM #FACTURAS_MARCADAS) > 1
			BEGIN
				SELECT 'KO' KO, 'Las facturas marcadas pertenecen a diferentes mecanismos (CPM / PPS / MER). Por favor, revise y desmarque las que no correspondan.' ERROR
				DROP TABLE #FACTURAS_MARCADAS;
				RETURN;
			END

			-- Validar que todas las facturas sean de la misma procedencia
			IF (SELECT COUNT(DISTINCT PROCEDENCIA) FROM #FACTURAS_MARCADAS) > 1
			BEGIN
				SELECT 'KO' KO, 'Las facturas marcadas pertenecen a diferentes procedencias (MAD / PHD / CMV). Por favor, revise y desmarque las que no correspondan.' ERROR
				DROP TABLE #FACTURAS_MARCADAS;
				RETURN;
			END

			-- Validar que para PHD (SALUD) todas las facturas pertenezcan al mismo plan
			IF EXISTS (SELECT 1 FROM #FACTURAS_MARCADAS WHERE PROCEDENCIA = 'SALUD')
			   AND (SELECT COUNT(DISTINCT IDPLAN) FROM #FACTURAS_MARCADAS) > 1
			BEGIN
				SELECT 'KO' KO, 'Para remesas PHD todas las facturas deben pertenecer al mismo plan. Por favor, seleccione un plan y desmarque las facturas que no correspondan.' ERROR
				DROP TABLE #FACTURAS_MARCADAS;
				RETURN;
			END

			-- Inicialización
			SET @TOTAL = (SELECT COUNT(*) FROM #FACTURAS_MARCADAS);
			SELECT @INICIO = 1, @FIN = 990, @LIMITE = 990;
			SELECT TOP 1 @MEC_FACT = MEC_FACT FROM #FACTURAS_MARCADAS;
			SELECT TOP 1 @TIPO_FACT = PROCEDENCIA FROM #FACTURAS_MARCADAS;

			WHILE @INICIO <= @TOTAL
			BEGIN
				-- Generar consecutivo
				SET @CNSCXC = NULL;
				EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CXC', @CNSCXC OUTPUT;
				PRINT '@CNSCXC >'  + COALESCE(@CNSCXC,' SIN @CNSCXC')
				SET @CNSCXC = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSCXC)) + LTRIM(RTRIM(@CNSCXC)), SPACE(1), '0');
				PRINT '@CNSCXC >'  + COALESCE(@CNSCXC,' SIN @CNSCXC')

				PRINT 'VOY A CREAR FCXC' 
				-- Insertar FCXC
				INSERT INTO FCXC(CNSCXC, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT, 
								  ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA, 
								  ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA, 
								  NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE,TIPOCXC,MEC_FACT,TIPO_FACT)
				SELECT @CNSCXC, DBO.FNK_GETDATE(), @IDTERCERO, NULL, NULL, 0, NULL, NULL, NULL, @USUARIO,@COMPANIA, 0, 0, 0, 0, NULL,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,@OBSERVACION, NULL, 'CARTERA', 
				0, 0, 0, NULL, 0, NULL, @IDSEDE, @MODALIDAD, @ATENCION, @MES, @ANO, @REGIMEN, NULL, NULL, NULL, 'Activa',@COORFACTURACION,@COORCARTERA,0, NULL, NULL, NULL, @MSEDE,'FTR',@MEC_FACT,@TIPO_FACT 

				PRINT 'VOY A CREAR FCXCD' 
				-- Insertar en FCXCD las facturas del lote actual
				INSERT INTO FCXCD(CNSCXC, N_FACTURA, USUARIO, COMPANIA, VALORFACTURA, DEDUCCIONES, VALORFACTURANETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, 
									 SALDO, SALDONETO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, MARCAPAGO,  NT_MARCAP, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, 
									 NROCOMPROBANTE, CUENTA, DESCRIPCION, NOREFERENCIAEXT, ENCOBROJUR, IDPLAN, ITFC, CNSITFC, VLRFCES, VLRLEVANTADO, 
									 MARCA, USURESP, RESPUESTA,  RAZONDEVOL)
				   SELECT @CNSCXC, FTR.N_FACTURA, @USUARIO, @COMPANIA, FTR.VR_TOTAL, 0, FTR.VR_TOTAL, 0, 0, 0, VR_TOTAL, VR_TOTAL,
							0, 0, 0, 0,  NULL, 0, 0, 0, NULL, FTR.CUENTACXC,'Traida desde Quasar', null, 0, FTR.IDPLAN, 0, NULL, 0, 0, 0, NULL, NULL,  NULL
				FROM FTR
				INNER JOIN #FACTURAS_MARCADAS FM ON FM.N_FACTURA = FTR.N_FACTURA
				WHERE FM.RN BETWEEN @INICIO AND @FIN;

				-- Actualizar facturas como asignadas
				UPDATE FTR
				SET INDASIGCXC = 1,
					INDCXC = 1
				WHERE N_FACTURA IN (
					SELECT N_FACTURA FROM #FACTURAS_MARCADAS WHERE RN BETWEEN @INICIO AND @FIN
				);

				PRINT 'ACTUALIZO VALORES'
				EXEC SPK_RELIQUIDACXCQX @CNSCXC;

				-- Avanzar al siguiente lote
				SET @INICIO = @INICIO + @LIMITE;
				SET @FIN = @FIN + @LIMITE;
			END

			-- Limpiar temporal
			DROP TABLE #FACTURAS_MARCADAS;
		END
	END TRY

	BEGIN CATCH
		INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
    END CATCH

    IF(SELECT COUNT(*) FROM @TBLERRORES)>0
    BEGIN
        SELECT 'KO' OK
        SELECT ERROR FROM @TBLERRORES
        RETURN
    END

    SELECT 'OK' OK
    RETURN 
   END
   
   IF @METODO='ENVIAR_REMESA_SAP'
	BEGIN 
		BEGIN TRY
			SELECT @CNSCXC=CNSCXC
			FROM   OPENJSON (@PARAMETROS)
			WITH (
				CNSCXC VARCHAR(20) '$.CNSCXC'
			)

			IF COALESCE(@CNSCXC,'')='' OR NOT EXISTS(SELECT 1 FROM FCXC WHERE CNSCXC=@CNSCXC)
			BEGIN
				SELECT 'KO' OK, 'Cuenta de Cobro Presenta inconsistencias en su Creacion, Valide e intente de nuevo' ERROR
				RETURN
			END

			SELECT @TIPOCXC=TIPOCXC FROM FCXC WHERE CNSCXC=@CNSCXC

			IF COALESCE(@TIPOCXC,'FTR') = 'FNOT'
			BEGIN
				IF CURSOR_STATUS('local', 'FCXCNOT_CURSOR') >= 0
				BEGIN
					IF CURSOR_STATUS('local', 'FCXCNOT_CURSOR') = 1
						CLOSE FCXCNOT_CURSOR;
					DEALLOCATE FCXCNOT_CURSOR;
				END

				DECLARE FCXCNOT_CURSOR CURSOR LOCAL FOR
				SELECT FCXCD.N_FACTURA, FCXCD.CNSFNOT FROM FCXCD 
				INNER JOIN FNOT ON FNOT.N_FACTURA=FCXCD.N_FACTURA
				WHERE FCXCD.CNSCXC = @CNSCXC AND COALESCE(FNOT.FACTEP,'') <> '102'
			
				OPEN FCXCNOT_CURSOR
				FETCH NEXT FROM FCXCNOT_CURSOR    
				INTO @N_FACTURA, @CNSFNOT
				WHILE @@FETCH_STATUS = 0    
				BEGIN
					PRINT 'INGRESE A EL CURSOR PARA [ENVIAR_REMESA_SAP].................'
			
					PRINT '@N_FACTURA > '+COALESCE(@N_FACTURA,'NO TENGO FACTURA')
					PRINT '@CNSFNOT >'  + COALESCE(@CNSFNOT,' SIN @CNSFNOT')
					IF NOT EXISTS(SELECT 1 FROM FNOT WHERE CNSFNOT=@CNSFNOT )
					BEGIN
						PRINT 'No existe el Documento En Notas Credito'
						FETCH NEXT FROM FCXCNOT_CURSOR    
						INTO @N_FACTURA, @CNSFNOT
						CONTINUE
					END
					IF COALESCE(@N_FACTURA,'')='' OR NOT EXISTS(SELECT 1 FROM FTR WHERE N_FACTURA=@N_FACTURA)
					BEGIN
						PRINT 'No existe el Documento En Facturacion'
						FETCH NEXT FROM FCXCNOT_CURSOR    
						INTO @N_FACTURA, @CNSFNOT
						CONTINUE
					END
					IF EXISTS(SELECT 1 FROM FTR WHERE N_FACTURA=@N_FACTURA AND (COALESCE(VR_TOTAL,0)<=0 OR TIPOANULACION<>'NC'))
					BEGIN
						PRINT 'Factura Sin Valor o no Anulada, No se Puede Enviar'
						FETCH NEXT FROM FCXCNOT_CURSOR    
						INTO @N_FACTURA, @CNSFNOT
						CONTINUE
					END
		
					IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
					BEGIN	
						PRINT 'INGRESO A ENVIO DE PROOVEDORES'
						IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP'
						BEGIN
							EXEC SPK_JSON_FTR_PERU_INTERFAX_FNOT @CNSFNOT,@N_FACTURA, 0
						END        
					END
			
					FETCH NEXT FROM FCXCNOT_CURSOR    
					INTO @N_FACTURA, @CNSFNOT
				END
				CLOSE FCXCNOT_CURSOR
				DEALLOCATE FCXCNOT_CURSOR
			
				PRINT 'TERMINE EL CURSOR'
				UPDATE FCXC SET ITFC = 1, FENVIO_ITFC = GETDATE() WHERE CNSCXC = @CNSCXC
			END
			ELSE
			BEGIN
				-- AHORA LAS CXC DE FACTURAS LAS ENVIA EL JOB SPK_ENVIAR_FACTURAS
				UPDATE FCXC SET ITFC = 1, FENVIO_ITFC = GETDATE() WHERE CNSCXC = @CNSCXC
				--IF CURSOR_STATUS('local', 'FCXC_CURSOR') >= 0
				--BEGIN
				--	IF CURSOR_STATUS('local', 'FCXC_CURSOR') = 1
				--		CLOSE FCXC_CURSOR;
				--	DEALLOCATE FCXC_CURSOR;
				--END

				--DECLARE FCXC_CURSOR CURSOR LOCAL FOR
				--SELECT FCXCD.N_FACTURA FROM FCXCD 
				--INNER JOIN FTR ON FTR.N_FACTURA=FCXCD.N_FACTURA
				--WHERE CNSCXC = @CNSCXC AND COALESCE(FTR.FACTEP,'') <> '102'
			
				--OPEN FCXC_CURSOR
				--FETCH NEXT FROM FCXC_CURSOR    
				--INTO @N_FACTURA
				--WHILE @@FETCH_STATUS = 0    
				--BEGIN
				--	PRINT 'INGRESE A EL CURSOR PARA [ENVIAR_REMESA_SAP].................'
			
				--	PRINT '@N_FACTURA > '+COALESCE(@N_FACTURA,'NO TENGO FACTURA')
				--	IF COALESCE(@N_FACTURA,'')='' OR NOT EXISTS(SELECT 1 FROM FTR WHERE N_FACTURA=@N_FACTURA)
				--	BEGIN
				--		--SELECT 'KO' OK, 'No existe el Documento En Facturacion' ERROR
				--		PRINT 'No existe el Documento En Facturacion'
				--		FETCH NEXT FROM FCXC_CURSOR    
				--		INTO @N_FACTURA
				--		CONTINUE
				--	END
				--	IF EXISTS(SELECT 1 FROM FTR WHERE N_FACTURA=@N_FACTURA AND (COALESCE(VR_TOTAL,0)<=0 OR ESTADO<>'P'))
				--	BEGIN
				--		--SELECT 'KO' OK, 'Factura Sin Valor o Anulada, No se Puede Enviar' ERROR
				--		PRINT 'Factura Sin Valor o Anulada, No se Puede Enviar'
				--		FETCH NEXT FROM FCXC_CURSOR    
				--		INTO @N_FACTURA
				--		CONTINUE
				--	END
				--	IF NOT EXISTS(SELECT 1 FROM FTRD WHERE N_FACTURA=@N_FACTURA )
				--	BEGIN
				--		--SELECT 'KO' OK, 'Factura Sin Detalles, No se Puede Enviar' ERROR
				--		PRINT 'Factura Sin Detalles, No se Puede Enviar'
				--		FETCH NEXT FROM FCXC_CURSOR    
				--		INTO @N_FACTURA
				--		CONTINUE
				--	END
		
				--	IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
				--	BEGIN	
				--		PRINT 'INGRESO A ENVIO DE PROOVEDORES'
				--		IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP'
				--		BEGIN
				--			EXEC SPK_JSON_FTR_PERU_INTERFAX @N_FACTURA, 0
				--		END        
				--	END
			
				--	FETCH NEXT FROM FCXC_CURSOR    
				--	INTO @N_FACTURA
				--END
				--CLOSE FCXC_CURSOR
				--DEALLOCATE FCXC_CURSOR
			
				--PRINT 'TERMINE EL CURSOR'
			END
		END TRY

		BEGIN CATCH
			IF CURSOR_STATUS('local', 'FCXC_CURSOR') >= 0
			BEGIN
				IF CURSOR_STATUS('local', 'FCXC_CURSOR') = 1
					CLOSE FCXC_CURSOR;
				DEALLOCATE FCXC_CURSOR;
			END
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH

		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		SELECT 'OK' OK
		RETURN
	END

	IF @METODO = 'EXPORTAR_FORMATO_CxC'
	BEGIN
		SELECT @CNSCXC = JSON_VALUE(@PARAMETROS, '$.CNSCXC')
		IF COALESCE(@CNSCXC,'')=''
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR = 'CNSCXC no encontrado'
			RETURN
		END	
		SELECT 'OK' AS OK
		PRINT 'CNSCXC=' + @CNSCXC
		
		SELECT N_FACTURA, '' AS NOREFERENCIAEXT
		FROM FCXCD
		WHERE FCXCD.CNSCXC=@CNSCXC
	END

	IF @METODO = 'IMPORTAR_RADICADO_CXC'
	BEGIN
		SELECT @CNSCXC=JSON_VALUE(@PARAMETROS,'$.CNSCXC')

		SELECT @PARAMETROS = DATA
		FROM OPENJSON(@PARAMETROS)
		WITH (DATA NVARCHAR(MAX) AS JSON);
		
		SELECT N_FACTURA, NOREFERENCIAEXT
		INTO #FCXCD
		FROM OPENJSON(@PARAMETROS)
		WITH (
			N_FACTURA VARCHAR(16) '$.N_FACTURA'
			,NOREFERENCIAEXT VARCHAR(30) '$.NOREFERENCIAEXT'
		)
		ALTER TABLE #FCXCD ADD ERROR VARCHAR(512)
		IF NOT EXISTS(SELECT 1 FROM FCXC WHERE CNSCXC=@CNSCXC AND INDRECIBIDO=1)
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR ='La cuenta de cobro indicada no existe o no se ha radicado'
			RETURN
		END

		UPDATE #FCXCD SET ERROR='Factura '+COALESCE(#FCXCD.N_FACTURA,'')+' no existe en cuenta de cobro '+COALESCE(@CNSCXC,'')
		WHERE ERROR IS NULL AND NOT EXISTS (SELECT 1 FROM FCXCD WHERE CNSCXC=@CNSCXC AND FCXCD.N_FACTURA=#FCXCD.N_FACTURA)
		
		UPDATE #FCXCD SET ERROR='Debe ingresar un numero de radicado en la factura '+COALESCE(#FCXCD.N_FACTURA,'')
		WHERE COALESCE(NOREFERENCIAEXT,'')='' AND ERROR IS NULL

		--UPDATE #FCXCD SET ERROR='La factura '+COALESCE(#FCXCD.N_FACTURA,'')+' ya cuenta con un numero de radicado'
		--WHERE NOT EXISTS (SELECT 1 FROM FCXCD WHERE CNSCXC=@CNSCXC AND FCXCD.N_FACTURA=#FCXCD.N_FACTURA AND COALESCE(FCXCD.NOREFERENCIAEXT,'')='') AND ERROR IS NULL
	    
		UPDATE FCXCD SET NOREFERENCIAEXT=A.NOREFERENCIAEXT
		FROM FCXCD
			INNER JOIN #FCXCD A ON A.N_FACTURA=FCXCD.N_FACTURA
		WHERE CNSCXC=@CNSCXC AND A.ERROR IS NULL

		SELECT 'OK' AS OK

		SELECT N_FACTURA, NOREFERENCIAEXT, ERROR
		FROM #FCXCD
		WHERE ERROR IS NOT NULL

	END
   IF @METODO='TRAER_CXC_VALIDADOS'     
   BEGIN         
      SELECT @CNSCXC=JSON_VALUE(@PARAMETROS,'$.CNSCXC')

      SELECT 'OK'OK, COUNT(*) CANT,SUM(CASE WHEN COALESCE(FTR.CUV,'')<>'' THEN 1 ELSE 0 END) VALIDADOS,
      SUM(CASE WHEN COALESCE(FTR.CUV,'')<>'' THEN 0 ELSE 1 END) ERRADOS
      FROM FCXCD INNER JOIN FTR ON FCXCD.N_FACTURA=FTR.N_FACTURA
      WHERE FCXCD.CNSCXC=@CNSCXC
      
      SELECT FTR.CNSFCT,FCXCD.N_FACTURA,FTRJSON.JSON_ENVIO,FTRJSON.JSON_RESPUESTA,FTRJSON.CUV,FTRJSON.FRADICA_RIPS
      FROM FCXCD INNER JOIN FTR ON FCXCD.N_FACTURA=FTR.N_FACTURA
                 INNER JOIN FTRJSON ON FTR.CNSFCT=FTRJSON.CNSFCT
      WHERE FCXCD.CNSCXC=@CNSCXC 
      AND COALESCE(FTR.CUV,'')<>''
      RETURN   
   END 
   IF @METODO='MOVER_FACTURAS_FCXC'     
   BEGIN         
      SELECT @DATOS=DATOS,@CNSCXC=CNSCXC_ORIGEN,@CNSENTREGA=CNSCXC_DESTINO    
      FROM   OPENJSON (@PARAMETROS)
      WITH ( 
      CNSCXC_ORIGEN  VARCHAR(20)   '$.CNSCXC_ORIGEN',
      CNSCXC_DESTINO  VARCHAR(20)   '$.CNSCXC_DESTINO',
      DATOS NVARCHAR(MAX) AS JSON 
      )

      SELECT * INTO #FCXCDX       
      FROM   OPENJSON (@DATOS)
      WITH   ( 
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA',
      NOREFERENCIAEXT  VARCHAR(20)   '$.NOREFERENCIAEXT'
      )   

     BEGIN TRY           
         UPDATE FCXCD SET CNSCXC=@CNSENTREGA,NOREFERENCIAEXT=CASE WHEN COALESCE(X.NOREFERENCIAEXT,'')<>'' THEN X.NOREFERENCIAEXT ELSE FCXCD.NOREFERENCIAEXT END
         FROM FCXCD INNER JOIN #FCXCDX X ON FCXCD.N_FACTURA=X.N_FACTURA 
         WHERE FCXCD.CNSCXC=@CNSCXC    
         
			PRINT 'ACTUALIZO VALORES ANTERIOR'
			EXEC SPK_RELIQUIDACXCQX @CNSCXC;
         PRINT 'ACTUALIZO VALORES NUEVA'
         EXEC SPK_RELIQUIDACXCQX @CNSENTREGA;
     END TRY
     BEGIN CATCH
             INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
     END CATCH

     DROP TABLE #FCXCDX  

      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
          RETURN
      END
      SELECT 'OK' OK 
      RETURN 
   END 
   IF @METODO='FECHA_ENVIO'     
   BEGIN         
      SELECT @CNSCXC=CNSCXC,@FECHARAD=CONVERT(DATE,FECHA),@NROGUIA=GUIA   
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSCXC  VARCHAR(20)   '$.CNSCXC',
      FECHA  VARCHAR(20)   '$.FECHA',
      GUIA  VARCHAR(20)   '$.GUIA'
      )
      IF EXISTS(SELECT  * FROM FCXC WHERE CNSCXC=@CNSCXC AND FENVIO IS NULL)  
      BEGIN
         BEGIN TRY           
             UPDATE FCXC SET FENVIO=@FECHARAD,QUIENRECIBIO=@USUARIO,NROGUIA=@NROGUIA WHERE CNSCXC=@CNSCXC                 
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'La cuenta por Cobrar ya fue enviada, Verfique e intente de nuevo '
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
          RETURN
      END
      SELECT 'OK' OK 
      RETURN 
   END  
   IF @METODO='ACTUALIZAR_RPDX_RADICACION'     
   BEGIN         
      SELECT @CNSCXC=CNSCXC,@CNSRPDX=CNSRPDX, @DATOS=[DATA]        
      FROM   OPENJSON (@PARAMETROS)
      WITH ( 
      CNSCXC  VARCHAR(20)   '$.CNSCXC',
      CNSRPDX  VARCHAR(20)   '$.CNSRPDX',
      [DATA] NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT * INTO #FACTU       
      FROM   OPENJSON (@DATOS)
      WITH   ( 
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA',
      NOREFERENCIAEXT  VARCHAR(20)   '$.NOREFERENCIAEXT',
      FECHA_RADICADO  VARCHAR(20)   '$.FECHA_RADICADO'
      ) 

      SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
      WHERE USUARIO=@USUARIO
      SELECT @MSEDE=MSEDE,@IDSEDEF=IDSEDE FROM FCXC WHERE CNSCXC=@CNSCXC
      IF @MSEDE=1 AND COALESCE(@IDSEDEF,'')<>''
      BEGIN
         SELECT @IDSEDE=@IDSEDEF
      END
      IF COALESCE(@CNSRPDX,'')=''
      BEGIN
         BEGIN TRY
            PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')  +COALESCE(@COMPANIA,'CIA') 
            SELECT @CNSRPDX=''
	         EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSRPDX OUTPUT   
	         SELECT @CNSRPDX = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
	         PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'')                               
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
      END   
      INSERT INTO RPDX (CNS,ID1,ID2,FECHA1,ID3)
      SELECT @CNSRPDX,N_FACTURA,NOREFERENCIAEXT,CAST(FECHA_RADICADO AS DATE),@CNSCXC FROM #FACTU

      UPDATE RPDX SET VALOR10=CASE WHEN  EXISTS( SELECT 1 FROM PRI WHERE FECHA_INI<=RPDX.FECHA1 AND FECHA_FIN>=RPDX.FECHA1 AND(CERRADO=1 OR CERRADO_CARTERA=1)) 
                                          OR NOT EXISTS(SELECT 2 FROM PRI WHERE FECHA_INI<=RPDX.FECHA1 AND FECHA_FIN>=RPDX.FECHA1 )
                                          THEN 1 ELSE  0 END
      WHERE CNS=@CNSRPDX
      
      SELECT @CANTI=COUNT(*)
      FROM RPDX
      WHERE CNS=@CNSRPDX
      AND VALOR10=1


      SELECT 'OK'OK,@CNSRPDX CNSRPDX,ERRADOS=@CANTI
      RETURN
   END 
   IF @METODO='BORRAR_RPDX'     
   BEGIN         
      SELECT @CNSRPDX=CNSRPDX      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSRPDX  VARCHAR(20)   '$.CNSRPDX' 
      )
      DELETE RPDX WHERE CNS=@CNSRPDX
     
     SELECT 'OK'OK
     RETURN
   END  

   IF @METODO = 'PRESUPUESTO_FCXC'
   BEGIN
      SELECT @CNSCXC = CNSCXC,
             @IDSEDEF = IDSEDE
      FROM   OPENJSON(@PARAMETROS)
      WITH (
         CNSCXC VARCHAR(20) '$.CNSCXC',
         IDSEDE VARCHAR(5)  '$.IDSEDE'
      )

      IF COALESCE(@CNSCXC, '') = ''
      BEGIN
         SELECT 'KO' KO, 'Debe indicar CNSCXC' ERROR
         RETURN
      END

      IF NOT EXISTS (SELECT 1 FROM FCXC WHERE CNSCXC = @CNSCXC)
      BEGIN
         SELECT 'KO' KO, 'Cuenta de cobro no encontrada' ERROR
         RETURN
      END

      IF NOT EXISTS (SELECT 1 FROM FCXCD WHERE CNSCXC = @CNSCXC)
      BEGIN
         SELECT 'KO' KO, 'La cuenta de cobro no tiene facturas en el detalle' ERROR
         RETURN
      END

      SELECT @MSEDE = MSEDE,
             @IDSEDEF = CASE WHEN COALESCE(@IDSEDEF, '') <> '' THEN @IDSEDEF ELSE IDSEDE END
      FROM   FCXC
      WHERE  CNSCXC = @CNSCXC

      IF @MSEDE = 1 AND COALESCE(@IDSEDEF, '') <> ''
      BEGIN
         SELECT @IDSEDE = @IDSEDEF
      END
      ELSE
      BEGIN
         SELECT @IDSEDE = IDSEDE
         FROM   FCXC
         WHERE  CNSCXC = @CNSCXC
      END

      IF COALESCE(@IDSEDE, '') = ''
      BEGIN
         SELECT 'KO' KO, 'Debe indicar IDSEDE' ERROR
         RETURN
      END

      IF COALESCE(DBO.FNK_VALORVARIABLE('PRESUP_CCOSTO'), '') = ''
      BEGIN
         SELECT 'KO' KO, 'No está configurada la variable PRESUP_CCOSTO (centro de costo presupuesto)' ERROR
         RETURN
      END

      IF COALESCE(DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO'), '') = ''
      BEGIN
         SELECT 'KO' KO, 'No está configurada la variable PRESUP_TIPORECO (tipo de reconocimiento). Valor esperado: CUENTAC' ERROR
         RETURN
      END

      IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO') <> 'CUENTAC'
      BEGIN
         SELECT 'KO' KO, 'PRESUP_TIPORECO debe ser CUENTAC para enviar facturas desde CxC' ERROR
         RETURN
      END

      INSERT INTO @TBLERRORES(ERROR)
      SELECT CONCAT(
                'Factura ',
                FTR.N_FACTURA,
                ' (fecha ',
                CONVERT(VARCHAR(10), FTR.F_FACTURA, 103),
                '): no existe presupuesto PTPTO vigente (FECHAINI/FECHAFIN) para esa fecha'
             )
      FROM   FCXCD
      INNER JOIN FTR ON FTR.N_FACTURA = FCXCD.N_FACTURA
      WHERE  FCXCD.CNSCXC = @CNSCXC
      AND    NOT EXISTS (
                SELECT 1
                FROM   PTPTO
                WHERE  PTPTO.FECHAINI <= FTR.F_FACTURA
                AND    PTPTO.FECHAFIN >= FTR.F_FACTURA
             )

      IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END

      BEGIN TRY
         DECLARE curFactPpto CURSOR LOCAL FAST_FORWARD FOR
            SELECT FCXCD.N_FACTURA
            FROM   FCXCD
            WHERE  FCXCD.CNSCXC = @CNSCXC
            ORDER BY FCXCD.N_FACTURA ASC

         OPEN curFactPpto
         FETCH NEXT FROM curFactPpto INTO @N_FACTURA

         WHILE @@FETCH_STATUS = 0
         BEGIN
            EXEC DBO.SPK_ENTREGA_FACTURA_PTTO
                 @N_FACTURA = @N_FACTURA,
                 @IDSEDE    = @IDSEDE

            IF NOT EXISTS (
               SELECT 1
               FROM   FTR
               WHERE  N_FACTURA = @N_FACTURA
               AND    COALESCE(ENPRESUPUESTO, 0) = 1
            )
            BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT CONCAT('La factura ', @N_FACTURA, ' no quedó en presupuesto. Revise PTPTO vigente, rubro del plan (PLN.RUBRO) y variables PRESUP_CCOSTO / PRESUP_TIPORECO=CUENTAC')
            END

            FETCH NEXT FROM curFactPpto INTO @N_FACTURA
         END

         CLOSE curFactPpto
         DEALLOCATE curFactPpto

         IF (SELECT COUNT(*) FROM @TBLERRORES) = 0
         BEGIN
            UPDATE FCXC
            SET    ENPRESUPUESTO = 1
            WHERE  CNSCXC = @CNSCXC
         END
      END TRY
      BEGIN CATCH
         IF CURSOR_STATUS('local', 'curFactPpto') >= 0
         BEGIN
            IF CURSOR_STATUS('local', 'curFactPpto') = 1
               CLOSE curFactPpto
            DEALLOCATE curFactPpto
         END

         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH

      IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK
      RETURN
   END
END

