CREATE OR ALTER PROCEDURE DBO.SPQ_CPNT_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY           INT 
       ,@PROCESO            VARCHAR(20)    ,@CPNT    NVARCHAR(MAX)
              ,@CODIGO     VARCHAR(20)
       ,@DESCRIPCION     VARCHAR(500)
       ,@CUENTA     VARCHAR(16)
       ,@MODULO     VARCHAR(6)
       ,@TIPORESPUESTA     VARCHAR(1)
       ,@HOMOLOGODIANDB     VARCHAR(3)
       ,@HOMOLOGODIANCR     VARCHAR(3)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_CPNT_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'CRUDCPNT'
   BEGIN
      PRINT 'CRUDCPNT'
      SELECT @CPNT  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      
      SELECT @PROCESO     = JSON_VALUE(@CPNT ,'$.PROCESO')
      --Leo Campos enviados y los coloco en las variables respectivas
      SELECT @CODIGO = JSON_VALUE(@CPNT , '$.CODIGO' )
      SELECT @DESCRIPCION = JSON_VALUE(@CPNT , '$.DESCRIPCION' )
      SELECT @CUENTA = JSON_VALUE(@CPNT , '$.CUENTA' )
      SELECT @MODULO = JSON_VALUE(@CPNT , '$.MODULO' )
      SELECT @TIPORESPUESTA = JSON_VALUE(@CPNT , '$.TIPORESPUESTA' )
      SELECT @HOMOLOGODIANDB = JSON_VALUE(@CPNT , '$.HOMOLOGODIANDB' )
      SELECT @HOMOLOGODIANCR = JSON_VALUE(@CPNT , '$.HOMOLOGODIANCR' )

      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'
         BEGIN TRY
			INSERT INTO @TBLERRORES(ERROR) 
			SELECT 'EL CONCEPTO DE NOTA YA EXISTE'
			WHERE EXISTS (SELECT 1 FROM CPNT WHERE CODIGO = @CODIGO)

			IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
			BEGIN
				INSERT INTO CPNT(CODIGO,DESCRIPCION,CUENTA,MODULO,TIPORESPUESTA,HOMOLOGODIANDB,HOMOLOGODIANCR)
				SELECT @CODIGO,@DESCRIPCION,@CUENTA,@MODULO,@TIPORESPUESTA,@HOMOLOGODIANDB,@HOMOLOGODIANCR
				SELECT @IDENTITY = SCOPE_IDENTITY()
			END
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK ,@IDENTITY CNS 
         RETURN
      END

      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         BEGIN TRY
            UPDATE CPNT SET
                    CODIGO = @CODIGO,DESCRIPCION = @DESCRIPCION,CUENTA = @CUENTA,MODULO = @MODULO,TIPORESPUESTA = @TIPORESPUESTA,HOMOLOGODIANDB = @HOMOLOGODIANDB,HOMOLOGODIANCR = @HOMOLOGODIANCR
            WHERE CODIGO = @CODIGO
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END

	  IF UPPER(@PROCESO) = 'ELIMINAR'
		BEGIN
			PRINT 'ELIMINAR'
			BEGIN TRY
				IF COALESCE(@CODIGO,'')=''
				INSERT INTO @TBLERRORES(ERROR) 
				SELECT 'EL CODIGO DEL CONCEPTO DE NOTA ES OBLIGATORIO'

				IF(SELECT COUNT(*) FROM @TBLERRORES) <=0
				BEGIN
					DELETE FROM CPNT WHERE CODIGO = @CODIGO
				END		
			END TRY

			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH

			IF(SELECT COUNT(*) FROM @TBLERRORES) >0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

			SELECT 'OK' OK
			RETURN
		END
      RETURN
   END
END


