CREATE OR ALTER PROCEDURE DBO.SPK_DELSERCAP
    @CNSFTR      VARCHAR(20),
    @N_CUOTA     INT,
    @IDTERCERO   VARCHAR(20),
    @IDPLAN      VARCHAR(6),
    @FECHAINI    DATETIME,
    @FECHAFIN    DATETIME,
    @PROCEDENCIA VARCHAR(4),
    @NOADMISION  VARCHAR(20) = NULL,
    @IDSEDE      VARCHAR(6) = NULL
WITH ENCRYPTION
AS
DECLARE @N_FACTURA  VARCHAR(20)
        ,@COPAGOS_CP DECIMAL(14,2)
        ,@COPAGOPROP BIT
        ,@MODERADORA DECIMAL(14,2)
BEGIN
    SELECT @N_FACTURA = N_FACTURA, @COPAGOPROP = COALESCE(COPAPROPIO, 0)
    FROM FTR
    WHERE CNSFCT = @CNSFTR

    PRINT 'Retirando Servicios de la Factura No. ' + @N_FACTURA + ' PROCEDENCIA ' + @PROCEDENCIA

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'HADM'
    BEGIN
        UPDATE HPRED SET FACTURADA = 0, N_FACTURA = ''
        FROM HPRED
        INNER JOIN FTRDC A ON HPRED.NOPRESTACION = A.NOPRESTACION AND HPRED.NOITEM = A.NOITEM
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'HADM'
        AND COALESCE(HPRED.N_FACTURA, '') = @N_FACTURA

        DELETE HADMF
        FROM HADMF
        INNER JOIN FTRDC A ON HADMF.NOADMISION = A.NOADMISION
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'HADM'
        AND HADMF.N_FACTURA = @N_FACTURA
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'AUT'
    BEGIN
        UPDATE AUTD SET FACTURADA = 0, N_FACTURA = ''
        FROM AUTD
        INNER JOIN FTRDC A ON AUTD.IDAUT = A.NOPRESTACION AND AUTD.NO_ITEM = A.NOITEM
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'AUT'

        UPDATE AUT SET FACTURADA = 0, N_FACTURA = ''
        FROM AUT
        INNER JOIN FTRDC A ON AUT.IDAUT = A.NOPRESTACION
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'AUT'
        AND NOT EXISTS (
            SELECT 1 FROM AUTD
            WHERE AUTD.IDAUT = AUT.IDAUT
            AND COALESCE(AUTD.FACTURADA, 0) = 1
            AND COALESCE(AUTD.N_FACTURA, '') <> ''
        )
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'CIT'
    BEGIN
        UPDATE CIT SET FACTURADA = 0, N_FACTURA = ''
        FROM CIT
        INNER JOIN FTRDC A ON CIT.CONSECUTIVO = A.NOPRESTACION
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'CIT'
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'ONCO'
    BEGIN
        UPDATE HCATDIMOV SET FACTURADA = 0, N_FACTURA = ''
        FROM HCATDIMOV
        INNER JOIN FTRDC A ON HCATDIMOV.CONSECUTIVOCIT = A.NOADMISION AND HCATDIMOV.ID = A.NOITEM
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'ONCO'

        UPDATE CIT SET FACTURADA = 0, N_FACTURA = ''
        FROM CIT
        INNER JOIN FTRDC A ON CIT.CONSECUTIVO = A.NOPRESTACION
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'ONCO'
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'APLIM'
    BEGIN
        UPDATE CIT SET FACTURADA = 0, N_FACTURA = ''
        FROM CIT
        INNER JOIN FTRDC A ON CIT.CONSECUTIVO = A.NOPRESTACION
        WHERE A.CNSFTR = @CNSFTR
        AND A.N_CUOTA = @N_CUOTA
        AND A.PROCEDENCIA = 'APLIM'
    END

    IF @PROCEDENCIA = 'TODA' OR @PROCEDENCIA = 'INV'
    BEGIN
        UPDATE IMOV
        SET FACTURADA = 0,
            N_FACTURA = '',
            NODOCUMENTO = CASE WHEN COALESCE(IMOV.NODOCUMENTO, '') = @N_FACTURA THEN '' ELSE IMOV.NODOCUMENTO END,
            MARCACONT = 0,
            CNSITFC = NULL
        FROM IMOV
        INNER JOIN (
            SELECT DISTINCT COALESCE(A.NOPRESTACION, A.NOADMISION) AS CNSMOV
            FROM FTRDC A
            WHERE A.CNSFTR = @CNSFTR
              AND A.N_CUOTA = @N_CUOTA
              AND A.PROCEDENCIA = 'INV'
        ) X ON IMOV.CNSMOV = X.CNSMOV
    END

    DELETE FTRDC
    WHERE CNSFTR = @CNSFTR
    AND N_CUOTA = @N_CUOTA
    AND (@PROCEDENCIA = 'TODA' OR PROCEDENCIA = @PROCEDENCIA)
    AND FECHA >= @FECHAINI
    AND FECHA < @FECHAFIN + 1
    AND NOADMISION = CASE WHEN COALESCE(@NOADMISION, '') = '' THEN NOADMISION ELSE @NOADMISION END
    AND COALESCE(IDSEDE, '') = CASE WHEN COALESCE(@IDSEDE, '') = '' THEN COALESCE(IDSEDE, '') ELSE @IDSEDE END

    UPDATE FTRD SET VLR_COPAGOS = CASE WHEN DBO.FNK_VALORVARIABLE('REDONDEOFTRFINANC') = 'SI'
        THEN ROUND(V.VALORCOPAGO, 0) ELSE V.VALORCOPAGO END
    FROM (SELECT VALORCOPAGO = SUM(VLR_COPAGO) FROM FTRDC WHERE CNSFTR = @CNSFTR AND N_CUOTA = @N_CUOTA) V
    WHERE CNSFTR = @CNSFTR
    AND N_CUOTA = @N_CUOTA

    SELECT @COPAGOS_CP = SUM(COALESCE(COPAGOS_CP, 0)) FROM FTRD WHERE CNSFTR = @CNSFTR

    UPDATE FTR SET CP_VLR_SERVICIOS = CASE WHEN DBO.FNK_VALORVARIABLE('REDONDEOFTRFINANC') = 'SI'
            THEN ROUND(V.VALORTOTAL, 0) ELSE V.VALORTOTAL END,
        CP_VLR_COPAGOS = CASE WHEN DBO.FNK_VALORVARIABLE('REDONDEOFTRFINANC') = 'SI'
            THEN ROUND(CASE WHEN FTR.COPAPROPIO = 1 THEN @COPAGOS_CP ELSE V.VALORCOPAGO END, 0)
            ELSE CASE WHEN FTR.COPAPROPIO = 1 THEN @COPAGOS_CP ELSE V.VALORCOPAGO END END,
        CP_VLR_PAGCOMP = CASE WHEN DBO.FNK_VALORVARIABLE('REDONDEOFTRFINANC') = 'SI'
            THEN ROUND(V.VALORPCOMP, 0) ELSE V.VALORPCOMP END,
        VALORCOPAGO = CASE WHEN DBO.FNK_VALORVARIABLE('REDONDEOFTRFINANC') = 'SI'
            THEN ROUND(V.VALORCOPAGO, 0) ELSE V.VALORCOPAGO END
    FROM (
        SELECT VALORTOTAL = SUM(VALORTOTAL),
               VALORCOPAGO = SUM(VLR_COPAGO),
               VALORPCOMP = SUM(VLR_PAGCOMP)
        FROM FTRDC
        WHERE CNSFTR = @CNSFTR
    ) V
    WHERE CNSFCT = @CNSFTR

    IF DBO.FNK_VALORVARIABLE('DESCCOP_CAPI') = 'SI'
    BEGIN
        UPDATE FTR SET VR_TOTAL = IIF(
            FTR.COPAPROPIO = 1,
            VALORSERVICIOS - COALESCE(CP_VLR_COPAGOS, 0),
            CASE WHEN DBO.FNK_VALORVARIABLE('REDONDEOFTRFINANC') = 'SI'
                THEN ROUND((SELECT SUM(VALOR * CANTIDAD) - SUM(VLR_COPAGOS) FROM FTRD WHERE CNSFTR = @CNSFTR), 0)
                ELSE (SELECT SUM(VALOR * CANTIDAD) - SUM(VLR_COPAGOS) FROM FTRD WHERE CNSFTR = @CNSFTR)
            END
        )
        WHERE CNSFCT = @CNSFTR
    END
END

