IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_SEPARA_SER_REL_AUT' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_SEPARA_SER_REL_AUT
END
GO
CREATE PROCEDURE DBO.SPK_SEPARA_SER_REL_AUT 
@IDAUT  VARCHAR(20)
WITH ENCRYPTION
AS  
DECLARE @NO_ITEM INT
DECLARE @IDSERVICIO VARCHAR(20)
DECLARE @IDSERVICIOR VARCHAR(20)
DECLARE @IDTERPART   VARCHAR(20)
DECLARE @IDPLANPART  VARCHAR(6)
DECLARE @NVO_ITEM INT
DECLARE @VALORSER DECIMAL(14,2)
DECLARE @VALORSERR DECIMAL(14,2)
DECLARE @IDTERCEROCA VARCHAR(20)
DECLARE @IDPLANCA    VARCHAR(6)
DECLARE @NOSEPARAR   SMALLINT
BEGIN 
   
   SELECT @IDTERPART=DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR'),  @IDPLANPART=DBO.FNK_VALORVARIABLE('IDPLANPART')

   SELECT 
		IDAUT ,NO_ITEM ,IDSERVICIO ,CANTIDAD ,VALOR ,VALORCOPAGO ,VALORCOPAGOCOSTO ,VALOREXCEDENTE 
		,VALORTOTALCOSTO ,IDPLAN ,IMPRESO ,AUTORIZADO ,COMENTARIOS ,PCOBERTURA ,OBS ,NORDEN 
		,CCOSTO ,CODIGOCPCJ ,MARCAPAGO ,NOAUTORIZEXT ,ESDELAB ,ENLAB ,IDTERCEROCA ,IDCONTRATO 
		,FACTURADA ,N_FACTURA ,CNSFCT ,AQUIENCOBRO ,MARCACOPAGOORDEN ,VALORPROV ,PCOSTO ,ITFC 
		,CNSITFC ,SYS_COMPUTERNAME ,NOCOBRABLE ,MDOSIFICACION ,CANTIDIA ,DIAS ,FRECUENCIA ,CODCUPS ,
      POSOLOGIA ,SINCRONIZADO ,APOYODG_AMBITO ,CITAAUTORIZADA ,DOSISAPL ,DURACIONTTOF ,DURACIONTTOC ,CLASEPOSOLOGIA ,
      MARCA ,USUARIOMARCA ,NUM_ORDEN ,PROCESADA ,PRIORIDAD ,HOMOLOGO ,IDSERVICIOH ,CANTIDADH 
		,VALORHOMO ,NO_ITEMH ,N_FACTURAORI ,DESCUENTO ,TIPODTO ,CNSFMED ,F_INGLAB ,F_SALILAB 
		,IDARTICULO ,IMPORTADO
   INTO #TX 
   FROM AUTD 
   WHERE IDAUT=@IDAUT  --AND NO_ITEM=@NO_ITEM

   DELETE #TX

	 DECLARE SERREL_CURSOR CURSOR FOR   
   SELECT AUTD.NO_ITEM,AUTD.IDSERVICIO,SERR.IDSERVICIOREL,IDTERCEROCA,IDPLAN,COALESCE(AUTD.CITAAUTORIZADA,0)
      FROM AUTD INNER JOIN SER ON AUTD.IDSERVICIO=SER.IDSERVICIO
                LEFT JOIN SERR ON SER.IDSERVICIO=SERR.IDSERVICIO 
      WHERE AUTD.IDAUT=@IDAUT
      AND COALESCE(HOMOLOGO,0)=0   
  
    OPEN SERREL_CURSOR  
    FETCH NEXT FROM SERREL_CURSOR 
    INTO @NO_ITEM,@IDSERVICIO,@IDSERVICIOR,@IDTERCEROCA,@IDPLANCA,@NOSEPARAR
    WHILE @@FETCH_STATUS = 0  
    BEGIN  
        PRINT '@IDSERVICIO='+@IDSERVICIO
        PRINT '@IDSERVICIOR='+@IDSERVICIOR

        IF COALESCE(@IDSERVICIOR,'')<>'' AND @NOSEPARAR=0
        BEGIN
           SELECT @NVO_ITEM=MAX(NO_ITEM)+1 FROM #TX WHERE IDAUT=@IDAUT
           IF COALESCE(@NVO_ITEM,0)=0
           BEGIN 
              SELECT @NVO_ITEM=MAX(NO_ITEM)+1 FROM AUTD WHERE IDAUT=@IDAUT
           END

           INSERT INTO #TX
           SELECT 
            IDAUT ,NO_ITEM ,IDSERVICIO ,CANTIDAD ,VALOR ,VALORCOPAGO ,VALORCOPAGOCOSTO ,VALOREXCEDENTE 
		    ,VALORTOTALCOSTO ,IDPLAN ,IMPRESO ,AUTORIZADO ,COMENTARIOS ,PCOBERTURA ,OBS ,NORDEN 
		    ,CCOSTO ,CODIGOCPCJ ,MARCAPAGO ,NOAUTORIZEXT ,ESDELAB ,ENLAB ,IDTERCEROCA ,IDCONTRATO 
		    ,FACTURADA ,N_FACTURA ,CNSFCT ,AQUIENCOBRO ,MARCACOPAGOORDEN ,VALORPROV ,PCOSTO ,ITFC 
		    ,CNSITFC ,SYS_COMPUTERNAME ,NOCOBRABLE ,MDOSIFICACION ,CANTIDIA ,DIAS ,FRECUENCIA ,CODCUPS ,
          POSOLOGIA ,SINCRONIZADO ,APOYODG_AMBITO ,CITAAUTORIZADA ,DOSISAPL ,DURACIONTTOF ,DURACIONTTOC ,CLASEPOSOLOGIA ,
          MARCA ,USUARIOMARCA ,NUM_ORDEN ,PROCESADA ,PRIORIDAD ,HOMOLOGO ,IDSERVICIOH ,CANTIDADH 
		    ,VALORHOMO ,NO_ITEMH ,N_FACTURAORI ,DESCUENTO ,TIPODTO ,CNSFMED ,F_INGLAB ,F_SALILAB 
		    ,IDARTICULO ,IMPORTADO
           FROM AUTD WHERE IDAUT=@IDAUT AND NO_ITEM=@NO_ITEM
        END
      --SELECT * FROM #TX

      SELECT TOP 1  @VALORSER=ROUND(COALESCE(VALOR,0),-2) 
      FROM SERTOT1
      WHERE IDTERCERO=@IDTERCEROCA
      AND IDPLAN=@IDPLANCA
      AND IDSERVICIO=@IDSERVICIOR
      AND FECHAFIN>GETDATE()
      AND FECHAFINFD>GETDATE()
      AND FECHAINI<=GETDATE()
      AND FECHAINIFD<=GETDATE()

      SELECT TOP 1  @VALORSERR=ROUND(COALESCE(VALOR,0),-2)
      FROM SERTOT1
      WHERE IDTERCERO=@IDTERPART
      AND IDPLAN=@IDPLANPART
      AND IDSERVICIO=@IDSERVICIO
      AND FECHAFIN>GETDATE()
      AND FECHAFINFD>GETDATE()
      AND FECHAINI<=GETDATE()
      AND FECHAINIFD<=GETDATE()
      
      SELECT @VALORSER=COALESCE(@VALORSER,0),@VALORSERR=COALESCE(@VALORSERR,0)

      IF COALESCE(@IDSERVICIOR,'')<>'' AND @NOSEPARAR=0
      BEGIN
         PRINT 'ACTUALIZO #TX'
         UPDATE #TX SET NO_ITEM=@NVO_ITEM,IDTERCEROCA=@IDTERPART,IDPLAN=@IDPLANPART,IDSERVICIO=@IDSERVICIO,
         VALOR=@VALORSERR-@VALORSER,VALOREXCEDENTE=((@VALORSERR-@VALORSER)*CANTIDAD),VALORCOPAGO=0
         WHERE IDAUT=@IDAUT
         AND NO_ITEM=@NO_ITEM

         UPDATE AUTD SET IDSERVICIO=@IDSERVICIOR,IDSERVICIOH=@IDSERVICIO,NO_ITEMH=@NVO_ITEM,HOMOLOGO=1,VALORHOMO=@VALORSERR,
         VALOR=@VALORSER, VALOREXCEDENTE=(@VALORSER*COALESCE(CANTIDAD,0))-COALESCE(VALORCOPAGO,0)
         WHERE AUTD.IDAUT=@IDAUT AND NO_ITEM=@NO_ITEM
      END
      ELSE
      BEGIN 
         SELECT TOP 1  @VALORSERR=ROUND(VALOR,-2)
         FROM SERTOT1
         WHERE IDTERCERO=@IDTERPART
         AND IDPLAN=@IDPLANPART
         AND IDSERVICIO=@IDSERVICIO
         AND FECHAFIN>GETDATE()
         AND FECHAFINFD>GETDATE()
         AND FECHAINI<=GETDATE()
         AND FECHAINIFD<=GETDATE()

         UPDATE AUTD SET IDSERVICIOH=@IDSERVICIO,NO_ITEMH=NO_ITEM,HOMOLOGO=1,VALORHOMO=VALOR,VALORCOPAGO=0,
         VALOR=@VALORSERR, VALOREXCEDENTE=(@VALORSERR*CANTIDAD),IDTERCEROCA=@IDTERPART,IDPLAN=@IDPLANPART
         WHERE AUTD.IDAUT=@IDAUT AND NO_ITEM=@NO_ITEM
      END

        FETCH NEXT FROM SERREL_CURSOR INTO @NO_ITEM,@IDSERVICIO,@IDSERVICIOR,@IDTERCEROCA,@IDPLANCA,@NOSEPARAR
        END  
  
    CLOSE SERREL_CURSOR  
    DEALLOCATE SERREL_CURSOR 

    UPDATE AUT SET VALORCOPAGO=(SELECT SUM(COALESCE(VALORCOPAGO,0)) FROM AUTD WHERE IDAUT=@IDAUT) WHERE IDAUT=@IDAUT
   
    INSERT INTO AUTD(IDAUT ,NO_ITEM ,IDSERVICIO ,CANTIDAD ,VALOR ,VALORCOPAGO ,VALORCOPAGOCOSTO ,VALOREXCEDENTE 
		,VALORTOTALCOSTO ,IDPLAN ,IMPRESO ,AUTORIZADO ,COMENTARIOS ,PCOBERTURA ,OBS ,NORDEN 
		,CCOSTO ,CODIGOCPCJ ,MARCAPAGO ,NOAUTORIZEXT ,ESDELAB ,ENLAB ,IDTERCEROCA ,IDCONTRATO 
		,FACTURADA ,N_FACTURA ,CNSFCT ,AQUIENCOBRO ,MARCACOPAGOORDEN ,VALORPROV ,PCOSTO ,ITFC 
		,CNSITFC ,SYS_COMPUTERNAME ,NOCOBRABLE ,MDOSIFICACION ,CANTIDIA ,DIAS ,FRECUENCIA ,CODCUPS ,
      POSOLOGIA ,SINCRONIZADO ,APOYODG_AMBITO ,CITAAUTORIZADA ,DOSISAPL ,DURACIONTTOF ,DURACIONTTOC ,CLASEPOSOLOGIA ,
      MARCA ,USUARIOMARCA ,NUM_ORDEN ,PROCESADA ,PRIORIDAD ,HOMOLOGO ,IDSERVICIOH ,CANTIDADH 
		,VALORHOMO ,NO_ITEMH ,N_FACTURAORI ,DESCUENTO ,TIPODTO ,CNSFMED ,F_INGLAB ,F_SALILAB 
		,IDARTICULO ,IMPORTADO)
    SELECT 
        IDAUT ,NO_ITEM ,IDSERVICIO ,CANTIDAD ,VALOR ,VALORCOPAGO ,VALORCOPAGOCOSTO ,VALOREXCEDENTE 
		,VALORTOTALCOSTO ,IDPLAN ,IMPRESO ,AUTORIZADO ,COMENTARIOS ,PCOBERTURA ,OBS ,NORDEN 
		,CCOSTO ,CODIGOCPCJ ,MARCAPAGO ,NOAUTORIZEXT ,ESDELAB ,ENLAB ,IDTERCEROCA ,IDCONTRATO 
		,FACTURADA ,N_FACTURA ,CNSFCT ,AQUIENCOBRO ,MARCACOPAGOORDEN ,VALORPROV ,PCOSTO ,ITFC 
		,CNSITFC ,SYS_COMPUTERNAME ,NOCOBRABLE ,MDOSIFICACION ,CANTIDIA ,DIAS ,FRECUENCIA ,CODCUPS ,
      POSOLOGIA ,SINCRONIZADO ,APOYODG_AMBITO ,CITAAUTORIZADA ,DOSISAPL ,DURACIONTTOF ,DURACIONTTOC ,CLASEPOSOLOGIA , 
      MARCA ,USUARIOMARCA ,NUM_ORDEN ,PROCESADA ,PRIORIDAD ,HOMOLOGO ,IDSERVICIOH ,CANTIDADH 
		,VALORHOMO ,NO_ITEMH ,N_FACTURAORI ,DESCUENTO ,TIPODTO ,CNSFMED ,F_INGLAB ,F_SALILAB 
		,IDARTICULO ,IMPORTADO 
    FROM #TX

    DROP TABLE #TX
END



