CREATE OR ALTER PROCEDURE DBO.SPQ_FTR_MASIVA_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS     NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO     VARCHAR(12)
       ,@GRUPO          VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A           INT
       ,@IDENTITY       INT            ,@PROCESO          VARCHAR(20)   
       ,@DATOS          NVARCHAR(MAX)  ,@ACCION           VARCHAR(1)      ,@REGISTRO      NVARCHAR(MAX)
       ,@NOAUT          VARCHAR(16)    ,@CNSFACT          VARCHAR(20)     ,@FECHAINI      DATE          ,@FECHAFIN        DATE
       ,@IDTERCERO      VARCHAR(20)    ,@IDPLAN           VARCHAR(6)      ,@IDSEDEF       VARCHAR(7)    ,@PROCEDENCIA     VARCHAR(20)
       ,@IDSEDE         VARCHAR(7)     ,@F_FACTURA        DATETIME        ,@COMPANIA      VARCHAR(2)    ,@NIT             VARCHAR(20)
       ,@FFACTURA       DATE           ,@IDAUT            VARCHAR(13)     ,@NUMCONCNSFACT INT = 0       ,@NUMCONCNSFACT2  INT = 0
	   ,@NUMCONCNSFACT_NEG INT  		,@NUMCONCNSFACT_MED INT 
       ,@PROCESOFACTMAS INT            ,@FECHAINIFIL      DATE            ,@FECHAFINFIL   DATE          ,@OBSERVACION     VARCHAR(MAX)
       ------- nuevas de jose manuel
       ,@CONSECUTIVO VARCHAR(20)           ,@DPR VARCHAR(20)                 ,@TIPOFAC VARCHAR(2)
       ,@N_fACTURA VARCHAR(20)             ,@FECHAFACT DATETIME              ,@NOITEM SMALLINT   
       ,@IDAFILIADO VARCHAR(20)            ,@ADDDEL VARCHAR(20)              ,@IDAUTD VARCHAR(20),	@NOAUTORIZACION VARCHAR(45)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
      
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A FTR_MASIVA_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'MARCAAUT_FTR'
   BEGIN
      PRINT 'MARCAAUT_FTR'
      SELECT @DATOS=DATOS,@ACCION=ACCION, @REGISTRO=REGISTRO
		FROM   OPENJSON (@PARAMETROS)
		WITH   (
			DATOS      NVARCHAR(MAX)     AS JSON,
			ACCION     VARCHAR(1)       '$.ACCION',
         REGISTRO   NVARCHAR(MAX)     AS JSON
			)
      IF @ACCION = '3'
      BEGIN
         PRINT 'ESTOY MARCANDO INDIVIDUAL AUT'
        
         SELECT @NOAUT = JSON_VALUE(@REGISTRO, '$.NOAUT')
         SELECT @CNSFACT=''
			SELECT @SEDE=IDSEDE FROM USUSU WHERE USUARIO=@USUARIO

         IF (SELECT COUNT(1) FROM AUT WHERE NOAUT = @NOAUT AND COALESCE(VALORTOTAL,0)<=0 ) > 0
         BEGIN
            INSERT INTO @TBLERRORES (ERROR ) SELECT 'Sin Valor'
            SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
         END

			--EXEC SPK_GENCONSECUTIVO '01',@SEDE, '@RPDX', @CNSFACT OUTPUT  
			--SELECT @CNSFACT = @SEDE + REPLACE(SPACE(8 - LEN(@CNSFACT))+LTRIM(RTRIM(@CNSFACT)),SPACE(1),0)     
         BEGIN TRY 
            IF (SELECT COALESCE(MARCAFAC,0) FROM AUT WHERE NOAUT = @NOAUT)= 0
            BEGIN
				IF (SELECT COALESCE(FACTURADA,0) FROM AUT WHERE NOAUT = @NOAUT) =2 --AGREGAR CVUADNO LA FACTURA ES PARCIAL EN AUT (NAREN)
				BEGIN
					UPDATE AUT SET MARCAFAC = 1 ,CNSFACT = @USUARIO WHERE NOAUT = @NOAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 2 AND COALESCE (MARCAFAC,0) =0  --(NAREN)
				END
				ELSE
				BEGIN
					UPDATE AUT SET MARCAFAC = 1 ,CNSFACT = @USUARIO WHERE NOAUT = @NOAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 
					UPDATE AUT SET CNSFACT = NULL  WHERE NOAUT = @NOAUT AND COALESCE(MARCAFAC,0) = 0 
				END
			END
            ELSE 
            BEGIN
               UPDATE AUT SET MARCAFAC = 0 ,CNSFACT = NULL WHERE NOAUT = @NOAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 --AND CNSFACT = @USUARIO
            END
         END TRY 
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH

			IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
         SELECT 'OK' OK
      END
      ELSE IF @ACCION = '4'
      BEGIN
         PRINT 'ESTOY MARCANDO INDIVIDUAL UNIFICADA'
         DECLARE @PROCEDENCIAFACTURACION VARCHAR(10)
         SELECT @PROCEDENCIAFACTURACION = JSON_VALUE(@REGISTRO,'$.PROCEDENCIAFACTURACION')
         PRINT '@PROCEDENCIAFACTURACION='+@PROCEDENCIAFACTURACION
         IF @PROCEDENCIAFACTURACION = 'CIT'
         BEGIN
            PRINT 'INICIO MARCACION UNIFICADA UNA CITA'
            SELECT @IDAUT = JSON_VALUE(@REGISTRO, '$.IDAUT')
            SELECT @CNSFACT=''
			   SELECT @SEDE=IDSEDE FROM USUSU WHERE USUARIO=@USUARIO

            IF (SELECT COUNT(1) FROM CIT WHERE CONSECUTIVO = @IDAUT AND COALESCE(VALORTOTAL,0)<=0 ) > 0
            BEGIN
               INSERT INTO @TBLERRORES (ERROR ) SELECT 'Sin Valor'
               SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
            END
			 IF EXISTS (SELECT 1 FROM CIT WHERE CONSECUTIVO = @IDAUT AND MARCAFAC = 1 AND CNSFACT <> @USUARIO)
            BEGIN
               INSERT INTO @TBLERRORES (ERROR ) SELECT 'Factura Marcada por otro usuario'
               SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
            END
            BEGIN TRY 
               IF (SELECT COALESCE(MARCAFAC,0) FROM CIT WHERE CONSECUTIVO = @IDAUT)= 0
               BEGIN
                  UPDATE CIT SET MARCAFAC = 1 ,CNSFACT = @USUARIO WHERE CONSECUTIVO = @IDAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 
                  UPDATE CIT SET CNSFACT = NULL  WHERE CONSECUTIVO = @IDAUT AND COALESCE(MARCAFAC,0) = 0 
               END
               ELSE 
               BEGIN
                  UPDATE CIT SET MARCAFAC = 0 ,CNSFACT = NULL WHERE CONSECUTIVO = @IDAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 --AND CNSFACT = @USUARIO
               END
            END TRY 
			   BEGIN CATCH
				   INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			   END CATCH

			   IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			   BEGIN
				   SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
			   END
            SELECT 'OK' OK
         END
         ELSE IF @PROCEDENCIAFACTURACION = 'AUT'
         BEGIN
            PRINT 'INICIO MARCACION UNIFICADA UN AUT'
            SELECT @NOAUT = JSON_VALUE(@REGISTRO, '$.NOAUT')
            SELECT @CNSFACT=''
			   SELECT @SEDE=IDSEDE FROM USUSU WHERE USUARIO=@USUARIO

            IF (SELECT COUNT(1) FROM AUT WHERE NOAUT = @NOAUT AND COALESCE(VALORTOTAL,0)<=0 ) > 0
            BEGIN
               INSERT INTO @TBLERRORES (ERROR ) SELECT 'Sin Valor'
               SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
            END
			IF EXISTS (SELECT 1 FROM AUT WHERE NOAUT = @NOAUT AND MARCAFAC = 1 AND CNSFACT <> @USUARIO)
            BEGIN
               INSERT INTO @TBLERRORES (ERROR ) SELECT 'Factura Marcada por otro usuario'
               SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
            END
            BEGIN TRY 
               IF (SELECT COALESCE(MARCAFAC,0) FROM AUT WHERE NOAUT = @NOAUT)= 0
               BEGIN
                  UPDATE AUT SET MARCAFAC = 1 ,CNSFACT = @USUARIO WHERE NOAUT = @NOAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 
                  UPDATE AUT SET CNSFACT = NULL  WHERE NOAUT = @NOAUT AND COALESCE(MARCAFAC,0) = 0 
               END
               ELSE 
               BEGIN
                  UPDATE AUT SET MARCAFAC = 0 ,CNSFACT = NULL WHERE NOAUT = @NOAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 --AND CNSFACT = @USUARIO
               END
            END TRY 
			   BEGIN CATCH
				   INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			   END CATCH

			   IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			   BEGIN
				   SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
			   END
            SELECT 'OK' OK

         END
      END
      ELSE 
      BEGIN
         SELECT @FECHAINI=F_INIMAS,@FECHAFIN=DATEADD(DAY,1,F_FINMAS),@IDTERCERO=IDTERMAS,
		          @IDPLAN=IDPLANMAS,@PROCEDENCIA=PROCE,@IDSEDEF=SEDEFMAS
		   FROM   OPENJSON (@DATOS)
		   WITH   (
			   F_INIMAS DATE          '$.F_INIMAS',
			   F_FINMAS DATE          '$.F_FINMAS',
			   IDTERMAS VARCHAR(20)   '$.IDTERMAS',
			   IDPLANMAS VARCHAR(20)  '$.IDPLANMAS',
			   PROCE VARCHAR(20)      '$.PROCE',
			   SEDEFMAS VARCHAR(20)   '$.SEDEFMAS'
            --,FACTURABLE BIT         '$.FACTURABLE'
            --,ESTADOFACTAUT SMALLINT '$.ESTADOFACT.value'
		   )
         PRINT '@FECHAINI='+CONVERT(VARCHAR,@FECHAINI)
         PRINT '@FECHAFIN='+CONVERT(VARCHAR,@FECHAFIN)
         PRINT '@IDTERCERO='+@IDTERCERO
         PRINT '@IDPLAN='+@IDPLAN
         PRINT '@IDSEDEF='+@IDSEDEF
         PRINT '@ACCION='+STR(@ACCION)
         IF @ACCION = 1
         BEGIN
            IF( 
                SELECT COUNT(*) --AUTD.IDAUT
                FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                WHERE  AUTD.IDTERCEROCA = @IDTERCERO
                AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINI 
                AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFIN
                AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
                AND    COALESCE(AUTD.FACTURADA,0) = 0      
                AND    COALESCE(AUTD.VALOR,0)>0 
                AND    COALESCE(AUT.FACTURABLE,0) = 1
                AND    COALESCE(AUT.MARCAFAC,0) = 0
                AND    AUT.ESTADO <> 'Anulada'
                --AND    COALESCE(CNSFACT,'') 
             ) <= 0
            BEGIN
               SELECT 'KO' OK,'No Existen Registros para ' + CASE WHEN @ACCION = 1 THEN 'Marcar' ELSE 'Desmarcar' END ERROR
			      RETURN
            END

            UPDATE AUT SET MARCAFAC = 1 , CNSFACT = @USUARIO
            FROM (
                     SELECT DISTINCT AUTD.IDAUT
                     FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                     WHERE  AUTD.IDTERCEROCA = @IDTERCERO
                     AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                     AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINI 
                     AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFIN
                     AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
                     AND    COALESCE(AUTD.FACTURADA,0) = 0      
                     AND    COALESCE(AUTD.VALOR,0)>0 
                     AND    COALESCE(AUT.FACTURABLE,0) = 1
                     AND    COALESCE(AUT.MARCAFAC,0) = 0
                     AND    AUT.ESTADO <> 'Anulada'
                 ) X
             WHERE  AUT.IDAUT = X.IDAUT

             SELECT 'OK' OK
         END
         ELSE IF @ACCION = 2
         BEGIN
            IF( 
                SELECT COUNT(*) --AUTD.IDAUT
                FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                WHERE  AUTD.IDTERCEROCA = @IDTERCERO
                AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINI 
                AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFIN
                AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
                AND    COALESCE(AUTD.FACTURADA,0) = 0      
                AND    COALESCE(AUTD.VALOR,0)>0 
                AND    COALESCE(AUT.FACTURABLE,0) = 1
                AND    COALESCE(AUT.MARCAFAC,0) = 1
                AND    AUT.ESTADO <> 'Anulada'
                AND    COALESCE(CNSFACT,'') = @USUARIO
             ) <= 0
            BEGIN
               SELECT 'KO' OK,'No Existen Registros para ' + CASE WHEN @ACCION = 1 THEN 'Marcar' ELSE 'Desmarcar' END ERROR
			      RETURN
            END
            UPDATE AUT SET MARCAFAC = 0  , CNSFACT = NULL
            FROM (
                     SELECT DISTINCT AUTD.IDAUT
                     FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                     WHERE  AUTD.IDTERCEROCA = @IDTERCERO
                     AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                     AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINI 
                     AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFIN
                     AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
                     AND    COALESCE(AUTD.FACTURADA,0) = 0      
                     AND    COALESCE(AUTD.VALOR,0)>0 
                     AND    COALESCE(AUT.FACTURABLE,0) = 1
                     AND    COALESCE(AUT.MARCAFAC,0) = 1
                     AND    AUT.ESTADO <> 'Anulada'
                     AND    COALESCE(CNSFACT,'') = @USUARIO
                 ) X
            WHERE  AUT.IDAUT = X.IDAUT

            SELECT 'OK' OK
         END
      END
      RETURN
   END
	IF @METODO = 'MARCATODO_UNI'
	BEGIN
		PRINT 'INICIO MARCACION / DESMARCACION UNIFICADA (CIT + AUT)'
		DECLARE @CMD VARCHAR(2048), @CONDICION VARCHAR(1024)

		SELECT @ACCION = ACCION, @CONDICION = CONDICION
		FROM OPENJSON(@PARAMETROS)
		WITH (
			CONDICION VARCHAR(1024) '$.WHERE',
			ACCION VARCHAR(50) '$.ACCION'
		)

		BEGIN TRY
			IF LOWER(@ACCION) = 'm'
			BEGIN
				PRINT 'Marcando todas las CIT y AUT seleccionadas'

				SELECT @CMD=' UPDATE CIT SET MARCAFAC = 1, CNSFACT = '''+@USUARIO+''' FROM CIT
				INNER JOIN VWQ_XFACTURAR_CE ON VWQ_XFACTURAR_CE.IDAUT=CIT.CONSECUTIVO AND VWQ_XFACTURAR_CE.PROCEDENCIAFACTURACION=''CIT''
				WHERE '+@CONDICION +' AND COALESCE(CIT.CNSFACT,'''')='''''

				EXEC (@CMD)

				SELECT @CMD=' UPDATE AUT SET MARCAFAC = 1, CNSFACT = '''+@USUARIO+''' FROM AUT
				INNER JOIN VWQ_XFACTURAR_CE ON VWQ_XFACTURAR_CE.IDAUT=AUT.IDAUT AND VWQ_XFACTURAR_CE.PROCEDENCIAFACTURACION=''AUT''
				WHERE '+@CONDICION+' AND COALESCE(AUT.CNSFACT,'''')='''''

				EXEC (@CMD)
			END

			-- DESMARCAR
			ELSE IF LOWER(@ACCION) = 'd'
			BEGIN
				-- CIT
				SELECT @CMD=' UPDATE CIT SET MARCAFAC = 0, CNSFACT = NULL FROM CIT
				INNER JOIN VWQ_XFACTURAR_CE ON VWQ_XFACTURAR_CE.IDAUT=CIT.CONSECUTIVO AND VWQ_XFACTURAR_CE.PROCEDENCIAFACTURACION=''CIT''
				WHERE '+@CONDICION +' AND COALESCE(CIT.CNSFACT,'''')= '''+@USUARIO+''''

				EXEC (@CMD)
				
				-- AUT
				SELECT @CMD=' UPDATE AUT SET MARCAFAC = 0, CNSFACT = NULL FROM AUT
				INNER JOIN VWQ_XFACTURAR_CE ON VWQ_XFACTURAR_CE.IDAUT=AUT.IDAUT AND VWQ_XFACTURAR_CE.PROCEDENCIAFACTURACION=''AUT''
				WHERE '+@CONDICION+' AND COALESCE(AUT.CNSFACT,'''')= '''+@USUARIO+''''
				EXEC (@CMD)
				
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) 
			SELECT ERROR_MESSAGE()
		END CATCH

		IF (SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		PRINT 'LLEGO AL OK'
		SELECT 'OK' OK
	END
   IF @METODO = 'FACTURAR_MASI'
   BEGIN
      DECLARE @PRESTACION VARCHAR(20)
		DECLARE @N_FACTURADEV  VARCHAR(20)
		SELECT @DATOS=DATOS,@ACCION=ACCION,@FFACTURA = FFACTURA ,@OBSERVACION = OBSERVACION
		FROM   OPENJSON (@PARAMETROS)
		WITH (
			DATOS       NVARCHAR(MAX) AS JSON,
			ACCION      SMALLINT     '$.ACCION',
         FFACTURA    DATE         '$.FFACTURA',
         OBSERVACION VARCHAR(MAX) '$.OBSERVACION'
		) 
		SELECT @FECHAINI=F_INIMAS ,@FECHAFIN   =F_FINMAS,@IDTERCERO=IDTERMAS,
		       @IDPLAN  =IDPLANMAS,@PROCEDENCIA=PROCE   ,@IDSEDEF  =SEDEFMAS
		FROM   OPENJSON (@DATOS)
		WITH   (
			F_INIMAS DATE          '$.F_INIMAS',
			F_FINMAS DATE          '$.F_FINMAS',
			IDTERMAS VARCHAR(20)   '$.IDTERMAS',
			IDPLANMAS VARCHAR(20)  '$.IDPLANMAS',
			PROCE VARCHAR(20)      '$.PROCE',
			SEDEFMAS VARCHAR(6)    '$.SEDEFMAS'
		)
      IF COALESCE(@FFACTURA,'') = ''
         SELECT @F_FACTURA=DBO.FNK_GETDATE()
      ELSE
         SELECT @F_FACTURA=@FFACTURA

		SELECT @COMPANIA='01',@NIT=NIT
		FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
		IF dbo.FNK_VALORVARIABLE('FACTSEDE')='SI'
		BEGIN
         IF @IDSEDEF = 'Todas'
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Escogio Todas las Sedes y esta IPS Tiene configurado Facturación por Sede'
			   SELECT 'KO' OK
			   SELECT ERROR FROM @TBLERRORES
			   RETURN
         END
         ELSE
			   SELECT @IDSEDE=@IDSEDEF
		END
		ELSE
			SELECT @IDSEDE=UBEQ.IDSEDE 
			FROM USUSU INNER JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME 
			WHERE USUARIO=@USUARIO

		IF COALESCE(@NIT,'')='' 
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'Tercero Facturador No Identificado, Revise Configuración Terceros'
         
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		IF NOT EXISTS(SELECT 1 FROM PRI WHERE FECHA_INI<=@F_FACTURA AND FECHA_FIN+1>@F_FACTURA AND COALESCE(CERRADO,0)=0)
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'Periodo Contable No Existe o no Esta Abierto, Revise Configuración Peridos Contables'
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
      IF @PROCEDENCIA='AUT'
      BEGIN
         IF @ACCION = 1
         BEGIN
            BEGIN TRY 
					EXEC SPQ_FACTURACE_ESCMA @USUARIO,@NIT,@COMPANIA,@IDSEDE,@USUARIO,@IDTERCERO,@IDPLAN,'',@IDTERCERO,'VARIOS',1,@FECHAFAC=@F_FACTURA
				END TRY 
				BEGIN CATCH
					INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
				END CATCH
				IF(SELECT COUNT(1) FROM @TBLERRORES)>0
				BEGIN
					SELECT 'KO' OK
					SELECT ERROR FROM @TBLERRORES
					RETURN
				END
				SELECT 'OK' OK
         END
      END
      ELSE IF @PROCEDENCIA='UNI'
      BEGIN
         IF @ACCION = 1
         BEGIN
            BEGIN TRY 
					EXEC SPQ_FACTURACE_ESCMA @USUARIO,@NIT,@COMPANIA,@IDSEDE,@USUARIO,@IDTERCERO,@IDPLAN,@OBSERVACION,@IDTERCERO,'CEUNIFICADO',1,@FECHAFAC=@F_FACTURA
				END TRY 
				BEGIN CATCH
					INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
				END CATCH
				IF(SELECT COUNT(1) FROM @TBLERRORES)>0
				BEGIN
					SELECT 'KO' OK
					SELECT ERROR FROM @TBLERRORES
					RETURN
				END
				SELECT 'OK' OK
         END
      END
      RETURN
   END
   IF @METODO='CONTEOFTRMARCADAS'
   BEGIN
      SELECT @PROCESOFACTMAS = JSON_VALUE(@PARAMETROS,'$.PROCESO')
      ,@IDTERCERO  = JSON_VALUE(@PARAMETROS,'$.IDTERCERO')
      ,@IDPLAN     = JSON_VALUE(@PARAMETROS,'$.IDPLAN')   
      ,@IDSEDEF    = JSON_VALUE(@PARAMETROS,'$.IDSEDE')   
      ,@FECHAINIFIL= JSON_VALUE(@PARAMETROS,'$.FINI')     
      ,@FECHAFINFIL= JSON_VALUE(@PARAMETROS,'$.FFIN')     
      ,@PROCEDENCIA= JSON_VALUE(@PARAMETROS,'$.PROCEDENCIA')
      PRINT 'PROCESOFACTMAS='+CONVERT(VARCHAR,@PROCESOFACTMAS) 
	  PRINT 'ANTES DE ENTRAR A LAS PROCEDENCIAS '
      IF @PROCESOFACTMAS = 4 OR @PROCESOFACTMAS = 3
      BEGIN
		 PRINT @PROCEDENCIA
         IF @PROCEDENCIA = 'CIT'
         BEGIN
			PRINT 'ENTRE A CITA DE CONTEO MARCADAS'
            SELECT @NUMCONCNSFACT = COUNT(*) FROM CIT 
            --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
            WHERE  USUARIONOFACTURABLE = @USUARIO 
            AND    MARCAFAC= 1    
            AND    COALESCE(FACTURADA,0)=0
            AND    COALESCE(IDCONTRATANTE,'') = @IDTERCERO
            AND    COALESCE(IDPLAN,'') = @IDPLAN
            AND    COALESCE(IDSEDE,'') = CASE WHEN @IDSEDEF='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
            AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
            AND    COALESCE(FACTURABLE,0) = 1

            IF @IDSEDEF='TODAS'
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDCONTRATANTE,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
            ELSE
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDCONTRATANTE,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR COALESCE(IDSEDE,'') <> @IDSEDEF OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
         END
		 --ONCOLOGIA--
		 ELSE IF @PROCEDENCIA = 'ONCO'
		 BEGIN
			PRINT 'CONTEOFTRMARCADAS - ONCOLOGÍA - PROCESO: ' + CAST(@PROCESOFACTMAS AS VARCHAR)
			-- Contar registros de ONCOLOGÍA marcados DENTRO de los filtros
			SELECT @NUMCONCNSFACT = COUNT(*) 
			FROM CIT
			WHERE CIT.USUARIONOFACTURABLE = @USUARIO 
			AND CIT.MARCAFAC = 1 
			AND COALESCE(CIT.FACTURADA, 0) = 0
			AND CIT.IDTERCEROCA = @IDTERCERO
			AND CIT.IDPLAN = @IDPLAN
			AND CIT.IDSEDE = CASE WHEN @IDSEDEF = 'TODAS' THEN CIT.IDSEDE ELSE @IDSEDEF END
			AND CONVERT(DATE, CIT.FECHA) >= @FECHAINIFIL
			AND CONVERT(DATE, CIT.FECHA) <= @FECHAFINFIL
			AND COALESCE(CIT.FACTURABLE, 0) = 1
			AND CIT.IDAUTSES IS NOT NULL  -- Identificador de ONCOLOGÍA

			-- Contar medicamentos (HCATDIMOV) marcados dentro de filtros
			PRINT 'CONTAR MEDICAMENTOS'
			SELECT @NUMCONCNSFACT_MED = COUNT(*)
			FROM HCATDIMOV H
			INNER JOIN CIT C ON H.CONSECUTIVOCIT = C.CONSECUTIVO
			WHERE H.MARCAFAC = 1
			AND CONVERT(DATE, C.FECHA) <= @FECHAFINFIL
			AND CONVERT(DATE, C.FECHA) >= @FECHAINIFIL
			AND C.IDTERCEROCA = @IDTERCERO
			AND C.IDPLAN = @IDPLAN
			AND COALESCE(H.FACTURADA, 0) = 0
			AND COALESCE(H.USUMARCA, '') = @USUARIO
			AND C.IDSEDE = CASE WHEN @IDSEDEF = 'TODAS' THEN C.IDSEDE ELSE @IDSEDEF END
			AND C.IDAUTSES IS NOT NULL
        
			PRINT 'Registros ONCO dentro de filtros: ' + CAST(@NUMCONCNSFACT AS VARCHAR)
			-- Contar registros de ONCOLOGÍA marcados FUERA de los filtros
			IF @IDSEDEF = 'TODAS'
			BEGIN
				SELECT @NUMCONCNSFACT2 = COUNT(*) 
				FROM CIT
				WHERE CIT.USUARIONOFACTURABLE = @USUARIO 
				AND CIT.MARCAFAC = 1 
				AND COALESCE(CIT.FACTURADA, 0) = 0
				AND COALESCE(CIT.FACTURABLE, 0) = 1
				AND CIT.IDAUTSES IS NOT NULL
				AND (
					CIT.IDTERCEROCA <> @IDTERCERO 
					OR CIT.IDPLAN <> @IDPLAN 
					OR CONVERT(DATE, CIT.FECHA) < @FECHAINIFIL 
					OR CONVERT(DATE, CIT.FECHA) > @FECHAFINFIL
				)
			END
			ELSE
			BEGIN
				SELECT @NUMCONCNSFACT2 = COUNT(*) 
				FROM CIT
				WHERE CIT.USUARIONOFACTURABLE = @USUARIO 
				AND CIT.MARCAFAC = 1 
				AND COALESCE(CIT.FACTURADA, 0) = 0
				AND COALESCE(CIT.FACTURABLE, 0) = 1
				AND CIT.IDAUTSES IS NOT NULL
				AND (
					CIT.IDTERCEROCA <> @IDTERCERO 
					OR CIT.IDPLAN <> @IDPLAN 
					OR CIT.IDSEDE <> @IDSEDEF 
					OR CONVERT(DATE, CIT.FECHA) < @FECHAINIFIL 
					OR CONVERT(DATE, CIT.FECHA) > @FECHAFINFIL
				)
			END		
			PRINT 'Registros ONCO fuera de filtros: ' + CAST(@NUMCONCNSFACT2 AS VARCHAR)
			SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA, COALESCE(@NUMCONCNSFACT_MED,0) AS CANTIDAD_MEDICAMENTOS
			SELECT CIT.CONSECUTIVO,CIT.IDSERVICIO,SER.DESCSERVICIO,'1' AS CANTIDAD,VALORTOTAL 
			FROM CIT
			LEFT JOIN SER ON SER.IDSERVICIO = CIT.IDSERVICIO
			WHERE CIT.USUARIONOFACTURABLE = @USUARIO 
			AND CIT.MARCAFAC = 1 
			AND COALESCE(CIT.FACTURADA, 0) = 0
			AND CIT.IDTERCEROCA = @IDTERCERO
			AND CIT.IDPLAN = @IDPLAN
			AND CIT.IDSEDE = CASE WHEN @IDSEDEF = 'TODAS' THEN CIT.IDSEDE ELSE @IDSEDEF END
			AND CONVERT(DATE, CIT.FECHA) >= @FECHAINIFIL
			AND CONVERT(DATE, CIT.FECHA) <= @FECHAFINFIL
			AND COALESCE(CIT.FACTURABLE, 0) = 1
			AND CIT.IDAUTSES IS NOT NULL  -- Identificador de ONCOLOGÍA
			 --SELECT PARA MEDICAMENTOS MARCADOS
			 SELECT H.CONSECUTIVOCIT AS CONSECUTIVO,H.IDSERVICIO,SER.DESCSERVICIO,H.CANTIDAD,COALESCE (H.VLR_UNITARIO,0) AS VALOR
				FROM HCATDIMOV H
				INNER JOIN CIT C ON H.CONSECUTIVOCIT = C.CONSECUTIVO
				LEFT JOIN SER ON SER.IDSERVICIO=H.IDSERVICIO
				WHERE 1=1
				AND CONVERT(DATE, C.FECHA) >= @FECHAINIFIL
				AND CONVERT(DATE, C.FECHA) <= @FECHAFINFIL
				AND C.IDTERCEROCA = @IDTERCERO
				AND C.IDPLAN = @IDPLAN
				AND H.MARCAFAC = 1
				AND COALESCE(H.FACTURADA, 0) = 0
				AND COALESCE(H.USUMARCA, '') = @USUARIO
				AND C.IDSEDE = CASE WHEN @IDSEDEF = 'TODAS' THEN C.IDSEDE ELSE @IDSEDEF END
				AND C.IDAUTSES IS NOT NULL
			RETURN
		 END
         SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA, COALESCE(@NUMCONCNSFACT_MED,0) AS CANTIDAD_MEDICAMENTOS
         RETURN
      END
      ELSE IF @PROCESOFACTMAS = 1
      BEGIN
         IF @PROCEDENCIA = 'AUT'
         BEGIN
            --SELECT @FECHAINIFIL FECHAINI,@FECHAFINFIL FECHAFIN
            SELECT @NUMCONCNSFACT = COUNT(*) 
            FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
            WHERE  AUTD.IDTERCEROCA = @IDTERCERO
            AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
            AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINIFIL 
            AND    CONVERT(DATE,AUT.FECHA) <=  @FECHAFINFIL
            AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    COALESCE(AUTD.FACTURADA,0) = 0      
            AND    COALESCE(AUTD.VALOR,0)>0 
            AND    COALESCE(AUT.FACTURABLE,0) = 1
            AND    COALESCE(AUT.MARCAFAC,0) = 1
            AND    AUT.ESTADO <> 'Anulada'
            AND    COALESCE(CNSFACT,'') = @USUARIO           

            IF @IDSEDEF='TODAS'
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT  
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  COALESCE(CNSFACT,'') = @USUARIO       
               AND    COALESCE(AUT.MARCAFAC,0) = 1
               AND    COALESCE(AUTD.FACTURADA,0) = 0      
               AND    COALESCE(AUTD.VALOR,0)>0 
               AND    COALESCE(AUT.FACTURABLE,0) = 1
               AND    (   AUTD.IDTERCEROCA != @IDTERCERO OR AUTD.IDPLAN <> CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                       OR CONVERT(DATE,AUT.FECHA) < @FECHAINIFIL OR CONVERT(DATE,AUT.FECHA) >  @FECHAFINFIL )
            ELSE
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT  
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  COALESCE(CNSFACT,'') = @USUARIO       
               AND    COALESCE(AUT.MARCAFAC,0) = 1
               AND    COALESCE(AUTD.FACTURADA,0) = 0      
               AND    COALESCE(AUTD.VALOR,0)>0 
               AND    COALESCE(AUT.FACTURABLE,0) = 1
               AND    (   AUTD.IDTERCEROCA != @IDTERCERO OR AUTD.IDPLAN <> CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                       OR CONVERT(DATE,AUT.FECHA) < @FECHAINIFIL OR CONVERT(DATE,AUT.FECHA) >  @FECHAFINFIL 
                       OR COALESCE(AUT.IDSEDE,'') <> @IDSEDEF)
            SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA 
            RETURN
         END
         ELSE IF @PROCEDENCIA = 'UNI'
         BEGIN
            PRINT 'INGRESE A UNI'
            PRINT '@USUARIO='+@USUARIO
            PRINT '@IDTERCERO='+@IDTERCERO
            PRINT '@IDPLAN='+@IDPLAN
            PRINT '@IDSEDEF='+@IDSEDEF
            --SELECT @FECHAINIFIL FECHAINIFIL ,@FECHAFINFIL FECHAFINFIL
            SELECT @NUMCONCNSFACT = COUNT(*) FROM CIT 
            --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
            WHERE  CNSFACT = @USUARIO 
            AND    MARCAFAC= 1 
            AND    COALESCE(FACTURADA,0)=0
            AND    COALESCE(IDCONTRATANTE,'') = @IDTERCERO
            AND    COALESCE(IDPLAN,'') = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN COALESCE(IDPLAN,'') ELSE  COALESCE(@IDPLAN,'') END
            AND    COALESCE(IDSEDE,'') = CASE WHEN @IDSEDEF='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
            AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
            AND    COALESCE(FACTURABLE,0) = 1

            SELECT @NUMCONCNSFACT2 = COUNT(*) 
            FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
            WHERE  AUTD.IDTERCEROCA = @IDTERCERO
            AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
            AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINIFIL 
            AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFINFIL
            AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    COALESCE(AUTD.FACTURADA,0) = 0      
            AND    COALESCE(AUTD.VALOR,0)>0 
            AND    COALESCE(AUT.FACTURABLE,0) = 1
            AND    COALESCE(AUT.MARCAFAC,0) = 1
            AND    AUT.ESTADO <> 'Anulada'
            AND    COALESCE(CNSFACT,'') = @USUARIO   
			
            SELECT 'OK' OK, @NUMCONCNSFACT CANTIDADCIT, @NUMCONCNSFACT2 CANTIDADAUT
            RETURN
        END
		 ELSE IF @PROCEDENCIA = 'ONCO'
		 BEGIN
			PRINT 'CONTEOFTRMARCADAS - ONCOLOGÍA - PROCESO 1 (PACIENTE)'
			PRINT 'NARENNNNNNNNNNNNNNNNN'
			-- Contar registros de ONCOLOGÍA marcados DENTRO de los filtros
			SELECT @NUMCONCNSFACT = COUNT(*) 
			FROM CIT
			WHERE CIT.USUARIONOFACTURABLE = @USUARIO 
			AND CIT.MARCAFAC = 1 
			AND COALESCE(CIT.FACTURADA, 0) = 0
			AND CIT.IDTERCEROCA = @IDTERCERO
			AND CIT.IDPLAN = @IDPLAN
			AND CIT.IDSEDE = CASE WHEN @IDSEDEF = 'TODAS' THEN CIT.IDSEDE ELSE @IDSEDEF END
			AND CONVERT(DATE, CIT.FECHA) >= @FECHAINIFIL
			AND CONVERT(DATE, CIT.FECHA) <= @FECHAFINFIL
			AND COALESCE(CIT.FACTURABLE, 0) = 1
			AND CIT.IDAUTSES IS NOT NULL  -- Identificador de ONCOLOGÍA        
			PRINT 'Registros ONCO dentro de filtros: ' + CAST(@NUMCONCNSFACT AS VARCHAR)
			-- Contar registros de ONCOLOGÍA marcados FUERA de los filtros
			IF @IDSEDEF = 'TODAS'
			BEGIN
				SELECT @NUMCONCNSFACT2 = COUNT(*) 
				FROM CIT
				WHERE CIT.USUARIONOFACTURABLE = @USUARIO 
				AND CIT.MARCAFAC = 1 
				AND COALESCE(CIT.FACTURADA, 0) = 0
				AND COALESCE(CIT.FACTURABLE, 0) = 1
				AND CIT.IDAUTSES IS NOT NULL
				AND (
					CIT.IDTERCEROCA <> @IDTERCERO 
					OR CIT.IDPLAN <> @IDPLAN 
					OR CONVERT(DATE, CIT.FECHA) < @FECHAINIFIL 
					OR CONVERT(DATE, CIT.FECHA) > @FECHAFINFIL
				)
			END
			ELSE
			BEGIN
				SELECT @NUMCONCNSFACT2 = COUNT(*) 
				FROM CIT
				WHERE CIT.USUARIONOFACTURABLE = @USUARIO 
				AND CIT.MARCAFAC = 1 
				AND COALESCE(CIT.FACTURADA, 0) = 0
				AND COALESCE(CIT.FACTURABLE, 0) = 1
				AND CIT.IDAUTSES IS NOT NULL
				AND (
					CIT.IDTERCEROCA <> @IDTERCERO 
					OR CIT.IDPLAN <> @IDPLAN 
					OR CIT.IDSEDE <> @IDSEDEF 
					OR CONVERT(DATE, CIT.FECHA) < @FECHAINIFIL 
					OR CONVERT(DATE, CIT.FECHA) > @FECHAFINFIL
				)

			END		        
			PRINT 'Registros ONCO fuera de filtros: ' + CAST(@NUMCONCNSFACT2 AS VARCHAR)
		 END
			
			-- Contar medicamentos (HCATDIMOV) marcados dentro de filtros
			PRINT 'CONTAR MEDICAMENTOS'
			SELECT @NUMCONCNSFACT_MED = COUNT(*)
			FROM HCATDIMOV H
			INNER JOIN CIT C ON H.CONSECUTIVOCIT = C.CONSECUTIVO
			WHERE 1=1
			AND CONVERT(DATE, H.FECHA_CREA) >= @FECHAINIFIL
			AND CONVERT(DATE, H.FECHA_CREA) <= @FECHAFINFIL
			AND COALESCE (NULLIF(H.IDTERCEROCA,''),C.IDTERCEROCA) = @IDTERCERO
			AND COALESCE(NULLIF(H.IDPLAN,''), C.IDPLAN) = @IDPLAN --C.IDPLAN = @IDPLAN VALIDA EL IDPLAN PRIMERO DE HCATDIMOV SI NO DE CITAS
			AND H.MARCAFAC = 1
			AND COALESCE(H.FACTURADA, 0) = 0
			AND COALESCE(H.USUMARCA, '') = @USUARIO
			--AND C.IDSEDE = CASE WHEN @IDSEDEF = 'TODAS' THEN C.IDSEDE ELSE @IDSEDEF END
			--AND C.IDAUTSES IS NOT NULL
			
			
    
	     SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA, @NUMCONCNSFACT AS CANTIDAD_CITAS, COALESCE(@NUMCONCNSFACT_MED,0) AS CANTIDAD_MEDICAMENTOS
		 --SELECT PARA CITAS MARCADAS
			SELECT CIT.CONSECUTIVO,CIT.IDSERVICIO,SER.DESCSERVICIO,'1' AS CANTIDAD,VALORTOTAL 
			FROM CIT
			LEFT JOIN SER ON SER.IDSERVICIO = CIT.IDSERVICIO
			WHERE CIT.USUARIONOFACTURABLE = @USUARIO 
			AND CIT.MARCAFAC = 1 
			AND COALESCE(CIT.FACTURADA, 0) = 0
			AND CIT.IDTERCEROCA = @IDTERCERO
			AND CIT.IDPLAN = @IDPLAN
			AND CIT.IDSEDE = CASE WHEN @IDSEDEF = 'TODAS' THEN CIT.IDSEDE ELSE @IDSEDEF END
			AND CONVERT(DATE, CIT.FECHA) >= @FECHAINIFIL
			AND CONVERT(DATE, CIT.FECHA) <= @FECHAFINFIL
			AND COALESCE(CIT.FACTURABLE, 0) = 1
			AND CIT.IDAUTSES IS NOT NULL  -- Identificador de ONCOLOGÍA
		 --SELECT PARA MEDICAMENTOS MARCADOS
		 SELECT H.CONSECUTIVOCIT AS CONSECUTIVO,H.IDSERVICIO,SER.DESCSERVICIO,H.CANTIDAD,COALESCE (H.VLR_UNITARIO,0) AS VALOR
			FROM HCATDIMOV H
			INNER JOIN CIT C ON H.CONSECUTIVOCIT = C.CONSECUTIVO
			LEFT JOIN SER ON SER.IDSERVICIO=H.IDSERVICIO
			WHERE 1=1
			AND CONVERT(DATE, C.FECHA) >= @FECHAINIFIL
			AND CONVERT(DATE, C.FECHA) <= @FECHAFINFIL
			AND COALESCE (NULLIF(H.IDTERCEROCA,''),C.IDTERCEROCA) = @IDTERCERO
			AND COALESCE(NULLIF(H.IDPLAN,''), C.IDPLAN) = @IDPLAN --C.IDPLAN = @IDPLAN
			AND H.MARCAFAC = 1
			AND COALESCE(H.FACTURADA, 0) = 0
			AND COALESCE(H.USUMARCA, '') = @USUARIO
			AND C.IDSEDE = CASE WHEN @IDSEDEF = 'TODAS' THEN C.IDSEDE ELSE @IDSEDEF END
			AND C.IDAUTSES IS NOT NULL
		RETURN

      END
	  ELSE IF @PROCESOFACTMAS = 5
      BEGIN
         IF @PROCEDENCIA = 'CIT'
         BEGIN
            SELECT @NUMCONCNSFACT = COUNT(*) FROM CIT 
            --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
            WHERE  USUARIONOFACTURABLE = @USUARIO 
            AND    MARCAFAC= 1 
            AND    COALESCE(FACTURADA,0)=0
            AND    COALESCE(IDTERCEROCA,'') = @IDTERCERO
            AND    COALESCE(IDPLAN,'') = @IDPLAN
            AND    COALESCE(IDSEDE,'') = CASE WHEN @IDSEDEF='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
            AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
            AND    COALESCE(FACTURABLE,0) = 1

            IF @IDSEDEF='TODAS'
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDTERCEROCA,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
            ELSE
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDTERCEROCA,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR COALESCE(IDSEDE,'') <> @IDSEDEF OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
         END         
         SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA 
         RETURN
      END
      RETURN
   END
   IF @METODO='FACTURAR_CITAUT'   
   BEGIN         
      SELECT @CONSECUTIVO=CONSECUTIVO,@OBSERVACION=OBSERVACION        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CONSECUTIVO  VARCHAR(20)   '$.CONSECUTIVO',
      OBSERVACION  VARCHAR(2048)   '$.OBSERVACION'
      )
      SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE)
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
      WHERE USUARIO=@USUARIO
      SELECT @TIPOFAC='Factura',@FECHAFACT=DBO.FNK_GETDATE()
      PRINT 'Valido sede'
      IF NOT EXISTS(SELECT * FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND PROCEDENCIA='FTR' AND COALESCE(VENCIDA,0)=0 )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Sede: '+@IDSEDE+' No habilitada para emitir Facturas, Comuniquese con el Administrador del Sistema'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN

      END
	  IF EXISTS (SELECT * FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO AND IDTERCEROCA = DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR'))
	  BEGIN
		INSERT INTO @TBLERRORES(ERROR)
		SELECT 'La atencion a facturar es Particular, por lo que no se puede facturar.'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
	  END
      IF NOT EXISTS(SELECT * FROM CIT WHERE COALESCE(FACTURADA,0)=1 AND COALESCE(N_FACTURA,'')='' AND CONSECUTIVO=@CONSECUTIVO) 
      BEGIN
         BEGIN TRY   
            EXEC SPK_FACTURACE_CITAUT_COL @CONSECUTIVO,@DPR,@COMPANIA,@IDSEDE, @USUARIO,'','','','','','CI','', 'FALSE', NULL,@FECHAFACT,@TIPOFAC, @IDTERCERO                 
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         SELECT @N_fACTURA=N_FACTURA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVO
         IF COALESCE(@OBSERVACION,'')<>''
         BEGIN
            UPDATE FTR SET OBSERVACION=@OBSERVACION WHERE N_FACTURA=@N_fACTURA
         END
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Cita ya Facturada o con Valores en Cero(0), Verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @N_FACTURA=N_FACTURA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVO
      SELECT 'OK' OK,@N_FACTURA N_FACTURA
      RETURN 
   END
   IF @METODO='ADDDEL_AUTD'     
   BEGIN         
      SELECT @IDAUT=IDAUT     
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      IDAUT  VARCHAR(20)   '$.IDAUT'
      )
      IF EXISTS(SELECT * FROM AUT WHERE IDAUT=@IDAUT AND COALESCE(MARCAFAC,0)=0)
      BEGIN
         UPDATE AUT SET MARCAFAC=1, CNSFACT=@USUARIO WHERE IDAUT=@IDAUT AND COALESCE(MARCAFAC,0)=0
      END
      ELSE
      BEGIN
         UPDATE AUT SET MARCAFAC=0, CNSFACT=NULL WHERE IDAUT=@IDAUT AND COALESCE(MARCAFAC,0)=1
      END
      SELECT 'OK' OK 
      RETURN 
   END  
   IF @METODO='MARCAFACT_AUTD'     
   BEGIN         
      SELECT @CONSECUTIVO=CONSECUTIVO,@IDAFILIADO=IDAFILIADO,@ADDDEL=ACCION       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CONSECUTIVO  VARCHAR(20)   '$.CONSECUTIVO',
      IDAFILIADO  VARCHAR(20)   '$.IDAFILIADO',
      ACCION  VARCHAR(20)   '$.ACCION'
      )
      PRINT @ADDDEL
      IF @ADDDEL='ADD'
      BEGIN
         PRINT 'VOY A MARACAR'
         UPDATE AUT SET MARCAFAC=1,CNSFACT=@USUARIO 
         FROM AUT
         WHERE AUT.IDAFILIADO=@IDAFILIADO
         AND CONSECUTIVOCIT=@CONSECUTIVO 
         AND COALESCE(AUT.FACTURADA,0)=0
         AND  EXISTS(SELECT * FROM AUTD WHERE AUT.IDAUT=AUTD.IDAUT 
         AND COALESCE(FACTURADA,0)=0
         AND COALESCE(NOCOBRABLE,0)=0
         AND 1=CASE WHEN COALESCE(AUTD.ESDELAB,0)=1 THEN CASE WHEN COALESCE(AUTD.ENLAB,0)=2 THEN 1 ELSE 2 END ELSE
                        CASE WHEN COALESCE(APOYODG_AMBITO,'')<> '' AND COALESCE(AUTD.ENLAB,0)=2
                        THEN 1 WHEN COALESCE(APOYODG_AMBITO,'')<> '' AND COALESCE(AUTD.ENLAB,0)<> 2 THEN 2 ELSE 1 END END
                        )

         UPDATE AUT SET MARCAFAC=1,CNSFACT=@USUARIO 
         FROM AUT
         WHERE AUT.IDAFILIADO=@IDAFILIADO 
         AND COALESCE(CONSECUTIVOCIT,'')<>@CONSECUTIVO 
         AND COALESCE(FACTURADA,0)=0
         AND EXISTS(SELECT * FROM AUTD WHERE AUT.IDAUT=AUTD.IDAUT 
         AND COALESCE(FACTURADA,0)=0
         AND COALESCE(NOCOBRABLE,0)=0
         AND 1=CASE WHEN COALESCE(AUTD.ESDELAB,0)=1 THEN CASE WHEN COALESCE(AUTD.ENLAB,0)=2 THEN 1 ELSE 2 END ELSE
                        CASE WHEN COALESCE(APOYODG_AMBITO,'')<> '' AND COALESCE(AUTD.ENLAB,0)=2
                        THEN 1 WHEN COALESCE(APOYODG_AMBITO,'')<> '' AND COALESCE(AUTD.ENLAB,0)<> 2 THEN 2 ELSE 1 END END)
         
      END
      ELSE
      BEGIN
         UPDATE AUT SET MARCAFAC=0,CNSFACT=NULL WHERE AUT.IDAFILIADO=@IDAFILIADO  AND  MARCAFAC=1 AND CNSFACT=@USUARIO  
      END
      SELECT 'OK' OK 
      RETURN 
   END  
   IF @METODO='NOCOBRAR_AUTD'
   BEGIN
	  DECLARE @TOTAL_ITEMS INT
      DECLARE @ITEMS_NOCOBRABLES INT
      --DECLARE @FACTURADA BIT

      SELECT @IDAUT=IDAUT,@NOITEM=NOITEM    
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      IDAUT  VARCHAR(20)   '$.IDAUT',
      NOITEM  SMALLINT   '$.NOITEM'
      )
	   --  VALIDACIÓN: No permitir si AUT está facturada
	  -- SELECT @FACTURADA = COALESCE(FACTURADA,0)  FROM AUT WHERE IDAUT = @IDAUT
   --	   IF @FACTURADA = 1
	  -- BEGIN
			--PRINT '1'
		 -- SELECT 'KO' OK, 'No se puede modificar: La autorización ya está facturada' ERROR
		 -- RETURN
	  -- END
	   --   VALIDACIÓN: No permitir si el item está facturado
	   --IF EXISTS ( SELECT * FROM AUTD  WHERE IDAUT = @IDAUT  AND NO_ITEM = @NOITEM   AND COALESCE(FACTURADA,0) = 1 )
	   --BEGIN
		  --SELECT 'KO' OK, 'No se puede modificar: El item ya está facturado' ERROR
		  --RETURN
	   --END
      IF EXISTS(SELECT * FROM AUTD WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM AND COALESCE(NOCOBRABLE,0)=0)
      BEGIN
         UPDATE AUTD SET NOCOBRABLE=1,USUARIOMARCA=@USUARIO WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM AND COALESCE(NOCOBRABLE,0)=0
      END
      ELSE
      BEGIN
         UPDATE AUTD SET NOCOBRABLE=0, USUARIOMARCA=NULL WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM AND COALESCE(NOCOBRABLE,0)=1
      END
	  --  AUTO-MARCADO: Actualizar AUT.FACTURABLE según items
	   SELECT @TOTAL_ITEMS = COUNT(*) FROM AUTD WHERE IDAUT = @IDAUT
   
	   SELECT @ITEMS_NOCOBRABLES = COUNT(*)  FROM AUTD WHERE IDAUT = @IDAUT AND COALESCE(NOCOBRABLE,0) = 1
   
	   -- Si TODOS son NO COBRABLE ? AUT.FACTURABLE = 0
	   IF @TOTAL_ITEMS > 0 AND @ITEMS_NOCOBRABLES = @TOTAL_ITEMS
	   BEGIN
		  UPDATE AUT SET FACTURABLE = 0
		  WHERE IDAUT = @IDAUT AND COALESCE(FACTURABLE,1) = 1
	   END
	   -- Si AL MENOS UNO es COBRABLE ? AUT.FACTURABLE = 1
	   ELSE IF @TOTAL_ITEMS > 0 AND @ITEMS_NOCOBRABLES < @TOTAL_ITEMS
	   BEGIN
		  UPDATE AUT SET FACTURABLE = 1
		  WHERE IDAUT = @IDAUT AND COALESCE(FACTURABLE,1) = 0
	   END
	   --PRINT 'ACTUALIZAR AHORA VALOR TOTAL'
	 --  UPDATE AUT SET VALORTOTAL = (
		--	SELECT SUM(COALESCE(AUTD.VALOR,0) * COALESCE(AUTD.CANTIDAD,1))
		--	FROM AUTD
		--	WHERE AUTD.IDAUT = @IDAUT
		--	AND COALESCE(AUTD.NOCOBRABLE,0) = 0 
		--	AND COALESCE(AUTD.FACTURADA,0) = 0   
		--)
		--WHERE IDAUT = @IDAUT

      SELECT 'OK' OK 
      RETURN 
   END   

   IF @METODO='ASIGNAR_NROAUT'
   BEGIN
	  SELECT @NOAUTORIZACION=NOAUTORIZACION      
	  FROM   OPENJSON (@PARAMETROS)
      WITH (NOAUTORIZACION  VARCHAR(20)   '$.NOAUTORIZACION')
	  SELECT 'OK' OK

	  UPDATE AUT SET NUMAUTORIZA = @NOAUTORIZACION
	  WHERE MARCAFAC=1 AND CNSFACT = @USUARIO

      UPDATE CIT SET NOAUTORIZACION = @NOAUTORIZACION
	  WHERE MARCAFAC=1 AND CNSFACT = @USUARIO
   END

   IF @METODO='CONTEOFTRMARCADAS_EVENTO'
   BEGIN
      SELECT @PROCESOFACTMAS = JSON_VALUE(@PARAMETROS,'$.PROCESO')
      ,@IDTERCERO  = JSON_VALUE(@PARAMETROS,'$.IDTERCERO')
      ,@IDPLAN     = JSON_VALUE(@PARAMETROS,'$.IDPLAN')   
      ,@IDSEDEF    = JSON_VALUE(@PARAMETROS,'$.IDSEDE')   
      ,@FECHAINIFIL= JSON_VALUE(@PARAMETROS,'$.FINI')     
      ,@FECHAFINFIL= JSON_VALUE(@PARAMETROS,'$.FFIN')     
      ,@PROCEDENCIA= JSON_VALUE(@PARAMETROS,'$.PROCEDENCIA')
      PRINT 'PROCESOFACTMAS='+CONVERT(VARCHAR,@PROCESOFACTMAS) 
      IF @PROCESOFACTMAS = 4 OR @PROCESOFACTMAS = 3
      BEGIN
         IF @PROCEDENCIA = 'CIT'
         BEGIN
            SELECT @NUMCONCNSFACT = COUNT(*) FROM CIT 
            --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
			INNER JOIN AFI ON CIT.IDAFILIADO=AFI.IDAFILIADO
            WHERE  USUARIONOFACTURABLE = @USUARIO 
            AND    MARCAFAC= 1 
            AND    COALESCE(FACTURADA,0)=0
            AND    COALESCE(IDCONTRATANTE,'') = @IDTERCERO
            AND    COALESCE(CIT.IDPLAN,'') = @IDPLAN
            AND    COALESCE(AFI.IDSEDE,'') = CASE WHEN @IDSEDEF='TODAS' THEN AFI.IDSEDE ELSE @IDSEDEF END
            AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
            AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
            AND    COALESCE(FACTURABLE,0) = 1

            IF @IDSEDEF='TODAS'
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDCONTRATANTE,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
            ELSE
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
			   INNER JOIN AFI ON CIT.IDAFILIADO=AFI.IDAFILIADO
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDCONTRATANTE,'') <> @IDTERCERO OR COALESCE(CIT.IDPLAN,'') <> @IDPLAN OR COALESCE(AFI.IDSEDE,'') <> @IDSEDEF OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
         END
         
         SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA 
         RETURN
      END
      ELSE IF @PROCESOFACTMAS = 1
      BEGIN
         IF @PROCEDENCIA = 'AUT'
         BEGIN
            --SELECT @FECHAINIFIL FECHAINI,@FECHAFINFIL FECHAFIN
            SELECT @NUMCONCNSFACT = COUNT(*) 
            FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
            WHERE  AUTD.IDTERCEROCA = @IDTERCERO
            AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
            AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINIFIL 
            AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFINFIL
            AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    COALESCE(AUTD.FACTURADA,0) = 0      
            AND    COALESCE(AUTD.VALOR,0)>0 
            AND    COALESCE(AUT.FACTURABLE,0) = 1
            AND    COALESCE(AUT.MARCAFAC,0) = 1
            AND    AUT.ESTADO <> 'Anulada'
            AND    COALESCE(CNSFACT,'') = @USUARIO           

            IF @IDSEDEF='TODAS'
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT  
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  COALESCE(CNSFACT,'') = @USUARIO       
               AND    COALESCE(AUT.MARCAFAC,0) = 1
               AND    COALESCE(AUTD.FACTURADA,0) = 0      
               AND    COALESCE(AUTD.VALOR,0)>0 
               AND    COALESCE(AUT.FACTURABLE,0) = 1
               AND    (   AUTD.IDTERCEROCA != @IDTERCERO OR AUTD.IDPLAN <> CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                       OR CONVERT(DATE,AUT.FECHA) < @FECHAINIFIL OR CONVERT(DATE,AUT.FECHA) >  @FECHAFINFIL )
            ELSE
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT  
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  COALESCE(CNSFACT,'') = @USUARIO       
               AND    COALESCE(AUT.MARCAFAC,0) = 1
               AND    COALESCE(AUTD.FACTURADA,0) = 0      
               AND    COALESCE(AUTD.VALOR,0)>0 
               AND    COALESCE(AUT.FACTURABLE,0) = 1
               AND    (   AUTD.IDTERCEROCA != @IDTERCERO OR AUTD.IDPLAN <> CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                       OR CONVERT(DATE,AUT.FECHA) < @FECHAINIFIL OR CONVERT(DATE,AUT.FECHA) >  @FECHAFINFIL 
                       OR COALESCE(AUT.IDSEDE,'') <> @IDSEDEF)
            SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA 
            RETURN
         END
         ELSE IF @PROCEDENCIA = 'UNI'
         BEGIN
            PRINT 'INGRESE A UNI'
            PRINT '@USUARIO='+@USUARIO
            PRINT '@IDTERCERO='+@IDTERCERO
            PRINT '@IDPLAN='+@IDPLAN
            PRINT '@IDSEDEF='+@IDSEDEF
            --SELECT @FECHAINIFIL FECHAINIFIL ,@FECHAFINFIL FECHAFINFIL
            SELECT @NUMCONCNSFACT = COUNT(*) FROM CIT 
            --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
            WHERE  CNSFACT = @USUARIO 
            AND    MARCAFAC= 1 
            AND    COALESCE(FACTURADA,0)=0
            AND    COALESCE(IDCONTRATANTE,'') = @IDTERCERO
            AND    COALESCE(IDPLAN,'') = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN COALESCE(IDPLAN,'') ELSE  COALESCE(@IDPLAN,'') END
            AND    COALESCE(IDSEDE,'') = CASE WHEN @IDSEDEF='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
            AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
            AND    COALESCE(FACTURABLE,0) = 1

            SELECT @NUMCONCNSFACT2 = COUNT(*) 
            FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
            WHERE  AUTD.IDTERCEROCA = @IDTERCERO
            AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
            AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINIFIL 
            AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFINFIL
            AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    COALESCE(AUTD.FACTURADA,0) = 0      
            AND    COALESCE(AUTD.VALOR,0)>0 
            AND    COALESCE(AUT.FACTURABLE,0) = 1
            AND    COALESCE(AUT.MARCAFAC,0) = 1
            AND    AUT.ESTADO <> 'Anulada'
            AND    COALESCE(CNSFACT,'') = @USUARIO   
			
            SELECT 'OK' OK, @NUMCONCNSFACT CANTIDADCIT, @NUMCONCNSFACT2 CANTIDADAUT
            RETURN
         END
      END
	  ELSE IF @PROCESOFACTMAS = 5
      BEGIN
         IF @PROCEDENCIA = 'CIT'
         BEGIN
            SELECT @NUMCONCNSFACT = COUNT(*) FROM CIT 
            --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
			INNER JOIN AFI ON CIT.IDAFILIADO=AFI.IDAFILIADO
            WHERE  USUARIONOFACTURABLE = @USUARIO 
            AND    MARCAFAC= 1 
            AND    COALESCE(FACTURADA,0)=0
            AND    COALESCE(IDTERCEROCA,'') = @IDTERCERO
            AND    COALESCE(CIT.IDPLAN,'') = @IDPLAN
            AND    COALESCE(AFI.IDSEDE,'') = CASE WHEN @IDSEDEF='TODAS' THEN AFI.IDSEDE ELSE @IDSEDEF END
            AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
            AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
            AND    COALESCE(FACTURABLE,0) = 1

            IF @IDSEDEF='TODAS'
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDTERCEROCA,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
            ELSE
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
			   INNER JOIN AFI ON CIT.IDAFILIADO=AFI.IDAFILIADO
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDTERCEROCA,'') <> @IDTERCERO OR COALESCE(CIT.IDPLAN,'') <> @IDPLAN OR COALESCE(AFI.IDSEDE,'') <> @IDSEDEF OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
         END
         
         SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA 
         RETURN
      END
      RETURN
   END
   IF @METODO = 'INFORME_PREVIO'
   BEGIN
      DECLARE @VALORCERO BIT = 0
             ,@PROCEDENCIA_FIL VARCHAR(10) = 'Todas'

      SELECT @DATOS = DATOS
      FROM OPENJSON(@PARAMETROS)
      WITH (DATOS NVARCHAR(MAX) AS JSON)

      SELECT @FECHAINI   = F_INIMAS,
             @FECHAFIN   = F_FINMAS,
             @IDTERCERO  = IDTERMAS,
             @IDPLAN     = IDPLANMAS,
             @IDSEDEF    = SEDEFMAS,
             @VALORCERO  = COALESCE(VALORCERO, 0),
             @PROCEDENCIA_FIL = COALESCE(PROCEDENCIA_FIL, 'Todas')
      FROM OPENJSON(@DATOS)
      WITH (
         F_INIMAS         DATE         '$.F_INIMAS',
         F_FINMAS         DATE         '$.F_FINMAS',
         IDTERMAS         VARCHAR(20)  '$.IDTERMAS',
         IDPLANMAS        VARCHAR(20)  '$.IDPLANMAS',
         SEDEFMAS         VARCHAR(20)  '$.SEDEFMAS',
         VALORCERO        BIT          '$.VALORCERO',
         PROCEDENCIA_FIL  VARCHAR(10)  '$.PROCEDENCIAFACTURACION.value'
      )

      IF COALESCE(@IDPLAN, '') = ''
      BEGIN
         SELECT 'KO' OK, 'Debe seleccionar un plan' ERROR
         RETURN
      END
      IF COALESCE(@FECHAINI, '') = '' OR COALESCE(@FECHAFIN, '') = ''
      BEGIN
         SELECT 'KO' OK, 'Debe seleccionar el rango de fechas' ERROR
         RETURN
      END
      IF COALESCE(@IDTERCERO, '') = ''
      BEGIN
         SELECT 'KO' OK, 'Debe seleccionar el tercero' ERROR
         RETURN
      END

      SELECT 'OK' OK

      ;WITH DETALLE AS (
         SELECT 'CE' AS PROCEDENCIA,
                A.NOAUT AS CONSECUTIVO,
                A.FECHA,
                A.NUMAUTORIZA AS AUTORIZACION,
                AFI.DOCIDAFILIADO,
                AFI.NOMBREAFI,
                SER.IDSERVICIO,
                SER.DESCSERVICIO,
                AUTD.CANTIDAD,
                AUTD.VALOR * AUTD.CANTIDAD AS SUBTOTAL,
                CASE A.COPAGOPROPIO
                   WHEN 1 THEN A.VALORCOPAGO
                   ELSE COALESCE(AUTD.VALORCOPAGO, 0)
                END AS VALORCOPAGO,
                (AUTD.CANTIDAD * AUTD.VALOR) -
                CASE A.COPAGOPROPIO
                   WHEN 1 THEN A.VALORCOPAGO
                   ELSE COALESCE(AUTD.VALORCOPAGO, 0)
                END AS VLRTOTAL
         FROM VWK_AUT_FTR A
         INNER JOIN AUT ON AUT.IDAUT = A.IDAUT
         INNER JOIN AFI ON AFI.IDAFILIADO = A.IDAFILIADO
         INNER JOIN AUTD ON A.IDAUT = AUTD.IDAUT
         INNER JOIN SER ON SER.IDSERVICIO = AUTD.IDSERVICIO
         WHERE A.CNSFACT = @USUARIO
           AND COALESCE(AUTD.FACTURADA, 0) = 0
           AND A.MARCAFAC = 1
           AND COALESCE(A.FACTURABLE, 0) = 1
           AND AUTD.IDTERCEROCA = @IDTERCERO
           AND AUTD.IDPLAN = CASE WHEN COALESCE(@IDPLAN, '') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
           AND CONVERT(DATE, A.FECHA) >= @FECHAINI
           AND CONVERT(DATE, A.FECHA) < DATEADD(DAY, 1, @FECHAFIN)
           AND AUT.IDSEDE = CASE WHEN UPPER(@IDSEDEF) = 'TODAS' THEN AUT.IDSEDE ELSE @IDSEDEF END
           AND COALESCE(A.VALORTOTAL, 0) > CASE WHEN @VALORCERO = 1 THEN -1 ELSE 0 END
           AND COALESCE(AUTD.VALOR, 0) > CASE WHEN @VALORCERO = 1 THEN -1 ELSE 0 END
           AND AUT.ESTADO <> 'Anulada'
           AND (@PROCEDENCIA_FIL = 'Todas' OR @PROCEDENCIA_FIL = 'AUT')

         UNION ALL

         SELECT 'CI' AS PROCEDENCIA,
                A.CONSECUTIVO,
                A.FECHA,
                A.NOAUTORIZACION AS AUTORIZACION,
                AFI.DOCIDAFILIADO,
                AFI.NOMBREAFI,
                SER.IDSERVICIO,
                SER.DESCSERVICIO,
                1 AS CANTIDAD,
                COALESCE(A.VALORTOTAL, 0) AS SUBTOTAL,
                COALESCE(A.VALORCOPAGO, 0) AS VALORCOPAGO,
                COALESCE(A.VALORTOTAL, 0) - COALESCE(A.VALORCOPAGO, 0) AS VLRTOTAL
         FROM CIT A
         INNER JOIN AFI ON AFI.IDAFILIADO = A.IDAFILIADO
         INNER JOIN SER ON SER.IDSERVICIO = A.IDSERVICIO
         WHERE A.CNSFACT = @USUARIO
           AND COALESCE(A.FACTURADA, 0) = 0
           AND A.MARCAFAC = 1
           AND COALESCE(A.FACTURABLE, 0) = 1
           AND COALESCE(A.VALORTOTAL, 0) > CASE WHEN @VALORCERO = 1 THEN -1 ELSE 0 END
           AND COALESCE(A.IDCONTRATANTE, '') = @IDTERCERO
           AND COALESCE(A.IDPLAN, '') = CASE WHEN COALESCE(@IDPLAN, '') = '' THEN COALESCE(A.IDPLAN, '') ELSE COALESCE(@IDPLAN, '') END
           AND COALESCE(A.IDSEDE, '') = CASE WHEN UPPER(@IDSEDEF) = 'TODAS' THEN A.IDSEDE ELSE @IDSEDEF END
           AND CONVERT(DATE, A.FECHA) >= @FECHAINI
           AND CONVERT(DATE, A.FECHA) <= @FECHAFIN
           AND (@PROCEDENCIA_FIL = 'Todas' OR @PROCEDENCIA_FIL = 'CIT')
      )
      SELECT PROCEDENCIA,
             CONSECUTIVO,
             FECHA,
             AUTORIZACION,
             DOCIDAFILIADO,
             NOMBREAFI,
             IDSERVICIO,
             DESCSERVICIO,
             CANTIDAD,
             SUBTOTAL,
             VALORCOPAGO,
             VLRTOTAL
      FROM DETALLE
      ORDER BY PROCEDENCIA, FECHA, CONSECUTIVO, IDSERVICIO

      SELECT PROCEDENCIA,
             COUNT(*) AS REGISTROS,
             SUM(CANTIDAD) AS CANTIDAD,
             SUM(SUBTOTAL) AS SUBTOTAL,
             SUM(VALORCOPAGO) AS VALORCOPAGO,
             SUM(VLRTOTAL) AS VLRTOTAL
      FROM (
         SELECT 'CE' AS PROCEDENCIA,
                AUTD.CANTIDAD,
                AUTD.VALOR * AUTD.CANTIDAD AS SUBTOTAL,
                CASE A.COPAGOPROPIO
                   WHEN 1 THEN A.VALORCOPAGO
                   ELSE COALESCE(AUTD.VALORCOPAGO, 0)
                END AS VALORCOPAGO,
                (AUTD.CANTIDAD * AUTD.VALOR) -
                CASE A.COPAGOPROPIO
                   WHEN 1 THEN A.VALORCOPAGO
                   ELSE COALESCE(AUTD.VALORCOPAGO, 0)
                END AS VLRTOTAL
         FROM VWK_AUT_FTR A
         INNER JOIN AUT ON AUT.IDAUT = A.IDAUT
         INNER JOIN AUTD ON A.IDAUT = AUTD.IDAUT
         WHERE A.CNSFACT = @USUARIO
           AND COALESCE(AUTD.FACTURADA, 0) = 0
           AND A.MARCAFAC = 1
           AND COALESCE(A.FACTURABLE, 0) = 1
           AND AUTD.IDTERCEROCA = @IDTERCERO
           AND AUTD.IDPLAN = CASE WHEN COALESCE(@IDPLAN, '') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
           AND CONVERT(DATE, A.FECHA) >= @FECHAINI
           AND CONVERT(DATE, A.FECHA) < DATEADD(DAY, 1, @FECHAFIN)
           AND AUT.IDSEDE = CASE WHEN UPPER(@IDSEDEF) = 'TODAS' THEN AUT.IDSEDE ELSE @IDSEDEF END
           AND COALESCE(A.VALORTOTAL, 0) > CASE WHEN @VALORCERO = 1 THEN -1 ELSE 0 END
           AND COALESCE(AUTD.VALOR, 0) > CASE WHEN @VALORCERO = 1 THEN -1 ELSE 0 END
           AND AUT.ESTADO <> 'Anulada'
           AND (@PROCEDENCIA_FIL = 'Todas' OR @PROCEDENCIA_FIL = 'AUT')

         UNION ALL

         SELECT 'CI' AS PROCEDENCIA,
                1 AS CANTIDAD,
                COALESCE(A.VALORTOTAL, 0) AS SUBTOTAL,
                COALESCE(A.VALORCOPAGO, 0) AS VALORCOPAGO,
                COALESCE(A.VALORTOTAL, 0) - COALESCE(A.VALORCOPAGO, 0) AS VLRTOTAL
         FROM CIT A
         WHERE A.CNSFACT = @USUARIO
           AND COALESCE(A.FACTURADA, 0) = 0
           AND A.MARCAFAC = 1
           AND COALESCE(A.FACTURABLE, 0) = 1
           AND COALESCE(A.VALORTOTAL, 0) > CASE WHEN @VALORCERO = 1 THEN -1 ELSE 0 END
           AND COALESCE(A.IDCONTRATANTE, '') = @IDTERCERO
           AND COALESCE(A.IDPLAN, '') = CASE WHEN COALESCE(@IDPLAN, '') = '' THEN COALESCE(A.IDPLAN, '') ELSE COALESCE(@IDPLAN, '') END
           AND COALESCE(A.IDSEDE, '') = CASE WHEN UPPER(@IDSEDEF) = 'TODAS' THEN A.IDSEDE ELSE @IDSEDEF END
           AND CONVERT(DATE, A.FECHA) >= @FECHAINI
           AND CONVERT(DATE, A.FECHA) <= @FECHAFIN
           AND (@PROCEDENCIA_FIL = 'Todas' OR @PROCEDENCIA_FIL = 'CIT')
      ) RESUMEN
      GROUP BY ROLLUP(PROCEDENCIA)
      ORDER BY CASE WHEN PROCEDENCIA IS NULL THEN 2 ELSE 1 END, PROCEDENCIA

      RETURN
   END

   IF @METODO = 'MARCA_APLIMF'
   BEGIN
      PRINT 'MARCA_APLIMF'
      DECLARE @IDAPLIMF_MARCA INT
             ,@MARCA_NUEVA    SMALLINT
             ,@IDAUT_MARCA    VARCHAR(20)

      SELECT @IDAPLIMF_MARCA = IDAPLIMF
      FROM OPENJSON(@PARAMETROS)
      WITH (IDAPLIMF INT '$.IDAPLIMF')

      IF COALESCE(@IDAPLIMF_MARCA, 0) = 0
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'IDAPLIMF es obligatorio'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF NOT EXISTS (
         SELECT 1
         FROM APLIMF F WITH (NOLOCK)
         INNER JOIN SER S WITH (NOLOCK) ON S.IDSERVICIO = F.IDSERVICIO
         WHERE F.ID = @IDAPLIMF_MARCA
           AND COALESCE(S.POS, 1) = 0
           AND NULLIF(TRIM(S.PREFIJO), '') = NULLIF(TRIM(DBO.FNK_VALORVARIABLE('PREF_MED_NOPOS')), '')
      )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Ítem no encontrado o no es medicamento No POS (PREF_MED_NOPOS)'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT @IDAUT_MARCA = NULLIF(TRIM(F.IDAUT), '')
            ,@MARCA_NUEVA = CASE WHEN COALESCE(F.MARCA, 0) = 1 THEN 0 ELSE 1 END
      FROM APLIMF F WITH (NOLOCK)
      WHERE F.ID = @IDAPLIMF_MARCA

      IF @MARCA_NUEVA = 1
         AND EXISTS (
            SELECT 1 FROM APLIMF WITH (NOLOCK)
            WHERE ID = @IDAPLIMF_MARCA
              AND COALESCE(FACTURADA, 0) = 1
              AND NULLIF(TRIM(N_FACTURA), '') IS NOT NULL
         )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se puede marcar: el ítem ya está facturado'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      BEGIN TRY
         UPDATE APLIMF
         SET MARCA = @MARCA_NUEVA,
             USUARIOMARCA = CASE WHEN @MARCA_NUEVA = 1 THEN @USUARIO ELSE NULL END
         WHERE ID = @IDAPLIMF_MARCA
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH

      IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK, @IDAPLIMF_MARCA AS IDAPLIMF, @MARCA_NUEVA AS MARCA,
             CASE WHEN @MARCA_NUEVA = 1 THEN @USUARIO ELSE NULL END AS USUARIOMARCA
      RETURN
   END

   IF @METODO = 'MARCA_TODO_APLIMF'
   BEGIN
      PRINT 'MARCA_TODO_APLIMF'
      DECLARE @IDAPLIM_TODO   INT
             ,@CANT_ELEGIBLE  INT
             ,@CANT_MARCADOS  INT
             ,@MARCA_TODO     SMALLINT
             ,@CANT_TODO      INT = 0

      SELECT @IDAPLIM_TODO = IDAPLIM
      FROM OPENJSON(@PARAMETROS)
      WITH (IDAPLIM INT '$.IDAPLIM')

      IF COALESCE(@IDAPLIM_TODO, 0) = 0
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'IDAPLIM es obligatorio'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT @CANT_ELEGIBLE = COUNT(1),
             @CANT_MARCADOS = SUM(CASE WHEN COALESCE(F.MARCA, 0) = 1 THEN 1 ELSE 0 END)
      FROM APLIMF F WITH (NOLOCK)
      INNER JOIN SER S WITH (NOLOCK) ON S.IDSERVICIO = F.IDSERVICIO
      WHERE F.IDAPLIM = @IDAPLIM_TODO
        AND COALESCE(S.POS, 1) = 0
        AND NULLIF(TRIM(S.PREFIJO), '') = NULLIF(TRIM(DBO.FNK_VALORVARIABLE('PREF_MED_NOPOS')), '')
        AND NOT (
           COALESCE(F.FACTURADA, 0) = 1
           AND NULLIF(TRIM(F.N_FACTURA), '') IS NOT NULL
        )

      IF COALESCE(@CANT_ELEGIBLE, 0) = 0
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No hay ítems No POS pendientes de facturar en este evento'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SET @MARCA_TODO = CASE WHEN COALESCE(@CANT_MARCADOS, 0) < @CANT_ELEGIBLE THEN 1 ELSE 0 END

      BEGIN TRY
         UPDATE F
         SET MARCA = @MARCA_TODO,
             USUARIOMARCA = CASE WHEN @MARCA_TODO = 1 THEN @USUARIO ELSE NULL END
         FROM APLIMF F
         INNER JOIN SER S ON S.IDSERVICIO = F.IDSERVICIO
         WHERE F.IDAPLIM = @IDAPLIM_TODO
           AND COALESCE(S.POS, 1) = 0
           AND NULLIF(TRIM(S.PREFIJO), '') = NULLIF(TRIM(DBO.FNK_VALORVARIABLE('PREF_MED_NOPOS')), '')
           AND NOT (
              COALESCE(F.FACTURADA, 0) = 1
              AND NULLIF(TRIM(F.N_FACTURA), '') IS NOT NULL
           )

         SET @CANT_TODO = @@ROWCOUNT
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH

      IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK, @MARCA_TODO AS MARCA, @CANT_TODO AS CANTIDAD, @IDAPLIM_TODO AS IDAPLIM
      RETURN
   END

   IF @METODO = 'CONTAR_MARCA_APLIMF_USU'
   BEGIN
      PRINT 'CONTAR_MARCA_APLIMF_USU'
      DECLARE @CANT_MARCA_USU INT

      SELECT @CANT_MARCA_USU = COUNT(1)
      FROM APLIMF F WITH (NOLOCK)
      INNER JOIN SER S WITH (NOLOCK) ON S.IDSERVICIO = F.IDSERVICIO
      WHERE COALESCE(F.MARCA, 0) = 1
        AND NULLIF(TRIM(F.USUARIOMARCA), '') = @USUARIO
        AND COALESCE(S.POS, 1) = 0
        AND NULLIF(TRIM(S.PREFIJO), '') = NULLIF(TRIM(DBO.FNK_VALORVARIABLE('PREF_MED_NOPOS')), '')

      SELECT 'OK' OK, COALESCE(@CANT_MARCA_USU, 0) AS CANTIDAD
      RETURN
   END

   IF @METODO = 'DESMARCAR_APLIMF_USU'
   BEGIN
      PRINT 'DESMARCAR_APLIMF_USU'
      DECLARE @CANT_DESMARCA INT = 0

      BEGIN TRY
         UPDATE APLIMF
         SET MARCA = 0,
             USUARIOMARCA = NULL
         WHERE COALESCE(MARCA, 0) = 1
           AND NULLIF(TRIM(USUARIOMARCA), '') = @USUARIO

         SET @CANT_DESMARCA = @@ROWCOUNT
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH

      IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK, @CANT_DESMARCA AS CANTIDAD
      RETURN
   END

   IF @METODO = 'GEN_AUT_NOPOS_APLIMF'
   BEGIN
      PRINT 'GEN_AUT_NOPOS_APLIMF'
      DECLARE @IDAPLIM         INT
             ,@IDMIPRES        VARCHAR(20)
             ,@PREFIJO         VARCHAR(6)
             ,@IDSEDE_AUT      VARCHAR(5)
             ,@CONSECUTIVOCIT  VARCHAR(20)
             ,@CONSECUTIVOHCA  VARCHAR(20)
             ,@AMBITO          VARCHAR(2)
             ,@CNSNOAUT        VARCHAR(20)
             ,@IDAUT_NUEVO     VARCHAR(20)
             ,@VALORTOTAL      DECIMAL(14,2)
             ,@CANT_ITEMS      INT
             ,@CNT_PREFIJOS    INT
             ,@CNT_MIPRES      INT
             ,@MIPRES_EXISTE   VARCHAR(20)
             ,@PREF_MED_NOPOS  VARCHAR(20)

      SELECT @IDAPLIM   = IDAPLIM
            ,@IDTERCERO = NULLIF(TRIM(IDTERCERO), '')
            ,@IDPLAN    = NULLIF(TRIM(IDPLAN), '')
            ,@IDMIPRES  = NULLIF(TRIM(IDMIPRES), '')
      FROM OPENJSON(@PARAMETROS)
      WITH (
         IDAPLIM   INT          '$.IDAPLIM',
         IDTERCERO VARCHAR(20)  '$.IDTERCERO',
         IDPLAN    VARCHAR(6)   '$.IDPLAN',
         IDMIPRES  VARCHAR(20)  '$.IDMIPRES'
      )

      IF COALESCE(@IDAPLIM, 0) = 0
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'IDAPLIM es obligatorio'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF COALESCE(@IDTERCERO, '') = '' OR COALESCE(@IDPLAN, '') = ''
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Debe indicar tercero y plan para generar la autorización'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF NOT EXISTS (SELECT 1 FROM APLIM WITH (NOLOCK) WHERE ID = @IDAPLIM)
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Evento APLIM no encontrado'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      ;WITH MARCADOS AS (
         SELECT F.ID, F.IDSERVICIO, F.CANTIDAD, F.IDAUT, F.IDMIPRESS, S.PREFIJO, S.AMBITO, S.POS
         FROM APLIMF F WITH (NOLOCK)
         INNER JOIN SER S WITH (NOLOCK) ON S.IDSERVICIO = F.IDSERVICIO
         WHERE F.IDAPLIM = @IDAPLIM
           AND COALESCE(F.MARCA, 0) = 1
           AND COALESCE(S.POS, 1) = 0
           AND NULLIF(TRIM(S.PREFIJO), '') = NULLIF(TRIM(DBO.FNK_VALORVARIABLE('PREF_MED_NOPOS')), '')
           AND NOT (
              COALESCE(NULLIF(TRIM(F.IDAUT), ''), '') <> ''
              AND EXISTS (
                 SELECT 1 FROM AUT AU WITH (NOLOCK)
                 WHERE AU.IDAUT = F.IDAUT
                   AND AU.ESTADO <> 'Anulada'
                   AND COALESCE(AU.FACTURADA, 0) = 0
              )
           )
      )
      SELECT @CANT_ITEMS = COUNT(1),
             @CNT_PREFIJOS = COUNT(DISTINCT NULLIF(TRIM(PREFIJO), '')),
             @CNT_MIPRES = COUNT(DISTINCT NULLIF(TRIM(IDMIPRESS), '')),
             @MIPRES_EXISTE = MAX(NULLIF(TRIM(IDMIPRESS), ''))
      FROM MARCADOS

      IF COALESCE(@CANT_ITEMS, 0) = 0
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'No hay ítems No POS marcados disponibles para autorizar en este evento'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF COALESCE(@CNT_PREFIJOS, 0) > 1
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Los ítems marcados tienen prefijos distintos; marque solo servicios del mismo prefijo'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF COALESCE(@CNT_MIPRES, 0) > 1 AND COALESCE(@IDMIPRES, '') = ''
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Los ítems marcados tienen MIPRES distintos; indique un MIPRES único o unifique los valores'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT @IDMIPRES = COALESCE(@IDMIPRES, @MIPRES_EXISTE)
      IF COALESCE(@IDMIPRES, '') = ''
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'MIPRES es obligatorio para facturar ítems No POS'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      -- MIPRES único: no puede existir en otra AUT vigente ni en otros APLIMF fuera del lote marcado
      IF EXISTS (
            SELECT 1
            FROM AUT AU WITH (NOLOCK)
            WHERE NULLIF(TRIM(AU.IDMIPRESS), '') = @IDMIPRES
              AND AU.ESTADO <> 'Anulada'
         )
         OR EXISTS (
            SELECT 1
            FROM APLIMF F WITH (NOLOCK)
            WHERE NULLIF(TRIM(F.IDMIPRESS), '') = @IDMIPRES
              AND NOT EXISTS (
                 SELECT 1
                 FROM APLIMF FM WITH (NOLOCK)
                 INNER JOIN SER SM WITH (NOLOCK) ON SM.IDSERVICIO = FM.IDSERVICIO
                 WHERE FM.ID = F.ID
                   AND FM.IDAPLIM = @IDAPLIM
                   AND COALESCE(FM.MARCA, 0) = 1
                   AND COALESCE(SM.POS, 1) = 0
              )
         )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'El MIPRES ' + @IDMIPRES + ' ya está registrado; debe ser un valor único'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      
      SELECT TOP 1
             @PREFIJO = S.PREFIJO
            ,@AMBITO = S.AMBITO
            ,@IDAFILIADO = A.IDAFILIADO
            ,@IDSEDE_AUT = COALESCE(NULLIF(TRIM(A.IDSEDE), ''), @SEDE, '01')
            ,@CONSECUTIVOCIT = M.CONSECUTIVOCIT
            ,@CONSECUTIVOHCA = M.CONSECUTIVOHCA
      FROM APLIMF F WITH (NOLOCK)
      INNER JOIN APLIM M WITH (NOLOCK) ON M.ID = F.IDAPLIM
      INNER JOIN APLI  A WITH (NOLOCK) ON A.ID = M.IDAPLI
      INNER JOIN SER   S WITH (NOLOCK) ON S.IDSERVICIO = F.IDSERVICIO
      WHERE F.IDAPLIM = @IDAPLIM
        AND COALESCE(F.MARCA, 0) = 1
        AND COALESCE(S.POS, 1) = 0
        AND NULLIF(TRIM(S.PREFIJO), '') = NULLIF(TRIM(DBO.FNK_VALORVARIABLE('PREF_MED_NOPOS')), '')
      ORDER BY F.ID

      -- Solo permite generar AUT si el prefijo del servicio coincide con PREF_MED_NOPOS
      SELECT @PREF_MED_NOPOS = NULLIF(TRIM(DBO.FNK_VALORVARIABLE('PREF_MED_NOPOS')), '')
      IF COALESCE(@PREF_MED_NOPOS, '') = ''
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Variable de sistema PREF_MED_NOPOS no está configurada'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF COALESCE(NULLIF(TRIM(@PREFIJO), ''), '') <> @PREF_MED_NOPOS
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'El prefijo del servicio (' + COALESCE(NULLIF(TRIM(@PREFIJO), ''), 'vacío')
              + ') no coincide con PREF_MED_NOPOS (' + @PREF_MED_NOPOS
              + '). No se genera autorización'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT @CNSNOAUT = NULL, @IDAUT_NUEVO = NULL, @VALORTOTAL = 0

      BEGIN TRY
         IF OBJECT_ID('tempdb..#NOPOS_MARCADOS') IS NOT NULL DROP TABLE #NOPOS_MARCADOS

         SELECT F.ID AS IDAPLIMF
               ,F.IDSERVICIO
               ,COALESCE(NULLIF(F.CANTIDAD, 0), 1) AS CANTIDAD
               ,S.PREFIJO
               ,CAST(0 AS DECIMAL(14,2)) AS VALOR
               ,CAST(0 AS DECIMAL(14,2)) AS VALORLINEA
               ,ROW_NUMBER() OVER (ORDER BY F.ID) AS NO_ITEM
         INTO #NOPOS_MARCADOS
         FROM APLIMF F
         INNER JOIN SER S ON S.IDSERVICIO = F.IDSERVICIO
         WHERE F.IDAPLIM = @IDAPLIM
           AND COALESCE(F.MARCA, 0) = 1
           AND COALESCE(S.POS, 1) = 0
           AND NULLIF(TRIM(S.PREFIJO), '') = NULLIF(TRIM(DBO.FNK_VALORVARIABLE('PREF_MED_NOPOS')), '')
           AND NOT (
              COALESCE(NULLIF(TRIM(F.IDAUT), ''), '') <> ''
              AND EXISTS (
                 SELECT 1 FROM AUT AU
                 WHERE AU.IDAUT = F.IDAUT
                   AND AU.ESTADO <> 'Anulada'
                   AND COALESCE(AU.FACTURADA, 0) = 0
              )
           )

         -- Tarifa del plan elegido en el diálogo MIPRES (PARAMETROS.IDPLAN), no el plan del filtro/evento
         UPDATE T
         SET VALOR = COALESCE(DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, T.IDSERVICIO, '', DBO.FNK_GETDATE(), 0), 0)
            ,VALORLINEA = COALESCE(DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, T.IDSERVICIO, '', DBO.FNK_GETDATE(), 0), 0) * T.CANTIDAD
         FROM #NOPOS_MARCADOS T

         IF EXISTS (SELECT 1 FROM #NOPOS_MARCADOS WHERE COALESCE(VALOR, 0) <= 0)
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Sin tarifa (FNK_VALORSERVICIO) para servicio ' + IDSERVICIO
            FROM #NOPOS_MARCADOS
            WHERE COALESCE(VALOR, 0) <= 0
         END
         ELSE
         BEGIN
            SELECT @VALORTOTAL = SUM(VALORLINEA), @CANT_ITEMS = COUNT(1) FROM #NOPOS_MARCADOS

            IF COALESCE(@VALORTOTAL, 0) <= 0
            BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT 'No se puede generar autorización ni factura con valor menor o igual a cero'
            END
            ELSE
            BEGIN
            EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE_AUT, @PREFIJO = '@AUTF', @LONGITUD = 8, @NVOCONSEC = @CNSNOAUT OUTPUT
            EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE_AUT, @PREFIJO = '@AUT',  @LONGITUD = 8, @NVOCONSEC = @IDAUT_NUEVO OUTPUT

            IF COALESCE(@CNSNOAUT, '') = '' OR COALESCE(@IDAUT_NUEVO, '') = ''
            BEGIN
               INSERT INTO @TBLERRORES(ERROR) SELECT 'No fue posible generar consecutivos AUT/NOAUT'
            END
            ELSE
            BEGIN
               -- AUTDIDSERVICIO es único por (IDSERVICIO, IDAUT): agrupar líneas APLIMF del mismo medicamento
               BEGIN TRAN

               INSERT INTO AUT (
                  IDAUT, NOAUT, FECHA, FECHASOL, IDAFILIADO, NUMCARNET, IDPLAN, IDSEDE, IDSEDEORIGEN,
                  TIPOAUTORIZACION, ESTADO, USUARIO, AMBITO, TIPOURGENCIA,
                  IDCONTRATANTE, FECHAGEN, IDTERCEROCA, CONSECUTIVOHCA, CONSECUTIVOCIT,
                  IDPLAN_AFI, IDTERCERO_AFI, FACTURABLE, FACTURADA, PROCEDENCIA, PREFIJO,
                  IDMIPRESS, VALORTOTAL, VALORCOPAGO, CNSMOV
               )
               SELECT @IDAUT_NUEVO, @CNSNOAUT, DBO.FNK_GETDATE(), DBO.FNK_GETDATE(), @IDAFILIADO, @IDAFILIADO,
                      @IDPLAN, @IDSEDE_AUT, @IDSEDE_AUT, 'Previa', 'Pendiente', @USUARIO, @AMBITO, 'NA',
                      @IDTERCERO, DBO.FNK_GETDATE(), @IDTERCERO, @CONSECUTIVOHCA, @CONSECUTIVOCIT,
                      @IDPLAN, @IDTERCERO, 1, 0, 'APLIM', @PREFIJO,
                      @IDMIPRES, @VALORTOTAL, 0, CONVERT(VARCHAR(20), @IDAPLIM)

               INSERT INTO AUTD (
                  IDAUT, NO_ITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALORCOPAGOCOSTO,
                  VALOREXCEDENTE, IDPLAN, AUTORIZADO, IDTERCEROCA, FACTURADA
               )
               SELECT @IDAUT_NUEVO
                     ,ROW_NUMBER() OVER (ORDER BY MIN(NO_ITEM))
                     ,IDSERVICIO
                     ,SUM(CANTIDAD)
                     ,MAX(VALOR)
                     ,0
                     ,0
                     ,SUM(VALORLINEA)
                     ,@IDPLAN
                     ,1
                     ,@IDTERCERO
                     ,0
               FROM #NOPOS_MARCADOS
               GROUP BY IDSERVICIO

               UPDATE F
               SET IDAUT = @IDAUT_NUEVO,
                   IDMIPRESS = @IDMIPRES,
                   MARCA = 0,
                   USUARIOMARCA = NULL
               FROM APLIMF F
               INNER JOIN #NOPOS_MARCADOS T ON T.IDAPLIMF = F.ID

               COMMIT TRAN
            END
            END
         END

         IF OBJECT_ID('tempdb..#NOPOS_MARCADOS') IS NOT NULL DROP TABLE #NOPOS_MARCADOS
      END TRY
      BEGIN CATCH
         IF @@TRANCOUNT > 0 ROLLBACK TRAN
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         IF OBJECT_ID('tempdb..#NOPOS_MARCADOS') IS NOT NULL DROP TABLE #NOPOS_MARCADOS
      END CATCH

      IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK, @IDAUT_NUEVO AS IDAUT, @CNSNOAUT AS NOAUT, @VALORTOTAL AS VALORTOTAL,
             @IDMIPRES AS IDMIPRES, @CANT_ITEMS AS CANTIDAD
      RETURN
   END

   IF @METODO = 'FACTURAR_NOPOS_APLIM'
   BEGIN
      PRINT 'FACTURAR_NOPOS_APLIM'
      DECLARE @IDAPLIM_FAC     INT
             ,@IDAUT_FAC       VARCHAR(20)
             ,@IDSEDE_FAC      VARCHAR(5)
             ,@FFACTURA_FAC    DATETIME
             ,@NIT_FAC         VARCHAR(20)
             ,@CANT_AUT        INT

      SELECT @IDAPLIM_FAC = IDAPLIM
            ,@IDTERCERO   = NULLIF(TRIM(IDTERCERO), '')
            ,@IDPLAN      = NULLIF(TRIM(IDPLAN), '')
            ,@IDSEDE_FAC  = NULLIF(TRIM(IDSEDE), '')
            ,@IDAUT_FAC   = NULLIF(TRIM(IDAUT), '')
            ,@FFACTURA_FAC = TRY_CONVERT(DATETIME, FFACTURA)
      FROM OPENJSON(@PARAMETROS)
      WITH (
         IDAPLIM   INT          '$.IDAPLIM',
         IDTERCERO VARCHAR(20)  '$.IDTERCERO',
         IDPLAN    VARCHAR(6)   '$.IDPLAN',
         IDSEDE    VARCHAR(5)   '$.IDSEDE',
         IDAUT     VARCHAR(20)  '$.IDAUT',
         FFACTURA  VARCHAR(30)  '$.FFACTURA'
      )

      IF COALESCE(@IDAPLIM_FAC, 0) = 0
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'IDAPLIM es obligatorio'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF COALESCE(@IDTERCERO, '') = '' OR COALESCE(@IDPLAN, '') = ''
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Debe indicar tercero y plan para facturar'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF @FFACTURA_FAC IS NULL
         SELECT @F_FACTURA = DBO.FNK_GETDATE()
      ELSE
         SELECT @F_FACTURA = @FFACTURA_FAC

      SELECT @COMPANIA = '01', @NIT_FAC = NIT
      FROM TER WHERE IDTERCERO = DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')

      IF COALESCE(@NIT_FAC, '') = ''
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Tercero Facturador No Identificado, Revise Configuración Terceros'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF NOT EXISTS (
         SELECT 1 FROM PRI
         WHERE FECHA_INI <= @F_FACTURA AND FECHA_FIN + 1 > @F_FACTURA AND COALESCE(CERRADO, 0) = 0
      )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Periodo Contable No Existe o no Esta Abierto'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF COALESCE(@IDSEDE_FAC, '') = '' OR UPPER(@IDSEDE_FAC) = 'TODAS'
      BEGIN
         SELECT @IDSEDE_FAC = COALESCE(NULLIF(TRIM(A.IDSEDE), ''), @SEDE, '01')
         FROM APLIM M WITH (NOLOCK)
         INNER JOIN APLI A WITH (NOLOCK) ON A.ID = M.IDAPLI
         WHERE M.ID = @IDAPLIM_FAC
      END

      IF DBO.FNK_VALORVARIABLE('FACTSEDE') = 'SI' AND (COALESCE(@IDSEDE_FAC, '') = '' OR UPPER(@IDSEDE_FAC) = 'TODAS')
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Debe indicar una sede concreta (FACTSEDE=SI)'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      IF OBJECT_ID('tempdb..#NOPOS_AUTS') IS NOT NULL DROP TABLE #NOPOS_AUTS

      SELECT DISTINCT F.IDAUT
      INTO #NOPOS_AUTS
      FROM APLIMF F WITH (NOLOCK)
      INNER JOIN SER S WITH (NOLOCK) ON S.IDSERVICIO = F.IDSERVICIO
      INNER JOIN AUT A WITH (NOLOCK) ON A.IDAUT = F.IDAUT
      WHERE F.IDAPLIM = @IDAPLIM_FAC
        AND COALESCE(S.POS, 1) = 0
        AND COALESCE(F.FACTURADA, 0) = 0
        AND NULLIF(TRIM(F.IDAUT), '') IS NOT NULL
        AND A.ESTADO <> 'Anulada'
        AND COALESCE(A.FACTURADA, 0) = 0
        AND COALESCE(A.FACTURABLE, 0) = 1
        AND COALESCE(A.VALORTOTAL, 0) > 0
        AND (
              (COALESCE(@IDAUT_FAC, '') <> '' AND F.IDAUT = @IDAUT_FAC)
           OR (COALESCE(@IDAUT_FAC, '') = '' AND COALESCE(F.MARCA, 0) = 1)
        )

      SELECT @CANT_AUT = COUNT(1) FROM #NOPOS_AUTS
      IF COALESCE(@CANT_AUT, 0) = 0
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No hay autorizaciones pendientes de facturar para este evento (marque ítems con AUT o genere AUT primero)'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         IF OBJECT_ID('tempdb..#NOPOS_AUTS') IS NOT NULL DROP TABLE #NOPOS_AUTS
         RETURN
      END

      BEGIN TRY
         DECLARE @NOAUT_FAC VARCHAR(16)

         DECLARE CUR_NOPOS_FAC CURSOR LOCAL FAST_FORWARD FOR
         SELECT A.NOAUT
         FROM #NOPOS_AUTS T
         INNER JOIN AUT A ON A.IDAUT = T.IDAUT
         WHERE NULLIF(TRIM(A.NOAUT), '') IS NOT NULL

         OPEN CUR_NOPOS_FAC
         FETCH NEXT FROM CUR_NOPOS_FAC INTO @NOAUT_FAC
         WHILE @@FETCH_STATUS = 0
         BEGIN
            EXEC DBO.SPK_FACTURACE_N
               @NOAUT_FAC,
               @NIT_FAC,
               @COMPANIA,
               @IDSEDE_FAC,
               @USUARIO,
               '', '', '', '', '',
               'CE',
               @IDTERCERO,
               'FALSE',
               @IDPLAN,
               @F_FACTURA,
               NULL

            FETCH NEXT FROM CUR_NOPOS_FAC INTO @NOAUT_FAC
         END
         CLOSE CUR_NOPOS_FAC
         DEALLOCATE CUR_NOPOS_FAC

         UPDATE F
         SET FACTURADA = 1,
             N_FACTURA = A.N_FACTURA,
             MARCA = 0,
             USUARIOMARCA = NULL
         FROM APLIMF F
         INNER JOIN #NOPOS_AUTS T ON T.IDAUT = F.IDAUT
         INNER JOIN AUT A ON A.IDAUT = F.IDAUT
         WHERE F.IDAPLIM = @IDAPLIM_FAC
           AND COALESCE(A.FACTURADA, 0) = 1
           AND NULLIF(TRIM(A.N_FACTURA), '') IS NOT NULL

         IF NOT EXISTS (
            SELECT 1
            FROM APLIMF F
            INNER JOIN #NOPOS_AUTS T ON T.IDAUT = F.IDAUT
            WHERE F.IDAPLIM = @IDAPLIM_FAC
              AND COALESCE(F.FACTURADA, 0) = 1
              AND NULLIF(TRIM(F.N_FACTURA), '') IS NOT NULL
         )
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'La facturación no dejó N_FACTURA en las autorizaciones; revise configuración / errores de facturación'
         END
      END TRY
      BEGIN CATCH
         IF CURSOR_STATUS('local', 'CUR_NOPOS_FAC') >= 0
         BEGIN
            CLOSE CUR_NOPOS_FAC
            DEALLOCATE CUR_NOPOS_FAC
         END
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH

      IF OBJECT_ID('tempdb..#NOPOS_AUTS') IS NOT NULL DROP TABLE #NOPOS_AUTS

      IF (SELECT COUNT(*) FROM @TBLERRORES) > 0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK, @CANT_AUT AS CANTIDAD, @IDAPLIM_FAC AS IDAPLIM
      RETURN
   END
END

